### ISSUE TITLE
真心建议>订阅>列表下一页规则>能支持内容规则的下一页规则啦

### ISSUE THREAD

**Issue by 1274003856** [gedoor/legado#1000]
现在的>订阅>列表下一页规则>只能支持>分类URL>源url下一页   希望能增加对>内容内容下一页>的支持啦    很多网站(比如视频站)~它的内容规则下一页规则是可以使用 >列表下一页规则>实现的啦   我知道我以前提的那个 需要在>内容规则>下面添加>内容下一页规则>不友好，但是我现在提的这个可以了啊   比如内容规则下一页   http://v.cn/yf/3.html   在内容规则 写上  http://v.cn/yf/{{page}}.html  然后直接让  列表下一页规则 {{page}}>来解析是可以实现的啊  这样可以省了写js啊，主要是无数小白不会写这样的js啊。

**Comment by gedoor** [comment]
好的
