### ISSUE TITLE
[Feature Request] web方式刷新最新章节

### ISSUE THREAD

**Issue by liangweipeng** [gedoor/legado#1001]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 目前提供的方式只能获取已有章节，要更新最新的只能打开手机手动刷新获取（可能是我没弄懂）

### 期望实现方式（阅读应该如何实现该功能）
> 获取书籍章节列表（URL = http://127.0.0.1:1234/getChapterList?url=xxx ，Method = GET）能一起刷新吗？或者单独的

### 附加信息（其他的与功能相关的附加信息）
> 我是旧手机装阅读，然后通过web看。web好用，就是新章要打开手机刷新。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>感谢！！！

**Comment by gedoor** [comment]
好的,我加个API
