### ISSUE TITLE
[BUG] 反转目录的问题

### ISSUE THREAD

**Issue by JinkerLeong** [gedoor/legado#1003]
### 机型（如Redmi K30 Pro）
>Poco x3 nfc

### 安卓版本（如Android 7.1.1）
>Android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.052320

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>国外

### 问题描述（简要描述发生的问题）
>反转目录后，选择中的目录章节出错，如我选最新倒数第三章，反转后会选成最早第三章。除此之外，在点下一章后会去第二章。

**Comment by gedoor** [comment]
反转目录是真的反转了,你目录正常就不要点了

**Comment by JinkerLeong** [comment]
反转是反转了。但正常目录时有300章，我选着299章，反转目录后选着的章节并没有跟着改变，会导致其选择第2章（章节内容还是在299章）。也因为这个原因，点下一个章节会去第1章。

**Comment by gedoor** [comment]
我看看
