### ISSUE TITLE
上下滑动会触发页面左右切换，希望优化一下灵敏度[BUG] 

### ISSUE THREAD

**Issue by qigithub** [gedoor/legado#1004]
### 机型（如Redmi K30 Pro）
>三星s10

### 安卓版本（如Android 7.1.1）
>11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>   有viewpager的页面上下滑动比较容易触发左右页面切换，希望修改一下灵敏度

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
已从viewPager2改回ViewPager
