### ISSUE TITLE
希望订阅的内容规则--能支持对同一域名下的所有网址生效啦--这样就不会出现第一页无广告-剩下的页面都有广告了

### ISSUE THREAD

**Issue by dalaola** [gedoor/legado#1005]
就是阅读--订阅--内容规则--能支持对同一域名下的所有页面生效啦
这样就可以--打开一个页面---无广告--打开这个页面的其他页面---也可以无广告啦
现在需要写  JS才能实现---真心的对新手太不又好了---看不懂这个JS怎么写的。

就像你的订阅--添加的夜间代码--就是可以对 内容规则所有页面有效的啊。

比如
内容规则能对这个页面生效   https://bwl87.com/play/25337-1-1/
能否可以强制对他下面的  
https://bwl87.com/play/25337-1-2/
https://bwl87.com/play/25337-1-3/
https://bwl87.com/play/25337-1-4/
https://bwl87.com/play/25337-1-5/
生效啊

订阅源  http://yck.mumuceo.com/yuedu/rssyuan/json/id/895.json

阅读的订阅--内容规则--只能对一页生效--实在很不友好啊。

**Comment by dalaola** [comment]
这样就可以做到  -使用订阅看书---不显示广告啦。。现在只能第一页没广告-剩下的页面都有广告。。。

**Comment by gedoor** [comment]
我看看

**Comment by Celeter** [comment]
> 这样就可以做到 -使用订阅看书---不显示广告啦。。现在只能第一页没广告-剩下的页面都有广告。。。

这样会出现有的规则不匹配不到，然后显示空白吗

**Comment by Easonzero** [comment]
似乎最新版本仍然没有这个功能

**Comment by dalaola** [comment]
你好。本邮箱因为站长长期不登陆，所以。侵权视频请电脑版访问网站右侧悬浮 在线客服 提交链接和标题侵权视频请手机版访问网站右侧悬浮 客服 提交链接和标题给你照成的不便敬请谅解啦。
