### ISSUE TITLE
[Feature Request] 增加调试发现的功能

### ISSUE THREAD

**Issue by TinyZzh** [gedoor/legado#1012]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在web服务中无法调试[发现]功能。对书源制作有比较大的帮助

### 期望实现方式（阅读应该如何实现该功能）
> 增加调试发现的功能。可以根据参数进行翻页调试。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 
![image](https://user-images.githubusercontent.com/5763397/119766064-efcee000-bee6-11eb-817e-aee321202bf7.png)

**Comment by Celeter** [comment]
已经有了，调试发现的方法和在app上是一样的
