### ISSUE TITLE
[Feature Request] 安全性相关，导出备份时，不导出 webdev 相关配置

### ISSUE THREAD

**Issue by ptable-1** [gedoor/legado#1016]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 当前版本备份时，会导出明文的 webdev 密码。这是个密码泄露风险。  
对于需要从 webdev 备份恢复的场景下，本身就需要使用者先完成 webdev 配置，才能恢复备份，导出 webdev 配置的行为毫无意义，且徒增风险。  
仅有从本地恢复备份的情况下，备份 webdev 配置才显得方便。  
但考量到密码泄露的风险，我认为无论何种情况，webdev 的配置都不得导出，而应由使用者人工输入。  

### 期望实现方式（阅读应该如何实现该功能）
>

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
可以

**Comment by yjvv1** [comment]
> 可以

可以把权限里面的允许通讯录取消掉么？，阅读不需要打电话吧？
