### ISSUE TITLE
[Feature Request] 最近上班划水的时候发现好像没有自动翻页功能，希望添加一个自动翻页功能

### ISSUE THREAD

**Issue by qq1036828060** [gedoor/legado#1018]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 自动翻页功能

### 期望实现方式（阅读应该如何实现该功能）
> 可参考其他阅读软件的自动翻页功能

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by zmn001125** [comment]
点击屏幕中间。悬浮按钮里的第二个按钮

**Comment by qq1036828060** [comment]
多谢，我说我记得以前用过啊
