### ISSUE TITLE
[BUG] 3.21.052622版本，书源较多时，点击列表后返回时，列表activity崩溃，卡顿后直接退回书架

### ISSUE THREAD

**Issue by richwxd** [gedoor/legado#1021]
### 机型（如Redmi K30 Pro）
>Oppo Reno Ace

### 安卓版本（如Android 7.1.1）
> Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.052622

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 联通和移动 双卡 + 联通宽带

### 问题描述（简要描述发生的问题）
> 最新版，搜索“末世”，然后在进程中点击一本书，停留一秒，然后退出来，应该回到原来的搜索结果页面，但是好像是当前activity崩溃了，退到了书架页面

### 使用书源（填写URL或者JSON）
> 全部都加上了

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 

1. 搜索“末世”
2. 在显示列表中选择一项，此时进程还未结束(感觉查询时应该排序处理，此处分页显示，避免查询一致执行)
3. 此时显示的应该是一本书，停留一秒，然后返回上一页，应该回到原来的搜索结果页面
4. 但是好像是当前activity崩溃了，而且发生了卡顿，然后直接退到了书架页面

### 日志提交（问题截图或者日志）
> 这个问题只要书源稍多一点，就很容易复现。是用户体验问题，不容易截图。

**Comment by 52fisher** [comment]
![image](https://user-images.githubusercontent.com/32198215/120983166-065d1d00-c7ac-11eb-90f6-cceff56dbf31.png)
搜索已有意向结果的时候，你应该先点击右下角的停止按钮停止搜索
