### ISSUE TITLE
我想要一个功能《操作历史》

### ISSUE THREAD

**Issue by wqx1919** [gedoor/legado#1022]
昨天2021年6月4日的时候，误删了一本书，忘记书名了，现在找不到了。我去坚果云备份里面查看操作历史，也没找到。（可能没备份到）
我的版本是3.21.052622
手机是redmi k40 miui 12.5.3
![image](https://user-images.githubusercontent.com/64262398/120888622-e43c9100-c62b-11eb-96f0-ad8e56654cbd.png)
只找到以上的lastUseTime，但是我不知道这个是什么进制，能帮帮我吗？

**Comment by zmn001125** [comment]
不是有阅读记录？

**Comment by wqx1919** [comment]
你好，是有阅读记录，但是只有俩种选择，我也因为那部小说是刚看的，就误删了，所以不知道笑啥名字，也不知道到看了多久
emmmm然后找坚果云备份
找到里面searchHistory.json
然后里面没找到那个时间段的小说[流泪]，那一本小说还是灵异小说
这是我勉强找到的解决方案，但是还是没找到





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月5日(周六) 晚上8:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] 我想要一个功能《操作历史》 (#1022)




 
不是有阅读记录？

**Comment by wqx1919** [comment]
你好，是有阅读记录，但是只有俩种选择，我也因为那部小说是刚看的，就误删了，所以不知道叫啥名字，也不知道到看了多久
emmmm
然后找坚果云备份
找到里面searchHistory.json
然后里面没找到那个时间段的小说[流泪]，那一本小说还是灵异小说
这是我勉强找到的解决方案，但是还是没找到
![A7867128@5DCE9250 0372BB60 jpg_recompress](https://user-images.githubusercontent.com/64262398/120892803-92ebcc00-c642-11eb-93a9-0e641281c57d.jpg)
![image](https://user-images.githubusercontent.com/64262398/120892850-be6eb680-c642-11eb-80ce-3f0ffd7da2f3.png)
![image](https://user-images.githubusercontent.com/64262398/120892858-c3336a80-c642-11eb-8871-3823d2333a02.png)

**Comment by szlk** [comment]
> 昨天2021年6月4日的时候，误删了一本书，忘记书名了，现在找不到了。我去坚果云备份里面查看操作历史，也没找到。（可能没备份到）
> 我的版本是3.21.052622
> 手机是redmi k40 miui 12.5.3
> ![image](https://user-images.githubusercontent.com/64262398/120888622-e43c9100-c62b-11eb-96f0-ad8e56654cbd.png)
> 只找到以上的lastUseTime，但是我不知道这个是什么进制，能帮帮我吗？

这个进制叫 时间戳（毫秒级），可以百度时间戳在线转换，可以得到具体时间 如：2021-04-03 23:34:12:561
