### ISSUE TITLE
新棉花糖 获取目录 修改

### ISSUE THREAD

**Issue by nmweizi** [gedoor/legado#1035]
获取目录 chapterlist修改为 chapterlist_klfsd，可以正确获取目录。

**Comment by nmweizi** [comment]
正文下一页URL规则添加
id.pt_next_@tag.a@href

**Comment by 52fisher** [comment]
书源规则直接修改后上传源仓库哈，这里不接受书源的反馈

**Comment by nmweizi** [comment]
意思是提个pull ，还是在哪上传？

**Comment by gedoor** [comment]
书源自己修改
