### ISSUE TITLE
[Feature Request] 优先读取webdav里的阅读记录

### ISSUE THREAD

**Issue by letterk** [gedoor/legado#1036]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
有一台墨水屏的A5当阅读器在家看书, 平时出门用另一台主力机阅读, 目前同步比较麻烦, 需要切换手机的时候一台去备份, 一台去恢复. 有时候忘了这一步骤会把两边的记录全搞乱. 
想要更好的同步需要点开书的时候, 优先使用在线记录而不是本地记录
### 期望实现方式（阅读应该如何实现该功能）
> 
在设置了WebDAV以后, 可选优先使用在线阅读记录
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
切换到后台的时候会自动上传进度

**Comment by letterk** [comment]
我知道切换后台会自动上传记录, 上传一直都是很及时的
但上传了记录不代表另一台手机能第一时间用新记录
我说的问题是在多台手机上, 就会出现上传和下载的流程不协调
单台手机肯定没这问题, 多台手机就有

**Comment by gedoor** [comment]
打开阅读界面是会下载记录,如果不退出阅读界面我也不知道什么时候需要下载记录啊

**Comment by letterk** [comment]
是启动app的时候会下载记录, 还是说打开书籍会下载记录?

**Comment by gedoor** [comment]
都会

**Comment by letterk** [comment]
那我知道怎么同步记录会混乱了. 我那个墨水屏只当阅读器, 基本上一直开着阅读, 怪不得切换手机的时候会冲突
