### ISSUE TITLE
[Feature Request] 添加web快捷开关

### ISSUE THREAD

**Issue by ifwlzs** [gedoor/legado#1037]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 我经常用web服务，但是每次都要打开软件>我的>web服务，我希望能在通知栏添加个快捷开关，用于控制web服务的开启和关闭

### 期望实现方式（阅读应该如何实现该功能）
> 实现效果类似于在通知栏进行个人热点的开关的开启关闭

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 红框中添加web服务的快捷开关
![image](https://user-images.githubusercontent.com/49548316/121480133-554dc100-c9fd-11eb-9139-5e123b5a97ef.png)

**Comment by zh690908189** [comment]
web服务在锁屏状态下可能造成应用因为电源管理被自动关闭，开启web服务最好能够检查下应用后台运行权限

**Comment by ifwlzs** [comment]
> web服务在锁屏状态下可能造成应用因为电源管理被自动关闭，开启web服务最好能够检查下应用后台运行权限

emmm 我不是说他自动关闭，这个问题我没遇到过，我得意思是说，在通知栏上加个web服务的开关，这样不用进入软件里面开关web服务了

**Comment by gedoor** [comment]
下版本就有这个功能了
