### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by we22101** [gedoor/legado#1038]
### 机型（如Redmi K30 Pro）
>SONY x1 iii

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.060618

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>点击区域设置屏幕点击区域不对，只有中间才行两边的无反应

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开电子书后按手机屏幕，下一页的那里的区域无反应，只有竖的中间的那一行有反应

### 日志提交（问题截图或者日志）
>

**Comment by we22101** [comment]
打开电子书后按手机屏幕，下一页的那里的区域无反应，只有竖的中间的那一行有反应

**Comment by ag2s20150909** [comment]
把全面屏手势优化关了
