### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by we22101** [gedoor/legado#1039]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 点击区域设置里加上 ，上一个文件或者下一个文件的设定，就是在当前文件的目录里打开上一个文件或者下一个文件

### 期望实现方式（阅读应该如何实现该功能）
>点击区域设置， 就在选择操作里实多几个任务选项 上一个文件或者下一个文件

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by we22101** [comment]
点击区域设置里加上 ，上一个文件或者下一个文件的设定，就是在当前文件的目录里打开上一个文件或者下一个文件

**Comment by 52fisher** [comment]
点击区域是针对当前书籍在界面的不同区域设置不同的功能的，要切换文件你应该先将文件加入书架，在书架中进行选择。
