### ISSUE TITLE
rss订阅源结果的部分元素的关闭标签被吃了

### ISSUE THREAD

**Issue by M17764017422** [gedoor/legado#104]
http://www.stats.gov.cn/tjsj/zxfb/rss.xml
因为默认的处理方法只能获取
@xpath:description的内容，但这个标签只是个概要没有完整的内容。于是就尝试着用
@xpath:自己写规则结果发现部分元素的关闭标签不见了，导致一个关键元素@xpath:link/text()无法获取。

**Comment by M17764017422** [comment]
相关的截图已经发到作者邮箱了

**Comment by M17764017422** [comment]
关注一下这个bug，目前最新版本编译后问题还在
调试显示<link>的关闭标签</link>不见了
<link>
http://www.stats.gov.cn/tjsj/zxfb/202002/t20200217_1726707.html
</link>
<source>国家统计局</source>

**Comment by gedoor** [comment]
新版本应该解决了

**Comment by M17764017422** [comment]
刚才安装了，问题还在。
看来需要仔细调试跟踪一下

**Comment by Celeter** [comment]
像link,source等标签在html中是支持自闭合的，在xml中是不支持的，xpath的解析库使用了jsoup，在jsoup会把xml格式化成html，这样像link,source等标签就会缺少关闭标签，这个（https://try.jsoup.org/）是jsoup的在线测试。
想解决此问题可以去https://github.com/zhegexiaohuozi/JsoupXpath反馈

**Comment by Celeter** [comment]
暂行的方法:
{
  "customOrder": 0,
  "enableJs": false,
  "enabled": true,
  "loadWithBaseUrl": false,
  "ruleArticles": "//item",
  "ruleContent": "",
  "ruleDescription": "",
  "ruleLink": "@xpath:./text()##\\s.*",
  "rulePubDate": "//pubTime/text()",
  "ruleTitle": "//title/text()",
  "sourceIcon": "",
  "sourceName": "最新",
  "sourceUrl": "http://www.stats.gov.cn/tjsj/zxfb/rss.xml"
}
