### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by we22101** [gedoor/legado#1040]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 能在本地打开文件里支持ZIP格式的文件

### 期望实现方式（阅读应该如何实现该功能）
> 打开文件里支持ZIP格式的文件

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by nobk** [comment]
如果支持了.zip格式，那是不是.rar格式也一起支持了啊，两个知轩藏书网站，一个用的.zip打包，另一个则是.rar的。
