### ISSUE TITLE
[BUG] 因为系统放大字体和界面，确认按钮被挤消失了

### ISSUE THREAD

**Issue by hsj1992** [gedoor/legado#1066]
### 机型（如Redmi K30 Pro）
>realme X2

### 安卓版本（如Android 7.1.1）
>Android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.060618

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>系统设置了“字体大小”为“超大”，“显示大小”为“大”，结果就是如图所示，看不见导入书源时候的确认按钮了。

### 使用书源（填写URL或者JSON）
>

任何书源
```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
系统设置如图所示，然后在导入书源时如图所示。

### 日志提交（问题截图或者日志）
>
![mmexport1623813338761](https://user-images.githubusercontent.com/4816005/122153470-a80ff880-ce95-11eb-9e5a-a449ee165612.jpg)
![mmexport1623813994599](https://user-images.githubusercontent.com/4816005/122153499-b8c06e80-ce95-11eb-9c42-d86be412c181.jpg)

**Comment by gedoor** [comment]
这个啊,我看看

**Comment by gedoor** [comment]
已解决
