### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yuncloud99** [gedoor/legado#1069]
### 机型（如Redmi K30 Pro）
>
红米note9pro

### 安卓版本（如Android 7.1.1）
>
11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.21.060618
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通4g

### 问题描述（简要描述发生的问题）
>
看本地书，使用搜索功能搜索书名，那个横杠一直动，不出结果。

老哥，还有是否能增加页脚的功能设置和页眉右侧的功能设置啊？

### 使用书源（填写URL或者JSON）
>

无
```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by yuncloud99** [comment]
我还有几个功能上的建议
1，看书的时候，页脚上的那条线可以设置取消么？
2.添加本地书籍时候本地书籍是否可以增加搜索功能和按照名称排序功能呢？

**Comment by 52fisher** [comment]
> 看本地书，使用搜索功能搜索书名
直接在搜索栏输入书名，不要点击搜索按钮，如果书架上有对应书籍，在下面的选项中会出现 **书架**
> 页脚上的那条线可以设置取消么
界面 -- 边距 --显示分隔线

**Comment by yuncloud99** [comment]
> > 看本地书，使用搜索功能搜索书名
> 
> 直接在搜索栏输入书名，不要点击搜索按钮，如果书架上有对应书籍，在下面的选项中会出现 **书架**
> 

我是想直接在文件夹里搜，太多书了都扔书架里看着太累赘。

> > 页脚上的那条线可以设置取消么
> 
> 界面 -- 边距 --显示分隔线


老哥，这个只能取消页眉上的分割线，取消不了页脚上的分割线啊。

**Comment by gedoor** [comment]
页脚分隔线页有个设置,找找

**Comment by yuncloud99** [comment]
> 页脚分隔线页有个设置,找找

![image](https://user-images.githubusercontent.com/86056024/123753772-cc83c000-d8ec-11eb-82a0-f05612cdcd3f.png)
老哥是说这个么，下面那个三角点上没反应，已经升级到0629版了。

**Comment by gedoor** [comment]
屏幕转一下,你这个显示不全

**Comment by yuncloud99** [comment]
> 屏幕转一下,你这个显示不全

好吧，这也行啊。。。。
