### ISSUE TITLE
下载导出可以添加替换规则整理文本内容吗

### ISSUE THREAD

**Issue by luchao900** [gedoor/legado#107]
新的测试版本添加了导出功能，非常强大。在导出时，合并的都是直接下载的文本，里面乱码的没进行替换。如果可以在导出前添加复选框，勾选是否使用规则替换，再进行导出，那样就更好了。

再个，谢谢大神开发出的这么强大的软件哦

**Comment by ChouE** [comment]
今天我也发现了这个问题，替换净化是在导出时是没效果的
但书源净化是有作用的

**Comment by 52fisher** [comment]
新版已经支持该功能，感谢建议[查看更新](https://github.com/gedoor/legado/commit/2aae76a8b4dd4e71385dd4f71fe238b54e336343)。如有疑问可继续提问.
