### ISSUE TITLE
[BUG] MIUI升级12.5.2后开源阅读读取本地书籍权限不足, 需修改书籍路径

### ISSUE THREAD

**Issue by KaiSanPao** [gedoor/legado#1070]
### 机型（如Redmi K30 Pro）
>Redmi K30 Pro

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.060618

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>无

### 问题描述（简要描述发生的问题）
>MIUI升级12.5.2后开源阅读读取本地书籍权限不足, 需修改书籍路径

### 使用书源（填写URL或者JSON）
>无

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>我的MIUI由12.0.xx(忘了是具体多少)升级为12.5.2后, 权限有所更新, 文件选择器似乎也变了, 

然后开源阅读读取本地txt权限不足, 重新给权限也不行, 就试着删掉重新添加, 发现本地书籍地址由
```
/storage/emulated/0/Books/《灭运图录》.txt
```
变为
```
content://com.android.externalstorage.documents/tree/primary%3ABooks/document/primary%3ABooks%2F%E3%80%8A%E7%81%AD%E8%BF%90%E5%9B%BE%E5%BD%95%E3%80%8B.txt
```
即
```
content://com.android.externalstorage.documents/tree/primary:Books/document/primary:Books/《灭运图录》.txt
```
重新添加后就正常了

然而我本地有很多txt, 还有书签等等记录, 不可能全删了再加吧? 

因为没找到直接修改本地txt地址的功能(换源好像只能选在线的, 而点击来源出现编辑书源似乎又不是), 因为怕丢失书签等记录, 后通过备份->修改bookshelf.json内书籍的bookUrl->再恢复, 临时处理了几本当前正在看的本地txt...

现只希望能给个解决办法, 比如直接在app内更新本地书籍地址的方法, 又或者是判断老地址不行尝试读取为这种新地址试试???或者其他我不知道的方法...

**Comment by gedoor** [comment]
android 11修改了文件权限,我也没办法

**Comment by KaiSanPao** [comment]
@gedoor 本地书籍的地址未发生变化, 那么地址是可以转换的, 
我的建议是: 
1. 在读取旧地址格式无权限的情况下, 转换成新地址的格式读取试试. 我修改配置手动进行转换是行得通的, 就是数量多, 还得转码拼接, 太麻烦了...如果因为各种机型和安卓版本不好做适配来判断, 那么就按下面的来
2. 在书籍信息编辑那, 针对本地书籍, 参考封面地址的修改, 添加个本地书籍地址, 让读者自己修改???

**Comment by gedoor** [comment]
好的
