### ISSUE TITLE
[Feature Request] 订阅源阅读的夜间模式

### ISSUE THREAD

**Issue by Ancientwood** [gedoor/legado#1074]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 订阅源阅读时的夜间模式自动切换

### 期望实现方式（阅读应该如何实现该功能）
> 在编辑订阅源样式中增加css媒体查询 `prefers-color-scheme: dark` 的支持

### 附加信息（其他的与功能相关的附加信息）
> 如兼容性原因无法支持此媒体查询，是否能通过 `js` 对时间的判断改变 `css` 来实现

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
![image](https://user-images.githubusercontent.com/18499887/123215691-569de400-d4fb-11eb-839a-b2211700002f.png)

**Comment by gedoor** [comment]
新版本添加
