### ISSUE TITLE
[Feature Request] 打算基于legado版本书源制作一款ios平台开源的小说阅读软件，请求能够将书源解析部分分离

### ISSUE THREAD

**Issue by cernard** [gedoor/legado#1075]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 打算基于legado版本书源制作一款ios平台完全免费并且开源的小说阅读软件，在阅读了legado的源码后，分离了jsoup、jsonpath、xpath解析代码，但是正则和js部分与android耦合的比较紧，我对原生安卓不太了解，特别是用kotlin之后……希望作者在有空时能够将其分离一下，感谢！

### 期望实现方式（阅读应该如何实现该功能）
> 分离成独立的kt或java文件，与安卓依赖解耦

**Comment by RinOrz** [comment]
不如用 flutter 让社区共同维护?

**Comment by cernard** [comment]
> 不如用 flutter 让社区共同维护?

确实用的是flutter，已经完成大部分ui，社区可以一起维护，还没传github，等初版功能出来传。不过flutter新手，布局但写的有点拉胯，但ui还是比较有信心的。内嵌了优书网作为社区和书城，在优书网点击阅读会和flutter交互使用legado书源进行阅读。

**Comment by RinOrz** [comment]
> 确实用的是flutter，已经完成大部分ui，社区可以一起维护，还没传github，等初版功能出来传。不过flutter新手，布局代码写的有点拉胯，但ui还是比较有信心的。内嵌了优书网作为社区和书城，在优书网点击阅读会和flutter交互使用legado书源进行阅读。

听起来很不错，开源了大佬弹我一下。太喜欢安卓端的阅读了，无奈手机主力ios

**Comment by ca1e** [comment]
@kaich 你们可以交流一下，确实核心规则感觉可以独立出来，这样大家精力不会浪费在兼容上

**Comment by kaich** [comment]
@ca1e 如果是项目初期可以改改，现在这个阶段，阅读规则不适合大改，要保持之前版本的兼容性，还要保持对安卓平台的强支持性，难！

**Comment by ca1e** [comment]
@kaich 并不是说要改规则，而是把解析引擎的实现单独分离出来维护成lib，这需要legado的配合实现。现在应该是有原生app调用flutter的lib之类的需求，可以调研下demo

**Comment by ca1e** [comment]
@gedoor 飞哥看下把规则引擎（书源、订阅等）拆分成依赖lib是否可行

**Comment by huage2580** [comment]
我去年实现过一个版本，后来发现flutter或者说dart在解析上的局限太大，没有维护过了
https://github.com/huage2580/yuedu_hd  
解析库源码在这里，可以参考，dart在这方面很难做，我最近在考虑重新实现解析库  
https://github.com/huage2580/reader_parser

**Comment by buzai** [comment]
规则太麻烦了，ui部分不是问题，规则是这个软件的核心

**Comment by aooiuu** [comment]
我在写一个JS版解析库。不过目前没有按照 legado 规则实现。 

目前很不完善, 感兴趣的话可以加入一起写两下

https://github.com/aooiuu/any-reader
