### ISSUE TITLE
[Feature Request] 建议提供搜书线程自选功能

### ISSUE THREAD

**Issue by xhy1640** [gedoor/legado#1078]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 书源一多，搜索速度很慢，希望可以自行选择并发数量

### 期望实现方式（阅读应该如何实现该功能）
> 在设置中提供选项

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by shutaozhenzhen** [comment]
其他设置——更新和搜索线程数
你是在说这个吗？
