### ISSUE TITLE
iOS版源阅读请求 阅读记录 的扩展

### ISSUE THREAD

**Issue by kaich** [gedoor/legado#1080]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 现在的阅读记录的功能和字段，仅仅显示时间，感觉有点鸡肋。 是否考虑扩展一下？ 

我在写iOS版 「源阅读」的时候，进行了扩展，但是这样，字段解构就没法进行兼容了。准备上线了，目前除了阅读记录，基本上全部兼容了，因此问问大佬有准备扩展阅读记录这部分功能么，可以在上线之前做一波兼容？

### 期望实现方式（阅读应该如何实现该功能）
例如「源阅读」的目前显示是这样的：

> 在 iPhone 8P 设备 『张三的手机』上，阅读章节『第一章』28 页 ~ 章节 『第五章』32页。
>
> 阅读了10分钟37秒，功阅读了20000字。

### 附加信息（其他的与功能相关的附加信息）
> 基本上以上信息可以满足绝大多数情况了，如果有需要我会把字段附上！

期待回复

**Comment by yangguo88858** [comment]
自己不开源，找别人开源解决问题，这也太恶心了吧

**Comment by kaich** [comment]
@yangguo88858  开不开源和提需求有什么关系？

难道这个被作者肯定的需求也是错？
https://github.com/gedoor/legado/issues/1307

**Comment by yangguo88858** [comment]
> @yangguo88858 开不开源和提需求有什么关系？
> 
> 难道这个被作者肯定的需求也是错？ #1307

脸都不要了？ 强蹭安卓阅读流量。  还让安卓放你的链接，真牛皮。

**Comment by kaich** [comment]
@yangguo88858 这是作者的事情！ 首先我感谢阅读作者大佬链接了『源阅读』好久。
 如果我是做了个产品，不准备出其它各种平台的。我也会欢迎第三方开发者的开发，链接。例如V2ex论坛，到处都是第三方开发者开发的V2ex的App，论坛作者也欢迎。
 记住，并非每个人都和你一样狭隘！另外做人要有点素质！本不欲与你这种争论，但这里是反馈问题和需求的地方，请不要在这里影响整个issue模块的干净。
