### ISSUE TITLE
[Feature Request] 优化本地文件的阅读体验

### ISSUE THREAD

**Issue by MIKIMIKA404** [gedoor/legado#1081]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 本地导入EPUB文件后，只能象TXT一样阅读，希望可以实现点击文中目录链接进行跳转，点击文中注释弹出弹窗

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 希望添加对chm文件的阅读支持

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
![Screenshot_2021-06-27-19-52-10-459_com flyersoft moonreaderp](https://user-images.githubusercontent.com/52788142/123543876-38e2b000-d783-11eb-94be-3a4b0f3805c4.jpg)
![Screenshot_2021-06-27-19-52-35-496_com flyersoft moonreaderp](https://user-images.githubusercontent.com/52788142/123543882-40a25480-d783-11eb-970a-b351e9a0b2be.jpg)

**Comment by gedoor** [comment]
这个比较麻烦,等有空吧
