### ISSUE TITLE
听书不支持m4a格式的音频文件，导致很多听书书源可以用，但是听不了

### ISSUE THREAD

**Issue by jerry321** [gedoor/legado#1082]
### 机型（如Redmi K30 Pro）
>荣耀v10

### 安卓版本（如Android 7.1.1）
>Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.062211

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
我看看
