### ISSUE TITLE
[Feature Request] 希望优化一下正文加载速度。

### ISSUE THREAD

**Issue by YumikoAzu** [gedoor/legado#1085]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
书源没问题，浏览原网站速度也很快，就是阅读正文章节(这个章节分页只有四页)加载超过一分钟。
### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 52fisher** [comment]
超过一分钟那绝对是源的问题，你可以把阅读理解为一个网页转码的浏览器. 源没写好就会影响加载速度

**Comment by YumikoAzu** [comment]
> 超过一分钟那绝对是源的问题，你可以把阅读理解为一个网页转码的浏览器. 源没写好就会影响加载速度

不是源问题，因为正文规则就是一个节点的text而儿。而且原网站访问速度很快的，正文加载出来才四页。
