### ISSUE TITLE
[BUG] The color of the book cover is rendered incorrectly.

### ISSUE THREAD

**Issue by LingLuoEtherealling** [gedoor/legado#1087]
### 机型
Mi 10 Pro , Snapdragon 865
>Android R (11)
>MIUI 12.6 Weekly

### 阅读Legdao版本
>legado_app_version_3.21.062920（Newest)

### 网络环境
>China Mobile/China Unicom
>network condition:good

### 使用书源（填写URL或者JSON）
>https://www.imiaobige.com/novel/134890.html

### 问题描述
>After clearing the application data, it was found that the color rendering was incorrect when the book cover was updated.

###步骤复现
>This bug is a sporadic bug and it is difficult to reproduce.

### 有关图片
>
![IMG_20210630_232126](https://user-images.githubusercontent.com/73578955/123991371-4014f280-d9fd-11eb-95c7-be68b88a3040.jpg)
![IMG_20210630_232058](https://user-images.githubusercontent.com/73578955/123991378-42774c80-d9fd-11eb-9a82-fd080a02bcf5.jpg)
![IMG_20210630_232206](https://user-images.githubusercontent.com/73578955/123991384-43a87980-d9fd-11eb-9c6a-0169d3b3ac9b.jpg)

No useful logs are available.

**Comment by 52fisher** [comment]
MIUI在最近的版本中更新了深色模式，出现这种问题先在通知栏中关闭深色模式，再打开即可.
