### ISSUE TITLE
[BUG 修复代码提交] WEB 阅读书架(新潮) 修复 Chapter.vue 阅读页 keyup 重复监听 bug

### ISSUE THREAD

**Issue by FanchangWang** [gedoor/legado#1088]
WEB 阅读书架(新潮)  阅读页监听 `keyup` 上下左右方向键有重复监听的 bug，重复从书架进入阅读页会导致多次监听 `keyup` 事件，现对此 bug 进行修复。

由于原 [Celeter/web-yuedu3](https://github.com/Celeter/web-yuedu3) 代码库已不存在，无法提交 `pr`，故在此 Issue 提交对应修复代码，希望能合并一下，谢谢。

修复代码详见此 `commit`

https://github.com/FanchangWang/web-yuedu3/commit/ec64a19caa7b29a4e2fab6226625a64574203985

**Comment by gedoor** [comment]
ok

**Comment by gedoor** [comment]
已改
