### ISSUE TITLE
[Feature Request] 阅读支持书源的订阅吗？

### ISSUE THREAD

**Issue by maysoft** [gedoor/legado#1089]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by FanchangWang** [comment]
本来就支持啊，订阅里面的 规则订阅，你添加一个书源类型的订阅地址就行了
