### ISSUE TITLE
下载的文件都是nb纯文件格式，可以换成HTML格式吗

### ISSUE THREAD

**Issue by luchao900** [gedoor/legado#109]
问题描述：现在的3.0和以前的2.0比较类似，都不能显示图片，后台存储的文件格式限制了这个功能的延伸。

方案提供：可以把采集下载的内容保存到HTML文件中，title存储标题，div   p   img标签用来存储文本内容以及图片链接，可以的话还可以添加是否下载图片选项，将图片离线保存到img子文件夹中

**Comment by M17764017422** [comment]
图片可以直接用
<img src=“data:image/gif;base64/>

**Comment by M17764017422** [comment]
内容规则也不要现在的只支持@text改成可以支持@HTML直接获取网页片段
