### ISSUE TITLE
[Feature Request] 朗读可与可以多几种声音选择？

### ISSUE THREAD

**Issue by fcleecx** [gedoor/legado#1092]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 好比如QQ阅读有不同的声音选择， 男性的女性的。

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 最好可以有附带感情的，不过这个应该不容易实现。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by celetor** [comment]
请自行配置语音api实现
