### ISSUE TITLE
3.0的最底部导航栏不能变色

### ISSUE THREAD

**Issue by luchao900** [gedoor/legado#110]
问题描述：3.0版本的阅读，底部导航栏不能随内容页面颜色的变化而改变，当前2.0版本的沉浸式状态栏用起来比3.0在视觉效果上看起来舒服多了。而且一到晚上关灯，手机下面白色的状态栏配合夜间模式，看起来非常刺眼。望改进哦，亲👍👍👍

**Comment by chrisxvin** [comment]
3.0 的导航栏，看着很突兀。其他都很美好。
作者加油~！

**Comment by 52fisher** [comment]
已支持
