### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sunsunzhe** [gedoor/legado#1107]
### 机型（如Redmi K30 Pro）
>

lg v60
### 安卓版本（如Android 7.1.1）
>

10
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.21.062920
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

加载漫画加载不出来，手机卡死
### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
可能书源问题
