### ISSUE TITLE
[Feature Request] 希望能加上app内部升级功能

### ISSUE THREAD

**Issue by WangJie0822** [gedoor/legado#1109]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 能在app内直接下载最新版本进行升级

### 期望实现方式（阅读应该如何实现该功能）
> github api有提供获取最新release信息以及release中的资源下载路径，可以依此实现

### 附加信息（其他的与功能相关的附加信息）
> 每次打开浏览器下载太麻烦，而且github经常性访问不了，可以在gitee也维护一个项目，git可以同时向两个不同的仓库提交代码的

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by ag2s20150909** [comment]
{
  "articleStyle": 0,
  "customOrder": -5,
  "enableJs": true,
  "enabled": true,
  "loadWithBaseUrl": true,
  "ruleArticles": "@js:var javaImport = new JavaImporter();\njavaImport.importPackage(\n    Packages.java.util\n);\nwith(javaImport){\n function ss(t,k,fid,uid){\n var h=new HashMap();\nh.put('referer','https://kunfei.lanzoui.com/')\nh.put('Accept-Language','zh-CN,zh;q=0.9')\nh.put('content-type','application/x-www-form-urlencoded')\n\n var bd ='lx=2&fid='+fid+'&uid='+uid+'&pg=1&rep=0&t='+t+'&k='+k+'&up=1'\njava.log(bd)\n var js1=java.post('https://kunfei.lanzoui.com/filemoreajax.php',String(bd),h).body();\njava.log(js1);\nreturn js1\n }\n}\n\nresult=result.replace(/[\\r\\n]/g,' ');\n//java.log(result)\nvar m=result.match(/ '(\\d+)';.*?var i.*? = '(.*?)';.*?pgs/);\nvar m2=result.match(/'fid':(\\d+),.*?'uid':'(\\d+)',/)\nvar t=m[1];\nvar k=m[2]\nvar fid=m2[1]\nvar uid=m2[2]\ndata=[]\njava.log(k)\njava.log(m2)\nvar j=JSON.parse(ss(t,k,fid,uid))['text']\nfor(i=0;i<j.length;i++){\ndata.push(JSON.stringify(j[i]))\n}\ndata",
  "ruleContent": "",
  "ruleDescription": "",
  "ruleImage": "@js:\"https://kunfei.lanzoui.com/images/filetype/\"+java.getString(\"$.icon\")+\".gif\"",
  "ruleLink": "@js:'https://kunfei.lanzoui.com/tp/'+java.getString('$.id')",
  "rulePubDate": "@js:java.getString('$.time')+'  '+java.getString('$.size')",
  "ruleTitle": "$.name_all",
  "singleUrl": false,
  "sortUrl": "阅读2.0::https://kunfei.lanzoui.com/b0f7pt4hi\n阅读3.0::https://kunfei.lanzoui.com/b0f7pt4ja\n阅读3测试::https://kunfei.lanzoui.com/b0f810h4b",
  "sourceGroup": "下载,兰奏",
  "sourceIcon": "http://ku.mumuceo.com/static/images/applogo/yuedu.png",
  "sourceName": "阅读兰奏下载",
  "sourceUrl": "https://kunfei.lanzoui.com/b0f810h4b"
}
