### ISSUE TITLE
[BUG] ChapterProvider Error

### ISSUE THREAD

**Issue by kk441123** [gedoor/legado#1113]
### 机型（如Redmi K30 Pro）
>Samsung Note20 Ultra

### 安卓版本（如Android 7.1.1）
>Android11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>2.21.071017

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>在某些书的某些章节（不确定）会跳出这个，但从源网站看是正常的，换源之后也一样

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
[>]
![log](https://user-images.githubusercontent.com/27012170/125165988-0d70b400-e1cc-11eb-8fa6-5204fc26adbe.jpg)

**Comment by celetor** [comment]
把自动换行关了就行

**Comment by gedoor** [comment]
好像卸载重装也能解决,记得先备份
