### ISSUE TITLE
[Feature Request] Cronet版与app版有什么区别，能否带个说明

### ISSUE THREAD

**Issue by JiuZhouWorlds** [gedoor/legado#1131]
### 功能描述（请清晰的、详细的描述你想要的功能）
> ronet版与app版有什么区别，推荐用哪个？

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
网络访问库不同

**Comment by celetor** [comment]
@ag2s20150909
