### ISSUE TITLE
[Feature Request] 书源去重

### ISSUE THREAD

**Issue by lwsgh** [gedoor/legado#1136]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望可以添加书源去重的功能, 如具有相同域名的书源可以筛选出来

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by celetor** [comment]
域名相同会覆盖
