### ISSUE TITLE
[Feature Request] 增加WiFi传书功能

### ISSUE THREAD

**Issue by JiuZhouWorlds** [gedoor/legado#1151]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 现在从电脑传书需要打开文件管理ftp服务复制进去，再从legado导入，工作流比较繁琐。既然有web服务能在网页看书，那不如再增加个WiFi传书功能吧

### 期望实现方式（阅读应该如何实现该功能）
> 打开WiFi传书开关，在电脑浏览器里打开相应网页，从文件管理器里拖拽或在网页打开批量选择文件，自动上传到legado里并加入书架。可参考多看阅读的WiFi传书功能。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的

**Comment by joyfun** [comment]
![image](https://user-images.githubusercontent.com/470369/156696383-6c8f7077-9e87-4188-ba94-5150eb50819f.png)
最新版3.22.030322 提示信息不在界面显示 
    {errorMsg: "没有设置书籍保存位置!", isSuccess: false}
最好界面加提示 提示设置app书籍保存位置
