### ISSUE TITLE
[Feature Request] ZIP正文获取的内容是gbk的显示乱码

### ISSUE THREAD

**Issue by haxc** [gedoor/legado#1152]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
书源：http://yck.mumuceo.com/yuedu/shuyuan/yuan/id/4498.html

获取得到的正文内容是gb2312的，但是显示乱码，要怎么转换成UTF-8？

### 期望实现方式（阅读应该如何实现该功能）
> 
最好直接显示正确内容

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
![Screenshot_2021-07-21-10-59-00-08_b46d61021eb8d6931849578836530a01](https://user-images.githubusercontent.com/2002770/126424034-a895b367-5c2b-41ff-bdf0-cf507d3f9b78.jpg)

**Comment by gedoor** [comment]
ok,我看一下

**Comment by gedoor** [comment]
已解决,可以先下载共存最新版本

**Comment by haxc** [comment]
> 已解决,可以先下载共存最新版本

谢谢大大
