### ISSUE TITLE
[本地txt书籍获取章节目录名称错误]

### ISSUE THREAD

**Issue by qwz160** [gedoor/legado#1153]
### 机型（如Redmi K30 Pro）
>
Redmi K30 Pro

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
本地txt书籍，没有获取到对应章节目录名的名称，而是app自定义目录章节名称（错误的目录章节名称，如第一章1，第二章2）

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by zmn001125** [comment]
点换源按钮换目录正则

**Comment by 52fisher** [comment]
正文界面 - 右上角帮助文档，有一个目录规则说明。点进去先看一下帮助文档。
如果还有问题可以通过帮助文档里面的邮箱给我发邮件
