### ISSUE TITLE
[Feature Request] 希望增加自动搜索本地书籍功能

### ISSUE THREAD

**Issue by qwz160** [gedoor/legado#1154]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 手机上有一些txt书籍，该app，不能自动搜索出手机上的书籍，需要查找到对应的目录才行，建议，添加本地书籍时，有个自动扫描本地书籍的功能

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by zmn001125** [comment]
右上角三点，智能扫描
