### ISSUE TITLE
选择文字选中区域 段首有多余的部分

### ISSUE THREAD

**Issue by YumikoAzu** [gedoor/legado#116]
![IMG_9206](https://user-images.githubusercontent.com/13196251/75251638-f8cd8f00-5815-11ea-9e52-cdc2c9823f85.PNG)
![IMG_9205](https://user-images.githubusercontent.com/13196251/75251641-fb2fe900-5815-11ea-9293-98354a1989b3.PNG)
2.0版本选中部分段首是没有的,3.0则有。还有反向交换选择会没效果,就是右选择头往左选择越过左选择头。

**Comment by gedoor** [comment]
段首有多余的部分,这不是bug,就这样设计的, 3.0的选择比2.0好没看出来吗
