### ISSUE TITLE
[BUG] 发现页URL被当做详情页解析了

### ISSUE THREAD

**Issue by lq975436833** [gedoor/legado#1160]
### 机型（如Redmi K30 Pro）
> Redmi Note 9 Pro

### 安卓版本（如Android 7.1.1）
> 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.072310

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
> 发现页URL被当做详情页解析了

### 使用书源（填写URL或者JSON）
> ::https://m.qidian.com/category/detail?gender=male&orderBy=&catId=21&subCatId=8

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 打开手机版 web 服务，在PC端调试书源

### 日志提交（问题截图或者日志）
>
![image](https://user-images.githubusercontent.com/49943048/126759839-e4cc0861-d3b6-4fc8-b3cd-b0c86b4b0977.png)

**Comment by zmn001125** [comment]
你把书源发出来，这应该是规则写的有问题

**Comment by zmn001125** [comment]
> 你把书源发出来，这应该是规则写的有问题

书籍列表没有获取到就会当做详情页链接

**Comment by lq975436833** [comment]
`{
    "bookSourceUrl": "https://m.qidian.com",
    "bookSourceType": "0",
    "bookSourceName": "💰起点中文网-手机版💰",
    "bookSourceGroup": "🇨🇳正版,🌟精品🌟",
    "bookSourceComment": "",
    "loginUrl": "https://passport.qidian.com",
    "bookUrlPattern": "https?://m\\.qidian\\.com.*",
    "header": "{\n  \"User-Agent\": \"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1 Edg/91.0.4472.164\"\n}",
    "searchUrl": "https://m.qidian.com/majax/search/list?kw={{key}}",
    "exploreUrl": "玄幻::/category/21\n东方玄幻::/category/detail?catId=21&subCatId=8&gender=male\n异世大陆::/category/detail?catId=21&subCatId=73&gender=male\n王朝争霸::/category/detail?catId=21&subCatId=58&gender=male\n高武世界::/category/detail?catId=21&subCatId=78&gender=male\n奇幻::/category/1\n现代魔法::/category/detail?catId=1&subCatId=38&gender=male\n剑与魔法::/category/detail?catId=1&subCatId=62&gender=male\n史诗奇幻::/category/detail?catId=1&subCatId=201&gender=male\n黑暗幻想::/category/detail?catId=1&subCatId=202&gender=male\n历史神话::/category/detail?catId=1&subCatId=20092&gender=male\n另类幻想::/category/detail?catId=1&subCatId=20093&gender=male\n武侠::/category/2\n传统武侠::/category/detail?catId=2&subCatId=5&gender=male\n武侠幻想::/category/detail?catId=2&subCatId=30&gender=male\n国术无双::/category/detail?catId=2&subCatId=206&gender=male\n古武未来::/category/detail?catId=2&subCatId=20099&gender=male\n武侠同人::/category/detail?catId=2&subCatId=20100&gender=male\n仙侠::/category/22\n修真文明::/category/detail?catId=22&subCatId=18&gender=male\n幻想修仙::/category/detail?catId=22&subCatId=44&gender=male\n现代修真::/category/detail?catId=22&subCatId=64&gender=male\n神话修真::/category/detail?catId=22&subCatId=207&gender=male\n古典仙侠::/category/detail?catId=22&subCatId=20101&gender=male\n都市::/category/4\n爱情婚姻::/category/detail?catId=4&subCatId=6&gender=male\n都市生活::/category/detail?catId=4&subCatId=12&gender=male\n都市异能::/category/detail?catId=4&subCatId=16&gender=male\n异术超能::/category/detail?catId=4&subCatId=74&gender=male\n青春校园::/category/detail?catId=4&subCatId=130&gender=male\n娱乐明星::/category/detail?catId=4&subCatId=151&gender=male\n商战职场::/category/detail?catId=4&subCatId=153&gender=male\n现实::/category/15\n社会乡土::/category/detail?catId=15&subCatId=153&gender=male\n生活时尚::/category/detail?catId=15&subCatId=153&gender=male\n文学艺术::/category/detail?catId=15&subCatId=153&gender=male\n成功励志::/category/detail?catId=15&subCatId=153&gender=male\n青春文学::/category/detail?catId=15&subCatId=153&gender=male\n爱情婚姻::/category/detail?catId=15&subCatId=153&gender=male\n现实百态::/category/detail?catId=15&subCatId=153&gender=male\n军事::/category/6\n军旅生涯::/category/detail?catId=6&subCatId=54&gender=male\n军事战争::/category/detail?catId=6&subCatId=65&gender=male\n战争幻想::/category/detail?catId=6&subCatId=80&gender=male\n抗战烽火::/category/detail?catId=6&subCatId=230&gender=male\n谍战特工::/category/detail?catId=6&subCatId=231&gender=male\n历史::/category/5\n架空历史::/category/detail?catId=5&subCatId=22&gender=male\n秦汉三国::/category/detail?catId=5&subCatId=48&gender=male\n上古先秦::/category/detail?catId=5&subCatId=220&gender=male\n历史传记::/category/detail?catId=5&subCatId=32&gender=male\n两晋隋唐::/category/detail?catId=5&subCatId=222&gender=male\n五代十国::/category/detail?catId=5&subCatId=223&gender=male\n两宋元明::/category/detail?catId=5&subCatId=224&gender=male\n清史民国::/category/detail?catId=5&subCatId=225&gender=male\n外国历史::/category/detail?catId=5&subCatId=226&gender=male\n民间传说::/category/detail?catId=5&subCatId=20094&gender=male\n游戏::/category/7\n电子竞技::/category/detail?catId=7&subCatId=7&gender=male\n虚拟网游::/category/detail?catId=7&subCatId=70&gender=male\n游戏异界::/category/detail?catId=7&subCatId=240&gender=male\n游戏系统::/category/detail?catId=7&subCatId=20102&gender=male\n游戏主播::/category/detail?catId=7&subCatId=20103&gender=male\n体育::/category/8\n篮球运动::/category/detail?catId=8&subCatId=28&gender=male\n体育赛事::/category/detail?catId=8&subCatId=55&gender=male\n足球运动::/category/detail?catId=8&subCatId=82&gender=male\n科幻::/category/9\n古武机甲::/category/detail?catId=9&subCatId=21&gender=male\n未来世界::/category/detail?catId=9&subCatId=25&gender=male\n星际文明::/category/detail?catId=9&subCatId=68&gender=male\n超级科技::/category/detail?catId=9&subCatId=250&gender=male\n时空穿梭::/category/detail?catId=9&subCatId=251&gender=male\n进化变异::/category/detail?catId=9&subCatId=252&gender=male\n末世危机::/category/detail?catId=9&subCatId=253&gender=male\n悬疑::/category/10\n诡秘悬疑::/category/detail?catId=10&subCatId=26&gender=male\n奇妙世界::/category/detail?catId=10&subCatId=35&gender=male\n侦探推理::/category/detail?catId=10&subCatId=57&gender=male\n探险生存::/category/detail?catId=10&subCatId=260&gender=male\n古今传奇::/category/detail?catId=10&subCatId=20095&gender=male\n轻小说::/category/12\n原生幻想::/category/detail?catId=12&subCatId=60&gender=male\n现代幻想::/category/detail?catId=12&subCatId=10&gender=male\n衍生同人::/category/detail?catId=12&subCatId=281&gender=male\n搞笑吐槽::/category/detail?catId=12&subCatId=282&gender=male\n恋爱日常::/category/detail?catId=12&subCatId=66&gender=male\n短篇::/category/20076\n诗歌散文::/category/detail?catId=20076&subCatId=20097&gender=male\n人物传记::/category/detail?catId=20076&subCatId=20098&gender=male\n影视剧本::/category/detail?catId=20076&subCatId=20075&gender=male\n评论文集::/category/detail?catId=20076&subCatId=20077&gender=male\n生活随笔::/category/detail?catId=20076&subCatId=20078&gender=male\n美文游记::/category/detail?catId=20076&subCatId=20079&gender=male\n短篇小说::/category/detail?catId=20076&subCatId=20096&gender=male",
    "enabled": true,
    "enabledExplore": true,
    "weight": 0,
    "customOrder": 3,
    "lastUpdateTime": 1627349341665,
    "ruleSearch": {
        "bookList": "@js:\nvar json = JSON.parse(result);\n    json.data.bookInfo.records.slice(1).map(ch=>({\n        bAuth: ch.bAuth,\n        bName: ch.bName,\n        bid: ch.bid,\n        bookType: ch.bookType,\n        cat: ch.cat,\n        catId: ch.catId,\n        cbid: ch.cbid,\n        cid: ch.cid,\n        clickCnt: ch.clickCnt,\n        cnt: ch.cnt,\n        desc: ch.desc,\n        imgUrl: ch.imgUrl,\n        isInShelf: ch.isInShelf,\n        isPub: ch.isPub,\n        isVip: ch.isVip,\n        lastChapterName: ch.lastChapterName,\n        lastUpdateTime: ch.lastUpdateTime,\n        recomendCnt: ch.recomendCnt,\n        signStatus: ch.signStatus,\n        state: ch.state,\n        subCateId: ch.subCateId,\n        subCateName: ch.subCateName,\n        subCateUrl: ch.subCateUrl,\n        updateTime: ch.updateTime\n    }));",
        "name": "bName",
        "author": "bAuth",
        "kind": "cat && subCateName && state && signStatus",
        "wordCount": "cnt",
        "lastChapter": "lastChapterName",
        "intro": "@js: lastUpdateTime+\"\\n\"+desc",
        "coverUrl": "@js:\"https:\"+imgUrl",
        "bookUrl": "@js:\"https://m.qidian.com/book/\"+bid"
    },
    "ruleExplore": {
        "bookList": "ol#books-@a",
        "name": "class.book-title@text",
        "author": "class.book-author@text",
        "kind": "class.gray@text && class.red@text",
        "wordCount": "class.blue@text",
        "intro": "class.book-desc@text",
        "coverUrl": "img@src##//(.*)##https://$1###",
        "bookUrl": "a@href"
    },
    "ruleBookInfo": {
        "name": "h2.book-title@text",
        "author": "div.book-rand-a@a@text##作者：(.*)级别##$1###",
        "kind": "class.book-score@tag.p.0@text&&class.book-score@tag.p.1@text##(连载|完本)##$1###",
        "wordCount": "p:contains(字)@textNodes##连载|完本|\\n",
        "lastChapter": "div.book-meta-r@text##：更新状态：(.*)·连载至(.*)##$2 ·$1",
        "intro": "<js>\n'　　★最近更新:'+result.match(/class=\"gray ell\" [^>]+>([^<]+)<span/)[1]+'★\\n'+result.match(/textarea hidden>([\\W\\w]+?)<\\/texta/)[1].replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,\"'\")\n</js>",
        "coverUrl": "img@src##//(.*)##https://$1###",
        "tocUrl": "##data-book-id=\"([^\"]+)##https://druid.if.qidian.com/argus/api/v1/chapterlist/chapterlist?bookId=$1###"
    },
    "ruleToc": {
        "chapterList": "<js>\n    var json=JSON.parse(result).Data;\n    var bid=json.BookId;\n    var base=\"https://m.qidian.com/book/\"+bid+\"/\";\n    json.Chapters.slice(1).map(ch=>({\n        title:ch.N,\n        link:base+ch.C,\n        vip:ch.V,\n        time:java.timeFormat(ch.T)\n    }))\n</js>",
        "chapterName": "title",
        "chapterUrl": "link",
        "isVip": "vip",
        "updateTime": "time"
    },
    "ruleContent": {
        "content": "section.jsChapterWrapper@p@html"
    }
}`

![image](https://user-images.githubusercontent.com/49943048/127080503-2ffd5c9b-ea1f-4d8b-964e-30a0842b458d.png)

**Comment by zmn001125** [comment]
> `{ "bookSourceUrl": "https://m.qidian.com", "bookSourceType": "0", "bookSourceName": "💰起点中文网-手机版💰", "bookSourceGroup": "🇨🇳正版,🌟精品🌟", "bookSourceComment": "", "loginUrl": "https://passport.qidian.com", "bookUrlPattern": "https?://m\\.qidian\\.com.*", "header": "{\n \"User-Agent\": \"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1 Edg/91.0.4472.164\"\n}", "searchUrl": "https://m.qidian.com/majax/search/list?kw={{key}}", "exploreUrl": "玄幻::/category/21\n东方玄幻::/category/detail?catId=21&subCatId=8&gender=male\n异世大陆::/category/detail?catId=21&subCatId=73&gender=male\n王朝争霸::/category/detail?catId=21&subCatId=58&gender=male\n高武世界::/category/detail?catId=21&subCatId=78&gender=male\n奇幻::/category/1\n现代魔法::/category/detail?catId=1&subCatId=38&gender=male\n剑与魔法::/category/detail?catId=1&subCatId=62&gender=male\n史诗奇幻::/category/detail?catId=1&subCatId=201&gender=male\n黑暗幻想::/category/detail?catId=1&subCatId=202&gender=male\n历史神话::/category/detail?catId=1&subCatId=20092&gender=male\n另类幻想::/category/detail?catId=1&subCatId=20093&gender=male\n武侠::/category/2\n传统武侠::/category/detail?catId=2&subCatId=5&gender=male\n武侠幻想::/category/detail?catId=2&subCatId=30&gender=male\n国术无双::/category/detail?catId=2&subCatId=206&gender=male\n古武未来::/category/detail?catId=2&subCatId=20099&gender=male\n武侠同人::/category/detail?catId=2&subCatId=20100&gender=male\n仙侠::/category/22\n修真文明::/category/detail?catId=22&subCatId=18&gender=male\n幻想修仙::/category/detail?catId=22&subCatId=44&gender=male\n现代修真::/category/detail?catId=22&subCatId=64&gender=male\n神话修真::/category/detail?catId=22&subCatId=207&gender=male\n古典仙侠::/category/detail?catId=22&subCatId=20101&gender=male\n都市::/category/4\n爱情婚姻::/category/detail?catId=4&subCatId=6&gender=male\n都市生活::/category/detail?catId=4&subCatId=12&gender=male\n都市异能::/category/detail?catId=4&subCatId=16&gender=male\n异术超能::/category/detail?catId=4&subCatId=74&gender=male\n青春校园::/category/detail?catId=4&subCatId=130&gender=male\n娱乐明星::/category/detail?catId=4&subCatId=151&gender=male\n商战职场::/category/detail?catId=4&subCatId=153&gender=male\n现实::/category/15\n社会乡土::/category/detail?catId=15&subCatId=153&gender=male\n生活时尚::/category/detail?catId=15&subCatId=153&gender=male\n文学艺术::/category/detail?catId=15&subCatId=153&gender=male\n成功励志::/category/detail?catId=15&subCatId=153&gender=male\n青春文学::/category/detail?catId=15&subCatId=153&gender=male\n爱情婚姻::/category/detail?catId=15&subCatId=153&gender=male\n现实百态::/category/detail?catId=15&subCatId=153&gender=male\n军事::/category/6\n军旅生涯::/category/detail?catId=6&subCatId=54&gender=male\n军事战争::/category/detail?catId=6&subCatId=65&gender=male\n战争幻想::/category/detail?catId=6&subCatId=80&gender=male\n抗战烽火::/category/detail?catId=6&subCatId=230&gender=male\n谍战特工::/category/detail?catId=6&subCatId=231&gender=male\n历史::/category/5\n架空历史::/category/detail?catId=5&subCatId=22&gender=male\n秦汉三国::/category/detail?catId=5&subCatId=48&gender=male\n上古先秦::/category/detail?catId=5&subCatId=220&gender=male\n历史传记::/category/detail?catId=5&subCatId=32&gender=male\n两晋隋唐::/category/detail?catId=5&subCatId=222&gender=male\n五代十国::/category/detail?catId=5&subCatId=223&gender=male\n两宋元明::/category/detail?catId=5&subCatId=224&gender=male\n清史民国::/category/detail?catId=5&subCatId=225&gender=male\n外国历史::/category/detail?catId=5&subCatId=226&gender=male\n民间传说::/category/detail?catId=5&subCatId=20094&gender=male\n游戏::/category/7\n电子竞技::/category/detail?catId=7&subCatId=7&gender=male\n虚拟网游::/category/detail?catId=7&subCatId=70&gender=male\n游戏异界::/category/detail?catId=7&subCatId=240&gender=male\n游戏系统::/category/detail?catId=7&subCatId=20102&gender=male\n游戏主播::/category/detail?catId=7&subCatId=20103&gender=male\n体育::/category/8\n篮球运动::/category/detail?catId=8&subCatId=28&gender=male\n体育赛事::/category/detail?catId=8&subCatId=55&gender=male\n足球运动::/category/detail?catId=8&subCatId=82&gender=male\n科幻::/category/9\n古武机甲::/category/detail?catId=9&subCatId=21&gender=male\n未来世界::/category/detail?catId=9&subCatId=25&gender=male\n星际文明::/category/detail?catId=9&subCatId=68&gender=male\n超级科技::/category/detail?catId=9&subCatId=250&gender=male\n时空穿梭::/category/detail?catId=9&subCatId=251&gender=male\n进化变异::/category/detail?catId=9&subCatId=252&gender=male\n末世危机::/category/detail?catId=9&subCatId=253&gender=male\n悬疑::/category/10\n诡秘悬疑::/category/detail?catId=10&subCatId=26&gender=male\n奇妙世界::/category/detail?catId=10&subCatId=35&gender=male\n侦探推理::/category/detail?catId=10&subCatId=57&gender=male\n探险生存::/category/detail?catId=10&subCatId=260&gender=male\n古今传奇::/category/detail?catId=10&subCatId=20095&gender=male\n轻小说::/category/12\n原生幻想::/category/detail?catId=12&subCatId=60&gender=male\n现代幻想::/category/detail?catId=12&subCatId=10&gender=male\n衍生同人::/category/detail?catId=12&subCatId=281&gender=male\n搞笑吐槽::/category/detail?catId=12&subCatId=282&gender=male\n恋爱日常::/category/detail?catId=12&subCatId=66&gender=male\n短篇::/category/20076\n诗歌散文::/category/detail?catId=20076&subCatId=20097&gender=male\n人物传记::/category/detail?catId=20076&subCatId=20098&gender=male\n影视剧本::/category/detail?catId=20076&subCatId=20075&gender=male\n评论文集::/category/detail?catId=20076&subCatId=20077&gender=male\n生活随笔::/category/detail?catId=20076&subCatId=20078&gender=male\n美文游记::/category/detail?catId=20076&subCatId=20079&gender=male\n短篇小说::/category/detail?catId=20076&subCatId=20096&gender=male", "enabled": true, "enabledExplore": true, "weight": 0, "customOrder": 3, "lastUpdateTime": 1627349341665, "ruleSearch": { "bookList": "@js:\nvar json = JSON.parse(result);\n json.data.bookInfo.records.slice(1).map(ch=>({\n bAuth: ch.bAuth,\n bName: ch.bName,\n bid: ch.bid,\n bookType: ch.bookType,\n cat: ch.cat,\n catId: ch.catId,\n cbid: ch.cbid,\n cid: ch.cid,\n clickCnt: ch.clickCnt,\n cnt: ch.cnt,\n desc: ch.desc,\n imgUrl: ch.imgUrl,\n isInShelf: ch.isInShelf,\n isPub: ch.isPub,\n isVip: ch.isVip,\n lastChapterName: ch.lastChapterName,\n lastUpdateTime: ch.lastUpdateTime,\n recomendCnt: ch.recomendCnt,\n signStatus: ch.signStatus,\n state: ch.state,\n subCateId: ch.subCateId,\n subCateName: ch.subCateName,\n subCateUrl: ch.subCateUrl,\n updateTime: ch.updateTime\n }));", "name": "bName", "author": "bAuth", "kind": "cat && subCateName && state && signStatus", "wordCount": "cnt", "lastChapter": "lastChapterName", "intro": "@js: lastUpdateTime+\"\\n\"+desc", "coverUrl": "@js:\"https:\"+imgUrl", "bookUrl": "@js:\"https://m.qidian.com/book/\"+bid" }, "ruleExplore": { "bookList": "ol#books-@a", "name": "class.book-title@text", "author": "class.book-author@text", "kind": "class.gray@text && class.red@text", "wordCount": "class.blue@text", "intro": "class.book-desc@text", "coverUrl": "img@src##//(.*)##https://$1###", "bookUrl": "a@href" }, "ruleBookInfo": { "name": "h2.book-title@text", "author": "div.book-rand-a@a@text##作者：(.*)级别##$1###", "kind": "class.book-score@tag.p.0@text&&class.book-score@tag.p.1@text##(连载|完本)##$1###", "wordCount": "p:contains(字)@textNodes##连载|完本|\\n", "lastChapter": "div.book-meta-r@text##：更新状态：(.*)·连载至(.*)##$2 ·$1", "intro": "<js>\n'　　★最近更新:'+result.match(/class=\"gray ell\" [^>]+>([^<]+)<span/)[1]+'★\\n'+result.match(/textarea hidden>([\\W\\w]+?)<\\/texta/)[1].replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,\"'\")\n</js>", "coverUrl": "img@src##//(.*)##https://$1###", "tocUrl": "##data-book-id=\"([^\"]+)##https://druid.if.qidian.com/argus/api/v1/chapterlist/chapterlist?bookId=$1###" }, "ruleToc": { "chapterList": "<js>\n var json=JSON.parse(result).Data;\n var bid=json.BookId;\n var base=\"https://m.qidian.com/book/\"+bid+\"/\";\n json.Chapters.slice(1).map(ch=>({\n title:ch.N,\n link:base+ch.C,\n vip:ch.V,\n time:java.timeFormat(ch.T)\n }))\n</js>", "chapterName": "title", "chapterUrl": "link", "isVip": "vip", "updateTime": "time" }, "ruleContent": { "content": "section.jsChapterWrapper@p@html" } }`
> 
> ![image](https://user-images.githubusercontent.com/49943048/127080503-2ffd5c9b-ea1f-4d8b-964e-30a0842b458d.png)

书籍URL

**Comment by zmn001125** [comment]
书籍URL正则写的太笼统了（导致直接判定为详情页）
要么改成https://m.qidian.com/book/\d+
或者不写

然后就是目录列表记得前面补上@js:

**Comment by zmn001125** [comment]
> 书籍URL正则写的太笼统了（导致直接判定为详情页）
> 要么改成[https://m.qidian.com/book/\d+](https://m.qidian.com/book/%5Cd+)
> 或者不写
> 
> 然后就是目录列表记得前面补上@js:

然后搜索规则如果像你这样用的allinone的话，只能在搜索列表把所有东西都弄好，下面的规则用@js:啥的都没用

**Comment by zmn001125** [comment]
> 书籍URL正则写的太笼统了（导致直接判定为详情页）
> 要么改成[https://m.qidian.com/book/\d+](https://m.qidian.com/book/%5Cd+)
> 或者不写
> 
> 然后就是目录列表记得前面补上@js:

😂才看到原本是有<js></js>，粘贴进阅读就无了
