### ISSUE TITLE
[BUG] 搜索书名是会导致软件无响应

### ISSUE THREAD

**Issue by szmabcd** [gedoor/legado#1165]
### 机型（如Redmi K30 Pro）
>
荣耀v30 pro

### 安卓版本（如Android 7.1.1）
>
Android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.072317

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通

### 问题描述（简要描述发生的问题）
>
搜索书名时会无响应

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

搜索书名时会无响应

### 日志提交（问题截图或者日志）
>

![image](https://user-images.githubusercontent.com/38176269/126850409-b67d781f-12d7-4785-92ac-11c9f29bfb18.png)

**Comment by 52fisher** [comment]
你导入的源太多了

**Comment by qingchuwudi** [comment]
你这个只是卡死，我用最新版的都搜不了书，输入书名以后什么反应都没有。
