### ISSUE TITLE
[BUG] 导出epub时带有图片的段落格式化错误导致读不出来文字

### ISSUE THREAD

**Issue by JiuZhouWorlds** [gedoor/legado#1166]
### 机型（如Redmi K30 Pro）
>Redmi note9

### 安卓版本（如Android 7.1.1）
>11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.072317

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>
阅读带有图片文字的章节，导出为txt还要带个文件夹放图片，不合适；导出为epub再导入阅读，发现图片文字所在段落只剩下图片，文字消失了，只有不含图片的段落里的文字还存在。解包发现类似的代码:

```
<h2 class="head">1总督大人</h2>
灵州城<div class="duokan-image-single"><img class="picture-80" src="../Images/6713229623c8b229.png"/></div>已经蒙了三日的细雨，而从钱家<div class="duokan-image-single"><img class="picture-80" src="../Images/b8df64deca31c254.png"/></div>事到现在江菱歌已经找遍了灵州里的达官贵人。可他们不是不肯<div class="duokan-image-single"><img class="picture-80" src="../Images/b8df64deca31c254.png"/></div>
```

可见图片所在段落里的其他文字没有被正确格式化。
### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by celetor** [comment]
富文本样式的会导致epub格式化有问题

**Comment by JiuZhouWorlds** [comment]
网址失效了，下次我再碰见这样的再发吧。

**Comment by 52fisher** [comment]
已修复
