### ISSUE TITLE
[BUG] 尝试将书架切换到文件夹时崩溃

### ISSUE THREAD

**Issue by JiuZhouWorlds** [gedoor/legado#1168]
### 机型（如Redmi K30 Pro）
>redmi note9 5g

### 安卓版本（如Android 7.1.1）
>11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.072317

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>尝试将书架切换到文件夹时崩溃

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>
[归档.zip](https://github.com/gedoor/legado/files/6871854/default.zip)

**Comment by gedoor** [comment]
这个还没开发好

**Comment by JiuZhouWorlds** [comment]
没注意，那我先关了
