### ISSUE TITLE
[BUG] 设置里点击字体直接报错

### ISSUE THREAD

**Issue by richwxd** [gedoor/legado#1169]
### 机型（如Redmi K30 Pro）
> Oppo Reno Ace

### 安卓版本（如Android 7.1.1）
> Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.072317

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动，联通

### 问题描述（简要描述发生的问题）
> 将legado_app_3.21.072317.apk备份，然后在legado_cronet_3.21.072317.apk里操作导入，点击进入一本书，点击显示“界面”->"字体"，在正常的版本中弹出选择字体的窗口。但是在cronet版本里报错
![图片](https://user-images.githubusercontent.com/22185826/126871105-48a3e5c5-de24-4cd3-b275-662c54ef8530.png)

### 使用书源（填写URL或者JSON）
> 与书源无关

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
好的,我看下

**Comment by gedoor** [comment]
最新版本应该好了
