### ISSUE TITLE
[BUG] 书籍的更新时间没有实际更新?

### ISSUE THREAD

**Issue by letterk** [gedoor/legado#1170]
长按书籍, 进入书籍信息
更新时间并没有更新, 有些还显示几个月前
不知道是不是和源的设置有关

**Comment by gedoor** [comment]
我看下

**Comment by celetor** [comment]
需要刷新详情页才行

**Comment by letterk** [comment]
> 需要刷新详情页才行，刷新书架只是更新目录页

刷新详情页还是不行, 换源的话, 会变成当前时间. 我发现好像是源的什么设置问题, 因为有些源在书籍信息那里并不显示更新时间这一项

**Comment by gedoor** [comment]
下版本修复,目录有变化就更新
