### ISSUE TITLE
[BUG]打开本地书籍偶现一直显示“加载数据中”状态

### ISSUE THREAD

**Issue by JiuZhouWorlds** [gedoor/legado#1175]
### 机型（如Redmi K30 Pro）
>redmi note9

### 安卓版本（如Android 7.1.1）
>11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.072522

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>打开本地书籍偶尔会出现一直加载的场景。点击翻页就进入第二页正常了，返回第一页也正常了。网络书籍未试验。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>偶尔出现，如果首次打开的本地新书籍出现概率会较高

**Comment by 52fisher** [comment]
见 我的 - 帮助
