### ISSUE TITLE
[Feature Request] 建议增加个切换图标的功能

### ISSUE THREAD

**Issue by ju0632** [gedoor/legado#1177]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 可切换图标以便区分不同版本如crnet版，测试版

### 期望实现方式（阅读应该如何实现该功能）
> 可在设置里切换app图标，

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
有这个功能,在主题设置里
