### ISSUE TITLE
[Feature Request] 希望添加自动开启web服务,或保持web服务不自动关闭

### ISSUE THREAD

**Issue by xsdcz** [gedoor/legado#1193]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望添加自动开启web服务，或者在安卓捷径上添加开启web服务的快捷按钮
阅读3现在的情况似乎是网络改变后就会关闭web服务，希望可以不自动关闭web服务，因为在家的时候，会喜欢用电脑进行阅读，并且阅读进度可以同步。但现在每次回到家都需要重新从设置里面进行开启，希望有更方便快捷的方法。

### 期望实现方式（阅读应该如何实现该功能）
> 比较理想的方式是切换网络时判断当前wifi是否是特定wifi,并自动开启web服务，或者干脆一直开着(可以加选项是否一直开启)

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的,我看看加个捷径

**Comment by ifwlzs** [comment]
#1037

**Comment by gedoor** [comment]
下版本就有这个功能了
