### ISSUE TITLE
希望加入pc端阅读

### ISSUE THREAD

**Issue by build233** [gedoor/legado#1199]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在pc端加入阅读

### 期望实现方式（阅读应该如何实现该功能）
> 具有添加书源的功能

### 附加信息（其他的与功能相关的附加信息）
> 无

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
无

**Comment by yafovo** [comment]
可通过在软件上开启Web服务，用浏览器在电脑上看书，需手机电脑连接同一个局域网，数据完全同步，缺点就是手机需要亮屏。

**Comment by huage2580** [comment]
https://github.com/huage2580/yuedu_hd  
我的开源项目，flutter实现，有打包Windows的，直接下载

**Comment by hectorqin** [comment]
https://github.com/hectorqin/reader
也可以看一下这个，不过要安装 java 环境
