### ISSUE TITLE
请增加选项，可以禁用滑动翻页，避免错误翻页

### ISSUE THREAD

**Issue by jacksonyin** [gedoor/legado#1200]
### 需求来源
> 现在点击屏幕下部，有时候会翻到上一页，因为触发了向右滑动导致的，这个极度影响阅读体验

### 功能描述（请清晰的、详细的描述你想要的功能）
> 请增加选项，在屏幕区域，可以禁用滑动翻页，只响应点击翻页

**Comment by s34304** [comment]
我也是有这个问题，点击偶尔会往前翻。
或者可以加长滑动检测时间
