### ISSUE TITLE
[BUG] 占用空间大

### ISSUE THREAD

**Issue by yuncloud99** [gedoor/legado#1208]
### 机型（如Redmi K30 Pro）
>redminote9 pro

### 安卓版本（如Android 7.1.1）
>

11
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.20.062909
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

联通
### 问题描述（简要描述发生的问题）
>
存储空间占用大

### 使用书源（填写URL或者JSON）
>

我就看本地书
```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

![image](https://user-images.githubusercontent.com/86056024/128032760-8c939970-2ca8-40b2-b425-b1b42cb7cf2c.png)
![Uploading image.png…]()
#

**Comment by yuncloud99** [comment]
![image](https://user-images.githubusercontent.com/86056024/128033128-98c54362-5b4e-47f5-a09a-49f94c70a1d4.png)

**Comment by JiuZhouWorlds** [comment]
你看的本地书会被复制一份到程序自己的目录所以占用大，你看完从书架删掉就好了

**Comment by yuncloud99** [comment]
这样太。。。。。。。老哥我只能说，为啥设计成这样啊。。。。

**Comment by JiuZhouWorlds** [comment]
大概是为了安全性吧

**Comment by 1552980358** [comment]
是访问限权的原因，在每一次选择本地书本后的文件URI只会有一个临时访问权，访问之后就不能再次访问了，所以只能复制到APP的私有目录

**Comment by gedoor** [comment]
> 是访问限权的原因，在每一次选择本地书本后的文件URI只会有一个临时访问权，访问之后就不能再次访问了，所以只能复制到APP的私有目录

确实是这个问题

**Comment by yuncloud99** [comment]
老哥你要不要参考一下掌阅的方案？我同一个手机上的掌阅才22MB........

**Comment by gedoor** [comment]
> 老哥你要不要参考一下掌阅的方案？我同一个手机上的掌阅才22MB........

android 11对存储权限收的很紧,根本不会给长期权限,我不知道掌阅的方案,掌阅又不开源,你知道你可以提pr

**Comment by ag2s20150909** [comment]
> 老哥你要不要参考一下掌阅的方案？我同一个手机上的掌阅才22MB........

掌阅的Target API 是26，刚好踩在国内要求第底线上，而要上架google play 最低就是28。

```html+
您上传的 APK 需要符合 Google Play 的目标 API 级别要求。全新应用和新版应用的目标运行环境必须为 Android 10（API 级别 29）或更高版本；Wear OS 应用除外，此类应用的目标运行环境必须为 API 级别 28 或更高级别。

自 2021 年 8 月起，全新应用需要：

使用 Android App Bundle 格式发布。
使用 Play Asset Delivery 或 Play Feature Delivery 分发所有下载体积超过 150MB 的资源或功能。对于全新应用，扩展文件 (OBB) 将不再受支持。
以 API 级别 30 (Android 11) 或更高级别为目标运行环境，并针对行为变更进行调整；Wear OS 应用除外，此类应用必须继续以 API 级别 28 或更高级别为目标运行环境。
从 2021 年 11 月开始，新版应用必须以 API 级别 30 或更高版本为目标运行环境，并针对 Android 11 中的行为变更进行调整。未收到更新的现有应用不会受到影响，用户可以继续从 Play 商店下载。Wear OS 应用必须继续以 API 级别 28 或更高级别为目标运行环境。

改用 Android App Bundle 发布方式也会影响使用旧版免安装应用 ZIP 格式的免安装体验。自 2021 年 8 月起，如果开发者要发布新的免安装应用或更新现有免安装应用，必须发布支持免安装体验的 App Bundle。
```

**Comment by Aetf** [comment]
虽然可能有点儿 overkill, 不过新的 [all file access](https://developer.android.com/about/versions/11/privacy/storage#all-files-access) 权限也许可以？
