### ISSUE TITLE
[BUG] 排版和虚拟键重叠

### ISSUE THREAD

**Issue by anyou523** [gedoor/legado#1210]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>安卓8.0 2台

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.080316

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>阅读时使用白天/深色模式按钮切换 会重新排版和虚拟键重叠 返回书架重新进入正常 切换后不正常

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>
![Screenshot_20210804-174500](https://user-images.githubusercontent.com/30484484/128159992-468a349d-60a0-44eb-bbf1-4cd7122683cf.jpg)

**Comment by ifwlzs** [comment]
我安卓11，小米10，miui12 20.9.3也出现同样问题
  下面两张图片，上面是正常显示，下面是异常显示。
  发生问题的过程是阅读放在后台(放后台时间要长一点更好复现)，切回来就会覆盖
![IMG_20210803_020353.jpg](https://user-images.githubusercontent.com/49548316/128274246-6b9cb09e-bb0b-41ef-b1e8-b3b0058625c0.jpg)
![IMG_20210805_085449.jpg](https://user-images.githubusercontent.com/49548316/128274482-d5687c54-cae6-4d2c-a90d-724b880b0326.jpg)

**Comment by gedoor** [comment]
下版本解决
