### ISSUE TITLE
[Feature Request] 编辑书源 书源安全

### ISSUE THREAD

**Issue by Pantyhose-X** [gedoor/legado#1218]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 防止书源被乱用，
例如：[我的云服务器](https://larsjung.de/h5ai/)，开启了，必须输入[2FA密码](https://getaegis.app/)才可以访问

### 期望实现方式（阅读应该如何实现该功能）
> 在编辑书源那，添加[2FA密码](https://getaegis.app/) 功能

**Comment by zanewayne78** [comment]
？有密码就不能被乱用吗？书源你不想给别人用不分享不就行了，分享出去，就算有密码我也可以导出或者截屏分享，这样博弈下去没完没了啊。
