### ISSUE TITLE
[BUG] 定时结束朗读功能偶尔失效

### ISSUE THREAD

**Issue by tatonka77** [gedoor/legado#1220]
### 机型（如Redmi K30 Pro）
>一加9R

### 安卓版本（如Android 7.1.1）
>安卓11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>版本：3.21.072051

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>睡前设定定时结束朗读，结果半夜起来发现还在朗读，而且定时倒计时居然还没归零

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>发生了两次

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
好的,我看看

**Comment by nobk** [comment]
bug重现方法之一：选中一本书开始读，然后定时，并设为后台。读一会儿之后，另选一本书，会开始新书的语音朗读，但定时被冻结了，朗读不会停止。

**Comment by gedoor** [comment]
行, 看看

**Comment by nobk** [comment]
8月21号的版本依然有这个bug。
由于换一本书之后，手动拖一下定时条，可以解决这个问题，如果内部查错困难，建议每打开一本书时，检查到计时如果未归零，程序自动模拟一遍手动拖定时条这个过程，来解决这个bug。

**Comment by gedoor** [comment]
找到原因了,下版本修复

**Comment by nobk** [comment]
> 找到原因了,下版本修复

还是有问题，现在定时走得太快了，180分钟定时20多分钟就走完了。

**Comment by gedoor** [comment]
嗯,我再修复一下
