### ISSUE TITLE
3.21.081008不能安裝，說是版本比之前低。

### ISSUE THREAD

**Issue by ifermi** [gedoor/legado#1224]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
![Uploading 16285636678035649800217700141724.jpg…]()

**Comment by iseeyo** [comment]
同样安装失败，不过没提示版本问题。

**Comment by gedoor** [comment]
从哪里下的版本

**Comment by a8214983** [comment]
请问，legado_app_3.21.081008.apk、legado_cronet_3.21.081008.apk，这两者有什么不同吗，app无法安装但cronet却可以。

**Comment by iseeyo** [comment]
> 从哪里下的版本

从release下载的最新版，覆盖安装时提示安装失败

**Comment by gedoor** [comment]
好像是自动生成的,release我还没发布,先删除了

**Comment by iseeyo** [comment]
> 好像是自动生成的,release我还没发布,先删除了

好的呢
