### ISSUE TITLE
两个app有什么不同吗

### ISSUE THREAD

**Issue by a8214983** [gedoor/legado#1225]
请问，legado_app_3.21.081008.apk、legado_cronet_3.21.081008.apk，这两者有什么不同吗，app无法安装但cronet却可以。

**Comment by iseeyo** [comment]
> 请问，legado_app_3.21.081008.apk、legado_cronet_3.21.081008.apk，这两者有什么不同吗，app无法安装但cronet却可以。

两者区别是前者是原内核，cronet采用的chrome内核，legado_app_3.21.081008.apk无法安装这个问题好几个人都遇到，等待修复吧。

**Comment by ag2s20150909** [comment]
只在网络请求库上有区别，其它地方没区别。

app版的网络请求框架是okhttp,是运行在jvm上的Http 客户端的一种实现，非常好用。支持http/1.x ,http/2,暂时还不支持新一代的http/3 协议。

cronet版的网络请求框架是Cronet(Chromium network stack, Chromium 网络堆栈),就是目前主流Chromium内核的浏览器的网络请求模块，主要实现运行在native层，支持http1.x ,http/2,http/3(QUIC) 等协议。
