### ISSUE TITLE
这个网的搜索页面的书籍封面地址采用常规写法提取不出来，@css写法可以，其他方法不行，可能我的写法不对，请大佬帮忙看看啥问题？

### ISSUE THREAD

**Issue by wpyok500** [gedoor/legado#1227]
机型
荣耀20 pro

安卓版本
鸿蒙os 2.0

阅读Legdao版本（我的-关于-版本,如3.20.112220）
阅读 版本 3.21.080316
书源搜索地址：https://www.biquyue.com/search.php?q={{key}}

以下写法都不能正常获取到搜索页面的书籍封面地址(**搜索页面**非详细页面)
1、class.result-game-item-pic@tag.img@src 或 class.result-game-item-pic@tag.a@tag.img@src  或 img@src
2、div.result-game-item-pic@tag.img@src 或 divresult-game-item-pic@tag.a@tag.img@src
3、@xpath:/html/body/div[3]/div[1]/div[1]/a/img/@src
4、//*html/body/div[3]/div[1]/div[1]/a/img/@src  或 //*[@class=\"result-game-item-pic-link-img\"]@src

@css 写法就可以正常获取
.result-game-item-pic-link-img@src 或 .result-game-item-pic>a>img@src

采用正常@css写法书源
[
  {
    "bookSourceComment": "",
    "bookSourceName": "笔趣阁1(兮)",
    "bookSourceType": 0,
    "bookSourceUrl": "www.biquyue.com",
    "customOrder": 1,
    "enabled": true,
    "enabledExplore": true,
    "lastUpdateTime": 1628655180443,
    "ruleBookInfo": {
      "author": "[property=og:novel:author]@content",
      "coverUrl": "[property=og:image]@content",
      "intro": "[property=og:description]@content",
      "kind": "[property=og:novel:category]@content&&[property=og:novel:status]@content",
      "lastChapter": "[property=og:novel:latest_chapter_name]@content&&[property$=update_time]@content",
      "name": "[property=og:novel:book_name]@content",
      "tocUrl": "#list@dd"
    },
    "ruleContent": {
      "content": "@css:#content@textNodes"
    },
    "ruleExplore": {},
    "ruleSearch": {
      "author": "class.result-game-item-info@p.0@span.1@text",
      "bookList": "class.result-item result-game-item",
      "bookUrl": "h3@tag.a@href",
      "coverUrl": " .result-game-item-pic>a>img@src",#书籍封面其他写法异常，用@css写法正常获取到
      "intro": "div.result-game-item-detail@tag.p@textNodes",
      "kind": ".result-game-item-info>p:eq(1)>span:eq(1)@text",
      "lastChapter": "class.result-game-item-info@p.3@tag.a@text",
      "name": "h3@tag.a@text"
    },
    "ruleToc": {
      "chapterList": "#list@dd",
      "chapterName": "a@text",
      "chapterUrl": "a@href"
    },
    "searchUrl": "https://www.biquyue.com/search.php?q={{key}}&&page={{page}}",
    "weight": 0
  }
]

**Comment by zmn001125** [comment]
![IMG_20210811_124625](https://user-images.githubusercontent.com/52020688/128971038-5aa8f1bc-befa-4037-959d-3d161316d95d.jpg)

![Screenshot_2021-08-11-12-43-46-800_io legado app release](https://user-images.githubusercontent.com/52020688/128970831-b676cacc-d158-42b3-9eeb-6837f25fd292.jpg)
我试了下普通写法可以获取呀，你给一下你的调试图？

**Comment by wpyok500** [comment]
我晕了，普通写法现在测试又可以了，在风中凌乱了。。。。晕哭了  @zmn001125 哔哩哔哩上的视频教程是你的吗，视频教程很好，就是小姐姐的声音小了点，要在比较安静的环境下看。

**Comment by wpyok500** [comment]
已正常，😂😂😂
