### ISSUE TITLE
正文文本在标签<img>正文内容</img>里的正常写法取不出来，请大佬帮忙看看

### ISSUE THREAD

**Issue by wpyok500** [gedoor/legado#1231]
### 机型（如Redmi K30 Pro）
>荣耀 20 pro

### 安卓版本（如Android 7.1.1）
>鸿蒙os 2.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>阅读Legdao版本：3.21.081020

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>正文文本在标签<img>正文内容</img>里的这几种正常写法取不出来
**书籍：万古第一媳，最新1059、1060章节采用img写法**
id.content@tag.img@text
id.content@tag.img@textNodes 
id.content@tag.img@ownText
#content>img@text
#content>img@textNodes
#content>img@ownText
#content>img@html 
tag.img@text
这些写法均不能取正文

正常可以取得@css写法，
1、#content@text 可以正常取但不分段落；

### 使用书源（填写URL或者JSON）
>大佬，以下书源的搜索关键字，请用    **万古第一**  进行调试

```json
[
  {
    "bookSourceComment": "",
    "bookSourceName": "笔趣阁1(兮)",
    "bookSourceType": 0,
    "bookSourceUrl": "www.biquyue.com",
    "customOrder": 1,
    "enabled": true,
    "enabledExplore": true,
    "lastUpdateTime": 1628729218133,
    "ruleBookInfo": {
      "author": "[property=og:novel:author]@content",
      "coverUrl": "[property=og:image]@content",
      "intro": "[property=og:description]@content",
      "kind": "[property=og:novel:category]@content&&[property=og:novel:status]@content",
      "lastChapter": "[property=og:novel:latest_chapter_name]@content&&[property$=update_time]@content",
      "name": "[property=og:novel:book_name]@content",
      "tocUrl": "#list@dd"
    },
    "ruleContent": {
      "content": ".content>img@text"
    },
    "ruleExplore": {},
    "ruleSearch": {
      "author": "class.result-game-item-info@p.0@span.1@text",
      "bookList": "class.result-item result-game-item.7",#设定了从书籍列表取这本书籍
      "bookUrl": "h3@tag.a@href",
      "coverUrl": " .result-game-item-pic>a>img@src",
      "intro": "div.result-game-item-detail@tag.p@textNodes",
      "kind": ".result-game-item-info>p:eq(1)>span:eq(1)@text",
      "lastChapter": "class.result-game-item-info@p.3@tag.a@text",
      "name": "h3@tag.a@text"
    },
    "ruleToc": {
      "chapterList": "#list@dd.-1",#设定了取最后一章，目前最新1060章
      "chapterName": "a@text",
      "chapterUrl": "a@href"
    },
    "searchUrl": "https://www.biquyue.com/search.php?q={{key}}&&page={{page}}",
    "weight": 0
  }
]





```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>
书籍源码截图
![image](https://user-images.githubusercontent.com/14154547/129121857-c4ea6eef-fd6d-4b50-a6d6-d84d9e320ea0.png)

**Comment by wpyok500** [comment]
@zmn001125 大佬，来帮忙看看，谢谢

**Comment by zmn001125** [comment]
> @gedoor @zmn001125 大佬，来帮忙看看，谢谢

id.content@html


最后@html会取<br>等标签就会有分段

**Comment by zmn001125** [comment]
正文在id="content"的标签里，不在img标签里

**Comment by wpyok500** [comment]
> 正文在id="content"的标签里，不在img标签里
1、点击img标签会最小化，不显示正文文本，而且看格式正文内容在<img>正文在这里</img>内。
2、我感觉是他这个img标签有问题，正常显示的应该是空格，而不是&nbsp，
![image](https://user-images.githubusercontent.com/14154547/129132203-f5d19ac1-03a4-4209-9d87-911571ce0454.png)

![image](https://user-images.githubusercontent.com/14154547/129132351-867ca30e-e186-4ddd-b45f-cc46f2f14be9.png)

**Comment by huage2580** [comment]
```
#content@html##<[\/]?img.*?>
```
使用这个正文规则就可以了，这个确实是网页有问题导致的。
