### ISSUE TITLE
[BUG] 新增分组名称不能换行

### ISSUE THREAD

**Issue by neihobatho** [gedoor/legado#1233]
### 机型（如Redmi K30 Pro）
>Samsung S21

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.081020

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>新增分组时分组名称不能换行，以前的版本可以

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>![Screenshot_20210813-002832_Legado](https://user-images.githubusercontent.com/76517199/129233860-ec9f446c-cd37-4715-950d-ba8a86a41880.jpg)

>新版本变成完成按钮不能换行
图中的全部分组是以前版本改的 能换行

**Comment by gedoor** [comment]
好的,我改下

**Comment by gedoor** [comment]
下版本修复
