### ISSUE TITLE
pc端请求

### ISSUE THREAD

**Issue by zhalon** [gedoor/legado#1237]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 能否在pc端加入阅读

### 期望实现方式（阅读应该如何实现该功能）
> pc端

### 附加信息（其他的与功能相关的附加信息）
> 最好能有linux版

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>无

**Comment by hectorqin** [comment]
可以看一下我改的项目 https://github.com/hectorqin/reader

**Comment by 10bits** [comment]
用golang抄了一个,解析书源生成epub书籍可以用win10自带的edge浏览器查看

https://user-images.githubusercontent.com/2499251/129387887-bef1d19d-ab88-42f0-b474-36607e16bebd.mp4

**Comment by zhalon** [comment]
@10bits 请问有没有项目地址？

**Comment by 10bits** [comment]
> @10bits 请问有没有项目地址？

暂未开源,纯属自娱自乐,爬虫这种东西怕不是有法律风险

**Comment by huage2580** [comment]
https://github.com/huage2580/yuedu_hd  
打包有Windows

**Comment by zhalon** [comment]
@huage2580 我主要想要一个linux的，可以搞一个吗？

**Comment by letterk** [comment]
为什么都不考虑web端，虽然目前还是半成品

**Comment by hectorqin** [comment]
> 可以看一下我改的项目 https://github.com/hectorqin/reader

这个项目就是在Web端的基础上改的

**Comment by letterk** [comment]
> > 可以看一下我改的项目 https://github.com/hectorqin/reader
> 
> 这个项目就是在Web端的基础上改的

我认为在手机阅读app良好的体验下, 再搞独立的PC端有点本末倒置. 
以移动端作为书架记录中心, webdav备份数据, web端在PC上阅读.
一条龙解决了, 以前书籍分散到多个网站上, 也不用担心网站挂掉导致多年的书架记录灰飞烟灭.

**Comment by hectorqin** [comment]
增加了安装包，但是需要安装`jdk10`以上的java环境

> > > > 可以看一下我改的项目 https://github.com/hectorqin/reader
> > > 
> > > 
> > > 这个项目就是在Web端的基础上改的
> > 
> > 
> > 你这个是linux版嘛？
> 
> 可以用Docker运行，然后浏览器访问 http://localhost:8080/web/
