### ISSUE TITLE
[BUG] 无法向前保存阅读章节位置

### ISSUE THREAD

**Issue by jl0476** [gedoor/legado#1246]
### 机型（如Redmi K30 Pro）
> 小米11pro

### 安卓版本（如Android 7.1.1）
> 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.081308

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 全部

### 问题描述（简要描述发生的问题）
>    无法向前保存阅读章节位置，
比如我之前看到1000章，现在我想从头看。看到第10章后退出，在进入阅读界面，自动跳转到1000章。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
1. 打开一本书，已经看完的或者看的进度比较靠后的。
2. 通过目录，选择之前已经看完的章节，看几页。
3. 退出，确认显示的章节正确。
4. 重新打开这本书，会自动跳转到靠后的章节。

### 日志提交（问题截图或者日志）
>
![https://github.com/jl0476/jl0476.github.io/blob/master/qi7em-u08u8.gif?raw=true](https://github.com/jl0476/jl0476.github.io/blob/master/qi7em-u08u8.gif?raw=true)

https://github.com/jl0476/jl0476.github.io/blob/master/qi7em-u08u8.gif?raw=true

**Comment by gedoor** [comment]
我看下,

**Comment by gedoor** [comment]
我试了下没有问题,在pause事件中上传当前进度,进入阅读界面的时候读取进度,出现这个问题应该是你当时上传进度失败了,应该是偶然事件

**Comment by jl0476** [comment]
不是偶然事件，这本书每次都是这样的。
你看我的动图里面，其实是试了两次的。

**Comment by jl0476** [comment]
甚至我把书籍删除了，再添加到书架里面，都能同步到进度。

**Comment by jl0476** [comment]
https://user-images.githubusercontent.com/5226690/130045811-ec160e5e-dce0-4015-8c23-b83a7a75194f.mp4

**Comment by jl0476** [comment]
@gedoor 我删除了webdev备份的bookprogress中这本书的进度保存文件，正常了。
