### ISSUE TITLE
是否考虑源上把小说和漫画源区分开？

### ISSUE THREAD

**Issue by kaich** [gedoor/legado#1247]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 为了更优秀的体验，有时候要针对特定的源做特定的处理，漫画好小说共用一个类型，有时候难以区分，无法针对特殊化处理。

### 期望实现方式（阅读应该如何实现该功能）
> 源类型上进行区分

**Comment by gedoor** [comment]
好的

**Comment by kaich** [comment]
@gedoor 感谢， 🙏 希望到时候漫画模式类型不要用`2`， `2`已经被我用掉了。
