### ISSUE TITLE
[BUG] 连接失败

### ISSUE THREAD

**Issue by bluelovers** [gedoor/legado#1249]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

legado_app_3.21.081909_原包名.apk

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

![image](https://user-images.githubusercontent.com/167966/130075473-b78e7480-3ab4-43ef-83d9-c3f399305998.png)

電腦端輸入手機提供的網址之後 能連上這個位址
但接下來就遇上顯示無法連上後端

不懂是哪裡出了問題

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
我试下

**Comment by bluelovers** [comment]
我發現好像跟書架內沒有任何書有關係
在書架內加了一本書之後 就正常了

**Comment by gedoor** [comment]
明白了,应该是判断没有数据就提示没有连接了
