### ISSUE TITLE
希望 WebDAV 备份能独立使用

### ISSUE THREAD

**Issue by ShuiHuo** [gedoor/legado#125]
WebDAV 备份应当能独立使用，和 WebDAV 恢复一样，不依赖其他权限。

具体应做到：
1. 填写完 WebDAV 地址后应提示“这是否是最终备份目录“。最终备份目录则不创建子目录 legado。
2. 手动点击备份时应该有 WebDAV 备份选项，不需要选择本地目录备份后才通过 WebDAV 备份。
3. 有实时备份和定时备份选项，增加实时性或更少流量。
4. 备份内容可选：书源、书籍、本地书籍、订阅、净化替换、主题、样式、其他配置。默认全选。
5. 帐号密码错误等情况应有提示。

可选实现：
1. 迁移，将本地和以前的网络备份迁移到一个新的服务器上，可选是否保留旧位置的文件。

**Comment by kang-mk** [comment]
我自己在群晖上开启了WEBDAV服务，然后备份时候提示no protocol XXXX/legado这个错误，不知道什么情况

**Comment by anleihn** [comment]
> 我自己在群晖上开启了WEBDAV服务，然后备份时候提示没有协议XXXX / legado这个错误，不知道什么情况

需要建立 legado文件夹
