### ISSUE TITLE
[BUG] web端看书, 阅读记录只能向后保存, 不能向前保存

### ISSUE THREAD

**Issue by letterk** [gedoor/legado#1250]
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.081308

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>例如, 看到"第二章", 这时, 手机app和web里阅读记录显示"第二章". web上退回到"第一章", 此时无法保存记录, 此时手机app和web的阅读记录均为"第二章"

>在打开web功能的时候, 还会出现, 手机app"150章", web点个"300章", 手机上显示历史记录是"300章", 点进去还是"150章". 需要重启app后, 手机上才能正确识别历史记录是"300章"

**Comment by gedoor** [comment]
好的,我看下

**Comment by letterk** [comment]
> 好的,我看下

![Snipaste_2021-08-24_03-52-56](https://user-images.githubusercontent.com/9822709/130510867-d0a36480-172a-4081-acf4-106b0f141121.jpg)
![Snipaste_2021-08-24_03-53-45](https://user-images.githubusercontent.com/9822709/130510911-dd317f74-879c-4d78-993d-febec8773bb5.jpg)

web端index大于app的index时, app会更新
小于则不会保存

**Comment by letterk** [comment]
![Snipaste_2021-08-24_04-01-35](https://user-images.githubusercontent.com/9822709/130511916-5dc69ae2-147f-46ec-b33d-70f95edf9c43.jpg)
我怀疑是这里的问题

**Comment by gedoor** [comment]
应该是的,我改下

**Comment by gedoor** [comment]
是因为这里没有把进度同步到webDav的问题

**Comment by letterk** [comment]
> 是因为这里没有把进度同步到webDav的问题

我平时是把webdav的同步进度关了的, 因为坚果云对频繁发送有限制. 一台手机上用可能感觉不出来, webdav不行就用本地记录, 多台手机就会出大问题

**Comment by letterk** [comment]
最初我是考虑用savebook让web端那边主动发送阅读记录到app.  发现了个bug.
![Snipaste_2021-08-24_17-10-25](https://user-images.githubusercontent.com/9822709/130590870-4da8d971-78a2-4de3-a97f-3adb9b40083a.jpg)

![Snipaste_2021-08-24_17-06-04](https://user-images.githubusercontent.com/9822709/130591041-ec7f332e-1cd5-4c77-bc09-07b27be3dd64.jpg)
![Snipaste_2021-08-24_17-11-56](https://user-images.githubusercontent.com/9822709/130590868-ccff3a77-8100-4dae-ac0a-f9d8a4655af4.jpg)


这个时候点开书籍, 跳转的位置依然是原来的地方
![Snipaste_2021-08-24_17-12-11](https://user-images.githubusercontent.com/9822709/130590863-e151789d-a5fa-4f18-be97-faeb3df7c95a.jpg)
这时打开目录, 显示的是修改后的地方, 第九章. 说明阅读记录已经正常保存了.
应该是打开书籍时使用的index缓存没有更新

所以APP退出重进后, 打开书籍就能定位到修改后的地方
