### ISSUE TITLE
[BUG] 页脚显示标题太长

### ISSUE THREAD

**Issue by szlk** [gedoor/legado#1252]
### 问题描述（简要描述发生的问题）
>
[页脚显示标题太长导致其他信息被遮挡，建议对中间页脚处理，当字数超过多少时变成省略号...

**Comment by szlk** [comment]
![UY5CR LITIBZC$EB CRQR3R](https://user-images.githubusercontent.com/47999330/130205548-94025a3f-91e9-473a-836b-65f7e1ec46b9.jpg)

**Comment by gedoor** [comment]
应该解决了,可以先试试最新测试版本
