### ISSUE TITLE
请教贴, 有个返回的bookurl地址很奇怪, 该怎么抓呢

### ISSUE THREAD

**Issue by letterk** [gedoor/legado#1253]
![Snipaste_2021-08-20_17-33-22](https://user-images.githubusercontent.com/9822709/130214034-af8350f6-71a8-44bf-b9e3-8b0811860ced.jpg)
用getBookshelf返回的数据, 发现有个bookurl地址不知道该怎么用

另外, 我一直以为api是抓的app里处理好的数据缓存, 没想到是直接从书源走

**Comment by haxc** [comment]
抓的是什么东西app的？

**Comment by letterk** [comment]
> 抓的是什么东西app的？

Namofree大佬的书源, 抓的是乐兔阅读app

**Comment by ag2s20150909** [comment]
> ![Snipaste_2021-08-20_17-33-22](https://user-images.githubusercontent.com/9822709/130214034-af8350f6-71a8-44bf-b9e3-8b0811860ced.jpg)
> 用getBookshelf返回的数据, 发现有个bookurl地址不知道该怎么用
> 
> 另外, 我一直以为api是抓的app里处理好的数据缓存, 没想到是直接从书源走

后面的是post 的body

**Comment by letterk** [comment]
> 后面的是post 的body

![Snipaste_2021-08-21_13-22-47](https://user-images.githubusercontent.com/9822709/130311486-3a029c26-987b-4d6b-a1e2-912b8728e308.jpg)
我知道是POST的body, 问题是web端的代码, 没用post. 直接用的get就把目录拉回来了. 好像是因为Axios的别名可以优先处理后面的method而忽视前面的get?

**Comment by SeaHOH** [comment]
form 可以 POST 也可以 GET，服务器一般都兼容。
