### ISSUE TITLE
详情页面在on click里面书源怎么编写

### ISSUE THREAD

**Issue by Codebglh** [gedoor/legado#1256]
例如：onclick="window.open('/si/info/65345.html')"

**Comment by xiaerzhuanyong** [comment]
试试规则后加正则，我碰到是用##^.*?\'|\'

**Comment by Codebglh** [comment]
我用xpath提取出window.open('/si/info/65345.html')然后用这个正则##^.*?\/|\'\)但是返回的是window.open('/si/info/65345.html

**Comment by Codebglh** [comment]
> 我用xpath提取出window.open('/si/info/65345.html')然后用正则##^.*?/|')但返回的是window.open('/si/info/65345. html



> 聪明规则后加正则，我碰到是用##^.*?'|'

谢谢
