### ISSUE TITLE
[Feature Request] 讨论：或许可以考虑用Compose重写，这样通过KMP能跨平台到桌面版和 iOS

### ISSUE THREAD

**Issue by LinXueyuanStdio** [gedoor/legado#1258]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 目前基于xml的ui控制逻辑很复杂，维护成本很大，尤其是阅读页。Compose可以渐进式改造现有ui，且可以通过KMP跨平台到桌面版。

### 期望实现方式（阅读应该如何实现该功能）
> 用Compose重写UI，抛弃xml

### 附加信息（其他的与功能相关的附加信息）
> 优点：
> 1. Compose 支持view体系的互操作，可以渐进改造，慢慢替换现有 xml
> 1. 逻辑层在各平台复用，都是kotlin写的，逻辑层不用改
> 2. 只用针对 UI 层对各个平台做兼容，而这里Compose帮忙处理了很大一部分
> 3. Compose 的 mvvm 比 xml 好太多了
> 4. AS也支持实时预览，不用编译成apk就能看 UI 效果，生产力++
> 5. 去除了xml，包体积减小

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 无

**Comment by hectorqin** [comment]
+1 如果能把核心抽象出来就好了，个人感觉和系统牵扯比较深的就是webview相关操作，这个估计用的人不多

**Comment by ca1e** [comment]
+1 不建议换flutter。同时分离核心功能的另一个好处就是可以独立开源维护并且不提供可直接编译apk的项目，这样可以防止被有些别有用心的人拿去二开私有化加广告什么的

**Comment by gedoor** [comment]
> 会考虑，我会试一下效果怎么样，到时候效果不错我就慢慢更新PR到master了

欢迎

**Comment by woniu163** [comment]
现在这个时间点，compose多平台其实已经比较成熟了，可以先考虑使用compose重构ui部分，之后再把android改造成多平台
