### ISSUE TITLE
[Feature Request] 自动阅读增加切换功能

### ISSUE THREAD

**Issue by 417710661** [gedoor/legado#1260]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 自动阅读可增加一个选项，可选择使用覆盖模式或滚动模式

### 期望实现方式（阅读应该如何实现该功能）
> 在自动阅读右下角的设置添加选项

### 附加信息（其他的与功能相关的附加信息）
> 自动阅读与朗读分开设置，朗读时点击设置可更改语音，自动阅读时点击设置切换翻页模式

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
![自动阅读设置](https://user-images.githubusercontent.com/71995981/130407673-acaa037a-6633-4477-923f-3bab4ca4bc1e.jpg)

**Comment by JiuZhouWorlds** [comment]
附议

**Comment by gedoor** [comment]
好的

**Comment by gedoor** [comment]
下版本实现
