### ISSUE TITLE
[BUG]  从搜索书籍页面 点进去修改源 返回无法查看书籍

### ISSUE THREAD

**Issue by TwoFlyingFish** [gedoor/legado#1268]
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.082409

### 问题描述（简要描述发生的问题）
>从搜索书籍页面，点击书籍详情，点击书源，书源页面修改保存。
一直返回到搜索页面，再次点击书籍详情，无反应。

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
改了书源的什么地方

**Comment by TwoFlyingFish** [comment]
此问题仅在只有一个书源启用的情况下出现。（修改书源任意地方）后保存返回到之前搜索页面，再次点击书籍详情，点击无反应。
如有多个书源，（修改书源任意地方）后保存返回到之前搜索页面，再次点击书籍详情，会自动跳到其它书源。
测试了最新版，还是有这个问题。
