### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JinYanchao** [gedoor/legado#1283]
### 机型（如Redmi K30 Pro）
> HUAWEI Mate 40 Pro+

### 安卓版本（如Android 7.1.1）
> HarmonyOS 2.0.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.082719等多个版本

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动宽带

### 问题描述（简要描述发生的问题）
> Web服务在手机锁屏情况下无法使用

### 使用书源（填写URL或者JSON）
> 无关书源

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 打开Web服务时，只有手机亮屏情况下可以正常使用，其他状态包括熄屏、熄屏显示以及锁屏显示页面都无法使用。
> 尝试了将阅读设置为后台运行，也无法解决。

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
这个可能与手机有关
