### ISSUE TITLE
这个网址无法做成书源，返回301错误，会跳转

### ISSUE THREAD

**Issue by wpyok500** [gedoor/legado#1291]
https://www.bxwxorg.com/

源仓库，几个大佬提供的书源也是一样的，情况，自己写也是。

 @zmn001125  @gedoor 大佬，来帮帮。

源仓库，其他大佬写的书源
~~~json
{
    "bookSourceComment": "",
    "bookSourceGroup": "🍅优选",
    "bookSourceName": "🍅笔下文学",
    "bookSourceType": 0,
    "bookSourceUrl": "https:\/\/www.bxwxorg.com",
    "bookUrlPattern": "",
    "customOrder": 10779,
    "enabled": true,
    "enabledExplore": true,
    "exploreUrl": "玄幻奇幻::\/xuanhuan\/{{page}}.html\n武侠仙侠::\/wuxia\/{{page}}.html\n都市生活::\/dushi\/{{page}}.html\n历史军事::\/lishi\/{{page}}.html\n游戏竞技::\/youxi\/{{page}}.html\n科幻未来::\/kehuan\/{{page}}.html\n恐怖悬疑::\/xuanyi\/{{page}}.html\n 二次 元 ::\/erciyuan\/{{page}}.html\n经典网文::\/jingdian\/{{page}}.html\n古代言情::\/guyan\/{{page}}.html\n现代言情::\/xianyan\/{{page}}.html\n幻想奇缘::\/huanqing\/{{page}}.html\n青春校园::\/qingchun\/{{page}}.html\n网络情缘::\/wangluo\/{{page}}.html\n科幻空间::\/mmkehuan\/{{page}}.html\n鬼怪灵异::\/lingyi\/{{page}}.html\n  N次元  ::\/Nciyuan\/{{page}}.html\n言情美文::\/yanqing\/{{page}}.html",
    "header": "",
    "lastUpdateTime": 1606660436074,
    "loginUrl": "",
    "ruleBookInfo": {
        "author": "[property=\"og:novel:author\"]@content",
        "coverUrl": "[property=\"og:image\"]@content",
        "intro": "id.intro@tag.p.0@html",
        "kind": "[property=\"og:novel:category\"]@content&&[property=\"og:novel:status\"]@content",
        "lastChapter": "[property=\"og:novel:latest_chapter_name\"]@content",
        "name": "[property=\"og:novel:book_name\"]@content",
        "wordCount": "[property=\"og:novel:update_time\"]@content"
    },
    "ruleContent": {
        "content": "id.content@tag.p@text##因某些原因.*回家的路！|喜欢.*速度最快。"
    },
    "ruleExplore": {
        "author": "class.s4@text",
        "bookList": "class.l@ul@tag.li||class.novelslist2@ul@tag.li!0",
        "bookUrl": "class.s2@tag.a@href",
        "kind": "class.s1@text&&class.s6@text##\\[|\\]",
        "lastChapter": "class.s3@text",
        "name": "class.s2@text",
        "wordCount": "class.s5@text"
    },
    "ruleSearch": {
        "author": "class.book_other.0@tag.span.0@text",
        "bookList": "id.sitembox@tag.dl",
        "bookUrl": "tag.a.1@href",
        "coverUrl": "tag.img@src",
        "intro": "class.book_des@text",
        "kind": "class.book_other.0@tag.span.1@text&&class.book_other.0@tag.span.2@text",
        "lastChapter": "class.book_other.1@tag.a.0@text",
        "name": "tag.a.1@text",
        "wordCount": "class.book_other.0@tag.span.3@text"
    },
    "ruleToc": {
        "chapterList": "id.list@tag.dd!0:1:2:3:4:5:6:7:8:9:10:11@tag.a",
        "chapterName": "text",
        "chapterUrl": "href"
    },
    "searchUrl": "\/search.html,{\n  \"method\": \"POST\",\n  \"body\": \"searchkey={{key}}\"\n}",
    "weight": 0
}
~~~

**Comment by gedoor** [comment]
好的,我看一下

**Comment by xiaerzhuanyong** [comment]
这个网址电脑版无法搜索，我换了手机版可以，发现规则你自己写一下
{
  "bookSourceComment": "",
  "bookSourceGroup": "🍅优选",
  "bookSourceName": "🍅笔下文学",
  "bookSourceType": 0,
  "bookSourceUrl": "https://m.bxwxorg.com/",
  "bookUrlPattern": "",
  "customOrder": 0,
  "enabled": true,
  "enabledExplore": true,
  "exploreUrl": "",
  "header": "{\n    'User-Agent': 'Mozilla/5.0 (Linux; Android 10.0; wv) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.110 Mobile Safari/537.36 T7/10.3 SearchCraft/2.6.2 (Baidu; P1 7.0)'\n\n}",
  "lastUpdateTime": 1630672762539,
  "loginUrl": {
    "url": ""
  },
  "ruleBookInfo": {
    "author": "",
    "coverUrl": "",
    "intro": "",
    "kind": "",
    "lastChapter": "",
    "name": "",
    "wordCount": "class.layui-btn layui-btn-xs layui-bg-red@text"
  },
  "ruleContent": {
    "content": "class.content@text"
  },
  "ruleExplore": {
    "author": "",
    "bookList": "",
    "bookUrl": "",
    "kind": "",
    "lastChapter": "",
    "name": "",
    "wordCount": ""
  },
  "ruleSearch": {
    "author": "class.data.0@tag.a@text",
    "bookList": "class.list@tag.li",
    "bookUrl": "class.bookname@tag.a@href",
    "coverUrl": "tag.img@src",
    "intro": "class.intro@text",
    "kind": "class.data.0@tag.span.0@text",
    "lastChapter": "tag.a.-1@text",
    "name": "class.bookname@tag.a@text",
    "wordCount": ""
  },
  "ruleToc": {
    "chapterList": "class.read@tag.li",
    "chapterName": "tag.a@text",
    "chapterUrl": "tag.a@href",
    "nextTocUrl": "class.pagenum@tag.a@href"
  },
  "searchUrl": "/search.html,{\n  \"method\": \"POST\",\n  \"body\": \"searchkey={{key}}\"\n}",
  "weight": 0
}

**Comment by wpyok500** [comment]
> 这个网址电脑版无法搜索，我换了手机版可以，发现规则你自己写一下
> {
> "bookSourceComment": "",
> "bookSourceGroup": "🍅优选",
> "bookSourceName": "🍅笔下文学",
> "bookSourceType": 0,
> "bookSourceUrl": "https://m.bxwxorg.com/",
> "bookUrlPattern": "",
> "customOrder": 0,
> "enabled": true,
> "enabledExplore": true,
> "exploreUrl": "",
> "header": "{\n 'User-Agent': 'Mozilla/5.0 (Linux; Android 10.0; wv) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.110 Mobile Safari/537.36 T7/10.3 SearchCraft/2.6.2 (Baidu; P1 7.0)'\n\n}",
> "lastUpdateTime": 1630672762539,
> "loginUrl": {
> "url": ""
> },
> "ruleBookInfo": {
> "author": "",
> "coverUrl": "",
> "intro": "",
> "kind": "",
> "lastChapter": "",
> "name": "",
> "wordCount": "class.layui-btn layui-btn-xs layui-bg-red@text"
> },
> "ruleContent": {
> "content": "class.content@text"
> },
> "ruleExplore": {
> "author": "",
> "bookList": "",
> "bookUrl": "",
> "kind": "",
> "lastChapter": "",
> "name": "",
> "wordCount": ""
> },
> "ruleSearch": {
> "author": "class.data.0@tag.a@text",
> "bookList": "[class.list@tag.li](mailto:class.list@tag.li)",
> "bookUrl": "class.bookname@tag.a@href",
> "coverUrl": "tag.img@src",
> "intro": "class.intro@text",
> "kind": "class.data.0@tag.span.0@text",
> "lastChapter": "tag.a.-1@text",
> "name": "class.bookname@tag.a@text",
> "wordCount": ""
> },
> "ruleToc": {
> "chapterList": "[class.read@tag.li](mailto:class.read@tag.li)",
> "chapterName": "tag.a@text",
> "chapterUrl": "tag.a@href",
> "nextTocUrl": "class.pagenum@tag.a@href"
> },
> "searchUrl": "/search.html,{\n "method": "POST",\n "body": "searchkey={{key}}"\n}",
> "weight": 0
> }
不行
![Screenshot_20210903_225455_com guoshi httpcanary premium](https://user-images.githubusercontent.com/14154547/132027355-4cba61d5-27f6-4948-9ca1-ffd691421a13.jpg)
![Screenshot_20210903_225512_com guoshi httpcanary premium](https://user-images.githubusercontent.com/14154547/132027376-9fd30a4d-e81e-4b5b-b59b-68de31e0355a.jpg)

**Comment by xiaerzhuanyong** [comment]
我手机可以，你先把抓包关了，把我写的书源粘进去试试，不行把软件卸载更新下

![Screenshot_2021-09-18-16-02-47](https://user-images.githubusercontent.com/46513416/133881913-31a4c67c-8ef6-41a9-88cc-0a044ce86a7c.png)
![Screenshot_2021-09-18-16-02-55](https://user-images.githubusercontent.com/46513416/133881915-9d98a558-02d5-4995-bf53-68badb1539dd.png)
![Screenshot_2021-09-18-16-03-44](https://user-images.githubusercontent.com/46513416/133881916-0bc0474c-5fd5-4081-99c0-53a60976562a.png)
![Screenshot_2021-09-18-16-03-55](https://user-images.githubusercontent.com/46513416/133881917-8ae3e9a8-3845-404e-8a9c-f5ed435c36c0.png)
