### ISSUE TITLE
本地txt导入，希望增加目录规则自定义

### ISSUE THREAD

**Issue by 471417811** [gedoor/legado#1294]
问题描述：当前阅读app，导入本地txt会自动分析获取目录名，但是有些txt目录名是获取错误的，直接无视了原来的 第001章 XXXX 而使用阅读本身的  第1章(1) 这样的形式
> 

### 期望实现方式：1、能够自定义当前小说txt的目录获取规则，纠正错误  
                                 2、加强目录分析规则，已测试目录获取错误的txt，在其他的的阅读app，如：起点阅读，中还是可以获取到每章章节目录名的
>

**Comment by zmn001125** [comment]
点换源按钮选目录正则

**Comment by zcold** [comment]
> 点换源按钮选目录正则

点换源按钮出来的是源列表 没有目录正则 啊

**Comment by gedoor** [comment]
本地txt才是目录正则,书源的就是换源

**Comment by rihalvnium76** [comment]
> 本地txt才是目录正则,书源的就是换源

我是【本地TXT】，但是书籍信息界面没有目录正则，点换源按钮出现的是在线源的列表，并没有目录正则，同样换源界面的菜单也没有目录正则

为什么不像净化规则那样单独弄一个目录规则的设置入口，而非要隐藏在其它设置还不能稳定出现呢？

**Comment by zmn001125** [comment]
> 

是正文页的换源按钮，如果是本地txt，那么目录正则选项是百分百出现的，
![IMG_20211121_145902](https://user-images.githubusercontent.com/52020688/142752888-03b6b47e-96bb-4bfd-b6d3-d11c3c0e20db.jpg)

**Comment by zcold** [comment]
找到了 但是我真的没找到 换源 这两个字在你截图中的任何按钮上。。

zmn001125 ***@***.***> 于 2021年11月21日周日 07:59写道：
