### ISSUE TITLE
[Feature Request] 书架布局方向锁定

### ISSUE THREAD

**Issue by lqfy-jhc** [gedoor/legado#1299]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 书架的布局，希望能允许锁定"书架"界面屏幕方向，让用户选择（竖屏/横屏/跟随屏幕），最好的话书籍内的方向允许和主界面不同
> 目前只要系统屏幕方向不固定，阅读的主界面方向就会跟着转（书籍内已选固定竖屏）

### 期望实现方式（阅读应该如何实现该功能）
> 1. 设置→主题设置  里添加一个"屏幕方向"选项，作用于主界面（书架/发现/订阅/我的）的布局
> 2. 书籍内的"屏幕方向"只作用于书籍内的阅读界面
> 3. 书籍内的"屏幕方向"再加一个"跟随设置"选项，用来和主界面的方向保持一致（默认"跟随设置"）

### 附加信息（其他的与功能相关的附加信息）
> 不容易实现上面的功能的话，可以接受把书籍内的"屏幕方向"作用范围扩大到全局，只是个人觉得分开控制会好点。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 额这个感觉不好演示啊![Screenshot_20210907120910.png](https://user-images.githubusercontent.com/59348827/132282904-ef824d11-e412-4969-8552-da16ff28233a.png)

**Comment by gedoor** [comment]
有空再弄
