### ISSUE TITLE
[Feature Request] 预下载可以改为打开书籍在启用吗

### ISSUE THREAD

**Issue by zanewayne78** [gedoor/legado#1304]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 新版的预下载只要一更新，离线缓存就启动全部书籍下载，几百部书籍全部下载，希望改回原来的模式

### 期望实现方式（阅读应该如何实现该功能）
> 改回原来的模式，或者改成点开小说阅读时在下载，否则一些还没看的小说全部下载，流量和手机缓存受不了啊

**Comment by zanewayne78** [comment]
清空缓存，再更新好像才这样，书籍预下载10章要等挺长时间，还有可以把预下载的缓存通知隐藏吗，闪一下又消失注意力都被通知栏吸走了

**Comment by gedoor** [comment]
设置里有个预下载章节数的配置

**Comment by zanewayne78** [comment]
> 设置里有个预下载章节数的配置

只能把预下载章节数改为1吗，我的想法是检查更新是预下载1章，点开阅读的时候可以再缓存10章，而不是一更新就开始缓存10章
