### ISSUE TITLE
[Feature Request] 权限不足

### ISSUE THREAD

**Issue by sky2549595028** [gedoor/legado#1308]
### 机型（如Redmi K30 Pro）
>
黑鲨3

### 安卓版本（如Android 7.1.1）
>安卓12以上

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>阅读
3.21.070914
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动

### 问题描述（简要描述发生的问题）
>
安卓系统高版本会有一个特殊权限叫做所有文件访问权限目前阅读不会申请这个权限，导致从QQ下载目录导入的书籍无法正常读取。
### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
安卓12版本以上目录在QQ的下载目录

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
可以直接在qq里打开,不准备申请这个权限了
