### ISSUE TITLE
[BUG] 多次出现退出再进入后当前阅读章节错乱的情况

### ISSUE THREAD

**Issue by siriiiiii** [gedoor/legado#1311]
### 机型（如Redmi K30 Pro）
>
华为nova3

### 安卓版本（如Android 7.1.1）
>
9.1.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.21.090920
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动+电信宽带

### 问题描述（简要描述发生的问题）
>
【进入软件打开一本书看5秒后，当前阅读章节错乱】
退出软件后，下次进入软件有较大概率触发该问题，80%的概率往后跳2-5章，20%的概率往前跳2-5章。
非正常退出（后台划掉，息屏太久自动清理）触发的可能性极大，正常退出软件触发可能性较小，但依然存在

该问题自上上上个版本中打开webdav连接到坚果云后开始出现，再以前使用包括2.0都从未出现过。
曾怀疑是自动同步阅读进度的问题，但是直接取消webdav授权，仍存在这个问题

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
没有其它人反馈过这个问题,我也没有遇到过,暂时没办法确认原因

**Comment by gedoor** [comment]
可能是webDav同步进度的问题,我加个同步开关吧

**Comment by siriiiiii** [comment]
> 没有其它人反馈过这个问题,我也没有遇到过,暂时没办法确认原因

我卸载清缓存重装下再观察一阵子试试

**Comment by siriiiiii** [comment]
> 可能是webDav同步进度的问题,我加个同步开关吧

卸载重装后没开webdav同步，仍然存在这个问题，刚打开小说看个5秒突然章节就跳个2章半，不过问题出现概率大幅度下降了
