### ISSUE TITLE
[BUG] 正文中以书名，标题开头的自动去重会误伤正常内容

### ISSUE THREAD

**Issue by Glavor** [gedoor/legado#1312]
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）

3.21.091421

### 问题描述（简要描述发生的问题）

正文中以书名，标题开头的自动去重会误伤正常内容，例如《三体》

个人认为这个功能不应当默认开启，最好可以只针对特定书开启。
或者改进一下替换净化规则，可以指定规则应用范围为仅正文，仅标题或全部生效。这样正文内书名，标题的净化依然可以方便的靠替换净化规则来实现，不需要软件自身强制进行净化。

正确内容：

![00](https://user-images.githubusercontent.com/32591808/133358223-a1134b85-a620-4544-a189-5c79bc44ba16.jpg)

![01](https://user-images.githubusercontent.com/32591808/133358315-b402223e-2225-4600-9ea4-ba26eb2a6ada.jpg)

开头的正常内容“三体”被误伤：

![04](https://user-images.githubusercontent.com/32591808/133358228-89bb66e3-9861-4167-95b7-a675e122a077.jpg)

![03](https://user-images.githubusercontent.com/32591808/133358322-86f70d86-0c11-419d-8aca-2f220263be00.jpg)

**Comment by gedoor** [comment]
这个我再改下,书名,标题是单独一行就去了吧,有点麻烦

**Comment by gedoor** [comment]
应该不会误删了
