### ISSUE TITLE
[BUG] 纯文本小说阅读页面排版抖动

### ISSUE THREAD

**Issue by s949492225** [gedoor/legado#1313]
### 机型（如Redmi K30 Pro）
>所有

### 安卓版本（如Android 7.1.1）
>10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 所有

### 问题描述（简要描述发生的问题）
> 阅读界面，点击屏幕中央弹出菜单，导致显示文本的view变小，这时候排版会变化，建议标题栏和菜单才用浮层的方式显示，实现难度小，改动不大，这样文本view没有高度变化，排版自然不会抖动

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开一本纯文本的小说，注意当前排版，点击屏幕中央弹出标题栏和底部菜单，此时排版出现变换，关闭菜单和标题栏后又会恢复

**Comment by gedoor** [comment]
目前就是浮动显示的啊

**Comment by s949492225** [comment]
问题是现在弹出来后会导致显示文本的view高度产生变化，进而排版也发生变化，期望弹出后文本view高度不变化，排版不变化
