### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 417710661** [gedoor/legado#1320]
### 机型（如Redmi K30 Pro）
>MEIZU 17 PRO

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.0.91611

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>WiFi电信宽带

### 问题描述（简要描述发生的问题）
>使用web看书结束后，手机端章节跟目录显示是同步的，但是打开后还是原先手机端阅读的内容。需要在目录重新点击当前章节

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

![Video_20210917_090851_483](https://user-images.githubusercontent.com/71995981/133707840-20d8f3b9-f320-4aee-b93a-1753a1a2246a.gif)

![S10917-09092230](https://user-images.githubusercontent.com/71995981/133707992-2c559513-dfa8-4730-9f16-97e5d2e452d9.png)
![S10917-09092541](https://user-images.githubusercontent.com/71995981/133708001-1fd0f245-b395-4cdf-9c1c-c53b647e0b16.png)

**Comment by gedoor** [comment]
我看下
