### ISSUE TITLE
[BUG] 换源(搜索)时快速终止，无法为书籍更换书源

### ISSUE THREAD

**Issue by lqfy-jhc** [gedoor/legado#1323]
### 机型（如Redmi K30 Pro）
>金立s10

### 安卓版本（如Android 7.1.1）
>7.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.091421
3.21.091512
3.21.091611
都有这个问题

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>任意网络

### 问题描述（简要描述发生的问题）
>搜索时不到一秒就自动结束，没有搜索到需要的书籍(书籍为书架内存在的小说，想换个源，搜索直接不到一秒停止，书籍内换源情况一样)，非书架的书籍也一样

### 使用书源（填写URL或者JSON）
>书源加视频

https://www.aliyundrive.com/s/141Qq23pG1d

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>步骤在视频里

### 日志提交（问题截图或者日志）
>软件没有崩溃，没有崩溃日志，有视频记录，都在链接文件夹里

**Comment by gedoor** [comment]
可能你选的换源分组不对

**Comment by lqfy-jhc** [comment]
•ᴗ•谢谢，切换源分组后恢复正常了，切换回之前的 全部书源 也能够正常刷新更换了•ᴗ•
