### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ReflectedInTheSnow** [gedoor/legado#1324]
### 机型（如Redmi K30 Pro）
>一加8pro

### 安卓版本（如Android 7.1.1）
>安卓11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21091611

### 问题描述（简要描述发生的问题）
>朗读跳段

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开按页朗读之后，翻页后恰好是新一段时，这一段读两个字后会自动跳过

**Comment by gedoor** [comment]
已解决
