### ISSUE TITLE
[Feature Request] 求助！！有网站搜索需要访问取值才能知道搜索地址怎么写

### ISSUE THREAD

**Issue by xiaerzhuanyong** [gedoor/legado#1326]
网址:                                                http://www.fushuwang365.com
搜索{我的}网站源码是:                            <head></head><body>Table 'phome_enewssearch' is read only<br>update ***_enewssearch set searchtime='1631962569',result_num='765',onclick=onclick+1,orderby='newstime',myorder='0',tempid='0' where searchid='40333'</body>
需要取searchid值:                             40333
需要访问搜索{我的}结果的地址:        http://www.fushuwang365.com/e/search/result/?searchid=40333

书源:[
  {
    "bookSourceComment": "",
    "bookSourceGroup": "书源",
    "bookSourceName": "365美文网",
    "bookSourceType": 0,
    "bookSourceUrl": "http://www.fushuwang365.com",
    "customOrder": 234,
    "enabled": true,
    "enabledExplore": true,
    "exploreUrl": "",
    "lastUpdateTime": 1631960824774,
    "loginUrl": {
      "url": "null"
    },
    "ruleBookInfo": {
      "author": "",
      "coverUrl": "",
      "init": "",
      "intro": "",
      "kind": "",
      "lastChapter": "",
      "name": "",
      "wordCount": ""
    },
    "ruleContent": {
      "content": "",
      "imageStyle": "0"
    },
    "ruleExplore": {
      "author": "",
      "bookList": "",
      "bookUrl": "",
      "coverUrl": "",
      "intro": "",
      "kind": "",
      "name": "",
      "wordCount": ""
    },
    "ruleSearch": {
      "author": "",
      "bookList": "",
      "bookUrl": "",
      "coverUrl": "",
      "intro": "",
      "kind": "",
      "lastChapter": "",
      "name": "",
      "wordCount": ""
    },
    "ruleToc": {
      "chapterList": "",
      "chapterName": "",
      "chapterUrl": ""
    },
    "searchUrl": "/e/search/index.php,{\n  \"charset\": \"gb2312\",\n  \"method\": \"POST\",\n  \"body\": \"keyboard={{key}}&show=title,softwriter,writers\"\n}",
    "weight": 0
  }
]

**Comment by gedoor** [comment]
可以用js里的java.ajax取值
