### ISSUE TITLE
[BUG] 语音朗读时的自动翻页问题

### ISSUE THREAD

**Issue by guo0001jian** [gedoor/legado#1334]
### 机型
>huawei mate30 pro

### 安卓版本
>harmony 2.0

### 阅读Legdao版本
>3.21.091611

### 问题描述（简要描述发生的问题）
>
语音朗读时，如果有跨页的一段，软件不能跟随朗读进度自动翻页，只有这一段全部朗读完，开始朗读下一段的时候才能翻页。

```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
语音朗读时，如果有跨页的一段，软件不能跟随朗读进度自动翻页，只有这一段全部朗读完，开始朗读下一段的时候才能翻页。

**Comment by o0HalfLife0o** [comment]
因为朗读时默认是一段一段的提交的，很难逐字判断朗读焦点来翻页
但是如果改成当前朗读段落置屏首，也就是按段落翻页，不知道会不会容易实现 @gedoor

**Comment by gedoor** [comment]
谷歌TTS会发送播放进度,会及时翻页,其它语音好像不行,没办法判断朗读到哪里了

**Comment by gedoor** [comment]
下版本就可以自动翻页了,我用了平均速度计算当前朗读到哪里了

**Comment by o0HalfLife0o** [comment]
谢谢 @gedoor
