### ISSUE TITLE
[Feature Request] 希望增加点击任意段落开始朗读的功能

### ISSUE THREAD

**Issue by someok** [gedoor/legado#1335]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 类似「多看阅读」的朗读模式，点击任意段落的时候，从该段落开头开始朗读

### 期望实现方式（阅读应该如何实现该功能）
> 点击「朗读」按钮后，按照现有模式从头开始朗读，但支持点击任意段落，点击后则从该段落开头朗读。

**Comment by gedoor** [comment]
有跳转上一段下一段的方法了
