### ISSUE TITLE
[BUG] 错误字体没有被替换，手动调整字体可以正常显示

### ISSUE THREAD

**Issue by syomie** [gedoor/legado#1339]
### 安卓版本（如Android 7.1.1）
> 9.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.092121

### 问题描述（简要描述发生的问题）
> 字体替换相关函数问题
错误字体没有被替换，手动调整字体可以正常显示

### 使用书源（填写URL或者JSON）
> 红袖招 链接导入
https://shuyuan.miaogongzi.cc/shuyuan/b0a13a1705184b949198faeabb307bfd.json
有效期2天，失效参考二维码导入
![qr.png](https://user-images.githubusercontent.com/55239702/134311077-d070a31c-8b89-4546-9c0d-bf0d5cd2c15e.png)

**Comment by gedoor** [comment]
我试试

**Comment by gedoor** [comment]
我看了下感觉还是字体问题

**Comment by syomie** [comment]
> 我看了下感觉还是字体问题

下载字体，然后在界面-字体选用可以正常显示。。
