### ISSUE TITLE
[BUG] 章节标题没有了

### ISSUE THREAD

**Issue by atjjme** [gedoor/legado#1341]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

![Screenshot_20210922-190518_Keep Notes](https://user-images.githubusercontent.com/4524111/134332896-045ba9e6-44d4-43be-a6ae-60f9d6517059.jpg)
### 阅读Legdao版本（我的-关于-版本,如3.21.092208）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
章节标题没有了，似乎是0909版本以后出现的，两部手机上都这样，重新安装0909及以前的版本不会出现这问题

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by ju0632** [comment]
净化规则更新一下

**Comment by atjjme** [comment]
> 净化规则更新一下

怎么更新？删除了再从网上的地方载入吗，里面有我自己添加的一些规则，不好删除
我用了最笨的方法，检查后删除了三条规则才恢复的

**Comment by Differenter** [comment]
净化规则使用飞哥推荐的那个导入就行，自己添加的容易出问题

atjjme ***@***.***> 于2021年9月23日周四 上午10:26写道：
