### ISSUE TITLE
[Feature Request] 目录规则中添加兜底规则

### ISSUE THREAD

**Issue by ghost** [gedoor/legado#1346]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 如果没有符合目录规则的书现在会默认按照长度划分章节，但此默认规则无法手动指明。因为有些书章节名字混乱，偶尔会恰巧符合某个目录规则，但实际上很多标题都识别不了。这就会造成一个超级大章的出现，甚至会出现整本书都在这一章内，打开会很卡。所以希望在目录规则那里，增加一个按长度划分目录的兜底规则，能让用户手动指明使用。

### 期望实现方式（阅读应该如何实现该功能）
> 在目录规则那里，增加按长度划分目录的默认兜底规则

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by bAdOoWindy** [comment]
应该是相关的情况,我使用Txt目录正则-目录

具体正则是
`^[ 　\t]{0,4}(?:序章|序言|卷首语|扉页|楔子|正文(?!完|结)|终章|后记|尾声|番外|第?\s{0,4}[\d〇零一二两三四五六七八九十百千万壹贰叁肆伍陆柒捌玖拾佰仟]+?\s{0,4}(?:章|节(?!课)|卷|集(?![合和])|部(?![分赛游])|篇(?!张))).{0,30}$`
此时如下内容分章节失败
`第九卷 第二章 这是标题

这是正文`
