### ISSUE TITLE
屏幕超时

### ISSUE THREAD

**Issue by windouxp** [gedoor/legado#1348]
屏幕超时是到时间就关屏的意思吗？小米11到时间不关屏幕

**Comment by gedoor** [comment]
屏幕超时不会小于系统的息屏时间

**Comment by windouxp** [comment]
好的 ，感谢&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月28日(星期二) 晚上6:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gedoor/legado] 屏幕超时 (#1348)





 
屏幕超时不会小于系统的息屏时间
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
