### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Codebglh** [gedoor/legado#1349]
### 机型（如Redmi K30 Pro）
>
1+ 9r

### 安卓版本（如Android 7.1.1）
>
Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.20.112220
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
![Screenshot_2021-09-27-19-23-25-42_90024215e504237](https://user-images.githubusercontent.com/63567640/134899198-304082ba-373d-4294-b54f-e8c1800aff54.jpg)

### 问题描述（简要描述发生的问题）
>
无法导入本地txt文件

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
没看出来哪里不能导
