### ISSUE TITLE
章节标题净化代码，需要不需要合并进来？

### ISSUE THREAD

**Issue by wqfantexi** [gedoor/legado#135]
处理了一下，把章节标题净化了，但是没有用配置文件，默认在显示时进行净化。
用正则表达式处理的。
(?<=.{1,20})[(（].*(推荐|章合|月票|收藏|点赞|保底|盟主|首订|全订|订阅|鲜花|大章|快乐|打赏|更新|谢谢|[三四五六七八九3-9][千万]字|第[一二三四五六七八九0-9]更|加[一二三四五六七八九0-9]?更).*[)）](?=\s{0,10})

要不要合并进来，需要的我发PR

**Comment by Antecer** [comment]
建议作为单独的净化源发布,尽量不要把规则写死在代码里面,毕竟你都不知道会碰到哪些奇葩的小说.

**Comment by Celeter** [comment]
合进来的话，遇到奇葩的小说会有问题
