### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by 2802580445** [gedoor/legado#1353]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 阅读的朗读功能希望可以加一个功能，类似于QQ音乐/网易云的桌面歌词悬浮窗

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
有点花里胡哨了,暂不考虑
