### ISSUE TITLE
[BUG] 小横条沉浸失效

### ISSUE THREAD

**Issue by lq-259** [gedoor/legado#1354]
### 机型（如Redmi K30 Pro）
>
Redmi K20

### 安卓版本（如Android 7.1.1）
>
android11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
版本 3.21.100223
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
小横条无法沉浸

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>
![Screenshot_20211003-004338](https://user-images.githubusercontent.com/60541200/135725300-950418b4-2421-42c1-8c32-2a9b256caaf3.png)

**Comment by gedoor** [comment]
这个不会修复了,用了沉浸会引起其它bug,可以隐藏导航栏
