### ISSUE TITLE
[Feature Request] 内置一个阿里云语音专用的朗读引擎设置

### ISSUE THREAD

**Issue by RinOrz** [gedoor/legado#1357]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
朗读功能建议添加一个阿里云的单独设置。因为阿里的token几天就会变一次，每天去复制新的再修改很麻烦，增加AccessKeyId和AccessKeySecret参数来自动获取token会舒服很多

获取 Token 的 SDK：
https://help.aliyun.com/document_detail/72153.htm?spm=a2c4g.11186623.0.0.762618195dqZeK#title-j7l-clf-hgy

现在的请求参数：
https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/tts?appkey=********&token=*******&text={{encodeURIComponent(speakText)}}&format=mp3&sample_rate=16000&volume=100

**Comment by gedoor** [comment]
好的

**Comment by gedoor** [comment]
https://help.aliyun.com/document_detail/72153.htm?spm=a2c4g.11186623.0.0.762618195dqZeK#title-j7l-clf-hgy
这个里面的参数分别是什么

**Comment by gedoor** [comment]
已添加登录功能

**Comment by RinOrz** [comment]
@gedoor 请问新加入的参数分别是什么呢
![Uploading image.png…]()
