### ISSUE TITLE
[Feature Request] 希望可以防止网页进行去广告检测

### ISSUE THREAD

**Issue by yahcme** [gedoor/legado#1362]
同一个网站，在浏览器用adblock去广告不会有问题，但是在阅读里访问时会提示关闭去广告并且无法查看内容

**Comment by EdisonYo** [comment]
内置的浏览器不加载脚本，这是阅读的基础设定，所以才快，因为不加载脚本所以会有检测提醒，不要阅读当成浏览器使用，能获取到正文就行了，如果真有需要，那跳到浏览器。
