### ISSUE TITLE
[BUG] 阅读网页端正文出现章节标题

### ISSUE THREAD

**Issue by fwzuw** [gedoor/legado#1367]
### 安卓版本（如Android 7.1.1）
>9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>legado_app_3.21.100821

### 使用书源（填写URL或者JSON）
>所有

### 日志提交（问题截图或者日志）
>网页端
![image](https://user-images.githubusercontent.com/48246272/136896307-4d7f1b9c-65df-4077-97d3-2e23c30ee77c.png)
手机端（未应用净化）
![image](https://user-images.githubusercontent.com/48246272/136896655-2d40350b-ff3a-4c8e-9b4a-b5150a1dceb9.png)

**Comment by gedoor** [comment]
下版本修复
