### ISSUE TITLE
[BUG] 新版登录的阿里云语音无法朗读

### ISSUE THREAD

**Issue by minoism** [gedoor/legado#1371]
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> https://github.com/gedoor/legado/releases/tag/3.21.101221

### 问题描述（简要描述发生的问题）
> 与 https://github.com/gedoor/legado/issues/1357 有关
![image](https://user-images.githubusercontent.com/58068445/137071242-e2b1bc64-aa1b-4560-add9-a350bc6680a5.png)
均已填入，但播放没有反应

如果需要，我可以提供相关的密文

**Comment by gedoor** [comment]
奇怪,我这边测试了没有问题啊,token参数不用加,规则直接加到访问头里面了,我再试试啊

**Comment by RinOrz** [comment]
坐等
