### ISSUE TITLE
[BUG] Web服务进度同步问题

### ISSUE THREAD

**Issue by 1552980358** [gedoor/legado#1374]
### 机型（如Redmi K30 Pro）
> 小米10Ultra

### 安卓版本（如Android 7.1.1）
> 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.101221

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> HKT

### 问题描述（简要描述发生的问题）
> Web服务在电脑阅读的章节号虽然能在手机主页同步，但是手机内点击书本后并没有同步进度，需要在目录点击当前章节号才能同步内容

### 使用书源（填写URL或者JSON）
>
### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 打开Web服务，在电脑端点击书本，进去下一章，返回手机APP，主页的章节号已经变了，点进去进度没变
### 日志提交（问题截图或者日志）
>

**Comment by 1552980358** [comment]
正在排查，待修复后会自行PR并Close

**Comment by letterk** [comment]
这个bug早就存在了, 实际阅读是更改了的, 应该是那里没刷新
需要重启阅读app才正常
