### ISSUE TITLE
[BUG] 阿里云语音规则存在问题

### ISSUE THREAD

**Issue by RinOrz** [gedoor/legado#1377]
### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 如果读到的行只有符号没有中文将会卡住不会进行下一行的朗读

例如
```
　　“该回去了。”
　　.....
　　.....
　　Ps：明天一章写完，第一卷就算是彻底结束了，至于为什么不是今天结束...
```
读完 `该回去了` 后将一直停留在 `.....` 上

与 https://github.com/gedoor/legado/issues/1357 有关

**Comment by gedoor** [comment]
应该......不会返回语音,我看看

**Comment by agutools** [comment]
legado_app_3.21.101420
百度在线TTS也存在同样的问题

**Comment by RinOrz** [comment]
@gedoor 是的

**Comment by gedoor** [comment]
应该不会出现这种情况啊

**Comment by ag2s20150909** [comment]
> 应该不会出现这种情况啊

下载前先判断是否全是不发音的符号，如果是就跳过

**Comment by olbb** [comment]
替换解决不了根本问题吧  各种符号 特殊字符 生僻字 什么的

**Comment by gedoor** [comment]
应该没问题了,
