### ISSUE TITLE
[BUG] 阅读引擎无法加载

### ISSUE THREAD

**Issue by 56800337** [gedoor/legado#1382]
机型
华为
阅读Legdao版本（3.20.112220）
__________
问题描述

最近朗读引擎里部分不能加载或加载错误。
研究后是pdt值160这个数不能加载了！
pdt=改成16成功加载。
______________________
解决办法
设置-朗读引擎-编辑-温柔女声
修改pdt=16

http://tts.baidu.com/text2audio,{
    "method": "POST",
    "body": "tex={{java.encodeURI(java.encodeURI(speakText))}}&spd={{(speakSpeed + 5) / 10 + 4}}&per=4126&cuid=baidu_speech_demo&idx=1&cod=2&lan=zh&ctp=1&pdt=16&vol=5&aue=6&pit=6&_res_tag_=audio"
}

**Comment by gedoor** [comment]
ok
