### ISSUE TITLE
[Feature Request]  请求朗读功能分段切换是减少暂停时间

### ISSUE THREAD

**Issue by 0x5c0f** [gedoor/legado#1386]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 目前朗读功能，比如说非系统tts，在朗读的时，每到分段的切换的时候，都会有明显的暂停，是否可以取消或减少这个暂停的时间。

### 期望实现方式（阅读应该如何实现该功能）
> 目前软件有一个”重新分段“的功能，此功能实际上已经解决了一部分问题，比如章节分段特别多的时候，会自动合并一些，但此解决方案只是让小说阅读有了更好的体验，但如果使用朗读，体验仍然不是很好，在切换分段的时候始终会出现较大的停顿，我个人觉得可以实现的方案是，添加一个新的分段功能，把整个章节合并为一个段落。这样朗读的时候应该就只会在切换章节的时候出现朗读卡顿。或者减少切换段落时候的间隔

### 附加信息（其他的与功能相关的附加信息）
> 关于上诉功能，第三方的tts转换，可能也不支持这么多字的转换，希望能有更好的方案

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 关于效果演示，这个实际上应该和重新分段一样，只是我想的是把整个章节合并为一个段落，这样在使用朗读功能的时候就只会在切换章节的时候出现卡顿了

**Comment by laulguo** [comment]
> 按句读

现在可以按句读吗

**Comment by eromoe** [comment]
我更新以后每一段暂停时间都很长，不知道要怎么配置。
