### ISSUE TITLE
[BUG] sony dpt-rp1上，底部操作按钮没反应

### ISSUE THREAD

**Issue by 0987363** [gedoor/legado#1398]
### 机型（如Redmi K30 Pro）
> sony dpt-rp1

### 安卓版本（如Android 7.1.1）
> 5.1.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21

### 问题描述（简要描述发生的问题）
> 在书籍的阅读界面，点击屏幕中间，底部出现操作按钮，点击底部所有操作按钮都无效，无法弹出操作项

**Comment by Kalinundefined** [comment]
fixed #2199
