### ISSUE TITLE
[Feature Request] 关于文中搜索定位的建议！

### ISSUE THREAD

**Issue by Norkii** [gedoor/legado#1400]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在小说里使用搜索查找关键词后，找到一些结果，在点击进入相关章节后，想要再次查找关键词的时候却又是从头开始显示，需要从头向下翻。希望修改为搜索后显示的结果，定位到当前阅读页面或者后面最近的那个结果。

### 期望实现方式（阅读应该如何实现该功能）
>搜索后显示的结果，定位到当前阅读页面或者后面最近的那个结果。
 

### 附加信息（其他的与功能相关的附加信息）
> 可参考爱读掌阅里的搜索功能。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 0xAmad3us** [comment]
+1
kindle也是有这个功能的，很需要这个功能，希望未来可以实现
