### ISSUE TITLE
[BUG] epub多级目录识别不全

### ISSUE THREAD

**Issue by laulguo** [gedoor/legado#1408]
### 机型（如Redmi K30 Pro）
>Redmi K30S Ultra

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.102414

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>无影响

### 问题描述（简要描述发生的问题）
>epub多级目录识别失败

### 使用书源（填写URL或者JSON）
>无影响

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开有多级目录的EPUB即可

### 日志提交（问题截图或者日志）
>

[多级目录电子书EPUB.zip](https://github.com/gedoor/legado/files/7466970/EPUB.zip)

**Comment by laulguo** [comment]
![APP内识别](https://user-images.githubusercontent.com/38545281/140047695-59832dc4-b4d1-464a-b744-4be1c413c8f3.jpg)
![sumatrapdf识别](https://user-images.githubusercontent.com/38545281/140047709-85a44689-773a-41c2-b7f5-31dcf0398448.JPG)
两者分别为sumatrapdf识别与阅读APP识别的目录信息

**Comment by rihalvnium76** [comment]
我这个也是，SumatraPDF识别的目录完整
而APP（legado_app_3.21.111418）识别残缺，而且**没有体现目录分级**
![image](https://user-images.githubusercontent.com/57667144/141685334-ed9d7b60-2bab-4d8a-94a6-913aa844996a.png)
[Seventh9日麻教程（79博客）v1.2.zip](https://github.com/gedoor/legado/files/7533922/Seventh9.79.v1.2.zip)
