### ISSUE TITLE
[BUG] 部分网上下载的EPUB书籍每一章只能显示第一页，翻页就会翻到下一章

### ISSUE THREAD

**Issue by AlynxZhou** [gedoor/legado#1409]
### 机型（如Redmi K30 Pro）

Galaxy S9+

### 安卓版本（如Android 7.1.1）

10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）

3.21.110219

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）

本地EPUB文件，不涉及网络

### 问题描述（简要描述发生的问题）

打开一些下载到本地的EPUB书籍的时候，每一章都只有第一页，翻页就会翻到下一章的开头，完全没有办法阅读到各章的内容。在电脑上使用 Calibre 等软件打开同样的文件没有任何问题。

### 使用书源（填写URL或者JSON）

无

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）

1. 比如以这本贴吧翻译的二世事件簿EPUB文件为例：[君主·埃尔梅罗二世的冒险 Vol.1 吞食神明的男子.zip](https://github.com/gedoor/legado/files/7472838/Vol.1.zip)，下载解压并导入 APP（GitHub 不支持 EPUB 上传所以压缩了）。
2. 打开这本书然后翻页，会发现每章都只显示一页，一翻就到下一章开头。
3. 不止一个文件有这种问题，在其他软件上打开都能正常浏览到内容。

### 日志提交（问题截图或者日志）

贴上一段录屏，可以看到问题：

https://user-images.githubusercontent.com/8444615/140270818-e9c31501-9708-4160-b4b0-fafd198c4069.mp4

同一个文件用 Calibre 打开是这样的：

![Screenshot from 2021-11-04 14-59-46](https://user-images.githubusercontent.com/8444615/140270884-5b30ca88-ab38-4f97-995b-0ee42e1b2d75.png)

这个问题困扰我很久了，但是因为不好描述我没搜到相关的 issue，所以自己开了一个。

**Comment by AlynxZhou** [comment]
> 由于长期没有状态更新，该问题将于5天后自动关闭。如有需要可重新打开。

我能说的都说了，没有开发者来回答呀

**Comment by GrayWei001** [comment]
感觉开发者对于 epub的用户不是很关心 也可能是有更需要的功能和bug需要维护吧，这个优先级低点。我现在改用掌阅了，至少看epub的书籍还是没有问题的。- -！
