### ISSUE TITLE
书源获取目录页没有链接的章节

### ISSUE THREAD

**Issue by SainoNamkho** [gedoor/legado#1417]
### 功能描述（请清晰的、详细的描述你想要的功能）
有的网页的目录页中部分章节只有文本没有链接，其余大多数为超链接
### 期望实现方式（阅读应该如何实现该功能）
支持从目录页获取章节名（目前可以做到）
并从邻近章节（如下一章节网页的”上一章“按钮）获取章节链接。

看了一下书源的编写规则，似乎没有比较好的解决方案。
请问这种情况有什么推荐的书源写法吗，如果没有，希望在阅读里支持。

**Comment by darkflame0** [comment]
目前我的做法是，如果遇到没有的章节就多读取一章（在读取正文的时候会用当前url跟下一章节的url做对比，如果读到了下一章节就会自动停止读取正文），这样子至少可以不少读

**Comment by darkflame0** [comment]
目前我的做法是，如果遇到目录没有链接的章节就多读取一章。

目前软件的机制是：读取正文的时候会用当前待读取的url与下一章节的url做对比，如果读到了下一章节就会自动停止读取正文

也就是说，读到下一章之前就会自动停止，但是如果不匹配的话，就会下一页下一页下一章一直读下去，只要做好判断，只多读一章就行了

**Comment by darkflame0** [comment]
目前我的做法是，如果遇到目录没有链接的章节就多读取一章，保证不漏就行

目前软件的机制是：读取正文的时候会用当前待读取的url与下一章节的url做对比，如果读到了下一章节就会自动停止读取正文

也就是说，读到下一章之前就会自动停止，但是如果不匹配的话，就会下一页下一页下一章一直读下去，只要做好判断，只多读一章就行了

一般情况下也很少有连续漏的，基本也够用了

**Comment by darkflame0** [comment]
目前我的做法是，在阅读的时候，如果遇到目录没有链接的章节就多读取一章，保证不漏就行

目前软件的机制是：读取正文的时候会用当前待读取的url与下一章节的url做对比，如果读到了下一章节就会自动停止读取正文

也就是说，读到下一章之前就会自动停止，但是如果不匹配的话，就会下一页下一页下一章一直读下去，只要做好判断，只多读一章就行了

一般情况下也很少有连续漏的，基本也够用了


不过这种做法仍然没有办法直接跳转到没有链接的章节
