### ISSUE TITLE
[Feature Request] 增加本地书籍同步 

### ISSUE THREAD

**Issue by cxhttt233** [gedoor/legado#1418]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
可以单独选择阅读中的本地书籍进行同步
### 期望实现方式（阅读应该如何实现该功能）
> 
在云备份的时候，本地书籍进度会被备份，但是并未在其他设备得到有效的使用，可以在其他设备重新链接书籍，选择进度。感觉也就是跳转以下百分比就行了
主要就是能够给其他设备恢复的本地书籍进度重新选择书籍位置。
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by jl0476** [comment]
顶上，希望能增加。
多设备的时候就方便多了！

**Comment by Lorduu** [comment]
同有这个需求，本地书籍同步后在其他客户端无法打开

**Comment by censujiang** [comment]
同样有这个需求

**Comment by censujiang** [comment]
已经一年多了，这个需求还是没做。

**Comment by gedoor** [comment]
好的,我考虑一下

**Comment by qianfanguojin** [comment]
> 好的,我考虑一下

最近我在尝试做一下这个需求，同样使用 WebDav 来进行同步

我都逻辑是这个样子的：

1. 书籍放在 WebDav 的服务器（指定名字的，如legado/books ）文件夹中
2. 有一个页面来获取并展示这个书籍列表，这个页面，同时可以选择下载某本书到本地，这里可以做个判断这本书本地是否已导入，已导入则不可下载
3. 下载下来之后可以按照导入本地书籍的例子,导入阅读即可

安卓小菜鸡，想试试看
