### ISSUE TITLE
[BUG] Moaan MIX7软件内调用系统文件夹选择器报错

### ISSUE THREAD

**Issue by pretenderlu** [gedoor/legado#1420]
### 机型（如Redmi K30 Pro）
>Moaan MIX7 墨案墨水屏阅读器

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.110219

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>调用系统文件夹选择器报错，导致无法读取上传的字体，无法长按恢复。可能是moaan系统本身的原因，但是有其他第三方软件没有出现类似问题，譬如Alreader等。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>调用系统文件夹选择器，就会复现

### 日志提交（问题截图或者日志）
[>报错截图](https://drfs.ctcontents.com/file/3285011/520124067/71c4b7/%E8%87%AA%E7%94%A8%E5%9B%BE%E5%BA%8A/Screenshot_20211109-105607.png
)

**Comment by gedoor** [comment]
收到,下版本使用系统文件夹选择器出错时自动打开应用文件夹选择器,部分系统文件夹选择器被阉割了
