### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xinbingyiran** [gedoor/legado#1422]
### 机型（如Redmi K30 Pro）
>
ZTE Blade A7

### 安卓版本（如Android 7.1.1）
>
Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.21.110219

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
任意网络或离线

### 问题描述（简要描述发生的问题）
>
使用本地TTS引擎朗读时，不能正常朗读，表现形式为快速跳过。

### 使用书源（填写URL或者JSON）
>
任意

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
任意打开一本书箱，选择系统TTS，然后朗读。

### 日志提交（问题截图或者日志）
>

https://user-images.githubusercontent.com/2202252/141039316-c54282a3-44a2-4028-9af1-93359eeb0c77.mp4

**Comment by gedoor** [comment]
你看看你的本地tts是不是中文的

**Comment by xinbingyiran** [comment]
> 你看看你的本地tts是不是中文的

是中文的，而且系统的TTS只有中文，系统TTS设置界面如图所示

![3e53885a3a7139cdd974bf1657f5b74](https://user-images.githubusercontent.com/2202252/141037197-1cf977b5-e31f-4a5f-9fc5-1cefd03f16d6.jpg)

**Comment by gedoor** [comment]
播放按钮能正常播放吗

**Comment by xinbingyiran** [comment]
https://user-images.githubusercontent.com/2202252/141038850-a312aece-a124-481d-8471-b4aba2835103.mp4

能播放，但不能算正常播放，就像视频上这样：点播放后，开始播放，但不等上一个播放完，就快速进行下一段；如果点了停止，会将最后一个播放到的段落正常播放完。

**Comment by gedoor** [comment]
重新安装个tts试试,比如谷歌语音,看看是系统兼容问题还是tts问题

**Comment by xinbingyiran** [comment]
> 重新安装个tts试试,比如谷歌语音,看看是系统兼容问题还是tts问题

百度在线播放是正常的。

**Comment by gedoor** [comment]
你这是本地问题,肯定要重新安装个本地tts测试啊,本地和在线不一样的

**Comment by xinbingyiran** [comment]
> 你这是本地问题,肯定要重新安装个本地tts测试啊,本地和在线不一样的

我安装了几个本地引擎并测试，结果是一样的：

https://user-images.githubusercontent.com/2202252/141045878-b86fea8c-fc32-4b80-b7d6-b864518898b5.mp4

**Comment by xinbingyiran** [comment]
> > 你这是本地问题,肯定要重新安装个本地tts测试啊,本地和在线不一样的
> 
> 我安装了几个本地引擎并测试，结果是一样的：
> 
>  74f271ae052371421767684b974a6b83.mp4

后来我又重启了一下app，结果讯飞的就可以正常使用了。看来真是系统TTS的问题了。
