### ISSUE TITLE
[BUG]长时间朗读跳行ヾ(Ő∀Ő๑)ﾉ

### ISSUE THREAD

**Issue by 56800337** [gedoor/legado#1423]
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 问题描述（简要描述发生的问题）
>

使用百度朗读时读着读着就没有声音了，朗读光标还在走行就是没有声音！
清除缓存后恢复正常！
不知道是不是我手机安装第三方系统原因！

希望大佬们设计个定时清除缓存功能！

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

**Comment by lzhiye** [comment]
我也遇到了同样的情况，听着听着没声音了，解锁手机查看发现变色强调行在继续向下走，但没有声音，也是清除缓存后即可恢复正常，这个情况已经跨了很多版本了，一直存在，包括当前最新的3.21.121021，我的系统是MIUI12.5
