### ISSUE TITLE
希望增加多级章节名和独立设置入口的自定义目录规则功能

### ISSUE THREAD

**Issue by rihalvnium76** [gedoor/legado#1424]
### 功能描述（请清晰的、详细的描述你想要的功能）
对于**本地TXT/EPUB**，自带的目录规则不好用（例子见下），而且自定义目录规则（目录正则）的入口缺乏足够的提示过于难找到（只有图标没有文字提示，且入口按钮只有一个）

例如含有章节名某一行：“始动！终结者之逆袭！ 第一章 洛杉矶1984”，应该将**这一行文字**原样显示，
或者像起点那样，“始动！终结者之逆袭！”作为卷名，“第一章 洛杉矶1984”作为章节名，
而不是“始动！终结者之逆袭！ ”划分到上一章结尾，章节名为“第一章 洛杉矶1984”

#1294 所提到的问题我觉得并没有得到有效解决就被关闭了
#1408 反馈的问题也是适用于TXT中上述有卷名和章节名的情况

### 期望实现方式（阅读应该如何实现该功能）
1. 像净化规则那样，在主界面的“我的”界面中，以及【任何来源（包含本地）】的书籍的目录界面中，再弄一个目录规则的入口与界面，以随时选择与配置目录规则，且每本书的目录规则可以单独记录，单独配置的自制规则优先级最高
2. 增加多级章节名以树的形式显示的功能

**Comment by gedoor** [comment]
好的

**Comment by zmn001125** [comment]
换源按钮指的是正文页的换源按钮，而且只有txt格式才有
