### ISSUE TITLE
导出进度直观化

### ISSUE THREAD

**Issue by kknd019** [gedoor/legado#1425]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 当前选择导出后，会在最下方显示正在导出，但不知道进度如何，特别是章节数较多的情况下，无法知道何时结束。
这里还有一个问题，不知道是不是bug，就是在导出过程中，如果切换出APP，导出就会中止（目标文件夹的文件大小不在变化，切换回APP后，导出也没有继续。

### 期望实现方式（阅读应该如何实现该功能）
> 一个简单的实现方式，就是显示类似于下载进度一样的“XXX/XXXX”的提示

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
正在导出“书名”，1/1000

**Comment by gedoor** [comment]
你用的不是最新版本吧,最新版本每本书导出都有进度条
