### ISSUE TITLE
阅读时闪的厉害[BUG] 

### ISSUE THREAD

**Issue by hellottyp** [gedoor/legado#1427]
这个是核心功能，看久了就头晕眼花，对比其他阅读软件就不会，不然其他功能做的再好也没用啊。另外，自带的主题好好调整一下吧，没几个舒服的

**Comment by rihalvnium76** [comment]
（不给作者提供crash日志吗）

**Comment by hellottyp** [comment]
这哪里有啥日志啊，就是细微的闪烁感，又好像是字体配色引起的，感觉就是没老牌阅读器好。忘记说了，是逐行滚动模式

**Comment by rihalvnium76** [comment]
> 这哪里有啥日志啊，就是细微的闪烁感，又好像是字体配色引起的，感觉就是没老牌阅读器好。忘记说了，是逐行滚动模式

同滚动模式，滑动时屏闪得太厉害了，估计是显示刷新频率或者刷新方法有问题
（因为调用WebView的普通浏览器看小说没有这个问题）

**Comment by DarkForestHello** [comment]
> 
通过开发者选项里的HWUI呈现分析进行查看， 发现阅读3.0在滚动阅读的时候，帧生成时间很长， 算下来只有十几帧的帧率，所以即使是高刷屏幕也会显得一滚一卡，因为渲染帧率就不够。 
通过开发者选项里的过度绘制分析， 发现阅读3.0在滚动阅读时整个阅读界面都存在4X以上重复绘制的问题。
