### ISSUE TITLE
本地txt 部分内容显示加载中

### ISSUE THREAD

**Issue by zhupengxiang** [gedoor/legado#1428]
### 机型（如Redmi K30 Pro）
mi8

### 安卓版本（如Android 7.1.1）
10.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
3.21.111418

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
wifi

### 问题描述（简要描述发生的问题）
导入本地txt   txt格式为第**卷  第**章  滑动到卷和章中间时候   页面显示加载中   在接着往上滑动显示正常   下面是两张对比图

### 使用书源（填写URL或者JSON）
本地txt文件

[book.zip](https://github.com/gedoor/legado/files/7543054/book.zip)
### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
就滑动到卷和第一章内容之间  来回滑动即可

### 日志提交（问题截图或者日志）
![image](https://user-images.githubusercontent.com/17894209/141888640-fcc0ebd6-ea6a-40ae-b179-e8ec56a7e024.png)
![image](https://user-images.githubusercontent.com/17894209/141888654-342ec6eb-96ea-48af-a612-a735cadfba31.png)

**Comment by zero-hugo** [comment]
本地导入的TXT文档，阅读几章之后，后面的就变成自动加载中……，只有把书籍从软件中删除，然后重新添加才能解决。但是在阅读一段时间之后，不知道什么时候又会变成自动加载中，一直卡在那里过不去。
