### ISSUE TITLE
[BUG] 反馈一下3.21.112020不显示标题

### ISSUE THREAD

**Issue by BlackRosePetals** [gedoor/legado#1436]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
更新到最新版本后，页眉页脚和正文都不显示标题/章节目录，旧版本正常显示，检查了界面-信息里面的设置，都是和旧版一致的。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
你看看你的替换规则,把标题替换了,以前替换规则对标题不起作用,新版本也作用标题

**Comment by BlackRosePetals** [comment]
确实是规则出问题了  我把所有规则删掉就有标题了   谢谢大佬
