### ISSUE TITLE
[BUG] 任意书籍-目录-3秒左右自动滑到目录最上

### ISSUE THREAD

**Issue by ShanHuilu** [gedoor/legado#1437]
### 机型（如Redmi K30 Pro）
>华为Mate20Pro

### 安卓版本（如Android 7.1.1）
>鸿蒙2.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.112020

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>结束阅读进程后，打开app，打开任意书籍，进入目录（当前章节不在目录第一页，最好大于10章），等待3秒左右（无论是不是在滑动目录），目录自动跳到最上。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
这个问题存在已久，直到今天才确定了比较精确的复现方法。一定要先退出阅读（结束进程），打开App，选择任意书籍（当前章节>10以保证当前章节不在目录页面最上位置），进入目录，3秒左右，目录跳到最上。复现一次后要先结束进程，再次进入才可以复现。

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
ok,我试试

**Comment by gedoor** [comment]
奇怪,可能与系统有关,我再我的手机上没有复现

**Comment by ShanHuilu** [comment]
> 奇怪,可能与系统有关,我再我的手机上没有复现
我这几乎100%， 我录了屏，怎么上传？

**Comment by Antecer** [comment]
上传很简单，只需要把文件拖到输入框，就行了。

**Comment by ShanHuilu** [comment]
https://user-images.githubusercontent.com/59857018/143365680-8c242111-1e8a-4cf8-8976-e43b3dd29ad9.mp4

**Comment by ShanHuilu** [comment]
> 上传很简单，只需要把文件拖到输入框，就行了。

感谢提醒，发了好多次终于发上来了

**Comment by gedoor** [comment]
奇怪,我再看看

**Comment by gedoor** [comment]
可以加我qq77148227测试

**Comment by gedoor** [comment]
已解决,等新版本
