### ISSUE TITLE
[BUG] 部分epub格式电子书打开显示【LoadTocError:目录列表为空】

### ISSUE THREAD

**Issue by moonmm** [gedoor/legado#1442]
### 机型（如Redmi K30 Pro）
>Redmi k20

### 安卓版本（如Android 7.1.1）
> 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.112020

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>部分epub格式电子书打开显示【LoadTocError:目录列表为空】，其他内容都看不到

### 使用书源（填写URL或者JSON）
> 本地 epub格式电子书

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
[>]
![e4027f53ff97ad00800f42ce703b188](https://user-images.githubusercontent.com/23271967/143821537-96b55329-7b79-4e51-a504-680587c2b15f.jpg)

**Comment by moonmm** [comment]
https://wwt.lanzouo.com/ixtWPx2nujc
密码:eg95

**Comment by gedoor** [comment]
我看看

**Comment by Netrvin** [comment]
会不会是 epub 制作的时候没加 toc/ncx/spine 之类的？我之前没加的时候也出过这种错误
