### ISSUE TITLE
[BUG] web服务不稳定

### ISSUE THREAD

**Issue by yyh28** [gedoor/legado#1443]
### 机型（如Redmi K30 Pro）
>

iqoo 3
### 安卓版本（如Android 7.1.1）
>

origon os 1.0
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.100821

### 问题描述（简要描述发生的问题）
>
web服务手机开启后，大概一小时后web端通过ip不能进行访问，提示后端连接断开，非常不稳定

**Comment by gedoor** [comment]
应该是后台被结束了

**Comment by YYH28** [comment]
我把后台自启动也开开了

**Comment by hectorqin** [comment]
可以试试服务器端的版本
https://github.com/hectorqin/reader
