### ISSUE TITLE
[BUG] 最近 3、4 个版本起点小说 VIP 章节（已购买）无法载入

### ISSUE THREAD

**Issue by someok** [gedoor/legado#1445]
### 机型（如Redmi K30 Pro）
> Mi 10 Pro

### 安卓版本（如Android 7.1.1）
> Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.112020

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 联通、电信、电信ADSL

### 问题描述（简要描述发生的问题）
> 起点小说 VIP 章节（已购买）无法载入，这个问题是最近 3、4 个版本中出现的，换了 4、5 个源都有问题

### 使用书源（填写URL或者JSON）
```json
{
  "bookSourceComment": "郁也风 2021-10-09",
  "bookSourceGroup": "💰 正版, 💝 someok",
  "bookSourceName": "💰 起点中文移动版",
  "bookSourceType": 0,
  "bookSourceUrl": "https://m.qidian.com",
  "bookUrlPattern": "",
  "customOrder": -999999,
  "enabled": true,
  "enabledExplore": true,
  "exploreUrl": "🔹               起   点   中   文               🔹::/all?style=1&page={{page}}\n\n🔸月 票 榜 ::/rank/yuepiao?style=1&page={{page}} \n  风 云 榜  ::/rank/fengyun?style=1&page={{page}}\n  热 销 榜  ::/rank/hotsales?style=1&page={{page}}\n\n🔸推 荐 榜 ::/rank/recom?style=1&page={{page}}\n  阅 读 榜  ::/rank/readIndex?style=1&page={{page}}\n  粉 丝 榜  ::/rank/newFans?style=1&page={{page}}\n\n🔸收 藏 榜 ::/rank/collect?style=1&page={{page}}\n  更 新 榜  ::/rank/vipup?style=1&page={{page}}\n  打 赏 榜  ::/rank/vipreward?style=1&page={{page}}\n\n🔹 往  期 三  江 🔹::/book/sanjiang?page={{page}}\n🔹 往  期 强  推 🔹::/book/strongrec?page={{page}}\n\n🔸 签  约 新  书 🔸::/rank/signnewbook?style=1&page={{page}}\n🔸 公  众 新  书 🔸::/rank/pubnewbook?style=1&page={{page}}\n🔸 新  签 新  书 🔸::/rank/newsign?style=1&page={{page}}\n🔸 新  人 新  书 🔸::/rank/newauthor?style=1&page={{page}}\n\n\n\n玄幻::/all?style=1&page={{page}}&chanId=21\n推荐::/all?style=1&page={{page}}&chanId=21&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=21&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=21&action=1\n免费::/all?style=1&page={{page}}&chanId=21&vip=0\n\n奇幻::/all?style=1&page={{page}}&chanId=1\n推荐::/all?style=1&page={{page}}&chanId=1&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=1&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=1&action=1\n免费::/all?style=1&page={{page}}&chanId=1&vip=0\n\n武侠::/all?style=1&page={{page}}&chanId=2\n推荐::/all?style=1&page={{page}}&chanId=2&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=2&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=2&action=1\n免费::/all?style=1&page={{page}}&chanId=2&vip=0\n\n仙侠::/all?style=1&page={{page}}&chanId=22\n推荐::/all?style=1&page={{page}}&chanId=22&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=22&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=22&action=1\n免费::/all?style=1&page={{page}}&chanId=22&vip=0\n\n都市::/all?style=1&page={{page}}&chanId=4\n推荐::/all?style=1&page={{page}}&chanId=4&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=4&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=4&action=1\n免费::/all?style=1&page={{page}}&chanId=4&vip=0\n\n现实::/all?style=1&page={{page}}&chanId=15\n推荐::/all?style=1&page={{page}}&chanId=15&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=15&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=15&action=1\n免费::/all?style=1&page={{page}}&chanId=15&vip=0\n\n军事::/all?style=1&page={{page}}&chanId=6\n推荐::/all?style=1&page={{page}}&chanId=6&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=6&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=6&action=1\n免费::/all?style=1&page={{page}}&chanId=6&vip=0\n\n历史::/all?style=1&page={{page}}&chanId=5\n推荐::/all?style=1&page={{page}}&chanId=5&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=5&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=5&action=1\n免费::/all?style=1&page={{page}}&chanId=5&vip=0\n\n游戏::/all?style=1&page={{page}}&chanId=7\n推荐::/all?style=1&page={{page}}&chanId=7&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=7&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=7&action=1\n免费::/all?style=1&page={{page}}&chanId=7&vip=0\n\n体育::/all?style=1&page={{page}}&chanId=8\n推荐::/all?style=1&page={{page}}&chanId=8&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=8&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=8&action=1\n免费::/all?style=1&page={{page}}&chanId=8&vip=0\n\n科幻::/all?style=1&page={{page}}&chanId=9\n推荐::/all?style=1&page={{page}}&chanId=9&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=9&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=9&action=1\n免费::/all?style=1&page={{page}}&chanId=9&vip=0\n\n悬疑::/all?style=1&page={{page}}&chanId=10\n推荐::/all?style=1&page={{page}}&chanId=10&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=10&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=10&action=1\n免费::/all?style=1&page={{page}}&chanId=10&vip=0\n\n短篇::/all?style=1&page={{page}}&chanId=20076\n推荐::/all?style=1&page={{page}}&chanId=20076&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=20076&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=20076&action=1\n免费::/all?style=1&page={{page}}&chanId=20076&vip=0\n\n轻小说::/all?style=1&page={{page}}&chanId=12\n推荐::/all?style=1&page={{page}}&chanId=12&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=12&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=12&action=1\n免费::/all?style=1&page={{page}}&chanId=12&vip=0\n\n\n\n🔹               起   点   女   生               🔹::/mm/all?style=1&page={{page}}\n\n🔸月 票 榜  ::/mm/rank/yuepiao?style=1&page={{page}}\n  字 数 榜  ::/mm/rank/wordcount?style=1&page={{page}}\n  热 销 榜  ::/mm/rank/hotsales?style=1&page={{page}}\n\n🔸推 荐 榜  ::/mm/rank/recom?style=1&page={{page}}\n  阅 读 榜  ::/mm/rank/readIndex?style=1&page={{page}}\n  粉 丝 榜  ::/mm/rank/newFans?style=1&page={{page}}\n\n🔸收 藏 榜  ::/mm/rank/collect?style=1&page={{page}}\n  更 新 榜  ::/mm/rank/vipup?style=1&page={{page}}\n  单 订 榜  ::/mm/rank/subscr?style=1&page={{page}}\n\n🔹   免     费    🔹::/mm/all?style=1&page={{page}}&vip=0\n🔹   完     本    🔹::/mm/all?style=1&page={{page}}&action=1\n\n🔸 签  约 新  书 🔸::/mm/rank/signnewbook?style=1&page={{page}}\n🔸 公  众 新  书 🔸::/mm/rank/pubnewbook?style=1&page={{page}}\n🔸 新  签 新  书 🔸::/mm/rank/newsign?style=1&page={{page}}\n🔸 新  人 新  书 🔸::/mm/rank/newauthor?style=1&page={{page}}\n\n古言::/mm/all?style=1&page={{page}}&chanId=80\n推荐::/mm/all?style=1&page={{page}}&chanId=80&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=80&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=80&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=80&vip=0\n\n仙侠::/mm/all?style=1&page={{page}}&chanId=81\n推荐::/mm/all?style=1&page={{page}}&chanId=81&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=81&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=81&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=81&vip=0\n\n现代::/mm/all?style=1&page={{page}}&chanId=82\n推荐::/mm/all?style=1&page={{page}}&chanId=82&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=82&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=82&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=82&vip=0\n\n青春::/mm/all?style=1&page={{page}}&chanId=83\n推荐::/mm/all?style=1&page={{page}}&chanId=83&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=83&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=83&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=83&vip=0\n\n玄幻::/mm/all?style=1&page={{page}}&chanId=84\n推荐::/mm/all?style=1&page={{page}}&chanId=84&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=84&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=84&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=84&vip=0\n\n悬疑::/mm/all?style=1&page={{page}}&chanId=85\n推荐::/mm/all?style=1&page={{page}}&chanId=85&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=85&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=85&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=85&vip=0\n\n短篇::/mm/all?style=1&page={{page}}&chanId=30083\n推荐::/mm/all?style=1&page={{page}}&chanId=30083&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=30083&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=30083&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=30083&vip=0\n\n科幻::/mm/all?style=1&page={{page}}&chanId=86\n推荐::/mm/all?style=1&page={{page}}&chanId=86&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=86&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=86&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=86&vip=0\n\n游戏::/mm/all?style=1&page={{page}}&chanId=88\n推荐::/mm/all?style=1&page={{page}}&chanId=88&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=88&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=88&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=88&vip=0\n\n生活::/mm/all?style=1&page={{page}}&chanId=30120\n推荐::/mm/all?style=1&page={{page}}&chanId=30120&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=30120&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=30120&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=30120&vip=0\n\n轻小说::/mm/all?style=1&page={{page}}&chanId=87\n推荐::/mm/all?style=1&page={{page}}&chanId=87&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=87&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=87&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=87&vip=0\n\n",
  "header": "",
  "lastUpdateTime": 1634733356052,
  "loginUrl": "https://passport.qidian.com",
  "respondTime": 180000,
  "ruleBookInfo": {
    "author": "@css:h4.book-title@text",
    "intro": "content@text",
    "kind": "class.book-meta.0@text",
    "lastChapter": "##span>连载至([^<]+)##$1###",
    "name": "@css:h2.book-title@text",
    "tocUrl": "<js>\nvar id = baseUrl.match(/book\\/(\\d+)/)[1];\njava.put('id', id);\n'https://druid.if.qidian.com/argus/api/v1/chapterlist/chapterlist?bookId='+id;\n</js>",
    "wordCount": "##\"book-meta\"[^>]+>([^<]+)<span##$1###"
  },
  "ruleContent": {
    "content": "tag.article@tag.p@text"
  },
  "ruleExplore": {},
  "ruleSearch": {
    "author": "class.book-author@text",
    "bookList": "class.book-ol@tag.li||class.book-list-wrap@class.book-list@tag.li",
    "bookUrl": "tag.a@href",
    "coverUrl": "tag.img@data-src",
    "intro": "class.book-desc@text",
    "kind": "class.book-meta-r@class.gray@text",
    "lastChapter": "",
    "name": "class.book-title@text",
    "wordCount": "class.book-meta-r@class.blue@text"
  },
  "ruleToc": {
    "chapterList": "Data.Chapters[1:]@put:{id:Data.BookId}",
    "chapterName": "N",
    "chapterUrl": "https://m.qidian.com/book/@get:{id}/{{$.C}}",
    "isVip": "V"
  },
  "searchUrl": "/search?kw={{key}}",
  "weight": 0
}
```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）

**症状表现：**
![image](https://user-images.githubusercontent.com/1523082/143883369-e3d1a69a-96ba-4c65-bcd2-9ab0b4ecff1b.png)

**从书页上的 URL 点击打开的 webview 显示内容正常**
![Frame 1](https://user-images.githubusercontent.com/1523082/143884086-6ee8c2ce-0b2e-4333-a414-2d59dab308c8.png)

**但是从「登录」按钮一路进入文章页，则是空空如也，如下图所示**
![Frame 2](https://user-images.githubusercontent.com/1523082/143884832-a0de17f1-80da-407d-aeee-ab4f4c4903de.png)

> 怀疑这两个 WebView 中在调用存储的登录信息时存在差别？

**Comment by gedoor** [comment]
好的,我看一下

**Comment by wqx1919** [comment]
> ### 机型（如Redmi K30 Pro）
> > Mi 10 Pro
> 
> ### 安卓版本（如Android 7.1.1）
> > Android 11
> 
> ### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> > 3.21.112020
> 
> ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > 联通、电信、电信ADSL
> 
> ### 问题描述（简要描述发生的问题）
> > 起点小说 VIP 章节（已购买）无法载入，这个问题是最近 3、4 个版本中出现的，换了 4、5 个源都有问题
> 
> ### 使用书源（填写URL或者JSON）
> ```json
> {
>   "bookSourceComment": "郁也风 2021-10-09",
>   "bookSourceGroup": "💰 正版, 💝 someok",
>   "bookSourceName": "💰 起点中文移动版",
>   "bookSourceType": 0,
>   "bookSourceUrl": "https://m.qidian.com",
>   "bookUrlPattern": "",
>   "customOrder": -999999,
>   "enabled": true,
>   "enabledExplore": true,
>   "exploreUrl": "🔹               起   点   中   文               🔹::/all?style=1&page={{page}}\n\n🔸月 票 榜 ::/rank/yuepiao?style=1&page={{page}} \n  风 云 榜  ::/rank/fengyun?style=1&page={{page}}\n  热 销 榜  ::/rank/hotsales?style=1&page={{page}}\n\n🔸推 荐 榜 ::/rank/recom?style=1&page={{page}}\n  阅 读 榜  ::/rank/readIndex?style=1&page={{page}}\n  粉 丝 榜  ::/rank/newFans?style=1&page={{page}}\n\n🔸收 藏 榜 ::/rank/collect?style=1&page={{page}}\n  更 新 榜  ::/rank/vipup?style=1&page={{page}}\n  打 赏 榜  ::/rank/vipreward?style=1&page={{page}}\n\n🔹 往  期 三  江 🔹::/book/sanjiang?page={{page}}\n🔹 往  期 强  推 🔹::/book/strongrec?page={{page}}\n\n🔸 签  约 新  书 🔸::/rank/signnewbook?style=1&page={{page}}\n🔸 公  众 新  书 🔸::/rank/pubnewbook?style=1&page={{page}}\n🔸 新  签 新  书 🔸::/rank/newsign?style=1&page={{page}}\n🔸 新  人 新  书 🔸::/rank/newauthor?style=1&page={{page}}\n\n\n\n玄幻::/all?style=1&page={{page}}&chanId=21\n推荐::/all?style=1&page={{page}}&chanId=21&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=21&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=21&action=1\n免费::/all?style=1&page={{page}}&chanId=21&vip=0\n\n奇幻::/all?style=1&page={{page}}&chanId=1\n推荐::/all?style=1&page={{page}}&chanId=1&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=1&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=1&action=1\n免费::/all?style=1&page={{page}}&chanId=1&vip=0\n\n武侠::/all?style=1&page={{page}}&chanId=2\n推荐::/all?style=1&page={{page}}&chanId=2&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=2&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=2&action=1\n免费::/all?style=1&page={{page}}&chanId=2&vip=0\n\n仙侠::/all?style=1&page={{page}}&chanId=22\n推荐::/all?style=1&page={{page}}&chanId=22&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=22&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=22&action=1\n免费::/all?style=1&page={{page}}&chanId=22&vip=0\n\n都市::/all?style=1&page={{page}}&chanId=4\n推荐::/all?style=1&page={{page}}&chanId=4&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=4&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=4&action=1\n免费::/all?style=1&page={{page}}&chanId=4&vip=0\n\n现实::/all?style=1&page={{page}}&chanId=15\n推荐::/all?style=1&page={{page}}&chanId=15&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=15&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=15&action=1\n免费::/all?style=1&page={{page}}&chanId=15&vip=0\n\n军事::/all?style=1&page={{page}}&chanId=6\n推荐::/all?style=1&page={{page}}&chanId=6&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=6&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=6&action=1\n免费::/all?style=1&page={{page}}&chanId=6&vip=0\n\n历史::/all?style=1&page={{page}}&chanId=5\n推荐::/all?style=1&page={{page}}&chanId=5&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=5&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=5&action=1\n免费::/all?style=1&page={{page}}&chanId=5&vip=0\n\n游戏::/all?style=1&page={{page}}&chanId=7\n推荐::/all?style=1&page={{page}}&chanId=7&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=7&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=7&action=1\n免费::/all?style=1&page={{page}}&chanId=7&vip=0\n\n体育::/all?style=1&page={{page}}&chanId=8\n推荐::/all?style=1&page={{page}}&chanId=8&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=8&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=8&action=1\n免费::/all?style=1&page={{page}}&chanId=8&vip=0\n\n科幻::/all?style=1&page={{page}}&chanId=9\n推荐::/all?style=1&page={{page}}&chanId=9&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=9&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=9&action=1\n免费::/all?style=1&page={{page}}&chanId=9&vip=0\n\n悬疑::/all?style=1&page={{page}}&chanId=10\n推荐::/all?style=1&page={{page}}&chanId=10&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=10&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=10&action=1\n免费::/all?style=1&page={{page}}&chanId=10&vip=0\n\n短篇::/all?style=1&page={{page}}&chanId=20076\n推荐::/all?style=1&page={{page}}&chanId=20076&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=20076&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=20076&action=1\n免费::/all?style=1&page={{page}}&chanId=20076&vip=0\n\n轻小说::/all?style=1&page={{page}}&chanId=12\n推荐::/all?style=1&page={{page}}&chanId=12&orderId=10\n收藏::/all?style=1&page={{page}}&chanId=12&action=1&orderId=11\n完本::/all?style=1&page={{page}}&chanId=12&action=1\n免费::/all?style=1&page={{page}}&chanId=12&vip=0\n\n\n\n🔹               起   点   女   生               🔹::/mm/all?style=1&page={{page}}\n\n🔸月 票 榜  ::/mm/rank/yuepiao?style=1&page={{page}}\n  字 数 榜  ::/mm/rank/wordcount?style=1&page={{page}}\n  热 销 榜  ::/mm/rank/hotsales?style=1&page={{page}}\n\n🔸推 荐 榜  ::/mm/rank/recom?style=1&page={{page}}\n  阅 读 榜  ::/mm/rank/readIndex?style=1&page={{page}}\n  粉 丝 榜  ::/mm/rank/newFans?style=1&page={{page}}\n\n🔸收 藏 榜  ::/mm/rank/collect?style=1&page={{page}}\n  更 新 榜  ::/mm/rank/vipup?style=1&page={{page}}\n  单 订 榜  ::/mm/rank/subscr?style=1&page={{page}}\n\n🔹   免     费    🔹::/mm/all?style=1&page={{page}}&vip=0\n🔹   完     本    🔹::/mm/all?style=1&page={{page}}&action=1\n\n🔸 签  约 新  书 🔸::/mm/rank/signnewbook?style=1&page={{page}}\n🔸 公  众 新  书 🔸::/mm/rank/pubnewbook?style=1&page={{page}}\n🔸 新  签 新  书 🔸::/mm/rank/newsign?style=1&page={{page}}\n🔸 新  人 新  书 🔸::/mm/rank/newauthor?style=1&page={{page}}\n\n古言::/mm/all?style=1&page={{page}}&chanId=80\n推荐::/mm/all?style=1&page={{page}}&chanId=80&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=80&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=80&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=80&vip=0\n\n仙侠::/mm/all?style=1&page={{page}}&chanId=81\n推荐::/mm/all?style=1&page={{page}}&chanId=81&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=81&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=81&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=81&vip=0\n\n现代::/mm/all?style=1&page={{page}}&chanId=82\n推荐::/mm/all?style=1&page={{page}}&chanId=82&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=82&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=82&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=82&vip=0\n\n青春::/mm/all?style=1&page={{page}}&chanId=83\n推荐::/mm/all?style=1&page={{page}}&chanId=83&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=83&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=83&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=83&vip=0\n\n玄幻::/mm/all?style=1&page={{page}}&chanId=84\n推荐::/mm/all?style=1&page={{page}}&chanId=84&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=84&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=84&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=84&vip=0\n\n悬疑::/mm/all?style=1&page={{page}}&chanId=85\n推荐::/mm/all?style=1&page={{page}}&chanId=85&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=85&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=85&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=85&vip=0\n\n短篇::/mm/all?style=1&page={{page}}&chanId=30083\n推荐::/mm/all?style=1&page={{page}}&chanId=30083&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=30083&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=30083&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=30083&vip=0\n\n科幻::/mm/all?style=1&page={{page}}&chanId=86\n推荐::/mm/all?style=1&page={{page}}&chanId=86&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=86&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=86&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=86&vip=0\n\n游戏::/mm/all?style=1&page={{page}}&chanId=88\n推荐::/mm/all?style=1&page={{page}}&chanId=88&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=88&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=88&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=88&vip=0\n\n生活::/mm/all?style=1&page={{page}}&chanId=30120\n推荐::/mm/all?style=1&page={{page}}&chanId=30120&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=30120&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=30120&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=30120&vip=0\n\n轻小说::/mm/all?style=1&page={{page}}&chanId=87\n推荐::/mm/all?style=1&page={{page}}&chanId=87&orderId=10\n收藏::/mm/all?style=1&page={{page}}&chanId=87&action=1&orderId=11\n完本::/mm/all?style=1&page={{page}}&chanId=87&action=1\n免费::/mm/all?style=1&page={{page}}&chanId=87&vip=0\n\n",
>   "header": "",
>   "lastUpdateTime": 1634733356052,
>   "loginUrl": "https://passport.qidian.com",
>   "respondTime": 180000,
>   "ruleBookInfo": {
>     "author": "@css:h4.book-title@text",
>     "intro": "content@text",
>     "kind": "class.book-meta.0@text",
>     "lastChapter": "##span>连载至([^<]+)##$1###",
>     "name": "@css:h2.book-title@text",
>     "tocUrl": "<js>\nvar id = baseUrl.match(/book\\/(\\d+)/)[1];\njava.put('id', id);\n'https://druid.if.qidian.com/argus/api/v1/chapterlist/chapterlist?bookId='+id;\n</js>",
>     "wordCount": "##\"book-meta\"[^>]+>([^<]+)<span##$1###"
>   },
>   "ruleContent": {
>     "content": "tag.article@tag.p@text"
>   },
>   "ruleExplore": {},
>   "ruleSearch": {
>     "author": "class.book-author@text",
>     "bookList": "class.book-ol@tag.li||class.book-list-wrap@class.book-list@tag.li",
>     "bookUrl": "tag.a@href",
>     "coverUrl": "tag.img@data-src",
>     "intro": "class.book-desc@text",
>     "kind": "class.book-meta-r@class.gray@text",
>     "lastChapter": "",
>     "name": "class.book-title@text",
>     "wordCount": "class.book-meta-r@class.blue@text"
>   },
>   "ruleToc": {
>     "chapterList": "Data.Chapters[1:]@put:{id:Data.BookId}",
>     "chapterName": "N",
>     "chapterUrl": "https://m.qidian.com/book/@get:{id}/{{$.C}}",
>     "isVip": "V"
>   },
>   "searchUrl": "/search?kw={{key}}",
>   "weight": 0
> }
> ```
> 
> ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> **症状表现：** ![image](https://user-images.githubusercontent.com/1523082/143883369-e3d1a69a-96ba-4c65-bcd2-9ab0b4ecff1b.png)
> 
> **从书页上的 URL 点击打开的 webview 显示内容正常** ![Frame 1](https://user-images.githubusercontent.com/1523082/143884086-6ee8c2ce-0b2e-4333-a414-2d59dab308c8.png)
> 
> **但是从「登录」按钮一路进入文章页，则是空空如也，如下图所示** ![Frame 2](https://user-images.githubusercontent.com/1523082/143884832-a0de17f1-80da-407d-aeee-ab4f4c4903de.png)
> 
> > 怀疑这两个 WebView 中在调用存储的登录信息时存在差别？

解决了吗，我也登陆不了

**Comment by gedoor** [comment]
正在调试

**Comment by gedoor** [comment]
好像是网站改了

**Comment by gedoor** [comment]
![image](https://user-images.githubusercontent.com/22701807/144734387-df0d9081-a191-4ad4-90c3-715f23640166.png)
启用webView就可以了

**Comment by wqx1919** [comment]
> ![image](https://user-images.githubusercontent.com/22701807/144734387-df0d9081-a191-4ad4-90c3-715f23640166.png)
> 启用webView就可以了
登陆了，但是现在变成预览了（相当于没订阅），能发一个你成功的书源给我试一下吗？

**Comment by wqx1919** [comment]
> 

哦 可以了在【目录url规则】xxxxx（原先写法）后面加上：@js:reult+',{"webView":ture}'，
如果不行就点击书源然后再退出来就可以了

**Comment by someok** [comment]
确实这样好用了，神奇
