### ISSUE TITLE
[BUG] 本地epub文件目录显示不全以及无法显示二级目录

### ISSUE THREAD

**Issue by progressforward** [gedoor/legado#1446]
### 机型（如Redmi K30 Pro）
>
Redmi note 9

### 安卓版本（如Android 7.1.1）
>
Android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.21.112719
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
本地文件和网络无关

### 问题描述（简要描述发生的问题）
>
1，打开本地epub文件，目录显示不全，缺少部分目录。
2，无法显示二级目录并且目录显示也不全。

### 使用书源（填写URL或者JSON）
>
放在百度云盘提供下载复现。
1，目录显示不全文件链接，
链接:https://pan.baidu.com/s/1wdxEorhFlOdUVnGnADvKsA 
提取码:1s9m
2，无法显示二级目录并且目录显示也不全，
链接:https://pan.baidu.com/s/1DpbIBRg5fA2eW2MF_h-d9g 
提取码:kn18

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

下载文件，打开即可

### 日志提交（问题截图或者日志）
>
作为对照，使用小米自带的阅读软件（多看阅读6.5.3…）
1，目录显示不全对照
Legdao版本
![Screenshot_2021-11-30-13-15-36-314_io.legado.app.release.jpg](https://user-images.githubusercontent.com/43518314/143989693-92ab97cf-551e-424b-97d1-a41789b31be1.jpg)
多看阅读版本
![Screenshot_2021-11-30-13-15-55-280_com.duokan.reader.jpg](https://user-images.githubusercontent.com/43518314/143989740-971e1908-44e3-4dc5-bca2-523d7bd6c2c0.jpg)
2，无法显示二级目录并且目录显示也不全
Legdao版本
![Screenshot_2021-11-30-13-17-54-708_io.legado.app.release.jpg](https://user-images.githubusercontent.com/43518314/143989913-db024f75-eb4b-4e11-b8f3-f067e402367f.jpg)
多看阅读版本
![Screenshot_2021-11-30-13-17-16-727_com.duokan.reader.jpg](https://user-images.githubusercontent.com/43518314/143989945-73269835-f8bc-4a0a-8a75-c442b42e2506.jpg)

**Comment by gedoor** [comment]
ok,我修复一下

**Comment by laulguo** [comment]
似乎仍未修复，跟我的情况相同：https://github.com/gedoor/legado/issues/1408

**Comment by gedoor** [comment]
重新添加一下试试

**Comment by laulguo** [comment]
> 重新添加一下试试

重新添加后没问题了

**Comment by laulguo** [comment]
> 重新添加一下试试

您好，三级目录的识别好像仍然会产生问题，我这里有一个具备二级及三级目录的
链接: https://pan.baidu.com/s/1EStplC1bJhhH-AkSjKjnxg 提取码: viq1

**Comment by dalu-test** [comment]
3.22.021120版本仍然不识别多级目录，而且正文内嵌的图片也不显示(未开净化规则)

**Comment by dalu-test** [comment]
3.22.021120版本仍然不识别多级目录，而且正文内嵌的图片也不显示(未开净化规则)
