### ISSUE TITLE
[BUG] 导入书源等失败，显示Connection reset

### ISSUE THREAD

**Issue by LaddVan** [gedoor/legado#1448]
### 机型
>

iqoo Neo5
### 安卓版本
>
Android 11

### 阅读Legdao版本
>
3.21.112020
### 网络环境
>
联通

### 问题描述
>
导入书源、RSS订阅源等失败
显示Connection reset

### 使用书源（填写URL或者JSON）
>
http://yck.mumuceo.com/d/DUNcT

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
网络问题
