### ISSUE TITLE
[BUG] 通过API调用百度语音合成，报502错误（token无法认证）

### ISSUE THREAD

**Issue by javacoffer2020** [gedoor/legado#1451]
### 机型（如Redmi K30 Pro）
>一加8 PRO

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.11279

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通、电信、电信宽带、校园网

### 问题描述（简要描述发生的问题）
>选用百度TTS作为自定义朗读引擎时，无法使用tok参数，报502错误。
{
  "concurrentRate": "0",
  "contentType": "audio/wav",
  "header": "",
  "id": 1638709393205,
  "loginCheckJs": "",
  "loginUi": "",
  "loginUrl": "",
  "name": "百度（逍遥精品）",
  "url": "http://tsn.baidu.com/text2audio,{\n    \"method\": \"POST\",\n    \"body\": \"tex={{java.encodeURI(java.encodeURI(speakText))}}&tok=24.88d9900cae460**********25b890730.*******.**********.******-********&spd={{(speakSpeed + 5) / 10 + 4}}&per=5003&cuid=javacoffertest&idx=1&cod=2&lan=zh&ctp=1&pdt=11&vol=5&aue=6&pit=11&_res_tag_=audio\"\n}"
}

日志：io.legado.app.model.NoStackTraceException: {"err_detail":"Invalid param pdt.","err_msg":"Invalid param pdt.","err_no":502,"err_subcode":404,"tts_logid":2338490645}

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by yaoxin1588** [comment]
pdt=11改成 pdt=220 试试

**Comment by javacoffer2020** [comment]
百度的技术文档中的错误代码有问题。改编pdt后正常。谢谢楼上！
