### ISSUE TITLE
[Feature Request] 曲面屏边缘增加死区防误触

### ISSUE THREAD

**Issue by a454500** [gedoor/legado#1453]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 曲面屏边缘防误触

### 期望实现方式（阅读应该如何实现该功能）
> 增加对应选项开关防误触功能

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
以添加禁止返回选项并修复了全面屏手势触发翻页的bug,等下个版本
