### ISSUE TITLE
[BUG] 书架布局的排序为手动排序时添加新书在书架最下方

### ISSUE THREAD

**Issue by 821938089** [gedoor/legado#1460]
### 机型（如Redmi K30 Pro）
>Xiaomi 6X

### 安卓版本（如Android 7.1.1）
>Android 9.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.121021

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>书架布局的排序为手动排序时添加新书在书架最下方
之前我提过issue #410 说是已经优化了，但是我试了实际没有效果，详见复现步骤

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
https://user-images.githubusercontent.com/8674809/145835616-36a5be0b-f306-4884-b537-5a4ff11ed751.mp4

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
收到
