### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yaodonggggggg** [gedoor/legado#1461]
### 机型（如Redmi K30 Pro）
>Redmi K40

### 安卓版本（如Android 7.1.1）
>Android11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.121021

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动和移动宽带

### 问题描述（简要描述发生的问题）
>漫画的横屏双页不起作用

### 使用书源（填写URL或者JSON）
>https://haxc.coding.net/p/booksrc/d/booksrc/git/raw/master/bookSource.json

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>1、（1）设置屏幕方向为横向，（2）开启平板/横屏双页，（3）图片移动到左侧，右侧空白
2、（1）取消手机的方向锁定，（2）设置屏幕方向为跟随系统，（3）开启平板/横屏双页，（4）将手机旋转为横向（5）图片移动到左侧，右侧空白

### 日志提交（问题截图或者日志）
>
![c512940c9533fa2b2e69b69976ee9a3](https://user-images.githubusercontent.com/45419657/146002065-7e07641d-0c64-464b-b67f-45cf09e59865.jpg)
![b5a62f2d770ed9dd07acbbd49e473bb](https://user-images.githubusercontent.com/45419657/146002159-d3754c73-6f37-484a-83f9-27bc3f7e1eab.jpg)

**Comment by gedoor** [comment]
漫画还是别双页了吧
