### ISSUE TITLE
[BUG] 朗读时声音会突然变调

### ISSUE THREAD

**Issue by Yvonne0827** [gedoor/legado#1462]
### 机型（如Redmi K30 Pro）
>
小米6

### 安卓版本（如Android 7.1.1）
>
Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.21.100821
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通4G

### 问题描述（简要描述发生的问题）
>
用小米6自带语音引擎或者App上带的那些百度语音引擎朗读书籍时，经常会发生突然由原始的正常声调变成其它奇怪的声调。目前暂时不知道是否跟书有关系还是跟语音引擎有关系。

### 使用书源（填写URL或者JSON）
>
本地下载的txt书籍或者在线书籍均出现过这种情况

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
1. 任意书籍开始朗读
2. 朗读一段时间后，正常音调的朗读声突然变成奇怪的音调，过一段时间又恢复正常，如此往复交替

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
这个不属于阅读问题,tts问题

**Comment by Yvonne0827** [comment]
经过我不断尝试，发现网络不佳的时候，声音就变调了
