### ISSUE TITLE
[BUG] 页面乱码

### ISSUE THREAD

**Issue by csh159** [gedoor/legado#1465]
### 机型（如vivo s5）
>

### 安卓版本（如Android 9）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
epub有乱码

### 使用书源（填写URL或者JSON）
>
![3540c047878786dce599493d952664b](https://user-images.githubusercontent.com/4157414/146308780-696a7ded-08ae-492f-8644-7da20385832f.jpg)

测试书籍文件
[1924940-沙丘六部曲【小力盘xiaolipan.com】.zip](https://github.com/gedoor/legado/files/7724574/1924940-.xiaolipan.com.zip)

**Comment by gedoor** [comment]
下版本解决
