### ISSUE TITLE
[BUG] 识别epub电子书的多级目录的行为和结果不正确

### ISSUE THREAD

**Issue by nukemiko** [gedoor/legado#1466]
### 机型
> Redmi K30 Pro

### 安卓版本（如Android 7.1.1）
> Android 11, MIUI 12.5.5

### 阅读Legdao版本
> 3.21.121021

### 问题描述（简要描述发生的问题）
> 打开一级目录中只有标题的空章节，页面显示“正在加载中……”且无法翻页
> 应用会逐渐卡死，任何响应都极其缓慢（至少10秒）
> 如果有足够耐心等到应用恢复，内容会显示，但显示的是空章节、下一章的标题和下下一章的内容

### 使用书源（填写URL或者JSON）
> 
[道与碳基猴子饲养守则_2021-12-17.zip](https://github.com/gedoor/legado/files/7729011/_2021-12-17.zip)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 下载以上链接中的文件，解压，导入
> 打开导入的书，进入目录，点按“第X卷”开头的章节
> 将会出现以上现象

### 日志提交（问题截图或者日志）
![Screenshot_2021-12-17-00-41-44-514_io legado app release](https://user-images.githubusercontent.com/53572814/146414225-37c66cf2-562e-4287-8bf2-96ae5b831c3d.jpg)

注意中下方的错误信息↓
![Screenshot_2021-12-17-00-42-46-098_io legado app release](https://user-images.githubusercontent.com/53572814/146414297-9c75edf4-08dd-49b6-9c23-9e2d717251a7.jpg)

**Comment by laulguo** [comment]
确实有这个问题，多级目录识别会有问题

**Comment by lidawei97688** [comment]
很多时候有些epub小说打开后每章的标题都是3个，语音朗读时候有种“重要的事情说三遍”的感觉T_T
