### ISSUE TITLE
[BUG] 替换净化功能会在每次退出应用后自动关闭

### ISSUE THREAD

**Issue by nukemiko** [gedoor/legado#1467]
### 机型
> Redmi K30 Pro

### 安卓版本（如Android 7.1.1）
> Android 11, MIUI 12.5.5

### 阅读Legdao版本
> 3.21.121021

### 问题描述（简要描述发生的问题）
> 替换净化功能会在每次退出应用后自动关闭；设置 > 其它设置 > 默认启用替换净化已经打开

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 打开一本书，打开替换净化
> 关闭应用
> 再次进入应用，打开上次打开过的书，可以看到替换净化被关闭

**Comment by gedoor** [comment]
是强制关闭应用吗,正常退出应该会保存配置

**Comment by gedoor** [comment]
没复现该问题

**Comment by nukemiko** [comment]
> 

没错，正常退出会保存这个开关的状态。

但问题是，强制退出之后，哪怕上次正常退出时替换净化开着，再进去之后也会被关掉，也就是说强制退出可以复现这个问题
