### ISSUE TITLE
[Feature Request] 将空章节（只有标题没有内容）的标题放在屏幕中间位置

### ISSUE THREAD

**Issue by nukemiko** [gedoor/legado#1468]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 将空章节（只有标题没有内容）的标题放在屏幕中间位置

### 期望实现方式（阅读应该如何实现该功能）
> 在解析电子书时，如果发现章节只有标题没有内容，那么在显示这一章节时，将标题放在屏幕中间位置

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）

这是厚墨在面对空章节时的行为↓
![Screenshot_2021-12-17-01-03-26-833_cn deepink reader](https://user-images.githubusercontent.com/53572814/146416207-f233a5e0-7c1f-469d-af89-d6174b63bb4a.jpg)

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/commit/4d7a84ed948f17e5abbc09248febd04821e4f20b resolved
