### ISSUE TITLE
[BUG] 自定义朗读引擎，无法修改请求的 Content-Type ？

### ISSUE THREAD

**Issue by meetcw** [gedoor/legado#1469]
微软的认知服务TTS提供每月500万字的免费限额，对于个人用户足够了。

所以我想添加一个自定义朗读引擎，调用它提供的API。

API格式如下：
```sh
curl --location --request POST 'https://INSERT_REGION_HERE.tts.speech.microsoft.com/cognitiveservices/v1' \
--header 'Ocp-Apim-Subscription-Key: INSERT_SUBSCRIPTION_KEY_HERE' \
--header 'Content-Type: application/ssml+xml' \
--header 'X-Microsoft-OutputFormat: audio-16khz-128kbitrate-mono-mp3' \
--header 'User-Agent: curl' \
--data-raw '<speak version='\''1.0'\'' xml:lang='\''en-US'\''>
    <voice xml:lang='\''en-US'\'' xml:gender='\''Female'\'' name='\''en-US-JennyNeural'\''>
        my voice is my passport verify me
    </voice>
</speak>' > output.mp3
```

我编写的规则：
```sh
# url
https://eastasia.tts.speech.microsoft.com/cognitiveservices/v1,{"method":"POST","body":"<speak version=\"1.0\" xml:lang=\"en-US\"><voice name=\"zh-CN-XiaoxiaoNeural\"><prosody rate=\"0%\" pitch=\"0%\">{{speakText}}</prosody></voice></speak>"}
# header key 需要使用替换为真实的key
{"Ocp-Apim-Subscription-Key": "key",
"Content-Type": "application/ssml+xml",
"X-Microsoft-OutputFormat": "audio-16khz-128kbitrate-mono-mp3",
"User-Agent": "yd"}
```

这个API需要设置Content-Type 为 `application/ssml+xml` ，我使用抓包工具发现请求的 Content-Type 被阅读修改为了 `application/x-www-form-urlencoded`，而且 body中的xml内容被截断并编码为了
```
%3Cspeak%20version=%221.0%22+xml%3Alang
```

看了下源代码，阅读现在似乎只能处理 Form 和 Json 两种 Content-Type 的 post 请求？

对 Kotlin 不太熟悉，也可能是我规则写的不对，请大佬们指教以下应该怎么修改？

**Comment by gedoor** [comment]
好的,我看下

**Comment by gedoor** [comment]
提交了一个测试版本,下载试试

**Comment by SinoAHpx** [comment]
![image](https://user-images.githubusercontent.com/34391004/146665895-77d4d4cf-491b-43f5-a718-2a1f2b77147a.png)

好像还是用不了？这是我复制的规则，开启朗读之后无事发生
app版本是`legado_app_3.21.12191159_共存.apk`

**Comment by meetcw** [comment]
> 提交了一个测试版本,下载试试
legado_app_3.21.12182037_共存.apk 的content-type会变成json。

**Comment by meetcw** [comment]
@SinoAHpx url 下面的 Content-Type 根据内置阅读引擎推测设置的应该是Response的Content-Type。即应该为 audio/mpeg。

**Comment by SinoAHpx** [comment]
@meetcw 谢谢老哥！我发现我传的url和header都有一点json语法问题，修正之后就可以用了

**Comment by Jay54520** [comment]
最后你们是怎么配置的？我的配置在阅读3.0日志中显示朗读出错。

URL: 
```
https://eastasia.tts.speech.microsoft.com/cognitiveservices/v1,{
    "method": "POST",
    "body": "<speak version=\"1.0\"xml:lang=\"zh-CN\"><voice name=\"zh-CN-XiaoxiaoNeural\"><prosody rate=\"0%\" pitch=\0%\">{{speakText}}</prosody></voice></speak>"
}
```
Content-type: `audio/mpeg`
请求头: 
```
{
  "Ocp-Apim-Subscription-Key": "API-KEY",
  "Content-Type": "application/ssml+xml",
  "X-Microsoft-OutputFormat": "audio-16khz-128kbitrate-mono-mp3",
  "User-Agent": "yd3.0"
}
```
我的 API-KEY 没有问题，因为能够使用 curl 获取到返回。
@meetcw @SinoAHpx

**Comment by gkcngk** [comment]
> 阅读3.0朗读引擎配置
> 
> 将下方代码中的 API-KEY 替换为 Azure 的 API-KEY 在阅读3.0中新增朗读引擎 复制下方代码，在阅读3.0中点击右上角菜单-`粘贴源`
> 
> ```
> {
>   "concurrentRate": "0",
>   "contentType": "audio/mpeg",
>   "header": "{\n  \"Ocp-Apim-Subscription-Key\": \"API-KEY\",\n  \"Content-Type\": \"application/ssml+xml\",\n  \"X-Microsoft-OutputFormat\": \"audio-16khz-128kbitrate-mono-mp3\",\n  \"User-Agent\": \"legado\"\n}",
>   "id": 1642068899362,
>   "loginCheckJs": "",
>   "loginUi": "",
>   "loginUrl": "",
>   "name": Azure,
>   "url": "https://eastasia.tts.speech.microsoft.com/cognitiveservices/v1,{\n    \"method\": \"POST\",\n    \"body\": \"<speak version=\\\"1.0\\\" xml:lang=\\\"zh-CN\\\"><voice name=\\\"zh-CN-XiaoxiaoNeural\\\"><prosody rate=\\\"0%\\\" pitch=\\\"0%\\\">{{speakText}}</prosody></voice></speak>\"\n}"
> }
> ```
> 
> Azure 参数是 `url` 中的 name, rate 和 pitch。

感谢！成功结局我遇到的问题
顺便提示使用eastasia以外服务器的用户，需要把eastasia换到你所在地对应的server

**Comment by SinoAHpx** [comment]
> > 阅读3.0朗读引擎配置
> > 
> > 将下方代码中的 API-KEY 替换为 Azure 的 API-KEY 在阅读3.0中新增朗读引擎 复制下方代码，在阅读3.0中点击右上角菜单-`粘贴源`
> > 
> > ```
> > {
> >   "concurrentRate": "0",
> >   "contentType": "audio/mpeg",
> >   "header": "{\n  \"Ocp-Apim-Subscription-Key\": \"API-KEY\",\n  \"Content-Type\": \"application/ssml+xml\",\n  \"X-Microsoft-OutputFormat\": \"audio-16khz-128kbitrate-mono-mp3\",\n  \"User-Agent\": \"legado\"\n}",
> >   "id": 1642068899362,
> >   "loginCheckJs": "",
> >   "loginUi": "",
> >   "loginUrl": "",
> >   "name": Azure,
> >   "url": "https://eastasia.tts.speech.microsoft.com/cognitiveservices/v1,{\n    \"method\": \"POST\",\n    \"body\": \"<speak version=\\\"1.0\\\" xml:lang=\\\"zh-CN\\\"><voice name=\\\"zh-CN-XiaoxiaoNeural\\\"><prosody rate=\\\"0%\\\" pitch=\\\"0%\\\">{{speakText}}</prosody></voice></speak>\"\n}"
> > }
> > ```
> > 
> > Azure 参数是 `url` 中的 name, rate 和 pitch。
> 
> 感谢！成功解决了我遇到的问题
> 顺便提示使用eastasia以外服务器的用户，需要把eastasia换到你所在地对应的server
> 另外如果网速不错的话，也可以把audio-16khz-128kbitrate-mono-mp3换到更高码率

建议使用@meetcw 的https://github.com/meetcw/ms-ra-forwarder 体验更佳

**Comment by kettly1260** [comment]
> > > 阅读3.0朗读引擎配置
> > > 将下方代码中的 API-KEY 替换为 Azure 的 API-KEY 在阅读3.0中新增朗读引擎 复制下方代码，在阅读3.0中点击右上角菜单-`粘贴源`
> > > ```
> > > {
> > >   "concurrentRate": "0",
> > >   "contentType": "audio/mpeg",
> > >   "header": "{\n  \"Ocp-Apim-Subscription-Key\": \"API-KEY\",\n  \"Content-Type\": \"application/ssml+xml\",\n  \"X-Microsoft-OutputFormat\": \"audio-16khz-128kbitrate-mono-mp3\",\n  \"User-Agent\": \"legado\"\n}",
> > >   "id": 1642068899362,
> > >   "loginCheckJs": "",
> > >   "loginUi": "",
> > >   "loginUrl": "",
> > >   "name": Azure,
> > >   "url": "https://eastasia.tts.speech.microsoft.com/cognitiveservices/v1,{\n    \"method\": \"POST\",\n    \"body\": \"<speak version=\\\"1.0\\\" xml:lang=\\\"zh-CN\\\"><voice name=\\\"zh-CN-XiaoxiaoNeural\\\"><prosody rate=\\\"0%\\\" pitch=\\\"0%\\\">{{speakText}}</prosody></voice></speak>\"\n}"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Azure 参数是 `url` 中的 name, rate 和 pitch。
> > 
> > 
> > 感谢！成功解决了我遇到的问题
> > 顺便提示使用eastasia以外服务器的用户，需要把eastasia换到你所在地对应的server
> > 另外如果网速不错的话，也可以把audio-16khz-128kbitrate-mono-mp3换到更高码率
> 
> 建议使用@meetcw 的https://github.com/meetcw/ms-ra-forwarder 体验更佳

好像只有晓晓可用，我替换了voice name，但是没办法正常连接。
