### ISSUE TITLE
[BUG] 正文部分错误节选到标题栏

### ISSUE THREAD

**Issue by Alicerong** [gedoor/legado#1471]
### 机型（如Redmi K30 Pro）
>huawei Nova5Pro

### 安卓版本（如Android 7.1.1）
>鸿蒙2.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.121021

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>三网都有

### 问题描述（简要描述发生的问题）
>有一部分正文被节选到标题栏加粗字体

### 使用书源（填写URL或者JSON）
>所有书源

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>无，更新后即发生

### 日志提交（问题截图或者日志）
>![Screenshot_20211219_162339_io.legado.app.release.jpg](https://user-images.githubusercontent.com/86073357/146668547-2747d66b-0ca2-4c83-89f4-4ad7e96f2ce1.jpg)

**Comment by gedoor** [comment]
替换规则问题
