### ISSUE TITLE
[BUG/FEATURE] Azure文本朗读请求过慢/提供缓存朗读音频功能

### ISSUE THREAD

**Issue by SinoAHpx** [gedoor/legado#1472]
### 机型（如Redmi K30 Pro）
> Redmi Note 8

### 安卓版本（如Android 7.1.1）
> Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> legado_app_3.21.12192146_共存.apk

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
> 似乎是Azure文本朗读请求速度过于缓慢？

> 经过我的尝试，不管挂不挂梯子，在我的手机上，请求一段100字左右的文本，差不多需要2秒左右的时间。
> 但是如果是过于长的文字，似乎需要的时间就太久了（可能是手机性能问题，我在手机上请求过长的文本没有成功过）

> 不知道legado朗读文本的方案怎么样的？如果是先请求一大段文字，再开始读它们，读的时候再请求下一大段的话，这就可以解释为> 么我使用文本朗读的时候总是读一段之后就不读了。

那么，是否可以请大佬实现一个一段一段地请求然后读的选项呢？**甚至更进一步，提供缓存朗读音频的功能呢？**

**Comment by meetcw** [comment]
看了你在 #1469 下的回复，你的 Azure TTS服务位置是在美东的吧？过慢可能是网络延迟导致的。

我用东亚，还经常报 429 Too Many Requests。以至于我不得不想办法增加延迟。

**Comment by SinoAHpx** [comment]
> 看了你在 #1469 下的回复，你的 Azure TTS服务位置是在美东的吧？过慢可能是网络延迟导致的。
> 
> 我用东亚，还经常报 429 Too Many Requests。以至于我不得不想办法增加延迟。
> 
> 

@meetcw 我现在也换成eastasia了，另外就算我挂上梯子好像也没有太大的改善？但是我在电脑上用postman请求一大串文本就不会出现请求失败的情况，可能还有手机性能的问题？

**Comment by meetcw** [comment]
我这边东亚可以直连访问。阅读现在的逻辑应该是在读当前这段的时候就会去请求后面很多段的语音并缓存。

如果只是卡住不读了的话，会不会是接口报错了？Azure 限制了每分钟最多发起20个请求。

**Comment by Jay54520** [comment]
读几段就会卡住，应该不是请求限制的原因，因为我在几秒之内立刻停止朗读，翻到下一页，再开启朗读后有声音，但只会读一段。同时我在电脑上请求返回的音频也正常。用在线的百度朗读引擎就没有这个问题。

**Comment by meetcw** [comment]
@Jay54520 

我之前是在LoginCheckJs导入Java的Thread..Sleep方法控制请求速度的，但是在最新版本好像会阻塞APP界面。

---

Azure 官方免费的API限制太多，而且现在好像只提供50W字/每月的免费额度了？所以我现在已经放弃了 Azure TTS API，转而使用 Edge 中提供的接口（效果和Azure TTS是一样的）。但是 Edge 提供的接口是基于 WebSocket 的，所以我通过 [Vercel](https://vercel.com/) 提供的 Serverless Function 将它包装成了可供“阅读”调用的POST接口（Vercel 提供的免费额度足够日常使用了）。

如果有兴趣的话可以参考 https://github.com/meetcw/ms-ra-forwarder

**Comment by Jay54520** [comment]
我写了一个 throttle proxy server，在触发 Azure 限制之前 sleep，目前解决了。

**Comment by Jay54520** [comment]
> @Jay54520
> 
> 我之前是在LoginCheckJs导入Java的Thread.Sleep方法控制请求速度的，但是在最新版本好像会阻塞APP界面。
> 
> Azure 官方免费的API限制太多，而且现在好像只提供50W字/每月的免费额度了？所以我现在已经放弃了 Azure TTS API，转而使用 Edge 中提供的接口（效果和Azure TTS是一样的）。但是 Edge 提供的接口是基于 WebSocket 的，所以我通过 [Vercel](https://vercel.com/) 提供的 Serverless Function 将它包装成了可供“阅读”调用的POST接口（Vercel 提供的免费额度足够日常使用了）。
> 
> 如果有兴趣的话可以参考 https://github.com/meetcw/ms-ra-forwarder

我写了一个 throttle proxy server，在触发 Azure 限制之前 sleep，目前解决了。
之前尝试过聚合多个请求的文本，但是有重复、顺序不一致、和手机端显示不一致的问题。
暂时不想用 Edge 的接口，担心不稳定。
