### ISSUE TITLE
[BUG] 手动编辑朗读引擎后 concurrentRate 会被重置为 0

### ISSUE THREAD

**Issue by meetcw** [gedoor/legado#1473]
### 机型

> 小米10 Pro

### 安卓版本

> 12

### 阅读Legdao版本

> 3.21.121913

### 网络环境

> wifi，4g

### 问题描述

> 现版本朗读引擎里的 `concurrentRate` 会影响并发请求数吗？我在导入文件中将 `concurrentRate`的值设置为 1，但是导入编辑保存后再导出，发现httpTts.json 中的`concurrentRate`的值又被重置为了0。

### 复现步骤

> 1. 使用本地或网络导入任意`concurrentRate`值为1的朗读引擎
> 2. 手动编辑并保存朗读引擎
> 3. 导出朗读引擎，发现`concurrentRate`值变为了0

**Comment by meetcw** [comment]
另外请问有办法控制朗读引擎的请求频率吗？我目前是在LoginCheckJS中使用JavaImport导入并调用`Thread.sleep`方法，但是偶尔还是有同一秒发起多个请求的情况。

**Comment by gedoor** [comment]
ok,我修复一下

**Comment by gedoor** [comment]
concurrentRate生效应该就可以了

**Comment by lidawei97688** [comment]
在这里问一下，能不能弄个替换规则啥的，比如起点读书和QQ阅读朗读百分比数字52.36%时候，讯飞语言会念成五十二，百分之三十六，它把那个小数点判断成了英语的句号，要是能手动替换一下就好了，当然不添加这功能也没关系，反正这么多年过来了，早习惯了
