### ISSUE TITLE
[BUG] 看英文书籍时字间距大小不定

### ISSUE THREAD

**Issue by shinki-alice** [gedoor/legado#1474]
### 机型（如Redmi K30 Pro）
>华为mate30

### 安卓版本（如Android 7.1.1）
>harmonyos

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.121021

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>看英文书籍字间距一会大一会小
![Screenshot_20211212_150029_io legado app release](https://user-images.githubusercontent.com/76115617/146697784-96ffcbd2-1422-4769-841e-09cc8910ebb4.jpg)

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
关闭两端对齐就好了
