### ISSUE TITLE
希望支持小窗功能

### ISSUE THREAD

**Issue by yaoyunpeng** [gedoor/legado#1475]
在玩游戏的时候能使用系统的小窗模式打开软件

**Comment by easythd** [comment]
玩游戏的同时还能看书？

**Comment by gedoor** [comment]
本来就支持吧

**Comment by yaoyunpeng** [comment]
抱歉 没咋注意过邮件，主要是现在好多游戏还是不支持后台运行，有些任务自动又不能切到后台，所以支持小窗可以看小说打发时间




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月31日(星期五) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] 希望支持小窗功能 (Issue #1475)





 
玩游戏的同时还能看书？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
