### ISSUE TITLE
[Feature Request] 添加固定间隔去除换行功能

### ISSUE THREAD

**Issue by KoriIku** [gedoor/legado#1476]
### 功能描述（请清晰的、详细的描述你想要的功能）
由于几大主流色〇小说论坛为便于在电脑上阅读，要求作者发布文章时使用换行固定每行字数
例如春x四合院的要求
> 二：每行３５字。
导致大量在这些论坛发布的小说被整理为TXT后依然保留换行，在小屏幕上的阅读体验非常差

### 期望实现方式（阅读应该如何实现该功能）

提供一个定间隔去除换行的功能，将被切分的段落重新合并。

### 附加信息（其他的与功能相关的附加信息）

这是论坛提供的排版工具，其中【排版】功能实现了每35字添加换行，希望阅读可以将这个“每34字一行”中添加的换行去掉

原功能描述`快速排版，按照原创区排序规则，英文数字字母标点自动转为全角，段落空两格，每行35字，对话用「」，自动按句号、引号智能分段。`

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）

![Snipaste_2021-12-20_20-20-49](https://user-images.githubusercontent.com/86508666/146766456-20bb04e5-1fec-4e5f-8f56-383d0da5087a.png)

**Comment by ruanima** [comment]
其实可以更简单点，不是行尾句号就合并断行
