### ISSUE TITLE
[BUG] 最近app版本和web阅读纪录同步问题

### ISSUE THREAD

**Issue by easythd** [gedoor/legado#1478]
### 机型（如Redmi K30 Pro）
>三星s20

### 安卓版本（如Android 7.1.1）
>安卓11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.112719

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带，电信手机

### 问题描述（简要描述发生的问题）
>最近app版本和web阅读纪录同步问题：比如web上从677章阅读到699章，回到app上，无论怎么从书架进到阅读界面，或是杀了app重进，都还是原来的677章的内容，但点目录列表看已经到699了，如果把677章一页一页翻完又会突然前进到700章。很影响阅读体验，切换web和app时会很懵。原来应该是直接会跳到699的啊，大概最近个把月内发现变成这样了，已经特意升级过好几个最近的版本都没解决。

### 使用书源（填写URL或者JSON）
>啥书都一样

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by dianso** [comment]
本来就是这样，特性。

**Comment by gedoor** [comment]
我看看

**Comment by ybasefinal** [comment]
请问一下web的地址是多少？

**Comment by easythd** [comment]
> 请问一下web的地址是多少？

app右下角点我的，页面中间的web服务，打开，就看到地址了

**Comment by ybasefinal** [comment]
哦，原来可以这样用，不过我刚才试了一下发现打不开，不知道是什么原因

**Comment by easythd** [comment]
> 哦，原来可以这样用，不过我刚才试了一下发现打不开，不知道是什么原因

pc和手机要连到同一wifi中

**Comment by ybasefinal** [comment]
赞！打开了

**Comment by gedoor** [comment]
下版本修复

**Comment by easythd** [comment]
> 下版本修复

测试了最新版本，发现没有修复完整。
最新版本现在现象是：在app上读到613章，然后换在web上读到620章，然后再换回app，这时在app上确实是已经解决了能从书架点书籍后进到620章的阅读界面了。但是，当翻到620章结束时，进入下一章，居然是614章的内容，这时点目录来看，目录上却显示当前是621章。

**Comment by easythd** [comment]
@gedoor  未修复完整。
测试了最新版本，发现没有修复完整。
最新版本现在现象是：在app上读到613章，然后换在web上读到620章，然后再换回app，这时在app上确实是已经解决了能从书架点书籍后进到620章的阅读界面了。但是，当翻到620章结束时，进入下一章，居然是614章的内容，这时点目录来看，目录上却显示当前是621章。

**Comment by gedoor** [comment]
好的,我再修复一下

**Comment by easythd** [comment]
> @gedoor 未修复完整。 测试了最新版本，发现没有修复完整。 最新版本现在现象是：在app上读到613章，然后换在web上读到620章，然后再换回app，这时在app上确实是已经解决了能从书架点书籍后进到620章的阅读界面了。但是，当翻到620章结束时，进入下一章，居然是614章的内容，这时点目录来看，目录上却显示当前是621章。


@gedoor  您好，又打扰您了。最近的几个版本（现在我用的3.22.052113），这个帖子主题中描述的同步问题又出现了，还有上面这段描述的app上因没同步而乱跳的问题也出现了！！（感觉是当时修复的代码全回滚了一样？）
同时还出现新的一个问题：web阅读现在加了读到一章的最后，自动加载下一章，但是，每次加载都是加载的下两章，如2100章读完到最后，加载的是2102章，而不是2101章。这时按右键，是加载2103章。
这3个问题加在一起后感觉好混乱，web版基本没法用了。
拜托抽时间修复一下

**Comment by easythd** [comment]
@gedoor 这几天更新到了3.22.060120版本（gg上的pro版本），除了自动加载问题已经修复，其他几个同步的问题还是没有解决仍然一样，
