### ISSUE TITLE
[Feature Request] 换源界面显示当前阅读章节的字数

### ISSUE THREAD

**Issue by 821938089** [gedoor/legado#1479]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 1、换源界面显示每个书源的当前阅读章节的字数。

> 2、一个小细节，换源界面始终显示当前选择的源。

### 期望实现方式（阅读应该如何实现该功能）
> 1、换源界面刷新时能够显示当前阅读章节在这个源的字数，添加一个按钮切换排序方式（默认排序/按章节字数降序排序）和一个是否显示字数的开关

> 2、点击换源后列表跳转到当前选择的源

### 附加信息（其他的与功能相关的附加信息）
我提出这两个功能的主要原因是有些小说在很多的网站上采集的内容都是不全的，很多源都是只有小说开头的100多个字就没了，换了十几个源都是这样，这些小说网站可以说是更新了，但是又没有完全更新...（例如《后悔药！我的时空回溯异能》这本书：http://www.duwanjuan.com/html/1041/1041864/122683897.html ）
~~所以呢我就想在搜索引擎上找，找到了，但是没法添加到阅读APP里面（即使我自己制作了书源），因为这个网站没有搜索功能/搜索功能无法正常使用。~~

在这个过程中我发现了个体验上不太好的问题：
一个一个换源很麻烦，换源太多会导致当前选择的源超出每次点击换源时显示的列表，需要下滑一下列表选择下一个源，还有每换一个就要等一会让他加载章节目录和内容，这些小说网站速度都不咋的，换源奇慢。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>![InkedInked2_LI](https://user-images.githubusercontent.com/8674809/147486707-ddff423a-79d8-4b0c-8716-d635fbfc46b3.jpg)

![3](https://user-images.githubusercontent.com/8674809/147487246-42edcc6c-79c2-428f-a108-e38a77ede0ee.jpg)

![10](https://user-images.githubusercontent.com/8674809/147487656-b783d30f-483e-46d2-952a-698d23d193f6.jpg)

**Comment by zmn001125** [comment]
书架页面，右上角三点，添加网址

**Comment by 821938089** [comment]
> 书架页面，右上角三点，添加网址

居然还能这样，学到了

**Comment by h11128** [comment]
看来这个需求真的是历史悠久了，我之前看到的是其他人的[issue](https://github.com/gedoor/legado/issues/2973)，所以UI不太一样
