### ISSUE TITLE
“放入书架”提示的相关逻辑

### ISSUE THREAD

**Issue by yfdyh000** [gedoor/legado#148]
搜索，进入书籍目录、章节，返回，被询问是否放入书架。
* 点确定，似乎未执行返回，是否放入不确定（可以Toast提示）。再次“返回”才回到书籍信息页，但“放入书架”按钮未改变（此时可点击切换并被保存），此时修改分组似乎也被忽略（未保存）。
* 点取消，回到了书籍信息，这似乎正常。但“放入书架”的提示就意义不大了，左下的按钮很方便、常在，如果担心用户忘记加，可以按钮突出、加tip、默认保留阅读进度。

此外建议，关键词搜索结果做缓存，或者返回时要求确认（可以弹框或要求双击返回），以免误操作后需要重新搜索（可能很久。结果可能变少）。

**Comment by gedoor** [comment]
嗯

**Comment by yfdyh000** [comment]
另外，已加书架的书籍再点是进入上次阅读章节，查看书籍信息（长按，或右上菜单项）的方法不是很明显。建议点开导航栏后点左上的书名能打开“书籍信息”。

“书籍信息”中的“书源”文本，单击能编辑书源，该功能因UI无差异而很不明显，制成小按钮则较为统一。点“作者”可搜索，同上。其他项的文本如果能点，可能更方便，当前改版后的按钮偏小，比如“设置分组”的可点区域小了不少，“查看目录”也需要，“最新章节”不建议（至少不要覆盖阅读进度）。
