### ISSUE TITLE
[BUG] 朗读遇到小于3个字符的段落就会跳过朗读

### ISSUE THREAD

**Issue by yk12510** [gedoor/legado#1480]
### 机型（如Redmi K30 Pro）
>Redmi K30 Pro

### 安卓版本（如Android 7.1.1）
>11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.121021

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>朗读遇到小于3个字符的段落就会停顿2秒，然后直接朗读下一段落

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>
![IMG_20211229_090844](https://user-images.githubusercontent.com/23448486/147717057-6776a543-8ba9-4dd2-887d-6ed72eebc023.jpg)

**Comment by yk12510** [comment]
不会朗读红圈中内容

**Comment by gedoor** [comment]
我测试了没发现这种情况
