### ISSUE TITLE
图源制作的问题: 如何处理 文章正文是一个json格式, 且放置在一个<script type="application/json">中的情况.

### ISSUE THREAD

**Issue by rsyqvthv** [gedoor/legado#1488]
一个简化版的例子: 

```html
<script id="__NEXT_DATA__" type="application/json">
{
    "props":
    {
        "pageProps":
        {
            "contents":
            [
                {
                    "text": "第一段",
                    "scramble": false
                },
                {
                    "text": "第二段",
                    "scramble": false
                }
            ],
            "session": null,
            "adChapterBottom": "true"
        }
    },
    "page": "/books/[bookid]/[id]",
    "buildId": "u79Lx6g0xLnOymQ6uwXUo",
    "isFallback": false,
    "gssp": true,
    "scriptLoader":
    []
}
</script>
```

这个<sciprt>是在一个html页面的底部, 上面都是正常的html代码.

请问写书源的时候, 要如何才能得到"第一段", "第二段"这样的正文内容呢?

**Comment by rsyqvthv** [comment]
我的尝试:

```javascript
var el = document.createElement('html');
el.innerHTML = result;
var data = JSON.parse(el.getElementById('__NEXT_DATA__').textContent);
var imges_data = data.props.pageProps.images;
var images = '';
for (let i = 0; i<imges_data.length; i++) {
    images += images_data[i].src+','
}
result = images;
```

调试的时候正文检查部分只显示开始读取正文, 但似乎就停在那里, 没有下文了.

**Comment by Xwite** [comment]
`
var json=String(java.getString('#__NEXT_DATA__@html',src,false)).replace(/<.?script.*?>/g,''),data=JSON.parse(json);

var text_data = data.props.pageProps.contents;
var text = '';
for (let i = 0; i<text_data.length; i++) { text += text_data[i].text+','}
result = text
`

**Comment by rsyqvthv** [comment]
@Xwite 感谢你的回复, 但我应用你的代码后(我在前面加了一个@js:, 不知道是否应该), 得到一个错误信息: 

> org.mozilla.javascript.EcmaError: ReferenceError: "src" is not defined. (<Unknown source>#2) in <Unknown source> at line number 1

不知道这个src是做什么用的, 抱歉, 我对java不太了解. 简单搜索了下java getstring, 也没有得到这个函数有多个参数的使用情况, 不知可否帮我再看看?

感谢.

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/blob/f0dff993bcc1dfe15bb3ff5da5605422e8df47d3/app/src/main/java/io/legado/app/model/analyzeRule/AnalyzeRule.kt#L201

https://github.com/gedoor/legado/blob/f0dff993bcc1dfe15bb3ff5da5605422e8df47d3/app/src/main/java/io/legado/app/model/analyzeRule/AnalyzeRule.kt#L649
https://github.com/gedoor/legado/blob/f0dff993bcc1dfe15bb3ff5da5605422e8df47d3/app/src/main/java/io/legado/app/model/analyzeRule/AnalyzeRule.kt#L58

**Comment by Xwite** [comment]
@rsyqvthv 你的阅读版本有点旧了，src是网页的源代码，result是上一步的结果，一般情况下是等于src的，js中通过java关键词调用阅读自带的某些函数
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/help/JsExtensions.kt
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/data/entities/BaseSource.kt
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/help/http/CookieStore.kt
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/help/CacheManager.kt
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/model/analyzeRule/AnalyzeRule.kt

**Comment by rsyqvthv** [comment]
@Xwite 感谢你的回复. 我自己再摸索一下.
