### ISSUE TITLE
[BUG] 本地(本机)的文件无法开启

### ISSUE THREAD

**Issue by a8214983** [gedoor/legado#1491]
> ### 机型（如Redmi K30 Pro）
> > 
> 
> ### 安卓版本（如Android 7.1.1）
> > 
> 6.0.1
> ### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> > 3.22.010310
> 
> ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > WI-FI
> 
> ### 问题描述（简要描述发生的问题）
> > 
> 
> 我的本地txt文件没办法开启
> 
> ### 使用书源（填写URL或者JSON）
> > 
> 
> ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> > 
> 
> ### 日志提交（问题截图或者日志）
> >
![Screenshot_20220103-203101](https://user-images.githubusercontent.com/84130703/147930747-e581dd06-2edb-4c98-b174-2c013b168a5b.jpg)

**Comment by gedoor** [comment]
可能这个文件太小了,我修复一下

**Comment by gedoor** [comment]
看了下没找出问题,可以把你的文件发一下

**Comment by sartonsh** [comment]
> 看了下没找出问题,可以把你的文件发一下



> 看了下没找出问题,可以把你的文件发一下

我也有同样问题，所有txt文件都打不开。

**Comment by gedoor** [comment]
确定是3号发的版本吗

**Comment by gedoor** [comment]
确定是3号发的版本吗

**Comment by sartonsh** [comment]
> 确定是3号发的版本吗

1号以后就这样

**Comment by gedoor** [comment]
说一下你的操作步骤

**Comment by sartonsh** [comment]
> 说一下你的操作步骤

就是正常的打开'添加本地'，然后选中书籍，点击'放入书架'。再退出后进入书架'本地'分组，打开书籍。和以前一样。

**Comment by C-Entropy** [comment]
同样的问题，试了10mb+的文件也不行

**Comment by gedoor** [comment]
可能和安卓版本有关,我测试下低版本的试试

**Comment by gedoor** [comment]
刚提交了一个修复,用最新测试版本看看

**Comment by sartonsh** [comment]
最新测试版还是老问题。

**Comment by gedoor** [comment]
加我qq,77148227

**Comment by a8214983** [comment]
TXT文件已经可以看了，但没办法用TXT目录正则
![Uploading Screenshot_20220106-192729.jpg…]()
