### ISSUE TITLE
[Feature Request] 希望web上设置参数能保存在手机上，希望web上能更新目录

### ISSUE THREAD

**Issue by easythd** [gedoor/legado#1497]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 1，现在web版本在pc上阅读时，是通过同一个wifi下局域网地址访问手机的ip进行阅读的，一些设置选项参数，如颜色啊字体啊这些，不知道是按什么方式存储在哪里的(按ip域名存cookie的么？)，经常在局域网中每次手机连上去，ip都会变，一变，就要用新ip访问，设置就恢复默认了，公司的wifi我又没办法管理让我的手机永远是一个ip，所以，设置每次都要重新按喜好设置，好麻烦。
强烈希望这个设置参数能保存到手机设置里，不管是什么ip访问，都是我设置好的参数。
2，现在web上目录不会更新，如果没有在手机上更新书籍目录，在web上就是原来的，读完就没有了，必须回到手机上更新一次，然后再到web上刷新页面才会看到最新的章节。希望web书架页上多个更新目录按钮，点了能更新目录。

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
收到,我解决一下

**Comment by easythd** [comment]
这个问题解决了么？

**Comment by easythd** [comment]
什么时候能排上日程啊？

**Comment by gedoor** [comment]
已经实现了
