### ISSUE TITLE
[BUG] TXT目录正则无法点选

### ISSUE THREAD

**Issue by a8214983** [gedoor/legado#1499]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>6.0.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>WIFI

### 问题描述（简要描述发生的问题）
>更新后TXT可以使用了，但TXT目录正则有些没办法使用

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>
![Screenshot_20220106-194316](https://user-images.githubusercontent.com/84130703/148378318-a1d2848f-ef2e-434d-8931-40fd9273969e.jpg)

**Comment by gedoor** [comment]
好的,我看看

**Comment by gedoor** [comment]
超过5万字的章节自动拆分,不使用规则

**Comment by a8214983** [comment]
是一章节不超过5万字吗

**Comment by gedoor** [comment]
是的

**Comment by a8214983** [comment]
可是轻小说章节多的没办法使用，章节多的都会变成
![Screenshot_20220108-185704](https://user-images.githubusercontent.com/84130703/148641597-8fce23e2-75a8-46f7-8fe7-466b242d6684.jpg)
我找个章节少的却是可以，去年版本全部都可以用
![Screenshot_20220108-185955](https://user-images.githubusercontent.com/84130703/148641687-24518f25-ec6a-44a4-842f-e8ea0d12dd7b.jpg)

**Comment by gedoor** [comment]
我再改下
