### ISSUE TITLE
[BUG] Web 书源编辑页提示无法连接到[阅读3.0APP]

### ISSUE THREAD

**Issue by jiajun2121** [gedoor/legado#1501]
### 机型（如Redmi K30 Pro）
> Redmi K30i

### 安卓版本（如Android 7.1.1）
> Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.010615

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> Wifi 局域网

### 问题描述（简要描述发生的问题）
> 书源编辑页点击【⇊拉取源】按钮，等几秒就弹出提示 “无法连接到[阅读3.0APP]”
> 注：更新前（V3.22.010310）没发现这个问题
> 注：订阅源编辑页可正常拉取

### 使用书源（填写URL或者JSON）
> 无

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 书源编辑页点击【⇊拉取源】按钮，即可复现

### 日志提交（问题截图或者日志）
> ![image](https://user-images.githubusercontent.com/32513558/148476633-65232635-eb09-4a63-bf5f-c584f3caf333.png)

**Comment by gedoor** [comment]
我看下

**Comment by gedoor** [comment]
测试没有问题

**Comment by UltramarineSky** [comment]
这个好像跟书源数量有关，书源多了拉取会失败显示无法连接
