### ISSUE TITLE
Web端看书后手机端同步问题[BUG] 

### ISSUE THREAD

**Issue by a1239750460** [gedoor/legado#1509]
### 机型（如Redmi K30 Pro）
>小米mix2s

### 安卓版本（如Android 7.1.1）
>Android10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.010310

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>web端看书后手机端目录同步后自然翻页到下一章是同步前的下一章。上一章同理。直接点下一章按钮的话要点两次，而且还会跳章，上一章按钮的话就是同步前的上一章

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
最新版本应该已经解决了
