### ISSUE TITLE
[BUG] 语音朗读无声

### ISSUE THREAD

**Issue by liutianfang** [gedoor/legado#1510]
### 机型（如Redmi K30 Pro）
>小米8

### 安卓版本（如Android 7.1.1）
>android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.010615  3.21.122920

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动宽带， 移动4g，电信4g

### 问题描述（简要描述发生的问题）
> 听书，使用百度tts引擎，无报错，无声，段落已变红，声音只有很短的轻微噪声，可能没有收到/生成正确声音，3.21.122920偶尔可以正常收到。阿里云引擎弹出错误信息，太快没有记录到

### 使用书源（填写URL或者JSON）
>与书源无关

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 听书都出错

### 日志提交（问题截图或者日志）
>

**Comment by Xwite** [comment]
百度可能失效，阿里云需要自行登录

**Comment by QAQQIAOY** [comment]
> 

大声朗读只能朗读一章。。。
