### ISSUE TITLE
[BUG] 墨水屏文字被拦腰截断

### ISSUE THREAD

**Issue by kin9-0rz** [gedoor/legado#1512]
### 机型（如Redmi K30 Pro）
> 墨案 inkPalm5

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.010615 最新版本

### 问题描述（简要描述发生的问题）
>
安装后，将主题设置为墨水屏，阅读的时候，文字偶尔会被从中间截断。

其他主题虽然没有这个问题，但是阅读不舒适。

![image](https://user-images.githubusercontent.com/2801072/148733669-ac14a4aa-9eca-4bef-9a88-181fc65c0c57.png)

**Comment by silentle** [comment]
同款设备，但没遇到过哎，你的翻页模式是啥，页脚设置啥样

**Comment by kin9-0rz** [comment]
在边距设置里面，设置页脚就好。
