### ISSUE TITLE
希望能够加入一个类似于2.X版本中的“追更”分组。

### ISSUE THREAD

**Issue by kk7469** [gedoor/legado#152]
3.0版本里面默认只有一个全部分组，本地书籍和网络小说混杂在一起很不方便，希望能够加入类似于2.X中追更的分组，把网络小说默认放进去。如果自己手动建立的追更分组，阅读过一次后小说就不知去向，而不是在分组的最前端。

**Comment by 52fisher** [comment]
新版可以自己手动调整
