### ISSUE TITLE
[BUG] 目录识别的正则功能似乎有一些bug

### ISSUE THREAD

**Issue by zsy1314** [gedoor/legado#1520]
### 机型（如Redmi K30 Pro）
>Redmi K40 Pro

### 安卓版本（如Android 7.1.1）
>11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.011116

### 问题描述（简要描述发生的问题）
>打开本地txt时部分文件目录会识别出错（没有找到不能正常识别文件的规律）。
具体的表现形式是正则公式不能正确匹配到章节名称，但是章节名称都是很普通的样式（比如“第001章”这种）。
此时尝试自己添加正则公式，试了几种，结果分别如下
公式“第....”，可以正常识别，但是因为公式不够精确会识别到很多不是章节标题的内容。
公式“第001章”，直接输入全部内容，可以正常识别。
公式“第\d”，不能正常识别，会按照系统默认的“第1章(1)”这样自动分章
类似尝试公式“第...章”，“第.{1,3}章”也是不行。

### 使用书源（填写URL或者JSON）
>
本地txt

**Comment by cyao2q** [comment]
20220101后的版本目录识别错误，手动选择规则不生效。暂时降级了 @zsy1314

**Comment by zsy1314** [comment]
> 可以提供一个txt文件我看下

我反复对比了一下文件的区别，觉得应该是个别小说单章的字数太多。
最后试出了大概的字数，你可以用下面这个txt试一下。
[新建文本文档 (3).txt](https://github.com/gedoor/legado/files/7905067/3.txt)
这个txt直接打开目录会被处理成系统自动的“第1章(1)”格式
如果打开txt删除掉“第001章”最后面的“b”，就会被正常识别成正确的目录。

**Comment by zsy1314** [comment]
@gedoor 更新了012821，还是不能正确分目录。
