### ISSUE TITLE
[Feature Request] 为不同的书指定不同的朗读引擎

### ISSUE THREAD

**Issue by Jay54520** [gedoor/legado#1533]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 对 A 书使用“武侠男”朗读引擎，B 书使用“AI 女声”朗读引擎。第一次手动配置后，程序记住配置，之后不需要再手动变动了。

### 期望实现方式（阅读应该如何实现该功能）
> 朗读引擎的配置和单本书联系在一起。

### 附加信息（其他的与功能相关的附加信息）
> 无

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 无

**Comment by QAQQIAOY** [comment]
新版本已经有了
