### ISSUE TITLE
[BUG] 章节过多时无法获取正文内容

### ISSUE THREAD

**Issue by hrmlsr** [gedoor/legado#1534]
### 机型
>realme gt

### 安卓版本）
>Android 12

### 阅读Legdao版本
>3.22.011116

### 网络环境
>电信宽带

### 问题描述（简要描述发生的问题）
>
搜索某些章节很多的书时，书源目录使用翻页规则后无法获取正文内容

### 使用书源（填写URL或者JSON）
>
`[
    {
        "bookSourceUrl": "http://m.ucshuku.com",
        "bookSourceType": "0",
        "bookSourceName": "UC书库",
        "bookSourceGroup": "调试",
        "bookSourceComment": "",
        "loginUrl": "",
        "loginUi": "",
        "loginCheckJs": "",
        "concurrentRate": "",
        "header": "",
        "bookUrlPattern": "",
        "searchUrl": "http://m.ucshuku.com/s.php?s={{key}}",
        "exploreUrl": "",
        "enabled": true,
        "enabledExplore": true,
        "weight": 0,
        "customOrder": 0,
        "lastUpdateTime": 1642215776156,
        "ruleSearch": {
            "bookList": "class.search_box@tag.p",
            "name": "tag.a.0@text",
            "author": "tag.a.2@text",
            "kind": "tag.a.1@text",
            "bookUrl": "tag.a.0@href"
        },
        "ruleExplore": {},
        "ruleBookInfo": {
            "name": "class.info i4@tag.h3@text",
            "author": "class.info i4@tag.p.0@text##作者：",
            "lastChapter": "class.m2.0@class.list@tag.li.0@text",
            "coverUrl": "class.info i4@tag.img@src"
        },
        "ruleToc": {
            "chapterList": "class.m2.1@class.list@tag.li",
            "chapterName": "tag.a@text",
            "chapterUrl": "tag.a@href",
            "nextTocUrl": "text.下一页@href"
        },
        "ruleContent": {
            "content": "class.mainContenr@html",
            "nextContentUrl": "text.下一页@href"
        }
    }
]`

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
以搜索《暗黑破坏神之毁灭》为例（目前共计4340章），书信息可以正常获取，但正文内容为空，阅读已经正常获取到正文链接，点开正文链接可直接打开对应章节页面；
不修改书源，直接搜索其他小说，如《夜的命名术》（目前共计558章），可正确识别并显示正文内容；
删除ruleToc的nextTocUrl": "text.下一页@href规则后，可以正常获取正文内容，但目录仅可获取前20条（该书源手机版目录一页20条）

顺便问一下，想要通过手机版网页搜索获取详情页之后跳转到电脑版网页的详情页，二者域名仅m.和www.的区别，要如何设置，部分网站电脑版网页无法使用搜索功能，手机版网页可以搜索但是部分信息没有电脑版好用

### 日志提交（问题截图或者日志）
>

**Comment by Xwite** [comment]
我这边正常的
![IMG_20220115_131014](https://user-images.githubusercontent.com/82232510/149609833-c286e44a-cd86-4e15-818c-305f5106c72a.jpg)
详情页规则
```js
http://www.ucshuku.com{{@@tag.a.0@href}}
```

**Comment by hrmlsr** [comment]
> 我这边正常的 ![IMG_20220115_131014](https://user-images.githubusercontent.com/82232510/149609833-c286e44a-cd86-4e15-818c-305f5106c72a.jpg) 详情页规则
> 
> ```js
> http://www.ucshuku.com{{@@tag.a.0@href}}
> ```
非常感谢
不过我电脑上调试还是出不来，到获取首章信息这里一会之后就会关闭调试
![QQ截图20220115134426](https://user-images.githubusercontent.com/32532458/149610710-2d5861af-f8f3-4511-ac1f-d52721b74afc.png)
但是刚刚又试了几次，手机上能调试成功了，章节页面反复刷新了好几次是空白然后突然某次成功了刷出了内容。。。我都不知道是怎么成功的。。
