### ISSUE TITLE
[BUG]txt文件打开报错

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#1537]
### 机型（如Redmi K30 Pro）
>sony xperia z4 tablet

### 安卓版本（如Android 7.1.1）
>android11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.011116

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>从android7刷了类原生los18.1升级到android11后由于安卓11的机制，在类原生系统无法获取到读取存储的权限，在设置里给权限只有仅允许访问媒体文件和拒绝两个选项，不像别的软件会请求文件权限，导致txt打开方式选阅读会报错 open failed:ECCSS(Permission denied)
![Screenshot_20220115_091918](https://user-images.githubusercontent.com/73186747/149627721-527e4738-58d7-4c4a-96a7-5118b9a232d6.jpg)
![Screenshot_20220115_091949](https://user-images.githubusercontent.com/73186747/149627774-fae15b4b-4da0-4084-872f-a6e5a26fed1a.jpg)
就算应用内备份授权只能选择自带授权，自带授权受系统限制无法选择整个内部存储，把文件放入备份的路径打开也会报错open failed:ECCSS(Permission denied)
![Screenshot_20220115_014822](https://user-images.githubusercontent.com/73186747/149627609-33b803e6-a575-4784-b79a-05040127dab6.jpg)
### 使用书源（填写URL或者JSON）
>
```json

```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by Xwite** [comment]
不在支持计划里 https://github.com/gedoor/legado/issues/1308#issuecomment-938287679

**Comment by ladia** [comment]
> 不在支持计划里 [#1308 (comment)](https://github.com/gedoor/legado/issues/1308#issuecomment-938287679)

只是缺少个权限请求而已。。。。。。

**Comment by ladia** [comment]
> 不在支持计划里 [#1308 (comment)](https://github.com/gedoor/legado/issues/1308#issuecomment-938287679)
只要在AndroidManifest.xml里<manifest xmlns:android=............里加图里划线部分那行
![Screenshot_20220116_194457](https://user-images.githubusercontent.com/73186747/149659104-17565a93-0b18-42cc-a1cd-c52bbd001e78.jpg)
就能在设置里给授权了
![Screenshot_20220116_195418](https://user-images.githubusercontent.com/73186747/149659200-aabecc57-8e42-4c02-90ad-b2c96170ed79.jpg)

**Comment by gedoor** [comment]
这个你创建一个文件夹放书籍就可以了
