### ISSUE TITLE
[BUG] 阅读进度同步失效

### ISSUE THREAD

**Issue by logique233** [gedoor/legado#1538]
### 机型（如Redmi K30 Pro）
redmi 10 5g 和 huawei matepad 11
>

### 安卓版本（如Android 7.1.1）
Android 11 和 harmonyos 2.0.0
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
3.22.011116
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
移动和移动宽带
>

### 问题描述（简要描述发生的问题）
关闭阅读界面有时候可以向坚果云的webdav上传阅读进度，有时候不可以，出发条件未知。
两个设备同步阅读进度失败
（云端阅读进度 130，手机进度 126， 平板进度 130）
手机手动拉取云端进度或关闭阅读页面，会覆盖云端进度变成126
平板手动拉取云端进度会提醒超过云端进度，确认拉取后平板进度不变，云端进度变为130
>

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
坚果云有限制

**Comment by logique233** [comment]
> 坚果云有限制

是否，可以限制上传webdav次数。

**Comment by Wirili** [comment]
3.22.012019 备份与恢复-恢复 可以用，但是 拉去云端进度 一直都没有成功，进度比云端快的，会提示。比云端慢没效果

**Comment by gedoor** [comment]
我看下
