### ISSUE TITLE
[BUG]无法删除外置内存卡的文件

### ISSUE THREAD

**Issue by BCYDTZ** [gedoor/legado#1546]
### 机型（如Redmi K30 Pro）
>华为M6

### 安卓版本（如Android 7.1.1）
>鸿蒙2.0安卓9.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.012019

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>通用

### 问题描述（简要描述发生的问题）
>书籍文件在手机内置存储空间时，可以正常通过阅读软件读取和删除，当文件在外置存储卡是，只能读取不能删除。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by 1552980358** [comment]
外置存储卡是要打开系统文件管理器，手动允许读写外置存储卡根目录，然后才能进行文件修改
