### ISSUE TITLE
[BUG] webdev无法保存订阅源

### ISSUE THREAD

**Issue by gitofrain** [gedoor/legado#1550]
### 机型（如Redmi K30 Pro）
>Realme X

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.012019

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通宽带 wifi

### 问题描述（简要描述发生的问题）
>电脑编辑订阅源无法保存，提示转换源失败

### 使用书源（填写URL或者JSON）
>任意

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
![image](https://raw.githubusercontent.com/la887744/Comment-photo/main/webdev.gif)

**Comment by gedoor** [comment]
ok,我修复一下
