### ISSUE TITLE
[Feature Request] 在书源中指定书籍的分组信息

### ISSUE THREAD

**Issue by zhangtao103239** [gedoor/legado#1552]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
实现书籍自动根据分类信息进行分组
建议可以在书源中通过参数指定书籍的分组，比如书源中目前已经有分类信息，如果有对应分类的分组，可以通过书源的配置自动加入到对应分组中
### 期望实现方式（阅读应该如何实现该功能）
> 
建议在书源中增加变量对应bookGroup，当书源给出此变量时，会自动将书籍分配到对应名称的分组中
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
如下图所示，标签中展示了此书籍的分类为武侠仙侠，下面的分组可以自动对应到武侠仙侠分类中
![437367D1CCA1CA61301B0B93FA658B6A](https://user-images.githubusercontent.com/20011922/150668494-c24f60b3-81fa-492e-98f1-1e0038a8aa89.jpg)

**Comment by 1552980358** [comment]
这个是书源的tag，而且做了分类之后会导致分类问题，例如同一本书有些书源分类“武侠仙侠”，有些“武侠“+“仙侠”，这会导致后续处理略笨拙

**Comment by danvozhou** [comment]
> 这个是书源的tag，而且做了分类之后会导致分类问题，例如同一本书有些书源分类“武侠仙侠”，有些“武侠“+“仙侠”，这会导致后续处理略笨拙

同样有这个需求。
建议：不一定完全按书源的分类。而是自己定义分类（关键字），如果书源分类包括这个关键字，就归入这个自定义分类。
我建议的关键字：出版、经典、科幻、军事、武侠、……
其实对我本人来说。我根本不在乎书源自己分类的”20万字校园“之类的分法，我只需要把达到出版标准的有点文学性的，和所有其他乱起八糟的宿主加点无脑穿越类，区别开来。
