### ISSUE TITLE
[Feature Request] 朗读时自动跳过比较短的章节

### ISSUE THREAD

**Issue by arix00** [gedoor/legado#1557]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 朗读时自动跳过比较短的章节

### 期望实现方式（阅读应该如何实现该功能）
> 增加选项：不跳过，少于xxxx字的章节自动跳过

### 附加信息（其他的与功能相关的附加信息）
> 短章节一般是请假/求票等等
看书的时候问题不大（也防止错漏），朗读的时候希望可以自动跳过

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的
