### ISSUE TITLE
[BUG] 轻小说插图无法显示

### ISSUE THREAD

**Issue by a8214983** [gedoor/legado#1567]
> ### 机型（如Redmi K30 Pro）
> > 
> 
> ### 安卓版本（如Android 7.1.1）
> > 6.0.1
> 
> ### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> > 
> 
> ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > Fi-Wi
> 
> ### 问题描述（简要描述发生的问题）
> > 看线上轻小说时插图无法显示，但有些可以显示，如果这个修不好可不可以增加关闭插图的功能吗，每次无法显示图片阅读APP都会显示停止运作。
> 
> ### 使用书源（填写URL或者JSON）
> > 
> 
> ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> > 
> 
> ### 日志提交（问题截图或者日志）
> > 
> 
> ![Screenshot_20220128-185808](https://user-images.githubusercontent.com/84130703/151536283-0b0ec5f7-f1d3-4255-b8fa-7988a35cbe8a.jpg)
> 
> ![Screenshot_20220128-190404](https://user-images.githubusercontent.com/84130703/151536260-d2b29e27-57bd-4878-bd3f-16d32d6349c5.jpg)

**Comment by a8214983** [comment]
> ### 机型（如Redmi K30 Pro）
> > 
> 
> ### 安卓版本（如Android 7.1.1）
> > 6.0.1
> 
> ### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> > 
> 
> ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > Fi-Wi
> 
> ### 问题描述（简要描述发生的问题）
> > 看线上轻小说时插图无法显示，但有些可以显示，如果这个修不好可不可以增加开启、关闭插图的功能吗，每次无法显示图片阅读APP都会显示停止运作。
> 
> ### 使用书源（填写URL或者JSON）
> > 
> 
> ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> > 
> 
> ### 日志提交（问题截图或者日志）
> > 
> 
> ![Screenshot_20220128-185808](https://user-images.githubusercontent.com/84130703/151536283-0b0ec5f7-f1d3-4255-b8fa-7988a35cbe8a.jpg)
> 
> ![Screenshot_20220128-190404](https://user-images.githubusercontent.com/84130703/151536260-d2b29e27-57bd-4878-bd3f-16d32d6349c5.jpg)

**Comment by a8214983** [comment]
还有，不知道是不是我的问题，我的离线快取里的汇出变得很慢

**Comment by a8214983** [comment]
可以增加隱藏圖片的功能嗎

**Comment by gedoor** [comment]
阅读主要用于阅读文本,这个是因为图片太大内存爆了,阅读没对这方面做优化
