### ISSUE TITLE
[BUG]  64位编译支持

### ISSUE THREAD

**Issue by gclm** [gedoor/legado#1571]
### 机型（如Redmi K30 Pro）
> 小米12
 

### 安卓版本（如Android 7.1.1）
> Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.012821

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>  联通，电信，移动宽带

### 问题描述（简要描述发生的问题）
> 新增64位支持，目前小米12/MIUI13上 存在卡炖现象。目前在上面 三种网络情况下都存在找个现象

**Comment by o0HalfLife0o** [comment]
![Screenshot_2022-02-04-00-44-31-316_com absinthe libchecker](https://user-images.githubusercontent.com/6436073/152387981-f5de251b-49d6-405a-80d1-83e86ae2308f.jpg)
阅读已经是64位的哦

**Comment by gclm** [comment]
@o0HalfLife0o  好像不是的。
![image](https://user-images.githubusercontent.com/27618687/152466274-b6275c44-9d2f-4a47-a54a-a77139f9d1af.png)
图中详情对应的链接
https://s.mi.cn/c/EzSysty3?channel=Share

**Comment by 1552980358** [comment]
阅读APP 是纯JVM应用，并没有采用任何JNI C/C++或Kotlin/Native的.so库（若有，则so库会存放于`src/main/libs`中），所以 阅读APP 并不需要进行特殊处理，参阅 [您的应用是否使用了原生代码？](https://developer.android.google.cn/distribute/best-practices/develop/64-bit#native-code) ，以及下面的 [应用是否包含 64 位库？](https://developer.android.google.cn/distribute/best-practices/develop/64-bit#64-bit-libraries) 。而且你截图内也写了 `无原生库`。

纯JVM应用与使用原生库应用区别在于JDK版本只要 `>=11` 即可在 `SDK版本>=21`的Android OS上运行，并且不需要根据ABI进行适配，因为ART已经对ABI适配过了，应用的字节码能直接在ART进行转译运行，相反，带有JNI C/C++或Kotlin/Native .so库的应用则需要对ABI分别进行交叉编译.so库，直接在内核层跑，否则就会出现文章里的问题。
