### ISSUE TITLE
[BUG]无法使用WebDav备份

### ISSUE THREAD

**Issue by TrustAsia** [gedoor/legado#1573]
点击备份后显示备份成功 但是webdev服务器上并没有备份文件出现
webdev服务器为Nginx
配置段为：

`    location / {`
`        try_files $uri $uri/ /index.php?$query_string;`
`        client_max_body_size 0;`
`        charset utf-8;`
`        dav_methods     PUT DELETE MKCOL COPY MOVE;`
`        dav_ext_methods PROPFIND OPTIONS LOCK UNLOCK;`
`        create_full_put_path    on;`
`        dav_access      group:rw all:r ;`
`        auth_basic      "Authorized Users Only";`
`        auth_basic_user_file    /etc/nginx/pwdfile;`
`    }`

**Comment by 99junlin99** [comment]
无法使用webdav备份加一。使用windows连接webdav是可以正常进行创建文件等行为。

**Comment by zzhydf** [comment]
无法使用webdav备份，服务器提示我账号被破解。同时如果你更换多个webdav服务器，在最新的报错信息里会出现之前的服务器信息

**Comment by JzcEmpty** [comment]
无法使用webdav备份加一，qnap和坚果云都无法使用

**Comment by hookhuang** [comment]
我的是群晖的Webdav服务，使用netdrive调用，是正常的，但是“阅读”软件备份里设置了提示找不到页面。
![5BIN5N(Y{QS%5Z$M{{NLJ1R](https://user-images.githubusercontent.com/56341028/159704856-cc366a70-6dce-42f6-9d8d-e30205241a8e.jpg)

**Comment by zwillim** [comment]
是不是配置问题？
配置的形式是
http(s)://ip:port/dir

**Comment by hookhuang** [comment]
> 

试过了，也不行，我配置的路径是绝对路径

**Comment by TrustAsia** [comment]
> 不能用的可以发个测试账号我测试一下,可能是因为webDav标准不一样导致的

请问下如何提供账户呢？

**Comment by hookhuang** [comment]
> > 不能用的可以发个测试账号我测试一下,可能是因为webDav标准不一样导致的
> 
> 请问下如何提供账户呢？

方便的话可以加我微信hooook， 或者给我邮件hooook@qq.com   我给个测试账号你试试。    谢谢。

**Comment by TrustAsia** [comment]
> 

账户和密码已通过邮箱发送给您了 您测试的时候请把文件放在legado目录内

**Comment by hookhuang** [comment]
我使用WINSCP来测试过了，应该就是编码问题了，“阅读”用的是“iso-8859-1”编码，其他的WebDav使用的是UTF-8编码导致的，坐等调整这个编码了。
