### ISSUE TITLE
[BUG] 阅读进度同步问题

### ISSUE THREAD

**Issue by Wirili** [gedoor/legado#1577]
### 机型（如Redmi K30 Pro）
>
海信A5 红米K30pro

### 安卓版本（如Android 7.1.1）
>
Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.012821

### 问题描述（简要描述发生的问题）
> 

2个设备 一个是红米K30pro 一个是海信A5 网盘是 teracloud 和 坚果云，都试过
1、进入阅读时读取进度，红米同步进度比较快，海信时好时坏(同步不了，退出阅读再进再等下可能可以)或是要比较久，可能是书籍多了海信循环读取webdav进度中间卡出错。能否优化下进度的读取，进度都放到同一个文件里面
2、如果进度是同一章节不同页，慢的不会同步到最新的
3、拉取云端进度 用不了

**Comment by gedoor** [comment]
下版本修复
