### ISSUE TITLE
[BUG] 书源检验闪退

### ISSUE THREAD

**Issue by 565465474575** [gedoor/legado#1585]
### 机型（如Redmi K30 Pro）
>oppo A83  Windows11安卓子系统   oppo Reno7

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.020311 （前几个版本也有）

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>进行书源检验第一次会出现失效的后利用搜索（书源管理内）选中失效的书源再次进行检验（为了排除彻底不能用的书源采用此方法）会出现闪退现象，大概在勾选书源10个以上会出现这个问题。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by Xwite** [comment]
至少提供下你用的书源

**Comment by gedoor** [comment]
好的,我试试

**Comment by 565465474575** [comment]
> 好，我试试
找到个解决办法，当搜索失效书源并全选后退回上一级，也就是全部显示书源，失效的书源仍旧会勾选出来，这时在进行检验就不会闪退。

**Comment by gedoor** [comment]
我可能知道原因了,我解决一下

**Comment by gedoor** [comment]
应该不再闪退了
