### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by saber20200** [gedoor/legado#1590]
### 机型（如Redmi K30 Pro）
>小米10

### 安卓版本（如Android 7.1.1）
>安卓12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.020311

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通宽带和wifi

### 问题描述（简要描述发生的问题）
>手机端开启web服务，电脑端连接后显示后端连接失败

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>
![image](https://user-images.githubusercontent.com/76509197/152675688-ad0a6194-2fbe-488a-bc8c-08fe26d38087.png)

**Comment by Xwite** [comment]
是不是路由器开启了ap隔离

**Comment by saber20200** [comment]
并没有开启ap隔离，试了两个路由器和三个手机一个小米10一个红米note3一个是真我gt2都不可以

**Comment by Xwite** [comment]
ip填的傻

**Comment by saber20200** [comment]
ip的填写也都是对应的，通知栏里面显示的ip

**Comment by Xwite** [comment]
无法复现
检查一下你电脑和手机的通信是否受到其他软件的影响
