### ISSUE TITLE
起点书源有问题[BUG] 

### ISSUE THREAD

**Issue by zhan-cn** [gedoor/legado#1593]
### 机型（如Redmi K30 Pro）
>
k30pro

### 安卓版本（如Android 7.1.1）
>

安卓12
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22020311
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

联通宽带
### 问题描述（简要描述发生的问题）
>

起点书源无法使用，点击小说进不去，看不了章节目录
### 使用书源（填写URL或者JSON）
>
一程的
https://namofree.gitee.io/yuedu3/legado3_booksource_by_Namo.json
```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by zhan-cn** [comment]
不是一程的，是namofree的，写错了

**Comment by zhan-cn** [comment]
加载目录失败

**Comment by Xwite** [comment]
书源问题，非软件本体问题
