### ISSUE TITLE
[询问] 搜索书名的红色含义？

### ISSUE THREAD

**Issue by StrollStars** [gedoor/legado#1599]
在书架中进行书名搜索，大多情况书名右侧的红色显示为1，最近出现了2。这个2是指在两个书源中有结果，还是书架中已有这本书的意思？
如果是前者，那如何查看来自两个源的书？因为点进去只能看到来自一个书源的信息。

**Comment by gedoor** [comment]
那个数字是未读章节数,红色是表示有更新

**Comment by StrollStars** [comment]
@gedoor 感谢回复，你说的是书架上的书吧？那个是未读章节数。我指的是搜索界面的书，而且基本都是1（未加入书架只有1个章节未读？），所以这回看到出现了2比较奇怪，当然1代表什么我也不清楚。

**Comment by gedoor** [comment]
搜索界面的数字是指书源的个数

**Comment by StrollStars** [comment]
@gedoor 感谢回复，那是不是只能先加入书架，再进行换源，而没办法在加入书架前先选择源呢？因为直接点进去只能看到一本书，不能看到两本书罗列。

**Comment by wyao4-ford** [comment]
> @gedoor 感谢回复，那是不是只能先加入书架，再进行换源，而没办法在加入书架前先选择源呢？因为直接点进去只能看到一本书，不能看到两本书罗列。

点进去是书籍信息界面，和书架点进去的的界面是一样的，也可以换源才对

**Comment by StrollStars** [comment]
@wyao4-ford 感谢指教，确实在换源处可以看到多个源。
