### ISSUE TITLE
书源校检

### ISSUE THREAD

**Issue by runzzr** [gedoor/legado#1600]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 校检时超过十秒或自定义时间的书源直接判为失效，有时书源不好直接卡那，浪费时间。

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
下版本修复
