### ISSUE TITLE
[Feature Request] 希望能给书源增加自定义参数

### ISSUE THREAD

**Issue by hoshinokiseki** [gedoor/legado#1618]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望能给书源增加自定义参数，例如用户名及密码。

**Comment by Xwite** [comment]
登录ui不能满足你的要求吗

**Comment by gedoor** [comment]
确实登陆ui可以满足,而且书源参数是有的,再详情也的菜单里可以设置书源参数
