### ISSUE TITLE
[Feature Request] 希望改善一下pc端

### ISSUE THREAD

**Issue by saber20200** [gedoor/legado#1619]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
以一台手机为服务器电脑端进入web后可以直接在里面进行书籍的搜索进而阅读，进度可以同步下去.
### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
目前进度可以同步
