### ISSUE TITLE
[询问] 关于书源更新的网络导入方式选择

### ISSUE THREAD

**Issue by StrollStars** [gedoor/legado#1621]
1.如果网络链接是暂时性的，则适合在“我的→书源管理”中进行导入，更新时删除原有的（作者在《[书源合集更新【2月】](https://mp.weixin.qq.com/s?__biz=MzIzMTc0NzE1MQ==&mid=2247492267&idx=1&sn=dd754ab738d2d881fae54aa5be448ce0)》中建议的操作）再导入。
如果网络链接是永久性的，则适合在“订阅→规则订阅”中添加（作者在《[新年书源大礼包](https://mp.weixin.qq.com/s?__biz=MzIzMTc0NzE1MQ==&mid=2247488078&idx=1&sn=2115c91e1fa29c615ba4b230c5efd7d4)》中建议的操作），但是否有更新软件本身没法自动探测？

2.假设以上理解都正确，那书源更新后，已加入书架的书，是否后续还能更新，还是要重新添加？
阅读进度是否还能保持同步？
已登录过的网站是不是要重新登录？

**Comment by 821938089** [comment]
>但是否有更新软件本身没法自动探测？

更新是手动的，是否有更新可以在你手动更新后查看结果。
>书源更新后，已加入书架的书，是否后续还能更新，还是要重新添加？

能更新，如果书源没了，换源即可。

>阅读进度是否还能保持同步？

能。

>已登录过的网站是不是要重新登录？

不是。
