### ISSUE TITLE
[BUG] 书名过长导致页脚信息文字重叠

### ISSUE THREAD

**Issue by wwuhy** [gedoor/legado#1622]
### 阅读Legdao版本
>3.22.021120

### 问题描述
>书名过长会导致页脚信息文字发生重叠。

### 复现步骤
>界面信息设置中打开页脚显示，左侧显示书名，右侧显示页数及进度，打开任意超长标题书籍，即可观察到该问题。

### 问题截图
>![Screenshot](https://user-images.githubusercontent.com/99197012/154325414-1297489f-b9c1-48e2-a89e-96a7903207eb.jpg)

**Comment by wwuhy** [comment]
与 issue #1252 问题相同

**Comment by gedoor** [comment]
ok

**Comment by gedoor** [comment]
修复了
