### ISSUE TITLE
[Feature Request] 希望增加单章换源功能

### ISSUE THREAD

**Issue by breathiness** [gedoor/legado#1626]
### 当前问题
> 目前在阅读时，如果发现当前章节出现问题的话。只能通过换源功能把所有章节都替换到另一个源。但是另一个源也可能会有其它章节问题。  
> 这导致我在阅读一些长篇小说时会经常在两个源之间跳来跳去。并且换源后缓存的章节也需要重新缓存。非常麻烦。

### 期望实现方式
> 希望增加一个选项，可以只替换当前章节的内容到其他源。可以不影响之前缓存好的内容。

**Comment by gedoor** [comment]
可以了
