### ISSUE TITLE
[BUG] 书架未读数偶尔出现是0的情况

### ISSUE THREAD

**Issue by zhj9709** [gedoor/legado#1628]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
> Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.021714

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
> 小说最新章读完后，偶尔出现如下图的情况

![Screenshot_2022-02-18-15-16-26-07_e2ba09773e1c9b0](https://user-images.githubusercontent.com/13991774/154636100-017b66c3-e476-4eec-a84e-3f791f6fe209.jpg)

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
已经修复提交,等下版本
