### ISSUE TITLE
听小说自动暂停倒计时功能

### ISSUE THREAD

**Issue by CHOI159** [gedoor/legado#1632]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 听小说的播放界面是否能添加显示自动暂停倒计时，目前只有通知栏才会显示自动暂停倒计时

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by zxfszane** [comment]
我觉得是增加类似的睡眠功能。如果是听小说的话，这个功能还是需要的。

**Comment by CHOI159** [comment]
目前朗读有此功能，不过没有显示倒计时，只有在通知栏上才有显示。听书也一样，只有在通知栏上显示暂停播放倒计时
