### ISSUE TITLE
[Feature Request] 阿里TTS调用次数优化

### ISSUE THREAD

**Issue by jl0476** [gedoor/legado#1633]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 阿里的商用TTS是按照调用次数收费的，现在阅读软件貌似是按照段落进行调用的，有的段落只有几个字，也算是一次调用了，不够经济实惠。希望阅读软件在调用阿里这种按调用次数收费的TTS时，能够增加一个选项，调用的时候按照字数或者多个段落合并调用。

### 期望实现方式（阅读应该如何实现该功能）
> 1.希望阅读软件在调用阿里这种按调用次数收费的TTS时，能够增加一个选项，调用的时候按照字数或者多个段落合并调用。
2. 是否有什么其他的方式可以合并段落？方便告知下。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by o0HalfLife0o** [comment]
朗读里有个选项可以按页朗读，也许可以再加个按章节朗读会更好
![Screenshot_2022-02-22-13-03-24-288_io legado app release](https://user-images.githubusercontent.com/6436073/155066404-5894e442-b5a5-47a1-8c6f-b417d8bd4f1e.jpg)

**Comment by 28FYChow** [comment]
***@***.***已收到。

**Comment by jl0476** [comment]
> 朗读里有个选项可以按页朗读，也许可以再加个按章节朗读会更好 ![Screenshot_2022-02-22-13-03-24-288_io legado app release](https://user-images.githubusercontent.com/6436073/155066404-5894e442-b5a5-47a1-8c6f-b417d8bd4f1e.jpg)

按页朗读是每一页调用一次TTS吗？

**Comment by jl0476** [comment]
> 朗读里有个选项可以按页朗读，也许可以再加个按章节朗读会更好 
测试了下，按页朗读也是会多次调用，并不能达到降低调用次数的效果。
![image](https://user-images.githubusercontent.com/5226690/155137137-d353fd2f-b1e7-4a8f-b267-3cd3395efe7d.png)

**Comment by meetcw** [comment]
一个折中的做法：

需要起一个代理服务用于

1. 接收并合并阅读发起的请求
2. 使用阿里云的 sdk 获取带边界信息的语音
3. 根据边界信息分割语音并返回给阅读

**Comment by jl0476** [comment]
> 按章朗读会导致没办法高亮当前朗读的内容和翻页吧。
> 
> 一个折中的做法：
> 
> 需要起一个代理服务用于
> 
> 1. 接收并合并阅读发起的请求
> 2. 使用阿里云的 sdk 获取带边界信息的语音
> 3. 根据边界信息分割语音并返回给阅读

en 这种就不是阅读软件直接调用aliyun的tts了，需要自己开发一个服务了。

**Comment by jl0476** [comment]
希望能够考虑下 @gedoor

**Comment by gedoor** [comment]
合并发起请求没法分段,没法准确定位阅读到哪里,体验不好

**Comment by jl0476** [comment]
是否可以增加按页请求，每页请求一次？ @gedoor

**Comment by kettly1260** [comment]
> 合并发起请求没法分段,没法准确定位阅读到哪里,体验不好

但是使用azure之类的感觉整章发起的请求会更少。服务器不容易出问题
