### ISSUE TITLE
[BUG] 漫画边距过大，会使图片超出屏幕宽度

### ISSUE THREAD

**Issue by nshusr** [gedoor/legado#1640]
### 机型（如Redmi K30 Pro）
>
一加8T

### 安卓版本（如Android 7.1.1）
>
安卓12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.022219 (10503)

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
漫画边距过大，会使图片超出屏幕宽度

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
打开一本漫画

### 日志提交（问题截图或者日志）
>
设置边距
![Screenshot_2022-02-22-21-58-58-36_90024215e504237c76412be1999ad914](https://user-images.githubusercontent.com/45023042/155147223-d2a42804-3adf-4a12-9cbc-3d296ccd6996.jpg)

0边距
![Screenshot_2022-02-22-21-59-02-23_90024215e504237c76412be1999ad914](https://user-images.githubusercontent.com/45023042/155147262-46ce65f4-5051-4773-80d8-de45391fc994.jpg)

**Comment by dalaoha** [comment]
漫画>点击屏幕中间>右上角自己看

**Comment by nshusr** [comment]
新版已经优化，不会超出了
