### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ben5758** [gedoor/legado#1642]
### 机型（如Redmi K30 Pro）
>小米8

### 安卓版本（如Android 7.1.1）
>MIUI10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>WiFi

### 问题描述（简要描述发生的问题）
>导入本地txt文件（非小说），一直显示“数据加载中”，但实际只有一页内容

### 使用书源（填写URL或者JSON）
>不是书源，是本地自建的txt文件

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by ben5758** [comment]
文件编码utf8，也不能换成其它。我网上下的txt和epub格式都能加载出来，自建的txt文档不能加载

**Comment by gedoor** [comment]
好的,我测试一下

**Comment by dianso** [comment]
我今天看金庸越女剑，字数很少的小说，竟然也是这个现象！

**Comment by ben5758** [comment]
就是这样的文件：ym.txt，王维咏佛诗集.txt。不知道差别在哪里



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 23, 2022 17:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gedoor/legado] [BUG]  (Issue #1642)




 
好的,我测试一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gedoor** [comment]
测试版本已经修复
