### ISSUE TITLE
[BUG] 在线朗读从3.22.020919起，几乎不可用

### ISSUE THREAD

**Issue by o0HalfLife0o** [gedoor/legado#1643]
### 机型（如Redmi K30 Pro）
>redmi k20p

### 安卓版本（如Android 7.1.1）
>miui12.5 android11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.020919至今

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带，联通流量

### 问题描述（简要描述发生的问题）
>在线朗读，在3.22.020311时除非切换网络，否则一直正常播放，几乎没有遇到过暂停播放，但到了3.22.020919，朗读几分钟必停，即使阅读一直在前台常亮，也会暂停，但是播放状态又是显示正在播放的，点一下暂停，却会跳一下暂停状态后又立刻恢复正常播放
之前一直都是用的最新版，但是以为这个问题很快会修复就没有提，这几天实在受不了，从1月初的版本开始测试，每个版本朗读半小时，一直到3.22.020311都是正常，但一换到3.22.020919，5~10分钟左右问题必现

### 使用书源（填写URL或者JSON）
>

```json
{
  "": "0",
  "contentType": "",
  "header": "",
  "id": 1645448865916,
  "loginCheckJs": "",
  "loginUi": "",
  "loginUrl": "",
  "name": "路由器-晓晓",
  "url": "http://:12345/tts-ms,{\n    \"method\": \"POST\",\n    \"body\": {\n        \"informant\":\"zh-CN-XiaoxiaoNeural\",\n        \"style\": \"Chat\",\n        \"rate\": {{ speakSpeed / 4.8 }},\n        \"quality\": \"ogg-24khz-16bit-mono-opus\",\n        \"text\": \"{{java.encodeURI(speakText)}}\"\n    }\n}"
}





```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
好的

**Comment by gedoor** [comment]
朗读停止的时候日志里面有错误吗,就是菜单里面的日志

**Comment by o0HalfLife0o** [comment]
@gedoor 稍等，我试试

**Comment by o0HalfLife0o** [comment]
@gedoor 刚刚安装上最新play版，打开其他设置里的记录日志后听书10分钟左右吧，就出现了自动暂停，但没有查到有任何日志记录

**Comment by gedoor** [comment]
那我自己测试吧

**Comment by o0HalfLife0o** [comment]
@gedoor 我昨晚睡觉前安装最新的测试版02242241，听了1个小时左右，早上起床也听了1个多小时，都没有遇到暂停的问题，中午再试试看

**Comment by gedoor** [comment]
又修复了一个朗读bug

**Comment by o0HalfLife0o** [comment]
中午安装了最新版，连续朗读了1个半小时，都没有暂停，应该是修复了，谢谢啦
