### ISSUE TITLE
[Feature Request] 支持 Data URLs 图片的显示

### ISSUE THREAD

**Issue by NihilityT** [gedoor/legado#1650]
### 功能描述（请清晰的、详细的描述你想要的功能）
一些网站会使用 [Data URLs] 来显示封面或者正文中的图，还有一些不规范的 epub 文件也会使用这样的形式来内嵌图片。
目前阅读在这方面似乎没有相关的支持，这会导致无法为一些特别的网站制作源，一些 epub 文件也无法正常显示。
因此希望能支持使用 [Data URLs] 来显示图片。

### 期望实现方式（阅读应该如何实现该功能）
1. 为书籍信息编辑中的封面地址提供 [Data URLs] 支持
2. 支持书籍正文中的 `<img src="data:image/xxx;yyy">` 图片显示

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

[Data URLs]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by NihilityT** [comment]
发现在 https://github.com/gedoor/legado/pull/1612 和 https://github.com/gedoor/legado/pull/1614 中已经支持了，但是规则没有写正确，导致没有带 [MIME type] 的图片无法显示出来。
根据 MDN 中的定义，[Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) 中有两部分是可选的，而代码里面的改动没有写成可选。
> data:\[\<mediatype>]\[;base64],\<data>

https://github.com/gedoor/legado/blob/4fc68405edc545c5eb2a68f632c7c4c5cefb7d37/app/src/main/java/io/legado/app/model/analyzeRule/AnalyzeUrl.kt#L461-L467

根据 MDN 中记载的 [MIME type] 定义，可能出现这样的 type：`text/plain;charset=US-ASCII`，因此这里简单的正则改法是：`data:.*?;base64,(.*)`

[MIME type]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

**Comment by Xwite** [comment]
`data:.*?(?:;base64)?,(.*)`

**Comment by NihilityT** [comment]
@Xwite 是图片，可是这一段是可选的，也就可以忽略。
实现上取得数据后如果是图片的话也可以在数据中找到 PNG 之类的标头，chrome 就支持不带 type 的 data url。

**Comment by Xwite** [comment]
改了
