### ISSUE TITLE
[Feature Request] 希望增加背景轮播功能

### ISSUE THREAD

**Issue by Learces** [gedoor/legado#1663]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 背景可以在多张图片间自动轮播
> 可以自定义轮播时间间隔，图片过度方式
> APP可以单独备份一份背景图片，而不是直接引用手机图库图片，防止误删丢失背景
>  轮播图集可以多份

### 期望实现方式（阅读应该如何实现该功能）
> 无

### 附加信息（其他的与功能相关的附加信息）
> 加入与小说题材相关的背景轮播图，提升沉浸感，特别是都市、灵异类的小说

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by dalaoha** [comment]
不推荐，因为图片轮播会加重软件的内存使用量，而且很多人只看书的
