### ISSUE TITLE
[Feature Request] 增加导出/下载小说为mobi格式文件的功能

### ISSUE THREAD

**Issue by imldy** [gedoor/legado#1667]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望增加导出/下载小说为mobi格式（或者其他[kindle可接受的格式](https://www.amazon.cn/gp/help/customer/display.html?nodeId=G5WYD9SAF7PGXRNA) ）文件的功能，方便kindle使用

### 期望实现方式（阅读应该如何实现该功能）
> 导入/下载到手机存储空间，或者为方便导入到kindle而提供在web服务中的下载按钮。

### 附加信息（其他的与功能相关的附加信息）
> kindle导入小说的方式：直接拷贝小说文件到kindle内置的存储卡、发送到设备邮箱（适合用户拿到文件手动发送）、kindle“体验浏览器”中点击下载链接（这个比较适合基于“web服务”开发吧，不过貌似此浏览器兼容性较差）。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
对这种格式不了解,可以帮我找一下这方面的库

**Comment by laulguo** [comment]
虽然不能直接帮助到你，但我这里有个工具可以直接将EPUB无损转换为AZW3，你看可以吗

**Comment by imldy** [comment]
> 对这种格式不了解,可以帮我找一下这方面的库

好的

**Comment by imldy** [comment]
> 虽然不能直接帮助到你，但我这里有个工具可以直接将EPUB无损转换为AZW3，你看可以吗

主要还是小说文件来源问题，有的小说连epub文件都找不到，所以要借助阅读的书源。

**Comment by laulguo** [comment]
> > 虽然不能直接帮助到你，但我这里有个工具可以直接将EPUB无损转换为AZW3，你看可以吗
> 
> 主要还是小说文件来源问题，有的小说连epub文件都找不到，所以要借助阅读的书源。

就是多转换一步，阅读导出EPUB，你电脑上转MOBI。
