### ISSUE TITLE
java.getCookie获取不了cookie

### ISSUE THREAD

**Issue by asters1** [gedoor/legado#1669]
java.getCookie获取不了cookie
我也不知道是不是我写的不对，大佬们看看
![IMG_20220302_154407](https://user-images.githubusercontent.com/97214636/156317502-b0b9d210-8d04-4e12-ad95-fcf132b94103.jpg)
![IMG_20220302_154439](https://user-images.githubusercontent.com/97214636/156317510-25c453fb-7feb-4faa-b2a8-ab873842dac1.jpg)

**Comment by 821938089** [comment]
试下baseUrl

**Comment by Xwite** [comment]
你的登录url不是qidian.com域名下的，应该是yuwen.com

https://github.com/gedoor/legado/blob/86171c3e7f9914ad1ad4191058b212bf9794e19a/app/src/main/java/io/legado/app/utils/NetworkUtils.kt#L163-L174

**Comment by dalaoha** [comment]
更新为阅读最新版本(0228版本)就好了，最近即可版本cookies获取都有问题

**Comment by gedoor** [comment]
这个最新版本有问题吗,没有我就关闭了
