### ISSUE TITLE
[bug]打开阅读0228版自动消耗流量500k+(未做任何操作)

### ISSUE THREAD

**Issue by dalaoha** [gedoor/legado#1672]
只是打开阅读3.0最新版(0228更新)，软件就会自动无限消耗流量(没有更新书等任何操作，只是打开阅读)
，流量消耗时时500k+
，希望大佬修复一下
。
流量用户真心受不了，打开阅读半小时，啥也不干，都可能100m流量没了。

**Comment by gedoor** [comment]
webDav的同步耗的流量吧
