### ISSUE TITLE
[Feature Request] “恢复忽略列表”增加“备份路径”的选项

### ISSUE THREAD

**Issue by Juijote** [gedoor/legado#1677]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 不同设备的备份路径可能不一致，在“恢复忽略列表”增加“备份路径”的选项，方便不同设备同步时减少操作。

### 期望实现方式（阅读应该如何实现该功能）
> 直接增加选项即可。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
ok
