### ISSUE TITLE
[Feature Request] 希望将所有书签在书籍外单独做成一个合集

### ISSUE THREAD

**Issue by RYLYLMQR** [gedoor/legado#1680]
### 因为看的书很多，有些很重要的书签和感悟一本一本的进去看感觉挺麻烦的，就想着如果能在书籍外单独设立一个按书分类查看书签的地方可就太方便了
> 

### 可以在“我的”加一个书签的立项，点进去就是有过书签的书籍，再点进入后就能查看自己标记的内容
> 

> 

>

**Comment by Liz-Sun** [comment]
支持！要是能把书签批量导出就更棒了！
