### ISSUE TITLE
[BUG] 某j的付费部分看不了

### ISSUE THREAD

**Issue by keepgoing69** [gedoor/legado#1702]
### 机型（如Redmi K30 Pro）
> Redmi K30

### 安卓版本（如Android 7.1.1）
>android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.030919

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>用某j书源时，一到付费章节，页面就只显示章节题目+获取正文失败  内容为空 或者是章节题目+获取正文失败+乱码

### 使用书源（填写URL或者JSON）
>源仓库里某j所有3.0的书源

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>某j正版官网的免费章节都可以在阅读app上正常阅读，免费章节结束，一到付费章节就出现获取正文失败  内容为空 或者获取正文失败和一堆乱码，阅读某j上所有的付费章节时显示的都是这两种情况。

### 日志提交（问题截图或者日志）
>
![26b80b320316541f](https://user-images.githubusercontent.com/101493976/158048641-150c0569-3e1a-4405-88ec-ed10a0d04b7c.jpg)
![-7ef0ad1b27011a9c](https://user-images.githubusercontent.com/101493976/158048650-d99ff419-05ca-4728-a7d6-a230768d864b.jpg)

**Comment by YumikoAzu** [comment]
啊这……你还想能用阅读看付费章节啊？除非你登录了账号而且购买了章节。

**Comment by dianso** [comment]
给我转账，我可以告诉你怎么付费观看

**Comment by gedoor** [comment]
这个不属于阅读问题

**Comment by keepgoing69** [comment]
啊抱歉抱歉啊，是我我我理解错了咱们app的功能了，实在是不好意思啊（挨打）（挨打）

**Comment by keepgoing69** [comment]
是我傻了傻了（挨打）真的抱歉啊，麻烦您了
