### ISSUE TITLE
[BUG] 息屏下tts 仅播放当前章节内容

### ISSUE THREAD

**Issue by scjtqs2** [gedoor/legado#1707]
### 机型（如Redmi K30 Pro）
> 三星 S21U

### 安卓版本（如Android 7.1.1）
> Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.2.2.030919

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 联通5G、电信wifi

### 问题描述（简要描述发生的问题）
> 升级系统到 oneui4.0 (安卓12） 后，使用听书功能，锁屏后听完`当前章节`，会立马停止语音。需要点亮一下屏幕，或者耳机手动按一下播放键才能继续播放语音，播放下一章节的内容。锁屏后又会继续出现此现象。
>
> 已关闭电池检测、并开启自动启动。使用的tts是`讯飞语记`。
>
> 安卓11的时候无此问题。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>  升级系统到 oneui4.0 (安卓12） 后，使用听书功能，锁屏后听完`当前章节`，会立马停止语音。需要点亮一下屏幕，或者耳机手动按一下播放键才能继续播放语音，播放下一章节的内容。锁屏后又会继续出现此现象。

### 日志提交（问题截图或者日志）
>

**Comment by scjtqs2** [comment]
是否能够增加 “禁用电池优化”的功能

**Comment by xingshao-ye** [comment]
机型（如Redmi K30 Pro）
荣耀 v30pro

安卓版本（如Android 7.1.1）
Harmony OS 2.0.0.222

阅读Legdao版本（我的-关于-版本,如3.20.112220）
3.22.040517

网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
联通5G、电信wifi

问题描述（简要描述发生的问题）
使用听书功能，锁屏后听完当前章节，会立马停止语音。需要点亮一下屏幕，播放下一章节的内容。锁屏后又会继续出现此现象。

使用书源（填写URL或者JSON）
使用的tts是讯飞语记
