### ISSUE TITLE
[BUG] web 端阅读页面出现滚动条

### ISSUE THREAD

**Issue by fwzuw** [gedoor/legado#1711]
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.031519

### 问题描述（简要描述发生的问题）
>![image](https://user-images.githubusercontent.com/48246272/158527699-01668b20-1cd6-4213-9730-8d0d27652a40.png)![image](https://user-images.githubusercontent.com/48246272/158528252-955a620a-2347-4f16-a8ba-11756e5e5b4c.png)

**Comment by Xwite** [comment]
https://github.com/gedoor/legado_web_bookshelf/pull/18
