### ISSUE TITLE
[BUG] 返回书架关闭app再打开仍然自动跳转最近阅读

### ISSUE THREAD

**Issue by qmzmdqs** [gedoor/legado#1714]
返回书架关闭app再打开仍然自动跳转最近阅读。应该算bug吧。不太方便啊。

**Comment by gedoor** [comment]
这个是有开关的,设置里面

**Comment by qmzmdqs** [comment]
额，我的意思是需要这个功能。如果app被kill掉前是读书，再次打开就是自动进入，如果不在读书，返回了，那再次打开应当不用自动进入。这样比较合理些吧，比如微信读书其它阅读软件也是这样设置的
