### ISSUE TITLE
web端多了滚动条BUG] 

### ISSUE THREAD

**Issue by a1239750460** [gedoor/legado#1715]
### 机型（如Redmi K30 Pro）
>
小米mix2s

### 安卓版本（如Android 7.1.1）
>
android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.031519
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
更新版本后web端的的阅读界面多了个滚动条

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>
![image](https://user-images.githubusercontent.com/28300775/158763680-1a0bd118-1366-430f-aa60-c18bd279072e.png)

**Comment by gedoor** [comment]
下版本解决

**Comment by a1239750460** [comment]
感谢
