### ISSUE TITLE
[BUG] 自动阅读bug

### ISSUE THREAD

**Issue by zniwva** [gedoor/legado#1716]
### 机型（如Redmi K30 Pro）
>
平板

### 安卓版本（如Android 7.1.1）
>
7.1.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>不记得从哪个版本开始的bug，只记得是自动阅读添加翻页模式和按中间菜单键暂停自动翻页后开始有的，现在版本还没有修复。

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
自动阅读开启后，点中间菜单键暂停翻页再点一下继续自动翻页，弹出现导航栏虚影，大约1/3的几率出现，没有按键只有导航栏虚影，已开隐藏导航栏，试了开关其他设置都不管用，之前版本没这问题。![Screenshot_2022-03-17-12-09-03.jpeg](https://user-images.githubusercontent.com/101483716/158785001-91fa2a9c-078b-4814-950b-a7905f71f78c.jpeg)

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
自动阅读开启后，点中间菜单键暂停翻页再点一下继续自动翻页，弹出导航栏虚影，大约1/3的几率出现。下图中的设置也试了，不管用。![Screenshot_2022-03-17-18-04-07.jpeg](https://user-images.githubusercontent.com/101483716/158785633-8021a710-b0c7-461d-9fbe-84f59e100d2f.jpeg)

### 日志提交（问题截图或者日志）
>![Screenshot_2022-03-17-12-09-03.jpeg](https://user-images.githubusercontent.com/101483716/158785192-167784cc-80bd-4fc4-a631-fea3f4f89409.jpeg)

**Comment by gedoor** [comment]
我试下

**Comment by gedoor** [comment]
我在模拟器上测试没发现这种情况
