### ISSUE TITLE
[Feature Request] 切换下一个源，换源搜索章节名

### ISSUE THREAD

**Issue by wojeer** [gedoor/legado#1718]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 点击小说→无内容→点击换源（1、换下一个源或自动定位到之前的源）
点击小说后换源搜索，源名称？不该是章节名或编号（或源名称）

### 期望实现方式（阅读应该如何实现该功能）
> 1、点击换源（换下一个源或自动定位到之前的源）
2、点击换源搜索 第一百一十一章或章节名

### 附加信息（其他的与功能相关的附加信息）
> 目前换源步骤：点击小说（正在手打中请稍后）→换源→自动获取书源→划拉划拉点击→加载中→正在手打中
ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤ ㅤㅤ  ↑←←←←←←←←←←←←←←←←←←←←←←←←←↓
### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 1、点击换源（换下一个源或自动定位到之前的源）
2、点击换源搜索 第一百一十一章或章节名

**Comment by gedoor** [comment]
分单章换源和整体换源,单章换源点击源会让选择章节
