### ISSUE TITLE
[BUG] 传书功能咨询

### ISSUE THREAD

**Issue by zhisibi** [gedoor/legado#1722]
![image](https://user-images.githubusercontent.com/52585688/159003357-0e4be89c-14cc-47dd-a5d8-39280f8302af.png)
传书界面怎么使用？提示上传成功了 但是手机端书架上却看不到。
这个功能怎么使用功能呢？

**Comment by gedoor** [comment]
成功了书架里应该有的啊

**Comment by zhisibi** [comment]
![image](https://user-images.githubusercontent.com/52585688/159005217-
![image](https://user-images.githubusercontent.com/52585688/159005698-00ad6260-a4ac-4dde-a61c-f1fa6b74e662.png)

可能是BUG了！
手机端版本 3.22.031209  

还有一个BUG  ：分组管理不能用

**Comment by gedoor** [comment]
我试试

**Comment by coolcoolcloud** [comment]
我也遇到了这个问题，f12看了一下请求，响应是
{"errorMsg":"保存书籍错误\n没有设置书籍保存位置!","isSuccess":false}
然后我找了一下，在其他设置了有一个书籍报错位置
我允许它访问下载内容
重新上传，响应
{"data":true,"errorMsg":"","isSuccess":true}
书架里就有了，下载目录也能看到我上传的文件
