### ISSUE TITLE
[Feature Request] 允许给书籍指定详情、目录地址

### ISSUE THREAD

**Issue by baka-gourd** [gedoor/legado#1723]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 允许给书籍指定详情、目录地址，从而跳过更新时的搜索过程

### 期望实现方式（阅读应该如何实现该功能）
> 在书籍信息编辑中提供编辑选项

### 附加信息（其他的与功能相关的附加信息）
> 因为某些源的搜索要过recaptcha之类的，这样可以直接解决这个问题

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
书籍更新使用的是详情或目录地址，不会进行搜索

**Comment by gedoor** [comment]
更新确实不会重新搜索
