### ISSUE TITLE
[Feature Request] 接入优书网评分 和 榜单

### ISSUE THREAD

**Issue by PlexPt** [gedoor/legado#1725]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 接入优书网评分 https://www.yousuu.com/rank/today

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by javacoffer2020** [comment]
作者再三说了，阅读只是一个类似于浏览器的工具，不提供具体内容。
所以，如果你需要特定的内容，可以根据教程自己写脚本，或求助各位维护书源或订阅源的大大们。
你可以加阅读的公众号——开源阅读，获取更多信息

**Comment by PlexPt** [comment]
脚本无法实现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月27日(周日) 上午10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] [Feature Request] 接入优书网评分 和 榜单 (Issue #1725)




 
作者再三说了，阅读只是一个类似于浏览器的工具，不提供具体内容。
 所以，如果你需要特定的内容，可以根据教程自己写脚本，或求助各位维护书源或订阅源的大大们。
 你可以加阅读的公众号——开源阅读，获取更多信息
