### ISSUE TITLE
[BUG] .mobi文件打开后为乱码

### ISSUE THREAD

**Issue by DTpeel** [gedoor/legado#1726]
### 机型（如Redmi K30 Pro）
>Honor 50 SE

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.031722

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>导入后缀为.mobi文件后，打开为乱码 无法正常阅读

### 使用书源（填写URL或者JSON）
>本地导入

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>导入mobi文件，如果需要我可提供.mobi文件 方便尝试导入测试

### 日志提交（问题截图或者日志）
>
![Screenshot_20220321_230631](https://user-images.githubusercontent.com/61195619/159290384-cec3162a-93ba-48f5-9631-c9c57c1f93a7.jpg)

**Comment by Xwite** [comment]
不支持mobi

**Comment by DTpeel** [comment]
> 

那有没有计划支持mobi格式文件的打算？

**Comment by Xwite** [comment]
@gedoor @DTpeel 
可以先转换成epub
https://github.com/gedoor/legado/issues/1667

**Comment by DTpeel** [comment]
> @gedoor @DTpeel 可以先转换成epub #1667

如果暂无mobi文件的相关计划，提个不成熟的建议，就是导入时检测是否为受支持的文件类型 若不是进行弹窗告知
“此文件为不受支持文件，您可以继续导入，但可能会导致乱码”
然后给三个选项，继续导入，自动转换，取消导入

请问这种可以实现吗？
