### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by RealNasty** [gedoor/legado#1731]
I'm not sure if i'm the only english user or what but nonetheless I hope I can fix this small issue.

First of all, the app is just awesome. I love every bit of it.
Now... Sometimes I like to use TTS to listen while doing stuff, Problem is even though I set everything up as english the voice that's spoken is not.
I'll provide some Screenshots for you to see.

![Screenshot_20220325-192354_Legado](https://user-images.githubusercontent.com/61031834/160187661-56d9eca9-77fa-4108-9105-16510704092a.png)
![Screenshot_20220325-192316_Settings](https://user-images.githubusercontent.com/61031834/160187666-f10e67fa-0480-49de-9392-80c132c72d1f.png)

**Comment by gedoor** [comment]
ok
