### ISSUE TITLE
[Feature Request] 关于书籍缓存自动清除

### ISSUE THREAD

**Issue by cainb** [gedoor/legado#1734]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 目前删除书籍和临时阅读但并未添加至书架的书籍产生的缓存不会自动清除，能否实现删除书籍或临时阅读的书籍在离开后自动清除缓存

### 期望实现方式（阅读应该如何实现该功能）
> * 从书架删除书籍时自动删除对应的书籍缓存
>
> * 未添加至书架的书籍产生的缓存和添加到书架产生的缓存分开存储，并在设置里分别提供清除书籍缓存和临时书籍缓存（如果能自动清除临时缓存自然更加美妙啦~

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
退应用的时候会自动清楚不在书架上书籍的缓存
