### ISSUE TITLE
将【本地】分组中的书移动到其他分组时【本地】移动失败

### ISSUE THREAD

**Issue by zja0918** [gedoor/legado#1741]
### 机型（如Redmi K30 Pro）
>Mate30 5G

### 安卓版本（如Android 7.1.1）
>HarmonyOS 2.0.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.032521

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>将【本地】分组中的书箱移动到其他分组时，书籍不会移动到目标分组中，只会复制到目标分组中。此时如果将【本地】分组中的书籍移除，目标分组中的书籍也会被移除

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by Xwite** [comment]
`移动`应该改成`添加`

**Comment by zja0918** [comment]
那可以实现移动吗？
