### ISSUE TITLE
[BUG] 书籍更换书源后，书签跳转错位

### ISSUE THREAD

**Issue by RYLYLMQR** [gedoor/legado#1743]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
比如一本书原本在笔趣阁书源下做好的书签摘抄，换成其他章节有差异的书源就会跳转错位，并且进度越往后错位越严重，最离谱的是在三百多章标下的书签往后拉了二十章
导致我现在都不敢乱换书源，一换几十条书签就全都错位了

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by Xwite** [comment]
目录内容都不一样了，书签还能准确定位吗？
书签记录的应该是章节序号和标记的位置，不是内容

**Comment by Xwite** [comment]
目录都不一样了，书签还能准确定位吗？
书签记录的应该是章节序号

**Comment by Xwite** [comment]
目录内容都不一样了，书签还能准确定位吗？
书签记录的应该是章节序号

**Comment by gedoor** [comment]
确实,这个没什么好的解决方法
