### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xianfanjie** [gedoor/legado#1746]
### 机型（如Redmi K30 Pro）
>
Redmi K40 Pro
### 安卓版本（如Android 7.1.1）
>
Android11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.033020
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动

### 问题描述（简要描述发生的问题）
>

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
下载app打开弹出的说明看不清，还有其他的说明。

### 日志提交（问题截图或者日志）
>

![IMG_20220401_011958](https://user-images.githubusercontent.com/102248059/161114220-d7fe4e9a-c871-4a79-b044-f02dc008619e.jpg)
看不清字，一片白。

![IMG_20220401_011936](https://user-images.githubusercontent.com/102248059/161114428-7b6035c3-fb24-4a7f-992c-5f2db0ef2d4a.jpg)

报错截图。

![IMG_20220401_012836](https://user-images.githubusercontent.com/102248059/161114856-e6a54246-46b8-46d8-89c6-5a5c5e0a23d9.jpg)
![IMG_20220401_012805](https://user-images.githubusercontent.com/102248059/161114860-a86aa0f8-0c97-4082-9c14-d934668b1363.jpg)
文件夹使用不了，不能导入本地小说

**Comment by xianfanjie** [comment]
试了下可以导入本地小说，移动到其他目录就能访问了。之前小说放在在download目录下的，这个目录不能选择。

**Comment by Xwite** [comment]
小米主题问题，换成默认试试

[android限制](https://developer.android.google.cn/training/data-storage/shared/documents-files?hl=zh-cn#grant-access-directory)
> 在 Android 11（API 级别 30）及更高版本中，您不能使用 ACTION_OPEN_DOCUMENT_TREE intent 操作来请求访问以下目录：
> * 内部存储卷的根目录。
> * 设备制造商认为可靠的各个 SD 卡卷的根目录，无论该卡是模拟卡还是可移除的卡。可靠的卷是指应用在大多数情况下可以成功访问的卷。
> * Download 目录。

**Comment by xianfanjie** [comment]
> 小米主题问题，换成默认试试
> 
> [android限制](https://developer.android.google.cn/training/data-storage/shared/documents-files?hl=zh-cn#grant-access-directory)
> 
> > 在 Android 11（API 级别 30）及更高版本中，您不能使用 ACTION_OPEN_DOCUMENT_TREE intent 操作来请求访问以下目录：
> > 
> > * 内部存储卷的根目录。
> > * 设备制造商认为可靠的各个 SD 卡卷的根目录，无论该卡是模拟卡还是可移除的卡。可靠的卷是指应用在大多数情况下可以成功访问的卷。
> > * Download 目录。

感谢，换了主题后解决了。
