### ISSUE TITLE
希望可以增加书签批量导出功能

### ISSUE THREAD

**Issue by Liz-Sun** [gedoor/legado#1747]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
希望可以增加书签批量导出功能，即一整本书的书签文字可批量导出为txt，或批量导出至第三方笔记软件，比如要是能导出到语雀或印象笔记就好啦
### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
ok
