### ISSUE TITLE
请问谷歌版如何使用外部模板

### ISSUE THREAD

**Issue by SkyDream01** [gedoor/legado#1749]
请问谷歌版如何使用外部模板

**Comment by ag2s20150909** [comment]
在导出目录新建一个名为```Asset```的文件夹,目录结构如下
```
.
├── Asset
│   ├── Images
│   │   └── test.jpg
│   ├── Styles
│   │   └── main.css
│   └── Text
│       ├── chapter.html
│       ├── cover.html
│       └── intro.html
└── 
```
Asset中里面必须有Text文件夹，Text文件夹里必须有chapter.html，否则导出正文会为空
chapter.html的关键字有{title}、{content}
其他html文件的关键字有{name}、{author}、{intro}、{kind}、{wordCount}
