### ISSUE TITLE
[掉帧] 

### ISSUE THREAD

**Issue by 1049234725** [gedoor/legado#1750]
### 机型
>Redmi K30 Pro

### 安卓版本
>11

### 阅读Legdao版本
>3.22.033020,等多个版本

### 网络环境
>无关

### 问题描述
>滑动阅读掉帧，字数越小越严重，
 经测试 字号越小越卡 最低就10帧
 正常使用的话掉到60帧左右（原120帧） 

### 使用书源（填写URL或者JSON）
>无关

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>正常使用有掉帧现象，无论60还是120帧，把字数调到最小，帧率达到10帧左右
，在其他软件测试没有该现象(不会因为字数多少而影响帧率）

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
正在想办法
