### ISSUE TITLE
[Feature Request] 期望实现 验证书源是否避开某点防盗版功能

### ISSUE THREAD

**Issue by cqwuzonglin** [gedoor/legado#1761]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 期望实现 验证书源是否避开某点防盗版功能

### 期望实现方式（阅读应该如何实现该功能）
> 一本书的阅读过程中 出现大量段落为前几章内容 则提示该书源 未避过防盗版功能 可立即删除该书源 并标记该书源,可在书源列表按标记 查询 删除 

### 附加信息（其他的与功能相关的附加信息）
> 未避过防盗版功能的书 章节内容错乱 大量内容为前几章的重复内容, 无阅读意义

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 一般书未收费章节都没有防盗版 到后边才有,所有检测 一般是在换源后才能检测出来 ,一般有自动缓存几章 如果几章内容有大量雷同 标记书源 并提供方便的删除方式

**Comment by gedoor** [comment]
实现不了
