### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wxianqq** [gedoor/legado#1763]
### 机型（mi 12）
>

### 安卓版本（Android 12）
>

### 阅读Legdao版本（我的-关于-版本,3.22.040716）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
打开电子书，金庸全集卡死，翻页翻不过去。
金庸作品全集（新修版）（全36册）+(金庸作品集)

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

打开电子书，阅读，翻页，到第4页卡死，不能往前翻后翻。

### 日志提交（问题截图或者日志）
>

![Uploading Screenshot_2022-04-09-00-54-45-969_io.legado.app.release.jpg…]()

**Comment by wxianqq** [comment]
![mmexport1649438292174](https://user-images.githubusercontent.com/59072402/162490968-1e1d2132-9c52-4556-9185-ed35a5db1cfb.jpg)

**Comment by wxianqq** [comment]
> ![mmexport1649438292174](https://user-images.githubusercontent.com/59072402/162490968-1e1d2132-9c52-4556-9185-ed35a5db1cfb.jpg)

电子书为epub.

**Comment by wxianqq** [comment]
> > ![mmexport1649438292174](https://user-images.githubusercontent.com/59072402/162490968-1e1d2132-9c52-4556-9185-ed35a5db1cfb.jpg)
> 
> 电子书为epub.

https://www.kexn.cn/1868.html  新修版

**Comment by wxianqq** [comment]
更新了两个版本，但还是不行。

**Comment by gedoor** [comment]
我看下,这两个版本没改这个
