### ISSUE TITLE
更自由的web端使用[Feature Request] 

### ISSUE THREAD

**Issue by siriiiiii** [gedoor/legado#1764]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
web端使用时无需局域网连接手机，也无需在手机阅读中打开web服务，可以直接读取云存档同步阅读记录
### 期望实现方式（阅读应该如何实现该功能）
> 
1.阅读提供在线网站以提供可视化界面，在网站内登录webdav，并将登录信息存储在本地，每次自动登陆自动同步。阅读只是提供一个空的web框架缓存到本地，看书读写文件应该不经过阅读的服务器，压力不会大，而且应该不会有什么法律问题？

2.依旧使用本地化网站，不过是需要另存为到本地再进行配置之后使用。另存为到本地后，对网站进行webdav配置，网页只是提供一个载体，书籍/书源依旧靠自己同步信息解决。
### 附加信息（其他的与功能相关的附加信息）
> 
这样搞的好处在于：手机上不需要打开阅读，不需要开启web服务，电脑上看书更方便，也能离线书籍之类的，加载更快
### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Xwite** [comment]
按你的意思是开发一个`阅读web版`？那等于重做一个了 ，目前web端没有解析书源的能力。
有个[服务器版](https://github.com/hectorqin/reader)的
