### ISSUE TITLE
[BUG] OOM Exception

### ISSUE THREAD

**Issue by zwillim** [gedoor/legado#1767]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>VMOS 虚拟机 - Android 7.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>legado_app_3.22.040716

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>whatever

### 问题描述（简要描述发生的问题）
>加载较大漫画时出现OOM

![微信图片_20220411091633](https://user-images.githubusercontent.com/5171795/162649618-794bd675-85dc-4299-a1f2-f6519a2452d1.jpg)

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

![Uploading 微信图片_20220411091633.jpg…]()

**Comment by gedoor** [comment]
最新版本如果再次出现oom重新提交吧,已经针对这方便做了优化
