### ISSUE TITLE
需求：本地书籍可以使用相对路径，通过设置书库路径实现多设备同步本地书架

### ISSUE THREAD

**Issue by casselluu** [gedoor/legado#1768]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 不同设备本地书库路径不同，同步设置时如果恢复书架，本地书籍无法打开

### 期望实现方式（阅读应该如何实现该功能）
> 添加本地书库相对路径设置，每个设备使用不同的路径，但都是：书库路径/book方式记录本地书架信息

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
我看看
