### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shzhyu1147** [gedoor/legado#1769]
### 机型（如Redmi K30 Pro）
>
huawei mate 40pro

### 安卓版本（如Android 7.1.1）
>
harmongos 2.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.040716
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>任何小说在使用滚动翻页动画进行看书的时候会持续性的丢帧，其他手机我没试，我们40pro和20pro都是这样

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
字号18
字句-0.03
行距0.4
段句1.0
翻页动画：滚动
正常翻阅小说，会掉帧卡顿

### 日志提交（问题截图或者日志）
>
![Uploading Screenshot_20220411_190910_io.legado.app.release.jpg…]()

**Comment by 1049234725** [comment]
#1750相同的问题，字号越小越严重

**Comment by shzhyu1147** [comment]
可以看看夸克浏览器自带小说浏览，看看能不能从中得到灵感，当然我也不太懂这个，可以去看下
