### ISSUE TITLE
生成app

### ISSUE THREAD

**Issue by Wirili** [gedoor/legado#177]
能差不多一段时间生成一个app吗，克隆生成的不能覆盖安装

**Comment by ZhangJiaLei123** [comment]
可以更换包名啊

**Comment by lmex621** [comment]
怎么更换包名？

**Comment by lmex621** [comment]
> 可以更换包名啊

怎么更换包名？有没有详细步骤哇。自己尝试编译失败！

**Comment by Antecer** [comment]
已经配置Actions，你可以经常访问这个标签以获取最新的app，它是自动编译的。
