### ISSUE TITLE
搜索功能请求优化

### ISSUE THREAD

**Issue by missionfree** [gedoor/legado#1779]
> 在搜索书名的时候，希望搜索的书能合一，不要那么多同名的书名，能不能将他们合一，出现一个就行了
#新手第一次使用github，如果有怎么不对的地方，请勿喷我

**Comment by Xwite** [comment]
书名作者都一样的会合并，右上角的数字是相同的个数。

**Comment by missionfree** [comment]
使用过程中还有个小问题，就是书架上的书，切换书源的话，书架上又多了一个同名的书

**Comment by Xwite** [comment]
是不是作者不一样



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月13日(星期三) 下午3:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] 搜索功能请求优化 (Issue #1779)




 
使用过程中还有个小问题，就是书架上的书，切换书源的话，书架上又多了一个同名的书

**Comment by gedoor** [comment]
同名同作者不可能存在两本,两本就是作者不一样

**Comment by gzsdbb** [comment]
我感觉这里没有问题 毕竟有的书可能同名但并不是同一本书 就算是同一本书 软件的逻辑也很难自动判断是不是同一本书 所以软件以作者等等的方式分类，多出几个选项也没什么
