### ISSUE TITLE
[BUG] 期刊epub文件无法加载目录 读不了期刊类的杂志

### ISSUE THREAD

**Issue by 17600410044** [gedoor/legado#1791]
### 机型（如Redmi Noto10 Pro）
>

### 安卓版本（如Android 12）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
最新版本
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
[正常网络](`url`)

### 问题描述（简要描述发生的问题）
>
epub文件已发你们联系邮箱 请知悉！仅测试使用 ！

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 17600410044** [comment]
[](url
![bug1](https://user-images.githubusercontent.com/39699341/163656251-326d178e-580f-44db-b4c8-dd58fb5b8461.jpeg)
![bug2](https://user-images.githubusercontent.com/39699341/163656261-9a59a8ec-b9ef-478e-a3bd-6a541514c7c6.jpeg)
)

**Comment by 17600410044** [comment]
![bug4](https://user-images.githubusercontent.com/39699341/163681558-453c77dd-5bcd-4976-ab78-9c54d04925fd.jpeg)我看了一下epub 的压缩文件看到一项 .opf文件的xmls 节点 不知道是不是这个问题？

**Comment by 17600410044** [comment]
已经确定是这个问题 .

**Comment by gedoor** [comment]
已经修改了
