### ISSUE TITLE
关于换源里的建议 

### ISSUE THREAD

**Issue by gzsdbb** [gedoor/legado#1793]
现在最新的3.22.041418版本 在换源的时候有机率出现"书籍类型不一样"(当其他源原作者没有注明的时候，其实是同一本书，只是有的源没有写上作者),
然后这个时候换源,收藏列表中会生成一个新的书籍,和原书籍同名并重复(不同源),

本来这个设计是为了方便同名而不同作者的书准备的吧!

本来是个不错的功能,但如果是同一本书呢 那就是重复了吧?

### 期望实现方式（阅读应该如何实现该功能）
> 当手动换源的时候 遇到书籍类型不一样的时候 希望多一个选择项 可以选择保留或覆盖原书籍,而不是默认的就去保留旧的

**Comment by Xwite** [comment]
#1779

**Comment by gzsdbb** [comment]
> #1779

这个和我这个情况不一样，你那是搜索，可能出现同名不同作者的情况 软件了不好判断。但我现在这个是因为源没有作者或标注有差别，软件同样能判断是不是同一本书 ，所以我只希望能够人工手动识别并选择是否保留或覆盖

默认保留后去删掉旧的也不是不行就是设置了书架自动排序后 换源后有时候旧的不知道会飞到哪里（收藏书太多的时候）又要慢慢去找！
