### ISSUE TITLE
[Feature Request] 增加TTS阅读进度保存频率

### ISSUE THREAD

**Issue by gzyguo** [gedoor/legado#1800]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 我不知道现在进度保存的机制但是经常会恢复到15分钟前播放的进度哎主要体现在中午比如去买菜然后听了一会儿然后下午再听的话感觉是在重复听中午的内容而且这种情况感觉好像一直在发生哎当然和我使用也有关系可能会手机重启APP被杀进程总之感觉最近这些日子情况很严重挺困扰的，谢谢

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 哎一般我是不太会打开APP去播放语音阅读通常我可能是手机开机以后就直接按播放键耳机的然后如果上次用的APP是这个APP的话它就会继续播放当然也会使用桌面图标长按弹出的那个语音阅读快捷键总之通常是不太会进入APP去播放感觉这个和进度丢失也许会有关系而且我发现在播放过程中进入APP可能会出现混乱的状况比如有耳机播放键开始的语音阅读听了一会儿进入APP打开的进度就不是当下正在阅读的片段应该是之前的某个进度

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
现在是暂停是按段,停止重新朗读是重新朗读这一页
