### ISSUE TITLE
[BUG] 快取/汇出没办法汇出图片

### ISSUE THREAD

**Issue by a8214983** [gedoor/legado#1801]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>6.0.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>最新版

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>WI-FI

### 问题描述（简要描述发生的问题）
>没办法汇出图片只汇出文件（txt）

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by ag2s20150909** [comment]
导出图片使用epub格式
