### ISSUE TITLE
希望辅助按键配置可以导出导入

### ISSUE THREAD

**Issue by dalaola** [gedoor/legado#1802]
一是方便写源，维护源。
阅读>书源>编辑>?>辅助按键配置

**Comment by gedoor** [comment]
ok

**Comment by dalaola** [comment]
你好。本邮箱因为站长长期不登陆，所以。侵权视频请电脑版访问网站右侧悬浮 在线客服 提交链接和标题侵权视频请手机版访问网站右侧悬浮 客服 提交链接和标题给你照成的不便敬请谅解啦。

**Comment by dalaola** [comment]
你好。本邮箱因为站长长期不登陆，所以。侵权视频请电脑版访问网站右侧悬浮 在线客服 提交链接和标题侵权视频请手机版访问网站右侧悬浮 客服 提交链接和标题给你照成的不便敬请谅解啦。

**Comment by dalaola** [comment]
你好。本邮箱因为站长长期不登陆，所以。侵权视频请电脑版访问网站右侧悬浮 在线客服 提交链接和标题侵权视频请手机版访问网站右侧悬浮 客服 提交链接和标题给你照成的不便敬请谅解啦。

**Comment by dalaola** [comment]
你好。本邮箱因为站长长期不登陆，所以。侵权视频请电脑版访问网站右侧悬浮 在线客服 提交链接和标题侵权视频请手机版访问网站右侧悬浮 客服 提交链接和标题给你照成的不便敬请谅解啦。

**Comment by dalaola** [comment]
你好。本邮箱因为站长长期不登陆，所以。侵权视频请电脑版访问网站右侧悬浮 在线客服 提交链接和标题侵权视频请手机版访问网站右侧悬浮 客服 提交链接和标题给你照成的不便敬请谅解啦。
