### ISSUE TITLE
[Feature Request] 阅读亮度调节功能

### ISSUE THREAD

**Issue by Mack00** [gedoor/legado#1805]
### 阅读亮度调节功能目前不支持调节到比系统最低亮度更低的亮度, 在晚上看书时系统最低亮度在黑色背景时文字还是会显得过亮. 希望阅读亮度调节功能支持调节到比系统最低亮度更低的亮度和通过屏幕左右边缘上下滑动来调节亮度(目前只能通过手动呼出菜单才能进行亮度调节).
> 

### 阅读亮度调节功能希望能和“搜书大师”app中的亮度调节功能一样, 能支持调节到比系统最低亮度更低的亮度和通过屏幕左右边缘上下滑动来调节亮度
>

**Comment by gedoor** [comment]
这个你可以通过调整文字颜色来实现

**Comment by Mack00** [comment]
> 这个你可以通过调整文字颜色来实现

是可以通过手动调节字体颜色实现, 但是目前的亮度调节功能没有“搜书大师”app那样通过屏幕边缘上下滑动这样便捷, 而且“搜书大师”app的亮度能够调节比系统亮度更低也是通过调节字体颜色实现. 所以希望阅读app也能集成这一个功能.

**Comment by lbpcvv** [comment]
最后老板如何解决的呢?  感觉晚上关灯亮度太高了, 能否实际搜书大师类的再低亮度调节呢? 谢谢
