### ISSUE TITLE
[Feature Request] 希望支持material you

### ISSUE THREAD

**Issue by youngxhui** [gedoor/legado#1807]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 

material you 已经成为新的设计语言，希望可以支持

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的
