### ISSUE TITLE
字体加粗存在问题

### ISSUE THREAD

**Issue by Carecluse** [gedoor/legado#181]
加粗后无法再换回未加粗状态，只能重启app才可以

**Comment by hingbong** [comment]
我的 Sony XZ2 Android 10 上没有这个问题

**Comment by Carecluse** [comment]
> 我的 Sony XZ2 Android 10 上没有这个问题

我是小米8 MIUI11 Android10，不知道其他机型还有没有这个问题

**Comment by git-ai** [comment]
我的华为机型emui10系统，也存在此问题
