### ISSUE TITLE
[BUG] 3.22.041820版本WebDAV挂了

### ISSUE THREAD

**Issue by nnkn** [gedoor/legado#1812]
### 机型（如Redmi K30 Pro）
>OPPO reno6 Pro +

### 安卓版本（如Android 7.1.1）
>Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.041820

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 电信数据，电信宽带

### 问题描述（简要描述发生的问题）
>WebDAV无效，提示未配置，
清空重新安装不行
换手机安装不行
安装上一版本功能正常

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

![Screenshot_2022-04-21-17-40-28-13_90024215e504237c76412be1999ad914](https://user-images.githubusercontent.com/22342244/164565131-50f4432c-6f05-40ed-8d65-3467153500ae.jpg)
![IMG_20220421_171125](https://user-images.githubusercontent.com/22342244/164565132-9bc41d12-82b8-4415-8f7a-f2d6eecf7307.jpg)

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by gedoor** [comment]
应该是个别webDav服务器返回的结果不一样的问题,我改下

**Comment by gedoor** [comment]
试试最新的测试版本

**Comment by nnkn** [comment]
> 试试最新的测试版本

最新版本可以了
