### ISSUE TITLE
多任务切换回阅读后 字体变细后逐渐变正常

### ISSUE THREAD

**Issue by bjqebjqe** [gedoor/legado#1813]
### 机型（如Redmi K30 Pro）
>k30s

### 安卓版本（如Android 7.1.1）
>安卓12 miui13.0.4

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.041820

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>多任务界面返回阅读时 字体会变细 然后慢慢变正常

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>使用完别的APP后，从多任务界面切换到阅读时（或者从APP直接切换到阅读），字体会变细，甚至在多任务界面就显示变细了。然后进入阅读后，字体会慢慢从细变回到正常状态。
但是假如把在多任务界面把变细的界面截图 还有正常的截图 一起在相册对比时两者没有区别 这是说明是显示的问题？
### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by bjqebjqe** [comment]
![IMG_20220422_095324](https://user-images.githubusercontent.com/79426403/164582786-33ce65f0-d73a-4b96-8a1c-63c39d7988d1.jpg)
类似于这样的 慢慢变粗 有一个渐变过程 
两个的截图放在一起对比时没问题 
（这是故意对比出的图）

**Comment by bjqebjqe** [comment]
我使用一月份的版本 只是偶尔出现 最新的版本就经常出现了

**Comment by gedoor** [comment]
我试试能不能复现吧
