### ISSUE TITLE
[Feature Request]  取消墨水屏动画

### ISSUE THREAD

**Issue by tabris233** [gedoor/legado#1815]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 墨水屏 取消动画

### 期望实现方式（阅读应该如何实现该功能）
> 在设置中增加一个选项，可以关闭动画

### 附加信息（其他的与功能相关的附加信息）
> 墨水屏场景下 类似点开设置然后翻页时画面会闪好多次。 希望可以优化下。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 无。

**Comment by Kalinundefined** [comment]
fixed #2199 #2207
