### ISSUE TITLE
[Feature Request] 开启web端后能在kindle阅读

### ISSUE THREAD

**Issue by qyzhaojinxi** [gedoor/legado#1823]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
可以正常在kindle浏览器阅读
### 期望实现方式（阅读应该如何实现该功能）
> 
参考微信读书那样，对网页版针对kindle进行优化

**Comment by ennnnny** [comment]
可以试试这个：https://ennnnny.github.io/legado_kindle_bookshelf/
填上阅读的web服务的地址就行了
