### ISSUE TITLE
[Feature Request] 订阅源规则订阅优化

### ISSUE THREAD

**Issue by caijimoyu** [gedoor/legado#1824]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
1.可以（定时）自动更新书源订阅
2.更新订阅时删除原此订阅的书源后重新导入
3.书源更新时自动添加分组名至源分组名
4.自定义源分组名固定，设置过一次后下次更新时无需再次设置
### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 
换源时可多选分组且分为必含分组和可含分组
### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的
