### ISSUE TITLE
io.legado.app.databinding 包不存在

### ISSUE THREAD

**Issue by zja0918** [gedoor/legado#1825]
### 问题描述（简要描述发生的问题）
>
io.legado.app.ui.main.bookshelf.style1.books.BooksAdapterGrid 类中 import io.legado.app.databinding.ItemBookshelfGridBinding 但是源码中，没有 io.legado.app.databinding 包。

![image](https://user-images.githubusercontent.com/13825729/165711635-478c8bda-8a79-4e56-817d-a1f54530acaa.png)

**Comment by 821938089** [comment]
你把整个legado文件夹删掉，然后重新clone，再打开项目等他构建完就好了。
