### ISSUE TITLE
[Feature Request] 备份时机调整

### ISSUE THREAD

**Issue by dabinn** [gedoor/legado#1828]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 当另一台机器上的阅读很久没使用的时候
打开APP会先使用"复原"功能让他的书库跟其它机器一致
但阅读APP似乎是在一打开的时候就立刻作了"备份"
于是就把其它机器传到webdav的资料给盖掉了
造成每次都得再开其它机器重新备份一次
(不太清楚这问题是不是后来有改，我刚才测试的是3.21版)

### 期望实现方式（阅读应该如何实现该功能）
> 我想到能改善的两种做法：
1. 比较简单是：APP刚打开的时候要经过一段时间(比如半小时)才会进行备份，避免盖掉
2. 比较完整的方法：APP读取本机的设定档修改时间，如果今日或昨天都没打开过，就没有把自己备份到webdav的必要

**Comment by gedoor** [comment]
ok
