### ISSUE TITLE
[BUG] 丢失换行和听书不启动 自动停止

### ISSUE THREAD

**Issue by liutianfang** [gedoor/legado#1830]
### 机型（如Redmi K30 Pro）
>Redmi K20 Pro

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.041020

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>八一中文内容页的换行丢失，导致超长段落（不影响阅读）
超长段落导致听书无法启动，读完标题就停止，手工翻页后可启动听书，如果后续内容超长则（未到章节结束）停止

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by liutianfang** [comment]
书源使用：https://yuedu.xiu2.xyz/shuyuan 其中的八一中文

**Comment by 821938089** [comment]
该书源的正文规则有问题，应为`id.content.0@html`，请向书源作者反馈问题。

**Comment by liutianfang** [comment]
虽然书源有错误导致无分段，但是基于段落的听书，最好还是改进一下，超大段落的确会导致听书异常
