### ISSUE TITLE
[BUG] 网络较差时，缓存的书打不开

### ISSUE THREAD

**Issue by cangming99** [gedoor/legado#1834]
### 机型（如Redmi K30 Pro）
>小米9

### 安卓版本（如Android 7.1.1）
>Android11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.050123

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>已经缓存的书籍，在网络较差的环境下打开，会显示一直在加载，一段时间后弹出FC，从几个版本前开始这样

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by shiqianwei0508** [comment]
遇到了同样的问题

**Comment by LTHPKBTE** [comment]
同样问题。如果网络过差甚至会未响应，关闭网络后正常。
