### ISSUE TITLE
[Feature Request] 希望支持书单自动备份

### ISSUE THREAD

**Issue by censujiang** [gedoor/legado#1837]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 我希望支持书单自动备份，因为我平时有多台设备用于阅读小说，书单倒来倒去很麻烦

### 期望实现方式（阅读应该如何实现该功能）
> 自动备份数据中新增书单备份

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 1059026669** [comment]
自动备份到本地么？可以自己操作啊

**Comment by censujiang** [comment]
> 自动备份到本地么？可以自己操作啊

备份到云

**Comment by 1059026669** [comment]
云的话代价就就大了，现在都是为爱发电

**Comment by censujiang** [comment]
> 云的话代价就就大了，现在都是为爱发电

代价哪大了？不是有备份到webdav的选项吗？

**Comment by 1059026669** [comment]
免费的容量很小，多了还是得付费

**Comment by censujiang** [comment]
> 免费的容量很小，多了还是得付费

可以自己搭的

**Comment by 1059026669** [comment]
> > 免费的容量很小，多了还是得付费
> 
> 可以自己搭的

自己搭就不需要电脑了么？

**Comment by censujiang** [comment]
> 

淘宝200块钱买个小主机或者腾讯轻量云

**Comment by 1059026669** [comment]
不还得花钱，还得维护

**Comment by 1059026669** [comment]
飞哥不出现啊

**Comment by censujiang** [comment]
> 不还得花钱，还得维护

你可以自己试着搭一个，你就知道维护这东西有多简单了
