### ISSUE TITLE
[Feature Request] 希望增加web端自定义字体功能

### ISSUE THREAD

**Issue by GitCourser** [gedoor/legado#1839]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 开web服务在pc上看书时,字体只能选择默认的3种,希望能增加自定义字体,比如在3个字体后加个输入框,可以自己输入字体名

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by GitCourser** [comment]
> Chrome系浏览器装个Stylus插件，加上以下设置即可：
> 
> ```
> p {
>     font-family: "PingFang SC" !important;
> }
> ```

我提这个问题前用的就是Stylus, 但用扩展还是比本身内置的麻烦,换电脑或不同的内部网络都要装个扩展重写css和作用域, 还是希望web端能内置换字体这个功能

**Comment by qianfanguojin** [comment]
纯靠自己输入的字体就能修改，要么就是app内置足够多的字体，要么就只能靠自己导入字体，从目前功能实现的逻辑来讲，这个字体能够使用的前提是要先下载并导入到阅读 app 中才行

**Comment by GitCourser** [comment]
> 纯靠自己输入的字体就能修改，要么就是app内置足够多的字体，要么就只能靠自己导入字体，从目前功能实现的逻辑来讲，这个字体能够使用的前提是要先下载并导入到阅读 app 中才行

你这逻辑有问题吧, 说的web端, 网页显示, 只要电脑安装有字体就行, 和app有什么关系.....

**Comment by qianfanguojin** [comment]
> > 纯靠自己输入的字体就能修改，要么就是app内置足够多的字体，要么就只能靠自己导入字体，从目前功能实现的逻辑来讲，这个字体能够使用的前提是要先下载并导入到阅读 app 中才行
> 
> 你这逻辑有问题吧, 说的web端, 网页显示, 只要电脑安装有字体就行, 和app有什么关系.....

oo，理解你的意思了，输入自己安装的字体名是吧，这个倒是可以

**Comment by qianfanguojin** [comment]
> > 纯靠自己输入的字体就能修改，要么就是app内置足够多的字体，要么就只能靠自己导入字体，从目前功能实现的逻辑来讲，这个字体能够使用的前提是要先下载并导入到阅读 app 中才行
> 
> 你这逻辑有问题吧, 说的web端, 网页显示, 只要电脑安装有字体就行, 和app有什么关系.....

可以了，做了个基本的版本，已经基本可用了
![自定义字体](https://user-images.githubusercontent.com/41330843/177451760-f59bea52-f51d-4362-aebd-02805d1d1e09.gif)

**Comment by GitCourser** [comment]
> > > 纯靠自己输入的字体就能修改，要么就是app内置足够多的字体，要么就只能靠自己导入字体，从目前功能实现的逻辑来讲，这个字体能够使用的前提是要先下载并导入到阅读 app 中才行
> > 
> > 
> > 你这逻辑有问题吧, 说的web端, 网页显示, 只要电脑安装有字体就行, 和app有什么关系.....
> 
> 可以了，做了个基本的版本，已经基本可用了 ![自定义字体](https://user-images.githubusercontent.com/41330843/177451760-f59bea52-f51d-4362-aebd-02805d1d1e09.gif) [ ](https://user-images.githubusercontent.com/41330843/177451760-f59bea52-f51d-4362-aebd-02805d1d1e09.gif) ![自定义字体](https://user-images.githubusercontent.com/41330843/177451760-f59bea52-f51d-4362-aebd-02805d1d1e09.gif) [ ](https://user-images.githubusercontent.com/41330843/177451760-f59bea52-f51d-4362-aebd-02805d1d1e09.gif)

感谢感谢, 这就是我想要的功能, 大佬可以pull给作者, 等下回作者更新编译就能用了

**Comment by qianfanguojin** [comment]
嗯，已经合了，等作者发布了
