### ISSUE TITLE
[Feature Request] 希望增加"社区"功能

### ISSUE THREAD

**Issue by kadidala** [gedoor/legado#1844]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望增加"社区"功能，大家讨论新书和推书

### 期望实现方式（阅读应该如何实现该功能）
> 底部菜单增加一个社区功能入口

### 附加信息（其他的与功能相关的附加信息）
> 社区内可以分区，综合区，书荒求助区，小说推荐区等

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 1059026669** [comment]
增加社区就要投资服务器，需要钱，肯定是不可能的

**Comment by 1059026669** [comment]
类似论坛，很容易违规被查。
已经有QQ频道了，比论坛功能强大
