### ISSUE TITLE
[BUG] 2K分辨率下翻页动画掉帧

### ISSUE THREAD

**Issue by 68star89** [gedoor/legado#1851]
### 机型（如Redmi K30 Pro）
>Redmi K50

### 安卓版本（如Android 7.1.1）
>Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.050215

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>所有场景

### 问题描述（简要描述发生的问题）
>2K分辨率下翻页动画掉帧，纯色背景下翻页动画均正常，但自定义图/软件自带背景图下覆盖翻页等各种翻页动画均掉帧明显

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>开启全局2K+120hz，打开软件翻页

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 68star89** [comment]
比对了同一部手机60hz和120hz场景下的翻页动画，发现120hz的翻页动画体感帧数比60hz场景更差

**Comment by xl7535** [comment]
更换背景后翻页动画明显卡顿，安卓12

**Comment by 68star89** [comment]
> 更换背景后翻页动画明显卡顿，安卓12

目前暂时已知的解决办法是，把自定义背景图片的分辨率调整为跟手机屏幕分辨率一致，可以解决掉帧问题

**Comment by 68star89** [comment]
提一个可能有助于解决掉帧的处理办法，将导入的自定义背景图片另存在软件本地，并将存在本地的图片调节拉伸成合适的分辨率

**Comment by xl7535** [comment]
> > 更换背景后翻页动画明显卡顿，安卓12
> 
> 目前暂时已知的解决办法是，把自定义背景图片的分辨率调整为跟手机屏幕分辨率一致，可以解决掉帧问题

还有这种操作，我试试

**Comment by xl7535** [comment]
> 

有用了

**Comment by 68star89** [comment]
问题已经解决，感谢
