### ISSUE TITLE
[Feature Request]  是否可以考虑给Web端添加书签功能

### ISSUE THREAD

**Issue by qianfanguojin** [gedoor/legado#1856]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 目前Web端的使用体验还不错，就是常用的书签功能没有，不知作者是否可以加一个添加书签的选项
> 还有就是可以提供更多的API，目前我从源码中看好像只有一些必要功能有API，希望提供更多，如划线，查找等等
### 期望实现方式（阅读应该如何实现该功能）
>

**Comment by gedoor** [comment]
好的,慢慢来
