### ISSUE TITLE
导入的本地书目录依然识别不出

### ISSUE THREAD

**Issue by XKL520** [gedoor/legado#186]
本地目录还是识别不出，同样的书在阅读2中是能正常显示的
目录类似:
第一卷 笼中雀 第一章 惊蛰
第一卷 笼中雀 第二章 开门
希望能尽量修复下，这个还是比较影响阅读的

**Comment by 52fisher** [comment]
升级到最新版，书籍页面右上角倒数第三个图标，打开txt正则目录，右上角导入默认规则
