### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by iseeyo** [gedoor/legado#1868]
### 机型（如Redmi K30 Pro）
>All

### 安卓版本（如Android 7.1.1）
>All

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.050122

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>All

### 问题描述（简要描述发生的问题）
>改变主题颜色后，部分颜色未跟随改变！很早之前的版本是会全部跟随改变的，貌似是出来Cronet版本开始就出现这个问题了

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>绿色主题色
![主题色](https://user-images.githubusercontent.com/7778828/167559260-8b690e89-670a-42b6-b186-ec8232d72898.png)

对话框字体颜色未跟随改变
![未改变颜色](https://user-images.githubusercontent.com/7778828/167559303-fb66c71c-fe5e-401a-9452-e9cf857e6802.png)

Tab边框颜色未跟随改变
![未改变颜色](https://user-images.githubusercontent.com/7778828/167560371-119e1c50-d30c-4b7d-943c-c8133d0343f1.png)

**Comment by gedoor** [comment]
ok
