### ISSUE TITLE
[Feature Request] 问题，自己添加源，网站有loading，正文获取的不是完整内容，如何获取完整正文？

### ISSUE THREAD

**Issue by 4FYamedeaR** [gedoor/legado#1885]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
自己添加源，网站有loading，会在loading结束后重新加载正文，正文获取的不是完整内容，如何获取完整正文？
![1652592890](https://user-images.githubusercontent.com/105576840/168458718-befcd78f-3482-4967-b639-ba65aab28005.jpg)
### 期望实现方式（阅读应该如何实现该功能）
> 
正文加载增加延迟或可以进行二次加载正文
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
调用webView,在webView里面用js判断

**Comment by 4FYamedeaR** [comment]
![1654067935(1)](https://user-images.githubusercontent.com/105576840/171350166-d9e3f01f-334f-47a2-b03b-4380a1a99c12.jpg)

**Comment by 4FYamedeaR** [comment]
目前有很多网站带有此类loading功能，能发把等待几秒重新获取文本的功能内置到APP中？

**Comment by gedoor** [comment]
webView的js需要返回正文内容,你可以在js里判断有没有加载完成,比如正文包含未加载完成js就返回空,会在1秒之后重新执行js,直到返回内容不为空,js会每秒循环执行一次直到返回的内容不为空,最长30秒

**Comment by lb12138h** [comment]
> webView的js需要返回正文内容,你可以在js里判断有没有加载完成,比如正文包含未加载完成js就返回空,会在1秒之后重新执行js,直到返回内容不为空,js会每秒循环执行一次直到返回的内容不为空,最长30秒

有简单的示例吗？
