### ISSUE TITLE
[Feature Request] 多端webdav同步

### ISSUE THREAD

**Issue by caijimoyu** [gedoor/legado#1888]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 支持多端webdav同步
1.多平台同步更安心
2.可以方便关联docker版实现进度同步

### 期望实现方式（阅读应该如何实现该功能）
> 增加webdav设置
可新增webdav
除主webdav强制实时同步，其他webdav可选择WiFi下同步
恢复时可自由选择从哪个webdav恢复哪些数据，例如从副webdav同步阅读进度

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
![image](https://user-images.githubusercontent.com/102563512/168507086-0d5283e8-04c9-449a-8ad9-cbe950fe8060.png)

**Comment by greenredstone** [comment]
相同需求，多个设备切换很困难，利用现有的webdav即可

**Comment by a8214983** [comment]
可以提供一下可以用的webdav吗…
