### ISSUE TITLE
请取消图片长按弹出〝查看和刷新〞菜单的功能，改为和以前一样的长按查看

### ISSUE THREAD

**Issue by So-Cho** [gedoor/legado#1889]
再不然就是提供一个长按图片固定放大查看的选项。

**Comment by gedoor** [comment]
这是为什么

**Comment by So-Cho** [comment]
> 这是为什么

原本看轻小说长按图片放大很方便，但改成这个长按弹出选项后就变得很烦琐了，而且这个地方的刷新按钮也几乎用不上。

**Comment by pungin** [comment]
建议加载失败后点击刷新，双指捏放来进行缩放，这样更直观
