### ISSUE TITLE
Trackers added?

### ISSUE THREAD

**Issue by IzzySoft** [gedoor/legado#1891]
Looks like your latest release added Firebase Analytics and GMS. If that was intentional (I see `启用firebase收集崩溃日志` in your release notes): would you consider providing a FOSS build coming without that? Or, would you consider removing that entirely?

If you need something for crash reporting or analytics, maybe my [collection of snippets](https://gitlab.com/-/snippets/1896503#acceptable-analytics) can help you choosing something that's FOSS and privacy-friendly. I'd also suggest making it opt-in (i.e. letting your users choose whether they want to send data).

Thanks in advance for taking care! And apologies for keeping my report in English, but I don't speak Chinese (if it's any consolidation, English isn't my mother tongue either…).

**Comment by IzzySoft** [comment]
@gedoor I hope I'm not too offensive if I ask for a statement on the issue? Will there be a chance? Privacy-focused users might be scared away with this. I wouldn't like Google & Co peeking into my reading habits :wink:

**Comment by IzzySoft** [comment]
Happened again with 3.23.103114:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

5 offenders.
```

Maybe they were dragged in unintentionally as a dependency? Could you please remove them again?

**Comment by IzzySoft** [comment]
Oof. Just updated library signatures, there's one more now indicating the app now makes use of advertisement (using Google's new so-called "privacy" sandbox). So the listing in my repo now looks quite scary, and the borderline of "offending libs" is quite crossed (6 > 4). Could you please let me know how you plan to handle this – so I know whether it will be solved (e.g. by a libre build flavor if not by outright removal of those "offenders") or if I'd have to remove the app [from my repo](https://apt.izzysoft.de/packages/io.legado.app.release/) instead?

![image](https://github.com/gedoor/legado/assets/6781438/2a2c2618-c191-4f30-a20e-2b90f220a7a9)

**Comment by IzzySoft** [comment]
So no chance of this being addressed, @gedoor? Not even a comment on it?

**Comment by IzzySoft** [comment]
With not even a response, and 4 anti-features attached, I've strongly to consider removing your app [from my repo](https://apt.izzysoft.de/packages/io.legado.app.release/) then. I've just updated its description to remove the references of it being "free, open source and ad-free" – as it is no longer ad-free, and only partly open-source (with all those proprietary libraries included). I'll set me a reminder to remove your app altogether should there be no reply within a month – it's already almost 2 years since I brought up the issue here and still didn't even get a single response, which is deeply disappointing and not sounding well concerning support for folks having issues.

Last ping for you, @gedoor (including @821938089 as another active contributor in the hope there'll be any response at least for clarity).

**Comment by IzzySoft** [comment]
The bot seems the only one "responding" here. It's been 3 months, the trackers are still present, and I didn't even receive a response here – so it looks like a change cannot be expected.

Which means I'll remove Legado from my repo now – effective with the next sync in 24h.

I'll leave this issue open (that bot will close it automatically anyway). Should you have a solution one day (e.g. a separate build flavor without those "offenders"), be welcome to give me a ping to check if I can add it back again.

**Comment by IzzySoft** [comment]
This should make users very confident about how much their privacy is "valued": almost 2 years after my initial report, and after several updates from my side, all answers received are from a bot that wants to close the issue for inactivity. Not a single response from a project member, not even any explanation, not to speak about any actions taken. Very sad.

**Comment by 821938089** [comment]
Due to some force majeure factors, the author is no longer active on this project and most likely will not release a new version, you can roll back to the previous version.

**Comment by IzzySoft** [comment]
Thanks (and sad to read this) – but too late, it is already removed. I just commented once more as I received a notification due to the bot's action.
