### ISSUE TITLE
[BUG] web上看书阅读记录有问题

### ISSUE THREAD

**Issue by lzpong** [gedoor/legado#1892]
### 机型
>NAM-AL00

### 安卓版本
>HarmonyOS 2.0.1

### 阅读Legdao版本
>[legado_app_3.22.051612](https://github.com/gedoor/legado/releases/tag/3.22.051612)

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通宽带

### 问题描述（简要描述发生的问题）
>1. web上看书, 翻下一章, APP上同步显示阅读记录争取, 但是点击书, 进去的 不是, 还是之前在APP上看的那一章,不是 web阅读记录的这一章
>2. web上书架点击书, APP上 这本书会跑到最后面去了(默认排序:按阅读时间)
>3. web上不能换源?

**Comment by gedoor** [comment]
ok
