### ISSUE TITLE
[Feature Request] 请求内置des加密解密

### ISSUE THREAD

**Issue by Ecalose** [gedoor/legado#1897]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
希望能像aes一样，内部提供des的加密和解密
### 期望实现方式（阅读应该如何实现该功能）
> 
类似aes引用即可
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Xwite** [comment]
不是有个3des吗

**Comment by 821938089** [comment]
看看这个是不是你想要的解密函数
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/help/JsExtensions.kt
https://github.com/gedoor/legado/blob/f3e46a130ff8ba5af37fc782bfd8a7cbd8ec33f7/app/src/main/java/io/legado/app/help/JsExtensions.kt#L785-L828
https://github.com/gedoor/legado/blob/f3e46a130ff8ba5af37fc782bfd8a7cbd8ec33f7/app/src/main/java/io/legado/app/help/JsExtensions.kt#L855-L898

**Comment by Ecalose** [comment]
> 看看这个是不是你想要的解密函数 https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/help/JsExtensions.kt
> 
> https://github.com/gedoor/legado/blob/f3e46a130ff8ba5af37fc782bfd8a7cbd8ec33f7/app/src/main/java/io/legado/app/help/JsExtensions.kt#L785-L828
> 
> 
> https://github.com/gedoor/legado/blob/f3e46a130ff8ba5af37fc782bfd8a7cbd8ec33f7/app/src/main/java/io/legado/app/help/JsExtensions.kt#L855-L898

感谢
