### ISSUE TITLE
[BUG] web无限滚动时章节内容没有按照章节目录排布

### ISSUE THREAD

**Issue by Summer1Solstice** [gedoor/legado#1898]
### 机型（如Redmi K30 Pro）
>
小米 8 miui12.0.5

### 安卓版本（如Android 7.1.1）
>
安卓10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.051719

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>局域网

### 问题描述（简要描述发生的问题）
>无限滚动章节,上一章和下一章之间会遗漏最少一章. 或者说混乱,除了跳过一些章节也会出现顺序颠倒的问题

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
没有什么明显的规律,暂时不清楚和书源有没有关系,3.0和pro,均出现了这种问题,概率不大但也不小,大概10几章就会出现一次,或者直接跳过了某些章节,或者是在前的章节和后面的章节对调了.
提供一个.mhtml文件作为日志,和一张目录图片
问题出现在13章和14章位置对调,和23章消失但出现在了25章后面.
![web目录](https://user-images.githubusercontent.com/46267607/169638921-46acafcd-39c9-48ab-8fa3-f1510aaa3ea7.png)
[宅童话 _ 28.契约.mhtml.zip](https://github.com/gedoor/legado/files/8747083/_.28.mhtml.zip)
压缩包无密码

**Comment by Xwite** [comment]
试一下最新测试版
反馈bug有效信息不多

**Comment by GitCourser** [comment]
用的最新版 3.22.052113
web端无限滚动确实有问题,并不是一章章的顺序往后,而是会几章几章的跳过
希望给个开关,能关掉这功能

**Comment by Netrvin** [comment]
+1，存在跳章问题
版本 3.22.052113
