### ISSUE TITLE
[BUG] 3.22.0521版本2K分辨率翻页卡顿

### ISSUE THREAD

**Issue by 68star89** [gedoor/legado#1899]
### 机型（如Redmi K30 Pro）
>Redmi K50

### 安卓版本（如Android 7.1.1）
>Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.0521

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>0516版本尚可通过修改背景图片分辨率解决卡顿问题，但0521版本该方案已经失效，且新版虽对卡顿有一定优化，但是尚不能达到纯色背景下的流畅度，也不能达到旧版2K背景图片的流畅度，个人建议在公众号提供解决方案并对相关更新进行倒车

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 68star89** [comment]
坤哥看到了能不能回复一下orz

**Comment by gedoor** [comment]
我再看看吧

**Comment by ag2s20150909** [comment]
可能是这里的问题
https://github.com/gedoor/legado/commit/2446be96eddd5d6249087e6586065543d99d379f

**Comment by 68star89** [comment]
问题已经解决，感谢
