### ISSUE TITLE
[Feature Request] 换源界面里的搜索改成搜索章节名

### ISSUE THREAD

**Issue by thredreams** [gedoor/legado#1900]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
现有的功能是搜索源，但是源多了之后，尤其是不喜欢维护源的人，根本就记不住哪些好用的源，都是靠书源分类选择一批源。而搜索功能这种情形下不如换成搜索章节名，因为新政策之后其他网站的更新速度都会晚上两三天。不同的源延迟的时间不一样，体现在换源页面里就是最新章节不同，所以希望搜索功能转为搜索章节名，或者说以章节名为关键词过滤源。如果能实现按章节排序就更好了。

**Comment by gedoor** [comment]
这个需要网站支持,而且大部分网站是目录更新了内容没有更新
