### ISSUE TITLE
[BUG] Web端阅读进度记录错误

### ISSUE THREAD

**Issue by Netrvin** [gedoor/legado#1904]
### 阅读Legdao版本
> 3.22.052113

### 问题描述
> Web端阅读小说，阅读进度记录会比当前阅读到的章节至少快一章

### 复现步骤
> Web端打开一本书再直接退回书架，即可发现阅读进度是刚才打开的章节的下一章
阅读几十章后，可以观察到进度记录快了好几章

### 建议
> 如该问题不便修复，可否先增加一个选项，用于关闭Web端底部自动加载

**Comment by GitCourser** [comment]
附议,web端无限滚动问题多,希望增加个开关能关闭这功能

**Comment by Xwite** [comment]
~WEB
