### ISSUE TITLE
[BUG] webdav

### ISSUE THREAD

**Issue by fhwhite** [gedoor/legado#1906]
用的官方推荐的坚果云，一直能备份，到现在也是每天都自动备份，打开看里面的数据也是正常的

但恢复有问题，今天写源的时候，用的模拟器，想通过备份恢复同步到手机，发现手动备份没反应，自动备份模拟器端也没反应，上坚果云看，今天早上已经有过同步文件，手动恢复报503。用手机测试，发现手动也无法备份，手动恢复跟模拟器端一样报503错误。

**Comment by 68star89** [comment]
可能是备份频率过大被坚果云临时冻结了，等半天再试试，关闭【备份与恢复】中的同步阅读进度有助于减少备份频率

**Comment by fhwhite** [comment]
还有这么一说吗，好的我去试试，不知道您试过没，这个频率大概是每天多少次，或者每小时？

**Comment by 68star89** [comment]
> 

试错成本太高没试过，但5-10分钟一次肯定是没问题的，阅读中的同步阅读进度会在每次退出某本书的时候就云备份一次到bookprogress文件夹，多打开几本书就很容易限流

**Comment by dianso** [comment]
和这个没关系，普通用户IO读写是每半小时3000次

**Comment by letterk** [comment]
如果你是单台设备, 只做备份, 那么推荐用坚果云, 至少可以保证每日备份是稳的
如果你是多台设备, 强烈不推荐用坚果云同步
你可能不知道, 阅读每次翻页都会向webdav传输数据, 所以多台设备是一定会触发坚果云的限制的

目前我的同步方案是自建本地webdav服务器, 然后用坚果云自家的客户端进行文件夹同步, 这个再频繁也没限制
