### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SogaSuga** [gedoor/legado#1911]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* Firefox PC 100.0.2
>

### 机型（如Redmi K30 Pro）
>三星 Galaxy Tab Active 3

### 安卓版本（如Android 7.1.1）
> Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.052113

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动宽带

### 问题描述（简要描述发生的问题）
>开启Web服务，在电脑上用firefox看书时，无限滚动偶尔会跳章，比如从100章一下子跳到105章。但是章节内容实际上还是在的，用上一章、下一章按钮就没有问题，手机上看也没问题。暂时没有发现稳定复现的规律，不过一次也不会跳很多章，大概3、4章左右。

### 使用书源（填写URL或者JSON）

<details>
 <summary>点击展开</summary>
 <pre><code>
https://www.xbiquwx.la/67_67699/16490139.html
<pre></code>
</details>

**Comment by Xwite** [comment]
Duplicate of #1898 #1904
