### ISSUE TITLE
能否增加一个过滤文章长度的属性

### ISSUE THREAD

**Issue by mhbalthasar** [gedoor/legado#1917]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 由于现在很多网站反抓取和反盗版，章节只会展示一小部分，100-200字的样子。缓存下来之后还得刷新。多个源的时候也不好判断源是不是正常。

### 期望实现方式（阅读应该如何实现该功能）
> 设置一个阀值，在对正文正则去掉空格和换行之后的字数进行计算，低于阀值的在目录里给出报告或者直接无视（当这章不存在）

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
这个可以自己在正文规则用js判断
