### ISSUE TITLE
[BUG] 开启app后, 第一次与webdav服务器连接失败, 卡加载

### ISSUE THREAD

**Issue by letterk** [gedoor/legado#1918]
legado_app_3.22.052723

自建本地webdav服务器
开启app, 第一次打开书籍会连接webdav服务器, 无法成功时就会陷入死循环. 页面显示`加载数据中`. 手机卡死无法操作, 直到10分钟左右才恢复. 

复现方法, 
1. 本地webdav服务器   (理论上无法成功连接上服务器都会触发这个bug)
2. 关闭wifi
3. 启动app, 随便打开一本书籍

应该是5月那个更新的bug

**Comment by gedoor** [comment]
最新测试版本试试

**Comment by letterk** [comment]
> 最新测试版本试试

还是有问题, 进入书籍OK了. 退出书籍就卡死黑屏

**Comment by letterk** [comment]
到今天为止, 依然没有修复该bug

**Comment by letterk** [comment]
3.22.071618版本已修复此bug
