### ISSUE TITLE
[BUG] epub目录加载混乱

### ISSUE THREAD

**Issue by ftnoone** [gedoor/legado#1927]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>小米8

### 安卓版本（如Android 7.1.1）
>Android10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.052723

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>加载本地epub时，第二项目录加载时间长，卡顿，加载后第二项目录中正文包含全文，第二项以后的目录项正常

### 相关截图
>
![Uploading Screenshot_2022-05-31-03-30-23-030_io.legado.app.release.jpg…]()

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>加载本地epub文件翻至第二页
### 本地epub文件如下
>https://github.com/ftnoone/drawio/blob/main/刘慈欣作品集（含三体）.epub

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by Xwite** [comment]
epub不支持二级目录

**Comment by ftnoone** [comment]
不是加载二级目录，是空目录会把后面的所有正文加载出来，后面的目录正常显示，举例子epub文件是
目录1：空
目录2：正文2
目录3：正文3
在阅读app中加载epub会变成
目录1：（目录2，正文2，目录3，正文3）这些目录1后所有内容变为目录1的正文
目录2：正文2
目录3：正文3

**Comment by Xwite** [comment]
测试版过了你这个文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月31日(星期二) 中午1:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] [BUG] epub目录加载混乱 (Issue #1927)




 
不是加载二级目录，是空目录会把后面的所有正文加载出来，后面的目录正常显示，举例子epub文件是
 目录1：空
 目录2：正文2
 目录3：正文3
 在阅读app中加载epub会变成
 目录1：（目录2，正文2，目录3，正文3）这些目录1后所有内容变为目录1的正文
 目录2：正文2
 目录3：正文3

**Comment by ftnoone** [comment]
好的，辛苦大佬了
