### ISSUE TITLE
[BUG] epub文件目录重复加载

### ISSUE THREAD

**Issue by ftnoone** [gedoor/legado#1932]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>小米8

### 安卓版本（如Android 7.1.1）
>Android10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.053108

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>WiFi

### 问题描述（简要描述发生的问题）
>相同的目录项重复出现五六次

### 相关截图
>其它软件正常加载epub目录截图
![1653977606875](https://user-images.githubusercontent.com/55370625/171106661-de2015f8-1fda-4a17-8f98-2a547601c454.jpg)
![1653977606882](https://user-images.githubusercontent.com/55370625/171106667-1ba5c81e-2fe9-4f45-9707-612064fdd8c6.jpg)
阅读app加载的混乱目录项截图
![1653977606867](https://user-images.githubusercontent.com/55370625/171106740-22ee3e0b-3f09-4b6f-96e3-555d067122de.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>本地导入epub文件，查看目录
### 本地epub文件蓝奏云（80MB）
> https://wwu.lanzouq.com/isJTB05onkgj
密码:2fwo

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by ftnoone** [comment]
beta的3.22.060112版本问题没有解决呀，这个文件的目录依然重复，有些目录项进去无法加载

**Comment by ftnoone** [comment]
3.22.06011452_共存版本，相同

**Comment by Xwite** [comment]
你好，5卷合一，每一卷前面都有介绍系列书籍的信息，请确保其他软件目录解析结果

**Comment by Xwite** [comment]
[epub.js](https://lwebapp.com/zh/epub-reader)

**Comment by Xwite** [comment]
有之前解析的缓存，先清楚缓存再试
