### ISSUE TITLE
[BUG] epub文件无法加载

### ISSUE THREAD

**Issue by ftnoone** [gedoor/legado#1938]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>小米8，6GB运行内存

### 安卓版本（如Android 7.1.1）
>Android10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.060120

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>阅读app内部加载epub文件无反应，用手机文件管理器打开epub文件（300MB左右）选择阅读app打开报错信息截图如下

### 相关截图
>
![Screenshot_2022-06-01-23-48-28-600_com android fi](https://user-images.githubusercontent.com/55370625/171450538-807f8442-e016-4120-af6d-907bc6aef103.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>阅读app内部本地导入epub文件打开和文件管理器打开epub文件选择阅读app打开
### epub文件meow云地址
>https://pan.miaogongzi.net/s/Akasd 密码：eoz35l

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by Xwite** [comment]
启用android:largeHeap好像就能过了
