### ISSUE TITLE
[BUG] 2022/06/01版本,用谷歌语音后台听书,打开其它app闪退

### ISSUE THREAD

**Issue by qidizi** [gedoor/legado#1939]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>mi 9

### 安卓版本（如Android 7.1.1）
>
 android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>2022/06/01

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 电信

### 问题描述（简要描述发生的问题）
> 后台使用谷歌语音听书,谷歌语音已经下载离线语音
打开其它app时闪退,印象中打开d音,微信,还好几个app都会出现
频率不高,无法重现.
闪退后,从app本身的b溃日志查看,没有内容
闪退现象是播放声音突然没了,状态栏上app播放条消失
txt文件来自手机本地,非网络来源
允许使用网络,能通过app本身升级
小米省电策略为无限制
暂停状态保持一晚上,还处暂停状态,打开过d音,未闪,关闭d音,稍后直接点击状态栏播放听一会,打开结束状态的d音就闪了.
相同的现象都是播放中,打开结束状态的其它app闪了

### 相关截图
> 无

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>无法重现

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>
均为空

<pre></code>
</details>

**Comment by gedoor** [comment]
打其它app时阅读闪退吗,我这边也用的谷歌语音,没遇到这种情况
