### ISSUE TITLE
不考虑上架Google Play 了吗

### ISSUE THREAD

**Issue by l-we** [gedoor/legado#194]
不考虑上架Google Play 了吗

**Comment by Firefly-Xu** [comment]
咕噜咕噜商店有啊，不过是付费的pro版！

**Comment by l-we** [comment]
没搜到，能发个链接吗，是美版商店吗

**Comment by l-we** [comment]
https://play.google.com/store/apps/details?id=io.legado.play.release 找到了，已购买
