### ISSUE TITLE
[BUG] epub打开某些目录项一直处于加载中

### ISSUE THREAD

**Issue by ftnoone** [gedoor/legado#1948]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>小米8

### 安卓版本（如Android 7.1.1）
>Android10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.060120release版本

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>进入某些目录项中加载正文时一直处于加载中，有的目录项会卡死，有的目录项从目录点击加载数据，翻页进去会一直加载中

### 相关截图
>
![Screenshot_2022](https://user-images.githubusercontent.com/55370625/171986565-fb8a3097-3d0a-4afa-948e-ffd9fdc19bd2.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>本地导入epub文件，如图操作
###epub文件
>https://github.com/ftnoone/drawio/blob/main/%E7%AC%AC%E4%BA%8C%E6%AC%A1%E4%B8%96%E7%95%8C%E5%A4%A7%E6%88%98%E5%AE%8C%E6%95%B4%E5%8E%86%E5%8F%B2%E5%AE%9E%E5%BD%95.epub

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by snipersteve** [comment]
同样有此问题
