### ISSUE TITLE
[Feature Request] 问题：正文有多个翻页按钮如何翻页

### ISSUE THREAD

**Issue by wzwwlc** [gedoor/legado#1950]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
正文翻页时，不是下一页，而是1， 2， 3这种，class.chapterPages@a@href的话会重复第一页，有多个a，求助
### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
你可能想要的是这个 `.chapterPages a!0@href`
