### ISSUE TITLE
[BUG] 5MBepub文件OutOfMemoryError

### ISSUE THREAD

**Issue by ftnoone** [gedoor/legado#1951]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>小米8

### 安卓版本（如Android 7.1.1）
>Android10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>legado_app_3.22.06052208_共存

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>导入本地epub文件打开如下图所示目录项无法加载且卡顿，等待一段时间崩溃

### 主界面日志截图
>![Screenshot_2022-06-05-23-53-06-073_io legado app](https://user-images.githubusercontent.com/55370625/172059428-0f5bf788-019c-4f36-8e2a-9634632891b0.jpg)

### 目录项截图
>![InkedScreenshot_2022_LI](https://user-images.githubusercontent.com/55370625/172059470-d917f962-d931-4400-bdfa-2486fac132b4.jpg)

### 奔溃日志太多了，直接打包，地址
>https://github.com/ftnoone/drawio/blob/main/io.legado.app.zip

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>导入本地epub文件打开如图所示目录项等待

### epub文件地址
> https://github.com/ftnoone/drawio/blob/main/%E7%AC%AC%E4%BA%8C%E6%AC%A1%E4%B8%96%E7%95%8C%E5%A4%A7%E6%88%98%E5%AE%8C%E6%95%B4%E5%8E%86%E5%8F%B2%E5%AE%9E%E5%BD%95.epub

**Comment by ftnoone** [comment]
还有大文件epub加载不了，拜托了

**Comment by dianso** [comment]
早就提议换epub解析库了，这个java库效率太低了

**Comment by gedoor** [comment]
> 早就提议换epub解析库了，这个java库效率太低了

有什么好的epub解析库吗

**Comment by dianso** [comment]
> 

github.com/futurepress/epub.js

**Comment by gedoor** [comment]
> > 
> 
> github.com/futurepress/epub.js

这个是js的啊用不了,想使用需要全部重新,工作量大啊

**Comment by 1552980358** [comment]
> > > 
> > 
> > 
> > github.com/futurepress/epub.js
> 
> 这个是js的啊用不了,想使用需要全部重新,工作量大啊

可以试一下这个[https://github.com/psiegman/epublib](https://github.com/psiegman/epublib)

**Comment by gedoor** [comment]
> 

现在就是用的这个
