### ISSUE TITLE
[BUG] 经常触摸到两侧连续翻N页

### ISSUE THREAD

**Issue by dream10201** [gedoor/legado#1952]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>
Redmi K40

### 安卓版本（如Android 7.1.1）
>
Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.041421

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通

### 问题描述（简要描述发生的问题）
>
看下说的时候经常触摸到两侧导致翻了N页，再看时都不知道看到哪里了，是否可以给个设置限制，翻页延迟或者一个开关

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
小说界面触摸手机屏幕两侧

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by letterk** [comment]
进入书籍, 菜单-设置-点击区域设置, 把左右两侧的点击翻页改成无操作
