### ISSUE TITLE
[Feature Request] 希望能移植桌面端

### ISSUE THREAD

**Issue by JZ-talone** [gedoor/legado#1956]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望能移植桌面端

### 期望实现方式（阅读应该如何实现该功能）
> 和现有功能大致一致，界面能自适应起到隐藏效果方便摸鱼

### 附加信息（其他的与功能相关的附加信息）
> mac端和win端

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Seidko** [comment]
如果你是Windows端，有一个极为类似的软件[https://github.com/Clean-Reader/CleanReader.Desktop](干净阅读)，也是开源的，你可以试一下

**Comment by nobk** [comment]
已经有浏览器界面了，开启该功能后，桌面PC开浏览器访问手机的ip地址就能看手机里的书，因此没必要再用一倍的人时数再造一个轮子。
你想摸鱼用浏览器的老板热键或者老板插件来搞定。

**Comment by JZ-talone** [comment]
已解决
