### ISSUE TITLE
[BUG] 备份产生了多余的文件

### ISSUE THREAD

**Issue by Doddddd** [gedoor/legado#1958]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>
三星 S21

### 安卓版本（如Android 7.1.1）
>
Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.060522

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动

### 问题描述（简要描述发生的问题）
>
备份错误

### 相关截图
>
![Screenshot_20220607-235532_MT Manager.jpg](https://user-images.githubusercontent.com/88972478/172450606-e3ca05f7-35f0-4d02-a324-7ad875d16e0d.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 1552980358** [comment]
未遇到此问题，可以尝试降级到正式`Release`版本使用
