### ISSUE TITLE
希望能通过webdav多设备自动同步书架分组和阅读进度

### ISSUE THREAD

**Issue by Wirili** [gedoor/legado#196]
1、希望能通过webdav多设备自动同步书架、分组和阅读进度。
2、设置跳转最近阅读，不会根据webdav的同步跳转，而是跳转到本机最近阅读；如果阅读进度比最新章节(其他设备看到最新上传了进度，当前设备还没更新)快，还是只能跳到最新章节
3、希望设置隐藏状态栏后，在界面设置的时候不显示状态栏
4、设置点击总是翻下一页，用海信A5墨水屏的时候，经常会出现跳到前面几页。普通手机不知道是不是滑屏触发太短（点击的时候滑动了一点点），会出现跳到上一页

**Comment by Wirili** [comment]
设置自动跳转最近阅读 ，打开软件进来还是之前的阅读进度，返回书架显示的是最新的进度，点击进入还是旧的进度，点其他书进入，再返回书架进入就才会是最新的进度

**Comment by 52fisher** [comment]
最新版已优化，如有问题可重新开issues
