### ISSUE TITLE
[Feature Request] 净化能屏蔽元素标签吗

### ISSUE THREAD

**Issue by zanewayne78** [gedoor/legado#1961]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 有些网站用了同样的模板，如ddxs点com正文里面每章插入这样的代码

`<p><a href="http://m.fantuankanshu.com" id="wzsy">fantuankanshu.com</a></p>`

### 期望实现方式（阅读应该如何实现该功能）
> 现在我是这样写id.contents.0@tag.p@ownText，
但还是希望能实现像adblock去广告那样的扩展可以屏蔽元素标签，能写规则###wzsy这样就能去除广告。
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
```js

#contents@html
<js>
var html = org.jsoup.Jsoup.parse(result)
var removeElementSelectors = ["#wzsy", "p[style]"] // 修改此处要移除元素的选择器
for (selector of removeElementSelectors) {
  html.select(selector).remove()
}
html
</js>
body@html


```

这段JS可以复用，要删除别的元素改一下数组就可以了，如果不需要再进行处理，可以省略 `body@html`
