### ISSUE TITLE
[Feature Request] 在正文上长按朗读的改进

### ISSUE THREAD

**Issue by nobk** [gedoor/legado#1964]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 目前在正文任意位置上长按出菜单，其中的朗读功能，目前只读选择的几个字，只读几个字没什么意义。而下方的朗读按钮，则是从当前页的开头开始读。如果听了半页了停下了，点朗读还得从头听已经听过的半页，耽误时间。

### 期望实现方式（阅读应该如何实现该功能）
> 希望长按选定功能的朗读按下后，改为从选定位置一直往下读，而不是只读选中的几个字。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> ![Screenshot_2022-06-12-03-08-27-192_io legado app release](https://user-images.githubusercontent.com/4659870/173201778-9f6375f6-9bb6-4329-a037-6647690fbc38.jpg)

**Comment by qianfanguojin** [comment]
这个长按朗读功能本来就是按照选中内容来朗读的，你需要的应该是 “从当前位置开始” 朗读的功能，这个和目前的 按段朗读 逻辑有冲突，应该暂时不处理,,

**Comment by nobk** [comment]
阅读选中内容毫无意义，选一小段读完就停还不如看得快。
依然需要这个功能，请重新打开。

**Comment by 821938089** [comment]
> 如果听了半页了停下了，点朗读还得从头听已经听过的半页，耽误时间。

可以快进的，有上一句下一句功能

**Comment by nobk** [comment]
感谢@gedoor提交的改进代码，测试这个功能没什么问题，现在长按后点朗读能够从选中处一直往下读了，issue关闭。
9494f9143088238f7e8c5c727e3c2ba1af623512
55e568425640cb03a396dd18578e618c47306032
bf889d936080155e7cf33653e6299dfdb15c8261

**Comment by nobk** [comment]
@gedoor 最新提交又默认只能朗读选中的那几个文字了？我没找到切换回一直往下读的选项。
我用的10寸平板听书，从中间断开从页首读要重复多读很多字。能不能把一直往下读设置为默认。

**Comment by 821938089** [comment]
长按切换朗读模式
