### ISSUE TITLE
[BUG] webDav 书籍无法添加

### ISSUE THREAD

**Issue by Aptiva27** [gedoor/legado#1969]
最新版 3.22.061022 
Android 7/9，  华为/一加

webDav 备份恢复正常使用。但是webDav 书籍无法添加。
点击+webDav 书籍  按钮后完全无反应，感觉不到有任何连接获取数据的动作。
屏幕上提示： webDav books 文件夹为空。（使用的坚果云，已在dav/legado/books  下放入各种格式书籍文件）
试过不同手机皆如此。

**Comment by gedoor** [comment]
最新测试版本应该好了

**Comment by Aptiva27** [comment]
感谢更新， 0617可正常使用
