### ISSUE TITLE
书籍列表界面下拉刷新，更新的目录不完全

### ISSUE THREAD

**Issue by sekaiacg** [gedoor/legado#197]
在书籍列表界面下拉刷新，书籍目录更新不完全：
每次下拉列表刷新的书籍目录会更新到非最新章节(不完全，如果最新章节是低100章，下次刷新可能是第80章)，几率大。

以下操作更新的目录是完整的：
进入对应的书籍信息-右上角3个点-刷新，这时候更新的目录是最新章节。

**Comment by 52fisher** [comment]
新版应该解决了该问题，如有疑问可再次提问。
