### ISSUE TITLE
本地epub书籍阅读的一些问题和界面布局的小bug[BUG] 

### ISSUE THREAD

**Issue by VincentYN** [gedoor/legado#1972]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

vivo z6
### 安卓版本（如Android 7.1.1）
>
安卓10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.061022

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
wifi 电信

### 问题描述（简要描述发生的问题）
>
1. epub的图片只有封面可以加载出来，其他章节的统统没有。
![Screenshot_20220613_115334](https://user-images.githubusercontent.com/90740912/173345760-78c505ca-7fd3-4e07-b950-e87f6962b7f7.jpg)
![Screenshot_20220613_115338](https://user-images.githubusercontent.com/90740912/173345803-eabe687d-119c-400f-83ad-0ac4a2719a86.jpg)
我用番茄小说打开统统正常。然后我去阅读数据目录的book_cache目录查看，发现阅读在该小说缓存路径的images只有一张封面图片，怪不得其他的看不见，我尝试手动导入其他的文件进去，发现没有用！
3. epub的目录没有层级折叠统统都在一根目录。直白点就是没有目录树统统都在根目录！
这是阅读的
![Screenshot_20220613_115349](https://user-images.githubusercontent.com/90740912/173345858-3989d50b-1781-42f4-ae59-b3bf3b125a05.jpg)
这是番茄小说的
![Screenshot_20220613_120406](https://user-images.githubusercontent.com/90740912/173345869-3f8e0dc8-bed5-426d-83bc-0f4a77f8519a.jpg)
![Screenshot_20220613_121429](https://user-images.githubusercontent.com/90740912/173345682-a6050bfd-8ce9-4ae6-83bb-a4b6545f2eaf.jpg)
4.还有就是epub正文里面的蓝链点击不支持跳转，阅读里面就是个text。
这是阅读的
![Screenshot_20220613_121913](https://user-images.githubusercontent.com/90740912/173345745-aff1e828-a372-4d12-a5cb-a0fb80f8cbe2.jpg)
这是番茄的
![Screenshot_20220613_121435](https://user-images.githubusercontent.com/90740912/173345733-9ea02c6b-fb77-49a0-afab-1d255c6477ab.jpg)
5. 还有个阅读布局小bug，如果你点任意一个或者新建一个布局，然后恢复预设，列如我点恢复微信阅读，你在恢复后如果动了你刚刚恢复的布局的各种设置，下次再点恢复预设就会读取你刚刚恢复的布局的设置，如果你把布局改名字了，你的预设名字甚至也会跟着改变如图。
![Screenshot_20220613_120859](https://user-images.githubusercontent.com/90740912/173345652-379aade5-fdca-4843-ad14-0731710d925c.jpg)
### 相关截图
>
希望大佬早日解决这些问题，阅读更上一层楼。
图1
图2
图3
图4
图5
图6
图7
图8

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

关于本地书记和界面布局的一些bug
### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by qianfanguojin** [comment]
目前我这边测试了几本书的图片是能读取的，如果方便的话，请提供您出错的书籍下载链接，这样才好调试

**Comment by VincentYN** [comment]
https://github.com/VincentYN/SSSSSSSSSS/blob/main/%E3%80%8A%E9%AC%BC%E5%90%B9%E7%81%AF%E3%80%8B%E7%B2%BE%E6%A0%A1%E6%8F%92%E5%9B%BE%E5%85%A8%E9%9B%86%20(%E5%A4%A9%E4%B8%8B%E9%9C%B8%E5%94%B1)%20.epub
