### ISSUE TITLE
版本legado_app_3.22.061022朗读问题[BUG] 

### ISSUE THREAD

**Issue by fuqt08** [gedoor/legado#1974]
朗读时 跳到下一章节的时候就不能自动朗读。需要停止功能再重新占朗读才行
安卓版本
安卓8
重新安装后把自启动选择开启好像就没有上面问题

**Comment by sheldon-lei** [comment]
您好，您的来信已收到。Best Wishes

**Comment by fuqt08** [comment]
重新安装后把自启动选择开启好像就没有上面问题。应该是权限被关的原因
