### ISSUE TITLE
[Feature Request] 是否可以添加一个关于搜索结果的过滤或屏蔽功能

### ISSUE THREAD

**Issue by GameOverUI** [gedoor/legado#1976]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 假如我通过关键词搜书，排在前面的大概率是含有关键词的姓名；部分书籍的简介会和关键词多次重合导致多次出现在搜索结果中；是否能添加一种可以过滤或屏蔽掉书名关键词/指定作者的功能

### 期望实现方式（阅读应该如何实现该功能）
> ①最理想的功能：通过书名关键词/指定作者来过滤搜索内容
> ②最低实现的功能：在搜索结果中屏蔽指定搜索结果，在以后的搜索中不会出现已屏蔽的搜索内容

### 附加信息（其他的与功能相关的附加信息）
> 我并不了解添加以上功能的难度，所以我给出了上面最理想的功能和最低功能要求

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>![T1](https://user-images.githubusercontent.com/73893589/173860746-59d2b394-94d4-480f-b2aa-024a7826d579.PNG)

**Comment by qianfanguojin** [comment]
这个做应该是可以的，问题是你需要在哪个阶段筛选？搜索之前设置好想要屏蔽的关键字？还是搜索之后？

**Comment by GameOverUI** [comment]
> 这个做应该是可以的，问题是你需要在哪个阶段筛选？搜索之前设置好想要屏蔽的关键字？还是搜索之后？

我个人倾向于在搜索结果之后

**Comment by qianfanguojin** [comment]
> > 这个做应该是可以的，问题是你需要在哪个阶段筛选？搜索之前设置好想要屏蔽的关键字？还是搜索之后？
> 
> 我个人希望能够在搜索之前添加关键词过滤（最好可以选定类型，比如书名关键词、作者），搜索之后添加手动屏蔽某一个搜索结果

最好是能提供类似工具的实现图就好了

**Comment by GameOverUI** [comment]
> 

![01](https://user-images.githubusercontent.com/73893589/175869509-a5434d6a-33e1-4867-9b71-c76542906499.jpg)
![02](https://user-images.githubusercontent.com/73893589/175869518-0e236b67-5334-49ec-aa61-9a17f04f83e4.jpg)

**Comment by GameOverUI** [comment]
> > > 这个做应该是可以的，问题是你需要在哪个阶段筛选？搜索之前设置好想要屏蔽的关键字？还是搜索之后？
> > 
> > 
> > 我个人希望能够在搜索之前添加关键词过滤（最好可以选定类型，比如书名关键词、作者），搜索之后添加手动屏蔽某一个搜索结果
> 
> 最好是能提供类似工具的实现图就好了

简单使用画图工具手动画出实现图

**Comment by GameOverUI** [comment]
test
