### ISSUE TITLE
[BUG] 平板/横屏双页 功能的bug

### ISSUE THREAD

**Issue by Violettx** [gedoor/legado#1980]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>联想小新Pad Pro 2021（分辨率为2560*1600）

### 安卓版本（如Android 7.1.1）
>版本13.1.555，Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>版本3.22.061722

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>【平板/横屏双页】功能存在bug，表现如下：

>目前的效果：
>如果打开【平板/横屏双页】功能：
>    横屏时：双页
>    竖屏时：双页
>如果关闭【平板/横屏双页】功能：
>    横屏时：单页
>    竖屏时：单页
--------------------------------------------------
>我认为该功能应当达到的效果：
>如果打开【平板/横屏双页】功能：
>    横屏时：双页
>    竖屏时：单页
>如果关闭【平板/横屏双页】功能：
>    横屏时：单页
>    竖屏时：单页

>此外，这个问题应该从2021-11-24就开始存在了（根据酷安搜索帖子得知）

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
你的设备不是平板吗？只要是平板就都是双页的啊。
你想要的功能实际上叫 `横屏双页`。

**Comment by Violettx** [comment]
是的，我希望得到的是横屏双页，因为平板竖屏也双页的话单列实在是太细长了；
我需要把这个作为一个Feature Request重新提issue吗？
