### ISSUE TITLE
[Feature Request] 平板/横屏双页 功能的小改进

### ISSUE THREAD

**Issue by Violettx** [gedoor/legado#1981]
### 功能描述（请清晰的、详细的描述你想要的功能）
>将 `平板/横屏双页`功能从目前只能选择`是`/`否`拆分为`全局双页`/`横屏双页`/`全局单页`三个选单。

### 期望实现方式（阅读应该如何实现该功能）
>目前的方式： `平板/横屏双页`功能只能选择`是`/`否`
>希望修改为： `平板/横屏双页`功能可以选择`全局双页`/`横屏双页`/`全局单页`三个选单。

### 附加信息（其他的与功能相关的附加信息）
> 此功能的原因是目前平板使用 `平板/横屏双页`功能只能选择是否全局双页（[见此issue](https://github.com/gedoor/legado/issues/1980)），但我个人的平板如果竖屏双页的话过于细长，而横屏单页的话过于宽了。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by qianfanguojin** [comment]
你这个问题描述不清楚，按照我的理解的话，你是有经常变换屏幕方向阅读的需求？

**Comment by Violettx** [comment]
@qianfanguojin 是的。我主要在Android平板上使用开源阅读app，我想要达到的效果是竖屏单页、横屏双页，但是目前的设置只能把平板的横竖屏同时都调成单页/双页。
（我的使用习惯是手持平板时竖向，放在桌上时横向，所以经常变换方向）

**Comment by qianfanguojin** [comment]
> @qianfanguojin 是的。我主要在Android平板上使用开源阅读app，我想要达到的效果是竖屏单页、横屏双页，但是目前的设置只能把平板的横竖屏同时都调成单页/双页。 （我的使用习惯是手持平板时竖向，放在桌上时横向，所以经常变换方向）

Get 了，这个应该不难

**Comment by Violettx** [comment]
多谢，最新版本已经支持此功能！
