### ISSUE TITLE
提问：一直没有找到从指定段落开始阅读的方法

### ISSUE THREAD

**Issue by kinsan2007** [gedoor/legado#1982]
配合微软tts 听书非常好用，但是听书软件中常用功能 双击某段落开始阅读的功能并未找到。
同时连续点击 朗读下一段也会造成tts卡死，造成想指定段落十分麻烦。

**Comment by qianfanguojin** [comment]
没有很简单，就是没做

**Comment by nobk** [comment]
现在有了，昨天的版本，长按以选中某个段落，松开后点阅读，就会从指定位置一直读下去了。

**Comment by chenjisuan** [comment]
能不能支持朗读模式下，点击或者双击自动跳到新的位置？类似掌阅的操作模式，小白爽文废话太多了。
