### ISSUE TITLE
[BUG] 经常性点击下一页会跳转到上一页

### ISSUE THREAD

**Issue by 18698399901** [gedoor/legado#1983]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>
Redmi 10X 4G

### 安卓版本（如Android 7.1.1）
>11.0.6

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.00.061722

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>翻页无动画，经常性点击下一页，实际上跳转的是上一页。每个版本都有这个BUG

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 18698399901** [comment]
翻页效果 用的是无动画

**Comment by 18698399901** [comment]
翻页动画用的是无动画

**Comment by nEdAy** [comment]
会不会是 "点击区域设置" 的问题？
![image](https://user-images.githubusercontent.com/10076735/176867483-597d51a9-7ef9-44f9-9d3e-39f6268cab07.png)

**Comment by 18698399901** [comment]
感谢您百忙之中回复信息，一直很喜欢阅读的排版和便利性，不是设置问题，这个我也有设置过，除了左上角和左上中
两个位置上一页，其他都设置点击下一页也是一样会出现，后面把音量键翻页也关了，一样也会出现，翻页动画用习惯了无动画效果，其他的效果没试过
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月1日(星期五) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] [BUG] 经常性点击下一页会跳转到上一页 (Issue #1983)





 
会不会是 "点击区域设置" 的问题？

**Comment by jacksonyin** [comment]
我以前和大家在群里也聊个这个问题，应该是和滑动翻页冲突了，有时候点击会触发滑动翻页。所以建议增加一个选项来禁止滑动翻页，@kunfei,  不过貌似木有回应。
workaround: 打开翻页动画，误翻页的几率会降低

**Comment by 18698399901** [comment]
> 



> 我以前和大家在群里也聊个这个问题，应该是和滑动翻页冲突了，有时候点击会触发滑动翻页。所以建议增加一个选项来禁止滑动翻页，@Kunfei, 不过貌似木有回应。 workaround: 打开翻页动画，误翻页的几率会降低
用不惯翻页动画，一直用的无动画效果
 - -！
