### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wushuangliu070** [gedoor/legado#1984]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>mi11 ultra

### 安卓版本（如Android 7.1.1）
>Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>
阅读备份默认路径不是自己的data，切换路径需要打开框架，但是安卓12框架访问不了被隐藏的data文件夹

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by wushuangliu070** [comment]
![Screenshot_2022-06-19-16-26-53-301_com.google.android.documentsui.jpg](https://user-images.githubusercontent.com/79258616/174473099-1fe170a2-490f-4667-b4d2-e79b47b40e15.jpg)

**Comment by gedoor** [comment]
备份路径自己选的,没有默认备份路径,选的文件夹不能是系统文件夹,可以自己新建文件夹再选择
