### ISSUE TITLE
[Feature Request] 朗读时按句号分段

### ISSUE THREAD

**Issue by XiaoXiaoYanHe** [gedoor/legado#1988]
功能描述：
朗读时每次只读一句话。

原因：
电子书经常出现长达三四页的大段落，在线朗读有限制字数就被跳过了，分页朗读的断句又很难受。

**Comment by rogueme** [comment]
这个不是很好解决吗,用替换净化功能,把。替换为。[换行],即可实现按句号分段朗读了
