### ISSUE TITLE
希望可以用鼠标滑轮🖱️翻页，上班摸鱼神器[Feature Request] 

### ISSUE THREAD

**Issue by bxuits** [gedoor/legado#1989]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by nEdAy** [comment]
鼠标滚动 
 - 是否开启 Switch 默认 false
 - 防抖 毫秒值 默认 200ms
 - 滚动方向（自然/反转）默认 自然

**Comment by jacklaplace** [comment]
所以，现在支持鼠标滚轮了吗？
我用的版本 3.22.052723，翻页动画是滚动，鼠标滚轮没有反应，左键单击倒是可以翻页。

然后在笔记本安卓模拟器上，鼠标滚轮也是不能控制滚动，但是笔记本触摸板用两个手指是可以控制滚动的，包括开启自动像素滚动翻页的时候，触摸板也可以同时控制向上滚或向下滚，鼠标滚轮还是不可以。

能否把鼠标滚轮和触摸板双手指滑动互相映射一样，以实现一样的功能？

**Comment by jacklaplace** [comment]
已经确认，最新版本 legado_app_3.22.120121-1，设置里有鼠标滚轮翻页这一项了。
