### ISSUE TITLE
进入正文后会自动变为最大亮度

### ISSUE THREAD

**Issue by darkflame0** [gedoor/legado#199]
系统设置为自动调节亮度，在其它界面时亮度正常，进入正文之后会自动变为最大亮度，2.0没有这种情况

手机型号为一加5T，安卓版本为9

**Comment by darkflame0** [comment]
测试了一下，系统使用固定亮度时进入正文也会变为最大亮度

**Comment by gedoor** [comment]
你设置下自动亮度,最顶上有个按钮

**Comment by darkflame0** [comment]
原来是有自动亮度设置的……我还以为取消了，由于背景的关系浅色按钮有点难看到

感谢
