### ISSUE TITLE
[Feature Request] 希望增加字体粗细无极调整的功能

### ISSUE THREAD

**Issue by Bijiazhou** [gedoor/legado#1991]
首先非常感谢作者对于本app付出的心血，我目前用的是smart3 墨水屏设备，整体体验很好！！！

### 功能描述
文字对比度这个我是看电子书自带的阅读app上有这个功能，所以这么写的，经过试验发现确实就是字体加粗。
目前咱们app有三档，普通在我这里显示有点发灰，加重则过于粗了。
所以想把需求变更为，字体粗细的无极调整，如图所示

### 效果演示
![WechatIMG674](https://user-images.githubusercontent.com/30489991/175242151-b5f01409-47da-4956-9641-ef2d1b6065d7.jpeg)
![WechatIMG675](https://user-images.githubusercontent.com/30489991/175242202-b5ce22da-fde5-49f8-afd3-380025ed8788.jpeg)

-------------------------以上为更新---------------------------------------------------------

### 功能描述
>  由于墨水屏本质就是一个安卓平板，部分系统对于第三方软件没有特殊适配，目前显示效果一般，文字显示有点寡淡，所以希望增加自定义文字对比度的功能
### 期望实现方式（阅读应该如何实现该功能）
> 不知道能不能直接调用安卓的API实现这一功能

### 附加信息（其他的与功能相关的附加信息）
> 此外本在我的设备上未能全屏显示，请问这个有机会优化么

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 在界面菜单新增对比度选项，阅读时全屏显示
![4399a4ec8d696cfcd1de1549eca701e](https://user-images.githubusercontent.com/30489991/174997379-e586cc0b-2b36-4e26-bd0d-0be256446af8.jpg)
![12e4bb932e7389e859af70d01e24b1b](https://user-images.githubusercontent.com/30489991/174997356-d2be0562-9182-40e5-b484-45bdad06b640.jpg)

以上，在此感激贡献者们对本APP的付出。

**Comment by 821938089** [comment]
全屏显示：设置 -> 隐藏状态栏

文字对比度有什么用啊，直接改文字颜色不行吗？
直接设置成黑色，不够黑就加粗。

**Comment by sheldon-lei** [comment]
您好，您的来信已收到。Best Wishes
