### ISSUE TITLE
[Feature Request] 安卓端web服务是否可移植到linux？

### ISSUE THREAD

**Issue by MooreFoss** [gedoor/legado#1993]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 单独web阅读服务端

### 期望实现方式（阅读应该如何实现该功能）
> 在linux系统上运行，可提供web阅读服务

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
我猜你在找这个 https://github.com/hectorqin/reader

**Comment by MooreFoss** [comment]
> 我猜你在找这个 https://github.com/hectorqin/reader

是的！非常感谢
