### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by kebedd69** [gedoor/legado#1996]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 书源编辑时的红色❓里的辅助按键配置希望可以增加一个导入导出的功能，或者加入备份

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
辅助按键配置已经加入备份了啊
