### ISSUE TITLE
[BUG] 订阅源的 webView 无法设置 UA

### ISSUE THREAD

**Issue by 821938089** [gedoor/legado#1997]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
> 小米6X

### 安卓版本（如Android 7.1.1）
> Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.062320

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动

### 问题描述（简要描述发生的问题）
> 给订阅源设置了电脑端UA，但是 webView 打开依然提示手机版页面。

### 相关截图
> 
![image](https://user-images.githubusercontent.com/8674809/175550306-97ea5ef3-ba5a-4c64-94bc-7fe18e839ddb.png)

期望页面

![image](https://user-images.githubusercontent.com/8674809/175550736-2d803ad0-b8d0-4e17-bc98-545472c0a7e7.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 导入此订阅源，打开它。

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>
{
  "articleStyle": 0,
  "customOrder": 0,
  "enableJs": true,
  "enabled": true,
  "enabledCookieJar": false,
  "header": "{\"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36\"}",
  "loadWithBaseUrl": true,
  "singleUrl": true,
  "sourceIcon": "",
  "sourceName": "a",
  "sourceUrl": "https://ani.gamer.com.tw/animeVideo.php?sn=28325"
}

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by gedoor** [comment]
ok,我看下

**Comment by gedoor** [comment]
应该已经解决了

**Comment by gedoor** [comment]
最新测试版本试下

**Comment by 821938089** [comment]
可以用了，辛苦了
