### ISSUE TITLE
[Feature Request] 添加繁简转换

### ISSUE THREAD

**Issue by flt6** [gedoor/legado#2000]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
对于文章正文所有繁体字转换为简体字。

### 期望实现方式（阅读应该如何实现该功能）
> 
在菜单中添加相关选项。
[jpinyin](https://github.com/qzw1210/jpinyin) 提供了Java的相关实现和接口，也许有帮助。
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
有这个功能，在界面 -> 简/繁
