### ISSUE TITLE
[Ask] jpg file format support

### ISSUE THREAD

**Issue by rektpartyaftermath** [gedoor/legado#2003]
# jpg file format support
Is jpg file format not supported as an content?
i tried to make source for a manga reading site, and they only use jpg format, but when everything is done, the image isn't loaded.

**Comment by 821938089** [comment]
Can you post the source json here?

**Comment by rektpartyaftermath** [comment]
https://shuyuan.mgz6.cc/shuyuan/9e978ce1ec30a92e090f4745c520db7d.json

**Comment by 821938089** [comment]
The image server uses the cloudflare firewall to filter out illegal referers, you need to add a header rule to bypass it.

`{"Referer": "https://readmangabat.com/"}`

**Comment by rektpartyaftermath** [comment]
Thank you so much.
