### ISSUE TITLE
[Feature Request] 希望可以添加书单-分组的加密/隐藏功能

### ISSUE THREAD

**Issue by LGCaerwyn** [gedoor/legado#2004]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 分组后的书单，可以隐藏/加密
隐藏后的书籍，不会在其他组中显示，"全部"组中也不显示，只在对应的加密/隐藏组中显示
p.s.隐藏组-可以设置密码/或者其他方式

**Comment by nEdAy** [comment]
@LGCaerwyn 那你想 加密/隐藏组 通过什么方式 触发显示呢？
