### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NeysaBan** [gedoor/legado#2006]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
- [x]  Chrome PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
> 版本 103.0.5060.53（正式版本） (arm64)

### 机型
> macbook pro 14

### pc系统版本
> montery 12.4

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.062320

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 联通

### 问题描述（简要描述发生的问题）
> web端切换字体不生效

### 相关截图
> ![1.png](https://s2.loli.net/2022/06/29/GKt9eLvXQAYJNjk.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
mac 系统没有这些字体
