### ISSUE TITLE
[Feature Request] 希望可以API的方式去获取书籍

### ISSUE THREAD

**Issue by xcbt9527** [gedoor/legado#2007]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
因为有一些小说源站点，是用异步js的方式加载章节内容或者书籍的，但是目前app获取书籍的方式是静态的获取。
有部分站点其实是有api调用提供的
### 期望实现方式（阅读应该如何实现该功能）
> 期望书源爬虫可以基于api的方式获取

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
阅读支持api获取，书源怎么写你去找个用api的书源看看
