### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by AssassinHjx** [gedoor/legado#2019]
提个小建议：希望可以将直接打开APP进行阅读的进度和web访问的阅读进度同步。

**Comment by qianfanguojin** [comment]
这两个本来就是同步的啊。。。。

**Comment by AssassinHjx** [comment]
额...我又确认了一下确实可以同步，之前使用时在web端看了之后在手机上打开进度也确实没能同步。可能延迟了吧😂
________________________________

**Comment by smartsl** [comment]
貌似是近期某个版本开始的bug，web看了之后，手机上外面看进度是同步了，实际进去还是在原来的旧章节

**Comment by AssassinHjx** [comment]
对的对的，就是这样
