### ISSUE TITLE
[Feature Request] 自定义缓存过期时间

### ISSUE THREAD

**Issue by Quackgrass** [gedoor/legado#2023]
### 功能描述（请清晰的、详细的描述你想要的功能）

部分书源会获取最新章节，即使没有没有正文内容，只挂个章节名。等第二天使用时，后续的没一章都需要刷新以获取内容。

属性必须点击上方的刷新按钮，单手时候时很不方便。

### 期望实现方式（阅读应该如何实现该功能）

希望能够定义缓存的过期时间，比如一个小时。

或者将刷新按钮和换源按钮放在下面，交换搜索和替换净化至上方。能做成自定义的方式更好🤣

**Comment by 821938089** [comment]
长按一下那个刷新按钮会弹出个菜单可以刷新后面的章节
