### ISSUE TITLE
[BUG] 有些书源进入编辑页面不编辑立刻返回会提示“尚未保存，是否继续编辑”

### ISSUE THREAD

**Issue by 821938089** [gedoor/legado#2029]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
> 小米6X

### 安卓版本（如Android 7.1.1）
> Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.062909

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动

### 问题描述（简要描述发生的问题）
> 有些书源点进去编辑页面然后不做任何操作直接返回会提示“尚未保存，是否继续编辑”。
好多书源都是这样，点进去只是看一眼，返回就会有提示，挺烦人的。

### 相关截图
> 

https://user-images.githubusercontent.com/8674809/177494264-785976cd-9676-4f69-9db8-690505987d50.mp4

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 导入下面的书源地址，然后进入该书源的编辑页面，然后返回。

### 使用书源（填写URL或者JSON）
https://shuyuan.mgz6.cc/shuyuan/f9c8786bbe34ad26b35b9c70e161a456.json
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by nEdAy** [comment]
getBookInfoRule() == source.getBookInfoRule()
