### ISSUE TITLE
虽然不会用编写，也要赞一个。建议加多个自动滚动就更好了。

### ISSUE THREAD

**Issue by cpf7115** [gedoor/legado#203]
谢谢作者。
好在找到别人分享的源，不然不会写真用不上。
另外，如果可以的话，加上自动滚屏并能设置滚动的速度。

**Comment by 52fisher** [comment]
新版应该解决了该问题，如有疑问可再次提问。

**Comment by cpf7115** [comment]
感谢大佬
________________________________
发件人: 52fisher <notifications@github.com>
发送时间: 2020年11月24日 0:50
收件人: gedoor/legado <legado@noreply.github.com>
抄送: cpf7115 <peterchen9087@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [gedoor/legado] 虽然不会用编写，也要赞一个。建议加多个自动滚动就更好了。 (#203)


新版应该解决了该问题，如有疑问可再次提问。

―
