### ISSUE TITLE
[BUG] 搜索时停止按钮出现异常

### ISSUE THREAD

**Issue by zealousfool** [gedoor/legado#2032]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
> 

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.062320

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
搜索时停止按钮有时不出现

### 相关截图
>
![cb2a9d340c255dfda2951101b64764b](https://user-images.githubusercontent.com/12507338/177653760-a125a0a8-e293-4736-ab0a-4fd8e4b6663e.jpg)
![a93918cf96f27846a5c5032afd5ff1e](https://user-images.githubusercontent.com/12507338/177653955-091cc190-8663-48f9-a348-9c54e5d84e6e.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
搜索时右下角停止按钮只有在搜索框搜索时才出现，而在搜索结果里点击作者二次搜索时不出现停止按钮。如上截图先搜书名，然后点击第一个结果再点击作者二次搜索，右下角无停止按钮。只有点击搜索框然后再搜索才能出现停止按钮

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by gedoor** [comment]
收到
