### ISSUE TITLE
[Feature Request] 换源时换源页面能否像之前版本一样缩小一点，或者半透明效果

### ISSUE THREAD

**Issue by zealousfool** [gedoor/legado#2033]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 换源时换源页面能否像之前版本一样缩小一点，或者半透明效果，这样换源的结果能提前知道，不合适可以直接再选择别的源

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
![0a2c166bf9922b487af777c2a351f18](https://user-images.githubusercontent.com/12507338/177654398-9e94f89c-6e93-43be-98b4-6bf97561eae5.jpg)
这样
![image](https://user-images.githubusercontent.com/12507338/177654577-240a7968-b5ea-4082-98c6-712f5a04bb99.png)

**Comment by nEdAy** [comment]
我试了试 取消了还原成功后的 dialog 自动消失 并 将换源 dialog 的宽高缩20%；
但效果并不是很好，很难在 dialog 还存在的情况下 从那 20% 了解换源成功后的 正文内容 是否满意；
不过这个确实是个痛点，我体验是换源后不满意，仍需要 激活菜单 -> 点击换源icon（我猜测你可能想简化的是这个步骤），那是不是可以换源成功后，dialog 消失，但出现一个仅存在几秒的浮动按钮，来让用户如果不满意这次换源，那点击这个按钮重新显示换源 dialog 重新选择

**Comment by larryli** [comment]
在阅读页面点击区域设置能自定义操作：切换到上一个源、切换到下一个源。能快速换源就可以了。
