### ISSUE TITLE
请问，如何使用阅读app看正版？比如起点

### ISSUE THREAD

**Issue by gudaocode** [gedoor/legado#2036]
我的源里面添加了起点，然后点击登录，会出现登陆界面，用户名密码后跳转到起点主页，然后点击我的书架，还是让登录，当然前一步不点我的书架，关闭弹出窗口，小说章节也是锁定状态。
看正版，该如何弄？谢谢

**Comment by nEdAy** [comment]
我看源仓库里很多起点源呀 搜 起点 看看
http://yck.mumuceo.com/yuedu/shuyuan/index.html

**Comment by gudaocode** [comment]
> 我看源仓库里很多起点源呀 搜 起点 看看 http://yck.mumuceo.com/yuedu/shuyuan/index.html

……
您不看正文么？

**Comment by nEdAy** [comment]
> 

嗯 我看了 我没用过起点的源 我是怕起点源需要什么特殊配置 你可以参考下

**Comment by gudaocode** [comment]
哦，谢谢！静候大佬帮忙解答

**Comment by letterk** [comment]
登陆后, 跳转到起点首页. 在这一步应该点右上角的√. 登陆只是为了获取cookie. 不是在网页里操作
