### ISSUE TITLE
support Linux/Windows/MacOS [Feature Request] 

### ISSUE THREAD

**Issue by ZhangAustin** [gedoor/legado#2038]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望增加对Arch linux/Windows/MacOS的支持

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by nEdAy** [comment]
现在支持 web 模式（用浏览器看书），所以有什么特别的需求 web 模式不支持的吗？
![image](https://user-images.githubusercontent.com/10076735/177948734-b8dfdd43-992f-483d-b98e-1a1b16707b20.png)
