### ISSUE TITLE
朗读引擎读字不是很清晰,推荐加入夸克朗读引擎,例子:https://nls-gateway-inner.aliyuncs.com/stream/v1/tts?appkey=AMS01xcocDkOJIH9&token=1c988cca36e847029b205a00b91db6b9&text=朗读内容&format=mp3&sample_rate=16000&voice=xiaolei

### ISSUE THREAD

**Issue by fbh45** [gedoor/legado#204]
朗读引擎读字不是很清晰,推荐加入夸克朗读引擎, 例子:https://nls-gateway-inner.aliyuncs.com/stream/v1/tts?appkey=AMS01xcocDkOJIH9&token=1c988cca36e847029b205a00b91db6b9&text=朗读内容&format=mp3&sample_rate=16000&voice=xiaolei

**Comment by gedoor** [comment]
token=1c988cca36e847029b205a00b91db6b9
这个token有时间限制吧

**Comment by fbh45** [comment]
可能 ,毕竟只是用httpcanary抓到的
