### ISSUE TITLE
[BUG] 部份机型无法写入webdav

### ISSUE THREAD

**Issue by dabinn** [gedoor/legado#2041]
### 机型（如Redmi K30 Pro）
> Nvidia Shield TV

### 安卓版本（如Android 7.1.1）
> Android TV 9.1.0 (33.2.0.125)

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.070722

### 问题描述（简要描述发生的问题）
> 使用Nvidia Shield TV时，
webdav(使用坚果云)读取正常，可读取书籍进度，也可回复备份
但无法写入webdav，包括无法写入书籍进度，webdav上bookProgress中的内容不会更新
备份时虽然显示备份成功，但也无法产生或更新backup20xx-xx-xx.zip档
之前用3.21.100121时一切正常
前几天换成3.22.062320之后出现此状况
今天换3.22.070722同样有问题
用手机的话则读取/写入都正常

**Comment by 821938089** [comment]
去备份一下，然后看下日志
在书架右上角三点->日志

**Comment by dabinn** [comment]
开启“记录日志”功能后，按备份
书架右上角三点->日志，显示为空
![IMAG4792](https://user-images.githubusercontent.com/21699064/178123820-cfd26108-c1b5-471f-b54e-2e0893a2c6c3.jpg)

**Comment by dabinn** [comment]
试着找了一下日志位置，不知对不对
也是空档案
![IMAG4792](https://user-images.githubusercontent.com/21699064/178123871-d647eb1e-3996-4fd7-9c2f-0a618c010292.jpg)

**Comment by dabinn** [comment]
试着找了一下日志位置，不知对不对
也是空档案
![IMAG4793](https://user-images.githubusercontent.com/21699064/178123887-ad6973e0-bbfd-4d5a-8812-1a1aa813cf0d.jpg)

**Comment by 821938089** [comment]
重新配置一下webDav

**Comment by dabinn** [comment]
我继续作了几个试验：
1. 移除阅读，重新安装legado_app_3.21.100121.apk，重设所有设置 --> 可成功备份
2. 升级至legado_app_3.22.070722.apk --> 可复原，无法备份
3. 清除webdav相关设置，退出阅读，重新进入并重新输入所有设置 -->  可复原，无法备份
4. 将webdav子路径改为legado2 --> 成功产生legado2及底下的bookProgress/及books/，但备份后仍然没有档案
除此之外观察到一个现象是
在按备份之后，io.legado.app.release/files/底下只有各种json档，但确没产生backup.zip

**Comment by 821938089** [comment]
你的电视是插网线联网的吗？

**Comment by dabinn** [comment]
是，插网线的
