### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gxmandppx** [gedoor/legado#2047]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [*] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>小米10s

### 安卓版本（如Android 7.1.1）
>12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.070921

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>每次打开出现一个toast提示，然后闪退

### 相关截图
>![Screenshot_2022-07-09-23-47-02-956_io.legado.play.release.jpg.png](https://user-images.githubusercontent.com/54546721/178112929-f1c24a0c-c28e-4027-a3a9-85c0e831a28c.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>每次打开都会直接闪退

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
最新版已修复
