### ISSUE TITLE
离线缓存自动停止，以及其他几个问题。

### ISSUE THREAD

**Issue by zhaohuiyingxue** [gedoor/legado#205]
1、小说离线下载时，点击按钮后下载大概百十章（不定）就自动停止了，下载一网文大概得重复点个一二十次才能下载完。
2、小说离线界面的导出，建议增加epub格式的导出。
3、通过webdav备份后，在另一台设备上还原，发现还有部分配置需要重新设置。
4、2.0里的eink模式还会有么？
5、开启网络服务，在端口1122中打开的web阅读器，显示了阅读进度，但打开都是从第一章开始读。

**Comment by 52fisher** [comment]
新版应该解决了该问题，如有疑问可再次提问。
