### ISSUE TITLE
[Feature Request] 简单的改良纯按键操作

### ISSUE THREAD

**Issue by dabinn** [gedoor/legado#2053]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 阅读目前算是可支持纯按键操作，像我平常用电视看书都是使用遥控器的按键
一些像是简单的选择书籍，进入后翻页都没什么问题
但比较大的困扰是在操作的时候没有指示，只能瞎猜目前选中的项目
比如我要选书的时候都是上下让他卷动几次，靠经验去猜现在选择的位置
左右的功能切换也都是要靠猜的

### 期望实现方式（阅读应该如何实现该功能）
> 在方向键操作的时候，简单加个反白或高亮的指示目前项目，就会好用很多了
--
谢谢作者的辛劳，有阅读真是太棒了

**Comment by nEdAy** [comment]
@dabinn 了解一下需求？除了 首页- 书架/发现/订阅/我的 外；还有哪里需要高亮焦点？

**Comment by dabinn** [comment]
谢谢！平常操作主要是选书把他打开而已
另外比较常用大概就更新目录的那个选单吧？
那个瞎按的话也挺不容易按出来的
