### ISSUE TITLE
[Feature Request] web模式行间距字间距

### ISSUE THREAD

**Issue by cxhttt233** [gedoor/legado#2057]
### 功能描述（请清晰的、详细的描述你想要的功能）
**1.web模式，可以调节行间距和字间距**
**2.看到一章结束点下一张太难受了，不如按起点的来，或者加上起点的按钮
对比**
![image](https://user-images.githubusercontent.com/28983554/178151015-c6d19e4f-d45f-4922-b51d-776cc90a2294.png)

![image](https://user-images.githubusercontent.com/28983554/178151004-dd9a6288-86dd-4cdd-8695-55679cd68e38.png)

**Comment by MrLinyuan** [comment]
![image](https://user-images.githubusercontent.com/69339943/178195788-f1a415d3-259a-4351-821e-ccb6c91e4dc8.png)
嗯？

**Comment by MrLinyuan** [comment]
> 

这两个章节切换都有，你是不是忽略了
