### ISSUE TITLE
[Feature Request] 阅读进度条改成全本的

### ISSUE THREAD

**Issue by xxldm** [gedoor/legado#2065]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 能否把截图中的这个进度条改成全本的？
比如拖到一半，跳转到全本的50%处

<img width="421" alt="image" src="https://user-images.githubusercontent.com/38677850/178401979-5ec37e27-57da-4d2b-95dc-915677bf71ca.png">

**Comment by nEdAy** [comment]
这个交互不是很认同
我直观上觉得此处进度条 就是当前章内进行拖动 而不是全文（全文拖目录就好了，而且清楚知道要拖动到哪章附近）

**Comment by xxldm** [comment]
> 这个交互不是很认同 我直观上觉得此处进度条 就是当前章内进行拖动 而不是全文（全文拖目录就好了，而且清楚知道要拖动到哪章附近）

好吧，我的想法是，一般情况下每章的内容不会太多，给个进度条有点大材小用了。
然后我下了一个小说合集，打开一本新书的时候，习惯随机跳几个地方看看。手动选章节也可以，但如果有一个能直接拖的进度条会方便很多。

或者可以考虑把进度条改成 全书目录 的进度（全书100章，拖到一半跳到50章）这种？这样交互就类似，上一页 页码 下一页 算是比较符合一般的操作习惯。
