### ISSUE TITLE
[Feature Request] 在书籍信息中添加设置分组的选项

### ISSUE THREAD

**Issue by 821938089** [gedoor/legado#2069]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在书籍信息中添加设置分组的选项

### 期望实现方式（阅读应该如何实现该功能）
> 在书籍信息页面右上角三点里面添加一个新的的选项叫“设置分组”，点击后显示一个选择分组的弹窗。

### 附加信息（其他的与功能相关的附加信息）
> 想要这个功能是因为我现在这个分组里面的书太多了，我想要将一些完本、烂尾、看不下去的书，移到别的分组里面。
虽然可以在书架管理里面批量管理，但是里面只显示书名、作者和分组，少了很多信息，导致我要在书架里面找到这些书并记住这些书名，然后去书架管理里面重新翻到这些书，非常麻烦，感觉不如我在书架里找到一本直接点进去书籍信息里面设置分组更方便一些。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
![屏幕截图 2022-07-13 220515](https://user-images.githubusercontent.com/8674809/178754121-0fe6c608-f86d-4d23-abab-921d5ca429f8.png)
点击设置分组后打开这个弹窗
![image](https://user-images.githubusercontent.com/8674809/178754402-624c8ef9-cf16-4f88-8a8f-df7298384941.png)

**Comment by lmst2** [comment]
作者
来源
最新
分组 <--
目录
分组功能不就在这嘛，你还要放到右上角干什么

**Comment by 821938089** [comment]
好吧，没看到...
