### ISSUE TITLE
可否用 阅读3 抓取新闻页面?

### ISSUE THREAD

**Issue by rsyqvthv** [gedoor/legado#207]
我知道 阅读 是个书源工具, 并不是新闻抓取工具.
但是我想这个也许并不冲突. 

但是我对于书院制作的各种项目感到十分困惑, 所以请教下, 

如果我想将 [凤凰新闻热点](http://news.ifeng.com/hotnews/) 转成一个列表当作一个书源, 每次点开可以自动看到更新的热点新闻链接, 并且点进去可以直接阅读新闻, 就像读书一样. 没有周围的广告什么的.

不知道谁能给我一个样例, 让我学习一下? 感谢.

**Comment by FanchangWang** [comment]
《阅读》不适合做这个，你的需求推荐你使用《M 浏览器（[酷安下载地址](https://www.coolapk.com/apk/cn.nr19.mbrowser)）》

**Comment by rsyqvthv** [comment]
> 《阅读》不适合做这个，你的需求推荐你使用《M 浏览器（[酷安下载地址](https://www.coolapk.com/apk/cn.nr19.mbrowser)）》

感谢你, 我去研究研究.

**Comment by 52fisher** [comment]
阅读支持这样的功能，但是书源写法你可能得自己先研究研究了
