### ISSUE TITLE
[Feature Request] 希望可以添加在线朗读的离线预加载功能

### ISSUE THREAD

**Issue by lmst2** [gedoor/legado#2071]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
朗读分为系统离线朗读和在线朗读。离线的tts限于处理器性能等原因通常效果不尽如人意。在线的tts比如微软tts就可以达到很好的效果。
然而在线tts的性能会因为网络原因使体验感极差，比如突然网卡了，或者某个地区访问国外tts服务延迟非常大（会导致读完一句话之后要等好久才有第二句），又比如上飞机没网了就用不了了。
所以我在想tts既然是请求完了得到一段mp3或者是wav等音频文件，那何不写一个和离线下载章节一样的功能，按照顺序把请求的音频文件保存下来呢，这样也不会因为网络波动导致每一句话直接都要等上一会，在没有网络的情况下也可以获得在线版的良好体验。
### 期望实现方式（阅读应该如何实现该功能）
> 可以顺序把音频文件保存在一个文件夹里，按照顺序重命名，离线朗读的时候按照顺序播放音频文件就行。
也可以每次获取到下一段音频，就和上一段音频合成，形成一个完整的音频。
具体选哪种操作就怎么方便怎么来。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
这样占用手机存储会非常大,目前是缓存一章的音频

**Comment by lmst2** [comment]
> 这样占用手机存储会非常大,目前是缓存一章的音频

是这样的，我准备自己添加一下这个功能。但是整个app还是比较复杂的，一时间不太确定各个模块之间的关联。现在是知道这些该怎么做，但是不清楚该在哪里添加模块。所以想作者能够帮忙列出有哪些模块我需要改动和添加的。想必作者对整个APP应该是非常熟悉的了，稍微思考一下就能够给出大概思路了。
我的初步想法是在model里面添加一个新的downloadAudio类，这里面可以调用现成的download service 还有 在线朗读服务。但是其他的ui更新还有数据库操作等我就不知道该怎么做了，还没研究透
希望作者可以给个思路，比如该在哪里修改ui，该在哪里操作数据库，操作完了需要调用什么服务migrate数据库等等，指明一下名称就行，我可以自己看看怎么办。但是想获得一个思路好让我更快上手这个APP

**Comment by gedoor** [comment]
io.legado.app.service.HttpReadAloudService
这个就是在线朗读服务,下载朗读语音也在这个里面,缓存音频不需要什么界面吧

**Comment by lmst2** [comment]
> io.legado.app.service.HttpReadAloudService 这个就是在线朗读服务,下载朗读语音也在这个里面,缓存音频不需要什么界面吧

啊，是我没说清楚，我是想搞成和离线下载章节以便于没网的时候看小说一样，搞出来个离线下载听书内容，没网的时候可以继续听书这样，所以需要界面进行操作，比如开始缓存和停止缓存，以及进阶的选择哪些章节缓存，还有显示到底哪些章节已经缓存了等等

**Comment by gedoor** [comment]
io.legado.app.ui.book.cache.CacheActivity
那界面参照这个就行

**Comment by lmst2** [comment]
> io.legado.app.ui.book.cache.CacheActivity 那界面参照这个就行

好的，其他还有什么细节吗，比如缓存了之后应该会把已缓存的章节保存在数据库里面吧，这个数据库操作是在哪里完成的

**Comment by 821938089** [comment]
没有数据库，这个是靠计算阅读文本的md5然后拼出路径来的。

**Comment by lmst2** [comment]
好的，另外我测试io.legado.app.ui.book.cache.CacheActivity的时候看到了这个
![image](https://user-images.githubusercontent.com/29498103/179319965-f41ecfbb-7cf2-466c-8aff-c09edcd47020.png)
从代码来看按理说缓存activity是可以看到音频书籍的。然而实际测试的时候缓存只显示了小说。如下图所示
![image](https://user-images.githubusercontent.com/29498103/179320639-4f74e2fd-2a19-4b0a-a71b-319700529fbf.png)
![image](https://user-images.githubusercontent.com/29498103/179320658-f1db7721-70e9-45be-9f84-6bacf904e462.png)
可以看到，我随便收藏了几本小说加上几本音频，点击缓存、导出的时候，只显示出了小说。而我看最上面那个方程明明是从数据库里select 所有种类的书籍。为啥音频不在里面，难不成是音频书籍的信息根本没有被添加进数据库？
还有这个
![image](https://user-images.githubusercontent.com/29498103/179320863-a13ebde9-bc04-483f-8185-932c0be05d65.png)
![image](https://user-images.githubusercontent.com/29498103/179320888-2b90b009-8405-41f0-a39f-1ef7d021f862.png)
这应该是对应`AppConst.bookGroupAudioId -> appDb.bookDao.flowAudio()`这行代码，可见他从数据库里面没有找到任何书。

然后我点进章节信息，发现前几章的音频已经缓存下来了，说明自动缓存前十章的功能有在起作用。
![image](https://user-images.githubusercontent.com/29498103/179321168-085be44f-962a-469f-bcdc-5efbefd7df4c.png)

但是在缓存/导出activity里面确实没有出现。我本来是想直接利用现成的音频缓存activity实现我的缓存在线tts功能的，准备在阅读界面放个按钮，可以自动创建另一个一模一样的音频书籍，并且把缓存功能替换成在线tts获取音频。所以试了一下音频书籍缓存功能，结果发现根本找不到音频书籍2333. 另外我看了一下，发现谷歌store上的pro版本也存在这个问题，不知道作者有没有发现这个问题以及怎么解决

**Comment by 821938089** [comment]
音频书被下面的代码过滤掉了
![image](https://user-images.githubusercontent.com/8674809/179327000-ebdf0475-5aa7-4f33-9249-27f31296e828.png)

这个音频缓存我估计就缓存个地址吧，我没找到哪里把音频下载下来了

**Comment by lmst2** [comment]
好家伙，为什么要过滤掉呀，是不是暂时只开发了小说缓存功能。。另，这个音频我也不清楚，我是直接点进去发现没有云符号的点开都是可以直接播放的所以想着应该是下载下来了，就是不知道下哪里去了

**Comment by lmst2** [comment]
> 好家伙，为什么要过滤掉呀，是不是暂时只开发了小说缓存功能。。另，这个音频我也不清楚，我是直接点进去发现没有云符号的点开都是可以直接播放的所以想着应该是下载下来了，就是不知道下哪里去了

更正，我断网试了一下，确实只缓存下来了url

**Comment by gedoor** [comment]
是的,音频只缓存了地址,所以过滤掉了

**Comment by lmst2** [comment]
遇到一个问题
![image](https://user-images.githubusercontent.com/29498103/179389541-b849a1f6-deeb-4005-b130-7668aa4bd255.png)
这是BookHelp.kt里面有保存文件的function。我参照这个function的保存地址在HttpReadALoudService.kt里把音频保存在了缓存之外的一样的地方。
![image](https://user-images.githubusercontent.com/29498103/179389661-8f672dca-39da-431f-aec3-55e860c54004.png)
![image](https://user-images.githubusercontent.com/29498103/179389711-084d9a63-e1c8-4ec3-8075-f58d3911151a.png)
地址检查过了和txt文件在一起。但是运行起来他却报错说read only file system。
![image](https://user-images.githubusercontent.com/29498103/179389769-75ad279c-e1bd-46e0-a643-5b0d73c6cd73.png)
这是啥情况呀，按理说这个文件夹是应用内部文件夹，不存在read only的情况呀，况且另外一个地方的function都能保存，为啥我写的就不行呢
提前感谢了。。

**Comment by lmst2** [comment]
咳咳，发现问题了。。
![image](https://user-images.githubusercontent.com/29498103/179390336-e0024dc9-f8e6-4afb-bca9-a8e41e1489c2.png)
习惯性在开头初始化变量，奈何开头的时候mIntent还没传进来。所以变成空字符串了，相当于直接在根目录写入了，当然没权限2333

**Comment by lmst2** [comment]
我暂时放弃写这个功能了。ReadAloudService是单线程的，和下载器的concurent并发严重冲突。（下载的内容混乱，或者干脆没下完就跑到下一章了）其中应该也有一些异步的问题。我想让它异步等待小说文本和声音一起下载完再下载下一章，但是基本上就是小说文本下载完了就下一章了。对于界面完全不了解，本来打算借用本来就有的缓存功能勉强实现一下的。但是发现我还是技术力不够。加上我对这个应用的异步处理不太了解。所以打算暂时放弃了。

大佬们如果有空闲时间可以帮我把这个功能实现一下吗，还是很想要这个功能的。过几天我再看看有什么思路吧 @gedoor @821938089
