### ISSUE TITLE
[Feature Request] 能否支持实体书扫描录入方式与书摘记录功能？

### ISSUE THREAD

**Issue by honghaier250** [gedoor/legado#2074]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 支持实体书扫描录入方式与书摘记录

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by mryun135** [comment]
扫描录入实现用ocr可以搞定，但是这不是阅读软件该涉及的领域了。
