### ISSUE TITLE
[BUG]  点离线缓存，弹出来选择界面，点击确定之后不缓存，状态栏上面下载进度都出不来。

### ISSUE THREAD

**Issue by lpn666** [gedoor/legado#2081]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>
墨案青春版

### 安卓版本（如Android 7.1.1）
>
8

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.071618

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动

### 问题描述（简要描述发生的问题）
>
点缓存没有反应，状态栏上面下载的进度的提示都出不来，下载没有开始。
但是在设置里面设置的预加载10章那个是可以的。

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by lpn666** [comment]
[123.log](https://github.com/gedoor/legado/files/9137412/123.log)

这是我用adb logcat 打印的日志，操作了下载，还有在缓存导出界面的下载，不知道是否有帮助

**Comment by nEdAy** [comment]
麻烦使用的书源 和 书籍 发下吧，我自己这边看没问题

**Comment by lpn666** [comment]
我用的书源是  miaogongzi书源，具体的是www.31xs.net那个。 
书籍是这游戏也太真实了。

**Comment by lpn666** [comment]
我不太懂安卓，咱们软件是怎么启动下载的，调用系统的下载组件么？
我这个设备用小米多看的安卓系统安装阅读是可以正常下载的。
换成现在的墨案系统，都是安卓8.1，但是就没法正常下载了。
我看以前有人提了相似的issue，但是已经关闭了，那哥们估计也没有解决。
