### ISSUE TITLE
[BUG] 章节名称错误

### ISSUE THREAD

**Issue by neetnya** [gedoor/legado#2085]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>
荣耀v9play

### 安卓版本（如Android 7.1.1）
>
7.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.071010

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
章节名称出现错误，
比如 {"status":1,"info":"success","data":{"id":640664,"name":"这个网游策划果然有问题","cid":4629283,"cname":"442、‘欢乐’","pid":4627692, 后略
可以看出正常的章节名称应该是【442、‘欢乐’】，但实际显示的时候会出现错误
https://infosxs.pysmei.com/BookFiles/Html/641/640664/4629283.html

### 相关截图
>
![Screenshot_20220720-100735](https://user-images.githubusercontent.com/12996163/179882670-d0aff141-d338-4310-8df7-e465916eb6e8.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
此书源下(其他好像也有吧 不是很确定)，最新几章都会这样，稳定出现
书名是《这个网游策划果然有问题》

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre>
{
  "bookSourceComment": "",
  "bookSourceGroup": "",
  "bookSourceName": "笔趣阁",
  "bookSourceType": 0,
  "bookSourceUrl": "https://infosxs.pysmei.com/",
  "bookUrlPattern": ".+/BookFiles/Html/\\d+/\\d+/index\\.html",
  "customOrder": 14,
  "enabled": true,
  "enabledCookieJar": false,
  "enabledExplore": true,
  "exploreUrl": "热门连载::https://scxs.pysmei.com/top/man/top/hot/week/{{page}}.html\n抖音热书::https://scxs.pysmei.com/top/man/top/collect/week/{{page}}.html\n高分神作::https://scxs.pysmei.com/top/man/top/vote/week/{{page}}.html\n微信热书::https://scxs.pysmei.com/top/man/top/commend/week/{{page}}.html\n豆瓣高分::https://scxs.pysmei.com/top/man/top/new/week/{{page}}.html\n完本精选::https://scxs.pysmei.com/top/man/top/over/week/{{page}}.html",
  "header": "{\"User-Agent\": \"okhttp-okgo/jeasonlzy\"}",
  "lastUpdateTime": 1651199464976,
  "respondTime": 180000,
  "ruleBookInfo": {
    "name": "$.data.name"
  },
  "ruleContent": {
    "content": "$.data.content\n<js>\na=String(chapter.title).replace(/\\s/g,\"\");\nresult.substring(0,90).includes(a)?result=result.split(a,2)[1]:result;\nresult.toLowerCase()\n</js>",
    "replaceRegex": "##^[^\\n]{0,19}[\\u4e00-\\u9fa5]\\n|^正在更新中，请稍等.+|^[^\\n]*求月票[^\\n]*\\n|^([^\\n]+\\n){0,5}\\h+第\\w{1,7}章[【 ].+\\n|(?<=\\n)\\h+\\W\\n|(?<=\\n)\\h*(打击盗版，支持正版，).*$|(?<=\\n)\\h*[【\\(（][\\u4e00-\\u9fa5]+[）\\)】]$|(?<=\\w：)\\s+(?=“\\w)|(?<=\\w，[”」]|[，、‘《（【［「『])\\s+|\\s+(?=[\\n，、’：；》）】］」』])"
  },
  "ruleExplore": {},
  "ruleSearch": {
    "author": "$.Author",
    "bookList": "$.data[:10]||$.data.BookList[*]",
    "bookUrl": "$.Id@js:\nvar n=result.match(/(^\\d+)\\d{3,}/);\nn=(n)?n[1]:'0';\nresult=(Number(n)+1)+'/'+result;\nbook.origin+'BookFiles/Html/'+result+'/index.html';",
    "coverUrl": "$.Img\n<js>\"https://imgapixs.pysmei.com/BookFiles/BookImages/\"+String(result.match(/[^\\/]+\\.\\w+$/)[0])</js>",
    "intro": "$.Desc",
    "kind": "$.BookStatus&&$.CName&&$.Score##(\\d+\\.\\d)$##$1分",
    "lastChapter": "$.UpdateTime&&$.LastChapter##\\h[\\d:]{8}\\n##",
    "name": "$.Name",
    "wordCount": "$.UpdateTime##\\h[\\d:]{8}"
  },
  "ruleToc": {
    "chapterList": "$.data.list[*].list[?(@.hasContent==1)]",
    "chapterName": "$.name",
    "chapterUrl": "{{$.id}}.html"
  },
  "searchUrl": "https://souxs.leeyegy.com/search.aspx?key={{key}}&page=1&siteid=app2",
  "weight": 0
}
<code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by gedoor** [comment]
我测试一下
