### ISSUE TITLE
Epub文件修改封面图片第2次导入封面图片不变[BUG] 

### ISSUE THREAD

**Issue by subtle99** [gedoor/legado#2094]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.072122

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>Epub文件修改封面图片第2次导入封面图片不变
详细：先导入 123.epub 到 阅读，在电脑上修改 123.epub 封面图片 1.png （仅修改文件内容，如添加文字到图片上，图片文件名不变），再次导入 123.epub 到 阅读，123.epub 的 1.png 内容仍然为 旧的内容，没有更新。 

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

**Comment by gedoor** [comment]
ok
