### ISSUE TITLE
要是能供系统tts引擎调用可好

### ISSUE THREAD

**Issue by chenyajunai** [gedoor/legado#2097]
系统的TTS引擎声音不好听，而且有的很慢，发现导入到阅读后的网络tts语音很快，而且发音人也很多，要是可以供系统TTS引擎调用阅读的网络发音人就好，像图片上能进去选择阅读，这样其它软件就可以调用阅读的更多发音人了
![IMG_20220725_085901](https://user-images.githubusercontent.com/22949809/180674289-1b858d9d-eadd-421d-845b-8922f3141ee7.jpg)

**Comment by gedoor** [comment]
等我有空开发个可配置的tts引擎,把阅读的在线引擎移过去

**Comment by chenyajunai** [comment]
> 等我有空开发个可配置的tts引擎，把阅读的在线引擎移过去

谢谢，好人啊，感谢
