### ISSUE TITLE
希望增加章节缺漏的提示

### ISSUE THREAD

**Issue by teddyundjenny** [gedoor/legado#2098]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 有些章节因为种种原因会被和谐掉，不注意章节序号可能发现不了，因此需要对“遗失的章节”进行提示。

### 期望实现方式（阅读应该如何实现该功能）
> 1. 气泡提示
例如，在226章最后一页翻页后是229章，在页面底部弹出气泡“227, 228章缺失”。
>
> 2. 检查目录
在目录界面增加一个检查功能，指出有哪些章节缺失。

### 附加信息（其他的与功能相关的附加信息）
> 实际情况可能比较复杂。例如，序号可能是阿拉伯数字，可能是汉字；可能分成几部，每一部都从第一章开始，也可能不分。这样就有了4种情况。而有些网站一个目录中就可能包含了上述情况中的几种。

**Comment by 501658362** [comment]
+1
