### ISSUE TITLE
希望可以支持添加文件夹，支持pdf，doc 

### ISSUE THREAD

**Issue by annce** [gedoor/legado#2101]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 当一个本地的pdf及文件阅读管理器

### 期望实现方式（阅读应该如何实现该功能）
>希望可以支持添加文件夹，支持pdf，doc  

### 附加信息（其他的与功能相关的附加信息）
> 谢谢

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by MrLinyuan** [comment]
阅读主要是网络阅读器，你说的这些暂时不会考虑。
