### ISSUE TITLE
[建议] 书籍目录分页加载显示

### ISSUE THREAD

**Issue by FanchangWang** [gedoor/legado#211]
### 问题

当书籍目录分页过多时（超过 100 个分页甚至更多），拉取书籍目录时间会很长，并且会因为拉取时间超时导致『获取目录失败』。

### 优化建议

书籍目录加载完第一页时，就在『书籍详情页』、『书籍目录页』进行显示，并在后台进行后续目录分页的加载，目录底部可以进行『目录获取中』的状态提示。

同时加载完成目录第一页，就可以提供阅读页获取章节正文，不需要等待目录全部加载完成才可以进行阅读。

**Comment by 52fisher** [comment]
一般不会有目录分页超过100个的情况吧

**Comment by FanchangWang** [comment]
> 一般不会有目录分页超过100个的情况吧

确实不会有很多这种，忽略掉吧

**Comment by haohanyuzmx** [comment]
期望目录分页加一，有些书籍本身网络就不太好，分页又多，一次加载成功比较困难
