### ISSUE TITLE
[Feature Request] 希望能增加禁用滑动翻页的功能！

### ISSUE THREAD

**Issue by 18698399901** [gedoor/legado#2110]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 501658362** [comment]
同求

**Comment by 18698399901** [comment]
感谢大佬增加了 滑动翻页阈值，设置高点就不会滑动翻页了！
