### ISSUE TITLE
[Feature Request] 电脑端服务端

### ISSUE THREAD

**Issue by miangou** [gedoor/legado#2113]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 可以在电脑上运行阅读服务端

### 期望实现方式（阅读应该如何实现该功能）
> 发布在PC上的服务端

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>控制台界面（

**Comment by MrLinyuan** [comment]
没有，试试网页版，也能自己搭

**Comment by dianso** [comment]
https://github.com/hectorqin/reader
早就有了

**Comment by miangou** [comment]
> https://github.com/hectorqin/reader
> 早就有了

感谢
