### ISSUE TITLE
[BUG] 有3页正文的小说只显示1页

### ISSUE THREAD

**Issue by subtle99** [gedoor/legado#2122]
### 问题描述（简要描述发生的问题）
>  关于 网站：https://m.xzytkc.com/  书源 正文规则
正文规则：id.nr1@html
正文下一页URL规则：text.下一章@href
正确的内容应该有3页的内容，书源经常只能显示1页，最好的结果就是第1章的内容是正常的，其他都只有1页的内容

如果不是软件BUG，求一个正确 书源 书写方式

**Comment by subtle99** [comment]
帮忙测一下，
[
  {
    "bookSourceComment": "正文有3页只提一页",
    "bookSourceGroup": "我自己定义",
    "bookSourceName": "🐌999小说[err]",
    "bookSourceType": 0,
    "bookSourceUrl": "https://m.xzytkc.com/",
    "bookUrlPattern": "",
    "customOrder": 0,
    "enabled": true,
    "enabledCookieJar": false,
    "enabledExplore": true,
    "exploreUrl": "玄幻小说::/xuanhuan/\n修真小说::/xiuzhen/\n都市小说::/dushi/\n历史小说::/lishi/\n网游小说::/wangyou/\n科幻小说::/kehuan/\n言情小说::/yanqing/\n其他小说::/qita/\n完结小说::/quanben/",
    "header": "{\n\"Cookie\":\"Hm_lvt_921ec5240f31edf56a17a804544f66ae=1657883967; cf_chl_prog=b; Hm_lpvt_921ec5240f31edf56a17a804544f66ae=1657884701\"\n}",
    "lastUpdateTime": 1659567891844,
    "loginUrl": "",
    "respondTime": 180000,
    "ruleBookInfo": {
      "author": "class.block_txt2@tag.p.2@text##作者：",
      "coverUrl": "img@src",
      "intro": "@class.intro_info@text",
      "kind": "class.block_txt2@tag.p.4@text##分类：",
      "lastChapter": "class.block_txt2@tag.a.3@text##最新：",
      "name": "class.block_txt2@h2@a@text",
      "tocUrl": "text.查看完整目录@href"
    },
    "ruleContent": {
      "content": "id.nr1@html##想要看最新章节内容，请下载爱阅小说app，无广告免费阅读最新章节内容。网站已经不更新最新章节内容，已经爱阅小说APP更新最新章节内容。.*|网站公告：亲爱的.*|.*999xs.net.*|请下载小说app爱阅app阅读最新内容|退出转码页面，请下载app爱阅小说阅读最新章节。##",
      "imageStyle": "0",
      "nextContentUrl": "text.下一章@href"
    },
    "ruleExplore": {
      "author": "class.author@text",
      "bookList": "class.bookbox",
      "bookUrl": "class.bookimg@a@href",
      "coverUrl": "class.bookimg@a@img@src",
      "intro": "class.intro_line@text##简介：|\\ \\ ",
      "kind": "",
      "lastChapter": "class.update@a@text",
      "name": "class.bookname@i@a@text"
    },
    "ruleSearch": {
      "author": "",
      "bookList": "",
      "bookUrl": "",
      "coverUrl": "",
      "kind": "",
      "lastChapter": "",
      "name": ""
    },
    "ruleToc": {
      "chapterList": "@class.chapter.-1@li",
      "chapterName": "@a@text",
      "chapterUrl": "@a@href",
      "nextTocUrl": ""
    },
    "searchUrl": "",
    "weight": 0
  }
]

**Comment by 821938089** [comment]
没发现有问题，你把有问题的书和章节发一下

**Comment by subtle99** [comment]
如 都市 分类 （第4本书）：重返84之寒门崛起 ,第1章，第2章内容不对，第3章只取了第1页。

**Comment by 821938089** [comment]
我这里是没问题的，你关一下替换净化试试

**Comment by subtle99** [comment]
![电脑](https://user-images.githubusercontent.com/59327126/182741813-2e3cfe76-fc4e-4d7f-845c-5dbfe03f3f3b.png)
![手机](https://user-images.githubusercontent.com/59327126/182741814-4a2c3035-671b-440f-96aa-aafe37226296.png)

**Comment by 821938089** [comment]
![image](https://user-images.githubusercontent.com/8674809/182746081-947fa227-8858-475e-8fda-b423a052ef9f.png)
我和你的显示不一样，不知道哪里有问题哦
