### ISSUE TITLE
请问目录分页的书源应该怎么写tocUrl

### ISSUE THREAD

**Issue by StanHustler** [gedoor/legado#2123]
dalao们好，最近写源碰到了一个网站，[sir, this way!](https://novelfull.com/)
目录是分页的（不是正文分页），请问这样应该怎么写源呢？

![Snipaste_2022-08-04_00-51-45](https://user-images.githubusercontent.com/62613346/182667962-7b54cd60-4cca-4446-b2c9-2f8e24693304.jpg)
![Snipaste_2022-08-04_01-03-36](https://user-images.githubusercontent.com/62613346/182667994-c88fed5d-9e9d-4b72-8823-bb66f5fdeec0.jpg)

[可能用得上的](https://novelfull.com/ajax-chapter-option?novelId=1139&currentChapterId=1477620)

**Comment by 821938089** [comment]
用目录下一页规则，最好一次性获取完，不然刷新目录会很慢

**Comment by StanHustler** [comment]
> 用目录下一页规则，最好一次性获取完，不然刷新目录会很慢

**Thanks!**
