### ISSUE TITLE
[BUG] 发现页进入目录错误，搜索进入目录正常

### ISSUE THREAD

**Issue by subtle99** [gedoor/legado#2126]
### 问题描述（简要描述发生的问题）
>发现页进入目录错误，搜索进入目录正常
同一本书，直接搜索书名 目录是正常的，从发现页直接进入同一本书，目录错误

### 使用书源（填写URL或者JSON）
[
  {
    "bookSourceComment": "发现页进入目录错误，搜索进入目录正常",
    "bookSourceGroup": "我自己定义",
    "bookSourceName": "🐌云中书库[err]",
    "bookSourceType": 0,
    "bookSourceUrl": "http://m.yunxs.com/",
    "bookUrlPattern": "",
    "customOrder": 0,
    "enabled": true,
    "enabledCookieJar": false,
    "enabledExplore": true,
    "exploreUrl": "玄幻::http://m.yunxs.com/xuanhuan/\n仙侠::http://m.yunxs.com/xianxia/\n都市::http://m.yunxs.com/dushi/\n穿越::http://m.yunxs.com/chuanyue/\n科幻::http://m.yunxs.com/kehuan/\n同人::http://m.yunxs.com/tongren/\n全本::http://m.yunxs.com/over.html",
    "lastUpdateTime": 1659568782984,
    "loginUrl": "",
    "respondTime": 180000,
    "ruleBookInfo": {
      "author": "class.dd_box.0@tag.span.0@text",
      "coverUrl": "img@src",
      "intro": "class.book_about@dl@dd@text",
      "kind": "class.dd_box.0@tag.span.1@text##分类：",
      "lastChapter": "class.book_box@dl@tag.dd.3@span@a@text",
      "name": "class.name@text",
      "tocUrl": "class.book_last.1@dl@dd",
      "wordCount": "class.dd_box.1@tag.span.1@text##字数："
    },
    "ruleContent": {
      "content": "id.chaptercontent@html##云中书库阅读网址：m.yunxs.com.*",
      "nextContentUrl": "text.下一页@href",
      "replaceRegex": ""
    },
    "ruleExplore": {
      "author": "class.p10@dl@dt@tag.span@text",
      "bookList": "class.hot@class.item",
      "bookUrl": "",
      "coverUrl": "img@src",
      "intro": "class.p10@dl@dd@text",
      "kind": "",
      "lastChapter": "",
      "name": "class.p10@dl@dt@tag.a.0@text",
      "wordCount": ""
    },
    "ruleSearch": {
      "author": "class.author@text##作者：.*",
      "bookList": "class.block so_list@class.bookbox",
      "bookUrl": "class.bookname@tag.a.0@href",
      "coverUrl": "img@src",
      "intro": "",
      "kind": "class.cat@text",
      "lastChapter": "class.update@text##最新章节：",
      "name": "class.bookname@tag.a.0@text"
    },
    "ruleToc": {
      "chapterList": "class.book_last.1@dl@dd",
      "chapterName": "a@text",
      "chapterUrl": "a@href",
      "nextTocUrl": "option@value",
      "preUpdateJs": ""
    },
    "searchUrl": "http://m.yunxs.com/plus/search.php?s=00000&q={{key}}",
    "weight": 0
  }
]

**Comment by 821938089** [comment]
详情页URL规则没写

**Comment by subtle99** [comment]
2个地方都是有写的

**Comment by 821938089** [comment]
![image](https://user-images.githubusercontent.com/8674809/182735553-11c69bfa-8a53-464c-983f-6c0f4e1b675b.png)

**Comment by subtle99** [comment]
好了
