### ISSUE TITLE
[Feature Request] WebDAV 书籍修改后同步到本地

### ISSUE THREAD

**Issue by Doddddd** [gedoor/legado#2128]
### 功能描述（请清晰的、详细的描述你想要的功能）
> WebDAV 书籍修改后同步到本地

### 期望实现方式（阅读应该如何实现该功能）
> 对比WebDAV 书籍和本地书籍的修改时间，替换旧文件

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
你是想自动同步吗,可以自己重新webDav导入

**Comment by Doddddd** [comment]
> 你是想自动同步吗,可以自己重新webDav导入

手动删除本地文件，才能重新导入
希望能直接在阅读里完成

**Comment by gedoor** [comment]
我看下
