### ISSUE TITLE
版本3.20.050310导入旧版3.20.032622书源 Bug

### ISSUE THREAD

**Issue by wanashaloner** [gedoor/legado#213]
旧版**3.20.032622**能用的书源导出到本地，换成最新版本**3.20.050310**后导入本地书源，出错，无法导入
![Screenshot_20200510-124330](https://user-images.githubusercontent.com/46282223/81491061-1316f500-92bc-11ea-8023-453832e49b8c.png)

**Comment by Antecer** [comment]
新版本APP可能会对书源数据库添加或者删除字段，因此可能无法降级导入。
