### ISSUE TITLE
禁止阅读自启动情况下在后台反复启动，是什么情况

### ISSUE THREAD

**Issue by Ll-Years** [gedoor/legado#2134]
### 机型
>MiUI 12~13

### 安卓版本（如Android 7.1.1）
>Android 11~12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>已出现好久，不知道更新多少次

### 问题描述（简要描述发生的问题）
>禁止阅读自启动情况下在后台反复启动，是什么情况

### 相关截图
>
![IMG_20220805_220054](https://user-images.githubusercontent.com/104861696/183094834-8b01a6f3-d150-4601-aba0-da95d0735c88.jpg)
#------
![IMG_20220805_215835](https://user-images.githubusercontent.com/104861696/183094955-fb1ae010-f72c-4bfb-8951-ebeb57281827.jpg)
#------
![IMG_20220805_215804](https://user-images.githubusercontent.com/104861696/183095022-e698a0f4-12e1-467f-9b56-8ee096c3de5d.jpg)
#------
![IMG_20220805_220114](https://user-images.githubusercontent.com/104861696/183094621-bca91944-43cb-4a76-a463-202bbfb7733c.jpg)
#------
![IMG_20220805_221425](https://user-images.githubusercontent.com/104861696/183095574-8e231102-1547-4012-ba81-a34917986b74.jpg)

**Comment by gedoor** [comment]
应该是音频按键唤醒的吧,阅读监测了音频按键

**Comment by gedoor** [comment]
![image](https://user-images.githubusercontent.com/22701807/183318400-4615859f-b1e4-4357-bcc7-b555f2c6c4f0.png)
目前阅读只注册了这一个广播接收,.其它的我就步清楚了

**Comment by gedoor** [comment]
![image](https://user-images.githubusercontent.com/22701807/183318551-a7390ec0-70bf-4c3b-ba12-6d75ec53d104.png)
从通知栏启动也有可能是这个,通知栏有个图标可以启动web服务

**Comment by JackiePenghe** [comment]
蓝牙耳机连接可能会自动触发播放，这个也属于媒体按键 还有有线耳机的相关按键
