### ISSUE TITLE
封面以及标题问题

### ISSUE THREAD

**Issue by honor3568** [gedoor/legado#214]
1、封面地址的三个按钮中选择本地图片和刷新封面无法使用
2、封面换源保存之后目录会重新刷新
3、导入的本地文件，其中标题会显示两边，也就是标题不仅会在标题的位置显示而且还会在正文再显示一遍，希望在正文能够不再显示

**Comment by 52fisher** [comment]
双标题问题已经优化，新版应该已经解决了该问题，如有疑问可再次提问。
