### ISSUE TITLE
[BUG] EPUB目录识别错误，阅读时位置错误

### ISSUE THREAD

**Issue by laulguo** [gedoor/legado#2140]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>Redmi K30S Ultra

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.080322

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>EPUB目录识别错误，阅读时位置错误

### 相关截图
>无

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开上传的EPUB文件，第二章诸多标题实际打开的都是同样的页面，会重复打开

### 使用书源（填写URL或者JSON）
>无
[太平洋战争系列(epub).zip](https://github.com/gedoor/legado/files/9280709/epub.zip)

**Comment by misaka-h** [comment]
同样版本，redmi note11t pro，android12，无法本地导入epub电子书。回退至上一版本3.22.072122后恢复正常。
具体表现：无法读取封面，目录等所有内容。

**Comment by gedoor** [comment]
收到
