### ISSUE TITLE
[BUG] 3.22.080322版本无法导入（读取）本地epub

### ISSUE THREAD

**Issue by lkyu-ly** [gedoor/legado#2141]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>redmi note11t pro

### 安卓版本（如Android 7.1.1）
>Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.080322

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>无法本地导入epub电子书。回退至上一版本3.22.072122后恢复正常。
具体表现：无法读取封面，目录等所有内容。

### 相关截图
>无

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>安装3.22.080322版本，并正确导入本地epub

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by gedoor** [comment]
收到
