### ISSUE TITLE
[BUG] 简繁转换 那個人=>神秘人

### ISSUE THREAD

**Issue by ZWolken** [gedoor/legado#2145]
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.072122

### 问题描述（简要描述发生的问题）
>原文的“那個人”在开启繁体转换为简体后为“神秘人”，疑似BUG？

**Comment by dianso** [comment]
私货很多，这个简繁库

**Comment by 821938089** [comment]
@qbeenslee https://github.com/liuyueyi/quick-chinese-transfer
