### ISSUE TITLE
[BUG] 朗读焦点与显示焦点偏移，导致章尾不自动切换到下一章

### ISSUE THREAD

**Issue by hwf1324** [gedoor/legado#2153]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
> Redmi K20 Pro

### 安卓版本（如Android 7.1.1）
> Android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.080322

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
> 朗读焦点与显示焦点偏移，导致章尾不自动切换到下一章

### 相关截图
> 
![1660211359692](https://user-images.githubusercontent.com/43466291/184108056-3569c5af-57df-4d1f-830f-03b0eba184ba.jpg)

![1660211359705](https://user-images.githubusercontent.com/43466291/184108098-bc36092e-8e93-42ff-93f4-cf91e59b04da.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 打开朗读功能时，如果正文有那种 TTS 不读出声的行，例如一部分分割线之类的，就会出现 TTS 直接读下一段，而显示焦点还在上一段的情况，累积到章尾就导致语音播放完而高亮焦点还在前面，不会自动切换到下一章的情况。

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by kinsan2007** [comment]
我也是 老是在章节末尾就不朗读了，还本来就是这样的呢 
只能退回@Voice Aloud Reader

**Comment by hwf1324** [comment]
> 我也是 老是在章节末尾就不朗读了，还本来就是这样的呢 
> 只能退回@Voice Aloud Reader

2.0版目前没有这个问题，3.0的更早版本也许也有没这个问题的。

我怀疑是文本处理的问题，也许是传递给合成器的文本处理掉了不朗读内容的行，但是我没看过源码。

**Comment by gedoor** [comment]
我看下,可能处理了不朗读的段落有问题
