### ISSUE TITLE
[Feature Request] 处理“正在手打中，请稍等片刻……”的章节

### ISSUE THREAD

**Issue by flyisland** [gedoor/legado#2159]
### 功能描述（请清晰的、详细的描述你想要的功能）
问题：目前有不少书源，在最新几天的章节，都只有短短几行，并且注明“正在手打中，请稍等片刻，内容更新后，请重新刷新页面”的说明。这给读者带来很多不便：
1. 兴冲冲下载的最新章节，发现看不了
2. 不知道网站什么时候会更新
3. 也不知道哪些章节刷新了，必须手动逐个刷新查看

希望能做到，从读者的使用角度来说：
1. 可自动检查章节，如发现“正在手打中，请稍等片刻……”，不将其显示为新章节
2. 可批量刷新“正在手打中，请稍等片刻……”的章节

### 期望实现方式（阅读应该如何实现该功能）
我想到一个实现思路：
1. 可自动检查章节，如发现“正在手打中，请稍等片刻……”或者字数小于一个设置值，不将其显示为新章节。这类章节设置为”待更新“章节
2. 提供批量刷新”待更新“章节的功能。如刷新后满足完整章节的要求（如字数，不包含特定字符串等），则标志为新章节

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
可以手动批量刷新，长按刷新按钮会弹出一个菜单可以刷新之后的章节

**Comment by flyisland** [comment]
> 可以手动批量刷新，长按刷新按钮会弹出一个菜单可以刷新之后的章节

多谢告知，我还不知道它可以长按
