### ISSUE TITLE
禁用书源工作显示不正常(CommonRecyclerAdapter.removeItem逻辑不正确)

### ISSUE THREAD

**Issue by yyjdelete** [gedoor/legado#217]
3.20.051419

换源, 长按, 禁用书源
禁用是正常工作了的, 但列表中的显示始终是去掉的最上面一条而不是选中的
疑似这段代码有问题, 应该是先记录index(>=0)再remove
https://github.com/gedoor/legado/blob/455418ecaa926a1f6fbb73419fccb0a3c7e83b1b/app/src/main/java/io/legado/app/base/adapter/CommonRecyclerAdapter.kt#L202-L208

**Comment by 52fisher** [comment]
新版应该解决了该问题，如有疑问可再次提问。
