### ISSUE TITLE
希望更新web端

### ISSUE THREAD

**Issue by caijimoyu** [gedoor/legado#2171]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望web端支持操作：换源，删除失效源，以及校验书源；实现其他翻页效果

### 期望实现方式（阅读应该如何实现该功能）
> 合并阅读服务器端的web样式

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>可参考 `https://github.com/hectorqin/reader` 的效果

**Comment by cwm-peace** [comment]
同求web端！！！

**Comment by gedoor** [comment]
好的,需要时间
