### ISSUE TITLE
[Feature Request] 书源分组的建议

### ISSUE THREAD

**Issue by keaiye** [gedoor/legado#2173]
网络导入书源增加一个订阅的功能，就类似于梯子的那种订阅，因为会导入很多人做的书源，可以方便以后的更新以及书源的来源，可以把这个功能集成到书源分组里
![Screenshot_2022-08-15-00-21-47-672_com v2ray ang-edit](https://user-images.githubusercontent.com/43440669/184545893-1e016860-f40b-4b10-a397-a6173d5f07d6.jpg)

**Comment by 821938089** [comment]
订阅功能在订阅->规则订阅里面
导入书源时可以自定义分组

**Comment by keaiye** [comment]
> 订阅功能在订阅书-> 订阅里面的 订阅源时可以自定义导入分组

找到了  谢谢
