### ISSUE TITLE
[Feature Request] 希望能优化听书路径

### ISSUE THREAD

**Issue by qidizi** [gedoor/legado#2174]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 打开app后,希望能便利的直接听书

### 期望实现方式（阅读应该如何实现该功能）

1.  直接在通知栏上显示播放条,不管上回是听书还是看书,不影响,可以直接点击播放用听方式继续
2.  可以在app首页显示个浮动或按钮继续听书[有通知栏播放,这个可省略]
3.  在每个书列表上显示个浮动播放按钮,直接听书,若是最后听过的,继续章节；或是未听过,直接从首节开始；不用进入阅读模式,浮动按钮不影响原来列表整个点击方式.

### 附加信息（其他的与功能相关的附加信息）
> 无

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
长按app图标有朗读
