### ISSUE TITLE
希望能够添加类似“搜书大师”的标注功能

### ISSUE THREAD

**Issue by ltpai91** [gedoor/legado#218]
希望能够增加类似“搜书大师”一样，选中文本后添加高亮即可对该段话作标注，标注和书签一样，每本书能够统一查看和导出。
我是一个花栗鼠型选手，就是标注功能让我始终无法抛弃搜书大师转向阅读。

**Comment by 52fisher** [comment]
阅读网文用户比较多，标注功能非必需
