### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by mobeiCanyue** [gedoor/legado#2183]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 下拉刷新改为按钮刷新（因为很容易误触，然后误触的话就会导致软件预加载章节）

### 期望实现方式（阅读应该如何实现该功能）
>在这个地方添加一个刷新按钮。
 ![IMG_20220817_235329.jpg](https://user-images.githubusercontent.com/81098819/185185769-9f223e48-1baa-4c6f-9674-799b0cb3c9d6.jpg)

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>![IMG_20220817_235329.jpg](https://user-images.githubusercontent.com/81098819/185185819-6a57d7c2-492f-42a8-93f9-f7dfc180b8db.jpg)

**Comment by MrLinyuan** [comment]
![20220822163850](https://user-images.githubusercontent.com/69339943/185877998-d89f0a63-9188-4a56-bdc8-119d06fb8804.png)
会不会已经有过了？

**Comment by mobeiCanyue** [comment]
已收到邮件, 辛苦了
