### ISSUE TITLE
[BUG] 搜索中简介使用 java.ajax(result.get(0))，报错，使用java.ajax(result)正常

### ISSUE THREAD

**Issue by wpyok500** [gedoor/legado#2184]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>
荣耀 20 pro

### 安卓版本（如Android 7.1.1）
>
鸿蒙 os 2.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.080322

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信

### 问题描述（简要描述发生的问题）
>
搜索中简介使用 java.ajax(result.get(0))，报错，使用java.ajax(result)正常，但result是个list，这样每个元素都要去请求一遍不好，影响性能。

### 相关截图
>
![222](https://user-images.githubusercontent.com/14154547/185265923-fce0587a-8d4e-4e54-9c0b-8782eb8ab103.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
<summary>点击展开</summary>
 <pre><code>

[
  {
    "bookSourceComment": "",
    "bookSourceGroup": "兮",
    "bookSourceName": "顶点小说(兮)",
    "bookSourceType": 0,
    "bookSourceUrl": "www.bookb.net",
    "bookUrlPattern": "",
    "concurrentRate": "",
    "customOrder": -26,
    "enabled": true,
    "enabledCookieJar": false,
    "enabledExplore": true,
    "exploreUrl": "玄幻小说::https://www.bookb.net/xuanhuanxiaoshuo/1_{{page}}.html&&修真小说::https://www.bookb.net/xiuzhenxiaoshuo/2_{{page}}.html&&都市小说::https://www.bookb.net/dushixiaoshuo/3_{{page}}.html&&穿越小说::https://www.bookb.net/chuanyuexiaoshuo/4_{{page}}.html&&网游小说::https://www.bookb.net/wangyouxiaoshuo/5_{{page}}.html&&科幻小说::https://www.bookb.net/kehuanxiaoshuo/6_{{page}}.html&&完本小说::https://www.bookb.net/wanben/1_{{page}}",
    "header": "{\n    \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36\",\n    \"Content-Type\":\"application/x-www-form-urlencoded;charset=gbk\"\n}",
    "lastUpdateTime": 1660781166517,
    "loginCheckJs": "",
    "loginUi": "",
    "loginUrl": "",
    "respondTime": 180000,
    "ruleBookInfo": {
      "author": "id.info@tag.p.0@text",
      "coverUrl": "id.fmimg@tag.img@src",
      "intro": "id.intro@text",
      "kind": "[property$=category]@content&&[property$=status]@content",
      "lastChapter": "[property$=lastest_chapter_name]@content&&[property$=update_time]@content",
      "name": "//*[@id=\"info\"]/h1/text()"
    },
    "ruleContent": {
      "content": "id.content@textNodes"
    },
    "ruleExplore": {
      "author": ".s5@text",
      "bookList": "<js>var doc=org.jsoup.Jsoup.parse(result).select(\".l>h2\");\nvar txt=doc[0].text().replace(\"好看的\",\"\").replace(\"最近更新列表\",\"\").replace(\"列表\",\"\");\n//java.log(txt);\njava.put('a',txt);\n//java.log(java.get('a'));\ndoc =org.jsoup.Jsoup.parse(result).select(\"#newscontent>.l>ul>li\");\n</js>\n",
      "bookUrl": ".s2>a@href",
      "coverUrl": ".s2>a@href##/(\\d+)##$1###@js:var xid=Math.floor(result/1000);'https://www.bookb.net/files/article/image/'+xid+'/'+result+'/'+result+'s.jpg'",
      "intro": "",
      "kind": "<js>java.get('a')</js>",
      "lastChapter": ".s3@text",
      "name": ".s2@text"
    },
    "ruleSearch": {
      "author": "class.odd.1@text",
      "bookList": "class.grid@tag.tr!0",
      "bookUrl": "class.odd.0@tag.a@href",
      "coverUrl": "class.odd.0@tag.a@href##/(\\d+)##$1###@js:var xid=Math.floor(result/1000);'https://www.bookb.net/files/article/image/'+xid+'/'+result+'/'+result+'s.jpg'",
      "intro": "#nr > td:nth-child(1) > a@href<js>java.ajax(result.get(0))</js>[name$=description]@content",#result.get(0)报错, result正常
      "kind": "class.even.-1@text",
      "lastChapter": "class.even.0@text&&class.odd.-1@text",
      "name": "class.odd.0@text",
      "wordCount": "class.even.1@text"
    },
    "ruleToc": {
      "chapterList": "id.list@li",
      "chapterName": "tag.a@text",
      "chapterUrl": "tag.a@href"
    },
    "searchUrl": "https://www.bookb.net/modules/article/search.php,{\n    \"charset\": \"gbk\",\n    \"method\": \"POST\",\n    \"body\": \"searchkey={{key}}&searchtype=articlename\"\n}",
    "weight": 0
  }
]

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
不要在搜索规则里使用ajax，会导致每个搜索结果都要访问一次网络，极大的拖慢了时间
另外，result是个string，不是list
