### ISSUE TITLE
[Feature Request] 搜索历史的排序，变为最近搜索/可选

### ISSUE THREAD

**Issue by zealousfool** [gedoor/legado#2187]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 搜索历史的排序，经过实验我发现现在的排序是按照搜索频次排序，不太合理，希望能够变为最近搜索项出现在第一位，或者排序可选是频次还是日期。
![3ce6abb6b553e3ed25230353669af2b](https://user-images.githubusercontent.com/12507338/185892677-af06627d-d3bc-4d9d-a44c-3d7f95da85df.jpg)

### 期望实现方式（阅读应该如何实现该功能）
> 希望能够变为最近搜索项出现在第一位，或者排序可选是频次还是日期。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
ok

**Comment by gedoor** [comment]
测试版本已改
