### ISSUE TITLE
应用闪退

### ISSUE THREAD

**Issue by BangClieCC** [gedoor/legado#2191]
系统安卓：5.0，运行内存：4g；软件版本：阅读（3.22.081920）；场景一：浏览图文类订阅，当滑动出现缩放按钮时，立即返回上级，应用卡死，闪退；场景二：点击阅读记录，应用卡死，闪退；场景三：切换主题时，翻页卡顿，之后会很大概率闪退；（这些问题在最新测试版依旧存在）
![01](https://user-images.githubusercontent.com/57783996/186334374-9a007325-f9f8-4e0b-acc7-7ac896d32acd.jpg)
![02](https://user-images.githubusercontent.com/57783996/186334390-28e16efb-5892-4dac-9f5a-8ee3c2ff1b3c.jpg)
![03](https://user-images.githubusercontent.com/57783996/186334402-a100093f-01a5-4fc6-bfc1-658df088f1d1.jpg)
![04](https://user-images.githubusercontent.com/57783996/186334411-f101d1ef-e66b-45c2-86fe-2ccac66db000.jpg)
![05](https://user-images.githubusercontent.com/57783996/186334419-bfa6018d-ff65-4b77-b036-f3772dbdace3.jpg)
![06](https://user-images.githubusercontent.com/57783996/186334427-c766f1a2-fae3-4253-8bbd-bcc3aae4e2f2.jpg)
![07](https://user-images.githubusercontent.com/57783996/186334438-2f09055d-8e40-40ba-add0-6b26f204a118.jpg)

**Comment by gedoor** [comment]
你这个系统好像缺少java库

**Comment by BangClieCC** [comment]
我试了早期的一个阅读版本（3.21.08141244），场景三会卡顿，但应用不会闪退，场景一、二应用也不会闪退。那么，大佬，如果想使用最新版本的阅读，除了换机或者升级系统外，是不是就没有其他解决办法了？

**Comment by BangClieCC** [comment]
解决了  升级了 系统 可以了

**Comment by BangClieCC** [comment]
我升级到了安卓7   一切问题都解决了，感谢！
