### ISSUE TITLE
详情页的章节目录需要点击按钮后，才会触发循环请求章节数据，返回html 的json数据，请问各位大佬这个章节目录规则该怎么写。 

### ISSUE THREAD

**Issue by wpyok500** [gedoor/legado#2193]
1、详情页的章节目录需要点击按钮后，才会触发循环请求章节数据，返回html 的json数据，请问各位大佬这个章节目录规则该怎么写。 

书库网站：https://www.idejian.com/

2、java.ajax 支持设置heads 吗？

3 、能否访问请求网络？
~~~~
<js>
var map = new Map();
map.set('User-Agent', "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36");
java.get("https://m.idejian.com/catalog?bookId=12524852", map)；
</js>
~~~~

//实现重定向拦截，返回[Connection.Response](https://jsoup.org/apidocs/org/jsoup/Connection.Response.html)
java.get(url: String, headers: Map<String, String>)
java.post(urlStr: String, body: String, headers: Map<String, String>)

@gedoor 大佬这种能处理吗？

**Comment by wpyok500** [comment]
@821938089 大佬，第3点能简单举例下，还是没明白

**Comment by 821938089** [comment]
```js
var headers = {"User-Agent": "..."}
java.get("https://m.idejian.com/catalog?bookId=12524852", headers)

```

**Comment by wpyok500** [comment]
val map = mapOf<String,String>("User-Agent" to "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36")

**Comment by 821938089** [comment]
你这是干嘛用的，阅读的规则只能写js啊，执行不了kotlin

**Comment by wpyok500** [comment]
> ```js
> var headers = {"User-Agent": "..."}
> java.get("https://m.idejian.com/catalog?bookId=12524852", headers)
> ```

<js>var hesads={"User-Agent" : "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36"};
java.get("https://m.idejian.com/catalog?bookId=12524852", heads)；</js>

这样报错
![Screenshot_20220825_234726_io legado app release](https://user-images.githubusercontent.com/14154547/186711419-ca0efd3f-77e9-476c-8d8d-17818802dd98.jpg)

**Comment by 821938089** [comment]
分号打错，变量名也不对

**Comment by wpyok500** [comment]
![Screenshot_20220825_235644_io legado app release](https://user-images.githubusercontent.com/14154547/186713274-6bca4038-02c1-41a3-a07e-175817a1c151.jpg)

**Comment by 821938089** [comment]
这样写 java.get(...).body()
还有规则执行结果需要是一个数组

**Comment by wpyok500** [comment]
~~~~
<js>java.get(https://m.idejian.com/catalog?bookId=12524852,{
    "charset": "utf-8",
    "method": "get",
    "User-Agent": "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36",
     "Content-Type":"application/x-www-form-urlencoded"
});</js>
~~~~
![Screenshot_20220826_065527_io legado app release](https://user-images.githubusercontent.com/14154547/186782889-550fe50e-472f-46a2-994a-0ce158e9e842.jpg)

**Comment by wpyok500** [comment]
~~~~
<js>java.get("https://m.idejian.com/catalog?bookId=12524852",{
    "charset": "utf-8",
    "method": "get",
    "User-Agent": "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36",
     "Content-Type":"application/x-www-form-urlencoded"
});</js>
~~~~
![Uploading Screenshot_20220826_065847_io.legado.app.release.jpg…]()

**Comment by wpyok500** [comment]
~~~~
<js>java.get("https://m.idejian.com/catalog?bookId=12524852",{
    "charset": "utf-8",
    "method": "get",
    "User-Agent": "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36",
     "Content-Type":"application/x-www-form-urlencoded"
});</js>
~~~~
![Screenshot_20220826_065847_io legado app release](https://user-images.githubusercontent.com/14154547/186783259-e1eb7827-8872-438f-878e-c79ced817ce6.jpg)

**Comment by 821938089** [comment]
java.get的第二个参数是协议头，不要把不是协议头的东西写进去

还是有以下问题：
这样写 java.get(...).body()
还有规则执行结果需要是一个数组

**Comment by wpyok500** [comment]
唉！
~~~~
<js>java.get("https://m.idejian.com/catalog?bookId=12524852",{
    "User-Agent": "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36"
}).body();</js>
~~~~
![Uploading Screenshot_20220826_123005_io.legado.app.release.jpg…]()

**Comment by wpyok500** [comment]
~~~~
<js>java.get("https://m.idejian.com/catalog?bookId=12524852",{
    "User-Agent": "Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36"
}).body();</js>
~~~~~
![Screenshot_20220826_123005_io legado app release](https://user-images.githubusercontent.com/14154547/186822712-147c1741-22c0-4351-8ec7-871ffd926093.jpg)

**Comment by 821938089** [comment]
你这个规则现在只获取到了json文本，需要把他处理成一个数组
