### ISSUE TITLE
[Feature Request] 希望跨设备提示同步书架时，不要把配置文件都同步了

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2195]
在跨设备使用时长时间没同步，经常会提示webdev书源比本地新，这功能还原里还会包含配置文件，不适合在跨设备时使用。因为同步数据是合并不是覆盖，如果一台做了书源校验，又会被合并数据，一般同步只需要书架玘阅读进度，但是现在书架没法单独同步，需要还原配置才行

**Comment by gedoor** [comment]
好的

**Comment by mobeiCanyue** [comment]
我觉得同步还是有必要同步一些必要的配置的。比如果 字体边距 字距段距，辛辛苦苦调好结果同步没有同步上很难受。

**Comment by zousizhe** [comment]
> 我觉得同步还是有必要同步一些必要的配置的。比如果 字体边距 字距段距，辛辛苦苦调好结果同步没有同步上很难受。

我说的是跨设备的还原，不是备份，备份一天
基本都有一两次，你改不改排版，也是那样设备，而且排版在跨设备时也未必都适合。基本也很少去改动，用不着经常去同步这种设置，同步无非是阅读进度，其次是书架，书源一个月都很少去改动，设置没有必要几乎不使用同步

**Comment by mobeiCanyue** [comment]
> 我说的是跨设备的还原，不是备份，备份一天 基本都有一两次，你改不改排版，也是那样设备，而且排版在跨设备时也未必都适合。基本也很少去改动，用不着经常去同步这种设置，同步无非是阅读进度，其次是书架，书源一个月都很少去改动，设置没有必要几乎不使用同步

       理解你的意思，同一部设备同步时不需要同步配置，但是跨设备需要。

**Comment by mobeiCanyue** [comment]
> > 我觉得同步还是有必要同步一些必要的配置的。比如果 字体边距 字距段距，辛辛苦苦调好结果同步没有同步上很难受。
> 
> 我说的是跨设备的还原，不是备份，备份一天
> 基本都有一两次，你改不改排版，也是那样设备，而且排版在跨设备时也未必都适合。基本也很少去改动，用不着经常去同步这种设置，同步无非是阅读进度，其次是书架，书源一个月都很少去改动，设置没有必要几乎不使用同步

你这个需求不是有实现吗
![IMG_20220829_023948.jpg](https://user-images.githubusercontent.com/81098819/187089647-26a3dfd4-f8b8-46b9-adf6-c55a7b4b1007.jpg)

**Comment by zousizhe** [comment]
> 

你说是主动避开这几个设置，但是有些是避不开，比如两台设备书源不一致，字体放置路径不一样的问题
跨设备使用会隔几天主动弹出同步提醒，一按错就是麻烦，
其实需要同步的是书架以及阅读记录，阅读进度需要实时同步。其他数据只是在需要时手动还原。但是现在书架并不能单独操作。
我平时是平板做主要阅读设备，另外一台设备是手机，平时在外面也没多少时间用来看，调整书源主要也是在平板上。要保持一至除非每次都清空书源或者两台设备都做校验，天天备份都不知道是哪台机的数据，都不敢轻易还原

**Comment by mobeiCanyue** [comment]
说回来 我想问你一下 
你的同步是退出软件自动同步吗。我的好像每次退出软件都没有给我同步，都是手动的。
![Screenshot_2022-08-29-21-47-12-783-edit_io.legado.play.release.png](https://user-images.githubusercontent.com/81098819/187217651-eb651171-eca8-4ffb-a239-10f758045347.png)

**Comment by zousizhe** [comment]
> 说回来 我想问你一下 你的同步是退出软件自动同步吗。我的好像每次退出软件都没有给我同步，都是手动的。 ![Screenshot_2022-08-29-21-47-12-783-edit_io.legado.play.release.png](https://user-images.githubusercontent.com/81098819/187217651-eb651171-eca8-4ffb-a239-10f758045347.png)

有时候会，有时候不会，一天最少有一次，就是不知道是哪台设备的数据，反正没事是不想还原，就是有时候想同步书架没办法，但是我也是情愿重新搜索添加小说，也不想用还原数据来同步书架
