### ISSUE TITLE
[Feature Request] 希望把二维码分享与上传合并在①赶快

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2196]
二维码分享书源功能几乎没法使用，书源编辑里把书源转二维码，有字符串长度限制，这个功能几乎没有书源能使用，在书源导出有个上传到上网的功能，希望能加个二维码的形式，或者替换掉书源编辑里的二维码分享

**Comment by zousizhe** [comment]
二维码分享书源功能几乎没法使用，是真把书源转成字符做二维码，有字符串长度限制，这个功能几乎没有书源能使用，在书源导出有个上传到上网的功能，希望能加个二维码的形式，或者替换掉书源编辑里的二维码分享

**Comment by gedoor** [comment]
上传到网络受网络影响有时候无法使用,我考虑一下
