### ISSUE TITLE
[BUG] 导入本地的epub文件不显示封面

### ISSUE THREAD

**Issue by pqwer99** [gedoor/legado#2211]
### 机型（nova9）
>
### 阅读Legdao版本（我的-关于-版本,如3.22.082409）
>

### 问题描述（简要描述发生的问题）
>

导入本地的epub文件不显示封面

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by Xwite** [comment]
可能是懒加载的原因
https://github.com/gedoor/legado/blob/8861436b40c1e4ecdd1794c957ac3e61282e5e02/app/src/main/java/io/legado/app/model/localBook/EpubFile.kt#L110
