### ISSUE TITLE
[BUG] 书源修改或者删除，缓存就无法使用了

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2214]
本来是打算用阅读来珍藏书籍的，但是似乎本地缓存不是很稳当，修改过书源或者校验时删除了书源，本地缓存就无法加载了，从书籍详情进目录看，是显示缓存还在的，但是却无法加载了，如果遇到的冷门书，没有源可用的话，那就直接无法读取了。要是导出到本地，又会要很多道步骤，要是能支持一键转成本地也好，直接就在副本路径，不用生成两个文件，也不用删除书签之类的数据，也不用再重新调分组

**Comment by mobeiCanyue** [comment]
> 本来是打算用阅读来珍藏书籍的，但是似乎本地缓存不是很稳当，修改过书源或者校验时删除了书源，本地缓存就无法加载了，从书籍详情进目录看，是显示缓存还在的，但是却无法加载了，如果遇到的冷门书，没有源可用的话，那就直接无法读取了。要是导出到本地，又会要很多道步骤，要是能支持一键转成本地也好，直接就在副本路径，不用生成两个文件，也不用删除书签之类的数据，也不用再重新调分组
> 

首先 **改书源 缓存是肯定没了的**，因为不同的小网站，内容不一定相同。
举例：有的小网站会屏蔽敏感词 有的不会，这就导致了书籍内容也不尽相同。
**如果书源从A改到B，显示的是B的缓存，而不是A的**。

其次 收藏问题
阅读支持导出缓存的书籍为txt，你可以找一个你比较满意的书源，然后缓存下来直接导出，注意导出的时候，你要等它导完。

**Comment by zousizhe** [comment]
> 
那么在无书源的情况下呢？似乎也不用考虑那些，缓存都已经处理好的数据了，难道每次读取本地缓存还是要经过书源解析一次吗？应该不用吧

**Comment by mobeiCanyue** [comment]
> > 
> 那么在无书源的情况下呢？似乎也不用考虑那些，缓存都已经处理好的数据了，难道每次读取本地缓存还是要经过书源解析一次吗？应该不用吧

你的无书源是什么意思呢？本地导入的txt吗？
如果这样的话应该是不过缓存的。

如果有本地缓存的肯定是优先用本地缓存，而不是网络上的书源。

**Comment by zousizhe** [comment]
> > > 
> > 
> > 
> > 那么在无书源的情况下呢？似乎也不用考虑那些，缓存都已经处理好的数据了，难道每次读取本地缓存还是要经过书源解析一次吗？应该不用吧
> 
> 你的无书源是什么意思呢？本地导入的txt吗？ 如果这样的话应该是不过缓存的。
> 
> 如果有本地缓存的肯定是优先用本地缓存，而不是网络上的书源。

如上所说，书源失效被校验后删除了，或者手动修复过书源，书源覆盖更新过，修改的书源需要切换一次源再换回来，如果没有其他源可换话，只能删除再重新搜索，重新缓存。这些都是原有缓存数据可用的情况下，并不需要再做二次解析，所以与新书源对应不上这个说法，应该是不成立，正常换源时，也允许单章换源，之前的缓存哪怕是正文加载不全也不会被强制重新解析，需要自己做一次全部缓存才行

**Comment by 821938089** [comment]
你把自动换源关了就可以了
