### ISSUE TITLE
建议增加中文竖排功能

### ISSUE THREAD

**Issue by southern-dust** [gedoor/legado#222]
如图，在当下以自左向右为主流的阅读习惯中，「这种自上而下的文字排版格式，会产生一种有序、静雅的美感。这种秩序之美不仅是读者的阅读需要，也是在这种秩序之下所产生的愉悦、静谧的阅读心境。」
![IMG_20200526_134603](https://user-images.githubusercontent.com/16912182/82864526-4cf02880-9f57-11ea-99d9-044cddf828a2.jpg)

**Comment by yimingriyue** [comment]
竖屏竖排的排版，也有助于于眼球上下运动，避免眼球一动不动，容易疲劳。

**Comment by BestGreed** [comment]
非常赞同，我也觉得竖排排版挺符合阅读习惯的
