### ISSUE TITLE
[BUG] 书源变量说明variableComment导入时丢失

### ISSUE THREAD

**Issue by lixuqi** [gedoor/legado#2221]
### 机型（如Redmi K30 Pro）
>小米 10

### 安卓版本（如Android 7.1.1）
>安卓11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.082409

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>
书源基本栏填写<变量说明variableComment>后导出分享链接，分享内容中存在variableComment，但是在其他设备导入时variableComment丢失。

### 相关截图
>
无具体截图

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
同问题描述

**Comment by gedoor** [comment]
收到

**Comment by gedoor** [comment]
已修复,等更新
