### ISSUE TITLE
[Feature Request] 希望可以设置目录书源

### ISSUE THREAD

**Issue by Kelvin-zk** [gedoor/legado#2223]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 问题：有很多书源没有更新到最新的章节，每次换源的时候目录也会跟着变，这样不方便看书

### 期望实现方式（阅读应该如何实现该功能）
> 希望可以设置目录书源，换源的时候如果选的书源缺少部分章节可以在目录中把相应的章节变灰色

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
各书源目录会不一样统一不了,有些是第1章有些是第一章或者有些是1.根本没办法判断

**Comment by Kelvin-zk** [comment]
可以发布网站上的章节为准

**Comment by FinchOrigin** [comment]
这个和读者心里有没有数没关系，而是程序没办法准确识别A书源目录与B书源章节的对应关系
