### ISSUE TITLE
[Feature Request] 希望优化换源策略

### ISSUE THREAD

**Issue by Kelvin-zk** [gedoor/legado#2224]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 一般情况下要换源的时候都是发生在当前章节看不了的情况下，这个时候换源的话是不希望影响之前看过的章节，现在换源的话单击换源按钮的话是整书换源

### 期望实现方式（阅读应该如何实现该功能）
> 希望把换源按钮的换源策略默认为更换当前章节及后续章节的书源，或者是增加设置换源策略的按钮，可以自由设置换源按钮是更换整书书源还是更换当前章节及后续章节的书源。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by zousizhe** [comment]
目前是可以做到单章换源的。长按缓存图标，但是如果之前使用的书源被删除了，可能会被强制重新缓存之前的内容
