### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 0987363** [gedoor/legado#2225]
### 机型（如Redmi K30 Pro）
>Sony DPT RP1

### 安卓版本（如Android 7.1.1）
>Android 5.1.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>[3.22.083120](https://github.com/gedoor/legado/releases/tag/3.22.083120)

### 问题描述（简要描述发生的问题）
> 选择ttf字体时，不识别中文名字体，将文件名改为英文就能识别字体

**Comment by Kalinundefined** [comment]
我的DPTRP没有出现这个问题，可以提供一下字体文件吗，我测试一下

**Comment by 0987363** [comment]
不好意思，忘了发字体

https://www.dropbox.com/s/brnr81zz2rh96a3/%E6%B5%AA%E6%BC%AB%E9%9B%85%E5%9C%86%E9%85%8D%E6%AD%A3%E5%9C%86%E8%A5%BF%E6%96%87_%E5%AE%81%E9%9D%99%E4%B9%8B%E9%9B%A8.ttf?dl=0
