### ISSUE TITLE
[Feature Request] 自定义超时时间

### ISSUE THREAD

**Issue by zaw007** [gedoor/legado#2228]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 可以自定义解析的超时时间
我配了一个书源，它的目录页设置了一些障碍防爬，抓取到的目录顺序需要特殊处理，部分章节没有链接，所以我想了一个办法，把目录地址设置为第一个找到的章节地址（即第一章，这个是固定的），把翻页规则设置为下一章的url，章节地址设置为当前地址({{baseUrl}},{"webView":true}，webview是因为有时正文内容是多个请求然后合并起来的)，这样进到第一章，去找下一章的地址，递归下去即可获取到完整的目录，缺点就是非常慢。我测试过，规则没问题，章节数较少时，解析正常，一旦多了，就无法获取到数据，调试模式下有时会报出timeout异常，但大多数时候，调试会无报错突然中断。
我猜测可能线程设置了超时时间，这些解析由于是递归，所以都在同一个线程里，递归时间久了就超时退出。当然我只是猜测，不太熟悉java，就没去翻源码。

### 期望实现方式（阅读应该如何实现该功能）
> 一个参数，像这样 {"timeout":-1}，正数就是超时的秒数，负数就是永不超时。当然也可以有一个全局参数，可以设置timeout。

### 附加信息（其他的与功能相关的附加信息）
> 这是我配置书源的部分信息
    "ruleSearch": {
        "bookList": "class.m9",
        "name": "tag.a.0@text",
        "author": "tag.span@tag.font.1@tag.a@text",
        "kind": "tag.span@tag.a.1@text",
        "lastChapter": "tag.a.1@text",
        "intro": "class.soujj@text",
        "coverUrl": "class.tp@tag.a@tag.img@src",
        "bookUrl": "tag.a.0@href"
    },
    "ruleExplore": {},
    "ruleBookInfo": {
        "name": "class.m9@class.lookmc@tag.strong@text",
        "author": "class.m9@class.zl.1@tag.a@text",
        "kind": "class.m9@class.zl.0@tag.a@text",
        "wordCount": "class.m9@class.zl.3@text##.*字数: |.*浏览: |.*更新: ",
        "intro": "class.js@text",
        "tocUrl": "class.mread@tag.tr.1@tag.a@href"
    },
    "ruleToc": {
        "chapterList": "tag.html",
        "chapterName": "class.max@tag.strong@text",
        "chapterUrl": "{{baseUrl}},{\"webView\":true}",
        "nextTocUrl": "class.max@tag.a@href"
    },
    "ruleContent": {
        "content": "class.content@html",
        "imageStyle": "TEXT"
    }

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
应该是网络超时，这种你调再大都没用。
这样的方法刷新目录代价太大了，章节数多的话估计几个小时都加载不完。
刷新一次要几个小时谁能忍受...

**Comment by gedoor** [comment]
有一个固定的超时时间是180秒

**Comment by gedoor** [comment]
再长我感觉没意义

**Comment by zaw007** [comment]
> 应该是网络超时，这种你调再大都没用。 这样的方法刷新目录代价太大了，章节数多的话估计几个小时都加载不完。 刷新一次要几个小时谁能忍受...

看到时候没目录太难受了，那边小说章节不算很多，最多就两三百章，应该不到一小时基本上就能抓完，等待时间长我倒无所谓，现在基本超过30章就超时了。

**Comment by zaw007** [comment]
> 应该是网络超时，这种你调再大都没用。 这样的方法刷新目录代价太大了，章节数多的话估计几个小时都加载不完。 刷新一次要几个小时谁能忍受...

看到时候没目录太难受了，那边小说章节不算很多，最多就两三百章，应该不到一小时基本上就能抓完，等待时间长我倒无所谓，现在基本超过30章就超时了。

**Comment by 821938089** [comment]
是网络超时，这个调了没用，这个超时我记得是30秒的，已经很大了。

**Comment by zaw007** [comment]
改用js处理
