### ISSUE TITLE
导入某些本地txt 失败或无法识别章节目录

### ISSUE THREAD

**Issue by ShanHuilu** [gedoor/legado#223]
版本：3.20.052420
1. 导入本地txt失败，显示内容：
LoadTocError:length=131072; regionStart=0; regionLength=-1
同一个txt用UC小说导入没问题
2. 导入本地txt 章节目录无法识别
txt 大小24MB ，导入成功，但无法识别章节目录。
同样UC小说导入没问题

在哪里能添加附件？ 我把这2个txt给附上

**Comment by ShanHuilu** [comment]
导入失败的问题找到原因了， txt里包含特殊字符“◇” ， 替换掉之后就可以了。

**Comment by ShanHuilu** [comment]
第二个问题将txt改成unicode编码保存后好了

**Comment by 52fisher** [comment]
麻烦将txt发我，我看看是不是目录的判定规则出现了问题。
邮箱：i@qnmlgb.trade
标题：legado 无法识别章节目录

内容请打上一些文字，以免被过滤规则拦截造成退件。
附件上传txt文件

**Comment by ShanHuilu** [comment]
邮件已发，请注意查收。

**Comment by ShanHuilu** [comment]
已有规则支持
