### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JackiePenghe** [gedoor/legado#2231]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [√ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>
Edge
### 机型（如Redmi K30 Pro）
>
Redmi 9

### 安卓版本（如Android 7.1.1）
>
Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.083120

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
Web端编辑书源，无法拉取源（其它页面都能进）
猜测可能是书源太多？我导入了源仓库的所有3.0书源

### 相关截图
>
![image](https://user-images.githubusercontent.com/20922322/188074314-7ce9e140-6879-4b3a-a7c4-5bbe5c58a908.png)
![image](https://user-images.githubusercontent.com/20922322/188074455-924fe35f-ef72-414d-b789-6d74c7fd881a.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
导入源仓库全部3.0书源 [http://yckceo.vip/](http://yckceo.vip/)
打开web服务，在浏览器中操作书源，选择“拉取源”

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by UltramarineSky** [comment]
不知道是不是拉取时有大小限制，试过逐渐删除部分书源可以拉取成功，但再导入几个比较复杂体积较大的书源后，虽然数量比拉取成功时的书源数量少也不行，往往需要再多删些书源才能成功拉取

**Comment by 821938089** [comment]
测试版换了个书源编辑器，已经可以用了

**Comment by UltramarineSky** [comment]
> 测试版换了个书源编辑器，已经可以用了

感謝，期待更新
