### ISSUE TITLE
分组管理界面删除没有二次确认容易误触

### ISSUE THREAD

**Issue by hotcoffie** [gedoor/legado#224]
自建的分组，手指一碰删除按钮就秒删，特别容易误触
特别是在勾选右上角一些系统默认分组时，很容易因为连点两下导致删除自建分组
今天一个失手，几十本完本小说跑到了未分组里，损失惨重

**Comment by Mupceet** [comment]
@gedoor 我感觉这个分组管理应该开一个全界面更好看一点，和书架整理一样。
这样删除加个确认步骤更合理，或者加个撤销操作的Snackbar。

**Comment by gedoor** [comment]
好的2020年8月31日 下午8:06，Mupceet <notifications@github.com>写道：

@gedoor 我感觉这个分组管理应该开一个全界面更好看一点，和书架整理一样。

这样删除加个确认步骤更合理，或者加个撤销操作的Snackbar。
