### ISSUE TITLE
[BUG] 仿真翻页卡顿明显

### ISSUE THREAD

**Issue by SkyDream01** [gedoor/legado#2241]
### 机型（如Redmi K30 Pro）
>Redmi K50 Ultra

### 安卓版本（如Android 7.1.1）
>Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.083120（pri）

### 问题描述（简要描述发生的问题）
>仿真翻页卡顿明显,掉帧（15帧左右）

**Comment by 821938089** [comment]
背景用纯色，或者降低背景图片的分辨率

**Comment by SkyDream01** [comment]
> 背景用纯色，或者降低背景图片的分辨率

试过了，改善不明显

**Comment by zousizhe** [comment]
总感觉这个仿真翻页不如2.0流畅，用手慢慢拉过屏幕肉眼可见的掉帧
