### ISSUE TITLE
有些小说网站搜索界面没有封面但是详情里面有，这会导致阅读的搜索界面也是没有封面的但是点进去详情是有的

### ISSUE THREAD

**Issue by jiangshuai218** [gedoor/legado#225]
有些小说网站搜索界面没有封面但是详情里面有，这会导致阅读的搜索界面也是没有封面的但是点进去详情是有的，能否优化一下这个逻辑

**Comment by shutaozhenzhen** [comment]
这个逻辑基本上没法优化，或者不适合优化。
这个逻辑是这样，这些网站你去搜索的时候就是没有封面的，要你点进去详情页里才有封面。如果要对这个做优化，等于要遍历这堆详情页……也就是要访问的页面一下子翻了十倍不止。你想想这个效率损耗，多不值得
