### ISSUE TITLE
[BUG] 书籍变量没有保存

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2259]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>
vivo Y3

### 安卓版本（如Android 7.1.1）
>
Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
最新

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
在详情页填的书籍变量没有保存，java.log()了一下，只能看见自己用java.put保存的变量

### 相关截图
>
![Screenshot_20220909_200328](https://user-images.githubusercontent.com/104120418/189348092-b2cd65c8-76ee-4ffd-8ede-4aad8bc6f546.jpg)
![Screenshot_20220909_200416](https://user-images.githubusercontent.com/104120418/189348093-ecd602e2-b9ec-4bb6-9404-a99c774b01ac.jpg)
![IMG_20220909_201127](https://user-images.githubusercontent.com/104120418/189348122-99c899d9-1cb2-4abf-80f7-c0887e3683ba.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
![image](https://user-images.githubusercontent.com/8674809/189362885-ab49f18e-25c1-48ea-8cab-4f9644eb8f37.png)
![image](https://user-images.githubusercontent.com/8674809/189362919-be5d1fcb-6aee-4411-a64e-c5e7d0002b73.png)
对比一下缺了啥

**Comment by iyhkhtrk** [comment]
@821938089 用book.getVariable("custom")返回的是null

**Comment by iyhkhtrk** [comment]
明白了，谢谢大佬
