### ISSUE TITLE
[Feature Request] 书源搜索有优化策略吗？

### ISSUE THREAD

**Issue by ftnoone** [gedoor/legado#2264]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 类似每次搜索后给书源加一个响应时间相关的权重，权重高的下一次优先使用，app里有实现吗

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Xwite** [comment]
无

**Comment by zousizhe** [comment]
> 

可以在书源校验时记录书源的访问速度，然后搜索时优先使用快的源，目前的多线程还是在撞运气，有时候倒霉五六秒才出结果，有时却是抬手就能出结果

**Comment by zousizhe** [comment]
> 无

可以在书源校验时记录书源的访问速度，然后搜索时优先使用快的源，目前的多线程还是在撞运气，有时候倒霉五六秒才出结果，有时却是抬手就能出结果

**Comment by 821938089** [comment]
你可以校验一遍书源，把失效的删除，这样搜索就快了。
还可以直接把线程数调高，也可以提升搜索速度。

另外，其实是可以手动对书源按响应时间排序的，不过不建议，书源多的话基本不准。
