### ISSUE TITLE
[BUG] 还是本地小说分组的问题。

### ISSUE THREAD

**Issue by weakestan** [gedoor/legado#2266]
### 问题描述（简要描述发生的问题）
>> 
这个bug有1年多了，以前也提交过，现在再提交一下。
本地书籍添加后，group为0，这个分组只能在书架管理中只能选择“全部”才能看到。
然后“未分组”这个组完全没用，即没办法分进去，也没办法看。
书籍少的时候就“全部”选择后，把其他分组反选，来导入目的分组。
现在书籍多了，只能备份后，编辑bookshelf.json，替换所有group=0的书籍。

### 建议
>
1.添加本地书籍的时候可以选择一个默认分组，我们就长期清空这个分组到其他需要的分组里面去。
2.或者把“未分组”利用起来，好像你分组id不能随便改，那就把“未分组”id弄成-1，默认就分到-1这个“未分组”去。

 **3.还是希望有个多级目录浏览方式打开书籍，本地书籍界面感觉更友好。目前架构下实现可能困难。有空就做吧。**

**Comment by 821938089** [comment]
本地书籍在本地分组里看不到吗？

app自带的分组只是对书的分类，是虚拟的分组，不能修改，你需要自己创建分组，然后把书分到里面去才是真正的分组。

**Comment by weakestan** [comment]
> 本地书籍在本地分组里看不到吗？
> 
> app自带的分组只是对书的分类，是虚拟的分组，不能修改，你需要自己创建分组，然后把书分到里面去才是真正的分组。

能看到。

如果没有网络订阅分组，本地和全部看到的书籍是一样的。都是所有分组在一起显示。
这样不容易选择出刚添加的本地书籍。
比如说所有本地书籍120本，A组分了30本，B组分了30本。C组分了60本。
然后我准备新添加30本书籍到D组。
默认添加到group0，只能在本地或者全部中的150本书中看到。即使排在最前面，要选出这30本书也很麻烦。
分组不多的情况下，我可以A组全选，C组全选，B组全选，然后全部书籍，最后反选。移入分组D。
分组少的时候还可以这么操作，分组多了我只能改json文件了。

**Comment by 821938089** [comment]
你可以选这30本书的第一本和最后一本，然后右下角三点菜单里面有个选中所选区间，点一下就能直接选上这30本书。

**Comment by weakestan** [comment]
好吧，还有这种操作，确实没摸索出来。
我刚刚想到一招，默认新添书籍group不是为0么，我直接修改bookgroup.json,把未分组groupid改为0试试。

**Comment by weakestan** [comment]
改为0没用。
发现这个分组id有意思。我刚才删除分组后。发现书籍的分组乱了，而且一本书可以在多个分组。
正式用的分组id是2的阶乘，也就是说小说的分组不是在bookgroup里面1对1查找结果，而是做的位运算获取所在组。
分组group改为0没用，因为0是不会算出正确分组的。
而且前面的分组不能随便删。

建议这里也改进下吧，正常书籍不会在2个组，直接查找就行了。

**Comment by gedoor** [comment]
添加了本地未分组
