### ISSUE TITLE
来自eink设备的建议

### ISSUE THREAD

**Issue by prenfic** [gedoor/legado#227]
1. 希望能有旧版本减少动画的选项
2. 希望能有关闭所有封面页只显示书名的选项
3. 希望能有设置应用最小字号选项（系统此选项已阉割）

最后，很感谢作者的努力跟付出，请问有paypal之类的接收小额捐赠的方式吗？

**Comment by 52fisher** [comment]
E-ink模式已经实现去掉动画功能
