### ISSUE TITLE
[BUG] 部分字体在开字体加粗选项后无法在正文生效，标题会生效

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2272]
有些比较较粗的字体在切换中与粗显示效果完全一样，但是在顶部章节标题的字体会变得更粗，正文却无效果。  试过在静读天下上面相同字体可以加粗正文。

另外问一下这个细的选项是不是个无用的，从来没见过有字体能支持的。

这是两个粗字体
https://wwm.lanzouy.com/ix1RV0blsc5i

**Comment by 821938089** [comment]
这个字体正常和加粗的粗细是一样的

粗细支不支持要看字体
