### ISSUE TITLE
[BUG] 读本地epub报错 “LoadTocError：目录列表为空”

### ISSUE THREAD

**Issue by ChenyangGao** [gedoor/legado#2275]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
> vivo iqoo neo 5

### 安卓版本（如Android 7.1.1）
> Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.083120

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 电信，wifi环境

### 问题描述（简要描述发生的问题）
> 新安装的阅读app，没有添加任何书源。在随便添加任何的 epub 书籍，打开就显示  “LoadTocError：目录列表为空”，我添加了十几本本地的 epub，全部都报这个错，不过有一定概率，过了几分钟，就能读了。
于是我随机挑选了十几本书，反复试验，要看看是不是书的问题。经过多次试验，我发现，过几分钟后，能读的，还不一样，看运气。可能这次试验，过几分钟，这几本不报错，下一次试验，就是另外几本了。反正，添加本地epub时，100%报错，过一会哪几本正常能看了，不知道，看运气。

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>
没有添加任何书源，我只是想看本地的epub

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by ChenyangGao** [comment]
是不是本地 epub 添加进去后，要从什么地方搜索这本书的信息，信息搜索不出来，才有一定的概率能看？

**Comment by Xwite** [comment]
已经修了 下载测试版

**Comment by ChenyangGao** [comment]
> 已经修了 下载测试版

ok，我试一下

**Comment by ChenyangGao** [comment]
> 已经修了 下载测试版

测试版哪里下载
