### ISSUE TITLE
[Feature Request] 自定义规则过滤书源

### ISSUE THREAD

**Issue by FreedomFoolt** [gedoor/legado#2278]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 已经提供了自动换源功能，请问决定换源的规则是什么呢？这个规则希望能够自定义

### 期望实现方式（阅读应该如何实现该功能）
> 通过自定义规则筛选某个章节的书源
e.g. 只要内容中包含有"阅读模式|404|403"的字，这个书源就被过滤掉，不显示或者不切换到该书源。字数少于`500`字，该书源也被过滤掉。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
书籍所使用的书源不存在时就会自动换源

**Comment by FreedomFoolt** [comment]
> 书籍所使用的书源不存在时就会自动换源

那么这确实是一个新功能需求。为：添加新的换源规则，符合某些条件的书源（在单章中）也视为不存在或者过滤掉

**Comment by h11128** [comment]
支持！换一个书源，检查，然后换下一个书源，这个过程效率实在太低了。而且出现很多没有更新章节内容，只更新标题的书源。有这么一个规则可以在手动或者自动换源的时候节省很多时间

**Comment by h11128** [comment]
而且添加自定义的规则，也许可以通过规则对书源进行评分，比如说内容的完整性，无关内容占比，响应时间。有评分的话就可以自动找到哪个是最有效的书源

**Comment by Xwite** [comment]
closed #2333
