### ISSUE TITLE
[BUG] 本地导入任意EPUB文件，均无法识别元数据，并提示“LoadTocError:目录列表为空”

### ISSUE THREAD

**Issue by eralmtice** [gedoor/legado#2279]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [*] Chrome/Edge/Firefox PC 
> 104.0.2-1

### 机型（如Redmi K30 Pro）
> Redmi K30 Ultra & Redmi Note11T Pro 

### 安卓版本（如Android 7.1.1）
> 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.080322 & 3.22.081920 & 3.22.082409 & 3.22.083120

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 任意网络状况

### 问题描述（简要描述发生的问题）
> 3.22.072122版本可正常导入EPUB文件，此版本之后的所有版本（3.22.080322 & 3.22.081920 & 3.22.082409 & 3.22.083120均已测试），已授予存储空间访问权限，从阅读导入或由文件管理器“通过阅读打开”任意EPUB文件，均无法识别元数据，并提示“LoadTocError:目录列表为空”。
> 
> 以上版本导入TXT文件未见异常，可正常渲染，并生成可用的目录。

**Comment by 821938089** [comment]
测试版已修复
