### ISSUE TITLE
能否增加一个对本地的小说进行小说内搜索的功能

### ISSUE THREAD

**Issue by Tsyshiu** [gedoor/legado#228]
开发者您好：
我不知道大家是否有这个需求，能否增加一个在小说内搜索的功能，就像windows的记事本、wps、office里面的查找功能一样？可以参考多看的小说内搜索功能？
或者说这个功能其实已经有了？只是我没找到吗？如果是这样，有人能告知我一下吗，我找了半天找不到，😆

最后感谢开发者的付出

**Comment by h11128** [comment]
赞同，这个功能很实用，但是app没有这个功能

改天试着写写看

**Comment by h11128** [comment]
最近初步实现了搜索的功能
![Screenshot_20200914-033120](https://user-images.githubusercontent.com/22561041/93043203-1da51a80-f61f-11ea-8ba0-7f46e4811e0a.png)
![Screenshot_20200914-033127](https://user-images.githubusercontent.com/22561041/93043205-1f6ede00-f61f-11ea-902a-4647eacc1acb.png)
![Screenshot_20200914-033114](https://user-images.githubusercontent.com/22561041/93043208-20a00b00-f61f-11ea-9aa6-978c654250f5.png)

但是还有很多需要完善和优化的地方

**Comment by Tsyshiu** [comment]
nice，感谢几位开发者的辛勤付出
