### ISSUE TITLE
[WIP] 书源web编辑未同步

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#2284]
当前web编辑源码~~https://github.com/jgckM/legado_web_editor~~
https://github.com/gedoor/legado_web_bookSource_editor

https://github.com/gedoor/legado_web_bookSource_editor/pull/1
- [x] #2250 段评规则
- [x] #2283 图片二次解密规则
- [x] 基本：变量说明
- [x] 详情：允许修改书名作者、下载URL规则
- [x] 目录：更新之前JS
- [x] 其他：CookieJar开关，段评开关
- [x] 自动提交编译
- [ ] ~~兼容订阅源~~

**Comment by 821938089** [comment]
其实还缺一些
基本：变量说明
详情：允许修改书名作者、下载URL规则
目录：更新之前JS
其他：CookieJar开关，段评开关

**Comment by Xwite** [comment]
其他需求https://github.com/gedoor/legado/pull/2235#issuecomment-1236121738
