### ISSUE TITLE
主页刷新时希望可以尝试加载正在阅读的或者正在阅读的下一章章节，加载成功时数字变红

### ISSUE THREAD

**Issue by SJJ-dot** [gedoor/legado#2286]
### 功能描述
> 主页刷新时希望可以尝试加载正在阅读的或者正在阅读的下一章章节，加载成功时数字变红

### 期望实现方式（阅读应该如何实现该功能）
> 主页刷新时检查阅读记录，如果下一章或者当前章节内容未加载或者加载失败时，尝试加载内容，加载成功数字变红

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
刷新书架时每一本书的目录更新完就会预下载章节的

**Comment by SJJ-dot** [comment]
> 刷新书架时每一本书的目录更新完就会预下载章节的

章节没变的情况下，对之前加载失败的章节会尝试重新加载吗？加载成功会提示吗？这在看连载小说的时候很有用

**Comment by 821938089** [comment]
要看怎样的加载失败，如果提示获取正文失败，是可以重新加载的。
其他情况需要手动刷新，长按刷新按钮可以刷新后面的章节。

没有提示。

**Comment by SJJ-dot** [comment]
> 要看怎样的加载失败，如果提示获取正文失败，是可以重新加载的。 其他情况需要手动刷新，长按刷新按钮可以刷新后面的章节。
> 
> 没有提示。

能否考虑获取正文失败时在首页预加载，并且增加提示呢？每次都要点进去加载的话比较麻烦

**Comment by gedoor** [comment]
那得多少提示,不可能的,太多了
