### ISSUE TITLE
[Feature Request] 新的【动画】选项：无动画滚动

### ISSUE THREAD

**Issue by IMJoyJ** [gedoor/legado#2298]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 新的【动画】选项：无动画滚动

### 期望实现方式（阅读应该如何实现该功能）
> 和目前的【滚动】一样，以拖拽方式可以让页面上下滚动；但在点击操作翻页时，没有动画。

### 附加信息（其他的与功能相关的附加信息）
> 使用情景：单手看书，看漏几行想回看，按左半屏向上并不方便，所以要【滚动】；快速滚动的动画晃眼，而且回退又太多。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> http://jp.duels.link:5212/s/odFn/video?name=SVID_20220917_154628_1.mp4
录了个小视频（软件不是阅读，是有类似功能的某大师）。

**Comment by IMJoyJ** [comment]
（保活）

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/pull/2457
