### ISSUE TITLE
[BUG] web书源编辑器无法从编辑源中粘贴书源导入到左侧表单

### ISSUE THREAD

**Issue by 821938089** [gedoor/legado#2307]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.091920

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>web书源编辑器无法从编辑源中粘贴书源导入到左侧表单

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>向编辑源中粘贴书源，然后下一步不知道该怎么操作了，以前那个导入按钮不见了，然后左侧表单也没自动导入书源

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by Xwite** [comment]
收到
对了你web书源可以正常删除吗

**Comment by 821938089** [comment]
最新正式版不能，测试版可以

还有个问题，书源列表的样式好像有点问题。
书源列表滚动条向下拉，左侧表单也会向下跑。
![image](https://user-images.githubusercontent.com/8674809/191167836-a453a799-d0a5-48f5-a61a-1b02342381b3.png)
