### ISSUE TITLE
[BUG] web书源编辑无法删除书源

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#2308]
### 安卓版本（如Android 7.1.1）
>11

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开web服务，点击web端书源编辑，先拉取书源，然后选中任意书源，点击删除书源，结果无法删除，F12 console显示报错
可能是这的原因
https://github.com/gedoor/legado/commit/b484a1096e8ee8ab0cf72ee9edcf856278ce4e0b

```js
{
errorMsg:"Interfaces can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Interface name: kotlinx.coroutines.sync.Mutex",
isSuccess: false
}
```

**Comment by gedoor** [comment]
我看下

**Comment by gedoor** [comment]
没问题了
