### ISSUE TITLE
设置为朗读时，可以把｛上一段，暂停，下一段｝这三个按钮放在侧边嘛？，如下图

### ISSUE THREAD

**Issue by 2306758816** [gedoor/legado#231]
**设置为朗读时，可以把｛上一段，暂停，下一段｝这三个按钮放在侧边嘛？（屏幕左边，右边，底边，都可以），如下图**
![Screenshot_2020-06-07-14-45-06-971_io legado app](https://user-images.githubusercontent.com/25405826/83962387-73a34d00-a8cf-11ea-8264-8b6d5b350cf2.png)
![Screenshot_2020-06-07-14-45-06-971_io legado app 2](https://user-images.githubusercontent.com/25405826/83962463-35f2f400-a8d0-11ea-9133-fd93a3383721.png)

**这样就不会像下面这样想点 下一段 或 上一段 的时候下面有一些内容被遮掩了**
![Screenshot_2020-06-07-14-32-57-248_io legado app](https://user-images.githubusercontent.com/25405826/83962405-a0576480-a8cf-11ea-94b3-1b8cbf009269.png)

**另外感谢作者为大批阅读爱好者提供了这么好的阅读APP，非常感谢**

**Comment by gedoor** [comment]
目前已经支持分区设置操作了
