### ISSUE TITLE
[Feature Request] 封面能不能跟正文一样加个图片解密

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2313]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
有些源的封面要解密才能显示，例如这个源
### 期望实现方式（阅读应该如何实现该功能）
> 
跟正文的图片解密一样
### 附加信息（其他的与功能相关的附加信息）
> 
http://www.yckceo.com/d/67sBz
### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by iyhkhtrk** [comment]
谢谢大佬，学会了

**Comment by iyhkhtrk** [comment]
大佬，用封面解密之后有部分图片不能显示，用之前的写法就可以
![Screenshot_20220921_111703](https://user-images.githubusercontent.com/104120418/191406856-0174973d-2f71-4368-ab55-724bcc723ecc.jpg)

**Comment by Xwite** [comment]
应该是缓存了
打开调试看看

**Comment by iyhkhtrk** [comment]
调试没有报错

**Comment by iyhkhtrk** [comment]
清理缓存之后好了，谢谢大佬
