### ISSUE TITLE
[BUG] 系统更新后，存储只有“仅照片和视频”权限了，打不开本地小说了

### ISSUE THREAD

**Issue by zhangshaohua199** [gedoor/legado#2316]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
> 荣耀V40

### 安卓版本（如Android 7.1.1）
> 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.092020

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
> 见标题，没有全部存储权限了，打不开本地小说了

### 相关截图
>
![image](https://user-images.githubusercontent.com/26537659/191411009-36dbedbc-4b8f-49d9-ab2d-3495ad35c553.png)
<img width="452" alt="image" src="https://user-images.githubusercontent.com/26537659/191411046-72ccc58e-1821-4b81-805b-0636c4fb2fc8.png">
![image](https://user-images.githubusercontent.com/26537659/191411071-b4560fda-8c36-4cac-894c-9e68c75414e7.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
重新打开对应的小说文件

**Comment by zhangshaohua199** [comment]
> 重新打开对应的小说文件

退了重新进吗？不行啊
覆盖安装了app也不行

**Comment by 821938089** [comment]
使用手机自带文件管理器找到对应小说文件，然后用app重新打开
或者把app内的本地小说删除，重新到书架右上角三点的添加本地里面加回来

**Comment by zhangshaohua199** [comment]
> 

用了第二个方法可以了👍
