### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by zhj9709** [gedoor/legado#232]
1. 打开软件时，如果上次阅读如果在其他自定义的书架时，会有一个从一个书架切换到另一个书架的动画，我手机上这个动画不流畅，所以看着有点不舒服，但在默认的第一个书架上，再次打开软件不会有这样的切换动画，所以希望能修改一下。(看漫画的那个异次元不会有这样的问题，挺好的)。或是加个设置，可以关闭书架点击时的切换动画，就像是从书架切换到发现，我的等页面一样，没有动画。

2. 还有一个我在2.0上就反馈过的问题，比如我看一本已经完结的书了，我把这本书的允许更新关掉了，因为完结不需要更新，但在我换源后，又默认打开了，2.0上也是一样，所以希望可以一起解决这个问题。

3. 想要快速的翻页，快速点击，但每次都是双击只能翻一页，也希望可以解决一下(2.0不会有这样的问题，2.0是点几下屏幕就翻几页)

4. 希望页眉页脚信息那里可以再加一个电量及时间，同时显示

**Comment by zhanghang1994** [comment]
自定义背景，退出软件后有时会导致失效

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues
