### ISSUE TITLE
[Feature Request] epub书籍能否实现注释/超链跳转

### ISSUE THREAD

**Issue by xhpk** [gedoor/legado#2325]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在有些书里面会有一些注释的地方（类似于这样的：[1]xxx ），这样用epub格式打开，点击这些注释是可以跳出对应的内容，或者是跳转到对应的页面上。

### 期望实现方式（阅读应该如何实现该功能）
> epub格式书籍实现注释跳转

### 附加信息（其他的与功能相关的附加信息）
> 一般epub书里面会自带这些超链，而非阅读器生成，只需要支持跳转即可

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 这里以多看为例，打开一本epub格式的书
**比如我打开一个目录，这个目录是可以跳转的**
![Screenshot_2022-09-22-16-32-40-638_com duokan reader](https://user-images.githubusercontent.com/40262993/191699356-5e64d699-4c64-4736-82e8-521b024495c3.jpg)
**然后我点击某一个，就跳转到对应的页面上**

![Screenshot_2022-09-22-16-32-54-402_com duokan reader](https://user-images.githubusercontent.com/40262993/191699589-56f00477-87f2-41be-bd58-4c1fc914810d.jpg)

**然后假如我点击某个注释，就跳到对应的注释页面**
![Screenshot_2022-09-22-16-33-14-987_com duokan reader](https://user-images.githubusercontent.com/40262993/191699868-b339eb32-fa62-44e2-9ae9-3a5903008487.jpg)
![Screenshot_2022-09-22-16-33-18-600_com duokan reader](https://user-images.githubusercontent.com/40262993/191699876-6e199758-9dc8-4445-9bd1-57188be74eae.jpg)

**Comment by Xwite** [comment]
应该不行

**Comment by xhpk** [comment]
> 应该不行 epub解析之后变成文本了 丢失了信息

o(╥﹏╥)o
