### ISSUE TITLE
[增加s3同步] 

### ISSUE THREAD

**Issue by Benjamin-Watson0** [gedoor/legado#2328]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 能增加s3同步吗，很期待

### 期望实现方式（阅读应该如何实现该功能）
> 就是通过s3同步

### 附加信息（其他的与功能相关的附加信息）
> 还有一个建议，希望有机会能看到阅读能像纯纯写作那样，可编辑，感谢您

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Xwite** [comment]
duplicate of #2329
