### ISSUE TITLE
[Feature Request] 建议把本地分组从自带未分组里分出去

### ISSUE THREAD

**Issue by ll8456** [gedoor/legado#2330]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 0915添加的更新，感觉反而乱了书架…

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
修改了,分为本地未分组和网络未分组
