### ISSUE TITLE
书源过滤功能建议：通过主角名+字数方式过滤无效书源

### ISSUE THREAD

**Issue by zhangweildlh** [gedoor/legado#2333]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 因各种原因，一些网站的小说章节页中要么没有真实内容，要么内容不完整(比如全章节3千字儿，它只显示300字儿)
因此，建议采用“主角名+字数方式过滤无效书源”

### 期望实现方式（阅读应该如何实现该功能）
> 一般小说最开始的章节页是完整的，不完整的章节页通常在最近更新部分。因此，是否能自动采集小说第10~第21章节的内容，筛选出里面出现频率最多的人物姓名(可以用搜狗+百度输入法的常用人名词库作为字典，并且允许用户自己输入小说主角姓名)。
用此人物姓名检索最新章节内容，如果最新章节中没有出现，或者出现频率少于2次，且章节总字数低于500字(允许用户自己调整)。
则判定该章节没有真实内容或者内容不完整！！！
阅读APP自动更换小说源！！！
> 建议在自动换源的时候对候选源进行多线程检测，而不是单线程一个一个排队检测。

**Comment by gedoor** [comment]
不好实现
