### ISSUE TITLE
[BUG] 在web上阅读后回到app不会同步阅读进度

### ISSUE THREAD

**Issue by easythd** [gedoor/legado#2338]
如题。
此问题在21年底开始出现，在12月底时我反馈过，1月份的版本中修复过两次版本后恢复正常了。但在5月份的版本又开始出现，我当时在5月和7月都在那个issue帖子中继续反馈过，但到现在的版本都一直未修复。（请参考上一个issue 1478： https://github.com/gedoor/legado/issues/1478 ）

由于我经常在web和app中切换阅读，总感觉这个bug非常麻烦，还是厚着脸皮再次发个新的issue了。

具体现象和操作重新描述如下：
先在app上阅读某一本书到306章，然后换在web上阅读，从306阅读到了318，这时回到app上打开时，还是原来在app上阅读的进度306章节，往前读到下一章会翻到307章节，但此时点开目录列表中显示当前章节却是318。
（如果在web上点开阅读的书不是在app上最后阅读的同一本书，就没有这个问题。但只要是在app上最后阅读的书又在web继续阅读，就肯定有这问题。）

拜托重新修复下吧？

难道这是个案？只有我遇到？或是没有人用web功能？我看都没有任何人反馈web阅读的问题。。。就我一个人持续在反馈。。。好惨。

**Comment by Xwite** [comment]
bug小能手

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/blob/49f286313f80a2d9e38ba341877c5f7effcd4194/app/src/main/java/io/legado/app/ui/book/read/ReadBookViewModel.kt#L85-L91

```kotlin
ReadBook.durChapterIndex !== book.durChapterIndex
```

**Comment by easythd** [comment]
哎呀，这是已经找到问题并修复了？真是高效啊~ 感谢感谢感谢！~~ @Xwite

**Comment by easythd** [comment]
等着发布~！

**Comment by Xwite** [comment]
没



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月27日(星期二) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] [BUG] 在web上阅读后回到app不会同步阅读进度 (Issue #2338)




 
哎呀，这是已经找到问题并修复了？真是高效啊~ 感谢感谢感谢！~~ @Xwite

**Comment by easythd** [comment]
额。。。好吧，继续等~

**Comment by Xwite** [comment]
fixed #2342
