### ISSUE TITLE
[Feature Request] 朗读设置能否换个位置？能否增加朗读的停顿时间设置？

### ISSUE THREAD

**Issue by joezjy** [gedoor/legado#2345]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 1，TTS引擎的设置，能不能调整个位置？在朗读开始后，才进行设置，有点不直观，而且在切换时，因为已经在朗读了，也会容易冲突。

> 2，能不能优化一下朗读时的停顿时间，无论用哪一种TTS引擎，即使将语速调到最大，句子与句子间，段落与段落间的停顿，都非常长，对于我们这种求量不求质的读者，这个停顿还是有点烦人的～～当然，如果能进行设置，兼顾“量”与“质”的用户就最好

### 期望实现方式（阅读应该如何实现该功能）
> 1，所有的设置，建议都归集到同一位置，例如***我的***->***设置***里
> 2，语速里，将停顿也考虑进去

### 附加信息（其他的与功能相关的附加信息）
> **None**

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> **None**

**Comment by gedoor** [comment]
朗读按钮可以长按,直接进入设置,不开始朗读,朗读之间的停顿没办法解决,现在朗读完一句都是直接朗读下一句的,根本没添加停顿
