### ISSUE TITLE
[Feature Request]搜索时选择多个源分组

### ISSUE THREAD

**Issue by 2584191127** [gedoor/legado#2350]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望在搜索时能选择多个分组（不是全部）

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
![Screenshot_20220930_193801_io legado app release_edit_249830027574378](https://user-images.githubusercontent.com/78305714/193261921-980eaa6a-d626-4f70-8dc5-fb572f698e4e.jpg)

**Comment by EdisonYo** [comment]
你的意思是多选几个分组，而不是多选几个源吧。
