### ISSUE TITLE
[Feature Request] 希望本地与在线可以无缝切换

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2354]
切换之后书签封面简介那些周边设置保留，如果本地文件丢失就自动切换在线源，现在跨设备同步书架的本地那里基本没法用，因为本地文件没法同步，如果能添加一个本地文件就自动上传webview就好了，但是书架不能单独同步，这样又没法结合到一起

**Comment by Xwite** [comment]
#2335
