### ISSUE TITLE
为什么要使用jsoup？

### ISSUE THREAD

**Issue by kaich** [gedoor/legado#236]
有点疑惑，请问：

直接用js的css/xpath不是很方便么？ 是用js的有些情况太复杂还是有什么必要性啊？

**Comment by Antecer** [comment]
js效率太低
开 2020/06/09, 星期二 17:47:57, kai cheng <notifications@github.com> 写到:
有点疑惑，请问：
直接用js的css/xpath不是很方便么？ 是用js的有些情况太复杂还是有什么必要性啊？

**Comment by kaich** [comment]
感谢回复
