### ISSUE TITLE
Please add io.legado.app APK to last release

### ISSUE THREAD

**Issue by IzzySoft** [gedoor/legado#2360]
[3.22.100120](https://github.com/gedoor/legado/releases/tag/3.22.100120) now only contains the `io.legado.play.release` build as APK. Could you please attach the `io.legado.app.release` APK as well? Thanks!

**Comment by 821938089** [comment]
Already updated
see https://github.com/gedoor/legado/releases/tag/3.22.100210
The web link in the app repo is no longer available, now it is https://gedoor.github.io/

**Comment by IzzySoft** [comment]
@821938089 Thanks!! Update pulled fine, website link updated – both becomes effective on my end with the next sync around 6 pm UTC.

PS: if you want, I can send you the metadata (basically summary, description, icon, featureGraphic – the URLs are not included as they are in a separate configuration file) as set up here in [fastlane format](https://gitlab.com/-/snippets/1895688) either via PR or as attachment so you could maintain them directly (and even add `cn` as locale), just let me know.

**Comment by IzzySoft** [comment]
Well, the bot got a point there. Feel free to ping me if you want the fastlane data anytime, though :smile:
