### ISSUE TITLE
[BUG] 画面旋转后系统状态栏露出

### ISSUE THREAD

**Issue by dabinn** [gedoor/legado#2378]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
> Chrome

### 机型（如Redmi K30 Pro）
> HTC U11

### 安卓版本（如Android 7.1.1）
>
Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.072122

### 问题描述（简要描述发生的问题）
>
阅读介面设定"隐藏状态栏"的功能可正常使用
但每次手机旋转方向后，系统上方的状态栏会露出迭在阅读介面的状态栏上
都需要点选画面中间叫出选单，再关闭一次才能把系统状态栏隐藏
只是很小的问题不过久了还是觉得有些恼人

### 相关截图
>
![image](https://user-images.githubusercontent.com/21699064/194015561-861f6e15-d3ac-49bc-b6fe-897e29d88de6.png)

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/pull/2382 fixed
