### ISSUE TITLE
[BUG] hutool的HexUtil这个类一直报错

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2383]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>vivo Y3

### 安卓版本（如Android 7.1.1）
>Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
最新

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
使用HexUtil这个类一直报错，用同个包的其他类没问题

### 相关截图
>
![Screenshot_2022_1006_103820](https://user-images.githubusercontent.com/104120418/194202330-d7c56dd0-30cf-47ee-b4d2-87bf7edaa5ab.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
https://shuyuan.mgz6.cc/shuyuan/5dcd617c1f32c9e61618959111b142f5.json

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>
<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
不支持
安卓没有java.awt.Color这个类
看了一下那边的issue，hutool这个库在安卓下使用是有一些兼容性问题的
