### ISSUE TITLE
[Feature Request] 朗读分割优化

### ISSUE THREAD

**Issue by ythong** [gedoor/legado#2384]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 现在的朗读是按照每段朗读的。有时段落较长，已经朗读到后面，但翻页还迟迟不翻。按页朗读又会出现页间不必要的停顿。

### 期望实现方式（阅读应该如何实现该功能）
> 希望能够自定义朗读分割字符。除了默认的回车，如句号、问号、感叹号、后引号（。？！”）等也可以作为分割符。这样可以最大限度保持朗读到哪里，翻页到哪里。方便读者观看朗读的文本。谢谢。

**Comment by gedoor** [comment]
不翻页是系统问题,或者tts问题,正常情况下会及时翻页的

**Comment by gedoor** [comment]
如果tts没问题,即使段落很长也会及时翻页

**Comment by ythong** [comment]
感谢作者及时回复。我把我的希望详细描述一下。
假设一个段落如下：
a。b。c。d。e。
共5个句子。其中a在当前页，b的一半在当前页，另一半在后一页，cde都在后一页。
下一个段落也在后一页：
f。g。h。
我希望当朗读到c句时，软件会翻到下一页。但目前我的现象是读到f句时才会翻到下一页。
请问您说的会及时翻页是读到c句翻页还是读到f句翻页。如果是c句翻页，那可能我的tts引擎出了问题。如果是f句翻页，这就不是我希望的状况了。
我的tts引擎是讯飞语记的。
再次感谢作者编写了这么好的软件。

**Comment by limne** [comment]
这个分割需要和提的每章完了停止有点关系，可以连续缓存几页的音频然后自动暂停，等音频缓存快被朗读完的时候再去缓存音频，这样可以节省流量，特别有些小说的大章实在太大。

但题主提的，既然是听小说，那干嘛还要盯着看呢？
