### ISSUE TITLE
[BUG] 书籍最后一页，页面反复闪烁

### ISSUE THREAD

**Issue by agsdxcze** [gedoor/legado#2387]
### 机型（如Redmi K30 Pro）
>google pixel 6a 

### 安卓版本（如Android 7.1.1）
>Android 13

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.100521

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>Wifi

### 问题描述（简要描述发生的问题）
>从前三版开始，看到最后每本小说最后一页，页面就会自动的开始闪烁，不停的在倒数第一和倒数第二页切换，无法停止。感觉页面在不停的排版。

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>每当进入大多数小说最后一页。

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by Xwite** [comment]
无法复现

**Comment by agsdxcze** [comment]
> 无法复现
> 
>     * 阅读界面布局
> 
>     * 阅读的本地文件或在线书籍对应的书源和链接
> 链接：http://www.31xiaoshuo.com/194/194911/
书源: {
  "bookSourceComment": "",
  "bookSourceGroup": "破冰",
  "bookSourceName": "31小说网",
  "bookSourceType": 0,
  "bookSourceUrl": "https://www.31xiaoshuo.com/",
  "bookUrlPattern": "https?://www\\.31xiaoshuo\\.com(/html)?/\\d+/\\d+/?",
  "customOrder": -240603,
  "enabled": true,
  "enabledCookieJar": false,
  "enabledExplore": true,
  "enabledReview": false,
  "exploreUrl": "[{\"title\":\"奇魔玄幻\",\"url\":\"https://m.31xiaoshuo.com/list/1/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"仙侠修真\",\"url\":\"https://m.31xiaoshuo.com/list/2/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"都市现代\",\"url\":\"https://m.31xiaoshuo.com/list/3/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"军史穿越\",\"url\":\"https://m.31xiaoshuo.com/list/4/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"竞技网游\",\"url\":\"https://m.31xiaoshuo.com/list/5/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"恐怖科幻\",\"url\":\"https://m.31xiaoshuo.com/list/6/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"同人次元\",\"url\":\"https://m.31xiaoshuo.com/list/7/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"综合言情\",\"url\":\"https://m.31xiaoshuo.com/list/8/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"浪漫青春\",\"url\":\"https://m.31xiaoshuo.com/list/9/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"现代言情\",\"url\":\"https://m.31xiaoshuo.com/list/10/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"古代言情\",\"url\":\"https://m.31xiaoshuo.com/list/11/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"幻想言情\",\"url\":\"https://m.31xiaoshuo.com/list/12/\",\"style\":{\"layout_flexGrow\":0.25,\"layout_flexBasisPercent\":-1}},{\"title\":\"完本小说\",\"url\":\"https://m.31xiaoshuo.com/qb/\",\"style\":{\"layout_flexGrow\":0,\"layout_flexBasisPercent\":0.29}}]",
  "lastUpdateTime": 1657122363913,
  "loginUrl": "",
  "respondTime": 3108,
  "ruleBookInfo": {
    "author": "id.info@tag.p.0@text##作 者：",
    "coverUrl": "id.fmimg@tag.img@src",
    "init": "",
    "intro": "id.intro@text",
    "kind": "[property=og:novel:update_time]@content&&\n[property=og:novel:category]@content&&\n[property=og:novel:status]@content",
    "lastChapter": "id.info@tag.p.3@tag.a@text##最 新：|免费章节 |正文卷 |正文 |VIP章节 ",
    "name": "id.info@tag.h1@text",
    "tocUrl": ""
  },
  "ruleContent": {
    "content": "id.content@html##加入书签|\\\\咪.*|多源小说APP.*|永久保存书架.*|本站手机APP.*|.*咪.*咪*阅.*读.*|（未完待续）|www.*com|siluke.com",
    "imageStyle": "0"
  },
  "ruleExplore": {
    "author": "class.author@text",
    "bookList": "class.hot_sale",
    "bookUrl": "tag.a.0@href@js:'https://www.31xiaoshuo.com'+result",
    "coverUrl": "img@src",
    "intro": "class.review@text",
    "lastChapter": "",
    "name": "class.title@text",
    "wordCount": ""
  },
  "ruleReview": {},
  "ruleSearch": {
    "author": "tag.td.3@text",
    "bookList": "id.bookcase_list@tag.tr",
    "bookUrl": "tag.td.1@tag.a@href",
    "coverUrl": "tag.td.1@tag.a@href<js>\nvar id = result.match(/(\\d+)\\/?$/)[1];\nvar iid = parseInt(id/1000);\n'https://img31xsorg.cdn.bcebos.com/'+iid+'/'+id+'/'+id+'s.jpg';\n</js>",
    "intro": "",
    "kind": "tag.td.0@text&&\ntag.td.4@text",
    "lastChapter": "tag.td.2@tag.a@text##免费章节 |正文卷 |正文 |VIP章节 ",
    "name": "tag.td.1@tag.a@text"
  },
  "ruleToc": {
    "chapterList": "id.list@tag.dl@tag.dd",
    "chapterName": "tag.a@text##_",
    "chapterUrl": "tag.a@href"
  },
  "searchUrl": "https://www.31xiaoshuo.com/search.php?keyword={{key}}",
  "weight": 0
}

>     * 视频（可选）


https://user-images.githubusercontent.com/60458544/194684397-1d23ccc0-a788-40be-9d58-a37bae6c8e67.mp4

**Comment by Xwite** [comment]
我这边不行

**Comment by agsdxcze** [comment]
是9月20多号一次更新后出现的问题。几乎每一本书看到最后一页都会有相同的闪烁。有的时候多按几次翻页就会停住。
在很多情况下，最后一页出现的内容已经在倒数第2页出现过了。感觉页面好像重新排版了。

这是倒数第2页。
![image](https://user-images.githubusercontent.com/60458544/194685421-be1d8322-e693-44f3-94f7-2a0920d66145.png)
这是倒数第一页。
![image](https://user-images.githubusercontent.com/60458544/194685479-d4a988ff-9fe2-4031-84e5-7fabc61e20f3.png)
这是开始闪烁后的倒数第2页。
![image](https://user-images.githubusercontent.com/60458544/194685492-03274e88-d64b-43d2-b43e-a4e2156c7172.png)
这是开始闪烁后的倒数第一页。
![image](https://user-images.githubusercontent.com/60458544/194685503-e044d2aa-afc1-4ed5-86d7-48e3f387fe76.png)

可以看见。开始闪烁后的第2页和没有闪烁前的排版不一样了。我想这可能是导致闪烁的原因。

**Comment by gedoor** [comment]
我看看9月20号更新了啥,还真没遇到过这种情况

**Comment by agsdxcze** [comment]
一开始以为这个现象很快就会修复，所以就没有管。结果接下来更新了几次，都是同样的情况。

**Comment by agsdxcze** [comment]
更新到3.22.101619后没有问题了。
