### ISSUE TITLE
部分使用ajax的书源网站无法正确读取内容

### ISSUE THREAD

**Issue by darkflame0** [gedoor/legado#239]
比如这个书源
http://ku.mumuceo.com/yuedu/detail/index/id/2856.html

它的目录（除第一卷）是页面加载完成后再通过API读取数据再重新渲染的，导致软件无法正确获取目录

像这种情况有没有解决的办法呢？

**Comment by gedoor** [comment]
可以用webView, js, js返回内容不为空时表示成功
