### ISSUE TITLE
[Feature Request] 优化恢复备份时的本地书籍路径覆盖

### ISSUE THREAD

**Issue by fwzuw** [gedoor/legado#2396]
### 功能描述（请清晰的、详细的描述你想要的功能）
我之前一直是在 pc 上用安卓模拟器挂着阅读再用电脑浏览器进行 web 端阅读，本地书籍路径在模拟器上和我的手机上是一致的，但最近升级 win11 后换成了 WSA，这玩意是安卓12，和我手机的路径没法做到一样了，如果我备份一端数据恢复到另一端，本地书籍的路径也会被更改为那一端的导致找不到书籍，我尝试过使用 WebDav 书籍优化这一点，但并没有改善，只是会在找不到书籍后重新下载一遍，如果再备份恢复一遍就又要下载一遍……

### 期望实现方式（阅读应该如何实现该功能）
- [ ] 可以通过 恢复忽略列表 来不覆盖本地书源路径，反正找不到后还能自动从 WebDav 下载，下一次后也就没问题了
- [x] 不以绝对路径而用相对路径读取本地书源，书籍保存位置 这个设置是不会被覆盖的，可以将所有本地书籍都放在这个文件夹中读取
- [ ] 单独为 WebDav 书籍做相对路径读取，本地书籍则在找不到路径时让用户选择使用 WebDav 下载或手动重设路径，该路径设置不会在恢复备份时被覆盖

**Comment by Xwite** [comment]
测试用 https://github.com/gedoor/legado/actions/runs/3213741330
