### ISSUE TITLE
app抓取内容和书源不一致

### ISSUE THREAD

**Issue by sabermelancholy** [gedoor/legado#240]
阅读3.0中抓取的内容在出现特定词汇的时候会变为其他内容如：大众-福斯 賓士-奔驰 富豪-沃尔沃 等 使用替换净化冶无法替换
 

![InkedScreenshot_20200613-135946_LI](https://user-images.githubusercontent.com/45264304/84561413-b6a56a80-ad7e-11ea-985c-4abfe3845aad.jpg)
![InkedScreenshot_20200528-142114_LI](https://user-images.githubusercontent.com/45264304/84561414-b86f2e00-ad7e-11ea-976c-288a7e314b92.jpg)
![InkedScreenshot_20200528-142217_LI](https://user-images.githubusercontent.com/45264304/84561416-ba38f180-ad7e-11ea-9f14-91c57c650aca.jpg)
![Screenshot_20200528-142153](https://user-images.githubusercontent.com/45264304/84561419-bc02b500-ad7e-11ea-9d62-d943063b3d2c.jpg)
![InkedScreenshot_20200613-134630_LI](https://user-images.githubusercontent.com/45264304/84561420-bc9b4b80-ad7e-11ea-83c5-5cc452f5a4fe.jpg)
![InkedScreenshot_20200613-134701_LI](https://user-images.githubusercontent.com/45264304/84561421-bdcc7880-ad7e-11ea-9312-475795f3bc3a.jpg)
![InkedScreenshot_20200605-175309_LI](https://user-images.githubusercontent.com/45264304/84561423-c02ed280-ad7e-11ea-88ff-8dcda797f501.jpg)

**Comment by gedoor** [comment]
是不是简繁转换的问题

**Comment by sabermelancholy** [comment]
> 是不是简繁转换的问题

还真是

**Comment by nukemiko** [comment]
估计是简繁转换的问题，之前因为开了繁转简，导致“酆都”（原文如此）被替换为“丰都”
