### ISSUE TITLE
书籍详情页顶栏不沉浸了

### ISSUE THREAD

**Issue by zmn001125** [gedoor/legado#2400]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.100921

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>书籍详情页顶栏不沉浸了

### 相关截图
>![Screenshot_2022-10-09-22-32-06-684-edit_io.legado.app.release.jpg](https://user-images.githubusercontent.com/52020688/194762650-538c63e5-43b1-45d1-aa37-4c32bf22a616.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by Xwite** [comment]
ref
https://github.com/gedoor/legado/commit/98b7362377304b8d92f3623f62ae7e38d0de61e7

https://github.com/gedoor/legado/commit/1f44aded5fe51d987e79b9cf68b3a6bd74bfbe62

**Comment by gedoor** [comment]
![d945aadc9c0385feb6dcba33279c6dc](https://user-images.githubusercontent.com/22701807/194792693-9585ae94-7747-4b01-bda2-0ed2a0e7a64b.jpg)
我这边是沉浸的啊,你手机安卓版本是什么?

**Comment by Xwite** [comment]
他说是`透明`



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月10日(星期一) 上午10:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] 书籍详情页顶栏不沉浸了 (Issue #2400)




 

 我这边是沉浸的啊,你手机安卓版本是什么?

**Comment by gedoor** [comment]
我加深了一点颜色防止背景太白文字看不清

**Comment by gedoor** [comment]
不过看那个截图是变成完全不透明了

**Comment by zmn001125** [comment]
> 我加深了一点颜色防止背景太白文字看不清

原来如此，不过现在看起来有种割裂的感觉😂

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/commit/d8e96ce1432780bf04960f321caf08f2becf193b
