### ISSUE TITLE
增加个撤销功能[Feature Request] 

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#2401]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 其实阅读进度跳转和全文搜索，这些功能其实一般都是临时用一下，回顾一下原来的剧情，提前看一下事件结局什么的，添加书签再跳转有点没必要，不添加想跳转回去还很难，如果可以一步步撤销回初始状态就好了

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Xwite** [comment]
阅读进度跳转 没反应
