### ISSUE TITLE
[Feature Request] 能增加对安卓低版本的支持吗？比如4.4

### ISSUE THREAD

**Issue by jjss520** [gedoor/legado#2407]
安卓4.4不能安卓，难受呀

**Comment by limne** [comment]
太旧的版本了

**Comment by jjss520** [comment]
> 太旧的版本了

kindle刷的安卓，只有4.4的版本，没办法。2.0可以安装，但没有webdav书架，书源也不多。

**Comment by qianfanguojin** [comment]
要适配低版本，需要更改SDK，工作量可能比较大.

**Comment by jjss520** [comment]
> 要适配低版本，需要更改SDK，工作量可能比较大.

用习惯了阅读，用其它app还真不习惯

**Comment by Yuangudashen** [comment]
估计是有些电纸书的安卓系统是4.4的，所以装不到电纸书上
