### ISSUE TITLE
[BUG] web阅读后同步到app又有问题了

### ISSUE THREAD

**Issue by easythd** [gedoor/legado#2413]
app版本：
3.22.100921

现象：
web阅读时，如果app是关闭退出状态或是停留在书架目录页，那web阅读的章节进度是正常同步到app中。
但如果web阅读时，手机app上是处于阅读内容页面，比如我在手机app上正在阅读100章的内容，接着换到web上阅读，而此时手机上app没有关闭也没有返回书架页，还是保留在100章内容阅读界面就切换到了桌面。那么，当web上阅读到了111章，回头到了手机切换到阅读app上，app还是在100章的内容阅读界面，这时再返回到书架也还是100章，再重新进去也是100章，不会到111章。

请叫我web同步bug发现小能手~~~

**Comment by Xwite** [comment]
这是web，app共用一个数据库字段保存进度导致的，最后使用的进度会覆盖之前的。

考虑新建另一个字段，可解决类似冲突的bug

**Comment by easythd** [comment]
谢谢。
下次解决这问题后，再反复测试下。

**Comment by 821938089** [comment]
你先退出到书架再去web那里接着看不就没问题了吗
