### ISSUE TITLE
[BUG] 使用tts-server朗读一章会停止很久

### ISSUE THREAD

**Issue by limne** [gedoor/legado#2415]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>
安卓13

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
最新

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信

### 问题描述（简要描述发生的问题）
>
使用tts-server朗读小说时，一章完了，下一章需要很久才有反应，大部分情况需要手工暂停再播放，根据tts-server日志来看是阅读app会连续缓存一章的音频，然后停下，下一章开始就要很久，与tts-server的作者反馈还没有发现问题，我猜测应该和网络有关，也可能是阅读app缓存完一章音频到下章获取音频之间时间太长，导致与tts-server连接断开或者是tts-server空闲太久服务出问题了，建议阅读app使用tts url这种方式获取音频可以设置预取页数和剩余缓存多少页再预取音频，这样以来就不至于与tts-server之间连接空闲太久，也不会大章缓存太多音频，比如《剑来》有的大章有60多页，全缓存完需要播放差不多40多分钟，如果听一部分，不听了，缓存也没了，下次还得再缓存，并且访问微软tts网络延迟比较高也可以保持朗读连贯。

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
每章完了之后都会出现这个问题

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by limne** [comment]
tts-server本身没有通知栏，其他有关省电的设置我都检查过了，没有问题。

**Comment by 821938089** [comment]
那可能就是系统问题了，你保持亮屏用应该就没问题了

**Comment by limne** [comment]
加通知的app版本已经装上了，再看看，昨天把“完全允许后台”权限打开也可以，但老是提示可能耗电。

**Comment by limne** [comment]
周末使用来看，通知也不起作用，应该是系统对前台服务的限制导致的，目前打开“完全后台行为”权限可以正常使用，就是会提示耗电，耗电还好，就这样吧
