### ISSUE TITLE
[BUG] WEB看书在手机锁屏一段时间后可能无法加载新章节

### ISSUE THREAD

**Issue by star-o0O** [gedoor/legado#2417]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [√] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>106.0.5249.119

### 机型（如Redmi K30 Pro）
>小米12

### 安卓版本（如Android 7.1.1）
>Android 12/13

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.100921以及之前版本

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>手机端阅读开启WEB服务，阅读锁/不锁后台，省电策略设置智能/无限制，PC端使用chrome连接阅读，网络环境为同网段局域网。
PC端阅读一段时间后（手机自然/手动锁屏），PC端无法加载下一章节，此时可以正常打开导航页，书架显示已连接，但是小说一直显示正在获取内容，可以正常返回书架，书架显示已连接，重新打开小说时有小概率可以正常加载下一章。
解决办法是点亮（唤醒）手机，即可立即加载下一章。
感觉是因为系统后台限制，但是可以正常加载导航页，正常进入书架，好像又没有限制，比较奇怪

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by star-o0O** [comment]
> 打开Web服务有没有显示通知？

有，手机通知栏会常驻一个WEB服务的通知，直到关闭服务或软件

**Comment by gedoor** [comment]
ok

**Comment by gedoor** [comment]
以添加唤醒锁

**Comment by star-o0O** [comment]
101619版本试了一段时间，加载正常，看起来已经解决
