### ISSUE TITLE
[BUG] Web服务开启后会优先使用移动网络网址

### ISSUE THREAD

**Issue by 0arkest** [gedoor/legado#2418]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [x] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
> Chrome 106.0.5249.119

### 机型（如Redmi K30 Pro）
> 三星S20FE

### 安卓版本（如Android 7.1.1）
> Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.100921

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> Cricket美国移动网络，WIFI

### 问题描述（简要描述发生的问题）
> 不确定是不是bug。我只是单纯的想把电脑上的txt小说传到手机阅读app上面看，开了Web服务后电脑Chrome浏览器输入网址一直打不开，确认了是同一WIFI和正确的网址（没错是http而不是https），搞得我以为是阅读这功能有问题。后来我灵机一动，把5G移动网络关了，只开WIFI，再打开阅读Web服务后网址变了，变成192开头，电脑输入后终于可以打开页面开始传书了。我意识到移动网络和WIFI同时开启时阅读Web服务会优先使用移动网络的网址，而我电脑是用WIFI的，想要传书还得特意关闭移动网络，事后再开。感觉很麻烦，能不能改成有WIFI的情况下先使用WIFI网络的网址来传书？

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by gedoor** [comment]
这个我看看

**Comment by 0arkest** [comment]
最新版本还是老样子，打开Web服务会优先使用移动网络作为网址，我还得去手机设置里关闭5G才能用WIFI连接Web服务

**Comment by 821938089** [comment]
你可以直接用WiFi的IP地址连，不用管web服务上面显示的

**Comment by 0arkest** [comment]
> 你可以直接用WiFi的IP地址连，不用管web服务上面显示的

 试了下，真的可以！感谢！

**Comment by SogaSuga** [comment]
我最近也注意到这个问题。虽然直接用wifi的ip可以连，但是加载下一章至少要用10多秒。
关掉移动数据后再开启web服务，阅读能识别到wifi的ip地址，电脑连上以后加载下一章就很快。
我的手机是三星s23，Android13。阅读版本3.23.060622

**Comment by 821938089** [comment]
@SogaSuga 保持应用亮屏和前台，这个ip只是获取问题，不会影响到web服务
