### ISSUE TITLE
[BUG] epub有些文件打不开

### ISSUE THREAD

**Issue by yuhldr** [gedoor/legado#2419]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
> 小米10  miui13.07

### 安卓版本（如Android 7.1.1）
> 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.100521

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 都这样

### 问题描述（简要描述发生的问题）
> 打开有的epub文件，比如附件这个
[0051. 毛泽东选集(套装共4册).tar.gz](https://github.com/gedoor/legado/files/9772296/0051.4.tar.gz)
  ，提示 “LoadTocError:目录列表为空“，但是阿里云app打开没问题，电脑okluar打开也没问题
可能是这个文件有些问题，但是希望兼容，毕竟其他软件可以打开，可是只有阅读比较方便

### 相关截图
> ![Screenshot_2022-10-13-16-00-12-851_io legado app release](https://user-images.githubusercontent.com/25719023/195538848-1e37c25c-e926-4bbc-bdbe-34d6da2a6dba.jpg)

![Screenshot_2022-10-13-16-01-18-542_com alicloud databox](https://user-images.githubusercontent.com/25719023/195538956-4de3525d-7ab1-4511-9eb6-9a00e435e208.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 下载解压[0051. 毛泽东选集(套装共4册).tar.gz](https://github.com/gedoor/legado/files/9772296/0051.4.tar.gz)
，用阅读，打开这个epub文件，100%出现，而其他软件没问题

### 使用书源（填写URL或者JSON）
和这个无关，是本地书籍

<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

这里没东西，空白的，软件没闪退

<pre></code>
</details>

**Comment by yuhldr** [comment]
搜书大师也可以打开这个文件
![Screenshot_2022-10-13-16-39-43-301_com flyersoft seekbooks](https://user-images.githubusercontent.com/25719023/195547373-511a583f-94e0-4f17-87a1-3c025e24b8cb.jpg)

**Comment by 821938089** [comment]
不能复现
还有不可能没日志

**Comment by yuhldr** [comment]
如图，什么也没



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月13日(周四) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] [BUG] epub有些文件打不开 (Issue #2419)




 
不能复现
 还有不可能没日志

**Comment by yuhldr** [comment]
> 不能复现 还有不可能没日志

我删除书架这个文件以后，重新在阅读app里添加，又好了，

之前可能是因为，我在阿里云app里直接点，用其他软件打开，然后选择阅读app，阅读app书架里出现这个文件，导致的
