### ISSUE TITLE
订阅源功能优化建议

### ISSUE THREAD

**Issue by old-yellow-ox** [gedoor/legado#2429]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
1.订阅源删除没有确认提示，这几天在编辑时手快点错了，误删了好几次，希望能增加提示。
2.订阅源的分组不能只填写uri部分，必须填写完整的地址，操作上有些繁琐，希望能自动拼接源地址到host部分。
### 期望实现方式（阅读应该如何实现该功能）
> 
1.增加订阅源删除提示，删除时需要确认。
2.订阅源的分组如果是完整地址，则直接使用；否则自动拼接源地址到前面，就像书源那样。
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
ok

**Comment by old-yellow-ox** [comment]
谢谢
