### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zhj200015** [gedoor/legado#2432]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>荣耀v 9play

### 安卓版本（如Android 7.1.1）
>7.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.100921

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信

### 问题描述（简要描述发生的问题）
>
使用微软tts听书一段时间后会把软件卡死

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
使用微软tts锁屏一段时间会卡死软件

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
有没有日志

**Comment by zhj200015** [comment]
卡死后没有生成崩溃日志

**Comment by 821938089** [comment]
手机有没有root，看日志需要root进入到系统文件夹里

**Comment by zhj200015** [comment]
没有root
