### ISSUE TITLE
[BUG] java.aesDecodeArgsBase64Str()不能解密

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2433]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>vivo Y3

### 安卓版本（如Android 7.1.1）
>Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>最新

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>java.aesDecodeArgsBase64Str()解密报错

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>https://shuyuan.mgz6.cc/shuyuan/92dc66633353ca7fdc2b1b374105aec5.json

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
入参str不对，请使用java.aesBase64DecodeToString()。

另外，我看了这个Js扩展类的加解密，很多加解密函数在我看来都是没有意义的，我也不是很懂这个加解密函数为什么要这么写，建议你直接调用hutool或者java加解密类做加解密，我看了很多源都是这样干的，阅读内置的加解密函数问题很大，基本上是无法使用的。

**Comment by iyhkhtrk** [comment]
> 入参str不对，请使用java.aesBase64DecodeToString()。
> 
> 另外，我看了这个Js扩展类的加解密，很多加解密函数在我看来都是没有意义的，我也不是很懂这个加解密函数为什么要这么写，建议你直接调用hutool或者java加解密类做加解密，我看了很多源都是这样干的，阅读内置的加解密函数问题很大，基本上是无法使用的。

java.aesBase64DecodeToString()不支持base64过且base64解密后是乱码的key和iv,
如果java.aesDecodeArgsBase64Str()能用的话会比引用Java加密类和hutool方便很多

**Comment by Xwite** [comment]
#2434
