### ISSUE TITLE
[Feature Request] 移除和cn.hutool.crypto重复的封装函数

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#2434]
- [x] EncoderUtils
> cn.hutool.crypto.symmetric
- [x] JsExtensions
> 实现Base64|Hex|Utf8字符串的自动识别，移除带ArgBase64字段函数

**Comment by 821938089** [comment]
他想要方便调用的封装函数

**Comment by Xwite** [comment]
考虑实现<base64|hex|utf8>到bytes的自动转换
就可以移除那几个ArgBase64的函数了
