### ISSUE TITLE
[BUG] java.createSymmetricCrypto()的bug

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2438]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>最新

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>在DES加密的时候如果key的长度为8时会报错:Wrong key size,必须自己转bytes才行。

自动判断key和iv的bug:
有些key和iv要经过md5加密后才知道,自动判断会把md5加密后得出的key和iv当hex转bytes，有时候需要直接当utf8转bytes。

能不能在函数里加个key和iv的类型,例：java.createSymmetricCrypto(transformation,key,iv,key和iv的类型(Hex|Base64|Bytes))(默认为UTF8),按类型转bytes

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by iyhkhtrk** [comment]
> ### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
> * [ ]  Chrome/Edge/Firefox PC
> * [ ]  Chrome/Edge/Firefox/WebView Android
> * [ ]  其他浏览器，请补充
> 
> > 
> 
> ### 机型（如Redmi K30 Pro）
> > 
> 
> ### 安卓版本（如Android 7.1.1）
> > 
> 
> ### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> > 最新
> 
> ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > 
> 
> ### 问题描述（简要描述发生的问题）
> 在DES加密的时候如果key的长度为8时会报错:Wrong key size,必须自己转bytes才行。
> 
> 自动判断key和iv的bug: 有些key和iv要经过md5加密后才知道,自动判断会把md5加密后得出的key和iv当hex转bytes，有时候需要直接当utf8转bytes。
> 
> 能不能在函数里加个key和iv的类型,例：java.createSymmetricCrypto(transformation,key,iv,key和iv的类型(Hex|Base64|Bytes))(默认为UTF8),按类型转bytes
> 
> ### 相关截图
> > 
> 
> ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> > 
> 
> ### 使用书源（填写URL或者JSON）
> 点击展开
> ### 日志提交（我的-关于-崩溃日志，书架-右上角-日志）
> 点击展开

**Comment by 821938089** [comment]
你可以先base64编码一下再传进去，这样自动转换出错的可能性就比较低

**Comment by iyhkhtrk** [comment]
谢谢，解决了。不过自己填类型不是更方便？🤔🤔

**Comment by Xwite** [comment]
已经不自动，需要的手动java.decodeBase64Hex(str: String)
