### ISSUE TITLE
[BUG] 本地同名书籍添加会直接顶掉在线同名书

### ISSUE THREAD

**Issue by zealousfool** [gedoor/legado#2442]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.101619

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
如题，本地同名书籍添加会直接顶掉在线同名书，在线和本地同名书不能共存，之前在线看书的进度也一并丢失。但是我记得以前版本是可以共存的。

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
以前也是不可以的，能共存是因为书名一样但作者不一样

**Comment by zealousfool** [comment]
> 以前也是不可以的，能共存是因为书名一样但作者不一样

是这样吗，那是不是能加个不显示的本地键值把两个区别开呢。

**Comment by 821938089** [comment]
不行，这个是数据库的唯一键的限制，这个我不会搞，你给书改个不一样的作者名就可以了

**Comment by zealousfool** [comment]
> 不行，这个是数据库的唯一键的限制，这个我不会搞，你给书改个不一样的作者名就可以了

我觉得不如让本地书的来源只能是本地，变为不可选。

**Comment by zousizhe** [comment]
> 不行，这个是数据库的唯一键的限制，这个我不会搞，你给书改个不一样的作者名就可以了

那替换掉也行，能不能书签封面简介那些原来带的一些配置不换掉？

**Comment by 821938089** [comment]
@zousizhe 
书签和具体的书没有关系，封面可以自动获取。
