### ISSUE TITLE
[Feature Request] 最新测试版搜索范围勾选多分组菜单拉宽问题

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2451]
还是放回下面吧，这个菜单实在太不美观了，或者直接显示成多组两个字，但是要是谁的分组名字长一点的话，那也不好看
![Screenshot_2022-10-17-22-23-32-1936405904](https://user-images.githubusercontent.com/37259360/196203747-e0113574-2e43-411f-b467-cc7a6537cec1.png)

**Comment by gedoor** [comment]
改了,现在显示方式应该可以接收了
