### ISSUE TITLE
[BUG] 在缓存导出界面，就算什么也不做菜单也是掉帧

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2453]
在缓存导出界面，在没有进行缓存下载的时候，滑动与下拉操作掉帧非常严重

**Comment by 821938089** [comment]
更新已下载数据会比较卡，你等他更新完成就不卡了

**Comment by gedoor** [comment]
应该是长时间读取磁盘导致的,我看看有没有其它办法解决

**Comment by 821938089** [comment]
直接枚举每本书的缓存目录下的文件数量当成已下载数量可能会快很多

**Comment by gedoor** [comment]
> 直接枚举每本书的缓存目录下的文件数量当成已下载数量可能会快很多

Files.walkFileTree() 方向遍历文件有个新方法,网上说快很多
