### ISSUE TITLE
[Feature Request] 优化阅读界面设置的同步方案

### ISSUE THREAD

**Issue by fwzuw** [gedoor/legado#2456]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 假设一个用户有两台设备，白天用设备 A 看小说，晚上用设备 B 看小说。这两台设备的阅读界面布局不一样，因此在恢复忽略列表中勾选了这项，这样在两台设备互倒时不会受到影响。某天他不慎丢失了设备 A 上的数据，当他从 WebDav 恢复时发现阅读布局是设备 B 上的，这是因为虽然在白天阅读完后都会上传设备 A 的备份，但晚上就会被设备 B 的数据覆盖，因此他丢失了设备 A 的阅读界面数据。

我认为应该对这一逻辑进行修改，将阅读界面布局配置改为通用数据，并在恢复备份时保留选择的配置方案。例如在设备 A 上选择布局一，在设备 B 上选择布局二，当修改或添加了布局数据时也会被同步到其他设备上，而选择的布局方案不变，这样就能保证存下所有的布局方案并互不打扰。

### 期望实现方式（阅读应该如何实现该功能）
- 恢复备份时恢复全部的阅读界面样式，并恢复当前设备“选择了哪一个样式”的数据，其他设备“选择了哪一个样式”的数据也会储存但不应用，以使云端数据统一
- 恢复备份时恢复全部的阅读界面样式，“选择了哪个样式”的数据不参与备份与恢复，缺点是在某些情况下恢复后需要手动重选样式

### 附加信息（其他的与功能相关的附加信息）
可以整个默认的界面样式或支持样式排序又或着能设置默认样式，避免老用户新设备的初始样式选到一个十分独特的布局
 
另外，最低五个样式的设计有意义吗？我想给它减到两个
![image](https://user-images.githubusercontent.com/48246272/196500989-e53aa54e-f771-4df1-8a4f-e62078e5cb44.png)

**Comment by gedoor** [comment]
我想想
