### ISSUE TITLE
[Feature Request] 希望小说内搜索列表能自动定位到当前章的位置

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2458]
小说内的文本查找功能，列表结果中当前章节虽然是粗体显示，但是进度条却是从第一个开始，要定位到当前都要找半天，大多数时候操作需求都是从当前的进度向后搜索，所以希望搜索列表能快速的从当前章节开始查看结果，而不是从顶部位置显示

**Comment by kaveys** [comment]
不是吧？我没回打开目录都是自动定位啊
