### ISSUE TITLE
[Feature Request] 单章换源匹配度

### ISSUE THREAD

**Issue by kaveys** [gedoor/legado#2461]
![Screenshot_2022-10-20-20-29-33-651_com tugoubutu liulanqi](https://user-images.githubusercontent.com/104361379/196948925-e26e7b2c-745a-4dbd-b1cf-73f7efe80592.jpg)
帖子来源:https://5yd.cc/thread-1364.htm

**Comment by kaveys** [comment]
行吧，如果能加的话尽量加，建议可以加个开关（默认关闭）

**Comment by EdisonYo** [comment]
不说资源耗费和实现的问题，没有正确的参照物，怎么判断正确度，匹配度没什么意义，防盗章节有只有几个字的，有乱更新其它书的内容，有乱更新本书之前章节的，就目前我看到的自动化优选源的设想里，没有一个是能完全适配到刚才说的所有场景，要找靠谱的新章节，目前只能靠耐心。如果非要自动化，只能跨域，先要在正版源准确定位到当前章节取开头，再以一些内容+字数匹配，这是个大工程，在不规范的情况下，甚至标题里的标点符号都会影响判断。

**Comment by SJJ-dot** [comment]
想法不错，回头加到我的APP里面😏🌝
