### ISSUE TITLE
在读书的内容界面加入添加净化的快捷操作

### ISSUE THREAD

**Issue by fifthmail** [gedoor/legado#2464]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在读书的页面加入添加净化的快捷操作，在看书的时候要添加净化挺麻烦的

### 期望实现方式（阅读应该如何实现该功能）
> 在读书的内容界面，在编辑菜单里加入添加净化的操作

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gyz1023** [comment]
![Screenshot_2022-10-21-09-14-21-216-edit_io legado app release](https://user-images.githubusercontent.com/106790230/197088446-3994a95b-40fa-43a7-ae04-812d11c48f0a.jpg)
不是有吗？

**Comment by fifthmail** [comment]
能不能直接把功能加内容编辑页面的长按菜单里

**Comment by 821938089** [comment]
长按菜单里有一个替换功能

**Comment by fifthmail** [comment]
太感谢了，长按菜单被我禁用掉了，现在找到了
