### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by XiangLong6** [gedoor/legado#2466]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [x] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>Redmi K30 Pro

### 安卓版本（如Android 7.1.1）
>11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.102020

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>听书~从选择的地方朗读~
我听书用的讯飞，系统TTS是小爱
之前可以正常从选择地方唤起讯飞开始朗读，现在更新后会唤起系统TTS朗读完选中的那几个字就结束了

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>任意小说长按选中几个字再点朗读

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
https://github.com/gedoor/legado/releases/tag/3.22.100210
看一下更新日志第二条

**Comment by XiangLong6** [comment]
啊，了解了，一次更太多版本没注意下面的，谢谢大佬给添麻烦了(◕ˇ∀ˇ◕)
