### ISSUE TITLE
[Feature Request] 章节名称和分卷名称能否分开？

### ISSUE THREAD

**Issue by NONONO1V** [gedoor/legado#2475]
如题
举个例子
ChapterName
——————————————————
VolumeName
——————————————————

**Comment by zanewayne78** [comment]
这个可以有，这样写分卷就不会用js处理，老实说js好难写只能用大佬写的改改而已

**Comment by NONONO1V** [comment]
> 现在卷名好像是在目录列表里获取。 但有些网站的章节和卷用了不同的class。 当我匹配章节的时候，卷似乎就无法匹配了。
是的，目录列表规则以下的规则，现在都只能获取目录列表规则范围内的

**Comment by NONONO1V** [comment]
> 现在卷名好像是在目录列表里获取。 但有些网站的章节和卷用了不同的class。 当我匹配章节的时候，卷似乎就无法匹配了。 https://www.wenku8.net/novel/2/2896/index.htm 比如这个 我章节列表匹配class.ccss@a的时候。 就没法用class.vcss@text匹配卷名了。 老实说，蛮难用的。

是的，目录列表规则以下的规则，现在都只能获取目录列表规则范围内的

**Comment by 821938089** [comment]
卷名处理在我看来是非常麻烦的，没有什么比较通用的处理方案，只能写js来做特定处理。
如果你有通用的方案也可以说一下。

**Comment by 821938089** [comment]
@daiaji 
这种情况章节列表规则写.css td就可以都获取到了

**Comment by daiaji** [comment]
那样章节计数不是会把卷也计入吗？

**Comment by 821938089** [comment]
好像是会的
只是多几章而已，影响不是很大，单独出来处理不如在一起方便

**Comment by daiaji** [comment]
就是感觉到丑陋。

**Comment by NONONO1V** [comment]
目录的规则要是自定义的范围能更多一点就好了

**Comment by daiaji** [comment]
确实

**Comment by 821938089** [comment]
我记得目录列表规则是可以用正则的，我想了一下，应该是可以满足大多数情况下的卷名处理了
如果不会写正则那就没办法了

**Comment by NONONO1V** [comment]
> 我记得目录列表规则是可以用正则的，我想了一下，应该是可以满足大多数情况下的卷名处理了 如果不会写正则那就没办法了

那起点的分卷是否能用正则写呢？
https://book.qidian.com/info/1010868264/#Catalog
这个对我来说很困难

**Comment by 821938089** [comment]
列表规则：`:<h3>  <a.*?</a>  (.*?)<i>&#183;</i>共.*?章<span class=.*?>.*?</span> </h3>|<h2 class=\"book_name\"><a href=\"(.*?)\" .*?\">(.*?)</a></h2>`
章节名称：`$1$3`
章节URL：`$2`
卷名标识：`$1`

这个起点的源已经有很多大佬做过了吧，有一些有分卷规则的，建议你就不要做了，这个目录有反爬，我搞了半天才获取到数据。
这个规则你就自己参考一下吧。

**Comment by 821938089** [comment]
我研究了一下，用jsoup语法也能做，而且应该也能满足大多数情况下的卷名处理，这个问题可以终结了。

列表规则：`#j-catalogWrap@h3, h2`
章节名称：`h3, h2@text`
章节地址：`h2 a@href`
卷名标识：`h3@text`

**Comment by NONONO1V** [comment]
> 我研究了一下，用jsoup语法也能做，而且应该也能满足大多数情况下的卷名处理，这个问题可以终结了。
> 
> 
> 
> 列表规则：`#j-catalogWrap@h3, h2`
> 
> 章节名称：`h3, h2@text`
> 
> 章节地址：`h2 a@href`
> 
> 卷名标识：`h3@text`

谢谢！jsoup简单易懂
