### ISSUE TITLE
[Feature Request] 抽离 WebBook、LocalBook 等逻辑

### ISSUE THREAD

**Issue by hectorqin** [gedoor/legado#2476]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 将 App 的 WebBook、LocalBook 等逻辑抽离出来，方便跨平台使用

### 期望实现方式（阅读应该如何实现该功能）
> https://github.com/hectorqin/reader-legado 我这边做了一个简单的版本，希望能一起完善这个仓库。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by dianso** [comment]
说白了还不是想白嫖开源代码，把阅读核心继续开源，其他私货不开源
