### ISSUE TITLE
订阅源列表，数据追加和重复请求问题

### ISSUE THREAD

**Issue by old-yellow-ox** [gedoor/legado#2479]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
1.数据追加方式不正确。
2.请求次数不正确。

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
1.待列表加载出数据后，上拉获取下一页数据（下拉多页也可以），此时数据从上到下顺序为page1、page2...；然后划到顶部，下拉刷新数据，此时会出现问题，数据列表变成了...page3、page2、page1的倒序方式。并且此时上拉也无法请求下一页数据了。
2.数据列表只有几条，但是加载了十几条数据，监测接口调用情况发现，同一个分类在未手动刷新的情况下自动请求了多页。数据量少的时候会自动请求下一页?

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>
{
    "articleStyle": 0,
    "customOrder": 6,
    "enableJs": true,
    "enabled": true,
    "enabledCookieJar": false,
    "header": "{\n    Cookie:\"uid=000000\"\n}",
    "lastUpdateTime": 1666660446155,
    "loadWithBaseUrl": true,
    "ruleArticles": "$.data",
    "ruleContent": "<js>\nvar json=JSON.parse(result).data;\n\n\"<style>body{padding:10px;line-height:2em;letter-spacing: 2px;background:floralwhite;font-family:sans-serif-Helvetica;word-wrap: break-word}</style>\"+json.map((x,i)=>\"<center><h4>No.\"+(i+1)+\"</h4><img src='\"+x.bookIcn+\"' width='130px' height='180px' ></center>\"+\"<p>书名:\"+x.bookName+\"</p><p>作者:\"+x.bookAuthor+\"</p><p>简介:\"+x.bookAppraise+\"</p><p>创建时间:\"+x.createTime+\"</p><p>更新时间:\"+x.updateTime+\"</p><p>*********************************</p>\").join(\"\\n\")\n</js>",
    "ruleImage": "$.headUrl",
    "ruleLink": "http://api.moonreader.cn/mreader/discuss/queryBookListInfo.do?listId={{$.listId}}",
    "ruleNextPage": "page",
    "rulePubDate": "updateTime",
    "ruleTitle": "listName",
    "singleUrl": false,
    "sourceComment": "实际条数和最大条数不一致",
    "sourceGroup": "书单",
    "sourceIcon": "https://android-artworks.25pp.com/fs08/2019/11/15/7/106_4213117808d53ee3721efc0fdf294589_con.png",
    "sourceName": "搜书大师书单",
    "sourceUrl": "http://api.moonreader.cn/mreader/discuss/queryBookLists.do?skip={{(page-1)*20}}&maxCount=5&sortType=1"
}

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
发一下订阅源

**Comment by old-yellow-ox** [comment]
{
    "articleStyle": 0,
    "customOrder": 6,
    "enableJs": true,
    "enabled": true,
    "enabledCookieJar": false,
    "header": "{\n    Cookie:\"uid=000000\"\n}",
    "lastUpdateTime": 1666660304075,
    "loadWithBaseUrl": true,
    "ruleArticles": "$.data",
    "ruleContent": "<js>\nvar json=JSON.parse(result).data;\n\n\"<style>body{padding:10px;line-height:2em;letter-spacing: 2px;background:floralwhite;font-family:sans-serif-Helvetica;word-wrap: break-word}</style>\"+json.map((x,i)=>\"<center><h4>No.\"+(i+1)+\"</h4><img src='\"+x.bookIcn+\"' width='130px' height='180px' ></center>\"+\"<p>书名:\"+x.bookName+\"</p><p>作者:\"+x.bookAuthor+\"</p><p>简介:\"+x.bookAppraise+\"</p><p>创建时间:\"+x.createTime+\"</p><p>更新时间:\"+x.updateTime+\"</p><p>*********************************</p>\").join(\"\\n\")\n</js>",
    "ruleImage": "$.headUrl",
    "ruleLink": "http://api.moonreader.cn/mreader/discuss/queryBookListInfo.do?listId={{$.listId}}",
    "ruleNextPage": "page",
    "rulePubDate": "updateTime",
    "ruleTitle": "listName",
    "singleUrl": false,
    "sourceComment": "实际条数和最大条数不一致",
    "sourceGroup": "书单",
    "sourceIcon": "https://android-artworks.25pp.com/fs08/2019/11/15/7/106_4213117808d53ee3721efc0fdf294589_con.png",
    "sourceName": "搜书大师书单",
    "sourceUrl": "http://api.moonreader.cn/mreader/discuss/queryBookLists.do?skip={{(page-1)*20}}&maxCount=5&sortType=1"
}

**Comment by old-yellow-ox** [comment]
{
    "articleStyle": 0,
    "customOrder": 6,
    "enableJs": true,
    "enabled": true,
    "enabledCookieJar": false,
    "header": "{\n    Cookie:\"uid=000000\"\n}",
    "lastUpdateTime": 1666660446155,
    "loadWithBaseUrl": true,
    "ruleArticles": "$.data",
    "ruleContent": "<js>\nvar json=JSON.parse(result).data;\n\n\"<style>body{padding:10px;line-height:2em;letter-spacing: 2px;background:floralwhite;font-family:sans-serif-Helvetica;word-wrap: break-word}</style>\"+json.map((x,i)=>\"<center><h4>No.\"+(i+1)+\"</h4><img src='\"+x.bookIcn+\"' width='130px' height='180px' ></center>\"+\"<p>书名:\"+x.bookName+\"</p><p>作者:\"+x.bookAuthor+\"</p><p>简介:\"+x.bookAppraise+\"</p><p>创建时间:\"+x.createTime+\"</p><p>更新时间:\"+x.updateTime+\"</p><p>*********************************</p>\").join(\"\\n\")\n</js>",
    "ruleImage": "$.headUrl",
    "ruleLink": "http://api.moonreader.cn/mreader/discuss/queryBookListInfo.do?listId={{$.listId}}",
    "ruleNextPage": "page",
    "rulePubDate": "updateTime",
    "ruleTitle": "listName",
    "singleUrl": false,
    "sourceComment": "实际条数和最大条数不一致",
    "sourceGroup": "书单",
    "sourceIcon": "https://android-artworks.25pp.com/fs08/2019/11/15/7/106_4213117808d53ee3721efc0fdf294589_con.png",
    "sourceName": "搜书大师书单",
    "sourceUrl": "http://api.moonreader.cn/mreader/discuss/queryBookLists.do?skip={{(page-1)*20}}&maxCount=5&sortType=1"
}

**Comment by old-yellow-ox** [comment]
`{
    "articleStyle": 0,
    "customOrder": 6,
    "enableJs": true,
    "enabled": true,
    "enabledCookieJar": false,
    "header": "{\n    Cookie:\"uid=000000\"\n}",
    "lastUpdateTime": 1666660688067,
    "loadWithBaseUrl": true,
    "ruleArticles": "$.data",
    "ruleContent": "<js>\nvar json=JSON.parse(result).data;\n\n\"<style>body{padding:10px;line-height:2em;letter-spacing: 2px;background:floralwhite;font-family:sans-serif-Helvetica;word-wrap: break-word}</style>\"+json.map((x,i)=>\"<center><h4>No.\"+(i+1)+\"</h4><img src='\"+x.bookIcn+\"' width='130px' height='180px' ></center>\"+\"<p>书名:\"+x.bookName+\"</p><p>作者:\"+x.bookAuthor+\"</p><p>简介:\"+x.bookAppraise+\"</p><p>创建时间:\"+x.createTime+\"</p><p>更新时间:\"+x.updateTime+\"</p><p>*********************************</p>\").join(\"\\n\")\n</js>",
    "ruleImage": "$.headUrl",
    "ruleLink": "http://api.moonreader.cn/mreader/discuss/queryBookListInfo.do?listId={{$.listId}}",
    "ruleNextPage": "page",
    "rulePubDate": "updateTime",
    "ruleTitle": "listName",
    "singleUrl": false,
    "sourceComment": "实际条数和最大条数不一致",
    "sourceGroup": "书单",
    "sourceIcon": "https://android-artworks.25pp.com/fs08/2019/11/15/7/106_4213117808d53ee3721efc0fdf294589_con.png",
    "sourceName": "搜书大师书单",
    "sourceUrl": "http://api.moonreader.cn/mreader/discuss/queryBookLists.do?skip={{(page-1)*20}}&maxCount=5&sortType=1"
}`

**Comment by old-yellow-ox** [comment]
已解决
