### ISSUE TITLE
[BUG] web阅读js页面报错问题

### ISSUE THREAD

**Issue by easythd** [gedoor/legado#2485]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
Chrome PC 版本 106.0.5249.119 (正式版本) (64 位)

>

### 机型（如Redmi K30 Pro）
>
手机 三星 S20FE

### 安卓版本（如Android 7.1.1）
>
android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.22.102223

### 问题描述（简要描述发生的问题）
>
使用web阅读，页面上会有Uncaught pagejs missing的js报错，导致后续js执行有问题。以前的阅读版本没有这个问题，就最近的这一两个版本开始出现这个问题。反复刷新10-20次，会有1-2次不出现这个报错。
我发现这个的原因是我的chrome浏览器上有文字加阴影渲染的插件，以前阅读web时都会自动字体加阴影加粗，突然这几天就不会自动加了，而且只有阅读web界面这一个网页不会，其它网页还是正常会，开F12研究了半天发现是这个错误导致的，而且更奇怪的是反复刷新多次会有一两次不报错。

### 相关截图
>
![捕获](https://user-images.githubusercontent.com/70197314/197702987-64d2f389-1dfd-48c7-a27d-772fb46b4b83.PNG)

**Comment by 821938089** [comment]
浏览器问题
尝试禁用扩展->重启浏览器->启用扩展->重启浏览器

**Comment by easythd** [comment]
> 浏览器问题 尝试禁用扩展->重启浏览器->启用扩展->重启浏览器

试了没用。而且你没看到我描述的，只且只有阅读web页面有这个问题，其它网站页面这个扩展工作得好好的。最近这个2个阅读的版本之前也是正常的，就这2个版本不正常。我天天用阅读web版本，很清楚这个变化。

**Comment by 821938089** [comment]
那就重装扩展，或者想办法降级扩展
我查了这个错误是属于浏览器/扩展的问题

**Comment by easythd** [comment]
> 那就重装扩展，或者想办法降级扩展 我查了这个错误是属于浏览器/扩展的问题 你换violentmonkey应该也能解决这个问题

好的，我按你说的试试。谢谢

**Comment by easythd** [comment]
> 那就重装扩展，或者想办法降级扩展 我查了这个错误是属于浏览器/扩展的问题 你换violentmonkey应该也能解决这个问题

换成暴力猴后没有这个问题了。
看来是用了什么新的功能和油猴有冲突？

**Comment by 821938089** [comment]
这个问题与阅读无关，最近两个版本的web书架除了更新了一个依赖之外，完全没有任何代码的修改。
是浏览器/扩展的问题，你可以去油猴的issues上看，有人发了这个问题
![image](https://user-images.githubusercontent.com/8674809/197749529-1548b569-d734-4fc5-ad2a-a4a6a1ac8d08.png)

**Comment by easythd** [comment]
> 这个问题与阅读无关，最近两个版本的web书架除了更新了一个依赖之外，完全没有任何代码的修改。 是浏览器/扩展的问题，你可以去油猴的issues上看，有人发了这个问题 

非常感谢细心耐心指导！！！
