### ISSUE TITLE
能否支持方向键翻页

### ISSUE THREAD

**Issue by huhd** [gedoor/legado#249]
蓝牙翻页器的左右键没响应。

**Comment by gedoor** [comment]
可以自定义翻页按键

**Comment by huhd** [comment]
那能否把左右方向键设为默认的翻页按键，应该大多数人习惯这种方式。
我的设备sony dpt-rp1不能在书页情况下打开页面设置（可能是没有登陆用户账号），所以自定义按键会比较麻烦，有个默认的会方便不少。
