### ISSUE TITLE
[BUG] 朗读定时功能生效一次后不会重置

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2490]
调过之后这个时间会持续生效，下次朗读会默认开启之前的时间，一般情况下还看不见在生效，容易让人以为是朗读有什么bug，以前的版本不会这样，如果是有这种需求，请把左边那个时钟做成定时开关

**Comment by Xwite** [comment]
refs #2435

**Comment by 821938089** [comment]
改了一下，点左边闹钟可以保存时间，下次更新之后你把进度条拉到0然后点一下闹钟就可以了
