### ISSUE TITLE
[Feature Request] 希望能增加自动备份开关

### ISSUE THREAD

**Issue by eaudouce** [gedoor/legado#2495]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 备份设置好webdav后，每天都会在云盘生成一个备份文件夹，既浪费空间又浪费流量，希望能加一个开关，可选是否自动备份。
给爱极简，爱手动备份的人一个选择吧~~

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by old-yellow-ox** [comment]
配置文件加起来1M都不到，这个没必要吧
