### ISSUE TITLE
[Feature Request] 求一个阿里云长文本语音合成的集成能力

### ISSUE THREAD

**Issue by gnuhpc** [gedoor/legado#2500]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望内置一个阿里云长文本语音合成能力

### 期望实现方式（阅读应该如何实现该功能）
> 填写AccessKey AID和App ID即可 

### 附加信息（其他的与功能相关的附加信息）
> https://help.aliyun.com/document_detail/130555.html

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
tts引擎有一个叫阿里云语音的，应该就是这个，你点一下然后把应用信息填进去就可以了
