### ISSUE TITLE
[Feature Request] 换源时希望能定位到当前选中源的位置

### ISSUE THREAD

**Issue by loLucky** [gedoor/legado#2501]
某个章节不能看时，有频繁的切换书源寻找可看源的需求。
但每次打开切换按钮，都定位在第一行（或者说第一页）。
而前面的源其实已经试过了，却还每次都要手动下拉找到当前列表中源的位置，再依次往下找，
这种情况下，书源越多，越不方便。
希望添加换源时定位到当前选中源的列表位置，这样更人性化。

**Comment by 821938089** [comment]
换源界面底下那一栏是可以点的，点一下就可以直接跳转

**Comment by loLucky** [comment]
> 换源界面底下那一栏是可以点的，点一下就可以直接跳转
居然一直没有注意到列表最左边还有个可点击的选项，谢谢，我关闭问题了
