### ISSUE TITLE
[Feature Request] 工具栏的“朗读”和“界面”位置对调更顺手

### ISSUE THREAD

**Issue by lenny20** [gedoor/legado#2503]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 底部工具菜单栏，“朗读”和“界面”对调位置，让后续频繁使用的“朗读”功能更顺手(右拇指)、与”后台“在同一位置，可以连续点击；”主菜单“和”界面“也在同一位置，比较顺手，”界面“设置是开始需要、以后很少用到的。

### 期望实现方式（阅读应该如何实现该功能）
> 只需要把“朗读”和“界面”的位置对调。

### 附加信息（其他的与功能相关的附加信息）
> 菜单栏显示”朗读“时右侧的”设置“内容也应该跟显示”主菜单“时右侧的”设置“内容调换，这样才完全和谐统一。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 目录    界面    朗读    设置

**Comment by lenny20** [comment]
你们玩手机，用左手还是右手？

**Comment by gedoor** [comment]
都习惯了,再调整不好

**Comment by lenny20** [comment]
那此处增加左右手习惯，需要增加的代码量大吗？
