### ISSUE TITLE
求助：替换规则里在js用replace替换时，一用这种形式的断言?<= 就会出错，其他断言没事

### ISSUE THREAD

**Issue by zmn001125** [gedoor/legado#2504]
替换规则里在js用replace替换时，一用这种形式的断言?<= 就会出错，其他断言没事
![Screenshot_2022-10-29-21-46-31-955-edit_io.legado.play.release.jpg](https://user-images.githubusercontent.com/52020688/198835152-3d012e8b-825f-4f71-b24b-4fd640481f5c.jpg)![Screenshot_2022-10-29-21-46-49-955-edit_io.legado.play.release.jpg](https://user-images.githubusercontent.com/52020688/198835162-947ae231-33b7-4d80-b912-ed743919c0fc.jpg)![Screenshot_2022-10-29-21-46-53-972_io.legado.play.release.jpg](https://user-images.githubusercontent.com/52020688/198835165-d44b6e39-11e1-481d-95dc-da23d6883d67.jpg)

**Comment by zmn001125** [comment]
![Screenshot_2022-10-29-21-46-53-972_io.legado.play.release.jpg](https://user-images.githubusercontent.com/52020688/198835186-eb4b66a9-1735-4ff5-836d-35eb2323c9e4.jpg)
![Screenshot_2022-10-29-21-46-31-955-edit_io.legado.play.release.jpg](https://user-images.githubusercontent.com/52020688/198835189-7da88524-aff9-4959-8010-45a2f6e52984.jpg)

**Comment by 821938089** [comment]
这个js引擎的正则不支持Lookbehind正则，这种简单的正则就没必要用Lookbehind了吧

**Comment by zmn001125** [comment]
> 这个js引擎的正则不支持Lookbehind正则，这种简单的正则就没必要用Lookbehind了吧

啊，因为很多用的这个，整合到一起后发现放在js里不行，那我还是单独建吧

.replace(/(?<=[天知通味难])到|到(?=理|歉|具|士|德|路|法)/gi,'道')

**Comment by 821938089** [comment]
可以这样写
`([天知通味难])到|到([理歉具士德路法])`
`$1道$2`

**Comment by zmn001125** [comment]
> 可以这样写
> `([天知通味难])到|到([理歉具士德路法])`
> `$1道$2`

收到，谢谢
