### ISSUE TITLE
[BUG] 插入url参数里的headers文件头参数填写无效

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2510]
其他几个正常，就文件头格式填写任何参数都只生成一个空的花括号

**Comment by 821938089** [comment]
你写的格式不对

**Comment by zousizhe** [comment]
> 你写的格式不对

![Screenshot_2022-11-01-16-55-17-0590088984](https://user-images.githubusercontent.com/37259360/199197312-c980688b-44ca-498d-a5a1-b15311892bf2.png)
![Screenshot_2022-11-01-16-55-11-1889845066](https://user-images.githubusercontent.com/37259360/199197539-9a4e6c78-87ec-4b44-bdf2-12fe6ae803d3.png)

那要怎么写才能像那个写好的那样插入ua？字都没有出来，谈什么格式

**Comment by 821938089** [comment]
填json键值对

**Comment by zousizhe** [comment]
> 填json键值对

那是另外一回事了，现在是反馈这个问题，不是我不知道怎么打字上去

**Comment by zmn001125** [comment]
> > 填json键值对
> 
> 那是另外一回事了，现在是反馈这个问题，不是我不知道怎么打字上去

你要这样填![IMG_20221101_194851.jpg](https://user-images.githubusercontent.com/52020688/199226156-3d5140b5-be2e-43af-8d9b-b320036e03cc.jpg)
