### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Benjamin-Watson0** [gedoor/legado#2511]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 微软云语音转文字接口

### 期望实现方式（阅读应该如何实现该功能）
> 就是能像阿里云和百度云那样填写密钥就可以调用

### 附加信息（其他的与功能相关的附加信息）
> 我知道有新建引擎，但我对此一窍不通，希望能添加这一个，读的很不错

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Xwite** [comment]
https://github.com/jing332/tts-server-android/releases/tag/0.1_202211011618
