### ISSUE TITLE
[BUG] httpTTS的并发率在更改配置后会重置

### ISSUE THREAD

**Issue by jing332** [gedoor/legado#2512]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
> 网络引擎的并发率在编辑界面修改配置后被重置为0。

复现: 
```
{"contentType":"audio/webm; codec=opus","header":"{\"Content-Type\":\"text/plain\",\"Format\":\"webm-24khz-16bit-mono-opus\", \"Token\":\"\"}","id":1667295705423,"lastUpdateTime":1667295705423,"name":"大声朗读1233（zh-CN-XiaoxiaoNeural）","url":"http://localhost:1233/api/ra ,{\"method\":\"POST\",\"body\":\"\u003cspeak xmlns=\\\"http://www.w3.org/2001/10/synthesis\\\" xmlns:mstts=\\\"http://www.w3.org/2001/mstts\\\" xmlns:emo=\\\"http://www.w3.org/2009/10/emotionml\\\" version=\\\"1.0\\\" xml:lang=\\\"en-US\\\"\u003e\u003cvoice name=\\\"zh-CN-XiaoxiaoNeural\\\"\u003e\u003cprosody rate=\\\"{{(speakSpeed -10) * 2}}%\\\" pitch=\\\"+0Hz\\\"\u003e{{String(speakText).replace(/\u0026/g, '\u0026amp;').replace(/\\\"/g, '\u0026quot;').replace(/'/g, '\u0026apos;').replace(/\u003c/g, '\u0026lt;').replace(/\u003e/g, '\u0026gt;').replace(/\\\\/g, '')}}\u003c/prosody\u003e\u003c/voice\u003e\u003c/speak\u003e\"}","concurrentRate":"4000"}

```

将上面这段配置通过网络导入后，一旦编辑保存4000就会被重置为0。
并且我发现，如果通过粘贴源的方式导入上面的配置，并发率总是为0。

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
你是怎么编辑并发率的？我都找不到能编辑的地方

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/pull/2514
