### ISSUE TITLE
[BUG] 目录搜索不能跳转

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#2513]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>Redmi k40s和Redmi k20Pro

### 安卓版本（如Android 7.1.1）
>
Android 11和Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.102918

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通

### 问题描述（简要描述发生的问题）
>
阅读是想搜索目录定向跳转，结果搜索出章节不能跳转，这样搜索不就是一点用都没有了

### 相关截图
>
![SC-1667301498237](https://user-images.githubusercontent.com/106790230/199222615-42b0ca10-071b-4180-8fb5-6337fd1542d5.gif)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>看任意一本书，打开目录，右上角搜索目录，搜索到什么都不能跳转，还会在当前章节

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by zmn001125** [comment]
好像是目录页显示有问题，返回正文页实际已经跳转

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/pull/2514
