### ISSUE TITLE
[Feature Request] 关于书单的导入导出问题

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2515]
这个书单导入为什么完全没反应，无论是导出的不带书源的书单配置还是备份时带书源的书单配置文件，都没有反应，使用还原来恢复书单则可以秒恢复，这应该不是书籍多的问题吧，现在这功能是没法用还是我不会用？

**Comment by zousizhe** [comment]
在使用一个共存版试了一下，书源相同，依然是不行，完全没反应

**Comment by zousizhe** [comment]
> 书架里已经有的书会跳过 需要有书源

在使用一个共存版试了一下，书源相同，依然是不行，完全没反应

**Comment by 821938089** [comment]
你把书单发一下我试试

**Comment by zousizhe** [comment]
> 你把书单发一下我试试

https://shuyuan.mgz6.cc/shuyuan/e81e4167c9eb6725308339dfd1ff7828.json

**Comment by zousizhe** [comment]
> 你把书单发一下我试试

另外书源应该也不会要求书源或者书架一样之类的要求，书单里面没有指定，只是个空书单，没有带书源，备份的书架配置文件才带书源，但是选那个导入一样无效

**Comment by 821938089** [comment]
我这里是可以导入的，可能是搜索书比较慢？
你的书源管理开头的书源是不是失效了啊？
