### ISSUE TITLE
[BUG] 书单导入功能完全没有反应

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2517]
使用了一个共存版试了一下，在两边书源完全一样，导入书单完全没反应。导入备份的书架配置文件也是没反应。 之后简介都进不去，创建分组也点不了确定，关掉重进才好

**Comment by 821938089** [comment]
校验一下书源，把失效的禁用一些再试试

**Comment by zousizhe** [comment]
> 

难道书单是阅读在后台一本本的搜出来的？不是导入就完事的？使用还原配置文件时又能瞬间恢复，不管书源在不在，有没效

**Comment by 821938089** [comment]
对
