### ISSUE TITLE
[Feature Request] 方向旋转（180°竖屏倒立）

### ISSUE THREAD

**Issue by xsdcz** [gedoor/legado#2518]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望添加一个倒立阅读的模式。
很多时候需要边充电边使用阅读，如果屏幕可以倒立着使用，那么充电口就在上面了，个人感觉这样会方便很多。

### 期望实现方式（阅读应该如何实现该功能）
> 除了已有的横屏竖屏模式之外，可以增加一个屏幕旋转180°的阅读模式。
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
加上了，需要关闭方向锁定

**Comment by xsdcz** [comment]
> 

是系统问题吗？ 我k40，miui13.05  最多只能旋转90°，没办法旋转180°

**Comment by 821938089** [comment]
你是用的最新测试版吗？

**Comment by xsdcz** [comment]
> 你是用的最新测试版吗？
嗯 ，是最新的测试共存版。 
我搞明白了，使用跟随系统或者跟随传感器 都是最多90° ，只有手动选择翻转才是180°。
