### ISSUE TITLE
[Feature Request] 希望听书时可以加个屏幕常亮的开关

### ISSUE THREAD

**Issue by xsdcz** [gedoor/legado#2519]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 听书的时候经常会因为没听清等情况会扫一眼，希望可以在听书时有一个保持常亮的开关，这样就可以像题词器一样边看边听。

### 期望实现方式（阅读应该如何实现该功能）
> 增加一个保持屏幕常亮的开关。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
屏幕超时设置成常亮

**Comment by xsdcz** [comment]
![fce4f4e9bd6ebc95759cca6bf00284e](https://user-images.githubusercontent.com/20486499/199641865-f573bdaa-a91b-4419-8855-6d4e50fd3181.jpg)
就是因为这系统没有常亮才提的这需求

**Comment by xsdcz** [comment]
> 屏幕超时设置成常亮

![fce4f4e9bd6ebc95759cca6bf00284e](https://user-images.githubusercontent.com/20486499/199642001-ea7d7d8f-0e2e-4504-9bc1-a2163a0f5aa5.jpg)

就是因为这系统没有常亮的选项，才来提的需求。

**Comment by 821938089** [comment]
app里面的屏幕超时设置有常亮

**Comment by xsdcz** [comment]
好的，感谢。我之前在设置里找了半天没找到这样的选项。原来在阅读界面的设置里...
