### ISSUE TITLE
建议可以参考一下MIUI12自带读数软件的处理方法

### ISSUE THREAD

**Issue by kang-mk** [gedoor/legado#252]
![Screenshot_2020-06-26-10-39-36-153_com duokan reader](https://user-images.githubusercontent.com/20243226/85814925-bb641880-b799-11ea-958e-c176803fe51f.jpg)
![Screenshot_2020-06-26-10-41-30-661_com duokan reader](https://user-images.githubusercontent.com/20243226/85814933-bef79f80-b799-11ea-93c6-d60a052f5c0a.jpg)
软件界面正常显示小白条，进入阅读界面就直接隐藏小白条，现在阅读是直接在下面空了一块
![Screenshot_2020-06-26-10-45-59-790_io legado app release](https://user-images.githubusercontent.com/20243226/85815140-3cbbab00-b79a-11ea-8c50-d821261e1808.jpg)
大佬辛苦了

**Comment by gedoor** [comment]
阅读界面设置里隐藏,应该可以

**Comment by kang-mk** [comment]
> 阅读界面设置里隐藏,应该可以

非常感谢回复，找到相关设置了，关闭问题了
