### ISSUE TITLE
[Feature Request] 重新添加自动双栏（双页）选项

### ISSUE THREAD

**Issue by fairyex** [gedoor/legado#2521]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 之前提供双栏阅读功能的时候在折叠屏上是自动切换的，外屏自动单列，内屏是双列，后来在阅读设置里提供选项之后就没有自动了，每次切换到内外屏阅读都要手动改一遍。

### 期望实现方式（阅读应该如何实现该功能）
> 在现在的双页设置选项里添加一个自动，像前几个版本一样，检测屏幕宽度来改变双栏

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 821938089** [comment]
改了，等会测试版出来了可以试试看

**Comment by fairyex** [comment]
收到，非常感谢🙏

**Comment by fairyex** [comment]
> 改了，等会测试版出来了可以试试看

收到，非常感谢🙏
