### ISSUE TITLE
[Feature Request] 书源调试能否看到请求的html

### ISSUE THREAD

**Issue by zhangzw218** [gedoor/legado#2525]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 我书源调试遇到问题
以搜索书籍为例：
class.novelslist2@tag.li!0获取不到结果
class.novelslist2可以获取到一个结果。
至少代表，class.novelslist2这个节点是存在的。
那么，class.novelslist2@tag.li就算搜索书籍为空，也至少有一个结果（列表的的标题栏，也是tag.li）
但是我依然获取不到
这时候我就很疑惑，为啥class.novelslist2可以获取到，class.novelslist2的内部是什么？
如果，可以知道我调试的时候，《阅读》获取到的页面内容就好了？
至少我可以和浏览器对比一下，html有什么区别。

**Comment by 821938089** [comment]
右上角三点里面有
或者用js也可以看

**Comment by zhangzw218** [comment]
@821938089 
你好，我指的是这个页面，没有看到你说的右上角三个点。
还有那个js怎么看，我F12看，数据好像都在手机那边？
![image](https://user-images.githubusercontent.com/40768649/201345684-1bb85104-6b0e-43d6-8c55-b1ae605d36a0.png)

**Comment by 821938089** [comment]
手机调试的右上角三点
电脑上看的话就只能用js了
<js>java.log(result)</js>

**Comment by zhangzw218** [comment]
<js>java.log(result)</js>
这一句应该写在浏览器的什么位置？我没有搞过。
@821938089

**Comment by 821938089** [comment]
获取数据的规则都可以用
例如书籍列表规则

**Comment by zhangzw218** [comment]
多谢，我可以看到了。
