### ISSUE TITLE
[Feature Request] 希望能自由分享书单，不用在后台校检书单是否能使用

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2526]
像导入书源一样，瞬间添加，允许导入导出任意选择，让书架可以添加不带网址的小说名单，不再检索是否可以使用，搜不到让用户自己想办法，现在这个书单限制太多，几乎没法用，会在在后台搜索再添加书架，半天都没什么反应，都成了无用功能

**Comment by gedoor** [comment]
我想想办法

zousizhe ***@***.***> 于 2022年11月8日周二 16:19写道：
