### ISSUE TITLE
[Feature Request] 建议书源增加一个地方存放全局函数和登录UI里的按钮支持调用登录URL里的JS

### ISSUE THREAD

**Issue by xingluo233** [gedoor/legado#2548]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 1.有些方法如加解密在多处需要用到，有了全局函数就可以不用麻烦的每个地方都用软件自带的解密了
   2.某些网站不支持密码登录，只能用验证码登录，而在阅读里需要先填账号，再点登录，登录界面就会关闭，收到验证码了再登录，这样可能会麻烦点，如果按钮支持调用JS就不用这么麻烦了

**Comment by xingluo233** [comment]
@gedoor 考虑下这个吧

**Comment by Xwite** [comment]
全局函数写在源注释里

调用函数的话，先执行这个
```js
eval(String(source.bookSourceComment))
```

按钮执行JavaScript使用测试版
https://github.com/gedoor/legado/commit/d301b8af09817be39150cc879bbaa3aab4530842
