### ISSUE TITLE
关于登录UI的button执行js

### ISSUE THREAD

**Issue by zmn001125** [gedoor/legado#2560]
请问怎么在不点✓的情况下，按button可以获取到“电话号码”的值，用source.getLoginInfoMap()好像要点✓保存后才能获取到，直接点button获取的是空![Screenshot_2022-11-12-19-31-51-902_io.legado.play.release.jpg](https://user-images.githubusercontent.com/52020688/201472056-83fe8fe1-115c-41a3-b80f-247ef12b3ebf.jpg)
![Screenshot_2022-11-12-19-35-55-418_io.legado.play.release.jpg](https://user-images.githubusercontent.com/52020688/201472124-22bd8a1e-ec83-4bb3-90f6-6b026b615ce6.jpg)

**Comment by Xwite** [comment]
fixed
