### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by lswlc33** [gedoor/legado#2563]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 添加web服务的网页pwa功能来提高平板和电脑的阅读体验
（能看到更简化的浏览器UI和使用更好的便捷性，在苹果里弥补没有应用的缺陷）

### 期望实现方式（阅读应该如何实现该功能）
> http://t.csdn.cn/TXmck
可以参考网络教程给网站添加三个文件

### 附加信息（其他的与功能相关的附加信息）
> 求求你啦![IMG_20221109_232308_176.png](https://user-images.githubusercontent.com/86835895/201496985-4d39b9f0-397b-4806-9a98-99ea6e90ec80.png)

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>难以演示

**Comment by Xwite** [comment]
PWA只能运行在https环境下
