### ISSUE TITLE
[BUG] 自动跳转最近阅读功能开启后，打开app进入阅读界面，用目录跳转章节无效

### ISSUE THREAD

**Issue by liukaitt67** [gedoor/legado#2566]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>MI 6

### 安卓版本（如Android 7.1.1）
>MIUI 11.0.5 稳定版

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.102918

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>自动跳转最近阅读功能开启后，打开app进入阅读界面，用目录跳转章节无效

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>app设置打开 自动跳转最近阅读，访问一个TXT文档，退出app后重新打开，此时已自动打开最后打开的txt文件的阅读界面，打开目录，点击任意其他章节，跳转无效

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by 821938089** [comment]
更新到最新版再试一下
