### ISSUE TITLE
Sophos扫描后报不安全项

### ISSUE THREAD

**Issue by InitialXKO** [gedoor/legado#257]
- 请求程序包安装
    此应用让 Android 安装其他应用。

- 读取帐户
    此应用可以访问帐户详细信息。如您的 Google 或 Facebook 帐户的用户名。

-读取电话号码
    此应用可以访问您的电话号码和手机供应商数据，如 IMEI 或设备序列号。

**Comment by gedoor** [comment]
这个是google统计需要的权限,不用在意
