### ISSUE TITLE
请问yushubo.net有办法写书源吗？

### ISSUE THREAD

**Issue by fhwhite** [gedoor/legado#2572]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

只是爱好者，也不太懂html，只好来求助

书源里的yushubo.net不好使了，发现书站在第一次加载搜索页的时候返回一个cookie，大概这个样子（ge_js_validator_45=1668495164@45@f4abd4ed130891d5287354e5bef7e104; path=/; max-age=60;）然后window.location.reload一下，用python获取，并且携带这个cookie再次访问search页面可以获取正确返回值，请问阅读的书源规则能处理这个问题吗？该怎么处理呢？

### 期望实现方式

不知道是否能实现，小白第一次遇到这种反爬办法

**Comment by Xwite** [comment]
{
  "bookSourceName": "测试",
  "bookSourceType": 0,
  "bookSourceUrl": "测试",
  "customOrder": 0,
  "enabled": true,
  "enabledCookieJar": true,
  "enabledExplore": true,
  "enabledReview": true,
  "lastUpdateTime": 1668498252235,
  "loginCheckJs": "a = result.body().match(/document.cookie = \"(.*?)\";/)\nif (a) {\na = a[1]\n//ge_js_validator_45=1668497689@45@cfc64257e27a5e350a1c2439fea346a4; path=/; max-age=60;\ncookieStr = a.split(\";\")[0]\njava.log(cookieStr)\ncookie.replaceCookie(source.getKey(), cookieStr)\njava.getStrResponse()\n} else result",
  "respondTime": 180000,
  "ruleBookInfo": {},
  "ruleContent": {},
  "ruleExplore": {},
  "ruleReview": {},
  "ruleSearch": {},
  "ruleToc": {},
  "searchUrl": "https://m.yushubo.net/search.html?ss=诡秘",
  "weight": 0
}

**Comment by fhwhite** [comment]
大佬牛逼，感谢感谢

**Comment by fhwhite** [comment]
或者大佬能告诉下这玩意是怎么实现的，我是纯爱好者，不懂这是什么语言，该查什么资料或者关键字学习

**Comment by fhwhite** [comment]
```
a = result.body().match(/document.cookie = "(.*?)";/)
if (a) {
a = a[1]
//ge_js_validator_45=1668497689@45@cfc64257e27a5e350a1c2439fea346a4; path=/; max-age=60;
cookieStr = a.split(";")[0]
java.log(cookieStr)
cookie.replaceCookie(source.getKey(), cookieStr)
java.getStrResponse()
} else result
```
原来不是写死的，但是第二次就不好使了，我再试试

**Comment by fhwhite** [comment]
应该不是代码问题，有的时候返回值正常，有的时候还是返回cookie那个页面，感谢大佬，我自己再研究研究
