### ISSUE TITLE
关于书源搜索后返回链接问题

### ISSUE THREAD

**Issue by owen20001** [gedoor/legado#2574]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

通过书源搜索书籍后，返回URL链接，无法获取到书籍内容

### 复现步骤

![b446ed2a6de6ded3bc17dc32d2ced6c](https://user-images.githubusercontent.com/43109890/202105289-e367923f-b266-41e2-ab6e-4ee3999e00f9.jpg)

### 阅读版本

3.22061022

### Android版本

Android 12

### 机型

MATE20

**Comment by old-yellow-ox** [comment]
你这是书源有问题吧。
