### ISSUE TITLE
滚动方式不连贯

### ISSUE THREAD

**Issue by progmboy** [gedoor/legado#258]
2.0的滚动方式是连贯的
![20200628_102828](https://user-images.githubusercontent.com/9927043/85936200-c8644180-b92a-11ea-90f1-ca8ea749d854.gif)
3.0不连贯
![20200628_102202](https://user-images.githubusercontent.com/9927043/85936203-d3b76d00-b92a-11ea-8598-d0d3e1b791c7.gif)

**Comment by gedoor** [comment]
好的,我看下

**Comment by gedoor** [comment]
下版本修复
