### ISSUE TITLE
书籍置顶功能失效

### ISSUE THREAD

**Issue by Chen-Yuanmeng** [gedoor/legado#2581]
### 确认

- [x] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

长按书籍进入书封面后，右上角三个点菜单里的“置顶”功无效

### 复现步骤

长按书籍进入书封面后，点击右上角三个点，选择菜单里的“置顶”，回到书架选择其他书进入阅读界面之后返回，选择置顶的书籍被挤下去了

### 阅读版本

3.22.111423 & 3.22.111716

### Android版本

Android 6.0.1

### 机型

MuMu虚拟机

**Comment by 821938089** [comment]
这个置顶只是把书放到书架顶端，不会固定
需要固定的话把排序设置成手动排序就可以了

**Comment by Chen-Yuanmeng** [comment]
好吧，跟想象中的置顶不太一样……理解，谢谢
