### ISSUE TITLE
TTS遇到标点符号出错

### ISSUE THREAD

**Issue by cool-delete** [gedoor/legado#2584]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

使用TTS的时候 朗读的段落会随着朗读位置表示红色,但是经常发现 红色表示段落的上一句的时候 TTS已经读完下一句了 这个时候TTS读完这一章的末尾就不读了....需要手动点击下一章才可以继续

### 复现步骤

后续发现 只要是一个段落都是省略号的时候 由于省略号tts会忽略 但是阅读app仍然会停留 导致阅读和tts两边不同步 
阅读的朗读部分应该是报错了 但是日志是空的

https://user-images.githubusercontent.com/13638610/202892297-a25fa558-bdb0-4d14-b728-dca3016050bd.mp4

https://user-images.githubusercontent.com/13638610/202892589-7f738a50-086c-4daa-a45a-ed2f97bd86ac.mp4

### 日志提交

webDav上传失败 401 

### 阅读版本

3.22.111423 其实一直存在的

### Android版本

11

### 机型

vivoNEX

**Comment by cool-delete** [comment]
目前只能用替换文本去掉标点符号 但是这样会破坏文意的 希望能修复 其实这个bug已经很久了

**Comment by 821938089** [comment]
TTS的问题，换一个朗读引擎

**Comment by cool-delete** [comment]
> TTS的问题，换一个朗读引擎
这是系统自带的tts啊 而且标点符号一个段落的例子 你要tts怎么处理 不应该由app同步一次吗 而且很明显因为段落的时候 红色文字和tts已经不同步导致的 

而且和tts无关 我用静读天下读这些标点的时候就没有这个问题

**Comment by 821938089** [comment]
https://kunfei.lanzoui.com/iJKgo0gkuspa
装一下这个测试版看看有没有问题

**Comment by lianbook** [comment]
我也遇到了，建议只有符号的文本，自动忽略朗读。

**Comment by jing332** [comment]
应该是段落切换过快导致不同步，有时某一段落朗读过快就会发生这种情况。

**Comment by 821938089** [comment]
@jing332 是这个系统的TTS在省略号那一段不会调用朗读完成的回调，导致阅读不知道这一段已经读完了
不知道静读天下怎么处理的

**Comment by cool-delete** [comment]
> @jing332 是这个系统的TTS在省略号那一段不会调用朗读完成的回调，导致阅读不知道这一段已经读完了 不知道静读天下怎么处理的

正则匹配到非文字的段落 就不提交到TTS？

阅读是怎么处理TTS的UI呢 每一个段落回调才会让字体变红。但是什么时候提交到TTS呢？ 我认为是应该调用TTS跟字体变红的功能应该用一个代理来执行吧

**Comment by jing332** [comment]
应该是每次回调焦点就+1

**Comment by jing332** [comment]
如果系统TTS未调用回调，那阅读就会在省略号那段卡住吧？但为什么朗读还正常？

**Comment by 821938089** [comment]
@jing332 
阅读会一次性发送本章未读的段落给TTS
然后靠回调来判断读到哪了
如果少一次回调，那么朗读焦点位置就会错位，并且会在最后那里卡住

**Comment by cool-delete** [comment]
> @jing332 阅读会一次性发送本章未读的段落给TTS 然后靠回调来判断读到哪了 如果少一次回调，那么朗读焦点位置就会错位，并且会在最后那里卡住

要么就一次性发送的时候 用正则过滤一下段落数组 把全是标点的去掉 要么是改掉逻辑 每个段落都先判断再发给TTS

**Comment by 821938089** [comment]
@cool-delete 你写个净化规则把标点符号段落删除就好了

**Comment by cool-delete** [comment]
> @cool-delete 你写个净化规则把标点符号段落删除就好了

我目前就是这样做的 但是这样就破坏文意了

**Comment by jing332** [comment]
> > @cool-delete 你写个净化规则把标点符号段落删除就好了
> 
> 我目前就是这样做的 但是这样就破坏文意了

你用的是哪个TTS引擎？我测试看看

**Comment by cool-delete** [comment]
> > > @cool-delete 你写个净化规则把标点符号段落删除就好了
> > 
> > 
> > 我目前就是这样做的 但是这样就破坏文意了
> 
> 你用的是哪个TTS引擎？我测试看看

我是vivo用户  默认的aiServiceTTS

**Comment by jing332** [comment]
这样啊，那好吧。

**Comment by gedoor** [comment]
可以试试最新测试版本,纯标段落问题修复了一下,不在提交给tts朗读,直接跳过
