### ISSUE TITLE
如果没有等到获取目录就添加书架然后返回，缓存该小说就会导致下载界面重载

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2585]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

在搜索列表进入小说还没有读取目录信息时缓存该小说，结果下载界面卡死随后下载界面重载，下载也未成功

### 复现步骤

在网络慢时小说没有获取目录就添加到书架，以及导入书单之后，选择缓存小说，在目录信息为0的情况缓存界面会卡死并重载。以前遇到过目录为0都可以正常检测到目录并缓存

### 阅读版本

3.22.111423

### Android版本

Android 12

### 机型

小米11青春版

**Comment by gedoor** [comment]
收到
