### ISSUE TITLE
是否可以增加onedrive的支持

### ISSUE THREAD

**Issue by tangshg** [gedoor/legado#2586]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

现在云备份采用 webdav 的方式实现，也可以读取 webdav 中的书籍，但 onedrive 云盘不支持 webdav 的服务，是否可以支持 onedrive 云备份和读取书籍？

### 期望实现方式

这是 onedrive 的文档：https://learn.microsoft.com/zh-cn/onedrive/developer/?view=odsp-graph-online

**Comment by Gladtbam** [comment]
可以尝试使用Alist，Cloudreve或者Rclone搭建WebDav，前面两个可能需要VPS，Rclone 使用Termux之类的终端模拟器放在本地就行

**Comment by lianbook** [comment]
你这网盘国外的，国内打开都卡，只为你一个人没必要吧？还不如支持腾讯阿里七牛云之类的云存储

**Comment by lianbook** [comment]
这些国内云存储都有一些免费额度

**Comment by lianbook** [comment]
坚果云说实话没有阿里腾讯靠谱，说不定哪天就给关闭了

**Comment by smarttommyau** [comment]
你可以試試 https://www.multcloud.com/tutorials/webdav-access-to-onedrive-6289.html 可以webdav来连接onedrive
