### ISSUE TITLE
建议遇到缓存连续几章都失败的就停止缓存

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2588]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

看了一下通知栏信息，被一个网站封了ip还在增加失败章节数，像这样的网站，继续缓存已经没有意义，越缓存封的越久，如果是网站的缺章，换源之后也是要重新缓存，要是网络问题，偶尔一两章失败可以继续，五六章都失败就没有必要再继续

### 期望实现方式

遇到连续的或者不连续的章节缓存失败一定数量后立刻停止，自动重试一两次下一本或者直接跳到下一本缓存

**Comment by yafovo** [comment]
这里面有个问题，有些网站有防抓取，短时间连续下载会出现大量下载失败。
得加个内容判断？对抓取失败或异常的章节，自动重新下载？

**Comment by zousizhe** [comment]
> 

不需要判断，哪个失败了app不是知道吗，通知栏显示了失败章节，不管是网络还是网站原因，连续的失败整本就跳过，最多重试一两次

**Comment by yafovo** [comment]
好像也是哈~~
