### ISSUE TITLE
WEB端朗读

### ISSUE THREAD

**Issue by kaveys** [gedoor/legado#2590]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

web端朗读功能取消了？为什么我这里没有啊

### 期望实现方式

加上web端的朗读

**Comment by 821938089** [comment]
本来就没有，要朗读的话可以用edge浏览器的大声朗读

**Comment by lianbook** [comment]
朗读卡了，能自动重连么？有时候卡了只能返回到书架页面重进才能重新朗读

**Comment by dianso** [comment]
自己对着屏幕叫就行

**Comment by MrLinyuan** [comment]
你要是听书就用手机听书
