### ISSUE TITLE
双页模式下图片问题

### ISSUE THREAD

**Issue by smarttommyau** [gedoor/legado#2591]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

在default图片模式下图片，会被挤到下一个大页，而不是旁边的那页

FULL
![Screenshot_20221122_145545_io legado app release](https://user-images.githubusercontent.com/75346987/203248212-4f2ade7a-0a99-4254-84dd-821d1f387eff.jpg)

DEFAULT
![Screenshot_20221122_150551](https://user-images.githubusercontent.com/75346987/203248259-9a5a3f6b-0103-4aa2-b09a-07774d536960.jpg)
![Screenshot_20221122_145554_io legado app release](https://user-images.githubusercontent.com/75346987/203248263-f5a51aff-7d11-41c2-8c2c-d7d3d8ccb9ae.jpg)

### 复现步骤

在双页模式下使用default图片模式

### 阅读版本

3.22.111423

### Android版本

Android 10/HarmonyOS 2.0

### 机型

Huawei Matedpad 10.4 2021

**Comment by 821938089** [comment]
用滚动翻页动画

**Comment by smarttommyau** [comment]
滚动翻页动画的话整个表现也不同，也没有解决到这个问题吧。现在的问题是在这些模式中图片不会利用右边的半页只会利用左边的半页，滚动模式下也是如此，图片应该要把右半页也利用上才对吧。

**Comment by gedoor** [comment]
我看下

**Comment by gedoor** [comment]
滚动应该是全页的
