### ISSUE TITLE
希望有一个更方便开关 Web 服务器的方法

### ISSUE THREAD

**Issue by Unintendedz** [gedoor/legado#2593]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

现在想要打开 Web 服务器必须退出当前小说，到右下角菜单里才能打开。（如果有别的方式望告知）
当这个操作每天可能进行好几次的时候就比较不方便了。
所以希望能添加一个更方便的开关 Web 服务的方法。

### 期望实现方式

- 添加控制中心的快捷开关
- 添加桌面图标长按菜单选项

### 效果演示
 
![image](https://user-images.githubusercontent.com/64687143/203792309-cddbb451-3c8f-4fd6-a218-071a7d557b6a.png)

![image](https://user-images.githubusercontent.com/64687143/203791863-32cffebe-1e23-478c-952a-d6ee78f0786b.png)

**Comment by 821938089** [comment]
有控制中心的快捷开关

**Comment by Unintendedz** [comment]
🤦‍♂️是我粗心了，谢谢提醒。
