### ISSUE TITLE
目录翻页js替换时感觉判定有问题

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#2596]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

目录翻页js替换时感觉判定有问题

### 复现步骤

书源如下
{
  "bookSourceComment": "",
  "bookSourceName": "稀饭小说",
  "bookSourceType": 0,
  "bookSourceUrl": "https://xifan.org",
  "bookUrlPattern": ".*/\\w+.xifan.org",
  "customOrder": 0,
  "enabled": true,
  "enabledCookieJar": false,
  "enabledExplore": true,
  "enabledReview": false,
  "exploreUrl": "[{\"title\":\"悬疑推理\",\"url\":\"https://1107.xifan.org/e/extend/more/lsmore.php?page={{page-1}}&line=10&sinfo=悬疑推理\",\"style\":{\"layout_flexGrow\":1}},{\"title\":\"传奇奇幻\",\"url\":\"https://xifan.org/e/extend/more/lsmore.php?page={{page-1}}&line=10&sinfo=传奇奇幻\",\"style\":{\"layout_flexGrow\":1}},{\"title\":\"灵异惊悚\",\"url\":\"https://xifan.org/e/extend/more/lsmore.php?page={{page-1}}&line=10&sinfo=灵异惊悚\",\"style\":{\"layout_flexGrow\":1}},{\"title\":\"悬疑\",\"url\":\"https://xifan.org/e/extend/more/lsmore.php?page={{page-1}}&line=10&sinfo=悬疑\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.4}},{\"title\":\"奇幻\",\"url\":\"https://xifan.org/e/extend/more/lsmore.php?page={{page-1}}&line=10&sinfo=奇幻\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.4}},{\"title\":\"爱情\",\"url\":\"https://xifan.org/e/extend/more/lsmore.php?page={{page-1}}&line=10&sinfo=爱情\",\"style\":{\"layout_flexGrow\":1}},{\"title\":\"古风\",\"url\":\"https://xifan.org/e/extend/more/lsmore.php?page={{page-1}}&line=10&sinfo=古风\",\"style\":{\"layout_flexGrow\":1}},{\"title\":\"青春\",\"url\":\"https://xifan.org/e/extend/more/lsmore.php?page={{page-1}}&line=10&sinfo=青春\",\"style\":{\"layout_flexGrow\":1}}]",
  "header": "{\n  \"User-Agent\": \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36\"\n}",
  "lastUpdateTime": 1669453841049,
  "respondTime": 180000,
  "ruleBookInfo": {
    "author": "p[0]@a@text",
    "coverUrl": "img[0]@src",
    "intro": ".cover-book-desc@text",
    "kind": ".detail-header-info@text##分类：(.*?)小?说? 状态：(.*?)\\((共\\d+章)\\) 更新时间：([^\\s]*)##$1,$4,$2$3###",
    "lastChapter": ".cover-mate-text!-1@text",
    "name": "h2@text",
    "tocUrl": "##data-bookid=\"(\\d+)\" data-classid=\"(\\d+)\" data-pagenum=\"(\\d+)\"##https://xifan.org/e/extend/bookpage/pages.php?classid=$2&id=$1&pageNum=0&dz=asc&pageCount=$3&totalPage=$3\n&loadlist=0###"
  },
  "ruleContent": {
    "content": "#news@html"
  },
  "ruleExplore": {
    "author": "$.username",
    "bookList": "$.*",
    "bookUrl": "$.url",
    "coverUrl": "$.pic",
    "intro": "$.smalltext",
    "kind": "$.date",
    "name": ".title"
  },
  "ruleReview": {},
  "ruleSearch": {
    "author": "span!0:2@text",
    "bookList": ".s-nv-list@li",
    "bookUrl": "a@href",
    "coverUrl": "img@src",
    "intro": "p@text",
    "name": ".title@text"
  },
  "ruleToc": {
    "chapterList": "$.list[*]",
    "chapterName": "$.title",
    "chapterUrl": "$.pic",
    "isPay": "",
    "nextTocUrl": "@js:var list=[];\nvar a=result.match(/\"totalPage\":(\\d+)/)[1];\nfor (var i=1;i<a;i++){\nlist.push(baseUrl.replace(/Num=\\d+&.*/g,\"Num=\")+i+'&dz=asc&pageCount='+a+'&totalPage='+a+'&loadlist=0')\n}\nlist;"
  },
  "searchUrl": "/e/search/index.php,{\n  \"body\": \"tbname=sinfo&show=title,username,renwu&tempid=1&classid=1&keyboard={{key}}\",\n  \"method\": \"POST\"\n}",
  "weight": 0
}
跳转目录时链接里有一部分&loadlist=0就没显示成链接的粉色
接着目录翻页匹配替换时.*匹配不到&loadlist=0,导致&loadlist=0还是在链接内 数字加在了&loadlist=0后面，生成的翻页链接都错误了。。。
![Screenshot_20221126-171652334 (1)](https://user-images.githubusercontent.com/73186747/204081862-d7113572-4bae-4f80-8ab2-914aae09c24e.jpg)

### 阅读版本

3.22.112523

### Android版本

Android10

### 机型

SONY Z4 TABLET

**Comment by 821938089** [comment]
你规则写错了

> 跳转目录时链接里有一部分&loadlist=0就没显示成链接的粉色

![image](https://user-images.githubusercontent.com/8674809/204086319-0c981edc-114a-458f-bc39-e584dc615227.png)

> 接着目录翻页匹配替换时.*匹配不到&loadlist=0

![image](https://user-images.githubusercontent.com/8674809/204086385-f9b8bfa0-d67a-4d5f-806b-4a1375737e34.png)

**Comment by ladia** [comment]
> 你规则写错了
> 
> > 跳转目录时链接里有一部分&loadlist=0就没显示成链接的粉色
> 
> ![image](https://user-images.githubusercontent.com/8674809/204086319-0c981edc-114a-458f-bc39-e584dc615227.png)
> 
> > 接着目录翻页匹配替换时.*匹配不到&loadlist=0
> 
> ![image](https://user-images.githubusercontent.com/8674809/204086385-f9b8bfa0-d67a-4d5f-806b-4a1375737e34.png)

发现了，感谢指出
