### ISSUE TITLE
书籍搜索时key需要gbk编码

### ISSUE THREAD

**Issue by zhangzw218** [gedoor/legado#2598]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

我一个搜索条件：
搜索书籍：二
会被自动转成gbk编码
http://www.fxqx.com/search.asp?key=%B6%FE
但是，我找不到可以转换的办法？
我尝试 java.utf8ToGbk(str: String)
java.log('key='+key);
key2 = java.utf8ToGbk(key)
java.log('key2='+key2);
这里只能获取到一个乱码。是因为这里需要一个utf8的原因么？
我想知道，有没有字符串直接转gbk的办法，或者字符串转ut8的办法，可以配合utf8ToGbk使用

### 期望实现方式

我想知道，有没有字符串直接转gbk的办法，或者字符串转ut8的办法，可以配合utf8ToGbk使用

**Comment by 821938089** [comment]
![image](https://user-images.githubusercontent.com/8674809/204132464-9cdac9b2-575c-4409-b1a2-21a38330d5a2.png)

**Comment by zhangzw218** [comment]
多谢，我搞定了
