### ISSUE TITLE
功能建议：修复错误的断句

### ISSUE THREAD

**Issue by relohu** [gedoor/legado#260]
有时候有些网站可能会乱断句。比如
“这是一
个例子”
这时候阅读体验较差。
另外，阅读3.0很多时候不能正确分析txt文件目录，而且这些文件2.0可以正确分析目录
下面是我用python处理txt时的程序。可以提供一下思路。

```
import re

chapter_title = re.compile(r'^.{0,2}第[ 0-9零壹贰叁肆伍拾陆柒捌玖拾佰仟万亿一二三四五六七八九十百千万亿]*?[章集节季篇部回].*?(?=\n)|(?<=\n).{0,2}第[ 0-9零壹贰叁肆伍拾陆柒捌玖拾佰仟万亿一二三四五六七八九十百千万亿]*?[章集节季篇部回].*?(?=\n)|^.{0,2}(序章|前言|楔子|引言|引子).*?(?=\n)|(?<=\n).{0,2}(序章|前言|楔子|引言|引子).*?(?=\n)|(?<=\n).{0,3}[作者完本结感言语]*?.{0,3}(?=\n)')

def fuzhu1(matched):
    a = matched.group()
    jiewei_danzifu = ['。', '！', '!', '？', '?', '”', '"', '」', '～', '~']
    jiewei_shuangzifu = ['……', '——']
    if len(a) == 2 and a[-2] == '…' or len(a) == 3 and a[:-2] == '……':
        return a
    elif chapter_title.search(a):
        return a
    else:
        if a[-2] in jiewei_danzifu:
            return a
        elif a[-3:-1] in jiewei_shuangzifu:
            return a
        else:
            return a[:-1]

def xiufu_duanju(a):  #修复错误的断句
    a = delduanqianhoukongzifu(a)  #删除段前后空字符
    a = delkongduan(a)  #删除空段
    a = re.sub(r'(?<=\n).+?\n', fuzhu1, a)
    return a
```

**Comment by 52fisher** [comment]
> 阅读3.0很多时候不能正确分析txt文件目录，而且这些文件2.0可以正确分析目录

阅读3.0内置了18种目录格式，部分txt文件可能并不是标准格式，需要用户手动切换目录规则。

**Comment by enximi** [comment]
> > 阅读3.0很多时候不能正确分析txt文件目录，而且这些文件2.0可以正确分析目录
> 
> 阅读3.0内置了18种目录格式，部分txt文件可能并不是标准格式，需要用户手动切换目录规则。

懂了，谢谢！之前没有注意到目录规则，看着是换源按钮就没点过。
另外，净化替换的规则似乎不支持反向预查？如果支持的话修复断句就能用净化替换凑合一下了。

**Comment by 52fisher** [comment]
> 
> 
> > > 阅读3.0很多时候不能正确分析txt文件目录，而且这些文件2.0可以正确分析目录
> > 
> > 
> > 阅读3.0内置了18种目录格式，部分txt文件可能并不是标准格式，需要用户手动切换目录规则。
> 
> 懂了，谢谢！之前没有注意到目录规则，看着是换源按钮就没点过。
> 另外，净化替换的规则似乎不支持反向预查？如果支持的话修复断句就能用净化替换凑合一下了。

负向环视 不支持可变长度，避免在负向环视使用.*     .+ 或 .*?    .+?   ?? 等元子组合，使用.{1,99}等可规避
