### ISSUE TITLE
tts净化规则默认按句子读

### ISSUE THREAD

**Issue by Benjamin-Watson0** [gedoor/legado#2600]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

当前只能按段读，而且段落换页时候，tts不换页，试过其他的软件，tts没问题。

我在其他的issues看到过精华规则的解决方法，我不懂这个，希望开源贡献者们可以满足我这小小的愿望

### 期望实现方式

tts净化规则默认按句子读（按句子断）

**Comment by lianbook** [comment]
有些句子太短，比如一句就三五个字。

**Comment by lianbook** [comment]
有些段落又太长，我建议分句，按文本长度 文本长度控制在一个区间…比如字符30到50的长度
