### ISSUE TITLE
上下翻页像素级滚动

### ISSUE THREAD

**Issue by Benjamin-Watson0** [gedoor/legado#2601]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

就是手机上看文章那种，阅读的时候往下滑，不知道是否能实现类似的内容

### 期望实现方式

向下像素级别滑动阅读（希望您能满足）

**Comment by 821938089** [comment]
翻页动画-滚动

**Comment by yafovo** [comment]
阻尼滑动，和 点击区域翻页 不能同时使用。。。【这是我最想吐槽的】（但是他左右滑动又能翻页，反而又增加了误操作）
刚开始没有滑动翻页后来加上了，但是也不好用，静读天下，这方面做的好很多。
现在我看书用点击区域翻页，看漫画用这个就不合适了，用阻尼滑动就好很多，但是每次改设置？
还有翻页的时候，加个设置可以保留上一页的最后一行。

**Comment by 821938089** [comment]
@yafovo 
你把漫画的书籍类型改成图片，翻页动画就会被覆盖为滚动。

滚动动画，点击滚动会保留一行

**Comment by yafovo** [comment]
> 

刚去看了一下设置，你说的漫画类型改成图片 我没找到。。

我刚看了设置，左右滑动翻页，导致误操作的问题已经解决了，
多了一个左右滑动翻页阈值的选项了，总算解决误操作的问题了。

**Comment by 821938089** [comment]
@yafovo 
在书籍信息右上角的编辑里面

**Comment by yafovo** [comment]
@821938089 找到了  Thanks♪(･ω･)ﾉ

**Comment by jacklaplace** [comment]
楼主需要的功能，我这试了，现在都有了，此主题可以关闭了吧。另外问问：

现在支持鼠标滚轮了吗？
我用的版本 3.22.052723，翻页动画是滚动，鼠标滚轮没有反应，左键单击倒是可以翻页。

然后在笔记本安卓模拟器上，鼠标滚轮也是不能控制滚动，但是笔记本触摸板用两个手指是可以控制滚动的，包括开启自动像素滚动翻页的时候，触摸板也可以同时控制向上滚或向下滚，鼠标滚轮还是不可以。

能否把鼠标滚轮和触摸板双手指滑动互相映射一样，以实现一样的功能？

关联以前有人提出过的主题：https://github.com/gedoor/legado/issues/1989
.
.

**Comment by jacklaplace** [comment]
如果开发者大大看到了这里，顺便提出一个建议，就是不限制字体字号、字体大小，现在最大是50，能否设置上限为80甚至100啊，用笔记本、平板、外接显示器、电视机来看小说的时候，字号50还是不够大。

**Comment by jacklaplace** [comment]
补上，谢谢各位大佬开发这么功能丰富的APP，辛苦辛苦！

**Comment by 821938089** [comment]
@jacklaplace 可以用滚轮翻页，你看看设置里面打开了没

**Comment by 821938089** [comment]
@jacklaplace 字号24我在电脑上看都超大了

**Comment by jacklaplace** [comment]
谢谢回复。设置里没找到啊。设置里有音量键翻页、自定义翻页按键，具体是哪个可以设置鼠标滚轮？你的阅读是什么版本？可能是我版本问题。

字号50大概食指指甲那么大，比拇指都小，不算超大吧？如果隔一米以上看显示器的话，还是希望越大越好哦。

**Comment by jacklaplace** [comment]
已经确认，最新版本 legado_app_3.22.120121-1，设置里有鼠标滚轮翻页这一项了。

剩下字号如果可以最大限制到100，已经很完美了！

**Comment by limne** [comment]
这是看小说还是看电视？这个不是手机app吗？

**Comment by jacklaplace** [comment]
@821938089 现在这个鼠标滚轮翻页，不得劲啊，跟鼠标左键单击一样一样的，就是翻页，这就功能重复重叠了呀，能否改进一下，因为滚轮本身就是控制平滑滚动的，做成像滚轮浏览txt、网页那样滚动，不知道行不行啊？

**Comment by 821938089** [comment]
@jacklaplace 弄起来麻烦，你用网页看吧，有web服务
