### ISSUE TITLE
为何备份的时候阿里云tts语音合成的登录key不备份；

### ISSUE THREAD

**Issue by lianbook** [gedoor/legado#2602]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

希望这个也可以备份。
直接备份登录的信息，如果怕泄露一些信息，可以用户单独开一个只用于语音合成权限的keyid

### 期望实现方式

直接备份登录的信息，如果怕泄露一些信息，可以用户单独开一个只用于语音合成权限的keyid

**Comment by 821938089** [comment]
key不是放在tts规则里面的，所以无法备份，你想要备份的话直接在规则里面写死key就可以了

**Comment by lianbook** [comment]
无语
