### ISSUE TITLE
谁有好用的书源推荐吗？

### ISSUE THREAD

**Issue by hymailto** [gedoor/legado#2603]
现在很多书源都不好使了，字词错误，甚至有些书源搞假更新，只有前面一小段，或者干脆就是无关的书内容放进来，防不胜防。

**Comment by yafovo** [comment]
https://xs11.lanzoul.com/i1YDa0azggle
试试这个？ 这是微信公众号上面推荐的，我也用的是这个，你可以自己去找找

**Comment by hymailto** [comment]
> https://xs11.lanzoul.com/i1YDa0azggle 试试这个？ 这是微信公众号上面推荐的，我也用的是这个，你可以自己去寻找

我不是这个意思。。。
一程大佬跟其他各位大佬的订阅源当然没问题，我说的是具体的书源，用来看老书挺好的，就是看最新的书有问题，比如深海余烬，最新章节总是有问题，怀疑是书源不好，有些是段落顺序乱了，有些是缺少末尾几段，还有些干脆就是把正版网站上的最前面一段放上来糊弄事儿。。。更过分的是完全放的是另一部书。
我目前在看的是天天看小说这个网站：cn.bg3.co
这个是墙外的，目前没找到关于他的书源，我老书用阅读app看，新书用这个网站在线看。只恨自己不会弄书源。

**Comment by 821938089** [comment]
这个源仓库有

**Comment by hymailto** [comment]
> 这个源仓库有

我看了，不是。只是名字一样，域名不是。源仓库里的那个也是有问题的。就以《深海余烬》为例，最近的几期都有段落调整的问题。

**Comment by 821938089** [comment]
你发的那个网址打开不是小说网站

**Comment by hymailto** [comment]
> 你发的那个网址打开不是小说网站

前几天还没事的，现在好像换网址了，自动跳转到另一个站

**Comment by hymailto** [comment]
现在我都是看全本老书了，新书去网站上看，app上的看不成，稍微有点热度的，都被处理过。

**Comment by thredreams** [comment]
这个没办法的，现在的盗版书比正版书都要晚三四天这样，而且再加上各个网站不同的防盗措施。

> 只有前面一小段

这个就是因为拿不到最新的正版内容，只爬了免费看的一小段。至于后面填充的无关内容大概确实是书源设置的问题，但相较而言也不是啥大事了。

有些书源看上去好一点，我觉得这是因为不同盗版网站的更新时间，更新频率不一样，但是换一本书，这个源可能就不好了。

**Comment by hymailto** [comment]
确实。最好就是那种更新可以慢，我能等，但是不要搞假更新。
这样的书源比较难找。


> 这个没办法的，现在的盗版书比正版书都要晚三四天这样，而且再加上各个网站不同的防盗措施。
> 
> > 只有前面一小段
> 
> 这个就是因为拿不到最新的正版内容，只爬了免费看的一小段。至于后面填充的无关内容大概确实是书源设置的问题，但相较而言也不是啥大事了。
> 
> 有些书源看上去好一点，我觉得这是因为不同盗版网站的更新时间，更新频率不一样，但是换一本书，这个源可能就不好了。

**Comment by 821938089** [comment]
如果你想要慢但不假的可以用147小说，69书吧，顶点小说，精华书阁，这些应该都符合你的要求。

**Comment by hymailto** [comment]
> 

对，我要的就是这种。我去看看。
