### ISSUE TITLE
阅读自带的正文净化章节名会误伤正常内容导致缺字

### ISSUE THREAD

**Issue by NONONO1V** [gedoor/legado#2606]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

如题

### 复现步骤

如题

### 阅读版本

3.22.112222

### Android版本

6

### 机型

mi 6

**Comment by 821938089** [comment]
既然没有导入净化，那怎么会误伤正常内容呢？

**Comment by NONONO1V** [comment]
> 既然没有导入净化，那怎么会误伤正常内容呢？

不清楚，但是正文确实缺少了章节名

**Comment by lianbook** [comment]
界面设置可以隐藏章节名，章节名你是不是隐藏了？

**Comment by Createanewpassword** [comment]
> > 既然没有导入净化，那怎么会误伤正常内容呢？
> 
> 不清楚，但是正文确实缺少了章节名

可能是书源本身就是缺少章节名的

**Comment by NONONO1V** [comment]
> > > 既然没有导入净化，那怎么会误伤正常内容呢？
> > 
> > 不清楚，但是正文确实缺少了章节名
> 
> 可能是书源本身就是缺少章节名的

源网页没有问题，正文规则也获取了全部

**Comment by NONONO1V** [comment]
![Snipaste_2022-12-01_19-13-11](https://user-images.githubusercontent.com/109849776/205038953-0d957387-a1ab-4147-b478-ef794cde0cc7.png)
https://gfnormal05at.com/h5/book-chapter-id-10115972-chapter_id-382131
正文规则section@p@html

**Comment by gedoor** [comment]
无法避免误伤,已经取消重复标题去除了
