### ISSUE TITLE
希望可以添加讨论功能

### ISSUE THREAD

**Issue by onvz** [gedoor/legado#2607]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

类似某个蓝色的读书app那种,可以对某章,某段,甚至是某个字,标点,划线,然后添加讨论,所有用户都可以看到,可以大家一起讨论,

### 期望实现方式

不知道,就是希望可以有这个功能,

**Comment by adhu2018** [comment]
阅读没有服务器的

**Comment by lianbook** [comment]
没必要

**Comment by Xwite** [comment]
｀
