### ISSUE TITLE
你好，希望能增加WEBDAV中文件夹的功能

### ISSUE THREAD

**Issue by gu2188** [gedoor/legado#2608]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

books下有其他小说分类目录无法显示

### 期望实现方式

期待

**Comment by 821938089** [comment]
已经有了

**Comment by gu2188** [comment]
是吗？我的版本号是3.22.120121，这没有啊

**Comment by gu2188** [comment]
![Screenshot_20221202_143013_io legado app release](https://user-images.githubusercontent.com/82312123/205230519-90ed0927-99db-4553-9de6-f62cf6367166.jpg)
![capture_20221202143345807](https://user-images.githubusercontent.com/82312123/205230671-2f7a4bca-d745-429a-b965-52740207be09.jpg)

**Comment by 821938089** [comment]
你用的什么webdav

**Comment by gu2188** [comment]
自己建的

**Comment by gu2188** [comment]
https://blog.csdn.net/weixin_34245749/article/details/90060786
https://blog.csdn.net/weixin_34294649/article/details/88663262
参考的是这两篇文章

**Comment by 821938089** [comment]
修好了，你装最新测试版就能显示了

**Comment by gu2188** [comment]
非常感谢！
