### ISSUE TITLE
关于书源管理

### ISSUE THREAD

**Issue by wilsonjor** [gedoor/legado#261]
能不能把在线书源网址做成可以添加到书源列表，只要点更新就可以了，自动校验把无效书源删除。

**Comment by db-one** [comment]
支持一下

**Comment by cathaysia** [comment]
这样搞会不会收到律师函

**Comment by db-one** [comment]
话说那个自动效验书源 的功能是怎么用的？ 我效验玩了之后 也没看到有显示哪些是正常 哪些是失效的？
要是可以在效验结束之后自动把无效的删除就好了

**Comment by cathaysia** [comment]
在校验后，失效的书源名称后面应当会追加“失效”字段，通过“搜索书源”可以进行过滤

**Comment by db-one** [comment]
> 在校验后，失效的书源名称后面应当会追加“失效”字段，通过“搜索书源”可以进行过滤

学习了  原来时候可能我前面的书源都是有效的    效验之后什么反应都没有    往下翻翻才看到失效的
