### ISSUE TITLE
目录正则无法选中以及使用逻辑的问题

### ISSUE THREAD

**Issue by ra1nbow2000** [gedoor/legado#2611]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

阅读本地txt小说时，发现目录分割不适合，便想切换另一个目录正则，遇到了于下两个问题，如有错误还请指正
1.关于目录正则选项界面，每个规则有一个选中按钮和一个开关按钮，不太理解其中使用的逻辑。就我使用体验来看，其和书源一样，目录正则只能使用一个。不像书源需要“开启”来作为搜索目标，目录正则选中了默认就是开启，没有选中的默认就是关闭，开关按钮似乎没有存在的必要，反而会对使用者造成迷惑。
2.在切换目录正则的时候，发现选定按钮锚定在了默认第一个规则上，无论是选中之后的哪一个规则都无法生效，把规则删除就直接无法选中了。复现过程参考了https://github.com/gedoor/legado/issues/1499 并关闭了“拆分超长章节”选项

### 复现步骤

打开软件，进入书架，点开将夜，打开目录，拉倒最底下，发现目录切割出错，如图所示（“数字+卷”前面应该有“第”字这个必要条件才能触发章节切割）
![Screenshot_2022-12-02-18-42-43-935_io legado play release](https://user-images.githubusercontent.com/32125748/205275080-657548bb-ee82-42a6-b1e5-3e8f1419dce5.jpg)
于是想要切换规则，发现无法切换，选定按钮锚定在了默认的第一个规则
![Screenshot_2022-12-02-18-46-50-437_io legado play release](https://user-images.githubusercontent.com/32125748/205275745-645fc0b5-5240-4f1c-9fe4-408b47258a0f.jpg)
尝试删除第一个规则，然后选中第二个规则，点击确定，结果如图所示
![Screenshot_2022-12-02-18-48-18-612_io legado play release](https://user-images.githubusercontent.com/32125748/205276029-45cc3493-771b-41ea-9c62-8c013ad453e3.jpg)
回到正文界面，点击右上角选项中的“更新目录”，再次进入目录界面，发现没有变化
在余下的十多本本地txt小说都触发了上述的问题，其中复现过程使用的将夜和体积最小的悟空传（规则本身没问题，但无法切换）已上传

### 日志提交

![Screenshot_2022-12-02-18-53-26-988_io legado play release](https://user-images.githubusercontent.com/32125748/205276951-a8d2dc4d-9e07-435d-bfc3-c0d28e7e9353.jpg)
![Screenshot_2022-12-02-18-53-38-719_io legado play release](https://user-images.githubusercontent.com/32125748/205276952-0f3b6419-256c-4270-b7c9-f12545734fdc.jpg)

### 阅读版本

3.22.120121

### Android版本

Android 11 miui 12.6 by xiaomi.eu

### 机型

xiaomi 9

### 其他信息

[《悟空传》（校对版全本）作者：今何在.txt](https://github.com/gedoor/legado/files/10140178/default.txt)
[《将夜》（校对版全本）作者：猫腻.txt](https://github.com/gedoor/legado/files/10140435/default.txt)

**Comment by 821938089** [comment]
左边的单选才是切换正则，你要把单选切换到你想要的正则上面

**Comment by ra1nbow2000** [comment]
> > 每个规则有一个选中按钮和一个开关按钮，不太理解其中使用的逻辑。就我使用体验来看，其和书源一样，目录正则只能使用一个。
> 
> 帮助文档中我已经写得很详细了，左边的按钮是针对当前书籍生效，更改当前章节的规则时，应当点选左边的按钮。 中间的开关是所有TXT书籍生效。 ![Screenshot_2022-12-02-22-06-34-083_io legado app release](https://user-images.githubusercontent.com/32198215/205310921-8ae2a5d6-08f5-42a3-a1a4-994795bde891.jpg)
> 
>

> 帮助文档中我已经写得很详细了，左边的按钮是针对当前书籍生效，更改当前章节的规则时，应当点选左边的按钮。 中间的开关是所有TXT书籍生效。 !
感谢解答，我大概理解“目录正则”的使用逻辑了，只要启用了就会像“替换净化”那样多个规则同时生效而不是像“书源”那样同时只能使用一个对吧。

**Comment by 821938089** [comment]
不明白为什么会无法切换，你明明只是在打开右边的开关，而不是切换左边的单选

https://user-images.githubusercontent.com/8674809/205336188-7e993a67-c708-40d7-8419-2785a7f0b660.mp4

**Comment by 821938089** [comment]
多个规则不会同时生效，只有一个会生效

**Comment by ra1nbow2000** [comment]
https://user-images.githubusercontent.com/32125748/205341409-45de92b2-277e-4065-94a8-8fa0145ebffb.mp4

**Comment by ra1nbow2000** [comment]
> 多个规则不会同时生效，只有一个会生效

那多个规则都“打开”的情况，如何确定是哪一个“生效”呢，是从上到下第一个吗

**Comment by 52fisher** [comment]
> 我现在了解了，感谢解答。我第一次知道换源按钮还有这个功能。不过“目录规则”不能在目录界面生效反而只能在换源界面生效是不是有点反常识🤔

书源管理 和 目录 页面的两个TXT目录正则 入口,功能都是异常的，因为平时很少用到，基本没维护

**Comment by 821938089** [comment]
第一次打开书籍的时候会自动选择一个合适的目录正则，这个是在已开启的目录正则里面选择的

**Comment by gedoor** [comment]
修复了目录里面目录规则修改后不生效的bug
