### ISSUE TITLE
默认分组

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#2621]
现在默认分组为啥可以删了，但删了分组会乱的，而且删了后咋恢复啊？还不如改回去，不能删默认分组
还有个小问题，其他设置里的源编辑框最大行数，之前误甚至到最大那个档次了，有bug翻不回来怎么办？
![Screenshot_2022-12-06-21-24-22-721_io legado app release](https://user-images.githubusercontent.com/106790230/205924241-1bc4f4c0-7f78-4e19-b3ea-0c418d4942b3.jpg)

**Comment by 821938089** [comment]
不用翻，可以直接输入数字的，你点一下就可以输入了

**Comment by 821938089** [comment]
默认分组删除后重新打开app会自动创建

**Comment by gedoor** [comment]
因为有人新建分组超过long最大值变成负数了,所以我把负数分组也弄成可以删除了,默认分组都是负数
