### ISSUE TITLE
cookie.getCookie获取不了cookie

### ISSUE THREAD

**Issue by NONONO1V** [gedoor/legado#2624]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

如题，搜索历史issue未解决问题

### 复现步骤

如题

### 阅读版本

3.22.120121

### Android版本

Android 6

### 机型

mi 6

### 其他信息

如题

**Comment by 821938089** [comment]
发一下书源

**Comment by NONONO1V** [comment]
> 发一下书源

https://github.com/mzbgf/guaner010225/blob/master/sources/guaner.json
晋江源-发现-我的收藏

**Comment by 821938089** [comment]
书源规则里没看到用了cookie.getCookie的地方
我登录了一下看好像也没问题啊

**Comment by NONONO1V** [comment]
> 书源规则里没看到用了cookie.getCookie的地方
> 
> 我登录了一下看好像也没问题啊

晋江文学-发现-收藏

**Comment by NONONO1V** [comment]
> 书源规则里没看到用了cookie.getCookie的地方
> 
> 我登录了一下看好像也没问题啊

\"我的收藏::http://app.jjwxc.org:80/androidapi/incrementFavorite?versionCode=185&token={{cookie.getKey('http://m.jjwxc.net','sid')}}&backupTime=&order=1\"

**Comment by 821938089** [comment]
你说一下你遇到了什么问题吧，我这里是没问题的啊

**Comment by NONONO1V** [comment]
> 你说一下你遇到了什么问题吧，我这里是没问题的啊

cookie.getCookie获取不了cookie
登录了看不了收藏

**Comment by 821938089** [comment]
我这里是可以看到收藏的，你重新登录一下试试

**Comment by NONONO1V** [comment]
> 我这里是可以看到收藏的，你重新登录一下试试

找到了，是我的问题，没打开cookiejar
