### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by unOmni** [gedoor/legado#2626]
newest update added an extra Title right under the normal Title.

**Comment by 821938089** [comment]
pls add screenshot for detail

**Comment by unOmni** [comment]
After

![Screenshot_20221210-153949_Legado.png](https://user-images.githubusercontent.com/106206117/206860881-c7fe8ecd-469a-49cc-bdab-ffd14f595361.png)

Before

![Screenshot_20221210-153109_Legado.png](https://user-images.githubusercontent.com/106206117/206860925-7c60dd49-8bcd-4a57-a69b-60001e3556f4.png))

**Comment by 821938089** [comment]
This is because the function of removing duplicate titles has the problem of being mistakenly removed, so it was deleted in the new version.
ref issue #2606

**Comment by unOmni** [comment]
Is there anyway to fix it manually

**Comment by 821938089** [comment]
If your title are in a fixed format, then you can use the Replace function to replace the title in the content with blanks.
e.g.  Pattern `^Chapter \d+\. .*`

**Comment by unOmni** [comment]
not all have a fixed format so doesn't work for all.

I'll just downgrade to last version for now

**Comment by gedoor** [comment]
最新测试版本已经解决这个问题,添加了开关,针对单个章节,默认开启去除重复标题
