### ISSUE TITLE
最新版本使用自建微软HTTP服务朗读跳段

### ISSUE THREAD

**Issue by jl0476** [gedoor/legado#2627]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

更新了最近的版本之后
使用自己搭建的微软晓晓语音服务朗读的时候
莫名的跳过段落
请看录屏

https://user-images.githubusercontent.com/5226690/206861586-6e5c5534-9e6a-41a4-a403-f9a57a2a5632.mp4

实际能看到调用情况
![image](https://user-images.githubusercontent.com/5226690/206861594-cd797848-c1e2-4aa3-9459-91a221caf64c.png)

### 复现步骤

选择自建语音朗读文章，
如果需要调试，我可以将地址和调用方法发给您

### 阅读版本

3.22.120819

### Android版本

12

### 机型

小米12s pro

**Comment by 821938089** [comment]
今天发了一个新版本，更新一下看看有没有问题
