### ISSUE TITLE
一些关于E-Ink模式的建议

### ISSUE THREAD

**Issue by BestGreed** [gedoor/legado#263]
以下是一些建议在E-Ink模式下加入的特性
1、书架页强制按页布局刷新和翻页。
2、去除更新时右上角转圈动画改为下划线或框选高  亮。或者一个静态的高辨识度的角标也可以
3、去除书架分组切换的动画。
4、允许修改书架里书名字体大小。
5、去除发现页的源被收起时的动画。
6、去除底栏点击特效。以及全部按钮的水波纹特效。
7、源刷新以及搜索加载的线条延伸指示改为点状指示。
8、添加一个退出APP的选项。关于这个主要是很多阅读器没有返回键啊xd
9、去除「我的」页各选项换页动画。
10、考虑接入部分开放式阅读器的全刷API。
简单归纳一下就是「动画全砍，一切从简。」
希望看到一个更加完善的「阅读」

**Comment by 52fisher** [comment]
E-Ink模式已经有所改善了，欢迎试用新版~感谢你的建议
