### ISSUE TITLE
从浏览器或者正文的搜索菜单搜索小说在进入详情后当前ui容易闪回前一步

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2630]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

从浏览器或者阅读的正文选中词语进入搜索小说时在小说详情选择阅读，经常会闪回到之前的主页面，不管之前界面是在正文或者书架

### 复现步骤

多次频繁的通过选中浏览器的词语开启阅读搜索就容易触发

### 阅读版本

3.22.121018

### Android版本

Android 12

### 机型

xiaomi 11青春版

**Comment by 821938089** [comment]
发个视频看一下

**Comment by zousizhe** [comment]
> 发个视频看一下


Uploading Screenrecorder-2022-12-12-19-54-03-59.mp4…


Uploading Screenrecorder-2022-12-12-19-53-34-356.mp4…

**Comment by zousizhe** [comment]
> 视频没发出来

https://wwc.lanzoux.com/ikHbI0ijg1oj

**Comment by 821938089** [comment]
装一下这个测试版看看好了没
https://kunfei.lanzoui.com/iBQy20ijqmub
