### ISSUE TITLE
webdav

### ISSUE THREAD

**Issue by Doddddd** [gedoor/legado#2631]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

1、坚果云会限制访问频率，希望可以自定义上传webdav的频率，或者可以手动关闭某些场景下的自动上传
![Screenshot_20221212_212441_legadoPro](https://user-images.githubusercontent.com/88972478/207056517-f3954d46-ed91-4882-94c9-f540d94cf1ab.png)
2、在重复报错后弹出toast

### 期望实现方式

自定义上传webdav的频率
手动关闭某些场景下的自动上传
重复报错后弹出toast

**Comment by lianbook** [comment]
要不用七牛云阿里云或者腾讯云百度云

**Comment by 821938089** [comment]
你把同步阅读进度关了就可以了
