### ISSUE TITLE
怎么增加百度的离线语音朗读

### ISSUE THREAD

**Issue by sdgey** [gedoor/legado#2632]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

怎么增加百度的离线语音朗读，度逍遥 | 武侠男声

### 期望实现方式

离线基础音库

**Comment by lianbook** [comment]
应该不支持。除非你自己写一个用于tts的引擎，或者你让写tts引擎的加入这个功能，但是百度语音合成离线sdk是付费的

**Comment by limne** [comment]
百度的直接用在线的，选mp3，不费流量的

**Comment by lianbook** [comment]
> 百度的直接用在线的，选mp3，不费流量的

在线需要联网，肯定要流量。

离线的那种试试。讯飞语记 或者谷歌的语音引擎

**Comment by Raytow** [comment]
> 百度的直接用在线的，选mp3，不费流量的

具体怎样操作？
