### ISSUE TITLE
校验具有验证码的源时闪退

### ISSUE THREAD

**Issue by liantn** [gedoor/legado#2640]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [x] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

如题，无XP
无论是上一个版本还是现在
我的另一个Android13设备也是同样的问题

### 复现步骤

详见附件

https://user-images.githubusercontent.com/81289991/208184039-1ed8f030-f86a-4c75-9e7d-2a306f4493fe.mp4

### 日志提交

SDK_INT=32
MODEL=M2104K10AC
RELEASE=12
MANUFACTURER=Xiaomi
versionName=3.22.121521
versionCode=12994
BRAND=Redmi
java.util.concurrent.ExecutionException: g0.s: Failed to load resource
	at v0.f.m(RequestFutureTarget.java:135)
	at v0.f.get(RequestFutureTarget.java:1)
	at r6.v2$a.invokeSuspend(VerificationCodeDialog.kt:71)
	at z9.a.resumeWith(ContinuationImpl.kt:9)
	at vc.m0.run(DispatchedTask.kt:119)
	at ad.g.run(LimitedDispatcher.kt:13)
	at bd.k.run(Tasks.kt:3)
	at bd.a$b.run(CoroutineScheduler.kt:82)
	Suppressed: vc.k0: [z1{Cancelling}@140ab1, Dispatchers.Main]
Caused by: g0.s: Failed to load resource
class g0.s: Failed to load resource
  Cause (1 of 1): class g0.s: Failed LoadPath{b->Bitmap->Bitmap}, REMOTE
    Cause (1 of 1): class g0.s: Failed DecodePath{b->Bitmap->Bitmap}

### 阅读版本

版本 3.22.121521

### Android版本

Android12

### 机型

POCO X3 GT

### 其他信息

[
  {
    "bookSourceComment": "// Error: org.mozilla.javascript.WrappedException: Wrapped u5.c: 验证结果为空 (<Unknown source>#6) in <Unknown source> at line number 6",
    "bookSourceGroup": "js失效",
    "bookSourceName": "⑱ 海棠书屋",
    "bookSourceType": 0,
    "bookSourceUrl": "https://www.beiyongzhan.me/",
    "bookUrlPattern": "",
    "customOrder": -88890259,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": true,
    "enabledReview": false,
    "header": "{\n\t\"cookie\":\"sotime=0\"\n\t}",
    "lastUpdateTime": 1671221267773,
    "loginUrl": "",
    "respondTime": 7658894,
    "ruleBookInfo": {
      "author": ".info@a@text",
      "coverUrl": "",
      "init": "",
      "intro": ".bd.2@html",
      "kind": "class.info@text&&class.status@text##作者：.*?类型：|字数：.*?人气.*|\\n##,",
      "lastChapter": ".list[0]@li[0]@text",
      "name": ".right@text",
      "tocUrl": "@js:\nindex = result.match(/全部章节列表...\\(共(\\d+)章节\\)/)[1];\nif(index>9){\naid=result.match(/javascript:goChapterList\\((\\d+)\\)/)[1];\n\nurl=\"https://www.beiyongzhan.me/mytool/getChapterList/\";\nverify=java.getVerificationCode(book.origin+\"/mytool/getVerify/?d=\"+Math.random());\nbody=\"verify=\"+verify+\"&aid=\"+aid+\"&sbt=提交\";\noption={\n\t\"method\":\"POST\",\n\t\"body\":String(body)\n\t}\nresult=url+\",\"+JSON.stringify(option)\n}else{baseUrl}",
      "wordCount": "class.info@text##作者：.*?字数：\\s*|\\s*人气.*\\s*"
    },
    "ruleContent": {
      "content": "<js>\ncontent={\n    childNode:[],\n    childNodes:\nresult.match(/nrid=\"([^\"]+)\";/)?java.getElements(\"#\"+result.match(/nrid=\"([^\"]+)\";/)[1]+\"@p\").toArray():\"\",\n    UpWz:function(m, i) {\n        var k = Math.ceil((i + 1) % this.code);\n        k = Math.ceil(m - k);\n        return k\n    },\n    load:function(){\n  this.code=String(result).match(/codeurl=\"(\\d+)\"/)[1];\n        var e =String(java.base64Decode(java.getString('[name=client]@content'))).split(/[A-Z]+%/);\n\n        for (var i = 0; i < e.length; i++) {\n            var k = this.UpWz(e[i], i);\n            this.childNode[k]=this.childNodes[i]\n        }}\n}\nif(title.match(/验证码/)){\n\tresult=\"如果没获取到目录，说明验证码不对，详情页刷新重新获取验证码\"\n}else{if(baseUrl.match(/\\d+_2\\.html/)){\ncontent.load();\nresult=content.childNode.join(\"<br>\");}else if(baseUrl.match(/\\/\\d+\\.html/)){\nresult=java.getElements(\"#contentinfo@p\")\n}else{\n\tresult=result.match(/html\\(d\\(\"([\\s\\S]+?)\",\".*?\\)\\)/)[1];\n\t}}\nresult+\"❎\"\n</js>",
      "nextContentUrl": ".curr+a@href##.*?(\\d+),(\\d+),(\\d+),(\\d+).*##/$1/$2/$3_$4.html",
      "replaceRegex": "##\\s*❎\\s*",
      "webJs": ""
    },
    "ruleExplore": {
      "bookList": ""
    },
    "ruleReview": {},
    "ruleSearch": {
      "author": ".info@a@text",
      "bookList": ".column-2",
      "bookUrl": "a@href",
      "checkKeyWord": "千方百计",
      "kind": "",
      "lastChapter": ".update@a@text",
      "name": ".name@text",
      "wordCount": ".info@span@text##字数："
    },
    "ruleToc": {
      "chapterList": "class.list.0@li@a||li@a\n<js>\nif(String(src).match(/验证码不对/)){\nresult=[{\"text\":\"右上角三点刷新重新获取验证码\"}]\n}else if(src.match(/请输入验证码/)){\tjava.setContent(result.toArray().reverse().join(\"\"))\n\tresult = java.getElement(\"a\")\n\t}\nelse{result=result}\n</js>",
      "chapterName": "text",
      "chapterUrl": "href"
    },
    "searchUrl": "https://www.beiyongzhan.me/s.html,{\n'charset': 'UTF-8',\n'method': 'POST',\n'body': 'wd={{key}}&submit=搜 索'\n}",
    "weight": 0
  }
]

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/commit/17a828cf409022fc3dcdd61042c6cb8e5f593ce2
