### ISSUE TITLE
弱弱的问一下，软件能设置代理吗？

### ISSUE THREAD

**Issue by kentcc88** [gedoor/legado#2642]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

发现有些挺好的小说网站需要代理才能访问，而想使用阅读进行收录，发现也采集不到里面的文章呢，请问有没有专门设置某个网站走代理的功能，这样的话，就感觉齐全了。

### 期望实现方式

当在看某个小说的时候，发现源都不满意，而在电脑上看到有些需要走代理的小说网站里的内容反而更完整，想在手机阅读软件里进行收录，但收录之后，却无法使用此源，原因是此网站需要走代理。。希望在手机阅读app里面，提供某个网站的源能走代理的功能。

**Comment by 821938089** [comment]
可以在书源里设置
