### ISSUE TITLE
能否为虚假更新的章节做自动重新下载和更新提醒功能

### ISSUE THREAD

**Issue by zhangzw218** [gedoor/legado#2646]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

盗版源现在出现两种：
1、一种是西红柿、147等有资源更新的，这种延迟大概7天左右，就会自动更新出来，没有虚假更新，这不是问题。
2、另一种是虚假更新的，它只更新了免费章节的前面一小部分。过几天手动刷新之后，才会有正式内容出来。
针对第二种，APP能否做一些处理？
如：指定字数以内的自动更新，比如指定300字以内章节自动重新更新，这个就和章节的预下载一样，在列表刷新的时候刷出来。
如：未阅读数量不包含未阅读章节，这就有一个要求，就是每一个章节都需要预下载之后，才能知道这个章节有没有正式内容。
只有新增的时候，才会一次性预下载几百章，正式阅读之后，一般每本书也就十章左右虚假更新。
需要每次打开APP的时候帮忙下载一下，有新的有效章节出来了，未阅读数量就显示1（这时候，未阅读数量，就不是根据目录，而是根据章节内容，或者说，根据章节字数判断了）
……
最后的最后，如果，我自己写一个控制台，从APP的调试接口进入，可以调用APP的书源来搜索书籍、目录、章节内容么？那个调试接口有这些调用方法么？

### 期望实现方式

1

**Comment by 821938089** [comment]
调试接口没有这些方法，你可以用web服务的接口，有目录、章节内容的方法。

**Comment by zhangzw218** [comment]
> 调试接口没有这些方法，你可以用web服务的接口，有目录、章节内容的方法。

我看了下，getChapterList和getBookContent对么。
我看参数传递的是url，那么返回的内容，是在线获取的，还是从手机上已经下载的数据中获取的？
这个我一时间不好测试，所以想直接问下。
1.如果这些数据是手机本地的，那么如何刷新内容，比如章节内容原本是假更新，现在需要重新更新，有办法通过接口来刷新本地内容么？我看只有手机上有刷新内容的按钮，web上好像没有。
2.如果这些数据是线上从互联网实时拉取的，那么网络上资源已经丢失了怎么办，有办法获取到手机上缓存的文本么。

**Comment by 821938089** [comment]
从手机上已经下载的数据中获取
没有刷新接口

**Comment by ydqsbfsyi** [comment]
也许是个简单的方法：每本书的下载弹框中，增加一个选项，可以选择：是否覆盖。。。这样即使原来下载的最后几章是虚假章节，如果今天真实章节来了，那么批量下载覆盖一次剩余章节，后面的虚假章节就一次性解决了。。。这样并不浪费资源，因为虚假章节就那么一些而已，不会出现重复下载上百章的情况。
