### ISSUE TITLE
目前我发现一个问题就是阅读的测试版本打开PDF还是会报错

### ISSUE THREAD

**Issue by zmyznu** [gedoor/legado#2647]
阅读 14点49分:
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@9b65dc4
阅读 14点49分:
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@eeaa77e
阅读 14点49分:
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@ec91a32
阅读 14点49分:
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@8c564e8
阅读 14点48分:
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@ca79f93
阅读 14点48分:
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@f134af7
阅读 14点48分:
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@a22481b
阅读 14点48分:
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@523cad2

**Comment by gedoor** [comment]
收到

**Comment by gedoor** [comment]
这个是图片被回收了,你把图片缓存设置小点试试

**Comment by zmyznu** [comment]
我回头试试
