### ISSUE TITLE
希望增加使用手柄翻页支持

### ISSUE THREAD

**Issue by fanqiedandan** [gedoor/legado#2653]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

躺在床上用平板支架看书的时候如果能用手柄翻页的话，就不用把手伸出被窝了

### 期望实现方式

希望能增加对手柄和其他无线控制器的翻页支持

**Comment by 821938089** [comment]
设置里有个自定义翻页按键，这个应该能支持
