### ISSUE TITLE
最新版本也存在这个bug

### ISSUE THREAD

**Issue by lhjgege** [gedoor/legado#2654]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

第一次添加想看的书点击换源书源全是空白。

### 复现步骤

第一次搜索电子书点击详情点击阅读进入点击返回键弹窗选择加入书籍，在自己书籍列表页进入刚才添加的电子书选择换源，换源界面一直空白搜索不出可换的源实际上有源的。把当前电子书删除重复上面的步骤又可以有书源可换了。

### 日志提交

。。

### 阅读版本

3.22.121521

### Android版本

鸿蒙3

### 机型

mate30

### 其他信息

。。

**Comment by 821938089** [comment]
发个视频看一下

**Comment by lhjgege** [comment]
[](url)

https://user-images.githubusercontent.com/20966610/209439710-f56bcb0c-8112-4d3a-81de-e972ab8bfe52.mp4

**Comment by 821938089** [comment]
是不是开了校验作者？

**Comment by lhjgege** [comment]
是的，开了校验作者

**Comment by 821938089** [comment]
你把校验作者关了就可以了

**Comment by lhjgege** [comment]
ok

**Comment by lhjgege** [comment]
开了校验作者就搜索不到，感觉是个bug啊。。。

**Comment by lhjgege** [comment]
有的时候能搜索到即使开了校验作者。

**Comment by 821938089** [comment]
你用的这个源的作者名有问题，在视频里他叫`@忘语`，而在大多数的书源中他叫`忘语`，你开了校验作者就会导致所有不叫`@忘语`的源都不会显示。

**Comment by lhjgege** [comment]
ok，谢谢了啊
