### ISSUE TITLE
建议将“还原”、“刷新”按钮挪到右下侧。

### ISSUE THREAD

**Issue by zhangweildlh** [gedoor/legado#2658]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

作为一个小说追更重度者，最长遇到的问题就是：当前小说网站没有跟进最新章节；小说网站更新章节内容后APP需要“刷新”。
1、对于第一个问题，需要频繁换源；
2、对于第二个问题，需要手动刷新章节。
因此，“还原”、“刷新”按钮的使用频率是非常高的。
目前，其放在右上侧很不方便。建议挪到右下侧！

### 期望实现方式

建议将“还原”、“刷新”按钮挪到右下侧。

### 效果演示

![微信截图_20221225160900](https://user-images.githubusercontent.com/62597291/209461712-1ab66bb2-deb5-4313-8422-d866cd9422ce.jpg)

**Comment by 821938089** [comment]
长按刷新按钮会弹出一个菜单可以刷新后面的章节

**Comment by zhangweildlh** [comment]
> 

@821938089   谢谢您的回复。因为每天阅读的小说数量比较多，而每一本小说每天只会更新1~2章节；每次进入小说阅读界面，右拇指按一下刷新即可。
所以“刷新”按钮的使用频率非常高。将其挪到右下侧，方便右拇指操作，有实际意义。
同理，因为每一本小说的更新章节较少，所以长按“刷新”按钮这个功能并不常用。
