### ISSUE TITLE
3.0的按键和点击翻页为啥有点迟钝？

### ISSUE THREAD

**Issue by ourfor-pp** [gedoor/legado#266]
翻页动画与2.0相比有两点不舒服:
1.按键或点击翻页明显感觉会延迟一下才触发动画
2.动画有点慢，不知道是否考虑加快速度或增加调节动画速度的操作

ps:应该不是手机原因吧
手机1+7pro， 官方氢os，安卓10

**Comment by gedoor** [comment]
这个,我再优化一下
