### ISSUE TITLE
阅读打开txt文件自动加入书架希望不要使用其他设置中的书籍存放位置

### ISSUE THREAD

**Issue by casselluu** [gedoor/legado#2662]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

目前我的本地书籍通过resilio sync在多个终端同步，在resilio sync中通过阅读打开txt文件发现书籍自动加入书架，但是却是将文件复制了一份到设置中的书籍保存位置，导致本地出现两份文件的情况，重复占用空间。

### 期望实现方式

希望能直接按书籍打开位置添加到书架

**Comment by 821938089** [comment]
不能，原有位置下次可能会无法访问导致书籍打不开。

**Comment by casselluu** [comment]
> 不能，原有位置下次可能会无法访问导致书籍打不开。

我的都在同一目录下，可以授予权限

**Comment by zousizhe** [comment]
通过阅读添加本地小说不会生成副本，使用关联方式打开阅读就会生成副本
