### ISSUE TITLE
WebDav books文件夹只有第一次能同步上，之后书架里添加的书一直同步不上去

### ISSUE THREAD

**Issue by wwwhahahaha** [gedoor/legado#2663]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

如题

### 复现步骤

如题

### 阅读版本

3.22.180823

### Android版本

Android 12

### 机型

Redmi k50

**Comment by 821938089** [comment]
上传失败提示是什么

**Comment by wwwhahahaha** [comment]
> 

没有失败提示，就是我在坚果云的books文件夹里没有新的同步内容，但是bookProgress文件夹里会记录有阅读记录的文件，books文件夹里正常不应该是书架的同步吗

**Comment by wwwhahahaha** [comment]
![image](https://user-images.githubusercontent.com/29722342/210039325-16ae8385-010a-4c43-89a9-cc304c63eeb9.png)
![image](https://user-images.githubusercontent.com/29722342/210039328-cb950976-4f99-4fd7-ac19-766624f5d58b.png)

**Comment by 821938089** [comment]
books文件夹是用来存你手动上传的本地书的
