### ISSUE TITLE
页面展示的文字在源码中顺序是错乱的，如何梳理正确的顺序

### ISSUE THREAD

**Issue by zhangzw218** [gedoor/legado#2665]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

求教，正文中每个字都死一个独立的元素，顺序在源码里面是错乱的，但是页面展示又是正确的，这个应该如何获取。
![image](https://user-images.githubusercontent.com/40768649/210131988-aa9e53ef-9eca-485d-9d54-a6579084ea52.png)

### 期望实现方式

这个是书源，网站也不是所有内容都需要二次加载，搜索：《我的战舰能升级》,这个可以出现
{
    "bookSourceComment": "",
    "bookSourceGroup": ".天星",
    "bookSourceName": "飞速中文",
    "bookSourceType": 0,
    "bookSourceUrl": "https://m.feiazw.com",
    "customOrder": -88903142,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": true,
    "enabledReview": true,
    "exploreUrl": "总点击榜::/top-allvisit-{{page}}/,{'webView': true}\n字数排行::/top-size-{{page}}/,{'webView': true}\n最新入库::/top-postdate-{{page}}/,{'webView': true}\n奇幻玄幻::/sort-1-{{page}}/,{'webView': true}\n武侠仙侠::/sort-2-{{page}}/,{'webView': true}\n都市小说::/sort-3-{{page}}/,{'webView': true}\n历史军事::/sort-4-{{page}}/,{'webView': true}\n游戏竞技::/sort-5-{{page}}/,{'webView': true}\n科幻灵异::/sort-6-{{page}}/,{'webView': true}\n同人小说::/sort-7-{{page}}/,{'webView': true}\n女频言情::/sort-8-{{page}}/,{'webView': true}\n其他小说::/sort-9-{{page}}/,{'webView': true}\n全部完本::/full-{{page}}/,{'webView': true}",
    "header": "",
    "lastUpdateTime": 1672479233551,
    "respondTime": 35274,
    "ruleBookInfo": {
        "author": ".block_txt2 a.0@text",
        "coverUrl": ".block_img2 img@src",
        "init": "",
        "intro": "#intr@html",
        "kind": ".block_txt2@p.1:2@text",
        "lastChapter": ".block_txt2 a.1@text",
        "name": ".block_txt2 h2@text"
    },
    "ruleContent": {
        "content": "#nr1@text",
        "replaceRegex": "",
        "webJs": ""
    },
    "ruleExplore": {
        "bookList": "",
        "name": ""
    },
    "ruleReview": {},
    "ruleSearch": {
        "author": "a.2@text",
        "bookList": ".nlist",
        "bookUrl": "a.1@href",
        "checkKeyWord": "",
        "coverUrl": "img@src",
        "intro": "p.0@text",
        "kind": "a.3@text&&span.-1@text##小说",
        "lastChapter": "",
        "name": "a.1@text"
    },
    "ruleToc": {
        "chapterList": ".chapter li a",
        "chapterName": "text",
        "chapterUrl": "href##$##,{\"webView\": true}",
        "nextTocUrl": "option@value"
    },
    "searchUrl": "/search.aspx?s={{key}}&submit=,{\n    \"headers\": {\"User-Agent\":\"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36 Edg/107.0.1418.56\"}\n}",
    "weight": 0
}

**Comment by 821938089** [comment]
建议放弃，需要解析css来还原内容，要写很多js来处理，非常麻烦。

**Comment by zhangzw218** [comment]
> 这个是前端处理的，不用管他，你把网页源码里面的加密内容解密出来就可以了。

能否指点一下大概的破解思路，F12有防破解的duebger，调试起来好麻烦。。我都不知道怎么入手。

**Comment by 821938089** [comment]
你用这个js文件替换掉原来那个，然后就可以调试了。
[show.js.txt](https://github.com/gedoor/legado/files/10328924/show.js.txt)
![image](https://user-images.githubusercontent.com/8674809/210174487-ee6d18cc-8a70-4bf0-beff-5d172398bc82.png)
你把这一行所调用到的代码提取出来然后放到阅读的正文规则里面执行就可以了。
这个js有非常多混淆，还原起来需要花很多时间，你有耐心的话可以慢慢捋。
atob是base64解码，这个可以换成阅读里面的函数。

**Comment by zhangzw218** [comment]
> 

你好，Content和update，是js里面的变量，这个有办法获取么？还是需要我获取页面信息之后，自己想办法用正则提取出来？

**Comment by 821938089** [comment]
获取页面信息再用正则提取

**Comment by zhangzw218** [comment]
@821938089 
好的，webJs应该怎么使用？我看教程没看懂。
假如说，我想在脚本注入中，调用方法修改页面元素，然后在正文中提取出来，我应该怎么做？
我尝试写,这样是无效的：
![image](https://user-images.githubusercontent.com/40768649/211153088-c0bc2b8d-fdb8-419e-8041-f57b9db7880a.png)

**Comment by 821938089** [comment]
webJs要有一个返回值，这个返回值将作为请求响应的内容返回，然后进行规则处理。
好像还挺简单的，你直接把那一行解密的JS贴进去就可以了。

**Comment by zhangzw218** [comment]
嗯，我看到好像是你说的那个用法，从其他源上面也找到类似的。
但我自己不知道为啥，怎么都不能达到想要的效果。
比如：
![image](https://user-images.githubusercontent.com/40768649/211153654-a4f12384-8f4f-4c0e-a0c1-5f09d66ef1e7.png)

**Comment by 821938089** [comment]
需要用webView访问才有效
