### ISSUE TITLE
希望书源列表能支持网站图标功能

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2667]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

通过名字来分辨书源经常有重复名的网站，要是加个图标功能的话在选择书源时更容易识别

### 期望实现方式

像chrome书签那样自动获取，或者支持手动定义

**Comment by zhangzw218** [comment]
你指的是有很多书源叫笔趣阁-1，笔趣阁-2这样么？
这其实就是做书源的时候对同名站点的编号，建议你可以自己修改成可以识别的名字，反正书源的名字可以随便改的，你改成笔趣阁-常用，笔趣阁-准确，这样的名字，都可以。
图标的话，这些通用网站，很多图标也很随便的。。
![image](https://user-images.githubusercontent.com/40768649/211154651-8f05ac99-bba5-4635-95df-be1471b5814d.png)
