### ISSUE TITLE
WEB端页面宽度增大一些

### ISSUE THREAD

**Issue by star-o0O** [gedoor/legado#2671]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

目前显示器应该至少是768P或1080P，现在WEB阅读的页面宽度最大只有960，看起来稍微小了一点，两边留白很多。能否再加大一些，比如1120/1280等

### 期望实现方式

页面宽度增加更大可选项

**Comment by Xwite** [comment]
https://github.com/gedoor/legado_web_bookshelf/commit/1c733aee891fd10bcbf1a2c63629d698235defb4
