### ISSUE TITLE
本地/webdav 来源的书从A设备同步备份后无法在B设备打开

### ISSUE THREAD

**Issue by kingfxx** [gedoor/legado#2672]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

本地/webdav 来源的书从A设备同步备份后无法在B设备打开,B设备打开时会出现找不到文件的错误,而且无法通过在B设备上直接从webdav下载修复,只能删掉书籍重新从webdav下载

### 复现步骤

1. 设备A 小米手机10pro,导入一个本地书籍到书架后,在软件内上传到webdav . / 如果是设备A 直接导入webdav的书籍之后再同步备份也会生成下面一样的错误
2. 在阅读内部点击备份生成备份文件
3. 设备B 小米平板5pro , 点恢复备份, 此时可以看到之前导入的本地书籍在书架上,但是无法打开,会显示找不到文件的错误
4. 设备B上选择从webdav导入书籍,可以看到之前上传的书籍,但是无法导入,图标显示该书已在书架.
5. 设备B :只能将书架上同步的书籍删掉以后,再从webdav重新导入,此时可以打开,阅读进度也可以同步过来.
6. 设备B: 如果此时再次点击恢复备份, 还是会出现和之前一样的错误

### 日志提交

暂无

### 阅读版本

3.22.122419

### Android版本

Andriod 12

### 机型

小米10Pro/小米平板5Pro

### 其他信息
建议:
备份选项中增加一个 是否备份 本地书籍 的选项,这样针对webdav/本地书籍可以只同步阅读进度,书籍本体可以在不同设备按需下载 ; 或者针对webdav的书籍增加同步link,可以同步的时候自动到webdav下载.

**Comment by 821938089** [comment]
将本地书籍通过阅读手动上传到webdav后备份，然后在另一台设备上恢复。
