### ISSUE TITLE
书架内本地书籍打开后显示自动换源，然后消失，无法再次添加

### ISSUE THREAD

**Issue by casselluu** [gedoor/legado#2674]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

如题，此问题多次多版本出现，书籍位置为书架默认本地，txt文件，确认未修改或移动。主要是无法再次通过内置添加本地功能添加，但外部txt直接打开可以自动添加并缓存到指定目录。之前有一次通过外部txt通过阅读打开后从书架中删除并删除源文件，然后可以再次通过添加本地添加。但此次上述操作无效果。之后通过备份还原至一天前，书籍未出现，但添加本地显示已添加，通过搜索功能搜到并打开阅读后出现在书架中。

### 复现步骤

添加本地添加的txt书，添加时能打开，有目录，过了几天打开就显示自动换源，返回后书从书架中消失，无法再次添加，可以用阅读打开该txt并自动缓存到指定路径，添加到书架

### 阅读版本

3.22.120121

### Android版本

HarmonyOS2

### 机型

华为Mate20

**Comment by 821938089** [comment]
你把自动换源关了看看能不能好

**Comment by casselluu** [comment]
自动换源在哪设置来着？我找半天没找到

**Comment by 821938089** [comment]
在阅读菜单的设置里面

**Comment by casselluu** [comment]
找到了，已经关上，看看之后还有没有这个问题
