### ISSUE TITLE
更新安卓12（ColorOSV12.1）后语音朗读忽大忽小

### ISSUE THREAD

**Issue by nixgnot** [gedoor/legado#2677]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

机型为oneplus7pro。app版本为最新egado_app_3.22.122419

更新ColorOSV12.1后，朗读功能出现问题。
具体为：一自然段全段文字声音变大，下一段又全段声音变小，下一段又变大，周而复始不停循环。所有书源均有问题。
感觉音量至少有一倍的差距。
已经尝试更换语音引擎，尝试讯飞、google、百度，问题均一样

### 复现步骤

必定出现

### 阅读版本

3.22.122419

### Android版本

Android 12

### 机型

oneplus7pro

**Comment by 821938089** [comment]
系统TTS的朗读是由对应的TTSApp完成的，阅读仅提供文字和语速等信息给系统TTS，这个问题与阅读无关。
你可以看看别的App调用系统的TTS有没有这个问题。

**Comment by nixgnot** [comment]
> 

已经尝试过直接用讯飞自身阅读（同样是分段的文字），并没有这个问题。
主要变大变小完全取决于文字分段，就很奇怪.....而且换用不同的tts问题也依旧

**Comment by nixgnot** [comment]
> 系统TTS的朗读是由对应的TTSApp完成的，阅读仅提供文字和语速等信息给系统TTS，这个问题与阅读无关。 你可以看看别的App调用系统的TTS有没有这个问题。

已经尝试过直接用讯飞自身阅读（同样是分段的文字），并没有这个问题。
主要变大变小切换完全取决于文字分段，就很奇怪.....而且换用不同的tts问题也依旧

**Comment by 821938089** [comment]
可能是系统问题，语音的播放是由系统TTS服务完成的，讯飞自身阅读可能是它自己播放的，所以正常。

**Comment by nixgnot** [comment]
问题已经解决。确认是手机自身声音平衡设置导致，左右声道不平衡导致的问题
（系统调用tts时默认会左右声道来回切换）
