### ISSUE TITLE
电纸书模式

### ISSUE THREAD

**Issue by AlongWY** [gedoor/legado#2678]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

增加一个电纸书模式，主要是减少各种动画效果

### 期望实现方式

1. 书架翻页直接一屏一屏翻页
2. 换源一屏一屏翻页

**Comment by 821938089** [comment]
主题模式选墨水屏

**Comment by AlongWY** [comment]
> 主题模式选墨水屏

似乎并不足够，特别是在目录页和换源的时候，动画效果还是很多
