### ISSUE TITLE
JXDocument创建部分有点问题

### ISSUE THREAD

**Issue by vinint** [gedoor/legado#2680]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

AnalyzeByXPath类

private fun strToJXDocument(html: String): JXDocument {
        var html1 = html
        if (html1.endsWith("</td>")) {
            html1 = "<tr>${html1}</tr>"
        }
        if (html1.endsWith("</tr>") || html1.endsWith("</tbody>")) {
            html1 = "<table>${html1}</table>"
        }
        return JXDocument.create(html1)
    }
    
其中JXDocument.create(html1)和JXDocument.createByUrl得到的结果不一致（会导致</link>丢失）

订阅源地址：https://api.feeddd.org/feeds/611f6a6065d23936d94a4368/rss

可以用这个地址验证下

### 复现步骤

同上问题描述

### 日志提交

无

### 阅读版本

3.22.122419

### Android版本

Android 13

### 机型

一加 ACE

**Comment by 821938089** [comment]
你遇到了什么问题？

**Comment by vinint** [comment]
在转换RSS时，默认应该使用的是html解析，会导致
<item>
            <title><![CDATA[悲伤，它并不总是一种自怜]]></title>
            <link>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ</link>
            <guid>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ</guid>
            <pubDate>Wed, 04 Jan 2023 01:04:50 GMT</pubDate>
            <description><![CDATA[悲伤，它并不总是一种自怜]]></description>
        </item>
变成——————
 <item>
     <title>&lt;![CDATA[悲伤，它并不总是一种自怜]]&gt;</title>
     <link>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ
     <guid>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ</guid>
     <pubdate>Wed, 04 Jan 2023 01:04:50 GMT</pubdate>
     <description><![CDATA[悲伤，它并不总是一种自怜]]></description> 
    </item>
    
 建议
 JXDocument.create(html1)
改成
val document = Jsoup.parse(html,Parser.xmlParser())
XDocument.create(document)

**Comment by vinint** [comment]
在转换RSS时，默认应该使用的是html解析，会导致

` <item>
            <title><![CDATA[悲伤，它并不总是一种自怜]]></title>
            <link>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ</link>
            <guid>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ</guid>
            <pubDate>Wed, 04 Jan 2023 01:04:50 GMT</pubDate>
            <description><![CDATA[悲伤，它并不总是一种自怜]]></description>
        </item>`

变成——————
 `<item>
     <title>&lt;![CDATA[悲伤，它并不总是一种自怜]]&gt;</title>
     <link>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ
     <guid>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ</guid>
     <pubdate>Wed, 04 Jan 2023 01:04:50 GMT</pubdate>
     <description><![CDATA[悲伤，它并不总是一种自怜]]></description> 
    </item>
`
建议
JXDocument.create(html1)
改成
val document = Jsoup.parse(html,Parser.xmlParser())
XDocument.create(document)

**Comment by 821938089** [comment]
这改不了，AnalyzeByXPath类不只是用来解析XML的。

**Comment by 821938089** [comment]
如果你想要用XML解析器的话可以用JS写。
```
<js>
doc = org.jsoup.Jsoup.parse(result, org.jsoup.parser.Parser.xmlParser())
java.setContent(doc)
</js>
//pubDate[text()]
```

**Comment by vinint** [comment]
我的意思是在使用
JXDocument.create(）方法时，还是判断下是html 还是单纯的xml来决定不同的引擎

我目前尝试使用RSS订阅
https://api.feeddd.org/feeds/611f6a6065d23936d94a4368/rss

自定义规则使用xpath,然后默认的引擎将
`<link>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ</link> `
识别成
`<link>https://mp.weixin.qq.com/s/Fk8mESPkFc5PnvAYuqclzQ`
那我用//link/text() 就获取不到文章的链接了
