### ISSUE TITLE
获取下一页url时遇到的问题

### ISSUE THREAD

**Issue by SmallAirplaneX** [gedoor/legado#2681]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

例如 

\<a onclick=abc()>下一页\</a>

var abc = function(){
       window.location.href = "url";
    }

这时应该怎么做

### 复现步骤

示例网址：http://m.xhbook.cc/book/13811/16030043.html

### 阅读版本

new

### Android版本

12

### 机型

huawei P30

**Comment by 821938089** [comment]
你可以把网页当文本来处理，直接取出那个url就可以了。

**Comment by SmallAirplaneX** [comment]
> 你可以把网页当文本来处理，直接取出那个url就可以了。
请问能具体一点吗，我不太清楚如何定位到html文本

**Comment by 821938089** [comment]
大概这样
```js
@js:[...result.matchAll(/window\.location\.href = "(.*?)";/g)][1][1]
```

**Comment by SmallAirplaneX** [comment]
感谢，虽然还是不懂
