### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by xingluo233** [gedoor/legado#2682]
1.有些书有分卷时，因为分卷算一个章节，而且里面啥都没有，导出时内容就变成了null，这样可能不太好，建议直接为空
2.那些正版书源，在目录里写了VIP标识的，导出时会把VIP标识那个锁也给导出来，建议不要导出锁

**Comment by zhangzw218** [comment]
这个是书源问题，你可以尝试去修改书源，将这些数据移掉。
如果实在不会写，可以发出来，找人帮忙。。

**Comment by xingluo233** [comment]
> 这个是书源问题，你可以尝试去修改书源，将这些数据移掉。
> 如果实在不会写，可以发出来，找人帮忙。。

vip标识确实是书源里可以去掉，但是导出时就不应该导出那个锁啊😂

**Comment by xingluo233** [comment]
@Xwite 能不能考虑下这两个建议，导出后的文件里章节标题有一把锁，真都很难看
