### ISSUE TITLE
两端对齐时会拉断破折号

### ISSUE THREAD

**Issue by entr0pia** [gedoor/legado#2683]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

设置为"文字两端对齐"时, 破折号被拉断, 见截图中两处破折号的不同

### 复现步骤

设置为"文字两端对齐"时, 找一本含破折号比较多的书, 总会遇到的

### 日志提交

![image](https://user-images.githubusercontent.com/30486766/210915595-e3f963d4-e579-4ce3-824f-1fb33c85c3ad.png)

### 阅读版本

3.23.01052249

### Android版本

Android 9

### 机型

文石 Nova2

### 其他信息

[[物语系列][01卷]化物语（上）.zip](https://github.com/gedoor/legado/files/10356876/01.zip)

似乎还有部分图片无法显示的问题

**Comment by gedoor** [comment]
没想到好的办法解决
