### ISSUE TITLE
TTS朗读时的翻页问题

### ISSUE THREAD

**Issue by 2980077544** [gedoor/legado#2685]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

选择仿真翻页模式，开启tts朗读功能。
如果当页的最后一个段落跨页，朗读到相应的字句不会翻页到正在读的内容。

### 复现步骤

同问题描述

### 阅读版本

3.23.010623

### Android版本

Android 11

### 机型

Redmi Note 10 Pro

**Comment by 821938089** [comment]
打开朗读设置里面的按页朗读功能

**Comment by gzyguo** [comment]
“朗读到相应的字句不会翻页到正在读的内容”
那会发生什么？

**Comment by 2980077544** [comment]
https://t.wss.ink/f/a7gkp0d1v3x 如视频，本页最后的段落里tts已经读到后一页的内容，但未翻页，直到该段内容读完。

**Comment by 2980077544** [comment]
是我的问题，开启按页阅读就行了•﹏•
