### ISSUE TITLE
从AOSP的文件管理器里的Android Samba Client添加的局域网文件夹打开书籍的时候报错

### ISSUE THREAD

**Issue by gzyguo** [gedoor/legado#2686]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

Attempt to invoke interface method booleanjava.util.Enumeration.hasMoreElements(' on a nullobject reference

是epub

### 复现步骤

从AOSP的文件管理器里的Android Samba Client添加的局域网文件夹打开书籍的时候报错

### 阅读版本

3.22.110823

### Android版本

12

### 机型

Oneplus 7 Pro

**Comment by 821938089** [comment]
先把书复制到你的手机里面再打开

**Comment by gzyguo** [comment]
> 先把书复制到你的手机里面再打开

那是不是需要把bug改成需求，如果想要直接打开的话
