### ISSUE TITLE
用那个是不是A12的新功能，Quick Settings media player，弄一个呗，多时尚

### ISSUE THREAD

**Issue by gzyguo** [gedoor/legado#2688]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

在QS显示TTS控制通知

### 期望实现方式

像Play Books一样

**Comment by gedoor** [comment]
发个截图看看,不知道说的是什么

**Comment by gzyguo** [comment]
![image](https://user-images.githubusercontent.com/14918112/211207859-854b4133-7286-49e9-9d93-0bc5e8c6ca6e.png)
![image](https://user-images.githubusercontent.com/14918112/211207885-bffe9d99-fd06-4dee-9475-7c096645ae45.png)

**Comment by pwd-github** [comment]
Yes, please use the Android Media Widget

https://developer.android.com/guide/topics/media/media-controls

https://developer.android.com/reference/android/widget/MediaController

**Comment by darkj2k** [comment]
這個也支持在鎖屏控制，語音朗讀時要暫定或停止不須解鎖、進App再按暫停或停止語音播放，非常方便。

**Comment by pwd-github** [comment]
> 這個也支持在鎖屏控制，語音朗讀時要暫定或停止不須解鎖、進App再按暫停或停止語音播放，非常方便。

确切地说，现在他们的音频控制有点坏了。 它说没有标题。 如果我们能得到这个，那将是完美的，即使对于像我这样的西方人也是如此。

**Comment by pwd-github** [comment]
Any chance to see this?

**Comment by pwd-github** [comment]
希望我们能看到它。這是我們所缺少的不多之一件事。
