### ISSUE TITLE
日间模式底栏颜色调整无效的bug

### ISSUE THREAD

**Issue by agutools** [gedoor/legado#269]
修复夜间模式底栏颜色调整无效的bug的同时，能否把日间模式中同样问题也修一下

**Comment by gedoor** [comment]
日间模式没问题吧

**Comment by waloyn** [comment]
> 日间模式没问题吧

我的最近几个版本，亮色主题的顶栏都是黑的，是暗色主题的顶栏，只有把主题换成墨水屏才正常。

**Comment by gedoor** [comment]
可以自己重新调一下颜色

**Comment by waloyn** [comment]
> 可以自己重新调一下颜色

嗯，刚试了下，修复了，之前几个版本调了没效果，后面就没试了。
