### ISSUE TITLE
希望在WebDev备份文件夹里放一个指引如何手动恢复的txt文件。

### ISSUE THREAD

**Issue by huangsijun17** [gedoor/legado#2693]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

在WebDev备份文件夹里放一个指引文件。

### 期望实现方式

备份时同时检测是否存在说明文件，无则生成一个。

### 附加信息

前些天手机坏了，所以去手动恢复数据。搞了半天才发现需要解压zip到设定的文件夹才能恢复。

**Comment by 821938089** [comment]
不能通过WebDav恢复吗？

**Comment by huangsijun17** [comment]
> 不能通过WebDav恢复吗？

新版本不同机型备份的时不同的文件。恢复时需要把机型改成别的设备，再改回来。
而且，我也不想手动输入WebDav设置。虽然最后发现备份里居然没有WebDav设置。

**Comment by 821938089** [comment]
我加在了这里，应该可以了。
![image](https://user-images.githubusercontent.com/8674809/211245464-197a3d4e-0449-4f50-8d7e-667a631ffe00.png)
