### ISSUE TITLE
更换书源后希望数据保留

### ISSUE THREAD

**Issue by old-yellow-ox** [gedoor/legado#2695]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

现在换源后，软件会重新创建缓存文件夹并获取书籍数据。但是有时候正在使用的网站换了域名，给书源修改成新域名后原来的书源等于没了，之前的书籍就不能看了，需要换到修改后的新源。
希望这种情况下原来的数据能保留，主要是漫画换源后所有数据重新缓存太慢了，也太麻烦了。

### 期望实现方式

换源时，能不能增加一个选项，是否保留该书原有的数据。如果保留的话，将原来的书籍缓存文件夹名称改一下，直接使用原来的数据，如果不保留就新建文件夹并下载数据。
这种情况不太多，可以考虑加在书籍内长按换源的选项中。（现在是单章换源和整书换源，加一个保留数据换源）。
谢谢。

**Comment by gedoor** [comment]
我看看,应该可以弄下
