### ISSUE TITLE
epub TTS读10分钟左右就回到章首去读了

### ISSUE THREAD

**Issue by gzyguo** [gedoor/legado#2696]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

感觉几乎每次了吧

每次听的时间都不长，就听一会，听一小会就回去了，正好回到章首

但好像把app放到前台就没事，因为平时都在后台放，我再测测前台

### 复现步骤

是在完全退出app后，关屏幕，媒体键播放，就这样10分钟基本上就会回去，两个手机都这样，1+5和1+7都是LOS19

### 阅读版本

3.22.110823

### Android版本

LOS 19.1

### 机型

Oneplus 5

### 其他信息

想放日志来着但是没找到，有日志可以上传吗？是app日志？

**Comment by 821938089** [comment]
后台朗读不知道为什么会有问题，所以尽量前台朗读。
日志在书架右上角三点里面。

**Comment by 821938089** [comment]
那应该是epub的问题

**Comment by gzyguo** [comment]
对不起我现在能够确定的东西不是很多，我会再多观注。但是我平时在读多本书用2个手机，都是会重复TTS完整章节。

**Comment by gzyguo** [comment]
换了一本书看了一下还是每章都会重复显示也重复朗读，前台也试了一下也还是会重复，我上传一本。
[02 偶然的创造 9787020146161.zip](https://github.com/gedoor/legado/files/10401766/02.9787020146161.zip)

**Comment by 821938089** [comment]
这个是bug，刚刚修复了

epub建议使用别的app看，阅读对epub兼容性一般，有很多问题
