### ISSUE TITLE
界面美观性的思考

### ISSUE THREAD

**Issue by Benjamin-Watson0** [gedoor/legado#2699]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

阅读界面初始的UI我感觉不是很美观，虽然在酷安已经有很多人分享了自己的样式可以复制到阅读里面。我寻思着怎么不内置2个好看的，哈哈，虽然不影响使用，但是还是觉得挑两个您认为比较好的，内制在里面也挺好。

### 期望实现方式

内制更美观主题

### 附加信息

这个事情不是很重要，您图一乐就好，谢谢开发者❤️❤️❤️

**Comment by gedoor** [comment]
正准备征集几个美观的配置作为默认界面

**Comment by Benjamin-Watson0** [comment]
收到
