### ISSUE TITLE
web服务 小说阅读接口 优化

### ISSUE THREAD

**Issue by cqwuzonglin** [gedoor/legado#270]
1,接口图书排序一致.
![image](https://user-images.githubusercontent.com/45115566/87005540-bbc8ce80-c1f1-11ea-991f-5bfd099c223c.png)
2.接口阅读图书进度保存.
![image](https://user-images.githubusercontent.com/45115566/87005633-e581f580-c1f1-11ea-9972-52486969d1c6.png)
感谢!!

**Comment by cqwuzonglin** [comment]
我搞了个APP web阅读配套的摸鱼工具 
![image](https://user-images.githubusercontent.com/45115566/87006360-1e6e9a00-c1f3-11ea-8e9f-feb8eda45a71.png)

**Comment by gedoor** [comment]
ok
