### ISSUE TITLE
换源的时候列表会增加相同类型的书

### ISSUE THREAD

**Issue by lhjgege** [gedoor/legado#2701]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

在看电子书时候选择换源，不同书源在电子书列表会出现相同的电子书只是书源不同。

### 复现步骤

阅读界面随便电子书选择换源就会复现

### 阅读版本

3.23.011022

### Android版本

鸿蒙3

### 机型

mate30

**Comment by 821938089** [comment]
什么意思？换源不就是同一本书吗？只是网站不同而已。

**Comment by lhjgege** [comment]
是同一本书，但是在书籍列表就会出现不同书源的同一本书，包括漫画也是一样

**Comment by lhjgege** [comment]
。。。我刚才想录制视屏给你看，但是不会复现了。

**Comment by lhjgege** [comment]
[](url)

https://user-images.githubusercontent.com/20966610/211993455-68107dd9-1799-4fe5-bd83-da55422544cd.mp4

**Comment by lhjgege** [comment]
上面就是我同一个漫画不同漫画源。在书籍列表就出现两本相同的

**Comment by lhjgege** [comment]
复现概率挺大的

**Comment by 821938089** [comment]
书名作者不同不算一本书，你换源的时候勾选一下校验作者就可以了。

**Comment by lhjgege** [comment]
行吧，勾选校验作者有时候搜不到书。看来还是书源的问题
