### ISSUE TITLE
tts朗读至下一章出错

### ISSUE THREAD

**Issue by ranqianchen** [gedoor/legado#2702]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

tts朗读至下一章出错，总会断掉
我被折磨三天了，tts重度用户

### 复现步骤

朗读至下一章就跳回书架了
https://user-images.githubusercontent.com/65606785/212297631-cd5f3ef6-cf6b-4a53-8acd-5df02c93a058.mp4

### 阅读版本

3.23.011022

### Android版本

Android 10

### 机型

realme q2

**Comment by 821938089** [comment]
发下日志：
1、书架右上角三点里面有日志
2、我的->关于->崩溃日志

**Comment by ranqianchen** [comment]
> 发下日志： 1、书架右上角三点里面有日志 2、我的->关于->崩溃日志

1. 是 18点17分的那个，那个也中断了

![image](https://user-images.githubusercontent.com/65606785/212301273-f6290ebc-95b8-4858-bb29-62d89fcbf7fc.png)

2. 第二个，没有崩溃日志QAQ

**Comment by 821938089** [comment]
你装个Logcat Reader，打开它，然后你复现一下，然后把Logcat Reader里面的日志保存发过来。

**Comment by 821938089** [comment]
把你用的TTS源发一下，我试试看有没有问题

**Comment by ranqianchen** [comment]
> 把你用的TTS源发一下，我试试看有没有问题

大佬我忙着做作业，我明天搞搞
这是我tts，要科学上网
{
  "concurrentRate": "",
  "contentType": "audio/mpeg",
  "enabledCookieJar": false,
  "header": "{\"Content-Type\":\"text/plain\",\"Authorization\":\"Bearer \",\"Format\":\"audio-48khz-192kbitrate-mono-mp3\"}",
  "id": 1671767312174,
  "lastUpdateTime": 1673610802275,
  "loginCheckJs": "",
  "loginUi": "",
  "loginUrl": "",
  "name": "微软TTS（云皓）",
  "url": "https://ms-ra-forwarder-01-5d3beqhf0-ranqianchen.vercel.app/api/azure,{\"method\":\"POST\",\"body\":\"<speak xmlns=\\\"http://www.w3.org/2001/10/synthesis\\\" xmlns:mstts=\\\"http://www.w3.org/2001/mstts\\\" xmlns:emo=\\\"http://www.w3.org/2009/10/emotionml\\\" version=\\\"1.0\\\" xml:lang=\\\"en-US\\\"><voice name=\\\"zh-CN-YunhaoNeural\\\"><mstts:express-as style=\\\"general\\\" styledegree=\\\"1.0\\\"><prosody rate=\\\"{{(speakSpeed - 10) * 2}}%\\\" pitch=\\\"+0Hz\\\">{{String(speakText).replace(/&/g, '&').replace(/\\\"/g, '"').replace(/'/g, '&apos;').replace(/</g, '<').replace(/>/g, '>')}}</prosody> </mstts:express-as></voice></speak>\"}"
}
