### ISSUE TITLE
更新后本地书籍显示加载中，好像上次更新也是，都需要重新导入，都不知道从哪找了😥

### ISSUE THREAD

**Issue by wlioi** [gedoor/legado#2703]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

如题，从网络备份恢复也没有变化。

有的书籍还要为每个书籍设定文件夹。这个可能和鸿蒙的权限系统变化有关吧，但是更新以后不知道之前的位置，找不到原来在哪放着呀。

另外的担心：不知道以后更新会不会出现要重新导入本地书籍的问题，如果是的话尽量不更新，但是哪天不注意更新了就又完蛋了。

### 复现步骤

更新APP

### 阅读版本

3.23.011022

### Android版本

鸿蒙3.0 193

### 机型

华为matepadpro12.6

**Comment by 821938089** [comment]
你重新设置一下书籍保存位置应该就可以了

**Comment by wlioi** [comment]
> 你重新设置一下书籍保存位置应该就可以了

上面写了，找不到原来的位置，有好几本书，存放在不同的位置，用各种方法下载到设备

**Comment by 821938089** [comment]
你去系统的文件管理那里全局搜索一下书名应该就能找到

**Comment by 821938089** [comment]
你把书整理一下，都放到一个文件夹里

**Comment by wlioi** [comment]
每次都移动真的很麻烦，过段时间就移动一次书籍，那要找的文件夹就太多了

> 你把书整理一下，都放到一个文件夹里
每次下载都移动一次很麻烦，如果过一段时间移动一次，那要找的文件夹就太多了

**Comment by 821938089** [comment]
从别的app调用阅读打开书籍，阅读会复制一份到书籍保存目录那里

**Comment by wlioi** [comment]
> 从别的app调用阅读打开书籍，阅读会复制一份到书籍保存目录那里

这样，找到了👍
