### ISSUE TITLE
本地书籍使用编辑内容功能，存在缺陷

### ISSUE THREAD

**Issue by tangshg** [gedoor/legado#2704]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

1、导入本地书籍，使用编辑内容功能，右上角点击保存。
2、此时阅读app中的书籍内容已是编辑后的内容。
3、使用文件管理器打开本地书籍，内容仍是编辑前的。

### 复现步骤

如问题描述

### 阅读版本

3.22.110823

### Android版本

Android 12

### 机型

Redmi k30

**Comment by gedoor** [comment]
阅读编辑不更改文件,你可以等都改好了再导出一下
