### ISSUE TITLE
从wifi网络切换到数据网络会停止朗读

### ISSUE THREAD

**Issue by nobk** [gedoor/legado#2707]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

如题

### 复现步骤

重现方法：在听书时，打开手机的数据网络，关掉wifi

### 阅读版本

a7c7f4a578c41baa336084ddd6fbee20f55d9c84

### Android版本

Android 12

### 机型

Redmi note11t pro

**Comment by 821938089** [comment]
录个视频看一下

**Comment by 821938089** [comment]
你这样都不在局域网里了，那肯定访问不了啊

**Comment by nobk** [comment]
但不应该一切换网络，访问不了webDAV就停止朗读吧。

**Comment by 821938089** [comment]
这个应该没有关系，你说的问题我测试不出来，我也不知道发生了什么

**Comment by nobk** [comment]
那先挂着吧，有和我类似环境的应该能重现这个bug，MIUI v13.2.3，Android 13

**Comment by 821938089** [comment]
日志有没有东西啊？
日志在书架右上角三点里面

**Comment by nobk** [comment]
日志只有webDAV阅读进度超时，但切换网络后阅读停止是立刻的，并没有等任何超时。而且阅读状态没改变，点状态栏进阅读节目，依然是正在朗读的行高亮，只是不走了。点下一页，或者停止后再点朗读，可以恢复TTS朗读。我用的是本地TTS，讯飞或者谷歌的，阅读人已经下载到了本地，不是在线TTS。
![Screenshot_2023-01-16-20-34-48-767_io legado app release-edit](https://user-images.githubusercontent.com/4659870/212680018-8f023ce5-c520-4788-bd84-c637773b9b87.jpg)

**Comment by nobk** [comment]
补充：手机开wifi时，如果对wifi热点重启，导致手机暂时断开互联网，也会立刻停止朗读。
