### ISSUE TITLE
希望每次停止语音播放，再启动的时候，要从上一次停止的地方继续，而不是重头再来

### ISSUE THREAD

**Issue by clacf** [gedoor/legado#2708]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

希望每次停止语音播放，再启动的时候，要从上一次停止的地方继续，而不是重头再来。
当前每次需要重头再来，会耽误很多时间。

### 期望实现方式

希望每次停止语音播放，再启动的时候，要从上一次停止的地方继续，而不是重头再来。

**Comment by 821938089** [comment]
你可以手动跳转一下，朗读菜单那里有快进快退的按钮

**Comment by clacf** [comment]
> 

虽说不错，但是还是挺麻烦。比方说有人跟你说话，你单击耳机暂停，再看的时候，还得打开手机，就不太方便了。可以参考下讯飞有声的操作逻辑。

**Comment by limne** [comment]
tts朗读又不是音乐播放器
