### ISSUE TITLE
设置两端对齐的时候，英文单词内的字母间距会改变。正常的应该是单词之间的距离改变。

### ISSUE THREAD

**Issue by wuqiong4945** [gedoor/legado#2709]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

正常的应该是单词之间的距离改变，而单词内字母的距离是不变的。参考word里面设置两端对齐。

### 复现步骤

打开一个英文文件，设置两端对齐
![Capture](https://user-images.githubusercontent.com/1294412/213104452-e5fa6432-2479-4aed-86de-820c7e102b83.PNG)

### 阅读版本

3.23.011022

### Android版本

Android 12

### 机型

Galaxy A90

**Comment by gedoor** [comment]
ok

**Comment by gedoor** [comment]
已修改,等新版本
