### ISSUE TITLE
能不能把阅读的那个，更新日志，关注公众号那个地方增加一个确定按钮或者是收到按钮

### ISSUE THREAD

**Issue by zmyznu** [gedoor/legado#2710]
希望类似的说明文档控件可以增加，我知道了或者是收到按钮，或者是确定的无障碍按钮，谢谢开发者

**Comment by AnLazyOtter** [comment]
听起来还是挺有意义的。
这个需求换个表达来说，应该是
> 希望为更新日志页面添加‘关闭’按钮，以满足视障人群在更新版本后，可以直接找到关闭更新日志弹窗的按钮来关闭弹窗，而非听完一大堆内容后发现必须用返回按钮来关闭该弹窗。
> 另外，该关闭按钮应当在较为靠前的界面顺序中。

**Comment by gedoor** [comment]
ok

**Comment by AnLazyOtter** [comment]
> ok

对了，如果有条件的话， 是否考虑对同类弹窗都实施类似的改造呢？
例如：
* “备份与恢复”界面中的问号帮助弹窗
* 书源管理界面帮助这个二级弹窗
* 其他同类样式的帮助页面
