### ISSUE TITLE
安卓12无法备份

### ISSUE THREAD

**Issue by NONONO1V** [gedoor/legado#2712]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

![IMG_1049](https://user-images.githubusercontent.com/109849776/213421803-59684bc6-82e1-4251-bf72-124ab4fa9e55.JPG)
如图

### 复现步骤

如题

### 阅读版本

3.22.011022

### Android版本

Android 12

### 机型

墨案air

### 其他信息

如题

**Comment by 821938089** [comment]
更新最新版（刚刚发的）然后给存储权限

**Comment by NONONO1V** [comment]
> 重新设置书籍保存目录或 更新最新版（刚刚发的）然后给存储权限

解决了
