### ISSUE TITLE
同步功能建议借鉴joplin

### ISSUE THREAD

**Issue by qxbug** [gedoor/legado#2713]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

joplin的同步功能里主要可以直接onedrive,我觉得还是比较有现实意义

### 期望实现方式

![520CE271-3183-4330-B91F-4714175FB17D](https://user-images.githubusercontent.com/32385072/213456780-f4c026a7-bf9e-4df0-b342-7d6553abc0d6.png)

**Comment by Xwite** [comment]
Duplicate of #1821 closed
