### ISSUE TITLE
在恢复webdav中的备份时，不显示某日期后的备份

### ISSUE THREAD

**Issue by DreamerDK** [gedoor/legado#2714]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

在从坚果云的webdav中恢复备份时，某些备份不会被拉取，不在列表中显示，而在网盘中看是有这些备份的。

![Screenshot_2023-01-19-20-36-04-515_com miui home](https://user-images.githubusercontent.com/5880281/213457744-da482a63-1f6f-4243-bfe1-de727863e87c.jpg)

### 复现步骤

每次恢复都一样

### 阅读版本

3.23.011918

### Android版本

Android 12

### 机型

Redmi K20 Pro Premium Edition

**Comment by 821938089** [comment]
不介意的话发一下你的账号密码让我测试一下是什么问题

**Comment by DreamerDK** [comment]
已近试出来了，估计是webdav里的备份太多了，从20年到现在的都在。
我删了760多个，现在没问题了，可能超过800个或者多少个的就不显示？

![Screenshot_2023-01-19-21-46-33-906_nutstore android](https://user-images.githubusercontent.com/5880281/213465550-89b80135-e593-4052-8347-676f5d09e77f.jpg)

删除以后正常显示了

![Screenshot_2023-01-19-22-16-36-030_io legado app release](https://user-images.githubusercontent.com/5880281/213465563-c5a33cb0-f9b7-4fa5-8798-79b7fce5f3d6.jpg)
