### ISSUE TITLE
能不能给阅读的测试版上传最新的正式版本包，谢谢

### ISSUE THREAD

**Issue by zmyznu** [gedoor/legado#2715]
因为我装的是原包名，但是我又想更新到正式版本，可惜签名不一致会导致我更新不上去，希望发一个正式版本的包，然后呢，签名是和测试版本的签名是一致，这样我就可以直接随心所欲更新了，希望开发者能做到这样，谢谢

**Comment by 821938089** [comment]
你直接装最新的测试版不行吗

**Comment by zmyznu** [comment]
好的，谢谢开发者，已等待了新的测试包，谢谢
