### ISSUE TITLE
希望滑动或者翻页不要打断并重定位朗读

### ISSUE THREAD

**Issue by XY50** [gedoor/legado#2720]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

希望滑动或者翻页不要重定位朗读，可以添加一个从此处开始朗读的按钮

### 期望实现方式

滑动或者翻页时不要打断朗读，可以添加一个从此处开始朗读的按钮，就像番茄小说这样

https://user-images.githubusercontent.com/121076219/213974272-904c5cf5-6a02-4394-82a1-46cc17e8ffea.mp4

### 附加信息

有时候没听清楚朗读的是什么滑回去看的时候，朗读就被打断了，而且翻页方式设为滑动还卡卡的，非常影响使用体验

**Comment by XY50** [comment]
各大阅读软件的解决方案分别为
【从本页开始朗读的按钮】
【长按某一段内容后点击从此处朗读】
【单击或双击某一段内容后从那段内容开始朗读】
【翻页或滑动后显示''回到当前朗读位置按钮''】
根据软件不同叫法和位置都不一样

**Comment by XY50** [comment]
翻页和滑动不重新定位朗读这个功能非常实用，希望能尽快支持！
支持这个功能之后还能自动解决，朗读时滑动卡顿、朗读时滑动导致文本高亮与音频错位的问题，一举多得

**Comment by limne** [comment]
一边听一边看？
