### ISSUE TITLE
Web书籍进度精确到每一章的已读字数

### ISSUE THREAD

**Issue by ZZFFLL** [gedoor/legado#2721]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

# 问题：手机端开启Web服务后其他端阅读进度进度不一致
例如在PC端，点某本书进来开始阅读时，会直接从某一章的开头开始阅读。
后期是否可以支持在手机端开启Web服务后，多端阅读进度进行同步，并且通过WebDAV进行阅读进度进行上传同步？

## 截图
![image](https://user-images.githubusercontent.com/63388574/213995942-bdbcd66c-9c13-4d27-a53e-2a0d92c92042.png)
![854f3b6c1349cbca5b4547f0b7edbad](https://user-images.githubusercontent.com/63388574/213996027-443cf3df-dc10-459c-9700-a7b5cfbe22ae.jpg)

### 复现步骤

例如在PC端，点某本书进来开始阅读时，会直接从某一章的开头开始阅读。

### 阅读版本

3.23.012018

### Android版本

12

### 机型

小米10

### 其他信息

Edge浏览器（版本 109.0.1518.61 (正式版本) (64 位)）

**Comment by 821938089** [comment]
不都是第一章吗？
