### ISSUE TITLE
更新APP出错了

### ISSUE THREAD

**Issue by qiuyue2379** [gedoor/legado#2722]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

更新程序一直加载中。不会下载

### 复现步骤

无

### 阅读版本

3.23.012317

### Android版本

android 12

### 机型

HUAWEI

**Comment by 821938089** [comment]
网络问题

**Comment by qiuyue2379** [comment]
换了AppUpdateGitHub后。才出现的

**Comment by 821938089** [comment]
那应该是混淆的问题
@gedoor
