### ISSUE TITLE
备份和恢复的webDav文件恢复列表希望排序

### ISSUE THREAD

**Issue by nobk** [gedoor/legado#2726]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

在webDav目录里已经积累了6个月的每天自动备份，偶尔需要从webDav恢复时，短按恢复，出现的webDav恢复列表，里面的文件名是未排序的，从200多个文件里找到昨天的文件，有点麻烦。

### 期望实现方式

希望对这个文件列表，按文件名倒序排列，让最近日期的文件在第一行。

**Comment by Quackgrass** [comment]
书架当前没有像阅读进度一样同步，当前只能通过 webdav 的备份来保持一致。过多的未排序备份干扰了选择，如上同希望能够添加日期的倒序排序。
