### ISSUE TITLE
预缓存后续章节网络TTS

### ISSUE THREAD

**Issue by xsdcz** [gedoor/legado#2727]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

由于微软提供的TTS有并发限制，希望可以在当前章节TTS已经缓存完毕的情况下，去低速率地缓存下一章节的TTS数据，避免在章开始时大量的并发访问。

### 期望实现方式

1、减少章节开始时的网络TTS并发数量与访问频率。
2、在当前章节TTS缓存完成后，用更低的频率去预缓存下一章节的TTS数据。

**Comment by 821938089** [comment]
TTS请求都是单线程的，不存在并发访问

**Comment by adoin** [comment]
我也想要有，但是不好办吧，缓存量太大了

**Comment by wuxq** [comment]
我也想要这个功能，能不能加呢？ 就是在家用 wifi 存下来， 出去后不走 5G
