### ISSUE TITLE
加入书架功能bug

### ISSUE THREAD

**Issue by who-am-i1504** [gedoor/legado#273]
搜索小说后进入阅读，返回时提示是否加入书架，选择取消，但是书架内任然被加入该书籍，望修复。
另外，对于加入书架的小说，选择删除时，删除功能有时不起作用，不知道为啥

**Comment by gedoor** [comment]
好的,我看看

**Comment by gedoor** [comment]
好的,我看看

**Comment by Antecer** [comment]
已经很久未能复现该问题。
