### ISSUE TITLE
对缓存导出文件添加存在检查

### ISSUE THREAD

**Issue by WanderMax** [gedoor/legado#2737]
在缓存导出时候，导出成功会提示一次，返回重新进入这个提示就消失了。
再次点击导出，会直接覆盖已导出的文件，导出很费时间。
能否在缓存导出时候，提示一个存在已导出内容，是否覆盖的提示。

**Comment by gedoor** [comment]
ok

**Comment by WanderMax** [comment]
另外，能否优化缓存导出速度。
目前的方法似乎是边导出边写入，不知如果先全部导出到内存再一次写入，不知速度上是否有优化？

**Comment by 821938089** [comment]
把净化关了就会快很多

**Comment by WanderMax** [comment]
还真的是，感谢！
