### ISSUE TITLE
Web service BUG

### ISSUE THREAD

**Issue by unOmni** [gedoor/legado#2739]
When using the web service to read on my TV, I can only read the current chapter, the one before, and the one after.
Moreover when I go to the next chapter or the one before the current one, I'm unable to go back to the 'current' chapter I was reading to begin with.
I can still select chapters from the drop down menu but using arrows produces the issue.

**Comment by gedoor** [comment]
ok

**Comment by Xwite** [comment]
fixed https://github.com/gedoor/legado_web_bookshelf/commit/66cbcce04183d4e1043c3030747b2e87f5c649d9. Try the beta app later.
