### ISSUE TITLE
web 看书点击下一页和上一页无效

### ISSUE THREAD

**Issue by moeelf** [gedoor/legado#2740]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar issues opened
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not works
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

web 看书时点击下一页和上一页无效，不会跳转章节。

### 复现步骤 / How to reproduce

web 看书时点击下一页和上一页无效，不会跳转章节。

### 阅读版本 / Legado Version

3.23.012922

### Android版本 / Android Version

Android 10

### 机型 / Model

Redmi K20 pro

**Comment by Xwite** [comment]
#2739
