### ISSUE TITLE
WSA安卓子系统，使用鼠标滚轮无法翻回上一页

### ISSUE THREAD

**Issue by bzkmsjy** [gedoor/legado#2741]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar issues opened
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not works
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在WSA中使用阅读观看书籍，鼠标滚轮向上和向下都是翻到下一页，没法往回翻，不知道是bug还是没适配滚轮，希望可以用滚轮前进后退。

### 复现步骤 / How to reproduce

Win11安装WSA，安装阅读，看书时，使用鼠标滚轮向上翻页

### 阅读版本 / Legado Version

3.23.012922

### Android版本 / Android Version

13

### 机型 / Model

Win11 WSA

**Comment by gedoor** [comment]
我看下
