### ISSUE TITLE
希望能够添加不同的只读webdav来读取网络书源

### ISSUE THREAD

**Issue by lilith-rong** [gedoor/legado#2742]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

现在的webdav功能只能设置自己的webdav，但是遇到别人分享的只读webdav，基本是无能为力的，尤其是多个别人的只读webdav。
希望能够在webdav书籍界面增加多个webdav选项可以直接切换多个不懂得webdav的书库

### 期望实现方式

在远程书库的选项里面可以多个可自定义的只读webdav书库，可以切换不同的webdav来切换远程书库

**Comment by gedoor** [comment]
ok
