### ISSUE TITLE
英文设置两端对齐的时候，右侧不齐

### ISSUE THREAD

**Issue by wuqiong4945** [gedoor/legado#2744]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar issues opened
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not works
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

英文设置两端对齐的时候，右侧不齐。
应该是没有忽略句末的空格导致的。
![Capture](https://user-images.githubusercontent.com/1294412/215917197-7a8ede5e-7780-445e-ba5c-7ed22957b94e.PNG)

### 复现步骤 / How to reproduce

打开一个英文图书，设置两端对齐

### 阅读版本 / Legado Version

3.23.012922

### Android版本 / Android Version

Android 12

### 机型 / Model

Galaxy A90

**Comment by gedoor** [comment]
ok, 好像是因为结尾有空格的问题
