### ISSUE TITLE
通知bug

### ISSUE THREAD

**Issue by 390057892** [gedoor/legado#2747]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar issues opened
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not works
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

android.permission.POST_NOTIFICATIONS 在安卓13上是运行时权限。需要申请才能使用。否则无法创建通知。

### 复现步骤 / How to reproduce

每次复现

### 阅读版本 / Legado Version

3.23.013123

### Android版本 / Android Version

Android13

### 机型 / Model

xiaomi mix4

**Comment by 821938089** [comment]
去应用权限那里打开也能用

**Comment by 390057892** [comment]
> 去应用权限那里打开也能用

有道理🤨，但是对于大部分用户来说他们可能不知道怎么设置，是不是在合适的时机申请一下会更好。不然下载/朗读/音频的通知都看不到了。

**Comment by gedoor** [comment]
ok
