### ISSUE TITLE
在阅读界面无法滚动截屏

### ISSUE THREAD

**Issue by k0KoI7tO** [gedoor/legado#2748]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

发现问题的场景：看到一段脑洞大开的剧情想分享到群里，结果太长截不下有七八屏幕左右，然后发群里被管理员警告刷屏封了10分钟。。
手机：红米k30pro
系统：MIUI 13 开发版 22.7.19
为什么觉得这是错的：因为在书架界面、书源界面、设置界面都可以正常滚动截屏，唯独阅读界面不能滚动截屏（已经设置滚动动画模式）
[<img src="https://tvax1.sinaimg.cn/large/008378cigy1hao1txlg9zj318m20inpd.jpg" alt="微信图片_20230201155154" width="1606" data-width="1606" data-height="2610">](url)

### 复现步骤 / How to reproduce

在阅读界面用音量键+电源键截屏，出现截图后等待几秒钟“截长图”按钮还是灰的，无法点击

### 日志提交 / Relevant log output

没有崩溃，崩溃日志是空

### 阅读版本 / Legado version

3.23.013123

### Android版本 / Android version

安卓12

### 机型 / Model

k30 pro

**Comment by 821938089** [comment]
阅读界面不支持截长图，你可以直接把链接发到群里
或者用别的软件拼接图片等

**Comment by k0KoI7tO** [comment]
> 阅读界面不支持截图，你可以直接把链接发到群里 或其他用户的软件拼接图片等

是不是正版盗版书的关系

**Comment by 821938089** [comment]
不是，阅读界面和其他界面不一样，这个是自定义的视图，该视图的触控处理有些特别，无法支持长截图

**Comment by k0KoI7tO** [comment]
原来如此明白了
