### ISSUE TITLE
为Jetbrains系列IDE开发了一个阅读app的插件端

### ISSUE THREAD

**Issue by nancheung** [gedoor/legado#2750]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

找了很久，没找到Jetbrains系列IDE（如IDEA、PyCharm、Android Studio等等）的阅读插件版，不能一边编码一边阅读，严重影响开发效率。
内嵌浏览器看web版又很麻烦体验也不好，所以我撸了个插件出来，目前第一版支持**ToolWindow中看书**

1. 支持查看书架目录
2. 阅读章节正文
3. 切换上下章
4. 与阅读APP同步进度

项目地址：https://github.com/nancheung/legado-reader
已发布版本：https://github.com/nancheung/legado-reader/releases

官方插件商店正在上架中：https://plugins.jetbrains.com/plugin/20974-legado-reader

可以先下载离线jar包使用

### 期望实现方式

已实现

**Comment by limne** [comment]
费劲，带上耳机听不就完了。

**Comment by adoin** [comment]
听书吧。。。

**Comment by adoin** [comment]
牛逼，还真搞出来了。。。那有没有听书功能的安排

**Comment by nancheung** [comment]
> 牛逼，还真搞出来了。。。那有没有听书功能的安排

有计划了，大佬多多关注

**Comment by tang-nn** [comment]
大佬们这个插件怎么用啊

**Comment by adoin** [comment]
> 大佬们这个插件怎么用啊

他这个就是开手机的web 服务器 然后ide上看。。。

**Comment by tang-nn** [comment]
> > 大佬们这个插件怎么用啊
> 
> 他这个就是打开手机的web服务器 然后ide上看。。。

谢了哈，
