### ISSUE TITLE
WebDav自动备份相关

### ISSUE THREAD

**Issue by chd666** [gedoor/legado#2752]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

WebDav备份设置好之后就开始每天备份一次，删除了用户密码等信息依然在备份，而且备份文件每天在增加，过往的备份文件并不会删除。

### 期望实现方式

1. 自动备份设置一个开关，在自动备份功能关闭后同时可以手动备份。
2. 如果可以的话，再支持一下定时删除过往备份文件，以月或周为周期。

### 附加信息

以上是我的功能请求，非常感谢作者的贡献！

**Comment by eaudouce** [comment]
以前我提过类似的，大概是作者不想改备份相关问题，时间长被关掉了。
如果能把WebDav和本地自动备份分开控制就好了

**Comment by chd666** [comment]
> 以前我提过类似的，大概是作者不想改备份相关问题，时间长被关掉了。 如果能把WebDav和本地自动备份分开控制就好了

如果有那个功能会很方便，可惜了

**Comment by jiusun** [comment]
+1 
希望可以把本地备份和webdav备份分开单独控制，以及自动删除过于老旧的历史备份

**Comment by pinoren** [comment]
希望增加”保留最近__个备份文件（每设备）“。
