### ISSUE TITLE
希望备份和web备份时可以备份备份和web备份的设置。

### ISSUE THREAD

**Issue by huangsijun17** [gedoor/legado#2754]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

希望可以在备份设置等数据时，将备份设置一并备份。在还原设置时，可选是否还原备份设置。以便于在更换系统后，无需重新设置WebDEV的地址、用户名和密码。

### 期望实现方式

在备份设置等数据时，将备份设置一并备份。在还原设置时，可选是否还原备份设置。

**Comment by Xwite** [comment]
已添加

**Comment by earmer** [comment]
好绕口的Issue标题……
