### ISSUE TITLE
[BUG] EPUB目录识别错误，阅读时位置错误

### ISSUE THREAD

**Issue by laulguo** [gedoor/legado#2755]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

打开部分EPUB文件，对子目录识别似乎有问题，单个HTML下多个标题会重复打开同一个HTML

### 复现步骤 / How to reproduce

打开上传的EPUB文件，第二章诸多标题实际打开的都是同样的页面，会重复打开
[epub.zip](https://github.com/gedoor/legado/files/10577474/epub.zip)

### 阅读版本 / Legado version

3.23.013123

### Android版本 / Android version

Android 11

### 机型 / Model

Redmi K30S Ultra

**Comment by 821938089** [comment]
阅读对epub支持不太好，用别的app看吧，例如静读天下，多看之类的

**Comment by Xwite** [comment]
你发的这个文件的章节内容不在定位标签内或者兄弟节点内

```html
<div id="secoo1">
  <h2>标题1</h2>
  <p> ...
</div>
<div id="secoo2">
  <h2>标题2</h2>
  <p> ...
</div>
```

```html
<h2><a id="sec001">标题1</a></h2>
<p> ...
<h2><a id="sec001">标题1</a></h2>
<p>
```
