### ISSUE TITLE
小米系统安装apk，提示”未通过小米安全审核，该应用未公示隐私政策“

### ISSUE THREAD

**Issue by scoful** [gedoor/legado#2758]
### 确认 / Assignments

- [x] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [ ] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

安装apk提示”未通过小米安全审核，该应用未公示隐私政策“

### 复现步骤 / How to reproduce

直接安装apk

### 阅读版本 / Legado version

3.23.013123

### Android版本 / Android version

Android 7.1.1

### 机型 / Model

MI MAX 2

### 其他信息 / Additions

小米系统 MIUI 11.0.2

**Comment by Xwite** [comment]
相信的话加入白名单
