### ISSUE TITLE
书籍换源，源目录从当前源开始显示

### ISSUE THREAD

**Issue by zealousfool** [gedoor/legado#2760]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

书籍换源，现在每次换源找好用的源从上往下的话需要反复滑动到最下面，然后选中新的源。能否换源时，源目录从当前源开始显示，这样免去反复滑动到底端寻找。

### 期望实现方式

换源时，滑动条在当前源的位置，源目录从当前源开始显示

**Comment by 821938089** [comment]
换源界面底部有一小条，点一下就会跳到当前用的源

**Comment by zealousfool** [comment]
> 

才知道，多谢
