### ISSUE TITLE
请问制作书源的时候搜索后直接跳转到书页该怎么获取详情地址

### ISSUE THREAD

**Issue by fhwhite** [gedoor/legado#2761]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

https://www.69shu.com
之前以为站挂了，最近才发现是域名被ban了，挂了代理正常访问，但以前的源都不能用了
编辑源后，列表正常，但如果结果唯一，就会直接跳转到书页

### 期望实现方式

不知道该怎么写69shu.com的书源？

**Comment by 821938089** [comment]
这种情况阅读会自动当详情页处理，你把规则都填好就行

**Comment by zhangzw218** [comment]
跳转后的详情页，需要和 基础的链接验证规则匹配？

**Comment by 821938089** [comment]
@zhangzw218 一般情况下，写不写都行

**Comment by zhangzw218** [comment]
> @zhangzw218 一般情况下，写不写都行

嗯，我去试了下，可以不填，但填了要正确。。
删掉之后才发现，上面写着，只有详情页和源域名不一样时才需要填写。。
