### ISSUE TITLE
[BUG] Epub Compatibility

### ISSUE THREAD

**Issue by tatacaw13** [gedoor/legado#2763]
Most of my EPUB files aren't supported. How to fix this? Also is there a guide in English on how to read manga on this app and how to use extensions? I don't understand Chinese language so it's hard to figure out. Please help 🙏🏻

**Comment by 821938089** [comment]
Send the error message when you open the epub file.

Unfortunately this is a Chinese app and hardly any foreigners use it, so there is no English extension.
But making an extension is very easy, as long as you have a basic knowledge of HTML, CSS language and using browser development tools, you can make your own extension.
Documentation (it's in Chinese, you can translate it to English using your browser): https://alanskycn.gitee.io/teachme/Rule/source.html

**Comment by tatacaw13** [comment]
@821938089 
LoadTocError:Attempt to invoke virtual method 'java.lang.String me.ag2s.epublib.domain.o.getHref()' on a null object reference


This is the error message .
I have absolutely no clue about the stuff you mentioned so its probably not something I'd be able to figure out . I will check out the translation though.
Btw thanks for reply. I appreciate it. I didn't think I'd get any response here in English tbh since all the comments are in Chinese 😅

**Comment by 821938089** [comment]
pls upload the epub file.

**Comment by tatacaw13** [comment]
It won't let me select the EPUB file ;(

**Comment by 821938089** [comment]
Add the epub file to the zip file and upload it.

**Comment by tatacaw13** [comment]
[Uploading your name.zip…]()

**Comment by tatacaw13** [comment]
[your name.zip](https://github.com/gedoor/legado/files/10610753/your.name.zip)

**Comment by 821938089** [comment]
fixed, you can try beta version:
https://github.com/gedoor/legado/suites/10787433350/artifacts/542278259

**Comment by tatacaw13** [comment]
@821938089 it worked, thank you!!
