### ISSUE TITLE
被截取的长标题导致移除重复标题不干净

### ISSUE THREAD

**Issue by Quackgrass** [gedoor/legado#2766]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

关闭“替换净化”、“移除重复标题”时，如下图一；只启用“移除重复标题”时，如下图二。

看上去像是超出长度后被强制换行了，希望能调整“移除重复标题”的优先级。

![Screenshot_2023-02-07-12-12-19-040-edit_io legado app release](https://user-images.githubusercontent.com/42032091/217147349-a2a350f2-0582-4b6b-aae3-ae5cc02023c7.jpg)

![Screenshot_2023-02-07-12-10-43-487-edit_io legado app release](https://user-images.githubusercontent.com/42032091/217147421-0fceb6d5-01be-4286-b234-0c507a20e7c6.jpg)

### 复现步骤 / How to reproduce

无需

### 日志提交 / Relevant log output

无需

### 阅读版本 / Legado version

3.23.013123

### Android版本 / Android version

Android 12

### 机型 / Model

Redmi K30 Pro

**Comment by 821938089** [comment]
原标题本身就是被截取的，但是正文里面的标题是完整的，所以在移除重复标题的时候就会剩下一部分

**Comment by Quackgrass** [comment]
表达时没说清楚。希望能先“移除重复标题”，再截取标题。

现在是“移除重复标题”只移除了截取后的标题，剩下的部分还残留在下面，这样“看上去像是超出长度后被强制换行了”。

这可以说是“移除重复标题”没起到应有的效果，而且之后应该不好再处理了。故“看上去像是超出长度后被强制换行了”

**Comment by 821938089** [comment]
标题被截取一般是网站的问题，你没开净化的话app不会对标题做任何处理
你去原网站看一下标题就知道了

**Comment by Quackgrass** [comment]
经确认是获取的目录本身不全，抱歉🙂
