### ISSUE TITLE
怎么才能在解析中引用crypto.js

### ISSUE THREAD

**Issue by Codebglh** [gedoor/legado#2770]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

const Crypot=import(CryptoJS.js);
function openMH(bookid, linkid, path) {
    var localhost = 'https://www.dd.xyz'
    const j = CryptoJS.enc.Utf8.parse('12cdefgabcdefg12');
    let j1 = CryptoJS.enc.Utf8.parse(linkid);
    let jg = CryptoJS.AES.encrypt(j1, j, {
        'mode': CryptoJS.mode.ECB, 'padding': CryptoJS.pad.Pkcs7
    });
    let url = localhost + '/play?linkId=' + linkid + '&bookId=' + bookid + "&path=" + path + '&key=' + jg.toString()
    return url
}

### 期望实现方式

我应该怎么调用我写的这个函数

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/blob/master/app/src/main/assets/help/jsHelp.md

```js
//从网络下载js并执行
eval(String(java.importScript("https://.....crypto.js")))

//内置JAVA方法
java.createSymmetricCrypto("AES/ECB/PKCS7Padding", "12cdefgabcdefg12").encryptBase64(linkId)
```

**Comment by Codebglh** [comment]
谢谢，我去试一下

**Comment by Codebglh** [comment]
//*[@class="cell-type"]/@onclick
获取的是open('37','21123',text)
我写一个
eval(result)
function open(bookid,linkid,text){
var host='https://sss/';
var a=java.createSymmetricCrypto("AES/ECB/PKCS7Padding", "12cdefgabcdefg12").encryptBase64(linkId);
return host+bookid+"page"+bookid+a+text;
}

**Comment by Codebglh** [comment]
这样写不可以呀
