### ISSUE TITLE
具体使用还是不清楚

### ISSUE THREAD

**Issue by Codebglh** [gedoor/legado#2771]
//*[@class="cell-type"]/@onclick
获取的是open('37','21123',text)
我写一个
eval(result)
function open(bookid,linkid,text){
var host='https://sss/';
var a=java.createSymmetricCrypto("AES/ECB/PKCS7Padding", "12cdefgabcdefg12").encryptBase64(linkId);
return host+bookid+"page"+bookid+a+text;
}

_Originally posted by @Codebglh in https://github.com/gedoor/legado/issues/2770#issuecomment-1421909568_

**Comment by 821938089** [comment]
text如果是网页里的变量的话还需要另外获取一下

**Comment by Codebglh** [comment]
function a(x) {
 const CryptoJS=eval(String(java.cacheFile('https://ghproxy.com/https://raw.githubusercontent.com/Codebglh/hikerule/main/l/crypto-js.js')))

     const j = CryptoJS.enc.Utf8.parse('12cdefgabcdefg12');
    let j1 = CryptoJS.enc.Utf8.parse(x);
    let jg = CryptoJS.AES.encrypt(j1, j, {
        'mode': CryptoJS.mode.ECB, 'padding': CryptoJS.pad.Pkcs7
    });
    return jg.toString();
}

**Comment by Codebglh** [comment]
我不能使用这个函数一直报错

**Comment by Codebglh** [comment]
很难受

**Comment by 821938089** [comment]
不需要`const CryptoJS=` ，直接eval就可以
