### ISSUE TITLE
不出意外是被白嫖代码商用了?

### ISSUE THREAD

**Issue by Julymycin** [gedoor/legado#2772]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

对方github: https://github.com/RenaisnNce/Renaisn_Android [MIT许可证](https://github.com/RenaisnNce/Renaisn_Android/blob/main/LICENSE)

### 复现步骤 / How to reproduce

对方官网: https://renaisn.com/#/home

### 阅读版本 / Legado version

3.22

### Android版本 / Android version

Android 13

### 机型 / Model

Samsung

**Comment by Xwite** [comment]
商用闭源
https://github.com/pixelor/reader
https://v2reading.com/

**Comment by MasterOfStar** [comment]
https://github.com/hectorqin/reader 也有违反许可证的行为，新版本部分开源，违反GPLv3许可证。
![image](https://user-images.githubusercontent.com/21274896/219374336-b28a786b-991b-47b9-9aa9-3f2b4e06e7f3.png)

**Comment by zhangzw218** [comment]
> https://github.com/hectorqin/reader 也有违反许可证的行为，新版本部分开源，违反GPLv3许可证。 ![image](https://user-images.githubusercontent.com/21274896/219374336-b28a786b-991b-47b9-9aa9-3f2b4e06e7f3.png)
这个项目也有4K星了啊，作者自己搞一个服务端部署版本，把这个项目挤掉
