### ISSUE TITLE
想要个文言文转白话文的翻译功能

### ISSUE THREAD

**Issue by wangxiaolong1234555** [gedoor/legado#2773]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

加一个文言转白话的按钮

### 期望实现方式

接入百度文言文翻译api吧？

**Comment by wangxiaolong1234555** [comment]
看一些例如《曹操穿越武大郎》的半文言太累了

**Comment by limne** [comment]
话本/小说都是大白话，哪有真正的文言，除非山海经这种先秦的。

**Comment by adoin** [comment]
一词多义太多了，别做梦了，这个得AI，国内没有大厂做这块，你可以自己开坑
