### ISSUE TITLE
从3.23.012922开始的版本WEB服务阅读进度不与APP同步

### ISSUE THREAD

**Issue by xrmhxj** [gedoor/legado#2774]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

PC端使用WEB服务阅读，APP中的阅读进度不更新WEB的阅读进度，只从3.23.012922开始的版本开始有该问题，在3.23.0.12.018的版本中无该问题。

### 复现步骤 / How to reproduce

开启WEB服务后，在PC端通过地址http://ip:1122进行阅读，点击下一章，APP中的进度还保留在最开始的进度不更新。

### 阅读版本 / Legado version

3.23.0.13.123

### Android版本 / Android version

Android 13

### 机型 / Model

Xiaomi 13

**Comment by Xwite** [comment]
看更新日志，返回书架同步进度

**Comment by Xwite** [comment]
https://github.com/gedoor/legado_web_bookshelf/commit/0082e55df49b9e86725b786ae731903a928dab50

**Comment by easythd** [comment]
> 看更新日志，返回书架同步进度

哎，非常不好用！ 谁在pc上阅读完了不是直接点关窗口，还得记着返回窗口？ 反pc操作习惯啊

**Comment by xrmhxj** [comment]
> > 看更新日志，返回书架同步进度
> 
> 哎，非常不好用！ 谁在pc上阅读完了不是直接点关窗口，还得记着返回窗口？ 反pc操作习惯啊

从来没有在PC端主动点击返回书架，所以我还以为是bug，好在退回旧版本就好了
