### ISSUE TITLE
[bug] pc上web阅读和手机端不同步问题

### ISSUE THREAD

**Issue by easythd** [gedoor/legado#2775]
版本：阅读Pro google版 3.23.020221

描述：
在pc上web界面阅读，如果不主动点回书架，那手机上的进度不会跟着变，但反过来手机上阅读的进度，pc上可以同步。
感觉在回书架同步，还是阅读就自动同步这个步骤上，双向逻辑有问题。

但是这个web阅读了手机不同步的问题已经快一年了，我都提过好几次问题了，除了第一次真的修复好了，后来的版本又出现了，我后面再提问题就一直没修复过，也不知道是因为只有我一个人出问题，还是大家根本不关心这个问题。
最近我看到大佬们更新了一些web同步的修复，结果最新版本还是这样，我再提一次吧。
希望大佬们能帮帮修复下，双向研究下同步问题。
感谢感谢！

**Comment by 821938089** [comment]
看一下更新日志，就是返回书架才同步的

**Comment by Xwite** [comment]
https://github.com/gedoor/legado_web_bookshelf/commit/0082e55df49b9e86725b786ae731903a928dab50

**Comment by easythd** [comment]
> 看一下更新日志，就是返回书架才同步的

哎，非常不好用！ 谁在pc上阅读完了不是直接点关窗口，还得记着返回窗口？ 反pc操作习惯啊
