### ISSUE TITLE
报错我无法解决大佬给个例子吧

### ISSUE THREAD

**Issue by Codebglh** [gedoor/legado#2776]
javax.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot find function createSymmetricCrypto in object io.legado.app.model.analyzeRule.AnalyzeRule@be38064. (<Unknown source>#3) in <Unknown source> at line number 3

//*[@class="cell-type"]/@onclick
//获取的是openMH(1,2,3)
<js>
function openMH(bookid, linkid, path) {
    var localhost = 'https://example'
var a=java.createSymmetricCrypto("AES/ECB/PKCS7Padding", "12cdefgabcdefg12").encryptBase64(linkId);
    let url = localhost + '/play?linkId=' + linkid + '&bookId=' + bookid + "&path=" + path + '&key=' +a
    return url
}
eval(result)
</js>

**Comment by 821938089** [comment]
更新到最新版

**Comment by Codebglh** [comment]
I will do it
