### ISSUE TITLE
web服务 WIFI传书功能失灵

### ISSUE THREAD

**Issue by ciel0923** [gedoor/legado#2777]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

本人WiFi传书党，最近更新到了最新版本后发现，使用WiFi传书功能发现，网页传书成功，但是手机上没有新的书籍增加

### 复现步骤 / How to reproduce

手机打开web服务
电脑网页输入地址
书籍拖入网页，显示载入成功
手机没有新增书籍

### 阅读版本 / Legado version

3.23.013123

### Android版本 / Android version

android 12

### 机型 / Model

Mi 11Pro

**Comment by 821938089** [comment]
重新设置书籍保存位置
