### ISSUE TITLE
改进：字典建议改为或加入汉典zdic和萌典moedict，有些字查不到就自动匹配海词dict英文了。

### ISSUE THREAD

**Issue by 01bbbbb** [gedoor/legado#2782]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

字典可以查询到准确的汉字

### 期望实现方式

将汉典zdic或萌典moedict加入，并优先在这两个里面查找

**Comment by CoelacanthusHex** [comment]
这两个在线词典挺好用的，而且来源都比较权威：
汉典简体部分是用的王同文编写的《高级汉语词典》，繁体部分用的是台湾教育部编《重编国语辞典修订本》，同时附有康熙字典和说文解字，便于阅读古文时使用
萌典来源是台湾教育部，同时附有两岸对照词典，对于阅读仅有台译本的轻小说非常方便

**Comment by gedoor** [comment]
我后面加个自定义字典规则吧
