### ISSUE TITLE
Web 端通过目录跳转多章无法正确记忆位置

### ISSUE THREAD

**Issue by 1nj0k** [gedoor/legado#2784]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在 WEB 端通过目录跳转时，无法正确记忆位置

比如我现在在 663 章，通过目录跳转到 669 章，这时点击目录依然显示在 663 章，并且下一章按钮会跳到 664 章

### 复现步骤 / How to reproduce

https://user-images.githubusercontent.com/13143916/218273997-d1c9b460-19c7-4f7c-846f-1fcb7fb69d5d.mp4

### 阅读版本 / Legado version

3.23.020921

### Android版本 / Android version

Android13

### 机型 / Model

Oneplus8T

**Comment by Xwite** [comment]
修了
