### ISSUE TITLE
最新版本 换源后会重复添加书籍到书架

### ISSUE THREAD

**Issue by 01bbbbb** [gedoor/legado#2785]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

升级最新版本后，书架中的书籍在阅读时进行换源，返回书架后，发现多个源的书籍重复添加到书架中。

### 复现步骤 / How to reproduce

无

### 阅读版本 / Legado version

3.23020921

### Android版本 / Android version

7.0

### 机型 / Model

redmi note 4x

**Comment by 821938089** [comment]
换源勾选校验作者

**Comment by 01bbbbb** [comment]
> 换源勾选校验作者

好多网站上 出版书籍 作者名格式千差百变，不像网络流行小说，基本一致，即使勾选校验作者也很大概率重复添加，需要的是改进校验作者的模式，或者换源后询问是否替换之前书架的源。
