### ISSUE TITLE
本地epub不显示图片

### ISSUE THREAD

**Issue by Benjamin-Watson0** [gedoor/legado#2786]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

现在这个问题解决了吗？我看有人说是解决了，但是我的还是不行啊。

### 复现步骤 / How to reproduce

阅读

### 阅读版本 / Legado version

3.23

### Android版本 / Android version

10

### 机型 / Model

vivos7

**Comment by 821938089** [comment]
发一下有问题的epub

阅读对epub支持不太好，建议使用别的阅读器，如静读天下，多看等
