### ISSUE TITLE
项目很不错，UI做的漂亮，请问有Flutter版本么？

### ISSUE THREAD

**Issue by ligbyte** [gedoor/legado#2787]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

项目很不错，UI做的漂亮，请问有Flutter版本么？

### 期望实现方式

项目很不错，UI做的漂亮，请问有Flutter版本么？

### 附加信息

项目很不错，UI做的漂亮，请问有Flutter版本么？

### 效果演示

项目很不错，UI做的漂亮，请问有Flutter版本么？

**Comment by Xwite** [comment]
https://github.com/gedoor/YueDuFlutter
