### ISSUE TITLE
关于获取通知权限的提示

### ISSUE THREAD

**Issue by Hadesisme** [gedoor/legado#2788]
平时不听书不下载，只在线阅读，如果不给通知权限，每次打开都跳出需要给通知权限的提示，还只有“取消”和“去设置”选项，没有取消并禁止再次跳出选项。这个提示能关掉吗？或者设个跳出前提，在没给通知权限并听书或下载时再跳出提示。

**Comment by limne** [comment]
这个通知也只有听书才有通知，就算打开不听书也完全没有影响。

**Comment by Hadesisme** [comment]
> 这个通知也只有听书才有通知，就算打开不听书也完全没有影响。
但在没给通知权限的情况下会降低体验感，毕竟除了聊天软件给通知权限外，我其他软件全部是在能用的前提下关闭所有权限

**Comment by gedoor** [comment]
我改下获取权限的时机
