### ISSUE TITLE
希望搜索功能改进

### ISSUE THREAD

**Issue by lxinlin** [gedoor/legado#2789]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

点击阅读页面的搜索按钮进入搜索页面，还需要再点击一次搜索框才能使用，感觉有点繁琐，
希望改进下，阅读页面点搜索后跳到搜索页直接聚焦搜索框弹出输入法，这样体验好很多

### 复现步骤 / How to reproduce

阅读页点搜索——>搜索页点搜索框

### 阅读版本 / Legado version

3.23.013123

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K60

**Comment by 821938089** [comment]
发个视频看看，我这里没有你说的问题

**Comment by lxinlin** [comment]
https://user-images.githubusercontent.com/125240956/218387183-5ace604f-6c2e-42bf-a2e5-5a4037068feb.mp4

**Comment by lxinlin** [comment]
https://user-images.githubusercontent.com/125240956/218387622-f5a2d8e1-c37f-4060-bbca-acbf40885a13.mp4

**Comment by 821938089** [comment]
原来是这里的正文搜索，没仔细看。
已修复

**Comment by lxinlin** [comment]
👍
