### ISSUE TITLE
本地txt文件内的文本搜索速度很慢

### ISSUE THREAD

**Issue by lxinlin** [gedoor/legado#2790]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

一个3.7MB左右的本地txt，搜索里面的文字好像几十秒都搜不完的样子，等起来有点郁闷啊，请求改进下搜索速度

### 复现步骤 / How to reproduce

阅读页面点搜索——>搜索页面点输入框——>输入文字回车

### 阅读版本 / Legado version

3.23.013123

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K60

**Comment by 821938089** [comment]
关闭净化

**Comment by lxinlin** [comment]
是那个替换净化吗，我看了下没有没有选中那个净化的

**Comment by lxinlin** [comment]
重开后是快了很多了，谢谢哈

**Comment by lxinlin** [comment]
好像还是不行，一个4MB的txt要搜索这么久


https://user-images.githubusercontent.com/125240956/218394807-74fa675a-e7ef-4b5b-a7f0-be6d6482cb73.mp4

**Comment by 821938089** [comment]
那再看一有没有开繁简转换

**Comment by lxinlin** [comment]
是这里吗，没选过繁简    
![267781258308024026](https://user-images.githubusercontent.com/125240956/218396200-7f6108a7-968a-483b-a547-5a23a14c0bc8.jpg)

**Comment by 821938089** [comment]
那目前这应该就是最快的了

**Comment by lxinlin** [comment]
这样的吗，我试了下其他阅读软件，基本2秒内搜完的。
