### ISSUE TITLE
能否实现页面自由滚动而非翻页

### ISSUE THREAD

**Issue by jonozw** [gedoor/legado#2791]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

能否实现页面上下自由滚动, 屏幕滑动多少就滚动多少, 而非翻页? 类似于`Moon Reader`那种整个页面自由滚动的效果? 

这个需求可能比较奇葩, 但还是有实际使用场景的😓

高度近视晚上不戴眼镜躺着看书的时候, 其实是无法看清整个屏幕的, 只能看清离得近的1/3屏幕, 这时候自由像素级滚动就比较合适了, 看多少, 翻多少. 如果整页翻的话, 还得调整手或者脑袋的位置😭

### 期望实现方式

能否实现页面上下自由滚动, 屏幕滑动多少就滚动多少, 而非翻页? 类似于`Moon Reader`那种整个页面自由滚动的效果?

**Comment by 821938089** [comment]
翻页动画设置为滚动

**Comment by jonozw** [comment]
谢谢指点[抱拳]
