### ISSUE TITLE
发现栏目下的书籍标题显示异常

### ISSUE THREAD

**Issue by SnakeCN21** [gedoor/legado#280]
如附件中的图片所示，当我在发现栏目中查看书籍的时候，看到的所有书籍标题都显示异常，我不确定这是不是个例。
![Screenshot_20200730-185616128](https://user-images.githubusercontent.com/49633350/88903324-d8a76d80-d296-11ea-8263-478eba88624e.jpg)
![Screenshot_20200730-185605201](https://user-images.githubusercontent.com/49633350/88903339-de04b800-d296-11ea-8069-fd83e127c200.jpg)

**Comment by AndyBernie** [comment]
明明是规则没写对

**Comment by SnakeCN21** [comment]
> 明明是规则没写对

你好，能告诉我怎么设置规则吗？我也不知道什么时候设置了规则

**Comment by AndyBernie** [comment]
你重新导入一个新的呗
http://ku.mumuceo.com/yuedu/detail/index/id/3378.html

**Comment by SnakeCN21** [comment]
> 你重新导入一个新的呗 http://ku.mumuceo.com/yuedu/detail/index/id/3378.html

非常感谢，问题解决了，第一次知道居然还有这么棒的书源网站

**Comment by SnakeCN21** [comment]
问题解决了，重新导入正确的书源即可
