### ISSUE TITLE
阅读进度不够直观

### ISSUE THREAD

**Issue by yuweiping** [gedoor/legado#2802]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

当前手机端阅读进度显示的是百分比，不够直观。
web端不显示进度

### 期望实现方式

希望能够显示（当前阅读章节/总章节）。
这样能够知道还有多少章没看。
首页虽然也能显示未读章节数。但是实际阅读的时候app一般不退出，也就不会经常打开首页。

**Comment by gedoor** [comment]
ok
