### ISSUE TITLE
将封面切换为默认封面

### ISSUE THREAD

**Issue by zhangsan1025** [gedoor/legado#2806]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

情况
1.一些书默认获取的封面是nsfw的
2.获取的封面图文无关
为什么不使用已有功能
本地和网络没有合适的封面
更换本地图片麻烦

### 期望实现方式

在书籍详情页点击封面封面换源的界面增加使用默认封面（只显示书名和作者）的功能

**Comment by 821938089** [comment]
长按书籍进入书籍信息页->右上角编辑->封面地址随便写点东西->保存

**Comment by zhangsan1025** [comment]
> 长按书籍进入书籍信息页->右上角编辑->封面地址随便写点东西->保存

太麻烦而且只能凑合用

**Comment by 821938089** [comment]
加了，下个版本或者测试版就有
