### ISSUE TITLE
弄了一个github actions自动构建

### ISSUE THREAD

**Issue by 10bits** [gedoor/legado#281]
## 在线编译legado阅读3.0(不用本地编译了)
这里 [gedoor-Build](https://github.com/10bits/gedoor-Build),对本仓库使用了github actions自动构建
> 可以随时基于最新代码编译你自己的阅读3.0,和已有阅读3.0共存
*  fork到你自己的仓库,或者在本仓库右上角点一下Star就会自动开始编译
*  已经Star的点Unstar,再点Star会再次开始编译
*  大概十多分钟就会编译好
*  编译好的apk自动打包为`legado.apk.zip`,去你自己的[Actions](https://github.com/gedoor/legado/actions)里找
*  默认自动清空`18PlusList.txt`
*  `安装失败(-102)`和`与已安装应用签名不同`问题已解决
*  多个APP`共存`问题通过修改`applicationIdSuffix='.releaseA'`,不用卸载重装了
* 增加一系列任务脚本,比如`action_app_custom.sh`用来个性化定制app
* 本项目现在可以对任意android项目进行自动化构建了,只需要更新一下脚本就可以了
## 现在可以编译MyBookshelf阅读2.0了
> 修改`action_setenv.sh`脚本里的坏境变量`APP_NAME`,`APP_GIT_URL`
```bash
APP_NAME='MyBookshelf'
APP_GIT_URL='https://github.com/gedoor/MyBookshelf.git'
```
## 友情提示
> github actions是普通用户当前能用的免费服务,请不要连续多次触发构建,防止滥用

>构建配置文件已提交到本仓库,会同步更新

**Comment by db-one** [comment]
厉害了我的哥

**Comment by 0honus0** [comment]
star

**Comment by lmex621** [comment]
怎么更换包名哇？

**Comment by bzsgdwn** [comment]
新手，过来试试
