### ISSUE TITLE
可能在不正常关闭阅读或者tts后再启动软件阅读小说会提示"未获取到音频焦点"

### ISSUE THREAD

**Issue by blackcd318** [gedoor/legado#2811]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

可能在不正常关闭阅读或者tts后再启动软件阅读小说会提示"未获取到音频焦点".
我觉得这是个bug,反馈一下,反编译了静读,再加上搜索引擎,找到这部分代码,可能可以解决这个问题.比较完整的可以在这个地方看到https://blog.csdn.net/stven_king/article/details/122835280,下面的是我觉得有用的部分.不过我对安卓代码不熟,要加入现有代码比较费力,另外每次新版本都要加也比较麻烦.(注:再要提交时看到你出来新版了,不过我看了这部分代码,你似乎没有修改,所以我大胆猜测新版本问题还在,若已修改,请忽略这个问题)

private AudioManager.OnAudioFocusChangeListener mListener;
private AudioManager mAudioManager;

        mListener = new AudioManager.OnAudioFocusChangeListener() {
            @Override
            public void onAudioFocusChange(int focusChange) {
                switch (focusChange) {
                    case AudioManager.AUDIOFOCUS_GAIN:
                       // TBD 继续播放
                        break;
                    case AudioManager.AUDIOFOCUS_LOSS:
                       // TBD 停止播放
                        break;
                    case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT:
                        // TBD 暂停播放
                        break;
                    case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK:
                        // TBD 混音播放 
                        break;
                    default:
                        break;
                }
            }
        };

private AudioManager mAudioManager;
mAudioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);

    private void requestAudioFocus() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
					mAudioManager.requestAudioFocus(mFocusRequest);
        } else {
          mAudioManager.requestAudioFocus(mListener, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
        }
    }

### 复现步骤 / How to reproduce

我每晚会设置任务来关闭念书软件防止睡着了一直念干扰睡眠,用的是am force-stop + 应用包名,包括开源阅读和讯飞语记,还有别的有类似功能的软件,然后早上起来再启动软件来朗读就提示"未获取到音频焦点",重试和关闭软件(小米可以长安返回强制关闭软件)再重试也不行,重启后可以,今天又试用静读天下先朗读,然后关掉,再用开源阅读也可以朗读了,

### 阅读版本 / Legado version

3.23.022219 

### Android版本 / Android version

miui 12.5.6

### 机型 / Model

Redmi k20pro

**Comment by blackcd318** [comment]
我先关掉吧,因为没弄明白在什么情况下会触发这问题,试验了下不是am force-stop关闭程序触发,但是今天早上还是不能播了,版本是 legado-3.23.022621

**Comment by blackcd318** [comment]
close #2811

**Comment by blackcd318** [comment]
试验了下不是am force-stop关闭程序触发,昨晚关闭后我又打开播放领,但是今天早上还是不能播了,版本是 legado-3.23.022621

**Comment by blackcd318** [comment]
试验了下不是am force-stop关闭程序触发,昨晚关闭后我又打开播放了,但是今天早上还是不能播了,版本是 legado-3.23.022621

**Comment by 821938089** [comment]
系统或其他app的问题，你再阅读的其他设置里把忽略音频焦点打开就可以了

**Comment by blackcd318** [comment]
恩恩,我试试,这个选项我看到过,我还以为打开了是为了同时既能放歌也能听书才做的

**Comment by blackcd318** [comment]
> 系统或其他app的问题，你再阅读的其他设置里把忽略音频焦点打开就可以了

恩恩,我试试,这个选项我看到过,我还以为打开了是为了同时既能放歌也能听书才做的

**Comment by blackcd318** [comment]
Closed #2811 as completed.
