### ISSUE TITLE
书籍更新失败后，导致的app闪退。

### ISSUE THREAD

**Issue by old-yellow-ox** [gedoor/legado#2812]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

网络波动导致书籍更新失败，归入了更新失败的分组，过了一会儿重新更新了一下。此时app弹窗报错，然后闪退。再次打开app书籍已显示到正常分组，更新失败分组中不存在了。
![116305806115780759](https://user-images.githubusercontent.com/76513019/221421574-f60d3580-1a8a-4a63-b3ee-827413a404d3.jpg)

### 复现步骤 / How to reproduce

断开网络更新某一本书籍，然后会加入更新失败分组，然后连接网络更新该分组，即可复现。
猜测是刷新后该书籍从更新失败分组中移除了，但是后续用该分组执行了其他操作却没有发现数据。

### 阅读版本 / Legado version

3.23.022621

### Android版本 / Android version

12

### 机型 / Model

华为

**Comment by gedoor** [comment]
收到,今天更新
