### ISSUE TITLE
部分epub格式不能正常显示图片

### ISSUE THREAD

**Issue by ohtfbbxy33** [gedoor/legado#2813]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

部分epub格式不显示图片，图片全是一个裂开加叹号的图片，但是别的软件可以正常显示

### 复现步骤 / How to reproduce

比如我在zlibrary下的《丰子恺：写给大家的简明艺术启蒙 套装共5册 认识绘画+认识建筑+美的情绪+音乐入门+慈悲的滋味 (丰子恺) (Z-Library)》打开图片就无法正常显示 

### 阅读版本 / Legado version

3.23.022621

### Android版本 / Android version

11

### 机型 / Model

xperia1

### 其他信息 / Additions

希望能尽快给个解决方法，有的书没图片看不了

**Comment by 821938089** [comment]
把有问题的文件上传一下

**Comment by ohtfbbxy33** [comment]
> 把有问题的文件上传一下把有问题的文件上传一下把有问题的文件上传一下

传不上来超过25m了，要不我挂个链接麻烦您去下一下

**Comment by ohtfbbxy33** [comment]
[https://clibrary.cn/#/book/17789245](url)

> 把有问题的文件上传一下

**Comment by 821938089** [comment]
ok
