### ISSUE TITLE
備註 註解類功能

### ISSUE THREAD

**Issue by pochen448** [gedoor/legado#2816]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

看書時常常因為記憶力不好、名字類似之類問題
忘記那個人是誰之類的
希望能設置註解方便閱讀

### 期望实现方式

希望用類似取代的功能設定備註
檢索出現的關鍵字
在關鍵字字旁設個小！
按下後跳出備註的訊息欄
或是關鍵字字上/下方加上一行小字備註
能減少頭疼的回憶時間
小白發言可能沒有考慮完善 開發者辛苦了
抱歉昨天沒使用提供模板

### 效果演示

[https://i.imgur.com/HzLCs7C.jpg](url)

**Comment by blackcd318** [comment]
你看的是口水文,别当学术著作来看

**Comment by limne** [comment]
> 是因为没有服务器，和你看的什么文有什么关系？

**Comment by blackcd318** [comment]
> > 是因为没有服务器，和你看的什么文有什么关系？

你会给口水文备注吗?再说备注跟服务器有什么关系?有就放,没有就本地

**Comment by h11128** [comment]
> > > > 是因为没有服务器，和你看的什么文有什么关系？
> > 
> > 
> > 你会给口水文备注吗?再说备注跟服务器有什么关系?有就放,没有就本地
> 
> 你管他看什么文，做什么备注，做不做备注，这是人家的自己的事情，备注的功能以前有人提过，app作者就是以没有服务器拒绝的，因为加了备注就会有人提出同步功能。

现有的书签功能就是备注，只是UI没有显示在正文里，而是要通过目录功能。所以要解决的话，就是加一个toggle并且加入相应的UI，toggle on在正文显示书签，toggle off不显示。至于同步不同步的其实没关系，webdav可以实现保存到网络的功能。
