### ISSUE TITLE
能否为听书的语音速度条添加尺度

### ISSUE THREAD

**Issue by zhangzw218** [gedoor/legado#2817]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

能否为听书的语音速度添加尺度，比如1.1倍数，1.3倍数,1.5倍数，2.0倍数这样的？
因为我玩游戏时听书，和骑车回家听书，语速是不一样的，每次调整，都没办法那么刚好的调整到习惯的速度。。

### 期望实现方式

能否为听书的语音速度添加尺度，比如1.1倍数，1.3倍数,1.5倍数，2.0倍数这样的？

**Comment by blackcd318** [comment]
你调节语速时记个位置就行了,2.0倍跟2.1倍对你听书的影响很大吗?

**Comment by gedoor** [comment]
添加了,等更新
