### ISSUE TITLE
手机解锁后朗读进度被重置到页顶

### ISSUE THREAD

**Issue by haitaoli** [gedoor/legado#2818]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如果手机解锁的时候app正在前台朗读，朗读进度被重置到当前页顶。

### 复现步骤 / How to reproduce

* 打开app开始朗读。
* 锁屏，然后解锁。

以下步骤没有同样的问题：
* 打开app开始朗读。
* 送app到后台。
* 锁屏，然后解锁。
* 切换app到前台。

### 阅读版本 / Legado version

3.23.022219

### Android版本 / Android version

Android 12或者Android 13

### 机型 / Model

Pixel 6A

**Comment by 821938089** [comment]
设置里把隐藏状态栏和隐藏导航栏都打开

**Comment by haitaoli** [comment]
隐藏导航栏解决了问题。
