### ISSUE TITLE
允许设置启用的字体特性

### ISSUE THREAD

**Issue by CoelacanthusHex** [gedoor/legado#2819]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

OpenType 和 TrueType 支持名为字体特性（feature）的功能，可以用于优化显示。
在阅读中常见的有 `kern`（英文连字），`chws`（中文标点挤压），`ccmp`（破折号连字），`cpct`（标点居中）等。
我希望可以设置阅读字体使用的特性，以此优化显示效果。

### 期望实现方式

可能的两种方案，一是由用户自由填写 feature，阅读原样传递给字体渲染组件，二是给常见的 feature 提供开关。

### 附加信息

一些特性的效果
https://github.com/Buernia/Zhudou-Sans#%E6%8E%92%E7%89%88%E5%8A%9F%E8%83%BD

**Comment by CoelacanthusHex** [comment]
Still interested

**Comment by CoelacanthusHex** [comment]
從最少的角度，常見的 Android 閱讀軟件，例如起點讀書，菠蘿包輕小說，刺蝟貓閱讀等，都至少默認啟用了標點壓縮（chws）和破折號連字（ccmp），希望至少加入這個功能，可以沒有設置選項，但是希望至少啟用。

**Comment by CoelacanthusHex** [comment]
Android API: https://developer.android.com/reference/android/graphics/Paint.html#setFontFeatureSettings(java.lang.String)

我對 Android 不是很熟悉，不知道 androidx 庫是不是有單獨的設置選項

**Comment by 821938089** [comment]
阅读的排版应该支持不了这个

**Comment by CoelacanthusHex** [comment]
> 阅读的排版应该支持不了这个

能解释一下为什么吗？只要是负责渲染字体的组件支持就可以吧，就算是使用浏览器组件渲染的，可是浏览器自身也是支持的，feature 设置可以注入给浏览器或者通过 CSS 注入给 HTML.

https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings

**Comment by 821938089** [comment]
因为阅读的排版是自己实现的，每个字的位置是阅读自己计算然后再画出来，并不是直接把文字给到系统组件就可以显示出来。

你自己看下排版代码：https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/ui/book/read/page/provider/ChapterProvider.kt
内容渲染代码：
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/ui/book/read/page/ContentTextView.kt
