### ISSUE TITLE
导入本地txt数量选择BUG

### ISSUE THREAD

**Issue by quuee** [gedoor/legado#2820]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

导入本地txt选择出现数量错误，以及全选时图标没有改变为全选

### 复现步骤 / How to reproduce

本来总共22本。先选择一本书，再选择全选，变成了23/22本。
全选时，checbox不会变成勾选状态。

### 阅读版本 / Legado version

3.23.030400

### Android版本 / Android version

11

### 机型 / Model

1+7TPRO

**Comment by 821938089** [comment]
发个视频看一下

**Comment by quuee** [comment]
https://user-images.githubusercontent.com/33923687/222896388-e6019f87-f02e-46a2-a2c3-6709684aa03a.mp4

**Comment by quuee** [comment]
> 发个视频看一下

https://user-images.githubusercontent.com/33923687/222896455-42fbbd8a-c1a3-4813-89bf-78e8b3febfd1.mp4

**Comment by 821938089** [comment]
ok，下个版本修复
