### ISSUE TITLE
本地导入会删除同名的在线书籍记录

### ISSUE THREAD

**Issue by Quackgrass** [gedoor/legado#2823]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

本地导入会删除**同名**的在线书籍记录，导致丢失在线书籍的阅读进度记录。

本地书籍可以通过换源，变成在线书籍，应当是识别出了同一书名导致的。

希望能在导入后移除时，将本地书籍的阅读进度设置为在线书籍的。

### 复现步骤 / How to reproduce

1. 添加一本在线书籍

2. 导入名称为“《书名》（校对版全本）作者：作者名.txt”的文件

### 阅读版本 / Legado version

3.23.030400

### Android版本 / Android version

Android 12

### 机型 / Model

Redmi K30 Pro

**Comment by 821938089** [comment]
你把书名或者作者改一下就可以共存了

**Comment by Quackgrass** [comment]
不是要共存。

现在的问题是在导入后移除同名的在线书籍记录，导致丢失在线书籍的阅读进度记录。

书名和作者名是自动完成识别的，导入后就直接删除在线记录了。如果导入之前还要改在线记录都太麻烦了。批量导入时这样操作也很麻烦。

能否只识别书名不识别作者名。或者导入的能使用在线的阅读进度。

**Comment by 821938089** [comment]
可以只识别书名不识别作者名，阅读可以自定义文件名中的书名作者的解析，在添加本地的右上角三点的导入文件名里
```js
name = src.match(/《(.*?)》/)[1]
author = ""
```

**Comment by Quackgrass** [comment]
能否给一个完整的示例，直接填入没用。不知道如何在这里返回一个 JSON。

**Comment by 821938089** [comment]
我看了一下，只有默认规则识别不了才会用这个js规则识别，所以用不了
那就只能改下书名或作者防止被移除

**Comment by Quackgrass** [comment]
可以优化这个问题吗？例如：调整默认规则的优先级，或者导入的能使用在线的阅读进度。

**Comment by 821938089** [comment]
ok 改了优先级
