### ISSUE TITLE
希望书架布局列表模式和网格模式增加个密集模式

### ISSUE THREAD

**Issue by yl9345** [gedoor/legado#2827]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

希望阅读以后能给书架布局列表模式和网格模式增加个密集模式。
我的小手机一屏列表模式只能显示4本，空隙较大，空间利用率有些低；网格模式书名经常显示不全。

### 期望实现方式

封面大小、标题字号、书距、字距、行距能够像阅读界面里一样自定义就好了，或者直接增加个密集模式，显示的信息多些也行。

**Comment by bewareilive** [comment]
同希望，类似windows的详情，可以再以 已读章节/总章节数显示下。

我的问题还不是小手机。只是习惯单独一个书架，放已读过的书，现在那个书架里的书非常多，卡片太大了很难找
