### ISSUE TITLE
音量精细化控制

### ISSUE THREAD

**Issue by SevendaysZzzz** [gedoor/legado#2830]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

由于，系统版本低，无法精细化控制手机音量，实体音量按键又只有30等分，最低听不到，再高一点，带着耳机用阅读听书，时间久了，又会觉得声音偏大。

### 期望实现方式

简单来说，就是在阅读app内，增加一个音量条，值100 ，可用 - 和 + 控制音量，按一次 + 1或者 - 1， 也可以拖动。

### 附加信息

或者，也可以提供 “护耳模式” 按钮，设置一个对耳朵舒服的固定值，来解决这个需求。最主要的是要能对 "低音" 进行精细化控制。

**Comment by bewareilive** [comment]
这个我可以回答你，我也经常使用听书。
可以在手机  无障碍-TTS语音设置里，找到你用的引擎。
我用的讯飞的，在后面的设置按钮点开有个“语速和音效”，在里面有音量调节，给小一点多试试就可以了。

**Comment by SevendaysZzzz** [comment]
感谢回复！我TTS引擎用的是 "Google  语音服务" 。

它的设置中，只有 “语速” 和 “音高” 可以调节。

去调动这个 “音高” ，大小都会觉得很奇怪。

一般我都是默认设置，然后，在阅读app中将 “朗读语速” 的值，设置为2.1 。

可能是听习惯了吧，只有设置值为2.1时，语音听起来才觉得舒服。

之前，也试过其它在线的 TTS 语音引擎，但都没有本地引擎用起来流畅。

**Comment by bewareilive** [comment]
@SevendaysZzzz  我用的也是本地的，在线的废流量也跑不流畅。使用的是讯飞语记5版本的“小鲜肉”，除了多音字读错，调快速度后，听起来没有电脑音的生硬感。
你这种情况应该主要还是手机的自身问题。我手机也是声音最小一格都大，有个软件可以调整到不到最小一格的地方，但是会无声音。
我的解决办法 除了用讯飞自身的设置，再就是用带音量控制的耳机，把声音调小点。

**Comment by pinoren** [comment]
音量的增大设计可能是线性的，人耳对声音的敏感度是指数式的。也就是说，无论等分成100还是30，只要设计的时候以对数形式增大音量，这个问题就可以得到解决。即低音量向高音量调节的时候，音量应该由平缓逐渐陡峭。这个应该是牵涉到音响设计问题。。。
