### ISSUE TITLE
WebDav书籍使用优化

### ISSUE THREAD

**Issue by casselluu** [gedoor/legado#2834]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

测试了一下新的 WebDav书籍功能，因我是用Resilio Sync同步多端书籍及远程下载书籍，阅读的云进度进行同步阅读。发现如果利用WebDav做云书架，阅读下载后本地的书籍存放只有一个路径，不能还原云上分类存放路径。希望以后能跟云上同步，方便利用其他软件进行同步修改。

### 期望实现方式

期望效果是个人使用时在不同设备通过webdav同步阅读进度，同时可以在任意设备通过任何同步备份软件进行书库的增删改等操作。因为阅读自带的webdav打开时因网速等缘故会出现卡顿，还不能本地缓存信息，resilio sync则可以进行全书库搜索，然后同步到本地，然后就可以用本地导入，到对应路径导入阅读。
预期使用效果是，电脑端下载小说到resilio书库，手机想看的时候通过resilio下载，阅读打开。此时书籍存放路径为resilio的书库同步路径，与webdav的书库路径一致。然后我看到一半更换为电子书设备，阅读记录已经通过webdav同步到这一设备，阅读发现本地书库没有这一文件，我在resilio中选择同步，或者阅读发现webdav书库中有，下载到本地。
大概意思就是resilio的多端同步使用起来更舒服，但阅读不能调用它，所以通过一样的webdav书库进行书籍的下载，阅读这个软件只需要知道，我这几个相对路径都是同样的书库结构和内容

**Comment by casselluu** [comment]
> 你用resilio同步那就不需要从webdav上下载书籍了啊
问题在阅读打开resilio时会自动复制一份到指定书架目录，而且是不按我的分类存放的，导致
所有的书都会重复占用空间。
所以写的含糊不清，因为只能自己再从阅读本地加书，书一旦多了还不好找

**Comment by 821938089** [comment]
你从添加本地那里打开是不会复制一份的

**Comment by casselluu** [comment]
本地添加的问题就是书多了不好找发自我的手机-------- 原始邮件 --------发件人： Horis ***@***.***>日期： 2023年3月6日周一 18:22收件人： gedoor/legado ***@***.***>抄送： Casselluu ***@***.***>, Author ***@***.***>主    题： Re: [gedoor/legado] WebDav书籍使用优化 (Issue #2834)

你从添加本地那里打开是不会复制一份的

**Comment by 821938089** [comment]
你不是用resilio同步吗，这个同步不会同步目录结构吗，怎么会找不到

**Comment by casselluu** [comment]
> 你不是用resilio同步吗，这个同步不会同步目录结构吗，怎么会找不到

不是找不到，是要在添加时从一堆书中找。这个还是比较少的
![image](https://user-images.githubusercontent.com/39119438/223373494-543040ce-d61f-4b84-a6c1-def36bdc2b74.png)
