### ISSUE TITLE
翻译

### ISSUE THREAD

**Issue by pwd-github** [gedoor/legado#2843]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

使用 Crowdin 或类似服务进行本地化，这样所有语言的人都可以享受 Legado

### 期望实现方式

www.weblate.org

www.crowdin.com

### 附加信息

在此之后，我可以进行英文翻译，因为有很多缺失的字符串

**Comment by 821938089** [comment]
这app外国人用的不多，你要翻译的话直接改这里的就行
https://github.com/gedoor/legado/blob/master/app/src/main/res/values/strings.xml
