### ISSUE TITLE
备份时没有生成*.json文件【部分设置没有数据时】，恢复时失败

### ISSUE THREAD

**Issue by subtle99** [gedoor/legado#2851]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

备份时没有生成*.json文件【部分设置没有数据时】，恢复时失败

### 复现步骤 / How to reproduce

备份时没有生成*.json文件【部分设置没有数据时】，恢复时失败

### 阅读版本 / Legado version

3.23.03400

### Android版本 / Android version

Android 11

### 机型 / Model

荣耀

**Comment by 821938089** [comment]
发一下日志

**Comment by subtle99** [comment]
没有找到日志内容，只有在恢复时 弹出 类似 “sourceSub.json 读取文件出错...”，应该时备份时没有生成“sourceSub.json”（不太清楚这个是设置什么内容的），还有其他的如“没有书签数据”时，“没有订阅-收藏夹数据时”   也提示"*.json  读取文件出错..."。

**Comment by 821938089** [comment]
这个只是你没那个文件，恢复时就会提示一下，其他的可以恢复的

**Comment by bewareilive** [comment]
> 这个只是你没那个文件，恢复时就会提示一下，其他的可以恢复的

能自动以压缩包备份不，比较好管理一些

**Comment by gedoor** [comment]
已修复

**Comment by gedoor** [comment]
> > 这个只是你没那个文件，恢复时就会提示一下，其他的可以恢复的
> 
> 能自动以压缩包备份不，比较好管理一些

ok
