### ISSUE TITLE
安装APP时有BUG

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#2856]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

安装APP时之前是直接安装，现在会出现个选择界面，下面会有选择框，有阅读APP和系统自带软件安装程序。每次都要选择软件安装程序，很麻烦。阅读和阅读PRO都有同样问题。

### 复现步骤 / How to reproduce

安装APP时之前是直接安装，现在会出现个选择界面，下面会有选择框，有阅读APP和系统自带软件安装程序。每次都要选择软件安装程序，很麻烦。阅读和阅读PRO都有同样问题。
![Screenshot_2023-03-09-12-34-52-940](https://user-images.githubusercontent.com/74254385/224009939-102023fa-c606-4a7d-beb3-bac890af8ff3.png)

### 阅读版本 / Legado version

3.23.03081841及近来版本

### Android版本 / Android version

Android 6

### 机型 / Model

SM919

**Comment by sartonsh** [comment]
怎么上传图片

**Comment by sartonsh** [comment]
怎么上传图片

**Comment by sartonsh** [comment]
![Screenshot_2023-03-09-12-34-52-940](https://user-images.githubusercontent.com/74254385/224007119-0e32f587-5358-428e-aec4-b0f7999dfeb3.png)

**Comment by sartonsh** [comment]
OK，重新上传了。

**Comment by 821938089** [comment]
ok，应该修复了

**Comment by sartonsh** [comment]
解决了，多谢！
