### ISSUE TITLE
备份书源文件导入报错

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#2857]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

导入备份的书源文件时会报错，导入不了。而把书源导出后再导入时没问题，导入别的书源也没问题。疑似备份的bookSource.json文件有问题。

### 复现步骤 / How to reproduce

导入备份的书源文件时会报错，导入不了。而把书源导出后再导入时没问题，导入别的书源也没问题。疑似备份的bookSource.json文件有问题。

### 阅读版本 / Legado version

3.23.03081841

### Android版本 / Android version

Android 6

### 机型 / Model

SM919

**Comment by sartonsh** [comment]
问题未解决

**Comment by sartonsh** [comment]
![Uploading 涂鸦_Screenshot_2023-03-08-19-56-46-292_阅读.jpg…]()
就是导入这个文件会报错

**Comment by sartonsh** [comment]
![涂鸦_Screenshot_2023-03-08-19-56-46-292_阅读](https://user-images.githubusercontent.com/74254385/224008295-6ef49c72-164e-42e8-90b3-d0ff0e275006.jpg)
![Screenshot_2023-03-08-19-53-00-066_阅读](https://user-images.githubusercontent.com/74254385/224008307-e97598b3-fa70-44d8-b701-4311bcbb0d83.png)

**Comment by sartonsh** [comment]
就是导入这个文件会报错。

**Comment by 821938089** [comment]
重启一下手机

**Comment by sartonsh** [comment]
重启后还是同样问题。

**Comment by 821938089** [comment]
你把书源文件发一下吧

**Comment by sartonsh** [comment]
已解决，之前备份的书源有问题，重装后导入以前备份的书源后就没问题了。
