### ISSUE TITLE
朗读完一章有概率暂停

### ISSUE THREAD

**Issue by ACGMC** [gedoor/legado#2861]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

经常发生,朗读完一章会暂停语音朗读,

### 复现步骤 / How to reproduce

语音朗读,切后台,也可能和锁屏幕有关,已经加了清理白名单,不会被清理

### 日志提交 / Relevant log output

音频焦点获得 继续阅读

### 阅读版本 / Legado version

3.22.122419

### Android版本 / Android version

harmony OS 3.0

### 机型 / Model

huawei p30

### 其他信息 / Additions

无

**Comment by 821938089** [comment]
试试这个测试版有没有问题
https://kunfei.lanzoui.com/is69S0prwewb

**Comment by blackcd318** [comment]
没遇见过,你试试新版本,现在都3.23.0304了

**Comment by Qiihz** [comment]
试过离线TTS吗 有可能是网络问题

**Comment by myname-dyh** [comment]
我也经常出现这个问题，从20年开始用，期间换过三个手机，都是阅读到下一章就莫名暂停

**Comment by ACGMC** [comment]
补充: 这时候点亮屏幕或者打开软件又会继续朗读

**Comment by blackcd318** [comment]
> 补充: 这时候点亮屏幕或者打开软件又会继续朗读

怎么觉得你这是省电控制的原因呢

**Comment by tisswb** [comment]
俺也一样~

**Comment by tisswb** [comment]
一番操作后，好像不出现暂停了，华为手机，设置-应用和服务-应用启动管理 找到阅读app 关闭自动管理 然后 开启允许后台活动 就好了
