### ISSUE TITLE
每个目录开头都加载相同内容, 读取方式发生错误

### ISSUE THREAD

**Issue by Pantyhose-X** [gedoor/legado#2862]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

每个目录开头都加载相同内容, 读取方式发生错误，建议提供选项 **从文件开头读取 的方式** 加载内容

## 每个目录开头都加载相同内容, 读取方式发生错误
![Screenshot_20230310193540](https://user-images.githubusercontent.com/42504385/224310583-2375e362-fbdf-4950-98b0-e1abb6985789.jpg)
![Screenshot_20230310193631](https://user-images.githubusercontent.com/42504385/224310607-57803efe-42d0-4e33-a0c5-384ef46c7c58.jpg)

## 其他阅读器，正确加。 在 祖堂集序, 后都是正文。没有重复内容

![Screenshot_20230310194016](https://user-images.githubusercontent.com/42504385/224310829-f0087295-fcbf-4d53-a5a5-8c365d27bd73.jpg)

### 复现步骤 / How to reproduce

1.添加本地 [epub](https://github.com/gedoor/legado/files/10941860/epub.zip)  这里是书籍，你可以重现这个错误

### 阅读版本 / Legado version

3.23.030400

### Android版本 / Android version

Android 8.0

### 机型 / Model

huawei

**Comment by 821938089** [comment]
阅读对epub的支持不好，建议使用多看、静读天下这些阅读器来看

**Comment by Xwite** [comment]
试试这个https://github.com/gedoor/legado/actions/runs/4385269953

**Comment by Xwite** [comment]
试试这个https://github.com/gedoor/legado/actions/runs/4385269953

**Comment by Pantyhose-X** [comment]
这个错误可能是legado 自动把.epub格式 转换成.nb 产生的

**Comment by Xwite** [comment]
nb文件是解析读取之后的缓存，应该无关
***
原有代码没有正确处理多个章节在同一个xhtml文件里的情况
