### ISSUE TITLE
希望能添加类似Google Play books的翻页动画

### ISSUE THREAD

**Issue by Dianshii** [gedoor/legado#2864]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

效果如图，我感觉这动画真的很性感，希望可以加上或者替换原本的覆盖动画。

![pageflips](https://user-images.githubusercontent.com/74195924/224486103-f4d2a081-b937-4684-8c58-85987f4a2635.gif)

### 期望实现方式

我查了查有咩有方案，这里有一个用OpenGL实现的：

https://github.com/karankalsi/PlayLikeCurl
![demo](https://user-images.githubusercontent.com/74195924/224487378-0a8ae994-d700-4469-8d4d-e9f43ae2730d.gif)

他用的是 Asin(2π/λ*x) 函数的效果，类似这种：

![image](https://user-images.githubusercontent.com/74195924/224486677-c8946c93-076f-4f33-a51c-9126d4347e0f.png)

### 效果演示

![pageflips](https://user-images.githubusercontent.com/74195924/224486103-f4d2a081-b937-4684-8c58-85987f4a2635.gif)

**Comment by akschy** [comment]
这真的很想要这个
