### ISSUE TITLE
隐藏书架视图中书籍的封面

### ISSUE THREAD

**Issue by mytreee** [gedoor/legado#2865]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

为书架视图提供隐藏书籍封面的列表布局

### 期望实现方式

常常批量导入本地源书籍，每个去设置封面太过繁琐，故希望作者考虑在后续版本实现相关功能

### 效果演示

目前的书架视图以封面为核心，列表、多列模式都会显示封面，无法仅显示书名栏

**Comment by gedoor** [comment]
可以设置默认封面,不显示封面不好看
