### ISSUE TITLE
常见压缩文档的解压支持

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#2866]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

- [x] ZIP
- [ ] RAR
- [ ] 7z

### 期望实现方式

|Librar|format|
|---|---|
|native [Android7P](https://github.com/hzy3774/AndroidP7zip)|7z, BZIP2, GZIP,TAR, WIM, XZ, zip
|[common-compress](https://github.com/apache/commons-compress)|bzip2, gzip, pack200, lzma, xz, Snappy, traditional Unix Compress, DEFLATE, DEFLATE64, LZ4, Brotli, Zstandard and ar, cpio, jar, tar, zip, dump, 7z, arj. 
|[junar](https://github.com/junrar/junrar)|< RAR 4

**Comment by gedoor** [comment]
ok

**Comment by Xwite** [comment]
加了的话 需不需要分abi打包apk

**Comment by gedoor** [comment]
不需要吧,太麻烦了

**Comment by Xwite** [comment]
收到
