### ISSUE TITLE
远程导入书籍时出现异常，使用的是TERAcloud云服务

### ISSUE THREAD

**Issue by wazk9595** [gedoor/legado#2868]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

![Screenshot_20230312_233351](https://user-images.githubusercontent.com/84953699/224555327-dff3e538-3999-4477-a33a-59e2e24896da.jpg)
出现上方字样

### 复现步骤 / How to reproduce

远程导入书籍就会出现

### 阅读版本 / Legado version

3.23.031210

### Android版本 / Android version

Android 10

### 机型 / Model

Vivo s9

**Comment by 821938089** [comment]
之前的版本可以导入吗

**Comment by qhfls** [comment]
遇到同样问题，坚果云，以前正常。
