### ISSUE TITLE
[RhinoJS]一直出现"Packages" is not defined.报错

### ISSUE THREAD

**Issue by xingluo233** [gedoor/legado#2878]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [x] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

~~每次打开软件第一次调试书源是没问题的，但是只要再次调试，就会出现"Packages" is not defined.报错，此时只能再次重新打开软件，无论有没有修改书源都是这样~~
经核实，是由于请求头才出现这个问题的
[书源](https://shuyuan.mgz6.cc/shuyuan/93f1d0c34ca69251c6b1f59955278515.json)

### 复现步骤 / How to reproduce

https://user-images.githubusercontent.com/54618947/224882928-60f669b7-daae-4ec0-bdfb-ed48137225ba.mp4

### 阅读版本 / Legado version

3.23.031314

### Android版本 / Android version

12

### 机型 / Model

Xiaomi 10

**Comment by 821938089** [comment]
把里面的报错全部复制发出来

尝试不用eval直接把代码复制到过来

**Comment by xingluo233** [comment]
> 把里面的报错全部复制发出来
> 
> 尝试不用eval直接把代码复制过来

是我傻逼了 请求头写错了导致的

**Comment by xingluo233** [comment]
> 把里面的报错全部复制发出来
> 
> 尝试不用eval直接把代码复制过来

我人已经傻了，我把op里的headers删了，就不报错了，但是我看https://alanskycn.gitee.io/teachme/Rule/source.html里post请求的请求头也是这样写的，给我整不会了

**Comment by Xwite** [comment]
书源贴一下

**Comment by Xwite** [comment]
最上面eval那段改成这个
{{source.bookSourceComment}}

**Comment by xingluo233** [comment]
> 书源贴一下

书源在1楼

**Comment by xingluo233** [comment]
> 最上面eval那段改成这个
> {{source.bookSourceComment}}

直接报错找不到函数了

**Comment by xingluo233** [comment]
原来用的是rhino引擎，咋不用node呢，我就说咋总是会报一些莫名其妙的错误

**Comment by xingluo233** [comment]
@Xwite 能顺便支持SHA256withRSA MD5withRSA等等签名算法吗，有个软件用到了这个

**Comment by Xwite** [comment]
调用java方法比较方便

**Comment by xingluo233** [comment]
行吧

**Comment by 821938089** [comment]
Packages 由于安全原因，在某些情况下会被删除。
不用eval好像是没有这个问题的，你把那部分代码复制过来就好了。

URL的处理逻辑有问题，用@js:代替<js></js>就可以了。
