### ISSUE TITLE
自动翻页建议增加屏幕常亮功能

### ISSUE THREAD

**Issue by Syt100** [gedoor/legado#288]
目前自动翻页一段时间后就会熄灭屏幕，建议开启自动翻页后将屏幕超时设置为常亮，关闭自动翻页后还原之前的屏幕超时设置。

**Comment by Antecer** [comment]
阅读页面的设置功能可以启用常亮（不影响软件切换出去后正常熄屏）

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持
