### ISSUE TITLE
文件类书源：重复请求

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#2881]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

`UrlUtil.getFileName`解析文件名
* 返回头返回`Content-Disposition`: 我们目前不能正确下载到内容，感觉可以去掉显示
* 后面的会下载一次文件，后面的点击导入也会下载一次

### 复现步骤 / How to reproduce

* 导入书源https://shuyuan.mgz6.cc/shuyuan/8602af56f5466b000914ac5ec38aa83f.json
* 点击任意发现里的第一本书
* 导入对话框的第一个是返回`Content-Disposition`，其余直接下载
* 在显示导入对话框之前可以发现下载了两个文件

### 阅读版本 / Legado version

3.23.0315

### Android版本 / Android version

12

### 机型 / Model

none

**Comment by gedoor** [comment]
{
    "bookSourceComment": "http://www.freexiaoshuo.com/book/dushiyule/2018/04/268.html\n\n本地下载\nhttp://www.freexiaoshuo.com/plus/download.php?open=2&id=268&uhash=d6d2d815fc555e78ae6fbc4c\n跳转真实下载地址\nhttp://www.freexiaoshuo.com/uploads/soft/180414/1-1P414102236.rar\n\n\n\n<js>java.ajax(\"http://www.freexiaoshuo.com\"+result.get(0))</js>",
    "bookSourceGroup": "",
    "bookSourceName": "㊦免费小说",
    "bookSourceType": 3,
    "bookSourceUrl": "http://www.freexiaoshuo.com##ycmd",
    "customOrder": -2085984610,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": true,
    "enabledReview": false,
    "exploreUrl": "[{\"title\":\"都市娱乐\",\"url\":\"/a/dushiyule/list_12_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},{\"title\":\"武侠仙侠\",\"url\":\"/a/wuxiaxianxia/list_13_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},{\"title\":\"奇幻玄幻\",\"url\":\"/a/qihuanxuanhuan/list_14_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},{\"title\":\"科幻灵异\",\"url\":\"/a/kehuanlingyi/list_15_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},{\"title\":\"历史军事\",\"url\":\"/a/lishijunshi/list_16_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},{\"title\":\"竞技游戏\",\"url\":\"/a/jingjiyouxi/list_17_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},{\"title\":\"实体书版\",\"url\":\"/a/shitinvsheng/list_18_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},{\"title\":\"二次元\",\"url\":\"/a/erciyuan/list_19_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},{\"title\":\"\",\"url\":\"\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}}]",
    "lastUpdateTime": 1678799395298,
    "respondTime": 180000,
    "ruleBookInfo": {
      "author": ".dlbt_wz@text##.*作者.",
      "coverUrl": ".jtsize img@src",
      "downloadUrls": "text.本地下载@href",
      "intro": ".dl_rjjs@html",
      "kind": ".dl_kk_info li.4:6@text##.*：",
      "name": ".dlbt_wz@text##《|》.*",
      "tocUrl": "",
      "wordCount": ".dl_kk_info li.0@text##.*：|\\s-.*"
    },
    "ruleContent": {
      "content": "@js:content=java.getString(\".plus_l li:not(:has(span))@html\",false)+'<br> ━ 长按选择浏览器打开下载 ━ <br>'+java.getElements(\".dl_kkbd_ccc a\")\n.toArray()\n.map(a => '【' + a.text() + '】http://www.freexiaoshuo.com' + a.attr('href'))\n.join('\\n');",
      "replaceRegex": "",
      "webJs": ""
    },
    "ruleExplore": {
      "bookList": ".pldal",
      "bookUrl": "a.1@href",
      "coverUrl": "img.0@src",
      "intro": ".pldal_r1_jj@text",
      "kind": "a.2@text&&span.0@text##\\[|\\]",
      "name": "a.1@text##《|》.*"
    },
    "ruleReview": {},
    "ruleSearch": {
      "bookList": ".pldals",
      "bookUrl": "a.1@href",
      "coverUrl": "img.0@src",
      "intro": ".pldal_r1_jj@text",
      "kind": "a.2@text&&span.1@text",
      "name": "a.1@text##《|》.*",
      "wordCount": "span.2@text"
    },
    "ruleToc": {
      "chapterList": ".dlbt_wz",
      "chapterName": "text##《|》.*",
      "chapterUrl": ""
    },
    "searchUrl": "/plus/search.php,{\n  \"charset\": \"gb2312\",\n  \"method\": \"post\",\n  \"body\": \"kwtype=0&q={{key}}\",\n  \"webView\": true\n}",
    "weight": 0
  }
这个书源下载文件url需要跳转,无法正确获取文件名和后缀

**Comment by Xwite** [comment]
不能自己请求吗

**Comment by gedoor** [comment]
自己请求一样要请求两次,可以先判断url里面有没有文件名,没有就请求一下,感觉这样比较好

**Comment by Xwite** [comment]
Location里面有链接 用head方式可以获取到
改一下UrlUtils

**Comment by gedoor** [comment]
我来测试一下

**Comment by Xwite** [comment]
感觉可以支持导入本地和WebDav的压缩文件，把文件类书源的解压过程放到LocalBook

**Comment by gedoor** [comment]
确实

Xwite ***@***.***> 于 2023年3月15日周三 19:05写道：
