### ISSUE TITLE
华为手机总是被杀后台

### ISSUE THREAD

**Issue by yangym95** [gedoor/legado#2883]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

mate40pro，刷gms了，NOH-ANOO 3.0，3月16日发现阅读3.0听书锁屏会被杀后台

### 复现步骤 / How to reproduce

启动项改手动，允许后台运行、自启动、关联，打开小说听书，锁屏放下手机，后台语音维持3-5s就停了，解锁重新开阅读有启动动画。

### 阅读版本 / Legado version

3.23.031520

### Android版本 / Android version

鸿蒙3.0

### 机型 / Model

mate40pro

**Comment by 821938089** [comment]
朗读设置里面有个唤醒锁，打开它试试

**Comment by yangym95** [comment]
> 朗读设置里面有个唤醒锁，打开它试试

没有变化，锁屏3s左右就停了

**Comment by yangym95** [comment]
试了试x点的语音读书，锁屏可以运行

**Comment by 821938089** [comment]
后台任务卡片有没有加锁

**Comment by yangym95** [comment]
> 后台任务卡片有没有加锁

啥意思？

**Comment by 821938089** [comment]
手机从底部上滑不是会显示多任务么，这里有没有加锁

**Comment by yangym95** [comment]
> 手机从底部上滑不是会显示多任务么，这里有没有加锁

试过加锁了，没变化

**Comment by yangym95** [comment]
> 手机从底部上滑不是会显示多任务么，这里有没有加锁

我感觉是鸿蒙没识别出来阅读的音频，因为开语音之后控制中心里看不见阅读播放，以前能看见

**Comment by 821938089** [comment]
那你有没有开了阅读的其他设置里面的忽略音频焦点

**Comment by yangym95** [comment]
> 那你有没有开了阅读的其他设置里面的忽略音频焦点

开过了，基本能设置的我都试过。昨天晚上我刷的gsm框架，有没有关系？一开始我怕是软件的问题，把这两天安装的除了gsm框架以外的app都删了也没变化，才来这提问的。

**Comment by 821938089** [comment]
关了忽略音频焦点也一样吗？

阅读在朗读的时候有没有通知显示？

**Comment by yangym95** [comment]
> 关了忽略音频焦点也一样吗？
> 
> 阅读在朗读的时候有没有通知显示？

有通知显示

**Comment by 821938089** [comment]
那看一下`我的->关于->崩溃日志`、`书架右上角三点里面的日志`里面有没有东西

**Comment by yangym95** [comment]
> 那看一下`我的->关于->崩溃日志`、`书架右上角三点里面的日志`里面有没有东西

崩溃日志是空白的，书架日志都是小说目录更新失败

**Comment by 821938089** [comment]
那不知道是啥问题了，你可以试试备份之后卸载重新安装一下阅读

**Comment by yangym95** [comment]
> 那不知道是啥问题了，你可以试试备份之后卸载重新安装一下阅读

试过了，正式和测试版都试过

**Comment by gedoor** [comment]
找不到原因没办法解决,,解锁重新启动应用还是被杀后台了

**Comment by mortal1976** [comment]
也遇到这个问题了，经过尝试，最后一个不被杀后台的是3.22.101712，从3.22.102020开始试了很多个版本，不管是朗读还是放后台，都可能被杀，后台关屏朗读100%被杀后台。lz可以尝试3.22.101712

**Comment by mortal1976** [comment]
不知道是否是3.22.102020版本的“添加web服务唤醒锁开关,默认关闭,有些手机开启唤醒锁会被杀后台”导致的

**Comment by 821938089** [comment]
@mortal1976 
你先试一下打开唤醒锁有没有问题

然后再试一下这个版本有没有问题 [3.22.101709](https://github.com/gedoor/legado/releases/tag/3.22.101709)

**Comment by mortal1976** [comment]
> 

今年的版本，不管是否打开唤醒锁都会被杀，我是从新到旧测试的，之前测试过去年7月的版本也没问题，所以大概率是10月后的版本bug

**Comment by yangym95** [comment]
> 也遇到这个问题了，经过尝试，最后一个不被杀后台的是3.22.101712，从3.22.102020开始试了很多个版本，不管是朗读还是放后台，都可能被杀，后台关屏朗读100%被杀后台。lz可以尝试3.22.101712

厉害👍，我用你说的版本就不杀后台了
