### ISSUE TITLE
书源里的URL栏不一定就得是个链接

### ISSUE THREAD

**Issue by xingluo233** [gedoor/legado#2885]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

某个书源，里面的所有url里都有一个uuId，每个uuid只能使用一次，而阅读里，url得先在上个页面生成，这样就会出问题，比如正文页的地址在目录那里就已经生成了，到正文页第一次访问是没问题，但是一刷新就会因为相同的uuid而出问题，而阅读里的url栏又不能只填个id

### 期望实现方式

建议支持只在上个页面只传个bookid到下个页面，URL在下个页面生成，这样就不会出现上面的问题

**Comment by 821938089** [comment]
？不是跟你说了用js生成吗

**Comment by xingluo233** [comment]
> ？不是跟你说了用js生成吗

这样在url栏还是得填个url啊，我的建议是url栏可以只填个id，不一定就是url

**Comment by 821938089** [comment]
![image](https://user-images.githubusercontent.com/8674809/225808842-5de3fdd5-b931-4664-8e98-59c689f4dee6.png)
