### ISSUE TITLE
[Rhino] for of 不能使用

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#2887]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

for of在js里不能使用，https://github.com/gedoor/legado/commit/0df2c69539e3917f21f76c0489148540bfb0b0f0 之前是可用的，修复过后就不能用了

### 复现步骤 / How to reproduce

```json
{
  "bookSourceName": "for of/in",
  "bookSourceType": 0,
  "bookSourceUrl": "https://www.baidu.com",
  "customOrder": 0,
  "enabled": true,
  "enabledCookieJar": true,
  "enabledExplore": true,
  "enabledReview": false,
  "lastUpdateTime": 1679102951566,
  "respondTime": 180000,
  "ruleBookInfo": {},
  "ruleContent": {},
  "ruleExplore": {},
  "ruleReview": {},
  "ruleSearch": {},
  "ruleToc": {},
  "searchUrl": "<js>\nlet a=[1,2,3]\njava.log(\"for \")\nfor (let i = 0,l=a.length;i<l;i++){\n\tjava.log(a[i])\n}\njava.log(\"for of\")\nfor (let o of a){\n\tjava.log(o)\n}\njava.log(\"for in\")\nfor (let o in a){\n\tjava.log(o)\n}\n</js>",
  "weight": 0
}
```

导入书源然后调试会报错
`org.mozilla.javascript.EvaluatorException: missing ; after for-loop initializer`

### 阅读版本 / Legado version

3.23.031520

### Android版本 / Android version

12

### 机型 / Model

none

**Comment by gedoor** [comment]
我看看

**Comment by gedoor** [comment]
解决了
