### ISSUE TITLE
我能否从调试接口获取到某个目录的所有章节

### ISSUE THREAD

**Issue by zhangzw218** [gedoor/legado#2888]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

![image](https://user-images.githubusercontent.com/40768649/226092850-e92e96ca-bdae-43f0-8e86-3277a121a4b4.png)
请问我有没有办法获取到某个目录链接内，所有的章节地址和名称？

### 期望实现方式

1.能否以APP为书源服务器，我通过接口，做二次处理？
2.传入一个书名，返回多个书源搜索结果。
3.传入一个书籍网址，返回所有章节目录。
4.传入一个章节地址，返回章节内容。
……
我目前上面4步，都是通过调试接口来完成，
而第3步，获取目录的方式如图：
但这需要对每个书源输入日志语句
![image](https://user-images.githubusercontent.com/40768649/226093475-67b390fc-44f6-4e5c-aaa9-2c343fe6b9d1.png)

能否为第3步提供一个专门的语句，比如将目录上的++改成**这样，然后就能返回所有目录了？

>

**Comment by 821938089** [comment]
用js把目录打印出来

**Comment by zhangzw218** [comment]
> 用js把目录打印出来

。。额。回复好快，我还在修改问题。
能否为第3步提供一个专门的查询规则，比如将目录上的++改成**这样，然后就能返回所有目录了。
如果加日志的话，我就需要对原始书源写入其他命令了。

**Comment by Xwite** [comment]
这不是吗https://github.com/gedoor/legado/blob/master/api.md

**Comment by zhangzw218** [comment]
> 这不是吗https://github.com/gedoor/legado/blob/master/api.md

这个应该是获取APP上已经有的书籍？
不存在的书好像需要先添加一次，那么后续的章节目录的获取，应该需要APP上去更新一下书籍，没办法通过这个接口实时获得？

**Comment by zhangzw218** [comment]
其实，我就是想将APP当成一个书源规则的服务，提供（搜索、详情、目录、章节）功能。
然后发现，可以通过调试接口，间接达到类似目的。。
不过目录的获取没有那么如意，就来求助，一个不需要修改书源规则就能获取到目录的办法。
