### ISSUE TITLE
书源本地导入格式不对…

### ISSUE THREAD

**Issue by a8214983** [gedoor/legado#2893]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

我的本地书源导入没办法导入耶，都显示格式不对，已经重复很多次了都一样不知道怎么回事。
![Screenshot_20230321-032253](https://user-images.githubusercontent.com/84130703/226446750-ddab75c9-b2a9-4aef-892b-4eddc577ac48.jpg)

### 复现步骤 / How to reproduce

我的>书源管理>本地导入>点选要导入的档案>格式错误

### 阅读版本 / Legado version

3.23.032021

### Android版本 / Android version

Android 6.0.1

### 机型 / Model

ASUS ZE550KL

**Comment by 821938089** [comment]
上传书源文件

**Comment by a8214983** [comment]
我把书源导出后再本地导入都会显示格式不对
![Screenshot_20230321-150512](https://user-images.githubusercontent.com/84130703/226539556-645a968b-4d79-4f54-a8e4-e9b50017b507.jpg)

不会上传档案只能放图片

**Comment by 821938089** [comment]
![image](https://user-images.githubusercontent.com/8674809/226560425-4e80dbd9-2b9a-4281-979d-b237fba2c76b.png)
点一下这里就能上传文件了，文件后缀名可能需要改成txt才能上传

**Comment by a8214983** [comment]
[shareBookSource.txt](https://github.com/gedoor/legado/files/11041541/shareBookSource.txt)
我的书源有2千多个，想要在加入1千多个书源本地导入都会显示格式不对，删掉全部书源在导入倒是可以导入。

**Comment by 821938089** [comment]
应该是应用内存不足，你把阅读关掉，然后用系统文件管理打开书源文件导入
