### ISSUE TITLE
2.0拷贝单个书源到3.0出bug

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#2899]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

更新了昨天的版本 2.0拷贝单个书源到3.0只能粘贴上书名和源url

### 复现步骤 / How to reproduce

2.0拷贝单个书源 到3.0书源管理粘贴源，现在粘贴完只有书源名和书源url 之前粘贴除了默认打开cookiejar没问题
下了最新版3.23.032212依然这样

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.032123

### Android版本 / Android version

android11

### 机型 / Model

meizu18

**Comment by gedoor** [comment]
OK

ladia ***@***.***> 于 2023年3月22日周三 15:10写道：

**Comment by gedoor** [comment]
已修复
