### ISSUE TITLE
希望能够在首页添加切换主题的功能

### ISSUE THREAD

**Issue by cathaysia** [gedoor/legado#290]
我在晚上看书时一般会将主题调换成夜间模式。但是当白天我打开阅读的时候，我几乎没办法看到《阅读》的界面，唯一的办法是盲操一番，过程简述如下：

1. 凭借感觉先点进一本书
2. 然后再呼出菜单
3. 最后凭感觉点击切换夜间模式的按钮

这个问题同样存在于掌阅上，但是现在我在使用 Firefox preview，它有一个这样的按钮：
![截屏_20200803_183016](https://user-images.githubusercontent.com/42114817/89173961-aad46880-d5b7-11ea-8132-90c7ac551a4a.jpg)

我感觉很有意思，那么可以可以在首页也添加这样一个大按钮呢，概念图如下：

![效果图](https://user-images.githubusercontent.com/42114817/89175360-351dcc00-d5ba-11ea-9e22-4a6153a042b2.png)

**Comment by zhj9709** [comment]
不喜欢这种，有点挡
![image](https://user-images.githubusercontent.com/13991774/89179085-985f2c80-d5c1-11ea-8020-accdc2d57e22.png)
而且这里设置也不麻烦，也不至于看不见吧
