### ISSUE TITLE
通过“远程书籍”选择坚果云webdav目录下txt文件 点击 放入书架 提示导入错误 Permission Denies

### ISSUE THREAD

**Issue by moyunhaipatruus** [gedoor/legado#2900]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

通过“远程书籍”选择坚果云webdav目录下txt文件 点击 放入书架 提示导入错误 Permission Denies

### 复现步骤 / How to reproduce

通过“远程书籍”选择坚果云webdav目录下txt文件 点击 放入书架 提示导

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.032123

### Android版本 / Android version

Android 9

### 机型 / Model

文石 BOOX Poke4

**Comment by 821938089** [comment]
重新设置书籍保存目录

**Comment by moyunhaipatruus** [comment]
请问在哪里设置“书籍保存目录” ？完全没找到这个功能
