### ISSUE TITLE
本地文件加载方式错误

### ISSUE THREAD

**Issue by Pantyhose-X** [gedoor/legado#2901]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 目录错误占用更多的空间。就不能提供一个禁止目录的选项？ 正确的加载方式应该像 文本编辑器 那样加载并自动换行就行。
![Screenshot_20230322210306](https://user-images.githubusercontent.com/42504385/226916323-cafa39ef-8468-436d-87c8-1e29585f2229.jpg)

### 静读天下的加载
![Screenshot_20230322210316](https://user-images.githubusercontent.com/42504385/226916397-a0c721f7-17c4-4ee2-8f18-8c5bebd4c4a9.jpg)

### 复现步骤 / How to reproduce

1.添加本地 [慈悲道场水忏法科注.txt](https://github.com/gedoor/legado/files/11040317/default.txt) 这里是书籍，你可以重现这个错误
2.进入界面把字号 拉到0，更明显

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.032123

### Android版本 / Android version

Android 8.0

### 机型 / Model

huawei

**Comment by gedoor** [comment]
txt目录规则是可以自定义的,不属于软件bug
