### ISSUE TITLE
滚动阅读时,多手指触摸事件触发导致屏幕闪烁

### ISSUE THREAD

**Issue by jaredtech** [gedoor/legado#2913]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

滚动阅读的情况下，多手指触摸拖动屏幕，计算触碰点(`touchX touchY`)时使用多点的位置平均值可能导致触碰点不在当前视图中心导致闪烁。在大屏窄边框的设备单手握持的的情况下，滑动文字时，虎口经常误触导致触摸点重新计算发生闪烁，阅读效果不好。

### 复现步骤 / How to reproduce

滚动阅读情况下，向下滑动再同时点击任意阅读区域

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.032112

### Android版本 / Android version

Android 13

### 机型 / Model

Nubia Z50 Ultra

**Comment by gedoor** [comment]
收到

**Comment by jaredtech** [comment]
> 收到

不太理解为什么`ScrollPageDelegate`的这个方法
```
    private fun onScroll(event: MotionEvent) {
        ......
        // Determine focal point
        var sumX = 0f
        var sumY = 0f
        val count: Int = event.pointerCount
        for (i in 0 until count) {
            if (skipIndex == i) continue
            sumX += event.getX(i)
            sumY += event.getY(i)
        }
        val div = if (pointerUp) count - 1 else count
        val focusX = sumX / div
        val focusY = sumY / div
        readView.setTouchPoint(sumX, sumY)
        ......
    }
```
要取多个触摸点的坐标的平均值，但造成闪烁(错误滚动到上一页)确实是因为这个计算方式，而如果只默认取第一个触摸的手指位置，则不会出现这样的问题
```
    private fun onScroll(event: MotionEvent) {
        ......
        readView.setTouchPoint(event.getX(0), event.getY(0))
        if (!isMoved) {
            val deltaX = (event.getX(0) - startX).toInt()
            val deltaY = (event.getY(0) - startY).toInt()
            val distance = deltaX * deltaX + deltaY * deltaY
            isMoved = distance > readView.slopSquare
        }
        ......
    }
```
不知原来的代码有什么作用，就不pull代码了

**Comment by gedoor** [comment]
这几天一直忙别的没顾得上,我看看,没问题我就直接照这个改了,之前的也忘了为啥那样写了

**Comment by gedoor** [comment]
现在都是全面屏,握着手机的时候可能触碰到屏幕,这时另一只手滑动如果只取第一个触摸点就无法滑动了,原来的计算方法也有问题,我再想想
