### ISSUE TITLE
调试时详情页链接为搜索地址

### ISSUE THREAD

**Issue by xingluo233** [gedoor/legado#2914]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

调试时，详情页的地址一直为搜索地址[书源](https://shuyuan.mgz6.cc/shuyuan/1e307f2d10604941777435f99137446b.json) 
![Screenshot_2023-03-26-12-53-08-408_io legado app release](https://user-images.githubusercontent.com/54618947/227756262-2d135c56-eecd-4d2d-b96f-a386755f6257.jpg)
![Screenshot_2023-03-26-12-52-28-446_io legado app release](https://user-images.githubusercontent.com/54618947/227756265-2b426515-ed98-4b12-ae95-4102645a71bc.jpg)
当详情页url栏填写$.id时却不会出现这个问题，其他不管填什么都会这样
![Screenshot_2023-03-26-13-02-36-244_io legado app release](https://user-images.githubusercontent.com/54618947/227756351-6ef8b7ea-3585-4e4f-9805-47221dcb8fc5.jpg)
![Screenshot_2023-03-26-13-02-45-028_io legado app release](https://user-images.githubusercontent.com/54618947/227756356-6e8b0c80-f446-4b3e-b6d0-cb280c7204cf.jpg)

### 复现步骤 / How to reproduce

如上

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.032123

### Android版本 / Android version

Android 13

### 机型 / Model

Xiaomi 10

**Comment by Xwite** [comment]
<js>
eval(String(source.bookSourceComment))
decrypt(result)
</js>$.result.list
