### ISSUE TITLE
NativeObject规则扩展和在线书籍导出

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#2915]
- [x] 导出本地文件时不应保留vip标识 #2682 https://github.com/gedoor/legado/commit/6f10337904a657cdb53bf9d011dfec4bc517b490
- [x] 列表规则为`NativeObject`时 只能以键值访问 #2914  https://github.com/gedoor/legado/commit/28d90203954d5912c5ac717733eb48b415e45611
```js
# 列表规则
<js>JSON.parse("{a:1,b:2}")</js>
# 其他规则
a // 返回 1
http://www.example.com/{{a}}.html // 返回null
```

**Comment by gedoor** [comment]
要不把列表变量弄到js里面吧

**Comment by Xwite** [comment]
这样吗
```js
http://www.example.com/{{result.a}}.html
// http://www.example.com/1.html
```

**Comment by gedoor** [comment]
嗯

**Comment by xingluo233** [comment]
话说我那个建议里的，当章节内容为空时，比如分卷章节，导出会是null，要不直接导出为空章节吧

**Comment by gedoor** [comment]
![image](https://user-images.githubusercontent.com/22701807/227774130-56ca80d5-e031-4319-a27b-fcf8cb6110b4.png)
改下这里,只有一个规则时走这个

**Comment by gedoor** [comment]
![image](https://user-images.githubusercontent.com/22701807/227774219-0a923a8b-f9b3-4a50-ba3f-dcea59f12c2c.png)
看看这样改有没有其它不好的影响

**Comment by 821938089** [comment]
@xingluo233 这个我记得我改过了

**Comment by xingluo233** [comment]
> @xingluo233 这个我记得我改过了

嗷嗷，好的

**Comment by gedoor** [comment]
![image](https://user-images.githubusercontent.com/22701807/227775477-7c0abf0d-3b24-4d41-81a7-cb1f57112383.png)

**Comment by Xwite** [comment]
这样好像可以了
