### ISSUE TITLE
你好，能否把系统支持版本下降到4.4

### ISSUE THREAD

**Issue by asdfj2381k** [gedoor/legado#292]
手上有一台小米1

MIUI最新只能更新到MIUI9，安卓版本是4.4

所以就没办法装阅读了，好痛苦。

**Comment by 10bits** [comment]
fork到自己的仓库,修改一下配置,点一下Star,可以在线编译

**Comment by asdfj2381k** [comment]
@10bits   好厉害啊，学习到了，谢谢

**Comment by aitianci** [comment]
小米1真是唤起了我的回忆，还是八九年前的机型，那时候超级火，而且是大学生能买得起的唯一一台像样的手机。
