### ISSUE TITLE
当使用有声书源听书时，锁屏再解锁后，目录回跳的问题

### ISSUE THREAD

**Issue by borpubi** [gedoor/legado#2920]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

当使用有声书源听有声小说时，锁定屏幕，再重新解锁，会打乱光前正在听书的章节，拼命往前跳。

### 复现步骤 / How to reproduce

使用有声书源听书，听的过程中直接锁定屏幕，然后重新解锁即可触发。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.031210 PRO

### Android版本 / Android version

Android 12

### 机型 / Model

IQOO 3

**Comment by 821938089** [comment]
发个视频看一下

**Comment by borpubi** [comment]
需要同时打开 李跳跳 才会出现

**Comment by borpubi** [comment]
点错了，锁屏录不到，看上去就像突然往前跳一样。

https://user-images.githubusercontent.com/28093885/227830710-5ee0980b-8621-47ec-bd84-1a5ba03be7ff.mp4

**Comment by 821938089** [comment]
将阅读加入李跳跳的黑名单里就行

**Comment by borpubi** [comment]
已设置，果然没问题了。不过老版本 3.22.11XXXXX的没问题。

**Comment by borpubi** [comment]
已设置，果然没问题了。不过老版本 3.22.11XXXXX的没问题。
