### ISSUE TITLE
ios版本有吗

### ISSUE THREAD

**Issue by huahai547** [gedoor/legado#2921]
### 确认 / Assignments

- [ ] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

ios版本有吗

### 期望实现方式 / How to implement

ios版本有吗

### 附加信息 / Additions

ios版本有吗

### 效果演示 / Demo

ios版本有吗

**Comment by 821938089** [comment]
没有

**Comment by wazk9595** [comment]
永远都不会有

**Comment by ccheneasy** [comment]
ios有类似的看书嘛

**Comment by Logan-CN** [comment]
> 永远都不会有

请问ios是应该政策原因，还是技术原因呢？
