### ISSUE TITLE
最新版闪退

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#2926]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

1.最新版安装后闪退，打不开程序。清除数据或者重新安装后可用。
2.不能恢复备份。webdev会显示没有配置，本地备份会报错。
3.换源时会闪退。
4.某些书源不能使用。

### 复现步骤 / How to reproduce

1.安装新版后闪退，打不开软件，没有日志。
2.不能恢复备份
![Screenshot_2023-03-29-01-21-34-326_阅读](https://user-images.githubusercontent.com/74254385/228327142-bd925b2a-5167-4105-97a0-8bf847697e08.png)
![Screenshot_2023-03-29-01-21-37-831_阅读](https://user-images.githubusercontent.com/74254385/228327152-eb00041d-325b-42bc-be64-9dbaab23bba0.png)

3.换源会闪退
![Screenshot_2023-03-29-01-32-35-210_阅读](https://user-images.githubusercontent.com/74254385/228327261-82e71b16-675f-46c3-b08d-4cc2dcfec282.png)

4.某些书源不能使用
书源：
{
  "bookSourceComment": "",
  "bookSourceGroup": "☘️ 正版",
  "bookSourceName": "☘️ 17K小说",
  "bookSourceType": 0,
  "bookSourceUrl": "https://www.17k.com",
  "bookUrlPattern": "",
  "customOrder": 0,
  "enabled": true,
  "enabledCookieJar": false,
  "enabledExplore": true,
  "enabledReview": false,
  "exploreUrl": "[{\"title\":\"✵  男 ♂ 榜  ✵\",\"url\":\"\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"总收藏\",\"url\":\"/all/book/2_0_0_0_0_7_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"月收藏\",\"url\":\"/all/book/2_0_0_0_0_6_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"周收藏\",\"url\":\"/all/book/2_0_0_0_0_5_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"总点击\",\"url\":\"/all/book/2_0_0_0_0_4_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"月点击\",\"url\":\"/all/book/2_0_0_0_0_3_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"周点击\",\"url\":\"/all/book/2_0_0_0_0_2_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"总字数\",\"url\":\"/all/book/2_0_0_0_0_1_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  男 ♂ 生  ✵\",\"url\":\"/all/book/2_0_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"✵  玄幻奇幻  ✵\",\"url\":\"/all/book/2_21_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"异世争霸\",\"url\":\"/all/book/2_21_115_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"魔法校园\",\"url\":\"/all/book/2_21_122_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"领主贵族\",\"url\":\"/all/book/2_21_123_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"西方奇幻\",\"url\":\"/all/book/2_21_1_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"东方玄幻\",\"url\":\"/all/book/2_21_8_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"异世大陆\",\"url\":\"/all/book/2_21_83_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"异术超能\",\"url\":\"/all/book/2_21_84_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  武侠仙侠  ✵\",\"url\":\"/all/book/2_24_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"洪荒封神\",\"url\":\"/all/book/2_24_85_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"现代异侠\",\"url\":\"/all/book/2_24_96_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"历史武侠\",\"url\":\"/all/book/2_24_124_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"奇幻修真\",\"url\":\"/all/book/2_24_82_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"国术古武\",\"url\":\"/all/book/2_24_125_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"传统武侠\",\"url\":\"/all/book/2_24_2_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"现代修真\",\"url\":\"/all/book/2_24_81_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"古典仙侠\",\"url\":\"/all/book/2_24_9_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  都市小说  ✵\",\"url\":\"/all/book/2_3_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"都市生活\",\"url\":\"/all/book/2_3_3_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"都市异能\",\"url\":\"/all/book/2_3_87_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"都市重生\",\"url\":\"/all/book/2_3_89_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"职场励志\",\"url\":\"/all/book/2_3_90_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"现实题材\",\"url\":\"/all/book/2_3_91_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"娱乐明星\",\"url\":\"/all/book/2_3_116_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"都市激战\",\"url\":\"/all/book/2_3_92_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"商业大亨\",\"url\":\"/all/book/2_3_117_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"校园风云\",\"url\":\"/all/book/2_3_118_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"乡村乡土\",\"url\":\"/all/book/2_3_119_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  历史军事  ✵\",\"url\":\"/all/book/2_22_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"历史穿越\",\"url\":\"/all/book/2_22_4_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"架空历史\",\"url\":\"/all/book/2_22_93_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"战争幻想\",\"url\":\"/all/book/2_22_11_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"军旅生涯\",\"url\":\"/all/book/2_22_94_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"历史传记\",\"url\":\"/all/book/2_22_120_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"战史风云\",\"url\":\"/all/book/2_22_126_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"谍战特工\",\"url\":\"/all/book/2_22_127_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  游戏竞技  ✵\",\"url\":\"/all/book/2_23_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"虚拟网游\",\"url\":\"/all/book/2_23_5_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"电子竞技\",\"url\":\"/all/book/2_23_12_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"游戏生涯\",\"url\":\"/all/book/2_23_14_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"篮球风云\",\"url\":\"/all/book/2_23_97_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"天下足球\",\"url\":\"/all/book/2_23_98_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"棋牌桌游\",\"url\":\"/all/book/2_23_99_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"游戏异界\",\"url\":\"/all/book/2_23_121_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"体育竞技\",\"url\":\"/all/book/2_23_100_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  科幻末世  ✵\",\"url\":\"/all/book/2_14_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"末世危机\",\"url\":\"/all/book/2_14_128_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"进化变异\",\"url\":\"/all/book/2_14_129_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"时空穿梭\",\"url\":\"/all/book/2_14_130_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"未来幻想\",\"url\":\"/all/book/2_14_6_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"古武机甲\",\"url\":\"/all/book/2_14_131_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"星际战争\",\"url\":\"/all/book/2_14_95_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"✵  悬疑推理  ✵\",\"url\":\"/all/book/2_29_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"民间奇谈\",\"url\":\"/all/book/2_29_179_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"恐怖悬疑\",\"url\":\"/all/book/2_29_180_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"侦探推理\",\"url\":\"/all/book/2_29_181_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"探险揭秘\",\"url\":\"/all/book/2_29_182_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  轻小说  ✵\",\"url\":\"/all/book/2_30_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"搞笑幽默\",\"url\":\"/all/book/2_30_183_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"男生同人\",\"url\":\"/all/book/2_30_184_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"宅系小说\",\"url\":\"/all/book/2_30_185_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"萌系小说\",\"url\":\"/all/book/2_30_186_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"灵魂转换\",\"url\":\"/all/book/2_30_187_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  女 ♀ 榜  ✵\",\"url\":\"\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"总收藏\",\"url\":\"/all/book/3_0_0_0_0_7_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"月收藏\",\"url\":\"/all/book/3_0_0_0_0_6_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"周收藏\",\"url\":\"/all/book/3_0_0_0_0_5_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"总点击\",\"url\":\"/all/book/3_0_0_0_0_4_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"月点击\",\"url\":\"/all/book/3_0_0_0_0_3_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"周点击\",\"url\":\"/all/book/3_0_0_0_0_2_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"总字数\",\"url\":\"/all/book/3_0_0_0_0_1_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  女 ♀ 生  ✵\",\"url\":\"/all/book/3_0_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"✵  都市言情  ✵\",\"url\":\"/all/book/3_17_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"总裁豪门\",\"url\":\"/all/book/3_17_134_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"游戏情缘\",\"url\":\"/all/book/3_17_135_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"都市情缘\",\"url\":\"/all/book/3_17_136_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"现代重生\",\"url\":\"/all/book/3_17_166_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"娱乐明星\",\"url\":\"/all/book/3_17_167_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"民国旧影\",\"url\":\"/all/book/3_17_168_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"跨国情缘\",\"url\":\"/all/book/3_17_169_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"职场丽人\",\"url\":\"/all/book/3_17_16_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"婚恋爱情\",\"url\":\"/all/book/3_17_26_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"✵  古装言情  ✵\",\"url\":\"/all/book/3_5_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"快意江湖\",\"url\":\"/all/book/3_5_132_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"架空历史\",\"url\":\"/all/book/3_5_133_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"古代重生\",\"url\":\"/all/book/3_5_139_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"前世今生\",\"url\":\"/all/book/3_5_140_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"经商种田\",\"url\":\"/all/book/3_5_165_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"宫廷贵族\",\"url\":\"/all/book/3_5_10_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"穿越时空\",\"url\":\"/all/book/3_5_22_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"家宅恩怨\",\"url\":\"/all/book/3_5_7_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  幻想言情  ✵\",\"url\":\"/all/book/3_18_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"玄幻仙侠\",\"url\":\"/all/book/3_18_137_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"异界魔法\",\"url\":\"/all/book/3_18_138_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"星际科幻\",\"url\":\"/all/book/3_18_170_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"灵异悬疑\",\"url\":\"/all/book/3_18_24_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"末世危机\",\"url\":\"/all/book/3_18_171_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"异能空间\",\"url\":\"/all/book/3_18_172_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"西方奇幻\",\"url\":\"/all/book/3_18_173_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"唯美纯爱\",\"url\":\"/all/book/3_18_437_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.296}},\n{\"title\":\"✵  浪漫青春  ✵\",\"url\":\"/all/book/3_20_0_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1,\"layout_flexGrow\":1}},\n{\"title\":\"网配快穿\",\"url\":\"/all/book/3_20_148_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"校园青春\",\"url\":\"/all/book/3_20_175_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"纯爱青春\",\"url\":\"/all/book/3_20_176_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.25,\"layout_flexGrow\":1}},\n{\"title\":\"悲伤青春\",\"url\":\"/all/book/3_20_177_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.295}},\n{\"title\":\"女生同人\",\"url\":\"/all/book/3_20_178_0_0_0_0_1_{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":0.295}}]",
  "header": "",
  "lastUpdateTime": 1666136268440,
  "loginUrl": "https://passport.17k.com/login",
  "respondTime": 39812,
  "ruleBookInfo": {
    "author": ".Author a@text",
    "coverUrl": "",
    "init": "",
    "intro": "",
    "kind": "",
    "lastChapter": "",
    "name": ".Title@text",
    "tocUrl": "text.点击阅读@href",
    "wordCount": ""
  },
  "ruleContent": {
    "content": ".p p:not([class])@html",
    "nextContentUrl": "",
    "sourceRegex": "",
    "webJs": ""
  },
  "ruleExplore": {
    "author": "a.4@text",
    "bookList": ".alltextlist",
    "bookUrl": "a.3@href",
    "coverUrl": "img@src",
    "intro": "a.-2@text##(^|[。！？]+[”」）】]?)##$1<br>",
    "kind": "a.5@text&&cite@text##\\s.*",
    "lastChapter": "a.-1@text##[\\(（【].*?[求更谢乐发订合补加].*?[】）\\)]",
    "name": "a.3@text",
    "wordCount": "code@text"
  },
  "ruleReview": {},
  "ruleSearch": {
    "author": "author",
    "bookList": ".textlist!0\n<js>\nresult.toArray().map(o=>{\n    var detail = String(o.select('dt a').attr('href')).replace('//','https://');\n    var J = org.jsoup.Jsoup.parse(java.ajax(detail));\n    return {\n       name:  o.select('dt a').text(),\n       author:String(o.select('.ls a').text()).replace('作者：',''),\n       tags:  String(o.select('.bq span:eq(1)').text()).replace('类别：',''),\n       num: String(o.select('.bq span:eq(2)').text()).replace('字数：',''),\n       latest: String(J.select('dl.NewsChapter a').last().text()).replace(/[\\(（].*[求更谢乐发订合补加].*[）\\)]/,''),\n       intro: String(o.select('li:eq(2)').text()).replace('简介：','').trim(),\n       cover: o.select('img').attr('src'),\n       catalogUrl: 'https://www.17k.com'+J.select('.read a').attr('href')\n    }\n});\n</js>",
    "bookUrl": "catalogUrl",
    "coverUrl": "cover",
    "intro": "intro",
    "kind": "tags",
    "lastChapter": "latest",
    "name": "name",
    "wordCount": "num"
  },
  "ruleToc": {
    "chapterList": ".Volume dd a",
    "chapterName": "text##[\\(（【].*?[求更谢乐发订合补加].*?[】）\\)]",
    "chapterUrl": "href",
    "isVip": "@js:result.select('span').hasClass('vip')",
    "nextTocUrl": "",
    "updateTime": ""
  },
  "searchUrl": "https://search.17k.com/search.xhtml?c.q={{key}}&page={{page}}",
  "weight": 0
}
这是调试时截图
![Screenshot_2023-03-29-01-29-45-690_阅读](https://user-images.githubusercontent.com/74254385/228326392-4c099ab9-0152-48fa-b2c5-fd323f46309a.png)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22.032820

### Android版本 / Android version

6

### 机型 / Model

sm919

**Comment by gedoor** [comment]
收到

sartonsh ***@***.***> 于 2023年3月29日周三 01:57写道：

**Comment by gedoor** [comment]
恢复备份解决了,老系统该淘汰了

**Comment by sartonsh** [comment]
我试了下测试版，恢复备份还是有问题。webdev恢复会显示没有配置，本地恢复可以恢复。但杀掉后台重启程序会闪退，程序就打不开了。删除数据后可以打开程序，我试了下就填写webdev的账号，密码，然后杀后台重启也会闪退。

**Comment by gedoor** [comment]
OK

sartonsh ***@***.***> 于 2023年3月29日周三 20:24写道：

**Comment by sartonsh** [comment]
最新版搞定了，谢谢大佬!
