### ISSUE TITLE
能否在小说换书源时给书源最新章节大小排序,然后添加最新章节字数大小的筛选设置

### ISSUE THREAD

**Issue by javacainiaoa** [gedoor/legado#2928]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在小说换书源时,由于小说源过多,而且良莠不齐,可以加上最新章节的大小排序,自动找到有最新章节的小说源,加上最新章节的字数筛选可以筛选掉那些更新的假的最新章节,或者只更新了一个章节名的

### 期望实现方式 / How to implement

在换小说源的右上角添加筛选的设置和排序的设置,最好能支持js表达式筛选

### 效果演示 / Demo

![Screenshot_2023-03-29-10-06-41-069_io legado app](https://user-images.githubusercontent.com/46554798/228407933-9b809696-75a6-4230-be43-dc5a41670849.jpg)

**Comment by liufuyou** [comment]
感觉不好实现，要在线字数判断

**Comment by javacainiaoa** [comment]
实现确实比较麻烦,要找到每个书源的这本书的最新章节,然后获取字数判断,会比较耗时

**Comment by javacainiaoa** [comment]
> 感觉不好实现，要在线字数判断

实现确实比较麻烦,要找到每个书源的这本书的最新章节,然后获取字数判断,会比较耗时

**Comment by Xwite** [comment]
Duplicate of #2973
