### ISSUE TITLE
分组下的所有书禁止更新

### ISSUE THREAD

**Issue by XiaoXiaoYanHe** [gedoor/legado#2929]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

主要针对“完本”“回收”分组，滑到这俩分组小心翼翼的，偶尔两三次划拉到更新浑身难受。
“书架管理”的批量禁止能用，自动更好

### 期望实现方式 / How to implement

加入分组的书改为禁止更新 或者 禁止分组的下拉更新动作

**Comment by gedoor** [comment]
ok
