### ISSUE TITLE
google版的测试包  安装时解析失败

### ISSUE THREAD

**Issue by BangClieCC** [gedoor/legado#2932]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

安卓7.1.1   google版的测试包 解析失败

### 复现步骤 / How to reproduce

安卓7.1.1   google版的测试包 安装时手机提示安装包解析失败

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.2303302112

### Android版本 / Android version

7.1.1

### 机型 / Model

vivoX7plus

**Comment by gedoor** [comment]
google版本我调到最低版本8.0了

**Comment by BangClieCC** [comment]
好的，谢谢作者！
