### ISSUE TITLE
书源以有新章节，APP无法获取、阅读

### ISSUE THREAD

**Issue by zhangweildlh** [gedoor/legado#2933]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

当前已选择的源，网络端已更新了新章节。但在书架、阅读界面中无法刷新出新章节。

### 复现步骤 / How to reproduce

在换源搜索中，发现当前已选择的源，网络端已更新了新章节。
[比如《灵境行者》书源为“读书阁网1”，网络已更新到第344章]
但在书架界面、阅读界面，无论是下拉刷新；或者阅读界面 点右上角三个小点，选择“目录更新”
都停留在第第343章！
![1](https://user-images.githubusercontent.com/62597291/229278579-46adec93-5b9f-458c-88e3-d457343bb94a.jpg)
![2](https://user-images.githubusercontent.com/62597291/229278591-a10aa1ac-6c15-4000-8307-87cb223ef60b.jpg)
![3](https://user-images.githubusercontent.com/62597291/229278595-dfa99fa8-2967-4cdb-bac1-927ff69f197b.jpg)
![4](https://user-images.githubusercontent.com/62597291/229278598-c12b526b-6512-4b11-ad76-b38c4383035c.jpg)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.032923

### Android版本 / Android version

Android 10

### 机型 / Model

CC9e

**Comment by 821938089** [comment]
我这里有第344章，不过没有正文

**Comment by Xwite** [comment]
那是假更新，检查下源站吧。可以考虑勾上加载目录

**Comment by zhangweildlh** [comment]
> 那是假更新，检查下源站吧。可以考虑勾上加载目录

您好，我勾上“加载目录”后，问题依旧！

**Comment by Xwite** [comment]
你没考虑过网站的问题?
