### ISSUE TITLE
能有对特殊标记的txt的小说特殊解析吗？

### ISSUE THREAD

**Issue by TingTing1990** [gedoor/legado#2934]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

这个是iOS上的一个阅读软件，有它自己的标记开放格式进行解析，类似MD，包括元数据、封面、目录等的自定义
https://www.ambibma.com/web/zs/

希望能增加对此格式的标记进行解析，在安卓上也希望能用到，谢谢！

### 期望实现方式 / How to implement

对特殊的标记（格式）的小说进行特殊解析

### 附加信息 / Additions

附上一个含有此标记格式的小说下载链接：

https://send.vis.ee/download/6c054f36c3dd036e/#r2qgIfG2YIGZsIackJQrOQ

**Comment by TingTing1990** [comment]
大佬为啥打了忽略标签🤣，其实主要是为了统一给txt文本的小说在文件内定义元数据的方式

**Comment by 821938089** [comment]
格式太小众了，你转成epub再用阅读打开就好
