### ISSUE TITLE
Possibility to use opds catalogues

### ISSUE THREAD

**Issue by Rorschach1010** [gedoor/legado#2935]
I have a calibre server and a calibre Web Server running. Both can be reached via the opds API.

Legado doesn't seem to be able to connect to opds. I tried the "add url" option but it says error.
Then I tried the source management. Seems like I can login through WebView inside legado but I couldn't download my books directly into legado.

Am I doing something wrong or is it not possible right now?

**Comment by Xwite** [comment]
legado only supports http protocol.

**Comment by Rorschach1010** [comment]
Since I don't have a domain and don't use a reverse proxy, I use only the http protocol. So technically it should work.

The thing is, I can login within the app but I can't download the books so that the book is in my legado library with all the tags (author, series, Publisher...).

Most of the in-app help is only in Chinese so I'm not sure if I'm missing something. Is there an English guide or wiki somewhere?

**Comment by Xwite** [comment]
if you want to download file from server
set source type to `File`
`downloadUrlRule` extract file download urls
