### ISSUE TITLE
图片 img 的 src 链接获取错误

### ISSUE THREAD

**Issue by Glavor** [gedoor/legado#2939]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

原始内容：

```
<img class="wr_img" wco="365" alt src="https://res.weread.qq.com/wrepub/CB_695233_logo.png" data-w="1280px" data-ratio="1.389" style="width:3.5em">
```

阅读处理后链接错误：

```
<img src="https://weread.qq.com/wrwebsimplenjlogic/1.389">
```

### 复现步骤 / How to reproduce

如上，手动把 `data-w="1280px" data-ratio="1.389"` 这两个去掉后就正确了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040118

### Android版本 / Android version

Android 13

### 机型 / Model

小米 11 Pro

**Comment by 821938089** [comment]
阅读的图片标签匹配比较宽松，有可能会出错，你可以先自己处理一下

参考：
```js
img@src
@js:
result.split("\n").map(src => `<img src="${src}">`).join("\n")
```
