### ISSUE TITLE
正版书源购买成功后能否实现自动刷新目录以及当前章节内容

### ISSUE THREAD

**Issue by Glavor** [gedoor/legado#2942]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

正版书源购买成功后可以在购买操作的 js 代码内实现自动刷新目录以及当前章节内容。

### 期望实现方式 / How to implement

```
...
var option = { method: "POST", body: JSON.stringify(body) };
var url = "https://weread.qq.com/web/pay/buyChapters," + JSON.stringify(option);
var rep = JSON.parse(java.ajax(url));
rep.succ ? java.longToast(`购买成功！\n价格 ${rep.price} 余额 ${rep.balance}`) : java.longToast("购买失败！");
```

这是我自己写的书源的购买操作的一部分，能否在判定购买成功后通过调用函数或其他方式实现自动刷新目录以及当前章节内容。

**Comment by gedoor** [comment]
ok

**Comment by gedoor** [comment]
我改成js返回true就刷新目录和正文
