### ISSUE TITLE
小说内容不能正确显示

### ISSUE THREAD

**Issue by ohtfbbxy33** [gedoor/legado#2943]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

不显示小说内容，用lithium可以正常看，我把不能看的这个后缀epub改成png上传上来了，好几次出现这种从zlibrary下下来的出现这种情况，我之前都以为是资源的问题。
![微信图片_20230403173513](https://user-images.githubusercontent.com/70877968/229473111-fb340d62-41a5-484f-8011-f3d6f156e289.jpg)
![微信图片_20230403173521](https://user-images.githubusercontent.com/70877968/229473120-d80b3c0e-f266-4fa9-b1b3-f28d3a53e5c5.jpg)

### 复现步骤 / How to reproduce

正常添加打开就不能正常显示
![Uploading 穆斯林的葬礼 (霍达 [霍达]) (Z-Library).png…]()

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040118

### Android版本 / Android version

11

### 机型 / Model

xperia1

**Comment by 821938089** [comment]
你文件没传上来，可以把epub改zip传

**Comment by ohtfbbxy33** [comment]
> 你的文件没有传上来，可以把epub改zip传
没注意到没上传过来
[穆斯林的葬礼 (霍达 [霍达]) (Z-Library).zip](https://github.com/gedoor/legado/files/11143975/Z-Library.zip)

**Comment by Xwite** [comment]
```html
<body id="fragmentId">
....

</body>
```

**Comment by ohtfbbxy33** [comment]
我想说更新了3.23.040420虽然内容可以显示了，但是很影响体验。
这个bug是把同样的内容重复显示了。

**Comment by ohtfbbxy33** [comment]
![微信图片_20230405150159](https://user-images.githubusercontent.com/70877968/230005639-b2341db9-b727-4177-99f8-78565b6e34b7.jpg)
![微信图片_20230405150208](https://user-images.githubusercontent.com/70877968/230005663-165cbc46-1c55-49fc-b8c5-98591f3d69ec.jpg)

**Comment by ohtfbbxy33** [comment]
@821938089 能来看看么

**Comment by Xwite** [comment]
测试版修了
