### ISSUE TITLE
刷新书架后，未读标志加红强调的逻辑有问题。

### ISSUE THREAD

**Issue by zealousfool** [gedoor/legado#2944]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

![image](https://user-images.githubusercontent.com/12507338/229807946-d8b02f76-32b9-4a5c-b4b3-23440e98c0fd.png)
现在的逻辑是：刷新后，有新增章节的，未读标志才变红强调。
但是变红强调后的未读标志，在没有点开阅读前，是永久变红强调的。（对于强迫症不太友好qaq）
逻辑应该是：本次刷新后，有新增章节的，未读标志才变红强调。没有新增章节的，取消其变红强调的未读标志。
也可以新增一条比如：刷新后可选择额外的显示标志：新增0章，新增2章

### 期望实现方式 / How to implement

逻辑应该是：本次刷新后，有新增章节的，未读标志才变红强调。没有新增章节的，取消其变红强调的未读标志。
也可以新增一条比如：刷新后可选择额外的显示标志：新增0章，新增2章

**Comment by 821938089** [comment]
刷新多次的话会有问题

**Comment by 821938089** [comment]
你再刷新一下就全都不会高亮了

**Comment by zealousfool** [comment]
> 你再刷新一下就全都不会高亮了

不会，连续刷新还是高亮的。我用的应该是最新版本3.23.040118
