### ISSUE TITLE
之前好像有个从选中文字开始朗读的功能，被拿掉了吗

### ISSUE THREAD

**Issue by ll8456** [gedoor/legado#2945]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

长按选中文字后，就从那里开始朗读

### 期望实现方式 / How to implement

长按选中文字后，就从那里开始朗读

### 附加信息 / Additions

长按选中文字后，就从那里开始朗读

### 效果演示 / Demo

长按选中文字后，就从那里开始朗读

**Comment by 821938089** [comment]
长按文字选择菜单可以切换模式
