### ISSUE TITLE
希望能在缓存之后统计章节字数，方便识别一些网站的空章节

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2949]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

有时候是网站有问题导致缓存空白章节，之后导出来也不知道是空章节

### 期望实现方式 / How to implement

希望能在缓存之后的目录列表后面加个字数统计，如果有字数异常就能看出缓存内容有异常

**Comment by dxh8286239** [comment]
非常需要这个功能
