### ISSUE TITLE
希望缓存报错之后在缓存导出列表中显示出来

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#2950]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前会弹出个字幕报错，但是一闪而过，之后就看不到了，也不知道是哪本小说出了什么问题，缓存列表任务里也没显示出来

### 期望实现方式 / How to implement

错误结果在缓存导出列表当中显示出来

**Comment by 821938089** [comment]
去日志那里看看
