### ISSUE TITLE
tocUrl多链接支持

### ISSUE THREAD

**Issue by Chen-Yuanmeng** [gedoor/legado#2951]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

书源里面，目录URL规则`tocUrl`只支持单个url，希望可以支持多个url，这样可以支持目录分好几页展示的网站

### 期望实现方式 / How to implement

如类似发现中的`page`关键字标识

**Comment by 821938089** [comment]
有目录下一页规则

**Comment by Chen-Yuanmeng** [comment]
嗯谢谢，我刚入门，离入土早着呢&hellip;&hellip;


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月5日(周三) 晚上6:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] tocUrl多链接支持 (Issue #2951)




 
有目录下一页规则
 
&mdash;

**Comment by crotoc** [comment]
请问下一页规则到底怎么填啊。我发现了这样的规则，麻烦帮忙看看应该怎么填：

![image](https://user-images.githubusercontent.com/12446554/230420774-ae6e4433-da30-4fc8-96b8-31bb5275a0d1.png)

**Comment by Chen-Yuanmeng** [comment]
> 请问下一页规则到底怎么填啊。我发现

这个应该填的是“下一页”按钮指向的链接，从你这个代码好像看不出来有没有下一页
