### ISSUE TITLE
书评与书单功能

### ISSUE THREAD

**Issue by XiaoXiaoYanHe** [gedoor/legado#2952]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

看书大多三章弃，印象浅，放在“回收”分组避免重读。
在“食之无味”分组再次搜索到、书荒回头翻找，进入书签多点四下。
想在书籍信息界面直接看到弃书理由

### 期望实现方式 / How to implement

在 书籍信息-编辑书籍信息-内容简介 的下面添加书评编辑

### 附加信息 / Additions

弱需求：“书单分享”添加文本或图片方式导出，弥补链接有效期短、文件分享麻烦。
并入书签，给予书评标记，方便批量查看管理。
打分，按评分排序。方便偶尔的书荒找书。

书单导入导出时可选，看到12月讨论。
跟书源一样可选，加入时自动换源，没源给个书名作者放着。 简单粗暴我喜欢。
或者 （自动 新建分组 分享者定义ID 在线更新 全部添加）即
临时建立书单分组或挂载界面，可以放书评，点击搜索，挑选完取消分组。实现麻烦，挑书可以慢慢来。
两方案用点击搜索和自动换源都方便。自动换源怕一次百本导入，换不看的书略不爽。选择权交给用户？
实现前者书单网站干碎小半，能挂载分享者的链接或更进一步——读取百度阿里大众网盘分享的文本文件大概能干没，不过太麻烦，没必要。

### 效果演示 / Demo

书单分享格式
《书名》作者 ：匿名 【10分】
书评内容
——————华丽分割线===---
《书名》作者 ：匿名 
【五星】书评内容

**Comment by XiaoXiaoYanHe** [comment]
附加信息里的弱需求是我联想着玩的，个人只需要“书籍信息界面直接看到弃书理由”

**Comment by 821938089** [comment]
你可以直接写在简介里

**Comment by XiaoXiaoYanHe** [comment]
> 你可以直接写在简介里

原来换源不简介更新。想要专门书评分隔，方便美观点（弱气）

**Comment by FeiLZX3Km** [comment]
支持。这种需求我也时常遇到。同希望能够出一个书评的功能。因为有些书我需要加入简单的评注，以安排调整是否需要阅读、何时阅读。而且这种批注最好能够以直观的方式展示出来，而不是“直接写在简介里”看似已经解决实则深藏于其他界面，不方便寻找与使用。

**Comment by gedoor** [comment]
好的

**Comment by XiaoXiaoYanHe** [comment]
> 好的

辛苦了。 扑充些新想法。
如果采用楼上 效果展示 类似的固定格式的明文进行导出， 那么 能够明文直接导入可太方便了。
好吧，读取导入实现麻烦，使用也麻烦（完备的书单管理编辑，太重了，没必要）

实现：
增加或者将“导入书单” 换成 “书单保存”界面，保存一个个其他书友分享的书单文本，读取书名号《》点击搜索，直接看书评，保存分类方便，可以慢慢挑选，比链接分享优点多太多。
书单分享全是简单明文，看的就是明文，没有书评的书单分享起来也没意思吧。 被书源分享带偏了，哈哈。
