### ISSUE TITLE
cloudflare提供了名为Privacy Pass的验证方式，集成到阅读会不会有用？

### ISSUE THREAD

**Issue by daiaji** [gedoor/legado#2953]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

基本上是在浏览器上用于过cloudflare的验证，感觉阅读也能用上。

### 期望实现方式 / How to implement

https://github.com/privacypass/challenge-bypass-extension

### 附加信息 / Additions

印象中如果你触发了一次cloudflare的验证码，Privacy Pass扩展会在你搞对验证码之后收集令牌方便你下次再和验证码对付上时能直接过 。
![图片](https://user-images.githubusercontent.com/25875791/231408492-7e8956f5-bafa-4040-8fe6-27c43b4c3c3c.png)
官方那边也是说默认这个是开启的。

**Comment by Xwite** [comment]
WebView不支持

**Comment by daiaji** [comment]
不知道能不能通过发送HTTP请求的方式用PrivacyPass。
