### ISSUE TITLE
平板双页需要优化

### ISSUE THREAD

**Issue by havoscc** [gedoor/legado#2958]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

第一是对双页模式优化，可以借鉴一下掌阅的横屏双翻页的文字布局之类的
![Screenshot_2023-04-09-10-41-55-389_io legado app release](https://user-images.githubusercontent.com/76244706/230754438-19810ac2-fdfb-4132-ae70-96c15a4090d2.jpg)

第二是双页的仿真翻页动画也需要优化，类似掌阅那种横屏双翻页

### 期望实现方式 / How to implement

参考掌阅的横屏模式

**Comment by 821938089** [comment]
第一个你自己改下边距，你都设置成0了那肯定是这样的啊
