### ISSUE TITLE
能加个订阅源广告屏蔽吗

### ISSUE THREAD

**Issue by javacainiaoa** [gedoor/legado#2959]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

加个订阅源广告屏蔽

### 期望实现方式 / How to implement

/

### 附加信息 / Additions

/

### 效果演示 / Demo

/

**Comment by 821938089** [comment]
已经有了，白名单、黑名单、注入Js都可以
