### ISSUE TITLE
小爱同学朗读功能朗读4个字的段落会跳过

### ISSUE THREAD

**Issue by yhan219** [gedoor/legado#2960]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

小米手机使用系统阅读（小爱），阅读到4个字或者少于4个字的段落，会停顿一下跳过这个段落。

### 复现步骤 / How to reproduce

一个小米手机
随便选一个小说
阅读一个少于4个字的段落

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040420

### Android版本 / Android version

Android 13

### 机型 / Model

小米 Mi10

**Comment by yhan219** [comment]
我卸载后重新装过，依然有这个问题。切换了书源也是同样的。但是没有网络的时候，不使用小爱，阅读就正常了

**Comment by 821938089** [comment]
这是你用的TTS软件有问题，你换个别的就行了

**Comment by yhan219** [comment]
系统默认用的是小爱。抓了下包有加密，也看不出什么问题。重启了手机好了，很奇怪。有时间再研究下

**Comment by hujie233** [comment]
我也遇到这个问题了，不是tts的问题，我换过微软、谷歌和自带的小爱都存在这个问题，我感觉是升级miui14之后出现的。
