### ISSUE TITLE
三星one ui 5.1 rss 看视频画面不动

### ISSUE THREAD

**Issue by woodwen** [gedoor/legado#2964]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

手机：三星23U
系统版本：one ui 5.1
阅读版本：3.23.040420
问题：点击订阅，可以看视频的rss订阅，比如 APP电影，看视频画面不动

### 复现步骤 / How to reproduce

点击订阅，可以看视频的rss订阅，比如 APP电影，看视频画面不动

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040420

### Android版本 / Android version

Android 13

### 机型 / Model

三星S23U

**Comment by woodwen** [comment]
> 三星手机同样问题, 可能和加载的webview没有开启硬件加速有关, 导致无法解析高码率视频流

我这发现了解决方法，降低webview版本到初始化版本，在设置-应用中搜索webview 卸载安装的 webview更新，就可以解决这个问题，目前已正常，你也可以尝试下看看

**Comment by liuchuancong** [comment]
这是看书软件，你看啥视频啊，小伙子节制啊

**Comment by woodwen** [comment]
> > > 三星手机同样问题, 可能和加载的webview没有开启硬件加速有关, 导致无法解析高码率视频流
> > 
> > 
> > 我这发现了解决方法，降低webview版本到初始化版本，在设置-应用中搜索webview 卸载安装的 webview更新，就可以解决这个问题，目前已正常，你也可以尝试下看看
> 
> 实测有效，什么原理呀？ 黑人问号

盲推一波应该是新的webview的属性可能和久的不大一样，所以要在AndroidManifest.xml的标注字段可能要加，具体的需要看安卓 webview 的更新文档

**Comment by helloyan** [comment]
感谢，解决了一个很久的问题
