### ISSUE TITLE
Webdav对于非ssl地址支持

### ISSUE THREAD

**Issue by Easedge** [gedoor/legado#2967]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

本地自建webdav服务端一般没有ssl的证书验证支持，因为目前非ssl会同步出错，所以提出这个请求

### 期望实现方式 / How to implement

希望能够添加一个区别的选项（例如untrust验证选项）来支持自建的webdav的连接

**Comment by 821938089** [comment]
本来就是不验证证书的

**Comment by Easedge** [comment]
> 本来就是不验证证书的

原来是这样子，那您对于这种同步失败的原因有没有什么经验，非常感谢

**Comment by 821938089** [comment]
发下日志

**Comment by Easedge** [comment]
> 发下日志

日志显示错误代码：401 unauthorized

**Comment by Easedge** [comment]
> 用户名或密码错误

我又严谨的尝试了几次，发现还是错误代码401,而我的其他软件在ios上使用webdav服务是可以正常同步的

**Comment by Easedge** [comment]
> > 用户名或密码错误
> 
> 我又严谨的尝试了几次，发现还是错误代码401,而我的其他软件在ios上使用webdav服务是可以正常同步的

排除了网络因素，排除了我部署的服务不能正常使用的因素，排除了中英文输入法的因素排除了是否需要在地址后面加80端口的因素

**Comment by 821938089** [comment]
有没有用nginx之类的软件做反向代理？

**Comment by Easedge** [comment]
> 有没有用nginx之类的软件做反向代理？

无，webdav是直接运行的docker镜像，映射到局域网80端口

**Comment by 821938089** [comment]
你用其他的webdav客户端（不是浏览器）可以使用吗？

**Comment by Easedge** [comment]
> 你用其他的webdav客户端（不是浏览器）可以使用吗？

我在iOS端使用笔记软件通过webdav同步，是可以正常使用的

**Comment by 821938089** [comment]
那这个webdav是用什么搭建的

**Comment by Easedge** [comment]
> 那这个webdav是用什么搭建的

使用docker镜像搭建的局域网端口映射，镜像仓库是dockerhub的bytemark/webdav

🔗https://hub.docker.com/r/bytemark/webdav

**Comment by 821938089** [comment]
阅读只支持Basic Authentication，你的AUTH_TYPE应该是设置了Digest所以导致一直401

**Comment by Easedge** [comment]
> 阅读只支持Basic Authentication，你的AUTH_TYPE应该是设置了Digest所以导致一直401

非常感谢，我需要调整docker镜像里面的哪些参数还是需要换一个webdav镜像

**Comment by Easedge** [comment]
> AUTH_TYPE改成Basic应该就可以了

好的，谢谢，那我close了
