### ISSUE TITLE
[Feature request] 请求开放阅读的 ContentProvider 接口

### ISSUE THREAD

**Issue by w568w** [gedoor/legado#297]
最近希望给[阅读]写个扩展功能的小插件，无奈没有发现[阅读]有任何的暴露接口…  
  
请问可以为[阅读]开放必要的Provider，使外部APP可以读取[阅读]中书架书目、增删书源的内容吗？个人认为，这对于进一步的扩展和应用功能的发展来说非常必要。  
  
PS:如果开发者对此感兴趣而无暇顾及，稍后也可以提出PR…

**Comment by Antecer** [comment]
其实是有接口的,阅读有一个Web管理接口,能够使用你需要的功能.
开 2020/08/07, 星期五 23:53:08, w568w <notifications@github.com> 写到:
最近希望给[阅读]写个扩展功能的小插件，无奈没有发现[阅读]有任何的暴露接口…
请问可以为[阅读]开放必要的Provider，使外部APP可以读取[阅读]中书架书目、增删书源的内容吗？个人认为，这对一个开源的阅读软件来说非常必要。
PS:如果开发者对此感兴趣而无暇顾及，稍后也可以提出PR…

**Comment by gedoor** [comment]
可以的,你可以提交PR

**Comment by w568w** [comment]
> 
> 其实是有接口的,阅读有一个Web管理接口,能够使用你需要的功能

@Antecer 感谢，这个完美解决需求了！

**Comment by w568w** [comment]
> 
> 
> 可以的,你可以提交PR

谢谢，已经提交 #298
