### ISSUE TITLE
能否添加判断章节是否为空的功能

### ISSUE THREAD

**Issue by dxh8286239** [gedoor/legado#2973]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

小说的章节好多都是空章节，换源很难找到有内容的站点，需要一个一个点开尝试，太过浪费时间

### 期望实现方式 / How to implement

能否通过判断网页文本大小的方法，删除空白章节的源

**Comment by h11128** [comment]
我也觉得这功能不错，换源显示响应时间和字数。但是UI不知道应该怎么样

**Comment by zhangweildlh** [comment]
很多时候，伪更新不是内容为空，而是有1.5~2页的内容，然后(正在手打中... ...)

**Comment by h11128** [comment]
<img width = 360 height = 640 src = https://user-images.githubusercontent.com/22561041/233816310-bb8b0d13-2fad-42fe-b11e-8b790243a756.png>
尝试性的做了下， UI是这样的

**Comment by tangshg** [comment]
> <img width = 360 height = 640 src = https://user-images.githubusercontent.com/22561041/233816310-bb8b0d13-2fad-42fe-b11e-8b790243a756.png>
> 尝试性的做了下， UI是这样的

是否可以加个功能，在章节字数少于x字的情况下，不显示这个章节？x是自定义的字数

**Comment by h11128** [comment]
> > <img alt="" width="360" height="640" src="https://user-images.githubusercontent.com/22561041/233816310-bb8b0d13-2fad-42fe-b11e-8b790243a756.png">
> > 尝试性的做了下， UI是这样的
> 
> 是否可以加个功能，在章节字数少于x字的情况下，不显示这个章节？x是自定义的字数。因为在更新的头几天，很多章节都只有前面的几十字。

好主意，但是我不知道UI应该怎么样，不然你给一个示意图

**Comment by zhangweildlh** [comment]
> > > <img alt="" width="360" height="640" src="https://user-images.githubusercontent.com/22561041/233816310-bb8b0d13-2fad-42fe-b11e-8b790243a756.png">
> > > 尝试性的做了下， UI是这样的
> > 
> > 
> > 是否可以加个功能，在章节字数少于x字的情况下，不显示这个章节？x是自定义的字数。因为在更新的头几天，很多章节都只有前面的几十字。
> 
> 好主意，但是我不知道UI应该怎么样，不然你给一个示意图

个人觉得这个UI可以的。简单明了的表示出新章节总字数。很容易就判断是否为“伪更新”。谢谢作者大神了！

**Comment by h11128** [comment]
我先把显示字数的PR https://github.com/gedoor/legado/pull/3063加了，免得拖太久。

后面的按照字数过滤和排序，我添加了[project](https://github.com/h11128/legado/projects/2#card-89118368)，想到什么样的UI合适后就可以做了
