### ISSUE TITLE
滑动翻页朗读时，几个很反人类的体验

### ISSUE THREAD

**Issue by xlggit** [gedoor/legado#2975]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1,朗读本段时，因为本段通常不在屏幕的居中位置，比如在靠近底部的地方，用户此时会向上滑动屏幕，让眼睛不至于俯视那么累。
   但是，当本段朗读完，开始读下一段时，页面居然会返回到滑动屏幕之前的位置，让眼睛继续俯视，主打一个累，惊吓。
    就不能让朗读和翻页两个功能分离吗
2滚动翻页朗读时，不能点击某段落，就朗读某段落吗，看小说软件我老是长按复制文本有什么用，摘抄吗，我知道这个复制功能能关闭。
   我就是想，点哪里，就能听哪里
3滚动翻页时，滑动屏幕的动画太生硬了，像掉帧一样，能不能优化一下，做到像pdf一样丝滑跟手
4能不能添加个功能，读到哪段，就让哪段自动处于屏幕中间，也省的来回滑动屏幕，手动让朗读段居中了
5滑动翻页时，语音朗读明显是按照默认翻页分段的，经常会出现，一段话，前半段是红色表示正在朗读，后半段是黑色，意思是下一段。可这明明就是一段话啊。
切换成默认翻页一看，哦，这前后半段不在一页上。
可是在滑动翻页下，红半段，黑半段，看着就很难受
能否在滑动翻页时，将书文字重排，排成无缝连接的一整页，让一段话别分两段了

### 期望实现方式 / How to implement

滑动翻页时，整本书文字重排，弄成真一页，像一卷卫生纸一样，一个pdf一样。
朗读某段时，某段自动居中，这个功能宜设置成用户可自行关闭
朗读下一段时，不改变已滑动屏幕的位置，即使甚至是，被朗读段已滑出屏幕外了

### 附加信息 / Additions

我是阅读的老用户了，在b站上还打过call，滑动翻页是我最喜欢的翻页方式，这些体验不好的功能，我原本想更新不易，后来作者肯定会逐步优化，但现在感觉作者没有意识到这样体验不好的地方，也没人提。
  还是要感谢作者，这是个好软件，群策群力，吃水不忘挖井人

**Comment by kulkatt** [comment]
进入书籍, 菜单-设置-点击区域设置, 把左右两侧的点击翻页改成无操作
