### ISSUE TITLE
小说源真实更新章节后，APP无法拉取到新章节！！有录屏，请大神下载录屏，观看分析问题。

### ISSUE THREAD

**Issue by zhangweildlh** [gedoor/legado#2976]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

前段时间有反映：小说源更新章节了，但APP拉取不到新的章节。必须更换其他小说源，然后再次更换回此小说源；APP才能够拉取到新的章节。
作者有回应：怀疑小说源为“伪更新”
本次我录制了视频。小说源是真实更新的。不是伪更新！
**************************************************
【例子】背景
小说名：灵境行者
小说源：读书阁网1
最新章节：第三百六十七章 帮派成员团聚 
No 367

### 复现步骤 / How to reproduce

【例子】问题
一、小说源：【读书阁网1】
1、在书架界面，下拉刷新；显示最新章节为第三百六十六 无痕大师的遗产 (No 366)
2、进入阅读界面，点出菜单，选择“更新目录”；依然显示最新章节是No 366
3、阅读界面，进行换源操作；可以看到【读书阁网1】显示最新章节是No 367，此时不换源，直接刷新，依然看不到这个新章节
4、接着第3步的操作，随便换一个其他小说源(哪怕这个小说源的章节只有100章)；退出阅读界面，再次进入阅读界面，再次换源，换回【读书阁网1】；此时，能够看到新章节No 367！！！能够阅读此章节了！！！

录制的视频，下载地址：坚果云  [https://www.jianguoyun.com/p/DU7fM74Q5eC5CxjA3YIFIAA](url)
坚果云 https://www.jianguoyun.com/p/DU7fM74Q5eC5CxjA3YIFIAA

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.032923

### Android版本 / Android version

Android 10

### 机型 / Model

CC9e

**Comment by zhangweildlh** [comment]
此问题不只是这一本小说，也不是只有这一个小说源
是很多本小说，几个小说源都存在问题

**Comment by Xwite** [comment]
重新搜索书籍/重新获取目录url
可以在刷新目录之前使用,有些书源书籍地址和目录url会变
```
java.reGetBook()
java.refreshTocUrl()
```

**Comment by Joackk** [comment]
> 重新搜索书籍/重新获取目录url 可以在刷新目录之前使用,有些书源书籍地址和目录url会变
> 
> ```
> java.reGetBook()
> java.refreshTocUrl()
> ```

请问大佬你发的这个就是重新获取吗？把这俩加到数据目录哪里？

**Comment by Joackk** [comment]
> > 重新搜索书籍/重新获取目录url 可以在刷新目录之前使用,有些书源书籍地址和目录url会变
> > ```
> > java.reGetBook()
> > java.refreshTocUrl()
> > ```
> 
> 我觉得您说得是正解。应该不是书源有问题，因为这些书源是可以搜索到书籍，换源到其他，然后换回来后，就可以看到新章节了。应该就是您说的，目录url变了。 请问能从APP层面解决吗

请问解决了吗？一样的问题
