### ISSUE TITLE
正则替换这个代码是不是有点问题？

### ISSUE THREAD

**Issue by SainoNamkho** [gedoor/legado#2978]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

https://github.com/gedoor/legado/blob/ad43beba347bd481aa8fc09c6f6ef9c5f1609c55/app/src/main/java/io/legado/app/model/analyzeRule/AnalyzeRule.kt#L395-L400

假设用`##a##b###`替换`foobar-foobar`，得到`b`。（应该得到的是`foobbr-foobar`）

而用`##a##b$###`替换，则会得到`foobb$r-foobar`。（不是合法的正则表达式，回退到字符串替换）

如果是出于只替换第一次的目的，第395行似乎应该是`vResult`。

### 复现步骤 / How to reproduce

见上

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040420

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K50 Ultra

**Comment by Xwite** [comment]
https://alanskycn.gitee.io/teachme/Rule/source.html
```
正则之OnlyOne

形式 ##正则表达式##替换内容###
只能在搜索列表、发现列表、详情页预加载、目录列表之外使用
例子见最后的【书源一】的详情页规则
注意点：该规则只能获取第一个匹配到的结果并进行替换

```

**Comment by SainoNamkho** [comment]
> https://alanskycn.gitee.io/teachme/Rule/source.html
> 
> ```
> 正则之OnlyOne
> 
> 形式 ##正则表达式##替换内容###
> 只能在搜索列表、发现列表、详情页预加载、目录列表之外使用
> 例子见最后的【书源一】的详情页规则
> 注意点：该规则只能获取第一个匹配到的结果并进行替换
> ```

但是现在的表现跟描述是不一样的

**Comment by 821938089** [comment]
哪里不一样了？

你找点规则看看实际的用法就知道了

**Comment by SainoNamkho** [comment]
> 哪里不一样了？
> 
> 你找点规则看看实际的用法就知道了

现在的实现里如果出现异常，他就回退到只替换一部分的情况了

> 而用`##a##b$###`替换，则会得到`foobb$r-foobar`。（不是合法的正则表达式，回退到字符串替

如果是按这种理解，`vResult.replaceFirst(rule.replaceRegex, rule.replacement)`也应该写成`rule.replacement`

**Comment by 821938089** [comment]
基本没有书源会用到这个情况的

估计可能是参照下面的随手写上的
