### ISSUE TITLE
有关起点等正版站

### ISSUE THREAD

**Issue by donmor** [gedoor/legado#2984]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

之前查看过起点PC版正版已购页面HTML，发现其结构与免费章节不一样，而目前的书源系统只允许一种正文规则，导致无法使用已有的起点正版书源阅读已购章节，希望能在书源中增加已购章节正文规则字段

### 期望实现方式 / How to implement

目前阅读已能识别付费章节，当加载付费章节时，改用已购章节正文规则解析（若字段为空则使用普通正文规则）

**Comment by 821938089** [comment]
你可以用js写的
