### ISSUE TITLE
校验书源时卡住

### ISSUE THREAD

**Issue by DSLZL** [gedoor/legado#2986]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在校验书源时，每次我都校验到最后一本就会卡住，就算我等了半个小时，还是重试了三次，还是一样

### 复现步骤 / How to reproduce

校验书源功能

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040420

### Android版本 / Android version

Android11

### 机型 / Model

vivo iQOO Pro 5G

**Comment by 821938089** [comment]
不知道是哪里的毛病，卡太久的话你直接点取消就好

**Comment by DSLZL** [comment]
> 不知道是哪里的毛病，卡太久的话你直接点取消就好
主要是我想去除失效书源来提供书籍换源的速度，有失效书源卡着太慢了，建议出多一个校验到一个失效书源就放到失效栏里（虽然我觉得应该在需求那边发）

**Comment by 821938089** [comment]
校验失败的书源会放到失效的分组里

**Comment by DSLZL** [comment]
> 校验失败的书源会放到失效的分组里

但是它好像是要全部校验完才会分类，我想就是校验到一本就放一本，不然我这卡死在最后一本永远无法去除失效书源

**Comment by DSLZL** [comment]
> 校验失败的书源会放到失效的分组里

但是它好像是要全部校验完才会分类，我想就是校验到一本就放一本，不然我这卡死在最后一本永远无法去除失效书源

**Comment by 821938089** [comment]
不是啊，校验完一个如果是失效的就会加失效分组

**Comment by DSLZL** [comment]
淦，我翻了一下，倒是没有找到，我现在还是手动检索删除吧，还有就是希望尽快修复校验卡在最后一本书上面的bug

**Comment by 821938089** [comment]
这个bug比较玄学，校验的书源少不会出现，校验的书源多才有可能会卡最后一本书

你可以分批校验

**Comment by DSLZL** [comment]
> 这个bug比较玄学，校验的书源少不会出现，校验的书源多才有可能会卡最后一个书源
> 
> 你可以分批校验

不过书源多的情况下分批校验有点麻烦，希望下个版本修复
