### ISSUE TITLE
开放/新增一个JS调java方法, 实现繁体和简体的互相转换

### ISSUE THREAD

**Issue by qbeenslee** [gedoor/legado#2988]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

书源中一般实现引入超长的JS代码实现转换, 但每个书源规则都增添这种冗余内容很不优雅

### 期望实现方式 / How to implement

希望新增两个方法:

1. traditionalized(String): String , 将简体转换为繁体
2. simplized(String): String , 将繁体转换为简体

JS端调用:
``` js
java.traditionalized(key)
java.simplized(key)
```

**Comment by javacainiaoa** [comment]
看小说页面的右下角的界面那里有简繁转换的

**Comment by javacainiaoa** [comment]
![Uploading Screenshot_2023-04-16-11-26-50-233_io.legado.app.release.jpg…]()
