### ISSUE TITLE
定时朗读到期停止后, 通过耳机线控启动下一轮朗读, 持续时间只有一分钟

### ISSUE THREAD

**Issue by sishau** [gedoor/legado#2989]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

朗读定时设置为10分钟, 朗读到期停止后, 如果屏幕处于锁屏状态, 通过耳机线控按键再启动一次朗读, 朗读1分钟后就会停止. 而如果线控启动的时候未处于锁屏状态, 则可以正常朗读10分钟

### 复现步骤 / How to reproduce

朗读定时设置为10分钟, 启动朗读. 锁屏. 10分钟到期停止后, 使用耳机线控按键启动下一轮朗读

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040420

### Android版本 / Android version

Android 12

### 机型 / Model

RedMi K30 Ultra

**Comment by 821938089** [comment]
给足后台权限了吗，任务管理卡片加锁，省电策略无限制之类的
