### ISSUE TITLE
主题配色适配遗留

### ISSUE THREAD

**Issue by agutools** [gedoor/legado#299]
![Screenshot_2020-08-09-11-51-31](https://user-images.githubusercontent.com/34952826/89725038-86581080-da3d-11ea-9c4e-c59af0691147.png)
![Screenshot_2020-08-09-11-53-03](https://user-images.githubusercontent.com/34952826/89725040-8b1cc480-da3d-11ea-90c3-63ae6c2de4da.png)

**Comment by gedoor** [comment]
好的

**Comment by gedoor** [comment]
下版本处理
