### ISSUE TITLE
Google Play 上已经无法搜索到 阅读Pro（2023/04/15 22:00）

### ISSUE THREAD

**Issue by flyflas** [gedoor/legado#2990]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

Google Play 上已经无法搜索到 阅读Pro（2023/04/15 22:00）

### 期望实现方式 / How to implement

重新上架阅读pro

### 附加信息 / Additions

无

### 效果演示 / Demo

无

**Comment by gedoor** [comment]
没办法,总是说自带更新,找不到原因

**Comment by yysy** [comment]
难怪今天想上去更新下，发现没了。还会上架吗？要不然只能换回普通版更新了

**Comment by Aetf** [comment]
Google Play 上依然没有上架，这之后还会考虑上架吗？我现在的公司设备只能安装 Google Play 的应用，阅读是我唯一没法在公司设备上用的 app 了。

**Comment by chn-yang** [comment]
想问下现在阅读pro还有在做吗? 怎么获取阅读pro的新版APK

**Comment by gedoor** [comment]
可以自己build一个

**Comment by Aetf** [comment]
如果可能的话依然希望上架。

**Comment by Zxilly** [comment]
去掉 `android.permission.REQUEST_INSTALL_PACKAGES` 就好了

**Comment by easythd** [comment]
> 去掉 `android.permission.REQUEST_INSTALL_PACKAGES` 就好了，或者接入 google play in-app update

要是可以就好了，我也是一直用play版，一直就没有更新了

**Comment by easythd** [comment]
@gedoor  大大是否可以看看是不是上面帖子里 @Zxilly 说的那个问题呢？
真的好希望上google版本

**Comment by lovelilke** [comment]
大大现在这个应用可以上架了吗 同希望下载谷歌google play 版本
