### ISSUE TITLE
支持书源订阅自动更新

### ISSUE THREAD

**Issue by h0cheung** [gedoor/legado#2998]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

把从固定链接下载的书源 json，例如 [XIU2](https://github.com/XIU2/Yuedu)、[aoaostar](https://legado.aoaostar.com)、[windyhusky/PixivSource](https://github.com/windyhusky/PixivSource) 提供的书源等视为订阅，支持方便地更新。

### 期望实现方式 / How to implement

对于远程书源，在本地保存 URL 用于更新，并提供自动、手动的更新功能。

**Comment by 821938089** [comment]
支持订阅，不过需要手动更新

**Comment by h0cheung** [comment]
> 

希望支持自动拉取

**Comment by Crazyokd** [comment]
同，强烈需要这个功能。

**Comment by DowneyRem** [comment]
非常需要这个功能
