### ISSUE TITLE
希望能给书签和阅读时间也加上分组功能

### ISSUE THREAD

**Issue by XTsat** [gedoor/legado#2999]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

书签和阅读时间展示所有的书，无法找到自己想要的，特别是文学类的书籍和网络小说混到一起后不方便回头查阅，希望能支持分组查询这些信息

### 期望实现方式 / How to implement

书签功能加上分组和搜索
阅读时间加上分组

**Comment by XTsat** [comment]
![iEcMxv.jpeg](https://i.328888.xyz/2023/04/16/iEcMxv.jpeg)
![iEcPM3.jpeg](https://i.328888.xyz/2023/04/16/iEcPM3.jpeg)

**Comment by Newdea** [comment]
分组功能确实有必要，书签多了后，希望能按照书本名进行分组及导出，就类似多看阅读中的笔记功能。
![Screenshot_2023-11-10-21-50-09-167_com duokan r](https://github.com/gedoor/legado/assets/9208450/e5d01d66-3eb3-4120-8f06-8062e3741ac2)
