### ISSUE TITLE
Rhino引擎中java.io.File无法使用

### ISSUE THREAD

**Issue by fengyuecanzhu** [gedoor/legado#3005]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

JS引擎中java.io.File无法使用，无法使用new File()，或者是java.getFile()得到的File对象无法调用文件有关函数。测试了下java版的Rhino没有这个问题。

### 复现步骤 / How to reproduce

```javascript
java.log(typeof Packages.java.io.File); //输出的是object，而正常的应该是function
new Packages.java.io.File("myFile"); //报错：com.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: [JavaPackage java.io.File] is not a function, it is object.

let javaImport = new JavaImporter(Packages.java.io);
with(javaImport){
   java.getFile("myFile").exists(); //报错：com.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot find function exists in object /storage/emulated/0/Android/data/io.legado.app.release/cache/myFile.
}
```
同样的代码在java版的Rhino上没问题：
![image](https://user-images.githubusercontent.com/61369261/232479293-c160be37-8704-4fbe-b87b-21ce66e62c47.png)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040420

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K40

**Comment by 821938089** [comment]
就是不能用的，这个被禁止了

**Comment by Xwite** [comment]
文件操作只能操作应用缓存目录下的，放开的话容易出问题
看下这个
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/help/JsExtensions.kt#L459

**Comment by fengyuecanzhu** [comment]
> 你可以试试这些： FileInputStream FileOutputStream FileReader FileWriter RandomAccessFile

其实我是想listFile找文件的![1C`}1MS 5HGBPRVD2)RRQ99](https://user-images.githubusercontent.com/61369261/232490642-d95b5ae5-7aa1-4235-a885-15f1538dc8c3.png)

**Comment by 821938089** [comment]
用新的文件API，这个可以list
java.nio.file

**Comment by fengyuecanzhu** [comment]
> 用新的文件API，这个可以list java.nio.file

ok，谢谢，我试试
