### ISSUE TITLE
app语言没法设置

### ISSUE THREAD

**Issue by h11128** [gedoor/legado#301]
app语言自动跟随系统语言，0710的版本不会自动跟随。

但是更新到0806会自动跟随了，没法设置成中文。

**Comment by gedoor** [comment]
等加设置吧

**Comment by arix00** [comment]
新版本有设置了但是没作用？
7.1.2 lineageos
试了模拟器里面的7.1，也是一样的问题

**Comment by h11128** [comment]
自己修复了这个bug
