### ISSUE TITLE
希望在自动翻页中增加状态栏

### ISSUE THREAD

**Issue by cool-delete** [gedoor/legado#3010]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

自动翻页应该是最常用的功能了。我习惯要么用tts读书了，要么就自动翻页 。设置了隐藏状态栏
但是由于自动翻页通常阅读很长的时间了，我又需要时不时看看状态栏 。目前的话需要暂停滑动之后手指滑动屏幕顶部，手机屏幕的尺寸也不少了吧，经常划不到顶部，反而会把书页往回走了，就很麻烦。而且长时间阅读屏幕，上面显示时间和电量也有可能导致了OLED烧屏

### 期望实现方式 / How to implement

希望能在滑动的过程中，当我点击屏幕让滑动暂停的时候，同时弹出状态栏。

**Comment by 821938089** [comment]
点一下中间弹出菜单时会显示状态栏

**Comment by cool-delete** [comment]
> 点一下中间弹出菜单时会显示状态栏

自动翻页的时候不会弹出状态栏的.
