### ISSUE TITLE
[ API ] 分离 API 以编译至其他平台

### ISSUE THREAD

**Issue by MicroCBer** [gedoor/legado#3012]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

分离 API 和书源解析部分，使得其可以被编译至如 Linux，Windows 等桌面平台并供其他软件使用。

### 期望实现方式 / How to implement

如上

**Comment by 821938089** [comment]
你可以试试这个 https://github.com/hectorqin/reader-legado

**Comment by MicroCBer** [comment]
kk 我过两天有空看看

**Comment by AlongWY** [comment]
这个不能解析 webview

**Comment by 821938089** [comment]
@AlongWY webview 是安卓特有的东西，别的平台肯定是用不了的

**Comment by MicroCBer** [comment]
> @AlongWY webview 是安卓特有的东西，别的平台肯定是用不了的

不可以用其他浏览器实现（如 pptr 或 chromium dev）模拟吗

**Comment by 821938089** [comment]
@MicroCBer 可以啊，但是要自己实现这一部分
