### ISSUE TITLE
不显示epub里的分割线

### ISSUE THREAD

**Issue by Frankienul** [gedoor/legado#3015]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

不管是hr/还是hr    /hr都不显示

### 复现步骤 / How to reproduce

不管是hr/还是hr    /hr都不显示

![Snipaste_2023-04-22_22-04-05](https://user-images.githubusercontent.com/37241509/233789529-c5ee99c8-1639-4d74-91bd-64744dbeb93c.png)

![4c7b5c90a712fe09f67d9f1d7150874](https://user-images.githubusercontent.com/37241509/233789545-fe8532ab-2231-47d5-aee1-5795c9180b46.jpg)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040420

### Android版本 / Android version

8.0.0

### 机型 / Model

Samsung Galaxy A9 Star

**Comment by 821938089** [comment]
阅读的epub是没有样式的，只当纯文字处理排版
