### ISSUE TITLE
漫画类网站图片打乱需要使用convas功能

### ISSUE THREAD

**Issue by klmmlk** [gedoor/legado#3017]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

很多漫画网站都有图片打乱防盗功能，原始图片和浏览器图片分别像下面这样
![原始图片](https://user-images.githubusercontent.com/12571901/233831736-626c89d3-5249-4423-b419-ed825f2363f2.png)
![浏览器显示图片](https://user-images.githubusercontent.com/12571901/233831929-de69c9c9-6620-4f1a-8098-93c92d9ca18a.png)

我看相关的资料，是通过convas实现重绘的。
但是我现在看这个框架好像是不支持dom的操作，convas也无从谈起，不知现在是否有什么解决方案？

### 期望实现方式 / How to implement

能对乱序图片进行重绘。

**Comment by 821938089** [comment]
安卓有canvas
https://developer.android.com/reference/android/graphics/Canvas
