### ISSUE TITLE
发现看有的订阅源的视频会卡顿

### ISSUE THREAD

**Issue by InternetofThingsprogrammer** [gedoor/legado#3019]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

看有的订阅源视频会出现卡顿，要一直点击屏幕，否则音画不同步。

### 复现步骤 / How to reproduce

……

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新版

### Android版本 / Android version

Android12

### 机型 / Model

Redmi k30Pro

**Comment by 821938089** [comment]
系统的webview问题，你可以用外部浏览器打开来看

**Comment by helloyan** [comment]
同问题，有些地址无法直接浏览器观看，是否有其他办法

**Comment by Xwite** [comment]
Duplicate of #2964
