### ISSUE TITLE
鸿蒙3.0无法备份

### ISSUE THREAD

**Issue by cheng9168** [gedoor/legado#3020]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

鸿蒙3.0需要权限，目前最新的版本都无法备份，应用里面只能设置媒体权限，没有储存卡权限选项
![Screenshot_20230423_193401_io legado play releaseA](https://user-images.githubusercontent.com/40489041/233837568-0249dfaa-89e6-4ed0-ac10-878b6ce36730.jpg)

### 复现步骤 / How to reproduce

设置好在线备份路径后点击备份

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.042316

### Android版本 / Android version

鸿蒙3.0

### 机型 / Model

荣耀v30pro

**Comment by 821938089** [comment]
用系统文件夹选择器
