### ISSUE TITLE
本地导入没有自带文件选择器

### ISSUE THREAD

**Issue by superabbite1** [gedoor/legado#3021]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

小米手机安卓10 阅读pro 3.23.012518 本地导入没有自带文件选择器，只有一个系统文件选择器。系统文件选择器里没办法选择文件夹 只有最近的

### 复现步骤 / How to reproduce

小米手机安卓10 阅读pro 3.23.012518 本地导入没有自带文件选择器，只有一个系统文件选择器。系统文件选择器里没办法选择文件夹 只有最近的

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.012518

### Android版本 / Android version

Android 10

### 机型 / Model

Redmi k30s

**Comment by 821938089** [comment]
pro版就是没有的

系统文件选择器左上角三横点一下，选“最近”下面的第一个，应该是手机图标的，然后你就可以选文件夹了
