### ISSUE TITLE
进一步优化epub导出功能

### ISSUE THREAD

**Issue by whx9986** [gedoor/legado#3029]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现在的导出epub功能已经挺不错了，是用txt快速制作一个入门epub版本的不错的选择，不过我观察到大部分人工制作的epub，其使用多看阅读打开后第一页，是一张全屏的封面图片，营造一种实体书从头打开的感觉，然后再是一页作者，一页简介，这样的排版。
而目前阅读这边导出来的epub，是将作者名字和一个缩小版的封面放在第一页，略显拥挤，而后是简介，这种排版方式就感觉差了点意思，观感体验是不如上面那种先来一张全屏的封面来的好的。而且自己做epub时辛苦找了搭配的高分辨率的图片，结果打开之后只能看到一个小小的缩略图，好难受的。

### 期望实现方式 / How to implement

希望开发者能够小小的优化一下这个功能，让生成的epub，第一页是一个全屏的封面，可能目前采用缩略图展示是为了解决封面图片尺寸不合适的问题，但是感觉采用类似播放视频时的智能填充方案会更好一些，如果使用的封面图片不能完美全屏，那就自动裁切一部分，来获得一个全屏的封面。谢谢！

### 附加信息 / Additions

上传了几张图片，萝莉勇者饲养日记，那张截图就是多看阅读里打开epub的效果，是全屏的，而后是简介信息截图，这里因为图片里已经提到了作者，简介里就没有写。
后面那张封面缩略图和作者一起显示的是阅读导出来的epub，希望阅读能够做到前者的效果，封面也能全屏展示，然后作者和简介各占一页或者放在一起都可。

### 效果演示 / Demo

![Screenshot_2023-04-25-04-22-33-436_com duokan reader](https://user-images.githubusercontent.com/58754399/234108381-0b69fe2d-9835-45a3-8ab3-710887402cf0.jpg)
![Screenshot_2023-04-25-04-22-37-392_com duokan reader](https://user-images.githubusercontent.com/58754399/234108396-1c296348-e6d9-4a15-bf5b-64085d56cc39.jpg)
![Screenshot_2023-04-25-04-24-17-038_com duokan reader](https://user-images.githubusercontent.com/58754399/234108401-90e4628e-a9c4-4b57-b6e5-e57fb0dd9e43.jpg)

**Comment by 821938089** [comment]
大多数网站的封面分辨率都很低，尺寸也不合适，强行放大会很糊，也丑。

阅读可以自定义epub模板的，如果你会epub制作的话可以做一个这样的模板来用。

**Comment by Discut** [comment]
阅读能导出书籍吗？请问入口在哪儿呢？

**Comment by whx9986** [comment]
可以让网络封面按照原排版来，然后本地图片封面，使用我描述的那种排版。
阅读epub可以自定义模板吗，我去看看

**Comment by 821938089** [comment]
阅读只有一张封面图，没有本地封面，你导出完了再找别的epub编辑软件再加一个吧

epub自定义模板的方式：
在导出目录下新建一个Asset文件夹，里再新建一个Text文件夹
Text文件夹里面`chapter.html`是正文模板
其他的html格式的是封面、简介模板或其他模板
Asset和Text文件夹下其他地方是资源文件，直接复制进epub里面

默认模板文件，可以参考一下这里的格式：
https://github.com/gedoor/legado/tree/master/app/src/main/assets/epub

模板文件有一些占位符：
1、正文模板：
`{title}` 处理后的章节标题（是一段html）
`{ori_title}` 原始章节标题（纯文本）
`{content}` 章节内容html

2、其他模板：
`{name}` 书名
`{author}` 作者
`{kind}` 分类
`{wordCount}` 字数
`{intro}` 简介

**Comment by whx9986** [comment]
好的好的，谢谢啦，我去研究研究
