### ISSUE TITLE
获取的字数规则是0的时候，详情页显示“0万”

### ISSUE THREAD

**Issue by NONONO1V** [gedoor/legado#3032]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题

### 复现步骤 / How to reproduce

无

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040420

### Android版本 / Android version

Android 11

### 机型 / Model

M6

**Comment by 821938089** [comment]
发一下规则

**Comment by NONONO1V** [comment]
> 发一下规则

http://www.guaner.work/Source/shuyuan.asp?time=2023-4-25231042
关耳的最新jj书源，我的收藏，我收藏了几本作者还没写的预收

**Comment by 821938089** [comment]
我这里不会显示0万字，你可以试试把字数规则删了还有没有问题

**Comment by NONONO1V** [comment]
> 我这里不会显示0万字，你可以试试把字数规则删了看看还有没有问题

……是晋江把0字显示成了0万
