### ISSUE TITLE
导入书源时忽略no-cache

### ISSUE THREAD

**Issue by SainoNamkho** [gedoor/legado#3034]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

[@XIU2](https://github.com/XIU2/yuedu/) 的书源 https://raw.iqiq.io/XIU2/Yuedu/master/shuyuan 无法导入，报错
```
ImportError:java.lang.lllegalStateException: Expected
BEGIN_ARRAY but was STRING at line 1 column 1 path
S
```

### 期望实现方式 / How to implement

这种服务器设置了 no-cache 的书源浏览器下载也并不方便，阅读是不是可以直接忽略它强行导入？

**Comment by 821938089** [comment]
你的网络有问题，这个服务器有waf防火墙，估计你遇到验证了

**Comment by 821938089** [comment]
这和能不能下载没有关系啊

都说了服务器有waf防火墙，你的请求要验证，所以阅读才会打不开啊

![image](https://user-images.githubusercontent.com/8674809/235139459-59fa73d2-8f08-463a-86f4-28138cc90c43.png)

这返回的html阅读怎么解析啊

**Comment by SainoNamkho** [comment]
> 这和能不能下载没有关系啊
> 
> 都说了服务器有waf防火墙，你的请求要验证，所以阅读才会打不开啊
> 
> ![image](https://user-images.githubusercontent.com/8674809/235139459-59fa73d2-8f08-463a-86f4-28138cc90c43.png)
> 
> 这返回的html阅读怎么解析啊

我这里并没有遇到跳转的问题，如果是跳转那确实正常
