### ISSUE TITLE
强制拆分章节关闭以后依然生效

### ISSUE THREAD

**Issue by scybbq** [gedoor/legado#3036]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [ ] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如果长章节是最后一章，已经关闭了的强制拆分章节依然会生效，不过如果把长章节移到末尾之外的地方就能关常关闭

### 复现步骤 / How to reproduce

![`) 5PQ(V_`N2OI ZIUT7)O](https://user-images.githubusercontent.com/80437613/235179378-6c6a6d46-2d55-4629-862a-91b980bbb7cc.jpg)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040420

### Android版本 / Android version

Android 10

### 机型 / Model

Redmi 9A

**Comment by 821938089** [comment]
把有问题的书发一下
还有使用的目录规则

**Comment by scybbq** [comment]
[え〜もん合集 作者：え〜もん.txt](https://github.com/gedoor/legado/files/11355209/default.txt)
[一隅@アンソレール合集 作者：一隅@アンソレール.txt](https://github.com/gedoor/legado/files/11355210/%40.%40.txt)

\[chapter.*

**Comment by scybbq** [comment]
> 把有问题的书发一下 还有使用的目录规则
[え〜もん合集 作者：え〜もん.txt](https://github.com/gedoor/legado/files/11358265/default.txt)
[一隅@アンソレール合集 作者：一隅@アンソレール.txt](https://github.com/gedoor/legado/files/11358266/%40.%40.txt)

\[chapter.*

**Comment by 821938089** [comment]
没测试出问题，我试了第一本，用你给的目录规则只有三章

**Comment by Xwite** [comment]
refs https://github.com/gedoor/legado/commit/069b4dc91f326f3e73966e3a4d8ac3e633fdf10c
