### ISSUE TITLE
替换净化规则的作用范围加一个排除范围

### ISSUE THREAD

**Issue by Chen-Yuanmeng** [gedoor/legado#3038]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

替换规则中加一个排除范围，即某本书或某个源不使用此替换规则。
（如果现在就可以实现的话麻烦指点一下怎么实现）

### 期望实现方式 / How to implement

加一个类似如图的项
![image](https://user-images.githubusercontent.com/118530431/235312661-de7ff4fb-1226-4a0f-941c-83e0622cfe9a.png)

**Comment by gedoor** [comment]
ok

**Comment by Chen-Yuanmeng** [comment]
感谢！！我把issue关了哈
