### ISSUE TITLE
自动换源 功能增强

### ISSUE THREAD

**Issue by QingHui653** [gedoor/legado#3039]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1. 现在看描述 自动换源 功能 只在书源被删除时，会自动切换。
2. 希望加入当获取的章节内容为空 或 字数 少于未订阅时字数时 ，也实现自动换源功能。

### 期望实现方式 / How to implement

1.当获取的章节内容为空 或 字数 少于未订阅时字数时 ，也实现自动换源功能

**Comment by Xwite** [comment]
Duplicate of #2973
