### ISSUE TITLE
行距和段距

### ISSUE THREAD

**Issue by 194802** [gedoor/legado#304]
可以把3.0行距和段距调大一点吗？我觉得距离有点小

**Comment by Antecer** [comment]
你可以自定义设置啊,这个就没必要提交issues了吧.
毕竟各人所好不同.
开 2020/08/14, 星期五 9:28:24, 194802 <notifications@github.com> 写到:
可以把3.0行距和段距调大一点吗？我觉得距离有点小

**Comment by 194802** [comment]
调到最大我还是觉得距离有点小😂

**Comment by Antecer** [comment]
最大2.0段距,每个段落之间直接就空2行了啊,这个还小吗!🤣
如果这个还觉得小,你自己提出需要多高的距离,比如N行.
这样作者就可以修改了,你不提供一个准确的需求,是没法修改参数的.
开 2020/08/14, 星期五 9:54:02, 194802 <notifications@github.com> 写到:
调到最大我还是觉得距离有点小😂

**Comment by 194802** [comment]
其实主要是行距，我经常看小说，觉得行距有点小，时间长了眼睛好难受😖，行距应该是1.5或者2吧
