### ISSUE TITLE
当动画暂停的时候,能弹出显示状态栏

### ISSUE THREAD

**Issue by cool-delete** [gedoor/legado#3045]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

隐藏状态栏设置为true.页眉设置为显示电量和时间的时候或其他信息 页眉的显示选项是状态栏显示时隐藏
当用户暂停动画,即是点击屏幕后,页面不在滚动翻页的时候,能弹出一下状态栏
自动翻页的时候.用户一般都是沉浸阅读的,但是偶尔也想看看有没有新通知的图标 当前信号是多少之类的信息
而且对于oled的烧屏问题也有一点改善
试着pull的.但最后还是无能为力,只能希望开发者实现了

### 期望实现方式 / How to implement

当用户点击屏幕暂停翻页动画的时候,能弹出一下状态栏

### 效果演示 / Demo

手动操作.但是很不方便
![image](https://user-images.githubusercontent.com/13638610/235466507-7002811a-6691-4053-9767-3a4f2bb0bcb6.png)

**Comment by 821938089** [comment]
我的手机（Android 9）是可以弹出来的，但是在Android 12模拟器里它不弹出来，不知道是什么问题，网上找不到解决方案

https://user-images.githubusercontent.com/8674809/235470950-f6a5f157-0d33-4dbf-aa97-5b95248b2a1c.mp4

**Comment by cool-delete** [comment]
> 我的手机（Android 9）是可以弹出来的，但是在Android 12模拟器里它不弹出来，不知道是什么问题，网上找不到解决方案

android9嘛.现在大部分都12 我这个13了...
估计是sdk版本没适配?
我打算想找其他能弹出来的代码
`getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);`
附加到https://github.com/gedoor/legado/blob/100589d215105488f9c2933fc79e91858b80aac7/app/src/main/java/io/legado/app/ui/book/read/ReadBookActivity.kt#L893
这里的 但是我实在搞不懂这里的初始进入动画和后续恢复动画怎么区分两者逻辑.本来也不熟Android开发的 所以pull不了

**Comment by 821938089** [comment]
好了，现在应该可以弹出来了，一会测试版出来了你可以试试

**Comment by cool-delete** [comment]
android13可以了 感谢~ 希望尽快release
