### ISSUE TITLE
希望能支持直接更换书源网站而无需重新搜索加载

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3046]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

每次书源地址改变几乎都要推倒重来，换源需要重新搜索，而如果网站又有搜索间隔限制的话，那么多本书要批量换源也没法操作，希望能增加一个更新书源地址的功能，直接在原来的源上更换新域名，之后只改变书源详情的url，保留正文缓存。

### 期望实现方式 / How to implement

可以与换源功能分开，以免造成书源目录差异混乱

**Comment by zhangzw218** [comment]
同一个网站，换域名的情况其实挺常见的，每次都要重新搜索源，还是希望能有个批量替换域名的，除了域名，后续路径都不需要改变。。
这个问题之前没人响应，是觉得这个功能其实没啥必要么。
。。也可能吧，这么久了，我就没看到第二个提这个需求的。。
