### ISSUE TITLE
希望能单个书源支持多域名

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3048]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

有些网站同时有多个域名，如果都做成书源会造成大量重复源，希望能在一个书源支持多选一域名，共用书源代码，这样也可以减少书源的体积，减少重复书源代码

### 期望实现方式 / How to implement

支持多个域名，每次只使用一个，手动切换或者在书源校验失败后提示更换新域名，

**Comment by 821938089** [comment]
可以多选一啊，我记得有源实现了
你用源变量或者登录UI+js切换就可以了

**Comment by zousizhe** [comment]
> 

这种书源能实现修改书籍详情的url定向吗，如果不能，那还是要重新搜索一次，效果和手动改一样，想要多域名，是希望能直接把书籍详情重新定向到新域名，也方便校验整理，不用写复杂脚本

**Comment by zousizhe** [comment]
> 可以多选一啊，我记得有源实现了 你用源变量或者登录UI+js切换就可以了

这种书源能实现修改书籍详情的url定向吗，如果不能，那还是要重新搜索一次，效果和手动改一样，想要多域名，是希望能直接把书籍详情重新定向到新域名，也方便校验整理，不用写复杂脚本

**Comment by 821938089** [comment]
想要改书籍的地址有两种方案

方案1:
临时用更新之前js规则更新一下地址，不过仍要搜索

方案2:
备份然后修改压缩包里的书籍数据json，替换掉地址，然后再恢复回去

**Comment by zousizhe** [comment]
> 想要改书籍的地址有两种方案
> 
> 方案1: 临时用更新之前js规则更新一下地址，不过仍要搜索
> 
> 方案2: 备份然后修改压缩包里的书籍数据json，替换掉地址，然后再恢复回去

第一个和手动更换源url没区别吧，第二个对老手来说也不太好上手，所以还是希望能支持这个功能，遇到这种场景的时候还是不少的

**Comment by zousizhe** [comment]
> 想要改书籍的地址有两种方案
> 
> 方案1: 临时用更新之前js规则更新一下地址，不过仍要搜索
> 
> 方案2: 备份然后修改压缩包里的书籍数据json，替换掉地址，然后再恢复回去

文案2试了一下，域名改了一个字符的全部替换成功，字数差异大的域名全部替换恢复就报错或者完全没反应，而只修改这个域名的其中一两本却可以成功，书源定向倒是换了，但是刷新却没有启用新源，不会把旧书籍url定向成新书源地址，还是卡在老url上

**Comment by 821938089** [comment]
替换不了可能是转义的问题，还是需要用脚本跑一下替换

改书籍的书源的话需要把书籍里的书源地址替换成新书源的地址，要相同

主要替换这三个 `bookUrl` `tocUrl` `origin` ，`origin` 要和书源的 `bookSourceUrl` 相同

**Comment by zousizhe** [comment]
> 替换不了可能是转义的问题，还是需要用脚本跑一下替换
> 
> 改书籍的书源的话需要把书籍里的书源地址替换成新书源的地址，要相同
> 
> 主要替换这三个 `bookUrl` `tocUrl` `origin` ，`origin` 要和书源的 `bookSourceUrl` 相同

脚本？直接文本编辑模式不行吗，只替换一两个都是有效果的，但是几十本一起替换就完全没有反应，也不报错，在线还原就会报，本地还原什么提示都没有
