### ISSUE TITLE
校验不够实用，一般还是用Debug，可以把校验和debug结合

### ISSUE THREAD

**Issue by h11128** [gedoor/legado#305]
在实际实用中发现校验不够实用：没有过程提示哪些任务正在校验哪些已经完成校验；也不知道校验是怎么进行的；校验失败会在分类后面加“失效”，如果要修复书源还需要进入书源以后，重新debug一遍；不修复书源直接删掉又有些不甘心。所以建议把校验的只校验搜索，改成校验搜索，详情，目录，章节，正文。其实就是debug的内容。

而debug界面的过程提示和结果提示就比较全面，看了代码发现校验和debug是不同的代码，某个app的启发是这两个功能是可以结合起来的，每次选择书源校验就是多线程debug，同时正在进行的书源会在下方给出字符提示当成的过程，结果和校验时间。为了区分校验和debug可以只校验关键项目或者可选项目。

最近看看能不能写代码实现这个想法

某个app的界面
![Screenshot_20200814-092915](https://user-images.githubusercontent.com/22561041/90203500-ebe62d00-ddae-11ea-88c0-ada538cfda67.png)
![Screenshot_20200814-092904](https://user-images.githubusercontent.com/22561041/90203501-ebe62d00-ddae-11ea-85d8-c81430efe820.png)
![Screenshot_20200814-092842](https://user-images.githubusercontent.com/22561041/90203502-ec7ec380-ddae-11ea-8baa-2cdafa0ac628.png)

**Comment by Syt100** [comment]
支持，有检验失败的原因更好，有的源是网站挂了，这种就可以直接删了，有的是网站规则改了，网页模板换了，这种源改改还能用

**Comment by h11128** [comment]
最近有时间，边学kotlin边开始写了一点，现在的进度是：
1. 在书源名字下面增加了一个隐藏的文本，当校验或者debug文本就会显示
2. 数据库增加了一个书源注释的属性，方便读取debug结果，并且可以保存书源作者和其他详细信息
3. 直接在书源管理页增加debug按钮，单个书源可以动态直接在书源管理页显示debug信息

<img src="https://user-images.githubusercontent.com/22561041/92433752-f86e6300-f16b-11ea-9851-af9407d99fc5.png" width="270" height="480"> <img src="https://user-images.githubusercontent.com/22561041/92433753-f906f980-f16b-11ea-8298-e3fa655993b6.png" width="270" height="480">

<img src="https://user-images.githubusercontent.com/22561041/92433754-f906f980-f16b-11ea-8c14-7459220802c2.png" width="270" height="480"> <img src="https://user-images.githubusercontent.com/22561041/92433755-f99f9000-f16b-11ea-96a6-dcf10a90c08b.png" width="270" height="480">


接下来的问题是
1. 怎么多个书源同时debug多线程
2. 多个书源校验时，对应的书源注释改变，如何通知booksourceadapter对应的书源要update

又是个学习的过程

**Comment by h11128** [comment]
当前进度
![Screenshot_20200911-030922](https://user-images.githubusercontent.com/22561041/92788196-bdd91600-f377-11ea-982e-0b89f0e02ada.png)

**Comment by 52fisher** [comment]
期待你的PR

**Comment by h11128** [comment]
> 
> 
> 期待你的PR

因为一直不够完善中间中断了一段时间。。。之前的第一个问题没解决，debug本身就是用CompositeCoroutine来管理task，log又是synchoronize，我再外套一个多线程太复杂不会写，只能在原有校验的基础上写。第二个问题“多个书源校验时，对应的书源注释改变，如何通知booksourceadapter对应的书源要update” 是又增加了响应时间和校验状态到数据库里，校验时postevent通知booksourceactivity校验状态改变，booksourceactivity再通知adapter，adapter再访问数据库查询两个属性的变化。虽然写出来了但是觉得这两个属性不应该存在数据库，postevent也不知道能不能这么频繁的使用，所以一直卡在那里中断了，总感觉有更好的办法

**Comment by h11128** [comment]
https://github.com/gedoor/legado/pull/1251

**Comment by h11128** [comment]
https://github.com/gedoor/legado/pull/1254
