### ISSUE TITLE
右滑返回无效

### ISSUE THREAD

**Issue by olkamz** [gedoor/legado#3053]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [ ] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在非夜间模式的情况下，从屏幕左边缘右滑返回上一级功能失效。
夜间模式可以实现右滑返回

### 复现步骤 / How to reproduce

非夜间模式下，屏幕左边缘右滑

### 确认 / Assignment

- [ ] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22.110823

### Android版本 / Android version

Android8.0

### 机型 / Model

OPPO watch 2

**Comment by 821938089** [comment]
这是手机的全面屏手势功能吧，我两边都可以返回啊

**Comment by olkamz** [comment]
不不不，我可以很确定的说，我没有触发全面屏手势，这功能是app的功能不是系统级的，也就是和iPhone的侧滑返回一个样子

**Comment by 821938089** [comment]
阅读没有侧滑返回功能啊，你说的我试不出来

**Comment by olkamz** [comment]
那就奇怪了，我也用手机试了下好像的确没有侧滑返回的功能，但在手表上就能触发
这是录的视频https://39550.ma3you.cn/articles/b127d60/
