### ISSUE TITLE
请求增加翻页模式

### ISSUE THREAD

**Issue by leeseven-li** [gedoor/legado#3055]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前不支持上下滑动阅读，只能左右阅读翻页，可以支持赏析滑动翻页嘛

### 期望实现方式 / How to implement

在设置里面增加一个翻页模式

**Comment by 821938089** [comment]
那个滚动就是上下滑动
