### ISSUE TITLE
丢失阅读进度

### ISSUE THREAD

**Issue by greenredstone** [gedoor/legado#3057]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

观看漫画、小说时第一次返回必定丢失阅读进度，多次返回后才可正常保存

### 复现步骤 / How to reproduce

随意打开一部漫画，返回，必定丢失进度并回到最开头，第二次之后才能够保存进度

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

关闭webdav的阅读进度同步也会出现此问题

### 阅读版本 / Legado version

3.23.050309

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi k20 Pro

**Comment by 821938089** [comment]
有没有开webdav的同步阅读进度

**Comment by greenredstone** [comment]
> 有没有开webdav的同步阅读进度

开的

**Comment by greenredstone** [comment]
> 有没有开webdav的同步阅读进度

但是关了这个功能也有相同问题

**Comment by 821938089** [comment]
你录个视频看一下

**Comment by greenredstone** [comment]
> 你录个视频看一下

https://1drv.ms/v/s!AmtNOaRmG2-pgTCbYq6biohkm-BS

**Comment by 821938089** [comment]
需要放入书架才能保存阅读进度

**Comment by greenredstone** [comment]
> 需要放入书架才能保存阅读进度

但是书架的书籍也会出现此问题

**Comment by greenredstone** [comment]
> 需要放入书架才能保存阅读进度

https://1drv.ms/v/s!AmtNOaRmG2-pgTHCb26PIyB3hXJ3

**Comment by 821938089** [comment]
我这里复现不了这个问题，你可以试试重装app，重启手机看看能不能好

**Comment by greenredstone** [comment]
> 我这里复现不了这个问题，你可以试试重装app，重启手机看看能不能好

并不能
