### ISSUE TITLE
对中、英文书籍做个别的字形设定

### ISSUE THREAD

**Issue by khlkh** [gedoor/legado#3058]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前的应用程序在中英文电子书之间切换时使用相同的字体设置。由于中文字体不能很好地显示英文内容（特别是看起来很难看），用户必须手动更改字体设置。

因此，如果电子书阅读器能够通过扫描第一段所使用的编码来区分中文电子书/英文电子书，并使用相应的字体设置，那将会是个很有用功能。

### 期望实现方式 / How to implement

Option #1
1. Open the ebook
2. Read the first paragraph and determine the encoding
3. Use the appropriate font setting for the ebook according to the detected encoding

Option #2
1. Use the default epub font settings when first open the ebook
2. If User has set the specific font, remember the setting for this particular ebook
3. Next time, when open a ebook check if a font was previously set for this ebook. If yes, use the user defined font.

### 附加信息 / Additions

**选项 #1**

1. 2. 打开电子书
3. 阅读第一段并确定编码方式
4. 根据检测到的编码方式为电子书使用相应的字体设置

**选项 #2**

1. 当首次打开电子书时，使用默认的epub字体设置
2. 如果用户已经设置了特定的字体，则为该特定电子书记住该设置
3. 下一次打开电子书时，检查此前是否已经为该电子书设置了字体。如果是，则使用用户定义的字体。

### 效果演示 / Demo

 😊

**Comment by realasking** [comment]
也有这个需求，希望能得到满足。
