### ISSUE TITLE
书签同步功能

### ISSUE THREAD

**Issue by wuxian0** [gedoor/legado#3062]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

2.无法跨页选中文字，希望能增加这个功能，选中到当前页右下角时自动翻到下一页继续增加选中内容

**Comment by MrLinyuan** [comment]
这个可以使用滚动阅读来选择文字

**Comment by gedoor** [comment]
菜单里有个编辑,可以选择全文
