### ISSUE TITLE
【问题咨询】oppo r7p安卓5.0 安装提示：安装包有异常，无法安装

### ISSUE THREAD

**Issue by Maple-G** [gedoor/legado#307]
从五月三十一号那个版本开始，后续的每一个版本都是这样不能安装，是那个版本升级到Android studio 4.0开始的。也想问问其他小伙伴们有没有oppo手机遇见相同问题的。代码fork走自己一通乱改，过于菜逼无力修复，求作者或者路过好心人指点。

**Comment by gedoor** [comment]
没人反应过这个问题

**Comment by Maple-G** [comment]
> 没人反应过这个问题

果然我是个特例，那我好好撸撸代码补补课好了......

**Comment by M17764017422** [comment]
可能是签名问题
https://gitee.com/M17764017422/legado/wikis/%E5%AE%89%E8%A3%85%E5%A4%B1%E8%B4%A5%EF%BC%9A%E5%AE%89%E5%8D%936.0%E6%98%BE%E7%A4%BA%E5%BA%94%E7%94%A8%E6%9C%AA%E5%AE%89%E8%A3%85?sort_id=2710166

**Comment by M17764017422** [comment]
最好能有系统安装日志
