### ISSUE TITLE
webdav time out

### ISSUE THREAD

**Issue by ywtz1** [gedoor/legado#3070]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

webdav同步失效，刚刚打开应用的时候可以正常使用，可以备份或恢复，点击获取云端进度后，无法连接，日志提示 webdav time out，回退到0404版本后一切正常。

### 复现步骤 / How to reproduce

刚刚打开应用的时候可以正常使用，可以备份或恢复，点击获取云端进度后，无法同步云端进度，备份恢复功能及云端书籍功能均失效，日志提示 webdav time out

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.050822

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi k60

**Comment by 821938089** [comment]
用的什么webdav

**Comment by ywtz1** [comment]
> 用的什么webdav

Windows server 带的IIS

**Comment by 821938089** [comment]
5月3日的那个版本可以用吗

**Comment by ywtz1** [comment]
> 5月3日的那个版本可以用吗

不能，好像五月3号或者是更早的一个版本更新了就不行了

**Comment by nobk** [comment]
好像是配置被破坏了，重新设置一次webdav的密码可以解决，通过本地备份恢复配置文件则不行。
