### ISSUE TITLE
能否加个标识或者排除

### ISSUE THREAD

**Issue by yehuoshun** [gedoor/legado#3072]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

就加入书架的书搜索的时候不显示或者标识在书架中
一些乱七八糟的书可以添加黑名单

### 期望实现方式 / How to implement

加入书架的书搜索的时候不显示或者标识在书架中
搜索结果页可以添加黑名单，让他以后都不显示

**Comment by gedoor** [comment]
在书架中的书是又标识的,书名前面有个绿点

**Comment by yehuoshun** [comment]
> 在书架中的书是又标识的,书名前面有个绿点

能否可以让让在书架的书不显示，毕竟书源多了搜出来的结果很多
还有“黑名单“功能，有些源搜出来的书是乱码书或不想看的书，能否直接屏蔽，搜索的时候不显示

**Comment by MrLinyuan** [comment]
> > 在书架中的书是又标识的,书名前面有个绿点
> 
> 能否可以让让在书架的书不显示，毕竟书源多了搜出来的结果很多 还有“黑名单“功能，有些源搜出来的书是乱码书或不想看的书，能否直接屏蔽，搜索的时候不显示

可以删除这个乱码源，自己常用源可以单独设立分组，搜索时勾选使用改分组
