### ISSUE TITLE
每次同步的时候总是尝试创建目录

### ISSUE THREAD

**Issue by ForestL18** [gedoor/legado#3082]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

每次用Webdav备份的时候，软件总是会尝试创建备份目录，这是bug还是特意设计成这样的？
个人感觉还是用户主动设置目录比较好，很多时候软件没有权限来创建目录😂

![Screenshot_2023-05-12-08-52-45-124_io legado play release-edit](https://github.com/gedoor/legado/assets/45709305/8033a465-b7b1-421c-8450-b67d3d387c5b)

### 复现步骤 / How to reproduce

同上

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.040516

### Android版本 / Android version

Android13

### 机型 / Model

Redmi K50

**Comment by 821938089** [comment]
就是这样的，每次打开软件都会创建一下目录
