### ISSUE TITLE
希望能在缓存之后的目录列表上显示字数

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3084]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

这样如果有缓存章节字数差异过大就能判断大概未加载完整或者在内容来源上有问题

### 期望实现方式 / How to implement

在缓存的目录列表右边显示字数，现在换源时已经支持查看字数，应该能实现统计字数功能吧

**Comment by h11128** [comment]
还是不太一样，一个是在搜书的时候加载没有缓存的正文。你说的是在已缓存的正文里面查看字数，当然已经缓存的应该更容易
