### ISSUE TITLE
很多人有老泡面盖，我的是KPW2，能不能弄？

### ISSUE THREAD

**Issue by tuhanbing** [gedoor/legado#3085]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

最近发现近视加剧了，想到老泡面盖，翻出来一看，还正常，就想能不能我的KPW2上安装，节省视力？

### 期望实现方式 / How to implement

最好是单独直接刷，不要弄什么安卓，就是看书。

**Comment by daiaji** [comment]
这等同于要求重新适配新平台，怕是不用想。
还不如刷安卓呢。

**Comment by MasterOfStar** [comment]
建议网页版
