### ISSUE TITLE
webdav 不记密码

### ISSUE THREAD

**Issue by holicchan658** [gedoor/legado#3087]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

 当我输入密码后，webdav正常同步，没有问题。
然后关了软件再打开，如果有联网的话就一切正常，webdav 正常同步。如果打开而没有联网的话，webdav密码那一栏会变空，要重新输入密码。5月3号版本就算没有联网，密码也不会没了的。

### 复现步骤 / How to reproduce

视频演示：
https://studenthcmupedu-my.sharepoint.com/:v:/g/personal/4601754065_student_hcmue_edu_vn/EdPqvpVojVtHiAXlW9HU1xIBKmvoIgiMDbRTOy478vPhpw?e=zOBO1q

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.050822

### Android版本 / Android version

Android 12

### 机型 / Model

Realme gt neo 3

**Comment by 821938089** [comment]
更新最新版本
