### ISSUE TITLE
希望新增一个搜索书源中的章节或搜索章节的关键字，通过这种方式找出没错别字的书源

### ISSUE THREAD

**Issue by qizhiquan666** [gedoor/legado#3090]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望新增一个搜索书源中的章节或搜索章节的关键字，通过这种方式找出没错别字的书源

### 期望实现方式 / How to implement

在单章换源下面新增一个通过关键字换源的入口，点进去出现一个弹窗，自动带出当前章节（可修改），然后下面给一个关键字搜索，点击搜索后找所有书源，匹配章节名称和章节内关键字，找到后就显示可换源的书源

**Comment by lograss** [comment]
最好是搜索源的时候，就可以选择先过滤掉章节里面有某些关键字的源，例如带“正在手打中，请稍等片刻”，不然找到一大堆源点进去都是错误章节。

**Comment by qizhiquan666** [comment]
目前太多书源被反爬了，导致错别字或者乱七八糟内容太多了，再次请求这个需求
