### ISSUE TITLE
【订阅】能否增加连续朗读选项？

### ISSUE THREAD

**Issue by myhtcg5** [gedoor/legado#3100]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前的订阅 可以批量获取rss文章，
以列表形式展现，点击单篇文章后→朗读
只能朗读本篇文章，能否本篇文章朗读结束后，自动跳转到本订阅的下一篇文章继续朗读？

### 期望实现方式 / How to implement

朗读订阅文章时，可以自动连续朗读下一篇文章！

**Comment by myhtcg5** [comment]
如果可以订阅和连续朗读，就可以结合miltitts 本地TTS，实现讯飞有声的替代
（本人需求是，出门前翻一遍微信公众号文章，想听的文章，丢到列表，路上可以听）
但是讯飞有声没有正则过滤功能，朗读文章时，大段的URL也会朗读（比如睡前消息文章好多URL）
某些文章文末或者开头的废话 也会朗读（好多公众号文末又往期文章推荐），使用体验不佳。

目前初步设想是这样
1.复制微信公众号连接
2.fooview获取粘贴板地址 发送给自己搭建的web服务器
3.自己的web服务器request获取文章内容，整理成rss格式
4.阅读订阅自己的RSS，然后批量朗读

如果 阅读 也考虑开发这个功能就更好了

**Comment by 821938089** [comment]
你做成书源来用就可以了

**Comment by myhtcg5** [comment]
> 你做成书源来用就可以了

做成书源头 可以自动连续读下一篇吗？
我还没看书源 光看RSS订阅了

**Comment by 821938089** [comment]
可以

**Comment by myhtcg5** [comment]
> 可以

好的 谢谢大佬指导
 我再学习学习 书源！

**Comment by myhtcg5** [comment]
> 你做成书源来用就可以了

添加了几个别人制作好的书源，也没有文章自动阅读下一本啊
你的意思是
我自己制作一个书源
根据日期什么的生成一个书名， 然后每个微信公众号文章作为小说的一章？
这样来实现？

还是没搞懂怎么做成书源就能自动读下一篇文章！
(ノへ￣、)

**Comment by 821938089** [comment]
小说可以自动读下一章的啊，你把每篇文章做成一章不就可以一直读下去了吗

**Comment by logique233** [comment]
`https://www.yckceo.com/yuedu/rss/content/id/13.html`
有办法把这个订阅源做成书源吗,
