### ISSUE TITLE
无法备份到指定文件夹

### ISSUE THREAD

**Issue by zhangweildlh** [gedoor/legado#3115]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

红米Note12Turbo，安卓13，MIUI 14.0.19
面具Magisk v26.1(26100)
阅读 v3.23.051919
今天刚红米Note12Turbo，采用“小米换机”App将数据、程序从CC9e迁移到了新手机。发现问题如下：
1、准备继续将阅读的数据、备份等放到/data/media/0/Books 即/storage/emulated/0/Books 【原CC9e中OK】
2、/data/media/0/Books 即/storage/emulated/0/Books 的权限是777
3、采用 阅读 “自带文件夹选择器”选取该路径；阅读提示备份失败！！！且该文件夹为空！！！云端也没有对应文件上传。
4、采用 阅读“系统文件夹选择器”选取该路径；显示content://con.  ... ...；阅读提示备份成功！！！
发现有一个自动建立的文件夹 /storage/emulated/0/Download/Books ；该文件夹有文件，但没有backup.zip！！！
5、在 /data/media/0/Android/data/io.legado.app.release/files 中找到了backup.zip，以及与 /storage/emulated/0/Download/Books 中同名的诸多文件。

### 复现步骤 / How to reproduce

反复尝试，反复重启，问题一直有。
**3、采用 阅读 “自带文件夹选择器”选取**
![微信图片编辑_20230522160134](https://github.com/gedoor/legado/assets/62597291/976fea48-a3e4-49f2-bfad-197f02443fee)
![微信图片编辑_20230522160304](https://github.com/gedoor/legado/assets/62597291/833b42be-bba0-48e1-98d7-4f8a32e4971e)

**4、采用 阅读“系统文件夹选择器”选取**
![微信图片编辑_20230522160045](https://github.com/gedoor/legado/assets/62597291/4049385f-3f4e-4a3b-826b-3c569dc93642)
![微信图片编辑_20230522160232](https://github.com/gedoor/legado/assets/62597291/90327751-ef43-47b6-b4b5-b35d9151ce61)
![微信图片编辑_20230522160419](https://github.com/gedoor/legado/assets/62597291/894352bc-f477-4dd6-ae5c-0dff2edfa987)

**5、在 /data/media/0/Android/data/io.legado.app.release/files 中**
![微信图片编辑_20230522160450](https://github.com/gedoor/legado/assets/62597291/dae7c379-0913-479e-bab0-7842255b82c5)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.032923

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi Note12Turbo

**Comment by Xwite** [comment]
不要选择根目录，选择`Documents` `Download目录下的子目录，如`/sdcard/Documents/legado/`

**Comment by 821938089** [comment]
`/storage/emulated/0/Download/Books`里面有什么文件？

**Comment by zhangweildlh** [comment]
> `/storage/emulated/0/Download/Books`里面有什么文件？
![微信截图_20230525080420](https://github.com/gedoor/legado/assets/62597291/1fd79b06-a9bc-477b-b3ec-dbcc2a3f0d57)
我把文件上传到坚果云了，还请下载
https://www.jianguoyun.com/p/DXxUt3wQ5eC5Cxiuw4oFIAA
