### ISSUE TITLE
ZIP中文件如果是中文（GBK或GB2312），会识别成????

### ISSUE THREAD

**Issue by simple8848** [gedoor/legado#3119]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

ZIP中文件，如果里面的文件名称是中文（GBK或GB2312编码），会识别成????
测试：如果传入对应的字符集可以正常识别
ZipArchiveInputStream(inputStream, "GBK")
ZipInputStream(inputStream, Charset.forName("GBK"))
val zip = ZipFile(zipFile, Charset.forName("GBK"))

### 复现步骤 / How to reproduce

ZIP中文件，如果里面的文件名称是中文（GBK或GB2312编码），会识别成????

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23

### Android版本 / Android version

所有

### 机型 / Model

所有

**Comment by 7845399855** [comment]
不会新发帖子，借用一哈评论区ʚ♡⃛ɞ(ू•ᴗ•ू❁)rar格式的压缩文件打不开，不管用自带还是系统文件夹选择器都打不开12系统和14系统都不行

**Comment by 821938089** [comment]
@7845399855 不支持RAR5
