### ISSUE TITLE
夜间模式翻页字体亮度会变暗

### ISSUE THREAD

**Issue by Moyivv** [gedoor/legado#3121]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

夜间模式翻页字体亮度会变暗，看起来的效果就是闪屏

### 复现步骤 / How to reproduce

夜间模式下翻页

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.051919

### Android版本 / Android version

Android12/HarmonyOS3.0

### 机型 / Model

荣耀30

**Comment by 821938089** [comment]
你看看你的手机有没有什么显示优化的东西，关掉它看看

**Comment by Moyivv** [comment]
没有显示优化的东西，好像和亮度有关系，调到最暗的时候就很明显

**Comment by 821938089** [comment]
这个估计是华为系统的问题，我看到过的类似问题的手机都是华为手机。

**Comment by Moyivv** [comment]
找到解决方法了，夜间模式背景不要设置纯黑色，调成偏灰色就好了
