### ISSUE TITLE
EPUB 重复显示章节标题

### ISSUE THREAD

**Issue by nukemiko** [gedoor/legado#3122]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

打开 EPUB 电子书时，每个章节都会显示两个标题：一个是章节在目录里的条目，一个是章节 HTML 开头的文本（通常是 h2 或 h3 等区域标题元素，是章节内嵌的标题）。

以下是每个样本文件的章节开头部分：

- 样本 1（导出自阅读应用，源格式为 TXT）
  ![Screenshot_20230526-105649_阅读](https://github.com/gedoor/legado/assets/53572814/3d3058e0-347a-4815-ae62-25a6e22901e7)
- 样本 2
  ![Screenshot_20230526-105703_阅读](https://github.com/gedoor/legado/assets/53572814/2801407f-c309-4070-b94f-bd6168ac4fd8)
- 样本 3（截图所示章节的内嵌标题已被修改为 `<For test purpose>`）
  ![Screenshot_20230526-111148_阅读](https://github.com/gedoor/legado/assets/53572814/2a7b2e3d-44a1-4be6-90a5-3d82bd98fa22)

### 复现步骤 / How to reproduce

使用任何有章节内嵌标题的 EPUB 文件测试即可复现。

附样本文件：
- 样本 1：https://0x0.st/HqwE.epub
- 样本 2：https://0x0.st/HqwI.epub
- 样本 3：https://0x0.st/Hqwl.epub

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

可以增加一个功能：打开 EPUB 时跳过章节开头的多少行，每个 EPUB 单独设置，以便读者跳过章节内嵌标题的部分；在此基础上，还可以添加每个章节的覆盖设置。

### 阅读版本 / Legado version

3.23.05251544（测试版）、3.23.051919（正式版）

### Android版本 / Android version

Android 12

### 机型 / Model

Redmi K30 Pro

**Comment by 821938089** [comment]
你可以把标题关了，这样就不会重复显示标题了

**Comment by nukemiko** [comment]
> 你可以把标题关了，这样就不会重复显示标题了

那样会影响易读性，碰到个不像标题的标题（比如某些短篇小说集），连上一篇看完了都不知道。（而且不好看
不过也算是个临时解决方案。
