### ISSUE TITLE
书源编辑希望能预设两个ua参数插入选项

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3124]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

方便在编辑书源时调用，有时候需要用到的时候都要去其他书源翻找，那一堆字符真不好输入

### 期望实现方式 / How to implement

希望能在插入url参数时调用两个ua，一个手机版一个pc版

**Comment by zmn001125** [comment]
最下边可以自由添加要用的东西![Screenshot_2023-05-27-20-12-31-704-edit_io.legado.app.release.jpg](https://github.com/gedoor/legado/assets/52020688/c6f2aa5c-9b10-4f6f-9bf0-90c49a984acc)

**Comment by zousizhe** [comment]
> 最下边可以自由添加要用的东西![Screenshot_2023-05-27-20-12-31-704-edit_io.legado.app.release.jpg](https://user-images.githubusercontent.com/52020688/241389450-c6f2aa5c-9b10-4f6f-9bf0-90c49a984acc.jpg)

这个功能通常要用在插入url参数，在这个选项里没有办法调用那些参数，而且还要手动输入很多字符与文字，当然你要说先调出来再剪切也行
