### ISSUE TITLE
在搜索小说返回列表之后经常直接回到了搜索框丢失搜索结果

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3126]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在搜索列表进入一个小说之后再返回，有较大机率会回退到输入关键词的阶段，搜索列表没了，又要重新搜索一次

### 复现步骤 / How to reproduce

在搜索结果进入一个小说，返回之后经常跳回搜索输入框了，搜索结果不见了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.051919

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
不能复现

**Comment by zousizhe** [comment]
> 不能复现

有一定机率，反复操作次数多了就会出现
![f45649c069f7465dbefad16701276876](https://github.com/gedoor/legado/assets/37259360/eb2eb215-6669-4f66-a01d-71c93b37c4d3)

**Comment by 821938089** [comment]
我这里怎么试都试不出来

https://github.com/gedoor/legado/assets/8674809/0c7e05e5-67cc-4b54-92da-6ded1552335c
