### ISSUE TITLE
希望在换源的折叠菜单直接显示选中的书源或者分组

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3127]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现在使用二级折叠分组没以前直观了，看不到当前使用的哪个源，希望能在折叠菜单直接显示当前选中的源，

### 期望实现方式 / How to implement

希望这个分组直接改成显示当前选中的分组或者书源
![IMG_20230527_153159](https://github.com/gedoor/legado/assets/37259360/08caeb5b-345a-4159-a277-9520207bad89)

**Comment by Xwite** [comment]
#3089

**Comment by gedoor** [comment]
ok
