### ISSUE TITLE
中文正则表达式困惑

### ISSUE THREAD

**Issue by cool-delete** [gedoor/legado#3129]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

![image](https://github.com/gedoor/legado/assets/13638610/e0b07183-eb50-4c8d-b07d-69dd4a07462c)
对于图片所示的句子
![image](https://github.com/gedoor/legado/assets/13638610/eabb1597-0b12-4a26-b9b3-327826e2a0c3)

### 复现步骤 / How to reproduce

【(叮咚！\w+)】
这种简单的要怎么写正则 我去regtest试过也没问题啊
还有括号也没法识别的
![image](https://github.com/gedoor/legado/assets/13638610/f88a1bcd-17f6-4f98-b732-398744a2aceb)
我试过\(\) 匹配不了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.050210

### Android版本 / Android version

13

### 机型 / Model

oneplus ace2

**Comment by 821938089** [comment]
`\w`不匹配中文
括号是正则的捕获组语法，匹配括号要转义
这里的正则引擎引用捕获组内容使用$1

麻烦学习一下正则表达式。。。

多行匹配的话开头没有空格

**Comment by cool-delete** [comment]
> `\w`不匹配中文 括号是正则的捕获组语法，匹配括号要转义 这里的正则引擎引用捕获组内容使用$1
额 还是一样啊 我用了\W 去测试网址能用W匹配中文
![image](https://github.com/gedoor/legado/assets/13638610/9eefe44f-00e3-4ce7-bf0f-2f360079798f)
在阅读里面怎么匹配中文呢
