### ISSUE TITLE
js使用+连接文本后,使用split出错

### ISSUE THREAD

**Issue by 83d** [gedoor/legado#313]
![image](https://user-images.githubusercontent.com/56167218/90425345-2f63d280-e0f2-11ea-93f5-acabcb724213.png)
![image](https://user-images.githubusercontent.com/56167218/90425463-53bfaf00-e0f2-11ea-8ce3-23b86991c255.png)

@js:
var data="";
data+="a|c";
data.split("|");
"123";

**使用concat连接文本时没有问题**
![image](https://user-images.githubusercontent.com/56167218/90425922-1f002780-e0f3-11ea-8c71-258cb924f7b0.png)
![image](https://user-images.githubusercontent.com/56167218/90425956-29babc80-e0f3-11ea-865b-d5df793014ca.png)
@js:
var data="";
data=data.concat("a|c");
data.split("|");
"123";

**Comment by Antecer** [comment]
可能是引擎不支持  +=
你试试: data = data + "a|c";
开 2020/08/18, 星期二 1:40:19, 83d <notifications@github.com> 写到:
[image] [https://user-images.githubusercontent.com/56167218/90425345-2f63d280-e0f2-11ea-93f5-acabcb724213.png]
[image] [https://user-images.githubusercontent.com/56167218/90425463-53bfaf00-e0f2-11ea-8ce3-23b86991c255.png]
@js [https://github.com/js]:
var data="";
data+="a|c";
data.split("|");
"123";
使用concat连接文本时没有问题
[image] [https://user-images.githubusercontent.com/56167218/90425922-1f002780-e0f3-11ea-8c71-258cb924f7b0.png]
[image] [https://user-images.githubusercontent.com/56167218/90425956-29babc80-e0f3-11ea-865b-d5df793014ca.png]
@js [https://github.com/js]:
var data="";
data=data.concat("a|c");
data.split("|");
"123";
