### ISSUE TITLE
[Feature Request] 关于将下载更新与搜索的线程分开

### ISSUE THREAD

**Issue by pfoysyz752** [gedoor/legado#3131]
# 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

# 功能描述 / Features

我发现有不少网站对请求量做了限制，在我设置了12线程的情况下。

当我搜书的时候大概每个订阅源的网站都只分配了1个线程所以没什么问题。

但当我主动对某本书缓存章节的时候，12个线程直接让网站把我BAN了，除了2章成功，其余章节都被返回了空内容。列如[飞速中文](https://www.feiazw.com)

由此产生了新需求，搜书的时候需要多个线程对多个订阅源搜索，但看书缓存的时候又需要限制线程到1或2。

# 期望实现方式 / How to implement

## 该设置的具体表现可以分为以下两个方面

1. 主要：能在配置项同时提供两项设置(切分自，更新和搜索线程数)
    - 全局更新和搜索线程数
    - 单书更新和缓存线程数

2. 次要：在订阅源创建时就允许作者添加最大线程限制
    - 默认该限制线程，跟随app设置的 [单书更新和缓存线程数]
    - 如果订阅源有该数值，则选app设置与订阅设置中较小的一个

**以上为行外人观点，仅作参考，具体可实现与否，还是要开发者根据实际情况调整与抉择**

# 附加信息 / Additions

_No response_

# 效果演示 / Demo

_No response_

**Comment by 821938089** [comment]
书源可以设置并发率限制请求速度

**Comment by pfoysyz752** [comment]
> 书源可以设置并发率限制请求速度

请问并发率的类型定义是什么？

我并未在书源入门到入土中找到该项的说明。

假设以全局10线程，书源需要限制1线程的需求
- 是表示最大线程数的整数`1`
- 还是表示百分比的小数`0.1`
- 还是直接就是`10%`

**Comment by 821938089** [comment]
阅读内置的书源帮助里有写

* 并发率
> 并发限制，单位ms，可填写两种格式

> `1000` 访问间隔1s  
> `20/60000` 60s内访问次数20
