### ISSUE TITLE
可以调试正则吗

### ISSUE THREAD

**Issue by cool-delete** [gedoor/legado#3139]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

 我实在弄不懂了 用其他python可以使用的正则 在app里面就不行
![image](https://github.com/gedoor/legado/assets/13638610/b3e74f78-95b6-49fd-acae-92b57790cd32)

我的正则这样写的
` [\u4e00-\u9fa5]+\.\.https:\/\/www\.jhssd\.com`
然后改为
`[\u7B2C]\d+[\u7ae0][\uFF1A][^\.]+\.https:\/\/www\.jhssd\.com`
才可以.
而且com后面有个回车和好几个空格的吧,直接给我干没了? 
![image](https://github.com/gedoor/legado/assets/13638610/dd4b8855-b73b-4b90-9f6b-4e469ce0b11f)
那是什么原因呢
感觉超级超浪费时间一步步试验

### 期望实现方式 / How to implement

可以debug文本

**Comment by 821938089** [comment]
不能调试

我说过了，没有空格，这里是格式化出来的，实际处理没有

第一个正则你写多了个点

不太清楚为什么换行没了，你看看是不是有其他规则替换了

**Comment by cool-delete** [comment]
调试的话可以加一个input然后运行一下显示匹配后的结果这样？

**Comment by 761089357** [comment]
> 调试的话可以加一个input然后运行一下显示匹配后的结果这样？

不是的，阅读app里面显示的是优化/处理后的文字，与实际txt里面可能是不一样的，需要用原始txt里面的信息去写正则（推荐在电脑上用notepad++之类的软件看下txt里有没有隐藏的字符），另外有专业的正则表达式测试网站百度下就可以自己写了

**Comment by cool-delete** [comment]
> 是的，因为我是直接下载txt然后导入阅读看书的所以写正则也是这样写的，长按选中的都是处理优化过的，也可能原来就是这样，所以我才说要找到原版txt再写正则不然可能有误。你可以看下本地目录里下载的章节原始文件，也可以尝试不使用净化复制出原始的文字再去网页上尝试自己写的规则


目前是当我长按托选文字的时候，操作栏里面可以直接送入替换功能的名称，，然后在替换界面保存当前的替换搜索规则。

那有没有可能，在送入替换功能的替换规则名称和替换规则的input里面的时候 送入原始文本呢？
