### ISSUE TITLE
app的主题配置希望能记录每个主题的背景图片配置

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3142]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

由于安卓特性，在选择图片时无法完整预览，导致想更换背景图片时非常不好选择，希望主题配置能包含单独的背景图片配置
![Screenshot_2023-05-30-18-53-38-450_com google android documentsui](https://github.com/gedoor/legado/assets/37259360/02b7991d-6273-4f1f-a5a0-8748b368bf53)

### 期望实现方式 / How to implement

记忆每个主题的背景图配置

**Comment by Discut** [comment]
你可以用你手机自带的相册选择看看
