### ISSUE TITLE
希望能在书架管理界面直接进入到小说

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3143]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

书架管理可以搜索到简介的关键词，但是无法进入小说，还要退出来再在书架搜索一次才能定位到那本小说，操作比较麻烦

### 期望实现方式 / How to implement

直接从书架列表进入该小说

![Uploading Screenshot_2023-05-30-19-04-31-455_io.legado.app.release.jpg…]()

**Comment by gedoor** [comment]
ok

**Comment by zousizhe** [comment]
> ok

建议改成进到小说详情而不是正文，毕竟是用来管理书架，仅用来确认搜索管理的小说的信息，并不需要从这里进去看小说
