### ISSUE TITLE
希望不要记录上次使用的换源分组，搜索分组与换源分组保持一致

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3144]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

搜索的小说有10个源，但是换源分组是上次使用的记录，那么换源时就看不到这10个结果，切换到与搜索一致的分组时，就需要重新检索一次，如果分组一致，那么在搜索时得到的可用源数量可以直接在换源列表看到，不用再次检索，换源需要很长的等待时间

### 期望实现方式 / How to implement

希望换源分组选择改为临时选项，只在当前小说换源时生效，重新搜索新小说时换源分组与搜索分组保持一致

**Comment by yafovo** [comment]
的确是个问题，每次换源后，章节进度总是乱的，希望能改善一下这个问题。
