### ISSUE TITLE
更新App的链接是否可以用一些代理站下载

### ISSUE THREAD

**Issue by BennettChina** [gedoor/legado#3146]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

App内置的更新下载链接目前用的应该是 `Github` 原站链接，能否用一些比如 [Ghproxy.com](https://ghproxy.com) 之类的代理网站进行下载的加速。

### 期望实现方式 / How to implement

考虑到代理站可能会宕机，可以搞一个设置选择是否启用该功能，以及让用户自己输入其他的镜像代理站。

**Comment by gedoor** [comment]
我看了下还挺方便的,这个稳定吗

**Comment by BennettChina** [comment]
> 我看了下还挺方便的,这个稳定吗

大部分时间是稳定的，偶尔会域名解析不到，我不确定是运营商的问题还是 DNS 的问题，一般出现这个情况时我用浏览器访问他的网站是可以访问到的。所以我建议的是配置化，只是当作可选项，默认还是用 GitHub 的源站，这样至少代理站有问题，源站还可以慢慢下。

**Comment by BennettChina** [comment]
我用的最多的是在 Linux 用作仓库的加速地址，所以命令行用时有遇到过这个问题。
