### ISSUE TITLE
订阅源之前可以用的更新后报错

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#3147]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

订阅源之前可以用的一键导入(书源/订阅源/替换)现在会报错
![image](https://github.com/gedoor/legado/assets/73186747/25f4f9c6-d15a-4a75-bcfb-61149a9abe90)

### 复现步骤 / How to reproduce

5.18的正式版之后出的问题 试了最新测试版也是这样 重新下了5.16版本点击一键导入可以正常导入，解析直链api是可以正常使用的
订阅源比如这个 
{
  "articleStyle": 0,
  "contentBlacklist": "https://lupic.cdn.bcebos.com/,\nhttps://cpro.baidu.com/,\nhttps://eclick.baidu.com/,\nhttps://sofire.baidu.com/,\nhttps://analytics.woozooo.com/,\nhttps://statics.woozooo.com/",
  "customOrder": 0,
  "enableJs": true,
  "enabled": true,
  "enabledCookieJar": false,
  "header": "{\n  \"User-Agent\": \"Mozilla/5.0Dalvik/2( Linux; U;NEM-AL10Build/HONORNEM-AL10; Youku;7.1.4;)AppleWebKit/537.36( KHTML, like Gecko)Version/4.0Safari/537.36( Baidu;P16.0)iPhone/7.1Android/8.0\"\n}",
  "injectJs": "document.querySelector(\".n_foot\").remove();\nvar importApiList = [\n  {url: \"https://apis.jxcxin.cn/api/lanzou?url=\", params: \"&pwd=&type=down\"},\n  {url: \"https://api.ooomn.com/api/lanzou?url=\", params: \"&type=down\"}\n];\nvar apiListLength = importApiList.length;\nvar lastSelectedIndex = -1;\nvar getRandomApi = () => {\n  var randomIndex;\n  do {\n    randomIndex = Math.floor(Math.random() * apiListLength);\n  } while (randomIndex === lastSelectedIndex);\n  lastSelectedIndex = randomIndex;\n  return importApiList[randomIndex];\n};\naddImportLink = (mbx) => {\n  var labelTitle = \"一键导入\";\n  var link = \"https://www.lanzout.com\";\n  var labelStyle = `\n    position: absolute;\n    right: 70px;\n    padding-top: 7px;\n    color:#87ceeb;\n  `;\n  if (!mbx.querySelector(\".import-link\")) {\n    var newLink = document.createElement(\"a\");\n    var filedown = mbx.querySelector(\".filedown\");\n    var Alink = mbx.querySelector(\".mbx .mlink\").getAttribute(\"href\");\n    //判断书源,订阅源,净化\n    var qz = 'legado://import/bookSource?src=';\n    if (mbx.querySelector('.filename').innerText.indexOf('订阅源') !== -1) {\n        if (mbx.querySelector('.filename').innerText.indexOf('替换净化') !== -1 || mbx.querySelector('.filename').innerText.indexOf('正文净化') !== -1) {\n            qz = 'legado://import/replaceRule?src=';\n        } else {\n            qz = 'legado://import/rssSource?src=';\n        }\n    }\n    var currentArray = getRandomApi();\n    var finalLink = currentArray.url + link + Alink + currentArray.params;\n    newLink.href = qz+finalLink;\n    newLink.innerText = labelTitle;\n    newLink.style.cssText = labelStyle;\n    newLink.classList.add(\"import-link\");\n    newLink.addEventListener(\"click\", (event) => {\n      event.preventDefault();\n      event.target.style.color = \"orange\";\n      var currentArray = getRandomApi();\n      var finalLink = currentArray.url + link + Alink + currentArray.params;\n      window.location.href = qz+finalLink;\n    });\n    filedown.parentNode.insertBefore(newLink, filedown);\n    mbx.style.position = \"relative\";\n  }\n};\naddAllImportLinks = () => {\n  var mbxList = document.querySelectorAll(\".mbx\");\n  mbxList.forEach((mbx) => addImportLink(mbx));\n};\nvar observer = new MutationObserver(function (mutationsList) {\n  for (let mutation of mutationsList) {\n    if (mutation.type === \"childList\" && mutation.addedNodes.length > 0) {\n      mutation.addedNodes.forEach((node) => {\n        if (node.classList && node.classList.contains(\"mbx\")) {\n          addImportLink(node);\n        } else if (node.querySelectorAll) {\n          node.querySelectorAll(\".mbx\").forEach((mbx) => addImportLink(mbx));\n        }\n      });\n    }\n  }\n});\naddAllImportLinks();\nvar moreButton = document.getElementById(\"filemore\");\nmoreButton.addEventListener(\"click\", () => {\n  observer.observe(document.getElementById(\"infos\"), { childList: true, subtree: true });\n});\ndocument.addEventListener('click', (event) => {\n  if (event.target.classList.contains(\"import-link\")) {\n    var currentArray = getRandomApi();\n    var labelTitle = \"一键导入\";\n    var link = \"https://www.lanzout.com\";\n    var Alink = event.target.parentNode.querySelector(\".mbx .mlink\").getAttribute(\"href\");\n    var finalLink = currentArray.url + link + Alink + currentArray.params;\n    event.target.href = 'legado://import/bookSource?src=' + finalLink;\n  }\n});\nvar moreButton = document.getElementById(\"filemore\");\nmoreButton.addEventListener(\"click\", () => {\n  observer.observe(document.getElementById(\"infos\"), { childList: true, subtree: true });\n});\n//为搜索页面添加\nvar sInput = document.getElementById(\"sinput\");\n// 添加“按下回车键”事件监听器\nsInput.addEventListener(\"keydown\", (event) => {\n  if (event.key === \"Enter\") {\n    // 延迟一定时间执行以下函数\n    setTimeout(() => {\n      observer.disconnect();\n      addAllImportLinks();\n      observer.observe(document.getElementById(\"infos\"), { childList: true, subtree: true });\n    }, 2000); // 延迟时间为 2 秒\n  }\n});\n//点击搜索建议时添加\nvar pcSubmitButton = document.querySelector(\"#s_ides\");\npcSubmitButton.addEventListener(\"click\", () => {\n  setTimeout(() => {\n    observer.disconnect();\n    addAllImportLinks(); observer.observe(document.getElementById(\"infos\"), { childList: true, subtree: true });\n  }, 2000); // 延迟时间为 2 秒\n});\n//模仿蓝奏云增强脚本,翻页到底部自动点击更多\nwindow.onscroll = function(ev) {\r\n    if ((window.innerHeight + window.pageYOffset) >= document.body.offsetHeight) {\r\n        let filemore = document.getElementById('filemore');\r\n        if (filemore && filemore.style.display != 'none' && filemore.textContent.indexOf('更多') > -1) {\r\n            filemore.click();\r\n        }\r\n    }\r\n};",
  "lastUpdateTime": 0,
  "loadWithBaseUrl": true,
  "singleUrl": true,
  "sourceComment": "",
  "sourceGroup": "",
  "sourceIcon": "https://assets.woozooo.com/assets/favicon.ico",
  "sourceName": "3.0源",
  "sourceUrl": "https://wwn.lanzout.com/b00r43dzi",
  "style": ""
}
之前书源/订阅/替换点击一键导入都正常跳转加载导入
![2023-06-02-20-34-43_ectype2](https://github.com/gedoor/legado/assets/73186747/017997ec-102a-407d-9320-dead7ae6bfac)
 更新后点击一键导入就都报错
![image](https://github.com/gedoor/legado/assets/73186747/1512a9cf-313d-4f62-9a64-91656c28132e)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.051919

### Android版本 / Android version

android11

### 机型 / Model

z4tablet

**Comment by 821938089** [comment]
现在地址参数需要进行编码，直接拼接是错误的

**Comment by ladia** [comment]
> 现在地址参数需要进行编码，直接拼接是错误的

是最近版本改的吗 因为今年5月中旬还可以这样写。。。我发的图可以那版是3.23.043012再往后的版本3.230514这种也可以

**Comment by 821938089** [comment]
是的

**Comment by ladia** [comment]
试着修改了一下把event.target.href = 'legado://import/bookSource?src=' + finalLink:改成event.target.href = 'legado://import/bookSource?src=' + encodeURIComponent(finalLink);还是报同样的错不是编码的问题

**Comment by ladia** [comment]
> 是的

试着修改了一下把event.target.href = 'legado://import/bookSource?src=' + finalLink:改成event.target.href = 'legado://import/bookSource?src=' + encodeURIComponent(finalLink);还是报同样的错不是编码的问题

**Comment by ladia** [comment]
> 是的

之前更新5.16那版后订阅源里加入书架也挂了 (链接带编码) 后面测试版就修了bug 没注意到书源/订阅/替换导入也挂了

**Comment by 821938089** [comment]
![image](https://github.com/gedoor/legado/assets/8674809/07d2f4d8-fa8a-44c4-86d7-3938c937d984)

这三个地方的都要改

**Comment by ladia** [comment]
> ![image](https://user-images.githubusercontent.com/8674809/243088754-07d2f4d8-fa8a-44c4-86d7-3938c937d984.png)
> 
> 这三个地方的都要改

ok 感谢指教
