### ISSUE TITLE
关于同步问题的几点建议

### ISSUE THREAD

**Issue by swRains** [gedoor/legado#3148]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1、目前的同步功能是同步书架和阅读进度，每次跨设备打开阅读的时候都会提醒webdav不同步，可以给默认设置成取最新的进度，不要提醒了。
2、书源同步，我期望能做个书源同步，并且独立出来，不是和书架同步放一起，因为不同设备有不同设备的网络需求。这样我们分享书源只需要webdav端更新了所有设备都能自动同步。

### 期望实现方式 / How to implement

书源同步为减少流量在上传同时可以做个各个书源的md5表，实现变动部分更新。
默认情况下采用云端的书源，如果云端失联，或者失效则采用本地的书源。
另外在同步时能够同步这本书的书源，当然这得有详细的是否同步的设置列表。

**Comment by 821938089** [comment]
那个webdav同步的提示会同步书源，实际上就是恢复最新的备份
