### ISSUE TITLE
同一本小说的另一个源作者名为空时，详情页补全作者后目录无法加载

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3149]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

搜索结果有书名匹配作者为空，也显示已标记，进入详情页时可以补全作者信息，如果是同一本书，会显示已添加，但是目录会加载失败，与原本冲突，删掉后才正常加载。就算是相同个网站，从这个网站搜索添加的小说，如果在发现页里也有但是没有作者名，那么也会冲突

### 复现步骤 / How to reproduce

搜索同一本小说，另一个源的作者名为空时，也会显示已添加，进入之后合并到一个详情页，但是会显示目录加载失败

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.6222

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
> 搜索结果有书名匹配作者为空，也显示已标记

搜索没有作者名时只判断书架是否有相同的书名 #2655

冲突问题解决不了，只能勉强修复一下目录无法加载的问题
