### ISSUE TITLE
换源时选了校验作者也会切换成不匹配的作者名

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3150]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

作者名一样但是有时候书源获取多了字也会被匹配，比如xxx 分类玄幻  这种作者名规则识别错误的源，校验作者选项只是匹配包含，并没有完整匹配

### 复现步骤 / How to reproduce

换源时有时会换到作者名不匹配的源

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.6222

### Android版本 / Android version

Android

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
校验作者就是匹配包含的，不是相等
