### ISSUE TITLE
漫画滚动异常

### ISSUE THREAD

**Issue by mcmy** [gedoor/legado#3153]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

看漫画时无法滚动，锁定到第一页，向上滚动是上一章，向下滚动是下一章，老版本无此问题

### 复现步骤 / How to reproduce

换了几本漫画和源，都有这个问题，添加漫画在软件里面无法正常阅读，现在只能在web端看漫画
复现视频：https://pan.nfcat.com/123/issue/Screenrecorder-2023-06-05-11-19-02-364.mp4

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

821938089 修复目录无法加载问题 #3149 / 79218ab

### Android版本 / Android version

android 12

### 机型 / Model

redmi K40S

**Comment by 821938089** [comment]
已修复

**Comment by mcmy** [comment]
已解决
