### ISSUE TITLE
希望记住每本小说应用的主题

### ISSUE THREAD

**Issue by mcmy** [gedoor/legado#3155]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1.希望可以根据小说名称记住主题样式，看漫画要设置白色背景，看小说喜欢羊皮纸，每次都要切换很麻烦
2.希望可以自定义夜间模式应用的主题，就是夜间模式的按钮是切换自己指定的自定义主题

### 期望实现方式 / How to implement

1.进入小说自动切换主题，设置可以加一个记住小说主题的按钮
2.界面-文字颜色和背景 的地方加一个主题是设置夜间模式按钮的主题

**Comment by zousizhe** [comment]
我已经建议过三次了，一年一次，还是没实现

**Comment by zousizhe** [comment]
> > 我已经建议过三次了，一年一次，还是没实现
> 
> 那过几天我研究一下，然后写写，这段时间打比赛

那希望能与排版联动，现在主题都是整套生态了
