### ISSUE TITLE
开启web服务时能否指定ip？

### ISSUE THREAD

**Issue by SkyLineCN** [gedoor/legado#3156]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

举例：我打开web服务，默认会生成一个IP地址，例如：http://192.168.0.104:1122/。
这个之前试过好多次，发现会变动，可能上一次是http://192.168.0.111:1122/。

### 期望实现方式 / How to implement

能否在设置里加一个web服务ip锁定的设置，例如，我想固定把ip写死为192.168.1.101:1122。

**Comment by 821938089** [comment]
你去WiFi设置里把IP改成静态就可以了

**Comment by SkyLineCN** [comment]
> 
原来是取得当前设备的ip。明白了。谢谢
