### ISSUE TITLE
希望批量检测更新功能能增加一个详情页的刷新

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3163]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

批量检测更新只能检测已经生成的目录url，但如果修复书源更新了目录url指向，只能手动去到每本小说一个个下拉刷新详情页，才能应用修复过的目录url，只做批量检测更新的话，虽然书源是可用，但是还是会判断成更新失败，因为目录url指向没刷新。虽然可以用批量换源解决，但是如果网站限制频繁操作，就可能需要很长的时间才能解决

### 期望实现方式 / How to implement

在书源管理加一个选项，不用放到主界面

**Comment by 821938089** [comment]
你可以临时用更新之前JS规则更新目录地址，更新完再删掉

**Comment by zousizhe** [comment]
> 你可以临时用更新之前JS规则更新目录地址，更新完再删掉

怎么写呢，我还是个菜鸟，js脚本不太会

**Comment by 821938089** [comment]
在更新之前JS规则填`java.refreshTocUrl()`就可以了

**Comment by zousizhe** [comment]
> 在更新之前JS规则填`java.refreshTocUrl()`就可以了

书源脚本做了二次跳转，在简介获取另一个新地址的简介+目录，需要刷新简介变动指向才行，有没有刷新详情页的规则命令？

**Comment by 821938089** [comment]
你是要刷新简介地址吗，那就只能重新搜索了啊

**Comment by gedoor** [comment]
有个 java.refreshBook() 会重新获取书籍地址

**Comment by 821938089** [comment]
这个实现和`java.refreshTocUrl()`是一样的
