### ISSUE TITLE
增加后台播放功能请求

### ISSUE THREAD

**Issue by Luke666999** [gedoor/legado#3171]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望增加后台播放功能，就是和许多听书软件一样，不需要设置什么权限息屏以后也可以自动播放，而不是听着听着就没声音了。举例软件飞韵听书，免费听书王之类的，qq音乐网易音乐这些都是直接开启然后息屏之后还能播放的。

### 期望实现方式 / How to implement

开启软件听书，息屏后仍然可以播放，可以设置播放时间，不到时间不会停止之类

**Comment by 821938089** [comment]
阅读可以后台播放

这是系统问题，你给够后台运行相关的权限就行

**Comment by Luke666999** [comment]
权限全给，也不行，我确实全部试过了，我尝试了其听书程序不用特别设置权限都可以，主要还是喜欢大佬你这个软件听书，折腾很久了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Horis ***@***.***>
发送时间: Tuesday, June 13, 2023 10:39:15 AM
收件人: gedoor/legado ***@***.***>
抄送: Luke666999 ***@***.***>; Author ***@***.***>
主题: Re: [gedoor/legado] 增加后台播放功能请求 (Issue #3171)


阅读可以后台播放

这是系统问题，你给够后台运行相关的权限就行

―

**Comment by Luke666999** [comment]
更新了新版本，解决问题了，估计是当时下的老版本太老了，当时不支持
