### ISSUE TITLE
希望把字数不足的章节的章节名 变成灰色

### ISSUE THREAD

**Issue by jvbac123** [gedoor/legado#3174]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

我们看书的时候一般 会自动预下载附近10章
当下载过程中 统计字数 如果字数太低 把章节名变成灰色，也就是比正常的黑色更暗，这样就可以区分实际更新位置了。

### 期望实现方式 / How to implement

就是把目录页面的章节名变成灰色，增加用户体验

**Comment by SJJ-dot** [comment]
直接显示章节字数更容易实现
