### ISSUE TITLE
更新最新版本后，点开阅读任意小说会在 "加载数据中..." 时大概率闪退

### ISSUE THREAD

**Issue by XIU2** [gedoor/legado#3175]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

刚才更新 `3.23.061416` 后，准备看看小说，结果在 "加载数据中..." 界面闪退了（有时候是立即闪退，有时候可能会 “卡住” 十秒左右才闪退），测试发现似乎也不是 100% 闪退，有时候连 "加载数据中..." 界面都没出来就闪退了。

安装最新测试版 `legado_app_3.23.06142159_共存.apk` 依然存在该问题，不过在这个测试版上我是用本地小说文件测试的，而原版上在线小说、本地小说我都测试过，都会出现闪退。

我先是来这里看了下发现没人提，又去酷安评论区看了下，发现还是有几个人提到了闪退问题，那看来不是个例。

### 复现步骤 / How to reproduce

以最新测试版为例（所有设置都是默认，安装打开后仅导入本地小说文件，因此干扰因素较少、测试条件/环境变量固定）：
1. 安装最新测试版 [legado_app_3.23.06142159_共存.apk](https://kunfei.lanzoui.com/izfDX0z5quah)
2. 添加本地小说文件（例如我测试时用到的[这个](https://pan.lanzouj.com/ibacM0z63wvi)，我也试过小文件，也是一样，应该和大小关系不大？在线小说也会闪退）
3. 点开小说，开始阅读（此时似乎不会闪退，可能是安装后第一次打开的原因？
4. 退出阅读 APP 后重新打开（要完全退出，比如多任务界面划掉），再点开小说开始阅读（此时闪退几率就很高了
5. 如果还是没有出现闪退，则尝试从 `全部` 分组切换到 `本地` 分组后，再次点开小说开始阅读
`（该步骤只是猜测，因为我遇到一次，在正常点开该小说后，切换分组后再去点就闪退了，不知道是否有关联`
6. 如果还是没有出现闪退，则尝试点开小说开始阅读后，查看目录并切换到间隔较远的章节试试
`（该步骤只是猜测，因为我遇到一次，在正常点开该小说后，切换到一个较远的章节后闪退了。。。`

> 以上步骤我试了 3 遍，安装、导入、点开、退出重进并点开，过程中没有任何多余操作，均在第 4 个步骤闪退。  

> 补充一下，我又测试了第 4 遍，发现这次步骤 4 没有闪退，然后一直重复步骤 4，重复了大概 4、5 次才出现闪退，而自从此次闪退后，再去重复步骤 4 就发现闪退几率明显更高了点？**因此如果步骤 4 没有闪退，可尝试重复步骤 4** 。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

`我的-关于-崩溃日志` 与 `书架-右上角-日志` 都是空的。
如果需要什么必要的日志信息，可以告诉我该如何获取。

### 阅读版本 / Legado version

3.23.061416

### Android版本 / Android version

Android 7.1

### 机型 / Model

魅蓝 Note6

**Comment by 821938089** [comment]
我这测试不出来，一会有个新的测试版你可以试试有没有问题

**Comment by XIU2** [comment]
@821938089 我用另一个 Android 12 手机试了下，发现确实无法复现，难道该问题仅存在老版本的 Android 手机上么。。。

> 我印象中，以前有个版本开始，我的 Android 7 点击朗读按钮就会闪退，但我因为用不上所以就没反馈，后来意外发现某个版本修复了朗读闪退的问题，我记得当时好像也没啥人提这个，可能也是和该问题类似都是只出现在老版本 Android 手机上么

**Comment by XIU2** [comment]
@821938089 试了下最新的 `legado_app_3.23.06151129_共存.apk` 依然存在闪退情况，而且似乎更严重了？
因为我发现添加本地小说后，第一次点开都开始概率闪退了，而上个测试版只在退出重进并再次点开时才会大概率闪退。

另外，多次测试中（清空软件数据后重复 2 3 4 步骤）发现，有次添加本地小说后，首次点开没有闪退，然后翻到下一章，似乎也没啥问题，我正想返回退出 APP 呢，结果在我点击返回键之后，闪退了。。。这个我是第一次遇到。

另外，多次测试中我发现，点开小说后，如果正常情况下处在 "加载数据中..." 界面的时间非常短，也就是几乎是一闪而过就显示小说正文了，而如果处在 "加载数据中..." 界面的时间超过了几秒，那么几乎可以确定接下来会闪退了。
也就是说，在闪退前，处在 "加载数据中..." 界面的时间会明显长很多。
当然，也存在连 "加载数据中..." 界面都还没出现就直接闪退的情况。。。

**Comment by 821938089** [comment]
我这里可以复现了，一会的测试版你再试试，应该修好了

**Comment by XIU2** [comment]
@821938089 应该是修好了，我这边重复了 3 次**步骤 2 3 4**，其中**步骤 4** 加起来重复了最少 20 次，均没有闪退。
感谢~

**Comment by 821938089** [comment]
我又改了下，麻烦你再测试一下最新的测试版会不会闪退

**Comment by XIU2** [comment]
好哒，我试试

**Comment by XIU2** [comment]
我按照上面的测试标准，对最新的 `legado_app_3.23.06151715_共存.apk` 进行了测试：
重复了 3 次**步骤 2 3 4**，其中**步骤 4** 依然是加起来重复了最少 20 次，均没有闪退。

**Comment by 821938089** [comment]
ok 那就是没问题了
