### ISSUE TITLE
加个目录排序功能

### ISSUE THREAD

**Issue by M17764017422** [gedoor/legado#318]
用js写个列表排序也可以但不通用而且自己写比较复杂。不知道有没有相关库能解决
https://www.guishuji.cc/guanchang/4613/
```
<table cellspacing=0 cellpadding=0 border=0><tr><th valign=top colspan=3><strong>正文</strong>
</th></tr><tr><td width="33%" valign=top><ul>
<li><a href="" title="第1章" target="_blank">第1章</a></li>
<li><a href="" title="第4章" target="_blank">第4章</a></li>
<li><a href="" title="第7章" target="_blank">第7章</a></li>
<li><a href="" title="第10章" target="_blank">第10章</a></li>
</ul></td>
<td width="33%" valign=top><ul>
<li><a href="" title="第2章" target="_blank">第2章</a></li>
<li><a href="" title="第5章" target="_blank">第5章</a></li>
<li><a href="" title="第8章" target="_blank">第8章</a></li>
</ul></td>
```

**Comment by AndyBernie** [comment]
> `function getCid(str){

    let URL=String(""+str).match(/href=.([^'"]+)/)[1];
    return (""+URL.split("/").slice(-1)).match(/(^\d+)/)[1]
}
function sortByCid(result){
    return result.toArray().sort((a,b)=>getCid(a)-getCid(b))
}


(function toList(arr){
   return arr.map(a=>{
          let doc=org.jsoup.Jsoup.parse(a);
          //目录列表规则必须获取到<a href="链接">章节名</a>
          //章节名称填text,链接填href
          //或者自行修改
          return { text:doc.select("a").text(),
                   href:doc.select("a").attr("href")
                  }
    });
})(sortByCid(result))
`

**Comment by AndyBernie** [comment]
```
function getCid(str){
    let URL=String(""+str).match(/href=.([^'"]+)/)[1];
    return (""+URL.split("/").slice(-1)).match(/(^\d+)/)[1]
}
function sortByCid(result){
    return result.toArray().sort((a,b)=>getCid(a)-getCid(b))
}


(function toList(arr){
   return arr.map(a=>{
          let doc=org.jsoup.Jsoup.parse(a);
          //目录列表规则必须获取到<a href="链接">章节名</a>
          //章节名称填text,链接填href
          //或者自行修改
          return { text:doc.select("a").text(),
                   href:doc.select("a").attr("href")
                  }
    });
})(sortByCid(result))
```

**Comment by Celeter** [comment]
> 用js写个列表排序也可以但不通用而且自己写比较复杂。不知道有没有相关库能解决
> https://www.guishuji.cc/guanchang/4613/
> 
> ```
> <table cellspacing=0 cellpadding=0 border=0><tr><th valign=top colspan=3><strong>正文</strong>
> </th></tr><tr><td width="33%" valign=top><ul>
> <li><a href="" title="第1章" target="_blank">第1章</a></li>
> <li><a href="" title="第4章" target="_blank">第4章</a></li>
> <li><a href="" title="第7章" target="_blank">第7章</a></li>
> <li><a href="" title="第10章" target="_blank">第10章</a></li>
> </ul></td>
> <td width="33%" valign=top><ul>
> <li><a href="" title="第2章" target="_blank">第2章</a></li>
> <li><a href="" title="第5章" target="_blank">第5章</a></li>
> <li><a href="" title="第8章" target="_blank">第8章</a></li>
> </ul></td>
> ```

这种有规律的可以使用`%%`来排序
