### ISSUE TITLE
书源管理的置顶置底搞反了

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3183]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

书源管理的置顶与置底两个功能对调了

### 复现步骤 / How to reproduce

在书源管理的单个书源菜单中选置顶会变成最底下，选置底反而在最顶上

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23

### Android版本 / Android version

ANDROID 13

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
你是不是打开了反序

**Comment by zousizhe** [comment]
> 你是不是打开了反序

用的是手动排序，不是说我之前置顶的在排序之后在底下，是书源右边菜单的置顶与置底两个是反的，选中哪个置顶就置底了

**Comment by 821938089** [comment]
手动排序上面不是还有个反序的选择吗，那个有没有打开

**Comment by zousizhe** [comment]
> 手动排序上面不是还有个反序的选择吗，那个有没有打开

没有

**Comment by 821938089** [comment]
右下角菜单里面的置顶和置底正常吗

**Comment by zousizhe** [comment]
> 手动排序上面不是还有个反序的选择吗，那个有没有打开

另外开了反序也一样
![Uploading Screenshot_2023-06-21-11-38-03-497_io.legado.play.release.jpg…]()

**Comment by gedoor** [comment]
先用下拖动排序,应该是序号太大或者太小到达int极限了,拖动排序遇到相同序列号会整体重新编号

**Comment by zousizhe** [comment]
> 右下角菜单里面的置顶和置底正常吗

右下角也不正常

**Comment by zousizhe** [comment]
> 先用下拖动排序,应该是序号太大或者太小到达int极限了,拖动排序遇到相同序列号会整体重新编号

但是功能实际却现实了，只是两个菜单功能对调了

**Comment by gedoor** [comment]
你先试试拖动的方法

**Comment by gedoor** [comment]
试试最新版本
