### ISSUE TITLE
（bug）阿里云tts保存密钥弹出错误提示（可正常使用）

### ISSUE THREAD

**Issue by ghost** [gedoor/legado#3184]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

我阿里云填写完密钥后点击右上角对号保存，会弹出错误提示，其实可以正常使用，这是bug吗
版本[legado_app_3.23.061622](https://github.com/gedoor/legado/releases/tag/3.23.061622)
![Screenshot_20230621_095730](https://github.com/gedoor/legado/assets/112467275/746ab71b-160a-4ea1-948f-2ad486489d9c)

**Comment by 821938089** [comment]
编辑源，然后右上角菜单里面点登录

**Comment by 821938089** [comment]
能用就不用管他了，要修复的话得改规则
