### ISSUE TITLE
添加issuse中其他大佬提过的在线tts（百度、azure）

### ISSUE THREAD

**Issue by ghost** [gedoor/legado#3185]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

github搜不到，我去discord才找到的。（百度现在app里接口的应该早就废了吧。）能集成在app中，或者出一个可以维护的列表吗🥰，我希望信息可以透明一点，更加方便。
https://github.com/gedoor/legado/issues/1451
https://github.com/gedoor/legado/issues/1469#issuecomment-1272196339
![image](https://github.com/gedoor/legado/assets/112467275/6819ed9a-ec05-4051-a7d1-8a721dfe149b)
![image](https://github.com/gedoor/legado/assets/112467275/bd743edc-fb70-4ef7-83c5-56d2ef997e86)

### 期望实现方式 / How to implement

github搜不到，我去discord才找到的。（百度现在app里接口的应该早就废了吧。）能集成在app中，或者出一个可以维护的列表吗🥰，我希望信息可以透明一点，更加方便。

### 附加信息 / Additions

感谢您。
祝你生活愉快。

**Comment by 821938089** [comment]
这个去阅读论坛里找，这里不是发源的地方
https://legado.cn/

**Comment by 821938089** [comment]
不能，这个好像不是开放的api
