### ISSUE TITLE
列表加载出现相同的书籍导致直接出现我也是有底线

### ISSUE THREAD

**Issue by 1124839262** [gedoor/legado#3189]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

我有几个书源,网站的原因导致,某些榜单下面的列表会偶尔出现重复的书籍,我看了一下源码,是做了判断查询出来的第一本书和最后一本书如果已经在列表里了就不再加载就会出现我也是有底线的提示,我只能看一下源码,没有修改能力

### 期望实现方式 / How to implement

希望作者能够后续版本中能够增加一个列表书籍重复,直接过滤掉重复书籍
或者做成可以选择是否加载重复书籍的选项

**Comment by 821938089** [comment]
发个书源
