### ISSUE TITLE
正则 平衡组请求支持

### ISSUE THREAD

**Issue by sonyxu** [gedoor/legado#319]
有广告形如`(xxxx(小说更新最快：xxx)xxxx)`现在的方式可以通过
`(\([^\(\)]*)+小说更新(\([^\(\)]*\))+` 屏蔽
形如`(xxxx小说更新最快(：xxx)xxxx)`
则不是很方便 尤其当左右括号不相同时最为麻烦所以请求支持平衡组
如`\[((?<Fopen>\[)|(?<-Fopen>\])|[^[]]*)*(?(Fopen)(?!))\]`得以支持
PS.应该算是个人需求如果麻烦当我没说。

或许是因为使用了多线程所以不能使用平衡组？
如果是这个也当我没说😂

**Comment by 52fisher** [comment]
不是所有语言都支持平衡组，目前来看，也就.NET对这个用法支持比较完善. 当然，平衡组也不是必需的，是可以通过其他方式规避的。
