### ISSUE TITLE
求问禁用跨域js后有没有解决办法

### ISSUE THREAD

**Issue by gzsdbb** [gedoor/legado#3198]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

自从6月14以后就禁用了第三方的js调用 然后有些书源也用不了了，有什么解决办法？ 虽然之前有个混蛋，利用这个漏洞，使用第三方js下载一些垃圾软件，但是这样一刀切的话 ，对其他的不太友好，我现在只能回退到6月6的版本，才能正常使用一些要解密的漫画源

### 期望实现方式 / How to implement

压力留给大佬，坐等解决方案

**Comment by 821938089** [comment]
报错是什么

**Comment by gzsdbb** [comment]
> 

也没报啥错，直接不加载图片了，书源是原仓库里面的漫蛙，https://www.yckceo.com/yuedu/shuyuan/json/id/3297.json
仓库里面源的原地址不对，需要改一下https://mwcomic6.co/，至少我回退到6月6的app能用，但14号后不行

**Comment by 821938089** [comment]
已修复，这个问题与跨域js无关

**Comment by gzsdbb** [comment]
> 已修复，这个问题与跨域js无关

谢谢大佬 就是说下次更新可用了吧？还是说书源里面的问题

**Comment by 821938089** [comment]
下次更新可用，或者你可用先用着测试版

**Comment by gzsdbb** [comment]
> 下次更新可用，或者你可以先用着测试版

测试版的签名不一样，得卸载原版，虽然可以备份，但是下一次更新也比较麻烦，我还是先用着6月6的，等下一版更新再更
