### ISSUE TITLE
导入书源和订阅源建议把新增和更新分类

### ISSUE THREAD

**Issue by BlackRosePetals** [gedoor/legado#3199]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

导入书源一直是新增和更新一起勾选，建议作者把新增单独列为一类，更新单独列为一类。至于导入订阅源我也希望能同步此分类管理。

### 期望实现方式 / How to implement

从分组那里入手是不是要方便一些，或者单独划分为3个功能按钮已有、新增、更新，点选哪个按钮，就直接勾选对应的所有源。

### 附加信息 / Additions

无

### 效果演示 / Demo

![微信图片_20230701174836](https://github.com/gedoor/legado/assets/53809038/4815256c-7b88-46f7-b138-3ad23cb3edfd)

**Comment by BlackRosePetals** [comment]
建议此功能是因为有时候不希望新增源，只是希望能更新现有的源。而单独勾选需要更新的源，就需要手动的一次一项去点击，特别麻烦。希望作者大大看见后，能想想办法针对此功能进行调整修改。

**Comment by zmn001125** [comment]
![Screenshot_2023-07-01-18-31-29-711_io.legado.app.release.jpg](https://github.com/gedoor/legado/assets/52020688/6f88cc47-3bec-4ad7-b6e7-a833a8d6a300)
