### ISSUE TITLE
Web API 更新书籍阅读进度的问题

### ISSUE THREAD

**Issue by fjkdashg** [gedoor/legado#320]
RT
目前通过 Web端阅读，没法在手机上同步进度是不呀
经常性在PC浏览器上看了半天，到下班时一键关了电脑，然后忘记看到哪张了，在手机上要翻好久才能找到进度
我看API的列表里好像没有提供同步阅读进度的接口，看看是不是可以考虑出一个？

**Comment by gedoor** [comment]
应该是同步进度的啊

**Comment by fjkdashg** [comment]
但是我现在使用新版的Web阅读器
 http://192.168.100.80:1122/new/bookshelf.html
在书架界面虽然可以看到手机的阅读进度，但是当我点开书籍的时候，默认打开的是第一章第一页，而不是手机的阅读进度，这个应该是html的参数的问题，
再者，不论Web端阅读到哪一章节，都没有同步更新手机端的进度。而且貌似Web端会单独保存一个自己的阅读进度。
我查看了那个API列表，只有获取书架、获取书籍及章节相关的API，没有看到更新(同步)阅读进度的API呀

**Comment by gedoor** [comment]
获取单独章节时就是保存获取章节的进度
