### ISSUE TITLE
添加当日阅读时长提示

### ISSUE THREAD

**Issue by Chen-Yuanmeng** [gedoor/legado#3200]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

添加一个当日阅读时长提示

### 期望实现方式 / How to implement

可以加到书架或者我的界面

### 效果演示 / Demo

类似起点读书APP的显示
![image](https://github.com/gedoor/legado/assets/118530431/762385dc-67ed-4331-8c61-e97eba9f401d)

**Comment by wuyou1024** [comment]
这个不错
