### ISSUE TITLE
请求接入ChatGPT

### ISSUE THREAD

**Issue by Baphes** [gedoor/legado#3202]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

可用于古文学习，翻译，字典或者是续写润色等。

### 期望实现方式 / How to implement

类似字典，选中文本后弹出菜单。

**Comment by jing332** [comment]
我自己写了个APP来实现此功能： https://github.com/jing332/TextSearcher
主界面配置好OpenAI密钥后，在阅读中选中文本 -> 更多 -> ChatGPT·文本搜索。

## 截图：
<img src="https://github.com/gedoor/legado/assets/42014615/ce059733-7f98-43d7-836e-700555299431" height="150px">

**Comment by jing332** [comment]
目前略麻烦，需要点两次按钮。
静读天下APP则可以修改 "字典"按钮 的行为：其他选项 -> 自定义词典设置 中设置词典1为ChatGPT·文本搜索
