### ISSUE TITLE
通知栏的朗读暂停与播放无反应或延迟严重

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3206]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

通知栏的朗读暂停与继续有严重的延迟或者无响应

### 复现步骤 / How to reproduce

在前台时控制一两次之后就有严重延迟，在后台时使用暂停与播放几乎就是完全失效，选停止朗读则能立刻响应

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K60 Pro

**Comment by lzhiye** [comment]
这个问题我多年前就反馈过，作者也专门解决过，确实起了点作用，把【暂停/播放】的反应延迟从三四秒缩短到了一两秒，但始终没有完全解决，我估计这问题不好解决，不然不会一直遗留好多年
