### ISSUE TITLE
添加新功能

### ISSUE THREAD

**Issue by gjmhmm8** [gedoor/legado#3210]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1 添加小说在线搜索功能，可从书源搜索api直接搜索小说，并自动添加到书源
2 支持markdown功能
3 支持自动更新书源，包括作者名，书名等等

### 期望实现方式 / How to implement

。

**Comment by Discut** [comment]
### 1 添加小说在线搜索功能，可从书源搜索api直接搜索小说，并自动添加到书源

APP中有“添加小说在线搜索功能，可从书源搜索api直接搜索小说”功能吧？只要你导入了书源就能搜索。
什么叫做“自动添加到书源”？如果指的是书籍的话，没有自动添加 的必要吧。

### 2 支持markdown功能

我记得app貌似是有md解析的能力的，但是没有md编辑的功能。

### 3 支持自动更新书源，包括作者名，书名等等

你是说存储网络书源配置地址，然后自动更新吗？
“包括作者名，书名等等”，书籍的这些信息更改的情况很少吧？
