### ISSUE TITLE
通用简介规则

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3213]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1：现在看本地书比较多，总感觉比在线书差点啥，既然封面有通用封面规则，还能手动换源，简介为啥不能呢？
2：还有现在全文搜索，开净化和关净化速度差太多了，搜索基本上要手动关净化再搜，搜完再开净化，有点麻烦，全文搜索能不能加个开关，搜索时默认搜净化前的内容，这样速度快。
3：阅读里的这个破折号——，只要字距不为0，就有个缝，可不可以特别优化一下，把缝去掉

### 期望实现方式 / How to implement

1：加通用简介规则和简介换源，提高一下本地小说的效果
2：全文搜索加个开关，打开后搜索默认是关闭净化的，提供全文搜索速度
3：优化一下破折号——显示效果，把间距去掉

**Comment by gedoor** [comment]
全文搜索加替换开关完成了
