### ISSUE TITLE
[建议]可以单独为某本书设定翻页动画模式（漫画需要 滚动 模式观看）

### ISSUE THREAD

**Issue by FanchangWang** [gedoor/legado#322]
新版本阅读增加图片模式后就可以用来看漫画了，但是漫画很多都是长图或者多张图片的，这时候翻页动画必须使用『滚动』才能完整显示。然而看小说的时候使用『覆盖』『滑动』等分页的效果会更好，这样在切换小说跟漫画的时候，就必须每次都修改翻页动画模式，比较麻烦。

另外，多图的漫画加载时必须等待所有图片都加载完毕才显示，直接打开第一章或跳章的时候要加载很长时间，希望能增加逐张图片加载的模式。

**Comment by 52fisher** [comment]
新版已经支持该功能了，快试用一下吧。感谢你的意见~
