### ISSUE TITLE
epub分割导出

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3220]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] #3221

### 问题描述 / Describe Bugs

![Screenshot_2023-07-12-05-56-48-088_io legado app release](https://github.com/gedoor/legado/assets/106790230/10053abc-d529-4cab-bfd0-9a44e29a9699)
像这么分割导出，1-9,11,13-25每个文件包含章节为10，我以为会是1-9和11一个文件，13-22一个文件，23-25一个文件，结果导出来就只有23-25那个文件，是不是导出文件名一样被覆盖了啊，不应该是这样的吧

### 复现步骤 / How to reproduce

试了三次，都是这样的，而且就这么一共二十多章，导出的巨慢，另外如果把每个文件包含章节数调成25，这个1-9,11,13-25就能完整导出

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.070913

### Android版本 / Android version

Android 13

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
检查导出文件名设置是否正确

**Comment by Discut** [comment]
我下班看看

**Comment by Discut** [comment]
我下班看看😢

**Comment by Discut** [comment]
目前我在更新最新版后并未复现出该bug
这是我按照你的配置导出的文件
![image](https://github.com/gedoor/legado/assets/71692038/7f180e29-506f-4894-9194-3a204d598d91)
文件 1内容
![image](https://github.com/gedoor/legado/assets/71692038/ef3b1823-8bfa-4927-9b85-8c6b4c3994c6)
文件2内容
![image](https://github.com/gedoor/legado/assets/71692038/5cd0c228-bebf-47b5-9f7b-71ae64d32ed6)
文件3内容
![image](https://github.com/gedoor/legado/assets/71692038/7b8af43e-d76c-4a12-b508-750160880a61)


对于文件覆盖的问题：
你是否自定义了导出文件名？

对于导出速度慢的问题：
我一共测试了两次，第一次确实存在该问题，第二次则导出速度正常。
接下来我有时间会尝试修复该问题。

其他

请你提供更多的有关该bug的信息，用于定位问题。
例如：提供出现该问题时，导出文件的本体。

Android 13
Xperia 1 II 日版

**Comment by gyz1023** [comment]
我把导出文件名加了新的变量，倒是能正确导出了，就是这个新变量在导出TXT或者完整epub时会有bug吧，直接显示规则错误用默认规则了，这个epub分割导出的名称规则应该单独出来最好吧
还有就是，为啥我之前导出文件名设错了，导出的只有3章，但大小却基本上是正确导出的3本20多章的和？内容很小，但大小却出奇的大
![Screenshot_2023-07-12-15-36-56-556_com android fileexplorer](https://github.com/gedoor/legado/assets/106790230/172cb822-cf89-4c3d-9dd4-1d7e33223526)

**Comment by 821938089** [comment]
因为目录只有三章
