### ISSUE TITLE
书源发现页新增长按书源显示搜索功能

### ISSUE THREAD

**Issue by Sun-QAQ** [gedoor/legado#3222]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前版本的功能，在发现页长按书源，仅显示编辑、刷新、删除等功能，没有搜索功能。
如果想在单个书源中搜索，要么在书籍搜索中选择单个书源，但此方法比较麻烦，要在自己大量的书源中先找到想要搜索的书源。
另一个方法是在书源管理页面，在相应书源点击后面三个点，弹出菜单里面也有搜索，此方法也要先找到书源，再进行搜索。

### 期望实现方式 / How to implement

在发现页中添加长按搜索，可以提前将想要搜索的书源加入发现页，然后长按搜索只在该书源中搜索，感觉方便了很多。

**Comment by 821938089** [comment]
可以输入书源名字搜索
