### ISSUE TITLE
图片处理规则优化，小图用小图规则，大图用大图规则

### ISSUE THREAD

**Issue by FeiLZX3Km** [gedoor/legado#3225]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

https://zlibrary-jp.se/book/11563739/4b6897?dsource=recommend

如，在Zlibrary上述链接内的图书《山海经》。因为部分古代汉字在当前字库不存在，所以出版者只能将其截图插入文本，但这种汉字截图往往分辨率很低；而其他部分的正文内容，却都是大图，都是高分辨率。在当前的阅读APP版本中，图片处理的default、full、text三种规则均不能将文章内存在的不同分辨率的图片处理好，故会而导致文章排版混乱，图片无法正常显示。

### 期望实现方式 / How to implement

增加相关规则，若书内图片分辨率相差过大，则智能地分别适用大小图规则，以尽量保持书内文章排版正常有序。

### 附加信息 / Additions

无

### 效果演示 / Demo

无

**Comment by Discut** [comment]
emm，这是你lib的个人域名？

**Comment by FeiLZX3Km** [comment]
> emm，这是你lib的个人域名？
应该不是，我记得之前的政策是只有捐款过的人才有，我就没捐过。^_^ 
不过我找到了专门的分享链接。如下：
https://zlibrary-jp.se/book/11563739/4b6897?dsource=recommend

**Comment by Baphes** [comment]
这个用微信读书体验更好。大部分都转换成文字了。

**Comment by FeiLZX3Km** [comment]
> 这个用微信读书体验更好。大部分都转换成文字了。

谢谢你的提醒。是我妄图在阅读里面all in one了。没想到微信读书效果竟然那么好！
