### ISSUE TITLE
希望增加翻页动画速度调整功能

### ISSUE THREAD

**Issue by hidohuang** [gedoor/legado#3226]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望能对翻页动画的速度进行自定义调整

### 期望实现方式 / How to implement

像阅读界面底部的文字颜色和背景一样，长按动画选项弹出对话框设置动画速度，给几个速度可选项即可

### 附加信息 / Additions

新转到大佬的app，按以前熟悉的阅读页面定制自己的阅读页面，基于强大的定制功能完全复现了页面效果，就是动画速度无法设置，用的仿真翻页尤其显得慢（非连点的情况），希望能有这个功能，万分感谢

**Comment by StoveOnBox** [comment]
确实有一样的需求，希望可以进行该功能的更新，祝软件越来越好~

**Comment by Discut** [comment]
在使用音量键翻页时想使用自定义的动画速度嘛？

**Comment by hidohuang** [comment]
> 

无此需求，个人基本不用音量键翻页，甚至大佬说了之后我去试了下才发现这两者动画速度原来还真是不一样的。。😂

**Comment by StoveOnBox** [comment]
怎么说呢，个人认为现有的动画速度看起来有点不是很舒服，希望加上这个功能，感谢提出这个问题的大佬和开发大佬
________________________________

**Comment by Discut** [comment]
> > 
> 
> 无此需求，个人基本不用音量键翻页，甚至大佬说了之后我去试了下才发现这两者动画速度原来还真是不一样的。。😂

自定义的动画速度你想应用在哪个地方？目前我知道使用默认动画速度的地方只有屏幕点击翻页和音量键翻页。

**Comment by StoveOnBox** [comment]
针对个人的需求来说，我可能使用屏幕点击更多，对于屏幕点击的动画速度调整需求应该大于使用音量键的动画速度调整，感谢回复🙏，注意休息。
________________________________

**Comment by hidohuang** [comment]
> > > 
> > 
> > 
> > 无此需求，个人基本不用音量键翻页，甚至大佬说了之后我去试了下才发现这两者动画速度原来还真是不一样的。。😂
> 
> 自定义的动画速度你想应用在哪个地方？目前我知道使用默认动画速度的地方只有屏幕点击翻页和音量键翻页。

和楼上一样，就个人而言我也只需求点击屏幕动画速度的调整，感谢大大
