### ISSUE TITLE
[技术功能需求] 阅读器UI组件化

### ISSUE THREAD

**Issue by stars-one** [gedoor/legado#3230]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

因为想要整个本地的阅读器,这几天也是看了其他几个不同的阅读器开源库,还是觉得阅读这边支持的功能强大

然后我想要尝试移植阅读器ui那部分的代码,移植了一天还是报错,代码有点耦合过头了....

> 那个PageView的绘制流程,还有关于小说的目录数据处理的逻辑,看得我很懵,一时半会估计是没法完成移植工作

不知道有没有大佬有意向出手

### 期望实现方式 / How to implement

小说阅读器部分,可以整成一个module形式，对外提供一个ReadActivity,外层其他页面调用只需要给ReadActivity负责传入简单的Book对象即可完成阅读书籍功能

**Comment by gedoor** [comment]
没这个打算,本来就是一个软件,没必要那样
