### ISSUE TITLE
查看当前页面生效净化

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3232]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

净化这功能还是大众一点好，不会写净化，起码让他们能放心用净化，不需要让他们会，让他们知道哪个净化有问题不难做到吧，不然他们得到的答案往往就是一句简单的关净化，从此远离这个明明特别好用的功能

### 期望实现方式 / How to implement

阅读界面右上角菜单，能不能加个扫描净化的功能，可以把当前页面生效的净化显示出来，帮助排除误杀的净化

**Comment by gedoor** [comment]
ok
