### ISSUE TITLE
针对不同的文件类型下载到不同的文件夹内

### ISSUE THREAD

**Issue by caijimoyu** [gedoor/legado#3236]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

订阅内所有的下载都只能下载缓存到Android/data/软件文件夹内。
希望可以设置针对不同的文件类型下载到不同的文件夹内。

### 期望实现方式 / How to implement

**例：**
识别到我下载`ttf`，将`ttf`下载到`sd/fonts`
识别到我下载的`epub,txt` 下载到书籍文件夹
识别到我下载的`apk`或者其他格式，下载到`download`

**Comment by 2642141265** [comment]
阅读只是一个阅读软件啊
