### ISSUE TITLE
最新版本在朗读到一章结束自动翻页时会直接翻过两页

### ISSUE THREAD

**Issue by lzhiye** [gedoor/legado#3238]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

版本是3.23.070913，朗读用的是百度tts，朗读到本章结束自动翻到下一章时会翻到下一章的第二页，但朗读的是第一页内容，且朗读正常，不看界面只听朗读的话完全不影响使用，更新版本前没这个问题，新版本我目前用了两天时间，也不是每次翻章都出现，出现几率大概一半的样子，这个翻页错误会持续到本章结束，到翻下一章时会恢复正常，但再到下下章时又大概率直接翻到第二页，如此循环。。。

### 复现步骤 / How to reproduce

用百度tts朗读，朗读到一章结束自动翻到下一章时，会翻页到下一章的第二页，该情况不是每次复现，但复现概率大于50%的样子

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.070913

### Android版本 / Android version

安卓13

### 机型 / Model

小米MIX4

**Comment by 821938089** [comment]
试试最新测试版

**Comment by lzhiye** [comment]
> 试试最新测试版

测试版在哪下载啊？

**Comment by 821938089** [comment]
https://kunfei.lanzoui.com/b0f810h4b

**Comment by lzhiye** [comment]
> https://kunfei.lanzoui.com/b0f810h4b

测试版安装时提示签名不一致，需要卸载旧版再安装，卸载后很多设置需要重新搞，不折腾了，反正这bug也影响不大

顺便吐槽一下备份功能，不能备份界面的设置，字体、颜色、主题这些从备份恢复不了。

**Comment by 821938089** [comment]
你先装共存版试一下

可以备份的，不过如果是要依赖一些文件的设置就不行了

**Comment by lzhiye** [comment]
> 你先装共存版试一下
> 
> 可以备份的，不过如果是要依赖一些文件的设置就不行了

legado_app_3.23.07180910_共存.apk
用了一个来小时，确定没有多翻页的问题，很棒！
