### ISSUE TITLE
读书项目与进度管理

### ISSUE THREAD

**Issue by FeiLZX3Km** [gedoor/legado#3239]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

一、希望能够爬取豆瓣书评与评分。其目的在于可以根据出版书籍评论预判相关书目是否有必要阅读；
二、希望增加读书项目与读书进度管理功能。小说类书籍动不动几千章，而非小说类书籍，又容易因为其他工作难以分配精力。希望能够在阅读APP内设置读书简单的读书计划功能，即根据已经爬取到的书籍章节数量，简单加减乘除算出每天分配只阅读的章节数量+阅读APP每天通知提醒。

### 期望实现方式 / How to implement

一、爬取豆瓣书评与评分；
二、希望增加读书项目与读书进度管理功能。

### 附加信息 / Additions

无。

### 效果演示 / Demo

无。

**Comment by MrLinyuan** [comment]
**纸间书摘** 或许可以试试。阅读也不是搞计划这些的软件

**Comment by FeiLZX3Km** [comment]
> **纸间书摘** 或许可以试试。阅读也不是搞计划这些的软件

谢谢，你给我推荐了一个宝贝。
