### ISSUE TITLE
朗读失败：TTS初始化失败！

### ISSUE THREAD

**Issue by srdgame** [gedoor/legado#3240]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

已安装TTS Server和讯飞语记，朗读设置成为TTS Server或者讯飞都回有TTS 初始化失败的提示。
开启了记录调试日志后，日志没有任何提示。
朗读引擎设定为“1.百度”（未设定任何信息，如登录URL等等），会提示五次调用失败（日志也会有调用失败记录）

### 复现步骤 / How to reproduce

1. 安装阅读
2. 安装TTS Server和讯飞
3. 在安卓系统里设定朗读引擎，并测试成功，点击能听到：这是中文合成效果。（首选引擎无论是TTS Server还是讯飞都能正常听到合成效果）
4. 打开阅读，随意添加书籍
5. 点击“朗读”，点击“设置”->朗读引擎
6. 设定引擎为:TTS Server (或者讯飞语记)
7. 点击停止朗读，再次点击朗读
8. 提示“TTS 初始化失败”

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.070913

### Android版本 / Android version

Android 9

### 机型 / Model

Meizu 16XS

**Comment by gedoor** [comment]
tts是否允许后台运行,自启动等

**Comment by srdgame** [comment]
> tts是否允许后台运行,自启动等

缺失是因为没有开启自启动的原因：

开启方式：
https://zhidao.baidu.com/question/655188387182598525.html
