### ISSUE TITLE
web服务网址出问题了

### ISSUE THREAD

**Issue by 416130325** [gedoor/legado#3244]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

不管是手机移动网络还是连了wifi，web服务网址都不变了，都一直是http://192.0.0.2:1122/
请问下这是什么问题

### 复现步骤 / How to reproduce

重新安装了也没用

### 确认 / Assignment

- [x] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.072018

### Android版本 / Android version

Android 13

### 机型 / Model

三星S23 ULTRA

**Comment by 821938089** [comment]
你去WiFi设置那里找一下WiFi的IP就可以连了

**Comment by 416130325** [comment]
好的谢谢

Horis ***@***.***> 于 2023年7月22日周六 上午3:27写道：
