### ISSUE TITLE
希望字典规则里增加一条旧版本直接打开浏览器搜索相关结果

### ISSUE THREAD

**Issue by Fuck0o0baidu** [gedoor/legado#3245]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

旧版本阅读，选中词句点击字典后，如果搜索不到相关信息会有一个直接跳转浏览器百度搜索的按钮，对于比较冷门的词句或者想要搜索相关网页时可以快速打开浏览器展示搜索结果。
虽然点击三个点再选择浏览器也能做到，不过步骤比较多，希望能告知一下这种字典规则该如何编写

### 期望实现方式 / How to implement

希望能告知“跳转到浏览器打开百度搜索相关词句做成单独的按钮”这个字典规则，可以自行添加进字典内，或者做成默认关闭的规则，有需者自行开启此功能

### 效果演示 / Demo

![QQ图片20230722000111](https://github.com/gedoor/legado/assets/140235459/730ed704-f63e-48bc-984a-cc670f065a48)

**Comment by 821938089** [comment]
这是原网站的东西，你可以找找旧版的字典规则弄到新版里用

**Comment by Fuck0o0baidu** [comment]
或者说如何添加一个字典规则，选中词句点击字典后有个按钮能直接打开浏览器搜索相关网页

**Comment by 821938089** [comment]
那个文本选择菜单是可以默认展开的，这样就不需要点那三个点了

**Comment by Fuck0o0baidu** [comment]
> 那个文本选择菜单是可以默认展开的，这样就不需要点那三个点了

好吧，这也是一种解决办法
