### ISSUE TITLE
问一下在编写书源规则时正文页下的替换规则能不能写一种以上的规则

### ISSUE THREAD

**Issue by blackcd318** [gedoor/legado#3246]
### 确认 / Assignments

- [x] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

如题,我遇到的情况是这样的,网页上的正文最后总是会加上一些网站的信息,这部分我希望能完全替换掉
##.+webinfo.+
然后有些页面可能他们人手不足,就会先上最前面一部分,然后来一句正在手打中然后巴拉巴拉,这样我就希望把全部正文替换掉,但是如果像前面一样替换为空,在开源阅读正文就会显示正文获取失败,这在网络连接失败时也会出现,我就想把他替换成别的字符,例如
##[\s\S]+正在手打中[\s\S]+##正在手打中###
我的需求就是这两种规则同时可以起作用,想问问现在的阅读支持不支持?支持的话要用什么分隔符?我试了逗号,分号,回车不行
ps:就是"ruleContent" =>"replaceRegex"这个字段

### 期望实现方式 / How to implement

不知道能不能实现,或者已经实现了?

**Comment by 821938089** [comment]
这样写 `##.+webinfo.+<js></js>##[\s\S]+正在手打中[\s\S]+##正在手打中###`
或者用js来替换

**Comment by blackcd318** [comment]
> 这样写 `##.+webinfo.+<js></js>##[\s\S]+正在手打中[\s\S]+##正在手打中###` 或者用js来替换

不知道阅读里js的语法是怎么样的,专门学似乎也有点不必要
我试着照你给的我写了一下,不行,原本正常的文字成空了
##.+本章完[\s\S]+<js[\s\S]+正在手打中[\s\S]+##(    )
这是我替代的办法,
##.+本章完.+<js></js>##[\s\S]+正在手打中[\s\S]+##正在手打中###
和
##.+本章完[\s\S]+<js></js>##[\s\S]+正在手打中[\s\S]+##正在手打中###
都会把正常的正文替换掉,很莫名其妙.
一起再问个问题,开源阅读里跨行匹配用什么啊,我在vim里用\_.\+就可以了,开源阅读里不行,[\s\S]+是我找的一个通融的做法,但是感觉可能不是很合适.

**Comment by 821938089** [comment]
你想要怎么替换啊

跨行匹配就是 `[\s\S]+` ，没有问题的

**Comment by blackcd318** [comment]
> 你把具体的书源发一下吧
> 
> 跨行匹配就是 `[\s\S]+` ，没有问题的

{
    "bookSourceName": "鬼吹灯",
    "bookSourceType": 0,
    "bookSourceUrl": "http://www.gdbzkz.com",
    "customOrder": 0,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": true,
    "lastUpdateTime": 0,
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": "class.info@class.small@span.0@text",
        "coverUrl": "class.cover@img@src",
        "intro": "class.intro@text",
        "kind": "class.info@class.small@span.1@text",
        "lastChapter": "class.info@class.small@span.5@a@text",
        "name": "class.info@h2@text"
    },
    "ruleContent": {
        "content": "class.showtxt@html",
        "replaceRegex": "##.+本章完[\\s\\S]+|[\\s\\S]+正在手打中[\\s\\S]+##()###"
    },
    "ruleExplore": {},
    "ruleReview": {},
    "ruleSearch": {
        "author": "class.author@text",
        "bookList": "class.bookbox.0",
        "bookUrl": "class.bookimg@a@href",
        "coverUrl": "class.bookimg@a@img@href",
        "kind": "class.cat@text",
        "lastChapter": "a.2@text",
        "name": "a.1@text"
    },
    "ruleToc": {
        "chapterList": "class.listmain@dd",
        "chapterName": "tag.a@text",
        "chapterUrl": "tag.a@href"
    },
    "searchUrl": "/s.php?ie=utf-8&q={{key}}",
    "weight": 0
}
测试是用的"参加恋综，这个小鲜肉过分接地气",183章,可以用来测试.+本章完.+,再往后几章就有正在手打中了,现在阅读的版本是3.23.070913

**Comment by 821938089** [comment]
正则规则用错了，把最后的###删掉就可以了

**Comment by blackcd318** [comment]
> 正则规则用错了，把最后的###删掉就可以了

我发的这个写法是能满足我的需要的,只是求完美觉得还是分开来表示比较好,你把
##.+本章完[\s\S]+<js></js>##[\s\S]+正在手打中[\s\S]+##正在手打中###
代入试试就知道我说的问题了

**Comment by 821938089** [comment]
这样写就可以了 `##.+本章完[\s\S]+<js>result</js>##[\s\S]+正在手打中[\s\S]+##正在手打中`

**Comment by blackcd318** [comment]
> 这样写就可以了 `##.+本章完[\s\S]+<js>result</js>##[\s\S]+正在手打中[\s\S]+##正在手打中`

试了可以了,谢谢啊,原来需要这样隔断

**Comment by blackcd318** [comment]
问题解决了,关闭话题

**Comment by blackcd318** [comment]
Fixes #3246

**Comment by blackcd318** [comment]
Closed #3246

**Comment by blackcd318** [comment]
Closed #编号

**Comment by blackcd318** [comment]
Closed #编号

**Comment by blackcd318** [comment]
Closed #3246

**Comment by 821938089** [comment]
你要关闭issue的话点这个就可以了
![image](https://github.com/gedoor/legado/assets/8674809/a12e9cf4-0c2c-47b2-968d-4757558b0e23)

**Comment by blackcd318** [comment]
晕,我没注意那还是个按钮,就以为是个选择框了
