### ISSUE TITLE
英文和中文的组合书名会导致导致webdav阅读进度备份丢失

### ISSUE THREAD

**Issue by ghost** [gedoor/legado#3248]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

## 书名导致webdav阅读进度备份丢失
版本：

**英文和中文的组合书名**会导致导致webdav阅读进度备份丢失，我想起之前有个英文书籍名称好像是包含一些连字符也没有备份成功，我不清楚是否还有别的名字会导致错误

## 问题发现背景

我对同一本书在同一台设备既想听书又想读书。为了让这两个互不干扰，所以我安装了一个共存版本。
这个两个app，本地备份文件夹不相同，webdav备份文件夹也不相同，webdav备份设备名也不相同（**webdav备份设备名称相同提示备份失败，我不知道算不算软件问题-**-**未知错误405**，所以我设置的两个app在同一个设备的设备名是不同的）

我一共四本书，其中一个备份文件夹只显示其中一本书，另一个备份文件夹另三本，我尝试翻阅等操作更改阅读进度，然后备份至webdav，没有反应。

我一共四本书，其中一个备份文件夹只显示其中一本书，另一个备份文件夹另三本，我尝试翻阅等操作更改阅读进度，然后备份至webdav，没有反应。

我准备报告错误时我想到了书名问题，其余三本要么是英文或中文，只有这本是中英混合名。
尝试了改为了英文名（删除了名字中的中文），并删除了webdav两个文件夹的备份后。原包名的webdav四本书都有了，并存包（legado_app_3.23.07222226_原包名.apk）的的webdav同步阅读进度没有文件，只能备份。可能是测试版的bug??

## 引申

能否提供正式版共存安装包

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

legado_app_3.23.072018

### Android版本 / Android version

10

### 机型 / Model

vivo S7

**Comment by 821938089** [comment]
日志有没有东西

**Comment by 821938089** [comment]
不是崩溃日志，就是普通的日志里有没有

**Comment by 821938089** [comment]
日志在书架右上角三点里面
