### ISSUE TITLE
安卓11权限导致文件无法访问

### ISSUE THREAD

**Issue by sakura2333** [gedoor/legado#3249]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

文件系统权限问题
     对安卓不是很懂，解释不清楚，要麻烦大佬看一下详细的测试过程，
     大致感觉是阅读在获取完全访问权限的时候对外部访问加了一个私有的子路径，导致除了这个路径以外的路径都无法访问。
     过程中用到的外部文件管理器如果调用阅读打开txt，会先把远程文件缓存到本地一个文件里，此时阅读是能获取这个路径的文件的

问题分析过程
1、升级了小米12.5.6（安卓11）
2、从/Android/data/com.tencent.xxx/.../QQfile_recv调用阅读打开txt
3、阅读申请磁盘完全访问权限，并且已赋权（小米的系统中找不到这个菜单，只有应用请求赋权的时候才能看到）
    此时小米系统中的读写手机存储已经开通，
    但是子菜单的权限访问内容管理：已申请访问相册，访问社交应用文件的应用中的列表中，没有阅读
![1755180c07e9ece5ce097f12afa7054b](https://github.com/gedoor/legado/assets/27041052/616c75c2-7728-4d11-bf93-8972e210bef9)
![4c73b2c992c1797b2fe3bb2afd0d136b](https://github.com/gedoor/legado/assets/27041052/11c2f52e-fe7a-48fb-842f-429c69ab6639)

4、此时从第三方文件管理器内调用阅读打开某个txt，提示
<img width="315" alt="image" src="https://github.com/gedoor/legado/assets/27041052/23b4215d-8494-4623-8db8-72b1261b0d6e">
**但是很奇怪的是，文件是储存在smb服务器上的smb://ip/bak/A/123.txt，应该和QQfile_recv没有关系**
5、此时清空阅读app的所有数据文件，再次从第三方文件管理器打开smb的文件，阅读会弹出选择保存数据的文件夹提示，
<img width="331" alt="image" src="https://github.com/gedoor/legado/assets/27041052/32c23793-9b61-4bb8-8893-643503e39210">，但是这个弹框可以直接按退出，然后直接能看到书籍内容
同时会弹出提示
![c0e98116f7382c4333e9a016fdf3ede8](https://github.com/gedoor/legado/assets/27041052/d6f3c548-ce6f-4d02-b1eb-32262bba2525)
6、如果再次从书架访问，这个文件路径应该是外部文件浏览器调用阅读时，本地缓存文件的路径
<img width="305" alt="image" src="https://github.com/gedoor/legado/assets/27041052/258ed6ba-069b-45ed-8fc6-385e198389d3">

### 复现步骤 / How to reproduce

见上文

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.072018

### Android版本 / Android version

android 11

### 机型 / Model

MI9 Transparent Edition

**Comment by 821938089** [comment]
给阅读打开所有文件访问权限，然后再试一下，还是不行的话就只能复制出来再打开，阅读读不了这个目录下的文件

**Comment by sakura2333** [comment]
> 给阅读打开所有文件访问权限，然后再试一下，还是不行的话就只能复制出来再打开，阅读读不了这个目录下的文件

权限是给了的，但是奇怪的是打开b路径的文件，提示没有a路径的权限

**Comment by 821938089** [comment]
不是普通的媒体访问权限，是所有文件访问权限，这个权限在单独的一个地方开启的，应用信息里面的权限是没有这个的

**Comment by sakura2333** [comment]
> 不是普通的媒体访问权限，是所有文件访问权限，这个权限在单独的一个地方开启的，应用信息里面的权限是没有这个的

我试了下 权限应该是有了 我能打开txt但是还是弹权限是因为我没有设置阅读的读写目录

但是第一个问题还是存在，
就是我第一次完全访问权限赋权的那个路径是从/Android/data/xxxxxxxx/QQfile_recv打开的阅读时候弹出的，
此后不管在任何其它路径下打开文件(比如系统Download/)，都会提示上面那个/Android/data/xxxxxxxx/QQfile_recv目录没有权限
但是只要我清理阅读的所有数据，这个问题就能解决
但是如果清空阅读所有数据，所有以前的使用数据都会丢失，所以方便的话能否帮忙看一下导致问题的原因

**Comment by sakura2333** [comment]
> > 不是普通的媒体访问权限，是所有文件访问权限，这个权限在单独的一个地方开启的，应用信息里面的权限是没有这个的
> 
> 我试了下 权限应该是有了 我能打开txt但是还是弹权限是因为我没有设置阅读的读写目录
> 
> 但是第一个问题还是存在， 就是我第一次完全访问权限赋权的那个路径是从/Android/data/xxxxxxxx/QQfile_recv/近代史.txt打开的阅读时候弹出的， 此后不管在任何其它路径下打开文件(比如系统Download/数据结构.txt)，都会提示上面那个/Android/data/xxxxxxxx/QQfile_recv目录没有权限 但是只要我清理阅读的所有数据，这个问题就能解决 但是如果清空阅读所有数据，所有以前的使用数据都会丢失，所以方便的话能否帮忙看一下导致问题的原因

**Comment by gedoor** [comment]
阅读文件夹不能选择其它应用的私有文件夹

**Comment by gedoor** [comment]
![image](https://github.com/gedoor/legado/assets/22701807/2d99d27c-9a6b-40aa-9da4-10a82d92581c)
可以在这里修改

**Comment by sakura2333** [comment]
> 阅读文件夹不能选择其它应用的私有文件夹

感谢，
目录修改为Docuenmts/yuedu为阅读的目录，外部文件可以正常载入了
不过以前的本地书籍无法正常载入![f60d2a9f435eaac386765dae3be9d760](https://github.com/gedoor/legado/assets/27041052/325d3491-2d0b-4071-8207-77d89a32e039)
但是如果从文件管理器里再次打开却可以正常载入

**Comment by sakura2333** [comment]
> 建议用MT移到其它目录

感谢 终于完美搞定了
