### ISSUE TITLE
大家遇到过带验证码的搜索吗

### ISSUE THREAD

**Issue by blackcd318** [gedoor/legado#3253]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

如题,遇到这种情况开源阅读是不是只能放弃这个源了? 像https://www.qiqidu.net/这个网站

### 期望实现方式 / How to implement

只是询问学习,没找到对应的选项,这肯定不是bug,就选了这个.

**Comment by blackcd318** [comment]
> 这个网站有人做了源，你可以看看他怎么做的 https://legado.cn/thread-6226-1-1.html

谢谢啊,我看了一下,他这个没有跳过验证码,搜索了以后会弹出验证码然后手工输入,不知道是怎么回事,没有得到从这个源的结果,电脑上搜这个站是有结果的,可能是对后面的页面分析不太合适
不过也不想去完善他了,这网站也不是每次都有结果,但是验证码却是每次都会弹出来,不输入还会挡住界面.

**Comment by 821938089** [comment]
验证码是不能跳过的啊

**Comment by blackcd318** [comment]
> 验证码是不能跳过的啊

嗯,我就是想看有什么办法跳过不能,这种手工输入的方式不可取,一旦采取的源多了,那输验证码就是个问题,而且输了还不一定会搜到结果
