### ISSUE TITLE
替换问题

### ISSUE THREAD

**Issue by luoqichen** [gedoor/legado#3255]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

有一年没有更新软件了，最近更新后发现替换功能不太好用，好像不会识别空格和换行，以前版本可以一整页替换，现在只能一行一行替换

### 复现步骤 / How to reproduce

点击替换后只要有换行和空格就无法替换成功

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22

### Android版本 / Android version

安卓12

### 机型 / Model

小米12

**Comment by 821938089** [comment]
现在替换时段首没有空格
