### ISSUE TITLE
测试版在通过小说详情搜索书名或作者瞬间弹出搜索结果为空还无法关闭

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3257]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

弹出搜索结果为空，弹窗底下明明在显示搜索结果，弹出的对话框还无法关闭

### 复现步骤 / How to reproduce

使用最新测试版，从小说详情点作者或者书名进入搜索就会瞬间弹出结果为空，无法关闭

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.072710

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
已修复瞬间弹出搜索结果为空问题
未复现无法关闭问题

**Comment by zousizhe** [comment]
> 已修复瞬间弹出搜索结果为空问题 未复现无法关闭问题

现在倒是正常了，就是从详情页进入搜索时会先在输入框停顿一两秒才开始搜索，之前不会这样的

**Comment by zousizhe** [comment]
> 已修复瞬间弹出搜索结果为空问题 未复现无法关闭问题

![Screenrecorder-2023-08-02-09-09-24-522](https://github.com/gedoor/legado/assets/37259360/ccd4e155-c0a8-46d0-b182-cae017a6a9ba)

**Comment by gedoor** [comment]
我看下

**Comment by zousizhe** [comment]
> 我看下

弹出菜单不可点击的问题修复了，但是切换搜索分组时依然会瞬间弹出结果为空

**Comment by gedoor** [comment]
我看下
