### ISSUE TITLE
希望可以备份阅读背景

### ISSUE THREAD

**Issue by wuyou1024** [gedoor/legado#3258]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望可以备份阅读背景

### 期望实现方式 / How to implement

无

### 附加信息 / Additions

1

### 效果演示 / Demo

1

**Comment by gedoor** [comment]
我考虑下怎么做好

**Comment by wuyou1024** [comment]
> 我考虑下怎么做好

辛苦飞哥了♥️

**Comment by Vstory** [comment]
> 我考虑下怎么做好

base64 保存图片，然后存到 json 文本里。

**Comment by wuyou1024** [comment]
> > 我考虑下怎么做好
> 
> base64 保存图片，然后存到 json 文本里。

飞哥行动力太强了，有点受宠若惊😯😯

**Comment by Vstory** [comment]
> 
> 飞哥行动力太强了，有点受宠若惊😯😯

已经支持了？

**Comment by YaKun9** [comment]
所以支持了吗

**Comment by Vstory** [comment]
> 所以支持了吗

不清楚 没关注
