### ISSUE TITLE
单本导出没有反应

### ISSUE THREAD

**Issue by wuyou1024** [gedoor/legado#3262]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

刚刚添加的单本书签导出没有效果

### 复现步骤 / How to reproduce

在书籍里书签栏右上角导出

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新普通版

### Android版本 / Android version

安卓12

### 机型 / Model

realmeq2

**Comment by gedoor** [comment]
应该修复了

**Comment by wuyou1024** [comment]
> 应该修复了

等下个版本吗，还是有测试版

**Comment by gedoor** [comment]
我测试没问题了啊
