### ISSUE TITLE
单本书签导出依然有问题

### ISSUE THREAD

**Issue by wuyou1024** [gedoor/legado#3263]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

与上一版本一样，点导出没有反应

### 复现步骤 / How to reproduce

在书籍里目录栏旁的书签栏，右上角导出

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新版

### Android版本 / Android version

安卓12

### 机型 / Model

realmeq2

**Comment by gedoor** [comment]
你是不是没有给通知权限

**Comment by wuyou1024** [comment]
> 你是不是没有给通知权限

给了

**Comment by gedoor** [comment]
看看日志,有报错日志吗,我这边没法复现

**Comment by wuyou1024** [comment]
> 看看日志,有报错日志吗,我这边没法复现

并没有任何关于书签的日志，我这边点导出是没有任何反应，也不报错

**Comment by gedoor** [comment]
书签导出有问题啊,我看成书籍导出了,我测试一下

**Comment by gedoor** [comment]
解决了
