### ISSUE TITLE
导出功能是否可以支持后台导出

### ISSUE THREAD

**Issue by sakura2333** [gedoor/legado#3270]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

使用导出功能耗时较长，所以想问一下是否支持后台导出，
目前试下来离开导出界面导出就会停止

### 期望实现方式 / How to implement

最简单是是否支持导出的时候切换到其他功能，甚至其他app

**Comment by Discut** [comment]
貌似接下来会实现？

**Comment by Discut** [comment]
你可以试试测试版

**Comment by sakura2333** [comment]
> 你可以试试测试版
确实很好用  可惜签名不一样  没法覆盖安装  只能等正式版了
