### ISSUE TITLE
禁用返回键选项消失

### ISSUE THREAD

**Issue by chaeolus** [gedoor/legado#3274]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

3.23.07310941以后的版本，阅读界面设置里的禁用返回键选项消失

### 复现步骤 / How to reproduce

进入阅读界面，点击设置，菜单中无禁用返回键选项

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.08020948

### Android版本 / Android version

Android 13

### 机型 / Model

OPPO Find X6 Pro

**Comment by 821938089** [comment]
删掉了

**Comment by chaeolus** [comment]
能否把这功能加回来呢？我的习惯是右滑翻上一页，没开这个选项的话经常会误触全局返回。

**Comment by 821938089** [comment]
好了
