### ISSUE TITLE
希望能开发tv版软件

### ISSUE THREAD

**Issue by softmetal66** [gedoor/legado#3278]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现在的电视大都是安卓操作系统，希望能开发tv版软件

### 期望实现方式 / How to implement

尽量简化、保留主要功能即可，同时适配遥控器操作；不知把手机端软件迁移过去难度几何

**Comment by 821938089** [comment]
你直接在电视上装就行了，应该是可以在电视上用的

**Comment by 821938089** [comment]
阅读设置里有一个自定义翻页按键功能，你设置一下应该就可以了

**Comment by Vstory** [comment]
这真牛批

**Comment by noir1216** [comment]
同九义，汝何秀

**Comment by taxueqinyin** [comment]
好奇问下，你是要用电视看小说？
