### ISSUE TITLE
语音阅读upub格式的电子书经常会重复阅读

### ISSUE THREAD

**Issue by bluceli0** [gedoor/legado#3283]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

语音阅读upub格式的电子书经常会重复阅读。微信阅读这类软件就没问题，使用语音时锁定的是一行来进行tts阅读。阅读是锁定一段，我用来读epub格式的电子书更是有时候会锁定一面进行tts阅读，而且会出现重复阅读。希望能更改一下锁定一行或者两三行来阅读。

### 复现步骤 / How to reproduce

本地导入的epub格式电子书，我导入的是《卢瑟经济学》（Z-Library上面可以搜到），TTS用的是MultiTTS。听一段时间就会发现经常重复。（重复的也许是一面文字，不太确定）

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.073011

### Android版本 / Android version

Android 13

### 机型 / Model

Xiaomi Mi 10s

**Comment by 821938089** [comment]
能不能录个视频看看

**Comment by bluceli0** [comment]
> 能不能录个视频看看

你自己试试吧，我把epub格式的转换成txt格式的了
