### ISSUE TITLE
本地小说简介

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3284]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

本地小说能自动匹配封面，不能自动匹配简介，其实正文里都有，像TXT格式可能比较难，里面简介格式不一样，EPUB是为什么出问题的?
![Screenshot_2023-08-11-09-09-46-098_io legado app release](https://github.com/gedoor/legado/assets/106790230/d16d82ab-6e98-4189-b116-dbb16ba15a49)
![Screenshot_2023-08-11-09-09-39-550_io legado app release](https://github.com/gedoor/legado/assets/106790230/1a47ff30-cfc6-442a-a26c-04d2ae534e58)
我阅读导出的EPUB，自动出现封面简介还挺开心的，就是这个简介咋没有换行，看着有点难受

### 期望实现方式 / How to implement

txt不强求了，EPUB匹配简介希望能支持换行

**Comment by 821938089** [comment]
已修复
