### ISSUE TITLE
mate30pro曲面屏换源页

### ISSUE THREAD

**Issue by 1770682368** [gedoor/legado#3286]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

mate30pro曲面屏换源页，开启左右拓展是正常的，没有左右拓展右边边距没有了。
![1](https://github.com/gedoor/legado/assets/26159318/8aedd863-40e3-4871-b982-3ab74b853708)
![2](https://github.com/gedoor/legado/assets/26159318/8fe4748d-d1f8-4e90-96aa-3ee8ec464ab1)
![3](https://github.com/gedoor/legado/assets/26159318/e1d01f3c-fa6e-4786-8f26-f5e2c64e78cf)

### 复现步骤 / How to reproduce

点击换源

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.073011

### Android版本 / Android version

harmonyOS 4.0.0

### 机型 / Model

华为mate30pro

**Comment by 821938089** [comment]
试试最新测试版

**Comment by 1770682368** [comment]
还是不行  
![Screenshot_20230811_142536_io legado app releaseA](https://github.com/gedoor/legado/assets/26159318/cc5e213e-b07a-4d1f-bcc3-d4ad5183c6e1)
![Screenshot_20230811_142544_io legado app releaseA](https://github.com/gedoor/legado/assets/26159318/45765336-9be5-4987-9fa7-b4fb80e3f26d)

**Comment by 821938089** [comment]
再试试最新的测试版

**Comment by 1770682368** [comment]
用了这个版本legado_app_3.23.08111750_共存.apk，还是一样

**Comment by 821938089** [comment]
再试试

**Comment by 1770682368** [comment]
还是不行，只有换源的弹窗会这样，别的弹窗窗口都是正常的，更新日志的弹窗窗口就是正常的
