### ISSUE TITLE
取消搜索功能是否实际生效问题

### ISSUE THREAD

**Issue by qq570026938** [gedoor/legado#329]
在搜索书籍过程中点击取消搜索，打印日志发现，后台仍旧在执行搜索任务，实际并没有关闭线程，这个是否可以做个优化，现在只有当退出页面时才真正的结束搜索任务

**Comment by gedoor** [comment]
好的

**Comment by qq570026938** [comment]
> 好的

请问什么时候针对搜索做下优化呢

**Comment by qq570026938** [comment]
> 好的

搜索优化后出现搜索不出来的问题，搜索中取消搜索，在次搜索小说时，出现搜索不到数据的问题

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持
