### ISSUE TITLE
阅读epub格式文件页面效果

### ISSUE THREAD

**Issue by BelongWhite** [gedoor/legado#3293]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在阅读epub格式文件时，打开文件对应页面显示注释，像这种的
![Screenshot_2023-08-15-09-33-32-01_c0fc23361849dfc0a4b4c6dd2adcac79](https://github.com/gedoor/legado/assets/32151114/272217f5-772d-47cc-8fed-547b8d071829)

### 期望实现方式 / How to implement

可以添加这个功能么

### 效果演示 / Demo

![Screenshot_2023-08-15-09-33-56-16_90024215e504237c76412be1999ad914](https://github.com/gedoor/legado/assets/32151114/b4cacf49-ba63-4ba1-b69e-30a383e02654)
![Screenshot_2023-08-15-09-33-32-01_c0fc23361849dfc0a4b4c6dd2adcac79](https://github.com/gedoor/legado/assets/32151114/c578f3fd-20c4-4067-a07d-dd729099836e)

**Comment by yyy33** [comment]
是的，这很有必要
