### ISSUE TITLE
正文&标题净化问题

### ISSUE THREAD

**Issue by wishdq** [gedoor/legado#3296]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

正文替换净化关闭后，无论标题净化打开还是关闭都不起作用。
有些图片源，不需要正文净化，但需要标题净化。但关闭正文净化后，标题净化不起作用。

### 期望实现方式 / How to implement

希望正文净化和标题净化互不干扰。

**Comment by 821938089** [comment]
你可以将该源加入净化规则排除范围里面
