### ISSUE TITLE
Webdav和本地备份成功却提示失败

### ISSUE THREAD

**Issue by BlackRosePetals** [gedoor/legado#3297]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 机型

OPPO R11s PLUS

### 安卓版本

Android 8.1.0

### 阅读版本

测试版，从 legado_google_3.23.08022356_原包名版本到legado_google_3.23.08122230_原包名都一样出现该问题

### 网络环境及Webdav服务商

电信数据和电信宽带，infiniCLOUD。

### 问题描述

手动点击备份，提示“备份失败，Webdav上传失败，文件不存在”，但是检查手机存储和webdav后台却是有新的备份文件和上传记录，手动恢复也可以恢复到最新备份的记录。

之前的任意版本都不会出现该提示，都是上传成功或上传失败的提示。

![Screenshot_2023-08-16-18-41-54-76-small](https://github.com/gedoor/legado/assets/53809038/8a773d9b-c163-4e82-8dbc-fa324dea837b)
![msedge_SmMcY809sA](https://github.com/gedoor/legado/assets/53809038/ef14247e-b1ab-4d38-9a02-3adf18e6a256)

### 复现步骤 / How to reproduce

不知道是不是备份的判定写错了，还是其它未知问题引起的。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

legado_google_3.23.08122230_原包名

### Android版本 / Android version

8.1.0

### 机型 / Model

OPPO R11S PLUS

**Comment by 821938089** [comment]
试试最新测试版，应该好了

**Comment by BlackRosePetals** [comment]
大佬效率真高，新版本已经修复了。刚刚安装测试了一下，备份恢复到正常提示了。
