### ISSUE TITLE
建议页脚的进度信息增加页码显示方式

### ISSUE THREAD

**Issue by easythd** [gedoor/legado#330]
现在在界面-信息这个对话框中，
页数是指当前章节共多少页，目前在第几页。如4/13
而进度是指当前阅读的章节在整本书百分之多少，如97.3%

强烈建议把这个进度改为：剩余章数/总章数，如12/2500，表示共2500章，当前剩余12章
或是只要剩余章数也可以，加一个剩余章数的信息选项，可以自己选择出来显示。

原因是那个进度的百分比一点用都没有，看不懂，如上面的例子，进度97.8%和进度99.2%，天知道是什么意思，到底还有多少是和总章数有关的，也许1%是10章，也许是100章，也许是23章。。。，脑子里算半天也不知道还有多少。。。不如不要。但如果直接显示剩余章数12，就很直观了。还有12章，还可以看一会。

**Comment by db-one** [comment]
或者干脆加这么一个进度    大家可以自由选择   不是有一个页脚的信息类型选择   加里面一个选项

**Comment by db-one** [comment]
我是比较习惯看进度的百分比的

**Comment by easythd** [comment]
> 我是比较习惯看进度的百分比的

嗯嗯，大家习惯不同。
我是看不懂，不知道97.3%代表还有多少章。
你说得对，加个选项自由选择

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持
