### ISSUE TITLE
点朗读上一段到本页上一句跳转BUG

### ISSUE THREAD

**Issue by N-0012** [gedoor/legado#3302]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

朗读状态时点击朗读上一段，当朗读的焦点句子超过当前页所显示的内容时会跳到上一章的末页首句（无论当前是在本章的哪一页）

### 复现步骤 / How to reproduce

开启朗读，击朗读上一段，移动朗读的焦点句子到当前页所显示内容的上一句，页面会跳到上一章的末页首句

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

```io.legado.app.exception.NoStackTraceException: 没有进度```

### 阅读版本 / Legado version

3.23.073011

### Android版本 / Android version

Android 13

### 机型 / Model

Realme GT Neo2

**Comment by aaro-n** [comment]
# 问题描述
小米12s pro使用阅读APP的朗读功能时，关闭屏幕并进入锁屏状态，再次打开屏幕并解锁，会出现朗读声音消失，并重新从第一行开始读，如果阅读APP退到后台，再次进行相同的测试，则不会出现问题。
# 介绍
阅读APP版本：3.23.073011
手机版本: miui 14.0.9 eu , Android 13，刷的MUI EU版本
朗读功能：自建ms-ra-forwarder

**Comment by 821938089** [comment]
@aaro-n 隐藏状态栏、导航栏、扩展到刘海都打开看看

**Comment by aaro-n** [comment]
@821938089 打开`隐藏导航栏`没有出现反馈的问题，开打`隐藏状态栏`和`扩展到刘海`对解决反馈问题无效，这三项都是分别单独测试。
