### ISSUE TITLE
建议增加自动更新时自动离线下载新章节的功能

### ISSUE THREAD

**Issue by easythd** [gedoor/legado#331]
关于离线下载2个建议：
1、现在离线下载是需要手工去选择执行的，建议在其它设置界面中打勾自动刷新这个选项时，可以同时选择自动离线下载。
2、离线下载开始后，下多少哪些已经下载，哪些还没下载，根本看不到，能否在目录中有标记显示？更进一步，可以在离线下载对话框中选择只下载当前章节以后未下载过的？

**Comment by Antecer** [comment]
刷新书架时自动缓存新章节的功能吗？

**Comment by easythd** [comment]
> 刷新书架时自动缓存新章节的功能吗？

是的

**Comment by gedoor** [comment]
这个已经有了,会缓存10章
