### ISSUE TITLE
请求把本地TTS也做到像在线TTS一样及时且自然的翻页

### ISSUE THREAD

**Issue by lzhiye** [gedoor/legado#3312]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在线TTS不勾选“按页朗读”也能在段中准确的及时翻页，但本地TTS就不行，必须等到本段朗读完才会翻页，勾了“按页朗读”虽然能及时翻页，但朗读会停顿一下，长时间听书时很难受，请求把本地TTS也做到像在线TTS一样及时且自然的翻页，感谢感谢！

### 期望实现方式 / How to implement

请求把本地TTS也做到像在线TTS一样及时且自然的翻页。

**Comment by 821938089** [comment]
用这个 https://github.com/jing332/tts-server-android
里面有个系统TTS转发器，可以将本地TTS转成在线TTS

**Comment by lzhiye** [comment]
> 用这个 https://github.com/jing332/tts-server-android
> 里面有个系统TTS转发器，可以将本地TTS转成在线TTS

我用的MultiTTS，有转发器，用过一段时间转发器，太耗电了，同样听书一个班的时间，用了转发器手机电量起码多消耗20%
