### ISSUE TITLE
js有一部分函数无法使用

### ISSUE THREAD

**Issue by gjmhmm8** [gedoor/legado#3313]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [ ] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

编辑书源时例如flat等等的函数无法使用

### 复现步骤 / How to reproduce

[[1,2,3,4,5],[6,7,8]].flat()

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.062623

### Android版本 / Android version

12

### 机型 / Model

hw p50 pro

**Comment by 821938089** [comment]
js引擎不支持新的规范标准，尽量用es6之前的来写，或者你自己加个polyfill来用

**Comment by gjmhmm8** [comment]
es6应该是支持那些的，怀疑目前只支持到es5甚至更早

**Comment by 821938089** [comment]
flat函数是在es2019中加入的，es6并不支持
