### ISSUE TITLE
如果网络不稳定卡住，半天无法加载正文，那么手动缓存章节成功之后依然无法加载

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3315]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如果有书源网络不稳定，进入正文被卡住，迟迟无法加载，这个时候选择缓存章节，并显示缓存成功了，用文件管理进到阅读缓存路径，可以看到已经成功缓存到了内容，正文内容也无误。但是因为小说卡在第一页的正文加载中，阅读无论如何都无法加载已缓存到的内容，往下翻页也一样无法加载，非要重新刷新第一页，等待重新解析成功才能读取缓存的章节

### 复现步骤 / How to reproduce

遇到有书源正文加载非常慢时，选择缓存所有章节，可以正常缓存，但是依然卡在解析第一页的正文，无法跳过这个步骤读取缓存内容

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23

### Android版本 / Android version

android 13

### 机型 / Model

redmi k60 pro

**Comment by 821938089** [comment]
有没有可以复现的书源
