### ISSUE TITLE
希望能增加批量换源的功能

### ISSUE THREAD

**Issue by Jnoee** [gedoor/legado#3317]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

书源过期了或者更换了网址，但其实书都还在，但原书源已不可用了。

### 期望实现方式 / How to implement

希望能够不用一本一本重新下载已经下载过的书，直接编辑原书源的地址即可替代。
或者提供一个批量换源的功能，可以一次性将同一个书源的书换成新的书源。

**Comment by 821938089** [comment]
书架管理里面可以批量换源
