### ISSUE TITLE
【八仙小说网】正文批量替换，搜索页字符集转换，目录手动排序

### ISSUE THREAD

**Issue by violetice** [gedoor/legado#3319]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1、批量替换（replaceRegex）字段，希望能支持多条替换规则。
2、搜索页的关键字，希望提供更多的字符集转换接口。
3、目录能用 JavaScript 进行排序。

这个站点的目录不是正常排序，如果软件能自行矫正排序的话，那更好（doge）

### 期望实现方式 / How to implement

1、批量替换，用分隔符来支持多条规则
```
##<img src="http://www.8xianxs.com/image/se.jpg">##色&
##<img src="http://www.8xianxs.com/image/chun2.jpg">##唇
```

2、字符集转换
现有 java.utf8ToGbk(str: String)，希望提供多字符集转换接口。
```
java.stringConvert(str: String, form: String(UTF-8|GBK|CP936...), to: String(UTF-8|GBK|CP936...))
```

3、目录排序
```javascript
// 传入一个自定义函数，入参（索引，章节名称），返回新索引。
function(index, title){
    if (title === '楔子|序之类的') {
        return 0
    }
    // title = 第四章
    let t = title.replace('第', '').replace('章', '')
    // 调用大写中文转数字库
    return nzh.decode(t) - 1
}
```

## 正文批量替换

web端设置书源，正文tab里有个替换规则（replaceRegex）。怎么批量替换啊？

替换一个是可以的，没法多个规则同时存在吗？只能后期导入净化规则？

可以再这个框里写 JavaScript 来替换吗？

[母上攻略_第一章_八仙小说网 (8xianxs.com)](http://www.8xianxs.com/page.asp?id=7605609)

![](https://cdn.vlice.cn/image/github/legado/2023-09-03%2004%2024%2044.png)

## 搜索页字符集转换

网站用的字符集是CP936，文档里只有java.utf8ToGbk(str: String)。能开放更多的字符集转码选项吗？

[仙子的_八仙小说网 (8xianxs.com)](http://www.8xianxs.com/search.asp?key=%CF%C9%D7%D3%B5%C4&x=0&y=0)

![](https://cdn.vlice.cn/image/github/legado/2023-09-03%2005%2016%2034.png)

**Comment by 821938089** [comment]
1、replaceRegex规则可以使用js，你也可以直接在正文规则里用js替换，具体可以看看别的源是怎么做的
2、这个函数没用的，你在请求参数那里直接设置charset就可以了
3、目录排序可以在目录列表规则那里做
