### ISSUE TITLE
希望增加订阅源分类合并功能和打开app默认显示订阅源功能

### ISSUE THREAD

**Issue by jxjxjhjh** [gedoor/legado#3327]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1、现在的订阅源查看的时候一次只能查看一个源，效率太低了，希望能让一个订阅源里面所有分类项目的条目放在一个列表中，就像rss阅读器的分类列表一样。
就比如我订阅源看B站UP主，一个分类只能显示一个UP主的视频列表，如果我订阅了5个，就得滑动四次才能全部查看完毕，如果有几个没更新，就等于白操作了。
2、看订阅源比较多，希望打开APP默认是订阅源界面。

### 期望实现方式 / How to implement

1、就像RSS阅读器一样。
2、实现方法应该不难。

**Comment by jxjxjhjh** [comment]
> 第一个功能可以通过修改源规则实现

求方法

**Comment by jxjxjhjh** [comment]
大佬有办法吗

**Comment by 821938089** [comment]
你改改列表规则，把所有的分类的数据都在这里请求然后合并到一起

**Comment by jxjxjhjh** [comment]
> 你改改列表规则，把所有的分类的数据都在这里请求然后合并到一起

不懂。
https;//xxx.com/feed1.xml
https://xxx.com/feed2.xml
这两个网址怎么通过修改列表规则合并到一起？

**Comment by jxjxjhjh** [comment]
> 你改改列表规则，把所有的分类的数据都在这里请求然后合并到一起

不懂。
https://xxx.com/feed1.xml
https://xxx.com/feed2.xml
这两个网址怎么通过修改列表规则合并到一起？
虽然它们得结构是一样的，可是怎么才能让它们的条目混合在一起，而不需要用分类功能？

**Comment by 821938089** [comment]
https://shuyuan.mgz6.cc/shuyuan/183fb89bfb59af3fc4a8d2f21cb34c39.json

**Comment by jxjxjhjh** [comment]
> https://shuyuan.mgz6.cc/shuyuan/183fb89bfb59af3fc4a8d2f21cb34c39.json

还真的可以，但你这种写法我不知道怎么扩展，如果是3个甚至更多feed网址呢？怎么写？
https://xxx.com/feed1.xml
https://xxx.com/feed2.xml
https://xxx.com/feed3.xml
https://xxx.com/feed4.xml

**Comment by 821938089** [comment]
列表规则ajax那里继续加就行

**Comment by jxjxjhjh** [comment]
> 列表规则ajax那里继续加就行

还有一个问题，能解决就完美了。
条目是按照
rss1全部
rss2全部
rss3全部
这样排列的，我要看rss2更新条目需要划完rss1全部才行，这样的查看方式比分类还麻烦。

**Comment by 821938089** [comment]
你不是要放一个列表里吗

**Comment by jxjxjhjh** [comment]
> 你不是要放一个列表里吗

是在一个列表里了，可是文章排列不是按更新时间来的。
网址1的全部文章显示完之后才显示网址2的文章。

**Comment by jxjxjhjh** [comment]
> 你不是要放一个列表里吗

![Uploading Screenshot_2023-09-11-15-07-41-416_io.legado.app.release.jpg…]()
![Screenshot_2023-09-11-15-07-45-659_io legado app release](https://github.com/gedoor/legado/assets/22759318/21e83e45-0ec8-4213-8eb0-3c9a5725640c)
![Screenshot_2023-09-11-15-07-51-071_io legado app release](https://github.com/gedoor/legado/assets/22759318/71b81b5d-4119-4da4-95dc-f73d74980263)
![Screenshot_2023-09-11-15-07-57-159_io legado app release](https://github.com/gedoor/legado/assets/22759318/34670376-6fe6-421f-9d63-7103f71f234b)

**Comment by jxjxjhjh** [comment]
> 你不是要放一个列表里吗

![Screenshot_2023-09-11-15-12-57-641_io legado app release](https://github.com/gedoor/legado/assets/22759318/caa0a733-5f0e-4128-905c-b1bbd3ca2bdc)
正常的rss列表应该是这样的

**Comment by jxjxjhjh** [comment]
> 你不是要放一个列表里吗

大佬还有办法吗？

**Comment by 821938089** [comment]
https://shuyuan.mgz6.cc/shuyuan/e09e8f5cce01e57143a43423da54d3a6.json

**Comment by jxjxjhjh** [comment]
> https://shuyuan.mgz6.cc/shuyuan/e09e8f5cce01e57143a43423da54d3a6.json

牛逼
