### ISSUE TITLE
最近经常出现百度tts调用失败, 希望失败的语句用本地tts替代, 目前是无声替代,剧情不连贯

### ISSUE THREAD

**Issue by tick-guo** [gedoor/legado#3331]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

经常出现无音段落
![微信图片_20230909101502](https://github.com/gedoor/legado/assets/39718787/ee43a5c8-c571-4acc-9bc8-fefc41d54b85)

### 期望实现方式 / How to implement

增加一个选项:
1.失败重试
2.tts下载音频失败时,用本地tts补充该段内容

**Comment by majorcheng** [comment]
是百度语音的pdt又不能用了

**Comment by wuxq** [comment]
百度的确实不能用了 另外 我看这个访问百度语音合成的能百度的文档也对不上啊
