### ISSUE TITLE
本地书换源问题

### ISSUE THREAD

**Issue by changqing23** [gedoor/legado#3332]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

之前的阅读同一本网络小说导入的本地书和用书源搜索到的网络书是可以共存的，现在的话如果想在网络上搜索小说就会默认将本地书换源成用书源搜索到的小说，导入的本地书籍就无法再观看了，能将原本的本地书籍与网络搜索到的书籍共存功能加回来吗

### 期望实现方式 / How to implement

能将原本的本地书籍与网络搜索到的书籍共存功能加回来吗

**Comment by 821938089** [comment]
一直都不能共存，你需要编辑一下书籍信息，让这两本书的书名或作者不一样就可以共存了
