### ISSUE TITLE
请求增加黑白墨水屏eink支持

### ISSUE THREAD

**Issue by cncqtan** [gedoor/legado#3334]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前软件为Android系统打造，软件中的彩色以及过渡动画在黑白色的墨水屏设备上都无法起作用，反而降低了阅读体验。

### 期望实现方式 / How to implement

去掉彩色以及过渡动画，去掉手势支持；或提供一个黑白墨水屏模式选项。

**Comment by 821938089** [comment]
主题模式改成墨水屏
