### ISSUE TITLE
允许设置 ”覆盖、滑动、仿真、滚动“ 翻页动画的翻页速度

### ISSUE THREAD

**Issue by ayuxy** [gedoor/legado#3335]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

翻页动画速度感觉稍微有点慢，同样是覆盖翻页，感觉番茄小说的覆盖翻页速度更加舒服一些。非常希望能够自己设置 ”覆盖、滑动、仿真“ 等翻页动画的速度
### 期望实现方式 / How to implement

在设置里面能够允许自己修改  " 覆盖、滑动、仿真、滚动 ” 翻页动画 各自 的翻页速度

### 附加信息 / Additions

无

### 效果演示 / Demo

无

**Comment by yjosx** [comment]
现在的翻页动画速度是固定的，看起来卡卡的，而且不跟手，真的很需要这个功能，可以问问为啥没通过这个pull request吗

**Comment by 821938089** [comment]
@yjosx 
他自己关闭的，可能是有问题
看起来卡卡的是没开高刷的问题

**Comment by pth2000** [comment]
求支持，翻页速度有点慢
