### ISSUE TITLE
进行搜索的时候，如果结果数量过多会出现问题（例如：卡死）

### ISSUE THREAD

**Issue by yehuoshun** [gedoor/legado#3338]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

进行搜索的时候，如果结果数量过多会出现问题（例如：卡死）
我降低了线程数，降低到20线程还是会出现这种情况

### 复现步骤 / How to reproduce

我降低了线程数，降低到20线程还是会出现这种情况

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.073011

### Android版本 / Android version

12

### 机型 / Model

真我neo5

**Comment by 821938089** [comment]
减少搜索的书源数量，搜到书了就马上停止搜索

**Comment by benziiii** [comment]
是的
