### ISSUE TITLE
请问自定义阿里云tts怎么获取朗读文本

### ISSUE THREAD

**Issue by TTTTTiT** [gedoor/legado#334]
https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/tts,{
    "method": "POST",
    "headers": {"Content-Type":"application/json"},
    "body": {
    "appkey":"",
    "text":{{encodeURIComponent(encodeURIComponent(speakText))}},
    "token":""
  }

}
上面是我的示例，已经获取了appkey和token,但是不能朗读。获取朗读文本text我是抄的阅读原来自带的百度在线tts的，请问具体该怎么写

[阿里云语音合成RESTful API](https://help.aliyun.com/document_detail/94737.html?spm=a2c4g.11186623.4.2.7ea8259e8TgJzV)

**Comment by gedoor** [comment]
url规则和书源里的url规则一样,不了解的可以看一下书源制作规则。

{{}}内部是js语句,支持两个参数speakText朗读文本,speakSpeed朗读速度,值为0-45,需要直接换算为合适的值。

**Comment by gedoor** [comment]
阿里的可能不要编码两次

**Comment by gedoor** [comment]
格式用mp3

**Comment by TTTTTiT** [comment]
https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/tts,{
    "method": "POST",
    "headers": {"Content-Type": "application/json"},
    "body": "appkey=xxxxxxxxxxx&text={{encodeURIComponent(speakText)}}&speech_rate={{String((speakSpeed + 5) / 10 + 4)}}&token=xxxxxxxxxx&format=mp3"
}
请问这样写的问题在哪，还是不能成功朗读。
编码一次或者两次的情况都试过，不要阅读速度的情况也试过。
我已经拿我的token和appkey测试过了，能正常响应。
![IMG_20200826_154424](https://user-images.githubusercontent.com/30504321/91275934-6487b900-e7b3-11ea-8c9c-eeda7daaa317.jpg)

**Comment by TTTTTiT** [comment]
用get方式朗读成功了
https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/tts?appkey=xxxx&token=xxxx&text={{encodeURIComponent(speakText)}}&format=mp3&sample_rate=16000

**Comment by Celeter** [comment]
> 用get方式朗读成功了
> [https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/tts?appkey=xxxx&token=xxxx&text={{encodeURIComponent(speakText)}}&format=mp3&sample_rate=16000](https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/tts?appkey=xxxx&token=xxxx&text=%7B%7BencodeURIComponent(speakText)%7D%7D&format=mp3&sample_rate=16000)

POST不需要url编码
![Screenshot_20200826-210959](https://user-images.githubusercontent.com/48249130/91307559-b266e600-e7e0-11ea-8caf-a89cc2b9d638.jpg)

**Comment by Celeter** [comment]
get的时候url编码要改成这个，阿里api里面有例子。
`encodeURIComponent(text).replace(/[!'()*]/g, function(c) {return '%' + c.charCodeAt(0).toString(16);})`

**Comment by db-one** [comment]
所以@tt

> [https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/tts,{](https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/tts,%7B)
> "method": "POST",
> "headers": {"Content-Type": "application/json"},
> "body": "appkey=xxxxxxxxxxx&text={{encodeURIComponent(speakText)}}&speech_rate={{String((speakSpeed + 5) / 10 + 4)}}&token=xxxxxxxxxx&format=mp3"
> }
> 请问这样写的问题在哪，还是不能成功朗读。
> 编码一次或者两次的情况都试过，不要阅读速度的情况也试过。
> 我已经拿我的token和appkey测试过了，能正常响应。
> ![IMG_20200826_154424](https://user-images.githubusercontent.com/30504321/91275934-6487b900-e7b3-11ea-8c9c-eeda7daaa317.jpg)

选择解决了没有

**Comment by olbb** [comment]
速度可以通过 speech_rate={{String((speakSpeed) * 20 - 400)}} 来指定
