### ISSUE TITLE
能兼容6.0安卓系统不？

### ISSUE THREAD

**Issue by ATang007dg** [gedoor/legado#3341]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

老手机用来看看小说什么的，但是目前版本没办法在6.0系统上安装。

### 期望实现方式 / How to implement

如果方便的话希望增加兼容低版本。可以让老手机发挥余热。

**Comment by 821938089** [comment]
Release中有个lollipop版的，最低5.0系统

**Comment by ATang007dg** [comment]
> Release中有个lollipop版的，最低5.0系统

谢谢我试试
