### ISSUE TITLE
段评功能

### ISSUE THREAD

**Issue by huajideshutiao** [gedoor/legado#3342]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

实际上是有相关issue的，但是已经过去一年了。[#2250](https://github.com/gedoor/legado/pull/2250) 这个pull到现在还没用上。

### 期望实现方式 / How to implement

如[此处](https://github.com/gedoor/legado/issues/1963) 所示

**Comment by 821938089** [comment]
PR作者已放弃开发
