### ISSUE TITLE
当书架里书很多的时候，向下翻动需要不停的用手指下滑翻动，滚动条不能拖动。

### ISSUE THREAD

**Issue by pinoren** [gedoor/legado#3346]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

很多本书的话就需要用手指不停的向下滑动，无法快速定位到某一位置。书架的右边是有一个滚动条的，是否可以让侧边滚动条可以快速拖动到某个位置？不是图书内，而是所有书展示出来的这个书架页面。这个问题其实很久以前提过，但是看着好像说是问题被提交了，但是后来就被关闭了，再也没有后续。。。

### 期望实现方式 / How to implement

能像例如书的目录章节列表一样，可以通过滚动条快速定位到某个位置。

**Comment by 821938089** [comment]
你记得书名的话可以直接搜索书架

**Comment by pinoren** [comment]
是的，这个功能也很好用，就是书比较多，想浏览的时候就会比较麻烦了，必须不停的向下滑动滑动。。。

**Comment by 821938089** [comment]
最新测试版改了，你可以试试

**Comment by pinoren** [comment]
好的好的，非常非常感谢您啦！！

**Comment by pinoren** [comment]
试用完毕，滚动条非常好用，太感谢您啦！
