### ISSUE TITLE
希望增加上次本地TXT等文本文件的功能

### ISSUE THREAD

**Issue by lalakiop** [gedoor/legado#3347]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望增加备份本地的小说文件（txt等）webdav备份的功能

### 期望实现方式 / How to implement

可以将阅读信息和小说文件信息分开上传，小说文件只有增加或者删减时才进行备份操作

**Comment by 821938089** [comment]
书籍详情页可以上传

**Comment by lalakiop** [comment]
找到了，非常感谢。可以单独增加一个功能的开关吗？就是默认关闭，打开后全部自动上传的那种。

**Comment by lalakiop** [comment]
> 书籍详情页可以上传

找到了，非常感谢。可以单独增加一个功能的开关吗？就是默认关闭，打开后全部自动上传的那种。

**Comment by pinoren** [comment]
你把本地的TXT书籍全部手工上传WEBDAV，然后用添加远程书籍功能全部导入，全部导入的时候已经存在的书籍是不会被重复导入的。。。
