### ISSUE TITLE
当 "第X卷 XX" 内容为空时，希望 直接跳过 或 显示卷名（大号字体），而非显示一个空白页

### ISSUE THREAD

**Issue by XIU2** [gedoor/legado#3354]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

一些书源、书籍、本地 TXT 包含有卷名 `第X卷 XXX`，但这些卷的内容基本上都是空的，在从该卷名前一章翻页到该卷时，会显示为一个空白页（1/1）。时不时遇见多少有点影响阅读体验。。。所以希望改进优化一下~

![01](https://github.com/gedoor/legado/assets/54703944/482f4e94-3b9e-41ab-9beb-735d7e812160)

![02](https://github.com/gedoor/legado/assets/54703944/c16d1126-2d61-414d-bb05-d156eb930993)

### 期望实现方式 / How to implement

考虑到这种卷名还是有其作用的，因此在不删除目录中卷名的情况下，我想了两种改进方案：
1. 翻页到空白内容的卷名时，**直接跳过**，衔接该卷名后面的章节。
2. 翻页到空白内容的卷名时，用**大号字体显示该卷名**（这个可能需要设计下是竖着写还是横着写？）

不过我更推荐**第一种（直接跳过）**，一方面是该方案实现起来最省力，另一方面就是不需要费脑细胞设计卷名显示方式以及可能出现的问题（比如卷名里有颜文字、卷名太长 等等）。

**Comment by 821938089** [comment]
正常来说是会显示卷名的，这个应该是bug，你发一本能复现的txt来看看

**Comment by XIU2** [comment]
啊？我这边的所有的本地 TXT 都这样。。。

那我就把我前面截图的那个 TXT 小说精简一下（依然可以复现问题）发上来吧。

[大唐风华路测试 作者：山下出水.txt](https://github.com/gedoor/legado/files/12656394/default.txt)

> 只保留了几个卷和章节，不影响测试及复现问题。

![03](https://github.com/gedoor/legado/assets/54703944/482a46de-74d1-4a7e-b4a2-1c53ee92e4a9)

****

补充，刚刚想到可能是我这个 阅读 APP 用的时间太长了，是从以前的老版本一路升级过来的，或许是哪里配置兼容性出现了问题？于是我就去下载了个最新测试共存版的阅读装上后什么都不动试了下，发现可以正常显示卷名（横着的）。

但是我又不想重装阅读 APP，担心导出再导入配置的话，万一还是这样岂不是白折腾了。。。

**Comment by XIU2** [comment]
所有界面相关选项挨个开关试了下，发现是 [信息] - 正文标题 我选了 [隐藏] 导致的。。。

因为我不是很喜欢正文开头有那个大字标题，所以一直都是隐藏的，结果没想到这个选项还会导致 卷名 也隐藏了。。。
是本来就这样设计的？还是以前没注意到这个小问题？。。。

**Comment by 821938089** [comment]
改了，现在卷名不会隐藏了

**Comment by XIU2** [comment]
本来想下来测试版试试的，结果发现测试版的蓝奏云链接要访问密码了。。。奇怪，昨天还没有呢。。。
https://kunfei.lanzoui.com/b0f810h4b

**Comment by 821938089** [comment]
确实，突然有密码了，你可以去Action里下载，是一样的

**Comment by XIU2** [comment]
OK 我装了最新测试共存版试了下，没有问题了，那我关闭啦~
