### ISSUE TITLE
缓存无法清除

### ISSUE THREAD

**Issue by colourjwh** [gedoor/legado#3356]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

3.23.073011版
在书架中缓存过的书,在书架删除后离线缓存中仍然存在无法删除,使用其他设置中的清理缓存也无法清除掉.

### 复现步骤 / How to reproduce

在书架中缓存过的书,在书架删除后离线缓存中仍然存在无法删除,使用其他设置中的清理缓存也无法清除掉.

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

'在书架中缓存过的书,在书架删除后离线缓存中仍然存在无法删除,使用其他设置中的清理缓存也无法清除掉.'

### 阅读版本 / Legado version

3.23.073011

### Android版本 / Android version

Android9

### 机型 / Model

三星note8

**Comment by 821938089** [comment]
发个图看看
