### ISSUE TITLE
正文下一页内容无法获取

### ISSUE THREAD

**Issue by jinshaopu** [gedoor/legado#3358]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=172237815534003445 skey=@crypt_de1a1653_b34c68c70ba981722bbfdee5518259fd mmweb_appid=wx_webfilehelper](https://github.com/gedoor/legado/assets/14891482/c850ef8f-2759-4ccf-b20e-8f4bf92cae35)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=1068758737295617677 skey=@crypt_de1a1653_b34c68c70ba981722bbfdee5518259fd mmweb_appid=wx_webfilehelper](https://github.com/gedoor/legado/assets/14891482/c09cfde4-fbd5-49c2-9901-a1d8711a4d66)
如截图，内容下一页地址已经获取，但是获取不到内容

网站地址 https://m.shuhaige.net
正文规则：class.content@html
正文下一页URL规则：class.pager@text.下一页@href

### 复现步骤 / How to reproduce

网站地址 https://m.shuhaige.net
正文规则：class.content@html
正文下一页URL规则：class.pager@text.下一页@href

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.073011

### Android版本 / Android version

android 11

### 机型 / Model

huawei

**Comment by 821938089** [comment]
估计是替换规则把正文删掉了

**Comment by blackcd318** [comment]
你没有把整个书源传上来,刚好在上一个说书源导不进的json里有你这个网站,他里面正文用的替换规则是 ##喜欢.*请大家收藏(.|\n)*
第一页最后符合这规则,括号里的是后面所有行都替换掉,第二页和之后的页自然被替换掉没有了,去掉就有了,看看你的是不是这样,不是的话把书源传上来,好分析问题
