### ISSUE TITLE
使用webdav同步时，默认是同步到根目录下，请问能添加一个自定义同步目录的功能吗？谢谢

### ISSUE THREAD

**Issue by cheni1994** [gedoor/legado#3373]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

使用webdav同步时，默认是同步到根目录下

### 期望实现方式 / How to implement

请问能添加一个自定义同步目录的功能吗？谢谢

**Comment by a534008561** [comment]
可以设置备份路径啊。

**Comment by cheni1994** [comment]
> 可以设置备份路径啊。

请问怎么设置呢？谢谢！

**Comment by pinoren** [comment]
/是根目录，/mybackup就是你自己指定的。。。你在webdav地址里把他填完整地址不要结尾只是/就可以啦。。。。
