### ISSUE TITLE
允许把书当前使用的书源进行保存绑定，将方便重新整理全局书源后已有的书无需重新搜索

### ISSUE THREAD

**Issue by qmzmdqs** [gedoor/legado#3380]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 背景

某本书使用的书源并没有失效，书源被移除会导致该书要重新匹配。
并且在 `书源管理` 页面无法知道哪些被使用了。

因此，希望，可以将 书 使用的书源规则保存，即每本书都缓存了当时使用的书源规则副本。

### 场景
场景1：
书源列表繁杂等原因，进行整理清空了列表。

场景2：
订阅别人的书源，为了干净简单会将之前的删掉（通过分组），重新导入。该书源不再存在

场景3：
各种情况导致了已使用的书源被删除了

### 目的
- 书源可用时，自然希望稳定，上面出现频率不低的场景会导致经常要重新搜索、查看选择合适的书源。
  这样应该能**省事不少**。
- 书源不可用，需要更新时，原本也需要重新搜索选择。因为不会增加操作步骤。

### 期望实现方式 / How to implement

实现应该是没问题的。

想到两个问题

默认行为：
默认就保存，还是手动操作后才把使用的书源规则保存至该本书

更新问题：
更新订阅后，同名书源规则有更新，如何处理？

**Comment by 821938089** [comment]
加了个导出所有书的书源，在书架管理那里，你要整理书源的话可以先导出一份再搞

**Comment by qmzmdqs** [comment]
扫了眼 commit ，好像不能自定义导出导入。不过也够用了。
