### ISSUE TITLE
求助，正文里有实体编码该怎么处理

### ISSUE THREAD

**Issue by fhwhite** [gedoor/legado#3381]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

今天找书写源，前面都完事了，到正文发现不对劲，正文是这样的

```

<div id="content" class="RBGsectionThree-content">
<p> <i>&#xe7dd;</i><i>&#xe670;</i>世界想<i>&#xe7aa;</i><i>&#xe6b8;</i>入....

```

https://www.03wxw.com/szy/144654/45044909.html

### 期望实现方式 / How to implement

chatgbt回答叫实体编码，但看不太懂，求教大佬们，该怎处理

**Comment by Xwite** [comment]
https://www.coolapk.com/feed/37488417

**Comment by Xwite** [comment]
https://www.coolapk.com/feed/37488417

**Comment by fhwhite** [comment]
> https://www.coolapk.com/feed/37488417

感谢大佬，好容易研究明白了，想着实在不行用最后一个笨办法替换，想看看是不是都用同一字体，真tm醉了，后面章节内容都一样。。。我被骗了，垃圾网站
