### ISSUE TITLE
请问google测试版如何打包APK？

### ISSUE THREAD

**Issue by BlackRosePetals** [gedoor/legado#3386]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

前两天反馈了一下打包遇到的问题，821938089大佬帮忙解答了，我也终于成功打包了阅读apk文件。但是打包的是阅读国内版本，原包和共存版都已经可以成功打包并安装。

本人使用的是之前分享的阅读google测试版，所以继续求助一下官方大佬，如何才能打包pro版本的阅读，我自己对比了一下，安装密钥都是legado.jks，应该是通用的。

### 期望实现方式 / How to implement

无

### 附加信息 / Additions

无

### 效果演示 / Demo

无

**Comment by 821938089** [comment]
已经没有pro版了，你要的话自己改下包名

**Comment by slash09** [comment]
> > 等于说现在就2个版本更新了？共存版和原版有什么区别了？
> 
> 现在只有一个版本，原来国内的普通版本，阅读图标后面没有pro的那个。功能上和pro版本是一样的，自定义欢迎界面也出现了。原包和共存包是可以同时安装的APK文件 ，相当于微信和微信分身。

等于说这两个版本没什么区别啊=.=那为什么又要搞一个共存版出来...之前还有一堆版...什么google版...releaseA版...

**Comment by old-yellow-ox** [comment]
测试版和正式版包名一样，签名不同，只能卸载重新安装吗？@BlackRosePetals

**Comment by slash09** [comment]
> > > > 等于说现在就2个版本更新了？共存版和原版有什么区别了？
> > > 
> > > 
> > > 现在只有一个版本，原来国内的普通版本，阅读图标后面没有pro的那个。功能上和pro版本是一样的，自定义欢迎界面也出现了。原包和共存包是可以同时安装的APK文件，相当于微信和微信分身。
> > 
> > 
> > 等于说这两个版本没什么区别啊=.=那为什么又要搞一个共存版本出来...之前还有多个版本...什么google版本...releaseA版本...
> 
> 国内版本一直只有2个（版本=普通版和ReadRro版本=google版） release和releaseA是原包名压缩和共存包压缩后的名称。

以后不会出google版也就是所谓的PRO版了吧?

**Comment by slash09** [comment]
> 我今天发现了一点不同，我有一个起点书源，在Pro版下打开书籍能加载目录，但是在最近资源的国内版打开，会显示加载目录失败（提示获取目录失败），我却想2个版本应该还是有点不同的地方。否则一个相同的书源，在2个app内就应该是一样的使用，而不是出现不同的情况。

我也发现了...今天刚换...也加载不出来...多开几次又好了...
