### ISSUE TITLE
改进漫画阅读体验

### ISSUE THREAD

**Issue by syumi-1** [gedoor/legado#3387]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

漫画阅读体验不是很好，能不能每页只显示一张图片
现在翻页的时候经常会把图片截断

### 期望实现方式 / How to implement

长按图片显示界面是可以进行缩放的
放大后横向拖动也有回弹效果
能不能用横向拖动触发显示下一张图片

**Comment by 821938089** [comment]
使用滚动翻页动画阅读

**Comment by syumi-1** [comment]
> 使用滚动翻页动画阅读

设置滚动翻页动画也是一整页一整页翻动啊还是会切割图片，除非自动翻页看图片一点一点爬，体验还是挺糟糕的

**Comment by wakening** [comment]
自用无缝滚动翻页配置，建议用共存app单独修改看漫画，这个设置是全局的会影响看小说，我没找到怎么只对当前漫画生效，有人知道可以告诉我一下，省的装两个app，一个看小说一个看漫画。
![IMG_20230929_213259](https://github.com/gedoor/legado/assets/32231663/940ab334-5586-416b-9f2c-b66caaf7d4c2)
![IMG_20230929_212902](https://github.com/gedoor/legado/assets/32231663/b0f48c44-8524-47b7-a1c7-e2bd67397714)

**Comment by farleme** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by syumi-1** [comment]
我明白你们的意思了,靠自动翻页来进行滚动翻页,然后弹出菜单来暂停来观看漫画是吧

这样的话触摸绑定如果能绑定自动翻页就好了,主题我先关了,已经可以将就看了
