### ISSUE TITLE
不要以段落为单位推送朗读。目前段落越长，朗读间隔也越长。阅读长段落时，明显感知到较长的朗读间隔。

### ISSUE THREAD

**Issue by shadwo1** [gedoor/legado#3388]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

能够在较短时间内朗读，不要以段落为单位推送。

目前如果段落太长，朗读时似乎会自动跳过。我测试时一个段落有570字，朗读这段时，只经过了一段时间的间隔，就自动跳到下一段。

朗读软件是 tts-server-android

### 期望实现方式 / How to implement

不要以段落为单位朗读。
可以在保持句子完整的条件下，在一定字数限制内推送。

或者可以强行自动分段，使得段落不要过长。

**Comment by syumi-1** [comment]
替换净化里有个长句拆分规则，可以实现你要的功能

`
[
  {
    "group": "可选",
    "id": 19,
    "isEnabled": true,
    "isRegex": true,
    "name": "#19 拆分🔺长句",
    "order": 19,
    "pattern": "([^\\n“”＂。：；！？—…]{15})，\\b(?!(?<=，\\w{1,3}，)|(?<=，\\w{4}，)\\w{4}，|(?<=，\\w{4,5}，)\\w{5}，|(?<=，\\w{4,6}，)\\w{6}，)(?![^\\n]{1,9}[：])(?=(?:\\b：“|[^\\n“”＂。：；！？—…]){15})(?!(?<=虽[\\w，、]{1,17})[虽但])(\\b|可是?|而且?)(?=\\b[，]|\\B[\\w、]{19}|\\b[\\u4e00-\\u9fcc][，]\\b|\\b(?:\\w[们某等辈主君王侯男女兄弟姐妹娘子儿]?)?虽|\\b非?但[^仍却]|\\b况且|\\b然[而则]|\\b所以|\\b不[仅但料论然]|不多时|\\b难不成|\\b且不?说|殊不知|只不过|\\b要不[然是]|\\b要是|果不其然|不得不说|不[消出]片刻|不知不觉间|\\b[诶欸哦噢喔]|毕竟|常言|除[非却了]|\\b到时候|\\b单[就凭单]|\\b[当随旋]即|对于|\\b顿时|俄顷|反[倒而正之]|仿[佛若]\\w{12}|否则|甫一|\\b故[此而]|\\b果然|更?何况|遑论|[既即][然没有不是无非]|即[\\W便使]|假[如若]|[鉴基]于|较之|届时|尽管|仅仅|经此|据说|看[这那]?样子|可谓是|老实说|没曾想|莫说是|哪怕|\\b那么[你我他她此这个]|[那这]般|难[怪道]|饶是|现?如[果今若非]|若[是非不能]|俗话说|\\b所谓|实际上(?![的却仍也])|孰料|说话间|倘若|特别是|万万没|万一|唯[有独]|无论|相比|\\b幸[亏好而]|言罢|\\b一旦|因[为此而]|有道是|尤其是|与其说|\\b于是|乍一看|再就是|再然后|再比如|\\b再者|自[从打]|纵[然使是观有]|\\b总之|[作身]为|正所谓|至于|直到|之所以|(?:换|\\b\\w\\w)言之|[按照][常道]?理来?说|曾几何时|除此\\w外|古往今来|归根结底|毫无疑问|换句话说|既[是便]?如此|假以时日|久而久之|可想而知|来日方长|迄今为止|若干年[前后]|事到如今|时至今日|以此类推|一直以来|一来二[去回]|一[来则][\\w、]+，二[来则]|(?:一般|简单|通常|严格|准确|具体|总[体的]|如此|现在)(?:[说看]来|[来而地][说讲言])|由此可\\w|与此同时|众所周知|[至自从]始[至自]终|(?:[再又就好]?比如|不[过管]|可是|若|就[好]?[连算像]|哪怕[只仅]?|然后?|甚至于?|尤其)(?:，|[把比跟和将令让是非像以与在]|\\w?[您你我他她它伱妳莪祂俺汝朕卿某谁这那此某诸其众整各自别人鬼者客员家氏士师叔伯侯父母兄弟姐妹姝妪奴最更很怎却])|([不对好呃哈呵嘿嗯啧])\\3{0,2}[，]|([\\u4e00-\\u9fcc]{2})([\\u4e00-\\u9fcc])[\\w、]{1,16}\\b[，](?=\\4[就是被则]|[更另也还再]\\4|\\4\\w?\\5)|(?:\\b\\w{2}(?:年间|[元初末]年|的是|之[中威势])|\\b\\w(?:[夜色光][中里]|[时此这兄了啊哟嘞呢])|\\b[你我他她](?:觉得|知道|发现|的\\w[中里])|\\b[第其][一二三四五]|\\b[一二三四][来则]|\\b[第这那某有前后上下同近于]?[一二三四五六七八九十百千万两半几数]{1,3}(?:[秒分刻点]钟?|[个多]{0,2}(?:世纪|小时|时辰|月份?)|炷香|盏茶|[天日晚周年岁名次])(?:\\b|[之以过]?[前后内里中间际来去初末]|[当昨今明][天日晚]|[上中下]午|[早晚]上|的?时[间刻])|(?:[霎瞬]时|[忽蓦突倏豁恍]然|(?:刹那|顷刻|[转眨][眼瞬]|弹指|须臾|仓促|恍惚|隐约|彼此)\\B)(?:之?间)?|\\b比如说?|\\b不错|不(?:曾想|远处|久之?[前后])|[不没只才]一会儿?|此\\w此\\w|大不了|当[时初下然]了?|到时候?|的确|短时间内|多年[之以][前后来]|而[后你我他她]|刚才|好半天|\\b还[有好]|\\b还是说|\\b很快|\\b后来|或[者许]说?|继而|接下来|紧?接着|\\b结果|见状|\\b今[天日后]|\\b就(?:\\w\\b|这样)|[就恰]?在[此这那]时|\\b也?就是说|据(?:说|[我他她]\\w\\w)|\\b看(?:起?来|上去|得出)|\\b可(?:[恶惜]|以说|\\w\\w是)|例如|\\b另外|\\b论\\w\\w|\\b没(?:错|办法|想到|过?多久)|目前|\\b平日里?|起初|最?起码|其[次实中]|其\\w{1,2}之[中内威势]|\\b恰好|前不久|\\b确实|所幸|随后|事实上|试[问想]|\\b是[夜的以故毕]|首先|说(?:到底|不定|起来|白了|真的|实话)|实?话说|\\b顺便一提|\\b同(?:[时样]的?|一[个件时]\\w)|很?显然|现在|现?如今|想来|[正恰]?相反|\\b心念\\w[转动]|眼下|\\b要不|\\b要知道|\\b也[许罢行]|翌日|依\\w看来?|[一半](?:路上|时间|[眨晃]眼)|[有某]\\w?时候|原来|再[次有者说则]了?|\\b在[你我他她妳]的\\w{2}|怎么样?|(?:[至在]|[直等待]?[到]了?)[这那]?\\w[时刻天]|最[终后]|[这那此](?:\\w|\\w\\w[友兄弟姐妹侠辈法诀谱]|[种个件时期]\\w{1,2})|[这那此现如]\\w(?:的话|[看想说一]来|情[况形]下)|真是的|\\b正[好巧]|\\b只?(?:不过|可惜|\\B是)|至少|终于)[，]|(?:[和与]\\w{2,6}[同样似仿比较]|[就正]?[自从如]\\w{1,6}[起始想虑]|[这就]?[当对于自从等待依据趁以在][\\w、「」]{1,9}(?:而言|[看想]来|来[看想讲说]|方面|为例|所知|身[份上]|[关尽]头|同时|[时年][候刻代]?|[瞬期]间|刹那间?|[这那上下的]一[刻瞬刹秒]|[之以][内外来]|之[见时际中间前后]|[现][前后]|[况助导持态]之?[下]|[中核]心|[眼感印]\\w?[里中])|[更最]\\w{1,9}的就?是)[，])",
    "replacement": "$1。$2",
    "scopeContent": true,
    "scopeTitle": false,
    "timeoutMillisecond": 3000
  },
  {
    "group": "可选",
    "id": 20,
    "isEnabled": false,
    "isRegex": true,
    "name": "#20 拆分🔻段落",
    "order": 20,
    "pattern": "(?:\\b\\w[^\\n]{1,29}?(?:(?<=如下)[：]|(?<![：；][^\\n：；]{0,9})[；](?![^\\n：；]{0,9}[：；])|(?<=[。！？—…])[”](?=(?<=(?:[：]|[说道问答忖][，])“[^\\n“”＂]{2,49}”)|“\\b[^\\n“”＂]{19}|[“]\\b(?:[\\w，、%](?!”)|[。！？—…]|”“){2,69}\\B”\\n)|[】](?=【\\w+：)|(?<=[。！？—…][”]\\b[\\w，、「」]{2,49})[。](?=[\\w“「『《])|(?<=[\\w，、「」]{9})[。！？]{1,2}(?![（【])(?=\\w+[，][“‘]|[“]?[\\w、「」]+[！？—…]|(?<=[\\w、「」]{16}[。！？]{1,2})|[“]?[\\w、「」]{16})|(?<=[\\w，、：「」]{9})[。：；！？—…]{1,2}(?=\\b[\\w，、「」]{1,49}\\b：|【\\w+】：|[第其]?[一二三四五六七八九十][来者则是]?\\b(?<=\\b\\w{2})[，]|[［（〔][一二三四五六七八九十]{1,3}[］）〕]))(?=[\\w“（【「『《][^\\n]{9})|\\b\\w[\\w，、「」《》]{29,69}[：](?=[“＂]?[^\\n：“”＂]{29})|\\b\\w[^\\n]{29,49}?[”」）】]?[。；！？—…]+[”）】]?(?=[\\w“（【「『《][^\\n]{29})(?!(?<=\\b[“][^\\n“”]{1,19}[”]|\\b[（][^\\n（）]{1,19}[）]|\\b[【][^\\n【】]{1,19}[】])\\b|(?<=[—…”])\\w{1,9}[。！？—…]|(?<=[！？])\\w{1,9}[！？]))(?<!“[^\\n”]{1,36}|‘[^\\n’]{1,36}|「[^\\n」]{1,36}|『[^\\n』]{1,36}|[（\\(][^\\n\\)）]{1,36}|【[^\\n】]{1,36}|[\\[［〔][^\\n\\]］〕]{1,36}|[\\{｛][^\\n\\}｝]{1,36}|《[^\\n》]{1,36})(?![^\\n“]{0,36}”|[^\\n‘]{0,36}’|[^\\n「]{0,36}」|[^\\n『]{0,36}』|[^\\n\\(（]{0,36}[）\\)]|[^\\n【]{0,36}】|[^\\n\\[［〔]{0,36}[\\]］〕]|[^\\n\\{｛]{0,36}[\\}｝]|[^\\n《]{0,36}》)",
    "replacement": "$0\n",
    "scopeContent": true,
    "scopeTitle": false,
    "timeoutMillisecond": 3000
  }
]
`

**Comment by shadwo1** [comment]
> 替换净化里有个长句拆分规则，可以实现你要的功能
> 
> `[ { "group": "可选", "id": 19, "isEnabled": true, "isRegex": true, "name": "#19 拆分🔺长句", "order": 19, "pattern": "([^\\n“”＂。：；！？—…]{15})，\\b(?!(?<=，\\w{1,3}，)|(?<=，\\w{4}，)\\w{4}，|(?<=，\\w{4,5}，)\\w{5}，|(?<=，\\w{4,6}，)\\w{6}，)(?![^\\n]{1,9}[：])(?=(?:\\b：“|[^\\n“”＂。：；！？—…]){15})(?!(?<=虽[\\w，、]{1,17})[虽但])(\\b|可是?|而且?)(?=\\b[，]|\\B[\\w、]{19}|\\b[\\u4e00-\\u9fcc][，]\\b|\\b(?:\\w[们某等辈主君王侯男女兄弟姐妹娘子儿]?)?虽|\\b非?但[^仍却]|\\b况且|\\b然[而则]|\\b所以|\\b不[仅但料论然]|不多时|\\b难不成|\\b且不?说|殊不知|只不过|\\b要不[然是]|\\b要是|果不其然|不得不说|不[消出]片刻|不知不觉间|\\b[诶欸哦噢喔]|毕竟|常言|除[非却了]|\\b到时候|\\b单[就凭单]|\\b[当随旋]即|对于|\\b顿时|俄顷|反[倒而正之]|仿[佛若]\\w{12}|否则|甫一|\\b故[此而]|\\b果然|更?何况|遑论|[既即][然没有不是无非]|即[\\W便使]|假[如若]|[鉴基]于|较之|届时|尽管|仅仅|经此|据说|看[这那]?样子|可谓是|老实说|没曾想|莫说是|哪怕|\\b那么[你我他她此这个]|[那这]般|难[怪道]|饶是|现?如[果今若非]|若[是非不能]|俗话说|\\b所谓|实际上(?![的却仍也])|孰料|说话间|倘若|特别是|万万没|万一|唯[有独]|无论|相比|\\b幸[亏好而]|言罢|\\b一旦|因[为此而]|有道是|尤其是|与其说|\\b于是|乍一看|再就是|再然后|再比如|\\b再者|自[从打]|纵[然使是观有]|\\b总之|[作身]为|正所谓|至于|直到|之所以|(?:换|\\b\\w\\w)言之|[按照][常道]?理来?说|曾几何时|除此\\w外|古往今来|归根结底|毫无疑问|换句话说|既[是便]?如此|假以时日|久而久之|可想而知|来日方长|迄今为止|若干年[前后]|事到如今|时至今日|以此类推|一直以来|一来二[去回]|一[来则][\\w、]+，二[来则]|(?:一般|简单|通常|严格|准确|具体|总[体的]|如此|现在)(?:[说看]来|[来而地][说讲言])|由此可\\w|与此同时|众所周知|[至自从]始[至自]终|(?:[再又就好]?比如|不[过管]|可是|若|就[好]?[连算像]|哪怕[只仅]?|然后?|甚至于?|尤其)(?:，|[把比跟和将令让是非像以与在]|\\w?[您你我他她它伱妳莪祂俺汝朕卿某谁这那此某诸其众整各自别人鬼者客员家氏士师叔伯侯父母兄弟姐妹姝妪奴最更很怎却])|([不对好呃哈呵嘿嗯啧])\\3{0,2}[，]|([\\u4e00-\\u9fcc]{2})([\\u4e00-\\u9fcc])[\\w、]{1,16}\\b[，](?=\\4[就是被则]|[更另也还再]\\4|\\4\\w?\\5)|(?:\\b\\w{2}(?:年间|[元初末]年|的是|之[中威势])|\\b\\w(?:[夜色光][中里]|[时此这兄了啊哟嘞呢])|\\b[你我他她](?:觉得|知道|发现|的\\w[中里])|\\b[第其][一二三四五]|\\b[一二三四][来则]|\\b[第这那某有前后上下同近于]?[一二三四五六七八九十百千万两半几数]{1,3}(?:[秒分刻点]钟?|[个多]{0,2}(?:世纪|小时|时辰|月份?)|炷香|盏茶|[天日晚周年岁名次])(?:\\b|[之以过]?[前后内里中间际来去初末]|[当昨今明][天日晚]|[上中下]午|[早晚]上|的?时[间刻])|(?:[霎瞬]时|[忽蓦突倏豁恍]然|(?:刹那|顷刻|[转眨][眼瞬]|弹指|须臾|仓促|恍惚|隐约|彼此)\\B)(?:之?间)?|\\b比如说?|\\b不错|不(?:曾想|远处|久之?[前后])|[不没只才]一会儿?|此\\w此\\w|大不了|当[时初下然]了?|到时候?|的确|短时间内|多年[之以][前后来]|而[后你我他她]|刚才|好半天|\\b还[有好]|\\b还是说|\\b很快|\\b后来|或[者许]说?|继而|接下来|紧?接着|\\b结果|见状|\\b今[天日后]|\\b就(?:\\w\\b|这样)|[就恰]?在[此这那]时|\\b也?就是说|据(?:说|[我他她]\\w\\w)|\\b看(?:起?来|上去|得出)|\\b可(?:[恶惜]|以说|\\w\\w是)|例如|\\b另外|\\b论\\w\\w|\\b没(?:错|办法|想到|过?多久)|目前|\\b平日里?|起初|最?起码|其[次实中]|其\\w{1,2}之[中内威势]|\\b恰好|前不久|\\b确实|所幸|随后|事实上|试[问想]|\\b是[夜的以故毕]|首先|说(?:到底|不定|起来|白了|真的|实话)|实?话说|\\b顺便一提|\\b同(?:[时样]的?|一[个件时]\\w)|很?显然|现在|现?如今|想来|[正恰]?相反|\\b心念\\w[转动]|眼下|\\b要不|\\b要知道|\\b也[许罢行]|翌日|依\\w看来?|[一半](?:路上|时间|[眨晃]眼)|[有某]\\w?时候|原来|再[次有者说则]了?|\\b在[你我他她妳]的\\w{2}|怎么样?|(?:[至在]|[直等待]?[到]了?)[这那]?\\w[时刻天]|最[终后]|[这那此](?:\\w|\\w\\w[友兄弟姐妹侠辈法诀谱]|[种个件时期]\\w{1,2})|[这那此现如]\\w(?:的话|[看想说一]来|情[况形]下)|真是的|\\b正[好巧]|\\b只?(?:不过|可惜|\\B是)|至少|终于)[，]|(?:[和与]\\w{2,6}[同样似仿比较]|[就正]?[自从如]\\w{1,6}[起始想虑]|[这就]?[当对于自从等待依据趁以在][\\w、「」]{1,9}(?:而言|[看想]来|来[看想讲说]|方面|为例|所知|身[份上]|[关尽]头|同时|[时年][候刻代]?|[瞬期]间|刹那间?|[这那上下的]一[刻瞬刹秒]|[之以][内外来]|之[见时际中间前后]|[现][前后]|[况助导持态]之?[下]|[中核]心|[眼感印]\\w?[里中])|[更最]\\w{1,9}的就?是)[，])", "replacement": "$1。$2", "scopeContent": true, "scopeTitle": false, "timeoutMillisecond": 3000 }, { "group": "可选", "id": 20, "isEnabled": false, "isRegex": true, "name": "#20 拆分🔻段落", "order": 20, "pattern": "(?:\\b\\w[^\\n]{1,29}?(?:(?<=如下)[：]|(?<![：；][^\\n：；]{0,9})[；](?![^\\n：；]{0,9}[：；])|(?<=[。！？—…])[”](?=(?<=(?:[：]|[说道问答忖][，])“[^\\n“”＂]{2,49}”)|“\\b[^\\n“”＂]{19}|[“]\\b(?:[\\w，、%](?!”)|[。！？—…]|”“){2,69}\\B”\\n)|[】](?=【\\w+：)|(?<=[。！？—…][”]\\b[\\w，、「」]{2,49})[。](?=[\\w“「『《])|(?<=[\\w，、「」]{9})[。！？]{1,2}(?![（【])(?=\\w+[，][“‘]|[“]?[\\w、「」]+[！？—…]|(?<=[\\w、「」]{16}[。！？]{1,2})|[“]?[\\w、「」]{16})|(?<=[\\w，、：「」]{9})[。：；！？—…]{1,2}(?=\\b[\\w，、「」]{1,49}\\b：|【\\w+】：|[第其]?[一二三四五六七八九十][来者则是]?\\b(?<=\\b\\w{2})[，]|[［（〔][一二三四五六七八九十]{1,3}[］）〕]))(?=[\\w“（【「『《][^\\n]{9})|\\b\\w[\\w，、「」《》]{29,69}[：](?=[“＂]?[^\\n：“”＂]{29})|\\b\\w[^\\n]{29,49}?[”」）】]?[。；！？—…]+[”）】]?(?=[\\w“（【「『《][^\\n]{29})(?!(?<=\\b[“][^\\n“”]{1,19}[”]|\\b[（][^\\n（）]{1,19}[）]|\\b[【][^\\n【】]{1,19}[】])\\b|(?<=[—…”])\\w{1,9}[。！？—…]|(?<=[！？])\\w{1,9}[！？]))(?<!“[^\\n”]{1,36}|‘[^\\n’]{1,36}|「[^\\n」]{1,36}|『[^\\n』]{1,36}|[（\\(][^\\n\\)）]{1,36}|【[^\\n】]{1,36}|[\\[［〔][^\\n\\]］〕]{1,36}|[\\{｛][^\\n\\}｝]{1,36}|《[^\\n》]{1,36})(?![^\\n“]{0,36}”|[^\\n‘]{0,36}’|[^\\n「]{0,36}」|[^\\n『]{0,36}』|[^\\n\\(（]{0,36}[）\\)]|[^\\n【]{0,36}】|[^\\n\\[［〔]{0,36}[\\]］〕]|[^\\n\\{｛]{0,36}[\\}｝]|[^\\n《]{0,36}》)", "replacement": "$0\n", "scopeContent": true, "scopeTitle": false, "timeoutMillisecond": 3000 } ]`

增加拆分段落规则后，确实可以了。
Thank you.
