### ISSUE TITLE
能否增加单击或双击图片放大的功能？

### ISSUE THREAD

**Issue by SoCyo** [gedoor/legado#3391]
### 确认 / Assignments

- [ ] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

看轻小说经常需要放大图片，现有的 长按图片弹出选项 -> 点击 显示 -> 放大图片 的步骤很繁琐。

### 期望实现方式 / How to implement

类似其他阅读器，单击或双击即可进入图片放大页面。或增加一个选项，长按图片直接进入图片放大页面，而不是需要选择〝显示〞才能进入。

**Comment by DancingDuck** [comment]
readactivity->onImageLongPress
