### ISSUE TITLE
替换净化忽略空白符

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3397]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

我发现阅读的替换净化其实是能写注释的，但写了注释排版就会很奇怪，可不可以再加个开关，忽略空白符，这样能好看些，就算不写注释，单个规则换行也能有条理些
![Screenshot_2023-10-02-20-27-49-869_io legado app release](https://github.com/gedoor/legado/assets/106790230/df0960ee-22a6-4729-be63-2fa1451eb4ec)
![Screenshot_2023-10-02-20-29-28-349_com tencent mm](https://github.com/gedoor/legado/assets/106790230/0d61a203-8cf9-4267-ab82-8d61ad27d7d2)

### 期望实现方式 / How to implement

加个开关

**Comment by 821938089** [comment]
可以在正则中添加`(?x)`开启此功能
