### ISSUE TITLE
加入文件至书架错误

### ISSUE THREAD

**Issue by KarsusNeko** [gedoor/legado#3398]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

## 背景  
* 设备：一加6
* 系统：Pixel Experience Plus 13
* 安卓版本：13
* App版本：3.23.072018
* 问题简述：导入本地epub至书架时失败  
## 问题描述  
从本地导入epub时，导入《怪诞故事集》后《糜骨之壤》自动从书架移除，导入《糜骨之壤》后《怪诞故事集》自动从书架移除。即两本书无法同时被导入书架。但在发现此问题前后，导入其他书籍均正常。  
在最新测试版中亦能复现该问题。

[!(复现截屏)](https://github.com/gedoor/legado/assets/4273513/24e72d32-ca96-45ff-9c1f-044c2c802c03)

附件：
无法同时导入的《怪诞故事集》和《糜骨之壤》样本[点击这里](https://github.com/gedoor/legado/files/12783486/samples.zip)下载

### 复现步骤 / How to reproduce

1. 下载并安装最新测试版app；
2. 下载“问题描述”中的附件至手机；
3. 打开app，点击右上角菜单按钮，在弹出列表中选择导入书籍（Import books）；
4. 在弹出界面中，选择并导入《怪诞故事集》和《糜骨之壤》，仅能导入其中一本，重新点击导入另一本后，前一本被导入的被移出书架。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.072018

### Android版本 / Android version

Android 13

### 机型 / Model

OnePlus 6

**Comment by adhu2018** [comment]
这两个的content.opf中dc:title都是奥尔加·托卡尔丘克，这是作者，而这里正确的应该是书名，属于epub制作的问题，跟阅读没啥关系

**Comment by KarsusNeko** [comment]
能否改成以MD5来验证？因为可能有同一本书不同版本的情况。

**Comment by Goojoe** [comment]
我也有这个问题，无法导入epub，本地云端无法导入，本地导入：
单独选中epub无法加入书架。将其他.txt文件一起选可以加入书架，但是无法加载
WebDav远程书籍导入：
导入失败，导入成功也是无法加载

阅读版本: beta legado_app_3.23.10062156_原包名.apk

Android版本 / Android version
Android 13

机型 / Model
Motorola Edge X30

相关文件:

这个epub是使用阅读缓存导出制作的

**Comment by 821938089** [comment]
@Goojoe 最新版修好了，建议重新导出一下epub，这些epub数据有些问题
