### ISSUE TITLE
打开本地txt后，文件总被复制一遍

### ISSUE THREAD

**Issue by KleinAsyourwish** [gedoor/legado#3399]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

从内置文件管理器跳转打开txt后，每次都把文件复制到别处

### 复现步骤 / How to reproduce

本地txt不需要被复制！管理乱七八糟，文件重复又累赘

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23

### Android版本 / Android version

Android 12

### 机型 / Model

Remi k20

**Comment by 821938089** [comment]
从添加本地导入不会复制一遍
