### ISSUE TITLE
日文五十音注音会和正文挤在一行

### ISSUE THREAD

**Issue by beaduo** [gedoor/legado#3400]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

需要优化下对日文的支持，像划线的这种字上面注音的，阅读不能把音标在上方，目前找到的阅读器只有多看、捧读和搜书大师支持
![2f20d47a3bae98a06a0bb5350175fda7](https://github.com/gedoor/legado/assets/147153103/5ea3b615-9f51-4e1f-8d73-bb48473396cb)
![eaa6abe8172762d5def5e07a825e0753](https://github.com/gedoor/legado/assets/147153103/cb367978-f95c-4799-8ac9-8e0f2ab132b2)

### 复现步骤 / How to reproduce

[雪国 (角川文庫) (川端 康成) (Z-Library).epub](https://wwny.lanzouj.com/i4w2l1axktmb) 
打开提供的雪国日文版，用阅读打开翻到第四页就可以发现

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

无

### 阅读版本 / Legado version

3.23.100613

### Android版本 / Android version

Android12

### 机型 / Model

Redmi K30 5G

**Comment by 821938089** [comment]
不支持特殊样式，换别的app看

**Comment by beaduo** [comment]
> 不支持特殊样式，换别的app看

除了搜书大师，别的APP在选中文字后，展不开欧路词典的查词选项😂，我找了几乎所有的阅读软件，满足日文适配，欧路词典查词这两样的只有搜书大师，如果再加一个云同步和纯净无广告，那就没软件了。能不能再考虑下对日文的适配
