### ISSUE TITLE
希望导出到本地也能保留在线更新小说

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3402]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在线与本地都有各自的缺点，在线可以更新，虽然可以缓存章节，但是书一多缓存了一堆零碎的小文件，我阅读保留了好几年的缓存数据，有好几万个小文件，最近pro版不更新打算换到标准版，备份起来读写真的很慢，而导出成本地小说又会失去在线检测更新

我收藏的有些书又下架了，一时间哪些要导出哪些可以在线阅读都分不清，比较乱
如果缓存章节能直接读取本地小说的数据就好了，这样备份数据与在线更新能兼容到一起

### 期望实现方式 / How to implement

 导出小说之后阅读的章节读取导出后的数据，如果格式不兼容可以使用zip格式直接把缓存文件都打包成一个文件，这样可以完全兼容原本的在线缓存格式

**Comment by 821938089** [comment]
你装完标准版恢复备份后把pro版的缓存目录复制到标准版里就可以了

**Comment by zousizhe** [comment]
> 你装完标准版恢复备份后把pro版的缓存目录复制到标准版里就可以了

近10万个文件，复制了一上午都还没好，听到群里有人说，data里改文件夹名就行，结果文件全丢失了

**Comment by Goojoe** [comment]
对，其实我也希望有这种功能。用webdav同步缓存，这样已缓存的可以同步到其他设备，离线下载和在线缓存互不冲突
