### ISSUE TITLE
有没有支持x86安卓6.0的旧版本可以下载

### ISSUE THREAD

**Issue by Ludummy** [gedoor/legado#3404]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

我的平板一个iPad，一个小米平板2(x86 Android 6.0)，手机是iOS，刚好完美避开了开源阅读App所有支持的设备...

### 期望实现方式 / How to implement

希望增加x86 Android 6.0适配或者能给个iOS版本吗，我已经越狱了可以直接安装ipa。

**Comment by 821938089** [comment]
最新测试版应该可以用
