### ISSUE TITLE
横屏分页阅读的新翻页方式

### ISSUE THREAD

**Issue by Wei-Jian-Xian** [gedoor/legado#3410]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在横屏分页阅读时仿真模式翻译，希望能从左到右翻开。也就是把右边半页翻到左边半页的上面。

### 期望实现方式 / How to implement

类似微信读书的那样。![Screenshot_2023-10-09-18-12-58-390_com.tencent.weread](https://picdm.sunbangyan.cn/2023/10/09/tzn39e.jpg)
https://picdm.sunbangyan.cn/2023/10/09/tzn39e.jpg

### 效果演示 / Demo

![Screenshot_2023-10-09-18-12-58-390_com.tencent.weread](https://picdm.sunbangyan.cn/2023/10/09/tzn39e.jpg)

**Comment by M17764017422** [comment]
双页模式下的仿真翻页动画，应该以中缝为轴心，在左右两页之间翻动。
