### ISSUE TITLE
默认封面规则失效

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3415]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

正式版没这bug，测试版默认封面规则失效了，进详情页出来不搜封面了

### 复现步骤 / How to reproduce

最新测试版，导一本本地TXT文件，没有封面，然后进详情页出来，封面还是不出来，设置里开了默认封面规则的，同样操作，正式版封面就会自己跳出来
![Screenshot_2023-10-13-09-47-08-535_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/681e23d4-aa4d-49ca-8b15-974fe422ac2c)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.101221

### Android版本 / Android version

android 13

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
已修复，已经在书架的书需要重新加书架或编辑书籍信息删掉封面地址
