### ISSUE TITLE
主题模式

### ISSUE THREAD

**Issue by yudi126** [gedoor/legado#342]
8月份更新的新版，主题模式，墨水屏，从暗处到亮处，不会自动增加亮度，谢谢

**Comment by gedoor** [comment]
你可能把自动亮度关了

**Comment by yudi126** [comment]
自动亮度是开着的，关了阅读的窗口，就会自动调节亮度。在阅读的窗口就不会自动调节。谢谢

**Comment by gedoor** [comment]
我说的是阅读的自动亮度

**Comment by yudi126** [comment]
仔细看了一下，是把侧边亮度自动关了，谢谢解答。
