### ISSUE TITLE
听书功能希望增加默认定时

### ISSUE THREAD

**Issue by jxjxjhjh** [gedoor/legado#3421]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

每次听书定时都要手动设定时间，非常麻烦，希望增加默认时长功能，这样就不需要每次都手动选择定时功能了。

### 期望实现方式 / How to implement

最好的做法其实是默认设定听几章后自动关闭。
在设置中设定【听书章节】为X章后，每次打开听书，都会在X后自动停止。此时播放界面的定时功能图标（闹钟）上有个识别图案，如果点一下，则取消自动停止，变成不自动停止。

**Comment by 821938089** [comment]
点击左边时钟可以记忆定时设置，点击右边时间可以快速设置定时

**Comment by jxjxjhjh** [comment]
> 点击左边时钟可以记忆定时设置，点击右边时间可以快速设置定时

并不能

**Comment by blackcd318** [comment]
> > 点击左边时钟可以记忆定时设置，点击右边时间可以快速设置定时
> 
> 并不能

你没试吧,或者版本太老了?你调好播放时长后,再点击朗读后在上一章下面朗读语速上面那个钟表图标,点了就会设置默认定时时间

**Comment by jxjxjhjh** [comment]
> > > 点击左边时钟可以记忆定时设置，点击右边时间可以快速设置定时
> > 
> > 
> > 并不能
> 
> 你没试吧,或者版本太老了?你调好播放时长后,再点击朗读后在上一章下面朗读语速上面那个钟表图标,点了就会设置默认定时时间

你说的是文字小说朗读，我说的是音频听书。
