### ISSUE TITLE
导入书源，提示报错

### ISSUE THREAD

**Issue by cMing1997** [gedoor/legado#3423]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在书源管理中从网络地址中导入 书源 提示Java 报错

### 复现步骤 / How to reproduce

1. 初次安装软件
2. 进入我的书源管理
3. 选择从网络地址导入，地址为：https://jt12.de/SYV2_4/2023/10/08/19/53/59/16967660396522985702e8c.json
4. 页面弹框报错
5. 
![微信图片_20231015222523](https://github.com/gedoor/legado/assets/40878104/776539b9-b788-4017-84c9-f0d6e0d91b2d)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

报错信息：
``` 
ImportError:java.lang.IllegalStateException:
Expected BEGIN_OBJECT but was STRING at line
1 column 1 path $
```

### 阅读版本 / Legado version

32.23.073011

### Android版本 / Android version

Android 12

### 机型 / Model

Redmi Note 11T Pro

**Comment by blackcd318** [comment]
我试了你用的地址,可以啊,能出来源列表,你再试试或者换个源试试
我是用的二维码导入,用firefox生成了网址的二维码,legado扫描

**Comment by cMing1997** [comment]
> 我试了你用的地址,可以啊,能出来源列表,你再试试或者换个源试试 我是用的二维码导入,用firefox生成了网址的二维码,legado扫描

今天重新试了一下，确实是可以了。之前的地址在浏览器上是可以获取到内容的，但是不确定是软件解析的问题，还是对应书源的服务有问题
