### ISSUE TITLE
替换净化规则里的中文括号问题

### ISSUE THREAD

**Issue by skybbk98** [gedoor/legado#3424]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

替换净化规则里如果包含中文空格，导出后就无法再被导入

### 复现步骤 / How to reproduce

  我做了一个简单的替换规则。把标题中的中文空格“　”替换成英文空格“ ”
测试生效了，可以正常使用，但是导出后别人和我都无法再导入
  导入会提示报错：
ImportError:格式不对

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.101313

### Android版本 / Android version

Android 13

### 机型 / Model

redmi note 12 turbo

**Comment by skybbk98** [comment]
标题写错了，不是中文括号是中文空格

**Comment by 821938089** [comment]
已修复

**Comment by skybbk98** [comment]
已解决
