### ISSUE TITLE
最新几个测试版搜索都无法翻页

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3426]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

单个网站搜索无法翻页

### 复现步骤 / How to reproduce

选中单个书源搜索拉到底全都没法翻页

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.101616

### Android版本 / Android version

Android

### 机型 / Model

Redmi K60pro

**Comment by 821938089** [comment]
已修复
