### ISSUE TITLE
请问朗读功能能否按页录音，然后段得到焦点？

### ISSUE THREAD

**Issue by Nicolas-Gong** [gedoor/legado#3435]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1、我发现按段来，我搭建的第三方的会在听了很久后就出现了限流，比如录制响应缓慢，时不时还报错，大概连续听个10来个小时就会出现，我怀疑是单个IP频繁的录制导致，我不知道怎么修改才能让他得到按页录制，以减少录制次数。
2、我录制的最大速度为2倍上限，感觉还是慢，我一般听小说都喜欢在3倍速左右。

### 期望实现方式 / How to implement

1、让他得到按页录制，以减少录制次数。
2、能否在播放上面再加速，因为录制的上限只支持2倍，可以1倍录制，3倍播放这样的操作

### 附加信息 / Additions

本人非安卓/java开发，只能大致能看懂点代码，但是代码注释偏少，很多地方一知半解，求大佬指点下

**Comment by 821938089** [comment]
你可以使用替换净化将段落合并再朗读

**Comment by Nicolas-Gong** [comment]
> 你可以使用替换净化将段落合并再朗读

我想通过代码修改，应该是`HttpReadAloudService`类里面的`downloadAndPlayAudios`方法，循环的时候我不知道有没有什么变量知道这一页，下一页的内容节点在哪儿

**Comment by 821938089** [comment]
每页内容可以从textChapter中获取

**Comment by Nicolas-Gong** [comment]
> 每页内容可以从textChapter中获取

大佬，我找到方法获取到了
```
textChapter?.pages?.forEachIndexed { index, textPage ->
          if (index >= pageIndex) {
              val text = textPage.text
         }
}
```
这样就能拿到了，但是还存在个问题，就是音频的焦点，怎么修改呢？也是翻页的问题

**Comment by 821938089** [comment]
用upTtsProgress方法更新
