### ISSUE TITLE
关于内置浏览器无法手动通过cloudflare验证

### ISSUE THREAD

**Issue by luckyzluz** [gedoor/legado#3436]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

可不可以更换一下内置浏览器  什么的

### 期望实现方式 / How to implement

这在浏览器上也遇到过，也是无限循环，当时是用的via，雨见，X，都是一个样。之后换了Chrome内核之后秒过，弹出验证直接帮你过了。一直是搞不懂问题在哪

### 附加信息 / Additions

如果只是开启主页防护，我可以直接  设置访问详情页，但是站长开启了全站防护。。。。

### 效果演示 / Demo

是否可以调用 外部浏览器

**Comment by 821938089** [comment]
需要正确的UA才能过
