### ISSUE TITLE
订阅功能也用全局用户代理信息（userAgent）吗?

### ISSUE THREAD

**Issue by old-yellow-ox** [gedoor/legado#3437]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

页面一直被判断为pc，查看了userAgent信息发现用的是设置里的用户代理信息。订阅和书源的能分开设置吗？或者我怎么能改变这个信息

### 期望实现方式 / How to implement

可以修改该信息。

**Comment by 821938089** [comment]
在请求头那里填UA
