### ISSUE TITLE
能否增加取词模式功能

### ISSUE THREAD

**Issue by WuYang09661** [gedoor/legado#3441]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在取词翻译的时候必须要长按 进入二级菜单 再选择词典翻译 非常的麻烦 能否增加长按直接翻译的取词功能呢 不用再进去子菜单选择词典

### 期望实现方式 / How to implement

无

### 附加信息 / Additions

无

### 效果演示 / Demo

无

**Comment by 821938089** [comment]
阅读设置里可以展开文本选择菜单

**Comment by WuYang09661** [comment]
hmmm我的意思就是 比如在使用阅读app来阅读外文文献，想要高频率使用自带词典的话，每次都要长按 点击展开 点击自带词典 这是比较麻烦的 能否像静读天下那样 提供选择 比如移动词典的优先级 用户自主选择触发词典的方式 比如长按或者单机后直接触发发件人: ***@***.*** ***@***.***> 代表 Horis ***@***.***>发送时间: 星期一, 十月 23, 2023 9:43:36 上午收件人: legado ***@***.***>抄送: 780391760 ***@***.***>; author ***@***.***>主题: Re: [gedoor/legado] 能否增加取词模式功能 (Issue #3441)
阅读设置里可以展开文本选择菜单
