### ISSUE TITLE
已经分组的书籍无法再设置成网络未分组（我的书架）

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#3444]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

已经分组的书籍无法再设置成网络未分组（我的书架）

### 复现步骤 / How to reproduce

![Screenshot_2023-10-24-02-41-34-688_io legado app releaseA-edit](https://github.com/gedoor/legado/assets/70464410/c7154ec8-55fa-4d32-9eeb-e23c7c825a44)
![Screenshot_2023-10-24-02-41-48-161_io legado app releaseA-edit](https://github.com/gedoor/legado/assets/70464410/e5077ddd-c59b-469a-94d6-f357495d09ef)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.102313

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
这个分组是app自带的，你无法自行将书设置到这个分组，你要自己建一个分组把书都放到里面

**Comment by skybbk98** [comment]
那可以给书籍移除分组么，这样也就等同于放进我的书架分组

**Comment by 821938089** [comment]
可以
