### ISSUE TITLE
希望书架向下滑动能像书源管理一样

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#3448]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望书架向下滑动多了能像书源管理侧边条一样能快速滑动。书架书多了往下滑特别不方便 

### 期望实现方式 / How to implement

就希望多次下滑后侧边也能出快速滑动滚动条

**Comment by 821938089** [comment]
最新测试版书架布局里面可以设置显示快速滚动条

**Comment by ladia** [comment]
> Collaborator

感谢大佬
