### ISSUE TITLE
共存版无法升级

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#3450]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

从共存版3.23.102313升级到3.23.102623时，提示无法降级安装

### 复现步骤 / How to reproduce

![Screenshot_2023-10-28-17-02-29-718_com miui packageinstaller-edit](https://github.com/gedoor/legado/assets/70464410/8665bba0-20f8-4642-92e6-3490451d5861)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.102313

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 Turbo

**Comment by adhu2018** [comment]
你原来安装的版本打包流程跟阅读官方的不一致，或经过其他修改，所以内部版本号比官方的高，不属于阅读本身的问题

**Comment by skybbk1998** [comment]
> 你原来安装的版本打包流程跟阅读官方的不一致，或经过其他修改，所以内部版本号比官方的高，不属于阅读本身的问题

我从GitHub Action里下载的，不存在其它修改

**Comment by adhu2018** [comment]
> > 你原来安装的版本打包流程跟阅读官方的不一致，或经过其他修改，所以内部版本号比官方的高，不属于阅读本身的问题
> 
> 我从GitHub Action里下载的，不存在其它修改

阅读正常构建的跟提交次数有关，这个机制决定了他不可能存在后构建的版本低于先构建版本的这个问题

**Comment by adhu2018** [comment]
在自动构建的版本里并没有3.23.102313这一个版本，请你检查安装包来源

**Comment by zousizhe** [comment]
喵公子的版本，签名是一样，但是差了几个版本序号，一个月之后再试，大概版本就追回来了

**Comment by skybbk1998** [comment]
好的明白了，谢谢
