### ISSUE TITLE
最新测试版，只要手动选择了小说书架分组，详情页查看目录就空白

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3451]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

从搜索结果进入小说详情，未加入书架时可以正常查看目录，直接选择加入书架也正常，但是只要是手动选择了书架分组，然后查看目录就一定会空白，在进入正文查看目录无问题，下次从书架进入详情也无问题

### 复现步骤 / How to reproduce

从搜索结果随便选择一本书进入详情页，手动选择书架分组，然后目录就会空白

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.102211

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K60 pro

**Comment by 821938089** [comment]
已修复
