### ISSUE TITLE
话说盼星星盼月亮终于等来更新，为什么书籍列表滚动条没有加进去。。。伤心

### ISSUE THREAD

**Issue by pinoren** [gedoor/legado#3459]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

之前请求的书籍列表页面的滚动条可以手指拖动的功能，您在测试版实现了，隔三差五刷新一下看有没有发新版，终于等来了，兴致勃勃的一拖动，还是不能拖动。。。伤心欲绝啊。。。

### 期望实现方式 / How to implement

可以拖动的书籍列表页面滚动条。。。

**Comment by 821938089** [comment]
加了个开关设置，在书架布局里面

**Comment by pinoren** [comment]
找到啦，真的太感谢了！！୧꒰•̀ᴗ•́꒱୨
