### ISSUE TITLE
在滚动模式下自动阅读时，3.23.110115 版本后无法手动向上翻了（会被锁定到某一页）

### ISSUE THREAD

**Issue by XIU2** [gedoor/legado#3467]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

3.23.110115 版本时出现了该问题（最新 3.23.110211 版本也依然存在该问题），

> 最新编译出来的测试版 `legado_app_3.23.11031153_共存.apk` 也依然存在该问题

即在滚动模式下自动阅读时，无法手动向上翻了（会被锁定到某一页顶部，但并不是该章节的第一页）

3.23.073011 版本不存在该问题。

我也不确定，这是新出现的 BUG 还是故意这样限制的？

### 复现步骤 / How to reproduce

设置为滚动阅读模式，然后开启自动阅读，手动向上翻，就会发现翻到顶了。
有时候会多翻两页才到顶，有时候会很快到顶，暂没有找到规律，但可以确定不是固定的限制在当前章节的第一页。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 7

### 机型 / Model

Meizu Note6

**Comment by 821938089** [comment]
试试最新测试版

**Comment by XIU2** [comment]
试了下最新测试版（`3.23.11031616`），该问题已修复！好快呀~
