### ISSUE TITLE
查看目录按钮会自动添加到书架

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#3468]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在任意书源章节目录规则为空，或者无效的时候。该书源搜出来的书，点进去详情页，再点击查看目录，返回后书籍会被自动添加到书架

### 复现步骤 / How to reproduce

- 把随便一个书源的章节目录规则删掉，用这个书源搜书，随便一本书点进去详情页，会提示“目录列表为空”。此时再点击查看目录按钮，仍然提示“目录列表为空”。之后返回到搜索结果，会看到刚才那本书已经被自动添加到书架，再点进该书籍详情页，左下角的“加入书架”已经变成了“删除书籍”。
 - 而在目录规则正确的时候，详情页里点击查看目录，之后无论是加载正文再返回还是直接返回都不会自动添加到书架。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110213

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 Turbo

**Comment by skybbk1998** [comment]
另外还有个地方就是，调试书源的时候，有些空的规则显示的就是空，而有些显示为null，这个能否让它都显示为空，强迫症看着难受

**Comment by 821938089** [comment]
已修复

**Comment by skybbk1998** [comment]
> 已修复

非常感谢！
