### ISSUE TITLE
文件源无法正确识别压缩包内的文件

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#3469]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

网站是用的rar压缩包，里面是TXT文件，书源能正常读取到下载链接。但无法识别压缩包内文件

### 复现步骤 / How to reproduce

https://shuyuan.mgz6.cc/shuyuan/59817b2b0154787f7913cef8a2c8ea84.json  
这是示例书源，示例书籍《超级系统》
![Screenshot_2023-11-04-02-17-32-888_io legado app release-edit](https://github.com/gedoor/legado/assets/70464410/d72c1fec-75d6-4807-92e7-4c0f0dca3d84)
![Screenshot_2023-11-04-02-17-55-656_io legado app release-edit](https://github.com/gedoor/legado/assets/70464410/754625f5-3b82-4377-adf2-c97137a0a980)
![Screenshot_2023-11-04-02-18-33-890_com mixplorer-edit](https://github.com/gedoor/legado/assets/70464410/68bb41b4-bfb5-4a4e-90a8-cc670f27088e)
![Screenshot_2023-11-04-02-19-22-941_com mixplorer-edit](https://github.com/gedoor/legado/assets/70464410/37439523-6b3c-4745-8959-f810ed762c40)
TXT文件采用的是gbk编码

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110323

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
已修复

**Comment by skybbk1998** [comment]
感谢🙏
