### ISSUE TITLE
关于网络倒入

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#3480]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

不知道为什么用api解析蓝奏云直链网络导入报错
![S31108-11520050_io legado app release](https://github.com/gedoor/legado/assets/73186747/2d5d0814-e8f2-4c30-af89-4886a61fb03b)

### 复现步骤 / How to reproduce

链接是https://tenapi.cn/v2/lanzou?url=https://www.lanzout.com/iNBvr1dhflfi&type=down 
看httpcanary里应该是能解析出直链的
![S31108-11551698_com guoshi httpcanary](https://github.com/gedoor/legado/assets/73186747/f9489896-906d-49f9-9b73-ec2c7f4aa0ca) 

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.11071210

### Android版本 / Android version

android13

### 机型 / Model

小米13

**Comment by 821938089** [comment]
内容不是书源数据
