### ISSUE TITLE
希望增加 筛选小说书源时，能自动屏蔽字数小于一定值的书源 功能

### ISSUE THREAD

**Issue by baiye125** [gedoor/legado#3484]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

包括内容为空等等。
还希望增加 能在筛选小说书源时，可以提前设置文字，如果在书源中匹配到，就屏蔽这个书源。减少查看的次数

### 期望实现方式 / How to implement

无

### 附加信息 / Additions

无

### 效果演示 / Demo

无

**Comment by 821938089** [comment]
如果你用的是最新版可以用替换净化把内容替换掉
