### ISSUE TITLE
优化批量更新

### ISSUE THREAD

**Issue by smarttommyau** [gedoor/legado#3492]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1. 增加一个选项，在批量更新是只是在更新进度为最新章节的书籍，建议默认开启。

### 期望实现方式 / How to implement

在选项中增加一个新选项。
在批量更新时，确定书籍进度为最新章节才进行更新。

### 附加信息 / Additions

这样能减低对网站的请求量，防止网站ip ban。同时，也能减低网站管理员对本app的反感。

**Comment by 821938089** [comment]
获取最新章节也要请求，刷新目录没有分页的话一般只用请求一次就够了，有影响的是搜索和章节缓存

**Comment by smarttommyau** [comment]
> 获取最新章节也要请求，刷新目录没有分页的话一般只用请求一次就够了，有影响的是搜索和章节缓存

不对啊，书架有过百本书就很多了吧。然后最新章节是指本地进度，不用请求。就是如果好有未读章节就不用请求伺服器。
