### ISSUE TITLE
Web服务增加书源管理功能（主要是网络导入）

### ISSUE THREAD

**Issue by bzkmsjy** [gedoor/legado#3494]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在电纸书上使用阅读，导入和更新书源非常困难，我的墨案电纸书系统还不允许浏览器跳转阅读，得手动复制粘贴，因为电纸书本身性能很差，在软件之间切换来去就更加折磨了，我发现Web服务个功能拿来传书不错，但是书源功能主要是用于写源，没有类似APP内的“书源管理”那样更加适合小白的功能界面，如果能至少把网络导入这个功能做进去，就能直接通过手机浏览器推送书源链接到电纸书里，对电纸书用户会很方便。

### 期望实现方式 / How to implement

理想情况是Web管理中增加APP书源管理的完整功能和界面（导入、删除、启用禁用等）

简单的方案是在Web管理——书源——源列表这一项里加入网络地址导入，目前好像只有本地json导入，不知道导入后是不是按一下“推送源”就行了？小白不是很懂这个界面

**Comment by a810439322** [comment]
我刚才研究了一会，有点心得分享给你
1、手机先开web，源列表拉取+导出，然后电纸书开web，源列表打开刚才导出的，再推送
2、开启webDav同步，用坚果云，可以多端同步配置和进度
