### ISSUE TITLE
移除重复标题功能无法工作

### ISSUE THREAD

**Issue by mayloglog** [gedoor/legado#3498]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

移除重复标题功能无法工作，软件找不到重复的标题。
故障文本及截图可在此下载：https://pan.baidu.com/s/1ULChDhH6cGno2V4R-GofXQ?pwd=1111 提取码: 1111

### 复现步骤 / How to reproduce

下载故障文本，在软件中打开，点击移除重复标题，可以观察到软件找不到重复标题的错误提示

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.079011

### Android版本 / Android version

Android 9

### 机型 / Model

Nokia X6

**Comment by 821938089** [comment]
移除重复标题是针对正文的，你这是txt有问题，里面的标题重复了，你改标题规则应该就可以了，参考双标题规则即可

**Comment by mayloglog** [comment]
> 移除重复标题是针对正文的，你这是txt有问题，里面的标题重复了，你改标题规则应该就可以了，参考双标题规则即可

你好，我试了一下自带的双目录规则，它显示LoadTocError：目录列表为空
