### ISSUE TITLE
打开PDF文件存在显示不全的问题

### ISSUE THREAD

**Issue by csb168** [gedoor/legado#3499]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

打开PDF文件后奇数页和偶数页在一个页面显示，且偶数页只显示上半部分。即第N(N为奇数)页和第N+1页一起显示，且第N+1页只显示上半部分，如果想看第N+1页，需要长按N+1页部分，点“显示”才能看到下半部分。
默认设置（平板/横屏双页为全局单页），竖屏状态，一个页面下显示两页，即第N(N为奇数)页和第N+1页一起显示，且第N+1页只显示上半部分，如果想看第N+1页，需要长按N+1页部分，点“显示”才能看到下半部分。
横屏后，只显示单页，但也只显示当前页的上半部分，无法看到下半部分。
设置为全局双页，竖屏状态下，则显示4页，其中第4页显示部分。
设置为全局双页，横屏状态下，则只显示1页，同样无法显示当前页下半部分。

手机为Vivo Y35M，屏幕分辨率为720*1600
![1](https://github.com/gedoor/legado/assets/35262600/8e5c8ccf-ef6c-461e-a147-c3f9102ed4a0)
![2](https://github.com/gedoor/legado/assets/35262600/e62ea450-3e87-4f18-8c5c-f5eabfeea57c)
![3](https://github.com/gedoor/legado/assets/35262600/dbce01d5-5898-4188-bbd9-496dc4489f23)
![4](https://github.com/gedoor/legado/assets/35262600/235d314d-f555-41cf-87c9-7360563a5d40)

### 复现步骤 / How to reproduce

换华为PAD，问题再现。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

![0](https://github.com/gedoor/legado/assets/35262600/e63a210c-01ee-4342-ade5-090762cae71e)

### 阅读版本 / Legado version

3.22.110211

### Android版本 / Android version

Android 12

### 机型 / Model

Vivo Y35M，华为matepad

**Comment by 821938089** [comment]
用滚动翻页动画看

**Comment by csb168** [comment]
试了。不行。滚动翻页就是把当前屏幕全滚动了，如果两页在一屏，就把这一屏全滚动了，然后换下一个两页。

**Comment by lzhga-tx** [comment]
在打开pdf书籍的任意界面，点右上角三个点，选择图片样式，选择default 好像是正常显示的
