### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by lqfy-jhc** [gedoor/legado#350]
阅读 版本 3.20.082919
打开个别订阅源时，软件会突然崩溃闪退，已知点击[AcFun思维实验室](http://ku.mumuceo.com/yuedu/rssyuan/yuan.html?id=157)  这个订阅源，软件会崩溃，另外附上一个小问题，
![Screenshot_20200901160447](https://user-images.githubusercontent.com/59348827/91824179-efadf680-ec6c-11ea-80e6-de1885cd4a29.png)图标有时会丢失，重启软件后会恢复，但如果再次点击这两个位置，还是会发生 图标丢失 现象。

**Comment by gedoor** [comment]
图标丢失问题,最新版本已经解决

**Comment by gedoor** [comment]
崩溃请发一下崩溃报告

**Comment by gedoor** [comment]
都解决了
