### ISSUE TITLE
导出epub格式，自定义导出每个文件包含的章节数量设置为大于1时出错

### ISSUE THREAD

**Issue by subtle99** [gedoor/legado#3500]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

导出epub格式，自定义导出每个文件包含的章节数量设置为大于1时出错
文件命名时（index>1）出错，只能导出（index=1）的第一个文件

### 复现步骤 / How to reproduce

导出epub格式，自定义导出每个文件包含的章节数量设置为大于1时出错

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.111302

### Android版本 / Android version

Android 12

### 机型 / Model

.

**Comment by 821938089** [comment]
需要输出的章节要填对

**Comment by subtle99** [comment]
以下是我的填写输入，应该如何修改
导出文件名：{epubIndex}
每个文件名包含的章节数量：100
需要输出的章节：1-550

https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/ui/book/cache/CacheActivity.kt
308行：                1，【？】
319行：                etEpubSize.setText("1")【？】
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/help/book/BookExtensions.kt
239行：    bindings["epubIndex"] = ""【?】

**Comment by 821938089** [comment]
把导出文件名的花括号删掉

**Comment by subtle99** [comment]
使用最新的修改的版本测试，文件名还是有问题。
能不能对即将   1，生成的文件名，2，epub文件的元素据（title）先做个测试，查看最终生成的名称是否是想要的结果，再导出。
尝试使用分卷导出后的多个epub文件重新导入阅读后失败了，只能导入一个文件。

**Comment by 821938089** [comment]
点一下那个三角可以看一下生成的文件名
重新导入应该是书名作者相同导致的问题，你导入一个然后改一下就行

**Comment by subtle99** [comment]
> 把导出文件名的花括号删掉

文件名写成 ：name author epubIndex （提示Error）,如何想要（文件名）：书名_作者_【epub分卷的序号】，应该如何写？ 多个变量连接符用什么？

**Comment by 821938089** [comment]
和js一样

**Comment by Discut** [comment]
有时间还得优化一下，用户引导不太行。(～￣▽￣)～
