### ISSUE TITLE
Web服务夜间模式的对比度可以强一些吗？

### ISSUE THREAD

**Issue by luo-chuan** [gedoor/legado#3502]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

如下图，对比度很低，很难看清。
![图片](https://github.com/gedoor/legado/assets/33930736/77b70225-6779-43e0-a1a7-c9cea1784914)

### 期望实现方式 / How to implement

建议增强暗黑模式的对比度，或者提供一个对比度更强的夜间主题。或者提供一个设置亮度、对比度的滑块。

**Comment by bzkmsjy** [comment]
用dark reader插件很完美

**Comment by luo-chuan** [comment]
可以reopen吗？
