### ISSUE TITLE
卷名有问题

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3504]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

也不知道是我写错了还是怎么样，卷名也显示了，也变黑了，然后他就开头的第一个显示异常，打不开，永远显示正在加载中。后面的卷名全正常，然后咋往后翻都是这一章卡着，必须去目录手动点其他章跳转
![Screenshot_2023-11-17-10-41-09-837_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/4d31ef46-648f-465c-8383-9a6edc871d5d)

![Screenshot_2023-11-17-10-36-55-182_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/7109db46-6b2f-44b0-b43c-edfb65d9e4af)
![Screenshot_2023-11-17-10-38-14-892_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/2e5f38cd-c32f-43bd-baa8-bd043dbf0569)

### 复现步骤 / How to reproduce

https://shuyuan.mgz6.cc/shuyuan/830ebb07ccfc53100d99eb95b42e889e.json
自己写的书源，琢磨半天，就这个卷名搞不定，不知道bug还是写错了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110614

### Android版本 / Android version

Android 13

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
网络问题

**Comment by gyz1023** [comment]
不是网络问题，至少不仅仅是网络问题，我不知道他为啥要在卷名下加载数据，这也许是有的卷名也带正文吧，但是加载不出来为啥要影响我翻页和下一章，为啥点目录又能正常跳转，这应该是老问题了吧，下一章早就加载出来

**Comment by 821938089** [comment]
卷名有地址它就会加载，你判断一下卷名不要返回地址就可以了

**Comment by blackcd318** [comment]
页面恐怕是后加载的,最初打开的页面就是这么显示,浏览器会用js加载正文,阅读你不告诉他他不加载

**Comment by 821938089** [comment]
修了一下，试试最新测试版
