### ISSUE TITLE
[Bug] java.ajax发不出PUT请求

### ISSUE THREAD

**Issue by helloplhm-qwq** [gedoor/legado#3506]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在书源js中将请求方法设置为PUT后实际发出去的是GET请求

### 复现步骤 / How to reproduce

![54412c81147bf6e7](https://github.com/gedoor/legado/assets/94218819/e4de1e34-9824-44ff-9483-a62dbc7d844c)
![-26ff0cae461a38b5](https://github.com/gedoor/legado/assets/94218819/c3aaae61-1e84-4c77-8918-2c6729b93429)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.111708 (14890)

### Android版本 / Android version

HarmonyOS 2.0.0 Android 10

### 机型 / Model

华为Mate40 Pro

**Comment by 821938089** [comment]
java.ajax只支持get和post请求，其他的请求可以自己调okhttp发送

**Comment by helloplhm-qwq** [comment]
> java.ajax只支持get和post请求，其他的请求可以自己调okhttp发送

但是如果我的请求需要Cookie，那么该如何获取保存的Cookie

**Comment by 821938089** [comment]
用java.getCookie

**Comment by helloplhm-qwq** [comment]
![image](https://github.com/gedoor/legado/assets/94218819/f9af04c7-18ef-4887-97a8-96a3f5ffd450)

**Comment by 821938089** [comment]
有一个参数，要填url

**Comment by helloplhm-qwq** [comment]
感谢: )
