### ISSUE TITLE
搜索和换源取消后依旧在线程中执行，是否消耗性能，是否需优化问题

### ISSUE THREAD

**Issue by qq570026938** [gedoor/legado#351]
虽然搜索取消后不会在success中回调，但是线程中的任务依旧在执行，应该是和传入的scope是viewmodel的scope有关系，处理时可以在循环线程的webbook外层加上launch传入这个launch的作用域，记录对应的job,在取消时，循环取消，job.cancel。此时webbook内部的线程会立刻关闭。但此方法感觉不是特别好，请问你们能不能优化下Coroutine类来达到这种效果呢。

**Comment by gedoor** [comment]
job.cancel后内部还是运行,我再找找办法吧

**Comment by YumikoAzu** [comment]
cancel 成功后只是成功的修改了协程的 Job 状态，并没有终止执行，那如何可以成功终止协程的执行呢，我们可以借助 yeild() 函数（包括 delay 都是支持取消的），我们可以在 cancel 函数调用后紧接着调用 yeild() 函数检查协程的取消。

**Comment by gedoor** [comment]
最新版本应该好了,网络访问会及时取消了
