### ISSUE TITLE
请添加具体书籍和作者的搜索功能

### ISSUE THREAD

**Issue by VceUtaoki1** [gedoor/legado#3516]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在发现界面的书源里可以搜索小说的名字或作者，这样可以快速找到小说，提高软件使用效率

### 期望实现方式 / How to implement

发现界面先找书源，在书源下找分类，在出现具体的书籍时可以按作者或者小说名字搜索具体书籍，

**Comment by 821938089** [comment]
点击详情页里的书名和作者可以搜索

**Comment by VceUtaoki1** [comment]
大佬，为何我无法在书源界面搜到任何内容？只能搜到书源的名字，搜具体小说的名字或作者都是啥也没有？这种情况不正常吧，具体咋操作？我哪里做的不对？

![S31122-11293985](https://github.com/gedoor/legado/assets/98039120/37a66b66-b407-4ae9-b77f-35410bfa318f)书名搜不到
![S31122-11295279](https://github.com/gedoor/legado/assets/98039120/abd8af5a-a3bf-494d-8a72-7f3e332126c2)作者搜不到
![S31122-11315091](https://github.com/gedoor/legado/assets/98039120/19d41727-eac0-4af6-bcf8-a31ac8db4a86)必须进书源里才能一个一个的找到

**Comment by 821938089** [comment]
这个是筛选发现，不是搜书，搜书去书架那里搜

**Comment by VceUtaoki1** [comment]
okok，好了，谢谢

**Comment by kebedd69** [comment]
额😓。。。你搜书要去书架右上角那搜，不是在发现那搜
