### ISSUE TITLE
默认非高刷

### ISSUE THREAD

**Issue by Link-ee** [gedoor/legado#3517]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现在的包都是默认60帧，如果想要高刷得手机设置开启自定义高刷。以前的PRO是默认高刷的。

### 期望实现方式 / How to implement

希望和PRO版一样默认开启高刷新率，或者app内添加开启高刷选项。

**Comment by zousizhe** [comment]
小米吗，那是系统的名单，pro不在里面，如果使用共存版也可以高刷
