### ISSUE TITLE
（拆分超长章节）能不能加个统一开关

### ISSUE THREAD

**Issue by Canoidi** [gedoor/legado#3518]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

看本地txt的时候，很多本来已经分好的章节由于（拆分超长章节）拆成十几章不太雅观，本来那章也没多长。但这么一拆，想改回去的话就需要点目录——右上角——取消拆分，很不便而且（拆分）总是对每本书都是默认开启的。

### 期望实现方式 / How to implement

《阅读》用了很久，个人感觉（拆分超长章节）开启是负作用的，是希望能够把（拆分超长章节）设置默认关闭，或者为其设置一个统一开关在目录正则或是总设置里（重新分段感觉也可以这么加个全局默认开关）。
感谢大佬一直以来付出！

### 附加信息 / Additions

![IMG_20231122_125950](https://github.com/gedoor/legado/assets/64999976/888b52e4-60b1-40a1-b86c-6be6764d0095)

**Comment by 821938089** [comment]
章节超过3万字左右才会拆分章节，你这一章按你说的拆成十几章至少都有四五十万字了吧。。。

**Comment by Canoidi** [comment]
> 章节超过3万字左右才会拆分章节，你这一章按你说的拆成十几章至少都有四五十万字了吧。。。

**Comment by 821938089** [comment]
默认关闭的话如果单章字数过多会导致应用崩溃

**Comment by Canoidi** [comment]
> 默认关闭的话如果单章字数过多会导致应用崩溃

![Screenshot_2023-11-30-14-34-29-410_io legado app release](https://github.com/gedoor/legado/assets/64999976/5011a298-e843-4541-8385-2988521f9180)
才发现本地书长按也有这几个选项，但如果默认关闭的话可能会崩溃，那能不能把开关设置成全局的，这个（删除提醒）每本书都是统一的
