### ISSUE TITLE
正文净化规则

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#3521]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现有版本想替换净化正文里的广告词，一般会把替换正则写在两个地方：
- 将替换正则加在正文内容规则后面
- 单独填写在替换规则里

然而，这两种写法是有区别的。
- 写在正文内容规则后面的话，如果整行广告词都被替换，显示正文将自动删除空行。
- 写在替换规则的话，如果整行广告词都被替换，显示正文将保留空行。

希望能实现：写在替换规则里的正则净化，替换掉整个空行的时候，显示正文自动删除空行。

### 期望实现方式 / How to implement

如上所述

**Comment by 821938089** [comment]
最终在阅读界面的显示是不会有空行的
或者你在正则里把换行符也匹配上就不会有空行了

**Comment by skybbk1998** [comment]
> 最终在阅读界面的显示是不会有空行的 或者你在正则里把换行符也匹配上就不会有空行了

测试最终阅读时确实没有空行，但是调试时两个替换方式，一个没有空行，一个有。按理来说，调试正文应该是一样的结果，要么都保留空行，要么都自动删掉空行。目前这个还是对写正文规则有一定的影响，不好判断某些正则表达式是否生效。
关于换行符，有些广告词一会儿在文章开头，一会儿在文章末尾，不太好加换行。

**Comment by 821938089** [comment]
正文规则那里替换是带html的，在处理html的时候会去掉空行，所以会不一样
不确定有没有换行符的话可以用`\s?`匹配

**Comment by skybbk1998** [comment]
> 正文规则那里替换是带html的，在处理html的时候会去掉空行，所以会不一样 不确定有没有换行符的话可以用`\s?`匹配

好的，明白了。谢谢
