### ISSUE TITLE
用酷安上“**枯藤老树**”的“**存储空间清理**”软件（版本4.18.7）清理了一次**空文件夹**后，再打开软件就崩溃闪退

### ISSUE THREAD

**Issue by Julianyeee** [gedoor/legado#3522]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

用酷安上“**枯藤老树**”的“**存储空间清理**”软件（版本4.18.7）清理了一次**空文件夹**后，再打开开源阅读软件就崩溃报错。
重装开源阅读软件后会稍微晚个几秒钟再崩溃报错，重启手机也无效，给开源阅读软件授予所有权限也无效，仍会崩溃。

### 复现步骤 / How to reproduce

同上描述，【用酷安上“**枯藤老树**”的“**存储空间清理**”软件（版本4.18.7）清理了一次**空文件夹**】

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

![开源阅读崩溃报错](https://github.com/gedoor/legado/assets/104682328/d9e855cc-0947-4fb3-9beb-b7ac5792c024)

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

HarmonyOS 4.0.0.116

### 机型 / Model

华为 mate 30

**Comment by 821938089** [comment]
打开这个路径/Android/data/io.legado.app.release/cache/crash
把里面的崩溃日志文件发一下

**Comment by adhu2018** [comment]
查了下这个权限，这个可能是firebase引起的问题，因为这个手机没有gms？firebase在崩溃时才会用到吧，所以除了这个问题以外，还有其他问题？

**Comment by 821938089** [comment]
可以试试最新测试版
