### ISSUE TITLE
希望优化在朗读模式下滑动切换上下句

### ISSUE THREAD

**Issue by 57334920** [gedoor/legado#3524]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望优化在朗读模式下，通过滑动切换上下句，因为目前的朗读模式下，上下滑动切换总是会回到文章的第一句重读。虽然有切换上下句或暂停的小控件，但是在不方便看手机屏幕下操作控件的方式确实不如滑动更快捷和方便。

### 期望实现方式 / How to implement

在朗读模式下，通过上下滑动屏幕控制上一句重听或快进到下一句，。例如上滑切换到上一句话，向下滑动屏幕就是快进到下一句。

**Comment by 821938089** [comment]
可以设置点击区域来朗读上一句或下一句

**Comment by xsdcz** [comment]
现在的滑动切换朗读确实有些不方便，比如有时候听书时有些句子没听清，就想划回去看一眼，结果就切换朗读了，而且切换朗读还不是按照段落来跳的，会回到某一页上（我习惯用滚动翻页），希望可以优化改进，或者干脆有个选项改成滑动时不切换朗读。
