### ISSUE TITLE
锁屏朗读或后台朗读时，每章结束后自动暂停需要手动继续

### ISSUE THREAD

**Issue by xcrichie** [gedoor/legado#3526]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

锁屏朗读、后台朗读时，每章结束后会暂停，需手动进入app才能继续朗读
是我哪里的设置出问题了吗？

### 复现步骤 / How to reproduce

打开小说，朗读后锁屏，朗读完一章后会自动停止，解锁后才会继续朗读。
后台朗读时，手动进入app才会继续朗读。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

HarmonyOS 4.0.0.116

### 机型 / Model

HUAWEU Mate40Pro

**Comment by surfaceyu** [comment]
vivo x100 也有同样的问题

**Comment by mkitclear** [comment]
魅族21出现同样的问题
