### ISSUE TITLE
配置文件导入能不能放宽限制，一修改书籍的url指向就报错

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3531]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

书源地址变动，以前书源地址改变可以在在配置文件批量修改书籍指向达到批量换源的效果，现在一修改导回就报错，手动换源又有搜索时间限制，半分钟换一个，书源加个webview又需要在url修改，之前添加的小说url地址固定了不能生效，也需要修改书籍url指向，希望能支持修改配置文件的书籍url导入覆盖，不然很难操作

### 期望实现方式 / How to implement

希望能修改配置文件，导入之后不报错

**Comment by 821938089** [comment]
没有限制吧，是不是你改的不对

**Comment by zousizhe** [comment]
> 没有限制吧，是不是你改的不对

把配置的一个书源从地址http改成https就导入不进去，现在我找了个去年的pro版，导入现在修改的数据，再更新成最后一个pro版，再次备份之后再导回现在的版本才行

**Comment by 821938089** [comment]
报错是什么

**Comment by zousizhe** [comment]
报错


> 报错是什么

现在又不报了，前几个版本还报，现在已经好了
