### ISSUE TITLE
关于打开软件书籍自动更新的bug

### ISSUE THREAD

**Issue by gzce** [gedoor/legado#3534]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

打开阅读APP时候会有个书籍自动更新的功能，这个bug可能来源于书架里某本书书源失效导致的无法更新，这时候CPU就会占用100%，并且一直都是如此，而且功耗也会是正常时候2倍多。

### 复现步骤 / How to reproduce

打开阅读APP时候会有个书籍自动更新的功能，这个bug可能来源于书架里某本书书源失效导致的无法更新，这时候CPU就会占用100%，并且一直都是如此，而且功耗也会是正常时候2倍多。
关闭自动更新书籍功能就完全正常了
希望在打开软件书籍自动更新功能加个时效功能，超时就自动跳过不执行书源错误的书籍了，这样就不会CPU一直高占用了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

安卓13

### 机型 / Model

真我gtNeo5se

**Comment by 821938089** [comment]
刷新是并行执行的，进入死循环的线程是没有办法终止的
有些书源写的不好，刷新非常慢
建议自己二分法排查一下是哪个书源有问题
或者书源管理校验一下书源，把失效的清理一下
