### ISSUE TITLE
第一页是默认下载状态，正文还未加载出来时选择缓存全部章节，会跳过第一页

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3535]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

之所以说这个问题是在晚上经常有遇到加载慢的网站，直接选择下载章节会比加载正文更快，但是等到小说下载完成再进去，发现还是要加载，之前总是搞不清什么原因，后来才发现在下载管理看却是第一页根本没下载，在目录里第一页默认是已下载状态，但是阅读并不会预读第一页，所以在未加载成功时不应该显示为已下载状态

### 复现步骤 / How to reproduce

一到晚上经常有遇到网速比较慢的书源，正文加载比较慢，从正文使用缓存全部章节，再退出正文，等待下载完成之后发现还剩下第一页并未被缓存

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi k

**Comment by 821938089** [comment]
进入正文阅读就会马上缓存看的那一章，没有缓存就是网络卡住了
