### ISSUE TITLE
鸿蒙和IOS平台的开源项目

### ISSUE THREAD

**Issue by nuaa-wwbin** [gedoor/legado#3538]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

鸿蒙系统逐渐被接受，而且马上要取消适配安卓了，请求项目组大佬们开启个鸿蒙版本的开源阅读吧，这神器不能缺席鸿蒙啊...
IOS就不强求了，苹果好像封闭的太严重了，能有就有吧。

### 期望实现方式 / How to implement

开启适配鸿蒙的开源阅读项目的开发

**Comment by feitxue** [comment]
我感觉难搞。
ios开发账号的钱谁出？（一年99刀起步，还要买mac os的电脑来开发发布，都是额外的成本）
国产安卓和各类类安卓系统（鸿蒙之类的所谓国产研发的），大概率后面要更强的监管，提高非应用商城的app的安装门槛。
应用商城上架要备案，这个也很麻烦。需要大量的时间成本来搞。

**Comment by BUTUbird** [comment]
可行性不高
