### ISSUE TITLE
在书源编辑页面查看源码只要源码过长往下滑动过程中就会出现崩溃

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#3541]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题

### 复现步骤 / How to reproduce

比如随便整个网址填进书源
{
  "bookSourceName": "四四",
  "bookSourceType": 0,
  "bookSourceUrl": "https://www.44xw.com",
  "customOrder": 0,
  "enabled": true,
  "enabledCookieJar": false,
  "enabledExplore": false,
  "lastUpdateTime": 1701441479352,
  "respondTime": 180000,
  "ruleContent": {
    },
  "ruleSearch": {
    "bookList": "html",
    "bookUrl": "href",
    "name": "text"
  },
  "searchUrl": "/s/{{key}}/",
  "weight": 0
}
搜索看搜索源码 因为有很多条结果源码结果很长，划着划着就开始报错崩溃
![Video_20231201_104405_754](https://github.com/gedoor/legado/assets/73186747/2ac6f349-a03b-415c-a612-9681f009d694)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

SDK_INT=33
WebViewUserAgent=Mozilla/5.0 (Linux; Android 13; MEIZU 18 Pro Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6148.0 Mobile Safari/537.36
MODEL=MEIZU 18 Pro
RELEASE=13
MANUFACTURER=meizu
versionName=3.23.112523
versionCode=14948
BRAND=meizu
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
	at com.meizu.internal.picker.ResultSender.sendPickerResult(ResultSender.java:587)
	at com.meizu.internal.picker.ScanScreen.lambda$doCapture$0$com-meizu-internal-picker-ScanScreen(ScanScreen.java:328)
	at com.meizu.internal.picker.ScanScreen$$ExternalSyntheticLambda4.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

### 阅读版本 / Legado version

3.23.120103

### Android版本 / Android version

Android13

### 机型 / Model

小米13

**Comment by 821938089** [comment]
系统问题，关闭传送门功能

**Comment by ladia** [comment]
/

> 系统问题，关闭传送门功能

我是小米刷的flyme

**Comment by 821938089** [comment]
那就关Aicy识屏
