### ISSUE TITLE
高亮和笔记功能

### ISSUE THREAD

**Issue by 809825706** [gedoor/legado#3542]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

能够实现向微信读书一样的高亮和笔记功能吗？

### 期望实现方式 / How to implement

增加修改epub文件或者外挂一个css实现特定位置文本的格式？

### 附加信息 / Additions

无

### 效果演示 / Demo

参见微信读书或者其他epub阅读器？

**Comment by Lujango** [comment]
need
