### ISSUE TITLE
能否增加小窗模式？

### ISSUE THREAD

**Issue by lxh015** [gedoor/legado#355]

**Comment by Mupceet** [comment]
什么叫小窗模式，能给个示例样式吗？

**Comment by lxh015** [comment]
如图，最底层是微信，中间多出一个文件管理的窗口。

现在主流安卓应该是支持分屏的，但是小窗口模式我就不知道了，这种模式类似于手机淘宝上的浏览商品内容时，那个视频会在页面中间一直在。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mupceet"<notifications@github.com&gt;; 
发送时间: 2020年9月9日(星期三) 晚上7:00
收件人: "gedoor/legado"<legado@noreply.github.com&gt;; 
抄送: "林小辉"<425883845@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gedoor/legado] 能否增加小窗模式？ (#355)





 
什么叫小窗模式，能给个示例样式吗？

**Comment by Mupceet** [comment]
你的图片没上传成功~

**Comment by lxh015** [comment]
类似与这个文件管理器






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mupceet"<notifications@github.com&gt;; 
发送时间: 2020年9月10日(星期四) 下午2:51
收件人: "gedoor/legado"<legado@noreply.github.com&gt;; 
抄送: "林小辉"<425883845@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gedoor/legado] 能否增加小窗模式？ (#355)





 
你的图片没上传成功~

**Comment by gedoor** [comment]
感觉没必要
