### ISSUE TITLE
展示从微信分享的epub文件（电子书文件是通过工具将word转成的epub的），只能展示第一页电子书，文件请见附件。

### ISSUE THREAD

**Issue by leef2464** [gedoor/legado#3553]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

展示从微信分享的epub文件，只能展示第一页电子书。该电子书文件是使用工具将word文档转成的epub格式，七猫或者掌阅是可以正常展示的。另外将pdf转成epub是可以正常展示的。具体电子书文件请见附件
[output2.zip](https://github.com/gedoor/legado/files/13574432/output2.zip)

### 复现步骤 / How to reproduce

下载最新代码运行打包，或者提供的release包都不能正常展示word文档转换之后的epub格式

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新版本

### Android版本 / Android version

android 13

### 机型 / Model

redmi  k60

**Comment by leef2464** [comment]
已经切换了目前几种阅读方式(滚动、覆盖、仿真等)，都不行

**Comment by adhu2018** [comment]
因为里面toc.ncx就只有一个navPoint啊，其他软件是什么情况，这不符合标准的是怎么能解析出来的😂

**Comment by leef2464** [comment]
> 因为里面toc.ncx就只有一个navPoint啊，其他软件是什么情况，这不符合标准的是怎么能解析出来的😂

您好，您说的toc.ncx和navPoint是什么啊，这个要怎么修改，或者我上哪里可以学习啊。我上传了掌阅的阅读效果，是可以阅读的，您可以看下，

https://github.com/gedoor/legado/assets/143598182/501c0405-4b4c-46f9-b52c-dbad88f38cee

但是《阅读》只展示了第一页的内容

**Comment by adhu2018** [comment]
> 因为里面toc.ncx就只有一个navPoint啊，其他软件是什么情况，这不符合标准的是怎么能解析出来的😂

好像懂了，toc.ncx不完整但是content.opf里的spine是完整的，所以其他软件能解析

**Comment by leef2464** [comment]
这个能改吗，刚接触epub的电子书，不清楚该怎么改，当前项目支持吗

**Comment by leef2464** [comment]
> 这个能改吗，刚接触epub的电子书，不清楚该怎么改，当前项目支持吗

这个能改吗，刚接触epub的电子书，不清楚该怎么改，当前项目支持吗

**Comment by leef2464** [comment]
@adhu2018 这个能改吗，刚接触epub的电子书，不清楚该怎么改，当前项目支持吗

**Comment by adhu2018** [comment]
> @adhu2018 这个能改吗，刚接触epub的电子书，不清楚该怎么改，当前项目支持吗

可以改epub，epub也是一个压缩包，改里面的toc.ncx，在已有的navPoint下加上
```
    <navPoint id="id2" playOrder="2">
      <navLabel>
        <text>未知</text>
      </navLabel>
      <content src="index.html"/>
    </navPoint>
```
阅读怎么改就不知道了，跳过toc.ncx直接content.opf的话可能会有其他问题

**Comment by leef2464** [comment]
@adhu2018 好的谢谢大佬

**Comment by 821938089** [comment]
最新测试版已修复

**Comment by leef2464** [comment]
另外我看之前别人提的问题(https://github.com/gedoor/legado/issues/1442)，也是电子书加载不出来，但是别家的可以加载出来.
出问题的电子书地址
https://wwt.lanzouo.com/i3sHwx2nwpa
密码:a8xs
https://wwt.lanzouo.com/ixtWPx2nujc
密码:eg95
这两个是为什么啊，使用现在的包也是加载不出来，希望可以解答一下

**Comment by 821938089** [comment]
你需要修改toc.ncx文件添加目录

**Comment by leef2464** [comment]
> 你需要修改toc.ncx文件添加目录

是的，我遍历章节列表和目录列表之后，添加了额外的目录

**Comment by 821938089** [comment]
PackageDocumentReader.java 文件中的 ensureImageInfo 方法报空指针，导致没找到目录文件

**Comment by leef2464** [comment]
> 是opf文件的命名空间不规范的问题

可以指点一下，需要怎么改吗，刚才看了报错的方法，没找到原因

**Comment by leef2464** [comment]
> [900bc38](https://github.com/gedoor/legado/commit/900bc3876c4e364a8e08e46fcb9a631fb6877a66)

可以了，感谢回复

**Comment by leef2464** [comment]
> 另外我看之前别人提的问题(#1442) 也是电子书加载不出来，但是别家的可以加载出来. 出问题的电子书地址 https://wwt.lanzouo.com/i3sHwx2nwpa 密码:a8xs https://wwt.lanzouo.com/ixtWPx2nujc 密码:eg95 这两个是为什么啊，使用现在的包也是加载不出来，希望可以解答一下

@821938089 您好，我今天看这个电子书的时候，发现封面有些东西是没展示出来的。只展示了封面，封面下方的文字介绍没展示出来，请看图片。
![image](https://github.com/gedoor/legado/assets/143598182/21659b44-670a-4674-96de-35acca980160)
![image](https://github.com/gedoor/legado/assets/143598182/415e2bd8-cd0e-491c-af1a-744a8110f52c)

**Comment by 821938089** [comment]
阅读对封面页做了特殊处理，会忽略实际内容直接返回封面图片，以解决封面图片不显示的问题

**Comment by leef2464** [comment]
> 阅读对封面页做了特殊处理，会忽略实际内容直接返回封面图片，以解决封面图片不显示的问题

请问这个逻辑在哪里呢，我研究下可以自己修改吗

**Comment by 821938089** [comment]
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/model/localBook/EpubFile.kt#L203

**Comment by leef2464** [comment]
> https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/model/localBook/EpubFile.kt#L203

好的，谢谢

**Comment by leef2464** [comment]
> https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/model/localBook/EpubFile.kt#L203
您好，我使用的是前几天下载的版本，还没有封面页特殊处理的逻辑，封面页还是战士不正常，下面是我的代码，附件为封面页的html文件，麻烦看一下
[coverpage.zip](https://github.com/gedoor/legado/files/13680808/coverpage.zip)

`private fun getBody(res: Resource, startFragmentId: String?, endFragmentId: String?): Element {
        // Jsoup可能会修复不规范的xhtml文件 解析处理后再获取
        var bodyElement = Jsoup.parse(String(res.data, mCharset)).body()
        bodyElement.children().run {
            select("script").remove()
            select("style").remove()
        }
        // 获取body对应的文本
        var bodyString = bodyElement.outerHtml()
        val originBodyString = bodyString
        /**
         * 某些xhtml文件 章节标题和内容不在一个节点或者不是兄弟节点
         * <div>
         *    <a class="mulu1>目录1</a>
         * </div>
         * <p>....</p>
         * <div>
         *    <a class="mulu2>目录2</a>
         * </div>
         * <p>....</p>
         * 先找到FragmentId对应的Element 然后直接截取之间的html
         */
        if (!startFragmentId.isNullOrBlank()) {
            bodyElement.getElementById(startFragmentId)?.outerHtml()?.let {
                /* 章节内容在fragmentI对应的div下时 会截取空白 */
                bodyString = bodyString.substringAfter(it).ifBlank { bodyString }
            }
        }
        if (!endFragmentId.isNullOrBlank() && endFragmentId != startFragmentId) {
            bodyElement.getElementById(endFragmentId)?.outerHtml()?.let {
                bodyString = bodyString.substringBefore(it)
            }
        }
        //截取过再重新解析
        if (bodyString != originBodyString) {
            bodyElement = Jsoup.parse(bodyString).body()
        }
        /*选择去除正文中的H标签，部分书籍标题与阅读标题重复待优化*/
        val tag = Book.hTag
        if (book.getDelTag(tag)) {
            bodyElement.run {
                getElementsByTag("h1").remove()
                getElementsByTag("h2").remove()
                getElementsByTag("h3").remove()
                getElementsByTag("h4").remove()
                getElementsByTag("h5").remove()
                getElementsByTag("h6").remove()
                //getElementsMatchingOwnText(chapter.title)?.remove()
            }
        }
        return bodyElement
    }`

**Comment by 821938089** [comment]
旧版的封面页处理逻辑在getContent函数那里
