### ISSUE TITLE
漫画可以只显示一页吗 

### ISSUE THREAD

**Issue by Monster-DP** [gedoor/legado#3559]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

一屏只显示一页漫画 ，希望可以增加这个的开关 ，漫画显示的时候应该是配最小的宽度或者最小的高度 按照比例适配 

### 期望实现方式 / How to implement

增加该功能

**Comment by 821938089** [comment]
用滚动翻页动画看

**Comment by 821938089** [comment]
你这也不是滚动翻页啊，漫画只能用这个看，其他的会不全的

**Comment by Monster-DP** [comment]
> 你这也不是滚动翻页啊，漫画只能用这个看，其他的会不全的

所以啊 提功能需求😂

**Comment by Monster-DP** [comment]
> 试试把图片显示样式改成默认

三种样式都试过了 不行
