### ISSUE TITLE
最新测试版，无法使用浏览器打开地址

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3561]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

无法在右上角使用浏览器打开了
![Screenshot_2023-12-08-13-04-00-112_android](https://github.com/gedoor/legado/assets/37259360/8061e7ab-5397-4184-a7e5-a57391a99f04)

### 复现步骤 / How to reproduce

通过内置webview打开网页后，无法在右上角使用浏览器打开了，原本应该调用默认浏览器，但是现在需要选择浏览器，但是选择界面空白

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.120802

### Android版本 / Android version

Android 13

### 机型 / Model

redmi k60 pro

**Comment by 821938089** [comment]
已经修复了
