### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by echoy6** [gedoor/legado#3575]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

从我的打开其他设置 点击清除webview数据就会闪退。前两个版本也出现了这个问题

### 复现步骤 / How to reproduce

我的-清除webview后就会闪退

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.121012

### Android版本 / Android version

Android 10

### 机型 / Model

vivo

**Comment by 821938089** [comment]
清除webview数据后需要重启应用才会生效，应该是杀掉应用后启动失败了，你自己再打开就行了

**Comment by echoy6** [comment]
> 清除WebView数据后需要重启应用才会生效，应该是杀掉应用后启动失败了，你自己再打开就行了

因为正式版还有之前的版本不会这样，之前的版本会提示成功清除缓存 也没有闪退 所以我觉得这是bug
