### ISSUE TITLE
https请求协议不支持tls1.2

### ISSUE THREAD

**Issue by Sun-QAQ** [gedoor/legado#3577]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前https请求协议好像不支持tls1.2？

### 期望实现方式 / How to implement

目前https请求协议好像不支持tls1.2？

**Comment by 821938089** [comment]
支持的，具体要看服务器和客户端的协商
