### ISSUE TITLE
净化替换规则对章节标题无效

### ISSUE THREAD

**Issue by agutools** [gedoor/legado#358]
现版本无论怎么设置规则，都无法对章节标题生效，请问是更改设定了吗？是从哪一个版本开始的呢？

**Comment by 52fisher** [comment]
净化规则不应该对标题生效的，可以通过修改书源解决

**Comment by agutools** [comment]
章节标题样式多数是因作者而异，而不是应站点而异，用书源去调节哪有净化规则来得明确直接，况且估算多数用户都是直接导入网络书源，不会调整😟
