### ISSUE TITLE
【移除重复标题】功能不起效

### ISSUE THREAD

**Issue by gxlmyacc** [gedoor/legado#3580]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题，不清楚是所有都不起效，还是这本书中不起效：[问题图片](https://www.jianguoyun.com/p/DdQbQ54Q-72cDBi-qq0FIAA)
我用编辑器打开看了下原始文本格式是这样的：[文本原始样子](https://www.jianguoyun.com/p/DWAkt7kQ-72cDBjHqq0FIAA)

另外：用app本身的【编辑内容】打开编辑是空白：[编辑内容](https://www.jianguoyun.com/p/DcWQipUQ-72cDBjdqq0FIAA)

### 复现步骤 / How to reproduce

1、在这个网址下载txt书籍：http://www.mayitxt.org/book/159563.html；
2、在app里添加这本书；
3、点击这本书，打开约定，随便找个重复章节名的章节，点击菜单中的【移除重复标题】

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

无

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 13

### 机型 / Model

小米14

**Comment by 821938089** [comment]
移除重复标题是针对正文的

**Comment by gxlmyacc** [comment]
哦，好的，了解了 :-)
