### ISSUE TITLE
再次启动朗读功能时第一行会跳到屏幕中间

### ISSUE THREAD

**Issue by gxlmyacc** [gedoor/legado#3581]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

我昨天升级到了最新版3.23.110211后，发现启动朗读好像是从屏幕开始位置朗读了，不过有个问题，就是朗读了一部分终止后，滚动下页面后，重新开始朗读时，它虽然是从屏幕开始位置朗读的，但是开始朗读后，朗读行会突然从原本的屏幕第一行跳到屏幕中间某一行（具体行数有点随机），让人一下子不好找到原先的位置了，这种体验不太好，建议修复下。

这是我录制的问题视频：[问题视频](https://www.jianguoyun.com/p/DZ4YdGYQ-72cDBinqa0FIAA)

### 复现步骤 / How to reproduce

1、设置翻页动画为【滚动】；
2、随便找一本书，点击打开；
3、点击菜单中的朗读，朗读一段时间后，用手在手机边缘滑动触发系统取消，这是会有toast提示“朗读暂停”；
4、向后滚动页面一段距离，重新定义一个新的开始朗读行，将其移动到屏幕的第一行；
5、打开菜单，点击菜单中的【终止朗读】；
6、重新打开菜单，点击朗读；
7、这是将会从屏幕的第一行开始朗读，但是朗读的第一行会突然跑到屏幕中间（具体哪一行是随机的，找不出规律）

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 13

### 机型 / Model

小米14

**Comment by 821938089** [comment]
为了保证高亮能够显示，必须要对齐本页的位置，所以要跳一下

**Comment by gxlmyacc** [comment]
> 为了保证高亮能够显示，必须要对齐本页的位置，所以要跳一下
这样给人的感官不太好，这样一跳我一开始都不知道跳哪里了，还是来回试了几次，才发现规律。建议能优化的话，还是尽量能优化下吧

**Comment by testwind** [comment]
TTS朗读功能，我正在优化改进。差不多好了。最近会把代码提交上来。
第一次提交代码，想问下，需要找谁，谁来审核合并代码？

**Comment by acewind1** [comment]
在开发中的几个功能：

1. 按标点分句子朗读，句子连续不会被分页打断。
             （之前是按整个段落朗读，而且会被分页打断）
2. 朗读时，手动翻页，翻章节，翻看其他页面，不会影响朗读位置。
3. 正在朗读的句子发生切换时，文章自动滚动/翻页。
4. 自动滚动时，保证朗读语句在显示区域限制在中部。
            当新句的底部 > 屏幕3/4 高度时，动画上滚屏幕，把这句话移动到屏幕1/8位置，确保显示在 1/8 到 3/4 屏高。
5. 正在朗读句子不在当前显示页面中时，不会发生朗读自动翻页/滚动
6. 点击预览图片时，暂停朗读。关闭图片时，继续朗读

testwind 账号也是我  :)
