### ISSUE TITLE
建议朗读菜单添加个【系统取消行为】的菜单项

### ISSUE THREAD

**Issue by gxlmyacc** [gedoor/legado#3582]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

我一般习惯在右手在屏幕上滑动来取消朗读，但是这样的取消只是“暂停朗读”，每次想重新从屏幕第一行开始朗读时，都必须先打开朗读菜单，然后点击“终止朗读”，然后再打开朗读菜单，点击开始按钮才行，操作比较繁琐。

### 期望实现方式 / How to implement

建议提供菜单配置：朗读时系统取消操作行为：暂停朗读 还是 终止朗读。
如果选择了【终止朗读】的话，屏幕边缘滑动触发系统取消事件后，朗读终止，而不是暂停

**Comment by 821938089** [comment]
你翻下页就可以重新从第一行开始读

**Comment by gxlmyacc** [comment]
我这里没有翻页功能，因为我的翻页方式是“滚动”，意味着页面没有分页的概念，可以自由滚动

**Comment by gxlmyacc** [comment]
昨天在用的时候发现，朗读只是暂停的话，滚动页面后，继续朗读，也是从当前屏幕第一行开始的，那么这个需求也就意义不大了。

最近刚开始使用这个app，很多功能还在探索，有不懂的地方还请见谅.
