### ISSUE TITLE
建议【书源管理】里的【分组管理】支持合并分组

### ISSUE THREAD

**Issue by gxlmyacc** [gedoor/legado#3584]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

之前从公众号中下载了一些书源进行导入，然后导入的书源里有各种分组，分组名很混乱，有些还是重复的，想对这些分组进行合并，但是目前的分组管理里只有编辑分组名和删除，没有提供合并的功能，建议能提供下合并功能。
<img src="https://github.com/gedoor/legado/assets/11564806/f0ae4d91-0db2-4cef-b519-5c59bf807a82" width="400px" />

### 期望实现方式 / How to implement

1、分组管理里每项前面加个复选框，
2、底部或头部添加合并按钮/图标；
3、点击合并后，将勾选的分组合并成同一个，合并后的分组名可以取第一个，也可以有个弹窗，让用户自己设置合并后的新的分组名

**Comment by 821938089** [comment]
改成相同名字就可以合并

**Comment by gxlmyacc** [comment]
> 改成相同名字就可以合并

谢啦
