### ISSUE TITLE
更新到最新测试版有突然有书源出现正文加载失败

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3585]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

![Screenshot_2023-12-15-13-43-07-2128986799](https://github.com/gedoor/legado/assets/37259360/25bbab13-5658-4731-b52e-923649acfb0e)
 3.23.121504版有个书源无法加载正文，上一版就正常

### 复现步骤 / How to reproduce

所有正文报错
https://shuyuan.mgz6.cc/shuyuan/7c0de3e6529f3ff024dcac7858fc4ce2.json

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.121504

### Android版本 / Android version

Android

### 机型 / Model

Redmi k60

**Comment by 821938089** [comment]
已修复
