### ISSUE TITLE
书籍添加方式

### ISSUE THREAD

**Issue by wyh3130024630** [gedoor/legado#3587]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

书源的搜索无法使用，但还能解析书籍。
用浏览器在书源网站找到所需书籍，使用书籍网址按书源解析该书籍添加到书架。

### 期望实现方式 / How to implement

在书源调试详情页调试中添加把解析出的书籍添加到书架的功能

**Comment by 821938089** [comment]
书架右上角可以添加网址，书源需要填写书籍URL正则规则
