### ISSUE TITLE
是否有开发者文档，关于编译以及开发环境初始化？

### ISSUE THREAD

**Issue by Mukvin** [gedoor/legado#3590]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望能添加下开发者文档，有关编译以及环境初始化等之类的。

### 期望实现方式 / How to implement

Markdown 文档方式

**Comment by 821938089** [comment]
代码用git clone下来然后直接用Android studio打开就行
