### ISSUE TITLE
音量键翻页失控

### ISSUE THREAD

**Issue by bajzc** [gedoor/legado#3595]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

小概率触发轻按音量键翻页后和长按滚动翻页一样的情况，大概每20次会触发一下。

不知能否在设置里添加一个**取消音量键滚动翻页**的功能。

### 复现步骤 / How to reproduce

多按几下翻页就会触发

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

https://github.com/gedoor/legado/blob/03af785add68270def405e6c06cbf4893e493f90/app/src/main/java/io/legado/app/ui/book/read/ReadBookActivity.kt#L825

### 日志提交 / Relevant log output

无

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 13 (MIUI14)

### 机型 / Model

Redmi K60 Ultra

**Comment by 821938089** [comment]
应该是你的手机的音量键出问题了，有时候会变成长按
