### ISSUE TITLE
epub封面

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3598]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

今天更新的最新测试版，导出个epub，封面显示不出来，我又看了一下之前导出的epub，封面还显示，但勾选一下那俩个选项，删除Ruby标签或者删除h标签，原本还显示的封面也不显示了
![Screenshot_2023-12-21-18-37-24-723_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/891f3873-6028-44c7-8d6d-84eccd5188a5)
![Screenshot_2023-12-21-18-23-55-157_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/098b8e00-60f5-4b11-a79a-7a83a89307ed)

### 复现步骤 / How to reproduce

随便一个epub都这样，都是之前用阅读导出的

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.121902

### Android版本 / Android version

Android 13

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
已修复，更新新版本后刷新一下目录就可以了
