### ISSUE TITLE
分屏/悬浮窗模式下状态栏显示多余空白

### ISSUE THREAD

**Issue by Mupceet** [gedoor/legado#360]
在华为系统上有问题，其他系统未验证。

![Screenshot_20200907_194028_io.legado.app.release.jpg](https://user-images.githubusercontent.com/5202761/92384344-7ddd1d80-f142-11ea-948e-72868b50c438.jpg)

![Screenshot_20200907_194420_io.legado.app.release.jpg](https://user-images.githubusercontent.com/5202761/92384358-87ff1c00-f142-11ea-939e-64707b6c8b3b.jpg)

**Comment by gedoor** [comment]
好的,我想想怎么解决

**Comment by gedoor** [comment]
最新版本应该解决了
