### ISSUE TITLE
明年华为好像要更新纯血鸿蒙，作为目前主力APP，麻烦请问下会将来会同步推出纯血版鸿蒙APP么（决定将来是否更新纯血鸿蒙系统）

### ISSUE THREAD

**Issue by xiaoran0503** [gedoor/legado#3603]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

明年华为好像要更新纯血鸿蒙，作为目前主力APP，麻烦请问下会将来会同步推出纯血版鸿蒙APP么（决定将来是否更新纯血鸿蒙系统）

### 期望实现方式 / How to implement

支持开发纯血版鸿蒙APP

**Comment by easythd** [comment]
不更新就完了。。。小众系統。。。

**Comment by anccnuer** [comment]
也许可以等纯血鸿蒙上的虚拟机应用，应该会有的吧……

**Comment by xiaoran0503** [comment]
> 不更新就完了。。。小众系統。。。

依照华为的尿性。。。就怕在某个时刻强制推送更新

**Comment by DingYou-K** [comment]
确实，就是不知道鸿蒙会不会支持模拟器了。
