### ISSUE TITLE
屏幕超时功能有问题！

### ISSUE THREAD

**Issue by fjfhukh** [gedoor/legado#3604]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

        我使用的是海信A5ProCC手机，阅读APP的屏幕超时功能使用默认选项，手机系统的休眠熄屏功能设置的时间要保证能正常看电子书，但是，手机的其它功能不一定也需要这个手机熄 屏时间，所以阅读APP的屏幕超时最好不使用默认选项，于是我选了3分钟，但是发现个问题——首先说明一点手机系统的休眠设定时间是15秒（和这个设置有关系），当手机点亮屏幕后，打开阅读APP，进入阅读的小说页面，发现有时候到了手机休眠设定的时间15秒后手机会熄屏（如果手机的系统休眠时间是30秒，那就是到了30秒后手机会熄 屏），而不是到阅读APP屏幕超时设定的3分钟后熄屏，还有，当正在看小说时，到了阅读APP屏幕超时设定的3分钟后，手机熄屏（这是正常的），但是手机熄屏后，点亮手机屏幕后，还是到了手机休眠设定的时间15秒后手机会熄屏，而不是到阅读APP屏幕超时设定的3分钟后熄屏，再次点亮屏幕，这个问题依旧，如果再次点亮屏幕，不对屏幕进行操作，问题一起存在，直到手机点亮屏幕后，触摸一下屏幕，或者翻页一下，这个问题才消失！这是使用海信A5ProCC手机发现的问题，其它的手机没有测试过，不知道是否存在这样的问题！

### 复现步骤 / How to reproduce

        我使用的是海信A5ProCC手机，阅读APP的屏幕超时功能使用默认选项，手机系统的休眠熄屏功能设置的时间要保证能正常看电子书，但是，手机的其它功能不一定也需要这个手机熄 屏时间，所以阅读APP的屏幕超时最好不使用默认选项，于是我选了3分钟，但是发现个问题——首先说明一点手机系统的休眠设定时间是15秒（和这个设置有关系），当手机点亮屏幕后，打开阅读APP，进入阅读的小说页面，发现有时候到了手机休眠设定的时间15秒后手机会熄屏（如果手机的系统休眠时间是30秒，那就是到了30秒后手机会熄 屏），而不是到阅读APP屏幕超时设定的3分钟后熄屏，还有，当正在看小说时，到了阅读APP屏幕超时设定的3分钟后，手机熄屏（这是正常的），但是手机熄屏后，点亮手机屏幕后，还是到了手机休眠设定的时间15秒后手机会熄屏，而不是到阅读APP屏幕超时设定的3分钟后熄屏，再次点亮屏幕，这个问题依旧，如果再次点亮屏幕，不对屏幕进行操作，问题一起存在，直到手机点亮屏幕后，触摸一下屏幕，或者翻页一下，这个问题才消失！这是使用海信A5ProCC手机发现的问题，其它的手机没有测试过，不知道是否存在这样的问题！

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

不会

### 日志提交 / Relevant log output

不会

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 10/Android version 7

### 机型 / Model

HLTE203T

**Comment by 821938089** [comment]
最新测试版已修复无操作息屏问题

**Comment by fjfhukh** [comment]
最新测试版的下载地址是什么




随缘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月23日(星期六) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] 屏幕超时功能有问题！ (Issue #3604)





 
最新测试版已修复无操作息屏问题

**Comment by 821938089** [comment]
https://github.com/gedoor/legado/actions/workflows/test.yml
点最新的一个workflow，在里面的Artifacts下载

**Comment by fjfhukh** [comment]
为什么你们的网址经常打不开！


随缘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月23日(星期六) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] 屏幕超时功能有问题！ (Issue #3604)





 
https://github.com/gedoor/legado/actions/workflows/test.yml
 点最新的一个workflow，在里面的Artifacts下载

**Comment by 821938089** [comment]
网络问题，打不开就挂梯子

**Comment by fjfhukh** [comment]
怎么找不到Artifacts




随缘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月23日(星期六) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] 屏幕超时功能有问题！ (Issue #3604)





 
https://github.com/gedoor/legado/actions/workflows/test.yml
 点最新的一个workflow，在里面的Artifacts下载

**Comment by 821938089** [comment]
在页面稍下面一点的地方

**Comment by fjfhukh** [comment]
谢谢！




随缘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月23日(星期六) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] 屏幕超时功能有问题！ (Issue #3604)





 
在页面稍下面一点的地方

**Comment by fjfhukh** [comment]
&nbsp; &nbsp; &nbsp; &nbsp;给你们提的这个建议好像你们理解错了，不是要你们增加一个长按音量键翻页的选项，我的意思是增加一个“翻了一页后接着翻下一页之间的时间间隔”的选项，选项中可以设置时间间隔从0秒至5秒(当然还可以是6秒、7秒.....等等)
&nbsp; &nbsp; &nbsp; &nbsp;还有在阅读页面中点击后，弹出的那个TXT目录规则图标，现在不是目录规则了


&nbsp; &nbsp; &nbsp; 不知道广大书友有没有遇到过这样问题——我们在使用阅读APP看电子书时，由于种种原因，当我们看完一页，需要翻页时，结果连续翻了两页，甚至三页或者更多页，可能很多书友一下子连续翻了两页，甚至三页或者更多页时，没注意到，但是，当书友们感觉到翻页后，新看的一页内容和刚看过的那一页内容不连贯时，就是可能连续翻了两页，甚至三页或者更多页，只是没有意思到而已，那么怎样解决这一问题呢！
? ?? ? 方法很简单，只需要在APP的翻页选项里面增加一个选项——连续翻页选项：连续翻页延迟0——5秒（当然这个5秒可以是3秒，10秒等等，范围的大小，决定着连续翻页延迟选择范围的大小，只是觉得5秒就可以了），0秒代表着，翻一页后，0秒后可以继续翻下一页，实际上就是不延迟的意思，1秒代表着，翻一页后，1秒内不可以继续翻下一页，1秒后可以继续翻下一页，也就是说延迟1秒才能连续翻页，2秒代表着，翻一页后，2秒内不可以继续翻下一页，2秒后可以继续翻下一页，也就是说延迟2秒才能连续翻页......以此类推，这样就可以彻底解决种种原因导致错误的一下了翻了两页，甚至三页或者更多页，比如连续误触了两次屏，比如经常翻页使用的机械按键，由于经常使用，导致机械按键接触不良，从而导致的连续翻页，再比如，现在很多书友，为了看电子书方便，特别是现在天气比较冷，为了不冻手，使用手机蓝牙遥控器，这些蓝牙遥控器，使用左右翻页键翻页时，基本上都会在手机屏幕上出现鼠标指针，影响观感，想使用音量键翻页功能，但是这些手机蓝牙遥控器的音量+-按键一般都是需要长按上下翻页按键，实现音量+-功能，但是用在电子书音量键翻页功能上时就出现问题了，由于长按的时间不好把控，所以就会导致有时翻不了页，有时候会连续翻页，如果APP增加了连续翻页的延迟功能后，连续翻页延迟功能设置延迟5秒连续翻页，针对这种长按实现音量+-功能的按键，我们只需要长按需要按的按键三四秒，既能达到长按实现音量+-键的音量+-功能，同时实现了APP的音量键翻页功能，也不会导致APP的不需要的连续翻页！
? ?? ? 如果开源阅读APP能够增加这一新功能，既能更好的使用开源阅读APP阅读电子书，同时，也是开源阅读APP的一个新亮点，让开源阅读APP功能更加优于同类的APP，让开源阅读APP书友更多！

**Comment by 821938089** [comment]
连续翻页就是因为长按音量键导致的啊，现在加了开关默认是关闭的就不会有问题了

**Comment by fjfhukh** [comment]
连续翻页的原因不是因为长按音量键，已经试过了，长按音量键，依然存在连续翻页的问题，其它连续翻页的原因由多种，比如如果触屏可以翻页，我们连续触屏，我们依然可以连续翻页，手指连续左右滑动屏幕，同样可以连续翻页等等。


随缘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月23日(星期六) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] 屏幕超时功能有问题！ (Issue #3604)





 
连续翻页就是因为长按音量键导致的啊，现在加了开关默认是关闭的就不会有问题了

**Comment by 821938089** [comment]
那不知道了，我测试长按音量键只能翻一页
这个是解决长按音量键连续翻页的问题而已

**Comment by fjfhukh** [comment]
我试的是无论把长按音量键翻页这个选项关闭还是打开，长按音量键，小说页面不停的滚动，难道是手机品牌和型号不同造成的，还有麻烦试试连续点击屏幕和连续滑动屏幕，会不会连续翻页。




随缘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月23日(星期六) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] 屏幕超时功能有问题！ (Issue #3604)





 
那不知道了，我测试长按音量键只能翻一页
 这个是解决长按音量键连续翻页的问题而已

**Comment by 821938089** [comment]
我不觉得这是问题，你别点那么快就行了

**Comment by fjfhukh** [comment]
专家你好！
&nbsp; &nbsp; &nbsp; 最新版的关闭"按键长按翻页“选项，可以实现长按手机音量键不连续翻页，但是，使用手机蓝牙遥控器时，长按遥控器上的音量键，仍然连续翻页，说明咱的思路方向不正确，你看看我的思路可以考虑考虑吗？
&nbsp; &nbsp; &nbsp; 我的思路是：我觉得很多看小说的APP中的自动翻页功能，可以借鉴到这个防止连续翻页功能当中，因为自动翻页需要设置翻页间隔时间，这就是两种功能的相同之处，把自动翻页功能中的翻页时间间隔的程序借鉴到防止连续翻页中是不是可以消除连续翻页，这项新功能若是设计成功，也是小说阅读类APP与众不同的新亮点，会有更多的书友使用咱们这款阅读APP，更能新高咱们这款阅读APP的知名度。




随缘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月23日(星期六) 晚上6:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] 屏幕超时功能有问题！ (Issue #3604)





 
我不觉得这是问题，你别点那么快就行了

**Comment by fjfhukh** [comment]
专家你好！
&nbsp; &nbsp; &nbsp;&nbsp;如今阅读APP支持左右滑屏正常翻页，上下滑屏能翻页，但是无论是向上滑屏，还是向下滑屏，都是翻到下一页，不能通过上下滑屏翻到上一页，但是我们有时候需要用到上下滑屏前后翻页，比如：我现在用的一款蓝牙戒指遥控器，总共三个触摸按键，没有音量+-功能，默认是上下滑屏抖音翻页视频，咱们的阅读APP也可以通过遥控器的上下按键滑屏翻页，但是只能翻到下一页，无法翻到上一页，遥控器切换到左右滑屏翻页模式，需要长按上键7秒，很麻烦，更要命的是遥控器切换到左右滑屏翻页模式不能记忆在这个模式，遥控器关机再开机(总之只要遥控器蓝牙手机断开了连接，重新连接后，又恢复到上下翻页模式)，所以想使用这款遥控器在咱们的阅读APP上看小说翻页很麻烦，但是如今正值寒冷季节，使用蓝牙手机遥控器可以不冻手，当然，还有很多款的手机蓝牙遥控器都存在这样的问题，所以，建议阅读APP开启上下滑屏正常前后翻页的功能，方便书友使用手机蓝牙遥控器看电子书！
