### ISSUE TITLE
关于开启上下滑屏前后正常翻页的建议

### ISSUE THREAD

**Issue by fjfhukh** [gedoor/legado#3605]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

如今阅读APP支持左右滑屏正常翻页，上下滑屏能翻页，但是无论是向上滑屏，还是向下滑屏，都是翻到下一页，不能通过上下滑屏翻到上一页，但是我们有时候需要用到上下滑屏前后翻页，比如：我现在用的一款蓝牙戒指遥控器，总共三个触摸按键，没有音量+-功能，默认是上下滑屏抖音翻页视频，咱们的阅读APP也可以通过遥控器的上下按键滑屏翻页，但是只能翻到下一页，无法翻到上一页，遥控器切换到左右滑屏翻页模式，需要长按上键7秒，很麻烦，更要命的是遥控器切换到左右滑屏翻页模式不能记忆在这个模式，遥控器关机再开机(总之只要遥控器蓝牙手机断开了连接，重新连接后，又恢复到上下翻页模式)，所以想使用这款遥控器在咱们的阅读APP上看小说翻页很麻烦，但是如今正值寒冷季节，使用蓝牙手机遥控器可以不冻手，当然，还有很多款的手机蓝牙遥控器都存在这样的问题，所以，建议阅读APP开启上下滑屏正常前后翻页的功能，方便书友使用手机蓝牙遥控器看电子书！

### 期望实现方式 / How to implement

如今阅读APP支持左右滑屏正常翻页，上下滑屏能翻页，但是无论是向上滑屏，还是向下滑屏，都是翻到下一页，不能通过上下滑屏翻到上一页，但是我们有时候需要用到上下滑屏前后翻页，比如：我现在用的一款蓝牙戒指遥控器，总共三个触摸按键，没有音量+-功能，默认是上下滑屏抖音翻页视频，咱们的阅读APP也可以通过遥控器的上下按键滑屏翻页，但是只能翻到下一页，无法翻到上一页，遥控器切换到左右滑屏翻页模式，需要长按上键7秒，很麻烦，更要命的是遥控器切换到左右滑屏翻页模式不能记忆在这个模式，遥控器关机再开机(总之只要遥控器蓝牙手机断开了连接，重新连接后，又恢复到上下翻页模式)，所以想使用这款遥控器在咱们的阅读APP上看小说翻页很麻烦，但是如今正值寒冷季节，使用蓝牙手机遥控器可以不冻手，当然，还有很多款的手机蓝牙遥控器都存在这样的问题，所以，建议阅读APP开启上下滑屏正常前后翻页的功能，方便书友使用手机蓝牙遥控器看电子书！

### 附加信息 / Additions

如今阅读APP支持左右滑屏正常翻页，上下滑屏能翻页，但是无论是向上滑屏，还是向下滑屏，都是翻到下一页，不能通过上下滑屏翻到上一页，但是我们有时候需要用到上下滑屏前后翻页，比如：我现在用的一款蓝牙戒指遥控器，总共三个触摸按键，没有音量+-功能，默认是上下滑屏抖音翻页视频，咱们的阅读APP也可以通过遥控器的上下按键滑屏翻页，但是只能翻到下一页，无法翻到上一页，遥控器切换到左右滑屏翻页模式，需要长按上键7秒，很麻烦，更要命的是遥控器切换到左右滑屏翻页模式不能记忆在这个模式，遥控器关机再开机(总之只要遥控器蓝牙手机断开了连接，重新连接后，又恢复到上下翻页模式)，所以想使用这款遥控器在咱们的阅读APP上看小说翻页很麻烦，但是如今正值寒冷季节，使用蓝牙手机遥控器可以不冻手，当然，还有很多款的手机蓝牙遥控器都存在这样的问题，所以，建议阅读APP开启上下滑屏正常前后翻页的功能，方便书友使用手机蓝牙遥控器看电子书！

**Comment by 821938089** [comment]
阅读可以自定义翻页按键

**Comment by fjfhukh** [comment]
专家你好！
&nbsp; &nbsp; &nbsp; 手机蓝牙遥控器的上下翻页键，在阅读APP的自定义翻页按键中不能定义，因为手机蓝牙遥控器的上下翻页键是用来控制手机鼠标指针上下移动来实现翻页的，应该是没有键值，即使有，我们也不知道键值是多少，在APP自定义翻页按键设置里面，可以通过按音量+-键，自动输入键值，但是按手机蓝牙遥控器的上下翻页键，只能让手机的鼠标指针上下移动，却不能自动输入键值，所以APP的自定义翻页按键不能定义手机蓝牙遥控器的上下翻页键来翻页，还有，最新测试版3.23.12250929，我测试过了，可以通过手机上下滑动屏幕实现电子书正常前后翻页，但是手机蓝牙遥控器的上下翻页键仍然是只能翻到下一页，不能翻到上一页，对于防止长按音量+-键连续翻页，手机的音量+-键，不会造成连续翻页，但是，长按手机蓝牙遥控器的上下翻页键实现音量+-键功能时偶尔会造成连续翻两页。


随缘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月25日(星期一) 中午12:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] 关于开启上下滑屏前后正常翻页的建议 (Issue #3605)





 
阅读可以自定义翻页按键
