### ISSUE TITLE
校验书源app闪退

### ISSUE THREAD

**Issue by ziyue7575** [gedoor/legado#3606]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

校验书源时，540左右app就开始卡顿，过几秒就崩溃重启。
7月初的时候还没有问题的，几千个书源偶尔会出现弹出页面但是返回就可以继续校验，现在不会弹页面，但是500多app就崩了。

### 复现步骤 / How to reproduce

选中上千书源，校验到540左右app就崩溃重启。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 11

### 机型 / Model

realme x50 pro （12G内存）

**Comment by 821938089** [comment]
线程数多少？
还有发一下崩溃日志

**Comment by ziyue7575** [comment]
> 线程数多少？ 还有发一下崩溃日志

我用了20线程，当时没有记录日志，不过可能是书源的问题，我把一堆书源删除之后没有出现了。昨天导入这个网盘里的书源的时候也出现了。https://caiyun.139.com/w/i/1E5C2IT39sV6z
