### ISSUE TITLE
图片式样imagestyle怎样设置为图片大小和文字内容字体大小一致？

### ISSUE THREAD

**Issue by eiauo** [gedoor/legado#361]
有些网站正文参杂图片替换文字，用FULL时，图片居中变大，和正文content文字不匹配。不写imagestyle参数时，图片又太小，而且也换行居中，和正文content文字也不匹配。
有没有其他参数可用？
看源码没找到相关参数。

图片式样imagestyle怎样设置为图片大小和文字内容字体大小一致？能否添加此内容？

**Comment by gedoor** [comment]
这个还不行,等后面更新吧

**Comment by 52fisher** [comment]
新版已解决此问题
