### ISSUE TITLE
本地导出问题

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3610]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

遇到个问题，一直都有，好多次了，下的知轩藏书的TXT，用阅读打开了，想导出epub，但是我又嫌前面多余内容，用WPS把前面知轩藏书什么的删了，问题可能是我先导入阅读，然后改的，删完前面多余内容，阅读目录其实立刻刷新了，每次都以为没问题，但导出就会随机缺少内容，修不修复问题可能也不大，大不了我改下操作顺序，就是遇到这种事很难受。既然直接改动导入阅读的本地文件，导出会有问题，不能修复的话，改动后不显示书籍，提示重新导入行不行
![Screenshot_2023-12-27-07-53-14-410_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/adb170a5-42f4-4d0d-8da1-a49ef1ea284a)
![Screenshot_2023-12-27-07-53-21-860_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/9ff58d24-d9a3-4bf7-a66f-8a2e1ccc6e9c)
这俩图就是原文和导出后的，明显缺一截内容，绝对不是净化的原因

### 复现步骤 / How to reproduce

直接用WPS什么的改变已经导入阅读的本地书，导出经常有问题，少内容，如果不能修复，阅读能不能禁止这个操作，原文件被改，提示一下打不开，让重新导入一下，这样导出应该就没问题

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.122400

### Android版本 / Android version

Android 13

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
试试最新测试版，不行的话就只能改完刷新下目录再导出

**Comment by 550-q** [comment]
用其它txt编辑软件（我用的mt管理器）修改完保存后，“阅读”这边打开一本其它书在返回原来的书就会刷新成新版本了，我经常这样操作没出现过问题。
但要注意这样操作不会改变在“阅读”文本界面右上角“编辑内容”编辑过的章节。
