### ISSUE TITLE
建议【封面换源】不清空历史的封面图片

### ISSUE THREAD

**Issue by gxlmyacc** [gedoor/legado#3613]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

每次点击封面图片打开【封面换源】想更换或查看封面图片的时候，一打开【封面换源】就会触发封面搜索，同时总会立即清空历史的封面图片，再加上查询封面图片的过程很慢，这导致封面图片更换很麻烦。
另外，搜索封面的过程中如果手机黑屏了的话，重新点亮屏幕后，也会重新触发封面查询并清空已经下载下来的封面图片，这也导致查询封面的过程中需要一直保持屏幕亮着，体验也不是很好

### 期望实现方式 / How to implement

触发封面查询后，不清空封面图片，而是等查到结果后，更新的更新，删除的删除

**Comment by 821938089** [comment]
其他设置里关掉自动清理过期搜索数据即可
搜索慢是你书源太多失效或很多书源搜不到这本书的问题

**Comment by gxlmyacc** [comment]
> 其他设置里关掉自动清理过期搜索数据即可 搜索慢是你书源太多失效或很多书源搜不到这本书的问题

我已经清过失效书源了，但是还是慢。换封面这里也没发指定书源搜索优先级。目前的情况就是这里搜索封面的体验确实不太好，建议还是能优化下吧
