### ISSUE TITLE
web服务功能有缺陷

### ISSUE THREAD

**Issue by pwatx** [gedoor/legado#3615]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

我是在同一个局域网里面使用的，但是经常出现电脑端无法显示内容的bug。我猜测应该是由于手机息屏引起的，因为我把手机亮屏就有可以连上了。

### 复现步骤 / How to reproduce

读着读着，手机息屏后，就会出现无法读取网页的情形，非常蛋疼。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22.041209

### Android版本 / Android version

Android 13

### 机型 / Model

一加 Ace2

**Comment by pwatx** [comment]
另外还有一个建议，就是web服务的页面，可以看到是参考起点中文网做的，但是实在是过于简陋。
1. 现在电脑都很宽，但是设置里面宽度只能加到960. 而且还不能双页显示，电脑两头的空间都浪费了。
2. 行距等选项无法调节。
3. 没有标注，章评等功能。

**Comment by 821938089** [comment]
系统问题，允许后台运行就好，找找相关设置，例如省电之类的

**Comment by pwatx** [comment]
> 系统问题，允许后台运行就好，找找相关设置，例如省电之类的

好像可以了，谢谢。
建议在开启网站这里加一个功能，提醒用户不要用省电模式，或者单独给这个应用设置允许后台活动。
