### ISSUE TITLE
根据正文去除章节

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3616]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现在防盗太恶心，那种光有正文没目录的能不能解决一下。很有用的，不然真的不知道咋对付他们

### 期望实现方式 / How to implement

就从最后一章开始检测正文，正文为空就取消这一章的目录，再检测上一章，以此类推，直到有正文。这样会净化就能解决很多问题。可以单独书源或小说加个开关

**Comment by 821938089** [comment]
遇到这种书源直接删掉才是正解
