### ISSUE TITLE
有什么办法禁用日志吗,小说每翻一页就有一个弹窗"IP已被封禁"

### ISSUE THREAD

**Issue by duzefu** [gedoor/legado#3619]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

短时间内缓存太多,被小说网站BAN了IP.但是每翻一页都提示一次IP被封禁是不是有点离谱了

### 期望实现方式 / How to implement

起码有一个开关能关闭 IP被封禁的 弹窗

### 附加信息 / Additions

![Screenshot_2024-01-02-17-42-05-55_90024215e504237c76412be1999ad914](https://github.com/gedoor/legado/assets/12474623/363179a0-3bb2-43b2-b40d-31b87777b385)

**Comment by 821938089** [comment]
换源

**Comment by NiYukk** [comment]
其他设置里预下载正文改小就行了

**Comment by duzefu** [comment]
> 换源

就这一个源是完整的,很难换啊...

**Comment by youke2580c** [comment]
关掉网络

**Comment by zhangzw218** [comment]
> > 换源
> 
> 就这一个源是完整的,很难换啊...

什么源地址，我想看看

**Comment by duzefu** [comment]
> > > 换源
> > 
> > 
> > 就这一个源是完整的,很难换啊...
> 
> 什么源地址，我想看看

{
  "bookSourceComment": "",
  "bookSourceGroup": "",
  "bookSourceName": "八一中文",
  "bookSourceType": 0,
  "bookSourceUrl": "https://www.81zw.com",
  "bookUrlPattern": "",
  "concurrentRate": "",
  "customOrder": 146,
  "enabled": true,
  "enabledCookieJar": false,
  "enabledExplore": false,
  "exploreUrl": "",
  "header": "{'User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko, By Black Prism) Chrome/99.0 Safari/537.36'}",
  "lastUpdateTime": 1675926141363,
  "loginCheckJs": "",
  "loginUi": "",
  "loginUrl": "",
  "respondTime": 180000,
  "ruleBookInfo": {
    "author": "//meta[@property='og:novel:author']/@content",
    "coverUrl": "//meta[@property='og:image']/@content",
    "intro": "//meta[@property='og:description']/@content",
    "kind": "//meta[@property='og:novel:category']/@content",
    "lastChapter": "//meta[@property='og:novel:latest_chapter_name']/@content",
    "name": "//meta[@property='og:novel:book_name']/@content"
  },
  "ruleContent": {
    "content": "id.content.0@html##(请退出转码|八一中文).+"
  },
  "ruleExplore": {},
  "ruleReview": {},
  "ruleSearch": {
    "author": "class.result-game-item-info-tag.0@tag.span.1@text",
    "bookList": "class.result-item",
    "bookUrl": "class.result-game-item-title-link.0@href",
    "coverUrl": "tag.img.0@src",
    "intro": "class.result-game-item-desc.0@text",
    "kind": "class.result-game-item-info-tag.1@tag.span.1@text",
    "lastChapter": "class.result-game-item-info-tag.3@tag.a.0@text",
    "name": "class.result-game-item-title-link.0@text"
  },
  "ruleToc": {
    "chapterList": "id.list.0@tag.dd",
    "chapterName": "tag.a.0@text",
    "chapterUrl": "tag.a.0@href"
  },
  "searchUrl": "/search.php?keyword={{key}}",
  "weight": 0
}
