### ISSUE TITLE
添加或者移动书籍到新分组时无法触发下拉刷新

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3620]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

需要在其他分组操作一次刷新，新的分组才能触发下拉刷新，不然没有反应

### 复现步骤 / How to reproduce

把小说添加到新分组之后无法使用下拉刷新

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.010220

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
已修复
