### ISSUE TITLE
我的小米6pro平板开始推送澎湃OS了，有人刷了吗，阅读能正常使用不？

### ISSUE THREAD

**Issue by nobk** [gedoor/legado#3623]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

要是运行阅读app有问题，那我暂时不升级固件了。

### 期望实现方式 / How to implement

测试兼容性

**Comment by HansonXHC** [comment]
应该不会有问题，HyperOS基于安卓，和MIUI差不多一个性质

**Comment by gebilaobai** [comment]
我小米12刷了澎湃，目前使用正常，暂未遇到问题

**Comment by MuggleGod** [comment]
米13已升级HyperOS, 目前没有问题
