### ISSUE TITLE
web页面简陋，建议增加几个常用功能

### ISSUE THREAD

**Issue by pwatx** [gedoor/legado#3635]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1. 现在电脑都很宽，但是设置里面宽度只能加到960. 而且还不能双页显示，电脑两头的空间都浪费了。
2. 行距，字距，边距等选项无法调节。
3. 无法选择翻页动画，甚至无法选择是左右翻页还是上下翻页。
4. 默认的翻页模式在右侧没有滚动条，无法用滚动条上下滑动页面。
5. 没有连续翻页的模式。预加载章节+连续翻页可以大大提高阅读的流畅度和舒适感，强烈建议增加！！
6. 没有标注，章评等功能。

### 期望实现方式 / How to implement

1. 增加对页面宽度，行距，字距，边距等调整的选项。
2. 增加翻页动画和翻页方式的选择。
3. 上下翻页和连续翻页增加滚动条。
4. 上下翻页增加连续翻页选项，连续翻页模式下可以预读取后面几章的章节，已实现流畅的阅读。
5. 增加标注，章评等功能

**Comment by qianfanguojin** [comment]
阅读的 web 端只是算一个轻量的临时阅读工具，如果 web 端使用频繁，建议使用 [hectorqin/reader](https://github.com/hectorqin/reader)
