### ISSUE TITLE
关于tts的请求超时问题

### ISSUE THREAD

**Issue by brian95827** [gedoor/legado#3643]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

1. 对于长段落的TTS，因为段落比较长，处理时间也比较长很容易导致超时
2. 超时之后app发起重试，因为同样的原因重试也会失败，导致多次失败后中途退出tts。

### 复现步骤 / How to reproduce

选中长段落进行tts，一些处理能力比较弱的api会处理长文本超时，
进而超时导致重试，重试依旧超时，进而app的tts多次失败自动退出。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

建议：
1. app中提供超时的相关设置：超时时间，重试次数。（用户可以自行设置）
2. 将长段落分割为多个小段，分次进行请求。

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 12

### 机型 / Model

Remid K50

**Comment by 821938089** [comment]
长段落切分可以用替换净化

**Comment by Yuansheng-Liang** [comment]
> 长段落切分可以用替换净化

你说的对，替换净化确实可行。

我写了一个长段落切分的替换净化，以便以后遇到相同问题查看issue的人可以参考：
```
{
  "excludeScope": "",
  "group": "",
  "id": 1704908067799,
  "isEnabled": true,
  "isRegex": true,
  "name": "分割长段落",
  "order": 0,
  "pattern": "(\\S{80,100}(?=[。，？”！\\-$])[。，？”！\\-$]*)",
  "replacement": "$1\n",
  "scope": "",
  "scopeContent": true,
  "scopeTitle": false,
  "timeoutMillisecond": 3000
}
```

**Comment by acewind1** [comment]
TTS朗读功能，我正在优化改进。差不多好了。最近会把代码提交上来。
第一次提交代码，想问下，需要找谁，谁来审核合并代码？

@Yuansheng-Liang 

我在开发中的几个功能：

1. 按标点分句子朗读，句子连续不会被分页打断。  
         （之前是按整个段落朗读，而且会被分页打断）
2. 按标点句子显示正在朗读的内容
3. 朗读时，手动翻页，翻章节，翻看其他页面，不会影响朗读位置。
4. 正在朗读的句子发生切换时，文章自动滚动/翻页。
5. 自动滚动时，保证朗读语句在显示区域限制在中部。
              当新句的底部 > 屏幕3/4 高度时，动画上滚屏幕，把这句话移动到屏幕1/8位置，确保显示在 1/8 到 3/4 屏高。
6. 正在朗读句子不在当前显示页面中时，不会发生朗读自动翻页/滚动
7. 点击预览图片时，暂停朗读。关闭图片时，继续朗读
