### ISSUE TITLE
webview不支持并发访问

### ISSUE THREAD

**Issue by Sun-QAQ** [gedoor/legado#3651]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题，正文多页同时webview访问，只有一页能正常访问

### 复现步骤 / How to reproduce

正文多页同时webview访问，只有一页能正常访问

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.07

### Android版本 / Android version

android12

### 机型 / Model

oppo reno 9

**Comment by 821938089** [comment]
发书源看看

**Comment by Sun-QAQ** [comment]
> 发书源看看

[test.json](https://github.com/gedoor/legado/files/13936515/test.json)

**Comment by 821938089** [comment]
网站问题，请求过快会404

**Comment by Sun-QAQ** [comment]
> 网站问题，请求过快会404

这个我到没注意，好的👍
