### ISSUE TITLE
搜索结果不匹配但是详情页匹配到已添加到书架时，书籍会变成未分组

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3652]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在搜索结果不匹配而在详情页补全信息才匹配到已添加该小说时，该小说之前的分组会变成未分组

### 复现步骤 / How to reproduce

搜索结果与详情信息不一致时，进入小说详情，显示已添加，小说分组会变成未分组

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.011120

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
试试最新测试版看看修好了没

**Comment by zousizhe** [comment]
> 试试最新测试版看看修好了没

好了
