### ISSUE TITLE
语音朗读时，没有及时自动翻页，念完一整段才翻页

### ISSUE THREAD

**Issue by star12134** [gedoor/legado#3653]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题，如果一段文字跨了两页，则那段文字下一页的部分只能听，听完了才会自动翻页。
无论是第三方TTS还是系统自动的语音引擎，都是如此

### 复现步骤 / How to reproduce

使用第三方TTS或系统自带的引擎进行朗读，直到一段文字跨两页时。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22.110211

### Android版本 / Android version

Android12

### 机型 / Model

三星s21u

**Comment by 821938089** [comment]
打开按页朗读

**Comment by acewind1** [comment]
@star12134 

使用的系统TTS，没有提供 onRangeStart 事件消息，
朗读服务无法感知到本页已读完。

直到整段读完时，才收到 onDone 事件消息，才进行翻页。

后续开发中的版本，已经解决此问题：
         1、支持按句朗读，
         2、支持滚动阅读时，自动上滚翻页
