### ISSUE TITLE
在正文标题生效的净化规则，目录页未开净化的时候，会在书架与详情页的最新章节栏生效，而且关不掉

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3656]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs
使用净化规则只替换正文标题时，书架与详情页最新章节会同步显示净化后的标题名，然后关掉正文净化，书架与详情页的最新章节栏上的净化却会一直生效，除非把那条净化规则关掉或者删除，不然就算没开净化功能也会一直生效

### 复现步骤 / How to reproduce

一个在正文标题生效的净化规则，目录页未开净化，在正文标题生效后，会在书架与详情页的最新章节里生效，之后再也关不掉，只能把规则删除或者完全关掉

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.011904

### Android版本 / Android version

Android

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
不能复现

**Comment by zousizhe** [comment]
> 不能复现

https://shuyuan.mgz6.cc/shuyuan/339421ffd6a44c563de3ea47b557b092.json

是净化规则导致，这个规则是修改正文标题，把第x页变成了第x章 页，目录未开启替换。

然后在书架与详情页，最新章节也会显示成第x章 页，这个原本应该显示目录最后一章的名字，现在显示的是正文净化后的标题名，然后关掉正文净化之后，正文标题恢复正常，但是书架与详情的最新章节就会一直显示第x章页，刷新一次后正常，但是下次进详情页又会在2秒内多出个 章字，之后添加这个站的所有小说都会变成这样

**Comment by 821938089** [comment]
已修复，试试最新测试版
