### ISSUE TITLE
长按点击朗读,会提示tts初始化失败

### ISSUE THREAD

**Issue by XY50** [gedoor/legado#3658]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

大概从一个星期前的测试版开始，长按点从此处开始朗读会提示TTS初始化失败。
点播放按钮朗读，可以正常朗读
经测试以前的旧版，无此问题

### 复现步骤 / How to reproduce

大概从一个星期前的测试版开始，长按点从此处开始朗读会提示TTS初始化失败。
点播放按钮朗读，可以正常朗读
![Screenshot_2024-01-20-17-27-31-006_io zhuliang pipphotos-edit](https://github.com/gedoor/legado/assets/121076219/ae0c64ab-74a1-437b-b8f5-b55bdb659a0d)
![Screenshot_2024-01-20-17-27-53-593_io zhuliang pipphotos-edit](https://github.com/gedoor/legado/assets/121076219/994afbe9-6ff5-4b81-9b52-670ebbbf7374)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.012012

### Android版本 / Android version

13

### 机型 / Model

红米k40g

**Comment by 821938089** [comment]
重新设置下朗读引擎

**Comment by XY50** [comment]
> 重新设置下朗读引擎



https://github.com/gedoor/legado/assets/121076219/7da4bdc5-0aab-4ae1-a9fe-7de0295bf2bf

重新设置也没用，长按从此处开始朗读依旧提示初始化失败，只有点击按钮才能正常朗读

**Comment by 821938089** [comment]
长按一下朗读按钮切换模式

**Comment by XY50** [comment]
> 长按一下朗读按钮切换模式

好了，正常了
