### ISSUE TITLE
Web newline

### ISSUE THREAD

**Issue by unOmni** [gedoor/legado#3662]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

Started using web service to read on tv and I noticed that words get broken down when starting new lines.
![_20240121_150026](https://github.com/gedoor/legado/assets/106206117/37f3400e-1d7f-49c8-b336-07ebabbddbeb)
Example captured on phone.

### 复现步骤 / How to reproduce

Always happens.

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 12

### 机型 / Model

Galaxy M21

**Comment by unOmni** [comment]
Bump

**Comment by 821938089** [comment]
try beta version
