### ISSUE TITLE
设置全局的翻页动画

### ISSUE THREAD

**Issue by fcxjluo** [gedoor/legado#3664]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

翻页动画的习惯是固定的，现在每次打开新的小说，都需要重新设置，比较麻烦

### 期望实现方式 / How to implement

需要能设置全局的翻页动画

**Comment by 821938089** [comment]
在界面里设置

**Comment by fcxjluo** [comment]
找到了，谢谢。 @821938089
