### ISSUE TITLE
搜索次数过多似乎会内存报警崩溃

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3667]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

个人习惯问题收藏了很多连载书籍，最近有大量失效了，因为各自的源不同以及用到的源有搜索时间间隔要求，没办法使用批量换源，所以只能手动操作，使用换源的速度还没有直接搜索书名作者再从标记小说进详情换源来得快，所以每次都这样操作，操作完成后还做了批量缓存，结果操作次数多了先是从详情页返回搜索列表时会直接跳回搜索输入框，再多操作几次就直接崩溃了

### 复现步骤 / How to reproduce

搜索次数过多就越来越卡直到崩溃

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

https://i-220.wwentua.com:446/01230900159575972bb/2024/01/23/6b18b1799f7ffd807394ca3c1087b302.7z?st=ibF2PqLaVB9jmb0SXbm9GA&e=1705975650&b=UWBbKVQ1UyUEOQN7B2ACfA_c_c&fi=159575972&pid=113-76-8-225&up=2&mp=1&co=0

### 阅读版本 / Legado version

3.24.012121

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 pro

**Comment by 821938089** [comment]
链接打不开，文件可以压缩后上传GitHub的

**Comment by zousizhe** [comment]
> 链接打不开，文件可以压缩后上传GitHub的

[crash.zip](https://github.com/gedoor/legado/files/14017569/crash.zip)

**Comment by 821938089** [comment]
为什么换源没有搜索再换源快啊？

搜到书马上停止，不要一直搜，不然用的内存会越来越多
批量缓存先把失效的书弄完在搞，不要一起来

**Comment by 821938089** [comment]
最新版测试版在其他设置增加了记录堆转储功能，你打开它然后下次内存不足崩溃的时候可以压缩一下这个发过来
崩溃后你在关于里点保存日志就会把堆转储复制到备份目录的heapDump文件夹下
