### ISSUE TITLE
通过手动修改书名匹配换源之后，简介无法更换

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3670]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

因为书名问题，多个括号文字，或者拼音，在失效时导致无法匹配其他源，然后调整书名之后可以成功匹配，但是简介无法更换了，使用java.refreshBook() 也无法更换

### 复现步骤 / How to reproduce

修改小说书名之后换源简介无法更换

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.12401

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
把简介全部删掉再保存
