### ISSUE TITLE
在书源的请求头里设置代理不生效

### ISSUE THREAD

**Issue by coulsontl** [gedoor/legado#3671]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题在书源的请求头里设置代理不生效；只有在编辑完的那一刻可能会生效一次，后面就永远不生效了；在书源调试里试了N次也不生效，在代理的日志里根本看不到请求过来，代理地址我用Chrome试了是可以正常使用的，就是放到书源的proxy里不生效，http和sock5都试了没用
![Xnip2024-01-24_10-20-18@2x](https://github.com/gedoor/legado/assets/149155411/2da6937c-8433-46f4-a4af-38eafaeedcbd)

### 复现步骤 / How to reproduce

书源的请求头里设置proxy    {"User-Agent": "xxxx",  "proxy": "http://xxxxxxx:7890"}

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新版本

### Android版本 / Android version

Android14

### 机型 / Model

小米14

**Comment by 821938089** [comment]
检查有没有打开Cronet，要关闭这个

**Comment by coulsontl** [comment]
> 检查有没有打开Cronet，要关闭这个

的确，关了这个选项就好了，赞
