### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xivi1839** [gedoor/legado#3672]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

**建议：阅读app可以考虑增加设置可以弄成像笔趣阁一样，有书城封面的界面吗？**

### 期望实现方式 / How to implement

请看图片。

### 附加信息 / Additions

请看图片。

### 效果演示 / Demo

如图，类似这样，
![001](https://github.com/gedoor/legado/assets/24610024/3ef0258c-72a8-4f01-9d23-af5bc08477c8)
![003](https://github.com/gedoor/legado/assets/24610024/23f23b8d-8da8-4ed2-9384-74eb1b7d0d60)
![004](https://github.com/gedoor/legado/assets/24610024/7517e8ed-e329-4d80-bc3d-62b24c3e45b6)

**Comment by lzb-libra** [comment]
什么时候能出个鸿蒙版呀，不让我收集升级系统后就用不到这么好用的软件了。
