### ISSUE TITLE
当阅读有两个及以上文件下载时，下拉通知栏进度通知，会瞬间来回的切换排序，表面上看一直在闪动

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3674]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

使用订阅源下载文件时，如果通知栏有两条下载通知时会来回切换排序，就算是下载完成之后，也是一跳一跳的，也不知道是不是系统的问题，在小米手机上会有这问题

### 复现步骤 / How to reproduce

下载一个文件之后不去操作，再下载一个文件，通知栏下载进度会闪动

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24

### Android版本 / Android version

Android

### 机型 / Model

Redmi K60 Pro

**Comment by zousizhe** [comment]
https://github.com/gedoor/legado/assets/37259360/fed036f8-18f1-4cf9-bc6e-3ed5e991bc6e

**Comment by 821938089** [comment]
试试最新测试版
