### ISSUE TITLE
朗读模式下切换中英文太麻烦了，希望能有至少两个自定义的TTS设置可以切换

### ISSUE THREAD

**Issue by kulkatt** [gedoor/legado#3675]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

比如我要从中文朗读状态切换到英文朗读状态，要先开始朗读，再点屏幕调出工具栏，再点系统TTS设置，再点语言，再在列表中选中另一种语言，再返回APP，再重新调整语速，对于经常切换中英文朗读的用户来讲实在太繁琐了。

### 期望实现方式 / How to implement

复杂的解决方案，实现双语(多语)朗读，对中英文自动分别调用不同的预设TTS
简单的解决方案，做一个切换TTS语言profile的选项

**Comment by 821938089** [comment]
长按朗读会直接弹出菜单

系统TTS设置是安卓系统的东西
嫌麻烦可以用别的app创建个快捷方式直接进

**Comment by larry801** [comment]
换一个支持自动切换的tts [smartvoice](https://poretsky.github.io/android/smartvoice/)

**Comment by kulkatt** [comment]
> 长按朗读会直接弹出菜单
> 
> 系统TTS设置是安卓系统的东西 嫌麻烦可以用别的app创建个快捷方式直接进

没写过安卓的代码，但是这应该是有方法可以实现的吧？
[https://medium.com/@vedantkingh/unlocking-the-power-of-android-tts-a-guide-to-using-different-languages-and-voices-fe4e6ead2368](url)

3. Set language and voice: To use different languages and voices, you need to specify the desired language and voice using thee setLanguage() and setVoice() methods. You can obtain a list of available voices by calling the getVoices() method. Add the following code snippet to set the language and voice:

private void setLanguageAndVoice() {
    Locale desiredLocale = Locale.US; // Change to the desired language/locale
    tts.setLanguage(desiredLocale);

    Set<Voice> voices = tts.getVoices();
    List<Voice> voiceList = new ArrayList<>(voices);
    Voice selectedVoice = voiceList.get(10); // Change to the desired voice index
    tts.setVoice(selectedVoice);
}

**Comment by kulkatt** [comment]
> 换一个支持自动切换的tts [smartvoice](https://poretsky.github.io/android/smartvoice/)

谢谢，不过在这个页面没找到下载链接

> 换一个支持自动切换的tts [smartvoice](https://poretsky.github.io/android/smartvoice/)

谢谢，不过似乎这个smart voice的可选语音里面并没有中文。。。

**Comment by larry801** [comment]
需要在blindhelp下载
https://blindhelp.net/software/smart-voice

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by larry801** [comment]
还要设置一下语音数据所在目录

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by larry801** [comment]
打开smart voice点击右上角齿轮图标
 general settings
voalizer expressive data folder



获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by larry801** [comment]
是不是路径问题呀 多一层不行
 /storage/emulated/0/voice_data
下面直接是一堆语音才行
要不试试这个精简版只有中英文的
https://we.tl/t-IzymHf7M2L

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by larry801** [comment]
用的是 /storage/emulated/0/VocalizerEx2
把几个中英文声音的 chinesexxxx  文件夹内容移动到 VocalizeEx2 里面看看

________________________________
发件人: ivysrono ***@***.***>
发送时间: 星期三, 二月 14, 2024 12:01:34 上午
收件人: gedoor/legado ***@***.***>
抄送: Larry Wang ***@***.***>; Comment ***@***.***>
主题: Re: [gedoor/legado] 朗读模式下切换中英文太麻烦了，希望能有至少两个自定义的TTS设置可以切换 (Issue #3675)


能把实际那个目录截图给我看下不？

我现在是：

/storage/emulated/0/VocalizerEx2/chinesemandarinlili/……

/storage/emulated/0/VocalizerEx2/chinesemandarintiantian/……

不这样读不出。

―

**Comment by kulkatt** [comment]
> 用的是 /storage/emulated/0/VocalizerEx2 把几个中英文声音的 chinesexxxx 文件夹内容移动到 VocalizeEx2 里面看看
谢谢，弄成了，但是后面还是遇到了问题，可能是那个400多M的包里面语音太多，解决办法是只留中文。
但之后还是遇到了问题，就是静读天下和Legado里面SmartVoice都不识别中文字符，全是按某种西语来读（听不太清楚，还夹杂着刺啦刺啦的噪音，像是德/英/法/俄之一）
