### ISSUE TITLE
关于深色模式和主题模式。

### ISSUE THREAD

**Issue by 550-q** [gedoor/legado#3683]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

偶尔会误触到“正文”界面的“深色模式”按钮，而这会将“我的”-“主题模式”设置一起改变。希望加入一个功能避免这种问题

### 期望实现方式 / How to implement

“主题模式”为”跟随系统“时，在正文界面点击”深色模式“，弹出【当前主题模式为跟随系统，是否改变主题模式】的确认弹窗。

### 效果演示 / Demo

![Screenshot_2024-01-29-23-15-26-492_io legado app release](https://github.com/gedoor/legado/assets/122971571/0b4b7c64-4e2f-45c8-a7ed-7afb214e59f0)

**Comment by asdsa9974** [comment]
👍🏼

**Comment by asdsa9974** [comment]
👍🏼
