### ISSUE TITLE
使用java.refreshBook() 在详情页刷新书名作者需要两次才能成功

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3684]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

书名作者项不一样在需要与详情页书名同步时，打开允许修改书名作者，使用java.refreshBook() 在详情页刷新，已经生效但是还报信息获取失败，第二次正常，从书架下拉更新不会报错。

也有时候第一次刷新无反应，第二次生效但是报获取失败，第三次才正常的，也有遇到第二次生效不报错的，手动修改书名再刷新详情页可以重现，

### 复现步骤 / How to reproduce

在刷新详情信息修改书名作者需要两次操作才能生效

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 pro

**Comment by 821938089** [comment]
你把 java.refreshBook() 填在哪个规则里？

**Comment by zousizhe** [comment]
> 你把 java.refreshBook() 填在哪个规则里？

目录最上面那栏，放别的地方又不生效，而且直接从书架下拉刷新也没问题

**Comment by 821938089** [comment]
发日志看看

**Comment by zousizhe** [comment]
> 发日志看看

保存日志为空，没有记录，可能是因为这个问题不是出错导致，报的也是书籍信息获取失败。
随便找个详情页有书名规则的书源，搜索一本书，再随便改名，或者编辑一下书源使小说获取书名作者不正确，添加到书架，再用那个方法刷新书名，就会重现了，使用老的pro版不会报错，但是也要下拉两次才能调整书名

**Comment by zousizhe** [comment]
> 发日志看看

右上角菜单日志里是  

java.lang.NullPointerException
	at io.legado.app.ui.book.info.u1.invokeSuspend(SourceFile:77)
	at io.legado.app.ui.book.info.u1.invoke(SourceFile:2)
	at io.legado.app.ui.book.info.u1.invoke(SourceFile:1)
	at io.legado.app.help.coroutine.e.invokeSuspend(SourceFile:37)
	at d7.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.m0.run(SourceFile:127)
	at com.bumptech.glide.load.engine.a.run(SourceFile:21)
	at w8.k.run(SourceFile:3)
	at w8.b.run(SourceFile:96)

**Comment by 821938089** [comment]
试试最新测试版
