### ISSUE TITLE
有关兼容Kindle电子墨水屏的APP阅读需求

### ISSUE THREAD

**Issue by tornado404** [gedoor/legado#3686]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

# 背景
需要兼容Kindle电子墨水屏
# 实用性&意义
阅读APP是目前最强大的APP，广大读者应该能够在更加护眼的墨水屏设备上享用这个佳作

### 期望实现方式 / How to implement

请求作者编写一个简单文档，描述“兼容Kindle电子墨水屏”**大致所需工作步骤**，
我想基于这个指南拉取一个分支去进行这方面的开发和编译调整，实现老旧墨水屏设备的重生！

### 附加信息 / Additions

本人是python、golang、Java后端、算法，有github开源项目开发经验，但对安卓开发不了解，喜欢看精品小说
如果作者可以接受这个功能请求，不胜感激

PS：另外我的Kindle kpw3已经刷机了安卓4.4，随机附带了一个阅读app改的“搜神阅读”，可能是书源2.0的规则 ？

**Comment by 821938089** [comment]
你先装个Android Studio然后拉取项目打开，修改build.gradle文件
https://github.com/gedoor/legado/blob/0f0b25f78d2c7c9a596d95bcee122333faa8105d/app/build.gradle#L44
把minSdk改成19，然后构建，然后他会报错，你根据它的报错改就好，基本上就是大量的库降版本，反向迁移代码等等

**Comment by zrwd01** [comment]
同需求。谢谢@gedoor

**Comment by tyf914** [comment]
我有个建议, 不如把 web 服务打开的网页版, 兼容下 kindle , 现在好像已经有些项目这么整了
