### ISSUE TITLE
正文菜单点书名查看详情，不管当前有没有在书架，全都显示已添加

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3687]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

搜索一个小说，还没有添加书架，进正文，调出菜单界面，点顶上的书名，查看详情，显示已经在书架了，再返回时又弹出是否添加书架，也就是并没有在书架

### 复现步骤 / How to reproduce

还未添加的小说在从正文菜单顶上书名查看详情页时也显示已添加到了书架

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
进入阅读时会临时将书添加到书架里，退出再删除
