### ISSUE TITLE
PC端应用程序，后期是否考虑一下

### ISSUE THREAD

**Issue by ANK789** [gedoor/legado#3688]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

后期是否会考虑推出PC端应用程序，期待您的回复；

### 期望实现方式 / How to implement

PC端应用程序，可以先实现windows的

**Comment by Cccc-owo** [comment]
试过[Calibre](https://github.com/kovidgoyal/calibre)吗？

**Comment by ANK789** [comment]
谢谢楼上的老哥，已知悉；
