### ISSUE TITLE
epub导出和识别封面

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3697]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

最新测试版导出epub 没有封面，其他软件也识别不了，后来用正式版导出，其他软件能识别，测试版阅读还是识别不了

### 复现步骤 / How to reproduce

要说原因，可能跟封面图片格式有关吧，我这个是起点的封面，webp格式封面。
![Screenshot_2024-02-03-21-26-42-000_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/ba5ab145-08d3-43e2-8690-2a8fd14e0c2b)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.020221

### Android版本 / Android version

Android13

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
把epub文件发下

**Comment by gyz1023** [comment]
[《火力为王》作者：如水意.zip](https://github.com/gedoor/legado/files/14154502/default.zip)

**Comment by gyz1023** [comment]
![Screenshot_2024-02-04-07-46-28-436_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/04c8d636-b48c-4790-8f48-0c85064df494)
![Screenshot_2024-02-04-07-46-15-957_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/85c8a0f8-3976-41e8-8ab8-0a5c6d329c0c)
导出的文件里就没封面，不知道为啥

**Comment by 821938089** [comment]
epub里没封面文件，你确定这书是有封面的吗，不是默认的那种

**Comment by gyz1023** [comment]
测试版导出有问题，不导出封面，我都试好多遍了，本地的，在线的，各种封面格式，反正最后都没有封面，用正式版的就正常

**Comment by 821938089** [comment]
复现不了，我导出是有封面的啊

**Comment by gyz1023** [comment]
![Screenshot_2024-02-04-15-17-04-213_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/dff5fdd0-426a-4d0c-a9f4-4b583d8e007b)
![Screenshot_2024-02-04-15-17-44-913_io legado app releaseA](https://github.com/gedoor/legado/assets/106790230/6815e9ea-4d53-4275-94ce-d27279492433)
应该跟封面的格式有关，我看了，这种没有后缀的，和后缀是webp的，他这个封面都不进阅读的封面那个文件夹里，明明能正常显示的。总之试试这种封面的源，比如这个起点源https://jt12.de/SYV2_4/2024/02/04/15/19/09/170703114965bf3a6d4b1f8.json

**Comment by 821938089** [comment]
试了，导出是有封面文件的

**Comment by zousizhe** [comment]
> 试了，导出是有封面文件的

试了一下，确实不行，其他源的封面也都不行，020110版本没有问题，pro版本没问题，用的同一套数据最新还原，最新测试版导出的所有epub都没有封面，/OEBPS/Images/cover.jpg不存在

**Comment by zousizhe** [comment]
> 试了，导出是有封面文件的

导出的新文件覆盖旧文件，新生成的文件打不开

**Comment by zousizhe** [comment]
> 试了，导出是有封面文件的

导出的新文件覆盖旧文件，新生成的文件打不开

**Comment by 821938089** [comment]
@zousizhe 不能复现，你是不是没导出完就打开了

最新测试版我加了日志，封面有问题的可以试一下导出书籍然后把日志发过来

**Comment by zousizhe** [comment]
> @zousizhe 不能复现，你是不是没导出完就打开了
> 
> 最新测试版我加了日志，封面有问题的可以试一下导出书籍然后把日志发过来

封面无问题，日志导出的是空文件。epub有时候第二次导出，有时候第三次导出有问题


https://github.com/gedoor/legado/assets/37259360/d7d511cf-6bb3-4fd1-bde3-47dc971cb7eb


https://github.com/gedoor/legado/assets/37259360/2fda08c8-c6e5-4d2c-a92d-f8b41b9c80ba



[样本.zip](https://github.com/gedoor/legado/files/14217728/default.zip)

**Comment by 821938089** [comment]
@zousizhe 试试最新测试版

样本我试了，都可以打开，没有损坏的
