### ISSUE TITLE
使用webview时代理不生效

### ISSUE THREAD

**Issue by coulsontl** [gedoor/legado#3700]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题使用webview时不管是把proxy拼在链接的后面还是放在书源的请求头里都不生效。如:https://www.69xinshu.com/txt/47130/31441485,{'webView': true,'proxy':'http://xcccc:7890@name@password'}

### 复现步骤 / How to reproduce

必现，不使用webview就没有问题，cronet已关闭

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 14

### 机型 / Model

小米14

**Comment by 821938089** [comment]
webview不支持代理
