### ISSUE TITLE
在测试版发现一个bug，百分百复现。“允许下拉刷新”失效

### ISSUE THREAD

**Issue by liufuyou** [gedoor/legado#3702]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在（分组管理）-（编辑分组）-（允许下来刷新）选项取消之后，只要退出阅读APP重进，就会失效，依然可以下拉刷新。
已经取消了，还是下拉刷新
一开始以为是旧的测试版问题。更新到最新测试版本，依旧有这个问题
### 复现步骤 / How to reproduce

（允许下来刷新）选项取消之后，只要退出阅读APP重进，就会依然可以下拉刷新。
![Screenshot_2024-02-07-16-25-17-15_b46d61021eb8d6931849578836530a01](https://github.com/gedoor/legado/assets/47191057/bb39c0f4-c97d-4d49-9221-2b9371478a86)
![image](https://github.com/gedoor/legado/assets/47191057/4acf83a8-31c5-4717-96e6-1b7476586237)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.020519

### Android版本 / Android version

12

### 机型 / Model

真我GT Neo5 SE

**Comment by 821938089** [comment]
已修复
