### ISSUE TITLE
是否考虑添加一个e-ink版本的阅读app？维护周期一年维护一次就行了，应该不会耗费过多的精力

### ISSUE THREAD

**Issue by lv746591263** [gedoor/legado#3703]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

就是墨水屏版本的阅读，主要是希望去除正式版本的一些动画，你看起点小说app都出了个墨水屏版本的，我用文石leaf3上看到的，大佬要不阅读app也搞一个怎么样？因为看书会使用残影较少的模式，但是，这时使用阅读，动画会特别的闪屏，就类似用这种模式看漫画一样闪的眼睛痛的感觉，希望加个墨水屏版本，谢谢！

### 期望实现方式 / How to implement

去除读书时点开中间弹出菜单过程中的动画，如果支持目录也通过音量键翻页那就更好了，当然这个不会太影响

**Comment by 821938089** [comment]
使用墨水屏主题模式
