### ISSUE TITLE
观看epub资源时简繁转换“『″变为引号

### ISSUE THREAD

**Issue by 709721** [gedoor/legado#3704]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

繁转简中『』会变成＂＂ 不确定其他符号是否也会有此状况 也不确定网络资源是否会出现此情况 不过简转繁正常

### 复现步骤 / How to reproduce

开启繁体转为简体

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 7.1.1

### 机型 / Model

OPPO A83

**Comment by 821938089** [comment]
这个是繁体的双引号，转成简体之后就是常见的双引号了
