### ISSUE TITLE
真白萌登录过不了cloudflare检测

### ISSUE THREAD

**Issue by YURICORN** [gedoor/legado#3712]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

真白萌https://masiro.me/ 登录过不了cloudflare检测，没开vpn，另外浏览器是可以过的

### 复现步骤 / How to reproduce

真白萌https://masiro.me/ 登录过不了cloudflare检测

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.020919

### Android版本 / Android version

android 12

### 机型 / Model

redmi k30 ultra

**Comment by 821938089** [comment]
UA问题，你自己改个正确的就可以了

**Comment by huisehuiyi** [comment]
更改UA后确实可以登录，但是无法更新小说目录。会显示获取正文失败，内容为空
