### ISSUE TITLE
希望能像“静读天下”那样，除翻页之外的任何方式“跳章”按返回都能提示是否回到原来阅读的位置

### ISSUE THREAD

**Issue by 550-q** [gedoor/legado#3713]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望能添加像“静读天下”那样，除翻页之外的任何方式“跳章”后，按返回都能提示是否回到原来阅读的位置。
看书翻阅前面读过的内容应该算是看书的人都有的，比较普遍的操作，偶尔还会往后跳章提前翻阅后面的内容，每次这样操作时想要找回原来读的位置还得去翻目录才行，希望可以添加“静读天下”那种返回方式。

### 期望实现方式 / How to implement

希望能像“静读天下”那样，无论是目录跳章、还是点下一章、拖动进度条、跳到搜索内容位置，只要不是正常的翻页的操作，都会记录每次“跳转”前的位置，按返回键就可以弹出弹窗选择想要回到的位置。

### 效果演示 / Demo

![IMG_20240213_015257](https://github.com/gedoor/legado/assets/122971571/dc2d938e-a638-43ae-9f70-1794ad6cd72f)

**Comment by asdsa9974** [comment]
👍🏼

**Comment by asdsa9974** [comment]
👏🏻

**Comment by Antecer** [comment]
这个建议好
