### ISSUE TITLE
通用封面规则

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3715]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

通用封面规则是不是失效了，最新稳定版就有这问题了，测试版也一样，还琢磨半天以为规则变了呢，换了老版本的，马上就生效了，新版本一点反应没有

### 复现步骤 / How to reproduce

新版本，开了通用封面规则，进详情页不自动换封面

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.021305

### Android版本 / Android version

Android13

### 机型 / Model

k40s

**Comment by 821938089** [comment]
没有封面地址才会自动换封面

**Comment by gyz1023** [comment]
原来改逻辑了，好吧，我自己改书源吧，主要还是正版网站封面清晰，好在琢磨半天也弄出来了
