### ISSUE TITLE
最新测试版有正文一定机率会空白

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3717]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

有一定机率进到正文就空白，有时候没有加载过程，直接空白，有时候显示加载1秒左右再变空白，任何书源都有机率触发，不需要添加到书架

另外，日志导出老报错

https://github.com/gedoor/legado/assets/37259360/7adc87d4-67a7-459d-bd9b-7efa51509492

https://github.com/gedoor/legado/assets/37259360/a446ac21-131e-467b-8310-80be3726ead6

[日志.zip](https://github.com/gedoor/legado/files/14274349/default.zip)

### 复现步骤 / How to reproduce

随机的在搜索或分类里进到任意的书源，有时候一两次触发，有时候10来本才触发

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.021407

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 Pro

**Comment by zousizhe** [comment]
不只是在线小说，连缓存好的小说，都有机率进入空白，翻一頁再翻回去，或者退出重新进入，要不就重载内容才恢复

**Comment by zousizhe** [comment]
不只是在线小说，连缓存好的小说，都有机率显示空白，换个界面再切换回去就又正常，比如退出重进，翻页再翻回去，或者刷新正文

**Comment by 821938089** [comment]
试试最新测试版
