### ISSUE TITLE
最新测试版书源无法调试

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3718]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

书源可以正常搜索，但是调试界面无法进行，一直在打转，昨天的版本0213正常

### 复现步骤 / How to reproduce

调试任意书源都无法继续

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.021407

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
试试最新测试版
