### ISSUE TITLE
最新测试版朗读字数超过限制，会导致朗读出错和错乱

### ISSUE THREAD

**Issue by xyzz2001** [gedoor/legado#3720]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

这个问题在一些字数非常多的轻小说非常明显
比如浏览到的是60页，朗读的却是前面或者后面的内容，或者是字数超过之后出现以下报错。
Index -2 out of bounds for length 993

### 复现步骤 / How to reproduce

找一个一张小说字数非常多的书源，例如哔哩轻小说。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

Index -2 out of bounds for length 993
启动朗读注出错

### 阅读版本 / Legado version

3.24.021305

### Android版本 / Android version

14

### 机型 / Model

小米13p

**Comment by 821938089** [comment]
你点一下这条日志把详细堆栈发一下

**Comment by 821938089** [comment]
试试最新测试版
