### ISSUE TITLE
按特定内容片段筛选书源？

### ISSUE THREAD

**Issue by Azuresonance** [gedoor/legado#3721]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现在很多书源内容错误很多，而且多个书源经常互相共享错误内容，因此希望能够自动对这些错误书源进行筛选。
我在用legado之前，在网页上读书，都是这样解决的：
1. 遇到一个特定的错句，例如“小明今天打开了方盗闩”
2. 购买单章官方正版，获取正确句子“小明今天打开了防盗门”
3. Google精确搜索“小明今天打开了防盗门”，找到一个包含此句子的，就是正确书源
4. 直接在网站上阅读

以上方法可行的原因是绝大部分书源都会共享内容，导致错误的句子完全一样，所以基本上这个句子正确的话，书源就是高质量的。

但是在legado中阅读的话，没有这样的功能实现第3步。因此我必须手动逐个查看所有书源，以求找到一个正确的。绝大部分书源都会共享完全一样的错误。
因此希望能够有一个根据”内容是否包含特定句子“筛选书源的功能。

### 期望实现方式 / How to implement

对于当前书籍可用的所有书源，自动筛选包含某个特定正确内容片段（例如句子“小明今天打开了防盗门”）的书源。
然后或许可以通过置顶的方式展现给用户。

**Comment by VeleSila** [comment]
以目前的设计不可能实现的。目前的设计是按照书名或者作者搜索，这样可以直接调用网站自带搜索引擎。**最重要的是达成这一切还需要有热心人编写手动规则去适配每一个小说网站**(也就是书源)。

而你提的要求需要用公共搜索引擎，再**反向跟踪得到网站本身，再_自动_编写规则**。如果能达到这一步，那根本不需要人去更新和维护书源了。它也许可以通过AI实现，不过你这恐怕得有_免费且可以无限量使用的AI做支持_。就算乐观去看，10年内应该都达不到。
