### ISSUE TITLE
有个奇怪问题，遇到敏感词会有明显的空格隔开

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3726]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

像内裤，色情这类的词，会有明显的空格与其他内容间隔，但是在编辑内容里看原始文本却并没有出现空格，选中复制能感觉到有一个空格，但是粘贴出来却没有，默认的微信读书排版不会这样，其他排版或者自建排版都会这样，排除是净化，字体，简繁转换与书源问题。如果把一堆敏感词连到一起写成一行，却不会出现这问题。
默认的微信读书改名或者换字体都不会变化，只要切换成其他排版，就会有这问题

### 复现步骤 / How to reproduce

这打扮很‌色‌‎‎情

上述语句做成txt文本用阅读打开，从很旧的版本到最新测试版都这样

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24

### Android版本 / Android version

Android

### 机型 / Model

Redmi K60 Pro

**Comment by zousizhe** [comment]
发现静读也这样，不知道是不是webview的问题，但是阅读默认微信读书排版却又不这样，不知道是哪的问题

**Comment by 821938089** [comment]
发图看看

**Comment by zousizhe** [comment]
> 发图看看

![Screenshot_2024-02-18-20-43-11-001_io legado app releaseA](https://github.com/gedoor/legado/assets/37259360/5e0a25b2-db13-4824-bc4a-8ac4e3d5f808)


微信读书的排版也没能避免，只不过是字距看不出来，把字距调大就明显了，把字距调成负的时候也是这个间隔词先粘连到了一起，其他字还未粘连
![Screenshot_2024-02-18-20-42-55-065_io legado app releaseA](https://github.com/gedoor/legado/assets/37259360/27db9999-4ea7-4ade-99d5-82743a351ab9)

**Comment by 821938089** [comment]
这段文字里有不可见字符

![image](https://github.com/gedoor/legado/assets/8674809/220b2611-cbd3-4b66-8eac-49b78f0f26bb)
