### ISSUE TITLE
背景音乐

### ISSUE THREAD

**Issue by coco-hkk** [gedoor/legado#3728]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

语音朗读时能够设置背景音乐。
背景音乐可独立调节音量。

### 期望实现方式 / How to implement

朗读小说的同时设置背景音乐，背景音乐不能影响朗读，可以独立的调节音量。
忽略音频焦点不能实现独立调节音量需求，不能满足背景音乐需求。

**Comment by 821938089** [comment]
如果你是MIUI的话系统可以单独调节每个应用的音量

**Comment by VeleSila** [comment]
背景音乐功能已经脱离了一个阅读器的范畴了。建议用独立音乐播放器而不是来这里提与核心功能不相关的需求。
