### ISSUE TITLE
我现在在开发ios版本的阅读，遇到一些源规则的问题，希望得到帮助

### ISSUE THREAD

**Issue by baobao9999** [gedoor/legado#3734]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现在大部分解析规则都调通了，就差@js: 这块的解析问题。   如果可以的话，希望可以得到的帮助。
最近换了电脑，安装Android Studio的后，安卓阅读代码也编译失败了，也希望得到帮助

### 期望实现方式 / How to implement

希望得到了解安卓阅读代码的帮助。可以通过telegram联系交流

**Comment by 821938089** [comment]
啥解析问题，js这部分在ios很难做兼容的，阅读的js可以调用java的东西，ios没java环境

**Comment by wangxiaolong1234555** [comment]
会用object C吗？用这个技术栈写ios版的应该容易吧？
