### ISSUE TITLE
深色模式/浅色模式切换后 阅读界面看不清字

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#3735]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

先切换夜间模式，然后重启App界面能看清字

在阅读界面切换深色模式，看不清字

### 复现步骤 / How to reproduce

* 打开阅读界面
* 界面-选择预设主题-微信读书
* 点击深色模式，字会看不清

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.022006

### Android版本 / Android version

Android 11

### 机型 / Model

Iqoo

**Comment by 821938089** [comment]
试试最新测试版

**Comment by Xwite** [comment]
https://github.com/gedoor/legado/commit/51673357e9bcf037c0fb61700f9b5713a8669952 fixed
