### ISSUE TITLE
能否考虑增加两个功能呢？

### ISSUE THREAD

**Issue by HYHHYHHYHHYHHYHHYHHYHHYH** [gedoor/legado#3740]
### 确认 / Assignments

- [x] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

1.订阅里面能否添加排序？可以参考书源界面的排序
2.搜索书源或者更换书源时能否在顶部书名或者作者名后添加实时搜索到的数量？

### 期望实现方式 / How to implement

期望

### 附加信息 / Additions

没了

**Comment by HYHHYHHYHHYHHYHHYHHYHHYH** [comment]
[](url)

**Comment by idiomer** [comment]
订阅添加自定义排序+1
订阅要是可以平铺文件夹就更好了，不是现在的标签筛选
