### ISSUE TITLE
翻页动画为滚动时，两页之间的段距跟设置的不一样

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#3746]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题

### 复现步骤 / How to reproduce

如题

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

![IMG_20240224_163830](https://github.com/gedoor/legado/assets/104120418/874a7f6e-21fb-42ba-9370-6daadae6a70c)

### 阅读版本 / Legado version

3.24.022416

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 11

**Comment by 821938089** [comment]
这里是两页之间吗，你换个翻页动画看看

**Comment by iyhkhtrk** [comment]
> 这里是两页之间吗，你换个翻页动画看看

https://github.com/gedoor/legado/assets/104120418/45f6a809-818f-4c0a-a637-c7b82602eed3
