### ISSUE TITLE
在安卓14上无法显示锁屏通知,请尽快解决一下,锁屏不能点击暂停很不方便

### ISSUE THREAD

**Issue by tick-guo** [gedoor/legado#3747]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

1.  无法弹出通知的权限申请窗口, 这个直接从系统通知里手动开启后,通知栏能显示语音朗读通知了.
2. 但是还是**无法在锁屏界面显示朗读播放的按钮通知**, 系统通知设置里能开的都开了.

### 复现步骤 / How to reproduce

锁屏不能显示朗读控制通知

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

无

### 日志提交 / Relevant log output

无

### 阅读版本 / Legado version

legado_app_3.23.110211

### Android版本 / Android version

Android 14

### 机型 / Model

iqoo neo7 竞速版

**Comment by 821938089** [comment]
锁屏不能显示是通知设置问题，你找找相关设置

**Comment by 821938089** [comment]
你把这些选项都全部开关一遍然后重新打开软件试试

**Comment by tick-guo** [comment]
还是不行

@821938089

**Comment by tick-guo** [comment]
![Uploading Screenshot_20240816_011329.jpg…]()
![Uploading Screenshot_20240816_011327.jpg…]()
![Uploading Screenshot_20240816_011310.jpg…]()
![Uploading Screenshot_20240816_011255.jpg…]()
![Uploading Screenshot_20240816_011248.jpg…]()
![Uploading Screenshot_20240816_011237.jpg…]()

**Comment by tick-guo** [comment]
![Uploading Screenshot_20240816_011329.jpg…]()

**Comment by tick-guo** [comment]
![Uploading mmexport1723743019448.png…]()

**Comment by tick-guo** [comment]
![mmexport1723743019448](https://github.com/user-attachments/assets/7323b46d-196f-4b14-aff8-8e51e1123133)

能解决一下这个问题不！？

**Comment by tick-guo** [comment]
怎么重新打开问题
