### ISSUE TITLE
TXT文本中img标签只能解析http和https连接，希望添加本地路径解析

### ISSUE THREAD

**Issue by mona-aliye** [gedoor/legado#3748]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望能在TXT文本中够解析如<img src="./img.jpg">的标签

### 期望实现方式 / How to implement

在解析标签功能中添加解析本地图片的内容

**Comment by 821938089** [comment]
你可以把txt做成epub，这样就可以显示图片了
