### ISSUE TITLE
墨水屏手机使用阅读软件后的一个建议

### ISSUE THREAD

**Issue by lrf6997** [gedoor/legado#3750]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

自从使用了海信A5墨水屏手机，发觉使用任何阅读软件都有残影留着屏幕（使用流畅模式，没有使用清晰模式，清晰模式翻页比较闪，晃眼的很）。偶然在贴吧发现有个吧友说【安装微信读书的正常版本，流畅模式，看书的时候点到分享，然后返回到正常阅读，从此再也没有残影，效果杠杠滴】，我下载试了一下，发觉真的有效果，然后我按他方法操作后，再切换到我们这个“阅读”，发觉也没有残影了。美中不足的地方就是手机要开着“微信读书”这个软件，一旦我锁屏后再打开看小说就会有残影了，就要切换到“微信读书”这个软件去操作一遍，比较麻烦。

### 期望实现方式 / How to implement

期望大佬可以在阅读软件添加一个这种模块，以期达到没有残影的效果。（具体是啥原因导致这个没有残影，我也不懂的）

**Comment by 821938089** [comment]
有可能是背景的原因，你可以试试打开一下日志然后关掉

**Comment by lrf6997** [comment]
楼上这个办法也可以，日志这里只是一小块，如果这个框可以整个屏幕是全白，就更理想了。或者在墨水屏主题模式下增加一个这样的按键就好了！

**Comment by 821938089** [comment]
背景不本来就是全白的吗，还要全白干嘛，你要全白的话自己找张白色图片放一下就可以了，墨水屏一般都有刷新功能的吧，你可以用那个刷新

**Comment by lrf6997** [comment]
不一样的。

**Comment by fjfhukh** [comment]
我使用的是海信A5 ProCC墨水屏手机,，在使用这款阅读APP时，在阅读小说模式下，把手机调成清晰模式，然后再改成流畅模式，屏幕的残影就没有了，手机熄屏后，再亮屏，屏幕依然没有残影，没有测试关机再开机后屏幕有没有残影，因为我的手机几乎没有关机过。

**Comment by fjfhukh** [comment]
墨水屏手机屏幕是利用电场的改变，使屏幕中有着黑白两色的微小颗粒改变在屏幕上显示的颜色，是一种机械过程，所以响应慢，流畅模式没有给这微小颗粒足够翻转的时间，所以屏幕上会有残影存在。

**Comment by lrf6997** [comment]
回复[fjfhukh]，我使用的是海信A5，按照你的方法，我试过了，还是一样有残影。我不是说阅读APP的问题，是看到“微信读书”软件按照那人方法操作后更没有残影，所以希望阅读APP增加一个这个模块而已。
