### ISSUE TITLE
书源导入时java.lang.String报错

### ISSUE THREAD

**Issue by wtm2001** [gedoor/legado#3759]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

同一个书源，同样的软件版本，在OnePlus7T这款机型上导入书源失败，在K30S，K20Pro两款机型上均能正常导入
[2.26最新精校阅读书源更新2905.json](https://github.com/gedoor/legado/files/14408704/2.26.2905.json)

### 复现步骤 / How to reproduce

![0687d459da0ab87706c227cef8563fd3](https://github.com/gedoor/legado/assets/57321330/2f3fa16b-8b59-4cd4-94b8-28f67780421b)
问题机型

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

安卓11

### 机型 / Model

OnePlus7T

**Comment by wtm2001** [comment]
报错信息如图
![a2ff81d262c002e8cee3e6fce5895da8](https://github.com/gedoor/legado/assets/57321330/2b20fc55-2f80-4835-8f68-03cd65539352)

**Comment by 821938089** [comment]
打开日志点一下那条日志把报错信息发过来
