### ISSUE TITLE
最新测试版所有书源章节标题显示不全，未开净化

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3761]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

有章节名的，目录标题完整，正文章节标题只能显示最后几个字.试过几个书源都这样

### 复现步骤 / How to reproduce

只要小说章节有标题名的都这样，第x章，纯数字标题的正常

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.022703

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
发图看看

**Comment by zousizhe** [comment]
> 发图看看



> 试试最新测试版

最新版正常了
