### ISSUE TITLE
TTS中speakSpeed的取值范围不对

### ISSUE THREAD

**Issue by OdinZhang** [gedoor/legado#3762]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

speakSpeed的取值范围疑似变成5-50了，帮助文档没有更新

### 复现步骤 / How to reproduce

我在使用xiaoxiao的源的时候自己加了语速配置，官方的说明是0.5-2，1为正常语速，按照说明，阅读内正常语速speakSpeed应为5
![image](https://github.com/gedoor/legado/assets/25601078/f497f17d-75a0-48bd-9831-72e1b2f6e9ce)
因此改动后的代码如下：
```xml
<prosody rate='{{String(Math.min((speakSpeed+5)/10,2))}}'>{{speakText}}</prosody>
```
此时使用默认语速应当输出1，但是实际使用中，需要设为`Math.min(speakSpeed/10,2)`才是正常语速

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 14

### 机型 / Model

Google Pixel 7

**Comment by 821938089** [comment]
已更新帮助文档

**Comment by OdinZhang** [comment]
> 已更新帮助文档

最新的文档在哪里，我看[httpTTSHelp](https://github.com/gedoor/legado/blob/d2030ee89c2f6e0b4bbfb0b250fd7c5e6724e581/app/src/main/assets/help/httpTTSHelp.md)中还是0-45
