### ISSUE TITLE
在书籍信息页右上角三个点按钮中添加缓存按钮

### ISSUE THREAD

**Issue by Sun-QAQ** [gedoor/legado#3768]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前的缓存按钮在书籍管理中，添加书籍之后还需要到书籍列表中去缓存。
在书籍信息页右上角三个点按钮中添加缓存按钮后，可以添加书籍后里面进行缓存。

### 期望实现方式 / How to implement

在书籍信息页右上角三个点按钮中添加缓存按钮

**Comment by 821938089** [comment]
阅读界面里也可以缓存
