### ISSUE TITLE
再次建议增加这个功能

### ISSUE THREAD

**Issue by fjfhukh** [gedoor/legado#3769]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

我们在使用阅读APP时横竖屏切换不是多么常用，但是这个功能是必不可少的，如果屏幕方向选择跟随系统或者跟随传感器，我们需要切换横竖屏时，只需要把手机横放或者竖放，就能方便的切换横竖屏，很方便，但是有时候手机横放或者竖放时，并不是都需要切换横竖屏，这时候屏幕方向选择跟随系统或者跟随传感器，就不需要了，但是把屏幕方向手动选择横屏或者竖屏，切换成竖向或者横向就有点不快捷了，所以建议在点击区域设置的选择操作中增加“横竖屏切换”选项，这样就可以让有这个需求的书友，把某个点击区域设置的选择操作中设置成“横竖屏切换”选项，当屏幕方向设置成横屏或者竖屏时，可以在需要切换横竖屏时，只需要点击设定“横竖屏切换”的区域，快捷的切换横竖屏了！当屏幕方向选择跟随系统或者跟随传感器，手机横放或者竖放，仍然可以自动切换横竖屏，我感觉这个功能非常实用。

### 期望实现方式 / How to implement

建议在点击区域设置的选择操作中增加“横竖屏切换”选项，这样就可以让有这个需求的书友，把某个点击区域设置的选择操作中设置成“横竖屏切换”选项，当屏幕方向设置成横屏或者竖屏时，可以在需要切换横竖屏时，只需要点击设定“横竖屏切换”的区域，快捷的切换横竖屏了！当屏幕方向选择跟随系统或者跟随传感器，手机横放或者竖放，仍然可以自动切换横竖屏。

### 附加信息 / Additions

无

### 效果演示 / Demo

![点击区域设置1](https://github.com/gedoor/legado/assets/53828408/72761dea-35ae-46d5-a125-2f8e97bf1634)
![点击区域设置](https://github.com/gedoor/legado/assets/53828408/29d9ae41-ac57-4ee5-af98-9245df2ff0b4)
![选择操作](https://github.com/gedoor/legado/assets/53828408/39dc15fe-19f7-4196-ad78-bf7ce7917aa2)

**Comment by fjfhukh** [comment]
有没有书友需要我建议的这个功能，有需要的书友顶一下！

**Comment by Discut** [comment]
就是仅仅需要一个手动切换横竖屏的功能？

**Comment by fjfhukh** [comment]
> 就是仅仅需要一个手动切换横竖屏的功能？

虽然仅仅需要一个手动切换横竖屏的功能，但是按归我这个功能就方便快捷的多，而且“点击区域设置”中的点击区域基本上就用不了这么多区域，比如：上一页和下一页根本就不需要设置在“点击区域设置”中，因为我们可以通过手指左右滑动屏幕实现翻页就非常方便，而且不容易无意中的翻页。如果我们在“点击区域设置”中设置了上一页和下一页，无意中碰触了设置了上一页和下一页的区域，就会造成错误的翻页。所以，我从来不把上一页和下一页设置在“点击区域设置”中，也更不喜欢使用那些取消不了点击屏幕就翻页的阅读类的APP，之前我使用的是搜书大师，也只可以取消通过点击屏幕翻页的功能，只有通过左右滑动屏幕翻页的功能最可靠，所以我的手机屏幕还有很多点击区域都设置成了无操作面闲置，我提议的这个功能正好可以增加到且“点击区域设置”中。
