### ISSUE TITLE
测试版使用tts时向上翻页会闪动

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3779]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在使用tts朗读时往回翻页会有字体闪动，往下翻页不会

### 复现步骤 / How to reproduce

启动tts朗读或者暂停朗读，向上翻页

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.030116

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
录个视频看看

**Comment by zousizhe** [comment]
> 录个视频看看

https://wwm.lanzov.com/iObsk0j0tn3a

**Comment by 821938089** [comment]
视频不对吧？和这个问题没关系啊

**Comment by zousizhe** [comment]
> 视频不对吧？和这个问题没关系啊

闪的还非常快，录屏帧数低了还捕捉不到

**Comment by zousizhe** [comment]
> 视频不对吧？和这个问题没关系啊

使用逐帧查看闪动，是在翻到上一页与上二页来回跳动了一次

**Comment by 821938089** [comment]
试试最新测试版
