### ISSUE TITLE
能否在列表中显示每本书的最后更新时间?

### ISSUE THREAD

**Issue by hamwong** [gedoor/legado#378]
能否在列表中显示每本书的最后更新时间? 另外能否在点作者名时能只搜索作者, 而不是全搜?

**Comment by Celeter** [comment]
阅读只能做到把结果过滤，搜索是网站的事，阅读控制不了

**Comment by h11128** [comment]
可以全搜然后过滤搜索结果只有作者

**Comment by Antecer** [comment]
搜索栏勾选“精准搜索”，能够暂时缓解一下 作者 搜索的问题。
后续可能考虑从书源规则解决这个问题，软件不会使用筛选的方式实现，一旦书源过多会造成严重卡顿。

**Comment by hamwong** [comment]
两年过去了, 虽然已有**更新时间**, 但不太实用, 能否在这里也显示, 如果源有提供, 则引用源的最后时间, 如果源没有, 就以本地取得更新的时间为准, 显示 多少 **秒/分钟/小时/天前** 有更新?
<img src="https://i.ibb.co/rvSwWF7/cap.jpg" alt="cap" border="0">

**Comment by 821938089** [comment]
这样搞数据更新太频繁了
而且还有一个很现实的问题：不能让所有人都满意，你满足了，别人就会有意见，改来改去的真没意思

**Comment by hamwong** [comment]
> 这样搞数据更新太频繁了 而且还有一个很现实的问题：不能让所有人都满意，你满足了，别人就会有意见，改来改去的真没意
我个人觉养书时很有用, 有这个功能可以一眼看出书有没有太监, 再说也可以在设置中决定是否显示,
至于"数据更新太频繁了", 我就不明白了, 要是不查书本更新, 就不会有"数据更新", 如果查了就多一个最后更新的时间, 都是顺带的事, 有增加"数据更新"吗?

**Comment by 821938089** [comment]
你这个

**Comment by 821938089** [comment]
你这个时间难道更新完书架就不动了吗，例如更新完显示0s前，那不更新的话永远都是0s前啊，这不就需要每秒都更新一次让他变成1s前2s前吗

**Comment by Antecer** [comment]
> 两年过去了, 虽然已有**更新时间**, 但不太实用, 能否在这里也显示, 如果源有提供, 则引用源的最后时间, 如果源没有, 就以本地取得更新的时间为准, 显示 多少 **秒/分钟/小时/天前** 有更新? ![cap](https://camo.githubusercontent.com/2b9311ecd902e2fd0bd691fe2c1fe9259139ac96847ddc122907623103170911/68747470733a2f2f692e6962622e636f2f727653775746372f6361702e6a7067)

其实没必要显示 多少时间前的，直接弄成 xxx年月日时分秒 更新就行了，后续刷新有新章节就覆盖时间，没有新章节就保持不变。

**Comment by 821938089** [comment]
刚加上了，下个版本就有了，或者测试版
