### ISSUE TITLE
可以导入calibre-web书源吗

### ISSUE THREAD

**Issue by hausen1012** [gedoor/legado#3783]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

导入calibre-web书源

### 期望实现方式 / How to implement

可以阅读pdf

**Comment by 821938089** [comment]
阅读可以打开pdf

**Comment by mslxl** [comment]
支持calibre和calibre-web实际上就是支持 opds协议，感觉可以用现有的书源中的js去实现

考虑opds实际上还是有部分应用，也许可以在添加书源的地方增加一个“从opds中添加”按钮来根据书源模板生成并添加书源

正巧我也有对应的需求，有时间的话我可以折腾看看

**Comment by hausen1012** [comment]
> ~支持calibre和calibre-web实际上就是支持 opds协议，感觉可以用现有的书源中的js去实现~
> 
> 感觉做的十分有限
> 
> 因为没有 opds 没有详情页的，而似乎 legado 只能从详情页获取文件下载地址，因此拿了一个echo 服务器伪装详情页来获取文件的下载地址
> 
> 此外因为opds里的发现有二级页面，但 legado 没有，除了把opds中所有的二级页面爬一遍后都放到一级之外应该没有别的办法了，但全爬一遍有点太慢了
> 
> 还有因为 calibre-web 登录后没有使用http头中的 `Cookie` 而是 `Authorization`，我不太清楚这该怎么写登录
> 
> **感觉如果走 opds 的话基本上没法用，有时间我再试试爬网页吧，不过可以确定的是使用 calibre-web 书源是可以自己写书源实现的**
> 
> 以下是失败的代码，如果要执意用的话需要把`http://nas.domain.com:8084`替换成自己的calibre-web的主机，并手动登录后设置`header.Authorization`
> 
> ```json
> {
>     "bookSourceName": "Calibre",
>     "bookSourceType": 3,
>     "bookSourceUrl": "http://nas.domain.com:8084",
>     "customOrder": 0,
>     "enabled": true,
>     "enabledCookieJar": true,
>     "enabledExplore": false,
>     "exploreUrl": "@js:(function(){\n// not available for opds with legado\nvar doc = java.ajax('http://nas.domain.com:8084/opds');\ndoc = org.jsoup.Jsoup.parseBodyFragment(doc)\nvar entries = doc.select(\"entry\");\nvar discovery = ''\nfor(var item in entries){\ndiscovery += entries[item].select('title').text()\ndiscovery += \"::\"\ndiscovery += entries[item].select('id').text()\ndiscovery += '\\n'\n}\nreturn discovery;\n})()",
>     "header": "{\n\"Authorization\": \"\"\n}",
>     "lastUpdateTime": 0,
>     "loginUi": "nas.domain.com:8084",
>     "loginUrl": "nas.domain.com:8084",
>     "respondTime": 180000,
>     "ruleBookInfo": {
>         "downloadUrls": "@css:link[rel=\"http://opds-spec.org/acquisition\"]@href@js:(function(result){\nvar arr = [];\nfor(let v in result){\narr.push(\"http://nas.domain.com:8084\" + result[v]);\n}\nreturn arr;\n})(result)",
>         "init": "@js:(function(result){return java.base64Decode(JSON.parse(result)['parsedQueryParams']['content'].toString()); })(result)"
>     },
>     "ruleContent": {},
>     "ruleExplore": {},
>     "ruleReview": {},
>     "ruleSearch": {
>         "author": "@css:author>name@text",
>         "bookList": "@css:entry",
>         "bookUrl": "@js:(function(resutl){ return \"https://echo.free.beeceptor.com?content=\" + java.base64Encode(result); })(result)",
>         "checkKeyWord": "haskell",
>         "coverUrl": "@css:link[rel=\"http://opds-spec.org/image/thumbnail\"]@href",
>         "intro": "tag.summary.0@text",
>         "kind": "@css:category@label",
>         "lastChapter": "@css:updated@text",
>         "name": "@css:title@text",
>         "wordCount": ""
>     },
>     "ruleToc": {},
>     "searchUrl": "/opds/search/{{key}}",
>     "variableComment": "",
>     "weight": 0
> }
> ```
> 
> 另外在 github 上有关自定义书源的文档似乎都404了 😢

辛苦大佬了，感谢。有时间我试试

**Comment by mslxl** [comment]
如果是 calibre-web 的话用这个吧，不走 opds 从网页上抓

只需要把 bookSourceUrl 改成自己的机子就好

```json
{
    "bookSourceUrl": "http://192.168.1.128:8084",
    "loginUrl": "/login",
    "ruleSearch": {
        "checkKeyWord": "抽象代数",
        "bookList": "@css:div.book",
        "name": "@css:p[title]@text",
        "author": "@css:a.author-name@text",
        "coverUrl": "@css:img[src]@src",
        "bookUrl": "@css:div.cover>a@href"
    },
    "ruleBookInfo": {
        "name": "@css:.book-meta>h2@text",
        "author": "@css:.book-meta>.author>a@text",
        "kind": "@css:.tags a.btn@text",
        "intro": "@css:.comments>div@text",
        "lastChapter": "@css:.publishing-date@text",
        "downloadUrls": "class.book-meta.0@class.btn-group.0@children@class.btn-group.0@tag.a@href@js:(function(args){\njava.log(args)\nlet links = []\nfor(var k in args){\n    if(args[k].startsWith('/download'))\n        links.push(args[k])\n}\nreturn links\n})(result)"
    },
    "ruleToc": {
        "nextTocUrl": "@css:li.page-next>a.next@href"
    },
    "ruleContent": {},
    "ruleReview": {},
    "ruleExplore": {
        "bookList": "@css:.load-more div.book",
        "name": "@css:p[title]@text",
        "author": "@css:a.author-name@text",
        "coverUrl": "@css:img[src]@src",
        "bookUrl": "@css:div.cover>a@href"
    },
    "bookSourceType": 3,
    "bookSourceName": "Calibre-Web",
    "searchUrl": "/search/stored/1/{{page}}?query={{key}}",
    "loginCheckJs": "",
    "exploreUrl": "@js:(function(){\n    let discovery = []\n    let doc = org.jsoup.Jsoup.parse(java.ajax(baseUrl))\n    let items = doc.select(\".navigation>ul a\")\n\n    function generateDiscoveryFromSecondary(pageSource){\n        let page =org.jsoup.Jsoup.parse(pageSource)\n        let items = page.select(\".container .row a\")\n        if (items.length == 0){\n            return []\n        }\n        let result = []\n        for(let i = 0; i < items.length; i++){\n            let e = items[i]\n            let href = e.attr('href')\n            // 可翻页\n            if(href.match(/\\/\\d+$/)){\n                href += '/{{page}}'\n            }\n            result.push({\n                title: e.text(),\n                url: href,\n                style: {\n                    layout_wrapBefore: i == 0\n                }\n            })\n        }\n        return result\n    }\n    function isSecondaryList(pageSource){\n        return generateDiscoveryFromSecondary(pageSource).length != 0\n    }\n    for(let key in items){\n        let href = baseUrl + items[key].attr(\"href\")\n        let pageSource = java.ajax(href)\n        let secondary = isSecondaryList(pageSource)\n        // 可翻页\n        if(href.match(/\\/\\d+$/)){\n            href += '/{{page}}'\n        }\n        discovery.push({\n            title: items[key].text(),\n            style: {\n                layout_flexGrow: 1,\n                layout_alignSelf: \"stretch\",\n                layout_flexShrink: 0,\n                layout_wrapBefore: true,\n            },\n            url: isSecondaryList(pageSource) ? undefined : href\n        })\n        if(secondary){\n            for(let e of generateDiscoveryFromSecondary(pageSource)){\n                discovery.push(e)\n            }\n        }\n      \n    }\n    return JSON.stringify(discovery)\n})()",
    "enabled": true,
    "enabledExplore": true,
    "enabledCookieJar": true
}
```

**Comment by liuqq58** [comment]
能支持opds协议就最好了，目前安卓好用，能用的还支持opds协议的几乎没有，仅有的还需要汉化，还不完整，而且还巨不好用，和阅读的阅读体验差太远了

**Comment by Halecoder** [comment]
> 如果是 calibre-web 的话用这个吧，不走 opds 从网页上抓
> 
> 只需要把 bookSourceUrl 改成自己的机子就好
> 
> ```json
> {
>     "bookSourceUrl": "http://192.168.1.128:8084",
>     "loginUrl": "/login",
>     "ruleSearch": {
>         "checkKeyWord": "抽象代数",
>         "bookList": "@css:div.book",
>         "name": "@css:p[title]@text",
>         "author": "@css:a.author-name@text",
>         "coverUrl": "@css:img[src]@src",
>         "bookUrl": "@css:div.cover>a@href"
>     },
>     "ruleBookInfo": {
>         "name": "@css:.book-meta>h2@text",
>         "author": "@css:.book-meta>.author>a@text",
>         "kind": "@css:.tags a.btn@text",
>         "intro": "@css:.comments>div@text",
>         "lastChapter": "@css:.publishing-date@text",
>         "downloadUrls": "class.book-meta.0@class.btn-group.0@children@class.btn-group.0@tag.a@href@js:(function(args){\njava.log(args)\nlet links = []\nfor(var k in args){\n    if(args[k].startsWith('/download'))\n        links.push(args[k])\n}\nreturn links\n})(result)"
>     },
>     "ruleToc": {
>         "nextTocUrl": "@css:li.page-next>a.next@href"
>     },
>     "ruleContent": {},
>     "ruleReview": {},
>     "ruleExplore": {
>         "bookList": "@css:.load-more div.book",
>         "name": "@css:p[title]@text",
>         "author": "@css:a.author-name@text",
>         "coverUrl": "@css:img[src]@src",
>         "bookUrl": "@css:div.cover>a@href"
>     },
>     "bookSourceType": 3,
>     "bookSourceName": "Calibre-Web",
>     "searchUrl": "/search/stored/1/{{page}}?query={{key}}",
>     "loginCheckJs": "",
>     "exploreUrl": "@js:(function(){\n    let discovery = []\n    let doc = org.jsoup.Jsoup.parse(java.ajax(baseUrl))\n    let items = doc.select(\".navigation>ul a\")\n\n    function generateDiscoveryFromSecondary(pageSource){\n        let page =org.jsoup.Jsoup.parse(pageSource)\n        let items = page.select(\".container .row a\")\n        if (items.length == 0){\n            return []\n        }\n        let result = []\n        for(let i = 0; i < items.length; i++){\n            let e = items[i]\n            let href = e.attr('href')\n            // 可翻页\n            if(href.match(/\\/\\d+$/)){\n                href += '/{{page}}'\n            }\n            result.push({\n                title: e.text(),\n                url: href,\n                style: {\n                    layout_wrapBefore: i == 0\n                }\n            })\n        }\n        return result\n    }\n    function isSecondaryList(pageSource){\n        return generateDiscoveryFromSecondary(pageSource).length != 0\n    }\n    for(let key in items){\n        let href = baseUrl + items[key].attr(\"href\")\n        let pageSource = java.ajax(href)\n        let secondary = isSecondaryList(pageSource)\n        // 可翻页\n        if(href.match(/\\/\\d+$/)){\n            href += '/{{page}}'\n        }\n        discovery.push({\n            title: items[key].text(),\n            style: {\n                layout_flexGrow: 1,\n                layout_alignSelf: \"stretch\",\n                layout_flexShrink: 0,\n                layout_wrapBefore: true,\n            },\n            url: isSecondaryList(pageSource) ? undefined : href\n        })\n        if(secondary){\n            for(let e of generateDiscoveryFromSecondary(pageSource)){\n                discovery.push(e)\n            }\n        }\n      \n    }\n    return JSON.stringify(discovery)\n})()",
>     "enabled": true,
>     "enabledExplore": true,
>     "enabledCookieJar": true
> }
> ```

需要登录怎们填写？

**Comment by mslxl** [comment]
> > 如果是 calibre-web 的话用这个吧，不走 opds 从网页上抓
> > 只需要把 bookSourceUrl 改成自己的机子就好
> > ```json
> > {
> >     "bookSourceUrl": "http://192.168.1.128:8084",
> >     "loginUrl": "/login",
> >     "ruleSearch": {
> >         "checkKeyWord": "抽象代数",
> >         "bookList": "@css:div.book",
> >         "name": "@css:p[title]@text",
> >         "author": "@css:a.author-name@text",
> >         "coverUrl": "@css:img[src]@src",
> >         "bookUrl": "@css:div.cover>a@href"
> >     },
> >     "ruleBookInfo": {
> >         "name": "@css:.book-meta>h2@text",
> >         "author": "@css:.book-meta>.author>a@text",
> >         "kind": "@css:.tags a.btn@text",
> >         "intro": "@css:.comments>div@text",
> >         "lastChapter": "@css:.publishing-date@text",
> >         "downloadUrls": "class.book-meta.0@class.btn-group.0@children@class.btn-group.0@tag.a@href@js:(function(args){\njava.log(args)\nlet links = []\nfor(var k in args){\n    if(args[k].startsWith('/download'))\n        links.push(args[k])\n}\nreturn links\n})(result)"
> >     },
> >     "ruleToc": {
> >         "nextTocUrl": "@css:li.page-next>a.next@href"
> >     },
> >     "ruleContent": {},
> >     "ruleReview": {},
> >     "ruleExplore": {
> >         "bookList": "@css:.load-more div.book",
> >         "name": "@css:p[title]@text",
> >         "author": "@css:a.author-name@text",
> >         "coverUrl": "@css:img[src]@src",
> >         "bookUrl": "@css:div.cover>a@href"
> >     },
> >     "bookSourceType": 3,
> >     "bookSourceName": "Calibre-Web",
> >     "searchUrl": "/search/stored/1/{{page}}?query={{key}}",
> >     "loginCheckJs": "",
> >     "exploreUrl": "@js:(function(){\n    let discovery = []\n    let doc = org.jsoup.Jsoup.parse(java.ajax(baseUrl))\n    let items = doc.select(\".navigation>ul a\")\n\n    function generateDiscoveryFromSecondary(pageSource){\n        let page =org.jsoup.Jsoup.parse(pageSource)\n        let items = page.select(\".container .row a\")\n        if (items.length == 0){\n            return []\n        }\n        let result = []\n        for(let i = 0; i < items.length; i++){\n            let e = items[i]\n            let href = e.attr('href')\n            // 可翻页\n            if(href.match(/\\/\\d+$/)){\n                href += '/{{page}}'\n            }\n            result.push({\n                title: e.text(),\n                url: href,\n                style: {\n                    layout_wrapBefore: i == 0\n                }\n            })\n        }\n        return result\n    }\n    function isSecondaryList(pageSource){\n        return generateDiscoveryFromSecondary(pageSource).length != 0\n    }\n    for(let key in items){\n        let href = baseUrl + items[key].attr(\"href\")\n        let pageSource = java.ajax(href)\n        let secondary = isSecondaryList(pageSource)\n        // 可翻页\n        if(href.match(/\\/\\d+$/)){\n            href += '/{{page}}'\n        }\n        discovery.push({\n            title: items[key].text(),\n            style: {\n                layout_flexGrow: 1,\n                layout_alignSelf: \"stretch\",\n                layout_flexShrink: 0,\n                layout_wrapBefore: true,\n            },\n            url: isSecondaryList(pageSource) ? undefined : href\n        })\n        if(secondary){\n            for(let e of generateDiscoveryFromSecondary(pageSource)){\n                discovery.push(e)\n            }\n        }\n      \n    }\n    return JSON.stringify(discovery)\n})()",
> >     "enabled": true,
> >     "enabledExplore": true,
> >     "enabledCookieJar": true
> > }
> > ```
> 
> 需要登录怎们填写？

我印象中书源管理中书源的下拉按钮有个登录按钮
