### ISSUE TITLE
最近的测试版开启梯子的情况下，大部分书源无法加载

### ISSUE THREAD

**Issue by xyzz2001** [gedoor/legado#3784]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

最近的版本不知道是设置原因还是什么，很多书源无法在开梯子换元的时候显示。单独复制网址去其他浏览器正常，关掉梯子也会正常

### 复现步骤 / How to reproduce

开启代理选择规则模式，然后测试

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

版本：3.24.030502

### Android版本 / Android version

14

### 机型 / Model

小米13p

**Comment by 821938089** [comment]
你调试一下书源看看报啥错
