### ISSUE TITLE
最新版本，txt阅读缺字，未开净化规则

### ISSUE THREAD

**Issue by 7845399855** [gedoor/legado#3785]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

本地的txt，最新的测试版阅读的时候偶尔会缺字，没有开替换净化，本地书也没有问题，就是缺字了不知道什么原因，系统是12OPPO手机

### 复现步骤 / How to reproduce

本地的txt，最新的测试版阅读的时候偶尔会缺字，没有开替换净化，本地书也没有问题，就是缺字了不知道什么原因，系统是12OPPO手机

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

本地的txt，最新的测试版阅读的时候偶尔会缺字，没有开替换净化，本地书也没有问题，就是缺字了不知道什么原因，系统是12OPPO手机

### 日志提交 / Relevant log output

本地的txt，最新的测试版阅读的时候偶尔会缺字，没有开替换净化，本地书也没有问题，就是缺字了不知道什么原因，系统是12OPPO手机

### 阅读版本 / Legado version

3.24.030519

### Android版本 / Android version

12

### 机型 / Model

oppo find x5 pro

**Comment by 821938089** [comment]
发图看看

**Comment by 7845399855** [comment]
![Uploading IMG_20240305_221247.png…]()

**Comment by 7845399855** [comment]
![Uploading IMG_20240305_221247.png…]()

**Comment by 7845399855** [comment]
![IMG_20240305_221247](https://github.com/gedoor/legado/assets/128984283/30d3429d-d82e-4a97-9b30-68e751a06cb5)

**Comment by 7845399855** [comment]
txt在mt管理器里的原文
![IMG_20240305_222430](https://github.com/gedoor/legado/assets/128984283/f26570ad-d754-42eb-93ad-27c989a3a4bb)

**Comment by 821938089** [comment]
把你用的字体发一下

**Comment by 7845399855** [comment]
系统默认的字体

**Comment by 821938089** [comment]
麻烦你长按选中一下有问题的那行字的最后几个字，截图发一下

**Comment by 7845399855** [comment]
这样吗
![IMG_20240305_230148](https://github.com/gedoor/legado/assets/128984283/2b6f06ed-f1b7-409e-960e-bf0f16bd83bf)

**Comment by 821938089** [comment]
你把这段文字复制出来发一下

**Comment by 7845399855** [comment]
那么点肉放在他身上, 压根看不出个什么来。

**Comment by 7845399855** [comment]
胖的两个字咋不见了复制两次都没有👀

**Comment by 821938089** [comment]
选择的和显示的没对应上
你界面里的字距设置是多少？

**Comment by 7845399855** [comment]
![IMG_20240305_235712](https://github.com/gedoor/legado/assets/128984283/f34c08c4-acd7-4471-af34-3bf0e32acf34)
这个不

**Comment by 821938089** [comment]
你把字距调大一点点看看显示会不会正常

**Comment by 7845399855** [comment]
调到最大0.5就不缺了

**Comment by 7845399855** [comment]
调到最大0.5还是缺字
![IMG_20240306_125151](https://github.com/gedoor/legado/assets/128984283/6a63d352-0342-4ee8-b4e2-47b295566851)

**Comment by 821938089** [comment]
关掉两端对齐，截图看看有问题的行

**Comment by 7845399855** [comment]
关掉正常了不缺字了
![Screenshot_20240306131412](https://github.com/gedoor/legado/assets/128984283/8c6cb722-25d7-4240-8e51-6075067ec86e)

**Comment by 821938089** [comment]
你装一下最新测试版试试

**Comment by 7845399855** [comment]
还是缺(ಥ_ಥ)

**Comment by 821938089** [comment]
你能把这个txt发一下吗

**Comment by 7845399855** [comment]
[《男配稳拿深情剧本》作者：祝麟.txt](https://github.com/gedoor/legado/files/14509008/default.txt)

**Comment by 7845399855** [comment]
弄了半天都是空文件夹没有东西在里面😂

**Comment by 7845399855** [comment]
记录日志也打开了

**Comment by 821938089** [comment]
重新设置下备份目录

**Comment by 7845399855** [comment]
[logs.zip](https://github.com/gedoor/legado/files/14512659/logs.zip)
好了好了有东西了

**Comment by 821938089** [comment]
试试最新测试版

**Comment by 7845399855** [comment]
好啦好啦辛苦啦谢谢๑•́₃•̀๑
