### ISSUE TITLE
希望增加朗读时滑动（翻页）不改变朗读进度的功能

### ISSUE THREAD

**Issue by xsdcz** [gedoor/legado#3786]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望在朗读时可以随意翻页回看文字内容而不影响正常的朗读进度，经常有些未听清的内容需要翻回去看之前的文字。

### 期望实现方式 / How to implement

回看内容时不改变朗读进度即可

**Comment by lidawei97688** [comment]
在朗读页锁屏后，过段时间再解锁（朗读自动翻页后），在很大概率从当前朗读的页的第一行开始重新念，就像是朗读时翻页后的动作
