### ISSUE TITLE
无法升级

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#3788]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

安装过3.24.022311版本后 无法再次升级，一直提示不能降版本安装

### 复现步骤 / How to reproduce

就是无法升级，缓存挺多了，不能重装了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.022311

### Android版本 / Android version

Android 13

### 机型 / Model

k40s

**Comment by 821938089** [comment]
只从同一个来源安装， 你应该是装了喵公子的版本，那你要升级的话就找喵公子那里发的新版本

**Comment by gyz1023** [comment]
> 只从同一个来源安装， 你应该是装了喵公子的版本，那你要升级的话就找喵公子那里发的新版本

一直都是喵公子的啊，不然我也安不上，反正就这个版本，升级了以后，后续升级不了

**Comment by adhu2018** [comment]
一切以这里的为准。喵公子那里之前的内部版本号比这里的高，只是现在改回来跟这里一致了。

**Comment by zqcnbi** [comment]
![IMG_20240306_195802](https://github.com/gedoor/legado/assets/52245548/08d2a427-01ce-46cb-aeb1-1bc23da65484)
是不是手机问题，我的也是这样的问题
