### ISSUE TITLE
在api.md中可以增加阅读记录操作的接口么

### ISSUE THREAD

**Issue by Lyon1994** [gedoor/legado#380]
我的kindle太老，浏览器不支持太多html5特性，导致web服务的页面在上面打开排版都是乱的，所以想自己做一个新的web服务器，看了下接口，似乎没有阅读记录操作的接口。

**Comment by gedoor** [comment]
好的

**Comment by Celeter** [comment]
> 我的kindle太老，浏览器不支持太多html5特性，导致web服务的页面在上面打开排版都是乱的，所以想自己做一个新的web服务器，看了下接口，似乎没有阅读记录操作的接口。

做好后分享一下鸭

**Comment by gedoor** [comment]
获取章节内容时会自动保存记录

**Comment by gedoor** [comment]
saveBook可以保存记录
