### ISSUE TITLE
语音朗读能不能添个预下载语音功能，语音朗读时一卡一卡的

### ISSUE THREAD

**Issue by JieDiO** [gedoor/legado#3800]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

语音朗读能不能添个预下载语音功能，语音朗读时一卡一卡的，尤其是用第三方语音服务时。

### 期望实现方式 / How to implement

语音朗读能不能添个预下载语音功能，语音朗读时一卡一卡的，尤其是用第三方语音服务时。

**Comment by 821938089** [comment]
有预下载
