### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lxx12445** [gedoor/legado#3810]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [ ] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

删除书籍后自动刷新后会再次出现,需要再次删除后书籍才会彻底删除

### 复现步骤 / How to reproduce

删除书籍

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22.110211

### Android版本 / Android version

android14

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
录个视频看看

**Comment by lxx12445** [comment]
[](url)

**Comment by lxx12445** [comment]
https://043hs-my.sharepoint.com/:v:/g/personal/lxx_043hs_onmicrosoft_com/ESnN8zTH4NlMjtAlYAuBl3EBtZ3gzQVJ4fj1QeoiqntXOg

**Comment by lxx12445** [comment]
视频太大,发不了

**Comment by 821938089** [comment]
试试最新测试版

**Comment by lxx12445** [comment]
我使用的是3.23.110211,这是我在release找到的最新版

________________________________

**Comment by 821938089** [comment]
最新测试版可以在这里下载
https://github.com/gedoor/legado/actions/workflows/test.yml
点进一个工作流里到Artifacts里下载

**Comment by lxx12445** [comment]
测试版的签名与我的版本不一致，我装了测试版的共存版，问题解决了。感谢你的帮助😘

________________________________
