### ISSUE TITLE
测试版分组搜索api抓包源，半天得不出结果

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3815]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

单独指定一个api源却是很快就出结果，如果整个分组都是这类源却是半天都不会有一个结果，前几个版本正常，普通源没有问题

### 复现步骤 / How to reproduce

api源的分组搜索一直不会出结果，使用单个源又很快就出结果，但是切换成分组就不出结果，以下是两个版本的对比

https://github.com/gedoor/legado/assets/37259360/e1c3a962-59f7-438f-a614-c3c72c7fd75a

https://github.com/gedoor/legado/assets/37259360/09699ec5-970e-4fb8-8281-fd3fbdc1ef21

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

[appLog-24-03-18 21_36_44.535.txt](https://github.com/gedoor/legado/files/14637427/appLog-24-03-18.21_36_44.535.txt)

### 阅读版本 / Legado version

3.24.031816

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60pro

**Comment by 821938089** [comment]
两个视频是一样的
