### ISSUE TITLE
OPDS Support

### ISSUE THREAD

**Issue by pwd-github** [gedoor/legado#3817]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

Official request for OPDS support.

### 期望实现方式 / How to implement

Please add support for the OPDS protocol.

**Comment by pwd-github** [comment]
真可惜。我一直认为这是 Android 所能提供的最佳阅读体验。

**Comment by Youxikong** [comment]
应该能通过书源写出来，opds不是很复杂。
