### ISSUE TITLE
WebDAV不支持空格为密码

### ISSUE THREAD

**Issue by wenfa1999** [gedoor/legado#3818]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

用的自建WebDAV，发现连接不上，用坚果云等随机密码的可以，后面在服务器改了下密码不是纯空格后发现连接成功

### 复现步骤 / How to reproduce

WebDAV设置密码为纯空格，填到软件配置上，点击备份后点击恢复，无法连接WebDAV服务器

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.073011

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K50

**Comment by 821938089** [comment]
试试最新测试版

**Comment by wenfa1999** [comment]
> 试试最新测试版

- [x] 最新测试版已经可以使用空格密码登录
