### ISSUE TITLE
想在每个章节末尾添加个xml布局，请问该如何实现

### ISSUE THREAD

**Issue by ChiShengCan** [gedoor/legado#3821]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

每个章节末尾想加入一些xml编写布局，如点赞、评论等按钮，请问该怎么实现

### 期望实现方式 / How to implement

每个章节末尾想加入一些xml编写布局，如点赞、评论等按钮，请问该怎么实现

**Comment by 821938089** [comment]
不支持

**Comment by Antecer** [comment]
正文页面是纯文本渲染的，不是html，所以没法支持。

**Comment by shapolang** [comment]
@ChiShengCan @821938089 @Antecer 有其他实现思路吗，我感觉这个是非常重要的功能吧，很多小说app都有
