### ISSUE TITLE
日志无法保存

### ISSUE THREAD

**Issue by hunyanjie** [gedoor/legado#3824]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

日志无法保存
![Uploadi
![Screenshot_2024-03-22-19-31-01-96_90024215e504237c76412be1999ad914](https://github.com/gedoor/legado/assets/67376760/f81cb5c5-0b00-4947-85eb-48d7644d8baa)
ng Screenshot_2024-03-22-19-28-10-96_90024215e504237c76412be1999ad914.png…]()

### 复现步骤 / How to reproduce

已开启日志保存按键，但是直接点击保存日志失败，日志内容显示也为空。
![Screenshot_2024-03-22-19-34-39-05_90024215e504237c76412be1999ad914](https://github.com/gedoor/legado/assets/67376760/cb0fe732-6d0b-4891-bd24-70525599618d)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.032018(15281)

### Android版本 / Android version

Android 14

### 机型 / Model

OnePlus Ace 2V

**Comment by 821938089** [comment]
重新设置备份路径
