### ISSUE TITLE
希望能将搜索、校验书源等的线程数设置之分开以实现单独设置

### ISSUE THREAD

**Issue by hunyanjie** [gedoor/legado#3826]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望能将下拉更新章节列表、搜索书籍、获取章节正文内容、批量更换书源、校验书源这几个支持多线程操作的线程数设置分开以支持单独设置线程数量

### 期望实现方式 / How to implement

可以分开设置，也可以选择全局统一，也可以设置与某一个操作的线程数保持一致（比如获取章节列表我设置了十个线程，而校验书源我设置与获取章节列表进程数一致，当我改变获取章节列表的进程数时校验的进程数也会同步改变）

### 附加信息 / Additions

感谢！

**Comment by gyz1023** [comment]
真要改，还是先把每个书源有个单独的线程设置吧，一些书源网站检测的好像有点严，比如69，线程一高容易被封IP，统一调低影响其他书源

**Comment by 821938089** [comment]
@gyz1023 已经有了，书源的并发率可以控制请求频次

**Comment by gyz1023** [comment]
> @gyz1023 已经有了，书源的并发率可以控制请求频次

那个并发率，我总感觉和线程不一样，之前就是，设置并发率会特别慢，限制线程会快很多，我试了好几天，现在按1线程设置的，弄并发率太慢，弄线程会影响其他源，我还是选择影响其他源吧，我源不多

**Comment by 821938089** [comment]
@gyz1023 你别调太大就可以了，例如100
