### ISSUE TITLE
搜索时软件崩溃

### ISSUE THREAD

**Issue by WySen-Yeah** [gedoor/legado#3829]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

当书源超过一定数量之后，书籍换源搜索时频繁崩溃

### 复现步骤 / How to reproduce

当书源超过一定数量之后，书籍换源搜索时频繁崩溃

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

"
SDK_INT=28
WebViewUserAgent=Mozilla/5.0 (Linux; Android 9; OPPO R11 Plus Build/PSV1.210329.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36
MODEL=OPPO R11 Plus
RELEASE=9
MANUFACTURER=OPPO
versionName=3.23.110211
versionCode=14860
BRAND=OPPO
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
"

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 9 / Xiaomi HyperOS 1.0.2

### 机型 / Model

OPPO R11 Plus，Redmi note 12 Tubo

**Comment by 821938089** [comment]
安装最新测试版，在其他设置里打开记录堆转储，崩溃后去关于那里点保存日志，然后去备份目录里将heapDump文件夹里的文件打包压缩一下上传上来

**Comment by gyz1023** [comment]
昨天我就闪退了，没有日志，一共5个源，挨个排查，发现目录规则改出问题了，所以你的闪退，可能就是某个源有问题，二分法，一半一半排查，看看哪个书源问题
