### ISSUE TITLE
RSS订阅源里的视频全屏播放会导致息屏，不全屏就没事

### ISSUE THREAD

**Issue by nxhswjy** [gedoor/legado#383]
video和iframe引用源都是这样，miui12有什么解决办法吗？(测试了3部手机)

还有个问题就是制作的RSS源，如果有两列都显示了同一个的资源的页面（就是同一个资源，按不同的标签来做列表，A标签列表和B标签列表都包含这个资源），会导致没法刷新，必须每次点清除才能刷新。分隔符&&好像也没用，是我操作有问题吗？

**Comment by gedoor** [comment]
好的,我看下
