### ISSUE TITLE
[BUG] web阅读不能及时的记住位置，web服务ip不显示局域网ip

### ISSUE THREAD

**Issue by easythd** [gedoor/legado#3830]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

两个我认为是BUG的问题，时间都很长了。我一直跟着稳定版走的，目前是最后的3.23.110211

第一个问题：**web阅读不能及时记住位置**
现在功能定义的是在pc端阅读要点返回书架后才会保存当前阅读位置，但实际使用过程中，经常是在pc端读了好几十章甚至上百章，然后离开电脑直接关了浏览器而忘记点返回书架的情况经常发生，而这时到手机上，进度还是几十章以前，手机上一打开，pc端进度又是和手机一样了。**强烈强烈强烈建议在pc端，换新的一章打开时，也同步章节进度到手机，不管字数到哪了，至少至少章节要对。。。会比现在好用**。

第二个问题：**web服务ip不显示局域网ip**
目前最新的两个版本，打开web服务后，都不显示wifi的局域网ip，只显示移动网络的ip。除非把数据流量关了。我记得以前不是这样的。现在搞得每次都必须自己要到wifi配置里去找当前ip是什么，阅读app里的显示和通知栏的显示都成了摆设。

### 复现步骤 / How to reproduce

一直就这样。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

android 13

### 机型 / Model

三星S20FE

**Comment by 821938089** [comment]
第一个问题更新最新测试版
第二个问题你可以固定IP，这样就不用管了

**Comment by easythd** [comment]
单位的网规则都是统一管理的，我固定不了啊。而且我觉得这只是个显示逻辑的问题，至少可以有只显示局域网ip的选项或全显示。以前都是好。

Horis ***@***.***> 于 2024年3月26日周二 17:17写道：

**Comment by easythd** [comment]
另外，请问下，您说的最新测试版在哪里发布下载呢？也是github的relese里？

Horis ***@***.***> 于 2024年3月26日周二 17:17写道：

**Comment by 821938089** [comment]
https://github.com/gedoor/legado/actions/workflows/test.yml
