### ISSUE TITLE
软件出问题了

### ISSUE THREAD

**Issue by yanguiSV0** [gedoor/legado#3834]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

![Screenshot_2024-03-27-20-40-23-118_io legado app releaseA](https://github.com/gedoor/legado/assets/144865706/a63415f7-e9bd-4f60-98c2-e8ea7bbb1a2c)
![Screenshot_2024-03-27-20-28-54-608_io legado app releaseA](https://github.com/gedoor/legado/assets/144865706/df32f977-acae-4322-b5a0-2686926f69fc)

所有源都是加载正文出问题，加载4到5张图片，然后下滑进度就一直重复显示那4到5张图片，日志显示没有进度条

### 复现步骤 / How to reproduce

![Screenshot_2024-03-27-20-28-54-608_io legado app releaseA](https://github.com/gedoor/legado/assets/144865706/edb29265-d3ea-435c-913b-7bab9242cdce)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

![Screenshot_2024-03-27-20-23-57-660_io legado app releaseA](https://github.com/gedoor/legado/assets/144865706/2cd5f215-48b0-4e6c-8a58-d3f00259f395)

### 日志提交 / Relevant log output

![Screenshot_2024-03-27-20-23-57-660_io legado app releaseA](https://github.com/gedoor/legado/assets/144865706/98b0368e-c604-40a6-b6aa-0d07bb04b80a)

### 阅读版本 / Legado version

3.24.032622

### Android版本 / Android version

13

### 机型 / Model

k60pro

**Comment by 821938089** [comment]
录个视频看看
还有点开编辑内容看看

**Comment by yanguiSV0** [comment]
> 录个视频看看 还有点开编辑内容看看


https://github.com/gedoor/legado/assets/144865706/8c2ef186-ea1d-43cd-a591-6512d66fc936

**Comment by yanguiSV0** [comment]
> 录个视频看看 还有点开编辑内容看看

![2b65aa8feab59d01cfb4033fb61032e6](https://github.com/gedoor/legado/assets/144865706/8711e2aa-a9fb-4471-bc26-7dfe6b16dd86)

**Comment by yanguiSV0** [comment]
> 录个视频看看 还有点开编辑内容看看最新版本有漏洞，我只能下一个很老的版本来用了现在

**Comment by 821938089** [comment]
试试最新测试版

**Comment by yanguiSV0** [comment]
> 尝试最新测试版本

安装了旧版本就没问题了，确实是新版本有漏洞

**Comment by yanguiSV0** [comment]
> 尝试最新测试版本

新版本，我测试了，没有那个情况了，修复了😊
