### ISSUE TITLE
gzip报错

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#3836]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在修复h5.17k.com书源时，遇到了gzip相关报错，有点束手无措

### 复现步骤 / How to reproduce

![Screenshot_2024-03-28-21-45-40-242_io legado app release-edit](https://github.com/gedoor/legado/assets/70464410/0a71363c-8033-4223-bde7-2e8b156c7e03)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.122016

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
试试最新测试版

**Comment by skybbk1998** [comment]
> 试试最新测试版

最新测试版已经正常，感谢
