### ISSUE TITLE
为web端添加方向键翻页功能选择

### ISSUE THREAD

**Issue by quxiquxi** [gedoor/legado#3838]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

能不能是的web端阅读时，可以让方向键不再是翻页，而是一行一行的滚动。web端直接翻页会使得视线需要从显示器下方直接跳转到上方，打断阅读连贯性。希望可以像起点网页端那样，每次点击滚动一行的。

### 期望实现方式 / How to implement

在web端添加切换选项。

**Comment by chenxirang** [comment]
方向键在哪里啊
