### ISSUE TITLE
可以指定Javascript脚本引擎吗

### ISSUE THREAD

**Issue by cqwuzonglin** [gedoor/legado#3843]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

写了个解析某个网站wasm的脚本 在JDK8中的脚本引擎能正常解析 但是在APP中解析异常

### 期望实现方式 / How to implement

期望以如下类似写法实现自定义脚本引擎
<js engine="javascript"></js>
@js['javascript']:

### 附加信息 / Additions

没办法当前自己开个后端接口,调用JDK的脚本引擎来实现的破解

**Comment by 821938089** [comment]
安卓平台没有Nashorn

**Comment by cqwuzonglin** [comment]
主要是现在的脚本引擎 在执行wasm2js转化后的js代码解密结果 和浏览器及JDK的JS引擎解密结果不一致...转化后的js解密代码又太复杂. 这种wasm除了复制他js代码,能有其他解密方案吗  https://www.sumingxs.com

**Comment by 821938089** [comment]
试试用webview

**Comment by cqwuzonglin** [comment]
默认就是开启了webview的 但是 加密内容并没有成功自动解密 网页自带js的执行还是有问题

**Comment by 821938089** [comment]
我看了看，那段字是画出来的。。。所以没用
你可以试试用webview来执行js
```js
function webViewEvalJS(js) {
    options = {
        webJs: js,
        webView: true
    }
    return java.ajax("about:blank," + JSON.stringify(options))
}
```

**Comment by cqwuzonglin** [comment]
大哥,那个我用java.webview能执行了 但是在公司会报错 类似 stack 1039K,在家又不会,这个是啥原因呢,同样的js长度 同样的章节 
是wifi或流量上网方式不同?

**Comment by 821938089** [comment]
不知道，这个报错好像是堆栈溢出了，你可以看看堆栈是哪里出问题了
