### ISSUE TITLE
实在找不到问题，请教怎么用阅读看漫画

### ISSUE THREAD

**Issue by fhwhite** [gedoor/legado#3851]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

本来以为是阅读的问题，但测试了一番后感觉是我的问题

我23年3月4日请教一个漫画源的问题，当时测试是好使的，阅读可以正常看漫画，但看小说比较多，就放下了

最近想看个漫画，发现点进章节直接显示图片链接而不是显示图片，如下

### 复现步骤 / How to reproduce

![微信截图_20240402015542](https://github.com/gedoor/legado/assets/47919090/e9f68ebf-7657-4782-9b1b-005a8fae4eac)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

经过多次测试，怎么都无法显示图片，换了多个版本，包括清空卸载重装软件后，什么都不设置只粘贴进一个漫画源，还是显示链接。。。

不知道是什么情况，我记得这种格式确实用阅读看过漫画呀，是哪里的设置我给改了之后不显示图片吗，full text default也没反应，实在找不到原因了，求助

### 阅读版本 / Legado version

legado_app_3.23.110211 legado_app_3.23.030400 legado_app_3.22.100921

### Android版本 / Android version

Android

### 机型 / Model

手机和模拟器

**Comment by fhwhite** [comment]
怎么在这里显示出来了。。。我把img前面的<删掉了
img src=https://r2.bakamh.com/manga_6425bd5a7cf3b/7088824b762a0107bfd877eaca9f5f8b/9f2648496b455ccce2b0e24e70dee6b0.jpg width='auto' height='auto' loading='auto'>
img src=https://r2.bakamh.com/manga_6425bd5a7cf3b/7088824b762a0107bfd877eaca9f5f8b/9ddeaae1564e2dcc8de5bb724ee4f0f2.jpg width='auto' height='auto' loading='auto'>

**Comment by adhu2018** [comment]
图片链接两边需要有引号，图中没有，关闭替换净化，检查书源正文规则

**Comment by fhwhite** [comment]
> 图片链接需要有引号，因此没有，关闭替换净化，检查书源正文规则

替换已经关闭，加了引号也不行，下面是复制的显示内容



　<img src='https://r2.bakamh.com/manga_6425bd5a7cf3b/7088824b762a0107bfd877eaca9f5f8b/9f2648496b455ccce2b0e24e70dee6b0.jpg' width='auto' height='auto' loading='auto'><img src='https://r2.bakamh.com/manga_6425bd5a7cf3b/7088824b762a0107bfd877eaca9f5f8b/9ddeaae1564e2dcc8de5bb724ee4f0f2.jp

**Comment by adhu2018** [comment]
双引号

**Comment by fhwhite** [comment]
> 双引号

我勒个去。。感激不尽。。但是为啥呢，以前同样的源就好使，现在就不好使呢，我之前写完源都没动过。。。不管怎么说好了好了好了，感激不尽

**Comment by fhwhite** [comment]
> > 双引号
> 
> 我勒个去。。感激不尽。。不过为啥呢，以前同样的源就好用，现在就不好使呢，我之前写完源都没动过。。。不管怎么样就好了好了好了，感激不尽

**Comment by adhu2018** [comment]
主要现有的匹配规则里有个地方不知道是在匹配什么的，起什么作用，不敢改，先用着，等其他人改吧

**Comment by 821938089** [comment]
是书源写的有问题吧，阅读自动识别生成的图片标签不是这样的，你是自己手动拼接的吗？
