### ISSUE TITLE
更改“阅读”看视频的默认播放器

### ISSUE THREAD

**Issue by kjoying** [gedoor/legado#3854]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在阅读中看视频时不能快进，不能滑动屏幕调节进度，总之很不方便，要是能更改播放器就好了

### 期望实现方式 / How to implement

能够更改默认播放器

**Comment by 821938089** [comment]
你需要找做那个源的人改

**Comment by kjoying** [comment]
> 你需要找做那个源的人改

但用阅读直接打开网址就没办法了，这时阅读没有写好的源，而且写的源播放器也不算好用
