### ISSUE TITLE
字体相关：反反爬字体

### ISSUE THREAD

**Issue by CsVeryLoveXieWenLi** [gedoor/legado#3855]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

**有些网站会使用，自己的字体，让设备本身的字体失效，解码出乱码，但是在网站上正常解码并显示。没做过字体，有点不明所以，字体的显示应该有用到unicode吧，不然设备怎么知道这个字符对应那个字形。也就是说把不存在字符设定为自己的字形，但是正常设备上没有？**

![Screenshot_20240406-024027_HttpCanary](https://github.com/gedoor/legado/assets/102389677/7c80ae25-ae9c-4b90-8beb-29957e1e2440)

### 期望实现方式 / How to implement

解析网站字体的映射表，对比设备字体的映射表。

**Comment by Antecer** [comment]
这个功能一直都有，请查看源制作教程。

**Comment by CsVeryLoveXieWenLi** [comment]
**很抱歉，给您添麻烦了，由于的疏忽。我查看了书源规则，发现了解析字体之类的API。**

> 这个功能一直都有，请查看源制作教程。
