### ISSUE TITLE
最近测试版翻页动画有bug

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#3868]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

最近测试版翻页动画“覆盖”，“滑动”模式有bug。

### 复现步骤 / How to reproduce

覆盖模式

https://github.com/gedoor/legado/assets/74254385/0d381bee-98fa-4ade-9826-16f55667427a

滑动模式

https://github.com/gedoor/legado/assets/74254385/941551b2-b102-4919-9cb7-0bfd56a45870

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.04

### Android版本 / Android version

6

### 机型 / Model

sm919

**Comment by 821938089** [comment]
试一下最新的测试版

**Comment by sartonsh** [comment]
还是老问题

**Comment by 821938089** [comment]
再试试

**Comment by sartonsh** [comment]
新功能“启用绘制优化”启用后回出现老问题

**Comment by 821938089** [comment]
这个功能在你的系统上有问题，不能开这个

**Comment by sartonsh** [comment]
已搞定，多谢
