### ISSUE TITLE
能不能像蕃茄小说一样加入多角色阅读 AI阅读功能  解放眼睛

### ISSUE THREAD

**Issue by flyhorse906** [gedoor/legado#3869]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

能不能像蕃茄小说一样加入多角色阅读  AI阅读功能  解放眼睛

### 期望实现方式 / How to implement

像蕃茄小说  加入AI深度学习功能

### 附加信息 / Additions

像蕃茄小说

### 效果演示 / Demo

像蕃茄小说

**Comment by kaveys** [comment]
部分 tts 源可以解决
