### ISSUE TITLE
希望增加在获取到有更新后尝试自动缓存更新的章节

### ISSUE THREAD

**Issue by hunyanjie** [gedoor/legado#3871]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望能增加一个缓存功能：当刷新书籍列表后若书籍有更新，就尝试直接获取更新的章节的缓存

### 期望实现方式 / How to implement

在设置中增加这个功能以及选项

### 附加信息 / Additions

谢谢

**Comment by 821938089** [comment]
这个已经有了，设置里的预下载就是
