### ISSUE TITLE
下划线问题

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#3872]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

切换黑夜/白天模式时下划线颜色不能及时切换，要杀掉后台重新启动才能切换。

### 复现步骤 / How to reproduce

切换黑夜/白天模式时下划线颜色不能及时切换，要杀掉后台重新启动才能切换。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.04

### Android版本 / Android version

6

### 机型 / Model

sm919

**Comment by 821938089** [comment]
已修复，试试最新测试版

**Comment by sartonsh** [comment]
已搞定，多谢
