### ISSUE TITLE
正文多格式文本

### ISSUE THREAD

**Issue by jiwangyihao** [gedoor/legado#3879]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

从书源制作的角度来说，现在的正文格式只有一种纯文本和图片，对书源作者来说可自定义的范围太少了。

对于相当一部分网站，往往会出现特殊格式的正文，比如：
- 章末评论
- [轻小说机翻机器人](https://books.fishhawk.top/)的原文-译文对照
下面是原网站的显示效果：
![image](https://github.com/gedoor/legado/assets/51940778/159531a7-bf16-48bb-8159-68222c341781)
这是我能够想到的在当前版本的阅读里的最佳实现效果：
![2b8f168ec20eed9cf58fb19a608dfae](https://github.com/gedoor/legado/assets/51940778/d3dff5ab-2b09-4f7f-95fe-0c16f38795e2)

### 期望实现方式 / How to implement

为正文提供可由书源实现的样式自定义。

比如：
```
<text size=0.5 alpha=0.5 line-height=0.5 tts=false>大小、透明度、行高（或者行距）均为用户设定的正文样式的一半的文字，并且不会被TTS读出</text>
```

另外，希望能让书源单独设定某一张图片的显示样式

**Comment by 821938089** [comment]
多格式文本的视图太难做了，我试了一下，太多东西要搞，放弃了
你可以找找别人会做这方面的，愿意来开发的搞一下

**Comment by jiwangyihao** [comment]
> 多格式文本的视图太难做了，我试了一下，太多东西要搞，放弃了
> 你可以找找别人会做这方面的，愿意来开发的搞一下

初期先考虑一些简单的样式？比如至少调整一下字号和透明度之类的会简单一些吗？

**Comment by 821938089** [comment]
目前不打算搞了
