### ISSUE TITLE
queryTTF (Unicode<->轮廓) 双向查询功能解析不正确

### ISSUE THREAD

**Issue by jiwangyihao** [gedoor/legado#3893]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

使用 `queryTTF` 方法解析某网站的[防盗版小米兰亭](https://www.bilinovel.com/public/font/read.ttf)和本人找到的同版本[原版小米兰亭](https://alist.jwyihao.top/d/Pack/MI%20LANTING(1).ttf)时均出现 `replaceFont` 方法不生效的问题。
初步排查后认为是 `queryTTF` 方法的解析存在问题。
使用 Python 可得到[防盗版小米兰亭](https://www.bilinovel.com/public/font/read.ttf)的 Unicode 码位范围是 `32~65509`
```Python
from fontTools.ttLib import TTFont

font = TTFont("ttf/read.ttf")
# 获取cmap节点code与name值映射, 返回为字典
print(font.getBestCmap())
```
在阅读中使用 `queryTTF.inLimit` 方法验证阅读解析得到的 Unicode 码位范围
```JavaScript
font=java.queryTTF("https://www.bilinovel.com/public/font/read.ttf")
java.log(font.inLimit(26786)) //true
java.log(font.inLimit(26787)) //false
```
可知阅读解析[防盗版小米兰亭](https://www.bilinovel.com/public/font/read.ttf)的 Unicode 码位范围是 `32~26786`，与该字体的实际码位不符。

使用同样的方法测试阅读解析[原版小米兰亭](https://alist.jwyihao.top/d/Pack/MI%20LANTING(1).ttf)的码位：
- Python 的 fontTools 库：`32~65509`
- 阅读：`32~25062`

### 复现步骤 / How to reproduce

新建书源

在阅读中使用 `queryTTF.inLimit` 方法验证阅读解析得到的 Unicode 码位范围
```JavaScript
font=java.queryTTF("https://www.bilinovel.com/public/font/read.ttf")
java.log(font.inLimit(26786)) //true
java.log(font.inLimit(26787)) //false
```

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.041900

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60

**Comment by 821938089** [comment]
字体里有复合字形
阅读的 `queryTTF` 没有写解析复合字形的代码
https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/model/analyzeRule/QueryTTF.java#L465

**Comment by jiwangyihao** [comment]
> 字体里有复合字形 阅读的 `queryTTF` 没有写解析复合字形的代码 https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/model/analyzeRule/QueryTTF.java#L465

复合字形处理有进一步完善的计划吗？

如果没有的话，有什么可能的不够优雅的临时处理措施吗？

这样的临时处理措施（如果提交了PR）会被合入主线吗？

**Comment by 821938089** [comment]
不知道，我帮你@Antecer 看看他会不会搞一下

用js库解析处理

书源端解决，应该不需要提交PR

**Comment by jiwangyihao** [comment]
> 不知道，我帮你@Antecer 看看他会不会搞一下
> 
> 用js库解析处理
> 
> 书源端解决，应该不需要提交PR

能给个示例吗，我尝试直接用 eval 加载 [`opentype.js`](https://github.com/opentypejs/opentype.js) 似乎不能正常使用

```JavaScript
eval(java.cacheFile("https://opentype.js.org/dist/opentype.js"))
java.log(opentype) //报错（在浏览器控制台直接粘贴上述代码可以正常使用）
```

另外刚刚我确认了一下，如图所示的码位为 `60506` 的字并非复合字形，也不在阅读解析的码位范围内

![image](https://github.com/gedoor/legado/assets/51940778/81d0d206-57ff-4b5c-b0bb-08ec18e5d690)

**Comment by jiwangyihao** [comment]
我也尝试了使用 `webView` 方法加载
```JavaScript
java.webView(`<script src="https://opentype.js.org/dist/opentype.js"></script>`, null, 'opentype')
```
这样确实可以正确加载 `opentype.js`，但是这个方法似乎没办法获取异步方法的返回值

感谢指正！

**Comment by 821938089** [comment]
需要转成js的String才能执行代码，不过我试了下，代码用了js的新特性，不兼容，执行不了
```js
eval(String(java.cacheFile("https://opentype.js.org/dist/opentype.js")))
```
解决办法：1、用babel转译一遍
2、用webview执行


https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/model/analyzeRule/QueryTTF.java#L475
这行限制了代码点范围，代码点 26786 对应字形数组中最后一个字形序号，超过了剩下的代码点就都跳过了

**Comment by 821938089** [comment]
这个java.webView是会轮询的，你把结果放到全局里，只要js执行结果为null就会等1秒继续执行，执行30次

**Comment by Antecer** [comment]
提供一下书源，我看看这个字体是咋回事。

**Comment by jiwangyihao** [comment]
> 提供一下书源，我看看这个字体是咋回事。

书源导入地址：https://mirror.ghproxy.com/https://raw.githubusercontent.com/jiwangyihao/source-j-legado/main/bilinovel.json

目前只有部分章节的最后一段被替换

可调试正文 `--https://www.bilinovel.com/novel/2958/156435.html` 测试

（上面这一版书源尚未对字体进行任何处理）

书源使用的防盗版字体以及对应的原版字体已在上文给出（已用 Python 确认对应字形 glyf 相同，不过是抽查）

**Comment by Antecer** [comment]
通常，这种反盗手段，它的每个页面可能都是用的不同的字体文件，我看了下，这网站用的woff2，得研究下怎么解析woff2字体了。

**Comment by jiwangyihao** [comment]
> 通常，这种反盗手段，它的每个页面可能都是用的不同的字体文件，我看了下，这网站用的woff2，得研究下怎么解析woff2字体了。

应该和这个没有关系，我确认过 ttf 字体和 woff 字体的内容是一样的，而且目前该网站字体放在 `/public` 中，不存在其他变种

**Comment by jiwangyihao** [comment]
> 通常，这种反盗手段，它的每个页面可能都是用的不同的字体文件，我看了下，这网站用的woff2，得研究下怎么解析woff2字体了。

![Screenshot_2024-04-25-10-25-37-443_com.microsoft.emmx-edit.jpg](https://github.com/gedoor/legado/assets/51940778/5379b7a4-7148-4ee4-ae70-7ce28b57859c)

woff 和 ttf 是互为替补的（woff优先级高，ttf是fallback），两个字体文件的内容不应该不同。

**Comment by Antecer** [comment]
同一个页面的两个字体文件肯定是相同的，我只是指出，碰到过这样的网站，不同的页面使用的替换字体不同的情况。

**Comment by jiwangyihao** [comment]
> 同一个页面的两个字体文件肯定是相同的，我只是指出，碰到过这样的网站，不同的页面使用的替换字体不同的情况。

嗯嗯（我只是觉得应该先把ttf处理完而已😂）

**Comment by Antecer** [comment]
我试了下，的确无法正确的找到字模。有点奇怪..

**Comment by Antecer** [comment]
解决了，以下是测试代码：
```js
if (String(src).match(errorReg())) {
    java.log(src);
    src = ajax(baseUrl);
}
java.setContent(src);
if (java.get('jsContent') == '' || java.get('id') == '') {
    jsLink = java.getString('tag.script@src').match(/http.+zhmb.+\?v.+/gi);
    try {
        jsLink.forEach((link) => {
            jsRaw = java.cacheFile(link);
            jsContent = jsRaw.match(/.+\\x.+/gi);
            if (jsContent) {
                java.put('id', jsRaw.match(/contentid: '.+(?=',)/gi)[0].replace("contentid: '", ''));
                java.put('jsContent', jsContent[0]);
            }
        });
    } catch (e) {
        throw '正文获取js错误：\n' + e + '\n正文源码：\n' + src;
    }
    //java.ajaxAll(jsLink).forEach(res => {
    //  jsRaw = res.body()
    //})
}
try {
    h = String(java.getString('id.' + java.get('id') + '@html'));
    h = h.replace('&nbsp;&nbsp;', '&emsp;');
    el = {innerHTML: String(h)};
    document = {
        getElementById: () => {
            return el;
        },
    };
    window = {document: document, RegExp: RegExp};
    eval(String(java.get('jsContent')));
} catch (e) {
    java.log(src);
    throw 'js 执行错误：' + e + '\njs 内容；\n' + jsContent;
}
h = el.innerHTML;

if (baseUrl.match(/_\d+\.html/)) {
    var f1 = java.queryTTF('https://www.bilinovel.com/public/font/read.ttf');
    var f2 = java.queryTTF('https://alist.jwyihao.top/d/Pack/MI%20LANTING(1).ttf');
    var result = java.replaceFont('窍戏毛漏吁。', f1, f2, true);
    java.log('DEBUG: ' + result);
}
h
```

由于这个文本，只有某一段文字使用了替换的字体文件，所以你需要精准的替换有问题的那一段文本。
这方面我就不研究了，你自己研究下怎么精准的找到那一段文本吧，示例代码使用了一段固定的错误文本。

**Comment by Antecer** [comment]
具体内容请查看 commit cb06d14

**Comment by jiwangyihao** [comment]
> 解决了，以下是测试代码：
> ```js
> if (String(src).match(errorReg())) {
>     java.log(src);
>     src = ajax(baseUrl);
> }
> java.setContent(src);
> if (java.get('jsContent') == '' || java.get('id') == '') {
>     jsLink = java.getString('tag.script@src').match(/http.+zhmb.+\?v.+/gi);
>     try {
>         jsLink.forEach((link) => {
>             jsRaw = java.cacheFile(link);
>             jsContent = jsRaw.match(/.+\\x.+/gi);
>             if (jsContent) {
>                 java.put('id', jsRaw.match(/contentid: '.+(?=',)/gi)[0].replace("contentid: '", ''));
>                 java.put('jsContent', jsContent[0]);
>             }
>         });
>     } catch (e) {
>         throw '正文获取js错误：\n' + e + '\n正文源码：\n' + src;
>     }
>     //java.ajaxAll(jsLink).forEach(res => {
>     //  jsRaw = res.body()
>     //})
> }
> try {
>     h = String(java.getString('id.' + java.get('id') + '@html'));
>     h = h.replace('&nbsp;&nbsp;', '&emsp;');
>     el = {innerHTML: String(h)};
>     document = {
>         getElementById: () => {
>             return el;
>         },
>     };
>     window = {document: document, RegExp: RegExp};
>     eval(String(java.get('jsContent')));
> } catch (e) {
>     java.log(src);
>     throw 'js 执行错误：' + e + '\njs 内容；\n' + jsContent;
> }
> h = el.innerHTML;
> 
> if (baseUrl.match(/_\d+\.html/)) {
>     var f1 = java.queryTTF('https://www.bilinovel.com/public/font/read.ttf');
>     var f2 = java.queryTTF('https://alist.jwyihao.top/d/Pack/MI%20LANTING(1).ttf');
>     var result = java.replaceFont('窍戏毛漏吁。', f1, f2, true);
>     java.log('DEBUG: ' + result);
> }
> h
> ```
> 
> 由于这个文本，只有某一段文字使用了替换的字体文件，所以你需要精准的替换有问题的那一段文本。
> 这方面我就不研究了，你自己研究下怎么精准的找到那一段文本吧，示例代码使用了一段固定的错误文本。

嗯嗯，大佬辛苦了

**Comment by jiwangyihao** [comment]
> fix with commit [cb06d14](https://github.com/gedoor/legado/commit/cb06d149f7fbc51699b0f1722d3ba3849450a55e) Test Build [#4618](https://github.com/gedoor/legado/actions/runs/8857424485)

@Antecer 我刚刚发现好像有一些字形的解析还是有问题（目前只发现了一个）
下图是用FontCreator和Python确认字形的结果
![0a90a1090cce717f4b757385167cc196](https://github.com/gedoor/legado/assets/51940778/09da4c52-0a01-4c70-b714-c282fe427f3c)
```Python
from fontTools.ttLib import TTFont

font = TTFont("ttf/read.ttf")

# 获取glyf节点TTGlyph字体xy坐标信息
glyf1 = font['glyf'][font.getBestCmap()[0xED43]].coordinates
# print(len(font.getGlyphOrder()))
print(glyf1)

font2 = TTFont("ttf/MI LANTING.ttf")
glyf2 = font2['glyf'][font2.getBestCmap()[0x4E24]].coordinates
print(glyf2)
print(glyf1 == glyf2)
```
![5aefa43dd5fee4585ab69d63aec54d72](https://github.com/gedoor/legado/assets/51940778/aad61a28-5a55-4eaf-b2c1-94b25dda34cc)

可以看到，这两个字形是相同的。

下面是使用阅读获取这两个字形的结果：

```JavaScript
java.log(java.queryTTF("https://www.bilinovel.com/public/font/read.ttf").getGlyfByCode(0xED43))
// 0000011407333635012627363736373523112311333627213521152106073311162306232627163316271123061506071617072627060726273E013723060716170726270601FFFFFFA403FFFFFFC103FFFFFFFEFFFFFF971B1949212108FFFFFFA544FFFFFFEC0301FFFFFFFEFFFFFFDD03FFFFFF86FFFFFFFEFFFFFFE80103FFFFFFE40675433F07093A3A5107FFFFFFA601051056552F4944285E181F514808FFFFFFC1060A403D2A352E2602FFFFFFBB47403750FFFFFFFDFFFFFF9B1B13515153720AFFFFFFFDFFFFFFC0027F40473E3E4245FFFFFFFDFFFFFFFD7402242004044301FFFFFFBB0707483B535A335648776F181558FFFFFFB3FFFFFF814135373835372B77000000
java.log(java.queryTTF("http://mirror.ghproxy.com/https://raw.githubusercontent.com/jiwangyihao/source-j-legado/main/utils/MI%20LANTING.ttf").getGlyfByCode(0x4E24))
// 0000010607333635012627363736373523112311333627213521152106073311162306232627163316271123061506071617072627060726273E013723060716170726270601FFFFFFA40003FFFFFFC103FFFFFFFEFFFFFF971B1949212108FFFFFFA544FFFFFFEC0301FFFFFFFEFFFFFFDD03FFFFFF86FFFFFFFEFFFFFFE80103FFFFFFE40675433F07093A3A5107FFFFFFA601051056552F4944285E181F514808FFFFFFC1060A403D2A352E2602FFFFFFBB47403750FFFFFFFDFFFFFF9B1B13515153720AFFFFFFFDFFFFFFC0027F40473E3E4245FFFFFFFDFFFFFFFD7402242004044301FFFFFFBB0707483B535A335648776F181558FFFFFFB3FFFFFF814135373835372B770000
```
![22377cf8eff01bfbba095abfc2570602_720](https://github.com/gedoor/legado/assets/51940778/efb14c01-2704-4928-af71-b6063ecad350)

可以看到，这两个结果非常相近，但是不完全相同。看起来似乎现在并没有「解析」而是使用原始字形数据直接比较，这可能是导致问题的原因？

当前的已处理字体问题的书源地址（包含了上述的测试代码）：https://shuyuan.mgz6.cc/shuyuan/cb4902e9ff389546d9297551112dae24.json

含有问题字形的章节：`--https://www.bilinovel.com/novel/3523/231612.html`

**Comment by Antecer** [comment]
被摆了一道：  
![image](https://github.com/gedoor/legado/assets/8684916/e0e0a5b6-4100-4883-8706-692942f92df9)

**Comment by jiwangyihao** [comment]
> 被摆了一道：  
> ![image](https://github.com/gedoor/legado/assets/8684916/e0e0a5b6-4100-4883-8706-692942f92df9)
> 

那么……

**Comment by Antecer** [comment]
意思就是，为了图省事，本来没有解析完整的轮廓数据，这下被迫要完整的解析了。。

**Comment by Antecer** [comment]
你再试试，应该解决了

**Comment by jiwangyihao** [comment]
现在好像有别的问题（
如图所示

![Screenshot_2024-04-29-20-50-23-314_io.legado.app.release-edit.jpg](https://github.com/gedoor/legado/assets/51940778/ff0f848d-8313-48f2-ab7a-cc16969fe5aa)

![Screenshot_2024-04-29-20-50-46-453_io.legado.app.release-edit.jpg](https://github.com/gedoor/legado/assets/51940778/8f0e8466-f57c-46fb-991c-a71c8f6805de)

之前的时候将最后一个参数设为false时会出现多乱码字的情况，改成true后就不会出现

但刚刚更换了 CI 中的 3.24.042919 后无论最后一个参数设为true还是设为false均会出现该问题

原始字符：`实，疲豆辈困聆。`
正确显示：`就这样，两年的岁月流逝而过。`
实际结果：`就这样，两疳年的豇月辊流逝而过。`

该问题在其他章节也有出现，如 `--https://www.bilinovel.com/novel/3523/222597.html`

![Screenshot_2024-04-29-21-23-30-012_io.legado.app.release-edit.jpg](https://github.com/gedoor/legado/assets/51940778/0c5d9cab-b330-43e0-a336-0d25f44b02ba)

我使用 JS 检查了原始字符的unicode码 `$ECFB$F2C1$5B9E$E400$FF0C$ED43$75B2$F7DF$F065$8C46$E0C7$E117$8F88$E47B$EEE9$56F0$EDB7$F449$8046$3002`，有 20 个字符，比实际应当正确显示的字符数量（14个）多出6个。

使用 FontCreator 检查实际字形对应的 unicode 码为 `$ECFB$F2C1$E400$FF0C$ED43$F7DF$F065$E0C7$E117$E47B$EEE9$EDB7$F449$3002`

多出了 `$5B9E`（不存在），`$75B2`（FontCreator和Python均提示字形为空，但阅读能获取到字形数据），`$8C46`（同前），`$8F88`（同前），`$5F60`（同前），`$8064`（同前）

而未能正确解析的字符「岁」的编码为 `$E0C7`，在阅读中获取不到字形数据，但FontCreator和Python中都是能获取到的。

看起来似乎还是字形解析的问题。

**Comment by Antecer** [comment]
主要是需要对比轮廓数据，如果轮廓数据对不上就没辙

**Comment by jiwangyihao** [comment]
> 主要是需要对比轮廓数据，如果轮廓数据对不上就没辙

见最后两段，对于同一个字体，相同编码位在字形的有无上阅读的获取情况也与FontCreator/Python不同

具体的编码位已经给出

**Comment by Antecer** [comment]
明天再看看，今天不搞了

**Comment by Antecer** [comment]
啃了2天微软的TTF文档，这下问题应该是彻底解决了：
![image](https://github.com/gedoor/legado/assets/8684916/a4ca3abb-7738-4742-8372-5d961feba2a9)
