### ISSUE TITLE
替换净化未生效，每段话结尾的</p>未替换掉

### ISSUE THREAD

**Issue by wjwkill** [gedoor/legado#3896]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

替换净化未生效，每段话结尾的html“< / p >”未替换掉，不知道是不是没有包含这种替换规则，或者我的替换规则里没有，但我觉得这条规则应该挺常见的

### 复现步骤 / How to reproduce

![1](https://github.com/gedoor/legado/assets/49703448/0b886626-e3b1-4952-bbef-139137e781b6)
![2](https://github.com/gedoor/legado/assets/49703448/bbf5e466-8b81-4690-9f86-dce25f2e09c3)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 10

### 机型 / Model

三星Note9

**Comment by Antecer** [comment]
书源贴出来看看？

**Comment by wjwkill** [comment]
https://www.56zw.com
https://www.56zw.com/10_10507/6672029.html

**Comment by Antecer** [comment]
![image](https://github.com/gedoor/legado/assets/8684916/60aea5aa-9270-4779-ab53-4d546364fc79)
它是这种东西，你自己添加一个替换净化的规则就行了。
把 `&lt;/p&gt;` 都替换掉

**Comment by wjwkill** [comment]
我自己写了一个规则，但是看起来没有效果，替换中文“一个”就可以，替换`&lt;/p&gt;`就不行，替换规则不生效
![Uploading 1.jpg…]()
![Uploading 2.jpg…]()

**Comment by wjwkill** [comment]
我自己写了一个规则，但是看起来没有效果，替换中文“一个”就可以，替换`&lt;/p&gt;`就不行，替换规则不生效
![1](https://github.com/gedoor/legado/assets/49703448/b3dd3f7c-6b31-46f3-ad59-3bb5906139da)
![2](https://github.com/gedoor/legado/assets/49703448/c001cbae-570b-4c78-a582-fe45457198eb)

**Comment by Antecer** [comment]
其实，有个简单的办法，你长按选中那些东西，然后在弹出菜单里面点击替换..
