### ISSUE TITLE
希望新增滑动或翻页不打断朗读的功能

### ISSUE THREAD

**Issue by XY50** [gedoor/legado#3905]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望新增滑动或翻页不打断朗读的功能，这个功能是刚需，QQ阅读、微信阅读、番茄小说、起点读书、书旗小说、几乎所有的小说软件都支持

### 期望实现方式 / How to implement

建议参考qq阅读，微信阅读，番茄小说，等各大阅读软件
![Screenshot_2024-05-01-22-29-59-063_io zhuliang pipphotos-edit](https://github.com/gedoor/legado/assets/121076219/9d3640cc-377b-41db-8610-e7c8dd0f975b)
![Screenshot_2024-05-01-22-29-45-185_io zhuliang pipphotos-edit](https://github.com/gedoor/legado/assets/121076219/2eda651f-8fb7-409e-a119-869876afb94a)
建议参考qq阅读，微信阅读，番茄小说，等各大阅读软件

**Comment by XY50** [comment]
很难实现吗？

**Comment by XY50** [comment]
...

**Comment by sheng-ri** [comment]
@821938089
这功能有考虑添加吗，比较想要

**Comment by 821938089** [comment]
@sheng-ri 
我不打算搞，你想要的话可以PR
