### ISSUE TITLE
更新最新测试版后部分书源不能用了

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#3906]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

最新测试版升级rhino后部分书源不能用了

### 复现步骤 / How to reproduce

最新测试版升级rhino后部分书源不能用了，之前版本都是正常
这是书源调试时的日志
[00:10.417] com.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "1" from null (<Unknown source>#5) in <Unknown source> at line number 5
	at com.script.rhino.RhinoScriptEngine.eval(SourceFile:33)
	at com.script.AbstractScriptEngine.eval(SourceFile:3)
	at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(SourceFile:119)
	at io.legado.app.model.analyzeRule.AnalyzeRule.getString(SourceFile:32)
	at io.legado.app.model.analyzeRule.AnalyzeRule.getString$default(SourceFile:2)
	at io.legado.app.model.analyzeRule.AnalyzeRule.getString(SourceFile:11)
	at io.legado.app.model.webBook.w.a(SourceFile:8)
	at io.legado.app.model.webBook.w.b(SourceFile:34)
	at io.legado.app.model.webBook.x0.k(SourceFile:463)
	at io.legado.app.model.webBook.s0.invokeSuspend(SourceFile)
	at m7.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.m0.run(SourceFile:127)
	at com.bumptech.glide.load.engine.a.run(SourceFile:15)
	at f9.k.run(SourceFile:3)
	at f9.b.run(SourceFile:96)
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "1" from null (<Unknown source>#5)
	at org.mozilla.javascript.ScriptRuntime.constructError(SourceFile:9)
	at org.mozilla.javascript.ScriptRuntime.constructError(SourceFile:3)
	at org.mozilla.javascript.ScriptRuntime.typeError(SourceFile:3)
	at org.mozilla.javascript.ScriptRuntime.typeErrorById(SourceFile:5)
	at org.mozilla.javascript.ScriptRuntime.undefReadError(SourceFile:20)
	at org.mozilla.javascript.ScriptRuntime.getObjectIndex(SourceFile:6)
	at org.mozilla.javascript.Interpreter.doGetElem(SourceFile:30)
	at org.mozilla.javascript.Interpreter.interpretLoop(SourceFile:99)
	at org.mozilla.javascript.Interpreter.interpret(SourceFile:57)
	at org.mozilla.javascript.InterpretedFunction.call(SourceFile:21)
	at org.mozilla.javascript.ContextFactory.doTopCall(SourceFile:1)
	at com.script.rhino.RhinoScriptEngine$1.superDoTopCall(SourceFile:1)
	at com.script.rhino.RhinoScriptEngine$1.doTopCall(SourceFile:60)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(SourceFile:8)
	at org.mozilla.javascript.InterpretedFunction.exec(SourceFile:23)
	at org.mozilla.javascript.Context.evaluateReader(SourceFile:7)
	at com.script.rhino.RhinoScriptEngine.eval(SourceFile:25)
	... 14 more

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.050213

### Android版本 / Android version

6

### 机型 / Model

sm919

**Comment by 821938089** [comment]
把书源发一下

**Comment by sartonsh** [comment]
{
  "bookSourceComment": "搜索不到时可以尝试以下格式搜索\n##完整书名",
  "bookSourceGroup": "☘️ 正版",
  "bookSourceName": "☘️ 晋江文学",
  "bookSourceType": 0,
  "bookSourceUrl": "https://m.jjwxc.net",
  "bookUrlPattern": "",
  "customOrder": 3,
  "enabled": true,
  "enabledCookieJar": true,
  "enabledExplore": true,
  "exploreUrl": "<js>\n//一行个数\nvar nums = 4 ;\n//分隔符\nvar separator = '::'\n\n//标题::链接::一行个数::分类\n\nall=[\"我的收藏::https://android.jjwxc.net/androidapi/incrementFavorite,{'method':'POST','body':'versionCode=279&token={{cookie.getKey('http://m.jjwxc.net','sid')}}&order=0&backupTime={{Date.now()}}'}\",\"今日限免::https://app-cdn.jjwxc.net/bookstore/getFullPage?channel=novelfree\",\"点击签到::https://m.jjwxc.net/my/signIn,{'headers':'cookie':'sid={{cookie.getKey(\\\"http://m.jjwxc.net\\\",\\\"sid\\\")}}'}\",\"百合搜索::https://app.jjwxc.org/search/getSearchForKeyWords?versionCode=226&offset={{(page-1)*20}}&limit=20&bq=0&removetags=0&fw=0&yc=0&xx=3&sd=0&lx=0&fg=0&mainview=0&fbsj=0&searchkeyWords={{String(source.getVariable()).match(/^搜索(.*)/)[1]}}&isfinish=2&token={{cookie.getKey('http://m.jjwxc.net','sid')}}&sortType=0\",\"🌸     百合全部    🌸::https://app-cdn.jjwxc.net/bookstore/getFullPage?channel=bhxs&version=3::1\",\"频道金榜::229\",\"运气淘文::2240000009\",\"勤奋更新::2226000013\",\"月度排行::2222000004\",\"季度排行::2222000005\",\"年度排行::2222000006\",\" VIP新文 ::2222000002\",\"新晋作者::2222000003\",\"🌸    百合完结    🌸::https://android.jjwxc.com/search/getSearchForKeyWords?versionCode=221&offset={{(page-1)*20}}&limit=20&bq=0&removetags=0&fw=0&yc=0&xx=3&sd=0&lx=0&fg=0&mainview=0&fbsj=0&isfinish=2&token={{cookie.getKey('https://m.jjwxc.net','sid')}}&sortType=2::1\",\"重来一世::2222000031\",\"幻想未来::2222000039\",\"架空历史::2222000033\",\"都市情缘::2222000040\",\"穿越时空::2222000034\",\"天赐良缘::2222000041\",\"时尚娱乐::2222000042\",\"奇幻异闻::2222000032\",\"系统快穿::2280000169\",\"宫廷侯爵::2280000165\",\"业界精英::2280000167\",\"情有独钟::2280000171\",\"🌸    百合连载    🌸::::1\",\"重来一世::2222000013\",\"幻想未来::2222000023\",\"架空历史::2222000015\",\"都市情缘::2222000024\",\"穿越时空::2222000016\",\"天赐良缘::2222000025\",\"时尚娱乐::2222000026\",\"奇幻异闻::2222000014\",\"系统快穿::2280000168\",\"宫廷侯爵::2280000164\",\"业界精英::2280000166\",\"情有独钟::2280000170\",\"-------- 标签[百合] --------::::1\",\"快穿::125::::bq\",\"穿书::134::::bq\",\"甜文::124::::bq\",\"重生::75::::bq\",\"爽文::137::::bq\",\"系统::122::::bq\",\"强强::19::::bq\",\"星际::135::::bq\",\"生子::20::::bq\",\"校园::185::::bq\",\"末世::81::::bq\",\"女配::96::::bq\",\"美食::99::::bq\",\"异能::72::::bq\",\"玄学::206::::bq\",\"打脸::138::::bq\",\"清穿::18::::bq\",\"女强::82::::bq\",\"直播::142::::bq\",\"年下::21::::bq\",\"武侠::11::::bq\",\"逆袭::184::::bq\",\"宫斗::74::::bq\",\"日韩::86::::bq\",\"婚恋::78::::bq\",\"竞技::70::::bq\",\"科举::174::::bq\",\"萌宠::205::::bq\",\"恐怖::29::::bq\",\"机甲::97::::bq\",\"科幻::28::::bq\",\"洪荒::67::::bq\",\"血族::69::::bq\",\"宅斗::73::::bq\",\"网红::141::::bq\",\"成长::183::::bq\",\"职场::98::::bq\",\"经商::180::::bq\",\"网配::84::::bq\",\"美娱::140::::bq\",\"商战::123::::bq\",\"传奇::89::::bq\",\"聊斋::188::::bq\",\"婆媳::80::::bq\",\"爱情::1::::lx\",\"武侠::2::::lx\",\"奇幻::3::::lx\",\"仙侠::4::::lx\",\"游戏::5::::lx\",\"传奇::6::::lx\",\"科幻::7::::lx\",\"童话::8::::lx\",\"惊悚::9::::lx\",\"悬疑::10::::lx\",\"剧情::16::::lx\",\"娱乐圈::64::::bq\",\"种田文::66::::bq\",\"年代文::173::::bq\",\"无限流::83::::bq\",\"少年漫::90::::bq\",\"古穿今::65::::bq\",\"升级流::139::::bq\",\"少女漫::14::::bq\",\"原著向::93::::bq\",\"姐弟恋::186::::bq\",\"大冒险::198::::bq\",\"轻小说::17::::lx\",\"穿越时空::60::::bq\",\"仙侠修真::68::::bq\",\"豪门世家::33::::bq\",\"随身空间::56::::bq\",\"情有独钟::39::::bq\",\"灵异神怪::26::::bq\",\"破镜重圆::47::::bq\",\"英美衍生::17::::bq\",\"虐恋情深::42::::bq\",\"青梅竹马::62::::bq\",\"超级英雄::132::::bq\",\"宫廷侯爵::32::::bq\",\"异世大陆::57::::bq\",\"悬疑推理::128::::bq\",\"天作之合::52::::bq\",\"天之骄子::54::::bq\",\"游戏网游::92::::bq\",\"都市情缘::30::::bq\",\"性别转换::24::::bq\",\"现代架空::126::::bq\",\"未来架空::127::::bq\",\"欢喜冤家::41::::bq\",\"前世今生::49::::bq\",\"幻想空间::25::::bq\",\"复仇虐渣::145::::bq\",\"东方玄幻::144::::bq\",\"朝堂之上::178::::bq\",\"奇幻魔幻::27::::bq\",\"励志人生::121::::bq\",\"民国旧影::61::::bq\",\"布衣生活::38::::bq\",\"业界精英::101::::bq\",\"历史衍生::91::::bq\",\"女扮男装::136::::bq\",\"市井生活::175::::bq\",\"古代幻想::189::::bq\",\"西方罗曼::59::::bq\",\"平步青云::55::::bq\",\"相爱相杀::103::::bq\",\"因缘邂逅::45::::bq\",\"灵魂转换::23::::bq\",\"魔法幻情::191::::bq\",\"西方名著::16::::bq\",\"江湖恩怨::35::::bq\",\"异国奇缘::37::::bq\",\"花季雨季::31::::bq\",\"制服情缘::85::::bq\",\"都市异闻::181::::bq\",\"古典名著::130::::bq\",\"近水楼台::46::::bq\",\"亡灵异族::192::::bq\",\"乔装改扮::51::::bq\",\"小门小户::177::::bq\",\"时代奇缘::22::::bq\",\"史诗奇幻::199::::bq\",\"阴差阳错::53::::bq\",\"恋爱合约::48::::bq\",\"异闻传说::196::::bq\",\"边缘恋歌::44::::bq\",\"三教九流::36::::bq\",\"骑士与剑::63::::bq\",\"七年之痒::79::::bq\",\"授权衍生::148::::bq\",\"异想天开::190::::bq\",\"乡村爱情::58::::bq\",\"爱情战争::50::::bq\",\"时尚流行::182::::bq\",\"时代新风::210::::bq\",\"古典衍生::20::::lx\",\"东方衍生::18::::lx\",\"西方衍生::19::::lx\",\"其他衍生::21::::lx\"];\n\n\n\n//@天天gg@酷安 下面不要动\nfunction parse(data){\n\tlet args=data.split(separator);\n\tlet title = args[0],url=args[1],num=nums;\n\t\n\t//链接生成\n\t let u=/^\\d+/.test(url)?\"http://app-cdn.jjwxc.net/bookstore/getFullPage?channelBody=%7B%\"+url+\"%22%3A%7B%22offset%22%3A%22{{(page-1)*25}}%22%2C%22limit%22%3A%2225%22%7D%7D&versionCode=148\":url;\n try {num = args[2] }catch(e){}\n try {tag = args[3];\n u=tag==\"bq\"?'https://android.jjwxc.com/search/getSearchForKeyWords?versionCode=221&offset={{(page-1)*20}}&limit=20&bq='+url+'&removetags=0&fw=0&yc=0&xx=3&sd=0&lx=0&fg=0&mainview=0&fbsj=0&collectionTypes=ors&isfinish=0&sortType=0&token={\\{cookie.getKey(\"https://m.jjwxc.net\",\"sid\")}\\}':u;\n u=tag==\"lx\"?'https://android.jjwxc.com/search/getSearchForKeyWords?versionCode=221&offset={{(page-1)*20}}&limit=20&bq=0&removetags=0&fw=0&yc=0&xx=3&sd=0&lx='+url+'&fg=0&mainview=0&fbsj=0&collectionTypes=ors&isfinish=0&sortType=0&token={\\{cookie.getKey(\"https://m.jjwxc.net\",\"sid\")}}':u\n }catch(e){}\n\treturn [title, u, num]\n\t}\n\nfunction FlexBox(title, url, num){\n\t\t let obj={};\n\t\t obj.style={},obj.title=title,obj.url=url?url:'',obj.style['layout_flexGrow']=1;\n\t//数值设定\n\tlet data={1:1,2:0.4,3:0.25,4:0.2,5:0.15,7:0.1,10:0.05};\nobj.style['layout_flexBasisPercent']=data[num]\n\t\treturn obj\n\t\t}\nresult=JSON.stringify(all.map(data=>{\n\tlet args=parse(data);\n\treturn FlexBox.apply(null, args)\n\t}))\n</js>",
  "header": "{\"User-Agent\": \"Dalvik/2.1.0\"}",
  "lastUpdateTime": 1714675619024,
  "loginCheckJs": "",
  "loginUrl": "https://m.jjwxc.net/",
  "respondTime": 202962,
  "ruleBookInfo": {
    "author": "$.authorName",
    "canReName": "1",
    "coverUrl": "{{$.novelCover}}\n<js>\nif(/(?:postimg|bmp|alicdn)\\./.test(result)){\n\tjava.setContent(src);\n\tresult = \"https://i9-static.jjwxc.net/novelimage.php?novelid={{$.novelId}}\"\n\t}else{\n\t\tresult = result\n\t\t}\n\n</js>",
    "init": "",
    "intro": "<js>\n//请假条\ntry{\na=JSON.parse(java.ajax('http://app.jjwxc.org/androidapi/getnovelOtherInfo?novelId='+baseUrl.match(/(\\d+)/)[1]+'&type=novelbasicinfo&versionCode=163'));\n\njava.put(\"pv\",a.novelreview)\n\n$=a.novelLeave;\nn='\\n';\nleave=$.leaveContent?'————————•————————'+n+'​'+n+$.leaveDateBack+n+'​'+'​'+'      '+$.leaveContent+n+$.leaveDate.replace(/请假时间：/,'⌚️')+n+$.leaveIntro:'';\njava.put('leave',leave);\njava.put('intro',JSON.parse(result).novelIntro.replace(/\\#/g,'＃'));\nresult}catch(err){\njava.log(err);\njava.put('leave',\"\");\njava.put('intro',\"\");\n}\n</js>\n{{/开启购买/.test(book.getVariable(\"custom\"))?\"&nbsp;&nbsp;💰已开启自动购买下五章，建议删除书籍变量的[开启/关闭购买]文字，避免刷新书籍时反复进行网络请求<br>\\n&lrm;<br>\":\"\"}}\n&nbsp;&nbsp;📖{{$.novelIntroShort##。$}}📖{{'\\n&lrm;'}}<br>\n🏆{{$.ranking}}    🍼{{$.nutrition_novel}}    📝{{$.comment_count}}    🔖{{$.novelStyle}}\n◉ 标签：{{$.novelTags##,|\\s##🏷}}<br>\n◉ {{$.protagonist##,|，|；|;##、}}<br>\n◉ {{$.costar##,|，|；|;##、}}<br>\n◉ {{$.other##,|，|；|;##、}}<br>\n◉ 视角：{{$.mainview}}<br>\n◉ 评分：{{java.get(\"pv\")}}<br>\n◉ 收藏：{{$.novelbefavoritedcount}}<br>\n{{String(java.get('intro')).replace(/立意:/,'◎◎ 立意：')}}<br>{{java.get('leave')}}<br>\n{{'\\n'+'​'}}\n\n<js>\nresult=String(result);\nli=result.match(/◎ 立意.*/)?'&lrm;\\n'+result.match(/(◎ 立意.*?<br>)/)[1]:'';\nString(result).replace(/📖📖|📖''📖/,'').replace(/(◉ 收藏.*?<br>)/,'$1\\n'+li+'&lrm;\\n'+'————————•————————\\n').replace(/◎◎ 立意.*<br>/,'').replace(/(?:◉ 标签：|◉ 主角：|◉ 配角：|◉ 其它：|◉ 视角：|◉ 评分：|&lrm;\\n◎ 立意：)<br>/g,'')</js>",
    "kind": "{{step=java.getString('$.novelStep')=='2'?'已完结':'连载中';}},{{$.novelClass&&$.novelTags}}##-##,",
    "lastChapter": "<js>\ntry{last=JSON.parse(java.ajax('http://android.jjwxc.net/androidapi/chapterList?novelId='+baseUrl.match(/(\\d+)/)[1])).chapterlist;\n$=last[last.length-1];\nvip=$.isvip?'🔒':'';\nchapterid=$.chapterid;\nchaptername=$.chaptername;\ndate=$.chapterdate;\nvip+chapterid+'.'+chaptername+' ★ '+date}\ncatch(err){\nresult=\"请刷新或暂无目录\"\n}\n</js>",
    "name": "$.novelName",
    "tocUrl": "http://app-cdn.jjwxc.net/androidapi/chapterList?novelId={{baseUrl.match(/novelId=(\\d+)/)[1]}}&more=0&whole=1&token={{cookie.getKey(\"http://m.jjwxc.net\",\"sid\")}}",
    "wordCount": "$.novelSize##,"
  },
  "ruleContent": {
    "content": "<js>\nif(baseUrl.match(/jjwxc/)){\nintro=java.get(\"intro1\");\nif(/token/.test(baseUrl) && !/message/.test(result)){\n\turl = \"https://android.jjwxc.net/androidapi/androidChapterBatchDownload,\";\n\tbody = \"versionCode=287&novelId=\"+baseUrl.match(/novelId=(\\d+)/)[1]+\"&chapterIds=\"+baseUrl.match(/chapterId=(\\d+)/)[1]+\"&token=\"+cookie.getKey(\"http://m.jjwxc.net\",\"sid\");\n\toption = {\n\t\t\"method\":\"POST\",\n\t\t\"body\":String(body)\n\t\t}\n\t\turl = url+JSON.stringify(option);\n\t\thtml = java.ajax(url)\n  \tjava.setContent(html)\n\t}\n\nintro=intro!=\"\"?\"◎\"+intro+\"◎<br>\":\"\";\ncontent=java.getString(\"$..content\");\nsaybody=java.getString(\"$..sayBody\");\nsay=saybody!=\"\"?\"\\n作者有话说：\\n\"+saybody:\"\";\nif(baseUrl.match(/token/)){\n\tvipc=String(content).length > 30?java.createSymmetricCrypto(\"DES/CBC/PKCS5Padding\", String(\"KW8Dvm2N\"), String(\"1ae2c94b\")).decryptStr(content):java.getString(\"$..message\")+\"\\n登录后请更新目录\";\n\t\n\t\nresult=intro+String(vipc+say);\n}else{result=intro+content+say}\n\n}else{result=\"&lrm;\"}\n\n\n//评论开启\nbbb = book.getVariable(\"custom\")\nsss=source.getVariable()\nif(/评论/.test(bbb) || /评论/.test(sss)){\n\t\nlet commentNum =/评论/.test(bbb)?bbb.match(/评论(\\d+)/)[1]:sss.match(/评论(\\d+)/)[1];\n\nif(/chapterContent/.test(baseUrl)){\ncommentUrl = baseUrl.replace(/androidapi/,'comment').replace(/chapterContent/,'getCommentList')+\"&limit=\"+commentNum+\"&offset=0\";\n}else if(/androidChapterBatchDownload/.test(baseUrl))\n{\n\tbody = baseUrl.match(/body\":\"(.*?)\"/)[1];\n\tcommentUrl = \"https://app.jjwxc.org/comment/getCommentList?\"+body+\"&limit=\"+commentNum+\"&offset=0&commentSort=0\"\n\t}\njava.log(commentUrl)\ncomment = JSON.parse(java.ajax(commentUrl));\ncflag = comment.code == \"200010\" ? false:true;\ncommentList = [];\nif(cflag){\n\tjava.log(JSON.stringify(comment))\ncommentList =comment.commentList || comment.data.commentList ;\ncommentb = \"\";\n}else{\n\tcommentb = comment.message\n\t}\nfor(i=0;i<commentList.length;i++){\n\tlet b = commentList[i];\n\tlet author = b.commentAuthor;\n\tlet body = b.commentBody;\n\tlet time = b.commentDate;\n\tcommentb+=\"▪\"+author+\" ——\"+time+\"▪\\n\"+body+\"\\n\";\n\t}\nresult = result + \"\\n&lrm;\\n最新评论：\\n\" + commentb\n}\nresult\n</js>\n##为营造更好的评论环境，近期网站要求发评须进行实名认证，未实名用户评论暂时仅在对应作者后台及发评用户后台可见.*|获取正文失败[\\s\\S]+|◎\\s+?◎",
    "imageStyle": "TEXT",
    "nextContentUrl": "",
    "payAction": "cid = baseUrl.match(/chapterId=(\\d+)/)[1];\nnid = baseUrl.match(/novelId=(\\d+)/)[1];\ntoken = baseUrl.match(/token=(.*?)&/)[1];\nenbody = String(Date.now())+\":\"+token+\":\"+nid;\nsign = java.createSymmetricCrypto(\"DES/CBC/PKCS5Padding\", String(\"KW8Dvm2N\"), String(\"1ae2c94b\")).encryptBase64(enbody)\n\nbody = \"versionCode=287&novelId=\"+nid+\"&chapters=\"+cid+\"&orderType=15&isautoBuy=0&autosubscribeStatus=0&notUseBackpoint=&sign=\"+sign;\n\nurl = \"https://android.jjwxc.net/androidapi/buy,\"\npost = {\n\t\"method\":\"POST\",\n\t\"body\":String(body)\n\t}\n a = java.ajax(url+JSON.stringify(post));\njava.toast(JSON.parse(a).message+\"请刷新正文\");",
    "replaceRegex": "@js:\n//去除章节简介与正文重复\nif(/^◎/.test(result) ){\nchapter = result.match(/◎([\\s\\S]+?)(…)*◎/)[1].replace(/\\s/g,'').replace(/,/g,'，');\n\nchapter2=result.match(/◎[\\s\\S]+?◎([\\s\\S]+)/)[1].replace(/\\s/g,'').replace(/,/g,'，');\n\n//前十个字相同就删除\nnum = 10\nif(chapter.substring(0,num)==chapter2.substring(0,num)){\n\tresult = result.replace(/◎[\\s\\S]+?◎/,'')\n\t}else{result}\n}else{result}",
    "sourceRegex": "",
    "webJs": ""
  },
  "ruleExplore": {
    "author": "$.authorName||$.authorname",
    "bookList": "@JSon:$..[?(@.novelName)]&&$..[?(@.novelname)]&&$.massage\n<js>\nif(result){\nfunction remove(a,b){\nlet delIndexList = a; // 要删除的序列\n if (delIndexList.length !== 0) { \nfor (let i = delIndexList.length - 1; i >= 0; i--) { b.splice(delIndexList[i], 1) } \nreturn b\n}\n}\n\nif(baseUrl=='https://app-cdn.jjwxc.net/bookstore/getFullPage?channel=bhxs&version=3'||baseUrl.match(/novelfree/)){\nlist=JSON.parse(src);\nfor(i in list){\nchannelName=list[i].channelName;\nblist=list[i].data;\nif(blist!=\"undefined\"){\nfor(j in blist){\nblist[j].channelName=channelName\n}}else{blist.channelName=channelName}\n\n}\nif(!baseUrl.match(/novelfree/)){\nlist=remove([0, 6,11,12,13],list)\n}else{\nlist=remove([1],list)\n}\nresult=JSON.stringify(list);}\nelse if(baseUrl.match(/signIn|getSearchForKeyWords/)){\nresult=\"{signIn:[\"+src+\"]}\"\n}\nelse{result=result}\n}else{result=\"\"}\n</js>\n$..[?(@.novelName)]&&$..[?(@.novelname)]&&$.signIn[*]",
    "bookUrl": "http://app-cdn.jjwxc.net/androidapi/novelbasicinfo?novelId={{$.novelid||$.novelId}}@put:{id:$.novelid||$.novelId}",
    "coverUrl": "@JSon:$.cover||$.novelCover||$.ebookurl",
    "intro": "$.novelIntroShort||$.novelintroshort\n<js>\nfree=\"{{$.freeDate}}\";\nif(free!=\"\"){\nresult=\"限免日期：🗓\"+free+\"\\n\"+result\n}else{\nresult=result\n}\n</js>",
    "kind": "@JSon:$.channelName&&$.tags&&$.novelSizeformat&&$.className##\\s+##,",
    "lastChapter": "第{{$.maxChapterId}}章##第章",
    "name": "$.novelName||$.novelname||$.message",
    "wordCount": "$.novelStep||$.novelstep\n@js:result==2?'已完结':'连载中';"
  },
  "ruleSearch": {
    "author": "@JSon:$.authorname",
    "bookList": "<js>\nkey=java.get('key');\npage=java.get('page');\n\n//创建两个空数组\njson=[];json2=[];\n\n//判定json里是否有items\nif(JSON.parse(result).items){\njson=JSON.parse(result).items;}\n\n//加载作者搜索页面并转为json\njson1=JSON.parse(java.ajax('http://android.jjwxc.net/androidapi/search?keyword='+key+'&type=2&page='+page+'&searchType=2&sortMode=DESC'));\n\n//判定json里是否有items\nif(json1.items){\njson2=json1.items\n}\n\n//书名搜索列表与作者搜索列表拼接\nlist=json.concat(json2);\n\n\nresult=JSON.stringify(list)\n</js>\n$.[*]",
    "bookUrl": "http://app-cdn.jjwxc.net/androidapi/novelbasicinfo?novelId={{$.novelid||$.novelId}}",
    "checkKeyWord": "穿进刑侦文",
    "coverUrl": "@JSon:$.cover",
    "intro": "$.novelintroshort",
    "kind": "@JSon:$.tags&&$.novelSizeformat##\\s##,",
    "lastChapter": "@js:\nlast=JSON.parse(java.ajax('http://android.jjwxc.net/androidapi/chapterList?novelId={{$.novelid||$.novelId}}')).chapterlist;\nif(last){\nlast=last[last.length-1];\nvip=last.isvip!=0?\"🔒\":'';\ndate=last.chapterdate;\nchapter=last.chaptername;\nchapterid=last.chapterid;\nresult=vip+chapterid+'.'+chapter+' ★ '+date}",
    "name": "$.novelname@put:{id:$.novelid||$.novelId}",
    "wordCount": "$.novelstep\n@js:result==2?'已完结':'连载中';"
  },
  "ruleToc": {
    "chapterList": "<js>\nif(/登入验证失败/.test(result)){\nurl = baseUrl.replace(/&token.*/,'');\njava.ajax(url)\n}else{\n\tresult\n\t}\n</js>\n$.chapterlist\n<js>\nfunction readEncrypt(novelid,flag) {\n     \tFORUMSIGNTAG = 1;\n       READSIGNTAG = 0;\n\t      strArr = [cookie.getKey('http://m.jjwxc.net','sid'),novelid,\"autosubscribe\",flag];\n\t         \n\t      sb = new Date().getTime().toString();\n         length = strArr.length;\n        for ( i2 = READSIGNTAG; i2 < length; i2 += FORUMSIGNTAG) {\n            str = strArr[i2];\n            sb+=\":\";\n            sb+=str;\n        }\n\t     \n\t    en= java.createSymmetricCrypto(\"DES/CBC/PKCS5Padding\", String(\"KW8Dvm2N\"), String(\"1ae2c94b\")).encryptBase64(sb)\n\t    \n\t      body = \"versionCode=287&sign=\"+en;\noption = {\n\tmethod:\"POST\",\n\tbody:String(body)\n\t}\nurl = \"https://android.jjwxc.com/androidapi/autoSubscribe,\"+JSON.stringify(option); java.longToast(JSON.parse(java.ajax(url)).message)\n    }\n    \n if(/(开启|关闭)购买/.test(book.getVariable(\"custom\"))){\n \ta = /关闭购买/.test(book.getVariable(\"custom\"))?\"cancel\":(/开启购买/.test(book.getVariable(\"custom\"))?\"open\":\"cancel\");\n \treadEncrypt(JSON.parse(result)[0].novelid,a)\n \t}\n \t\nresult = result==\"[]\"?JSON.stringify([{\"chaptername\":\"暂无目录\",\"chapterid\":\"\",\"islock\":\"0\"}]):result;\n</js>\n$.[*]",
    "chapterName": "<js>\n$=result;\ntitle=$.chaptername;\ntitle=String(title).replace(/^\\s+/,'');\nintro=$.chapterintro;\nvip=$.isvip!='0';\nlock=$.islock!='0';\ntype=$.chaptertype=='1'?true:false;\nnum=!type?$.chapterid+\"  ☪ \":'';\n\n//下面被注释的代码是已经有章节数的前面就不加序号了\nbbb = book.getVariable(\"custom\");\nsss = source.getVariable();\nif(/去章节序号/.test(bbb) || /去章节序号/.test(sss)){\nnum=''\n}else{num=num}\n\ntitle=type?'📖 '+title+' 📖':title;\nif( (/目录简介/.test(bbb) || /目录简介/.test(sss))&&!/📖/.test(title)){\n\ttitle = title + \" ❖ \"+intro\n\t}else{\n\t\ttitle = title\n\t\tjava.put(\"intro1\",intro);\n\t\t}\n\nl=lock?'[此章节已锁]':'';\nresult=num+title+l;\n</js>",
    "chapterUrl": "@js:\n$=result;\ncookie=cookie.getKey(\"http://m.jjwxc.net\",\"sid\");\nchapterid=$.chapterid;\nvip=$.isvip!='0';\n\ntype=$.chaptertype=='1';\n\nif( !type){\nif(!vip){\nresult='https://app.jjwxc.net/androidapi/chapterContent?novelId='+baseUrl.match(/novelId=(\\d+)/)[1]+'&chapterId='+chapterid\n}else{\n\turl = \"https://android.jjwxc.com/androidapi/chapterContent?novelId=\"+baseUrl.match(/novelId=(\\d+)/)[1]+\"&versionCode=287&token=\"+cookie+\"&chapterId=\"+chapterid\n\t}\n}else{ result=\"\"}",
    "isPay": "$..point\n<js>\nresult!=0?false:true\n</js>",
    "isVip": "$..isvip",
    "isVolume": "<js>\n\"{{$.chaptertype}}\"=='1'?true:false;\n</js>",
    "preUpdateJs": "java.refreshTocUrl();",
    "updateTime": "{{$.chaptersize}}字•{{$.chapterdate}}•{{$.chapterintro##^\\s*}}##^•|0000-00-00.*|^0字•|•$"
  },
  "searchUrl": "http://android.jjwxc.net/androidapi/search?keyword={{key}}&type=1&page={{page}}&searchType=1&sortMode=DESC\n@js:java.put('key',key);java.put('page',page);result",
  "variableComment": "1、书籍变量（当前书）\n填写 [去章节序号] —— 去除章节序号\n\n填写 [目录简介] —— 章节简介放到目录列表，正文不出现\n\n填写 [评论+评论数量]——如 评论50  则可以显示50条评论，数量必填\n\n填写 [开启购买/关闭购买]  —— 如 开启购买 则会开启自动购买下五章【确认以后点右上角三点刷新才会生效，使用完毕后最好删除，避免重复请求】\n\n2、源变量（所有书）\n其余同书籍变量\n填写[搜索+书名] —— 必须在第一行，搜索百合书籍，在发现里点击[百合搜索]",
  "weight": 0
}

**Comment by sartonsh** [comment]
另外页面的时间，电量都不刷新了
![Uploading Screenshot_2024-05-03-10-18-03-627_阅读.png…]()

**Comment by Xwite** [comment]
`com.jayway.jsonpath.ReadContext.#read`返回的是`java.util.LinkedHashMap`，而rhinojs1.714默认关闭特性`FEATURE_ENABLE_JAVA_MAP_ACCESS`
https://github.com/mozilla/rhino/issues/820

一是启用特性
https://github.com/gedoor/legado/blob/38daea8487695b66e7dcb01d30f38a585afc28c9/modules/rhino/src/main/java/com/script/rhino/RhinoScriptEngine.kt#L313
二是改源
```js
result.bookName // rhino 1.7.14之前
result.get("bookName") //rhino 1.7.14（含）之后
```
