### ISSUE TITLE
最新测试版时间和电量不刷新

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#3908]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

最新测试版时间和电量不刷新

### 复现步骤 / How to reproduce

最新测试版时间和电量不刷新

![Screenshot_2024-05-03-10-18-03-627_阅读](https://github.com/gedoor/legado/assets/74254385/2eee6a6d-cdb0-4a0b-b4fd-ba88a68adb0b)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.050213

### Android版本 / Android version

6

### 机型 / Model

sm919

**Comment by 821938089** [comment]
不能复现，你可以重启下手机试试

**Comment by sartonsh** [comment]
安装新版后又好了
