### ISSUE TITLE
阅读页点击中间进入菜单区会导致排版变化

### ISSUE THREAD

**Issue by cyrnicolase** [gedoor/legado#3920]
问题描述 / Describe Bugs
在阅读页时，点击页面中部进入菜单区时，文章内容的排版会发生变化

复现步骤 / How to reproduce
进入阅读页
点击页面中部，进入到菜单页
观察文章内容区域，会发现文字位置会发生偏移
离开菜单区，文字内容有恢复回来
阅读版本 / Legado version
3.23.110211

Android版本 / Android version
Android 13

机型 / Model
Honor90

https://github.com/gedoor/legado/assets/2086960/047bc584-0177-4de8-a1d1-256555183197

视频录制如上！可以看出来每次弹出菜单栏的时候，中间阅读区域都是会有闪的情况。

**Comment by adhu2018** [comment]
阅读界面设置里打开扩展到刘海

**Comment by cyrnicolase** [comment]
完美解决！
