### ISSUE TITLE
添加划线和高亮显示功能

### ISSUE THREAD

**Issue by Mshaoyang1991** [gedoor/legado#3927]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望添加类似微信读书或koodo的划线和高亮显示功能，便于知识整理，目前只有书签功能，不便于知识回顾和整理。
koodo 的高亮功能1

### 期望实现方式 / How to implement

可参考koodo 和 微信阅读
![屏幕截图 2024-05-10 115121](https://github.com/gedoor/legado/assets/90541090/4ced3444-ded5-45b1-b371-181b9f2bb781)
![屏幕截图 2024-05-10 115419](https://github.com/gedoor/legado/assets/90541090/a6a43b7d-782f-4f0f-a518-52fd185ff051)

**Comment by vlate** [comment]
同意，需求加一。

**Comment by ybbluesky** [comment]
有这需求，加一
