### ISSUE TITLE
启动Web服务失败提示：web service cant start, no ip address

### ISSUE THREAD

**Issue by cheerwold** [gedoor/legado#3929]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

使用4G网络时，无法启动Web服务，提示：web service cant start, no ip address

### 复现步骤 / How to reproduce

1. 使用环境（4G + zerotier + zerotier IP访问)

2. 最新Test版本, legado_app_3.24.05110657_原包名.apk, 启动Web服务失败：
Test Build #4652: Commit [06d486c](https://github.com/gedoor/legado/commit/06d486c96c3dc327fa42dee0eeae2b2c24f9b9b0) pushed by [821938089](https://github.com/821938089)

3. 退回旧版本, legado_app_3.24.03272326_原包名.apk, 启动Web服务成功：
Test Build #4562: Commit [68eddef](https://github.com/gedoor/legado/commit/68eddefb94afcbead3a08e1754ad4f87e46c52c4) pushed by [821938089](https://github.com/821938089)

4. 本人不是java开发，看代码感觉是 [app/src/main/java/io/legado/app/utils/NetworkUtils.kt](https://github.com/gedoor/legado/commit/9c50621895b554964a890595c8e70db1c8bfa271#diff-3c79ef0f86416f527f37069e4d0824f0f96fc80013f903f315e50329ef612b75) 修改后的原因，望大佬帮忙查看

### 阅读版本 / Legado version

3.24.05110657

### Android版本 / Android version

Android 13

### 机型 / Model

Realme RMX3366

**Comment by 821938089** [comment]
试试最新测试版

**Comment by cheerwold** [comment]
> 试试最新测试版

已测试，在WIFI和移动网络都可正常启动Web服务👍👍👍
