### ISSUE TITLE
优化页码显示

### ISSUE THREAD

**Issue by vlate** [gedoor/legado#3931]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

当前页数只有当前章节的进度和页数，希望增加全书页数和当前页数，类似微信读书的页码显示方式。

### 期望实现方式 / How to implement

能够显示本书总页数。

### 附加信息 / Additions

如上。

**Comment by qux-bbb** [comment]
全书页数也是可以显示的  
打开一本书，点中间一下呼出配置界面，选择下方的"界面"  
新页面选择右侧的"信息"  
新页面的"页脚"，可以自定义左中右的显示信息，其中的"进度(xx/yyy)"就是当前页数和全书页数

**Comment by licocy** [comment]
> 全书页数也是可以显示的 打开一本书，点中间一下呼出配置界面，选择下方的"界面" 新页面选择右侧的"信息" 新页面的"页脚"，可以自定义左中右的显示信息，其中的"进度(xx/yyy)"就是当前页数和全书页数

打开“进度(xx/yyy)”后显示的页数，会出现连续翻好多页页数不变化的情况，似乎计算的并不是当前页数？
