### ISSUE TITLE
是否可以添加本地自动备份

### ISSUE THREAD

**Issue by sht2017** [gedoor/legado#3932]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

如题，是否可以在退出时自动备份到本地文件夹

### 期望实现方式 / How to implement

如果备份路径非空则在退出时调用对应方法

**Comment by sht2017** [comment]
听一些朋友说以前是有的 可能是某次更新破坏了？ github和telegram（beta）上最新的release在我的设备上都实测无效。
设备： Google Pixel 8 Pro
系统： Android 14 （AP1A.240505.005）
应用版本： 3.24.051501 （telegram上的beta release）
包名： io.legado.app.release

**Comment by 821938089** [comment]
有自动备份啊，你先试试手动备份是否成功

**Comment by adhu2018** [comment]
一天只会自动备份一次，正常退出才会备份，如返回两次退出

**Comment by Sun-QAQ** [comment]
> 一天只会自动备份一次，正常退出才会备份，如返回两次退出

这不是有自动备份吗，你的需求是什么？
