### ISSUE TITLE
期望定时结束后退出APP

### ISSUE THREAD

**Issue by xiaoniezi** [gedoor/legado#3934]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

睡前设定了听书定时时间，到时间后听书暂停。希望可以退出APP，不耗费电量

### 期望实现方式 / How to implement

可不可以加个控制，定时结束自动退出APP，杀死进程。

**Comment by huaxuanHan** [comment]
请问一下新版本在哪里下载？

**Comment by xiaoniezi** [comment]
> 

[版本地址](https://github.com/gedoor/legado/releases)
选择版本下的apk应用包

**Comment by huaxuanHan** [comment]
[legado_app_3.23.110211](https://github.com/gedoor/legado/releases/tag/3.23.110211)
这个版本以后没新版本了？

**Comment by xiaoniezi** [comment]
> [legado_app_3.23.110211](https://github.com/gedoor/legado/releases/tag/3.23.110211) 这个版本以后没新版本了？

是吧，我用的就是这个版本

**Comment by huaxuanHan** [comment]
感谢

**Comment by sht2017** [comment]
> [legado_app_3.23.110211](https://github.com/gedoor/legado/releases/tag/3.23.110211) 这个版本以后没新版本了？

不知道为什么github上停止更新了 明明nightly弄个github action就行 似乎现在更新都是在tg上

**Comment by xiaoniezi** [comment]
> > [legado_app_3.23.110211](https://github.com/gedoor/legado/releases/tag/3.23.110211) 这个版本以后没新版本了？
> 
> 不知道为什么github上停止更新了 明明nightly弄个github action就行 似乎现在更新都是在tg上

有下载地址吗？

**Comment by zhangzw218** [comment]
> > [legado_app_3.23.110211](https://github.com/gedoor/legado/releases/tag/3.23.110211) 这个版本以后没新版本了？
> 
> 不知道为什么github上停止更新了 明明nightly弄个github action就行 似乎现在更新都是在tg上

什么意思？还有更高的版本？ tg是啥

**Comment by xiaoniezi** [comment]
> > > [legado_app_3.23.110211](https://github.com/gedoor/legado/releases/tag/3.23.110211) 这个版本以后没新版本了？
> > 
> > 
> > 不知道为什么github上停止更新了 明明nightly弄个github action就行 似乎现在更新都是在tg上
> 
> 什么意思？还有更高的版本？ tg是啥

下载地址： [beta版下载](https://beta.miaogongzi.cc/)
更新前最好备份一下

**Comment by zhangzw218** [comment]
> > > > [legado_app_3.23.110211](https://github.com/gedoor/legado/releases/tag/3.23.110211) 这个版本以后没新版本了？
> > > 
> > > 
> > > 不知道为什么github上停止更新了 明明nightly弄个github action就行 似乎现在更新都是在tg上
> > 
> > 
> > 什么意思？还有更高的版本？ tg是啥
> 
> 下载地址： [beta版下载](https://beta.miaogongzi.cc/) 更新前最好备份一下

多谢
