### ISSUE TITLE
java.startBrowserAwait()使用的ua不是我在书源请求头中设置的

### ISSUE THREAD

**Issue by xianfanjie** [gedoor/legado#3935]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

调用java.startBrowserAwait()方法过cloudflare验证的时候,使用的是我在阅读设置用户代理填写的ua，而不是我在书源请求头设置的，因为ua不一样过不去验证。
不想修改我在阅读用户代理里面设置的ua，调用java.startBrowserAwait()方法的时候手动再重新构造一个包含相同ua的请求头感觉有点麻烦，因为我已经在书源请求头里面设置过了。

### 期望实现方式 / How to implement

希望能改为使用书源请求头中设置的

**Comment by xianfanjie** [comment]
> 正常应该使用书源请求头里面的UA，检查是不是写错了 你用的是最新的测试版本吗？

> 我是测试版的，上周更新过。抓包发现使用的是java.getWebViewUA()这个返回的ua,和我手机的ua是一样的，用的也不是阅读用户代理里面填的ua
我书源请求头是这样设置的:
 
@js:
(() => {
    var headers = {
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.9999.99 Safari/537.36",
        "referer": baseUrl
    };
    return JSON.stringify(headers);
})();

**Comment by 821938089** [comment]
user-agent 要大写 User-Agent
还有 referer 大写才是正确的 Referer

**Comment by xianfanjie** [comment]
> user-agent 要大写 User-Agent 还有 referer 大写才是正确的 Referer

没问题了，没想到还得要求大写才行。

**Comment by xianfanjie** [comment]
> user-agent 要大写 User-Agent 还有 referer 大写才是正确的 Referer

好像有些字段设置了无效
![IMG_20240517_162310](https://github.com/gedoor/legado/assets/102248059/f6ffe457-7cf1-4d6c-a259-917c2383170d
Sec-ch-ua这些设置了覆盖不了。

**Comment by 821938089** [comment]
应该是webview限制了，改不了

**Comment by xianfanjie** [comment]
> 应该是webview限制了，改不了

好吧，谢谢大佬解答。
