### ISSUE TITLE
书签同步

### ISSUE THREAD

**Issue by zyh778** [gedoor/legado#3936]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前不同端的书签无法同步，不利于阅读

### 期望实现方式 / How to implement

通过webdev的设置，同步阅读的书签

**Comment by 821938089** [comment]
这个应该是可以同步的，如果没有的话也可以手动再恢复一下备份
