### ISSUE TITLE
优化左右分栏漫画阅读

### ISSUE THREAD

**Issue by luo-chuan** [gedoor/legado#3938]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

我用的折叠屏手机，即使把屏幕展开，看左右分栏的漫画仍然很费眼睛，字小，画面小。下图是《犬夜叉》在开源阅读中的显示画面：
![Screenshot_20240520_174045_io legado app release](https://github.com/gedoor/legado/assets/33930736/978e1bf7-f796-4ef3-a444-6274557d832c)

### 期望实现方式 / How to implement

可以参考 [mihon](https://github.com/mihonapp/mihon) APP，它是一个专业的漫画阅读APP，它可以将这种分栏的漫画左右分开，重新排列，显示画面大，字大，不费眼。下图是《犬夜叉》在mihon中的显示效果：
![Screenshot_20240520_174543_app mihon debug](https://github.com/gedoor/legado/assets/33930736/b126459b-8c17-4f80-af2d-2804da82d02f)

**Comment by Sun-QAQ** [comment]
你上面这个两栏是一张图片吧，下边是一栏就是一张图片，建议换个源

**Comment by luo-chuan** [comment]
> 你上面这个两栏是一张图片吧，下边是一栏就是一张图片，建议换个源

你错了，这是mihon的特色功能。如图：
![Screenshot_20240521_221750_app mihon debug](https://github.com/gedoor/legado/assets/33930736/5430f024-ea49-4150-ad80-349435991e1f)

**Comment by Sun-QAQ** [comment]
> > 你上面这个两栏是一张图片吧，下边是一栏就是一张图片，建议换个源
> 
> 你错了，这是mihon的特色功能。如图： ![Screenshot_20240521_221750_app mihon debug](https://private-user-images.githubusercontent.com/33930736/332461098-5430f024-ea49-4150-ad80-349435991e1f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTk0NzcsIm5iZiI6MTcxNjM1OTE3NywicGF0aCI6Ii8zMzkzMDczNi8zMzI0NjEwOTgtNTQzMGYwMjQtZWE0OS00MTUwLWFkODAtMzQ5NDM1OTkxZTFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA2MjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMDFiODlkOWE3OTYwMTFkMTQyY2M3NDVkMDI1MTk3OTIxNWI5OWNiNzAxMTUzMzVjNmExMDBmMTQ3YWE5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IbnvPMukm9oM0pZyxXjMxZjWGu5EDlqwSpPj60jDhI0)

还是换个源比较好，直接找一栏就是一张图片的，感觉阅读不太好实现它这个算法，而且也没必要
