### ISSUE TITLE
Bold and italic

### ISSUE THREAD

**Issue by unOmni** [gedoor/legado#3939]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

The app needs to be able to support bold and italic when reading.

### 期望实现方式 / How to implement

Unsure…

### 效果演示 / Demo

Example:
![Screenshot_20240520-162658](https://github.com/gedoor/legado/assets/106206117/cac7d0ec-a3d6-4e5b-b2c6-21bf67f13159)
![Screenshot_20240520-162734](https://github.com/gedoor/legado/assets/106206117/7e73291d-fc42-4735-9422-cf0358f00da8)

**Comment by unOmni** [comment]
Up

**Comment by unOmni** [comment]
Maybe something like what moon reader does can be implemented, being able to use otf/ttf for each case.

**Comment by Xhichn** [comment]
It looks like current implementation will remove all the html tags except <img> and just display the plain text only. https://github.com/gedoor/legado/blob/84813a549c28087e739e92b4bb4136fa581b20a1/app/src/main/java/io/legado/app/utils/HtmlFormatter.kt

**Comment by unOmni** [comment]
> It looks like current implementation will remove all the html tags except `<img>` and just display the plain text only. https://github.com/gedoor/legado/blob/84813a549c28087e739e92b4bb4136fa581b20a1/app/src/main/java/io/legado/app/utils/HtmlFormatter.kt

Hopefully that changes.
