### ISSUE TITLE
web服务设置中开启无限加载异常

### ISSUE THREAD

**Issue by zzmalone** [gedoor/legado#3942]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

    小米手机打开web服务，电脑浏览器中阅读模式设置无限加载，要么重复同一章节内容，要么加载不过去，点击下一章后，还需点击设置，不停点击无限加载中的开启选项后，章节内容才可以展现。

### 复现步骤 / How to reproduce

高频率复现，可以说是100%

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

澎湃OS

### 机型 / Model

小米13pro

**Comment by zzmalone** [comment]
没有出现相同问题的吗？太纠结了

**Comment by 821938089** [comment]
不能复现，你是在应用前台亮屏下测试的吗
