### ISSUE TITLE
部分情况下Epub中图片无法正常加载

### ISSUE THREAD

**Issue by weiwei-cool** [gedoor/legado#3948]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

在epub中，如果一个src标签引用了某个目录下的图片，那么该图片将无法被加载

### 复现步骤 / How to reproduce

若一个epub电子书中存在src引用某个epub内的目录内的图片时，图片无法被正常加载

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

[不白吃漫画这就是世界美食.zip](https://github.com/gedoor/legado/files/15437356/default.zip)
如该文件，在其它阅读器内图片能被正常加载，但阅读会报错

### 阅读版本 / Legado version

3.23.121012

### Android版本 / Android version

Android 14

### 机型 / Model

Oneplus Ace2v

**Comment by 821938089** [comment]
已修复，试试最新测试版

**Comment by weiwei-cool** [comment]
> 已修复，试试最新测试版

经过测试，该bug已经完美修复，感谢开发者对开源社区的贡献，也感谢开发者提供如此优秀的阅读项目！
