### ISSUE TITLE
WebView会被网站识别并且封禁IP

### ISSUE THREAD

**Issue by zhangzw218** [gedoor/legado#3954]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

调试时，如果调用了webView会导致IP被封禁一段时间（几分钟）
可以先用--https://www.69shuba.pro/txt/51672/33761347试试，一开始是可以的。
但是先调用 --https://www.69shuba.pro/txt/51672/33761347,{"webView":true} 会访问不了。
这时候IP已经近了，再调用--https://www.69shuba.pro/txt/51672/33761347也没办法了。

### 复现步骤 / How to reproduce

这个只是猜测，我最近访问69，浏览器可以正常访问，但是一旦通过本软件阅读，就打不开了，这时候再用浏览器还是打不开。
只能通过更换IP解决。。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

鸿蒙4

### 机型 / Model

华为P40

**Comment by xianfanjie** [comment]
X-Requested-With值为io.legado.app.release就会被封  请求头把这个值设置为其他的可以访问，只对首次webView请求有效果。

**Comment by xianfanjie** [comment]
> > X-Requested-With值为io.legado.app.release就会被封 请求头把这个值设置为其他的可以访问，只对首次webView请求有效果。
> 
> 这个应该是代码中的？还是我们可以在APP中设置？

应该是webView发送请求会自动把X-Requested-With设置为应用包名

**Comment by zhangzw218** [comment]
那有哪位大佬帮忙搞个可自定义RequestedWith参数的版本么？或者这个参数移除会有什么影响么。

**Comment by xianfanjie** [comment]
> @xianfanjie 那大佬帮忙搞个可自定义RequestedWith参数的版本么？或者这个参数移除会有什么影响么。

书源请求头里面添加就行，其它的我也没办法

**Comment by zhangzw218** [comment]
> > @xianfanjie 那大佬帮忙搞个可自定义RequestedWith参数的版本么？或者这个参数移除会有什么影响么。
> 
> 书源请求头里面添加就行，其它的我也没办法

多谢，搞定了
