### ISSUE TITLE
第一次拉下来编译报空指针，提示引用的第三方库java.lang.NullPointerException

### ISSUE THREAD

**Issue by kube1206** [gedoor/legado#3955]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

> Task :app:mergeExtDexAppDebug
AGPBI: {"kind":"error","text":"java.lang.NullPointerException","sources":[{"file":"C:\\Users\\Administrator\\.gradle\\caches\\modules-2\\files-2.1\\org.slf4j\\slf4j-api\\2.0.11\\ad96c3f8cf895e696dd35c2bc8e8ebe710be9e6d\\slf4j-api-2.0.11.jar"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"java.lang.NullPointerException: Cannot invoke \"String.length()\" because \"<parameter1>\" is null","sources":[{"file":"C:\\Users\\Administrator\\.gradle\\caches\\modules-2\\files-2.1\\org.apache.commons\\commons-lang3\\3.14.0\\1ed471194b02f2c6cb734a0cd6f6f107c673afae\\commons-lang3-3.14.0.jar"}],"tool":"D8"}

> Task :app:mergeExtDexAppDebug FAILED

java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
![6](https://github.com/gedoor/legado/assets/7588187/c3fde2d3-8da0-44bf-811c-eb8d94eab19a)

### 复现步骤 / How to reproduce

第一次拉下master代码后编译

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

9247d56

### Android版本 / Android version

Adnroid 33

### 机型 / Model

Redmi K60

**Comment by 821938089** [comment]
你用的是git clone下载的源码吗，不要download zip
