### ISSUE TITLE
下载和听书时总会跳出提示框

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#3957]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

最新测试版下载和听书时总会跳出提示框
![Screenshot_2024-05-30-05-51-45-823_阅读](https://github.com/gedoor/legado/assets/74254385/da23023b-466f-44a5-b788-36ff05cf9cef)
不知是不是bug，如果是这样的设置，希望改进为提醒一次。

### 复现步骤 / How to reproduce

最新测试版下载和听书时总会跳出提示框

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.0529

### Android版本 / Android version

6

### 机型 / Model

sm919

**Comment by 821938089** [comment]
改了一下，现在Android 12以上才会请求权限
