### ISSUE TITLE
书架同步到源

### ISSUE THREAD

**Issue by huajideshutiao** [gedoor/legado#3958]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望增加一个功能，允许源将书架/发现中的作品添加/删除到对应源站的书架中

至于为啥想要这个功能，其实源站的书架就相当于一个备份了。而且方便在官方客户端与阅读之间切换。通常站点的个性化推送都是集成在app中的，想要提取出来很麻烦，有这个功能就可以直接无缝切换而不需要考虑源站书架和阅读书架的一致性了。

### 期望实现方式 / How to implement

大致分为两个方面

对于用户来说，可以将源站的书架直接拉取到本地的默认分组中(具体实现可以复用发现，如图)
![IMG_20240530_093317](https://github.com/gedoor/legado/assets/38980554/224d4a2f-e4d5-4316-b67b-1df66eca4654)
如果是单个书籍，可以直接在这里塞个按钮。
![Screenshot_2024-05-30-09-42-34-727_io legado app release](https://github.com/gedoor/legado/assets/38980554/581b8171-b976-429a-882d-edf5d85aee8a)
也可以同步操作，也就是说添加/删除到本地书架时源站执行同样的操作(不过估计大家不会喜欢这种设定)。
还有一些零碎的操作，比如刷新书籍的时候也同步书籍在两个书架中的状态之类的。

对于源作者来说(因为我没看过开发文档，所以下面有些api可能已经有了)，可以获取书籍是否在书架中，可以主动在目录的更新前js(preUpdateJs)中设置同步规则，在书源的基本组里加个同步体(syncForm)用来写js进行post

**Comment by ybbluesky** [comment]
有这个需求
