### ISSUE TITLE
选择导出多本小说时在通知栏取消，会继续生成只有简介无正文的txt文件

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3962]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs
导出所有成txt格式，取消后缓存界面提示Job was cancelled，而选择导出epub格式，取消后会停止生成文件。取消导出通知栏流程会持续显示，直到全部文件都过一遍显示导出完成，才不再显示

### 复现步骤 / How to reproduce

选择导出所有，txt与epub任选，然后在通知栏选停止

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.053018

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60pro

**Comment by 821938089** [comment]
试试最新测试版

**Comment by dreamwar2005** [comment]
> 试试最新测试版

请问最新测试版在哪里下载？

**Comment by 821938089** [comment]
@dreamwar2005 
https://github.com/gedoor/legado/actions/workflows/test.yml?query=branch%3Amaster
第一个工作流里的Artifacts
