### ISSUE TITLE
可以支持阿里云盘OpenApi吗

### ISSUE THREAD

**Issue by vtrayy** [gedoor/legado#3966]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

坚果云的webdav不够用，而阿里云盘存了很多书籍，可以把阿里云盘和阅读结合起来形成一个个人图书馆

### 期望实现方式 / How to implement

开发者申请OponApi以内置的方式或者类似webdav留下ClientId和ClientSecret两个字段，用户可以自行申请OpenApi并填写（我已经申请成功了，感觉很容易）

**Comment by Vstory** [comment]
确实好想法

**Comment by Sun-QAQ** [comment]
曲线一下，用alist挂载？我只挂载了一些网盘到我本地，alist也可以挂载webview
