### ISSUE TITLE
仍有epub内图片不显示的bug

### ISSUE THREAD

**Issue by FoeniX233** [gedoor/legado#3968]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

更新0603的测试版后，epub内插图仍然不显示
[入间人间 - 说谎的男孩与坏掉的女孩 4 羁绊的支柱是欲望.epub.zip](https://github.com/user-attachments/files/15537095/-.4.epub.zip)其他软件（如静读天下）正常
![Screenshot_2024-06-04-00-49-21-044_io legado app release](https://github.com/gedoor/legado/assets/13049595/8bea33a3-ad0b-44cf-9ae1-7ccd274bea4c)
![Screenshot_2024-06-04-00-49-35-239_com flyersoft moonreaderp](https://github.com/gedoor/legado/assets/13049595/04ea97fb-1a3c-438f-af0b-cfb436f411a3)
![Screenshot_2024-06-04-00-49-37-618_com flyersoft moonreaderp](https://github.com/gedoor/legado/assets/13049595/32e7fab7-14dc-4915-91d6-dd0e40f1be1e)

### 复现步骤 / How to reproduce

打开epub即可

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.060309

### Android版本 / Android version

Android 14

### 机型 / Model

Xiaomi 14

**Comment by 821938089** [comment]
试试最新测试版

**Comment by FoeniX233** [comment]
> 试试最新测试版

测试3.24.060409已正常，感谢

**Comment by FoeniX233** [comment]
该本书封面无法显示，其他软件内正常
