### ISSUE TITLE
字典输入为空

### ISSUE THREAD

**Issue by xianfanjie** [gedoor/legado#3969]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

正文最右侧单个字符长按，替换、复制、书签、朗读、字典等都无效，字典会提示输入为空

### 复现步骤 / How to reproduce

正文最右侧单个字符长按，弹出菜单选择字典或者其他，朗读需要切换为朗读选择内容

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.060409

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi K40Pro+

**Comment by 821938089** [comment]
试试最新测试版

**Comment by xianfanjie** [comment]
没问题了。
