### ISSUE TITLE
epub封面图片获取不到

### ISSUE THREAD

**Issue by FoeniX233** [gedoor/legado#3970]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

该本书封面无法获取 已使用3.24.060409内测版
[竹宫悠由子 - 龙与虎 SO·２.zip](https://github.com/user-attachments/files/15543430/-.SO.zip)
![Screenshot_2024-06-04-14-20-32-461_com flyersoft moonreaderp](https://github.com/gedoor/legado/assets/13049595/655db661-56f0-4f3e-b02f-a86c794c76ad)
![Screenshot_2024-06-04-14-20-18-021_io legado app releaseA](https://github.com/gedoor/legado/assets/13049595/fb35f7a1-c70a-4996-8572-12dffe6d8e58)
![Screenshot_2024-06-04-14-19-42-021_com gmail jxlab app reasily](https://github.com/gedoor/legado/assets/13049595/fb25c74a-506c-4e43-9b31-5813df573ba7)

### 复现步骤 / How to reproduce

导入书籍

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.060409

### Android版本 / Android version

Android 14

### 机型 / Model

Xiaomi 14

**Comment by 821938089** [comment]
试试最新测试版

**Comment by FoeniX233** [comment]
> 试试最新测试版

重新导入书籍后恢复正常
