### ISSUE TITLE
本地书籍导入报错 java.lang.illegalStateException

### ISSUE THREAD

**Issue by lianghdx** [gedoor/legado#3972]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

导入本地书籍报错，书籍格式为UTF-8的txt。
![报错](https://github.com/gedoor/legado/assets/44738868/fa828437-38e1-4b14-90d1-006ccaaaa4b8)

### 复现步骤 / How to reproduce

在“我的”-“书源管理”-右上角三个点-“本地导入”，2个文件选择器均尝试过，都报错。
[东野圭吾-白ye行.txt](https://github.com/user-attachments/files/15552005/-.ye.txt)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

无

### 日志提交 / Relevant log output

![崩溃日志](https://github.com/gedoor/legado/assets/44738868/e96e4f97-4da7-4422-a556-5196a9166272)
![日志](https://github.com/gedoor/legado/assets/44738868/4a6e9917-fbb6-452c-97d8-2eabb0a7490d)

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

鸿蒙3.0.0.312

### 机型 / Model

华为 Mate 40

**Comment by 821938089** [comment]
这里是导入书源的地方，导入书籍去书架那里导入
或者在文件管理里用阅读打开也行

**Comment by lianghdx** [comment]
好的，问题已解决
