### ISSUE TITLE
TTS朗读内容划分功能，希望加入用逗号或者句号来划分朗读内容

### ISSUE THREAD

**Issue by litemini** [gedoor/legado#3973]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前的朗读划分功能是整段或者整页。使用edge接口朗读有字数限制，有部分文章的整段很长，有三四页那么多，这时候朗读就停止了；虽然使用整页阅读可以解决，但翻页时就会停顿一下，体验上有点不大丝滑。
![IMG_20240605_023448](https://github.com/gedoor/legado/assets/107750950/55256014-55c4-4dd1-a83c-d7da98de3d6d)
![IMG_20240605_023512](https://github.com/gedoor/legado/assets/107750950/008bc63d-ea58-45b3-878b-637ede2704d3)

### 期望实现方式 / How to implement

希望加入用逗号或者句号来划分朗读内容，如静读天下
![IMG_20240605_023421](https://github.com/gedoor/legado/assets/107750950/ea5be096-5229-43cf-9d7e-48a67e563d8e)

**Comment by youke2580c** [comment]
打开使用自定义中文分行和重新分段，不行再写个替换净化

**Comment by litemini** [comment]
“重新分段”，这个没找到，请问路径是
