### ISSUE TITLE
横屏双页时选中右侧部分文字无法在右侧的文字结束选中

### ISSUE THREAD

**Issue by ts8zs** [gedoor/legado#3978]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [ ] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

横屏双页时选中右侧部分文字无法在右侧的文字结束选中
另外无telegram 找不到蓝奏云测试版链接

### 复现步骤 / How to reproduce

https://github.com/gedoor/legado/assets/6174819/de96ea04-47a1-4a11-b6e9-b87176d56895

如视频

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22.110211

### Android版本 / Android version

14

### 机型 / Model

y700 2022

**Comment by 821938089** [comment]
最新测试版下载
https://github.com/gedoor/legado/actions/workflows/test.yml?query=branch%3Amaster
第一个工作流里的Artifacts
