### ISSUE TITLE
固定屏幕方向，不要自动旋转

### ISSUE THREAD

**Issue by zero-hugo** [gedoor/legado#3979]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

系统打开屏幕自动旋转的情况下，阅读软件也会自动旋转躺在床上用的时候，老是变成横屏。虽然小说正文里面可以设置屏幕方向，但是书架是无法设置的。希望能添加一个全局的屏幕方向设置。

### 期望实现方式 / How to implement

希望能添加一个全局的屏幕方向设置。

### 附加信息 / Additions

希望能添加一个全局的屏幕方向设置。

**Comment by zero-hugo** [comment]
这软件是以后都不更新了吗？

**Comment by 821938089** [comment]
作者已经不更新了，新功能应该是没有的了，或者看看有没有人愿意PR

方向锁定一直开着不行吗，我都是常开的
