### ISSUE TITLE
WEBDAV为什么要默认books目录且不可修改？

### ISSUE THREAD

**Issue by knudalr** [gedoor/legado#3980]
### 确认 / Assignments

- [X] #3983
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

把我的群晖电子书目录ebook作为webdav共享出来，APP添加后，发现APP要去读取我共享目录下的books目录，这意味着我所有的电子书都无法被访问，除非我把我所有电子书迁移到books目录下。

为什么呢？

为什么要强制这个目录？我共享出了目录，直接读这个目录不行么？

### 复现步骤 / How to reproduce

必现

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22.111423

### Android版本 / Android version

鸿蒙4.2

### 机型 / Model

Mate60Pro

**Comment by 821938089** [comment]
你可以在远程书籍里面的服务器配置里添加，这个是根目录
