### ISSUE TITLE
分页的章节，第二页下载失败，有办法识别重新下载么

### ISSUE THREAD

**Issue by zhangzw218** [gedoor/legado#3982]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

一个章节分成了2页，这个时候如果第二页下载失败了，我无法发现，只能看到章节的第一页内容。
有办法识别这个情况么？比如第二页下载失败，第一页的内容也不要了，等后续网络情况好了整个章节重新下载？
当前有办法这么做么？还是说需要另外搞这个功能？

### 期望实现方式 / How to implement

第二页下载失败，第一页的内容也不要了，等后续网络情况好了整个章节重新下载？

**Comment by 821938089** [comment]
因网络原因的下载失败会直接报错，不会保存任何内容的

**Comment by zhangzw218** [comment]
> 因网络原因的下载失败会直接报错，不会保存任何内容的

会的，我遇到情况，一个章节有2个页面，1/2下载成功了，2/2没了。
然后我没注意的时候，就会漏掉下半章。

**Comment by yafovo** [comment]
我也遇到过 加载1/2的问题，点原网页可以正常看，
少量出现，影响还是较大的
感觉更像是网站或者书源的问题？

**Comment by Antecer** [comment]
我没记错的话，下载机制是：
1. 正文页提供的 List , 如果其中一个链接失败了会重试几次。
2. 正文页提供的是第一页，并给定了下一页url规则，这种情况下一页下载失败就直接失败了。

**Comment by youke2580c** [comment]
可以用js写个循环判断处理，参考我这个源https://shuyuan.mgz6.com/shuyuan/3bc0d225df584600ea4ebb3fb31c6c0a.json
