### ISSUE TITLE
请问下如果获取当前小说读到第几页以及小说总页数

### ISSUE THREAD

**Issue by xiaoyu915** [gedoor/legado#3991]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

你好 我在源码里看到展示当前阅读进度的代码之后，有点疑问，我不太清楚这个进度是怎么算的 
/**
     * 阅读进度
     */
    val readProgress: String
        get() {
            val df = readProgressFormatter
            if (chapterSize == 0 || pageSize == 0 && chapterIndex == 0) {
                return "0.0%"
            } else if (pageSize == 0) {
                return df.format((chapterIndex + 1.0f) / chapterSize.toDouble())
            }
            var percent =
                df.format(chapterIndex * 1.0f / chapterSize + 1.0f / chapterSize * (index + 1) / pageSize.toDouble())
            if (percent == "100.0%" && (chapterIndex + 1 != chapterSize || index + 1 != pageSize)) {
                percent = "99.9%"
            }
            return percent
        }

### 期望实现方式 / How to implement

我想知道当前阅读到第几页是哪个值/公式 以及小说总页数是哪个值/公式。非常感谢

**Comment by 821938089** [comment]
这个进度不是用总页数算出来的
它是用已读章节百分比加单章百分比乘以本章已读页数百分比算出来的

**Comment by xiaoyu915** [comment]
> 这个进度不是用总页数算出来的 它是用已读章节百分比加单章百分比乘以本章已读页数百分比算出来的
好的 大佬。那已读页数和总页数是怎么算呢

**Comment by 821938089** [comment]
这个算不出来的，因为未加载内容的章节无法确定页数

**Comment by xiaoyu915** [comment]
好的。后期有打算更新这个功能吗 ，可以显示已读页数和总页数

**Comment by 821938089** [comment]
这app作者已经不更新了，所以大概率是没有了，而且这功能估计是实现不了的

**Comment by xiaoyu915** [comment]
就是目前没有api可以算总页数吗。我想是不是可以在小说初始化的时候拿到章节信息 然后累计一下章节的页数当做总页数呢。我说的本地小说

**Comment by 821938089** [comment]
是的

可以，但是可能要花很多时间

**Comment by Antecer** [comment]
计算总页数属实没有必要，这需要把本小说都渲染一遍，时间消耗伤不起的。
