### ISSUE TITLE
搜索结果为5时无法翻页

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#3992]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

http://sy.legado1.top/sy.php/c4669438123609e685214653b8cb9c78.json

这个书源的搜索规则可以自定义搜索结果数量，但是测试发现：pagesize=10时在搜索结果里可以正常翻页，pagesize=5时无法翻页；通过修改固定页码是可以搜出下一页结果的，所以可以排除网站问题。

### 复现步骤 / How to reproduce

以上

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.061919

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
搜索结果太少，列表没办法滚动到底的话，是无法触发加载下一页的，不要限制太少就可以了

**Comment by skybbk1998** [comment]
> 搜索结果太少，列表没办法滚动到底的话，是无法触发加载下一页的，不要限制太少就可以了

这个网站搜索结果里没有作者，所以我用了ajax访问详情页获取作者，如果结果设置太多很影响搜索速度。请问这个在代码上还有没有优化空间

**Comment by 821938089** [comment]
应该没有了
正常与其他源一起搜索时应该是可以加载下一页的
建议不要用ajax，这样搜索太慢了，增加了很多不必要的请求，对网站造成负担
你实在要的话可以在书籍列表规则里处理，用ajaxAll可以快很多

**Comment by skybbk1998** [comment]
> 应该没有了 正常与其他源一起搜索时应该是可以加载下一页的 建议不要用ajax，这样搜索太慢了，增加了很多不必要的请求，对网站造成负担 你实在要的话可以在书籍列表规则里处理，用ajaxAll可以快很多

好的，我试试，感谢大佬
