### ISSUE TITLE
网络导入问题

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#3996]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

印象中原来网络导入填这种能直接解析出直链的可以直接导入阅读，https://api.hanximeng.com/lanzou/?url=https://wwb.lanzov.com/iEJCX0zin8id&type=down 现在导入会报错

### 复现步骤 / How to reproduce

![S40621-13390426_io legado app release](https://github.com/gedoor/legado/assets/73186747/da864309-d796-4c64-a2cc-b5f3d021b685)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.062017

### Android版本 / Android version

Android13

### 机型 / Model

小米13

**Comment by 821938089** [comment]
蓝奏云加了验证，需要验证才能继续下载
