### ISSUE TITLE
书源管理: 导出书源 或备份书源

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [gedoor/legado#4001]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

我写了一个书源, 导入去测试， 就没有办法导出书源继续编辑。如果这个书源链接死亡，我没有时间去维护, 其他人可以导出这个书源 换一个链接 继续使用。

我试 备份与恢复，他没有备份书源

### 期望实现方式 / How to implement

书源管理 添加 导出书源 或备份书源 选项。
可以选择多个书源 或 全部 。导出或备份

**Comment by 821938089** [comment]
阅读可以导出书源，可以编辑书源，也可以备份书源。
不行的话麻烦录个视频看看什么情况。

**Comment by Zig-Rust-Odin** [comment]
我的>设置>备份与恢复  
> backup.zip 压缩包并没有备份书源

**Comment by 821938089** [comment]
你多备份几次，代码有写备份书源的，但是不知道为什么有些人的压缩包里有时候会没有书源。

我复现不了这个问题，不知道是哪出问题了。
