### ISSUE TITLE
更换书源时可按字数排序

### ISSUE THREAD

**Issue by jbb892543969** [gedoor/legado#4004]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

增加书源按字数排序功能

### 期望实现方式 / How to implement

根据书源列表字数字段，进行降序排序

### 附加信息 / Additions

在看书的时候，该源最新章节不存在，想切换到其他书源存在，但是其他书源是否存在最新章节，目前只能根据字数来判断，一本书存在几十个书源，大部分书源，本章字数在几百字内，说明大概率没有最新章节，字数多的书源很有可能有最新章节。那是否能把书源列表，按照字数多少进行升序或者降序，能更好的找到最新的书源，或者有其他方式可以实现类型需求，快速找到最新章节书源

**Comment by 821938089** [comment]
打开加载字数就可以了

**Comment by Gloryandel** [comment]
很难实现或者没必要。
1. 书源源站点质量参差不齐，仅部分站点提供字数统计
2. 如果站点不提供字数信息，统计字数得全部章节爬取一遍，相当于下载所有时间和风险（反爬虫拉黑，站点崩溃的法律责任，爬虫无错，把站点爬崩了付法律责任）
3. 最优解书源尽量填写最新章节规则。目录总数的获取很容易，唯有按章节总数排序有实际意义

**Comment by h11128** [comment]
@Gloryandel 没有那么复杂吧，加载字数的选项已经有了，增加一个按照字数排序的功能就完了

**Comment by Gloryandel** [comment]
> @Gloryandel 没有那么复杂吧，加载字数的选项已经有了，增加一个按照字数排序的功能就完了

期望的是 **根据书源列表字数字段**，疑惑在**”本章字数在几百字内，说明大概率没有最新章节“**，这似乎涉及章节内容是否完整而不是最新章节是否存在，很少见作者发布章节分部分发布的，不应该审核完整章直接发布吗？。

最新章节似乎目录计数更相关，所以是否转化需求为=》根据目录计数排序

而章节字数排序**如果可能**（不同源涉章节匹配问题）似乎新增至单章换源更合理

还是那句话，书源及站点质量参差不齐。

**Comment by h11128** [comment]
> > @Gloryandel 没有那么复杂吧，加载字数的选项已经有了，增加一个按照字数排序的功能就完了
> 
> 期望的是 **根据书源列表字数字段**，疑惑在**”本章字数在几百字内，说明大概率没有最新章节“**，这似乎涉及章节内容是否完整而不是最新章节是否存在，很少见作者发布章节分部分发布的，不应该审核完整章直接发布吗？。
> 
> 最新章节似乎与目录计数更相关，所以是否转化需求为=》根据目录计数排序
> 
> 而章节字数排序**如果可能**（不同源涉章节匹配问题）似乎新增至单章换源更合理
> 
> 还是那句话，书源及站点质量参差不齐。

作者都会发布完整章，但是小说网站不一定有完整章的内容，要看书源站点质量怎么样。很多书源是有最新的目录，但是很多章节内容都是只有前面一小段，所以要看字数

**Comment by h11128** [comment]
@jbb892543969 我看了一下代码，发现已经有这个逻辑了，如果打开加载字数的话：
字数大于 1000 的书源排在前面。
如果存在并列，并列的书源按章节编号以降序排列。
如果存在并列，并列的书源按字数降序排列。
如果存在并列，并列的书源按原来的顺序升序排列项目。

按照这个逻辑，字数大于1000的，章节数最多的，字数最多的，原来顺序就高的书源排前面。比你说的需求还更详细了
