### ISSUE TITLE
本地epub有章节或整本书不能打开的情况

### ISSUE THREAD

**Issue by QYZX** [gedoor/legado#4006]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

两个epub：
[epub.zip](https://github.com/user-attachments/files/16022878/epub.zip)

第6卷某个章节显示如下：
![1719537189059](https://github.com/gedoor/legado/assets/18007823/8ac1ea9b-5de6-4671-9138-c7cbb302eb7b)

然后第7卷无法获取章节，导致整本无法阅读
![1719537189062](https://github.com/gedoor/legado/assets/18007823/c581bd81-064f-42b6-b7b2-3353eb45bb95)

，以上两个情况在静读天下或PC用wps打开均正常

### 复现步骤 / How to reproduce

导入后打开阅读

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.061818

### Android版本 / Android version

HyperOS 1.0.38.0

### 机型 / Model

小米14

**Comment by 821938089** [comment]
试试最新测试版

**Comment by QYZX** [comment]
> 试试最新测试版

已经是最新版
