### ISSUE TITLE
词汇在没有使用替换规则的情况下被替换

### ISSUE THREAD

**Issue by KuarKuar** [gedoor/legado#4012]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

明明没有使用替换规则，相关选项也全都取消勾选了，为什么仍然有部分词汇会被替换（包括本地书籍），例如菲林会被替换为胶卷，整合会被替换成集成，还有其他的一些词汇。

### 复现步骤 / How to reproduce

本地书籍已经确认过原本词汇，导入app后仍被替换。替换规则里完全没有该规则

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22.110211

### Android版本 / Android version

Android 12

### 机型 / Model

Galaxy Note10+ 5G

**Comment by 821938089** [comment]
关闭繁简转换
