### ISSUE TITLE
请求增加一个阿拉伯数字转中文数字的方法，能在目录 > 格式化规则中调用

### ISSUE THREAD

**Issue by sky-bbk** [gedoor/legado#4014]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

请求增加一个阿拉伯数字转中文数字的方法

### 期望实现方式 / How to implement

能在目录 > 格式化规则中调用

**Comment by skybbk1998** [comment]
修改标题

**Comment by skybbk1998** [comment]
目前可以用js代码实现
```js
function SectionToChinese(n){for(var r="",h="",c=0,e=!0;n>0;){var i=n%10;0===i?e||(e=!0,h=chnNumChar[i]+h):(e=!1,r=chnNumChar[i],r+=chnUnitChar[c],h=r+h),c++,n=Math.floor(n/10)}return 0===h.indexOf("\u4e00\u5341")&&(h=h.slice(1)),h}function n2c(n){var r=0,h="",c="",e=!1;if(0===n)return chnNumChar[0];for(;n>0;){var i=n%1e4;e&&(c=chnNumChar[0]+c),h=SectionToChinese(i),0!==i&&(h+=chnUnitSection[r]),c=h+c,e=1e3>i&&i>0,n=Math.floor(n/1e4),r++}return c}var chnNumChar=["\u96f6","\u4e00","\u4e8c","\u4e09","\u56db","\u4e94","\u516d","\u4e03","\u516b","\u4e5d"],chnUnitSection=["","\u4e07","\u4ebf"],chnUnitChar=["","\u5341","\u767e","\u5343"];
```

**Comment by 550-q** [comment]
> 目前可以用js代码实现
> ```js
> function SectionToChinese(n){for(var r="",h="",c=0,e=!0;n>0;){var i=n%10;0===i?e||(e=!0,h=chnNumChar[i]+h):(e=!1,r=chnNumChar[i],r+=chnUnitChar[c],h=r+h),c++,n=Math.floor(n/10)}return 0===h.indexOf("\u4e00\u5341")&&(h=h.slice(1)),h}function n2c(n){var r=0,h="",c="",e=!1;if(0===n)return chnNumChar[0];for(;n>0;){var i=n%1e4;e&&(c=chnNumChar[0]+c),h=SectionToChinese(i),0!==i&&(h+=chnUnitSection[r]),c=h+c,e=1e3>i&&i>0,n=Math.floor(n/1e4),r++}return c}var chnNumChar=["\u96f6","\u4e00","\u4e8c","\u4e09","\u56db","\u4e94","\u516d","\u4e03","\u516b","\u4e5d"],chnUnitSection=["","\u4e07","\u4ebf"],chnUnitChar=["","\u5341","\u767e","\u5343"];
> ```

大佬，求问这个代码怎么使用
