### ISSUE TITLE
书籍被自动添加到书架

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#4015]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在正文界面进入编辑书源，此时搜同一本书会发现书籍被自动添加到书架

### 复现步骤 / How to reproduce

- 在用单个书源搜索书架没有的书时，进入正文，再从正文右上角编辑书源。
- 在编辑书源界面用右上角的搜索搜同一本书，会发现这本书已经被加入书架。
- 虽然一层层返回时“是否将此书加入书架”的提示依然会出现，此时如果点否会自动从书架删除。但是如果在出现提示之前强行停止阅读，或者其他途径返回了主页面。再次打开时书籍会重新出现在书架上

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.070217

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
阅读书籍必须要先临时加到书架里，如果不从阅读界面正常退出的话则无法自动删除

你说一下怎么强行停止阅读和从其他途径返回主界面，我看看能不能在这些地方增加删除代码

**Comment by skybbk1998** [comment]
强行停止就是从后台划掉阅读，等同于在APP信息界面使用强行停止按钮。
其他途径返回主界面，我没有复现成功，只是偶尔出现过三四次。不过刚刚发现，如果我搜书籍a，再从a的正文-编辑书源-搜索 书籍b，再从b的正文-编辑书源-搜索 书籍c，进入c的正文后，返回会提示是否把书籍a加入书架，此时如果选否，返回主页面会发现书籍b和c已经被自动加入书架

**Comment by skybbk1998** [comment]
其他途径返回主界面复现成功。步骤：
书源管理--任意书源--编辑--右上角搜索--任意书籍详情--正文--右上角编辑书源--直接保存，此时会直接返回书源管理界面，跳过了“是否将此书加入书架”的步骤，而刚才打开正文的书也会被自动添加到书架。

**Comment by 821938089** [comment]
试试最新测试版

**Comment by skybbk1998** [comment]
已经修复，感谢大佬

**Comment by 821938089** [comment]
@aay116 这个我觉得算bug，所以修复了，你可以在阅读记录找回书名
