### ISSUE TITLE
epub封面

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#4016]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

闲着没事把epub文件换个封面，但只要不改文件名，还是原来的文件名，阅读要么识别以前的封面，要么没封面，所以这是bug不，为啥不能刷新出新的封面？重新添加好几次都不行

### 复现步骤 / How to reproduce

epub书，改封面不改文件名，就会加载不出新封面

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.070421

### Android版本 / Android version

Android 14

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
epub首次打开时会缓存封面图片，此图片名字的生成与文件路径有关，所以改文件名会重新获取封面

**Comment by gyz1023** [comment]
![image](https://github.com/gedoor/legado/assets/106790230/9639cdf3-0633-4d50-86b6-3deb179a4445)
是不是起码要让这个刷新封面生效啊，点了没反应的

**Comment by 821938089** [comment]
不是，这个是手动填地址然后刷新的

**Comment by 821938089** [comment]
试试最新测试版
