### ISSUE TITLE
模拟追读功能

### ISSUE THREAD

**Issue by xuanyue202** [gedoor/legado#4019]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

模拟追读功能允许用户设定一个小说的起始阅读日期、起始章节以及每日更新的章节数量。软件将根据用户设定，自动模拟小说的更新过程，每天向用户展示新增的章节内容。这不仅能够满足用户追读小说的需求，还能提供一种新颖的阅读体验。

举例 / Example:

用户选择小说《星际穿越者》
设定起始日期为2024年7月10日
设定起始章节为第1章
设定每日更新章节数为3章
从2024年7月10日起，软件每天自动解锁《星际穿越者》的第1章、第2章和第3章，直到小说完结或用户设定的章节数。

### 期望实现方式 / How to implement

# 用户界面设计：
在小说阅读器中添加一个"模拟追读"的设置选项，用户可以通过此选项输入起始日期、起始章节和日更章节数。

**章节解锁机制：**

当用户打开软件时，检查当前日期与用户设定的起始日期之间的差异，确定今天应该解锁哪些章节。
如果有新章节解锁，软件会通知用户，并在书架或追读列表中显示。

**数据同步：**

确保用户的追读设置和章节解锁状态在不同设备间同步。

**Comment by xuanyue202** [comment]
如果可以的话，我可以开发这个功能提一个PR

**Comment by huajideshutiao** [comment]
好奇怪的功能说是。

**Comment by xu-li-logic** [comment]
对我来说很有用的功能。但如果用手机开Web服务，即使开启了“模拟追读”也可以获取到未解锁的章节（阅读APP版本：3.25）。
