### ISSUE TITLE
最新版本web端功能异常

### ISSUE THREAD

**Issue by old-yellow-ox** [gedoor/legado#4024]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

书源，订阅源编辑页面，获取源数据失败。
书单页面图片无法加载。
之前正常，昨天更新以后开始出现问题。

### 复现步骤 / How to reproduce

最新版本，web功能

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新版

### Android版本 / Android version

12

### 机型 / Model

mate30

**Comment by old-yellow-ox** [comment]
基本设定初的后台地址默认是空的，导致接口请求失败，手动设置之后正常了。
应该改为默认使用当前地址栏的地址

**Comment by 821938089** [comment]
试试最新测试版

**Comment by old-yellow-ox** [comment]
可以了
