### ISSUE TITLE
墨水屏主题模式下，排版出现问题

### ISSUE THREAD

**Issue by crystalxpcn** [gedoor/legado#4027]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

我是在电子阅读器（6寸）里安装的阅读。选择墨水屏主题模式下，排版会出现问题，对每一页的最后处理不到，出现字体只显示一半等问题。其他主题模式下无此排版问题，但会出现换页时闪屏严重的问题。

### 复现步骤 / How to reproduce

1、在电子阅读器（6寸）里安装的阅读。（[legado_app_3.23.110211]）
2、切换到墨水屏主题模式
3、阅读小说并进行翻页操作。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

无

### 日志提交 / Relevant log output

无

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 11

### 机型 / Model

国文A8S

**Comment by 821938089** [comment]
你去界面设置里面调整一下边距

**Comment by crystalxpcn** [comment]
调整过边距的，并没用。目测好像是计算行数有问题。
