### ISSUE TITLE
没有加入书架的小说在阅读界面切换夜间模式时出现没有书籍的情况

### ISSUE THREAD

**Issue by zhangpengjunzi** [gedoor/legado#4031]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

没有加入书架的小说在阅读界面切换夜间模式时出现没有书籍的情况，貌似数据丢失了

### 复现步骤 / How to reproduce

1.小说没有加入书架
2.阅读界面切换夜间模式
3.阅读页出现没有书籍的提示

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新代码编译

### Android版本 / Android version

Android 14

### 机型 / Model

一加 ave 2

**Comment by 821938089** [comment]
好了，你重新拉取一下代码编译吧

**Comment by zhangpengjunzi** [comment]
好的，问题解决了，这个bug没有了

**Comment by 821938089** [comment]
@aay116 已修复

**Comment by zhangpengjunzi** [comment]
除了上面的问题之外，不在书架的小说在阅读页切换夜间模式点退出选否，返回书架会出现删除该书籍的动画

**Comment by 821938089** [comment]
已修复
