### ISSUE TITLE
发现页榜单内容重复获取？

### ISSUE THREAD

**Issue by ghost** [gedoor/legado#4037]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

任意书源-发现-点击xx榜单-下拉 当发生拉取下一页内容页转圈时内容重复

### 复现步骤 / How to reproduce

以上

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.072300

### Android版本 / Android version

14

### 机型 / Model

14

**Comment by 821938089** [comment]
已修复
