### ISSUE TITLE
[Theme]: 添加A屏黑，高对比度

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [gedoor/legado#4040]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望界面主题能给个A屏黑，以及添加高对比度主题，这样即使开的很暗也能看的清楚，有助于省电和夜间阅读

### 期望实现方式 / How to implement

- A屏黑: 即背景在OLED下不发光
- 高对比度: 为了长时间伏案和观看出现的主题家族，清晰好认，即使屏幕素质很差也不影响使用

**Comment by 821938089** [comment]
有A屏黑主题

**Comment by Mr-Ao-Dragon** [comment]
> 有A屏黑主题

不够啊，除了阅读界面其他都不是

**Comment by 821938089** [comment]
在主题设置-主题列表里面

**Comment by Mr-Ao-Dragon** [comment]
> > 在主题设置-主题列表里面
> 
> 背景色不能太暗，什么情况

全黑才是A屏黑啊

**Comment by Mr-Ao-Dragon** [comment]
这个限制能关吗？

**Comment by 821938089** [comment]
在夜间主题里设置

**Comment by Mr-Ao-Dragon** [comment]
好吧...
