### ISSUE TITLE
部分书源目录无法查看更新，删除书籍后重新添加或换源后可解决

### ISSUE THREAD

**Issue by lvlavy** [gedoor/legado#4042]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

![Screenshot_20240725_002853](https://github.com/user-attachments/assets/6f05a774-cfb1-4974-b96b-89a4dcef029d)
![Screenshot_20240725_002846](https://github.com/user-attachments/assets/4d91ffd4-ff57-4d82-9dca-a9cf388a3943)
看书时目录显示不更新，看到结尾显示没有下一页
切换书源有下一章，更新目录不管用
删除书籍后重新添加可有下一章
以前版本也有同样毛病

### 复现步骤 / How to reproduce

书源为梓澄qwq 大佬的番茄书源（自用）
书籍为系统崩溃？补偿宇宙唯一天赋！

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.072422

### Android版本 / Android version

Android 14

### 机型 / Model

vivo iqoo neo 9s pro

**Comment by 821938089** [comment]
编辑书源，在目录的更新之前JS填上`java.refreshTocUrl()`应该就可以了
