### ISSUE TITLE
听书时，预加载语音不会跨章节，因使用自建chattts文字转语音效率不能秒转，导致每次换新的一章都会卡个几秒

### ISSUE THREAD

**Issue by seepine** [gedoor/legado#4050]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

听书时，预加载语音不会跨章节，因使用自建chattts文字转语音效率不能秒转，导致每次换新的一章都会卡个几秒

### 期望实现方式 / How to implement

预加载语音能够跨章节

**Comment by 821938089** [comment]
最新测试版已增加预加载下一章开头部分内容，你可以试试

**Comment by DanielZhao1990** [comment]
方便分享一下如何自建chattts文字转语音吗
