### ISSUE TITLE
书籍列表下一页加载错误

### ISSUE THREAD

**Issue by xiaohan231** [gedoor/legado#4052]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

书籍列表加载下一页后，前一页的数据没有清空，多次重复加载

### 复现步骤 / How to reproduce

书籍列表下拉加载下一页

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

72306

### Android版本 / Android version

12

### 机型 / Model

小米

**Comment by 821938089** [comment]
哪里的书籍列表？

**Comment by xiaohan231** [comment]
最新测试版没问题
