### ISSUE TITLE
img标签支持本地路径

### ISSUE THREAD

**Issue by code0o0** [gedoor/legado#4055]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

修改小说文本，插入img标签时能不能增加本地路径支持，先判断下src是不是以/storage/emulated/0开头，如果是可以直接复制到缓存路径。

### 期望实现方式 / How to implement

saveImage函数增加一个路径判断，增加一个复制函数

**Comment by 821938089** [comment]
高版本安卓是不能直接访问内部存储目录的，建议做成epub来看

**Comment by code0o0** [comment]
> 高版本安卓是不能直接访问内部存储目录的，建议做成epub来看

好的，本来想着要是能插入本地图片，可以方便导出和编辑epub
