### ISSUE TITLE
扫描的pdf显示

### ISSUE THREAD

**Issue by fuyuyang** [gedoor/legado#4057]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

扫描的pdf显示目前一页显示2个图片，第二张图片显示不完整，翻页也无法看到缺少的部分

### 期望实现方式 / How to implement

一张图一页比较好

**Comment by 821938089** [comment]
只能用滚动动画看
