### ISSUE TITLE
发现分类的书籍列表存在重复获取

### ISSUE THREAD

**Issue by youke2580c** [gedoor/legado#4058]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

发现分类没有翻页的书籍列表会重复获取
![Screenshot_2024_0731_160740](https://github.com/user-attachments/assets/aef9b326-d689-4720-b6b2-787d6c05edeb)

### 复现步骤 / How to reproduce

发现分类上滑列表[零点看书.json](https://shuyuan.mgz6.com/shuyuan/95ecd84ea8f69f023a1dfe4f419d1fe3.json)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.073013

### Android版本 / Android version

11

### 机型 / Model

vivo

**Comment by 821938089** [comment]
已修复，你更新最新测试版试试

**Comment by youke2580c** [comment]
> 已修复，你更新最新测试版试试

最新测试版正常了
