### ISSUE TITLE
WEB传书有bug

### ISSUE THREAD

**Issue by ymbzd** [gedoor/legado#4059]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

使用web传书功能传一个漫画，epub格式的，大概80MB，提示是传输成功了，但是书架上和手机上均未找到

### 复现步骤 / How to reproduce

使用web传书功能传一个漫画，epub格式的，大概80MB，提示是传输成功了，但是书架上和手机上均未找到

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新版本

### Android版本 / Android version

android 14

### 机型 / Model

小米14

**Comment by 821938089** [comment]
把文件发一下

**Comment by ymbzd** [comment]
链接：https://pan.baidu.com/s/1APghyd7R_iUvfMbBxtp_fA 
提取码：qf30

**Comment by ymbzd** [comment]
> 把文件发一下

上面发了 辛苦您看一下

**Comment by 821938089** [comment]
你设置了书籍保存位置了吗？

**Comment by 821938089** [comment]
修复了，你试试最新测试版

**Comment by ymbzd** [comment]
可以给个地址嘛…忘了在哪里看到了，翻了半天也没找到  麻烦您了

**Comment by 821938089** [comment]
https://github.com/gedoor/legado/releases
