### ISSUE TITLE
华为鸿蒙3.0（安卓10阉割版）测试版闪退无法打开

### ISSUE THREAD

**Issue by cxl2020MC** [gedoor/legado#4061]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

使用最新测试版legado_app_3.24.073121时无法打开
闪退
稳定版正常运行
由于没有能抓取日志的其他设备，故无法提供日志

### 复现步骤 / How to reproduce

https://github.com/user-attachments/assets/3b7f7da3-dae0-45b2-894c-2f26458fb9a3

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.073121

### Android版本 / Android version

鸿蒙3.0 安卓10

### 机型 / Model

honor 20 lite

**Comment by 821938089** [comment]
你可以用安卓的logcat记录日志，安装一个logcat reader，开始记录，再打开阅读，保存日志发过来

**Comment by gurenn** [comment]
貌似mate40pro的鸿蒙4.0也是这个问题，最后一个正常的版本是[legado_app_3.23.110211]，今年前面不管是从哪儿下的测试版都是闪退进不了，最新的包括3.25也一样闪退。

**Comment by harrypo03** [comment]
> 貌似mate40pro的鸿蒙4.0也是这个问题，最后一个正常的版本是[legado_app_3.23.110211]，今年前面不管是从哪儿下的测试版都是闪退进不了，最新的包括3.25也一样闪退。

我这儿用的是华为荣耀平板，鸿蒙2.0版本，3.25也是无法启动闪退，3.23正常，不知道您那儿解决了吗？

**Comment by harrypo03** [comment]
> > > 貌似mate40pro的鸿蒙4.0也是这个问题，最后一个正常的版本是[legado_app_3.23.110211]，今年前面不管是从哪儿下的测试版都是闪退进不了，最新的包括3.25也一样闪退。
> > 
> > 
> > 我这儿用的是华为荣耀平板，鸿蒙2.0版本，3.25也是无法启动闪退，3.23正常，不知道您那儿解决了吗？
> 
> 解决了，我用了3.24.090309之后的版本就可以了。

感谢您的分享，我也试试，请问这个新版本增加了什么功能了吗？

**Comment by cxl2020MC** [comment]
日志没有电脑进行adb，好像抓不到，但是目前最新测试版能正常使用（正式版3.25也是闪退）
