### ISSUE TITLE
朗读定时增加tasker支持或intents

### ISSUE THREAD

**Issue by OdinZhang** [gedoor/legado#4068]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前睡觉前喜欢使用阅读听书，但是设置时间使用滑动方式不方便选择，考虑到睡觉还喜欢使用sleep as Android记录睡眠，故希望可以集成tasker或使用某种方式设置定时任务方便选择时间和操作

### 期望实现方式 / How to implement

增加tts定时的外部调用方式，自动朗读上一本打开的书，设定自动停止时间等

**Comment by 821938089** [comment]
点击右边的分钟可以快速设置定时，点击左边的闹钟可以记忆定时设置
你可以先设置好记忆定时，然后调用朗读

**Comment by OdinZhang** [comment]
> 点击右边的分钟可以快速设置定时，点击左边的闹钟可以记忆定时设置 你可以先设置好记忆定时，然后调用朗读

非常感谢，是我不会用了
