### ISSUE TITLE
报毒

### ISSUE THREAD

**Issue by chjchen** [gedoor/legado#4070]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

手机报毒。
手机品牌
![Screenshot_2024-08-07-16-43-50-68_035d55d4552197c94b0185899d8a326c](https://github.com/user-attachments/assets/ac8c4573-7f5a-4ddb-93de-bc73f93bf29d)
：一加

### 复现步骤 / How to reproduce

。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新测试版

### Android版本 / Android version

。

### 机型 / Model

一加

**Comment by youke2580c** [comment]
正常，app没备案大多都会报。阅读是开源的，放心使用。

**Comment by chjchen** [comment]
新的测试版已经不提示了。
