### ISSUE TITLE
章节定位错误

### ISSUE THREAD

**Issue by wilsendd** [gedoor/legado#4071]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

当下拉刷新刷新成功时，且小说更新后有新章节出现时。点击进入小说后，章节定位会错乱。
例如：看到上次500章，共1000章。刷新后首页显示500/1005。但点进入之后会跳转到350章。打开目录也是定位到350章。并不是我上次看到的第500章。

视频如下：（打开时跳转错误情况，这次未复现出来，可能是因为我看到最后了吧。小说看一半的时候再刷新可能出现打开就跳转错误）

https://github.com/user-attachments/assets/312117c7-26d0-428e-9065-193ed8de6d78

### 复现步骤 / How to reproduce

刷新->有新章节出现-进入后阅读进度错位。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 12

### 机型 / Model

Huawei Mate 40

**Comment by 821938089** [comment]
发书源看看

**Comment by wilsendd** [comment]
> 发书源看看

{
  "bookSourceComment": "",
  "bookSourceGroup": "Namo",
  "bookSourceName": "精华书阁WAP",
  "bookSourceType": 0,
  "bookSourceUrl": "https://wap.jhssd.com/",
  "customOrder": 0,
  "enabled": true,
  "enabledCookieJar": false,
  "enabledExplore": true,
  "exploreUrl": "玄幻::/list/1_{{page}}.html\n修真::/list/2_{{page}}.html\n都市::/list/3_{{page}}.html\n穿越::/list/4_{{page}}.html\n网游::/list/5_{{page}}.html\n科幻::/list/6_{{page}}.html\n灵异::/list/7_{{page}}.html\n女生::/list/8_{{page}}.html\n其他::/list/9_{{page}}.html\n完本::/wanben_{{page}}.html\n日点击榜::/Ranking_dayvisit/{{page}}.html\n周点击榜::/Ranking_weekvisit/{{page}}.html\n月点击榜::/Ranking_monthvisit/{{page}}.html\n总点击榜::/Ranking_allvisit/{{page}}.html\n周推荐榜::/Ranking_weekvote/{{page}}.html\n月推荐榜::/Ranking_monthvote/{{page}}.html\n总推荐榜::/Ranking_allvote/{{page}}.html\n收藏推荐::/Ranking_goodnum/{{page}}.html\n字数排行::/Ranking_size/{{page}}.html\n最新入库::/Ranking_postdate/{{page}}.html\n最新更新::/Ranking_lastupdate/{{page}}.html\n新书榜单::/Ranking_goodnew/{{page}}.html",
  "header": "",
  "lastUpdateTime": 1689836134016,
  "respondTime": 180000,
  "ruleBookInfo": {
    "author": "p.2@text",
    "coverUrl": "class.block_img2@tag.img@src",
    "intro": "class.intro_info@textNodes",
    "kind": "[property=\"og:novel:category\"]@content&&\n[property=\"og:novel:status\"]@content",
    "lastChapter": "@li.0@text",
    "name": "class.block_txt2@a.1@text"
  },
  "ruleContent": {
    "content": "id.nr@html",
    "imageStyle": "TEXT",
    "nextContentUrl": "id.pb_next@href",
    "replaceRegex": "##.*更新不易请收藏！|\\『章节.*\\』|\\(本章未完.*|精华书阁.*最新章节！|为您提供.*书签！|看.*最快更新.*查看|【目前用下来，听书声音最全最好用的App，集成4大语音合成引擎，超100种音色，更是支持离线朗读的精华书阁神器，精华书阁精华书阁App.|本章未完，请点击下一页继续阅读》》阅读提示：为防止内容获取不全，请勿使用浏览器阅读模式。",
    "webJs": ""
  },
  "ruleExplore": {
    "author": "tag.span.1@text",
    "bookList": "class.xbk",
    "bookUrl": "class.tjimg@a@href",
    "coverUrl": "class.tjimg@img@src",
    "intro": "tag.span.2@text",
    "kind": "class.tjrs@text",
    "name": "class.xsm@text"
  },
  "ruleReview": {},
  "ruleSearch": {
    "author": "class.author@text",
    "bookList": "class.searchbook",
    "bookUrl": "class.bookimg@tag.a@href",
    "checkKeyWord": "不科学",
    "coverUrl": "class.bookimg@tag.img@src",
    "kind": ".cat@text##分类：",
    "lastChapter": ".update@a@text",
    "name": "h4@text",
    "wordCount": "class.p4@text"
  },
  "ruleToc": {
    "chapterList": "class.chapter.1@li@a",
    "chapterName": "text",
    "chapterUrl": "href",
    "nextTocUrl": "option!0@value"
  },
  "searchUrl": "https://wap.jhssd.com/search.html?ie=utf-8&word={{key}}",
  "weight": 0
}

**Comment by 821938089** [comment]
这个书源好像失效了

**Comment by wilsendd** [comment]
> 这个书源好像失效了

可能是格式问题吧，我这里还好用，还能搜索。
从下面这个txt文件里复制试试呢

[书源.txt](https://github.com/user-attachments/files/16536110/default.txt)

**Comment by 821938089** [comment]
还是失效的

我看了这个书源是用手机版页面做的，手机版页面章节目录有分页，可能是分页太多，部分分页目录没加载出来导致的，建议找个用桌面端页面做的书源用

**Comment by wilsendd** [comment]
> 还是失效的
> 
> 我看了这个书源是用手机版页面做的，手机版页面章节目录有分页，可能是分页太多，部分分页目录没加载出来导致的，建议找个用桌面端页面做的书源用

好的，我再试试其他书源，谢谢！
