### ISSUE TITLE
从右下角翻页，翻页效果就卡住了

### ISSUE THREAD

**Issue by lyqaiym** [gedoor/legado#4075]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

翻页效果就卡住了
<img width="161" alt="504a6ef663ad08dccd27c1411bdb7eda" src="https://github.com/user-attachments/assets/bca9bf25-422c-4018-b882-122d4e055629">

### 复现步骤 / How to reproduce

从右下角翻页，翻到垂直的时候，翻页效果就卡住了
我已经找到代码问题了。
ReadView 的 onTouchEvent 方法。
判断 event.y > height.minus(insets.bottom)
像是判断键盘的，我从右下角翻。松手的时候，ACTION_UP 刚好 return 了
PageDelegate 的 onAnimStart 就不执行了。
`if (event.y > height.minus(insets.bottom) && (event.action != MotionEvent.ACTION_UP && event.action != MotionEvent.ACTION_CANCEL)) {
                    return true
                }`
判断抬起，这样就不复现了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

2024-08-09 11:35:25.851 PageDelegate D  onDown
2024-08-09 11:35:27.021 PageDelegate D  onTouch:action=1
2024-08-09 11:35:27.021 PageDelegate D  startScroll:startX=833,606
2024-08-09 11:35:27.027 PageDelegate D  computeScroll_1
2024-08-09 11:35:27.160 PageDelegate D  computeScroll_2
2024-08-09 11:35:27.160 PageDelegate D  stopScroll
2024-08-09 11:35:27.169 PageDelegate D  computeScroll_3

### 阅读版本 / Legado version

3.24.080911debug

### Android版本 / Android version

14

### 机型 / Model

xiaomi 14 Pro

**Comment by 821938089** [comment]
这个是判断是否在导航栏区域的

已修复，试试最新测试版

**Comment by lyqaiym** [comment]
可以了
