### ISSUE TITLE
测试版 Web 服务需要手机亮屏才能使用

### ISSUE THREAD

**Issue by MapleLuoYu** [gedoor/legado#4087]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

3.23.110211 正式版Web 服务使用正常，测试版本（3.24.081100）必须亮屏且APP停留在书架页面才能使用（切换到订阅，设置等页签都不行），电源及后台设置都是一样的

### 复现步骤 / How to reproduce

打开Web服务后，浏览器访问。或打开Web服务后切换到书架页签，手机息屏再浏览器访问

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.081100

### Android版本 / Android version

HarmonyOS 4.2.0

### 机型 / Model

Huawei Mate 40 Pro

**Comment by 821938089** [comment]
需要给后台权限

**Comment by MapleLuoYu** [comment]
> 需要给后台权限

后台锁和电源，启动权限都给了

**Comment by 821938089** [comment]
看一下这个页面，确定全都设置上了吗

https://consumer.huawei.com/cn/support/content/zh-cn00428704/

**Comment by MapleLuoYu** [comment]
> 看一下这个页面，确定全都设置上了吗
> 
> https://consumer.huawei.com/cn/support/content/zh-cn00428704/

谢谢，好了。

上述所有设置我之前都有，唯一有差异的地方就是后台下拉加锁后没有点击清理（只加锁，没清理直接退出了后台卡片界面）。

解决方案：取消加锁，然后重新加锁并清理其他后台，
