### ISSUE TITLE
恢复备份后书籍排序失效

### ISSUE THREAD

**Issue by yaday1** [gedoor/legado#4089]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

测试版3.24.081100。全新状态下设置书籍排序按照手动排序有效，恢复备份后书籍排序失效，全部变成按阅读时间排序，更改排序方法无效。试了之前共存版有一样的问题。

### 复现步骤 / How to reproduce

1.设置手动排序
2.备份
3.恢复
4.失效

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.081100

### Android版本 / Android version

14

### 机型 / Model

realme大师探索版

**Comment by 821938089** [comment]
分组里面的排序有没有重新设置

**Comment by yaday1** [comment]
有，无论设置哪个都无效，还是按阅读时间排序

**Comment by 821938089** [comment]
发一下你的备份

**Comment by yaday1** [comment]
[backup.zip](https://github.com/user-attachments/files/16623794/backup.zip)
![Screenshot_2024-08-15-17-24-46-00_90024215e504237c76412be1999ad914](https://github.com/user-attachments/assets/e4fff21a-cce1-435f-966c-f1dc3c5d2466)
无论全部还是小分类我都设置了

**Comment by 821938089** [comment]
我恢复你的备份后发现书架布局和分组里面都是设置的按阅读时间啊，我改回去就没问题了

**Comment by yaday1** [comment]
那你能把你设置完的再发给我吗，我再导入试试。上面截图就是我怕有这种情况说明一下。

**Comment by yaday1** [comment]
用了你设置过的就可以了，谢谢，不知道是什么问题。
