### ISSUE TITLE
在iqoo vivo安卓14上无法显示锁屏通知

### ISSUE THREAD

**Issue by tick-guo** [gedoor/legado#4090]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在安卓14上无法显示锁屏通知

### 复现步骤 / How to reproduce

![mmexport1723743019448](https://github.com/user-attachments/assets/c2978b85-e916-42dd-8fe5-2096795b56c4)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.081100

### Android版本 / Android version

Android 14

### 机型 / Model

iQOO Neo9S Pro+

**Comment by tick-guo** [comment]
#3747 无法重新open

**Comment by 821938089** [comment]
可能是系统问题，你可以试试备份好数据后卸载应用重新安装一遍

**Comment by tick-guo** [comment]
> 可能是系统问题，你可以试试备份好数据后卸载应用重新安装一遍

手机都换了，共存版也装了

**Comment by 821938089** [comment]
你卸载重装过了吗？

**Comment by tick-guo** [comment]
> 你卸载重装过了吗？

用的普通版，有问题，昨天又装了共存版，算重装吧

**Comment by 821938089** [comment]
算，共存版也显示不了吗？

**Comment by tick-guo** [comment]
> 算，共存版也显示不了吗？

是的呢

**Comment by tick-guo** [comment]
> 算，共存版也显示不了吗？

要是你有vivo手机测试就好了

**Comment by tick-guo** [comment]
> 算，共存版也显示不了吗？

可以怎么抓日志吗，我可以搞一搞

**Comment by 821938089** [comment]
你装个Logcat Reader，然后开始记录，点朗读，去锁屏看一下，然后保存日志上传

**Comment by tick-guo** [comment]
> 你装个Logcat Reader，然后开始记录，点朗读，去锁屏看一下，然后保存日志上传

[log_2024_08_16_12_52_46.zip](https://github.com/user-attachments/files/16633059/log_2024_08_16_12_52_46.zip)

说要电脑用命令授予logreader更多权限，上面的log是没有授予的情况下抓取的，你看够不，不够，等下我用电脑弄下

**Comment by 821938089** [comment]
不够，里面只有这个应用自己的日志

**Comment by 821938089** [comment]
阅读通知设置里（第四张图）下面应该有几个通知类别，你看看朗读这个类别有没有开锁屏通知

**Comment by tick-guo** [comment]
> 不够，里面只有这个应用自己的日志

[1.zip](https://github.com/user-attachments/files/16633423/1.zip)
直接用logcat命令抓的，看看

**Comment by tick-guo** [comment]
> 阅读通知设置里（第四张图）下面应该有几个通知类别，你看看朗读这个类别有没有开锁屏通知

下面没有锁屏设置了，其他开了

**Comment by 821938089** [comment]
你截图我看看，那个类别应该是可以点的

**Comment by tick-guo** [comment]
> 你截图我看看，那个类别应该是可以点的

![mmexport1723787940058](https://github.com/user-attachments/assets/afdce454-300f-49a3-bd71-068aeda405d9)

**Comment by 821938089** [comment]
日志里没有找到有用的信息

最新测试版我给通知设置了类别，你下载最新的共存版卸载重新安装一遍试试

**Comment by tick-guo** [comment]
> 日志里没有找到有用的信息
> 
> 最新测试版我给通知设置了类别，你下载最新的共存版卸载重新安装一遍试试

还是不行哦，请问项目是怎么打包成apk的，我稍微研究一下

**Comment by 821938089** [comment]
你安装一个Android Studio
然后git clone这个项目，在里面打开
手机打开adb连接好电脑，点运行就可以了

**Comment by tick-guo** [comment]
> 你安装一个Android Studio 然后git clone这个项目，在里面打开 手机打开adb连接好电脑，点运行就可以了 ![image](https://private-user-images.githubusercontent.com/8674809/358571433-6c09ec58-ad86-47b7-9f7c-2e3075f25cec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDkwMDUsIm5iZiI6MTcyMzgwODcwNSwicGF0aCI6Ii84Njc0ODA5LzM1ODU3MTQzMy02YzA5ZWM1OC1hZDg2LTQ3YjctOWY3Yy0yZTMwNzVmMjVjZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTE0NTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwNmY5MjE0ZmNhMTJiMTNlM2JmM2U2ODVhYTg5NzAzZDgzZGI2NGEyYzU0MjI2ZWViNGViNWFmMjY4MTBkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vrLn-3-8hAfxIC_Zq3t05O-cG21nIsLEAsDp1w0SaTk)
> 
> 发送朗读通知的代码在BaseReadAloudService.kt的upReadAloudNotification函数中 创建通知通道的代码在App.kt的createNotificationChannels函数中

加个微信吗？到时候请教一下  tick_guo
