### ISSUE TITLE
听书时，每次都会弹出提示后台权限

### ISSUE THREAD

**Issue by Leroy-X** [gedoor/legado#4092]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

听书时，每次都会弹出后台权限提示。

系统为三星one ui 5.1，系统软件设置中设置电池为优化（三星中优化是指允许后台运行，不允许后台联网），该模式可以正常后台听书运行。但3.25每次都会弹出后台权限，旧版不会。

希望只在安装软件后第一次使用时弹出提示，后面就不弹了。

现在是每次点击听书，都会弹窗提示

![469e98b06e80c770f57b93dae46e1f4](https://github.com/user-attachments/assets/df50aefd-06b8-449e-849b-78b280d31009)

### 复现步骤 / How to reproduce

打开书籍，点击朗读

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android 13

### 机型 / Model

Samsung s20

**Comment by 821938089** [comment]
你点去设置，然后弹出来的电池优化里点允许
