### ISSUE TITLE
绘制优化功能会让已经加载好的图片消失一部分

### ISSUE THREAD

**Issue by miss0701** [gedoor/legado#4094]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

绘制优化功能会让已经加载好的图片消失一部分 长按图片显示还是完整的

### 复现步骤 / How to reproduce

打开绘制优化
![Screenshot_2024-08-16-19-26-00-051_io legado app release](https://github.com/user-attachments/assets/b40a555a-02cd-488f-b9ed-847cbd76344b)
![Screenshot_2024-08-16-19-25-56-327_io legado app release](https://github.com/user-attachments/assets/e84a80f7-7b61-4aa3-8bd7-a2fa585147a6)

![Screenshot_2024-08-16-19-28-28-078_io legado app release](https://github.com/user-attachments/assets/0260a2b6-4c21-4378-a53f-584390cd9629)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

13

### 机型 / Model

xiaomi11

**Comment by 821938089** [comment]
把书源、书名发一下

**Comment by miss0701** [comment]
神速 最新测试版已修复
