### ISSUE TITLE
epub里的超链接功能缺失

### ISSUE THREAD

**Issue by dun21can** [gedoor/legado#4095]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

epub里的超链接都没有了，望在后续的版本更新一下，谢谢。

### 复现步骤 / How to reproduce

epub里的超链接都没有了，望在后续的版本更新一下，谢谢。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Harmony 4

### 机型 / Model

Huawei P30

**Comment by Wu-HZ** [comment]
是的，我打开一本epub看目录页，却不能跳转了，没找到打开此功能的设置
