### ISSUE TITLE
备份恢复相关：可能的BUG、功能优化建议等

### ISSUE THREAD

**Issue by jkqxl** [gedoor/legado#4097]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

备份数据过程中出现，提示备份成功，但实际上备份不完全，当书籍存储量特别大的时候。打开备份文件发现 bookshelf.jison 文件备份失败，里面没有任何书籍内容

因为之前 关闭 仅保留最新备份 功能，长时间会导致产生几十个，甚至更多的备份文件，这样到管理这些文件的时候，删除也是个麻烦的事情，结果本次 开启  仅保留最新备份 功能，导致仅1个备份文件，且文件被新的备份覆盖，因此造成了较大的损失。好在阅读历史备份成功，以后还能一个个回复，不至于全部完了。

优化建议
1. 根本上解决问题
2. 建议将  仅保留最新备份 ，修改为   仅保留3～5最新备份 ，增加容错率

### 复现步骤 / How to reproduce

1. 使用测试版 v3.24.081710 备份数据，提升备份成功
2. 安装 v3.25版后，恢复数据
3. 打开书籍列表发现没有任何书籍

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

无

### 阅读版本 / Legado version

v3.24.081710

### Android版本 / Android version

鸿蒙OS 2.0

### 机型 / Model

xxx

**Comment by 821938089** [comment]
这个问题我复现不了，最新的测试版我在备份那里加了些日志，你安装一下备份一次，然后把日志发过来

**Comment by jkqxl** [comment]
> 这个问题我复现不了，最新的测试版我在备份那里加了些日志，你安装一下备份一次，然后把日志发过来

再次测试，v3.24.081710_releaseA 版本 备份文件出现 book开头的文件就一个，当然同样 bookshelf.jison 文件也没有，再次备份操作，第二次才成功；使用 3.24.08171746_releaseA版本，似乎也无法复现。

软件的保存日志功能无法正常工作，保存到 配置文件夹的文件 是空的。

还有，现在的版本，发现，即使 关闭 仅保留最新备份 功能，备份的文件也似乎仅仅1个，而不会更多，还是希望可以有3~5个备份的，这样无论是 网络波动，还真的是软件问题，都不至于无法弥补。

**Comment by 821938089** [comment]
需要打开其他设置里的记录日志

备份文件名同一天都是一样的，所以每天的备份只有一个

**Comment by jkqxl** [comment]
> 需要打开其他设置里的记录日志
> 
> 备份文件名同一天都是一样的，所以每天的备份只有一个

恩，再试了几次，v3.24.081710_releaseA 版本 也无法复现，需要说明的是，有一次使用备份恢复的时候，未能成功恢复配置，而是仅恢复了列表的书籍，感觉可能与备份失败的原因是一样的。

以上几次备份失败，都是在安装好软件后的第一次备份时，之后就无法复现了。

测试了十几次， 3.24.08171746_releaseA版本终于出现了问题，但即使是在 其他设置-记录日志 启用，在 关于-保存日志 ，依然是啥也没有。
错误的备份情况如图

![Snipaste_2024-08-17_19-34-18](https://github.com/user-attachments/assets/3c549cd6-13c9-4a51-96ae-a4695a1be493)

**Comment by jkqxl** [comment]
日志保存了几次，终于有了。
[appLog-24-08-17 19_35_30.128.txt](https://github.com/user-attachments/files/16644643/appLog-24-08-17.19_35_30.128.txt)
[appLog-24-08-17 19_36_45.658.txt](https://github.com/user-attachments/files/16644644/appLog-24-08-17.19_36_45.658.txt)

**Comment by 821938089** [comment]
日志里没有备份相关的日志，你再多备份几次再保存

**Comment by 821938089** [comment]
你再更新一下最新测试版看看还有没有问题

**Comment by jkqxl** [comment]
> 你再更新一下最新测试版看看还有没有问题

保存日志很多次，在启动 其他设置-记录日志 的情况下，依然都是空白文件。

**Comment by 821938089** [comment]
你把整个压缩包发过来吧

你再去应用缓存目录里看看日志在不在

**Comment by jkqxl** [comment]
> 你把整个压缩包发过来吧
> 
> 你再去应用缓存目录里看看日志在不在

24-08-18 09:57:19.345: Backup 阅读备份 bookshelf.json 列表为空
24-08-18 09:57:19.353: Backup 阅读备份 bookmark.json 列表为空

但很显然，书籍列表不可能是空的

**Comment by jkqxl** [comment]
> 你把整个压缩包发过来吧
> 
> 你再去应用缓存目录里看看日志在不在

试了很多次，还是无法复现，不过备份恢复时，倒是经常性出问题，能否把 恢复的日志一起加进来，同时测试。
之前那个92.66K的备份文件，应该是恢复时没有恢复书籍导致的，这样的话，很难确定第一次备份失败到底是什么原因导致的。

话说，自动备份到底在每天的什么时间点，午夜的话，确实有断网的情况。

**Comment by 821938089** [comment]
自动备份除了webdav的上传外其他的不受网络影响

你书架有多少本书？

**Comment by jkqxl** [comment]
> 自动备份除了webdav的上传外其他的不受网络影响
> 
> 你书架有多少本书？

应该有上百本吧，已经是十几年的老读者了，哈！

**Comment by 821938089** [comment]
恢复备份的日志已经加上了，你更新最新测试版再恢复备份看看有没有问题

**Comment by jkqxl** [comment]
> 恢复备份的日志已经加上了，你更新最新测试版再恢复备份看看有没有问题

奇怪，连续几天测试，最新测试版软件都没有出现任何问题，这就没办法了。不过建议，以后测试版都默认开启日志，这样不用每次重装都要首先开启它

**Comment by 821938089** [comment]
那应该是修复了，你可以试试装回旧版看看能不能复现

**Comment by jkqxl** [comment]
> 那应该是修复了，你可以试试装回旧版看看能不能复现

之前原始的那个出问题安装包没有保存着，既然已经修复，那就不折腾了。
