### ISSUE TITLE
新书添加希望能够改为添加在书架列表最上方

### ISSUE THREAD

**Issue by 821938089** [gedoor/legado#410]
因为我习惯相对固定的位置，我就把排序改成了手动排序，改完后发现在添加新书时是添加在列表最后的，我的书架最下面的书都是一些旧的书，每次添加都要移动到最上方，非常不方便。

我是新旧版一起用的，我看了下旧版明明是添加在最上方的，怎么新版就不一样了。

希望能和旧版一致。

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持

**Comment by 821938089** [comment]
> 最新版已优化该功能，如有问题可重新开issues，感谢支持

 我最新版添加新书还是在列表最下面啊，排序模式是手动排序。
