### ISSUE TITLE
下载链接后缀识别失败

### ISSUE THREAD

**Issue by zmn001125** [gedoor/legado#4101]
### 确认 / Assignments

- [x] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

书源链接：https://jt12.eu/SYV2_4/2024/08/18/16/33/29/172397000966c1b1d94ac34.json

3.23版本的阅读更新可添加{"type":类别}来识别下载后缀后，该源可正常下载直接读取阅读，但3.24不知道哪个版本开始，无法识别下载了。

正常显示：书名.txt  阅读版本为3.23 10月份的
现在显示：text  阅读版本为3.24 7月份的
![Screenshot_2024-08-18-16-31-54-416_com miui home-edit](https://github.com/user-attachments/assets/c16eb0a3-913f-4a71-9eb9-d0ca13bfddf3)
![Screenshot_2024-08-18-16-32-25-945_io legado app release](https://github.com/user-attachments/assets/954e323c-a3f5-4570-8c5b-7dc753fc295b)

无法正常下载
![Screenshot_2024-08-18-16-43-55-215_io legado app release](https://github.com/user-attachments/assets/f0c5e8cb-ca27-4f74-a0b5-6e4fc904214c)
![Screenshot_2024-08-18-16-44-17-680_io legado app release](https://github.com/user-attachments/assets/7ef87b1e-e4af-4787-ac41-57a48768a0fa)

### 复现步骤 / How to reproduce

书源链接：https://jt12.eu/SYV2_4/2024/08/18/16/33/29/172397000966c1b1d94ac34.json

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.081816

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi k50

**Comment by 821938089** [comment]
试试最新测试版
