### ISSUE TITLE
音量键翻页如果翻的快会无效

### ISSUE THREAD

**Issue by wuyou1024** [gedoor/legado#4110]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

如题

### 复现步骤 / How to reproduce

快速音量键翻页即可

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.08200225

### Android版本 / Android version

A12

### 机型 / Model

realmeq2

**Comment by 821938089** [comment]
不是bug，这是限制了音量键的点击频次

**Comment by wuyou1024** [comment]
> 不是bug，这是限制了音量键的点击频次

emm，有原因吗

**Comment by 821938089** [comment]
#3595

**Comment by wuyou1024** [comment]
> #3595

OK
