### ISSUE TITLE
共存版讀取雲端備份，排版會跑掉

### ISSUE THREAD

**Issue by miaomiaorun** [gedoor/legado#4115]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

1.截至最新3.24.08202038為止，共存版只要讀取web進度檔，排版包含字型、字體大小、標題大小、邊距、頁首頁尾等等…設定全部都會變回預設

2.前面已有大大說過,每次開啟朗讀，都會強制跳出電池優化設定提醒  （以前pro版不會，而且的確電池優化選自定義就能正常朗讀了，不希望它再出現）

### 复现步骤 / How to reproduce

備份與復原／復原／選擇復原檔／排版就跑回預設

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

legado_app_3.24.08202038_releaseA

### Android版本 / Android version

安卓14

### 机型 / Model

三星S22 Ultra

**Comment by 821938089** [comment]
麻烦录个复现视频看看

**Comment by miaomiaorun** [comment]
https://github.com/user-attachments/assets/a611a623-3d96-4cd5-9e7c-b9fcca522398

如影片所示，讀取後頁首頁尾跑掉，跑出分割線，把分割線取消，就會連字型都跑掉(但是剛剛測試，復原同一設備的備份不會，只有復原另一台設備的備份，才會出現錯誤)

**Comment by miaomiaorun** [comment]
https://github.com/user-attachments/assets/0a0c4d32-edcd-4086-b824-e91703e3ee95

朗讀時會強制跳出電池優化通知，但是實際上，背景朗讀完全不會有問題

**Comment by 821938089** [comment]
另一台设备的阅读界面配置和这台是一样的吗

无法判断朗读会不会出问题，所以只能都请求权限

**Comment by miaomiaorun** [comment]
界面是設定一樣的，頁首頁尾也是，我的3.25也是還原同一個檔案，就不會跑掉，只有3.24會

另，pro就不會強制請求權限啊，建議可以新安裝的第一次提醒，不用
