### ISSUE TITLE
新版上下滑动翻页每一页连接处设置的行距段距不生效

### ISSUE THREAD

**Issue by hughuh11** [gedoor/legado#4117]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [x] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

新版本翻页动画为滚动模式下，前后页连接处导致行距段距不生效，旧版无此问题
![IMG_20240822_114006](https://github.com/user-attachments/assets/b86301e5-ba88-448c-ac2d-28e2c907aabe)
![Screenshot_2024-08-22-11-37-54-27_b46d61021eb8d6931849578836530a01](https://github.com/user-attachments/assets/8ac8d399-02dc-4a96-8380-86ae993bf6d8)

### 复现步骤 / How to reproduce

将翻页动画设置为滚动，信息中页眉页脚设置为隐藏，边距中正文上下边距设置为零，设置打开隐藏状态栏拓展至刘海，滑动屏幕在上下页连接处设置的行距段距不生效

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.082114

### Android版本 / Android version

安卓14

### 机型 / Model

一加12

**Comment by 821938089** [comment]
已修复，试试最新测试版
