### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#4118]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

书籍封面和书籍里打开图片显示时下边界太长，超出了屏幕

### 复现步骤 / How to reproduce

图片显示问题

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.08

### Android版本 / Android version

10

### 机型 / Model

mate 10

**Comment by 821938089** [comment]
发图看看

**Comment by sartonsh** [comment]
![Screenshot_20240822_134031_io legado app release](https://github.com/user-attachments/assets/1a3360e9-cad3-47de-93ff-a654eb6ce64f)
![Screenshot_20240822_134406_io legado app release](https://github.com/user-attachments/assets/3651a849-72f6-43dd-825e-a8dd4a8fd1d5)
![Uploading Screenshot_20240822_134751_io.legado.app.release.jpg…]()

**Comment by 821938089** [comment]
试试最新测试版

**Comment by sartonsh** [comment]
OK
