### ISSUE TITLE
[反馈] AOSP/LineageOS 等类原生 Android 系统全面屏手势跟翻页手势同时生效

### ISSUE THREAD

**Issue by FanchangWang** [gedoor/legado#412]
《阅读》翻页手势非常贴近屏幕边缘，类原生 Android 系统的全面屏手势从屏幕边缘左右滑动或向上滑动时，会触发阅读器的左右翻页，希望能把阅读器响应翻页手势距离屏幕边缘稍远一些

**Comment by 52fisher** [comment]
现在支持自定义翻页区域了

**Comment by FanchangWang** [comment]
> 现在支持自定义翻页区域了

这个你理解错了，不是 9 宫格的翻页区域，是响应手势距离屏幕边缘太近了，使用系统返回手势的时候，相当于同时再阅读器上进行了一次左滑或右滑操作，导致阅读器会在返回书架的时候同时左右翻一页章节
