### ISSUE TITLE
浏览发现时闪退

### ISSUE THREAD

**Issue by Gslw** [gedoor/legado#4120]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

浏览发现时闪退

### 复现步骤 / How to reproduce

浏览发现时闪退

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

浏览发现时闪退

### 日志提交 / Relevant log output

[Uploading logs.zip…]()

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

安卓14

### 机型 / Model

IQOO Z9 Turbo

**Comment by 821938089** [comment]
日志文件没有上传成功，另外崩溃日志需要单独传一下
