### ISSUE TITLE
正文<img src='https://cdn.uaa.com/file/bucket-media/image/other/roman11.webp'>不加载图片，用正则表达式将单引号改成双引号才成功加载，这算bug吗？

### ISSUE THREAD

**Issue by zhongerxll** [gedoor/legado#4121]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

如标题

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.082215

### Android版本 / Android version

a13

### 机型 / Model

galaxy s23 ultra

**Comment by 821938089** [comment]
不算，需要双引号才能识别到图片
