### ISSUE TITLE
爬取页面时执行 Javascript

### ISSUE THREAD

**Issue by molingyu** [gedoor/legado#4122]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

很多网站防止爬虫，使得直接获取页面而不执行js会导致抓取不到数据。需要在请求页面后执行页面的JavaScript才能获取到相应的数据。

希望能给书源添加个功能，允许爬取后执行页面里的 JavaScript
在执行完毕后再抓取想要的数据

### 期望实现方式 / How to implement

技术上使用 Appium 来模拟网页执行js

**Comment by youke2580c** [comment]
用webView动态加载![Screenshot_2024_0823_155008.jpg](https://github.com/user-attachments/assets/3516af54-d3a2-4ebb-ad3c-f7cbccfe14f5)

**Comment by 821938089** [comment]
可以在页面执行js，用webjs
