### ISSUE TITLE
恢复以往的备份后，书架中不显示手机本地书籍封面。

### ISSUE THREAD

**Issue by runningwaterpro** [gedoor/legado#4126]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

备份恢复后，书架上的本地书籍封面并未按照epub书籍封面显示，而是显示为自动生成的带文字的封面；通过书源搜索的书籍能够显示封面。

本地的书籍是在“\books”文件夹中，都是epub格式，点击书籍，能够显示书籍内容，之前的阅读进度也都正常。

![Screenshot_2024-08-26-09-03-53-789_io legado app release](https://github.com/user-attachments/assets/d605b144-06e9-4591-8d3d-016e559c8caa)

### 复现步骤 / How to reproduce

1. 通过设置中的功能备份，同时备份到本地和WebDav
3. 卸载应用
4. 安装最新版3.25
5. 设置WebDav
6. 恢复当日最新备份版本

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

下载、安装最新测试版“ab519d6”，显示版本号为3.24.082522，低于当前正式版 3.25，所以无法安装。

### 日志提交 / Relevant log output

新安装应用，“我的-关于-崩溃日志”无内容。

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

澎湃OS 1.0.12.UMNCNXM , Android 14

### 机型 / Model

Redmi K60

**Comment by 821938089** [comment]
不会备份封面图片，你到详情页里重新刷新一下

**Comment by runningwaterpro** [comment]
> 不会备份封面图片，你到详情页里重新刷新一下
> 
> 最新测试版版本号是比正式版高的，不过签名不同，是无法直接安装的

刚刚更新了之前的说明，书源里搜索的点进去后能够更新封面，但是本地的epub书籍，刷新书架、进入书籍都不会显示原有epub自带的封面。

**Comment by runningwaterpro** [comment]
> > 不会备份封面图片，你到详情页里重新刷新一下
> > 最新测试版版本号是比正式版高的，不过签名不同，是无法直接安装的
> 
> 刚刚更新了之前的说明，书源里搜索的点进去后能够更新封面，但是本地的epub书籍，刷新书架、进入书籍都不会显示原有epub自带的封面。

找到更新方式了，囧。

**Comment by runningwaterpro** [comment]
> 不会备份封面图片，你到详情页里重新刷新一下
> 
> 最新测试版版本号是比正式版高的，不过签名不同，是无法直接安装的

找到更新方式了，这个交互是一时间没想到的，因为点击封面直接查看书籍了，需要长按才能进入详情，感觉有点别扭。

问题已经解决了，谢谢。
