### ISSUE TITLE
处理器差点的！打来阅读就卡！

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#413]
每次进去书源就卡个十秒！每次刷书架也是，拖动就卡！

**Comment by gedoor** [comment]
书太多了吗,835cpu不卡啊

**Comment by chenweizi666** [comment]
飞哥就十几本书！华为的手机！麒麟处理器？？
![Uploading Screenshot_20201010-134734.jpg…]()

**Comment by chenweizi666** [comment]
![Uploading Screenshot_20201010-230109.jpg…]()

**Comment by gedoor** [comment]
更新一下
