### ISSUE TITLE
3.25朗读行颜色无法更改或者是我不知道在哪更改

### ISSUE THREAD

**Issue by Animism001** [gedoor/legado#4154]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

不知道是不是bug，更新3.25版本后，开启朗读，发现正在朗读的那一段文字颜色不够显眼（白天黑色字体，朗读段落却是灰色的），试着更改，以前是在主题设置里面更改对应主题模式的强调色就行，现在修改了强调色却无法生效，还是原来的颜色，“界面”设置中更改字体颜色也只能修改文字颜色，不能修改朗读段落文字颜色。

### 复现步骤 / How to reproduce

主题设置，更改当前主题模式（白天\夜间）强调色，软件界面字体\图标颜色改变，返回朗读页面，朗读段落颜色不变

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.2.5

### Android版本 / Android version

Android 10

### 机型 / Model

三星 Note9

**Comment by 821938089** [comment]
麻烦录个视频看看

**Comment by Animism001** [comment]
https://github.com/user-attachments/assets/843e52f8-c814-4134-b5cf-9ff801d92aa7

**Comment by Animism001** [comment]
自动翻页的话线的颜色好像是和朗读文字颜色一样的，灰色，很不显眼

**Comment by 821938089** [comment]
你可以下载共存版，releaseA那个
https://github.com/gedoor/legado/releases/tag/beta

**Comment by Animism001** [comment]
[logs.zip](https://github.com/user-attachments/files/16759036/logs.zip)
试了一下测试版，还是改不了，用了谷歌版3.23就不存在这种问题

**Comment by 821938089** [comment]
你再更新一下最新测试版看看好了没

**Comment by 821938089** [comment]
长按刷新按钮会弹出菜单可以刷新后续的章节

**Comment by Animism001** [comment]
好的，谢谢！这功能不说还真不知道
________________________________
发件人: Horis ***@***.***>
发送时间: 2024年8月27日 22:41
收件人: gedoor/legado ***@***.***>
抄送: Animism001 ***@***.***>; Author ***@***.***>
主题: Re: [gedoor/legado] 3.25朗读行颜色无法更改或者是我不知道在哪更改 (Issue #4154)


长按刷新按钮会弹出菜单可以刷新后续的章节

―

**Comment by Kagamine-Rinrin** [comment]
> 最新测试版里添加了一些日志，你安装后去其他设置里打开记录日志，然后去主题设置里换一下强调色，然后去关于那里点保存日志上传到这里

夜间模式正在朗读段落现在变成了紫红色😂，晚上看有些刺眼了 
已确认主题设置里的强调色是咖啡色，如下图：
上个版本没有出现这个问题
![Screenshot_20241130-171055](https://github.com/user-attachments/assets/c823b3c2-a805-4488-8c76-69c03ea9d1f9)
![Screenshot_20241130-171028](https://github.com/user-attachments/assets/36621512-938e-428e-9c28-7f643194fdac)

**Comment by 821938089** [comment]
@Kagamine-Rinrin 更新最新测试版

**Comment by Kagamine-Rinrin** [comment]
> @Kagamine-Rinrin 更新最新测试版

好的，我去试试~

**Comment by Kagamine-Rinrin** [comment]
> > @Kagamine-Rinrin 更新最新测试版
> 
> 好的，我去试试~

反馈一下(未使用测试版)：
之前我试过重新更改设置、重启程序等方法，问题依旧


然后昨晚开始
我什么都没做，它莫名其妙就好了，朗读的段落标记颜色能按照设置里的显示了…
