### ISSUE TITLE
希望可以支持一下低版本sdk 安卓

### ISSUE THREAD

**Issue by gaows20** [gedoor/legado#4160]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望可以支持一下低版本sdk 安卓4.4

### 期望实现方式 / How to implement

希望可以支持一下低版本sdk 安卓4.4

**Comment by some0ne1980** [comment]
这是新版，以前是2.x的版本是支持的。就是书源都比较旧了，需要自己制作书源
