### ISSUE TITLE
最新测试版本听说进度不会动

### ISSUE THREAD

**Issue by lhjgege** [gedoor/legado#4161]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

听书时候息屏在打开进度条不会动了

### 复现步骤 / How to reproduce

进入听说界面播放听书，然后息屏在打开进度条不会动了

https://github.com/user-attachments/assets/9967acb2-2289-4bd3-a77c-0a3e04487690

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

...

### 日志提交 / Relevant log output

没错误日志

### 阅读版本 / Legado version

3.24.082720

### Android版本 / Android version

android14

### 机型 / Model

小米13

**Comment by 821938089** [comment]
你把息屏打开的操作录个视频，我试了没出现和你一样的问题

**Comment by lhjgege** [comment]
又不会出现了。

**Comment by lhjgege** [comment]
等复现我在录制视频一下

**Comment by 821938089** [comment]
我测试的时候发现切换章节的时候就会出现你视频里的情况，现在修复了，你更新最新测试版试试

**Comment by lhjgege** [comment]
好的好的，感谢感谢

**Comment by lhjgege** [comment]
又发一个bug，听书中如果设置快进为1.2切换到下一章进度条又会恢复到1了

https://github.com/user-attachments/assets/85a1a254-a180-4f76-af6f-9e072c73a127

**Comment by 821938089** [comment]
修复了，试试最新测试版
