### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Gslw** [gedoor/legado#4162]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

本次是搜索闪退,之前浏览发现也闪退过,但是当时日志没留下来.

### 复现步骤 / How to reproduce

反复搜索时闪退

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

已经是最新的Actions版本了.

### 日志提交 / Relevant log output

[logs.zip](https://github.com/user-attachments/files/16797301/logs.zip)

### 阅读版本 / Legado version

3.24082909

### Android版本 / Android version

Android 14

### 机型 / Model

IQOO Z9 Turbo

**Comment by 821938089** [comment]
你看看崩溃日志里面有没有东西
