### ISSUE TITLE
更改导入的txt文本书架里的内容不会改变

### ISSUE THREAD

**Issue by fawumeng404** [gedoor/legado#4164]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在软件里导入一个txt文本，之后更改对应地址上的txt文本内容，书架里的内容不会改变，点了刷新后还是不改变，必须删除书籍，然后重新导入才行（也不知道是我没点对还是怎么的），希望大佬能处理一下这个问题

### 复现步骤 / How to reproduce

导入txt文件，更改对应地址txt文件内容，刷新，内容不变

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android 14

### 机型 / Model

oppo reno8 pro

**Comment by 821938089** [comment]
你如果不是在阅读的添加本地里导入的书籍，那么你打开的书籍将会复制一份到书籍保存位置中，你需要修改这里的文件

**Comment by fawumeng404** [comment]
大佬，我是在添加本地里导入的书籍啊，但更改对应地址的txt文件后，刷新以后书架里的还是没有改变，必须得删了之后重新添加

**Comment by fawumeng404** [comment]
大佬，我是在添加本地里导入的书籍啊，但是更改在本地导入那里选择的地址里的txt文件，之后刷新不起作用，书架上的书籍还是没变化

**Comment by 821938089** [comment]
你怎么刷新的？是更新目录吗？

**Comment by fawumeng404** [comment]
![Screenshot_2024-08-29-21-56-28-17_90024215e504237c76412be1999ad914](https://github.com/user-attachments/assets/74f6413c-fc38-472c-8e83-3fb6cefe8bb6)
就这里

**Comment by 821938089** [comment]
这个刷新不行，你重启下阅读再更新目录试试

**Comment by fawumeng404** [comment]
解决了，大佬牛逼，感谢感谢

**Comment by fawumeng404** [comment]
就是必须重启一下才行(◦˙▽˙◦)

**Comment by fawumeng404** [comment]
哎，这个问题怎么又开启了，关一下

**Comment by 821938089** [comment]
你点Close issue就可以关了

**Comment by fawumeng404** [comment]
哦吼，谢谢
