### ISSUE TITLE
导出功能补充：增加调用其他应用按钮”打开为“

### ISSUE THREAD

**Issue by X012C** [gedoor/legado#4165]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

希望能够做导出的后面增设一个按钮”打开为“，用来调用第三方应用阅读。（毕竟阅读缺乏本地阅读笔记功能，导出功能多数是配合第三方阅读器使用。）

### 期望实现方式 / How to implement

增设调用其他应用功能。

**Comment by runningwaterpro** [comment]
哈哈，当下载器用了。
