### ISSUE TITLE
三个锦上添花功能参考

### ISSUE THREAD

**Issue by kangpou** [gedoor/legado#4167]
### **◆给选定的字显示注音**
  1. 功能1，开关，给常用易错、生僻字显示注音。
  2. 功能2，填写，手动添加文字，添加的文字会显示注音。
  3. 功能3，开关，给所有字添加注音。
  ![IMG_20240831_023433](https://github.com/user-attachments/assets/c5071618-1236-48ff-a435-61147cffc27f)
(有些字，一错就是一辈子！避免被人喊文盲)

### **◆添加评论显示**
  1. 给句末后面添加一个评论显示图标，点击后显示评论弹框，如图，参考奇点。
  2. 此功能主打一个氛围，评论对于小说，相比于弹幕对于影视来说有异曲同工之妙。
  3. 可能类似于书源一样，需要源编写，需要代码爬取
  ![IMG_20240831_023425](https://github.com/user-attachments/assets/a9f55342-22e6-40e1-8e21-25ba4098cd23)
(漫漫阅读之路，还有各位书友的陪伴)

### **◆书签(笔记)显示支持**
  用更直白的方式显示书签(笔记)。
  1. 加了书签(笔记)的文本增加下划线显示，或在句末增加一个铅笔图标。
  2. 点击下划线或铅笔图标后直接弹框显示书签内容。
  ![IMG_20240831_023602](https://github.com/user-attachments/assets/35032840-91eb-4f79-b686-a5c16dc0670e)
(书签更直白、更直观)

----
萌新发言，如有打扰冒犯请随时关闭此 issue 。

**Comment by X012C** [comment]
笔记功能有很多次反馈的，开发者好像是坚决反对的。

话说你这个是什么应用？

**Comment by X012C** [comment]
> 个人看法：
> 
> > 给选定的字显示注音
> 
> 注音感觉用处好像不大，一般都是关注情节推进。
> 
> > 添加评论显示
> 
> 一般来说，书源都是类似笔趣阁之类的网站，根本没评论。有评论的比如起点，但是免费章节有限，一般都看几十章就要换别的源。这感觉是个完全没必要的需求。
> 
> > 书签(笔记)显示支持
> 
> 书签现在是有的，你的描述感觉是对某一段文字进行记笔记，跟书签好像没什么关系。 这个需求感觉意义不大。 首先源会失效，当出现某些章节少了又会换源，这会导致这些笔记都没了，书签现在好像也是这样，换源后没了。 然后网络小说通常关注的是直接的情节推进，信息密度相对较低，记不记笔记感觉没什么必要，不如直接使用书签记录这个位置

划线可以起到辅助阅读的作用。这是阅读习惯的差异吧。笔记功能的需求呼声还是挺高的。
借楼问一下大佬这个项目最近是什么状态，原先维护的开发者都跑路了？公众号好像停更好久了。

**Comment by Iseink** [comment]
哈哈，英雄所见略同，特指段评，为了这个，今天我还去起点重新订阅一本书，就是想重刷的时候看段评。我抓过QQ浏览器，评论都是明文，做书源其实不难，这功能有搞头。

**Comment by kangpou** [comment]
> 哈哈，英雄所见略同，特指段评，为了这个，今天我还去起点重新订阅一本书，就是想重刷的时候看段评。我抓过QQ浏览器，评论都是明文，做书源其实不难，这功能有搞头。

对爱看网文的乐子人书友加成很大，氛围拉满。

**Comment by Discut** [comment]
段评好像debug版有相关的ui，不知道为啥没做。可能是不好爬评论

**Comment by YingJuanJuan** [comment]
> 功能1，开关，给常用易错、生僻字显示注音。  

这个需求其实不小，需要考虑的东西有点多。  

- 业务方面：  
    - 生僻字注音，首先你得先知道生僻字有哪些。根据我随手一查的结果，**生僻字至少有六千个**。[生僻字大全](https://www.converts.cn/shengpizi.html)  
    - 然后是多音字的情况，你如何**为多音字指定读音**呢，不同的情景下有不同的读音，这也是需要考虑的一个方面。  
    - 如果有个字不属于易错字、生僻字，但用户不认识，给项目提了缺陷，开发者还要额外消耗精力处理无效缺陷。  


- 技术方面：  
    - 新增一个**显示注音**开关，这个倒不是难点。  
    - 注音功能打开时，需要预留注音的 UI 空间，这个会**影响字间距、段落间距**的布局。  
    - 最麻烦的是额外的性能开销，注音功能需要遍历文章中是否存在生僻字，这可能会**占用更多的性能，还会影响正文加载速度、电量消耗速度**。  

---

理想情况下，注音功能是个好功能，但实际使用可能就会发现没那么好用。再说了，一般的小说正文也不会有太多的生僻字。  

退一步讲，如果想查询某个字的读音，可以**导入字典源**，然后使用**在线字典**查询读音。  

---

具体这个功能要不要考虑实现，那就要看开发者有没有精力了。

**Comment by kangpou** [comment]
> > 功能1，开关，给常用易错、生僻字显示注音。
> > 功能2，填写，手动添加文字，添加的文字会显示注音。
> > 功能3，开关，给所有字添加注音。
> 
> 这个需求其实不小，需要考虑的东西有点多。
> 
> * 业务方面：
>   
>   * 生僻字注音，首先你得先知道生僻字有哪些。根据我随手一查的结果，**生僻字至少有六千个**。[生僻字大全](https://www.converts.cn/shengpizi.html)
>   * 然后是多音字的情况，你如何**为多音字指定读音**呢，不同的情景下有不同的读音，这也是需要考虑的一个方面。
>   * 如果有个字不属于易错字、生僻字，但用户不认识，给项目提了缺陷，开发者还要额外消耗精力处理无效缺陷。
> * 技术方面：
>   
>   * 新增一个**显示注音**开关，这个倒不是难点。
>   * 注音功能打开时，需要预留注音的 UI 空间，这个会**影响字间距、段落间距**的布局。
>   * 最麻烦的是额外的性能开销，注音功能需要遍历文章中是否存在生僻字，这可能会**占用更多的性能，还会影响正文加载速度、电量消耗速度**。
> 
> 理想情况下，注音功能是个好功能，但实际使用可能就会发现没那么好用。再说了，一般的小说正文也不会有太多的生僻字。
> 
> 退一步讲，如果想查询某个字的读音，可以**导入字典源**，然后使用**在线字典**查询读音。
> 
> 具体这个功能要不要考虑实现，那就要看开发者有没有精力了。

确实有些理想化，实现这功能需要投入的精力我也能想象得到，所以我也只敢说「锦上添花」、「参考」，这些也只是我使用 阅读 过程中昙花一现的一些小idea。
