### ISSUE TITLE
NetworkUtils.kt中hasUrlEncoded方法对字符的判断不全，导致已经经过编码的URL被重新编码

### ISSUE THREAD

**Issue by kasugu** [gedoor/legado#4168]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在最新版本阅读中，我使用某个书源搜书小说时出现了含有\~等字符的URL，出现该类字符时会导致URL被重复编码，从而导致与预期访问的URL不匹配，单独出现此问题时影响不大，只需自己不要传编码后的字符串即可。
但是假如此URL中还含有某些特殊请求参数时，比如带&等字符的参数("key1=test&test~")时，传递未经编码处理的原始字符串如直接java.ajax(strUrl)，携带的&会被当做不合法的单独参数而被过滤，不会当成某个参数的一部分，解析出的参数会变为"key1=test"，因此需要对该参数预先进行编码为"key1=test%26test~"，但是由于该bug存在，即使已经进行过编码，app/src/main/java/io/legado/app/utils/NetworkUtils.kt中hasUrlEncoded方法仍会返回true，导致被重复编码为key1=test%2526test~"，其中的%字符被重复编码为%25，如果含有中文字符也均会被重复编码
可能的解决方法:重写app/src/main/java/io/legado/app/utils/NetworkUtils.kt中hasUrlEncoded方法以及调用的notNeedEncoding方法，添加"-_.~"4个特殊字符的判断，保留这些特殊字符并且使其不影响hasUrlEncoded的判断

### 复现步骤 / How to reproduce

访问的URL携带的单个参数同时含有&与~等特殊字符时

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.072306

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K70

**Comment by 821938089** [comment]
你把~也一起编码了就没问题了

**Comment by kasugu** [comment]
> 你把~也一起编码了没什么问题了

~属于4个特殊字符里面的，编码前后不变😂

**Comment by 821938089** [comment]
会编码的，你用java.encodeURI

**Comment by kasugu** [comment]
> 会编码的，你用java.encodeURI

![Screenshot_2024-09-01-21-13-52-686_com android chrome](https://github.com/user-attachments/assets/afc5b7a7-6f56-4ed7-ba0e-9472e478858a)
我在在线网站上尝试是没有编码的
然后我在阅读上尝试打印了编码后的值，分别通过encodeURI与encodeURIComponent
![Screenshot_2024-09-01-21-17-30-585_io legado app release](https://github.com/user-attachments/assets/95600c6a-e8c8-418e-a382-9d10e9585d23)

**Comment by kasugu** [comment]
> 使用java.encodeURI尝试

可以了，感谢，没想到这里还有区别的😂之前那种写法就不会把\~转成URL编码
