### ISSUE TITLE
章节目录生成问题<民国投机者>

### ISSUE THREAD

**Issue by fjkdashg** [gedoor/legado#417]
宋美龄长出一口气，她终于看到让蒋介石回来的一丝曙光了。随后张静江又传来好消息，戴季陶居正的态度软化，不再坚持武力平叛。宋美龄立刻招来宋子文和孔祥熙商议，决定向何应钦提供十万法币充足作平叛军费。

    南京的情况很快传到西安，在东北军和西北军中引起巨大震动，部分东北军和西北军军官议论纷纷，指责张学良把他们带入险境；于学忠从兰州来电，甘肃驻军有不稳迹像，驻防甘南的两个团叛变。张学良闻报焦急万分，迫不得已请曾扩情出来作公开广播，告诉南京蒋介石还活着，呼吁南京方面要慎重行事，切勿挑起内战。

    十八日 .

_**第二部 经略西南 第八章 投机西安 第九节 转机（二）**_

    十二月二十日教导总队占领东西赤水，第二天攻克渭南，斯役教导总队两天内连下三城，伤亡不足百人，击溃东北军三个师，光俘虏就有三千多人，桂永清志得意满。

    但渭南一下，桂永清就面临选择的难题，何应钦接到攻克渭南的电报后，立刻给他来停止进攻的命令；而同时朝天宫的电报也到了，要求只有一个，继续进攻，一直打到西安城下。

    桂永清在渭南城内左右为难，南京城内的这句话、何应钦、贺衷寒这紧张的关注他的行动；除了他们以外，渭南以南公王岭俞济时也紧张的盯着桂永清的动向，他的一个旅正在阳郭以南待命。当然他没指望这个旅能解决教导总队，他们只启辅助作用。

民国投机者  章节目录未生成
链接：[民国投机者 https://share.weiyun.com/LaHzWrmj](https://share.weiyun.com/LaHzWrmj) 密码：8dtkfm

**Comment by 52fisher** [comment]
已内置此规则，由于此规则对于文本解析的错误率较高，故默认关闭。
如需要开启，可点击换源按钮手动点选 目录规则： 目录（古典、轻小说备用）

**Comment by fjkdashg** [comment]
收到    3Q
