### ISSUE TITLE
FLYME系统下 打开阅读会 自动修改 手机系统字体

### ISSUE THREAD

**Issue by okm0080808** [gedoor/legado#4173]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

我魅族手机，flyme10/11,都发现这个问题。 打开阅读后， 手机系统的字体大小会被修改

### 复现步骤 / How to reproduce

手机设置一个字体大小， 打开阅读，手机字体大小就会被修改

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

无

### 日志提交 / Relevant log output

无

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android 14

### 机型 / Model

魅族20PRO

**Comment by 821938089** [comment]
这个应该是系统的问题，你可以去魅族那里反馈，阅读不会修改系统的字体
