### ISSUE TITLE
希望支持搜索下一页规则

### ISSUE THREAD

**Issue by NRHSYD** [gedoor/legado#4177]
### 确认 / Assignments

- [x] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现有搜索下一页规则没有目录下一页规则强大，导致部分网站的搜索不能通过{{page}}翻页，比如e-hentai.org

### 期望实现方式 / How to implement

与目录下一页规则相似即可

**Comment by 821938089** [comment]
你自己把下一页地址存变量里调用就可以了，注意要用source.put和source.get来存
