### ISSUE TITLE
替换出错

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#4178]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

正文里有$$，替换就出错，找了半天原因

### 复现步骤 / How to reproduce

正文有$$，替换出错了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.082611

### Android版本 / Android version

Android 14

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
请提供详细复现步骤

**Comment by gyz1023** [comment]
https://jt12.eu/SYV2_4/2024/09/06/9/19/20/172558556066da5898a0d53.json
我用的净化，然后随便一本书，编辑内容，里面加上$，一个多个都行，他就出错误

**Comment by 821938089** [comment]
已修复，试试最新测试版
