### ISSUE TITLE
听书源发现处进度条归零

### ISSUE THREAD

**Issue by SH6915** [gedoor/legado#4179]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

发现处,第一次听书进度条正常,返回在看时进度条为零

### 复现步骤 / How to reproduce

点开听,返回再回来归零
![Screenshot_20240906_130439](https://github.com/user-attachments/assets/9727dce4-a37f-44b4-9ca4-4d4f3bbfcf83)
![Screenshot_20240906_130442](https://github.com/user-attachments/assets/eb4acf10-248f-4a98-95ca-d5f42099eb79)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.090609

### Android版本 / Android version

Android14

### 机型 / Model

iqoo12

**Comment by 821938089** [comment]
加书架了吗？没加的话是正常的

**Comment by SH6915** [comment]
了解[没加]
