### ISSUE TITLE
显示不全

### ISSUE THREAD

**Issue by SH6915** [gedoor/legado#4180]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

![Screenshot_20240906_162718](https://github.com/user-attachments/assets/bdae3fb8-4047-409e-8057-322c6b641eb2)

### 复现步骤 / How to reproduce

未知

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.090614

### Android版本 / Android version

Android14

### 机型 / Model

iqoo12

**Comment by yezechuandl** [comment]
同样的问题。编辑书源弹出输入法，看起来挺正常的，收回输入法后出现大片空白区域，刚好是输入法覆盖的部分。那部分无法进行点击滑动等操作，非空白区域正常。

**Comment by 821938089** [comment]
已修复，试试最新测试版
