### ISSUE TITLE
书源管理编辑后关闭输入法仍有遮罩

### ISSUE THREAD

**Issue by bellongyan** [gedoor/legado#4181]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在书源管理页面进行编辑书源后，关闭输入法后，应用界面原输入法区有遮罩覆盖，只能退出当前页面重新进入

### 复现步骤 / How to reproduce

1. 打开阅读的书源管理页面
2. 点击任意一条书源的编辑页面进行编辑书源
3. 点击任意输入框
4. 主动点击输入法的降下按钮或使用系统返回键关闭输入法

录屏文件链接[复现录屏 https://github.com/user-attachments/assets/efe08a5a-da04-4cc0-bf85-3beb559c858b](https://github.com/user-attachments/assets/efe08a5a-da04-4cc0-bf85-3beb559c858b)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.090515

### Android版本 / Android version

Android 14

### 机型 / Model

iQOO Neo9S Pro

**Comment by 821938089** [comment]
已修复，试试最新测试版
