### ISSUE TITLE
帮助里缺个图片

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#4182]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

本地小说，换目录正则页面的帮助里，缺个图片
![Screenshot_2024-09-07-14-35-51-686_io legado app releaseA](https://github.com/user-attachments/assets/33e46e96-209e-443c-89af-1dd0fe0eb6ba)

### 复现步骤 / How to reproduce

看txt本地小说，目录正则帮助页面里少个事例图片

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.090609

### Android版本 / Android version

Android 14

### 机型 / Model

redmi k40s

**Comment by 821938089** [comment]
这个已经修复了，你截图的阅读不是最新测试版吧？
