### ISSUE TITLE
删除18PlusList.txt 已经过时

### ISSUE THREAD

**Issue by jujubeja** [gedoor/legado#4183]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

legado 是一款开源阅读器, 不做 网络审查 这种破坏互联网自由的事情。
18PlusList.txt 列表也过老。

### 期望实现方式 / How to implement

删除 https://github.com/gedoor/legado/blob/master/app/src/main/assets/18PlusList.txt

**Comment by runningwaterpro** [comment]
解码看了下，不知道是不是福利，担心有NSFW，没敢搜索查阅。
