### ISSUE TITLE
大佬们，如何更换包名？有没有傻瓜教程！多谢了！

### ISSUE THREAD

**Issue by lmex621** [gedoor/legado#419]
大佬们，如何更换包名？
自己尝试修改了包名，但编译报错！
有没有傻瓜教程！本人菜鸟一枚！
多谢了！

**Comment by Celeter** [comment]
直接下载actions里面的版本https://github.com/gedoor/legado/actions
里面包名是改过的

**Comment by lmex621** [comment]
> 直接下载actions里面的版本https://github.com/gedoor/legado/actions
> 里面包名是改过的
哦。谢谢。我想改成自己想的包名。并不是共存。

**Comment by Celeter** [comment]
> 哦。谢谢。我想改成自己想的包名。并不是共存。

根据actions的脚本做对应修改就行

**Comment by clijiac** [comment]
> > 直接下载actions里面的版本https://github.com/gedoor/legado/actions
> > 里面包名是改过的
> > 哦。谢谢。我想改成自己想的包名。并不是共存。

编辑\legado\app\build.gradle
- 第六行 前面加上两个//
> `apply plugin: 'com.google.firebase.crashlytics'`
> `//apply plugin: 'com.google.firebase.crashlytics'`

- 最后一行 前面加上两个//
> `apply plugin: 'com.google.gms.google-services'`
> `//apply plugin: 'com.google.gms.google-services'`



编辑第三十五行 "io.legado.app" 里面为你想要的包名
```java
        applicationId "io.legado.app"
```

然后cmd进入legado根目录, 运行 gradlew assembleAppRelease

编译好的apk在legado/app/build/outputs/apk/app/release

**Comment by lmex621** [comment]
> > > 直接下载actions里面的版本https://github.com/gedoor/legado/actions
> > > 里面包名是改过的
> > > 哦。谢谢。我想改成自己想的包名。并不是共存。
> 
> 编辑\legado\app\build.gradle
> 
> * 第六行 前面加上两个//
> 
> > `apply plugin: 'com.google.firebase.crashlytics'`
> > `//apply plugin: 'com.google.firebase.crashlytics'`
> 
> * 最后一行 前面加上两个//
> 
> > `apply plugin: 'com.google.gms.google-services'`
> > `//apply plugin: 'com.google.gms.google-services'`
> 
> 编辑第三十五行 "io.legado.app" 里面为你想要的包名
> 
> ```java
>         applicationId "io.legado.app"
> ```
> 
> 然后cmd进入legado根目录, 运行 gradlew assembleAppRelease
> 
> 编译好的apk在legado/app/build/outputs/apk/app/release

大哥牛批。我去试下。
