### ISSUE TITLE
希望加入声音翻页

### ISSUE THREAD

**Issue by freeocha** [gedoor/legado#4197]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在床上使用懒人支架看书手臂要一直悬空很不舒服。而且点击屏幕会造成晃动。
希望加入声控翻页。当发出一定声音就自动翻到下一页。

### 期望实现方式 / How to implement

开启声控翻页后，麦克风一直运行，接收到超过一定分贝的音量（可自行调节敏感度）就会翻到下一页。两次翻页的间隔大于2秒。

**Comment by joseph-lincc** [comment]
不如弄个蓝牙遥控器，不然屋外一个喇叭声可能就翻页了

**Comment by freeocha** [comment]
> 不如弄个蓝牙遥控器，不然屋外一个喇叭声可能就翻页了

敏感度做成可调节的就行，蓝牙有不固定的延迟，体验不好

**Comment by lededev** [comment]
那样也太吵了吧，不如加入眨眼翻页，或者嘴角舌头翻页
向后翻页：闭上左眼0.5秒并保存，然后眨两下右眼，并睁开双眼
向前翻页：闭上右眼0.5秒并保存，然后眨两下左眼，并睁开双眼
向后翻页：右嘴角上翘隙开0.5秒，然后露出舌头0.2秒，恢复嘴巴正常
向前翻页：左嘴角上翘隙开0.5秒，然后露出舌头0.2秒，恢复嘴巴正常

**Comment by freeocha** [comment]
上网找了很久，其实iOS那边的anyview也是支持声控翻页的，实现方案很早就有了，可惜安卓没有这个app。

**Comment by lededev** [comment]
上一个大版本（用Java写的那个）我在自动翻页加入了按字数/每分钟(CPM)设定滚动速度的功能，每页字数不同，自动滚动的速度也就不一样，始终按设定的CPM滚屏，如果某个用户习惯每分钟读200个字并以此设置，那么如果一屏显示的正好是200个字，滚屏时间就会是1分钟。如果是末尾页只有20个字，那么这一屏这些字的停留时间也就6秒钟，就会翻到新章节了。
比起匀速滚屏更科学。供需要实现翻页的用户参考。

**Comment by freeocha** [comment]
> 上一个大版本（用Java写的那个）我在自动翻页加入了按字数/每分钟(CPM)设定滚动速度的功能，每页字数不同，自动滚动的速度也就不一样，始终按设定的CPM滚屏，如果某个用户习惯每分钟读200个字并以此设置，那么如果一屏显示的正好是200个字，滚屏时间就会是1分钟。如果是末尾页只有20个字，那么这一屏这些字的停留时间也就6秒钟，就会翻到新章节了。 比起匀速滚屏更科学。供需要实现翻页的用户参考。

可能和个人阅读习惯有关。我看书看到某些会停下来思考有没有更好的解决方法，或者如果是某个角色会说什么话。读到某些段落会津津有味地多读两遍。遇到一些伏笔或者不太理解书中人物的操作就会前后看看想一想。作者写得不好的部分会快速略过。
所以阅读不是匀速的，而且时快时慢的事经常发生。自动翻页无论是因为等待翻页而打断思绪，还是没看完就被翻页，从来都没法带来好的体验。
