### ISSUE TITLE
翻页会跳章

### ISSUE THREAD

**Issue by cyao2q** [gedoor/legado#420]
阅读APP 有时候看小说 翻页的时候 跳章了 章节不连续（实际在目录看章节都有） 是咋回事啊

**Comment by gedoor** [comment]
没遇到过,可以观察一下什么时候跳章

**Comment by cyao2q** [comment]
> 没遇到过,可以观察一下什么时候跳章

公众号那边给您发了个录制视频  您可以看下

**Comment by cyao2q** [comment]
> 没遇到过,可以观察一下什么时候跳章

给这个kunfei.ge@gmail.com 邮箱发邮件了

**Comment by 52fisher** [comment]
如果还有问题的话，可以重新发起issue

**Comment by cyao2q** [comment]
不看 那本小说了 暂时没发现 最近看书都是缓存下来 导出成txt再看
