### ISSUE TITLE
朗读时快速双击会弹出两次朗读菜单

### ISSUE THREAD

**Issue by sheng-ri** [gedoor/legado#4201]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

朗读时快速双击会弹出两次朗读菜单

### 复现步骤 / How to reproduce

1. 开始朗读
2. 默认双击屏幕中间

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 pro

**Comment by 821938089** [comment]
已修复，试试最新测试版
