### ISSUE TITLE
我看图片类型的文字会储存在本地，有没有可能把图片类型的文字与实际文字手动匹配替换，只需一次性手动匹配后网站换掉图片代码也可从本地图片识别换成文字😅

### ISSUE THREAD

**Issue by bzt345** [gedoor/legado#421]
我看图片类型的文字会储存在本地，有没有可能把图片类型的文字与实际文字手动匹配替换，只需一次性手动匹配后网站换掉图片代码也可从本地图片识别换成文字😅

**Comment by bzt345** [comment]
就是说小说内图片换成文字。
有些网站图片代码吧一天一换，如果能本地图片与文字产生一种链接，就没必要再看图片了，图片还放在中间居中，站长换代码就换，反正识别的是本地图片

**Comment by bzt345** [comment]
最好导出txt时也能内容替换

**Comment by Celeter** [comment]
书源规则里去实现

**Comment by bzt345** [comment]
> 书源规则里去实现

本地图片转文字的功能能实现？

**Comment by shutaozhenzhen** [comment]
> > 书源规则里去实现
> 
> 本地图片转文字的功能能实现？

可以，我看到过这种书源。添加一个一对一的js替换。

**Comment by bzt345** [comment]
> > > 书源规则里去实现
> > 
> > 
> > 本地图片转文字的功能能实现？
> 
> 可以，我看到过这种书源。添加一个一对一的js替换。

一对一的js替换了，站长换图片代码后这个方式还可行吗？

**Comment by Celeter** [comment]
> > > > 书源规则里去实现
> > > 
> > > 
> > > 本地图片转文字的功能能实现？
> > 
> > 
> > 可以，我看到过这种书源。添加一个一对一的js替换。
> 
> 一对一的js替换了，站长换图片代码后这个方式还可行吗？

在规则里使用ocr接口

**Comment by bzt345** [comment]
> > > > > 书源规则里去实现
> > > > 
> > > > 
> > > > 本地图片转文字的功能能实现？
> > > 
> > > 
> > > 可以，我看到过这种书源。添加一个一对一的js替换。
> > 
> > 
> > 一对一的js替换了，站长换图片代码后这个方式还可行吗？
> 
> 在规则里使用ocr接口

不懂，但感觉有点麻烦，用户能不能点击小说内容里的图片文字通过几步来直接建立替换链接，而不是等大佬做，我是这个想法😅
