### ISSUE TITLE
Web service to TV

### ISSUE THREAD

**Issue by unOmni** [gedoor/legado#4210]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

The ability to use custom fonts on tv when using web service. Since unlike a pc, you can't install fonts on a tv (as far as i'm aware).

### 期望实现方式 / How to implement

Perhaps a pre-made list of fonts that can potentially increase over time.

**Comment by Xwite** [comment]
Use [FontFace](https://developer.mozilla.org/en-US/docs/Web/API/FontFace/FontFace) to load font from Internet.
1. input any characters into customFont inputbox
2. click save button and select the letf button in next dialog.
3. input URL which serves the font resource

**Comment by unOmni** [comment]
> Use [FontFace](https://developer.mozilla.org/en-US/docs/Web/API/FontFace/FontFace) to load font from Internet.
> 1. input any characters into customFont inputbox
> 2. click save button and select the right button in next dialog.
> 3. input URL which serves the font resource
> 

Give an example please for something like Noyh Geometric font.
