### ISSUE TITLE
Web服务书架页面由于大量请求封面导致无法使用

### ISSUE THREAD

**Issue by CKopoer** [gedoor/legado#4211]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

![image](https://github.com/user-attachments/assets/af2d514e-2c14-483e-9a91-6c5daf03f71a)
web服务无法加载出书架书单图片且阻塞在该页面，无法阅读
3.23.110211也有此问题但触发概率小，3.25更新后一直有此问题

### 复现步骤 / How to reproduce

打开web服务

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android 14

### 机型 / Model

XiaoMi 13

**Comment by 821938089** [comment]
最新测试版优化了一下，应该没那么卡了，你可以试试

**Comment by 821938089** [comment]
看这里的commit：
前端：
https://github.com/gedoor/legado/commits/master/modules/web/

后端：
https://github.com/gedoor/legado/commits/master/app/src/main/java/io/legado/app/web
https://github.com/gedoor/legado/tree/master/app/src/main/java/io/legado/app/api/controller

导致这个问题主要是网络问题，网络好就不会卡

**Comment by kangmeng1** [comment]
每次使用web服务前 清除webview 数据

**Comment by 501658362** [comment]
> 每次使用web服务前 清除webview 数据

还是你这招好使啊
