### ISSUE TITLE
后台缓存切回来时闪退

### ISSUE THREAD

**Issue by Gslw** [gedoor/legado#4212]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

RT,后台缓存切回来时闪退,新测试版刚更新还在测试

### 复现步骤 / How to reproduce

RT
[logs.zip](https://github.com/user-attachments/files/17054834/logs.zip)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.090712

### Android版本 / Android version

Android 14

### 机型 / Model

IQOO Z9 Turbo

**Comment by 821938089** [comment]
线程数开太大了，调小一些试试

**Comment by Gslw** [comment]
> 线程数开太大了，调小一些试试 不要同时缓存太多书籍

其他设置里那个更新和搜索线程数?默认是多少?目前12改6?

**Comment by 821938089** [comment]
对，可以试试改成6
