### ISSUE TITLE
调试有声小说时卡死

### ISSUE THREAD

**Issue by sky-bbk** [gedoor/legado#4213]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

书源：https://dns.jingluo.love/2024/66ebd084b7713.json
调试关键词：我的

### 复现步骤 / How to reproduce

调试后软件卡死无相应

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.091322

### Android版本 / Android version

Android 14

### 机型 / Model

23049RAD8C

**Comment by 821938089** [comment]
正文太大，加载卡住了

**Comment by sky-bbk** [comment]
原来我的正文规则是多余的，把正文规则删了就好了
