### ISSUE TITLE
cloudflare无限验证

### ISSUE THREAD

**Issue by zrnp** [gedoor/legado#4214]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

有些需要cloudflare验证的书源里，cloudflare总是无限验证，“检查站点连接是否安全”页面反复转圈。

### 复现步骤 / How to reproduce

使用以下需要cloudflare验证的书源，即出现以上bug
![qr](https://github.com/user-attachments/assets/12fceb18-8d11-4030-b266-38b78af033eb)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

andorid 12

### 机型 / Model

honor x10

**Comment by 821938089** [comment]
需要填一个正确的UA
