### ISSUE TITLE
英文文档要怎么排版呢？

### ISSUE THREAD

**Issue by weitianxiang19910000** [gedoor/legado#4220]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

需要对英文文档进行排版，现在英文的单词会在末尾拆分换行，这样不太合理

### 期望实现方式 / How to implement

需要对英文文档进行排版，现在英文的单词会在末尾拆分换行，这样不太合理

**Comment by 821938089** [comment]
关闭使用自定义中文分行
