### ISSUE TITLE
【作者看看】用Flutter开发了iOS版，适配了桌面端，能否加入一起开发

### ISSUE THREAD

**Issue by chinabrant** [gedoor/legado#4230]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

使用的阅读的源，部分规则不支持。
iOS TestFlight：https://testflight.apple.com/join/gxfZGKtX

桌面端也编译了一个简单版本，这是macos的截图：
![640](https://github.com/user-attachments/assets/b7405deb-5639-4322-935b-2f6f5dcb212c)

### 期望实现方式 / How to implement

能否一起开发，弥补阅读iOS和桌面端的缺失。

**Comment by aooiuu** [comment]
借个楼

有兴趣用 `javascript`、`typescript` 或者 ~~anyscript~~ 技术栈的欢迎大家加入开发

仓库地址: https://github.com/aooiuu/any-reader

---

目前实现了 eso 规则解析 https://github.com/aooiuu/any-reader/tree/master/packages/core
感谢 Horis 大佬贡献的 阅读规则解析  https://github.com/aooiuu/any-reader/tree/master/packages/legado

**Comment by wziton** [comment]
真有大佬开发ios版啊，最近想换苹果手机但又舍不得阅读😁

**Comment by newbinxxxx** [comment]
软件已经很好了，如果能把做个语音自定义的就很完美了！谢谢作者开发

**Comment by Yinghai75** [comment]
已经2个月没更了，是搁置了吗？ 如果能用Azure TTS， 微软晓晓多语言的话，我的安卓阅读器就可以闲置了。

**Comment by wziton** [comment]
> 真有大佬开发ios版啊，最近想换苹果手机但又舍不得阅读😁

有更新吗
