### ISSUE TITLE
藍芽翻頁器無法正確翻頁

### ISSUE THREAD

**Issue by Chloewubooks** [gedoor/legado#4232]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

原廠藍芽翻頁器(文石)可以連上，按菜單會正確顯示，但按上下頁沒有反應

### 期望实现方式 / How to implement

應該是實體音量鍵翻頁未正確映射，或許可以開放自定義?

**Comment by 821938089** [comment]
可以自定义按键

**Comment by miaomiaorun** [comment]
選單/設定/自訂翻頁按鍵，點在“上一頁按鍵”的輸入處，按一下你想設定的上一頁按鍵，系統就會自動輸入對應的按鍵數字，“下一頁”的設定也是一樣，藍芽鍵盤也是一樣的設定方式。

（BOOX遙控的方向鍵⬆️不能設定為上一頁，所以我的上一頁是設定➡️鍵，下一頁則可以正常用⬇️沒問題）

**Comment by Chloewubooks** [comment]
謝謝解答

> 選單/設定/自訂翻頁按鍵，點在“上一頁按鍵”的輸入處，按一下你想設定的上一頁按鍵，系統就會自動輸入對應的按鍵數字，“下一頁”的設定也是一樣，藍芽鍵盤也是一樣的設定方式。
> 
> （BOOX遙控的方向鍵⬆️不能設定為上一頁，所以我的上一頁是設定➡️鍵，下一頁則可以正常用⬇️沒問題）
