### ISSUE TITLE
正文可以等规则加载完再访问下一章吗，不是并发率

### ISSUE THREAD

**Issue by zhongerxll** [gedoor/legado#4233]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

某个网站看着看着正文就会要求人机验证，我搞了个判断，如果要求验证码就java.getVerificationCode然后重新访问一遍baseUrl，但是他会弹出好几个验证码弹窗给我，也就是多个章节的验证码弹窗，我搞并发率不管用，它不会等规则完成

### 期望实现方式 / How to implement

就像功能描述那样

**Comment by 821938089** [comment]
预加载章节调成0
