### ISSUE TITLE
书源越多,书源越少

### ISSUE THREAD

**Issue by cqwuzonglin** [gedoor/legado#4238]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

搜索和书换源时显示的书源异常

### 复现步骤 / How to reproduce

1 Redmi K60E 使用 阅读APP(版本[3.25][3.23.110211])换源时均出现只有两个或三个书源, 但同时我的小米10旧手机能有5-6个书源
2 Redmi K60E 删除部分不常用的书源后 再次换源 发现出现的书源正常了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

Redmi K60E换源时 只显示两个书源就结束搜索了,其他应该正常的书源不会出现

### 阅读版本 / Legado version

3.25,3.23.110211

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60E

**Comment by cqwuzonglin** [comment]
我两个手机是使用的相同的webdav 书源完全相同 但是换源时可选的书源不同

**Comment by 821938089** [comment]
网络相同吗？

**Comment by cqwuzonglin** [comment]
搞错了,有个书源有问题偷偷的修改了书名,造成某些网站能搜到. 那个书源把书名改成了 "我看那本书名" 加空格隔开的一堆书名 长度刚好后边被APP省略了..所以看起来书名一样的 但是换源和搜索效果不一样 要么书名改成滚动显示? 这个逼书源太坏了

**Comment by tyy39** [comment]
哪个书源，让我们避个坑
