### ISSUE TITLE
并不需要这种把书名减少的摆设左右间距[傲慢]请问能去掉么

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#424]
![6be87673071907a80780d1d48d653fca](https://user-images.githubusercontent.com/71624331/96325025-589fd100-1057-11eb-91a7-46cb85b7a861.jpg)
![f1a605a7bf08c56e6e503fa4600f25c7](https://user-images.githubusercontent.com/71624331/96325027-5a699480-1057-11eb-86d9-8b14026de5c9.jpg)
![Screenshot_20201017-085734](https://user-images.githubusercontent.com/71624331/96325029-5c335800-1057-11eb-9a78-15be3b3ea5ee.jpg)
并不需要这种把书名减少的摆设左右间距[傲慢]请问能去掉么

**Comment by gedoor** [comment]
好的
