### ISSUE TITLE
貌似header的js执行有问题

### ISSUE THREAD

**Issue by yolo52** [gedoor/legado#4241]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

同样的漫画源:http://sy.legado1.top/sy.php/b9667132511b581f6e3fef995aa6ab42.json
在之前的版本一直正常，但在3.240725左右之后的版本一直到最新都会有这个问题，在header中执行js会有些没有header头一样，具体不清楚，就是会导致图片访问不了
![Screenshot_20240927_165050](https://github.com/user-attachments/assets/1a3fab18-f9dd-43c7-a7a2-39e588021407)
![Screenshot_20240927_165042](https://github.com/user-attachments/assets/75586519-2e69-43d2-afe0-1dff6d138def)
![Screenshot_20240927_165032](https://github.com/user-attachments/assets/be9f8335-7f14-4484-98b1-312f6d619fef)
![Screenshot_20240927_164908](https://github.com/user-attachments/assets/346d1eca-1dbb-448f-b9dc-7d53ec0bed94)

### 复现步骤 / How to reproduce

上图中正常的是我用3.240622所访问的，其余的从搜索到正文以及日志是在3.24092213测试版访问部分图片均不能加载

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

```java.util.zip.ZipException: incorrect header check
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:184)
	at okio.InputStreamSource.read(SourceFile:41)
	at okio.Buffer.writeAll(SourceFile:10)
	at okio.RealBufferedSource.readByteArray(SourceFile:2)
	at okhttp3.ResponseBody.bytes(SourceFile:16)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.getByteArrayAwait(SourceFile:76)
	at io.legado.app.model.analyzeRule.AnalyzeUrl$getByteArrayAwait$1.invokeSuspend(Unknown Source:11)
	at d9.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.i0.run(SourceFile:125)
	at com.google.common.util.concurrent.w.n(SourceFile:6)
	at com.google.common.util.concurrent.w.run(SourceFile:9)
	at yb.k.run(SourceFile:3)
	at yb.b.run(SourceFile:96)
```

### 阅读版本 / Legado version

3.24092213

### Android版本 / Android version

Android 14

### 机型 / Model

vivo neo3

**Comment by yolo52** [comment]
![Screenshot_20240927_165050](https://github.com/user-attachments/assets/75993fc8-b097-43ab-93da-6b96238acaa6)
![Screenshot_20240927_165042](https://github.com/user-attachments/assets/1c4b69d7-5238-460b-9db6-c23d9ca2ec68)
![Screenshot_20240927_165037](https://github.com/user-attachments/assets/07900589-617e-423a-a69d-3faf5fb11ac2)
![Screenshot_20240927_165032](https://github.com/user-attachments/assets/ccaa7469-27b2-4b32-95e2-dc210c961a28)
![Screenshot_20240927_164908](https://github.com/user-attachments/assets/2d785c83-cb0c-4922-a02e-8c5ea7eebbc2)

**Comment by 821938089** [comment]
已修复，试试最新测试版
