### ISSUE TITLE
legado_app_3.25 apk 包无法下载，解析出现问题

### ISSUE THREAD

**Issue by YasonGF** [gedoor/legado#4246]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

下载legado_app_3.25 apk 包后，手机上无法安装

### 复现步骤 / How to reproduce

略

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

legado_app_3.25

### Android版本 / Android version

android 13

### 机型 / Model

iqoo neo8

**Comment by 821938089** [comment]
挂梯子下载

**Comment by yafovo** [comment]
github访问缓慢，下载东西基本都很慢，也容易出错，我有时候复制地址 用的迅雷在下。

**Comment by xxmyxz** [comment]
要么碰运气，要么改Host文件，要么挂V，要么使用Github的国内镜像，比如把Github换成bgithub.xyz等
