### ISSUE TITLE
书架书名华为手机照样没有显示全书名

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#425]
![Screenshot_20201018-125817](https://user-images.githubusercontent.com/71624331/96359167-fa035180-1141-11eb-89ae-5bcf2e2c9c65.jpg)

**Comment by chenweizi666** [comment]
vivo手机也一样。。搞不懂为何别人手机都可以，不是屏幕大小的问题

**Comment by chenweizi666** [comment]
![Uploading Screenshot_2020_1018_130938.jpg…]()

**Comment by chenweizi666** [comment]
![Screenshot_2020_1018_130938](https://user-images.githubusercontent.com/71624331/96359348-6717e680-1144-11eb-8d9d-0bdb0723cc23.jpg)

**Comment by gedoor** [comment]
好的,我再调下

**Comment by chenweizi666** [comment]
显示名称规则和订阅一样了，4格8个字，但是5月之前的版本，订阅名称可以全部显示，以后的超过8个字就省略

**Comment by chenweizi666** [comment]
> 好的,我再调下

今天更新的版本还没有全显示
