### ISSUE TITLE
测试版web界面看不到书架

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#4261]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

最新测试版使用web界面加载不了书架列表，共存版同样，老版pro正常

### 复现步骤 / How to reproduce

使用Web服务

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.100509

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 pro

**Comment by blackcd318** [comment]
我也遇到这问题了，因为降版本要卸载，就没降级了，先将就着用。
版本是legado_app_3.24.100508，手机是红米k20
