### ISSUE TITLE
legado_app_3.24.101017 版本仍然打不开书架

### ISSUE THREAD

**Issue by blackcd318** [gedoor/legado#4269]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

如题，比1005版本好的是只是没内容，不再是完全空白了

### 复现步骤 / How to reproduce

电脑上浏览器打开/vue/index.html#/ ，内容部分空白
![Uploading 1.png…]()

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.101017

### Android版本 / Android version

Android 12.5

### 机型 / Model

Redmi K20 pro

**Comment by Xwite** [comment]
复现不了，另外截图看不到

**Comment by sky-bbk** [comment]
我也是，书架一本书也没有
![Screenshot_2024-10-12-11-21-24-985_com kiwibrowser browser dev-edit](https://github.com/user-attachments/assets/f9ec26db-4eca-4487-81ff-18b22d585355)

**Comment by Xwite** [comment]
> 我也是，书架一本书也没有 ![Screenshot_2024-10-12-11-21-24-985_com kiwibrowser browser dev-edit](https://private-user-images.githubusercontent.com/70464410/375919779-f9ec26db-4eca-4487-81ff-18b22d585355.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDM3NTQsIm5iZiI6MTcyODcwMzQ1NCwicGF0aCI6Ii83MDQ2NDQxMC8zNzU5MTk3NzktZjllYzI2ZGItNGVjYS00NDg3LTgxZmYtMThiMjJkNTg1MzU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDAzMjQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YzFhNTFmMDMzZTI0NGI2NTY3MGE3OGY4ZjZiODcyNjIzY2I1MjVhODI2MTliYjlhNjA0ODYwOTlhYmE1YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7ttsXZh5SGcWML_LLuwk9oCULXl1Ujy_byxhjSHfO1s)

在上面的搜索栏任意搜索下然后回车/确认

**Comment by adhu2018** [comment]
书架切到“全部”分组，下拉刷新，处理所有出错的书籍，刷新网页

**Comment by zousizhe** [comment]
> 书架切到“全部”分组，下拉刷新，处理所有出错的书籍，刷新网页

如果使用旧版，pro，什么都不做也没问题

**Comment by Xwite** [comment]
复现用的书源和书名都不提供，怎么修复呢

**Comment by zousizhe** [comment]
> 复现用的书源和书名都不提供，怎么修复呢


https://github.com/user-attachments/assets/86463516-eb5a-412d-8923-e7db3c4bf3ac

**Comment by zousizhe** [comment]
> 复现用的书源和书名都不提供，怎么修复呢

搜索完整书名可以显示，不搜索一本看不见

**Comment by Xwite** [comment]
> > 复现用的书源和书名都不提供，怎么修复呢
> 
> 搜索完整书名可以显示，不搜索一本看不见
打开web服务 打开这个
http://localhost:1122/getBookshelf

**Comment by zousizhe** [comment]
> > > 复现用的书源和书名都不提供，怎么修复呢
> > 
> > 
> > 搜索完整书名可以显示，不搜索一本看不见
> 
> 打开web服务 打开这个,贴一下返回值 http://localhost:1122/getBookshelf

可以看到书架配置
![Screenshot_2024-10-12-17-24-14-609_com mmbox xbrowser](https://github.com/user-attachments/assets/62b6fb2b-163d-449b-83d9-864620ac9882)

**Comment by Xwite** [comment]
> > > > 复现用的书源和书名都不提供，怎么修复呢
> > > 
> > > 
> > > 搜索完整书名可以显示，不搜索一本看不见
> > 
> > 
> > 打开web服务 打开这个,贴一下返回值 http://localhost:1122/getBookshelf
> 
> 可以看到书架配置 ![Screenshot_2024-10-12-17-24-14-609_com mmbox xbrowser](https://private-user-images.githubusercontent.com/37259360/375946296-62b6fb2b-163d-449b-83d9-864620ac9882.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjYxMzksIm5iZiI6MTcyODcyNTgzOSwicGF0aCI6Ii8zNzI1OTM2MC8zNzU5NDYyOTYtNjJiNmZiMmItMTYzZC00NDliLTgzZDktODY0NjIwYWM5ODgyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjQyZGMzNWNkODhjYTg0ODBjZWU3NmZlYTczYmY5MTU2OGNjMzQxZGNiZTU1ZjRlNGFiZmYwMmZjNjY0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KYCCjw4lci2IZgLlB8iaq1vWweZQ69x8ykr2XizkPUw)

浏览器内核版本多少，有换过其它浏览器吗？清楚浏览器缓存再试试。
可以考虑提供下书源和书架排除下阅读APP的问题

**Comment by zousizhe** [comment]
> > > > > 复现用的书源和书名都不提供，怎么修复呢
> > > > 
> > > > 
> > > > 搜索完整书名可以显示，不搜索一本看不见
> > > 
> > > 
> > > 打开web服务 打开这个,贴一下返回值 http://localhost:1122/getBookshelf
> > 
> > 
> > 可以看到书架配置 ![Screenshot_2024-10-12-17-24-14-609_com mmbox xbrowser](https://private-user-images.githubusercontent.com/37259360/375946296-62b6fb2b-163d-449b-83d9-864620ac9882.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjYxMzksIm5iZiI6MTcyODcyNTgzOSwicGF0aCI6Ii8zNzI1OTM2MC8zNzU5NDYyOTYtNjJiNmZiMmItMTYzZC00NDliLTgzZDktODY0NjIwYWM5ODgyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjQyZGMzNWNkODhjYTg0ODBjZWU3NmZlYTczYmY5MTU2OGNjMzQxZGNiZTU1ZjRlNGFiZmYwMmZjNjY0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KYCCjw4lci2IZgLlB8iaq1vWweZQ69x8ykr2XizkPUw)
> 
> 浏览器内核版本多少，有换过其它浏览器吗？清楚浏览器缓存再试试。 可以考虑提供下书源和书架排除下阅读APP的问题

试用其他浏览器，webview与独立内核，也在电脑上试过，都不行，使用pro版正常，旧些的测试版都无问题

**Comment by blackcd318** [comment]
> > > > > > 复现用的书源和书名都不提供，怎么修复呢
> > > > > 
> > > > > 
> > > > > 搜索完整书名可以显示，不搜索一本看不见
> > > > 
> > > > 
> > > > 打开web服务 打开这个,贴一下返回值 http://localhost:1122/getBookshelf
> > > 
> > > 
> > > 可以看到书架配置 ![Screenshot_2024-10-12-17-24-14-609_com mmbox xbrowser](https://private-user-images.githubusercontent.com/37259360/375946296-62b6fb2b-163d-449b-83d9-864620ac9882.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjYxMzksIm5iZiI6MTcyODcyNTgzOSwicGF0aCI6Ii8zNzI1OTM2MC8zNzU5NDYyOTYtNjJiNmZiMmItMTYzZC00NDliLTgzZDktODY0NjIwYWM5ODgyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjQyZGMzNWNkODhjYTg0ODBjZWU3NmZlYTczYmY5MTU2OGNjMzQxZGNiZTU1ZjRlNGFiZmYwMmZjNjY0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KYCCjw4lci2IZgLlB8iaq1vWweZQ69x8ykr2XizkPUw)
> > 
> > 
> > 浏览器内核版本多少，有换过其它浏览器吗？清楚浏览器缓存再试试。 可以考虑提供下书源和书架排除下阅读APP的问题
> 
> 试用其他浏览器，webview与独立内核，也在电脑上试过，都不行，使用pro版正常，旧些的测试版都无问题

大概是哪个大神把web服务这部分的代码改了，虽然书架的数据下载到了，但是不解析，只供搜索用。
不过我看的都是些没什么营养的网文，没记这些书的名字。虽然知道了不是什么问题，但觉得页面这么做不怎么友好。

**Comment by blackcd318** [comment]
> > > > > > > 复现用的书源和书名都不提供，怎么修复呢
> > > > > > 
> > > > > > 
> > > > > > 搜索完整书名可以显示，不搜索一本看不见
> > > > > 
> > > > > 
> > > > > 打开web服务 打开这个,贴一下返回值 http://localhost:1122/getBookshelf
> > > > 
> > > > 
> > > > 可以看到书架配置 ![Screenshot_2024-10-12-17-24-14-609_com mmbox xbrowser](https://private-user-images.githubusercontent.com/37259360/375946296-62b6fb2b-163d-449b-83d9-864620ac9882.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjYxMzksIm5iZiI6MTcyODcyNTgzOSwicGF0aCI6Ii8zNzI1OTM2MC8zNzU5NDYyOTYtNjJiNmZiMmItMTYzZC00NDliLTgzZDktODY0NjIwYWM5ODgyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjQyZGMzNWNkODhjYTg0ODBjZWU3NmZlYTczYmY5MTU2OGNjMzQxZGNiZTU1ZjRlNGFiZmYwMmZjNjY0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KYCCjw4lci2IZgLlB8iaq1vWweZQ69x8ykr2XizkPUw)
> > > 
> > > 
> > > 浏览器内核版本多少，有换过其它浏览器吗？清楚浏览器缓存再试试。 可以考虑提供下书源和书架排除下阅读APP的问题
> > 
> > 
> > 试用其他浏览器，webview与独立内核，也在电脑上试过，都不行，使用pro版正常，旧些的测试版都无问题
> 
> 大概是哪个大神把web服务这部分的代码改了，虽然书架的数据下载到了，但是不解析，只供搜索用。 不过我看的都是些没什么营养的网文，没记这些书的名字。虽然知道了不是什么问题，但觉得页面这么做不怎么友好。

legado_app_3.24.10152123版本修复了，结帖
