### ISSUE TITLE
搜索书籍的出现乱码书名！

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#427]
![468cd0b719054624](https://user-images.githubusercontent.com/71624331/96370747-825d1300-1191-11eb-9a35-3ab6883f3bb7.jpg)
搜书列表出现多个乱码书名！

**Comment by chenweizi666** [comment]
![468cd0b719054624](https://user-images.githubusercontent.com/71624331/96371083-a4a36080-1192-11eb-94ff-aaf50be5a88d.jpg)

**Comment by chenweizi666** [comment]
![9ac91d229b670ba](https://user-images.githubusercontent.com/71624331/96371118-c270c580-1192-11eb-8403-8fdbf160772c.jpg)
我

**Comment by Celeter** [comment]
书源问题

**Comment by chenweizi666** [comment]
才不是吧！？

**Comment by zmn001125** [comment]
书源问题

**Comment by Antecer** [comment]
如果确定不是书源问题，你需要按照最新bug模板详细提交问题。
