### ISSUE TITLE
会支持纯血鸿蒙吗

### ISSUE THREAD

**Issue by zZQI** [gedoor/legado#4275]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

会支持纯血鸿蒙系统吗

### 期望实现方式 / How to implement

0

**Comment by joseph-lincc** [comment]
建议关注telegram频道或者群组，现在开始Harmony版阅读Beta测试了，可以去申请一下子

**Comment by loverchun** [comment]
> 建议关注telegram频道或者群组，现在开始Harmony版阅读Beta测试了，可以去申请一下子

请问频道地址是什么？我在简介里加入的频道没看到鸿蒙版的相关消息

**Comment by gujiwuqing** [comment]
> 建议关注telegram频道或者群组，现在开始Harmony版阅读Beta测试了，可以去申请一下子

请问频道地址是什么？我在简介里加入的频道也没看到鸿蒙版的相关消息
