### ISSUE TITLE
web页面只能打开一次

### ISSUE THREAD

**Issue by 281302552** [gedoor/legado#4277]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

手机小米14
使用流量/无线网环境，开启web服务后，浏览器能打开，进入看书页面，但是返回再重新打开的话就不行了，直接访问不通了。
app开启了保持后台运行的。
最新版和安装 旧一些版本一样会这样。

### 复现步骤 / How to reproduce

1.开启web服务；
2.浏览器访问(自带浏览器/夸克均试过)
3.浏览书架，并返回到首页
4.再次点击书架，无反应，网页访问不同，刷新后网页挂掉 

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110115

### Android版本 / Android version

Android  14

### 机型 / Model

小米14

**Comment by Xwite** [comment]
你确定吗?能录个视频看看吗?可以的话看下电脑浏览器控制台信息
