### ISSUE TITLE
增加全书总页码显示：[当前页码]/[总页码]

### ISSUE THREAD

**Issue by simp-lee** [gedoor/legado#4282]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

目前阅读页只能提示当前章节的进度和页数，希望增加 **全书页数** 和 **当前页数**，类似 `[当前页码]/[总页码]` 显示方式。

### 期望实现方式 / How to implement

显示效果：
`[当前页码]/[总页码]` 
`125/986`

**Comment by kehongwei** [comment]
这个怎么说 大佬们给个思路也行啊 我看有的阅读器是可以的。  但是都没咱这个功能全。。
