### ISSUE TITLE
这个PDF翻页错误

### ISSUE THREAD

**Issue by xfdyd** [gedoor/legado#4288]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

这个PDF翻页错误

### 复现步骤 / How to reproduce

一打开就显示了两页，但第二页只显示了一点。但一翻页，就第三页了。
[翻电2.0 C3 论语 E02 何谓礼崩乐坏.pdf](https://github.com/user-attachments/files/17436004/2.0.C3.E02.pdf)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

13

### 机型 / Model

百事乐 L23 Pro

**Comment by hamkido** [comment]
@xfdyd 看了下代码,应该是 pdf 默认翻页方式 index 拿错了
临时解决方案: 打开书籍 -> 界面 -> 翻页动画 -> 滚动
