### ISSUE TITLE
下载规则不触发

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#4290]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

书源里添加了下载链接，但是似乎并不能获取到填入的下载链接，还是会读取目录，然后目录获取失败，想知道是写源码写的有问题吗

### 复现步骤 / How to reproduce

{
  "bookSourceComment": "",
  "bookSourceGroup": "",
  "bookSourceName": "爱去txt论坛",
  "bookSourceType": 0,
  "bookSourceUrl": "http://www.527txt.shop/list.html",
  "bookUrlPattern": "",
  "customOrder": -2,
  "enabled": true,
  "enabledCookieJar": false,
  "enabledExplore": true,
  "exploreUrl": "[{\"title\":\"推荐\",\"url\":\"/list-high-0-{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1}},{\"title\":\"🌸言情\",\"url\":\"/list-1-{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1}},{\"title\":\"穿越重生\",\"url\":\"/list-1-{{page}}.html?label=穿越重生\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"都市校园\",\"url\":\"/list-1-{{page}}.html?label=都市校园\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"玄幻架空\",\"url\":\"/list-1-{{page}}.html?label=玄幻架空\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"古装言情\",\"url\":\"/list-1-{{page}}.html?label=古装言情\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"现代都市\",\"url\":\"/list-1-{{page}}.html?label=现代都市\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"灵异玄幻\",\"url\":\"/list-1-{{page}}.html?label=灵异玄幻\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"仙侠魔幻\",\"url\":\"/list-1-{{page}}.html?label=仙侠魔幻\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"网游竞技\",\"url\":\"/list-1-{{page}}.html?label=网游竞技\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"bg同人\",\"url\":\"/list-1-{{page}}.html?label=BＧ同人\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"🌱耽美\",\"url\":\"/list-2-{{page}}.html\",\"style\":{\"layout_flexBasisPercent\":1}},{\"title\":\"灵异玄幻\",\"url\":\"/list-2-{{page}}.html?label=灵异玄幻\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"现代都市\",\"url\":\"/list-2-{{page}}.html?label=现代都市\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"古装迷情\",\"url\":\"/list-2-{{page}}.html?label=古装迷情\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"穿越重生\",\"url\":\"/list-2-{{page}}.html?label=穿越重生\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"网游竞技\",\"url\":\"/list-2-{{page}}.html?label=网游竞技\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"蕾丝百合\",\"url\":\"/list-2-{{page}}.html?label=蕾丝百合\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"综漫同人\",\"url\":\"/list-2-{{page}}.html?label=综漫同人\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"影视同人\",\"url\":\"/list-2-{{page}}.html?label=影视同人\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"动漫同人\",\"url\":\"/list-2-{{page}}.html?label=动漫同人\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"小说同人\",\"url\":\"/list-2-{{page}}.html?label=小说同人\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"HP同人\",\"url\":\"/list-2-{{page}}.html?label=HP同人\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"历史同人\",\"url\":\"/list-2-{{page}}.html?label=历史同人\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.25}},{\"title\":\"真人同人\",\"url\":\"/list-2-{{page}}.html?label=真人同人\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.4}},{\"title\":\"其他同人\",\"url\":\"/list-2-{{page}}.html?label=其他同人\",\"style\":{\"layout_flexGrow\":1,\"layout_flexBasisPercent\":0.4}}]",
  "lastUpdateTime": 1729268094289,
  "respondTime": 180000,
  "ruleBookInfo": {
    "author": ".pk-text-center.0@text##.*作者：|【\\w*完.*|.*by",
    "canReName": "1",
    "downloadUrls": "",
    "intro": ".readcontent@p:not(:has(a))@html##《.*?》txt全集 作者：.*?【\\w*完结.*?】[ 　]*(?:文案[：: 　])?[ 　]*|《.*?》txt全集 作者：.*?(?=(?:晋江|长佩|豆腐|起点)VIP|七猫中文网)[ 　]*(?:文案[：: 　])?[ 　]*|　　文案：?　　|爱去小说网（www.\\w+\\.\\w+）全力打造最方便的TXT电子书下载网|本书为言情小说站<js>result=result.replace(/[ＢB]/g,\"b\").replace(/Ｇ/g,\"g\").replace(/Ｌ/g,\"l\").replace(/ＣＰ/g,\"cp\")</js>",
    "kind": "",
    "name": ".pk-text-center.0@text##《|》.*",
    "tocUrl": "<js>a=\"http://www.527txt.shop/\"+java.getString(\"@@.readcontent@a@href\");\ndoc=java.ajax(a);\nu=doc.match(/downloadurl = \"([^\"]*)/)[1];\nurl=\"http://www.527txt.shop/\"+String(u);\n</js>"
  },
  "ruleContent": {
    "content": "",
    "replaceRegex": "##推荐一个小说下载必备网址：www.\\w+.com\r\n每天更新，喜欢的去看看。"
  },
  "ruleExplore": {},
  "ruleReview": {},
  "ruleSearch": {
    "author": ".rt@text##.*作者：|【\\w*完.*|.*by",
    "bookList": ".read-list!0",
    "bookUrl": ".rt@a@href",
    "intro": "tag.div.8@text##《.*?》txt全集 作者：.*?【\\w*完结.*?】[ 　]*(?:文案[：: 　])?[ 　]*|《.*?》txt全集 作者：.*?(?=(?:晋江|长佩|豆腐|起点)VIP|七猫中文网)[ 　]*(?:文案[：: 　])?[ 　]*|　　文案：?　　|爱去小说网（www.\\w+\\.\\w+）全力打造最方便的TXT电子书下载网站|本书为言情小说\n<js>result=result.replace(/[ＢB]/g,\"b\").replace(/Ｇ/g,\"g\").replace(/Ｌ/g,\"l\").replace(/ＣＰ/g,\"cp\")</js>",
    "kind": "{{@@a.2@text}},{{@@div.5@text}},{{@@span.-1@text}},{{@@font@color}}\n<js>result=result.replace(/.FF0000/gi,\"荐\").replace(/[ＢB]/g,\"b\").replace(/Ｇ/g,\"g\").replace(/Ｌ/g,\"l\").replace(/ＣＰ/g,\"cp\").replace(/小说|专区|\\u0023000000|.0000FF/g,\"\")</js>",
    "name": ".rt@text##《|》.*"
  },
  "ruleToc": {
    "chapterList": "",
    "chapterName": "",
    "chapterUrl": ""
  },
  "weight": 0
}
是书源，测试下载链接填的<js>a="http://www.527txt.shop/"+java.getString("@@.readcontent@a@href");
doc=java.ajax(a);
u=doc.match(/downloadurl = "([^"]*)/)[1];
url="http://www.527txt.shop/"+String(u);
</js> 因为调试源时不显示下载url也没法判断获取到的是什么值，把这一段放到目录url规则调试http://www.527txt.shop/read-69784-1.html 目录填html时看目录页源码是可以正常加载出下载的全文的，但是把这段放入下载url，在发现里点进去看书阅读就会弹目录列表为空 

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24101521

### Android版本 / Android version

14

### 机型 / Model

小米13

**Comment by 821938089** [comment]
书源类型需要是文件

**Comment by ladia** [comment]
> 书源类型需要是文件

改完确实好了 就是在选择下载在线文件时
![Screenshot_2024-10-20-20-20-06-722_io legado play releaseA-edit](https://github.com/user-attachments/assets/43b181b2-2d5f-4baf-b5a5-81d59b964815)
这里可以在书源里实现规范化命名吗

**Comment by 821938089** [comment]
不能
