### ISSUE TITLE
预下载延迟

### ISSUE THREAD

**Issue by zeng-zijie** [gedoor/legado#4293]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在开启预下载的时候，能够在预下载的章节之间增加一个**用户自定义**的延迟（单位为秒）。希望以此来规避一些书源 检测缓存多个章节 的问题

### 期望实现方式 / How to implement

在预下载章节数 >=1时，增加一个预下载延迟

**Comment by 821938089** [comment]
用并发率
