### ISSUE TITLE
ua优化

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#4294]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

阅读的ua应该是被检测出来了，69书源能用，但打开原网页会被封IP，打开原网页能不能直接用书源的ua，或者阅读这个ua怎么改能改成书源那种形式，现在只能默认用浏览器打开，平白多个跳转
![Screenshot_2024-10-20-17-19-22-730_io legado app releaseA](https://github.com/user-attachments/assets/3012deba-51c1-4a37-a16b-a6d10e2cfa49)

![Screenshot_2024-10-20-17-09-37-999_io legado app releaseA](https://github.com/user-attachments/assets/9c2dc1ff-fa21-4a60-8205-b8caa22d87ad)

### 期望实现方式 / How to implement

阅读时候，点击上方网址跳转原网页，能用书源自带ua，别让网站检测出来用的是阅读
![Screenshot_2024-10-20-17-24-20-808_com coolapk market](https://github.com/user-attachments/assets/ae460891-4300-4e61-9bcd-2d7891fc853a)

**Comment by 821938089** [comment]
这个和UA没关系，是那个x-requested-with请求头的问题，这是webview自动加的，删不掉，只能用外部浏览器打开
