### ISSUE TITLE
在阅读中，符号显示错误

### ISSUE THREAD

**Issue by linghaiyeyingpiao** [gedoor/legado#4302]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

阅读中，符号~显示上横线

### 复现步骤 / How to reproduce

修复一下

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.102422

### Android版本 / Android version

Android11

### 机型 / Model

viovy76s

**Comment by 821938089** [comment]
关净化试试

**Comment by linghaiyeyingpiao** [comment]
一直都是关净化的












灵骸叶影飘
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月22日(周二) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] 在阅读中，符号显示错误 (Issue #4302)




 
关净化试试

**Comment by 821938089** [comment]
那可能是字体问题

**Comment by linghaiyeyingpiao** [comment]
还真是












灵骸叶影飘
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月22日(周二) 下午4:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] 在阅读中，符号显示错误 (Issue #4302)




 
那可能是字体问题
