### ISSUE TITLE
使用web服务, 无法打开书籍

### ISSUE THREAD

**Issue by maudslice** [gedoor/legado#4304]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

使用阅读web服务, 进入书架, 无法打开书架上的书, 抓包显示savebook请求阻塞超时
操作系统: windows11
浏览器: edge 130.0.2849.46

### 复现步骤 / How to reproduce

1. 使用阅读3.25版本 web服务
2. 访问书架
3. 点击任意一本书, 无法打开

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

14

### 机型 / Model

honor 100 pro

**Comment by 821938089** [comment]
用测试版

**Comment by maudslice** [comment]
> 用测试版

我已经装了3.25装不上, 删除会不会把我本地的数据也删了

**Comment by 821938089** [comment]
会的，如果不能删的话就用共存版

**Comment by maudslice** [comment]
唉, 早知道不手贱升级了

**Comment by maudslice** [comment]
> 会的，如果不能删的话就用共存版

使用测试版, edge浏览器依然无法打开书籍, firefox可以, firefox version 131, win10

**Comment by 821938089** [comment]
打开开发工具看看

**Comment by Eyion** [comment]
同为3.25，前两天Chrome打开还是正常的，昨晚就突然出问题了，Edge也同样问题，目前只有Firefox可正常打开。

**Comment by maudslice** [comment]
> 同为3.25，前两天Chrome打开还是正常的，昨晚就突然出问题了，Edge也同样问题，目前只有Firefox可正常打开。

看到你的回复之后我打开测试了一下, 又可以访问了, edge, firefox都可以, 很神秘

**Comment by maudslice** [comment]
关了, 总之不知道发生了什么, 神秘

**Comment by cyitianyou** [comment]
我也遇到了同样的问题 升级后使用Chrome和Edge浏览器无法访问. 看到楼上评论使用Firefox试过确实可以,然后再使用chrome测试也可以正常访问了. 真是个神奇的问题
