### ISSUE TITLE
【新功能讨论】增加连续页面布局

### ISSUE THREAD

**Issue by popyoung** [gedoor/legado#4306]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

现在只有单页或双页布局。能不能做一个连续页面。至少在本地文件上有类似功能。我很不习惯翻页，以前用过的讯飞听书和微信读书都有这个功能。

### 期望实现方式 / How to implement

在现有布局选择的基础上增加连续页面的选择

**Comment by 821938089** [comment]
你是在找滚动翻页吗？

**Comment by popyoung** [comment]
没错，是我没找到这个功能吗？

**Comment by popyoung** [comment]
经你提醒找到了，没想到逻辑层面的设置在ui相关的翻页动画里
