### ISSUE TITLE
阅读Pro两大BUG！我用的是正版未改的阅读pro！一导入背景的地方没有自带壁纸图安卓系统版本8不支持。 导入别人排班没有背景图！

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#431]
阅读Pro两大BUG！我用的是正版未改的阅读pro！一导入背景的地方没有自带壁纸图安卓系统版本8不支持。
![66db888a849a3ad1](https://user-images.githubusercontent.com/71624331/96428024-dd464700-1231-11eb-94b4-32eb94760e18.jpg)

二导入别人排版zip没有背景图！排班数据都在！唯独没有壁纸图显示！我跟我朋友试了一下午，用了三个手机安卓8/9/10。正版未改阅读pro！9导入两次才成功，8/10系统失败。我记得飞哥修复过好几次这个问题。
![27ee4ccfee05f71e](https://user-images.githubusercontent.com/71624331/96428298-2f876800-1232-11eb-8001-326bd02ba197.jpg)
![-5dcbbffce6e2df6e](https://user-images.githubusercontent.com/71624331/96428320-37dfa300-1232-11eb-9036-c6cf4362339c.jpg)
![-1e7926f03d985ac2](https://user-images.githubusercontent.com/71624331/96428346-3f06b100-1232-11eb-9a57-2b5027b9379f.jpg)
![-131327124dc57675](https://user-images.githubusercontent.com/71624331/96428368-4463fb80-1232-11eb-9333-6388c244b91b.jpg)
![-5078c8270e4d2065](https://user-images.githubusercontent.com/71624331/96428385-49c14600-1232-11eb-86f6-9226ed18e3a1.jpg)
![-1993b3b44909310f](https://user-images.githubusercontent.com/71624331/96428413-5180ea80-1232-11eb-9764-0698830cf0d3.jpg)

**Comment by chenweizi666** [comment]
还有酷安的也是不显示阅读自带切换的背景壁纸！安卓八。

**Comment by gedoor** [comment]
奇怪
