### ISSUE TITLE
打包共存版时适用不同的应用名或图标

### ISSUE THREAD

**Issue by THR-hub** [gedoor/legado#4316]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

安装有原版和共存版阅读时二者不好区分，特别是同从其他应用分享或者用阅读打开链接的时候。

### 期望实现方式 / How to implement

打包共存版时把应用名改为 阅读A 阅读共存版 等等名称，或者改为不同的图标

**Comment by yezechuandl** [comment]
图标阅读内自己可更改啊，主题设置里边，有七个图标供选择。

**Comment by THR-hub** [comment]
> 图标阅读内自己可更改啊，主题设置里边，有七个图标供选择。

在MIUI/HyperOS中，更改图标只对桌面有效，绝大多数地方（如分享/用特定应用打开等）还是原始图标，另外好像也有其他厂商也是这样做的，所以这个方法对很多用户无效

**Comment by niu-hb** [comment]
提了pr，不知道会不会通过

**Comment by niu-hb** [comment]
@THR-hub 合并了，最新版名称区分了

**Comment by THR-hub** [comment]
> @THR-hub 合并了，最新版名称区分了

感谢
