### ISSUE TITLE
希望可以出一个阅读服务器版

### ISSUE THREAD

**Issue by flycat233** [gedoor/legado#4317]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

部署到服务器上（最好是WinServer服务器）可以通过web和APP端进行操作，添加、解析书源、实现数据一端部署多端同步的效果，可以自己搭建服务器，看书进度设置之类的可以在服务器上同步，也可以在服务器上解析在传入手机端

### 期望实现方式 / How to implement

开发一个服务端，可以实现阅读的基本功能（书源、订阅、解析、搜索、数据同步、配置文件同步）

**Comment by 821938089** [comment]
有第三方开发的服务器版实现了你想要的部分功能
https://github.com/hectorqin/reader
