### ISSUE TITLE
手机分屏或者小窗口功能使用时，自适应存在问题

### ISSUE THREAD

**Issue by niu-hb** [gedoor/legado#4318]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

手机分屏或者悬浮小窗口功能使用时，下方会有一些文字无法显示出来，是不是窗口高度判断有问题？
![a8c41844d86287f65a10f82f7505d4a](https://github.com/user-attachments/assets/0bfb6f66-072f-43cb-9d29-972fc31b1140)

### 期望实现方式 / How to implement

以前好像是正常的，不知道从什么时候开始出现这种情况。不是必出现，但是出现概率很高。能够优化一下

**Comment by 821938089** [comment]
复现不了，你可以看看有没有开了绘制优化，关掉试试
