### ISSUE TITLE
朗读暂停状态下，系统状态栏显示异常

### ISSUE THREAD

**Issue by Roufoye** [gedoor/legado#4321]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [ ] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在3.25版本中，朗读暂停时，弹出系统状态栏
![Screenshot_2024-11-01-08-14-56-24_90024215e504237c76412be1999ad914](https://github.com/user-attachments/assets/f0c06c56-f849-4522-8f2f-6cde8033e06c)
正常阅读时无异常
![Screenshot_2024-11-01-08-15-05-77_90024215e504237c76412be1999ad914](https://github.com/user-attachments/assets/7bc7412f-8c41-44bb-a4bc-664b0a50bd7f)
在play商店的3.23pro版本中无此现象
![Screenshot_2024-11-01-08-14-05-68_e2ba09773e1c9b06fd122062837b0a0a](https://github.com/user-attachments/assets/a1537ec7-62d1-465d-8825-dfd16115364a)

### 复现步骤 / How to reproduce

点击朗读，然后暂停朗读

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

14

### 机型 / Model

一加9pro

**Comment by 821938089** [comment]
不是bug，弹出菜单的时候会显示状态栏

**Comment by Roufoye** [comment]
> 不是bug，弹出菜单的时候会显示状态栏

3.23版本是没有的，这是新加上的么？

**Comment by 821938089** [comment]
是的
