### ISSUE TITLE
远程书籍(webdav)-文件名不支持中文文件名

### ISSUE THREAD

**Issue by XiePingfan** [gedoor/legado#4324]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

APP版本 3.25
操作路径：[+远程书籍]->列表页中，如果中文文件名，会显示乱码。
文件名看起来是少了调用urldecoder 

### 复现步骤 / How to reproduce

APP版本 3.25
操作路径：[+远程书籍]->列表页中，如果中文文件名，会显示乱码。
文件名看起来是少了调用urldecoder 
![微信图片_20241103172105](https://github.com/user-attachments/assets/c08b32c1-fd7d-4074-b48f-e1c26c691a5f)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android 14

### 机型 / Model

荣耀HONOR 60

**Comment by 821938089** [comment]
你用的是什么webdav？

**Comment by XiePingfan** [comment]
> 你用的是什么webdav？

nginx

**Comment by lededev** [comment]
我的webdav怎么支持中文字符呢，是你自己没配置好服务吧。

**Comment by LeanFly** [comment]
> 我的webdav怎么支持中文字符呢，是你自己没配置好服务吧。

![image](https://github.com/user-attachments/assets/f604c216-e185-40d9-a121-449553bef549)

我使用了 https://github.com/ionelmc/docker-webdav 的镜像搭建，修改了nginx的配置文件，在网页上可以正常显示中文了。
在app配置webdav后显示的内容是经过urlencode处理后的。不知到为啥。

**Comment by 821938089** [comment]
注意浏览器上显示的不是webdav，是另外的index，纯webdav服务浏览器是无法打开索引的

**Comment by 821938089** [comment]
@LeanFly 修复了，试试最新测试版

**Comment by LeanFly** [comment]
> @LeanFly 修复了，试试最新测试版

大佬威武[]()![Screenshot_2024-11-19-13-26-19-666_io.legado.app.releaseA.jpg](https://github.com/user-attachments/assets/f7abe609-dcf7-4e49-bd73-272b29169217)
