### ISSUE TITLE
3.25版本 从搜索书籍界面退出卡死

### ISSUE THREAD

**Issue by jinrikuaile** [gedoor/legado#4335]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [x] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

从搜索书籍界面退出后，软件就会卡死

### 复现步骤 / How to reproduce

点击搜索，然后滑动返回到书架。就会卡死。

使用上滑回到桌面，上滑的瞬间，阅读软件回到搜索界面，就可以动作了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

[Uploading heap-dump-1730721725285.zip…]()

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android 15

### 机型 / Model

vivo x100pro

**Comment by 821938089** [comment]
最新测试版也是这样吗？

**Comment by jinrikuaile** [comment]
> 最新版测试也是这样吗？

是的，我刚刚换了个手机，也是安卓15。3.25也是这样。
测试版是3.24.110412。也是这样。

之前用的3.23不会有这个问题

**Comment by 821938089** [comment]
你把你用的书源发一下看看，可能是里面有个书源有问题

**Comment by jinrikuaile** [comment]
> 你把你用的书源发一下看看，可能是里面有个书源有问题

我刚刚把所有书源删了，也还是这样。只要是通过侧滑返回书架就会卡住。搜索界面左上角的箭头返回就不会卡。

**Comment by jinrikuaile** [comment]
> 你把你用的书源发一下看看，可能是里面有个书源有问题

又试了次，清除软件数据，直接点进去也会这样。

**Comment by jinrikuaile** [comment]
> 你把你用的书源发一下看看，可能是里面有个书源有问题

感觉是不是和安卓15的侧滑返回有冲突。

还有个界面也会这样:
书源管理，右上角分组管理的图标，随便点一个分组，然后侧滑返回。也会卡住

**Comment by 821938089** [comment]
重启下手机试试

**Comment by jinrikuaile** [comment]
> 重启下手机试试

我两个手机都这样。
一个vivo x100pro，系统是安卓15的 originos5。
一个是一加7pro ，系统是类原生的 yaap 安卓15。重启没效果的

**Comment by jinrikuaile** [comment]
> 重启下手机试试

[log.txt](https://github.com/user-attachments/files/17619313/log.txt)
我用adb抓了log。
不知道是不是这个报错导致的：

11-04 22:07:06.212 W/InputDispatcher( 1539): Not sending touch gesture to bbc3eef ActivityRecordInputSink io.legado.app.release/io.legado.app.ui.main.MainActivity because it has config NO_INPUT_CHANNEL

**Comment by jinrikuaile** [comment]
> 重启下手机试试

再补充一个：把系统导航模式从手势导航换成三按钮导航，用按键返回，也不会触发这个bug

**Comment by 821938089** [comment]
修复了，试试最新测试版

**Comment by jinrikuaile** [comment]
> 修复了，试试最新测试版

测试版可以了。

**Comment by jinrikuaile** [comment]
测试版已修复，希望尽快加入正式版更新
