### ISSUE TITLE
蓝牙耳机连接听书短句无声.

### ISSUE THREAD

**Issue by iamiis** [gedoor/legado#4336]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

阅读在连接蓝牙设备听书的时候,短句(3字以下)会不读,调慢语速可以解决,猜测可能语音过短触发蓝牙的静音机制有关.已尝试更换蓝牙协议及各种蓝牙设置无效.
我知道这与阅读本身没什么关系,现在是单行发送的,能否请帮忙在阅读软件里面增加多行发送选项,可以暂时避过这个.

### 复现步骤 / How to reproduce

用系统tts或者mulittts朗读,连接蓝牙耳机或者音箱,只要正常语速,文章中有少于2字的短句,大概率会复现.

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

14

### 机型 / Model

redmi note12t

**Comment by 821938089** [comment]
你可以用替换净化将短段落合并一下

**Comment by sc104501** [comment]
https://github.com/sc104501/legado
@iamiis 我也是这个问题，自己魔改了一次三行的（至少也有三个字），会编译的话你自己编译一下。
