### ISSUE TITLE
请求提供HomoneyOS Next版本的阅读

### ISSUE THREAD

**Issue by locis08** [gedoor/legado#4339]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

阅读APP的多年老用户，付费支持过几次，现在手里的华为手机升级到HomoneyOS Next系统了，原来的阅读不能用了，哭求提供HomoneyOS Next版本的阅读

### 期望实现方式 / How to implement

提供HomoneyOS Next版本的阅读APP

**Comment by yafovo** [comment]
你可以试一下喵公子的鸿蒙版本，
是否好用  我就不知道了。

**Comment by zqyltx2008** [comment]
> 你可以试一下喵公子的鸿蒙版本， 是否好用 我就不知道了。

喵公子的鸿蒙版本在哪里 能否提供一下地址
