### ISSUE TITLE
备份恢复失败

### ISSUE THREAD

**Issue by starroikai** [gedoor/legado#4342]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

从3.24.08071917备份数据后，安装3.25，备份恢复失败，仅能恢复阅读主题和订阅源，书架和书源均无法恢复。
backup压缩包里面的文件挨个尝试后，发现有几个.json文件一打开就显示格式错误
[backup.zip](https://github.com/user-attachments/files/17676864/backup.zip)
有什么方法能打开这几个格式错误的文件

### 复现步骤 / How to reproduce

书都没了，只剩下这个备份文件了。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.08071917

### Android版本 / Android version

harmonyos4.2.0.213

### 机型 / Model

MatePad 11

**Comment by starroikai** [comment]
应该是从beat版备份的

**Comment by 821938089** [comment]
备份里面没有书架和书源的json文件

**Comment by starroikai** [comment]
寄
