### ISSUE TITLE
阅读应用在originos5系统中无法使用

### ISSUE THREAD

**Issue by sanqiaixiayu** [gedoor/legado#4344]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

无法加载新章节，并且非常卡，手机发热，右下角显示1/0

### 复现步骤 / How to reproduce

更新orginos5后打开阅读应用

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.090312

### Android版本 / Android version

Android 15

### 机型 / Model

iqooneo9pro

**Comment by 821938089** [comment]
更新最新测试版试试

**Comment by sanqiaixiayu** [comment]
> 更新最新版试试

还是一样，一打开就疯狂发热

**Comment by shookgao** [comment]
我的X200PRO用3.25版本没这个问题
