### ISSUE TITLE
阅读页面的自定义背景文字布局等等能否加个指定书源类型的功能

### ISSUE THREAD

**Issue by RejectVanity** [gedoor/legado#4362]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在自定义阅读页面的文字颜色和背景，布局等，能否加个指定特定类型的书源生效？

这个功能在有同时阅读小说和浏览漫画的情况下非常便利。

### 期望实现方式 / How to implement

可以在自定义背景图的页面加上选择选项，以应用于特定类型的书源。

主要是图片类型和文本类型

**Comment by a534008561** [comment]
阅读本来就有，界面哪里你可以，储存多个布局，![IMG_20241120_215755.jpg](https://github.com/user-attachments/assets/3acb6b4a-cd68-4321-aa7f-52a0e2ba4f0e)
