### ISSUE TITLE
下载缓存的书籍web需要同步到另外的设备（电纸书）

### ISSUE THREAD

**Issue by yeweiyuni** [gedoor/legado#4366]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

在下载缓存中可以选择导出到webdav,但只是备份到云端，即无法重新同步到本地，也不能同步到另外的设备。
在使用电纸书时WiFi下观看耗电快，如果可以直接同步一些别的设备上传的本地缓存，就很方便了。

查看webdav空间知，导出已经上传，但却无法同步下载到本地。

### 期望实现方式 / How to implement

希望可以将导出到云端的缓存直接备份到压缩包，就可以直接恢复了

**Comment by 821938089** [comment]
你先缓存好再把WiFi关了看

**Comment by yeweiyuni** [comment]
现在就是这么看的，但有一些小麻烦，有时要翻墙，而且电纸书处理的慢，换源也慢。一些源还容易崩。
