### ISSUE TITLE
请求头搜索数据传递错误

### ISSUE THREAD

**Issue by ladia** [gedoor/legado#4369]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

https://search.yanxuan.org/indexes/yanxuan/search,{
	 "headers": "{Authorization:'Bearer e369a1a3b41676085bf3c8b4d2f7306bd09e30560ec352a74fe91c3fe7602ec4'}",
  "method": "POST",
  "body": {"q": "{{key}}","attributesToHighlight": ["*"],"attributesToCrop": ["content"],"cropLength": 30}
}这样写搜索会报错{"message":"Invalid value type at `.cropLength`: expected a positive integer, but found a number: `30.0`","code":"invalid_search_crop_length","type":"invalid_request","link":"https://docs.meilisearch.com/errors#invalid_search_crop_length"}

### 复现步骤 / How to reproduce

似乎传递的json数据自动把数字转成浮动类型

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

把搜索改成这样@js:url = "https://search.yanxuan.org/indexes/yanxuan/search," + JSON.stringify({
  "method": "POST",
  "body": JSON.stringify({
    "q": key,
    "attributesToHighlight": ["*"],
    "attributesToCrop": ["content"],
    "cropLength": 30
  }),
  "headers": {
    "Authorization": "Bearer e369a1a3b41676085bf3c8b4d2f7306bd09e30560ec352a74fe91c3fe7602ec4"
  }
});又能正确解析成30，不知道是不是bug

### 阅读版本 / Legado version

3.24.112016

### Android版本 / Android version

13

### 机型 / Model

小米13

**Comment by 821938089** [comment]
body是json对象时在反序列化时整数会变成浮点，传字符串不会反序列化json，所以没问题
最新测试版修复了，你可以试试
