### ISSUE TITLE
刷新分组时分类没有更新

### ISSUE THREAD

**Issue by huajideshutiao** [gedoor/legado#4374]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

我在更新前js preUpdateJs 中测试了java.refreshTocUrl()和java.refreshBook() ，刷新分组后进入书籍详情页发现分类 kind 并没有更新，详情页下拉是能自动更新的

### 复现步骤 / How to reproduce

如上

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.112312

### Android版本 / Android version

Android 14

### 机型 / Model

redmi k70 pro

**Comment by 821938089** [comment]
发书源看看

**Comment by huajideshutiao** [comment]
> 发书源看看

省流，kind用了js

[源.json](https://github.com/user-attachments/files/17892907/default.json)

**Comment by huajideshutiao** [comment]
> 修复了，试试最新测试版

确实好了，感谢❤️

**Comment by huajideshutiao** [comment]
> 修复了，试试最新测试版

顺便问个问题，目前书源中有办法在书籍添加到书架后触发什么操作吗？

**Comment by 821938089** [comment]
没有
