### ISSUE TITLE
webview能跟着主题自动变化吗？

### ISSUE THREAD

**Issue by niu-hb** [gedoor/legado#4382]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

书籍阅读界面打开源网页，或者rss页面都是webview展示的。大晚上的还是白色背景很晃眼，能不能跟着app的设置走，自动变化明暗背景。最好所有地方都调整下

### 期望实现方式 / How to implement

根据app的主题模式自动变化

**Comment by 821938089** [comment]
可以的，不会变的话大概是webview不支持吧
也有可能是网页问题

**Comment by niu-hb** [comment]
app功能上是支持的，但是要看webview和网页的支持？
那好吧
