### ISSUE TITLE
特定格式的段落文字转码后丢失

### ISSUE THREAD

**Issue by Aye111111** [gedoor/legado#4402]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

![微信图片_20241205121919](https://github.com/user-attachments/assets/ceb23e6f-0ac4-4ec3-857d-8fa297766806)
![微信图片_20241205121911](https://github.com/user-attachments/assets/e226ac07-e05f-441d-8e64-2a9ccc131e5e)

上图中圈选的段落在转码后丢失，这个书源的所有书每一章开头都是这样没有缩进的段落，全部都丢失，已确认非替换净化导致，关闭替换净化仍然缺失这一段。由于目前能用的书源已经极少，69shuba.cx基本已经是硕果仅存了，此问题影响还是比较大的

### 复现步骤 / How to reproduce

使用69书吧的源,69shuba.cx，任意打开一本书，对比网页版的内容，都会看到每一章第一段文字丢失

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

鸿蒙4.2

### 机型 / Model

华为P40

**Comment by 821938089** [comment]
规则写的不对
正文规则填这个 `.txtnav@html`

**Comment by Aye111111** [comment]
> 规则写的不对 正文规则填这个 `.txtnav@html`

感谢，解决了
