### ISSUE TITLE
阅读本地epub文件时出现缺少插图的情况

### ISSUE THREAD

**Issue by MacaronUwU** [gedoor/legado#4407]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在打开以下以下这份类似的epub时，legado不会加载封面与插图中的图片，仅留下空白章节，而在其他阅读器下显示正常，暂不清楚为何导致的。
[Silent Witch 沉默魔女的秘密 - 01.zip](https://github.com/user-attachments/files/18032284/Silent.Witch.-.01.zip)

### 复现步骤 / How to reproduce

导入附录小说就会产生上述问题

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android 14

### 机型 / Model

Xiaomi 14

**Comment by 821938089** [comment]
修复了，试试最新测试版

**Comment by MacaronUwU** [comment]
感谢开源大佬:)
