### ISSUE TITLE
更新之前 JS（preUpdateJs）有时不可用

### ISSUE THREAD

**Issue by huajideshutiao** [gedoor/legado#4416]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

如果通过添加网址将书籍添加到书架，更新之前 JS（preUpdateJs）中的内容不会被执行

### 复现步骤 / How to reproduce

更新之前 JS（preUpdateJs）
book.canUpdate=false

如上操作后，刷新书架后属于对应源的书籍依旧会刷新，而从搜索或者发现页点进去添加书架的书籍没有这个问题

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.120615

### Android版本 / Android version

Android 15

### 机型 / Model

redmi k70 pro

**Comment by 821938089** [comment]
preUpdateJs 有些地方不会执行，你再刷新一次书架应该会执行吧
另外不推荐修改变量，这些变量给你是用来读取一些可能需要的信息的

**Comment by huajideshutiao** [comment]
> preUpdateJs 有些地方不会执行，你再刷新一次书架应该会执行吧 另外不推荐修改变量，这些变量给你是用来读取一些可能需要的信息的

因为我是通过添加网址直接导入的，又因为默认刷新书架不刷新详情页，所以必须到书籍详情页刷新一下才能执行book.canUpdate=false
至于变量问题，因为源站容易封控而书籍信息基本是不变的(包括详情页和目录url，除了正文页面源码会变)，保险起见就设置不更新书籍了

**Comment by huajideshutiao** [comment]
> preUpdateJs 有些地方不会执行，你再刷新一次书架应该会执行吧 另外不推荐修改变量，这些变量给你是用来读取一些可能需要的信息的

然后还有个小问题，如果添加书架之后不点进详情页就直接刷新了书架，再进详情页会显示下图，实际上目录是有列表的
![Screenshot_2024-12-08-16-08-50-085_io legado app release](https://github.com/user-attachments/assets/a0ed5306-f229-4be2-ba86-34b9659aae28)

**Comment by 821938089** [comment]
我看了下代码，这个应该实际有执行的，但是canUpdate属性会同步数据库里的数据时又会改回去，所以没变

**Comment by 821938089** [comment]
章节列表里没有null章节吗？
你发下书源吧

**Comment by huajideshutiao** [comment]
> 章节列表里没有null章节吗？ 你发下书源吧

http://shuyuan.cloudepay.cc/shuyuan/f6140ab0065c6655.json

**Comment by huajideshutiao** [comment]
> 章节列表里没有null章节吗？ 你发下书源吧

等下，这个书源要账号的，我处理一下

**Comment by huajideshutiao** [comment]
> 章节列表里没有null章节吗？ 你发下书源吧

http://shuyuan.cloudepay.cc/shuyuan/d178941de674600a.json
这个应该可以不登陆就测试

**Comment by 821938089** [comment]
用不了

**Comment by huajideshutiao** [comment]
> 用不了

忘记说了，这个要开梯子的，如果e-hentai.org网页能访问而源不行，等我改一下

**Comment by 821938089** [comment]
不用了，我用别的源复现了

**Comment by huajideshutiao** [comment]
> 不用了，我用别的源复现了

刚才才看到，停电没网了说是

**Comment by 821938089** [comment]
修复了，试试最新测试版

**Comment by huajideshutiao** [comment]
> 修复了，试试最新测试版

确实，能正确显示第一个章节了
不过book.canUpdate=false似乎还是那样

**Comment by 821938089** [comment]
这个修不了，判断不了这个值哪个新哪个旧

**Comment by huajideshutiao** [comment]
> 这个修不了，判断不了这个值哪个新哪个旧

行吧，我直接批量操作了。也算小问题，除了导入链接能遇到其他情况正常
