### ISSUE TITLE
一个书源有一本无法打开的书

### ISSUE THREAD

**Issue by Gslw** [gedoor/legado#4418]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

就是能搜索到，能进详情页，正文就是加载不了，但是点击上面那个网络连接是可以的。同一个书源的其他书可以阅读正文。

### 复现步骤 / How to reproduce

就添加书架之后，点击打开阅读正文

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

正文报错：
OutOfMemoryError thrown while trying to throw an exception; no stack trace available

可能崩溃，如果崩溃日志如下：
SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; V2352A Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.107 Mobile Safari/537.36
MODEL=V2352A
RELEASE=14
packageName=io.legado.app.release
MANUFACTURER=vivo
versionName=3.24.112521
versionCode=15818
BRAND=vivo
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at io.legado.app.help.http.f0@f6c2c42]){Completed}@3972453. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.i0.f(SourceFile:40)
	at kotlinx.coroutines.i0.run(SourceFile:197)
	at com.google.common.util.concurrent.w.n(SourceFile:6)
	at com.google.common.util.concurrent.w.run(SourceFile:9)
	at zb.k.run(SourceFile:3)
	at zb.b.run(SourceFile:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [kotlinx.coroutines.e2@c14ca8e, d2{Active}@265b2af, Dispatchers.IO]
Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available

### 阅读版本 / Legado version

最新测试版

### Android版本 / Android version

安卓14

### 机型 / Model

iQOO Z9 turbo

**Comment by 821938089** [comment]
安装最新测试版，在其他设置里打开记录堆转储，复现崩溃后去关于那里点保存日志，然后去备份目录里将heapDump文件夹里的文件打包压缩一下上传上来
