### ISSUE TITLE
备份与恢复设置有问题

### ISSUE THREAD

**Issue by moumouye** [gedoor/legado#4438]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

备份路径、备份都要先进行选择文件夹，但实际上已经不可用。data下找legado相关的文件夹。已经明确相关数据就是放那里
![1734236613154_d](https://github.com/user-attachments/assets/b9ac3746-b922-4015-8023-7f1776641436)

### 复现步骤 / How to reproduce

![1734236496035_d](https://github.com/user-attachments/assets/d2f0e5d0-71c6-4b96-886b-321677add411)

![1734235633889_d](https://github.com/user-attachments/assets/ea90c221-22fd-4df6-bf03-b2bdc713b648)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

14

### 机型 / Model

小米6spro、荣耀X50

**Comment by 821938089** [comment]
不要放这里，这里是app的数据目录，高版本安卓是访问不了的，你自己建一个目录放
