### ISSUE TITLE
书名显示何时不用省略号代替？安卓8bc文件夹的壁纸何时可以能用！？

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#445]
书名显示何时不用省略号代替？拜托屏幕的限制，6寸屏幕就九个字。安卓系统8改字体颜色地方bc文件夹的壁纸何时可以能用！？暗黑主题下，能否导入壁纸成功？

**Comment by gedoor** [comment]
这个里手机字太大没办法,可以用列表啊,两行已经不少了,行数太多难看

**Comment by gedoor** [comment]
壁纸问题下版本修复
