### ISSUE TITLE
允许订阅源添加到书架

### ISSUE THREAD

**Issue by huajideshutiao** [gedoor/legado#4450]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

订阅源自己的收藏太麻烦了，不如直接和书架合并

### 期望实现方式 / How to implement

就想普通的书籍那样能管理分组啥的，不过点进去就直接是订阅源的界面

**Comment by niu-hb** [comment]
订阅源有分组功能，页面布局和书籍是不一样的，不太可能重构，工作量估计会很大。

**Comment by huajideshutiao** [comment]
> 订阅源有分组功能，页面布局和书籍是不一样的，不太可能重构，工作量估计会很大，而且也不是很有必要吧

其实还好，虽然订阅源有分组，但是书架也有啊，至于布局，就用书籍的就好。
至于必要性，其实还挺有用的，因为现在的收藏藏得有点深

**Comment by huajideshutiao** [comment]
好像没啥用
