### ISSUE TITLE
夜间模式下阅读界面状态栏显示黑色看不清内容

### ISSUE THREAD

**Issue by GitHub-T4** [gedoor/legado#4453]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

阅读界面通过菜单开启夜间模式，状态栏时间信号通知等图标变成深色，此时背景色也是深色时会导致状态栏全是黑色看不清内容。但是唤出菜单栏时状态栏时间信号通知等图标自动变回浅色，内容清晰可见。夜间模式下软件其他界面状态栏都是浅色，只有阅读界面显示异常。
希望能修复一下
![Screenshot_20241221_232818](https://github.com/user-attachments/assets/3bd04406-6a7f-45ec-9cd5-f0ba79b6238c)
![Screenshot_20241221_232811](https://github.com/user-attachments/assets/c620364b-e564-4113-a2ca-62177e28f2b0)

### 复现步骤 / How to reproduce

阅读界面开启模式，状态栏时间信号通知等图标自动变成深色，背景色同为深色导致看不清状态栏内容

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android14

### 机型 / Model

vivo X100

**Comment by 821938089** [comment]
文字颜色和背景里面可以设置

**Comment by GitHub-T4** [comment]
> 文字颜色和背景里面可以设置

破案了，是我设置的问题😂，把深色状态栏关掉就好了
舒服了，舒服了☺️
![IMG_20241222_170915](https://github.com/user-attachments/assets/61120cdd-f9d8-4574-b625-ed718c0b2f44)
