### ISSUE TITLE
界面适配问题

### ISSUE THREAD

**Issue by yolo52** [gedoor/legado#4469]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

其一，目录页的volume标识后文字在框框中偏上，emm，对我这强迫症属实是有点点难受了，可以优化下像不使用volume的一样放在正中嘛。
其二，希望对登录UI可以添加style属性或者插入js或者可以直接填一个参数用于一排放几个按钮这样子。
其三，那个新添加的章节字数功能，希望添加一个可以自行选择打开或关闭的按钮

### 期望实现方式 / How to implement

第一个可能是界面适配问题，第二个换字体或者换一个设备展示出来的就不一样了，希望可以添加，第三个添加个开关最好

### 附加信息 / Additions

以上功能均不强求，有点算个人需求(所以麻烦的话就回复一下我直接关了就行)

**Comment by niu-hb** [comment]
3加了开关，其他两个我无能为力，等其他人处理吧

**Comment by 821938089** [comment]
都优化了，试试最新测试版

**Comment by Sun-QAQ** [comment]
> 都优化了，试试最新测试版

登录UI这里都加了啥属性呢？要不在帮助文档里面写一下？

**Comment by 821938089** [comment]
和发现规则一样

**Comment by yolo52** [comment]
> 都优化了，试试最新测试版

已测试，非常好用，万分感谢大佬

**Comment by yolo52** [comment]
> 3加了开关，其他两个我无能为力，等其他人处理吧

好的好的，感谢大佬

**Comment by miss0701** [comment]
> 和发现规则一样
> 
> 已更新帮助文档

非常好用 感谢大佬 终于不用空格大法排版了
