### ISSUE TITLE
漫画间距问题

### ISSUE THREAD

**Issue by sky-bbk** [gedoor/legado#4471]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No related requests

### 功能描述 / Features

看漫画时得先切换到自己设置的漫画布局，不然就会有大黑边（段距的问题），看完漫画又去看小说还得再切换回来，每次都要多点4下。所以希望看漫画时能自动设置段距为0

网友提过的类似的建议：#1651   #1703  #4096

### 期望实现方式 / How to implement

方式一：阅读时自动检测该书类型，如果为漫画就临时设置段距为0.
方式二：对某一分组/书架 采用相同布局，一键设置此分组布局，并且新加入的书自动应用此布局
方式三：针对某本书可单独设置布局

**Comment by niu-hb** [comment]
方式1好实现，但是不一定所有人都想要这样设置吧。

**Comment by sky-bbk** [comment]
可以加个开关，漫画间距自动调整，自己输入间距就行

**Comment by sky-bbk** [comment]
可以了，非常感谢大佬。实际使用中发现，要实现沉浸式阅读漫画，正文的左右边距也要设置为0,不知道能不能和段距一并设置。当然如果大佬觉得没必要或者不好实现就算了，目前段距为0已经很满意了

**Comment by niu-hb** [comment]
> 可以了，非常感谢大佬。实际使用中发现，要实现沉浸式阅读漫画，正文的左右边距也要设置为0,不知道能不能和段距一并设置。当然如果大佬觉得没必要或者不好实现就算了，目前段距为0已经很满意了

我换个方式，再改改

**Comment by niu-hb** [comment]
漫画和书籍的布局分开了，打开时会自动切换对应布局。

**Comment by sky-bbk** [comment]
感谢大佬，辛苦了。目前还有点小问题，书的布局和漫画的布局都设置好后，从一种切换到另一种，布局方案会自动切换，但是布局的参数（字体大小、行距段距等）不会自动切换，这时候随便调整一下参数才切换过来

**Comment by niu-hb** [comment]
提交了，过几分钟试试最新的版本

**Comment by sky-bbk** [comment]
ok完美了，非常感谢您的付出

**Comment by lhjgege** [comment]
请问这个是在哪里设置，我没有找到，老是看漫画图片之间有间隔

**Comment by sky-bbk** [comment]
选择一个单独的布局作为漫画专用布局，然后把段距调整为0,其他参数也可以适当调整。漫画布局和小说要分开设置，阅读会记忆你看小说和漫画各自用的哪个布局
