### ISSUE TITLE
提交参数的编码

### ISSUE THREAD

**Issue by lemon-xxy** [gedoor/legado#448]
上次提的gbk编码的urlencode方法什么时候能实现啊？

**Comment by gedoor** [comment]
加了啊,java.utf8ToGbk("")

**Comment by lemon-xxy** [comment]
好吧  没在更新说明中看到  我以为没加:)

**Comment by lemon-xxy** [comment]
> 加了啊,java.utf8ToGbk("")

看了一下不是我说的那个方法啊  我是要

fun encodeURI(str: String): String {
        return try {
            URLEncoder.encode(str, "UTF-8")//把utf-8换成gbk
        } catch (e: Exception) {
            ""
        }
    }

**Comment by gedoor** [comment]
fun encodeURI(str: String, enc: String): String {
        return try {
            URLEncoder.encode(str, enc)
        } catch (e: Exception) {
            ""
        }
    }

**Comment by gedoor** [comment]
下版本

**Comment by lemon-xxy** [comment]
> 下版本

好的谢谢
