### ISSUE TITLE
布局切换问题，当前按照书源分类来分了，但是未加入书架时阅读会按照小说类型来走

### ISSUE THREAD

**Issue by Sun-QAQ** [gedoor/legado#4481]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

如题
在发现或搜索中阅读未加入书架的书籍时，会默认走小说类型的布局走，麻烦老师看看。@niu-hb

### 复现步骤 / How to reproduce

在发现或搜索中，阅读书源为图片类型的书籍。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.123011

### Android版本 / Android version

android 14

### 机型 / Model

oppo

**Comment by 821938089** [comment]
更新最新测试版

**Comment by Sun-QAQ** [comment]
> 更新最新测试版

大佬效率这么高
