### ISSUE TITLE
看部分书源小说内容一直加载中。最近三个版本都这样。

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#449]
看部分书源小说内容一直加载中。最近三个版本都这样。换来换去！不管怎么样都在加载中！过了很久小说内容不出来
![Screenshot_20201030-094208](https://user-images.githubusercontent.com/71624331/97650499-c7881b80-1a94-11eb-8133-c823f1aaae94.jpg)
![Screenshot_20201029-134357](https://user-images.githubusercontent.com/71624331/97650528-d8389180-1a94-11eb-8bcc-fd2aeb2d3632.jpg)
![Screenshot_20201029-134439](https://user-images.githubusercontent.com/71624331/97650541-dec70900-1a94-11eb-8245-f2c85949038a.jpg)
![Screenshot_20201029-134502](https://user-images.githubusercontent.com/71624331/97650542-e2f32680-1a94-11eb-8d1b-9cfa64ee1380.jpg)

**Comment by chenweizi666** [comment]
![Screenshot_20201030-094947](https://user-images.githubusercontent.com/71624331/97650756-6dd42100-1a95-11eb-8ea2-a4517cd8205e.jpg)
![Screenshot_20201030-095006](https://user-images.githubusercontent.com/71624331/97650757-6f054e00-1a95-11eb-8688-f20f9817807e.jpg)
![Screenshot_20201030-095053](https://user-images.githubusercontent.com/71624331/97650760-6f9de480-1a95-11eb-942e-54e78df1475a.jpg)

**Comment by chenweizi666** [comment]
![Screenshot_20201030-095423](https://user-images.githubusercontent.com/71624331/97651016-023e8380-1a96-11eb-9f4d-cdb48c0bfb5f.jpg)
![Screenshot_20201030-095428](https://user-images.githubusercontent.com/71624331/97651025-04084700-1a96-11eb-8488-997e1bdab1d3.jpg)
![Screenshot_20201030-095447](https://user-images.githubusercontent.com/71624331/97651032-05397400-1a96-11eb-8e5b-37a2d0cfe78a.jpg)

**Comment by gedoor** [comment]
提供下书源,我测试一下

**Comment by haxc** [comment]
https://pasteme.cn/62021
这个源，在093018版中正常，可以加载目录出来，在最近的几个
> 提供下书源,我测试一下

**Comment by haxc** [comment]
在最近的几个版本加载不了目录了

**Comment by gedoor** [comment]
"chapterList": ".jogger2@tag.li.!0:1:-1@a"
改成
"chapterList": ".jogger2@tag.li!0:1:-1@a",
取所有不需要加点

**Comment by chenweizi666** [comment]
> 提供下书源,我测试一下
飞言情和海棠官方正版源 这两个是我试了很多版本！
https://pasteme.cn/62070

https://pasteme.cn/62072

**Comment by gedoor** [comment]
更新了一下可以了
