### ISSUE TITLE
更新版本还是小说内容加载中！

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#451]
![Screenshot_20201030-213227](https://user-images.githubusercontent.com/71624331/97713568-fa64fa80-1afa-11eb-8753-ef43957a24ed.jpg)
![Screenshot_20201030-213132](https://user-images.githubusercontent.com/71624331/97713579-fe911800-1afa-11eb-9157-8425748f867b.jpg)
![Screenshot_20201030-212342](https://user-images.githubusercontent.com/71624331/97713588-ffc24500-1afa-11eb-8cff-98dab70efb21.jpg)
华为8*10/11小说内容还是加载中。刚刚更新！还是不行。。更新29还是28号的版本就开始。。为撒华为系统跟阅读总是过不去。。！！？我两个网友也是这个问题。。搞不明白！不管怎么刷新缓存就是不能看。。

**Comment by gedoor** [comment]
我再看看

**Comment by gedoor** [comment]
我手机上测试了正常啊

**Comment by chenweizi666** [comment]
> 我手机上测试了正常啊

我也抓狂！为撒华为的系统！总是bug层出不穷！就是加载中。。

**Comment by chenweizi666** [comment]
> 我手机上测试了正常啊

闪退啦了！用了今天九点的共存版！还是加载中。。。

**Comment by chenweizi666** [comment]
> 我手机上测试了正常啊

![Screenshot_20201031-104209](https://user-images.githubusercontent.com/71624331/97769554-ebb42d00-1b66-11eb-9877-815f53bfd6ad.jpg)

**Comment by Antecer** [comment]
我试了下，这个网站打开很慢，可能你这个源已经挂了。
