### ISSUE TITLE
闪退加加载中加目录半天不出来不是一个源这样！

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#452]
![Screenshot_20201031-124443](https://user-images.githubusercontent.com/71624331/97771394-6d13bb80-1b77-11eb-91c5-61969ee63b53.jpg)
![Screenshot_20201031-124630](https://user-images.githubusercontent.com/71624331/97771396-6f761580-1b77-11eb-8548-3fdfa088443c.jpg)
![Screenshot_20201031-124639](https://user-images.githubusercontent.com/71624331/97771399-70a74280-1b77-11eb-84fc-ab88020ef193.jpg)

**Comment by chenweizi666** [comment]
![-355a3a718c501f45](https://user-images.githubusercontent.com/71624331/97771441-f62af280-1b77-11eb-9b1e-7ef6693574dd.jpg)
vivo手机也这样。。

**Comment by chenweizi666** [comment]
![Screenshot_20201031-130931](https://user-images.githubusercontent.com/71624331/97771856-2a081700-1b7c-11eb-8ed0-d06439446738.jpg)
![Screenshot_20201031-131506](https://user-images.githubusercontent.com/71624331/97771859-2e343480-1b7c-11eb-8f8f-808bc0fbcfa3.jpg)
新18和若尘还是一个能看小说打开目录的。为什么两个手机都是加载慢不出来
![Screenshot_20201031-131535](https://user-images.githubusercontent.com/71624331/97771869-45732200-1b7c-11eb-8b51-14cdd452694b.jpg)
![Screenshot_20201031-131707](https://user-images.githubusercontent.com/71624331/97771870-473ce580-1b7c-11eb-80be-bf8a46a12623.jpg)

**Comment by gedoor** [comment]
安卓版本多少,我看看是不是升级了SDK30的原因

**Comment by chenweizi666** [comment]
> 安卓版本多少,我看看是不是升级了SDK30的原因

![Screenshot_20201101-150316](https://user-images.githubusercontent.com/71624331/97796968-63f81c80-1c53-11eb-835f-7f3c09b90950.jpg)
华为安卓8

**Comment by chenweizi666** [comment]
> 安卓版本多少,我看看是不是升级了SDK30的原因

![IMG_20201101_151845](https://user-images.githubusercontent.com/71624331/97797238-6dcf4f00-1c56-11eb-8238-115edfced23b.jpg)
vivo手机的版本两个手机都是这个情况
