### ISSUE TITLE
epub本地书籍显示有问题

### ISSUE THREAD

**Issue by Xumingyan** [gedoor/legado#454]
![Screenshot_20201031-232054_Legado](https://user-images.githubusercontent.com/29301453/97783209-2783dc80-1bd1-11eb-97ee-52de41c70a59.jpg)

**Comment by gedoor** [comment]
好像是书名太长

**Comment by Xumingyan** [comment]
我把文件改短，存在同样的问题，这个文件名不知道是从哪里获取到的

**Comment by gedoor** [comment]
我处理在书名太长的问题

**Comment by gedoor** [comment]
新版本解决
