### ISSUE TITLE
目录空白！离线缓存不了！小说内容加载！严重影响使用！

### ISSUE THREAD

**Issue by chenweizi666** [gedoor/legado#456]
飞哥！您好！自从更新sdk30的驱动阅读版本！导致我vivo和华为手机的安卓8系统，这几天我试用了好多阅读版本，共存酷安pro，都是加载中，目录，离线缓存，小说内容，通通没有反应，严重影响我使用阅读，真没办法看书啦！很多源都是正常的，没有失效，这几天试了很多！还是离线缓存下载不啦，目录空白，正文加载中！求求您修复下吧！我也不知道随更新版本越来越多，安卓八频繁出问题。。
![IMG_20201101_151845](https://user-images.githubusercontent.com/71624331/97797356-5cd30d80-1c57-11eb-90ae-a59142227b58.jpg)
![Screenshot_20201101-150316](https://user-images.githubusercontent.com/71624331/97797357-5f356780-1c57-11eb-8737-6a6fda0c5846.jpg)
![Screenshot_20201031-124630](https://user-images.githubusercontent.com/71624331/97797364-6a889300-1c57-11eb-9620-d9275ebecafb.jpg)

![Screenshot_20201031-131707](https://user-images.githubusercontent.com/71624331/97797369-75dbbe80-1c57-11eb-8a66-a0ebaa21ead8.jpg)
![Screenshot_20201031-124443](https://user-images.githubusercontent.com/71624331/97797370-75dbbe80-1c57-11eb-8905-f2626917518f.jpg)
![Screenshot_20201030-212342](https://user-images.githubusercontent.com/71624331/97797371-76745500-1c57-11eb-8c97-2f65837b4ee0.jpg)

我试了太多！我这几天都卸载阅读！看完结了😫😫😫🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by gedoor** [comment]
好的,这原因真奇怪

**Comment by gedoor** [comment]
加我qq,我发个SDK29的你试试

**Comment by chenweizi666** [comment]
> 加我qq 77148227,我发个SDK29的你试试

我已经添加你啦了！qq1737925959

**Comment by Xumingyan** [comment]
我的手机存在同样的问题，手机型号是三星s10

**Comment by gedoor** [comment]
加QQ测试吧

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持
