### ISSUE TITLE
添加本地书籍Bug，未分组里不显示

### ISSUE THREAD

**Issue by nxhswjy** [gedoor/legado#458]
这Bug挺久了，从上次更新增加分组命名后就存在了。

在线书籍添加到未分组的可以显示，本地书籍添加到未分组里则没有显示。(未分组的本地列表跑到本地分组里去了)导致现在添加本地书籍非常不方便，需要在本地分组里一个一个勾选，才能批量添加到想添加的分组里。
![IMG_20201102_162619](https://user-images.githubusercontent.com/69415035/97846421-f0284380-1d28-11eb-99dc-e1fd5fa8f118.jpg)
![IMG_20201102_162556](https://user-images.githubusercontent.com/69415035/97846429-f3233400-1d28-11eb-8071-b21c172de59e.jpg)

**Comment by gedoor** [comment]
特地这样的,已经在本地了就没在未分组

**Comment by nxhswjy** [comment]
好的,谢谢解答

> 特地这样的,已经在本地了就没在未分组
