### ISSUE TITLE
WEB阅读器是否能支持epub中图片的显示呢？

### ISSUE THREAD

**Issue by zhaohuiyingxue** [gedoor/legado#459]
目前对epub格式的支持，有几个地方感觉还有待优化。
1、目录有的是分层的，这个目前是堆一起了。
2、内容自带格式的目前没有展示出来。
3、也是我个人比较迫切的。在web阅读器中不能显示图片。

**Comment by Celeter** [comment]
web已经支持图片显示了，有请求头限制的暂时没办法

**Comment by zhaohuiyingxue** [comment]
请求头？我指的不是单独一个图片在web中显示，而是在epub中文章内的插图。在webapi的返回json中，整个章节被输出成纯文本了(data字段)。其中的图片代码会作为字符串直接显示。

手机app内查看没有问题，另外我用的是新版web阅读器

**Comment by zhaohuiyingxue** [comment]
图片目前被显示成html代码了，比如这样　　<img class="singlepage" src="../images/00005.jpeg" width="1748" height="2480">

**Comment by zhaohuiyingxue** [comment]
图片现在被显示成了这样的html代码，　　〈img class="singlepage" src="../images/00005.jpeg" width="1748" height="2480">

**Comment by zhaohuiyingxue** [comment]
我记得应该是这个接口返回的章节内容吧

![Screenshot_2020-11-06-22-07-35-130_com tencent mm](https://user-images.githubusercontent.com/17868221/98375131-9df16600-2039-11eb-823c-0849e3e9b71b.jpg)

**Comment by zhaohuiyingxue** [comment]
刚才没上传成功图片

获取书籍内容
URL = http://127.0.0.1:1234/getBookContent?url=xxx&index=1
Method = GET
获取指定图书的第index章节的文本内容。

**Comment by zhaohuiyingxue** [comment]
我觉得这个问题应该和 #286 是一类的问题。都是因为epub的一些资源是在压缩包中的，本地导入后也是在本地存储，通过API传送的地址无法访问的原因。新版本的web浏览器更新了，img标签可以输出，但是src不是在线地址所以依然无法显示。

如果api能够提供本地图片的访问，尤其是像epub这种包内资源的，应该就可以了把？或者可以通过将图片base64编码后和正文传输，应该也行。[https://www.cnblogs.com/wteng/p/5748742.html](url)

**Comment by zhaohuiyingxue** [comment]
比如，epub的封面，在web浏览的时候，html是这样的：img data-v-21a7f6c5="" src="/storage/emulated/0/Android/data/io.legado.app.release/files/covers/9af46d656a03a6f1.jpg" alt="" class="cover">
**这个url显然是手机存储的地址，肯定是访问不到的。**

对于正文，比如有这样一个图片：img src="../images/00001.jpeg" class="singlepage" width="1819" height="2551">
../images/00001.jpeg指的是epub内部结构的相对路径，这个路径被直接显示到web浏览器中后，实际地址会变为
**http://192.168.0.146:1122/images/00001.jpeg**
这个地址肯定也是访问不到的。

**Comment by Celeter** [comment]
epub图片除非传整个文件，不然看不了图

**Comment by hoodie13** [comment]
本地带图片的epub在web端显示的时候能否直接过滤掉图片。
现在图片仍然在显示，但是显示出来是一张坏图。

另外能不能在web上加个默认封面。

**Comment by zhaohuiyingxue** [comment]
@hoodie13  epub的图片是在本地，在手机上看是没问题的，在web端是找不到图片的，因为API接口返回的内容是文本内容。作者改了一版之后，图片标签可以出来，但是因为图片url不存在所以也显示不出来。如果API能返回时将图片编码成功base64理论上就可以了。

刚更新了最新版本，目前WEB端暂时还不能看图文的epub
