### ISSUE TITLE
请问可以支持微软Azure的tts吗？

### ISSUE THREAD

**Issue by joglein** [gedoor/legado#468]
本人小白，但是我看微软edge浏览器里的大声朗读（TTS）Xiaoxiao Natural，贼舒服，但是不知道怎么操作，求大神指导

**Comment by joglein** [comment]
我现在版本是3.20.110116，因为现在可以增加朗读引擎的url，所以有此一问。

**Comment by gedoor** [comment]
这个你看看能不能在浏览器里面调用,能写成url就可以了

**Comment by joglein** [comment]
> 这个你看看能不能在浏览器里面调用,能写成url就可以了

有大神做过吗？
