### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by 13776** [gedoor/legado#469]
并不是所有人都喜欢左右仿真的阅读方式，比如本人就是习惯上下阅读的。
刚上手阅读，发现作者大大虽然提供了上下触摸阅读，但还有三点个人觉得需要优化/更新的：
1.希望向上滑动固定翻一页的功能；
2.希望可以定制单击翻页的触点区域，或者请至少提供一个上下版的，毕竟我上下模式也需要点击左右翻页感觉非常的违和；
3.希望更新翻页保留最后一行的功能。这个功能理论上不该没有，但我确实没找到。
如上，刚上手翻了几遍设置，也许有的功能是提供了但我没找到的，请见谅。
最后，支持作者大大！

**Comment by 52fisher** [comment]
滚动翻页不需要固定行数. 第二个需求已经完成了
