### ISSUE TITLE
打开web后直接是书源编辑界面

### ISSUE THREAD

**Issue by hjianhao** [gedoor/legado#470]
如题。用kindle浏览器打开web地址直接是书源编辑，也没法跳转到阅读界面。

**Comment by Antecer** [comment]
右侧帮助选项卡里面有跳转到阅读界面的链接.
开 2020/11/09, 星期一 8:19:27, Jason Huang <notifications@github.com> 写到:
如题。用kindle浏览器打开web地址直接是书源编辑，也没法跳转到阅读界面。

**Comment by Celeter** [comment]
kindle的浏览器太垃圾，无法正常显示web的内容，你放弃吧

**Comment by hjianhao** [comment]
> kindle的浏览器太垃圾，无法正常显示web的内容，你放弃吧

还是希望能支持，例如微信读书的web版在kindle浏览器上就支持得还不错。

kindle没有追书功能啊，如果配合手机的阅读app，用web方式能在kindle上阅读，能解决大问题了。
