### ISSUE TITLE
关于朗读设置一些建议

### ISSUE THREAD

**Issue by playnetcn** [gedoor/legado#472]
有些人有时候晚上喜欢听小说，能否在软件的朗读设置中增加一些有名的主播声音？例如周建龙，大灰狼，艾宝良，周铁叶欣等声音。大家可以根据自己的喜好选择主播来朗读小说。

**Comment by gedoor** [comment]
这个可以自定义的

**Comment by playnetcn** [comment]
@gedoor 能指导一下在哪可以找到自定义主播的声音源，如何配置增加声音？

**Comment by gedoor** [comment]
关注公众号 开源阅读 有一个自定义朗读的教程
