### ISSUE TITLE
提一个关于朗读TTS的奇葩需求

### ISSUE THREAD

**Issue by echoIIImk2** [gedoor/legado#474]
Google的TTS非常强，中文朗读已经非常接近真人，比讯飞强不少，讯飞虽然搞了一大堆风味、方言啥的，但是核心功能已经多年没改进了，表现出来是词跟词之间衔接的时候会有不协调的地方，说白了就是合成味儿很浓。

但是Google存在两个问题，一个是偶尔莫名其妙变成另一个声线，这个没办法，而且尚能忍；另一个问题是多音字，鬼知道Google什么逻辑，多音字念得莫名其妙，比如干干净净能念成gan qian jing jing。而Google的做派我们也熟悉，核心功能做好了之后，边边角角的可能一辈子都不改，很难指望得上。

于是我这里有个看起来有点奇葩的功能需求，就是建一个多音字表（多音字表可以手动维护），把常见的多音字在TTS朗读前先替换成非多音的同音字再让TTS去朗读。比如把干干净净替换成甘甘净净再朗读，多音字表大致就是这样的词汇的替换。这样处理一下虽然不能完全解决多音字念错的问题，但是由于绝大多数常见的多音字在固定的词汇或短语中的读音是确定的，所以能够大幅减少读错的情况，体验会好不少。不知作者能否考虑一下。

**Comment by 10bits** [comment]
谷歌的可能没有进行分词，百度的tts，试试4007这个台湾腔女声，已经很自然了

**Comment by echoIIImk2** [comment]
> 谷歌的可能没有进行分词，百度的tts，试试4007这个台湾腔女声，已经很自然了

请问这个4007是哪个，试了一下自带的百度的那几个，也都有合成味儿大的问题，只有“度逍遥”还行，只是不能调速度

**Comment by echoIIImk2** [comment]
学了一下怎么添加，原来就是改一下id，试了一下4007，也是有合成味儿，百度这个在线TTS有全一点的列表吗

**Comment by 10bits** [comment]
除了对话，已经很不错了，再试试5201这个萝莉女声

**Comment by Celeter** [comment]
还不如你自己建个表，要朗读的时候使用净化功能现实

**Comment by echoIIImk2** [comment]
并不是要求像人声一样有感情，而是目前多数风味TTS都有词汇衔接时的金属颤音，很不舒服，这就是我说的合成味儿。
另外试了一段时间的自带的“度逍遥”，发现经常会有中断的问题，特别是在非wifi的场景下，估计是不是因为是网络TTS的缘故，本地TTS就没这问题，实际上Google的足够好用，如果没有多音词的问题的话。
也考虑过净化功能，但说实话我并不是一直用TTS，而是只在路上等不方便用手机的时候用，就存在一个经常切换的问题，所以希望能专门针对TTS做个替换。
