### ISSUE TITLE
默认的全局翻页动画无法设置

### ISSUE THREAD

**Issue by bigfoxtail** [gedoor/legado#477]
使用Elink不想使用翻页动画，但是没有全局设置 ，只能每一本小说单独修改

**Comment by bigfoxtail** [comment]
。。。忘记原来的动画设置在哪了，现在找到了

**Comment by Rainboylvx** [comment]
> 。。。忘记原来的动画设置在哪了，现在找到了

请问在哪里设置呢？我也找了很长的时间

**Comment by bigfoxtail** [comment]
> > 。。。忘记原来的动画设置在哪了，现在找到了
> 
> 请问在哪里设置呢？我也找了很长的时间

看书的界面，按中间弹出设置-然后下面的界面，选择无动画。。。非常明显的地方，当时找半天
