### ISSUE TITLE
最近几个版本才出现的问题， 虚拟菜单不应用主题配色

### ISSUE THREAD

**Issue by sunleeyy** [gedoor/legado#479]
大多数情况下，虚拟按键会应用和设置背景一样的配色。

![QQ图片20201115214640](https://user-images.githubusercontent.com/73533507/99186594-5b8ffd80-278c-11eb-92b1-ade68b8b548f.png)
像这样
![QQ图片20201115214948](https://user-images.githubusercontent.com/73533507/99186608-7febda00-278c-11eb-95c8-2e005aeb00ba.png)
但是最近几个版本更新后某些情况下，虚拟按键不应用主题配色(退出到书架，再进入会恢复正常)
Android 11 氢OS

**Comment by gedoor** [comment]
好的,我看下

**Comment by sunleeyy** [comment]
> 好的，我看下+
----------------------
以下情况必出现：
1.开启朗读，2.选择小说目录 
这时候虚拟按键就会不应用主题色，不开朗读，直接选择目录倒无此问题

**Comment by gedoor** [comment]
下版本修复

**Comment by sunleeyy** [comment]
> 下版本修复

最近一周更新了111620、111820下载后，虚拟按键由白色变成灰色。
![Screenshot_20201123-175338](https://user-images.githubusercontent.com/73533507/99949582-3ddb1d80-2db6-11eb-94ca-3b762201bfe0.jpg)
我仔细试过了110715以及以前版本是正常的。
从111113版本开始才出现的这个问题
