### ISSUE TITLE
Bug:详情页链接缺少urloptions

### ISSUE THREAD

**Issue by AndyBernie** [gedoor/legado#483]
阅读版本：3.20.111514
书源：[哔哩哔哩漫画](http://yck.mumuceo.com/yuedu/shuyuan/yuan/id/2605.html)
搜索词：`我的`或者`https://manga.bilibili.com/twirp/comic.v1.Comic/ComicDetail?device=pc&platform=web,{"method":"POST","body":"{\"comic_id\":\"27491\"}","headers":{"Referer":"https://manga.bilibili.com/detail/mc27491?from=manga_serach"}}`
详情页链接期望结果：`https://manga.bilibili.com/twirp/comic.v1.Comic/ComicDetail?device=pc&platform=web,{"method":"POST","body":"{\"comic_id\":\"27491\"}","headers":{"Referer":"https://manga.bilibili.com/detail/mc27491?from=manga_serach"}}`
详情页链接实际结果：`https://manga.bilibili.com/twirp/comic.v1.Comic/ComicDetail?device=pc&platform=web`

![Screenshot_20201116-142734397](https://user-images.githubusercontent.com/26325370/99220001-c424bc00-2818-11eb-94de-6691b8b6ee4a.jpg)

**Comment by gedoor** [comment]
好的,我改下,实际是起作用了的
