### ISSUE TITLE
关于进度和书签同步的功能

### ISSUE THREAD

**Issue by echoIIImk2** [gedoor/legado#486]
核心功能里好像就只缺这个，不知是否在待做列表里。
既然已经有webdav备份功能了，应该快了吧。
如果做的话，希望在自动同步的基础上增加手动同步的按钮，用Moonreader的时候就经常该同步的没同步。

**Comment by hoodie13** [comment]
目前阅读设置界面有一个同步按钮，就是换源右边的相邻按钮，我测试可以把webdav中的进度同步到本地。但是此时不支持本地同步到webdav。
关于上传逻辑：
1.kindle的做法是点击手动同步后阅读最远处的阅读记录上传到服务器。但是这个又引入了清除最远记录的逻辑，搞得有些复杂。
2.多看微读等主流做法是同步最近一次的记录。这个容易误操作冲掉需要的阅读记录。其中做的最好的是静读天下，在切任务出去和关屏幕都会上传一次记录。
3.起点的同步逻辑是上传最近三次的记录，记录包含了上传时间，上传设备名，上传章这些关键信息，让用户选择。选择入口在目录/书签/云端进度。我觉得这个是最完美的方案。

**Comment by dabinn** [comment]
> 目前阅读设置界面有一个同步按钮，就是换源右边的相邻按钮，我测试可以把webdav中的进度同步到本地。但是此时不支持本地同步到webdav。
> 关于上传逻辑：
> 1.kindle的做法是点击手动同步后阅读最远处的阅读记录上传到服务器。但是这个又引入了清除最远记录的逻辑，搞得有些复杂。
> 2.多看微读等主流做法是同步最近一次的记录。这个容易误操作冲掉需要的阅读记录。其中做的最好的是静读天下，在切任务出去和关屏幕都会上传一次记录。
> 3.起点的同步逻辑是上传最近三次的记录，记录包含了上传时间，上传设备名，上传章这些关键信息，让用户选择。选择入口在目录/书签/云端进度。我觉得这个是最完美的方案。

请问阅读设置界面的同步按钮在哪？我的换源右边是Reflesh按钮
![image](https://user-images.githubusercontent.com/21699064/101309541-a41c7180-3887-11eb-9afb-a95a22b2f1fd.png)

**Comment by ql1307096** [comment]
同步进度的功能有问题。2台手机，每次关闭的时候都备份到webdav，但是另一台启动的时候进度不变，即使选择恢复进度，书籍的进度依然不变，之前的版本可以。

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持
