### ISSUE TITLE
关于文字排版的一些建议。

### ISSUE THREAD

**Issue by hoodie13** [gedoor/legado#491]
对于冒号目前的处理是是断行前置的。能否冒号后置。主流的还是后置的。
标点符号和引号的组合能否做压缩。如句号和引号在一起压缩成一个汉字的宽度。
能否支持标点悬挂。像kindle的话逗号和句号是支持标点悬挂的。

**Comment by hoodie13** [comment]
读了下排版实现，目前是在用安卓StaticLayout处理的。发现StaticLayout对中文标点处理一般逗号句号都还很中规中矩，但是冒号不知道为什么进制出现到行尾。因为也不能出现到行首。所以遇到这种情况会自动换行，上一行空了2个字。
像这样
![Screenshot_20201130_182303](https://user-images.githubusercontent.com/74173949/100598594-eac71480-3339-11eb-8d1f-4500907e09dd.jpg)
我看了下主流的大厂APP，都做了处理。不知道是不是重写了排版算法。像微信读书
![Uploading Screenshot_20201130_181019.jpg…]()

不知道是有没有一些现成的排版算法可以直接用的。

**Comment by hoodie13** [comment]
自己抽时间重写了一套排版算法。中文排版其实很简单，每个字宽一直，只需要针对中文标点处理，因为复杂排版的书也不看，改了以后看网文满足要求！阅读很棒！

**Comment by gedoor** [comment]
> 自己抽时间重写了一套排版算法。中文排版其实很简单，每个字宽一致，只需要针对行首行尾中文标点处理，也实现了标点压缩。因为复杂排版的书也不看，改了以后看网文完全满足要求！阅读很棒！

可以提交个pr我看看

**Comment by gedoor** [comment]
> 自己抽时间重写了一套排版算法。中文排版其实很简单，每个字宽一致，只需要针对行首行尾中文标点处理，也实现了标点压缩。因为复杂排版的书也不看，改了以后看网文完全满足要求！阅读很棒！

我自己去你的代码里看吧

**Comment by hoodie13** [comment]
@gedoor 怎么提pr。。刚刚学kotlin，好多语法不会，所以代码写的乱七八糟的。不知道能不能看懂。
主要原则是最多下移一个字符去避首尾标点。如果需要移两个字符就做标点压缩。如果特别多连续标点才做多字符截断。

**Comment by hoodie13** [comment]
这个是原版排版，空3个字符会太大了
![Screenshot_20201213_085236](https://user-images.githubusercontent.com/74173949/102000271-af0c5180-3d20-11eb-8d99-0582c0f1f01d.jpg)
![Screenshot_20201213_085222](https://user-images.githubusercontent.com/74173949/102000274-b4699c00-3d20-11eb-9757-b46898aa3426.jpg)

**Comment by SplitGemini** [comment]
![Screenshot_2020-12-21-14-41-04-070_io legado app release](https://user-images.githubusercontent.com/34861918/102747488-55003180-439b-11eb-8cdb-2fb0df18815b.jpg)

中间这行因为对齐产生了间隔，比较影响观看，不知道是设置问题还是什么

**Comment by yukinaz** [comment]
> ![Screenshot_2020-12-21-14-41-04-070_io legado app release](https://user-images.githubusercontent.com/34861918/102747488-55003180-439b-11eb-8cdb-2fb0df18815b.jpg)
> 
> 中间这行因为对齐产生了间隔，比较影响观看，不知道是设置问题还是什么

左右对齐的效果啊，把右侧空的宽度平分给这行每一个字间距。

**Comment by yukinaz** [comment]
> 这个是原版排版，空3个字符会太大了
> ![Screenshot_20201213_085236](https://user-images.githubusercontent.com/74173949/102000271-af0c5180-3d20-11eb-8d99-0582c0f1f01d.jpg)
> ![Screenshot_20201213_085222](https://user-images.githubusercontent.com/74173949/102000274-b4699c00-3d20-11eb-9757-b46898aa3426.jpg)

我现在用大佬fork的项目 来看小说，挺不错的，啥时候支持epub图文显示？
