### ISSUE TITLE
内置广告过滤器

### ISSUE THREAD

**Issue by liwen629528** [gedoor/legado#492]
阅读的订阅源打开的浏览器里还是有很多广告，尝试了很久写代码但真的太难了。大佬能不能在内置浏览器里加入一个广告过滤功能，比如alook浏览器的内置的Adblock Plus广告过滤，可以自动屏蔽，也可以手动选择屏蔽。

**Comment by Antecer** [comment]
软件不能内置广告拦截，已经有很多前车之鉴了。
你需要广告拦截，要么自己写规则，要么找别人写规则，软件永远不会内置的。
