### ISSUE TITLE
两端对齐时，英文单词内部字母的间距改变

### ISSUE THREAD

**Issue by wuqiong4945** [gedoor/legado#503]
![mmexport1605711183682](https://user-images.githubusercontent.com/1294412/99909090-6a912580-2d21-11eb-9d1a-d332e21694cc.jpg)

**Comment by Antecer** [comment]
软件，目前主要以中文阅读为主，这个需求可能要等很久才能得到解决。
建议阅读英文内容使用左对齐布局。
