### ISSUE TITLE
[BUG] 这是一个BUG反馈模板

### ISSUE THREAD

**Issue by Antecer** [gedoor/legado#505]
### 机型
>
华为Mate7

### 安卓版本
>
Android 7.1.1

### 阅读Legdao版本（我的-关于-版本）
>
3.20.112220

### 问题描述（简要描述发生的问题）
>
我发现了一个BUG (●'◡'●)

### 使用书源（填写URL或者JSON）
>
```json
{
    "bookSourceUrl": "https://www.siluke.tw",
    "bookSourceType": "0",
    "bookSourceName": "思路客",
    "bookSourceGroup": "正则",
    "bookSourceComment": "",
    "loginUrl": "",
    "bookUrlPattern": "",
    "header": "",
    "searchUrl": "search.php?keyword={{key}}&page={{page}}",
    "exploreUrl": "",
    "enabled": false,
    "enabledExplore": false,
    "weight": 0,
    "customOrder": 15,
    "lastUpdateTime": 0,
    "ruleSearch": {
        "bookList": "//*[@class=\"result-list\"]/div",
        "name": "//a[@cpos=\"title\"]/@title",
        "author": "//*[text()=\"作者：\"]/following-sibling::*/text()",
        "kind": "//*[text()=\"类型：\"]/following-sibling::*/text()",
        "lastChapter": "//a[@cpos=\"newchapter\"]/text()",
        "coverUrl": "//img/@src",
        "bookUrl": "//a[@cpos=\"title\"]/@href"
    },
    "ruleExplore": {},
    "ruleBookInfo": {
        "name": "//*[@property='og:novel:book_name']/@content",
        "author": "//*[@property='og:novel:author']/@content",
        "kind": "//*[@property='og:novel:category']/@content",
        "lastChapter": "//*[@property='og:novel:latest_chapter_name']/@content",
        "intro": "//*[@property='og:description']/@content",
        "coverUrl": "//*[@property='og:image']/@content"
    },
    "ruleToc": {
        "chapterList": ":(?s)dd><a href=\"([^\"]*)\"[^>]*>([^<]*)",
        "chapterName": "$2",
        "chapterUrl": "$1"
    },
    "ruleContent": {
        "content": "//*[@id='content']"
    }
}
```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
打开阅读>点击我的>书源管理>右上角（本地导入）>选择自带文件选择器>软件显示白屏，看不到文件

### 日志提交（问题截图或者日志）
>
这个不用举例了，自己把问题出现时的界面截图，拖入页面内就会自动上传了。

**Comment by JerryFlyFly** [comment]
阅读Legdao版本:3.20.120609，这个不重要，估计所以版本都有这个问题

问题描述：
**动画选择滚动**，开启**自动翻页**，如果自动翻页时长设置超过40s，界面就不会自动翻页。

解决办法：
我查看过源码，是**ReadBookActivity.kt 里面的autoPagePlus函数**有问题
你用handler每20ms滚动一次，滚动距离是 -pageView.height/autoReadSpeed/50 ,但是**int除法是整除**，如果 pageView.height < autoReadSpeed*50，那么结果就是0，所以就不会滚动。我的手机高度为1920，1920/40/50=0，所以我设置时间小于40s，自动翻页就没反应了。（**动画选择滚动**）

把代码可以改为：
        if (binding.pageView.isScroll) {// 采用了滚动动画
            val dPixel: Float =
                binding.pageView.height.toFloat() / ReadBookConfig.autoReadSpeed.toFloat()
            if (dPixel < 50) { // 说明每20ms需要滚动的像素小于1像素，这时需要修改handler的更新频率
                 binding.pageView.curPage.scroll(-1)  // 为了动画更加流畅，每次移动1个像素
                mHandler.postDelayed(autoPageRunnable, (1000f / dPixel).toLong())
            } else {
                binding.pageView.curPage.scroll(-(dPixel / 50 + 0.5).toInt()) // 这里还有问题，int除法结果是整数，意味着如果结果为1.0-1.999之间都会是1，用户在调节时长时如果恰好在[a.0,a.999]之间实际上自动翻页速度都是a，并没有改变。暂时我没有想到好的办法，可以从改变mHandler刷新间隔调整方面考虑
                mHandler.postDelayed(autoPageRunnable, 20) 
            }
        }
