### ISSUE TITLE
[Feature Request] 关于页眉页脚中的信息显示自定义的需求

### ISSUE THREAD

**Issue by hoodie13** [gedoor/legado#506]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
1.目前的页眉页脚信息如电量时间章节名称等，默认显示的颜色与正文一致。目前一些主流的阅读器页眉页脚的的颜色会比正文颜色稍浅。可以更突出正文内容而不是喧宾夺主。
2.另外期望电量和时间显示可以合并，类似于起点APP的做法。

### 期望实现方式（阅读应该如何实现该功能）
>
1. 期望信息显示支持更多自定义：字体颜色，字体大小。
2.期望支持电量和时间显示合并，（为了一致电量可以只显示百分比不显示电池小图标）

### 附加信息（其他的与功能相关的附加信息）
> 无

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by hoodie13** [comment]
![Screenshot_20201124_174336_io legado app debug](https://user-images.githubusercontent.com/74173949/100077234-1438f980-2e7d-11eb-8a4f-ce624ab41a61.jpg)
我自己初步改了一下，感觉效果会好一些

**Comment by gedoor** [comment]
已完成
