### ISSUE TITLE
[Feature Request] 3.0 覆盖滑动太快，以至于掉帧，希望恢复2.0滑动

### ISSUE THREAD

**Issue by wac81** [gedoor/legado#509]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 3.0 覆盖滑动太快，以至于掉帧，希望恢复2.0滑动

### 期望实现方式（阅读应该如何实现该功能）
> 希望恢复2.0滑动帧率

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by YumikoAzu** [comment]
在酷安上阅读3.0的评论区也经常看到这个滑动问题反馈。说3.0比不上阅读2.0滑动。

**Comment by hoodie13** [comment]
感觉滚动有些掉帧，不如2.0。不知道是不是我的错觉。
不过我一般使用无动画。感觉3.0的手感一级棒。
