### ISSUE TITLE
[Feature Request] 希望听书能支持倍速

### ISSUE THREAD

**Issue by lovejia** [gedoor/legado#510]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望在听书页面能支持倍速，就像看视频一样，支持1.25倍数，1.5倍数，2倍速等等

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
支持的啊
