### ISSUE TITLE
[Feature Request] 与全面屏手势冲突

### ISSUE THREAD

**Issue by Acytoo** [gedoor/legado#511]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 全面屏手势退出时，与滑动翻页冲突，退出时也会翻一页。

### 期望实现方式（阅读应该如何实现该功能）
> 检测是否触发全面屏的``` onBackPressed() ```，如果触发返回，就取消刚刚的翻页。或者延迟翻页的触发时间，确定不是返回时再翻页。

### 附加信息（其他的与功能相关的附加信息）
> 手机是pixel，原生安卓10.

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
试试最新版本是不是好了
