### ISSUE TITLE
[Feature Request] 希望可以上架f-droid

### ISSUE THREAD

**Issue by shutaozhenzhen** [gedoor/legado#512]
### 功能描述（请清晰的、详细的描述你想要的功能）
https://f-droid.org/zh_Hans/
F-Droid 是一个 Android 平台上 FOSS（Free and Open Source Software，自由开源软件）的目录，并提供下载安装支持。使用客户端可以更轻松地浏览、安装及跟进设备上的程序更新。

**Comment by linsui** [comment]
@52fisher 请问我们是否可以打包发布这个应用？如果可以的话，打包的工作由我负责，另外我会提交一个添加 Fastlane 元数据的 PR。

**Comment by 52fisher** [comment]
> @52fisher 请问我们是否可以打包发布这个应用？如果可以的话，打包的工作由我负责，另外我会提交一个添加 Fastlane 元数据的 PR。

因其他用户提交未经审查的PR造成阅读功能不稳定，影响正常使用. 本人就此事与其他开发者产生较大的意见分歧，多次劝说无果，自此决定不再参与阅读的任何事宜. 有任何问题请联系阅读主要开发者.

**Comment by linsui** [comment]
抱歉打扰了 :joy:

**Comment by linsui** [comment]
@gedoor 请问我可以打包这个应用吗？
