### ISSUE TITLE
[BUG] Webdav阅读进度同步位置不一致

### ISSUE THREAD

**Issue by dabinn** [gedoor/legado#514]
### 机型（如Redmi K30 Pro）
>各式机型

### 安卓版本（如Android 7.1.1）
>各式版本

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.20.112422

### 问题描述（简要描述发生的问题）
>在不同装置之间以webdav同步bookProgress.json，每个装置打开的阅读位置都不同

### 使用书源（填写URL或者JSON）
>所有书源

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 1. 准备各个屏幕大小不同的装置或模拟器，并设置不同的阅读字体大小，使其每页显示不同字数
2.关闭自动换源， 并手动选择同一书源，确保各装置使用的书源一致。
3.在其中一台装置退出阅读介面或退出APP，在webdav中确认bookProgress.json已被更新
4.在其它装置回复bookProgress.json，进书架察看章节确认阅读进度已成功读入
5.点进阅读介面，此时各装置显示的阅读进度位置都不一致

**Comment by gedoor** [comment]
最新版本已经记录当前阅读字数,部是页数

**Comment by dabinn** [comment]
回报：安装3.20.120412后测试，看json里面durChapterPos是比较大的数字(例如412)应该是已改为记字数没错
但两装置之间阅读进度还是有些落差。

**Comment by gedoor** [comment]
> 回报：安装3.20.120412后测试，看json里面durChapterPos是比较大的数字(例如412)应该是已改为记字数没错
> 但两装置之间阅读进度还是有些落差。

这个就没办法了,分页部同不可能一模一样

**Comment by dabinn** [comment]
收到，不会差太多就可以了 :D
