### ISSUE TITLE
[Feature Request] 增加换源界面的便捷性操作的建议

### ISSUE THREAD

**Issue by hoodie13** [gedoor/legado#516]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望在换源的操作界面增加分组选择的设计逻辑：
目前找书有2个入口，一个是搜索，一个是发现。搜索中的分组设置只对搜索当次有效。如果通过发现找到的书或者已在书架上的书。点换源界面的刷新搜索的书是已启用的全部分组的书。对于有100多条书源以上有细致分组管理的人，可能当前仅需要在某个分组搜索以及展示即可。(比如最常见的设计了常用分组和备用分组。大部分只搜索常用，搜不到时开启备用。如果能直接切分组实现而不是去书源管理里启用就方便多了)另外，添加书源管理菜单，跟搜索界面一致。第三，搜索出的书源长按直接调整分组（目前是禁用功能）
希望换源界面的标题和作者可点击搜索。（只搜书名、只搜作者）

### 期望实现方式（阅读应该如何实现该功能）
> 换源界面增加书源分组的选择。当选择某个分组，只检索本分组的书源。如果数据库存了大量已有搜索书源数据，也仅展示当前分组的书源。选择分组后，搜索界面也默认切换到这个分组。增加书源管理按钮。长按已搜索到书源支持调整分组功能。
换源界面Title上的书名作者支持点击搜索。当前书找到的书源无法严格匹配书名作者时，点击Tile上的书名可以直接跳到搜索界面。（类似于书籍信息界面中点书名的操作），点击作者直接跳到搜索界面。

### 附加信息（其他的与功能相关的附加信息）
> 目前以上逻辑是通过多次启用和禁用来实现的。如果让分组管理来实现，会更快捷。也更逻辑统一。
对于有大量书源的人会比较有效。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by hoodie13** [comment]
如果支持分组管理的情况下，我觉得换源界面的搜索也是可有可无的。
![Screenshot_20201205_120020_io legado app debug](https://user-images.githubusercontent.com/74173949/101233185-bfee0f00-36f1-11eb-8347-c8704ccaedf5.jpg)
![Screenshot_20201205_120256_io legado app debug](https://user-images.githubusercontent.com/74173949/101233199-d6946600-36f1-11eb-885e-b2073c466298.jpg)

**Comment by gedoor** [comment]
好的
