### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AdminHcat** [gedoor/legado#519]
### 机型（如Redmi K30 Pro）
>华为mate8

### 安卓版本（如Android 7.1.1）
>Android 8.0.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.20.120609

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>已离线缓存的书（原书源已失效），点击阅读界面上刷新按钮会导致章节内容报错(全篇变成java.xxxx)，望修复

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>一本离线缓存后的书，书源失效，点击刷新按钮

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
刷新按钮会删除已下载的内容重新下载,书源失效当然下载不了

**Comment by AdminHcat** [comment]
> 刷新按钮会删除已下载的内容重新下载,书源失效当然下载不了

但是会使已经缓存完的书籍内容不能继续阅读了，希望检测书源失效后禁用刷新按钮，现在是点击刷新后会使原先缓存好的章节全部乱码
