### ISSUE TITLE
[BUG] 自动翻页图标在停止自动翻页后没有更新

### ISSUE THREAD

**Issue by JerryFlyFly** [gedoor/legado#521]
在停止自动翻页时，你忘记把 fabAutoPage图标设置为 ic_auto_page.xml

io\legado\app\ui\book\read\ReadBookActivity.kt
忘记在stopAutoPage()中调用 binding.readMenu.setAutoPage(false)

    override fun stopAutoPage() {
        isAutoPage = false
        mHandler.removeCallbacks(autoPageRunnable)
        binding.pageView.upContent()
        binding.readMenu.setAutoPage(false) // 增加这行
    }

**Comment by gedoor** [comment]
已添加
