### ISSUE TITLE
[Feature Request] 阅读介面增加读取webdav进度按钮

### ISSUE THREAD

**Issue by dabinn** [gedoor/legado#523]
### 功能描述（请清晰的、详细的描述你想要的功能）
> webdav阅读进度同步的功能有以下问题
1. 目前比较严重的问题：进度互相覆盖
当装置先前忘记退出，还停留在阅读介面
会无法同步另一台装置的阅读进度
因为同步进度必需先退出阅读介面，而退出时bookprogress.json会被本机进度覆盖
2.使用上不方便的问题：每次读取进度都必需进到设置菜单深处，或是退出APP重新进入，才能更新
因为到设置选单步骤太多而且很怕按错(比如不小心按到备份)
依我使用经验后来就会变成经常在退出APP重进APP，用起来其实挺不舒服的

### 期望实现方式（阅读应该如何实现该功能）
> 
1.在阅读介面中增加一个读取webdav进度按钮，按下就读取bookprogress.json
可以避免以上提到问题
2. 如果可以的话在书柜的菜单上，也加一个读取bookprogress.json按钮。或者是整合到"更新"按钮也行。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>如图红色P字部份
![image](https://user-images.githubusercontent.com/21699064/101307572-c8298400-3882-11eb-93f1-c2e8d5dbfc15.png)

**Comment by gedoor** [comment]
目前是进入应用时自动读取

**Comment by dabinn** [comment]
是的，所以必须退出应用再重进才能更新进度
而且如果从阅读界面退出，进度就被本机覆盖了

**Comment by gedoor** [comment]
好的

**Comment by dabinn** [comment]
谢谢!

**Comment by gedoor** [comment]
完成

**Comment by dabinn** [comment]
新的机制真心好用！
