### ISSUE TITLE
[BUG] 3.20.121112同步进度仍有问题

### ISSUE THREAD

**Issue by dabinn** [gedoor/legado#537]
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.20.121112

### 问题描述（简要描述发生的问题）
>同步进度仍有问题
wabdav上可看到新"bookProgress"目录，以及分割成单本书的"书名_作者名.json"
json内容也有更新到新章节
但就是无法同步
记得是第一次的同步测试是正常的，后来就双方就都只有写入正常，读取却没反应

### 使用书源（填写URL或者JSON）
>另外就是发现新json的资料和旧的相比的少了书源相关的栏位，不知是bug还是改版后特别拿掉的(我是觉得新改的这样比较好)
新：
{
  "author": "猫腻",
  "durChapterIndex": 7,
  "durChapterPos": 0,
  "durChapterTime": 1607670718330,
  "durChapterTitle": "第七章 坟场",
  "name": "庆余年"
}
旧：
  {
    "bookUrl": "https://www.dxmwx.net/dxmbook/10173.html",
    "durChapterIndex": 8,
    "durChapterPos": 332,
    "durChapterTime": 1607669696794,
    "durChapterTitle": "第八章 年龄不是问题",
    "origin": "https://www.dxmwx.net",
    "originName": "🎉 大熊猫",
    "tocUrl": "https://www.dxmwx.net/dxmchapter/10173.html"
  },

**Comment by gedoor** [comment]
我再看看

**Comment by gedoor** [comment]
应该没问题了

**Comment by dabinn** [comment]
谢谢！测试后完全正常，定位也比之前好
