### ISSUE TITLE
[Feature Request] 相关功能简繁转换

### ISSUE THREAD

**Issue by dabinn** [gedoor/legado#538]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 有些功能因为简体/繁体不同使用上有些不便
1. 书源：例如两个网站一个是简体站，另一个是繁体站。书名/作者名/章节，甚至内容都完全相同。只有简繁差别。却无法被视为可互换的书源使用。
2. 书籍搜寻：希望能够无论打简体或繁体，都能找到同一本书。
3. 书源名称搜寻：同上，但这比较不重要。
4. 书柜简繁转换：目前只有文章内容有简舞转换，书框的显示没有转换。但也是比较不重要的部份。

### 期望实现方式（阅读应该如何实现该功能）
> 1&2可能得一起做才有办法实现。但2有点麻烦。
如果每个站都简/繁各搜一次的话，效率太差。
想到二个实现的方式大概是：
方式一：
因为大多数都是简体书源，就先搜简体，如果没有得到结果，才搜繁。储存的资料(例如bookprogress的内容)则一律用简体。
方式二：
在书源的设定档搜寻相关的json栏位加上一栏，用来判定各书源的简繁状态：
例如0=简，1=繁，2=简繁都有
缺省时则只搜简体 (相容原有书源设置)

**Comment by 52fisher** [comment]
做源的时候可以使用js处理。但是由于简繁并不是简单的相互替换的关系，很多词语可能还需要语义转换，比较麻烦
