### ISSUE TITLE
[Feature Request] 请求增加支持本地pdf书籍的导入

### ISSUE THREAD

**Issue by qyrh** [gedoor/legado#539]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望能够支持本地pdf格式文件的导入，包括文字和扫描版pdf每页的图片格式显示。

**Comment by EWF54Y6U7I** [comment]
想🍑

**Comment by 52fisher** [comment]
阅读主要面向在线阅读，pdf等本地书籍建议使用其他软件替代。
