### ISSUE TITLE
[Feature Request] 语音合成内置

### ISSUE THREAD

**Issue by RinOrz** [gedoor/legado#541]
在线 AI 语音的这个 AI 艾夏的声音太好听了，感觉可以通过 Demo 的请求来内置到阅读？（ios 那边的爱阅书香就有这个的 Demo 音源）
https://www.zaixianai.cn/voiceCompose

**Comment by Celeter** [comment]
token和cookie都有时效，不好搞

**Comment by RinOrz** [comment]
> token和cookie都有时效，不好搞

那就有点遗憾了，因为在ios上经常听这个语音，换回android后没有这个语音不习惯 :)

**Comment by Celeter** [comment]
搞好了，用20201228之后的版本加入下面这个语音，之前的版本有bug
```
<js>eval(""+java.ajax("https://cdn.jsdelivr.net/gh/Celeter/build/.github/scripts/voice.js"));voice(speakText,speakSpeed)</js>
```

**Comment by echoIIImk2** [comment]
> https://cdn.jsdelivr.net/gh/Celeter/build/.github/scripts/voice.js



> 搞好了，用20201228之后的版本加入下面这个语音，之前的版本有bug
> 
> ```
> <js>eval(""+java.ajax("https://cdn.jsdelivr.net/gh/Celeter/build/.github/scripts/voice.js"));voice(speakText,speakSpeed)</js>
> ```

这个好棒，好像是用的aliyun的，似乎不用自己改token了。话说能选aliyun的别的声线吗

**Comment by Celeter** [comment]
> > 搞好了，用20201228之后的版本加入下面这个语音，之前的版本有bug
> > ```
> > <js>eval(""+java.ajax("https://cdn.jsdelivr.net/gh/Celeter/build/.github/scripts/voice.js"));voice(speakText,speakSpeed)</js>
> > ```
> 
> 这个好棒，好像是用的aliyun的，似乎不用自己改token了。话说能选aliyun的别的声线吗

这个不是阿里云的，是(在线语音转换的demo)[https://www.zaixianai.cn/voiceCompose]

**Comment by kuleyu** [comment]
> 搞好了，用20201228之后的版本加入下面这个语音，之前的版本有bug
> 
> ```
> <js>eval(""+java.ajax("https://cdn.jsdelivr.net/gh/Celeter/build/.github/scripts/voice.js"));voice(speakText,speakSpeed)</js>
> ```

这个音源好像还稍稍有点问题，语速控制不起作用

**Comment by echoIIImk2** [comment]
> > > 搞好了，用20201228之后的版本加入下面这个语音，之前的版本有bug
> > > ```
> > > <js>eval(""+java.ajax("https://cdn.jsdelivr.net/gh/Celeter/build/.github/scripts/voice.js"));voice(speakText,speakSpeed)</js>
> > > ```
> > 
> > 
> > 这个好棒，好像是用的aliyun的，似乎不用自己改token了。话说能选aliyun的别的声线吗
> 
> 这个不是阿里云的，是[在线语音转换的demo](https://www.zaixianai.cn/voiceCompose)，改别的声线我有空再搞吧

是的，不过这个站用的就是aliyun的服务，界面和声线名字一模一样https://ai.aliyun.com/nls/tts，声线数量比aliyun本地少了不少，不知道缺的这些有没有可能调出来。。我最喜欢的 艾婷 这个声线就缺。。。
等您有空搞了，aliyun这些的效果远超baidu

**Comment by Celeter** [comment]
> 是的，不过这个站用的就是aliyun的服务，界面和声线名字一模一样[https://ai.aliyun.com/nls/tts](https://ai.aliyun.com/nls/tts)，声线数量比aliyun本地少了不少，不知道缺的这些有没有可能调出来。。我最喜欢的 艾婷 这个声线就缺。。。
> 等您有空搞了，aliyun这些的效果远超baidu

```
<js>eval(""+java.ajax("https://cdn.jsdelivr.net/gh/Celeter/build/.github/scripts/ttsDemo.js"));ttsDemo(speakText,speakSpeed,"Aiting")</js>
```

**Comment by RinOrz** [comment]
> ```
> <js>eval(""+java.ajax("https://cdn.jsdelivr.net/gh/Celeter/build/.github/scripts/ttsDemo.js"));ttsDemo(speakText,speakSpeed,"Aiting")</js>
> ```
如何使用？直接复制到url好像没有效果

**Comment by RinOrz** [comment]
@Celeter 3.21.041610 版本的阅读阿里云音源貌似失效了，大佬能修复吗
