### ISSUE TITLE
[BUG] 3.20.121311换源无法刷新书源

### ISSUE THREAD

**Issue by dabinn** [gedoor/legado#543]
### 问题描述（简要描述发生的问题）
>搜寻或换源时无法读取/刷新书源。完全空白或是只跑出一个。

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>测试了四个版本，只有最新121311有问题
3.20.121311 有问题
3.20.121112 正常
3.20.120412 正常
3.20.113015 正常
用两台不同的设备测试都是一样结果
估计是改RxHttp的side effect？

**Comment by gedoor** [comment]
选择了分组的原因,菜单里选一下全部分组

**Comment by dabinn** [comment]
试了下确实是分组的问题，其中一台装置上不知为何分组变成没有任何选择。选全部分组之后就好了。
