### ISSUE TITLE
能不能写个代码框架说明

### ISSUE THREAD

**Issue by M17764017422** [gedoor/legado#65]
最好能做个代码结构的思维导图
有时候一些最简单的功能需求完全可以自己实现，但在对安卓开发不是很了解的情况下，不知道在哪里修改

**Comment by M17764017422** [comment]
这样一些简单的功能需求就可以由用户自己实现，提高用户对开源的参与度，降低作者的工作量，作者只维护主要的基础模块并维持各功能间协调。这样的开源才有意义

**Comment by gedoor** [comment]
嗯,有时间写一个

**Comment by gedoor** [comment]
各文件夹都放了readMe文件,每个文件夹的作用应该可以看懂了
