### ISSUE TITLE
[BUG] legado_app_3.20.121417点击闪退

### ISSUE THREAD

**Issue by honor3568** [gedoor/legado#735]
### 机型（如Redmi K30 Pro）
>荣耀V30

### 安卓版本（如Android 7.1.1）
>10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>legado_app_3.20.121417

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>更新到legado_app_3.20.121417版本后，打开书籍，应用会闪退

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by Celeter** [comment]
像这种只有你发生了闪退，还不提供日志的，和没反馈是一样的

**Comment by gedoor** [comment]
最新版应该解决了
