### ISSUE TITLE
[Feature Request] 关于书签定位到章节问题

### ISSUE THREAD

**Issue by luoxin1314** [gedoor/legado#738]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望把书签功能改回到精确到哪一个段落

### 期望实现方式（阅读应该如何实现该功能）
> 因为有些段落因为书源或者作者写作习惯，部分章节较多的情况下，保存书签功能就很鸡肋了，上次有个章节字数较多，一百多页找个内容硬是翻页翻到吐，希望老大能做出改动

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的

**Comment by aiden-5154** [comment]
然后现在回头看好像找不到添加新书签的入口了

**Comment by gedoor** [comment]
长按，选择文本的菜单里2020年12月29日 下午11:16，aiden-5154 <notifications@github.com>写道：

然后现在回头看好像找不到添加新书签的入口了
