### ISSUE TITLE
[Feature Request] 进度同步问题

### ISSUE THREAD

**Issue by SkeStars** [gedoor/legado#739]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 最近的更新好像更改了进度同步机制，之前启动APP时会自动恢复云端的进度，现在只有进入阅读界面才会恢复该书的进度，这样更换阅读设备后，就无法判断追的小说新更的章节是否已经在其他设备看完，得一本一本点进去才能知道

### 期望实现方式（阅读应该如何实现该功能）
> 进入阅读界面时恢复该书的云端进度，退出阅读界面时自动备份这本书的进度（维持现在的功能）；
启动APP时自动恢复所有书的云端进度（可以在设置里加个选项）；
手动下拉刷新书架时，检测所有书云端是否有更靠后的进度，然后恢复所有有新进度的书的云端进度，覆盖本地进度

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的
