### ISSUE TITLE
[功能请求]

### ISSUE THREAD

**Issue by ghost** [gedoor/legado#742]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 额我想知道可以做到支持MOBI 和AZW3格式的本地书嘛

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
可以做到,等有时间吧
