### ISSUE TITLE
[Feature Request] 行首遇标点自动补字 希望添加选项

### ISSUE THREAD

**Issue by fhwhite** [gedoor/legado#746]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 一行小说的第一个字符，如果是冒号或者引号，句号等标点的时候，会自动从上一行取字，上一行就缺了一块，虽然可以选择文字两端对齐，但竖排对不齐，看着有点别扭

### 期望实现方式（阅读应该如何实现该功能）
> 能否给出选项，是否需要换行对齐？

### 附加信息（其他的与功能相关的附加信息）
> 或者如果已经有了此功能的选项，我没有找到，能否告诉我一下在哪里？

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
 @>

![Screenshot_20201219_235939](https://user-images.githubusercontent.com/47919090/102693795-0eee8500-4258-11eb-9bf6-eb062ed64ef9.jpg)

**Comment by hoodie13** [comment]
现代中文排版引入了前后置标点的规范，大部分中文排版都不允许逗号什么的放行首了。你看看纸质书，都是2行文字不对齐的。

**Comment by fhwhite** [comment]
因为看小说多年用的都是一些老软件，真没注意过这个问题，但现在纸质书竖排都不对齐了吗？崩溃，好多年没看纸质书了

**Comment by hoodie13** [comment]
实体书逗号都不可能放行首的，只是每一行字多，感觉不出来。
上下每个字严格对齐应该是不可能实现的。随便加个英文单词，字宽都不定，汉字就对不齐了。
如果只看纯汉字的古书，有个远古神器叫AA小说下载阅读器，可以自定义任何前置后置标点，不过调整难度MAX。

**Comment by 52fisher** [comment]
不符合现代中文排版的标准。
