### ISSUE TITLE
[Feature Request] 能不能添加本地缓存导出为epub的功能？

### ISSUE THREAD

**Issue by EternalTimes** [gedoor/legado#747]
能不能添加本地缓存导出为epub的功能？

**Comment by hoodie13** [comment]
浏览器里搜索下乐书，可以在线txt转epub，内部是调calibre转的，兼容性还不错。

**Comment by EternalTimes** [comment]
> 浏览器里搜索下乐书，可以在线txt转epub，内部是调calibre转的，兼容性还不错。

前提得有txt

**Comment by hoodie13** [comment]
阅读支持导出为txt。
不过体验一般般，因为找到一本书，然后全部下下来，看了一半突然发现有错字漏章什么的。重新再下又太烦了。
不像阅读里直接看，有问题能立刻换源

**Comment by EternalTimes** [comment]
> 阅读支持导出为txt。
> 不过体验一般般，因为找到一本书，然后全部下下来，看了一半突然发现有错字漏章什么的。重新再下又太烦了。
> 不像阅读里直接看，有问题能立刻换源

    没有吧

**Comment by Celeter** [comment]
> > 阅读支持导出为txt。
> > 不过体验一般般，因为找到一本书，然后全部下下来，看了一半突然发现有错字漏章什么的。重新再下又太烦了。
> > 不像阅读里直接看，有问题能立刻换源
> 
> ```
> 没有吧
> ```

有的，在离线下载里

**Comment by 52fisher** [comment]
新版已支持
