### ISSUE TITLE
[Feature Request] 请优化离线刷新导致书本内容丢失的问题

### ISSUE THREAD

**Issue by AdminHcat** [gedoor/legado#750]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 断网时或书源失效时，禁用刷新功能

### 期望实现方式（阅读应该如何实现该功能）
> 先取书源状态，再决定是否删除已缓存完成的文件

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的

**Comment by gedoor** [comment]
下版本实现
