### ISSUE TITLE
[Feature Request] 阅读配置颜色独立设置的建议

### ISSUE THREAD

**Issue by hoodie13** [gedoor/legado#752]
### 功能描述（请清晰的、详细的描述你想要的功能）
我又来提需求了，汗！！大佬帮忙看看这个好不好实现。
近几年的阅读APP在配色上都分为两套逻辑。阅读界面和非阅读界面是独立的配色。非阅读界面采用正常的配色逻辑。阅读界面会强调与阅读背景的协调性，阅读界面的主流配色方案有两种，一种是多看的经典配色，上下固定黑色半透明。（前几年好多APP都在抄这个风格）如图所示

![Screenshot_20201221_170828_com duokan reader](https://user-images.githubusercontent.com/74173949/102759606-4d4a8800-43af-11eb-999f-750a04116a02.jpg)

另一种是顶底栏主色调与阅读背景颜色是相近色，强调沉浸感，不同的阅读背景采用不同的主色调。（这几年新的APP都流行这种配色，不过确实很好看）做得好的如微信读书，参看下图（微信读书的主色调和背景色是相近色，蜗牛读书的话主色调直接采用了背景色，上下栏做的很窄，也很好看，这里就不插图了）

![Screenshot_20201221_175314_com tencent weread](https://user-images.githubusercontent.com/74173949/102764001-7110cc80-43b5-11eb-8a98-1caabba59f38.jpg)

legado采用了一套配色加自定义主题的方式。可自定义的程度其实非常高。但一套逻辑有一个问题，一般在书架时，底部操作栏和强调色不需要一致。为了阅读界面协调，我看社区很多分享的主题都不得不设成了相近色。

### 期望实现方式（阅读应该如何实现该功能）
支持阅读界面采用独立于主题设置之外的配色逻辑。顶栏底栏共享主色调。顶栏和底栏的文体、图标、进度条，状态栏文字等颜色共享文字色。圆形快捷按钮支持独立配色，不支持也可以，写死一个经典色。overFlowMenu的底色也共享主色调，文字颜色共享主文字颜色。强调色的话可以不用单独设置，共享主题设置中的强调色，做成单独配置也行，毕竟要改就都改了。

这样看，主要需要独立两种色系，主色系配置背景，文字色配置文字图标进度条等。这些配色可以做到背景配置里。一个配置一套色系。
### 附加信息（其他的与功能相关的附加信息）
> 这么一改感觉颜值可以提升一档。哈哈！

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
我自己拉代码简单改了下，书架用的是阅读经典色，不改也很漂亮。

![Screenshot_20201221_180103_io legado app debug](https://user-images.githubusercontent.com/74173949/102764698-85a19480-43b6-11eb-9e46-b04441800ae8.jpg)

阅读界面改成了多看风格，把章名链接合并一行。另外关于4个按钮，怎么调都不好看，我发现改到右侧立马颜值就上去了。

![Screenshot_20201221_180611_io legado app debug](https://user-images.githubusercontent.com/74173949/102765186-3c057980-43b7-11eb-9853-f820689b66c7.jpg)

关于这4个快捷按钮，我个人觉得搜索键和规则替换键可以收起来。因为搜索只能搜已下载的，感觉用的不是太多。替换规则的话，最方便快捷的入口是长按文字替换，放到快捷键里反而有误导。

然后自动翻页和朗读可以放到一起，作为阅读模式，类似于多看的配置。这样只剩下一个夜间模式的按钮，再做大些，应该会更美观很多。

另外没找到seekBar进度条改颜色的地方，现在有些暗。（初学者，汗！！）toolBar上图标颜色也没找到怎么改，我看现在只支持黑白，否则全部配成类似于微信读书的颜色，整体会非常好看。

**Comment by hoodie13** [comment]
亮度调节我觉得放右边顺手。稍微调小点感觉更好看。
![Screenshot_20201221_180958_io legado app debug](https://user-images.githubusercontent.com/74173949/102765647-da91da80-43b7-11eb-862f-71cf585f3648.jpg)

**Comment by gedoor** [comment]
好的
