### ISSUE TITLE
[BUG] 一直闪退，点好多次才能打开

### ISSUE THREAD

**Issue by dcdcz** [gedoor/legado#755]
### 机型（如Redmi K30 Pro）
>HUAWEI Nova 7

### 安卓版本（如Android 7.1.1）
>Android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.20.121923

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
> 一直闪退，点好多次才能打开

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开就闪退

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
发崩溃日志,或者备份清下数据试试

**Comment by 52fisher** [comment]
因长时间无回复，此issue将被关闭。问题若仍然存在，请继续反馈。
