### ISSUE TITLE
可以加个书籍置顶、置底功能吗？

### ISSUE THREAD

**Issue by Super-YYQ** [gedoor/legado#758]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 把书籍在书架中置顶或置底

### 期望实现方式（阅读应该如何实现该功能）
> 长按书籍，详情页中增加置顶、置底按钮

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by nobk** [comment]
已经有分组功能了，可以用分组来实现这种置顶、置底的分类方法。
首先在分组管理中建一个名字叫“置顶”的组，然后长按书籍，在书籍封面里设置分组中勾选这个组。
置底类似。
