### ISSUE TITLE
[BUG] 书源管理界面触摸行为异常，猜测是DragSelectTouchHelper类有bug

### ISSUE THREAD

**Issue by Jerry-ojk** [gedoor/legado#760]
### 机型（如Redmi K30 Pro）
> 红米note9 pro

### 安卓版本（如Android 7.1.1）
> 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.20.121923

### 问题描述（简要描述发生的问题）
> 书源管理界面触摸行为异常：
1、某些边缘地方不能触摸
2、上下滑动的时候行为异常，居然会有选中CheckBox的效果，具体请看视频

根据源码来看应该是 **io\legado\app\ui\book\source\manage\BookSourceActivity.kt**里面的 **initRecyclerView()** 函数中的 
```
val dragSelectTouchHelper =
            DragSelectTouchHelper(adapter.dragSelectCallback).setSlideArea(16, 50)
        dragSelectTouchHelper.attachToRecyclerView(binding.recyclerView)
        dragSelectTouchHelper.activeSlideSelect()
```
DragSelectTouchHelper类(io\legado\app\ui\widget\recycler\DragSelectTouchHelper.kt)代码有问题
把这三行代码注释后编译运行就没有这个问题了

要是视频加载不出来，可以复制这个issue页面url，粘贴到加速网站 https://toolwa.com/github/ ，选择线路一稍等就可以看到视频了

### 日志提交（问题截图或者日志）
> 
https://user-images.githubusercontent.com/27681779/103098736-d5968a80-4646-11eb-85af-3742e3457abb.mp4

**Comment by gedoor** [comment]
滑动选择就是特地开发的啊

**Comment by Jerry-ojk** [comment]
那边缘地方不能触摸是怎么回事

**Comment by gedoor** [comment]
感觉系统bug,我手机上没问题

**Comment by gedoor** [comment]
可能和全局手势有关,等我买了小米11测试一下

**Comment by Jerry-ojk** [comment]
大佬就是强，小米11都预定好了，okk
