### ISSUE TITLE
[Feature Request] 阅读界面增加双栏显示正文

### ISSUE THREAD

**Issue by fairyex** [gedoor/legado#761]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 阅读界面增加双栏左右显示文本，像实体书那样

### 期望实现方式（阅读应该如何实现该功能）
> 可以参考微信读书或者Kindle APP在平板上面的表现

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 10bits** [comment]
等明年win10要是能运行安卓，估计会支持的

**Comment by 1274003856** [comment]
屏幕太宽了吧，一般人手机受不了
