### ISSUE TITLE
由于是截屏绘制翻页动画在翻页结束之后页面出现内容加深问题[BUG] 

### ISSUE THREAD

**Issue by CrazyShado** [gedoor/legado#762]
### 机型（如Redmi K30 Pro）
>xiaomi redmi 5 plus

### 安卓版本（如Android 7.1.1）
>7.1.2

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>1.0.1

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by 52fisher** [comment]
因长时间无回复，此issue将被关闭。问题若仍然存在，请继续反馈。
