### ISSUE TITLE
打开TF卡上小说后，会在手机存储 "Android/data/io.legado.app.release/files/bookTxt"备份一份

### ISSUE THREAD

**Issue by SunYongWei** [gedoor/legado#763]
### 机型（如Redmi K30 Pro）
>海信A5

### 安卓版本（如Android 7.1.1）
>9.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.20.121923

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>打开TF卡上小说后，会在手机存储 "Android/data/io.legado.app.release/files/bookTxt"备份一份，造成手机存储不足。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>每次

### 日志提交（问题截图或者日志）
>

**Comment by CrazyShado** [comment]
这个正常吧，避免sd卡文件被删除，书架书籍没法打开的情况，不算bug

**Comment by SunYongWei** [comment]
本来就是想节省手机存储空间才插入的TF卡，这样复制的话和将小说直接复制到手机里面没有区别了。

**Comment by Jerry-ojk** [comment]
可以建议作者增加一个选项开关
