### ISSUE TITLE
打开书后第一次按屏幕中间弹出的导航栏和菜单重叠，听书时按屏幕中间弹出的状态栏和小说最上面信息重叠[BUG] 

### ISSUE THREAD

**Issue by SunYongWei** [gedoor/legado#764]
### 机型（如Redmi K30 Pro）
>海信A5

### 安卓版本（如Android 7.1.1）
>9.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.20.121923

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>打开书后第一次按屏幕中间弹出的导航栏和菜单重叠，听书时按屏幕中间弹出的状态栏和小说最上面信息重叠

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>设置里面隐藏了导航栏和状态栏  打开任何书后，第一次按屏幕中间弹出的导航栏和菜单重叠（视频5秒时），听书时按屏幕中间弹出的状态栏和小说最上面信息重叠（视频12秒时） 看视频巨居然要fanqiang.

https://user-images.githubusercontent.com/43627564/103148592-66cb4580-479c-11eb-975b-3bc6cc64e994.mp4

### 日志提交（问题截图或者日志）
>

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持

**Comment by SunYongWei** [comment]
安装3.21.060618，问题依旧，打开小说后按屏幕蹭第一次下面导航栏菜单重叠，再按，再按才能正常显示。
