### ISSUE TITLE
[Feature Request] rss支持相关

### ISSUE THREAD

**Issue by ug26** [gedoor/legado#765]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 现在订阅源的作用类似于rss，但直接新建源进行编辑对普通人不太友好，最好能支持导入rss链接

### 期望实现方式（阅读应该如何实现该功能）
> 订阅设置里额外增加一个rss链接导入（最好导入时能设定筛选标题等）

### 附加信息（其他的与功能相关的附加信息）
> https://docs.rsshub.app/ 
RSSHub 是一个开源、简单易用、易于扩展的 RSS 生成器，可以给任何奇奇怪怪的内容生成 RSS 订阅源。RSSHub 借助于开源社区的力量快速发展中，目前已适配数百家网站的上千项内容

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
默认就是标准rss
