### ISSUE TITLE
有考虑把epub，txt解析放到c++那处理吗？

### ISSUE THREAD

**Issue by YumikoAzu** [gedoor/legado#766]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
把epub,txt解析放到c++处理，这样解析大文件比较快些。
### 期望实现方式（阅读应该如何实现该功能）
> 
https://github.com/newbiechen1024/NBReader
跟https://github.com/geometer/FBReaderJ
的处理方式。
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
我有空看看
