### ISSUE TITLE
为啥jsengine不考虑用quickjs_android或者j2v8呢？

### ISSUE THREAD

**Issue by YumikoAzu** [gedoor/legado#767]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
rhino_android是Java编写的，跟quickjs和j2v8性能比，应该稍微弱点吧。
[quickjs_android](https://github.com/seven332/quickjs-android)
[j2v8](https://github.com/eclipsesource/J2V8)
### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
rhino_android 调用java最友好,因为本身就是用java写的
