### ISSUE TITLE
分组管理相关功能建议[Feature Request] 

### ISSUE THREAD

**Issue by SplitGemini** [gedoor/legado#769]
### 功能描述（请清晰的、详细的描述你想要的功能）
1. 书源、替换净化和订阅的分组管理界面，切换分组时不要单纯地把组名放在搜索里，不精确
2. 搜索界面和换源界面，选择书源分组希望可以多选
3. 替换净化管理界面和订阅规则管理界面，希望可以添加像书源管理界面类似的批量添加或移除分组功能，同时移除分组只需要给一个已选择项目所在的分组列表就行

### 期望实现方式（阅读应该如何实现该功能）
1. 针对上1，希望切换分组菜单里的分组是多选框，可以同时显示多个分组，且切换分组是精确根据组名分开，而不是用搜索模糊匹配
2. 针对上2，希望把搜索和换源界面的切换分组菜单改成多选，全部书源选项可以删除，或者改成和多选组互斥
3. 针对上3， 替换净化界面和订阅管理界面可能没有书源管理那么完善。对于移除分组的输入框可以直接改成下拉选择框，毕竟已经不需要输入了

### 附加信息（其他的与功能相关的附加信息）
可选：
1. 发现界面分组多选且不只是通过搜索过滤
2. 搜索和换源添加排序功能，根据响应时间排序。这个可能更难实现

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
更新：
1. 针对上1，
<img src="https://user-images.githubusercontent.com/34861918/103256841-990dba80-49c9-11eb-9b33-d211411e2c50.jpg" width = "500" alt="图片名称" align=center/>

类似这种，精确筛选分组
2. 针对上二，改为多选组
<img src="https://user-images.githubusercontent.com/34861918/103257087-b7c08100-49ca-11eb-9ec0-c58d40ad72bf.jpg" width = "500" alt="图片名称" align=center/>

和1其实也类似，换源界面同理

3. 针对上3，书源管理有那么多选项
<img src="https://user-images.githubusercontent.com/34861918/103257177-2271bc80-49cb-11eb-8a8c-e94e00a9553a.jpg" width = "500" alt="图片名称" align=center/>

但是替换净化和订阅管理只有这些
<img src="https://user-images.githubusercontent.com/34861918/103257204-3a494080-49cb-11eb-9f60-d330166718f9.jpg" width = "500" alt="图片名称" align=center/>

相似功能可以补充一下。

对于移除分组

<img src="https://user-images.githubusercontent.com/34861918/103257266-77adce00-49cb-11eb-8853-048f518b9d88.jpg" width = "500" alt="图片名称" align=center/>

最好是已选项目的组名集合去重的列表而不是全部组名的列表

#### 可选

4. 针对附加信息1，发现分组类似上述的多选
5. 针对附加信息2，添加排序选项，可以是响应时间或者优先级
<img src="https://user-images.githubusercontent.com/34861918/103258020-85188780-49ce-11eb-982c-782577dfcd4c.jpg" width = "500" alt="图片名称" align=center/>
换源界面同理

**Comment by SplitGemini** [comment]
再提一些bug，净化替换的order是可以重复的，假如全部item order都一样的话一手动排序马上全乱了

**Comment by gedoor** [comment]
好的

**Comment by SplitGemini** [comment]
还有，组名查询是模糊匹配的吧，比如两个组分别叫'ABC'和'AB'，修改组名为'AB'的源会把组名'ABC'一起修改了，删除同理。
这个跟上面的精确分组问题还是差不多的原因吧，不如一起搞定掉

**Comment by gedoor** [comment]
好的2020年12月31日 下午2:18，Guo <notifications@github.com>写道：
还有，组名查询是模糊匹配的吧，比如两个组分别叫'ABC'和'AB'，修改组名为'AB'的源会把组名'ABC'一起修改了，删除同理。
这个跟上面的精确分组问题还是差不多的原因吧，不如一起搞定掉
