### ISSUE TITLE
订阅源中文乱码

### ISSUE THREAD

**Issue by M17764017422** [gedoor/legado#77]
默认对订阅内容编码识别有问题大量的内容部分的中文乱码

**Comment by M17764017422** [comment]
大部分的rss源在调试的时候正常，但实际浏览的时候就会中文乱码，中文列表是正常的，只有内容描述部分乱码
比如：
http://www.chinanews.com/rss/scroll-news.xml

https://www.html5tricks.com/feed

**Comment by gedoor** [comment]
这个是通过webView自动识别的

**Comment by M17764017422** [comment]
问题已解决，代码已提交。请更新发布谢谢！
