### ISSUE TITLE
[BUG] 两个阅读app

### ISSUE THREAD

**Issue by GitHubWebb** [gedoor/legado#772]
### 机型（如Redmi K30 Pro）
>华为meta30pro 5g

### 安卓版本（如Android 7.1.1）
>Android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
 ## legado_app_3.20.122920
 ## legado_app_3.20.122715

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>wifi

### 问题描述（简要描述发生的问题）
>我之前一直是通过release下载版本，刚刚看到Actions构建了一个最新版本到蓝奏云，于是下载更新了，发现出现两个不同版本的阅读app，并且记录没有统一，新版本没有任何记录，从低版本选择备份后，去新版本还原也没有同步，我应该如何去获得统一呢

### 使用书源（填写URL或者JSON）
>无

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>通过release下载版本通过蓝奏云下载更新最新版本

### 日志提交（问题截图或者日志）
>
![高版本日志说明](https://user-images.githubusercontent.com/24510234/103295084-2d116d80-4a2e-11eb-9723-7f208c52ce2c.jpg)

![低版本日志说明](https://user-images.githubusercontent.com/24510234/103295165-5d590c00-4a2e-11eb-850a-08b86288fed3.jpg)

![高版本恢复数据](https://user-images.githubusercontent.com/24510234/103295224-795cad80-4a2e-11eb-877c-c8625e03daec.jpg)

![低版本备份数据](https://user-images.githubusercontent.com/24510234/103295273-95604f00-4a2e-11eb-8012-eeb640c968f0.jpg)

**Comment by SplitGemini** [comment]
actions里的是共存版，可以从本地还原啊

**Comment by GitHubWebb** [comment]
> actions里的是共存版，可以从本地还原啊

我上面发的备份和恢复数据两张截图，就是进行备份还原操作的，无效的

**Comment by zmn001125** [comment]
两个是共存版，不能

**Comment by zmn001125** [comment]
两个版本是共存的，不能备份还原是因为备份路径的问题，你两个都换个备份路径

**Comment by GitHubWebb** [comment]
> 两个版本是共存的，不能备份还原是因为备份路径的问题，你两个都换个备份路径

 # 备份与恢复
 ## 备份路径

  我指向的都是下载文件夹 系统的download

**Comment by zmn001125** [comment]
> > 两个版本是共存的，不能备份还原是因为备份路径的问题，你两个都换个备份路径
> 
> # 备份与恢复
> ## 备份路径
> 我指向的都是下载文件夹 系统的download

你看过你备份出来的东西有内容吗。你看看文件大小是不是都是0b

**Comment by GitHubWebb** [comment]
> > > 两个版本是共存的，不能备份还原是因为备份路径的问题，你两个都换个备份路径
> > 
> > 
> > # 备份与恢复
> > ## 备份路径
> > 我指向的都是下载文件夹 系统的download
> 
> 你看过你备份出来的东西有内容吗。你看看文件大小是不是都是0b

看了一下是0kb,备份没写入进数据,不过我配置的坚果云WebDav上有生成的备份数据,刚刚通过坚果云恢复了,不过本地是0kb这个应该跟我配置没关系才对,系统文件夹没有写入权限,不对啊,可以生成文件

**Comment by zmn001125** [comment]
> > > > 两个版本是共存的，不能备份还原是因为备份路径的问题，你两个都换个备份路径
> > > 
> > > 
> > > # 备份与恢复
> > > ## 备份路径
> > > 我指向的都是下载文件夹 系统的download
> > 
> > 
> > 你看过你备份出来的东西有内容吗。你看看文件大小是不是都是0b
> 
> 看了一下是0kb,备份没写入进数据,不过我配置的坚果云WebDav上有生成的备份数据,刚刚通过坚果云恢复了,不过本地是0kb这个应该跟我配置没关系才对,系统文件夹没有写入权限,不对啊,可以生成文件

所以叫你换备份路径，如果你要本地恢复的话，不要备份在这个路径

**Comment by GitHubWebb** [comment]
> > > > > 两个版本是共存的，不能备份还原是因为备份路径的问题，你两个都换个备份路径
> > > > 
> > > > 
> > > > # 备份与恢复
> > > > ## 备份路径
> > > > 我指向的都是下载文件夹 系统的download
> > > 
> > > 
> > > 你看过你备份出来的东西有内容吗。你看看文件大小是不是都是0b
> > 
> > 
> > 看了一下是0kb,备份没写入进数据,不过我配置的坚果云WebDav上有生成的备份数据,刚刚通过坚果云恢复了,不过本地是0kb这个应该跟我配置没关系才对,系统文件夹没有写入权限,不对啊,可以生成文件
> 
> 所以叫你换备份路径，如果你要本地恢复的话，不要备份在这个路径

是文件夹原因,谢谢

**Comment by SplitGemini** [comment]
因为是同一个文件夹，新app会自动备份然后把之前的覆盖掉了
