### ISSUE TITLE
[BUG] 分组内书籍数目少于搜索线程数目，会导致搜索线程数目变低

### ISSUE THREAD

**Issue by yisuixinq** [gedoor/legado#775]
### 机型（如Redmi K30 Pro）
> 华为P40

### 安卓版本（如Android 7.1.1）
> 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.20.122715

### 问题描述（简要描述发生的问题）
> 若某个分组内只有一本书籍，下拉刷新后，再切换到其他分组刷新，会看到刷新线程只有一个 (一次只有一本图书有转圈) 

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
好的,我看看

**Comment by yisuixinq** [comment]
这个问题有修复的规划吗？

**Comment by gedoor** [comment]
下版本修复
