### ISSUE TITLE
语音朗读至本页页末时自动翻页

### ISSUE THREAD

**Issue by lifengdp** [gedoor/legado#777]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 目前语音朗读时，是朗读到本段段末后，再自动翻页的，而本段的段末可能在下页的页中或者下下页，这样在朗读的同时目视阅读比较不方便。

如果手动翻页，则语音朗读又会从页首文字重新开始，影响体验；当然可以“朗读设置”中打开“按页朗读”，可以实现语音朗读至页末时自动翻页，但打开此功能后，朗读至页末文字后，实际是中断后再继续朗读下页文字，以至朗读换页时语调不流畅及顿挫，同样影响体验。

### 期望实现方式（阅读应该如何实现该功能）
> 增加一个选项：”语音朗读至页末时自动翻页“；
或者增加一个选项：“手动换页时语音朗读不重新从页首开始朗读”

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by lifengdp** [comment]
> ### 功能描述（请清晰的、详细的描述你想要的功能）
> > 

> 目前语音朗读时，是朗读到本段段末后，再自动翻页的，而本段的段末可能在下页的页中或者下下页，这样在朗读的同时目视阅读比较不方便。

> 如果手动翻页，则语音朗读又会从页首文字重新开始，影响体验；当然可以“朗读设置”中打开“按页朗读”，可以实现语音朗读至页末时自动翻页，但打开此功能后，朗读至页末文字后，实际是中断后再继续朗读下页文字，以至朗读换页时语调不流畅及顿挫，同样影响体验。
> 
> ### 期望实现方式（阅读应该如何实现该功能）
> >

>  增加一项功能：”语音朗读至页末时自动翻页“；
>  或者增加另一个功能：“手动换页时语音朗读不重新从页首开始朗读”
> ### 附加信息（其他的与功能相关的附加信息）
> > 
> 
> ### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> >

**Comment by gedoor** [comment]
有些朗读引擎会按只播报朗读进度,这种的就会及时翻页,比如google文字转语音
