### ISSUE TITLE
净化替换切换分组失效[BUG] 

### ISSUE THREAD

**Issue by SplitGemini** [gedoor/legado#779]
### 机型（如Redmi K30 Pro）
> K30

### 安卓版本（如Android 7.1.1）
> 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.010510

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
> 净化替换切换分组失效

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 右上角切换净化替换分组

### 日志提交（问题截图或者日志）
> 
![Screenshot_2021-01-05-10-52-57-904_io legado app release](https://user-images.githubusercontent.com/34861918/103601564-dbdd0e80-4f44-11eb-942d-7ba478b16d92.jpg)
![Screenshot_2021-01-05-10-50-53-897_io legado app release](https://user-images.githubusercontent.com/34861918/103601488-b51ed800-4f44-11eb-8cd7-a609abeff6c0.jpg)

**Comment by gedoor** [comment]
收到

**Comment by SplitGemini** [comment]
可以了，不知道是更新了还是什么情况
