### ISSUE TITLE
[Feature Request] 希望增加的一些功能

### ISSUE THREAD

**Issue by qyrh** [gedoor/legado#780]
1文字颜色和背景、朗读引擎可以调整顺序
2规则订阅可以设置为定期自动更新
3（如果觉得不合理请无视）可以自动优化一本书：遍历已有书源，摘取正文重复率高的部分作为优化后的正文，这样可以筛除和纠正不同书源的网址，错别字，乱码等。

**Comment by 1274003856** [comment]
关于2，用处不大~因为很多源压根不更新。
