### ISSUE TITLE
[BUG] WebDavError:Protocol not found:https://dav.jianguoyun.com/dav/legado/

### ISSUE THREAD

**Issue by eshxcmhk** [gedoor/legado#781]
### 机型（如Redmi K30 Pro）
>MuMu模拟器

### 安卓版本（如Android 7.1.1）
>6.0.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.010510

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>WebDavError:Protocol not found:https://dav.jianguoyun.com/dav/legado/

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>在其它手机上备份过后，按照备份操作说明配置好坚果云，点击恢复

### 日志提交（问题截图或者日志）
>
[https://1drv.ms/u/s!AjesLjN3FVPPmX41peJc42lqtdYP?e=TUKcWv](url)

**Comment by Celeter** [comment]
去坚果云看看有没有legado文件夹

**Comment by eshxcmhk** [comment]
> 去坚果云看看有没有legado文件夹

有的，在原来的手机上可以正常备份和恢复

**Comment by Celeter** [comment]
> > 去坚果云看看有没有legado文件夹
> 
> 有的，在原来的手机上可以正常备份和恢复

webdav地址重新输一下，一般都是多打了空格
