### ISSUE TITLE
书源换源界面增加清除功能

### ISSUE THREAD

**Issue by szlk** [gedoor/legado#782]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在小说换源界面新增重新搜索按钮，清除当前检索到的书源，重新进行搜索。

### 期望实现方式（阅读应该如何实现该功能）
> 在小说换源界面新增重新搜索按钮，清除并重新搜索书源

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by SplitGemini** [comment]
右上角有

**Comment by szlk** [comment]
哪一个啊，叫什么？

**Comment by szlk** [comment]
> 右上角有

哪一个按钮？叫什么名字🌝🌝

**Comment by gedoor** [comment]
好的,我把刷新按钮加下刷新之前先清除

**Comment by szlk** [comment]
> 好的,我把刷新按钮加下刷新之前先清除

作者给力！！

**Comment by szlk** [comment]
> 好的,我把刷新按钮加下刷新之前先清除

老大，这不对啊，他数据那块是清楚了之前的书源了，但是ui界面还没清除啊

**Comment by szlk** [comment]
> 好的,我把刷新按钮加下刷新之前先清除

书源数据那块是清除了之前的数据，但是在UI界面并没有清空之前搜索到的数据，只有搜索完书源，然后再次搜索一次并快速退出小说界面，重新进入书源界面后才会发现之前的书源清掉了

**Comment by gedoor** [comment]
好的
