### ISSUE TITLE
[BUG] 朗读随机时间后会出现自动停止朗读

### ISSUE THREAD

**Issue by mlc2743** [gedoor/legado#785]
### 机型（如Redmi K30 Pro）
>
荣耀8

### 安卓版本（如Android 7.1.1）
>8.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动4g

### 问题描述（简要描述发生的问题）
>
[BUG] 朗读随机时间后会出现自动停止朗读。有时通过翻页可以继续朗读，有时需要重新打开软件才可以继续朗读。但是每次都要重新打开手机才可以进行翻页或重启软件的操作，就有点麻烦了。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by litcc** [comment]
本地tts引擎还是http引擎？ 如果是本地的用的哪个，如果是http引擎则又用的是哪个

**Comment by carlye** [comment]
我是到一章结束就停了，得在点一次播放才行。已经给了常驻后台的权限。目前也不知道怎么解决

**Comment by mlc2743** [comment]
> 我是到一章结束就停了，得在点一次播放才行。已经给了常驻后台的权限。目前也不知道怎么解决



用久了发现应该是联网不稳定导致的，后来我用讯飞语音引擎（这个支持离线语音），没有再出现任何问题，唯一的缺憾就是讯飞的声音比较一般。
