### ISSUE TITLE
导入txt小说目录解析问题

### ISSUE THREAD

**Issue by changrq** [gedoor/legado#790]
### 机型（如Redmi K30 Pro）
>1+3

### 安卓版本（如Android 7.1.1）
>9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>导入txt小说目录有问题，都是这种 第[0-9]\*章([0-9]\*) ，查看txt原文件并没有出现此字段，原小说目录是 

序 第一章 第二章 ... 
第一卷 第一章 第二章 ... 
第二卷 第一章 第二章 ...
...

这种结构

### 使用书源（填写URL或者JSON）
>无

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>
![Screenshot_20210108-173905](https://user-images.githubusercontent.com/26922465/104000185-d566c500-51d8-11eb-9779-58cd86921562.jpg)
![Screenshot_20210108-174109](https://user-images.githubusercontent.com/26922465/104000221-e4e60e00-51d8-11eb-8a3d-1d0e1618e63f.jpg)
![Screenshot_20210108-174157](https://user-images.githubusercontent.com/26922465/104000248-edd6df80-51d8-11eb-9e85-9ef0fa128390.jpg)

**Comment by changrq** [comment]
在UC浏览器的小说书架里导入txt测试，目录解析正常

**Comment by Antecer** [comment]
这个不是BUG,你需要重新选择解析规则.

**Comment by changrq** [comment]
> 这个不是BUG,你需要重新选择解析规则.

那怎么选择呢？没找到选项

**Comment by 52fisher** [comment]
在书籍页面点击右上角的换源按钮，切换规则即可

**Comment by changrq** [comment]
> 在书籍页面点击右上角的换源按钮，切换规则即可

原来在这啊，谢谢
