### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wk4work** [gedoor/legado#791]
> index.js L334
```javascript
localStorage.setItem('RuleSources', JSON.stringify(RuleSources = json.data));
```
如果书源列表过长超过浏览器的localStorage大小限制会导致拉取失败
![image](https://user-images.githubusercontent.com/49431253/104033587-b2550900-520a-11eb-8836-5ccaa9075130.png)
建议分批或分页等相关机制

**Comment by Antecer** [comment]
卧槽,我还是第一次发现竟然有书源列表比localStorage大的....

**Comment by bingaha** [comment]
好家伙，localstorage上限是多少来着，这还能不够用
