### ISSUE TITLE
[BUG] 本地文件EPUB从目录定位文章永远在第一页

### ISSUE THREAD

**Issue by qingyuyichen** [gedoor/legado#792]
### 机型（如Redmi K30 Pro）
>锤子pro2s

### 安卓版本（如Android 7.1.1）
>7.2.01

### 阅读Legdao版本（我的-关于-版本,如3.21.010520）
>3.21.010520

### 问题描述（简要描述发生的问题）
>EPUB书籍从目录定位文章永远在第一页

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开epub数据，选择任意目录，查看页码，页码为1

### 日志提交（问题截图或者日志）
>
![image](https://user-images.githubusercontent.com/42742593/104092906-0b33a880-52c2-11eb-8e37-21693f095ce9.png)
![image](https://user-images.githubusercontent.com/42742593/104092912-17b80100-52c2-11eb-8d1c-efbcf67d93df.png)

**Comment by ag2s20150909** [comment]
新版应该修复了

**Comment by qingyuyichen** [comment]
已修复
