### ISSUE TITLE
[反馈]默认夜间主题的快捷按钮配色

### ISSUE THREAD

**Issue by lifenjoiner** [gedoor/legado#794]
下部的4个快捷按钮和正文一样都是白色，不便于识别。当然，熟悉了之后是知道在那一片的。

![legado-icon-color](https://user-images.githubusercontent.com/19585474/104115834-8a6ebe00-534e-11eb-8041-132b199045cd.png)

把图标颜色改成和自动亮度那样的橙色怎样，是不是好点？

![legado-icon-color-s](https://user-images.githubusercontent.com/19585474/104115841-9ce8f780-534e-11eb-9b43-b4da2a45a626.png)

PS：
传到电脑上才发现，颜色和手机上看着不完全一样，手机上正文背景和底栏差异更小。可能手机屏幕DPI较高，图显得小，还和屏幕材质有关吧。。。

**Comment by gedoor** [comment]
好,我改下颜色

**Comment by lifenjoiner** [comment]
我举例 P 的颜色不好，占用了按钮激活的颜色，忘记了。。。
具体您统筹吧，我没偏好，效果好就成

**Comment by lifenjoiner** [comment]
有些不成熟的想法，仅供参考：

主要是因为这几个看着是孤立的悬浮按钮，又小，相近的颜色中容易被淹没。
除了`强调色`用于表示打开了自动亮度，主题设置里就剩 3 个颜色了。在正文背景色和字体色相间中，要想看的清，小按钮就要有些不同于这2个的第3种色调。它背景色目前是和底栏一致的。要给图标着色就只剩选文字或者顶栏颜色了。
白天主题，底栏颜色和正文背景色反差大，底部4个看的清；不过自动亮度关闭状态的按钮就不明显了。
夜晚主题，整体期望黑色多一些，顶栏、正文背景、底栏差异小，底部4个就被淹没了；亮度调节那里区域大对比又好了。

总体上看，我感觉再加一个颜色：`小按钮图标色`，这样比较容易兼顾多种场景，可以给用户自定义……

另外，底部 4 个其实只有一个颜色，并没有激活状态色，一点就切换到新的界面了。

又 P 了蓝、绿两个色调的示意图：

自动亮度**关**

![legado-icon-color-b-a-off](https://user-images.githubusercontent.com/19585474/104450288-d6359780-55da-11eb-8d04-463caf1b3365.png)
![legado-icon-color-g-a-off](https://user-images.githubusercontent.com/19585474/104450324-e51c4a00-55da-11eb-8630-20d415e5823e.png)

自动亮度**开**

![legado-icon-color-b-a-on](https://user-images.githubusercontent.com/19585474/104450355-ef3e4880-55da-11eb-8bc6-53bd73ece9d7.png)
![legado-icon-color-g-a-on](https://user-images.githubusercontent.com/19585474/104450373-f49b9300-55da-11eb-9d2e-10833aa7038b.png)

**Comment by lifenjoiner** [comment]
另一个方案：
把自动/手动亮度切换图标，和白天/夜晚切换图标一样，做成两个不同的，这样就不用亮起表示打开了，也可以所有图标统一颜色。
