### ISSUE TITLE
更新之后以前缓存的小说不见了

### ISSUE THREAD

**Issue by baby528** [gedoor/legado#795]
之前应该是3.0的低版本，从52pojie.cn更新3.20.031215版，以及该网站提供的6220书源、182净化规则，再打开以前的小说缓存的章节都没了，重新搜小说，也只能看到目录，内容都是空白，怎么办呢？

**Comment by baby528** [comment]
安装的安卓版

**Comment by SplitGemini** [comment]
换源，内容空白只能用于发现。
缓存好了就不要随便换源了
