### ISSUE TITLE
两个想法，有条件的情况下希望可以实现

### ISSUE THREAD

**Issue by lunhuil** [gedoor/legado#798]
### 功能描述
1.主题，背景，封面，排版 导出和导入进行整合
2.规则，主题等可以一键分享至第三方文本分享网站，
如 
https://pasteme.cn/
http://netcut.cn/
>
### 期望实现方式
1.1 总体可在主题菜单中操作，导入导出时提供主题，背景，封面，排版 选项勾选，比如现在的“恢复忽略列表”那样。
1.2 导出可压缩成一个压缩包或一个文本（封面和背景可转换成Base64，这样就可以以文本形式分享）
>

**Comment by hhaoao** [comment]
希望加个文本排序功能,不是帮助文档里说的情况,是本来就是反序的.[新人必读](https://github.com/gedoor/legado/blob/master/app/src/main/assets/help/appHelp.md)
![aaa](https://user-images.githubusercontent.com/11269610/104837300-99c1ae80-58ee-11eb-9b3d-ccec80538fb1.png)

**Comment by Antecer** [comment]
这个文本反序的问题,写书源的人可以解决.

**Comment by hhaoao** [comment]
> 这个文本反序的问题,写书源的人可以解决.

@Antecer 经你提醒,我终于知道我想要什么体验了,就是少个评价书源的地方,几千个源没人告诉你哪个源相对于这本书是最优质的,再多也没用.

**Comment by SplitGemini** [comment]
> > 这个文本反序的问题,写书源的人可以解决.
> 
> @Antecer 经你提醒,我终于知道我想要什么体验了,就是少个评价书源的地方,几千个源没人告诉你哪个源相对于这本书是最优质的,再多也没用.

这个有点太复杂，用经常更新的人提供的书源可以解决大部分问题

**Comment by 52fisher** [comment]
正文文本反序，可在正文规则后面加入
@js: result.split("").reverse().join("")
