### ISSUE TITLE
ChapterProvider ERROR[BUG] 

### ISSUE THREAD

**Issue by SplitGemini** [gedoor/legado#799]
### 机型（如Redmi K30 Pro）
>  k30

### 安卓版本（如Android 7.1.1）
> 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.011221

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 电信

### 问题描述（简要描述发生的问题）
> ChapterProvider ERROR
![Screenshot_2021-01-13-18-05-24-144_io legado app release](https://user-images.githubusercontent.com/34861918/104447619-ffecbf80-55d6-11eb-9a2c-59607a25cbc0.jpg)

### 使用书源（填写URL或者JSON）
> 大概不重要

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 见视频

https://user-images.githubusercontent.com/34861918/104448025-94efb880-55d7-11eb-982a-6e5c280400de.mp4

### 日志提交（问题截图或者日志）
> 日志里啥也没有

### 猜测
> 大概是净化替换的正则写的太多太费时，在同一个list里协程冲突了
> 用的净化替换规则 [https://gitee.com/SplitGemini/ReplaceRules/raw/master/exportReplaceRule.json](https://gitee.com/SplitGemini/ReplaceRules/raw/master/exportReplaceRule.json)，主要针对“通用长垃圾集和”

**Comment by gedoor** [comment]
好的,我试试
