### ISSUE TITLE
[Feature Request] 要求继续发压缩代码版本

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#807]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
因为正常代码版本下部分书源和订阅源无法使用，只有压缩代码版本才能使用。
### 期望实现方式（阅读应该如何实现该功能）
> 在发正常代码版本时，同时也发个压缩代码的版本。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by SplitGemini** [comment]
哪有压缩体积版本

**Comment by sartonsh** [comment]
前面发了好几个吧

**Comment by SplitGemini** [comment]
> 前面发了好几个吧

前面根本没有

**Comment by Antecer** [comment]
之前只听说压缩版本无法使用部分书源,这咋还出现正常版本无法使用的书源?
你给贴几个正常版本无法使用的书源上来做个测试.

**Comment by sartonsh** [comment]
不世玄奇的全网搜书系列，以及修复书源合集中的部分书源。
我之前发了个帖子有说。

**Comment by sartonsh** [comment]
> > 前面发了好几个吧
> 
> 前面根本没有

每次发布正式版本时同时发布的测试版。就前几次有。

**Comment by sartonsh** [comment]
> 之前只听说压缩版本无法使用部分书源，这咋还出现正常版本无法使用的书源？
> 你给贴几个正常版本无法使用的书源上来做个测试。

我的正常版本好像对部分@js支持不太好，压缩版本就没问题。之前Celeter说他用压缩版本不能用的书源，我试了下可以用。挺奇怪的。

**Comment by gedoor** [comment]
这就奇怪了,压缩版本才会少东西啊

**Comment by 10bits** [comment]
不是说了吗，你系统版本太低，android6.0的问题，有bug别人也没办法帮你测试的

https://stackoverflow.com/questions/44663228/multidex-throws-java-lang-noclassdeffounderror-rxjava-retrolambda

**Comment by sartonsh** [comment]
所以说希望大佬继续发个压缩版，我用的挺好。

**Comment by sartonsh** [comment]
> 这就奇怪了，压缩版本才会少东西啊

对我来说，压缩版最合适。最近两个版本没压缩版本了，我都没更新了。
