### ISSUE TITLE
[BUG]近期朗读经常失效，出现大范围跳过内容，或者不启动 

### ISSUE THREAD

**Issue by wangshujun-tj** [gedoor/legado#809]
### 机型（如Redmi K30 Pro）
>小米6，华为P40

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.011819，近期连续升级版本，问题频繁发生

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>多种网络环境

### 问题描述（简要描述发生的问题）
>朗读无法启动，或者跳过段落，似乎是百度朗读接口问题，华为的本地tts是正常的

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by luotingv1** [comment]
我也遇到了这个问题

**Comment by Celeter** [comment]
接口失效了，不是bug

**Comment by db-one** [comment]
https://github.com/gedoor/legado/pull/810

根据这个把参数改为pdt=30了，就可以了，如果是接口失效不是应该完全不能用吗？

**Comment by luotingv1** [comment]
> #810
> 
> 根据这个把参数改为pdt=30了，就可以了，如果是接口失效不是应该完全不能用吗？

哪里修改

**Comment by db-one** [comment]
直接点语音TTS选择人物那里   后面有编辑按钮
找到DPT参数把默认的1改成30

**Comment by Celeter** [comment]
> #810
> 
> 根据这个把参数改为pdt=30了，就可以了，如果是接口失效不是应该完全不能用吗？

接口里的参数参数是用来鉴别用户的，这个用户没用使用这个接口的权限，难道不是失效吗

**Comment by db-one** [comment]
学习了  我不知道这个参数是干吗的

**Comment by lywwl** [comment]
无论改成什么都不可以用。
