### ISSUE TITLE
[Feature Request] 加载大量文本，正文显示耗时长问题

### ISSUE THREAD

**Issue by YumikoAzu** [gedoor/legado#815]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 对于加载大量文本(就是一章能有百页以上的)，正文显示花费时间长。能否不进行整个章节完全分好页再显示？就是先分出几页显示出来给用户看，后台再继续进行分页逻辑(举例-一个章节实际分页出来有80页，先把这个章节的文本进行分页，分出来两三页后立即显示给用户看，让用户不在等待，后台则继续进行分页计算。)

### 期望实现方式（阅读应该如何实现该功能）
> 最好能够实现用户要看的内容马上展示出来，后台继续进行分页逻辑。(文字要被一页页地展示给用户，分页计算是无可避免的。既要进行分页计算，又要降低分页计算的耗时，只有采用懒加载，推迟不必要的计算，只计算马上需要展示给用户的分页。)
例如多看阅读:
![AB2AB5DA-D37C-4B57-8BBA-CA14570FA440](https://user-images.githubusercontent.com/13196251/105181554-ea434100-5b66-11eb-9f06-f3046dee3be3.png)
用户看的那个章节，最先加载的一页显示出来，然后后台还在继续进行分页逻辑。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by zhj9709** [comment]
确实有点慢，阅读本地txt时，章节页数十几二十页，跳转到其他章节时，要加载很久

**Comment by zhj9709** [comment]
![image](https://user-images.githubusercontent.com/13991774/109276887-8a207880-7851-11eb-9125-1efe5f036aeb.png)
在线资源，106页，加载几分钟。。。
