### ISSUE TITLE
[Feature Request] APP中增加退出程序的按钮或者菜单

### ISSUE THREAD

**Issue by wqfantexi** [gedoor/legado#819]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 电纸书中没有实体按键，无法退出程序，希望能加个按钮可以退出去出去

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
没用返回按钮吗

**Comment by gedoor** [comment]
好的
