### ISSUE TITLE
[BUG] 无法打开本地文件 Permission denied

### ISSUE THREAD

**Issue by zybjyy** [gedoor/legado#820]
### 机型（如Redmi K30 Pro）
>vivo iqoo7

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.012120

### 问题描述（简要描述发生的问题）
>无法打开本地文件

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>本地txt文件，选择打开方式-阅读后，提示Permission denied，并且无法打开。

>存储权限中，只有“媒体文件”选项，没有“所有文件”选项

### 日志提交（问题截图或者日志）
>
![Screenshot_20210125_165153](https://user-images.githubusercontent.com/77959882/105682699-b92f8b80-5f2d-11eb-8976-de88d7e56b7c.jpg)
![Screenshot_20210125_164540](https://user-images.githubusercontent.com/77959882/105682009-d9127f80-5f2c-11eb-8e4d-072a5f7a21b9.jpg)
![Screenshot_20210125_164546](https://user-images.githubusercontent.com/77959882/105682061-e891c880-5f2c-11eb-8d03-2ceab1cfced0.jpg)

对比其他应用：

![Screenshot_20210125_164559](https://user-images.githubusercontent.com/77959882/105682090-f6474e00-5f2c-11eb-927f-89d6d2366466.jpg)

**Comment by 52fisher** [comment]
安卓11请尽量在阅读中添加并打开。
