### ISSUE TITLE
网页在线阅读增加手机中的语音合成

### ISSUE THREAD

**Issue by vicguo0724** [gedoor/legado#825]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 网页在线阅读新版中增加手机中的语音合成

**Comment by Celeter** [comment]
浏览器自带不是有吗

**Comment by vicguo0724** [comment]
> 浏览器自带不是有吗?用手机上的话需要时间去下载音频，再传到电脑，延迟肯定很高

浏览器自带的很难听，我尝试过Natural Reader Text to Speech插件，但是不是很好用，有什么好用的推举吗？

**Comment by Celeter** [comment]
> > 浏览器自带不是有吗?用手机上的话需要时间去下载音频，再传到电脑，延迟肯定很高
> 
> 浏览器自带的很难听，我尝试过Natural Reader Text to Speech插件，但是不是很好用，有什么好用的推举吗？

edge自带大声朗读
