### ISSUE TITLE
书架界面的书籍显示上希望能参考起点UI改进

### ISSUE THREAD

**Issue by casselluu** [gedoor/legado#827]
> 主要是作者字号改小，不显示正在阅读章节，改为显示未读章节数

**Comment by zmn001125** [comment]
有显示未读章节数呀

**Comment by casselluu** [comment]
> 有显示未读章节数呀

不是说没有，是希望能把正在阅读的章节这行改为显示未读章节数目，一是因为如果读到最新章，就会出现两行重复文字，别扭且浪费，此外书籍有关信息最后都在屏幕靠左，方便关注。怎么说呢，起点的阅读器真的是用习惯了觉得有很多设计上的优点，可以用来'参考'

**Comment by 1274003856** [comment]
土豪的世界我们不懂，我们只要阅读模式
 土豪~~起点模式只适合土豪~土豪就是土豪
作者文字小了~真心不行啊。

**Comment by zhj9709** [comment]
我还觉得现在这种挺好的，而且不能为了你一个人的需求就改变大家的习惯，你可以反馈说加一个这样的设置切换显示格式，但也不能希望把以前的UI直接改掉吧

**Comment by casselluu** [comment]
> 我还觉得现在这种挺好的，而且不能为了你一个人的需求就改变大家的习惯，你可以反馈说希望加一个这样的设置切换显示格式，但也不能希望把以前的UI直接改掉吧

我只是提出改进意见，而且什么叫改变大家习惯。提出的改进方向是参考起点设计，绝对比个人设计的好，此外我提到了读到最新章节后会出现两行重复信息，这就是资源浪费，所以希望能改一下，又没有必须要求去做。如果不是因为gradle的本地配置麻烦，我早就上手改成自己想要的

**Comment by zhj9709** [comment]
> > 我还觉得现在这种挺好的，而且不能为了你一个人的需求就改变大家的习惯，你可以反馈说希望加一个这样的设置切换显示格式，但也不能希望把以前的UI直接改掉吧
> 
> 我只是提出改进意见，而且什么叫改变大家习惯。提出的改进方向是参考起点设计，绝对比个人设计的好，此外我提到了读到最新章节后会出现两行重复信息，这就是资源浪费，所以希望能改一下，又没有必须要求去做。如果不是因为gradle的本地配置麻烦，我早就上手改成自己想要的

好吧，刚找了几张起点的书架图看了一下，感觉还可以，就是那个多少小时前感觉没必要显示，毕竟不同书源更新的时候可能不同。我觉得如果你会改的话，可以改一下，直接发一个pr请求。gradle配置应该也不是特别麻烦吧

**Comment by casselluu** [comment]
> > > 我还觉得现在这种挺好的，而且不能为了你一个人的需求就改变大家的习惯，你可以反馈说希望加一个这样的设置切换显示格式，但也不能希望把以前的UI直接改掉吧
> > 
> > 
> > 我只是提出改进意见，而且什么叫改变大家习惯。提出的改进方向是参考起点设计，绝对比个人设计的好，此外我提到了读到最新章节后会出现两行重复信息，这就是资源浪费，所以希望能改一下，又没有必须要求去做。如果不是因为gradle的本地配置麻烦，我早就上手改成自己想要的
> 
> 好吧，刚找了几张起点的书架图看了一下，感觉还可以，就是那个多少小时前感觉没必要显示，毕竟不同书源更新的时候可能不同。我觉得如果你会改的话，可以改一下，直接发一个pr请求。gradle配置应该也不是特别麻烦吧

IJ导入项目后就是gradle报错，版本不匹配，我折腾了一上午都没弄成，最后放弃了。虽然是最新的IJ但和4.1就是不匹配

**Comment by zhj9709** [comment]
> > > > 我还觉得现在这种挺好的，而且不能为了你一个人的需求就改变大家的习惯，你可以反馈说希望加一个这样的设置切换显示格式，但也不能希望把以前的UI直接改掉吧
> > > 
> > > 
> > > 我只是提出改进意见，而且什么叫改变大家习惯。提出的改进方向是参考起点设计，绝对比个人设计的好，此外我提到了读到最新章节后会出现两行重复信息，这就是资源浪费，所以希望能改一下，又没有必须要求去做。如果不是因为gradle的本地配置麻烦，我早就上手改成自己想要的
> > 
> > 
> > 好吧，刚找了几张起点的书架图看了一下，感觉还可以，就是那个多少小时前感觉没必要显示，毕竟不同书源更新的时候可能不同。我觉得如果你会改的话，可以改一下，直接发一个pr请求。gradle配置应该也不是特别麻烦吧
> 
> IJ导入项目后就是gradle报错，版本不匹配，我折腾了一上午都没弄成，最后放弃了。虽然是最新的IJ但和4.1就是不匹配

Android Studio呢

**Comment by casselluu** [comment]
> > > > > 我还觉得现在这种挺好的，而且不能为了你一个人的需求就改变大家的习惯，你可以反馈说希望加一个这样的设置切换显示格式，但也不能希望把以前的UI直接改掉吧
> > > > 
> > > > 
> > > > 我只是提出改进意见，而且什么叫改变大家习惯。提出的改进方向是参考起点设计，绝对比个人设计的好，此外我提到了读到最新章节后会出现两行重复信息，这就是资源浪费，所以希望能改一下，又没有必须要求去做。如果不是因为gradle的本地配置麻烦，我早就上手改成自己想要的
> > > 
> > > 
> > > 好吧，刚找了几张起点的书架图看了一下，感觉还可以，就是那个多少小时前感觉没必要显示，毕竟不同书源更新的时候可能不同。我觉得如果你会改的话，可以改一下，直接发一个pr请求。gradle配置应该也不是特别麻烦吧
> > 
> > 
> > IJ导入项目后就是gradle报错，版本不匹配，我折腾了一上午都没弄成，最后放弃了。虽然是最新的IJ但和4.1就是不匹配
> 
> Android Studio呢

l懒得再去折腾了，另外多少小时更新这个没必要，主要是读到最新章后会出现两行一样的章节信息，把其中一个改成多少章未读或已经读到最新章节就更好一些。
主要都是一些细节上的优化，无关紧要，所以懒得再去折腾
