### ISSUE TITLE
希望能增加一个订阅板块的待阅列表

### ISSUE THREAD

**Issue by kevking** [gedoor/legado#828]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望能增加一个订阅板块的待阅列表。在浏览订阅板块时，遇到感兴趣的内容，可以右滑标题，加入待阅列表中。待阅列表参照音乐类APP，可以顺序朗读列表内的文章。

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 1274003856** [comment]
这会增加手机内存，而且很多时候，你待遇内容太多，不阅读不就麻烦啊
