### ISSUE TITLE
[Feature Request] 希望能增加在书架搜索书籍的功能

### ISSUE THREAD

**Issue by b286951543** [gedoor/legado#829]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在书架搜索，而不是在数源里搜

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by lunhuil** [comment]
这个功能有的，搜索就是书架，网上二合一

**Comment by zhj9709** [comment]
![image](https://user-images.githubusercontent.com/13991774/109096929-6aa62480-7759-11eb-8159-ad5ae35084ee.png)
