### ISSUE TITLE
[Feature Request] 关屏后也可以使用Headset buttons are always available

### ISSUE THREAD

**Issue by gzyguo** [gedoor/legado#834]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 按media_play_pause button, 听书开始

### 期望实现方式（阅读应该如何实现该功能）
> app退出后+关屏后

### 附加信息（其他的与功能相关的附加信息）
> 现在需要 APP跑到前边来才可以，但是息屏后APP好像不太能跑到前面来，其实他跑到前面来都可以退一步接受，但是息屏没办法开始播放，是指退出后，

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
有个配置,退出后也可以生效

**Comment by gzyguo** [comment]
> 有个配置,退出后也可以生效

嗯我知道那个选项，现在就是希望能够 兼容屏幕熄灭时，也能够正常工作 ，再进一步 可选择的 兼容最后使用的播放器不是 legado的情况，比如刚刚用音乐APP在播放听歌
