### ISSUE TITLE
[Feature Request] 别的播放器开始播放音乐的时候听书自动停止，

### ISSUE THREAD

**Issue by gzyguo** [gedoor/legado#835]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 别的播放器开始播放音乐的时候听书自动停止，

### 期望实现方式（阅读应该如何实现该功能）
> 就是别的播放器开始播放音乐的时候听书自动停止啦

### 附加信息（其他的与功能相关的附加信息）
> 读书的时候如果开始播放音乐听书并不会停，希望可以选择让听书自动停止，当然，反过来也希望可以选择是这样，在播放音乐的时候开始听书的话，音乐自动停止，并且切换到听书以后耳机的播放按键可以控制听书，再反过来也是，如果听书的时候开始播放音乐，可以选择之后的耳机播放按键控制音乐，也就是希望可以选择，让按键，对，最后一个，使用的APP，有效，谢谢！

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的,我加个开关
