### ISSUE TITLE
[Feature Request] 希望桌面图标长按的快捷方式后台开始TTS

### ISSUE THREAD

**Issue by gzyguo** [gedoor/legado#836]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 是叫shortcut bubble吗，一键TTS

### 期望实现方式（阅读应该如何实现该功能）
> 最好不需要app必需跑到前边才能开始…

### 附加信息（其他的与功能相关的附加信息）
> 发现用别的放了音乐，听书又退出了，耳机键就不能一键听书了，这时候就需要一个快捷方式，这是啰唆的话啦，总之这样大家用得上，我也用得上，完美

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 52fisher** [comment]
你都没打开书籍....怎么确定你想听哪一本
而且阅读在听书的时候通知栏有相应的按钮

**Comment by gzyguo** [comment]
你都没打开书籍....怎么确定你想听哪一本
最后打开过的那本就行

而且阅读在听书的时候通知栏有相应的按钮
那个按钮有时候没有长弹的好用

谢谢

**Comment by 1274003856** [comment]
添加桌面快捷方式~不现实~很多人的手机桌面，上百个应用图标，翻都累死人啊。
状态栏的那个 图标才是最好的。

**Comment by gzyguo** [comment]
> 添加桌面快捷方式~不现实~很多人的手机桌面，上百个应用图标，翻都累死人啊。
> 状态栏的那个 图标才是最好的。

并不是希望去掉状态栏的图标啊，而且想要去掉的话在手机操作就可以了，不需要跑到这里来啊去掉啊，那些桌面图标上百的人，很多，状态栏的图标也不少，当然我也知道，有些人的状态栏没有很多图标，有些人会更少，但我并没有关于现实的数据，所以如果说什么样是现实的的话，我不知道，我只知道很多APP都会在长按图标的地方添加快捷方式，包括这个APP也是，现在已经有长按继续阅读的功能，

**Comment by gedoor** [comment]
可以的
