### ISSUE TITLE
希望订阅源的内容页-增加夜间模式按钮-不然夜晚看阅读-订阅源-任意内容页太伤眼睛了

### ISSUE THREAD

**Issue by 1274003856** [gedoor/legado#837]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望阅读-订阅源-任意内容页-增加-夜间模式按钮。-主要为了夜晚不伤眼睛

### 期望实现方式（阅读应该如何实现该功能）
> 就是在  阅读-订阅源-内容页的收藏按钮的前面添加个  夜间模式  按钮即可
就像下图这样即可  https://s3.ax1x.com/2021/02/02/ynFCSe.jpg

### 附加信息（其他的与功能相关的附加信息）
> 主要是这样能让夜晚都能好好用啊  不伤眼睛啊。

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 52fisher** [comment]
如果你的手机有深色模式的话，请在运行阅读时开启。
