### ISSUE TITLE
[功能请求]上下滑动翻页

### ISSUE THREAD

**Issue by QYY799** [gedoor/legado#838]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 上下滑动翻页

### 期望实现方式（阅读应该如何实现该功能）
> 加个翻页方式

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by zmn001125** [comment]
![Uploading IMG_20210205_183520.jpg…]()

**Comment by zmn001125** [comment]
界面->滚动
