### ISSUE TITLE
[Feature Request]  希望繁体转换简体可以参考繁化姬这个项目

### ISSUE THREAD

**Issue by dianso** [gedoor/legado#839]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
有些简体转换繁体或繁体转换简体，转出来错误很多

建议使用zhconvert.org这个api，我试了这个转换后一些词组能正确被转换

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Celeter** [comment]
你想使用接口的话，可以在正文里调用，把繁简转换改成接口，实用性不高

**Comment by 10bits** [comment]
简繁转换最好的是opencc，想要效果好还要做好分词，还要做自然语言处理，不是那么容易的事
