### ISSUE TITLE
[BUG] 一点击就闪退

### ISSUE THREAD

**Issue by zqhjl** [gedoor/legado#846]
### 机型（如Redmi K30 Pro）
> 华为畅享9Plus

### 安卓版本（如Android 7.1.1）
> Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.020316

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动宽带

### 问题描述（简要描述发生的问题）
> 一点开就闪退，而在酷安论坛中提问后有人回复说，同机型没有这个问题，所以搞不懂为什么

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 据说无法复现

### 日志提交（问题截图或者日志）
> 不知道在哪里找日志…
> 我放个录屏

https://user-images.githubusercontent.com/61345763/107319714-54059980-6ada-11eb-8786-a45a3fd524dd.mp4

**Comment by zmn001125** [comment]
卸载重装试试

**Comment by zqhjl** [comment]
> 卸载重装试试

试过了…我甚至尝试了几个历史版本和2.0，都会闪退，2.0相对好一些，偶尔能不闪退

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持
