### ISSUE TITLE
[BUG] 打开本地epub不显示图片，替换净化已经关闭了

### ISSUE THREAD

**Issue by maxshq** [gedoor/legado#847]
### 机型（如Redmi K30 Pro）
>Google Pixel3XL

### 安卓版本（如Android 7.1.1）
>11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>legado_app_3.21.020316

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>打开本地epub不显示图片，替换净化已经关闭了

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by wuzeqingit** [comment]
目前导入的epub只支持文本，不支持图片。帮助文档有写。https://github.com/gedoor/legado/blob/master/app/src/main/assets/help/appHelp.md#%E6%9C%AC%E5%9C%B0%E4%B9%A6%E7%B1%8D%E7%9B%B8%E5%85%B3

**Comment by maxshq** [comment]
> 目前导入的epub只支持文本，不支持图片。帮助文档有写。https://github.com/gedoor/legado/blob/master/app/src/main/assets/help/appHelp.md#%E6%9C%AC%E5%9C%B0%E4%B9%A6%E7%B1%8D%E7%9B%B8%E5%85%B3

哦哦，但是我记得之前某个版本能看epub里的图片
