### ISSUE TITLE
[Feature Request] 希望增加疲劳锁定提醒功能

### ISSUE THREAD

**Issue by dwphic** [gedoor/legado#850]
### 原因及需求
* 第三方锁机应用适配性不好，各类设备特别是墨水屏设备权限设置魔改严重，使用不方便。
* 需多种定义，如
  * 锁定 n 分钟
  * 每日累计阅读 n 分钟后锁定
  * 每连续阅读 n 分钟后锁定
  _* 定时锁定，如 23:00 锁定（废）_
  * 时间段之内锁定。如 23:00 - 07:00 锁定，当 23:34 点击时无法阅读。
### 参考
* 禅定空间
* 静读天下

**Comment by 1274003856** [comment]
用处不大啊，你这就是定时杀死阅读进程啊，很多人都是不看了，不听了，直接退出阅读吧

**Comment by dwphic** [comment]
不是杀进程，是按规则触发疲劳提醒的Activity，参考静读天下。防沉迷用的。不是所有人自制力都强，前两天有个朋友孩子高二躲被窝沉迷小说，晚上睡不着白天不上学。虽说不是阅读造成的，但还是希望阅读有独立的防沉迷功能。
