### ISSUE TITLE
[BUG] 文字内容被异常覆盖

### ISSUE THREAD

**Issue by lqfy-jhc** [gedoor/legado#851]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>7.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.020316 (7256)

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>文章原文没有问题，但阅读APP加载后，显示出来的文章部分文字被同音字覆盖，看着很难受，已发现被替换文字【拾-->十】

### 使用书源（填写URL或者JSON）
>所有书源(已测试与书源无关，进入书源所在的网站小说内容正常)

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>任意建立一个【txt文档名为：拾】【章节名：拾】【内容：拾】导入阅读APP，可以看到，书籍名正常，在目录页中章节名正常，在正文页中章节名与正文都被替换修改，已禁用所有替换规则并禁用替换
![Screenshot_20210217094821](https://user-images.githubusercontent.com/59348827/108145679-cd1e7580-7106-11eb-936f-fdacc18962ea.png)

### 日志提交（问题截图或者日志）
>
![Screenshot_20210217094821](https://user-images.githubusercontent.com/59348827/108146781-c42ea380-7108-11eb-9422-ae7ab9641ca7.png)

**Comment by Antecer** [comment]
关掉简繁&繁简转换
