### ISSUE TITLE
希望优化下漫画阅读

### ISSUE THREAD

**Issue by airchaoz** [gedoor/legado#852]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 只有一章漫画全部缓存完毕时才会显示出图片，不能够加载好一张图片就显示一张图片。而且对于几百页的单本漫画，即使缓存好也无法加载出来，会占用大量内存。

### 期望实现方式（阅读应该如何实现该功能）
> 像网页一样，加载好一张图片就显示一张图片，而且优先加载当前浏览位置的图片

**Comment by 1274003856** [comment]
这不现实，因为爬虫做不到的。只能一起抓取的。
主要还是 漫画图片链接速度慢的问题。推荐直接使用网页看

**Comment by airchaoz** [comment]
> 这不现实，因为爬虫做不到的。只能一起抓取的。
> 主要还是 漫画图片链接速度慢的问题。推荐直接使用网页看

爬虫爬的时候可以不用加载图片资源，只需要爬去图片的url，加载画面阅读的时候再一一加载图片就好了。

**Comment by Celeter** [comment]
阅读主要是看文字内容而不是图片，要看图片的话推荐异次元

**Comment by akira-hit** [comment]
最近在查找源的时候发现有漫画源。试着用了下，图片加载一页较慢。然后就想办法解决。
尝试把图片页当目录页解析。发现章节解析页里提交图片地址，返回的是二进制数据，结果解析页当UTF8处理了。
遂目录页面-章节地址提交<img src=“”>,章节解析页空置或者用{{baseurl}}可以解决。
用是能用了，但是可以添加个在章节页可以直接解析图片的功能吗？

我怕说的不明白。
附加个书源数据
{
  "bookSourceComment": "",
  "bookSourceGroup": "画",
  "bookSourceName": "🔞 旧漫兜",
  "bookSourceType": 0,
  "bookSourceUrl": "https://mandou.info/",
  "customOrder": 0,
  "enabled": true,
  "enabledExplore": true,
  "exploreUrl": "全部::https://mandou.info/page/{{page}}",
  "lastUpdateTime": 1618295987313,
  "ruleBookInfo": {
    "coverUrl": "",
    "intro": ".cat-tag div.single-post-category,.tag_area a@text&&[property=\"og:title\"]@content##サークル・作者\\n|原作\\n\n\n<js>\na=result.split('\\n');\nb=a[a.length-1];\na.splice(-1,1)\nresult=' 🔖'+a.join(' 🔖')+'\\n'+b;\n</js>\n",
    "kind": "",
    "lastChapter": "time[class=\"single-post-date published updated\"]@text"
  },
  "ruleContent": {
    "content": "",
    "imageStyle": "FULL",
    "nextContentUrl": ""
  },
  "ruleExplore": {},
  "ruleSearch": {
    "author": "a@title##(【.+?】)##$1###",
    "bookList": "article[class=\"grid_post-box\"]",
    "bookUrl": "a@href",
    "coverUrl": "img@data-src",
    "kind": "a[rel]@text",
    "name": "a@title##【.+?】"
  },
  "ruleToc": {
    "chapterList": "div[class=\"content\"]@a",
    "chapterName": "@img[itemprop=\"contentUrl\"]@alt##\\D",
    "chapterUrl": "@href##(.+)##<img src=\"$1\">###",
    "nextTocUrl": "link[rel=\"next\"]@href"
  },
  "searchUrl": "https://mandou.info/?s={{key}}",
  "weight": 0
}

**Comment by 1274003856** [comment]
你直接做成订阅源~不就可以了

**Comment by akira-hit** [comment]
恩。楼上是在回复我么。那啥订阅源还不会用。
