### ISSUE TITLE
[Feature Request] 建议添加opds书库书籍的阅读和下载、rss订阅两个功能

### ISSUE THREAD

**Issue by yunchee** [gedoor/legado#853]
### 功能描述
> 
opds书籍订阅、rss订阅号订阅。
### 期望实现方式
> 
opds书籍订阅，在右上角菜单栏里选择“添加网址”或者“添加网络书籍”，然后弹出子菜单“电子书文件”、”opds“等。选择opds后，用户输入opds网址、用户名、密码后成功登入opds。
rss订阅应该不用多说，都懂。本来以为阅读有rss但一直没用上，刚测试了一下才知道居然新增订阅源里没有rss选项。。
：订阅页面，新增订阅源，选择rss，新增，用户填入地址、名称等。
### 附加信息（其他的与功能相关的附加信息）
> 提供opds书源：http://www.cbeta.org/opds/ 可以用这个测试
rss的话，嗯提供这个吧：http://csyglhh.com/rss

opds阅读可参照ALreader这个app，手机乐园有（菜单-打开-风格书库-添加目录）
rss订阅可参照rolly rss reader这个app，酷安能搜到

### 效果演示
>https://sharechain.qq.com/d748fa5f5613c539af077269b4fe5c59

这是ALREADER和ROLLY新增源的演示。github上不去图片，没梯子，用微云凑合看吧

**Comment by zmn001125** [comment]
rss地址直接新建订阅源填在源url保存就可以用了

**Comment by yunchee** [comment]
那opds呢，没法添加。跟rss差不多



---原始邮件---
发件人: "zmn001125"<notifications@github.com&gt;
发送时间: 2021年2月18日(周四) 下午4:30
收件人: "gedoor/legado"<legado@noreply.github.com&gt;;
抄送: "yunchee"<1410434961@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [gedoor/legado] [Feature Request] 建议添加opds书库书籍的阅读和下载、rss订阅两个功能 (#853)




 
rss地址直接新建订阅源填在源url保存就可以用了
