### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by axin-plus** [gedoor/legado#855]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
为什么软件会自动变大

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by axin-plus** [comment]
用户数据一直变大 之前没有这种情况

**Comment by 52fisher** [comment]
缺乏有用信息，等待补充
