### ISSUE TITLE
[Feature Request] 协议唤起和密码锁

### ISSUE THREAD

**Issue by tomtrije** [gedoor/legado#856]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
1、协议唤起
- 当前有协议唤起书源和订阅源导入的能力，但是唤起App暂时不支持。
- 添加协议唤起，可以在一些特殊设备上通过浏览器唤起App（比如：Yota3的背面阅读屏）
- 之前已在2.0版本中自己fork实现过，但是还是希望这个功能能作为基础功能提供给大众
2、密码锁
- 有了自定义源之后，总有一些敏感的订阅信息不适合拿到手机就能看到的
- 最好能区分书架、订阅分别设置锁，在进入activity的时候做解锁，最low可以是启动密码
- 同步/备份能包含密码（低优先级）
### 期望实现方式（阅读应该如何实现该功能）
> 
1、协议唤起
- 在AndroidManifest.xml中WelcomeActivity/MainActivity下添加唤起协议，类似ImportBookSourceActivity
- 协议参考：yuedu://homepage
2、密码锁
- 不太了解怎么实现，能完成功能可用即可
- 密码的存储还是要加密的

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 1274003856** [comment]
阅读~设置~其他设置~显示订阅~右面不点红(就是红在左面)
你返回阅读首页~就不会显示~订阅了
这个比你说的好多了
毕竟，在软件加锁等，朋友看了你也不好意思啊
直接不显示~大法才是最好滴。

**Comment by tomtrije** [comment]
> 阅读~设置~其他设置~显示订阅~右面不点红(就是红在左面)
> 你返回阅读首页~就不会显示~订阅了
> 这个比你说的好多了
> 毕竟，在软件加锁等，朋友看了你也不好意思啊
> 直接不显示~大法才是最好滴。

这个功能是知道的，也是当前在用的。也可以针对这个设置做加密，毕竟当前是可以随意打开的
