### ISSUE TITLE
[BUG]  恢复备份需要多次重新打开软件，恢复两次才能恢复到备份前

### ISSUE THREAD

**Issue by zhj9709** [gedoor/legado#859]
### 机型（如Redmi K30 Pro）
> 小米note3，魅族MX5

### 安卓版本（如Android 7.1.1）
> 安卓9，安卓5.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.20.xxxx，3.21.xxxx

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动，联通，电信

### 问题描述（简要描述发生的问题）
> 恢复备份需要多次重新打开软件，恢复两次才能恢复到备份前

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 1. 备份
> 2. 清除软件数据(全部数据)
> 3. 第一次恢复，会先恢复阅读列表，书架，记录，书源等。但软件设置未恢复。(比如软件的主题，进入阅读界面后里面的设置，还有我没有显示订阅，但第一次恢复后还是显示的)
> 4. 第一次恢复后，需要先关闭软件后，再进行第二次恢复，但我是关闭订阅的，恢复后，在`我的`界面，显示的是订阅的界面。
> 5. 关闭软件后，再次打开，这时会恢复到备份前的样子。

**2.0不会有这样的问题**

### 日志提交（问题截图或者日志）
>

**Comment by 1274003856** [comment]
恢复后~退出软件，再次进去阅读就可以了的
你是恢复后，返回阅读首页就会这样的
阅读~设置~备份与恢复~恢复忽略列表
你可能有内容勾选了

**Comment by zhj9709** [comment]
> 恢复后~退出软件，再次进去阅读就可以了的 你是恢复后，返回阅读首页就会这样的 阅读~设置~备份与恢复~恢复忽略列表
> 你可能有内容勾选了

忽略列表没有勾选，而且只退出再重新进阅读不恢复一次不行的
如果设置显示订阅了，只要恢复一次后，重新进阅读再恢复一次就行了，如果不显示订阅，需要在第二次恢复后再重新进入阅读。

**Comment by gedoor** [comment]
好的,我看看

**Comment by zhj9709** [comment]
2021/02/26更新有一条 
- 修复恢复bug

但经过测试，bug仍然存在，需要至少恢复两次
用了两部手机+win上的安卓模拟器测试
包括
小米note3 MIUI11 安卓9
魅族MX5 flyme6 安卓5.1
雷电模拟器 安卓7.1.2

**Comment by gedoor** [comment]
我再看看

**Comment by sunrisewestern** [comment]
我恢复重进四五次都不行，每次都要搞到坚果云检测异常把我封了
