### ISSUE TITLE
希望阅读能添加禁止自启动外部应用功能~就是在阅读直接打开任意网站，不会自启动支付宝等

### ISSUE THREAD

**Issue by 1274003856** [gedoor/legado#863]
比如我在阅读~订阅源~直接添加了
https://m.baidu.com/s?word=爱你
单url订阅源    直接打开后
找到
大家还在搜
的任意内容~任意点击
阅读就会自动启动外部应用~软件商店了

希望阅读能修改成
当我点击
大家还在搜 的任意内容

弹窗提示
是否打开外部应用
确认  取消

当我点击  确认 才会启动外部应用
点击 取消  就不会打开外部应用

因为现在很多网页都会自动打开外部应用，比如爱奇艺，腾讯视频，优酷(会自动打开她们的官方app~手机安装了她们的官方app的话)
还有很多网页都有各种支付宝口令红包等，打开这些网站，在阅读就会自动打开支付宝，实在影响体验啊。

**Comment by 1274003856** [comment]
x浏览器就可以在设置~设置
是否自动允许启动外部应用 右面不点绿色就不会
打开任意网站，自动打开支付宝等了
via浏览器在打开任意网站后，页面会弹窗提示
是否允许网站启动外部应用
确认  取消
点击  取消就不会启动外部应用了

**Comment by 1274003856** [comment]
演示图片
https://www.hualigs.cn/image/6035f68d245ff.jpg

**Comment by 1274003856** [comment]
比如这个网址

https://mbd.baidu.com/ma/tips?appKey=frQ5XpOCpnq00kpFyPRtIgvgMjMgQGyB

**Comment by 1274003856** [comment]
比如这个网址

https://mbd.baidu.com/ma/tips?appKey=frQ5XpOCpnq00kpFyPRtIgvgMjMgQGyB

单url订阅源，在阅读打开
点击 前往百度app
就会自动启动  应用商店等

希望修改成
点击 前往百度app
弹出
是否打开外部应用程序
点击  确认  才会打开外部应用
不点击~2秒后自动消失

**Comment by gedoor** [comment]
好的

**Comment by gedoor** [comment]
已经修改
