### ISSUE TITLE
阅读~订阅源默认(猫咪)封面希望能够自己修改成自己喜欢的图片~就像小说的默认封面那样

### ISSUE THREAD

**Issue by 1274003856** [gedoor/legado#864]
希望增加
阅读~设置~其他设置~默认订阅源封面
可以打开图库~选择自己喜欢的图片作为这个
默认订阅源封面
毕竟
现在的订阅源默认封面(猫咪图~不好看啊)
因为关耳大佬做的最新订阅源模板~不显示内容封面啊

**Comment by 1274003856** [comment]
关耳大佬的最新订阅源模板
http://yck.mumuceo.com/yuedu/rssyuan/yuan.html?id=402

**Comment by 1274003856** [comment]
演示图片
https://www.hualigs.cn/image/6035f73f25e8b.jpg
https://www.hualigs.cn/image/6035f73f603fa.jpg

**Comment by gedoor** [comment]
好的
