### ISSUE TITLE
有出iOS版的打算么？

### ISSUE THREAD

**Issue by kaich** [gedoor/legado#865]
请问有退出ios版的计划么？ 

如果没有，我会尝试看看能不能做一个完全兼容兼容的ios版出来，这样不管换什么手机，都可以用这一套了，简单方便。

PS： 我看了源码，貌似有些解析涉及到了JAVA独有的库，能不能实现还是未知数。如果大佬没有这个计划，我就来试试看。

**Comment by 10bits** [comment]
爬虫部分可以用golang做，用socketio通信

* 解析部分用到的库golang里都可以找到
* jsoup可以用goquery代替
* 处理js可以用goja这个库

**Comment by kaich** [comment]
@10bits 没有那么简单的，有很多特定的JS解析，Golang这些是做不了的

**Comment by 10bits** [comment]
有什么解决不了的，那是你的问题，不是golang的问题

**Comment by kaich** [comment]
@10bits 这么强？ 有空写一个？

**Comment by zhj9709** [comment]
~~搞个legado-flutter项目~~

**Comment by kaich** [comment]
@zhj9709 flutter个单线程的语言，耗时任务，性能捉急！（如果要提升性能，另外又要做很多额外工作，麻烦的很！）

**Comment by chuxiaorong** [comment]
大佬求出个ios版本的，ios找半天只有一个爱阅书香能看，不过广告太烦

**Comment by kaich** [comment]
@chuxiaorong 在做了

**Comment by zeroBugL** [comment]
同求ios版 阅读  ！！看个书太难了

**Comment by FanXingChunShui** [comment]
同求iOS版

**Comment by idalin** [comment]
> @10bits 没有那么简单的，有很多特定的JS解析，Golang这些是做不了的

我之前打算用golang为kindle写一个，基本的功能实现了，但后来发现qt实在卡的无法用，就太监了。暂时就没继续了，不过简单的抓取和解析库已经有了(部分实现，json等等本来是打算做完gui再弄的，结果太监了)
https://github.com/idalin/govel

**Comment by kaich** [comment]
@idalin i  如果是简单书源纯jsoup、jsonpath，xml解析很简单，复杂的书源，你看看源码就知道能不能实现了... 既然要做阅读ios版，至少适配兼容程度达到95%以上，单纯的弄个半成品，各种书源导入一大堆问题，肯定是没必要的

**Comment by idalin** [comment]
> @idalin i 如果是简单书源纯jsoup、jsonpath，xml解析很简单，复杂的书源，你看看源码就知道能不能实现了... 既然要做阅读ios版，至少适配兼容程度达到95%以上，单纯的弄个半成品，各种书源导入一大堆问题，肯定是没必要的

我是觉得没必要搞的那么复杂，99.99%的需求其实已经用这些功能解决了，更复杂的可以在以后慢慢优化实现。用不着在一开始就做的很完善，因为其实大部分人根本用不上，比如我自己就用不到那些。

**Comment by Jeffrey-jiacj** [comment]
同求IOS版本

**Comment by zeroBugL** [comment]
> > @idalin i如果是简单书源纯jsoup，jsonpath，xml解析很简单，复杂的书源，你看看源码就知道能不能实现了...既然要阅读ios版，至少适应兼容程度达到95 ％以上，单纯的弄个半成品，各种书源引入一大堆问题，肯定是没必要的
> 
> 我是觉得没必要搞的那么复杂，99.99％的需求其实已经用这些功能解决了，更复杂的可以在以后逐步优化实现。用不着在一开始就做的很完善，因为实际上大部分人根本用不上，某些我自己就用不到那些。

我也这么觉得，有书源能用、能看书就行，复杂的可以慢慢搞

**Comment by zeroBugL** [comment]
> > @idalin i如果是简单书源纯jsoup，jsonpath，xml解析很简单，复杂的书源，你看看源码就知道能不能实现了...既然要阅读ios版，至少适应兼容程度达到95 ％以上，单纯的弄个半成品，各种书源引入一大堆问题，肯定是没必要的
> 
> 我是觉得没必要搞的那么复杂，99.99％的需求其实已经用这些功能解决了，更复杂的可以在以后逐步优化实现。用不着在一开始就做的很完善，因为实际上大部分人根本用不上，某些我自己就用不到那些。

我也这么觉得，有书源能用、能看书就行，复杂的可以慢慢搞

**Comment by kaich** [comment]
@zeroBugL 其它功能是可以慢慢做，我说的就是现在3.0版本书源很复杂啊，各种嵌入！单纯的jsoup，jsonpath，xml基本上很少了，不能让用户导入个源，动不动就解析不出来。
