### ISSUE TITLE
[Feature Request] 希望书源分组可以加一个未分组

### ISSUE THREAD

**Issue by zhj9709** [gedoor/legado#866]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 加一个未分组，效果就是选出所有未分组书源，可以将位置放在已禁用下面

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by h11128** [comment]
有一个默认的未分组

**Comment by zhj9709** [comment]
> 有一个默认的未分组

书源管理，我看了一下，并没有。我测试了，删掉几个书源的源分组，并没有看到未分组。

**Comment by h11128** [comment]
哦你说的是书源而不是书籍， 搞错了
