### ISSUE TITLE
[BUG] [重要]web 网页在线阅读手机本地文本报错 不能阅读

### ISSUE THREAD

**Issue by YuiCC** [gedoor/legado#867]
### 安卓版本 
>Android 10

### 阅读Legdao版本 
>legado_app_3.21.022121

### 网络环境 
>局域网

### 问题描述 
>legado开启web服务后, 电脑端web 网页在线阅读手机本地文本报错 , 只有章节标题 没有章节内容

### 使用书源 
>手机本地文本

### 日志提交（问题截图或者日志）
>
![image](https://user-images.githubusercontent.com/21233545/109244198-3b56ec80-7819-11eb-9046-030a234ba17a.png)

**Comment by Celeter** [comment]
我试了一下没问题啊，你看看network里返回的是什么
![image](https://user-images.githubusercontent.com/48249130/109249251-4cf0c200-7822-11eb-9d0e-5e4d26d11276.png)

**Comment by YuiCC** [comment]
![image](https://user-images.githubusercontent.com/21233545/109249578-ec15b980-7822-11eb-94a3-e3e9306dd8b6.png)
![image](https://user-images.githubusercontent.com/21233545/109249611-0059b680-7823-11eb-83f6-a80b2eba2f5a.png)
http://10.4.214.207:1122/getBookContent?url= 有返回章节内容,但没有显示, 有报错

**Comment by Celeter** [comment]
是所有本地都有问题吗
是本地书的所有章节都有问题吗

**Comment by YuiCC** [comment]
所有本地书的所有章节都有问题

**Comment by Celeter** [comment]
> 所有本地书的所有章节都有问题

非本地书有问题吗

**Comment by Celeter** [comment]
你可以先用这个`http://alanskycn.gitee.io/vip/reader/`输入IP地址看吧

**Comment by Celeter** [comment]
试试[https://github.com/Celeter/web-yuedu3/actions/runs/601597604](https://github.com/Celeter/web-yuedu3/actions/runs/601597604)用这个行不行

**Comment by YuiCC** [comment]
![image](https://user-images.githubusercontent.com/21233545/109266191-abc63380-7842-11eb-9e09-0ac277e3af7f.png)
![image](https://user-images.githubusercontent.com/21233545/109266226-bb457c80-7842-11eb-842f-a1a80e2e2acd.png)

legado_appX_3.21.022612.apk web没报错,getBookContent?url=有获取到章节内容,但没有显示章节内容

**Comment by Celeter** [comment]
你换个浏览器试试吧，我这里本地书是正常的，不能复现

**Comment by YuiCC** [comment]
我这 firefox85 、chrome88 、Edge 88都不正常，，

**Comment by Celeter** [comment]
这我就不知道了

**Comment by fhwhite** [comment]
我的也正常，应该是个例
![1](https://user-images.githubusercontent.com/47919090/109387136-8288ce80-793a-11eb-8c93-f20461f58f06.png)

**Comment by YuiCC** [comment]
![image](https://user-images.githubusercontent.com/21233545/110906607-1f8a3500-8347-11eb-9e10-f76d30e20402.png)
问题原因

**Comment by Celeter** [comment]
> ![image](https://user-images.githubusercontent.com/21233545/110906607-1f8a3500-8347-11eb-9e10-f76d30e20402.png)
> 问题原因

这个[lanzou](https://wwa.lanzous.com/iMhQFmujn5e)你试试

**Comment by YuiCC** [comment]
> > ![image](https://user-images.githubusercontent.com/21233545/110906607-1f8a3500-8347-11eb-9e10-f76d30e20402.png)
> > 问题原因
> 
> 这个[lanzou](https://wwa.lanzous.com/iMhQFmujn5e)你试试

这个正常了
