### ISSUE TITLE
[Feature Request] 希望导出的txt命名方式为“《书名》作者：张三”，而不是“书名 by 张三”

### ISSUE THREAD

**Issue by viviyaaa** [gedoor/legado#868]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望导出的txt命名方式为“《书名》作者：张三”，而不是“书名 by 张三”

### 期望实现方式（阅读应该如何实现该功能）
> 
![image](https://user-images.githubusercontent.com/79686337/109266282-cdbfb600-7842-11eb-8ead-3a60eb081b26.png)

### 附加信息（其他的与功能相关的附加信息）
> 因为txt名称为《…》作者：… 的样式，用阅读或其他本地书籍APP打开可以自动读取书名及作者（如下图），所以希望离线缓存导出的txt名字也能改成这样。
![image](https://user-images.githubusercontent.com/79686337/109266288-d1533d00-7842-11eb-8b03-679e66f1a37c.png)

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 10bits** [comment]
好家伙，以前用的作者:,注意是英文冒号，在windows下是非法字符，改成中文冒号后整体感觉太长了，所以被我改成by了

**Comment by hoodie13** [comment]
现在导入txt识别作者的规则是作者：。导出规则改了是不是导入txt识别书名规则也同步下更合理。

**Comment by nobk** [comment]
@hoodie13 @10bits 我已经提交针对这个问题的PR了，描述详见issue #925。其实用by也有一定好处，就是不只适用于中文小说，当然现在阅读的绝大部分用户都是中文用户。
