### ISSUE TITLE
[Feature Request] 希望作者大大能把每章的标题优化一下，这个标题看得好难受

### ISSUE THREAD

**Issue by LeeeKevin** [gedoor/legado#869]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望作者大大能把每章的标题优化一下，这个标题看得好难受

### 期望实现方式（阅读应该如何实现该功能）
> 标题可以居中、然后与正文不同，可以加粗和行高占比高 左右的padding希望能多一点

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by zmn001125** [comment]
标题可以居中，可以调字号和上下间距，
加粗跟换其他样式不行

**Comment by zmn001125** [comment]
> 标题可以居中，可以调字号和上下间距，
> 加粗跟换其他样式不行

我看着标题是比正文颜色深些
![Uploading Screenshot_2021-02-26-17-59-47-500_io.legado.play.release.jpg…]()

**Comment by zmn001125** [comment]
> 标题可以居中，可以调字号和上下间距，
> 加粗跟换其他样式不行

我看着标题好像比正文颜色深些
![Screenshot_2021-02-26-18-01-17-484_io legado play release](https://user-images.githubusercontent.com/52020688/109286376-1d12e000-785d-11eb-98e0-fa302716a33f.jpg)
![Screenshot_2021-02-26-17-59-47-500_io legado play release](https://user-images.githubusercontent.com/52020688/109286389-213efd80-785d-11eb-9c94-d6605a8e58af.jpg)

**Comment by LeeeKevin** [comment]
> > 标题可以居中，可以调字号和上下间距，
> > 加粗跟换其他样式不行
> 
> 我看着标题好像比正文颜色深些
> ![Screenshot_2021-02-26-18-01-17-484_io legado play release](https://user-images.githubusercontent.com/52020688/109286376-1d12e000-785d-11eb-98e0-fa302716a33f.jpg)
> ![Screenshot_2021-02-26-17-59-47-500_io legado play release](https://user-images.githubusercontent.com/52020688/109286389-213efd80-785d-11eb-9c94-d6605a8e58af.jpg)

感谢大哥的帮助，调整之后看着爽多了
