### ISSUE TITLE
[BUG] 文字显示错误“猛”显示为“勐”

### ISSUE THREAD

**Issue by fhwhite** [gedoor/legado#874]
### 机型（如Redmi K30 Pro）
>雷电模拟器和荣耀9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>legado_app_3.21.022715最新版和以前的版本

### 问题描述（简要描述发生的问题）
>“猛”字显示为“勐”，无论是手机还是模拟器都一样，以前发现过，但因为是书源，以为网站本身的问题，今天看手机本地txt也这样，刚刚用模拟器试了一下，同样问题，已经关闭净化规则（曾试过把“勐”替换为“猛”，还是显示勐）

### 日志提交（问题截图或者日志）
>
![无标题](https://user-images.githubusercontent.com/47919090/109387253-3f7b2b00-793b-11eb-94b2-2c53729c3039.png)

**Comment by Antecer** [comment]
你是不是开了简繁转换?
开 2021/02/27, 星期六 20:39:58, fhwhite <notifications@github.com> 写到:
机型（如Redmi K30 Pro）
雷电模拟器和荣耀9
阅读Legdao版本（我的-关于-版本,如3.20.112220）
legado_app_3.21.022715最新版和以前的版本
问题描述（简要描述发生的问题）
“猛”字显示为“勐”，无论是手机还是模拟器都一样，以前发现过，但因为是书源，以为网站本身的问题，今天看手机本地txt也这样，刚刚用模拟器试了一下，同样问题，已经关闭净化规则（曾试过把“勐”替换为“猛”，还是显示勐）
日志提交（问题截图或者日志）
[无标题] [https://user-images.githubusercontent.com/47919090/109387253-3f7b2b00-793b-11eb-94b2-2c53729c3039.png]

**Comment by fhwhite** [comment]
没有啊，图中是我手动新建的txt文本，还是显示错误

**Comment by fhwhite** [comment]
以为是字体问题，换成系统内置字体也一样

**Comment by fhwhite** [comment]
等等。。。简繁体转换。。我找找

**Comment by fhwhite** [comment]
。。。。。这个问题能删除吗。。。太丢人了
