### ISSUE TITLE
[BUG] 播放音频后，手势返回，自动停止播放

### ISSUE THREAD

**Issue by baizhi1989** [gedoor/legado#876]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>一加5T 9.0.9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.022720

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by adhu2018** [comment]
这个不能算是bug吧，朗读的时候在阅读内点击`后台`的图标才可以退回书架并保持朗读，最多只能算是操作逻辑需要优化  
![Screenshot](https://user-images.githubusercontent.com/41824074/109762930-51571980-7c2c-11eb-93c5-59aa11df2907.jpg)
