### ISSUE TITLE
[Feature Request] webdav备份只保留一定时间内的备份文件，清除过期备份

### ISSUE THREAD

**Issue by zhongfly** [gedoor/legado#877]
### 功能描述（请清晰的、详细的描述你想要的功能）
目前每天都会生成一个备份文件保存在webdav上，长久来看会使得备份数量越来越多，并且时间久远的备份通常来说也不会再用于恢复(个人看法)。
因此希望能够只保留一段时间内的备份，并删除之前的过期备份

### 期望实现方式（阅读应该如何实现该功能）
> 增加备份保留的时间期限，如一周/一个月/三个月/永久等选项

**Comment by hoodie13** [comment]
这个功能挺好的。我的webDav也是定期清理一次。建议不按照时间清理，而是只保留最近20个记录。这样是不是合理点。

**Comment by zhongfly** [comment]
> 这个功能挺好的。我的webDav也是定期清理一次。建议不按照时间清理，而是只保留最近20个记录。这样是不是合理点。

是一回事，备份是每天只有一个记录

**Comment by zhongfly** [comment]
依旧缺失此类功能…
