### ISSUE TITLE
[Feature Request] 阅读排版增加竖排

### ISSUE THREAD

**Issue by haocvg** [gedoor/legado#880]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 阅读界面设置增加排版方向，可以选择竖向、横向，从左向右、从右向左，保持现有的翻页动画（覆盖、滑动、仿真、滚动、无动画）

### 期望实现方式（阅读应该如何实现该功能）
> 界面设置中增加单独排版设置，将字号、字距、行距、段距以及排版方向、阅读方向统一放入。颜色和排版分离，增加“预设”栏。替代原来的“文字颜色和背景（长按自定义）”

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>这是我自己设计的一版
![image](https://user-images.githubusercontent.com/44605406/109599897-0d461500-7b57-11eb-9bd2-bbc1e19eff23.png)

**Comment by AuYoku** [comment]
完全看不出来是竖排，支持切换横排\竖排的似乎只有ireader？竖排的一般是港台日韩的小说吧

**Comment by haocvg** [comment]
我这里只是提供了一个设置的排版，实际上我没有专门去做文字竖排的效果。竖排主要想在看古典文学的时候能够看的仔细一些。
