### ISSUE TITLE
[Feature Request] 能否增加每天阅读章节数量限制？

### ISSUE THREAD

**Issue by flyisland** [gedoor/legado#881]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 例如设置每本书每天阅读章节数量为10，那么当天阅读章节10章后，则无法再打开这本书。可以全局设置，也可以每本书单独设置。

**Comment by Mupceet** [comment]
这个需求有什么意义吗？只会增加软件的复杂度。
这个限制加在自己内心即可。
