### ISSUE TITLE
[Feature Request] 关于精确搜索

### ISSUE THREAD

**Issue by zmn001125** [gedoor/legado#882]
### 功能描述（请清晰的、详细的描述你想要的功能）

> 目前的精确搜索太过精确，如要搜索的书名为《xxxx》，只会搜出为xxxx的书，不会出现xxxx[重生]这种带后缀的，导致部分书籍无法搜出。

### 期望实现方式（阅读应该如何实现该功能）

> 如要保存该方式的搜索方法，希望再增添一个部分匹配的搜索方法，实现只要包含搜索关键词就显示【之前的阅读版本是这样】

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
好的

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持
