### ISSUE TITLE
[Feature Request] epub分章节解析，整本epub解析下来再分页显示耗时比较长。

### ISSUE THREAD

**Issue by YumikoAzu** [gedoor/legado#884]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 

原先的加载策略是：解析完所有章节(xhtml)后再进行显示(EPub格式的书籍里每一章对应一个xhtml页面)
修改目标为：先只解析用户上次阅读所在的章节，快速打开显示，随后在后台进行全部章节的加载

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by hoodie13** [comment]
只会解析全书的目录吧，获取章节只获取当前章和前后章的。

**Comment by YumikoAzu** [comment]
> 只会加载全书的目录吧，获取章节只获取当前章和前后章的。
> 不过我发现有些书加载目录也要几S时间。要看看啥原因。
要是那个章节字数比较多(差不多十万字以上吧)加载挺慢，可以改成跟多看阅读那样(分页的时候先分几页出来让用户看到，然后在后台继续分页)。

**Comment by ag2s20150909** [comment]
新版已修复，epub基本秒开。
