### ISSUE TITLE
求数据库字段不要和特定平台关联，方便做iOS版本

### ISSUE THREAD

**Issue by kaich** [gedoor/legado#887]
求数据库字段不要和特定平台关联，方便做iOS版本

例如 `ReadRecord ` 表有 `androidId`字段。 请求不要设置这种带明显安卓含义的字段。方便兼容。

另外：
  如果我没有理解错误。
 `ReadRecord`表的 `androidId`字段，没什么用处。
一般个人阅读记录，作为统计数据用的，手机型号、手机名称等信息做为区分就够了，完全没有必要录入有可能发生变化的androidId。

希望收到回复，谢谢。

**Comment by gedoor** [comment]
好的,这个是为了分辨不同设备用的,我看看改成deviceId

**Comment by kaich** [comment]
@gedoor 非常感谢！
