### ISSUE TITLE
关于webDav的疑问

### ISSUE THREAD

**Issue by zyyfriends** [gedoor/legado#89]
* 请问目前webDav备份只能够支持坚果云吗？自己使用群晖搭建的webDav服务貌似无法使用（更改了端口）。。

* 3.0版本的webDav设置无法保存，返回后重新进入便清空了

**Comment by sangmingda** [comment]
> * 3.0版本的webDav设置无法保存，返回后重新进入便清空了

我用了也是这样，坚果云无法使用，备份位置是手机内部存储

**Comment by gedoor** [comment]
我看看

**Comment by zyyfriends** [comment]
> * 请问目前webDav备份只能够支持坚果云吗？自己使用群晖搭建的webDav服务貌似无法使用（更改了端口）。。

经测试，http 可以正常备份，但是地址需要加入 目录路径，  https会提示如图 ![](http://oss.zhouyuyang.com/img/yuedu_error.jpg)

建议在新版本中能加入对于webdav设置的验证及提示信息

**Comment by gedoor** [comment]
好的

**Comment by zyyfriends** [comment]
啊。。。3.0版本现在可以保存webdav设置了，但是备份后显示成功，却没有生成对应文件。。设置除目录以外和2.0是一模一样的

**Comment by yaocanfeng** [comment]
webdav设置了，备份提示webdav no protocol https://dav.jianguoyun.com/dav/legado/
