### ISSUE TITLE
[Feature Request] 希望长按文本可以使用第三方词典取词

### ISSUE THREAD

**Issue by SogaSuga** [gedoor/legado#899]
### 功能描述（请清晰的、详细的描述你想要的功能）
阅读时，长按字、词弹出的菜单中，接入第三方词典如GoldenDict，Mdict等的取词翻译功能。

**Comment by gedoor** [comment]
应该是有的啊

**Comment by SogaSuga** [comment]
> 
> 
> 应该是有的啊

可能是系统的限制？我这三星手机上，只有系统自带的 词典.app 会出现在长按菜单里，也没有相关的设置选项。
只有像静读天下那样，能自定义长按菜单的app才能选择用别的词典。
