### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lywwl** [gedoor/legado#902]
### 机型（如Redmi K30 Pro）
>小米10青春版

### 安卓版本（如Android 7.1.1）
>
安卓11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>无法朗读，整屏整屏瞬间的过，无声音。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by wilsonjor** [comment]
有的书源播放不了，换一个试

**Comment by lywwl** [comment]
正播放的书，不可以用了，换了几部，还是不能播放。

**Comment by Celeter** [comment]
> 正播放的书，不可以用了，换了几部，还是不能播放。

在线tts失效了，去看下公众号有说明
