### ISSUE TITLE
[BUG] 无法读取EPUB3标准的epub电子书的元信息

### ISSUE THREAD

**Issue by nukemiko** [gedoor/legado#904]
### 机型（如Redmi K30 Pro）
> Xiaomi Mi 10

### 安卓版本（如Android 7.1.1）
> Android 11, crDroid 7.4

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.2.1.031720

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 本地的epub文件，和网络环境无关

### 问题描述（简要描述发生的问题）
> 如果导入的epub文件采用了EPUB3标准，会出现以下问题：
> 目录章节数不正确（可能受到[issue897](https://github.com/gedoor/legado/issues/897)的影响）；
> 无论是在目录中还是在章节开头，所有章节名全部显示为“未知”
> 书籍详情页部分信息显示为“未知”

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
1. 下载这个文件[Package.zip](https://github.com/gedoor/legado/files/6177071/Package.zip)；
2. 解压上述文件，得到一个EPUB2和EPUB3的文件（文件前缀已经标明），分别导入阅读；
3. EPUB3标准的文件可见明显异常

### 日志提交（问题截图或者日志）
> 这是EPUB2标准的文件
> ![EPUB2](https://user-images.githubusercontent.com/53572814/111898892-d2534500-8a63-11eb-81e2-651cdd7d1ef0.png)
> 这是EPUB3标准的文件
> ![EPUB3](https://user-images.githubusercontent.com/53572814/111898905-e6974200-8a63-11eb-8fd3-0ea7bcb98291.png)

**Comment by ag2s20150909** [comment]
Epublib的问题，epublib没有适配epub3，在epub3中没有toc.ncx作为目录

**Comment by ag2s20150909** [comment]
或许可用尝试使用 https://github.com/readium/mobile 来解析epub

**Comment by ag2s20150909** [comment]
这个是Android的例子：https://github.com/readium/r2-testapp-kotlin

**Comment by gedoor** [comment]
好的, 我看看

**Comment by ag2s20150909** [comment]
> ### 机型（如Redmi K30 Pro）
> > Xiaomi Mi 10
> 
> ### 安卓版本（如Android 7.1.1）
> > Android 11, crDroid 7.4
> 
> ### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> > 3.2.1.031720
> 
> ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > 本地的epub文件，和网络环境无关
> 
> ### 问题描述（简要描述发生的问题）
> > 如果导入的epub文件采用了EPUB3标准，会出现以下问题：
> > 目录章节数不正确（可能受到[issue897](https://github.com/gedoor/legado/issues/897)的影响）；
> > 无论是在目录中还是在章节开头，所有章节名全部显示为“未知”
> > 书籍详情页部分信息显示为“未知”
> 
> ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 1. 下载这个文件[Package.zip](https://github.com/gedoor/legado/files/6177071/Package.zip)；
> 2. 解压上述文件，得到一个EPUB2和EPUB3的文件（文件前缀已经标明），分别导入阅读；
> 3. EPUB3标准的文件可见明显异常
> 
> ### 日志提交（问题截图或者日志）
> > 这是EPUB2标准的文件
> > ![EPUB2](https://user-images.githubusercontent.com/53572814/111898892-d2534500-8a63-11eb-81e2-651cdd7d1ef0.png)
> > 这是EPUB3标准的文件
> > ![EPUB3](https://user-images.githubusercontent.com/53572814/111898905-e6974200-8a63-11eb-8fd3-0ea7bcb98291.png)

新版应该修复了

**Comment by 52fisher** [comment]
新版应该解决该问题了
