### ISSUE TITLE
[Feature Request]希望支持可以长按删除书源

### ISSUE THREAD

**Issue by AuYoku** [gedoor/legado#905]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
希望支持可以长按删除书源，这个功能在阅读2是存在的，到3没了。很好用，现在如果要删除书源就需要退出阅读去“书源管理”找到再删除
### 期望实现方式（阅读应该如何实现该功能）
> 
希望支持可以长按删除书源
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by h11128** [comment]
https://github.com/gedoor/legado/pull/1201
