### ISSUE TITLE
[Feature Request] js全局

### ISSUE THREAD

**Issue by zmn001125** [gedoor/legado#906]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望在编辑书源的基本页面添加一个专门写能应用到全局的js变量和js函数，一些重复的js函数就可以不用重复的写在各个地方，
比如移动阅读http://yck.mumuceo.com/yuedu/shuyuan/jsons?id=4230
这个书源，很多都是重复的函数，写在一个地方调用会方便，简约一些

**Comment by gedoor** [comment]
好的
