### ISSUE TITLE
[Feature Request] 希望增加本章说功能

### ISSUE THREAD

**Issue by hu1240050829** [gedoor/legado#907]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 起点的本章说，好像要这个功能啊，有点像B站弹幕一样，习惯了就离不开了

### 期望实现方式（阅读应该如何实现该功能）
> 本章说即段落评论，每一段文字都可以单独的进行发表评论

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Celeter** [comment]
要服务器

**Comment by Acytoo** [comment]
我也觉得这个功能很棒，看看别人的评论与吐槽挺有意思的。

能不能通过一个公用的Webdav网盘或者是一个github账号来实现呢？如果数据不大的话，利用免费的资源就可以实现。

**Comment by ShanHuilu** [comment]
我觉得没必要，阅读的初衷就是个阅读器，本身就是用爱发电，没有必要加这些浪费资源的功能。

**Comment by kaich** [comment]
加载到章节的时候就要加载评论，这种没有良好服务器作为支撑，很难获得良好的体验，很可能你翻过去了，评论才加载出来，一般看小说速度又快，这种很大可能吃力不讨好。而且很负责任的说，会很多打广告的

**Comment by Acytoo** [comment]
> 加载到章节的时候就要加载评论，这种没有良好服务器作为支撑，很难获得良好的体验，很可能你翻过去了，评论才加载出来，一般看小说速度又快，这种很大可能吃力不讨好。而且很负责任的说，会很多打广告的

乱发内容确实令人烦恼，有可能需要人工审核。但是加载就好说了，跟章节一起预加载就好，文字的东西很小，不占用很多资源，如果做的话可以加开关嘛。另外的难题是布局设计？

**Comment by dianso** [comment]
其实本章说完全可以弄成注释，自己可以随意添加修改，或者增加评论~

**Comment by 1274003856** [comment]
第一，需要用到服务器和域名，(域名几十，服务器几千)
第二，因为有大量的移动用户，域名必须是备案的。(不然三天两头404)
第三，很多人都是直接缓存好所有章节，然后听书的(这不就浪费了)
第四，用户多了，起点会给阅读递律师涵的。
第五，因为服务器和域名要钱，就会接广告维持(正规广告接来维持不下去，不正规的女的会投诉的)

给你的建议，直接在 起点书源，自己写规则 采集 起点的本章说吧。(因为你这个功能太小众了，需要采集起点 电脑版页面啊，采集速度会变慢。)
主要是需要的人太少了，可能就你和很少，比如30人。
投入域名，服务器做这个，每月投入100元，就算你们30人时时都看，本章说，广告收入一天最多0.5元，100-15=75元啊。

**Comment by 1274003856** [comment]
简单啊，服务器域名每月可能花费300元左右，你一次性给一年的吧，只需要3600元，先给阅读作者打款，你说的功能就出来了，
不给钱，就不要想了，(每章添加评论功能，免费的就得添加广告，谁会喜欢啊)付费的你又不付款啊。

**Comment by auto-bot-ty** [comment]
在 github 看[本章说 ](https://github.com/auto-bot-ty/qidian-chapterReview/blob/main/utils.js)
