### ISSUE TITLE
[Feature Request]  Use Readium replace Epublib

### ISSUE THREAD

**Issue by ag2s20150909** [gedoor/legado#908]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
Epublib只支持epub2,不兼容epub3,而且很久没有更新，没人修复bug.
而Readium Mobile SDK支持Android与iOS平台，兼容epub2/3,支持更多的格式，使用kotlin编写，与本项目是同一语言，还在更新维护中。
Readium Mobile:https://github.com/readium/mobile
Android Example:https://github.com/readium/r2-testapp-kotlin
### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
我看看啊,

**Comment by ag2s20150909** [comment]
> 我看看啊,
我到处东拼西凑的搞出一个能解析目录的epublib
https://github.com/ag2s20150909/EpubLib

**Comment by gedoor** [comment]
行,我拿来用
