### ISSUE TITLE
[BUG] epub的目录加载逻辑

### ISSUE THREAD

**Issue by ag2s20150909** [gedoor/legado#910]
### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
3.21.032520

### 问题描述（简要描述发生的问题）
测试文件从[904](904) 处获取
当epub的父目录与子目录的href相同时（第一卷与第一章href相同），这样的父目录与子目录打开时有bug，会出现文本后又消失，无法翻页到下一章，等一就会把所有子章节都加载了，手动跳转到第二章后才能正常翻页，建议使用获取线性目录的方法。
[![6XdHJK.png](https://z3.ax1x.com/2021/03/25/6XdHJK.png)](https://imgtu.com/i/6XdHJK)

       //获取线性的阅读菜单
        List<Resource> spineReferences = book.getTableOfContents().getAllUniqueResources();
        for(Resource sp:spineReferences){
            Log.d(TAG,sp.getHref()+sp.getTitle());
        }

        //获取层级的菜单
        List<TOCReference> tocReferences =book.getTableOfContents().getTocReferences();
        for (TOCReference top:tocReferences){
            Resource topres= top.getResource();
            Log.d(TAG,"父目录"+topres.getHref()+topres.getTitle());
            if (top.getChildren().size()>0){
                for (TOCReference child:top.getChildren()){
                    Resource childres= child.getResource();
                    Log.d(TAG,"子目录"+childres.getHref()+childres.getTitle());
                }
            }
        }

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
ok
