### ISSUE TITLE
三星s21全面屏手势冲突

### ISSUE THREAD

**Issue by brydio** [gedoor/legado#914]
左右的返回和home都会冲突，另外点击区域是不是可以考虑自定义区域

**Comment by zmn001125** [comment]
![IMG_20210327_115341](https://user-images.githubusercontent.com/52020688/112709294-1a0a1e80-8ef3-11eb-9c4a-65102d776038.jpg)
自定义区域是说这个？

**Comment by brydio** [comment]
是的，我指的这个界面的九宫格可以拖动点击区域的范围

**Comment by 1274003856** [comment]
你把你截图的 最下面的
下一页  无操作，无操作，
都给改成 无操作不就可以了。
至于拖动范围，压根用不到的，
另外全面屏自带的手势，你改一下即可，
改成显示 按钮的那种就可以了。
不然你就只能让开发者单独给你开发了，

**Comment by brydio** [comment]
有道理，我把中间的上下改成菜单，就方便多了

**Comment by nobk** [comment]
建议阅读缩小九宫格边界，并且对从边缘划进来的手势忽略，这样就不需要设定一堆无操作了避免和系统手势的冲突了。

**Comment by 1274003856** [comment]
你这个简单啊-你把你的全面屏的的那个可隐藏功能打开就是了这是你对手机不熟悉啊。
至于缩小九宫格边界-这是没用的啊，
给你的解决办法。
一。多去看看你的手机设置。系统手势。好好配置一下
二。换 部手机吧，你的这部手机不支持阅读。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月4日(星期天) 上午8:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gedoor/legado] 三星s21全面屏手势冲突 (#914)





 
建议阅读缩小九宫格边界，并且对从边缘划进来的手势忽略，这样就不需要设定一堆无操作了避免和系统手势的冲突了。
 
&mdash;
