### ISSUE TITLE
安卓8.1无法离线缓存

### ISSUE THREAD

**Issue by lcd-screen** [gedoor/legado#916]
### 机型（如Redmi K30 Pro）
>墨案青春版

### 安卓版本（如Android 7.1.1）
>Android 8.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.032520

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通、联通宽带

### 问题描述（简要描述发生的问题）
>无法离线缓存，点击没反应

### 使用书源（填写URL或者JSON）
>www.dstiejuan.com

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>阅读界面离线缓存确认缓存章节后，没反应
书架界面离线缓存点击开始按钮后，没反应
但是正常小说阅读缓存10章是可以的

### 日志提交（问题截图或者日志）
>

**Comment by 1274003856** [comment]
点击后要慢慢等待，缓存需要时间的，另外，只能一本一本的点击缓存的，一起缓存就会没信号了的。
只要书源的章节是可看的，没问题的，就可以缓存的，但是部分书源网站，访问有点慢，就会缓存很慢或者不能缓存，多次点击缓存即可。
如果你等不起，可以移民 米国，泡菜国，膏药国等，就可以快速缓存了的
至于原因，GFW 自己百度一下你就懂了。

**Comment by 1274003856** [comment]
基本上除了，正常xs找的服务器再国内，其他的db网站服务器都在米国等的。因为中美最近的国际环境问题，就会这样

**Comment by lcd-screen** [comment]
额，但是我用手机就可以缓存，就是电纸书不行，而且源也是国内的，所以我在想是不是某方面的兼容性有问题，应该不是网络的原因

**Comment by ag2s20150909** [comment]
有的网站限制一定时间内的访问频次，频率高了就返回空白。
