### ISSUE TITLE
[Feature Request] 希望增加一个多书源比对功能

### ISSUE THREAD

**Issue by SouthFox-D** [gedoor/legado#918]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 有一些书源经常会出现段落丢失的情况，经常看得人摸不着头脑，后知后觉才发现是书源的问题。
是否能获取多书源的文章并进行比对？

### 期望实现方式（阅读应该如何实现该功能）
> 同时获取多书源文章并将内容进行比对，显示完整文章，甚至可以更近一步，校准别字或者清除广告段落。

**Comment by 1274003856** [comment]
你看的书要是火，书源有1000，就可能有300书源有信号，要是300书源都对比同一章，你的手机还不卡冒烟啊。
而且对比也是做不到的啊，同时上下左右显示4个书源同一章内容，对比起来不说卡，你的手机屏幕也看不下去啊。

你的这个要求需要找开发者单独为你开发的，
第一，手机屏幕要大(14英寸左右吧)，同时对比10章都很完美。
第二，你是内存一定要大，没有100g就不要想了。
最后，因为是单独为你开发的版本，你给开发者多少钱，一万吗。

**Comment by SouthFox09** [comment]
> 你看的书要是火，书源有1000，就可能有300书源有信号，要是300书源都对比同一章，你的手机还不卡冒烟啊。
> 而且对比也是做不到的啊，同时上下左右显示4个书源同一章内容，对比起来不说卡，你的手机屏幕也看不下去啊。
> 
> 你的这个要求需要找开发者单独为你开发的，
> 第一，手机屏幕要大(14英寸左右吧)，同时对比10章都很完美。
> 第二，你是内存一定要大，没有100g就不要想了。
> 最后，因为是单独为你开发的版本，你给开发者多少钱，一万吗。

啊？你是不是没理解我的意思？迷惑……
照你这说法，每次搜索的时候搜几千个书源不也是卡爆？我也没说是全部书源吧，限制限制不就行了……

我的意思是先获取到文章再比对处理啊，处理好之后才显示到屏幕上啊，你是怎么理解成上下左右一起显示的……

**Comment by kaich** [comment]
@SouthFox09  章节内可能缺字少字，缺段落，标点符号等不一致。怎么比较哪个是全的呢？ 找字数最多的？

**Comment by SouthFox09** [comment]
> @SouthFox09 章节内可能缺字少字，缺段落，标点符号等不一致。怎么比较哪个是全的呢？ 找字数最多的？

简单的话就是直接获取三到五篇文章，然后比对差异，和其他差异加起来总差异最小的就切换到这个书源。做复杂一点的话，可以每一篇段落都进行比对，我想的差不多是这样吧……

**Comment by YumikoAzu** [comment]
> > @SouthFox09 章节内可能缺字少字，缺段落，标点符号等不一致。怎么比较哪个是全的呢？ 找字数最多的？
> 
> 简单的话就是直接获取三到五篇文章，然后比对差异，和其他差异加起来总差异最小的就切换到这个书源。做复杂一点的话，可以每一篇段落都进行比对，我想的差不多是这样吧……

看到你提的这个需求。。。简直无语。。。。怎样比对？然后你想要怎样的对比结果。每个书源里面的正文很多都不一样，或者网站自己加的一些文字。然后你怎么知道文章是否缺失？程序又不会思考。你以为比对，就会像人看小说小说一样知道文章缺失内容吗？

**Comment by 1274003856** [comment]
正版文章就是一段文字(有的作者为了防止盗版，一章小说可能发布3到5次~一次防盗，二次错字，三次才正常很多的)，d版网站每个网站都会给它添加文字，位置随机，而且很多都是二次的
这会造成 同一段文字，每个网站都不一样(添加的文字内容，位置都不一样，机器无法对比的)
比如 正版文字是
我爱你，你比我
盗版的就会
我爱卡卡你，你卡卡比我
我爱你，你比我
我爱你，你比加油我
我冲压爱你，你比我
我爱你看看，你比我
我爱你，图你比我
这才一句话，你给我看看机器能对比，人工对比起来都费劲啊
一篇小说2000字，添加起来可是厉害去了
再说了，阅读是完全本地话的软件啊
要做到机器模拟人工对比，就需要云服务器，每月上万美元的那种才可以的，

**Comment by kaich** [comment]
@SouthFox09  暂且不考虑楼上的书籍里面复杂的差异。先看看你说的：

 和其他差异，参照物是谁？A、 B、X、Y 分别是最缺失，第二缺失，最全，第二全。A和B相似度为90， X和Y相似度为90，求解怎么能比较出差异？并找到A是最全的？即使AB和XY的差异度不一样，最后得到的还是两个结果，取哪一个？

你的逻辑里面太多漏洞（也可能是我没明白你的意思）。
我觉得应该会这这里发需求大多都是干程序相关的吧。你如果觉得可行，可以定一个详细算法出来，让大家讨论。

**Comment by SouthFox09** [comment]
@1274003856 @kaich @YumikoAzu 

啊这，我真觉得这不是什么难事啊，我用 `python` 自带的标准库十分钟就能写出个原型了，就只是比较每一段相似度，简单粗暴取最大的就好了……

> 怎么能比较出差异？并找到A是最全的？即使AB和XY的差异度不一样，最后得到的还是两个结果，取哪一个？

碰上相似度相同的那就是具体考虑了，具体实现具体再说呗，我只是出来贴个意向而已……

> 这才一句话，你给我看看机器能对比，人工对比起来都费劲啊
> 一篇小说2000字，添加起来可是厉害去了
> 再说了，阅读是完全本地话的软件啊
> 要做到机器模拟人工对比，就需要云服务器，每月上万美元的那种才可以的，

文本对比操作具体下来也无非加减乘除罢了，真不是什么大计算，现在的手机也相当于二十年前的超级计算机，完全吃得消的啊。


见下图，用三段有问题的文本最终都能合出一篇正常文本，足以见得原型上是有这个可能的，至于具体实现要是发现有大困难，那就拉倒呗……

![image.png](https://i.loli.net/2021/03/31/wFvOdo5WkTutGhR.png)

[代码：https://gist.github.com/SouthFox09/2230455fdd909a09fe4b906d8ef4a374](https://gist.github.com/SouthFox09/2230455fdd909a09fe4b906d8ef4a374)

**Comment by 52fisher** [comment]
python在数据处理这部分本身就是强项，另外，总体来看，手机的性能目前确实比不上电脑。在中低端机型上，这样的计算会消耗比较大的性能，造成机器卡顿等问题。做源内容的对比的前提是能够定位到相同的章节或者内容，因为部分网站增加了广告、分页等，获取换源的目录一般只需要发起一次请求，但对比内容的话可能会同时发起多个请求，各网站响应需要一定的等待时间，同时也会对源站造成一定的影响。这个功能非常的人性化，但是对于手机的配置还是有一定的门槛要求。

**Comment by eromoe** [comment]
现在可以调gpt接口了
