### ISSUE TITLE
[Feature Request] 希望添加一个语音源

### ISSUE THREAD

**Issue by longcy** [gedoor/legado#919]
这个我感觉糖糖的声音不错，可以加入一下，也没有什么麻烦的的验证。
http://dev.hivoice.cn/exp_center/tts/tts.jsp
`http://dev.hivoice.cn/TTSServlet,{
	"method":"GET",
	"body":"text=hello&voiceName=tangtang&voicePitch=50&voiceSpeed=50&voiceVolume=100&bright=50"
}`

**Comment by Celeter** [comment]
有cookie验证
