### ISSUE TITLE
换源界面功能添加

### ISSUE THREAD

**Issue by szlk** [gedoor/legado#920]
### 功能描述
> 换源界面搜索出来的书源长按以后现在只有禁用书源选项，建议新增书源置顶和删除书源选项，这样方便置顶一些比较好的书源，也可以将不用的书源直接删掉。

**Comment by 1274003856** [comment]
好建议，

**Comment by szlk** [comment]
自顶

**Comment by h11128** [comment]
我也觉得很实用，加了 https://github.com/gedoor/legado/pull/1201
