### ISSUE TITLE
希望添加长按选择文字后出现词典翻译功能

### ISSUE THREAD

**Issue by QQ9711634** [gedoor/legado#924]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望添加长按选择文字后出现词典翻译功能

### 期望实现方式（阅读应该如何实现该功能）
> 能够实现中文词典，英汉翻译

### 附加信息（其他的与功能相关的附加信息）
> 可以采用多看阅读里面的翻译插件，需要的就下载，不需要的可以不用，下载后长按语句出现的选择条添加词典翻译选项，选择条能够自己修改顺序就更好了。
### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>长按文字的选择条没法截图，这个软件原来就有只是添加词典翻译选项

**Comment by 1274003856** [comment]
只需要有个翻译API即可 这不是难事。
主要是需要的人太少了。
毕竟。小说中出现英语。你都看不懂
读书的时候英语白学了啊，
很多人都是听书的，压根没空管啊

**Comment by 52fisher** [comment]
可自己下载安装词典，长按工具条中会自动增加该选项
