### ISSUE TITLE
[BUG] 封面换源不支持从阅读3自身导出的文件名中提取书名及作者名

### ISSUE THREAD

**Issue by nobk** [gedoor/legado#925]
### 阅读Legdao版本
> 3.21.030812

### 问题描述（简要描述发生的问题）
> 阅读3支持导出.txt文件，文件名格式为：`书名 by 作者.txt`
然而在其他设备上导入这种文件名格式的.txt小说为本地小说后，长按进入书籍页，点选封面无法进行封面换源。
封面图片下方的作者一栏的作者姓名也显示为空。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 由设备A的阅读3的离线缓存导出小说，并快传至设备B的同版本阅读3进行添加本地，然后长按进入书籍页，查看作者信息，尝试封面换源。
封面换源还有另外一个小问题：在10寸平板**横屏**显示模式下，封面换源的待选列表里的预览图片只能显示部分内容，选择完成后的图片则显示正常。

**Comment by 1274003856** [comment]
这是必然的啊。主要是不同的软件不同的导入数据啊
阅读生成的这个本来就是用来一般导入的
你需要的是高级版本啊
需要生成
书名 作者 书籍封面  书源名 书源链接的
有的书源网站的封面就是特例独行的

**Comment by nobk** [comment]
两个建议的修正方式：
1. 增加此种文件名格式的分析代码，提取书名及作者
```
diff --git a/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt b/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt
index 19e293b2b..2d9fd64c3 100644
--- a/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt
+++ b/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt
@@ -72,6 +72,16 @@ object LocalBook {
         if (smhStart != -1 && smhEnd != -1) {
             name = (name.substring(smhStart + 1, smhEnd))
         }
+        if (author == "" && name.contains(" by ")) {
+            var rstr = name.reversed()
+            // find last ' by ' near '.txt' using reversed string
+            var pattern = """^txt\.(.*) yb (.*)$""".toRegex()
+            var matches = pattern.findAll(input = rstr)
+            matches.forEach { matchResult ->
+                name = matchResult.groupValues[2].reversed()
+                author = matchResult.groupValues[1].reversed()
+            }
+        }
         val book = Book(
             bookUrl = path,
             name = name,
```

2. 导出.txt时按常用的中文书名格式导出
```
diff --git a/app/src/main/java/io/legado/app/ui/book/cache/CacheViewModel.kt b/app/src/main/java/io/legado/app/ui/book/cache/CacheViewModel.kt
index ef0cc2aea..3c374d864 100644
--- a/app/src/main/java/io/legado/app/ui/book/cache/CacheViewModel.kt
+++ b/app/src/main/java/io/legado/app/ui/book/cache/CacheViewModel.kt
@@ -49,7 +49,7 @@ class CacheViewModel(application: Application) : BaseViewModel(application) {
 
     @Suppress("BlockingMethodInNonBlockingContext")
     private suspend fun export(doc: DocumentFile, book: Book) {
-        val filename = "${book.name} by ${book.author}.txt"
+        val filename = "《${book.name}》作者：${book.author}.txt"
         DocumentUtils.delete(doc, filename)
         DocumentUtils.createFileIfNotExist(doc, filename)?.let { bookDoc ->
             val stringBuilder = StringBuilder()
```

**Comment by nobk** [comment]
刚发现新增了.epub电子书格式，修改了一下，支持.txt和.epub两种后缀，我只在kotlin命令行模式下搭了个脚手架编译执行了这部分代码，保证书名及作者提取正常，没有编译整个app。

```
diff --git a/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt b/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt
index 19e293b2b..8fd4f0dbd 100644
--- a/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt
+++ b/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt
@@ -72,6 +72,16 @@ object LocalBook {
         if (smhStart != -1 && smhEnd != -1) {
             name = (name.substring(smhStart + 1, smhEnd))
         }
+        if (author == "" && name.contains(" by ")) {
+            var rstr = name.reversed()
+            // find last ' by ' near '.txt' or '.epub' using reversed string
+            var pattern = """^(txt|bupe)\.(.*) yb (.*)$""".toRegex()
+            var matches = pattern.findAll(input = rstr)
+            matches.forEach { matchResult ->
+                name = matchResult.groupValues[3].reversed()
+                author = matchResult.groupValues[2].reversed()
+            }
+        }
         val book = Book(
             bookUrl = path,
             name = name,
```

**Comment by ag2s20150909** [comment]
> 刚发现新增了.epub电子书格式，修改了一下，支持.txt和.epub两种后缀，我只在kotlin命令行模式下搭了个脚手架编译执行了这部分代码，保证书名及作者提取正常，没有编译整个app。
> 
> ```kotlin
> diff --git a/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt b/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt
> index 19e293b2b..8fd4f0dbd 100644
> --- a/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt
> +++ b/app/src/main/java/io/legado/app/model/localBook/LocalBook.kt
> @@ -72,6 +72,16 @@ object LocalBook {
>          if (smhStart != -1 && smhEnd != -1) {
>              name = (name.substring(smhStart + 1, smhEnd))
>          }
> +        if (author == "" && name.contains(" by ")) {
> +            var rstr = name.reversed()
> +            // find last ' by ' near '.txt' or '.epub' using reversed string
> +            var pattern = """^(txt|bupe)\.(.*) yb (.*)$""".toRegex()
> +            var matches = pattern.findAll(input = rstr)
> +            matches.forEach { matchResult ->
> +                name = matchResult.groupValues[3].reversed()
> +                author = matchResult.groupValues[2].reversed()
> +            }
> +        }
>          val book = Book(
>              bookUrl = path,
>              name = name,
> ```

epub文件的话，可以直接从文件读取书名，作者名，和封面(如果有的话)，目前导入epub时是直接使用文件名的，是为了防止导入多个同名同作者不同版本的epub时冲突。

**Comment by nobk** [comment]
刚装了Android Studio，编译调试了一下，发现一点小问题，修改后测试通过，已经重新推送PR。

**Comment by nobk** [comment]
> epub文件的话，可以直接从文件读取书名，作者名，和封面(如果有的话)，目前导入epub时是直接使用文件名的，是为了防止导入多个同名同作者不同版本的epub时冲突。

从本地导入书名和作者完全相同的两本书，在第一本已经导入的情况下，第二本会被忽略不再导入。用文件名来确定书名、作者而不是元数据，有个好处是方便用户修改，例如希望一定要导入第二本，将文件名的书名部分或者作者部分加个1或者做别的修改，就可以成功了。
