### ISSUE TITLE
希望订阅源编辑功能能新增 视频展示页的 展示页链接规则(或者让描述规则支持它)~学习制作订阅源的菜鸟

### ISSUE THREAD

**Issue by 1274003856** [gedoor/legado#927]
希望订阅源编辑功能能新增
视频展示页的 展示页链接规则
有的视频网站视频页有 视频展示页
比如  http://www.hbqdq.com/yezi/329.html
叶子订阅源 http://yck.mumuceo.com/yuedu/rssyuan/json/id/597.json
这就是视频展示页，只需要取它的 点击播放链接
class.btn btn_primary@href
这个代码放到内容规则很不友好，获取不到域名
class.btn btn_primary@html
写成这样在内容规则需要点击才会跳转
希望在链接规则的下方新增一个
展示页链接规则
这样就好了
当然啦，如果能让描述规则能直接解析
class.btn btn_primary@href  也很ok
因为描述规则一般情况下也用不到啊，让他支持这样的功能，会大佬你来说很简单的
我是新手小白，在学习制作订阅源，希望大佬能看看啦，帮帮小弟。
视频展示页截图
![Screenshot_2021-04-04-06-33-08-13](https://user-images.githubusercontent.com/40195821/113494940-df6e3a80-951f-11eb-81fb-a7dababe96b0.jpg)

订阅源编辑想让你新增截图
![Screenshot_2021-04-04-06-33-08-13](https://user-images.githubusercontent.com/40195821/113494953-062c7100-9520-11eb-82ac-da5d613ef92a.jpg)

**Comment by zmn001125** [comment]
你在内容规则填
立即播放的链接
然后java.ajax(链接)就行

**Comment by zmn001125** [comment]
> 你在内容规则填
> 立即播放的链接
> 然后java.ajax(链接)就行

http://yck.mumuceo.com/d/EyVmz参考
我觉得这种小问题，你在酷安问，应该会收到一堆解决方法

**Comment by 1274003856** [comment]
> 希望订阅源编辑功能能新增
> 视频展示页的 展示页链接规则
> 有的视频网站视频页有 视频展示页
> 比如 http://www.hbqdq.com/yezi/329.html
> 叶子订阅源 http://yck.mumuceo.com/yuedu/rssyuan/json/id/597.json
> 这就是视频展示页，只需要取它的 点击播放链接
> class.btn btn_primary@href
> 这个代码放到内容规则很不友好，获取不到域名
> class.btn btn_primary@html
> 写成这样在内容规则需要点击才会跳转
> 希望在链接规则的下方新增一个
> 展示页链接规则
> 这样就好了
> 当然啦，如果能让描述规则能直接解析
> class.btn btn_primary@href 也很ok
> 因为描述规则一般情况下也用不到啊，让他支持这样的功能，会大佬你来说很简单的
> 我是新手小白，在学习制作订阅源，希望大佬能看看啦，帮帮小弟。
> 视频展示页截图
> ![Screenshot_2021-04-04-06-33-08-13](https://user-images.githubusercontent.com/40195821/113494940-df6e3a80-951f-11eb-81fb-a7dababe96b0.jpg)
> 
> 订阅源编辑想让你新增截图
> ![Screenshot_2021-04-04-06-33-08-13](https://user-images.githubusercontent.com/40195821/113494953-062c7100-9520-11eb-82ac-da5d613ef92a.jpg)
