### ISSUE TITLE
希望新增订阅源源调试添加源码查看

### ISSUE THREAD

**Issue by 1274003856** [gedoor/legado#929]
这样我就可以扔掉浏览器啦，我和手机自带浏览器鬼强制自动升级，太烦人。

**Comment by gedoor** [comment]
好的

**Comment by 1274003856** [comment]
我觉得这是刚需啦，毕竟提取网页div还需要其他浏览器很麻烦，直接使用阅读查看源码提取简单方便啊。

**Comment by 1274003856** [comment]
> 这样我就可以扔掉浏览器啦，我和手机自带浏览器鬼强制自动升级，太烦人。
