### ISSUE TITLE
[BUG] 手机深色模式下字体颜色无法选择黑色

### ISSUE THREAD

**Issue by KoedaNagi** [gedoor/legado#932]
### 机型（如Redmi K30 Pro）
>小米9

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by 1274003856** [comment]
必然的啊，手机深色模式，文字你选黑色，是看不见的啦
推荐手机深色模式，直接使用软件自带的，夜间模式
