### ISSUE TITLE
18PlusList.txt能够改成请求远程地址，且增加特定关闭/开启功能

### ISSUE THREAD

**Issue by ju0632** [gedoor/legado#936]
### 功能描述（请清晰的、详细的描述你想要的功能）
> -阅读内置了18PlusList.txt文件屏蔽了不可描述的网址，然而有时有特定使用场景

### 期望实现方式（阅读应该如何实现该功能）
> -增加特定开关按钮
-18PlusList.txt文件改成请求远程地址

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 1274003856** [comment]
它好像就屏蔽了丝瓜啊，但是丝瓜早更换网址了
至于屏蔽了的其他网址，有的网址真心国内禁止打开的，还不是害怕有的人吧有的网址做成书源/订阅源啊。
如果你对这个不满意，可以试试 阅读测试版哈

**Comment by nobk** [comment]
GooglePlay市场版没有18PlusList.txt名单限制，一份才两刀，如果有这方面需要建议买一份，支持一下作者。
