### ISSUE TITLE
[Feature Request] epub插图问题。

### ISSUE THREAD

**Issue by YumikoAzu** [gedoor/legado#937]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
图片样式为TEXT，epub插图大小不对劲。
![B4EBEFE9-F579-46C8-A314-CC20933DE913](https://user-images.githubusercontent.com/13196251/113654061-9ce86180-96c9-11eb-9279-8cc708da2b7c.jpeg)

### 期望实现方式（阅读应该如何实现该功能）
> 
![7FD76D22-8B6B-4838-B517-D0D9B93A4EEF](https://user-images.githubusercontent.com/13196251/113654154-d1f4b400-96c9-11eb-9074-1dca06829fb0.jpeg)

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 1274003856** [comment]
图片规则填写
full
即可
公众号有教程的

**Comment by YumikoAzu** [comment]
> 图片规则填写
> full
> 即可
> 公众号有教程的



> 图片规则填写
> full
> 即可
> 公众号有教程的

epub啊。。。填啥图片规则。。。。

**Comment by ag2s20150909** [comment]
> > 图片规则填写
> > full
> > 即可
> > 公众号有教程的
> 
> > 图片规则填写
> > full
> > 即可
> > 公众号有教程的
> 
> epub啊。。。填啥图片规则。。。。

如果是导出的epub的话，之前的版本没对img标签处理。如果是导入本地的epub话，目前应该是移除了img标签的。

**Comment by YumikoAzu** [comment]
> > > 图片规则填写
> > > full
> > > 即可
> > > 公众号有教程的
> > 
> > 
> > > 图片规则填写
> > > full
> > > 即可
> > > 公众号有教程的
> > 
> > 
> > epub啊。。。填啥图片规则。。。。
> 
> 如果是导出的epub的话，之前的版本没对img标签处理。如果是导入本地的epub话，目前应该是移除了img标签的。

我没选替换净化。
