### ISSUE TITLE
希望书架上的书可以长按~置顶~有的书更新很慢，但是喜欢看啊

### ISSUE THREAD

**Issue by 1274003856** [gedoor/legado#938]
订阅源，书源等都可以长按~置顶
希望书架上的书也可以长按~置顶
有的书更新很慢，但是喜欢看啊
因为采用的进入阅读自动刷新书架
有的书不能~置顶
就会被很多书给压下去了，
很难找到啊。

**Comment by nobk** [comment]
分组管理，新建分组“长期”。
然后对更新慢的设置分组，都勾选上“长期”分组，就可以立刻找到了

**Comment by 1274003856** [comment]
> 订阅源，书源等都可以长按~置顶 希望书架上的书也可以长按~置顶
> 有的书更新很慢，但是喜欢看啊
> 因为采用的进入阅读自动刷新书架
> 有的书不能~置顶
> 就会被很多书给压下去了，
> 很难找到啊。
