### ISSUE TITLE
建议增加WEBDAV备份文件标识

### ISSUE THREAD

**Issue by ju0632** [gedoor/legado#939]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 如题假如我有多个设备，阅读了不同的内容时，使用了webdav备份那么会互相替换造成数据紊乱

### 期望实现方式（阅读应该如何实现该功能）
> 添加可自定义的备份文件标识，则备份后的文件名为backup-2021-04-06-自定义标识1.zip，backup-2021-04-06-自定义标识2.zip则不会互相替换，恢复时也能区分不同的备份文件和设备
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by Celeter** [comment]
自己改备份文件夹就行了

**Comment by ju0632** [comment]
> 自己改备份文件夹就行了

阅读的webdav设置哪来的改备份文件夹

**Comment by Celeter** [comment]
> > 自己改备份文件夹就行了
> 
> 阅读的webdav设置哪来的改备份文件夹

url里加上文件夹名字就行了
