### ISSUE TITLE
[Feature Request] 点搜索直接弹出输入面板

### ISSUE THREAD

**Issue by ourpzh** [gedoor/legado#941]
点搜索按钮出来搜索界面，然而搜索框没有获取焦点，还得再点一下搜索框才能输入搜索内容，相当不便

**Comment by 1274003856** [comment]
你是第一次搜索啦，次数多了，会自动获取你搜索过的书的，在搜索的下面，之所以这样，方便直接点击搜索过的书名再次搜索啦，
这在很多阅读软件都是这样的那，

**Comment by nobk** [comment]
@ourpzh 已经解决的issue就主动关掉吧，否则一不小心还会点进来。
