### ISSUE TITLE
换源时自动搜索大量重复[BUG] 

### ISSUE THREAD

**Issue by waloyn** [gedoor/legado#943]
### 机型（如Redmi K30 Pro）
>vivo x27

### 安卓版本（如Android 7.1.1）
>安卓9.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.040323

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>换源时搜索结果大量重复，升级之前没有问题

### 日志提交（问题截图或者日志）
>

![Screenshot_20210408_122334](https://user-images.githubusercontent.com/20416585/113968947-a8bd5a80-9866-11eb-9c48-45c78fcdbea7.jpg)

**Comment by zmn001125** [comment]
详情页链接不一样，就会这样，你自己去源网站搜一下，看看是不是也是这么多结果

**Comment by zmn001125** [comment]
> 详情页链接不一样，就会这样，你自己去源网站搜一下，看看是不是也是这么多结果

试了两个笔趣阁的，都是多个搜索结果
![IMG_20210408_124041](https://user-images.githubusercontent.com/52020688/113969592-d525a680-9867-11eb-970a-f1dc116ea013.jpg)

**Comment by ag2s20150909** [comment]
是源网站的问题

**Comment by waloyn** [comment]
几天了，GITHUB时好时坏，我知道源网站能搜出来很多，但正常截图里的第二个，是完全匹配书名和作者的，现在是模糊匹配了。

**Comment by gedoor** [comment]
作者改成模糊匹配了
