### ISSUE TITLE
[BUG] 群晖webDav备份失败

### ISSUE THREAD

**Issue by charmingYouYou** [gedoor/legado#944]
### 机型（如Redmi K30 Pro）
> 小米10Pro

### 安卓版本（如Android 7.1.1）
> 安卓10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.21.040323

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 联通, wifi

### 问题描述（简要描述发生的问题）
> 使用群晖webDav进行备份, 提示备份成功, 但备份文件夹下并没有保存任何东西

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 4月月初就备份失效, 同样情况使用Tampermonkey和PT-Plugin-Plus进行webDav都是可以的

### 日志提交（问题截图或者日志）
>
![image](https://user-images.githubusercontent.com/31199453/113983894-0f4d7300-987d-11eb-8fa1-a680fd722789.png)
![image](https://user-images.githubusercontent.com/31199453/113983919-18d6db00-987d-11eb-8912-ed9f4cae2285.png)

**Comment by nobk** [comment]
我这里正常。建议删除bookProgress.json之后再试试，另外还可以读一下webdav的日志。

**Comment by charmingYouYou** [comment]
> 我这里正常。建议删除bookProgress.json之后再试试，另外还可以读一下webdav的日志。

好的, 麻烦问下webdav日志目录在哪啊?

**Comment by nobk** [comment]
> 好的, 麻烦问下webdav日志目录在哪啊?

应该就是web server的日志吧，我没群晖设备，你自己找找看吧。

**Comment by charmingYouYou** [comment]
> > 好的, 麻烦问下webdav日志目录在哪啊?
> 
> 应该就是web server的日志吧，我没群晖设备，你自己找找看吧。

刚刚按照操作移除bookProgress.json后进行备份, 同样不可以, 群晖webDav日志并没有接收到app的备份消息
![image](https://user-images.githubusercontent.com/31199453/114130329-e4bdf180-9932-11eb-82b2-6fffc6f5e0ff.png)

**Comment by nobk** [comment]
可以试下短按“备份与恢复”->“恢复”，如果能出现webdav的选择恢复文件列表，说明访问webdav的读没问题，如果选择恢复文件的列表出不来，再查其他原因吧。
我是在WSL下自己用Apache搭的WebDav，备份和恢复都没问题，查apache日志也正常。

**Comment by charmingYouYou** [comment]
> 可以试下短按“备份与恢复”->“恢复”，如果能出现webdav的选择恢复文件列表，说明访问webdav的读没问题，如果选择恢复文件的列表出不来，再查其他原因吧。
> 我是在WSL下自己用Apache搭的WebDav，备份和恢复都没问题，查apache日志也正常。

想问下你用的是那个阅读版本啊?我去用你的版本试试

**Comment by nobk** [comment]
> 想问下你用的是那个阅读版本啊?我去用你的版本试试

最近的版本
https://github.com/gedoor/legado/releases

**Comment by charmingYouYou** [comment]
找到问题了, 我备份目录中是有中文路径的, 之前旧版本App中带中文无法备份, 我就`encode`转码了下, 现在改回中文路径就好了
