### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lu158** [gedoor/legado#947]
### 机型（如Redmi K30 Pro）
>
荣耀v10

### 安卓版本（如Android 7.1.1）
>
安卓10.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.21.040820
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

电信
### 问题描述（简要描述发生的问题）
>
1.本地txt文件，删除时勾选源文件，不能删除本地txt文件。
2.源订阅里切换布局不能直接切换显示，要退出源，再点，才能显示需要的布局。（就最近两个版本才这样的）
### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by 1274003856** [comment]
关于①，可能是你的手机自动升级版本了，阅读和权限获取失败，就会这样了，建议回退手机版本
关于②，强烈支持修复，虽然切换布局退出再进也可以，但是麻烦

**Comment by gedoor** [comment]
解决了
