### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by gqd000** [gedoor/legado#953]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望有批注功能 

### 期望实现方式（阅读应该如何实现该功能）
> 入选图片展示

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 
![image](https://user-images.githubusercontent.com/57956533/115176436-acbb6900-a0ff-11eb-9a51-d93b82926dcb.png)
![image](https://user-images.githubusercontent.com/57956533/115176469-be9d0c00-a0ff-11eb-934b-3dd9e2fa2b58.png)
![image](https://user-images.githubusercontent.com/57956533/115176474-c197fc80-a0ff-11eb-811a-46401255603c.png)

**Comment by 1274003856** [comment]
你截图的这里，长按文本内容
书签
就可以做到你说的批注功能了的。

**Comment by gqd000** [comment]
> 你截图的这里，长按文本内容
> 书签
> 就可以做到你说的批注功能了的。

好的
