### ISSUE TITLE
[Feature Request] 关于阅读小说正文界面图片模式的一些建议

### ISSUE THREAD

**Issue by YumikoAzu** [gedoor/legado#955]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
现在的图片模式有三个：默认，full，text。

希望改进一下分成text(纯文本)，singleimage(单个图片一页，例如动漫之家的轻小说里面的插图章节全是图片，每个图片一个分页)，混合模式(图文混排，例如哔哩轻小说书源和epub)，漫画模式(滚动翻页下浏览。)
### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 1274003856** [comment]
你说的这些用处基本上没有的啊啊啊，一看你就不是专门写源的啊啊啊。建议多看看漫画源啊啊啊，
full 只是让图片自适应手机屏幕宽度用的
正文规则的代码可以做到 图文混合 一页一张无限自动识别加载等的。

**Comment by JinkerLeong** [comment]
@1274003856 有用啊，我看飞卢小说很多都是图片显示，一章一个图片，图片的height特别长那种。如果有漫画模式(向下滑动)就能正常看了，现在看不了。

**Comment by 52fisher** [comment]
> @1274003856 有用啊，我看飞卢小说很多都是图片显示，一章一个图片，图片的height特别长那种。如果有漫画模式(向下滑动)就能正常看了，现在看不了。

书籍页面右上角 **翻页动画** 选择 **滚动** 即可
