### ISSUE TITLE
[BUG] EPUB格式目录读取不正确

### ISSUE THREAD

**Issue by borpubi** [gedoor/legado#960]
### 机型（如Redmi K30 Pro）
>IQOO 3

### 安卓版本（如Android 7.1.1）
>Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.041610

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>打开<凤凰项目一个IT运维的传奇故事>后，读取的目录不正确，例如目录口的第11章，实际点目录跳转过去是第3章。
此书在电脑上阅读是正常的，手机上目前只有 阅读能打开，不能测试其他软件是否正常。

### 使用书源（填写URL或者JSON）
>书是网上下载的，百度云盘如下：
链接: https://pan.baidu.com/s/1JTH3wxclKNnnJOKIBNOZ_Q 提取码: 9vp8

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
下载此书，使用阅读APP打开即可。

### 日志提交（问题截图或者日志）
>
![image](https://user-images.githubusercontent.com/28093885/116026041-6ed0be80-a684-11eb-8aa3-45bf2d8cf2e1.png)

**Comment by ag2s20150909** [comment]
是epub的文件本身有问题。下图是[Sigil](https://github.com/Sigil-Ebook/Sigil)打开的。

![](https://i.bmp.ovh/imgs/2021/04/870604eeb77ea64e.png)

**Comment by ag2s20150909** [comment]
epub的ncx目录居然有href与fragmentId两者都相同的值，这是制作者的问题。
![](https://i.bmp.ovh/imgs/2021/04/1c181430b9965871.png)

**Comment by ag2s20150909** [comment]
建议使用Sigil编辑一下epub,重新生成目录。
![](https://i.bmp.ovh/imgs/2021/04/5501009d7a2f0487.png)

**Comment by borpubi** [comment]
感谢回复！目前修复完目录后就可以了。但这带一个问题：如果没有电脑修复的时候，就没办法看了。具体到这本书，如果您查看到最后就会发现，实际能看的只有十几章……还是有些微不方便的。有没有可能直接读取正确的信息生成目录呢？或者直接在阅读口直接修复类似的错误？

> 
> 
> 建议使用[Sigil](https://github.com/Sigil-Ebook/Sigil)编辑一下epub,重新生成目录。
> ![](https://camo.githubusercontent.com/9b35df5fd039c795c60011b61bd7e7c9493051f934ddfb44c15867f06ae2dee3/68747470733a2f2f692e626d702e6f76682f696d67732f323032312f30342f353530313030396437613266303438372e706e67)
