### ISSUE TITLE
怎么设置才能达到多看阅读的看书效果？

### ISSUE THREAD

**Issue by teraStars** [gedoor/legado#961]
我将字体，字距，行距，段距，背景等等设置了半天，但怎么都达不到多看阅读App的效果。要怎么设置才能达到，有高手解惑吗？
### **多看阅读的读书界面：**
![Screenshot_2021-04-26-12-26-15-794_com duokan rea](https://user-images.githubusercontent.com/7426499/116028939-ce31cd00-a68a-11eb-9436-6e99a8821a57.png)
![Screenshot_2021-04-26-12-21-13-807_com duokan rea](https://user-images.githubusercontent.com/7426499/116028948-d2f68100-a68a-11eb-91ab-7374da2f6437.png)

### **legado的读书界面：**
![Screenshot_2021-04-26-12-21-32-933_io legado app](https://user-images.githubusercontent.com/7426499/116028951-d5f17180-a68a-11eb-9916-a231ff3b2e0e.png)

**Comment by 52fisher** [comment]
关于主题排版等方面的问题，可以去coolapk评论区，感谢支持
