### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [gedoor/legado#962]
is there a way to translate this app without having to create a pull request?

**Comment by gedoor** [comment]
What language do you want to translate

**Comment by mondlicht-und-sterne** [comment]
english does not look finished. so english and german, if that could somehow work.

**Comment by dianso** [comment]
能增加日本语吗

**Comment by gedoor** [comment]
https://github.com/gedoor/legado/blob/master/app/src/main/res/values/strings.xml
You can translate this document and mail it to me after translation

**Comment by 52fisher** [comment]
> english does not look finished. so english and german, if that could somehow work.
> so i can't make it from chinese to english. so english would have to be ready by then

The English translation of the latest version has been completed, and a small number of fields will be updated later

**Comment by gedoor** [comment]
> 能增加日本语吗

没有人会翻译啊
