### ISSUE TITLE
希望本地小说txt也做成与网络小说一样的缓存

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#963]
本地txt文件如果修改过无法生效，建议要么把txt与下载的小说一样转成本地缓存，目前本地小说也有个清除缓存的菜单，但是没有作用，把这个选项改成删除副本也可以，删除之后也会重新读取原本生成新文件，不然每次都要手动进入booktxt删除副本文件才能刷新修改过的txt

**Comment by ag2s20150909** [comment]
> 本地txt文件如果修改过无法生效，建议要么把txt与下载的小说一样转成本地缓存，目前本地小说也有个清除缓存的菜单，但是没有作用，把这个选项改成删除副本也可以，删除之后也会重新读取原本生成新文件，不然每次都要手动进入booktxt删除副本文件才能刷新修改过的txt

在阅读界面 右上角进入菜单 更新目录。

**Comment by zousizhe** [comment]
> > 本地txt文件如果修改过无法生效，建议要么把txt与下载的小说一样转成本地缓存，目前本地小说也有个清除缓存的菜单，但是没有作用，把这个选项改成删除副本也可以，删除之后也会重新读取原本生成新文件，不然每次都要手动进入booktxt删除副本文件才能刷新修改过的txt
> 
> 在阅读界面 右上角进入菜单 更新目录。

你说的是编辑booktxt里面的副本文件吧，正常用户谁会深入到那个文件夹去操作，在安卓10上还得找特殊文件管理器才能进去，很不好搞

**Comment by zousizhe** [comment]
> > 本地txt文件如果修改过无法生效，建议要么把txt与下载的小说一样转成本地缓存，目前本地小说也有个清除缓存的菜单，但是没有作用，把这个选项改成删除副本也可以，删除之后也会重新读取原本生成新文件，不然每次都要手动进入booktxt删除副本文件才能刷新修改过的txt
> 
> 在阅读界面 右上角进入菜单 更新目录。

别人可以，但是我的不行，放在内置储存与内存卡根目录上，修改了txt选更新目录没法刷新，另外别人随便建立个文本用来测试，我这就直接报代码错误，强制要获取目录，失败就报错不可读取了

**Comment by 1274003856** [comment]
手机问题 换手机
你这是手机给阅读的权限不够啊

**Comment by zousizhe** [comment]
> 手机问题 换手机
> 你这是手机给阅读的权限不够啊

我不是安卓10都已经承受了安卓10以上的限制了，还给我来这么一出，EMUI的权限管理已经没什么可以授权了

**Comment by zousizhe** [comment]
> > 本地txt文件如果修改过无法生效，建议要么把txt与下载的小说一样转成本地缓存，目前本地小说也有个清除缓存的菜单，但是没有作用，把这个选项改成删除副本也可以，删除之后也会重新读取原本生成新文件，不然每次都要手动进入booktxt删除副本文件才能刷新修改过的txt
> 
> 在阅读界面 右上角进入菜单 更新目录。

没有用，我用手机与虚拟机都试过，都不能刷新

**Comment by 52fisher** [comment]
你可以在书架中长按 封面 移除该书籍，再重新添加即可。不需要去私有化目录删除相应文件
