### ISSUE TITLE
本地小说章节分段太严格，强制分段太能看

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#964]
不分章节就看不了，章节获取不全还会内容缺失，没法关掉目录正则，强制要分段，不然就报错，另外，滚动翻页模式不太平滑

**Comment by 52fisher** [comment]
> 章节获取不全

阅读自带的规则适用于常见的txt目录格式，其他小众的标题格式请自己添加相应规则获取。

> 强制要分段

分段不会影响正文内容，不想要目录可以不看目录
