### ISSUE TITLE
[Feature Request] 请求添加 fastlane 式元数据文件夹

### ISSUE THREAD

**Issue by pessoalzy** [gedoor/legado#965]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 请求在库中添加 fastlane 式元数据文件夹，以满足 [F-Droid](https://f-droid.org/) 收录应用的要求。
Please add app metadata in a Fastlane folder structure in the repository to meet the inclusion policy of [F-Droid](https://f-droid.org/).

### 期望实现方式（阅读应该如何实现该功能）
> F-Droid 提供的关于 Fastlane file structure 的描述可见于 https://gitlab.com/snippets/1895688
> F-Droid provide a [brief introduction of Fastlane file structure](https://gitlab.com/snippets/1895688).

> 参考上述链接中的描述，应在相应的文件夹内添加应用的简介、描述、图标、截图及更新日志等。效果演示中给出了一个简单的示例。
> According to the introduction provided by F-Droid, the short description, full description, icon, screenshots and etc. should be included in specific file or folder.  There is a simple demonstration below.

### 附加信息（其他的与功能相关的附加信息）
> 相关的 F-Droid 请求收录 issue 见于 [https://gitlab.com/fdroid/rfp/-/issues/1716](https://gitlab.com/fdroid/rfp/-/issues/1716)。其中对 Fastlane 做出要求的回复原文为 "There is no fastlane. Please add it via a PR or request it via an issue."
> The url of corresponding F-Droid submission issue is [https://gitlab.com/fdroid/rfp/-/issues/1716](https://gitlab.com/fdroid/rfp/-/issues/1716).

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> 一个简单的 Fastlane file structure 示例如下。其中标 ¹ 的为应有项， ² 、³ 为建议项。
> There is a simple demonstration of Fastlane file structure. Items marked with ¹ are the minimum requirements (i.e. must be there), ² means "strongly recommended". Consider all others optional, and ³ nice to have:
```
/                                           (repo-root)
└── fastlane
    └── metadata
        └── android
            ├── en-US                       (en-US seems to be required by F-Droid)
            │   ├── short_description.txt   (short description, max 80 chars) ¹
            │   ├── full_description.txt    (full app description) ¹
            │   ├── title.txt               (app name)
            │   ├── images
            │   │   ├── icon.png            (app icon; useful e.g. for "service apps" containing none)
            │   │   ├── phoneScreenshots    ²
            │   │   │   ├── 1.png
            │   │   │   ├── 2.png
            │   │   │   ...
            │   └── changelogs              ³
            │       ├── 100000.txt          (must correspond to versionCode, literally, no padding)
            │       ├── 100100.txt          (so this means: versionCode=100100)
            │       └── 100101.txt          (max size: 500 bytes)
            └── zh_Hans
                ...
                └── changelogs
                    └── 100100.txt
```

**Comment by gedoor** [comment]
收到
