### ISSUE TITLE
[Feature Request] 请求在 build.gradle 中添加其他 maven 库

### ISSUE THREAD

**Issue by pessoalzy** [gedoor/legado#966]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 请求在 `build.gradle` 中添加其他 maven 库，以满足 F-Droid 收录应用的要求。
> 对于此项要求我可能有所误解，回复原文为：“The https://maven.aliyun.com/nexus/content/groups/public/ , https://s3.amazonaws.com/fabric-artifacts/public and https://github.com/psiegman/mvn-repo/raw/master/releases is not allowed. Please ask upstream to provide a flavor without them.”

> Please add other maven repositories in the `build.gradle`  to meet the inclusion policy of F-Droid.
> I may misunderstood the requirement. The original reply in submission issue is “The https://maven.aliyun.com/nexus/content/groups/public/ , https://s3.amazonaws.com/fabric-artifacts/public and https://github.com/psiegman/mvn-repo/raw/master/releases is not allowed. Please ask upstream to provide a flavor without them.”

### 期望实现方式（阅读应该如何实现该功能）
> 我找到了一些关于允许的库的清单。
> 在 F-Droid  [Build Metadata Reference](https://f-droid.org/en/docs/Build_Metadata_Reference/) 页面的 ["srclibs" 一节](https://f-droid.org/en/docs/Build_Metadata_Reference/#build_srclibs) 中，有清单如下：
>>F-Droid allows the following known repositories until a source-built alternative is available:
>> -  ‘mavenCentral’ - the original repo, hardcoded in Maven and Gradle.
>> -  ‘jCenter’ - hardcoded in Gradle, this repo by Bintray tries to provide easier handling. It should sync with mavenCentral from time to time.
>> -  ‘OSS Sonatype’ - maintained by the people behind mavenCentral, this repository focuses on hosting services for open source project binaries.
>> -  ‘OSS JFrog’ - maintained by the people behind jCenter, this repository focuses on hosting services for open source project binaries.
>> -  ‘JitPack.io’ - builds directly from GitHub repositories. However, they do not provide any option to reproduce or verify the resulting binaries. Builds pre-release versions in some cases.
>> -  ‘Clojars’ - Clojure libraries repo.
>> -  ‘CommonsWare’ - repo holding a collection of open-source libs.
>
> 在 [`fdroidserver/scanner.py`](https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/scanner.py) 中有如下内容，似乎是更完整的白名单：
```
     allowed_repos = [re.compile(r'^https://' + re.escape(repo) + r'/*') for repo in [
        'repo1.maven.org/maven2',  # mavenCentral()
         'jcenter.bintray.com',     # jcenter()
         'jitpack.io',
         'www.jitpack.io',
         'repo.maven.apache.org/maven2',
         'oss.jfrog.org/artifactory/oss-snapshot-local',
         'oss.sonatype.org/content/repositories/snapshots',
         'oss.sonatype.org/content/repositories/releases',
         'oss.sonatype.org/content/groups/public',
         'clojars.org/repo',  # Clojure free software libs
         's3.amazonaws.com/repo.commonsware.com',  # CommonsWare
         'plugins.gradle.org/m2',  # Gradle plugin repo
         'maven.google.com',  # Google Maven Repo, https://developer.android.com/studio/build/dependencies.html#google-maven
         ]
```

### 附加信息（其他的与功能相关的附加信息）
> 相关的 F-Droid 请求收录 issue 见于 [https://gitlab.com/fdroid/rfp/-/issues/1716](https://gitlab.com/fdroid/rfp/-/issues/1716)。
The url of corresponding F-Droid submission issue is [https://gitlab.com/fdroid/rfp/-/issues/1716](https://gitlab.com/fdroid/rfp/-/issues/1716).

**Comment by dianso** [comment]
没必要，FDROID现在也流氓了，不听话就不让上架

**Comment by 52fisher** [comment]
暂无该计划，如有问题可重新开issues，感谢支持

**Comment by IzzySoft** [comment]
@ivysrono Yes? What is the question? Sorry, but I cannot easily follow here as I cannot even read Chinese :cry: If it's about F-Droid: I'm currently [not active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447). And Legado has been removed from my repo, see #1891
