### ISSUE TITLE
希望阅读>订阅>编辑>内容规则下面增加>内容规则下一页规则(部分订阅源需要这个功能啦)

### ISSUE THREAD

**Issue by 1274003856** [gedoor/legado#971]
就像多图网，每组图片都是
一页一张图，一组十多页/几十页

内容规则需要会写 js来全部获取拼接，但是对无数小白来说太难了(比如我)
提交到源仓库求大佬们修复~还被源仓库木木禁止我和账号登陆。

期望实现但是截图
<img src="http://yun.wap.zy40.cn/tu/IMG_20210504_192520.jpg">

多图网订阅源
http://yun.wap.zy40.cn/tu/exportRssSource.json

**Comment by 1274003856** [comment]
这样就可以像 列表下一页那样
自动获取所有页面并读取出来数据了
不然js提取的那种
第一是代码非常长，
第二是一般人压根不会写
第三是挂了修复太难了

**Comment by gedoor** [comment]
好的

**Comment by 1274003856** [comment]
感谢老大啦 你做好后，以后遇到这种网站，做成订阅源，就不用写如何多的内容规则 js 啦，最主要的，无数小白压根不会写这样的js代码啊，太难了，百度几天js了，还是没学会，每个网站js代码都不一样啊         关于用处，可以应用于  视频站>电视剧每部几十集 /图片站~每个图集几十页，一页一张图/小说站~有的短篇小说就2~3章        主要是这些做成书源太麻烦啦，而且用处也不大啊。

**Comment by gedoor** [comment]
收到,有空加啊
