### ISSUE TITLE
[Feature Request] 希望能加个多本小说一键导出功能

### ISSUE THREAD

**Issue by fymoe915** [gedoor/legado#972]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 添加一键导出功能，好多本长篇小说想导出时间太长，得一本本导，求能满足下

### 期望实现方式（阅读应该如何实现该功能）
> 希望能加个和一键缓存似的导出功能

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by 1274003856** [comment]
本来就是可以，一本一本导出的啊，默认就是这样的啊，一起导出也是可以的啊   我怀疑你是外星人，不会用地球上的产品啊，对一本书 导出，多选书导出，难道  源仓库 没玩过啊

**Comment by 1274003856** [comment]
关于不支持，多选小说，一起导出(只能一本一本导出的说明)                       第一，谁看的书会是短篇几张/几十张的书，这样的谁导出啊。                    一般导出的都是几百张/几千张的书，只能一本一本导出的，                     原因，第一，章节太多。第二，如果多本同时导出，会有一大堆导出失败的。                               第一，很多人用的安卓机都是几百元/千元的，能力不够  你以为是 苹果万元机啊

**Comment by 1274003856** [comment]
最主要还是为了适配安卓百元机/千元机，性能不够啊，如果是苹果万元机/windoes万元机，当然无所谓啦

**Comment by fymoe915** [comment]
可能我没说清楚点，我也知道可以同时导，但出错率高点，所以一般我都是导出这本成功后再导出另一本，所以要等一本成功再去点另一本。因此我想的是可不可以有个一键导出，它不是让多本书同时进行导出，而是按顺序一本成功导出后再执行另一本的那种，这样可以就不用守着它，一次搞定，导出也成功点0.0

**Comment by gedoor** [comment]
已添加
