### ISSUE TITLE
希望提供的众多API函数中，不要有重名的

### ISSUE THREAD

**Issue by kaich** [gedoor/legado#973]
例如：

`JsExtensions`类中有 `fun get(urlStr: String, headers: Map<String, String>): Connection.Response` 这样的函数。

`AnalyzeRule` 类中有 `fun get(key: String): String` 函数。

他们是继承关系，并且他们的名字都是`get`。在iOS中不能支持相同名字的方法，否则会造成调用混乱。

希望这种提供的API不要这样的重名情况。  

希望将`JsExtensions`中的`get`方法改为`getSoupResponse` 这样含义明确的方法名！

**Comment by gedoor** [comment]
他们的参数不一样,ios中不能有这样的吗

**Comment by gedoor** [comment]
那我改一下吧

**Comment by kaich** [comment]
@gedoor  参数不一样也不行，必须名字不一样。否则会有问题
