### ISSUE TITLE
群晖webdav备份[BUG] 

### ISSUE THREAD

**Issue by oreme2** [gedoor/legado#974]
### 机型（如Redmi K30 Pro）
>LGG7

### 安卓版本（如Android 7.1.1）
>安卓9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.050610
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>群晖无法webdav备份设置，显示method not allowed。直至4.14日此功能可用，如图
![73d7e61b9ecacddfbbfb01d36340e61](https://user-images.githubusercontent.com/38098761/117241525-ef05d980-ae65-11eb-9ed2-843324688fd9.jpg)
![edb7ced3d92c72db172dd76d7494716](https://user-images.githubusercontent.com/38098761/117241532-f5945100-ae65-11eb-9c1a-236f9c9448aa.jpg)

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
好的,我看看

**Comment by gedoor** [comment]
已解决
