### ISSUE TITLE
WebDAV[BUG] 

### ISSUE THREAD

**Issue by DDOS-SU** [gedoor/legado#976]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>安卓11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>legado_app_3.21.050610

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>在阿里云上搭建了Cloudreve云盘，使用其WebDAV功能时，显示冲突，只有在将云盘中备份的文件夹删掉，再点备份才会备份成功，而再次点备份时会提示冲突。而我用老版本阅读时，WebDAV功能正常。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by gedoor** [comment]
已解决
