### ISSUE TITLE
[BUG] 簡轉繁錯誤 "才"不需轉換成"纔"

### ISSUE THREAD

**Issue by bbbear9527** [gedoor/legado#980]
### 机型（如Redmi K30 Pro）
>samsung s20

### 安卓版本（如Android 7.1.1）
>android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.050816

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>簡轉繁錯誤 "才"不需轉換成"纔"，保持原來的"才"字才是正確的。纔字幾乎無人使用。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by Celeter** [comment]
反馈错地方了 https://github.com/liuyueyi/quick-chinese-transfer

**Comment by liuyueyi** [comment]
升级版本到 0.1.2 ，已修复
