### ISSUE TITLE
关于翻页动画“滚动”[BUG] 

### ISSUE THREAD

**Issue by 734445058** [gedoor/legado#982]
### 机型（如Redmi K30 Pro）
>
LG G7 thinq

### 安卓版本（如Android 7.1.1）
>
android 10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.21.050610

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信宽带 ，联通

### 问题描述（简要描述发生的问题）
>
使用翻页动画内的“滚动”选项的时候，一根手指是正常的滑动，但是如果是A手指按着屏幕，B手指滑动屏幕，页面就会跳到下一页或者上一页 ，松开B手指，会跳回原样，无论怎么滑，松开B手指的时候也是跳回A手指的原样。有时候手掌边缘会误触，弄的挺烦的。

希望大佬修复一下。再优化一点点点滚动的流畅程度就更好啦。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
可以录屏吗。那我放上去

### 日志提交（问题截图或者日志）
>

https://user-images.githubusercontent.com/50134959/118094465-593bf280-b401-11eb-8cbe-35f82e3b407a.mp4

**Comment by 734445058** [comment]
没有人咩

**Comment by gedoor** [comment]
好的,我看下

**Comment by 734445058** [comment]
Xiexie dalao

**Comment by 734445058** [comment]
> 好的,我看下

请问一下 这个问题能搞吗
