### ISSUE TITLE
希望链接一下iOS版的地址

### ISSUE THREAD

**Issue by kaich** [gedoor/legado#983]
iOS版的大致功能已经能用，有些功能还在完善，目前有[testflight版本](https://testflight.apple.com/join/2Svrtr9y)，等两个测试版已经功能方面就完善得差不多了。

这里是地址：`https://github.com/kaich/Yuedu`。

等功能方面完善后，会对备份数据做兼容，这样不同平台之间可以备份和恢复，做到平台互通！

希望README页面中链接一下地址！谢谢！

另外我想在iOS版内添加分享安卓版的功能，大佬给个你觉得比较比较好的链接！方便在使用iOS版的时候，用户通过这个链接可以分享地址给使用安卓的朋友。

**Comment by gedoor** [comment]
好的

**Comment by kaich** [comment]
谢谢，我已在iOS版分享功能，添加了安卓的的地址了！

**Comment by Goda0214** [comment]
来个名额
