### ISSUE TITLE
[Feature Request] 希望在目录列表显示卷名

### ISSUE THREAD

**Issue by tushonT** [gedoor/legado#986]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 有些网站在章节列表中会有额外一条显示分卷名称，希望作者能在目录中加一个分卷名显示（如果可以实现各网站通用）

### 期望实现方式（阅读应该如何实现该功能）
> 在书源编辑—目录里加入分卷名称规则(VolumeName)、分卷Url规则(VolumeUrl)两项，
 1. 当这两条内容为空时，正常显示目录列表
 2. 当两条都填写了内容，把目录列表以卷名位置为标识分块，把卷名新列为一章插入列表此位置后合并显示。
 3. 由于有些网站只有卷名text没有url，所以当只写VolumeName不写VolumeUrl时，依旧插入卷名到目录列表。

### 附加信息（其他的与功能相关的附加信息）
> 1. 如果能实现的话，当只写VolumeName不写VolumeUrl时，把两卷名位置之间的所有章名排列显示到卷名这一章的正文，作为二级目录。
 2.目录列表里的卷名加背景以突出显示
### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
> ![1620829403358.jpg](https://user-images.githubusercontent.com/43551657/118323791-c059c400-b533-11eb-99d4-dca5d62d79c5.jpg)
![Screenshot_2021-05-15-04-23-38-0323385459.png](https://user-images.githubusercontent.com/43551657/118325031-6f4acf80-b535-11eb-829a-701213e3da78.png)

**Comment by gedoor** [comment]
准备弄二级目录

**Comment by tushonT** [comment]
> 准备弄二级目录

谢谢作者的支持
