### ISSUE TITLE
预下载希望有个开关，既然可以设定下载多少章，那么应该有不下载或者下载0张的选项[Feature Request] 

### ISSUE THREAD

**Issue by yjvv1** [gedoor/legado#987]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 

### 期望实现方式（阅读应该如何实现该功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
设置1章就行

**Comment by 52fisher** [comment]
最新版已优化该功能，如有问题可重新开issues，感谢支持
