### ISSUE TITLE
[BUG] 字体颜色以及编码问题导致乱码

### ISSUE THREAD

**Issue by 2293310198** [gedoor/legado#988]
### 机型（如Redmi K30 Pro）
>小米8 透明探索版

### 安卓版本（如Android 7.1.1）
>安卓10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.051220

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>中国联通wifi及移动流量

### 问题描述（简要描述发生的问题）
>1.界面》文字颜色和背景》+》文字颜色选择黑#000000仍为白色，但是试了#ff0000正常显示为红色。
2.部分网站存在响应头content-type
	text/html; charset=gbk跟网页head头<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
里定义的文件编码不一样，如果以gbk编码显示为乱码，但浏览器以utf-8正常显示。
编写规则采集过来的也是乱码。

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by 10bits** [comment]
编码转换三部曲
* 如果有自定义编码使用自定义编码转换
*  通过正则`<meta .*(http-equiv="?Content-Type"?.*)?charset="?([a-zA-Z0-9_-]+)"?`获取html编码进行转换
*  使用charset detect获取编码进行转换

响应体里获取的编码可能不准确

**Comment by Celeter** [comment]
编码可以手动设置

**Comment by 2293310198** [comment]
> 编码可以手动设置

怎么设置啊？我看教程里也没有

**Comment by Celeter** [comment]
> > 编码可以手动设置
> 
> 怎么设置啊？我看教程里也没有

url,{'chatset':'gbk'}
