### ISSUE TITLE
webdav设置了，备份提示webdav no protocol https://dav.jianguoyun.com/dav/legado/

### ISSUE THREAD

**Issue by WangJie0822** [gedoor/legado#990]
webdav设置了，备份提示webdav no protocol https://dav.jianguoyun.com/dav/legado/

_Originally posted by @yaocanfeng in https://github.com/gedoor/legado/issues/89#issuecomment-647252459_

同样的 无法进行webdav备份

**Comment by 21307369** [comment]
升级最新版本的阅读  就可以了

**Comment by WangJie0822** [comment]
我用的就是最新的版本，但还是有这个问题

**Comment by gedoor** [comment]
坚果云我测试了没有问题啊

**Comment by WangJie0822** [comment]
但我的手机确实有这个问题，相关信息如下：
![image](https://user-images.githubusercontent.com/19624881/118424036-f3998000-b6f8-11eb-8741-749f7661617b.png)
![image](https://user-images.githubusercontent.com/19624881/118424054-fb592480-b6f8-11eb-8d30-97d3064b2d6b.png)
![image](https://user-images.githubusercontent.com/19624881/118424062-ff854200-b6f8-11eb-8e58-4f445be8e331.png)

**Comment by dianso** [comment]
要空格干嘛

**Comment by WangJie0822** [comment]
居然是https前面的一个空格导致的、、、、
但是现在又有了新的问题‘’
![image](https://user-images.githubusercontent.com/19624881/118488483-5b2dea80-b74e-11eb-823c-c199f5d5cdf5.png)

**Comment by WangJie0822** [comment]
神奇了，我换了一个设备就好了，手机清空数据之后重新配置也可以了
