### ISSUE TITLE
[BUG] 近两个版本部分界面重新出现主题配色问题

### ISSUE THREAD

**Issue by agutools** [gedoor/legado#991]
### 机型
> MIUI 12

### 安卓版本
>Android 10

### 阅读Legdao版本
>legado_app_3.21.051220 ~ legado_app_3.21.051618

### 问题描述（简要描述发生的问题）
> 近两个版本部分界面重新出现主题配色问题

### 主题配色
```json
{
  "accentColor": "#ff385538",
  "backgroundColor": "#ffc7c3a7",
  "bottomBackground": "#ff82ab81",
  "isNightTheme": false,
  "primaryColor": "#ff4b714a",
  "themeName": "柔和"
}
```

### 复现步骤
> 默认「日间模式」使用以上主题配色，更新这两个版本均有以下问题（截图）

### 问题截图
>
01：
![IMG_20210517_124215](https://user-images.githubusercontent.com/34952826/118434410-88d24f80-b6cc-11eb-92f9-7b0f116a99b7.jpg)
02：「反选」「删除」两按钮“不显示”：
![IMG_20210517_124147](https://user-images.githubusercontent.com/34952826/118434436-92f44e00-b6cc-11eb-90ae-fe6aabb81239.jpg)
03：
![IMG_20210517_124046](https://user-images.githubusercontent.com/34952826/118434535-c3d48300-b6cc-11eb-9c4d-6ee5ba62d3ce.jpg)
04：
![IMG_20210517_123948](https://user-images.githubusercontent.com/34952826/118434616-e070bb00-b6cc-11eb-9c29-843ac3b38b63.jpg)
05：
![IMG_20210517_123909](https://user-images.githubusercontent.com/34952826/118434744-1c0b8500-b6cd-11eb-812c-1d619effc515.jpg)
06：
![IMG_20210517_123753](https://user-images.githubusercontent.com/34952826/118434790-334a7280-b6cd-11eb-8f8b-9ab20df7d4de.jpg)

**Comment by agutools** [comment]
「朗读引擎」列表显示正常：
![IMG_20210517_130922](https://user-images.githubusercontent.com/34952826/118435277-35610100-b6ce-11eb-9a28-a91c663ca01f.jpg)

**Comment by gedoor** [comment]
好的,我看下

**Comment by gedoor** [comment]
下版本解决
