### ISSUE TITLE
web服务希望能在手机锁屏时使用

### ISSUE THREAD

**Issue by yangchenglin** [gedoor/legado#992]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
打开web服务时，如果手机在锁屏状态，浏览器则不能读取书架信息和阅读书箱
### 期望实现方式（阅读应该如何实现该功能）
> 
希望能在手机锁屏时可以正常使用浏览器进行阅读
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>

**Comment by gedoor** [comment]
可以的啊,锁定阅读后台应该就行

**Comment by liangweipeng** [comment]
web似乎不能更新最新的章节。要打开手机更新一次。（我是用老手机锁屏开web）

**Comment by yangchenglin** [comment]
> 可以的啊,锁定阅读后台应该就行

还真是，谢谢~~
