### ISSUE TITLE
[FeatureRequest] 书源正文规则中是否可添加支持链接标签，跳出阅读APP或调用webview打开链接

### ISSUE THREAD

**Issue by gavinjing1** [gedoor/legado#994]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 书源正文规则中是否可添加支持链接标签，跳出阅读APP或调用webview打开链接
应用场景: 比较喜欢阅读的下拉更新功能，能及时获取更新，我改造了一下海阔的一个视频源，可以实现下拉获取剩余未看剧集的视频链接，但是要复制到浏览器播放，希望能在正文规则中增加对打开链接的支持。

### 期望实现方式（阅读应该如何实现该功能）
> 支持链接标签，跳出阅读APP或调用webview打开链接

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以手绘一些草图，或者提供可借鉴的图片）
>
![Screenshot_2021-05-18-22-18-14-002_io legado app release](https://user-images.githubusercontent.com/7686867/118667910-f85c5200-b826-11eb-8141-70f146ccadfd.jpg)

**Comment by zmn001125** [comment]
你点章节链接就可以跳了呀

**Comment by 52fisher** [comment]
![image](https://user-images.githubusercontent.com/32198215/118707165-c9f16d80-b84c-11eb-8a05-5aed4766f8fd.png)
点击最上面的链接即可跳转，点击名称跳转源编辑界面

**Comment by gavinjing1** [comment]
> ![image](https://user-images.githubusercontent.com/32198215/118707165-c9f16d80-b84c-11eb-8a05-5aed4766f8fd.png)
> 点击最上面的链接即可跳转，点击名称跳转源编辑界面
想要跳转的不是详情页，而是详情页(广告太多)中的视频播放地址
![Screenshot_2021-05-19-06-21-39-677_io legado app release](https://user-images.githubusercontent.com/7686867/118730852-d5539180-b86a-11eb-92ed-55c124ebe9ca.jpg)

 如确无办法，跳转详情页基本可以满足，感谢回复
