### ISSUE TITLE
[BUG] 页面滑动过于灵敏，很容易造成左右滑动

### ISSUE THREAD

**Issue by szlk** [gedoor/legado#996]
页面滑动过于灵敏，很容易造成左右滑动，比如下拉刷新时极容易跑到其他页面。

**Comment by 1274003856** [comment]
这在使用订阅源上>简直了>下滑=左右滑动

**Comment by szlk** [comment]
> 这在使用订阅源上>简直了>下滑=左右滑动

订阅源？订阅源没有设置左右滑动的啊
