### ISSUE TITLE
希望>阅读记录>上的书可以直接点击跳到书阅读页(现在是不可点击啊)

### ISSUE THREAD

**Issue by 1274003856** [gedoor/legado#998]
主要是有时候，看了书，然后刷新书架>看的书更新不够快>就在底部去了，不好翻啊 我知道新建分组>可以吧刚才看的书>放在这个分组  但是麻烦啊      阅读>我和>阅读记录>里面不是可以显示书名>阅读了多少时间啊   点击书名 增加直接跳转到相应书籍阅读页  就完美了啊。

**Comment by 1274003856** [comment]
好的，反正代码就一小段，加上去即可

**Comment by gedoor** [comment]
ok
